import type { CodeRef } from "@/components/code/types";
import schedulerPy from "./codebase/vllm/v1/core/sched/scheduler.py?raw";
import outputPy from "./codebase/vllm/v1/core/sched/output.py?raw";
import parallelPy from "./codebase/vllm/v1/engine/parallel_sampling.py?raw";
import sequencePy from "./codebase/legacy-v0.6.6/vllm/sequence.py?raw";
export const codeRefs: Record<string, CodeRef> = {
"running-need": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [510, 523], "desc": "진행 목록을 순회하며 요청의 필요량을 계산하고 잔액으로 자릅니다.", "annotations": [{"lines": [511, 523], "color": "sky", "note": "A의 필요량 1과 잔액 8이면 배정 후보 1입니다. P의 필요량 6과 잔액 4이면 후보 4가 됩니다."}]}, code:schedulerPy, lang:"python"},
"running-allocation": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [616, 639], "desc": "저장 공간을 확보한 요청만 이번 배정에 넣고 토큰 잔액을 줄입니다.", "annotations": [{"lines": [616, 628], "color": "amber", "note": "공간을 얻지 못하면 성공 목록에 넣지 않습니다. 중단된 요청과 회수된 토큰도 별도로 처리합니다."}, {"lines": [629, 639], "color": "emerald", "note": "A와 B를 성공 배정하면 각각 1씩 줄어 잔액이 6입니다."}]}, code:schedulerPy, lang:"python"},
"waiting-need": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [874, 879], "desc": "대기 요청의 미계산 입력을 구하고 별도 조각 상한을 적용합니다.", "annotations": [{"lines": [874, 879], "color": "sky", "note": "입력 길이 10에서 이미 계산한 0을 빼면 10입니다. 상한이 4라면 먼저 4로 줄입니다."}, {"lines": [899, 914], "color": "emerald", "note": "Chunking이 허용된 경로에서 남은 token_budget으로 다시 자릅니다. 기본 사례는 min(10,6)=6입니다."}]}, code:schedulerPy, lang:"python"},
"waiting-clip": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [899, 914], "desc": "입력 조각 상한과 chunking 허용 조건을 거쳐 토큰 잔액으로 배정량을 자릅니다.", "annotations": [{"lines": [899, 914], "color": "sky", "note": "상한 0이면 별도 상한을 적용하지 않습니다. C의 입력 10과 잔액 6은 min(10,6)=6이 됩니다."}]}, code:schedulerPy, lang:"python"},
"waiting-failure": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [972, 995], "desc": "대기 요청의 저장 공간 배정에 실패하면 수용을 중단합니다.", "annotations": [{"lines": [972, 987], "color": "sky", "note": "여러 저장 조건을 함께 넘겨 할당합니다. 본문은 재사용·원격 전송 등이 없는 경로입니다."}, {"lines": [988, 999], "color": "amber", "note": "new_blocks가 없으면 break입니다. C의 수용 성공과 토큰 잔액 감소는 아직 일어나지 않았습니다."}]}, code:schedulerPy, lang:"python"},
"waiting-success": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [1055, 1075], "desc": "공간 배정 뒤 새 요청을 진행 목록에 넣고 이번 계산량을 기록합니다.", "annotations": [{"lines": [1055, 1075], "color": "emerald", "note": "C가 running에 들어가고 num_scheduled_tokens[C]=6이 됩니다. 잔액 감소와 상태 전환은 이 성공 경로 뒤에 옵니다."}]}, code:schedulerPy, lang:"python"},
"output-fields": {...{"path": "vllm/v1/core/sched/output.py", "highlight": [192, 208], "desc": "새 요청 정보와 갱신 정보, 요청별 배정량과 그 합을 전달하는 실제 구조체입니다.", "annotations": [{"lines": [202, 208], "color": "sky", "note": "A:1, B:1, C:6의 합계는 8입니다. 출력 토큰 8개라는 뜻은 아닙니다."}]}, code:outputPy, lang:"python"},
"progress-update": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [1317, 1341], "desc": "배정 반환 전에 진행 위치와 아직 실행 중인 양을 함께 전진시킵니다.", "annotations": [{"lines": [1317, 1326], "color": "amber", "note": "원문 주석은 즉시 다음 조각을 예약하기 위한 진행 갱신과 이후 거부 토큰의 교정을 설명합니다."}, {"lines": [1327, 1341], "color": "sky", "note": "C의 computed와 in-flight가 각각 6 늘어납니다. 이 시점의 computed를 GPU 완료 확인으로 쓰지 않습니다."}]}, code:schedulerPy, lang:"python"},
"parallel-children": {...{"path": "vllm/v1/engine/parallel_sampling.py", "highlight": [71, 94], "desc": "여러 응답 요구를 각각 하나의 응답을 만드는 자식 요청으로 나눕니다.", "annotations": [{"lines": [71, 81], "color": "sky", "note": "자식마다 n=1로 바꿉니다. 지정된 seed는 자식 인덱스를 더해 분리합니다."}, {"lines": [83, 94], "color": "emerald", "note": "부모 p의 n=3은 0_p, 1_p, 2_p 같은 자식 식별자를 만듭니다."}]}, code:parallelPy, lang:"python"},
"legacy-group": {...{"path": "legacy-v0.6.6/vllm/sequence.py", "highlight": [624, 647], "desc": "역사적 v0.6.6 고정 원문입니다. 같은 입력에서 나온 여러 생성 경로를 한 그룹에 담았습니다.", "annotations": [{"lines": [624, 647], "color": "sky", "note": "seqs 목록이 여러 Sequence를 담습니다. 현재 V1 자식 요청 코드와 같은 버전으로 혼동하지 않습니다."}]}, code:sequencePy, lang:"python"},
};
