import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { Sp1ReceiptViz } from "./Sp1ReceiptViz";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefsReal } from "./codeRefsReal";
import { sp1RealTree } from "./fileTreeReal";

const PROGRAM = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/core/executor/src/program.rs";
const RECORD = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/core/executor/src/record.rs";
const PROOF = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/sdk/src/proof.rs";
const PROVER = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/sdk/src/prover.rs";

export default function ModernSp1() {
  const sidebar = useCodeSidebar();
  return <>
  <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Fibonacci RV64IM program이 n=10의 결과 55를 공개하기</p><h2 className="text-3xl font-bold tracking-tight">실행 기록과 공개값을 같은 증명에 연결합니다</h2></header><p>Rust 프로그램을 RV64IM 실행 파일인 ELF로 만들고, 비공개 입력 n=10을 실행해 공개 결과 55를 쓰는 사례입니다. 이 글은 SP1 v6.4.0의 실행 파일·검증 키, 실행 기록·분할, 증명 형식을 연결합니다.</p><p><a className="text-primary hover:underline" href="/cs/crypto/stark-theory">STARK 정본</a>과 <a className="text-primary hover:underline" href="/cs/crypto/plonk">PLONK 정본</a>에서 각 증명 방식의 수학을 이어 볼 수 있습니다.</p><Sp1ReceiptViz /><ContentBoundary article="sp1" /></section>

    <section id="program-artifact" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Program 자료 묶음</p><h2 className="mt-2 text-2xl font-bold">실행 파일과 검증 키를 함께 고정합니다</h2></header><p>증명할 프로그램은 실행기가 읽은 ELF의 명령·메모리 이미지와 준비 단계에서 만든 생성·검증 키로 정합니다. 소스 파일이나 패키지 이름만 같다고 같은 실행 파일이 되는 것은 아닙니다.</p><p>재현을 위해 소스 버전, 컴파일러 대상과 설정, ELF·검증 키의 해시를 기록합니다. 비공개 입력과 공개 출력의 바이트 순서, SP1 버전도 함께 고정합니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="Program struct" onClick={() => sidebar.open("sp1-program", codeRefsReal["sp1-program"])} /></div><ExplainedFormula question="Program artifact identity에 왜 ELF와 VK가 모두 필요한가?" idea={<>실행 bytes와 verifier가 승인하는 key가 같은 setup에서 나왔음을 결속합니다.</>} formula={String.raw`A_P=H(d_{src}\|d_{tool}\|H(ELF)\|H(VK)\|d_{schema}\|v)`}
    annotatedFormula={String.raw`A_P=\underbrace{H(d_{src}\|d_{tool}\|H(ELF)\|H(VK)\|d_{schema}\|v)}_{\text{I/O schema 계산}}`}
    operations={[
      { expression: String.raw`H(d_{src}\|d_{tool}\|H(ELF)\|H(VK)\|d_{schema}\|v)`, annotation: ["I/O schema이(가) 식의 결과에 기여하는 방식을","계산합니다.","실행 bytes와 verifier가 승인하는 key가 같은","setup에서 나왔음을 결속합니다."] },
    ]} terms={[{symbol:"A_P",name:"Program artifact id",description:"배포 가능한 SP1 program/key bundle의 digest입니다."},{symbol:"d_{src}",name:"Source revision",description:"Program과 dependencies의 pinned revision입니다."},{symbol:"d_{tool}",name:"Toolchain identity",description:"Rust/LLVM target과 build profile digest입니다."},{symbol:"ELF",name:"RV64IM executable",description:"SP1 executor가 parse하고 실행하는 bytes입니다."},{symbol:"VK",name:"Verification key",description:"Setup이 이 program에 대해 만든 verifier key입니다."},{symbol:"d_{schema}",name:"I/O schema",description:"stdin와 public values encoding/order digest입니다."},{symbol:"v",name:"SP1 version",description:"Executor/prover/serialization version입니다."}]} assumptions={["모든 fields는 canonical length-delimited encoding입니다.","정확한 SP1 vkey hash/serialization은 pinned implementation을 따릅니다."]} interpretation="ELF가 같아도 다른 VK를 묶거나 public-values order가 바뀌면 새 artifact입니다." /><div id="paper-sp1-program"><CitationBlock type="code" citeKey={1} source="SP1 Program parser · v6.4.0 commit f66b4bf" href={PROGRAM}><p><strong>문제:</strong> ELF bytes를 zkVM이 실행할 deterministic RISC-V program image로 바꿔야 합니다.</p><p><strong>핵심 기여:</strong> 고정한 source는 RV64IM ELF parsing과 Program의 instruction/memory image construction 경계를 제공합니다.</p><p><strong>중요 가정:</strong> SP1 v6.4.0 executor와 지원 ELF/ISA profile을 사용합니다.</p><p><strong>근거 범위:</strong> 해당 release의 program loading implementation입니다.</p><p><strong>일반화 금지:</strong> 임의 ELF, native OS behavior, source-level equivalence나 program safety를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="execution-shards" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Execution record and shards</p><h2 className="mt-2 text-2xl font-bold">나눈 실행 조각의 시작과 끝이 이어져야 합니다</h2></header><p>ExecutionRecord에는 CPU·메모리·시스템 호출의 이벤트와 공개값이 들어 있습니다. 명령 개수 하나만 기록한 자료가 아니라 증명을 만들 때 쓸 실행 기록입니다.</p><p>기록을 여러 조각인 shard로 나누면 증거를 병렬로 만들 수 있습니다. 그래도 명령 위치와 시계, 메모리 초기화·종료 조건이 인접 조각 사이에서 이어져야 원래 한 실행입니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="ExecutionRecord · split()" onClick={() => sidebar.open("sp1-record", codeRefsReal["sp1-record"])} /></div><ExplainedFormula question="여러 shards가 같은 실행임을 어떤 불변식으로 확인할까?" idea={<>인접 shard의 종료 machine commitment와 다음 시작 commitment를 같게 합니다.</>} formula={String.raw`m_i^{out}=m_{i+1}^{in},\quad E=\sum_{i=0}^{k-1}|events_i|`}
    annotatedFormula={String.raw`m_i^{out}=\underbrace{m_{i+1}^{in},\quad E=\sum_{i=0}^{k-1}|events_i|}_{\text{Next input state 계산}}`}
    operations={[
      { expression: String.raw`m_{i+1}^{in},\quad E=\sum_{i=0}^{k-1}|events_i|`, annotation: ["Next input state이(가) 식의 결과에 기여하는","방식을 계산합니다.","인접 shard의 종료 machine commitment와","다음 시작 commitment를 같게 합니다."] },
    ]} terms={[{symbol:"m_i^{out}",name:"Shard output state",description:"i번째 shard의 PC, clock, memory/public state commitment입니다."},{symbol:"m_{i+1}^{in}",name:"Next input state",description:"다음 shard가 시작할 때의 같은 state commitment입니다."},{symbol:"k",name:"Shard count",description:"ExecutionRecord를 나눈 조각 수입니다."},{symbol:"events_i",name:"Shard events",description:"i번째 shard에 포함된 admitted execution events입니다."},{symbol:"E",name:"Total events",description:"전체 execution의 event 수입니다."}]} assumptions={["같은 ELF/program key와 execution semantics를 사용합니다.","실제 public-values layout과 boundary constraints는 pinned machine implementation을 따릅니다."]} interpretation="4개 shards 중 세 번째의 시작 PC가 두 번째 종료 PC와 다르면 shard proofs를 recursion으로 합쳐서는 안 됩니다." /><div id="paper-sp1-record"><CitationBlock type="code" citeKey={2} source="SP1 ExecutionRecord · v6.4.0 commit f66b4bf" href={RECORD}><p><strong>문제:</strong> RISC-V execution과 chips가 소비할 events/public values를 shardable witness로 표현해야 합니다.</p><p><strong>핵심 기여:</strong> 고정한 source는 ExecutionRecord fields, shard metadata, memory events와 public-values constraints를 정의합니다.</p><p><strong>중요 가정:</strong> v6.4.0 machine/chips와 같은 record schema를 사용합니다.</p><p><strong>근거 범위:</strong> SP1 executor record and sharding data model입니다.</p><p><strong>일반화 금지:</strong> 모든 shard size가 최적이거나 record만으로 proof soundness가 성립한다는 뜻은 아닙니다.</p></CitationBlock></div></section>

    <section id="proof-receipt" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Proof 검증 기록</p><h2 className="mt-2 text-2xl font-bold">증명을 압축해도 프로그램과 공개값의 연결을 확인합니다</h2></header><p>Core는 실행 조각별 증거이고 compressed는 이를 재귀적으로 묶은 증거입니다. PLONK·Groth16 형식은 외부 검증 환경을 위해 다른 증명으로 감싼 결과입니다. 형식에 따라 자료와 검증 방법이 달라집니다.</p><p>기록에는 증명 형식과 SP1 버전, 검증 키 해시, 공개값의 바이트와 인코딩을 남깁니다. 실행 장치와 검증 결과도 함께 기록합니다. 다른 증명으로 감싼 뒤에도 원래 프로그램 키와 공개값이 기대한 값인지 확인해야 합니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="SP1ProofWithPublicValues · verify_mock_public_inputs()" onClick={() => sidebar.open("sp1-proof", codeRefsReal["sp1-proof"])} /><CodeViewButton label="Prover trait" onClick={() => sidebar.open("sp1-prover", codeRefsReal["sp1-prover"])} /></div><ExplainedFormula question="Proof mode가 달라도 같은 statement임을 어떻게 기록할까?" idea={<>Program key와 public values를 공통 statement digest로 두고 proof mode/bytes를 별도 receipt에 결속합니다.</>} formula={String.raw`d_S=H(vkHash\|H(PV)),\quad R=H(d_S\|mode\|H(\pi)\|v)`}
    annotatedFormula={String.raw`d_S=\underbrace{H(vkHash\|H(PV)),\quad R=H(d_S\|mode\|H(\pi)\|v)}_{\text{Vkey hash 계산}}`}
    operations={[
      { expression: String.raw`H(vkHash\|H(PV)),\quad R=H(d_S\|mode\|H(\pi)\|v)`, annotation: ["Vkey hash이(가) 식의 결과에 기여하는 방식을","계산합니다.","Program key와 public values를 공통","statement digest로 두고 proof"] },
    ]} terms={[{symbol:"d_S",name:"Statement digest",description:"Program verification key와 public values의 결속입니다."},{symbol:"vkHash",name:"Vkey hash",description:"SP1 verification key의 canonical identity입니다."},{symbol:"PV",name:"Public values",description:"Guest가 공개한 ordered bytes입니다."},{symbol:"R",name:"Proof receipt id",description:"Statement, mode, proof와 version을 묶은 digest입니다."},{symbol:"mode",name:"Proof mode",description:"Core, compressed, PLONK 또는 Groth16입니다."},{symbol:String.raw`\pi`,name:"Proof bytes",description:"선택한 mode의 canonical encoded proof입니다."},{symbol:"v",name:"Version",description:"SP1/verifier/encoding revision입니다."}]} assumptions={["Exact vkey hash와 wrapped public-input encoding은 pinned SP1 source를 따릅니다.","Wrapper verifier 성공과 expected program/public values comparison을 모두 수행합니다."]} interpretation="PLONK wrapper가 cryptographically valid해도 vkHash나 PV가 기대와 다르면 application은 거절해야 합니다." /><div id="paper-sp1-proof"><CitationBlock type="code" citeKey={3} source="SP1 proof receipt types · v6.4.0 commit f66b4bf" href={PROOF}><p><strong>문제:</strong> 여러 proof modes를 public values와 함께 serialize하고 올바른 vkey에 결속해야 합니다.</p><p><strong>핵심 기여:</strong> 고정한 source는 SP1ProofWithPublicValues, proof variants와 wrapped proof public-input/vkey-hash checks를 구현합니다.</p><p><strong>중요 가정:</strong> v6.4.0 verifier, keys와 serialization format을 고정합니다.</p><p><strong>근거 범위:</strong> SP1 SDK proof container와 verification boundary입니다.</p><p><strong>일반화 금지:</strong> 임의 wrapper contract, proof compatibility across versions나 guest correctness를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · 실패와 비용 확인</p><h2 className="mt-2 text-2xl font-bold">정상·실패 사례를 확인한 뒤 방식별 비용을 비교합니다</h2></header><p>정상 사례 n=10→55와 공개 결과를 바꾼 사례를 비교합니다. 다른 ELF·검증 키, 잘못된 입력 형식, 누락하거나 순서를 바꾼 실행 조각도 거절되어야 합니다. 메모리 경계 손상이나 증거 한 바이트의 변경도 별도로 확인합니다.</p><p>CPU에서 CUDA로 장치를 바꿀 때는 같은 공개값과 유효한 증거가 나오는지 먼저 봅니다. 그 뒤 준비·실행·생성·압축·검증 시간과 이벤트 수, 증거 크기, 호스트·장치별 최대 메모리를 측정합니다. 새 버전의 실패가 확인되면 검증해 둔 버전과 실행 장치 설정으로 돌아갑니다.</p><ExplainedFormula question="서로 다른 proof mode의 유효 처리량을 어떻게 공정하게 비교할까?" idea={<>Expected statement로 검증된 receipts만 mode별 end-to-end wall time으로 나눕니다.</>} formula={String.raw`Q_m=\frac{N_{verified,m}}{T_{setup}+T_{execute}+T_{prove,m}+T_{verify,m}}`}
    annotatedFormula={String.raw`Q_m=\underbrace{\frac{N_{verified,m}}{T_{setup}+T_{execute}+T_{prove,m}+T_{verify,m}}}_{\text{기준량당 비율}}`}
    operations={[
      { expression: String.raw`\frac{N_{verified,m}}{T_{setup}+T_{execute}+T_{prove,m}+T_{verify,m}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","Expected statement로 검증된 receipts만","mode별 end-to-end wall time으로 나눕니다."] },
    ]} terms={[{symbol:"Q_m",name:"Mode throughput",description:"Mode m에서 초당 검증된 receipts입니다."},{symbol:"m",name:"Proof mode",description:"Core, compressed, PLONK 또는 Groth16입니다."},{symbol:"N_{verified,m}",name:"Verified receipts",description:"Expected VK와 PV로 승인된 mode-m receipts 수입니다."},{symbol:"T_{setup}",name:"Setup/load",description:"ELF key artifact 준비 시간입니다."},{symbol:"T_{execute}",name:"Execution",description:"ExecutionRecord 생성 시간입니다."},{symbol:"T_{prove,m}",name:"Mode proving",description:"Core/recursion/wrapper를 포함한 proving 시간입니다."},{symbol:"T_{verify,m}",name:"Mode verification",description:"Application statement comparison까지 포함한 시간입니다."}]} assumptions={["같은 ELF/input distribution/hardware/backend/cold-warm 조건을 사용합니다.","Mode마다 verifier와 proof-size 목표가 달라 하나의 숫자로 우열을 일반화하지 않습니다."]} interpretation="Compressed가 core보다 느려도 proof count/size나 downstream wrapper 목적이 다릅니다. 한 proof라도 statement mismatch면 release를 막습니다." /><div id="source-sp1-formal-verification" className="space-y-4"><h3 className="text-xl font-semibold">형식 증명에서 제외된 정상 실행도 검사해야 합니다</h3><p>Ethereum Foundation의 2026-05-20 보고서는 과거 SP1 v6.0.2의 JALR 문제를 설명합니다. 규격은 두 입력을 더한 뒤 최하위 비트를 지웁니다. 설명용 입력 100과 1이면 합 101의 마지막 비트를 지워 목적 주소 100을 얻습니다.</p><p>당시 실행기·증인 생성·제약은 이 비트 지우기를 함께 빠뜨렸습니다. 형식 정리도 마스크 전 합이 4의 배수라는 전제를 두어 이 정상 입력을 다루지 않았습니다. 내부 구현끼리 결과가 같다는 검사에 더해 독립 규격과의 비교가 필요한 이유입니다.</p><CitationBlock source="EF zkEVM · On Formal Verification and a Bug in SP1 Hypercube (2026-05-20)" citeKey={5} href="https://zkevm.ethereum.foundation/blog/sp1-fv"><p>원문은 이를 <q>This is a completeness bug</q>라고 분류합니다. 거짓 실행이 승인된 사례가 아니라 정상 실행이 증명 생성 실패나 거절로 이어진 사례입니다. 보고서에 따르면 Succinct는 v6.1.0에서 수정했다고 알렸습니다. 이 글이 고정한 v6.4.0에도 같은 버그가 남아 있다는 주장은 아닙니다.</p></CitationBlock><p>형식 증명의 적용 범위를 읽을 때는 정리가 가정한 입력, 증인 생성, 메모리 일관성, 명령 간 연결을 나누어 확인합니다. <a href="/cs/crypto/snark-overview#security">완전성과 건전성</a>은 서로 다른 방향의 보장입니다.</p></div><div id="paper-sp1-prover"><CitationBlock type="code" citeKey={4} source="SP1 Prover interface · v6.4.0 commit f66b4bf" href={PROVER}><p><strong>문제:</strong> Program setup, execution, proof construction과 verification을 stable SDK 경계로 제공해야 합니다.</p><p><strong>핵심 기여:</strong> 고정한 source는 setup/execute/prove/verify interfaces와 prover components의 조합을 정의합니다.</p><p><strong>중요 가정:</strong> 같은 v6.4.0 SDK, prover backend와 keys를 사용합니다.</p><p><strong>근거 범위:</strong> SP1 SDK prover lifecycle입니다.</p><p><strong>일반화 금지:</strong> 특정 backend availability, hardware speedup, audit/security 수준을 자동 보장하지 않습니다.</p></CitationBlock></div></section>
  </article>
  <CodeSidebar
    codeRefKey={sidebar.codeRefKey}
    codeRef={sidebar.codeRef}
    onClose={sidebar.close}
    onNavigate={sidebar.navigate}
    codeRefs={codeRefsReal}
    fileTrees={{ sp1: sp1RealTree }}
    projectMetas={{
      sp1: {
        id: "sp1",
        label: "succinctlabs/sp1 · Rust",
        badgeClass: "bg-orange-500/10 border-orange-500 text-orange-700",
      },
    }}
  />
  </>;
}
