import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { Sp1ReceiptViz } from "./Sp1ReceiptViz";

const PROGRAM = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/core/executor/src/program.rs";
const RECORD = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/core/executor/src/record.rs";
const PROOF = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/sdk/src/proof.rs";
const PROVER = "https://github.com/succinctlabs/sp1/blob/f66b4bff51d0ccff51d152e0f7f66b2ffedf3529/crates/sdk/src/prover.rs";

export default function ModernSp1() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Fibonacci RV64IM program이 n=10의 결과 55를 공개하기</p><h2 className="text-3xl font-bold tracking-tight">SP1에서는 ELF를 실행한 record가 shards가 되고, 선택한 proof mode가 public values와 verification key를 receipt로 묶는다</h2></header><p className="text-lg leading-8 text-foreground/90">고정 workload는 Rust program을 RV64IM ELF로 만들고 private stdin n=10을 실행해 public values에 55를 쓰는 작업입니다. <a className="text-primary hover:underline" href="/crypto/stark">STARK 정본</a>과 <a className="text-primary hover:underline" href="/crypto/plonk">PLONK 정본</a>은 각 proof system의 수학을 소유합니다. 이 글은 SP1 v6.4.0의 ELF/program key, execution record/shards, core·compressed·PLONK·Groth16 proof receipt 경계만 소유합니다.</p><Sp1ReceiptViz /><ContentBoundary article="sp1" /></section>

    <section id="program-artifact" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Program artifact</p><h2 className="mt-2 text-2xl font-bold">RV64IM ELF, parsed Program, proving/verifying keys와 schema를 하나의 versioned artifact로 고정한다</h2></header><p>Host source나 Cargo package 이름이 proof statement는 아닙니다. Executor가 parse한 ELF의 instructions/memory image와 setup이 만든 proving/verifying keys가 기준입니다. Source revision, compiler target/toolchain, feature/profile, ELF digest, VK digest, stdin/public-values schema와 SP1 version을 artifact receipt에 남깁니다.</p><ExplainedFormula question="Program artifact identity에 왜 ELF와 VK가 모두 필요한가?" idea={<>실행 bytes와 verifier가 승인하는 key가 같은 setup에서 나왔음을 결속합니다.</>} formula={String.raw`A_P=H(d_{src}\|d_{tool}\|H(ELF)\|H(VK)\|d_{schema}\|v)`} terms={[{symbol:"A_P",name:"Program artifact id",description:"배포 가능한 SP1 program/key bundle의 digest입니다."},{symbol:"d_{src}",name:"Source revision",description:"Program과 dependencies의 pinned revision입니다."},{symbol:"d_{tool}",name:"Toolchain identity",description:"Rust/LLVM target과 build profile digest입니다."},{symbol:"ELF",name:"RV64IM executable",description:"SP1 executor가 parse하고 실행하는 bytes입니다."},{symbol:"VK",name:"Verification key",description:"Setup이 이 program에 대해 만든 verifier key입니다."},{symbol:"d_{schema}",name:"I/O schema",description:"stdin와 public values encoding/order digest입니다."},{symbol:"v",name:"SP1 version",description:"Executor/prover/serialization version입니다."}]} assumptions={["모든 fields는 canonical length-delimited encoding입니다.","정확한 SP1 vkey hash/serialization은 pinned implementation을 따릅니다."]} interpretation="ELF가 같아도 다른 VK를 묶거나 public-values order가 바뀌면 새 artifact입니다." /><div id="paper-sp1-program"><CitationBlock type="code" citeKey={1} source="SP1 Program parser · v6.4.0 commit f66b4bf" href={PROGRAM}><p><strong>문제:</strong> ELF bytes를 zkVM이 실행할 deterministic RISC-V program image로 바꿔야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 RV64IM ELF parsing과 Program의 instruction/memory image construction 경계를 제공합니다.</p><p><strong>중요 가정:</strong> SP1 v6.4.0 executor와 지원 ELF/ISA profile을 사용합니다.</p><p><strong>근거 범위:</strong> 해당 release의 program loading implementation입니다.</p><p><strong>일반화 금지:</strong> 임의 ELF, native OS behavior, source-level equivalence나 program safety를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="execution-shards" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Execution record and shards</p><h2 className="mt-2 text-2xl font-bold">Executor events를 ExecutionRecord로 모으고 shard마다 public state와 memory boundary를 이어 붙인다</h2></header><p>ExecutionRecord는 단순 instruction count가 아니라 CPU, memory, syscall/precompile events와 public values를 담는 witness artifact입니다. Record를 shards로 나누면 각 shard proof를 병렬 생성할 수 있지만, initial/final PC·clock와 memory initialization/finalization 같은 boundary constraints가 이어져야 원래 한 실행입니다.</p><ExplainedFormula question="여러 shards가 같은 실행임을 어떤 불변식으로 확인할까?" idea={<>인접 shard의 종료 machine commitment와 다음 시작 commitment를 같게 합니다.</>} formula={String.raw`m_i^{out}=m_{i+1}^{in},\quad E=\sum_{i=0}^{k-1}|events_i|`} terms={[{symbol:"m_i^{out}",name:"Shard output state",description:"i번째 shard의 PC, clock, memory/public state commitment입니다."},{symbol:"m_{i+1}^{in}",name:"Next input state",description:"다음 shard가 시작할 때의 같은 state commitment입니다."},{symbol:"k",name:"Shard count",description:"ExecutionRecord를 나눈 조각 수입니다."},{symbol:"events_i",name:"Shard events",description:"i번째 shard에 포함된 admitted execution events입니다."},{symbol:"E",name:"Total events",description:"전체 execution의 event 수입니다."}]} assumptions={["같은 ELF/program key와 execution semantics를 사용합니다.","실제 public-values layout과 boundary constraints는 pinned machine implementation을 따릅니다."]} interpretation="4개 shards 중 세 번째의 시작 PC가 두 번째 종료 PC와 다르면 shard proofs를 recursion으로 합쳐서는 안 됩니다." /><div id="paper-sp1-record"><CitationBlock type="code" citeKey={2} source="SP1 ExecutionRecord · v6.4.0 commit f66b4bf" href={RECORD}><p><strong>문제:</strong> RISC-V execution과 chips가 소비할 events/public values를 shardable witness로 표현해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 ExecutionRecord fields, shard metadata, memory events와 public-values constraints를 정의합니다.</p><p><strong>중요 가정:</strong> v6.4.0 machine/chips와 같은 record schema를 사용합니다.</p><p><strong>근거 범위:</strong> SP1 executor record and sharding data model입니다.</p><p><strong>일반화 금지:</strong> 모든 shard size가 최적이거나 record만으로 proof soundness가 성립한다는 뜻은 아닙니다.</p></CitationBlock></div></section>

    <section id="proof-receipt" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Proof receipt</p><h2 className="mt-2 text-2xl font-bold">Core proofs를 compressed proof로 재귀 집계하고 필요할 때 PLONK/Groth16 wrapper로 내려 public values와 vkey hash를 확인한다</h2></header><p>Proof mode는 같은 bytes의 이름표가 아닙니다. Core는 shard proofs, compressed는 recursion으로 묶은 proof, PLONK/Groth16은 외부 verifier 친화적 wrapper artifact입니다. Receipt에는 mode, SP1 version, VK/vkey hash, public-values schema/bytes, proof encoding, backend와 verifier result를 남깁니다. Wrapper가 있어도 원래 program key와 public values 결속을 다시 검사합니다.</p><ExplainedFormula question="Proof mode가 달라도 같은 statement임을 어떻게 기록할까?" idea={<>Program key와 public values를 공통 statement digest로 두고 proof mode/bytes를 별도 receipt에 결속합니다.</>} formula={String.raw`d_S=H(vkHash\|H(PV)),\quad R=H(d_S\|mode\|H(\pi)\|v)`} terms={[{symbol:"d_S",name:"Statement digest",description:"Program verification key와 public values의 결속입니다."},{symbol:"vkHash",name:"Vkey hash",description:"SP1 verification key의 canonical identity입니다."},{symbol:"PV",name:"Public values",description:"Guest가 공개한 ordered bytes입니다."},{symbol:"R",name:"Proof receipt id",description:"Statement, mode, proof와 version을 묶은 digest입니다."},{symbol:"mode",name:"Proof mode",description:"Core, compressed, PLONK 또는 Groth16입니다."},{symbol:String.raw`\pi`,name:"Proof bytes",description:"선택한 mode의 canonical encoded proof입니다."},{symbol:"v",name:"Version",description:"SP1/verifier/encoding revision입니다."}]} assumptions={["Exact vkey hash와 wrapped public-input encoding은 pinned SP1 source를 따릅니다.","Wrapper verifier 성공과 expected program/public values comparison을 모두 수행합니다."]} interpretation="PLONK wrapper가 cryptographically valid해도 vkHash나 PV가 기대와 다르면 application은 거절해야 합니다." /><div id="paper-sp1-proof"><CitationBlock type="code" citeKey={3} source="SP1 proof receipt types · v6.4.0 commit f66b4bf" href={PROOF}><p><strong>문제:</strong> 여러 proof modes를 public values와 함께 serialize하고 올바른 vkey에 결속해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 SP1ProofWithPublicValues, proof variants와 wrapped proof public-input/vkey-hash checks를 구현합니다.</p><p><strong>중요 가정:</strong> v6.4.0 verifier, keys와 serialization format을 고정합니다.</p><p><strong>근거 범위:</strong> SP1 SDK proof container와 verification boundary입니다.</p><p><strong>일반화 금지:</strong> 임의 wrapper contract, proof compatibility across versions나 guest correctness를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Execute parity와 shard continuity를 먼저 확인한 뒤 mode별 prove/verify receipt를 따로 승인한다</h2></header><p>n=10→55 positive fixture와 wrong public value, wrong ELF/VK, stdin schema mismatch, missing/reordered shard, memory-boundary corruption, wrong proof mode/version, 한 byte 손상을 테스트합니다. CPU/CUDA 같은 backend를 바꿔도 같은 PV와 valid statement가 나오는지 확인한 뒤 setup/execute/core/compress/wrap/verify, events/shards, proof bytes와 peak host/device memory를 기록합니다. 새 backend나 wrapper 실패 시 이전 version/artifact/backend allowlist로 rollback합니다.</p><ExplainedFormula question="서로 다른 proof mode의 유효 처리량을 어떻게 공정하게 비교할까?" idea={<>Expected statement로 검증된 receipts만 mode별 end-to-end wall time으로 나눕니다.</>} formula={String.raw`Q_m=\frac{N_{verified,m}}{T_{setup}+T_{execute}+T_{prove,m}+T_{verify,m}}`} terms={[{symbol:"Q_m",name:"Mode throughput",description:"Mode m에서 초당 검증된 receipts입니다."},{symbol:"m",name:"Proof mode",description:"Core, compressed, PLONK 또는 Groth16입니다."},{symbol:"N_{verified,m}",name:"Verified receipts",description:"Expected VK와 PV로 승인된 mode-m receipts 수입니다."},{symbol:"T_{setup}",name:"Setup/load",description:"ELF key artifact 준비 시간입니다."},{symbol:"T_{execute}",name:"Execution",description:"ExecutionRecord 생성 시간입니다."},{symbol:"T_{prove,m}",name:"Mode proving",description:"Core/recursion/wrapper를 포함한 proving 시간입니다."},{symbol:"T_{verify,m}",name:"Mode verification",description:"Application statement comparison까지 포함한 시간입니다."}]} assumptions={["같은 ELF/input distribution/hardware/backend/cold-warm 조건을 사용합니다.","Mode마다 verifier와 proof-size 목표가 달라 하나의 숫자로 우열을 일반화하지 않습니다."]} interpretation="Compressed가 core보다 느려도 proof count/size나 downstream wrapper 목적이 다릅니다. 한 proof라도 statement mismatch면 release를 막습니다." /><div id="paper-sp1-prover"><CitationBlock type="code" citeKey={4} source="SP1 Prover interface · v6.4.0 commit f66b4bf" href={PROVER}><p><strong>문제:</strong> Program setup, execution, proof construction과 verification을 stable SDK 경계로 제공해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 setup/execute/prove/verify interfaces와 prover components의 조합을 정의합니다.</p><p><strong>중요 가정:</strong> 같은 v6.4.0 SDK, prover backend와 keys를 사용합니다.</p><p><strong>근거 범위:</strong> SP1 SDK prover lifecycle입니다.</p><p><strong>일반화 금지:</strong> 특정 backend availability, hardware speedup, audit/security 수준을 자동 보장하지 않습니다.</p></CitationBlock></div><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> ELF/key artifact, Program parse, record fields, shard continuity, proof modes, vkey/PV receipt, backend parity, negative fixtures, 측정과 rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>;
}
