import type { Article } from "../types";

export const philosophyHistoryArticles: Article[] = [
  {
    slug: "ancient-mediterranean-inquiry-virtue-and-control",
    title: "좋은 삶을 누가 판단하는가: 고대 지중해의 문답·덕·통제",
    subcategory: "philosophy-history-ancient-mediterranean",
    sections: [
      { id: "overview", title: "1. 좋은 삶은 정답 목록보다 자기 이유를 검사하는 일에서 시작합니다" },
      { id: "black-box", title: "2. 질문·성품·공동체·통제의 네 갈래를 엽니다" },
      { id: "case", title: "3. 10시간의 계획과 경기 결과를 같은 장부에 넣지 않습니다" },
      { id: "picture", title: "4. 아테네의 문답에서 제국 시대의 생활 훈련까지 이동합니다" },
      { id: "need", title: "5. 이름을 외우는 연표만으로는 논쟁의 이유를 알 수 없습니다" },
      { id: "names", title: "6. 문답 검사·덕의 습관·통제 구분에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 믿음을 질문하고 행동을 고른 뒤 결과를 다시 해석합니다" },
      { id: "source", title: "8. MIT 과정은 플라톤에서 칸트까지 질문과 시대 변화를 함께 읽습니다" },
      { id: "comparison", title: "9. 고대 윤리는 소크라테스에서 스토아까지 하나의 덕 이론이 아닙니다" },
      { id: "limits", title: "10. 그리스 철학을 서양 전체의 시작이나 보편 이성의 단일 원천으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/ancient-mediterranean-inquiry-virtue-and-control"),
  },
  {
    slug: "warring-states-china-care-ritual-and-standards",
    title: "전쟁을 줄일 기준은 무엇인가: 전국시대 중국의 겸애·예·법",
    subcategory: "philosophy-history-warring-states",
    sections: [
      { id: "overview", title: "1. 전쟁 중인 나라의 예산 100을 어디에 쓰느냐가 철학 논쟁이 됩니다" },
      { id: "black-box", title: "2. 목적·판단 기준·사람에 대한 가정·행정 수단을 엽니다" },
      { id: "case", title: "3. 군비 50과 의례 20을 줄이면 구제 재원이 얼마나 늘어나는지 봅니다" },
      { id: "picture", title: "4. 스승의 학파보다 서로 비판하고 빌린 논쟁망을 봅니다" },
      { id: "need", title: "5. 겸애를 모두를 똑같이 좋아하라는 감정 명령으로 줄이지 않습니다" },
      { id: "names", title: "6. 겸애·의례 수양·행정 표준에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 예산 변경을 결과·행동·권력의 세 장부로 검사합니다" },
      { id: "source", title: "8. Stanford의 묵가 개관은 윤리·정치·논리의 결합을 보여 줍니다" },
      { id: "comparison", title: "9. 법가라는 이름은 법 하나보다 표준·기술·권세의 묶음을 가리킵니다" },
      { id: "limits", title: "10. 전국시대 사상을 현대 진보·보수나 유교 대 법치로 바로 번역하지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/warring-states-china-care-ritual-and-standards"),
  },
  {
    slug: "classical-india-pramana-self-and-liberation",
    title: "무엇이 지식이 되는가: 고전 인도의 프라마나·자아·해탈 논쟁",
    subcategory: "philosophy-history-classical-india",
    sections: [
      { id: "overview", title: "1. ‘내일 시장이 열린다’는 한 문장을 무엇으로 믿을지 묻습니다" },
      { id: "black-box", title: "2. 인식 사건·지식 통로·오류 검사·삶의 목표를 나눕니다" },
      { id: "case", title: "3. 네 근거를 세어도 독립된 지식 통로 수는 학파마다 다릅니다" },
      { id: "picture", title: "4. 베다 해석·논쟁 규칙·불교 비판이 서로의 이론을 정교하게 만듭니다" },
      { id: "need", title: "5. 지각이 기본이라는 말도 착각과 개념 작용을 설명해야 합니다" },
      { id: "names", title: "6. 프라마나·나이야의 네 통로·불교의 두 통로에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 시장 정보를 행동으로 옮기기 전에 통로별 실패를 찾습니다" },
      { id: "source", title: "8. Stanford 개관은 고전 인도 인식론을 거의 스무 세기의 논쟁으로 봅니다" },
      { id: "comparison", title: "9. 디그나가와 다르마키르티는 불교 인식론의 방향을 바꿨습니다" },
      { id: "limits", title: "10. 인도 철학을 여섯 정통 학파 목록이나 종교적 신비로 줄이지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/classical-india-pramana-self-and-liberation"),
  },
  {
    slug: "islamic-philosophy-translation-illumination-and-being",
    title: "번역은 끝이 아니라 새 논쟁의 시작이었다: 이슬람 철학의 존재·빛·종합",
    subcategory: "philosophy-history-islamic",
    sections: [
      { id: "overview", title: "1. 번역된 책 한 권은 답이 아니라 새 질문을 만드는 재료였습니다" },
      { id: "black-box", title: "2. 번역·논증·직관·경전 해석의 네 지식 작업을 엽니다" },
      { id: "case", title: "3. 9세기·11세기·12세기·17세기의 네 정거장을 잇습니다" },
      { id: "picture", title: "4. 바그다드에서 라틴 서방과 이스파한까지 여러 갈래가 뻗습니다" },
      { id: "need", title: "5. 알가잘리 이후 철학이 끝났다는 이야기를 자료와 맞춰 봅니다" },
      { id: "names", title: "6. 번역·주석 사슬·조명적 앎·존재의 우위에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 한 개념이 번역되고 반박되고 다시 종합되는 과정을 추적합니다" },
      { id: "source", title: "8. 아랍어 철학은 라틴 서방의 거의 모든 분야를 바꿨습니다" },
      { id: "comparison", title: "9. 수흐라와르디와 물라 사드라는 논증과 직관의 경계를 다시 그렸습니다" },
      { id: "limits", title: "10. 이슬람 철학을 한 종교·한 언어·한 문명 블록으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/islamic-philosophy-translation-illumination-and-being"),
  },
  {
    slug: "early-modern-europe-doubt-experience-and-causality",
    title: "확실성에서 경험의 조건까지: 근대 유럽의 의심·인과·마음",
    subcategory: "philosophy-history-early-modern",
    sections: [
      { id: "overview", title: "1. 당구공이 열 번 움직였어도 열한 번째 원인을 눈으로 본 것은 아닙니다" },
      { id: "black-box", title: "2. 의심·경험·습관·경험의 조건을 나눕니다" },
      { id: "case", title: "3. 관찰 10회와 11번째 예측 사이의 빈칸을 찾습니다" },
      { id: "picture", title: "4. 종교전쟁·인쇄·실험과 기계론이 지식의 무대를 바꿉니다" },
      { id: "need", title: "5. 몸과 마음을 나눈 뒤 둘이 어떻게 작용하는지 설명해야 합니다" },
      { id: "names", title: "6. 방법적 의심·인과 습관·선험적 인과 범주에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 같은 10회 기록을 데카르트·흄·칸트의 질문으로 다시 씁니다" },
      { id: "source", title: "8. MIT 과정은 정전과 동시대 비판자를 같은 읽기 훈련에 놓습니다" },
      { id: "comparison", title: "9. 흄이 흔든 인과를 칸트가 그대로 되돌린 것은 아닙니다" },
      { id: "limits", title: "10. 합리론 대 경험론 두 편으로 근대 철학 전체를 나누지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/early-modern-europe-doubt-experience-and-causality"),
  },
  {
    slug: "colonial-modernity-race-and-decolonization",
    title: "식민 질서는 사람의 자기 인식까지 바꾼다: 뒤부아·파농과 탈식민 철학",
    subcategory: "philosophy-history-colonial-modernity",
    sections: [
      { id: "overview", title: "1. 같은 지원서 100장도 누가 기준을 만들었는지에 따라 다르게 읽힙니다" },
      { id: "black-box", title: "2. 제도·타인의 시선·자기 이해·집단 행동을 나눕니다" },
      { id: "case", title: "3. 100명 중 40명의 준비 조건을 지우면 같은 시험도 다른 비용을 숨깁니다" },
      { id: "picture", title: "4. 노예제 폐지 뒤의 인종 질서와 식민 통치가 철학의 대상을 바꿉니다" },
      { id: "need", title: "5. 억압의 경험을 개인의 낮은 자존감으로 치료하면 제도가 남습니다" },
      { id: "names", title: "6. 이중의식·식민 주체 형성·탈식민 실천에 이름을 붙입니다" },
      { id: "mechanism", title: "7. 지원서에서 시선이 만들어지고 다시 제도로 돌아가는 경로를 봅니다" },
      { id: "source", title: "8. 뒤부아의 이중의식은 타고난 분열이 아니라 억압적 환경에서 생깁니다" },
      { id: "comparison", title: "9. 파농은 식민 폭력이 독립 뒤의 정치와 문화에도 남는다고 봅니다" },
      { id: "limits", title: "10. 뒤부아와 파농을 모든 흑인·식민 경험의 한 목소리로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-history/colonial-modernity-race-and-decolonization"),
  },
];
