import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import ModernLotusSuiteViz from "./viz/ModernLotusSuiteViz";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefs } from "./codeRefs";
import { lotusTree } from "./fileTrees";

const COMPONENTS = "https://docs.filecoin.io/storage-providers/architecture/lotus-components";
const LOTUS = "https://github.com/filecoin-project/lotus/tree/154c0c3a46e92006008818bb06aaf959e2e705a9";

export default function ModernFilecoinLotusArticle() {
  const sidebar = useCodeSidebar();
  return <>
  <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">높이 100의 tipset과 sector 42가 만나는 지점부터</p><h2 className="text-3xl font-bold tracking-tight">Lotus는 하나의 daemon이 아니라 chain 검증과 provider 작업을 artifact로 연결하는 suite다</h2></header><p className="text-lg leading-8 text-foreground/90">Filecoin node가 받은 block을 검증하는 일과 고객 bytes를 sector로 만들고 proof를 제출하는 일은 같은 완료 상태가 아닙니다. <strong>Tipset</strong>은 같은 부모에서 함께 실행할 수 있는 block 묶음이고, <strong>sector</strong>는 provider가 저장 증명의 단위로 관리하는 data container입니다. 이 글은 Lotus 전체의 지도만 소유하며, ChainSync는 <a className="text-primary hover:underline" href="/blockchain/lotus-chain">Lotus chain 글</a>, deal은 <a className="text-primary hover:underline" href="/blockchain/lotus-market">market 글</a>, proof scheduling은 <a className="text-primary hover:underline" href="/blockchain/lotus-miner">provider 글</a>에서 깊게 내려갑니다.</p><ModernLotusSuiteViz /><ContentBoundary article="filecoin-lotus" /></section>

    <section id="process-map" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Process responsibility</p><h2 className="mt-2 text-2xl font-bold">Chain lag·deal failure·proof miss를 한 프로세스 탓으로 묶지 않는다</h2></header><p><code>lotus</code> daemon은 P2P chain sync, tipset 검증·state execution, wallet/RPC를 맡습니다. Provider 쪽 scheduler는 sector와 proof jobs를 만들고 worker capability에 배치하며, worker는 CPU·GPU·storage를 사용해 계산합니다. Boost는 deal negotiation·data transfer와 retrieval 입구를 담당합니다. 역사적 <code>lotus-miner</code> state machine과 Curio의 database-backed task model은 같은 구현이 아니므로 배포 revision을 반드시 기록합니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="FilecoinEC struct" onClick={() => sidebar.open("lotus-filecoin-ec", codeRefs["lotus-filecoin-ec"])} /><CodeViewButton label="CreateBlock()" onClick={() => sidebar.open("lotus-mine", codeRefs["lotus-mine"])} /></div><div className="grid gap-3 sm:grid-cols-2"><article className="rounded-lg border border-border p-4"><h3 className="font-semibold">고정 예제 · chain</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">높이 100 tipset의 header·messages·state root는 lotus daemon이 검증합니다. Provider worker가 빨라도 node가 stale head라면 새 randomness를 신뢰할 수 없습니다.</p></article><article className="rounded-lg border border-border p-4"><h3 className="font-semibold">고정 예제 · storage</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Deal D7은 Boost에서 PieceCID P로 준비되고 scheduler가 sector 42 작업을 만든 뒤 worker가 CommD·CommR과 proof를 계산합니다.</p></article></div><div id="paper-lotus-components"><CitationBlock citeKey={1} source="Lotus suite components · official docs" href={COMPONENTS}><p><strong>문제:</strong> Node·provider·worker·dealmaking 책임을 구분해야 합니다.</p><p><strong>핵심 기여:</strong> Lotus daemon, miner/worker와 Boost의 역할 및 service dependency를 설명합니다.</p><p><strong>중요 가정:</strong> 2026-08-14 문서와 실제 배포 topology·versions를 함께 기록합니다.</p><p><strong>근거 범위:</strong> 공식 Filecoin storage-provider component 설명입니다.</p><p><strong>일반화 금지:</strong> 모든 배포가 같은 process 수·HA 구성·성능을 가진다는 뜻은 아닙니다.</p></CitationBlock></div></section>

    <section id="artifact-handoff" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Artifact handoff</p><h2 className="mt-2 text-2xl font-bold">D7→PieceCID P→sector 42→CommR→chain receipt를 하나의 lineage로 잇는다</h2></header><p>Process 이름보다 중요한 것은 immutable identifier입니다. Chain 쪽에는 network, tipset key, message CID, state/receipt roots가 있고 provider 쪽에는 proposal digest, PieceCID와 size, sector number, CommD·CommR, proof profile·parameters, job generation이 있습니다. 각 단계는 upstream digest와 software/schema revision을 받아야 하며 durable completion marker가 쓰이기 전에는 다음 단계가 결과를 소비하면 안 됩니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="Weight()" onClick={() => sidebar.open("lotus-weight", codeRefs["lotus-weight"])} /><CodeViewButton label="ChainStore struct" onClick={() => sidebar.open("lotus-chainstore", codeRefs["lotus-chainstore"])} /><CodeViewButton label="StateManager struct" onClick={() => sidebar.open("lotus-statemgr", codeRefs["lotus-statemgr"])} /></div><ol className="grid gap-3 md:grid-cols-4">{[["1","deal","D7 · P · size"],["2","sector","42 · CommD/CommR"],["3","proof","profile · proof digest"],["4","chain","message CID · tipset receipt"]].map(([n,t,d])=><li key={n} className="rounded-lg border border-border p-4"><p className="font-mono text-xs text-primary">{n}</p><h3 className="mt-2 font-semibold">{t}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{d}</p></li>)}</ol><p><strong>완료 경계:</strong> Deal을 publish한 것은 저장 의도를 chain에 올린 것이고, sector activation은 별도 actor state입니다. Proof bytes 생성은 cryptographic computation 완료일 뿐 message inclusion과 reorg confidence까지 뜻하지 않습니다. 이 경계를 합치면 재시도에서 duplicate publish나 stale proof가 발생합니다.</p></section>

    <section id="operations" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Operations</p><h2 className="mt-2 text-2xl font-bold">Readiness는 profile마다 필요한 chain·version·artifact 조건의 교집합이다</h2></header><ExplainedFormula question="한 provider job을 실행 가능한 상태라고 언제 판단할까?" idea={<>Chain context, software/profile compatibility와 upstream artifact lineage가 모두 유효해야 합니다.</>} formula={String.raw`A_{ready}=A_{chain}\land A_{profile}\land A_{lineage}`}
    annotatedFormula={String.raw`A_{ready}=\underbrace{A_{chain}\land A_{profile}\land A_{lineage}}_{\text{판정 조건 결합}}`}
    operations={[
      { expression: String.raw`A_{chain}\land A_{profile}\land A_{lineage}`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","Chain context, software/profile","compatibility와 upstream artifact","lineage가 모두 유효해야 합니다."] },
    ]} terms={[{symbol:"A_{ready}",name:"Job readiness",description:"이 generation을 worker 또는 chain submission에 보낼 수 있으면 1입니다."},{symbol:"A_{chain}",name:"Chain context",description:"필요한 head·network version·randomness가 승인됐으면 1입니다."},{symbol:"A_{profile}",name:"Compatibility",description:"Node·actor·proof/service schema가 허용된 조합이면 1입니다."},{symbol:"A_{lineage}",name:"Artifact lineage",description:"Upstream IDs·digests·completion markers가 같은 generation이면 1입니다."}]} assumptions={["각 Boolean은 typed evidence로 계산하며 단순 process health가 아닙니다.","Read-only node처럼 provider artifact가 필요 없는 profile은 별도 readiness 식을 사용합니다."]} interpretation="세 항 중 하나라도 0이면 job을 시작하거나 external effect를 내지 않습니다. 이 식은 availability 수치나 deadline 성공 확률을 계산하지 않습니다." /><p>장애도 같은 지도에서 좁힙니다. Chain lag는 peer·header/message fetch·state replay부터, deal failure는 proposal/piece/publish lineage부터, PoSt miss는 deadline snapshot·storage reads·proof worker·message inclusion부터 확인합니다. 한 서비스의 CPU 사용률만으로 다른 failure domain의 원인을 결론내리지 않습니다.</p></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release and rollback</p><h2 className="mt-2 text-2xl font-bold">Version manifest와 failure replay가 맞아야 suite 조합을 채택한다</h2></header><p>Canary는 Lotus source SHA, network·actor bundle, provider scheduler·database schema, Boost/retrieval profile, proof API·parameter manifest를 고정합니다. 같은 D7/sector 42 fixture에서 stale head, wrong CommR, missing worker, process crash, message replacement와 reorg를 주입하고 state·artifact·external-effect parity를 확인합니다. 측정은 sync lag, job queue age, stage p50/p99, proof verification, chain inclusion/confidence와 retrieval success를 섞지 않고 기록합니다.</p><p><strong>증명 아이디어:</strong> 각 external effect가 유일한 job generation과 canonical chain receipt를 역참조하면 재시작한 process가 이미 완료된 작업을 새 작업으로 오인하기 어렵습니다. 반대로 모든 health check가 성공해도 stale head의 randomness로 proof를 만들면 lineage가 끊기므로 readiness는 0입니다. 실패 시 새 writes를 멈추고 이전 호환 binary·schema·parameter bundle로 돌아가며, 이미 제출한 message는 chain state를 조회해 재전송 여부를 결정합니다.</p><div id="paper-lotus-source"><CitationBlock type="code" citeKey={2} source="Lotus v1.36.0 · commit 154c0c3" href={LOTUS}><p><strong>문제:</strong> Suite implementation 사실을 재현 가능한 revision에 고정해야 합니다.</p><p><strong>핵심 기여:</strong> Lotus node와 legacy miner/worker의 chain·state·storage source tree를 제공합니다.</p><p><strong>중요 가정:</strong> v1.36.0 dependencies, network/actor/proof profile과 build configuration을 함께 고정합니다.</p><p><strong>근거 범위:</strong> Commit 154c0c3에 존재하는 package/API behavior입니다.</p><p><strong>일반화 금지:</strong> Master branch, Curio·Boost 전체, production availability나 future behavior를 보장하지 않습니다.</p></CitationBlock></div><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> 네 process의 owner, 고정 예제, chain/provider identifiers, 네 completion states, readiness 식, failure routing, immutable lineage, stale-head 반례, compatibility canary와 rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>
  <CodeSidebar
    codeRefKey={sidebar.codeRefKey}
    codeRef={sidebar.codeRef}
    onClose={sidebar.close}
    onNavigate={sidebar.navigate}
    codeRefs={codeRefs}
    fileTrees={{ lotus: lotusTree }}
    projectMetas={{
      lotus: {
        id: "lotus",
        label: "Lotus · Go",
        badgeClass: "bg-blue-500/10 border-blue-500 text-blue-700",
      },
    }}
  />
  </>;
}
