import ExplainedFormula from "@/components/ui/explained-formula";
import BPEMergeViz from "./viz/BPEMergeViz";
export default function BPE(){return <section id="bpe" className="mb-16 scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">BPE는 corpus 빈도를 merge rank로 바꾼다</h2><div className="prose prose-neutral dark:prose-invert max-w-none"><p className="leading-7">Subword BPE는 초기 symbol sequence에서 인접 pair 빈도를 세고 가장 자주 붙는 pair를 새 symbol로 병합한다. 이 과정을 반복한 결과는 vocabulary와 순서가 있는 merge table이다. Encoding에서는 corpus 빈도를 다시 세지 않고 해당 table의 우선순위로 입력 symbol을 합친다.</p></div><BPEMergeViz/><ExplainedFormula question="BPE training의 한 round에서 어떤 pair를 새 token으로 만들까?" idea={<>현재 corpus segmentation에서 모든 인접 symbol pair의 발생 횟수를 센 뒤 가장 많은 pair를 선택합니다. 병합하면 corpus를 다시 표현하므로 다음 round의 count도 바뀝니다.</>} formula={String.raw`(a^*,b^*)=\arg\max_{(a,b)\in\mathcal P}\operatorname{count}_{\mathcal C}(a,b)`}
annotatedFormula={String.raw`(a^*,b^*)=\underbrace{\arg\max_{(a,b)\in\mathcal P}\operatorname{count}_{\mathcal C}(a,b)}_{\text{경계 후보 선택}}`}
operations={[
  { expression: String.raw`\arg\max_{(a,b)\in\mathcal P}\operatorname{count}_{\mathcal C}(a,b)`, annotation: ["허용 후보 중 목적에 맞는 경계값을 선택합니다.","현재 corpus segmentation에서 모든 인접","symbol pair의 발생 횟수를 센 뒤 가장 많은","pair를 선택합니다."] },
]} terms={[{symbol:String.raw`\mathcal C`,name:"segmented corpus",description:"현재까지 학습한 merge가 적용된 전체 training corpus입니다."},{symbol:String.raw`\mathcal P`,name:"adjacent pairs",description:"현재 segmentation에서 실제로 이웃한 symbol pair 집합입니다."},{symbol:"(a^*,b^*)",name:"next merge",description:"새 vocabulary symbol ab가 되는 pair입니다."}]} assumptions={["같은 빈도의 tie-break, word boundary와 pre-tokenizer 규칙을 구현에 고정합니다.","Vocabulary budget에 도달할 때까지 greedy하게 반복하므로 전체 최적 compression을 보장하지 않습니다."]} interpretation="BPE는 merge 당시의 local frequency를 보존합니다. Token의 언어학적 형태소성이나 downstream utility를 직접 최적화하는 식은 아니므로 corpus와 pre-tokenizer가 바뀌면 merge 결과도 달라집니다."/><div className="prose prose-neutral dark:prose-invert max-w-none"><h3 id="byte-level-tokenization" className="scroll-mt-20">Byte-level tokenization은 초기 alphabet을 byte 256개로 고정한다</h3><p className="leading-7">
            Byte-level tokenization은 character나 subword 대신 UTF-8 byte 값 0~255를 초기 alphabet으로 삼는다. 어떤 입력이 오든 결국
            byte sequence로 표현되므로 training vocabulary에 없던 문자열도 처음부터 알려진 256개 base token만으로 완전히 표현할 수 있다.
            Unknown 문자를 위한 별도 fallback 규칙이 필요 없어 UNK 비율이 정확히 0이 된다.
          </p><p className="leading-7">작은 예로 한글 &quot;안&quot; 한 글자는 UTF-8에서 3 byte(<code>EC 95 88</code>)로 인코딩된다. Byte-level BPE 학습 전이라면 &quot;안&quot;은 이 3개의 base byte-token으로 남고, 학습 corpus에 &quot;안&quot;이 자주 나와 <code>EC-95-88</code> pair가 반복해서 병합 대상이 되면 결국 하나의 token으로 합쳐진다. 반대로 드문 script는 병합 기회가 적어 여러 byte-token으로 길게 쪼개진 채로 남을 수 있다.</p><p className="leading-7">OpenAI GPT-2는 이 byte-to-unicode 매핑 위에 BPE 병합을 적용해 <code>&lt;UNK&gt;</code> 없이 임의의 텍스트를 인코딩했고, 이후 <a href="https://github.com/openai/tiktoken" target="_blank" rel="noreferrer">tiktoken</a>처럼 reversible byte-level BPE 구현으로 이어졌다. 그러나 모든 BPE 구현이 byte 기반이거나 무조건 lossless인 것은 아니다. Normalizer, regex pre-tokenizer, byte mapping과 special-token policy를 함께 확인한다.</p></div><div id="paper-gpt2-bytebpe" className="not-prose my-8 border-l border-primary/50 pl-4 scroll-mt-24"><p className="text-xs font-bold text-primary">논문 읽기 · Byte-level BPE</p><p className="mt-2 text-sm font-semibold">Language Models are Unsupervised Multitask Learners (GPT-2)</p><p className="mt-2 text-sm leading-6 text-muted-foreground">
            Character-level BPE의 256-byte 시작 alphabet을 그대로 쓰되 byte를 출력 가능한 unicode 문자로 매핑했습니다. 그렇게 만든 byte-
            level BPE encoder는 별도 UNK 없이 임의의 텍스트에 BPE를 적용합니다. 이 글에서 가져오는 것은 초기 alphabet을 byte로 고정한다는 mechanism
            하나입니다. 논문의 language-model 성능 주장까지 그대로 옮겨 오지는 않습니다.
          </p><a className="mt-3 inline-block text-sm font-medium text-primary underline-offset-4 hover:underline" href="https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf" target="_blank" rel="noreferrer">원 논문 보기</a></div><div id="paper-bpe" className="not-prose my-8 border-l border-primary/50 pl-4 scroll-mt-24"><p className="text-xs font-bold text-primary">논문 읽기 · Subword BPE</p><p className="mt-2 text-sm font-semibold">Neural Machine Translation of Rare Words with Subword Units</p><p className="mt-2 text-sm leading-6 text-muted-foreground">
            희귀 단어와 open vocabulary 번역을 위해 character sequence에 BPE를 적용해 frequent character sequence를 subword로
            학습했습니다. 모든 현대 byte-level tokenizer의 normalization·regex·special-token 규격까지 이 논문이 정한 것은 아닙니다.
          </p><a className="mt-3 inline-block text-sm font-medium text-primary underline-offset-4 hover:underline" href="https://arxiv.org/abs/1508.07909" target="_blank" rel="noreferrer">원 논문과 학습 절차 보기</a></div></section>}
