import { useMemo, useState } from 'react';
import { Activity, ChartSpline, CircleDot, Gauge, ScanSearch, ShieldCheck } from 'lucide-react';
import { MetricGrid, SegmentedControl } from '../../nlp-shared';

const clamp = (value: number, low: number, high: number) => Math.min(high, Math.max(low, value));
const fmt = (value: number, digits = 2) => Number.isFinite(value) ? value.toFixed(digits) : 'n/a';

function Range({ label, value, min, max, step = 1, unit = '', tone = 'blue', onChange }: { label: string; value: number; min: number; max: number; step?: number; unit?: string; tone?: 'blue' | 'teal' | 'amber' | 'violet'; onChange: (value: number) => void }) {
  const accent = { blue: 'accent-blue-600', teal: 'accent-teal-600', amber: 'accent-amber-600', violet: 'accent-violet-600' }[tone];
  return <label className="block min-w-0"><span className="mb-2 flex items-center justify-between gap-3 text-xs font-semibold"><span>{label}</span><span className="shrink-0 font-mono">{value}{unit}</span></span><input className={`h-2 w-full cursor-pointer ${accent}`} type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>;
}

function Status({ danger = false, children }: { danger?: boolean; children: React.ReactNode }) {
  return <div className={`rounded border px-3 py-2 text-xs leading-relaxed ${danger ? 'border-red-500/30 bg-red-500/[0.045] text-red-800 dark:text-red-200' : 'border-teal-500/30 bg-teal-500/[0.045] text-teal-900 dark:text-teal-100'}`}>{children}</div>;
}

function LabFrame({ icon, title, status, danger = false, children }: { icon: React.ReactNode; title: string; status: string; danger?: boolean; children: React.ReactNode }) {
  return <figure className="foundation-viz-explorer not-prose my-8 overflow-hidden rounded-md border border-border bg-background"><figcaption className="grid min-w-0 gap-2 border-b border-border py-4 pl-4 pr-16 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center sm:pr-20"><span className="flex items-center gap-2 font-mono text-xs font-black text-blue-700 dark:text-blue-300">{icon} FRACTURE LAB</span><strong className="text-sm leading-snug">{title}</strong><span className={`text-[10px] font-black ${danger ? 'text-red-700 dark:text-red-300' : 'text-teal-700 dark:text-teal-300'}`}>{status}</span></figcaption>{children}</figure>;
}

function PlotShell({ children, label }: { children: React.ReactNode; label: string }) {
  return <div className="relative h-56 overflow-hidden rounded-md border border-border bg-[linear-gradient(to_right,hsl(var(--border)/.42)_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border)/.42)_1px,transparent_1px)] bg-[size:12.5%_25%]"><span className="absolute left-3 top-3 z-10 text-[10px] font-black text-muted-foreground">{label}</span>{children}</div>;
}

type FlawType = 'surface' | 'corner' | 'through';

export function FlawIdealizationLab() {
  const [type, setType] = useState<FlawType>('surface');
  const [depth, setDepth] = useState(1);
  const [halfLength, setHalfLength] = useState(3.2);
  const [spacing, setSpacing] = useState(5);
  const interact = spacing < 2 * halfLength;
  const effectiveC = interact ? halfLength * 2 + spacing / 2 : halfLength;
  const severity = type === 'through' ? effectiveC * 1.25 : depth * (1 + depth / effectiveC);
  return <LabFrame icon={<ScanSearch className="h-4 w-4" />} title="검사 indication을 해석 가능한 crack geometry로 바꾸기" status={interact ? 'INTERACTION RULE NEEDED' : 'GEOMETRY DECLARED'} danger={interact}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Analysis crack type" value={type} onChange={setType} options={[{ value: 'surface', label: '표면' }, { value: 'corner', label: '모서리' }, { value: 'through', label: '관통' }]} /><Range label="Depth a" value={depth} min={0.2} max={6} step={0.1} unit=" mm" onChange={setDepth} /><Range label="Half-length c" value={halfLength} min={0.5} max={10} step={0.1} unit=" mm" tone="teal" onChange={setHalfLength} /><Range label="Neighbor spacing" value={spacing} min={0.5} max={24} step={0.5} unit=" mm" tone="amber" onChange={setSpacing} /></div><div><div className="relative h-60 overflow-hidden rounded-md border border-border bg-muted/[0.035]"><div className="absolute inset-x-6 bottom-8 top-8 rounded-sm border border-border bg-background" /><svg role="img" aria-label={`${type} crack a ${depth} c ${effectiveC}`} viewBox="0 0 640 240" className="absolute inset-0 h-full w-full"><path d={type === 'through' ? `M ${320-effectiveC*16} 35 L ${320+effectiveC*16} 205` : `M ${320-effectiveC*15} 55 Q 320 ${55+depth*22} ${320+effectiveC*15} 55`} fill="none" stroke="#2563eb" strokeWidth="4" strokeLinecap="round" /><path d={`M ${320-effectiveC*15-spacing*4} 55 Q ${320-spacing*4} ${55+depth*18} ${320+effectiveC*15-spacing*4} 55`} fill="none" stroke={interact ? '#dc2626' : '#94a3b8'} strokeWidth="2" strokeDasharray="6 6" /><line x1="320" x2="320" y1="55" y2={55+depth*22} stroke="#d97706" strokeWidth="2" /><text x="328" y={75+depth*11} fontSize="12" fill="currentColor">a</text><line x1={320-effectiveC*15} x2={320+effectiveC*15} y1="44" y2="44" stroke="#0d9488" strokeWidth="2" /><text x="315" y="35" fontSize="12" fill="currentColor">2c</text></svg></div><div className="mt-4"><Status danger={interact}>{interact ? '인접 indication을 독립 crack 둘로 계산하면 interaction을 놓칠 수 있다. 먼저 approved interaction rule로 virtual crack을 만든다.' : 'Inspection pixels가 아니라 crack type, a, c, front, location and orientation이 analysis state다.'}</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{ label: 'Effective half-length', value: `${fmt(effectiveC, 1)} mm` }, { label: 'Aspect a/c', value: fmt(depth/effectiveC, 2) }, { label: 'Interaction', value: interact ? 'COMBINE' : 'SEPARATE' }, { label: 'Severity index', value: fmt(severity, 2), accent: !interact }]} /></div>
  </LabFrame>;
}

export function EnergyBalanceLab() {
  const [stress, setStress] = useState(120);
  const [crack, setCrack] = useState(2.4);
  const [resistance, setResistance] = useState(3.2);
  const E = 71e3;
  const G = Math.PI * stress ** 2 * (crack / 1000) / E * 1000;
  const unstable = G >= resistance;
  const releasePoints = Array.from({ length: 40 }, (_, index) => { const x = 28 + index * 14; const a = index / 39 * 8; const y = 200 - clamp(Math.PI*stress**2*(a/1000)/E*1000, 0, 8)/8*160; return `${x},${y}`; }).join(' ');
  const yR = 200 - clamp(resistance,0,8)/8*160;
  return <LabFrame icon={<ChartSpline className="h-4 w-4" />} title="균열이 늘며 방출하는 에너지와 재료 저항 비교" status={unstable ? 'EXTENSION ENERGETICALLY POSSIBLE' : 'RESISTANCE EXCEEDS DRIVE'} danger={unstable}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><Range label="Nominal stress" value={stress} min={30} max={260} step={5} unit=" MPa" onChange={setStress} /><Range label="Crack size a" value={crack} min={0.2} max={8} step={0.1} unit=" mm" tone="amber" onChange={setCrack} /><Range label="Crack resistance Gc" value={resistance} min={0.5} max={8} step={0.1} unit=" kJ/m²" tone="teal" onChange={setResistance} /></div><div><PlotShell label="에너지 방출률 G(a) / 저항 Gc"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={releasePoints} fill="none" stroke="#2563eb" strokeWidth="3" /><line x1="28" x2="574" y1={yR} y2={yR} stroke="#0d9488" strokeWidth="3" /><line x1={28+crack/8*546} x2={28+crack/8*546} y1="30" y2="203" stroke="#d97706" strokeWidth="2" strokeDasharray="5 5" /><circle cx={28+crack/8*546} cy={200-clamp(G,0,8)/8*160} r="6" fill="#fff" stroke={unstable?'#dc2626':'#2563eb'} strokeWidth="3" /></svg></PlotShell><div className="mt-4"><Status danger={unstable}>같은 stress라도 crack이 길어지면 방출 가능한 elastic energy가 커진다. Griffith의 지속되는 통찰은 바로 이 size effect이며, 1921 논문의 모든 계수와 분자 가설이 그대로 남은 것은 아니다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{ label: 'Driving G', value: `${fmt(G,2)} kJ/m²` }, { label: 'Resistance Gc', value: `${fmt(resistance,2)} kJ/m²` }, { label: 'G/Gc', value: fmt(G/resistance,2) }, { label: 'Energy state', value: unstable?'EXTEND':'ARREST', accent: !unstable }]} /></div>
  </LabFrame>;
}

type Mode = 'I' | 'II' | 'III';
export function CrackTipFieldLab() {
  const [mode, setMode] = useState<Mode>('I');
  const [K, setK] = useState(22);
  const [radius, setRadius] = useState(0.8);
  const sigma = K / Math.sqrt(2*Math.PI*(radius/1000));
  const glyph = mode === 'I' ? 'M170 115 L290 115 M170 100 L150 80 M170 130 L150 150 M290 100 L310 80 M290 130 L310 150' : mode === 'II' ? 'M170 115 L290 115 M160 92 L205 92 M160 92 L178 82 M300 138 L255 138 M300 138 L282 148' : 'M170 115 L290 115 M170 92 L150 70 M290 138 L310 160';
  return <LabFrame icon={<Activity className="h-4 w-4" />} title="Crack-tip mode와 elastic asymptote의 물리 경계" status="LOCAL FIELD, NOT PEAK STRESS">
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><SegmentedControl label="Crack-tip deformation mode" value={mode} onChange={setMode} options={[{ value: 'I', label: 'Mode I 열림' }, { value: 'II', label: 'Mode II 면내 전단' }, { value: 'III', label: 'Mode III 면외 전단' }]} /><Range label="Stress intensity K" value={K} min={4} max={60} unit=" MPa√m" onChange={setK} /><Range label="Distance from tip r" value={radius} min={0.1} max={6} step={0.1} unit=" mm" tone="amber" onChange={setRadius} /></div><div><div className="relative h-60 overflow-hidden rounded-md border border-border bg-muted/[0.035]"><svg role="img" aria-label={`Mode ${mode} crack-tip deformation`} viewBox="0 0 460 230" className="h-full w-full"><path d="M48 115 L230 115" stroke="#111827" strokeWidth="3" /><path d="M230 115 L412 115" stroke="#94a3b8" strokeWidth="1.5" strokeDasharray="5 5" /><circle cx="230" cy="115" r={clamp(radius*5,5,34)} fill="#d9770610" stroke="#d97706" strokeWidth="2" strokeDasharray="4 4" /><path d={glyph} stroke="#2563eb" strokeWidth="3" fill="none" strokeLinecap="round" /><text x="242" y="103" fontSize="11" fill="currentColor">r</text><text x="28" y="28" fontSize="11" fill="currentColor">elastic K-field</text><text x="285" y="210" fontSize="11" fill="currentColor">process / plastic zone inside</text></svg></div><div className="mt-4"><Status>`1/√r`는 crack tip 바깥의 leading elastic field다. r→0에서 계산값이 커지는 것은 실제 재료가 infinite stress를 가진다는 뜻이 아니라 plasticity and microstructure가 지배하는 내부 영역에 LEFM을 밀어 넣었다는 경고다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{ label: 'Mode', value: mode }, { label: 'Elastic field estimate', value: `${fmt(sigma/1000,1)} GPa` }, { label: 'Radius', value: `${fmt(radius,1)} mm` }, { label: 'Interpretation', value: 'ASYMPTOTIC', accent: true }]} /></div>
  </LabFrame>;
}

type Geometry = 'wide'|'finite'|'surface';
export function GeometryFactorLab() {
  const [geometry,setGeometry]=useState<Geometry>('surface');
  const [stress,setStress]=useState(145);
  const [crack,setCrack]=useState(2);
  const [ratio,setRatio]=useState(0.35);
  const Y=geometry==='wide'?1:geometry==='finite'?1/Math.sqrt(Math.max(Math.cos(Math.PI*ratio/2),.1)):1.12+0.55*ratio;
  const K=Y*stress*Math.sqrt(Math.PI*crack/1000);
  return <LabFrame icon={<Gauge className="h-4 w-4" />} title="Nominal stress를 geometry-aware crack driving force로 변환" status={K>35?'TOUGHNESS APPROACHING':'GEOMETRY CORRECTED'} danger={K>35}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.7fr)_minmax(0,1.3fr)]"><div className="space-y-5"><SegmentedControl label="Crack geometry" value={geometry} onChange={setGeometry} options={[{value:'wide',label:'넓은 판'},{value:'finite',label:'유한 폭'},{value:'surface',label:'표면'}]} /><Range label="Nominal stress" value={stress} min={30} max={280} step={5} unit=" MPa" onChange={setStress}/><Range label="Crack size a" value={crack} min={.2} max={8} step={.1} unit=" mm" tone="amber" onChange={setCrack}/><Range label="Geometry ratio" value={ratio} min={.05} max={.8} step={.05} unit="" tone="teal" onChange={setRatio}/></div><div><div className="grid gap-4 sm:grid-cols-[minmax(9rem,.8fr)_minmax(0,1.2fr)]"><div className="relative h-60 rounded-md border border-border bg-muted/[.035]"><div className="absolute inset-x-5 bottom-7 top-7 border border-border bg-background"/><div className="absolute left-1/2 top-7 w-1 -translate-x-1/2 bg-blue-600" style={{height:`${clamp(crack*18,8,135)}px`}}/><div className="absolute left-1/2 top-7 h-2 -translate-x-1/2 bg-amber-500" style={{width:`${clamp(ratio*160,12,125)}px`}}/><span className="absolute bottom-3 left-3 text-[10px] font-black">{geometry.toUpperCase()}</span></div><div className="grid content-start gap-px overflow-hidden rounded-md border border-border bg-border"><div className="bg-background p-4"><p className="text-[10px] font-black text-blue-700 dark:text-blue-300">NOMINAL LOAD</p><p className="mt-2 font-mono text-xl font-black">{stress} MPa</p></div><div className="bg-background p-4"><p className="text-[10px] font-black text-teal-700 dark:text-teal-300">GEOMETRY FACTOR</p><p className="mt-2 font-mono text-xl font-black">Y = {fmt(Y,3)}</p></div><div className="bg-background p-4"><p className="text-[10px] font-black text-violet-700 dark:text-violet-300">DRIVING FORCE</p><p className="mt-2 font-mono text-xl font-black">K = {fmt(K,1)} MPa√m</p></div></div></div><div className="mt-4"><Status danger={K>35}>Y는 보정용 장식 계수가 아니다. finite width, free surface, crack-front position, loading mode and stress gradient를 어떤 solution으로 모델링했는지의 압축된 흔적이다.</Status></div></div></div>
  </LabFrame>;
}

export function ConstraintToughnessLab(){
  const[thickness,setThickness]=useState(10); const[yieldStrength,setYield]=useState(430); const[Kic,setKic]=useState(32); const[Kapp,setKapp]=useState(26);
  const required=2.5*(Kic/yieldStrength)**2*1000; const constraint=thickness>=required?'plane-strain':thickness<required*.35?'plane-stress':'transition'; const usable=constraint==='plane-strain'?Kic:constraint==='transition'?Kic*1.18:Kic*1.35; const danger=Kapp>=usable;
  return <LabFrame icon={<CircleDot className="h-4 w-4"/>} title="Thickness constraint와 transferable toughness 구분" status={danger?'RESISTANCE EXCEEDED':constraint.toUpperCase()} danger={danger}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.7fr)_minmax(0,1.3fr)]"><div className="space-y-5"><Range label="Part thickness" value={thickness} min={2} max={80} unit=" mm" onChange={setThickness}/><Range label="Yield strength" value={yieldStrength} min={180} max={900} step={10} unit=" MPa" tone="teal" onChange={setYield}/><Range label="Lower-bound KIc" value={Kic} min={12} max={90} unit=" MPa√m" tone="violet" onChange={setKic}/><Range label="Applied K" value={Kapp} min={3} max={90} unit=" MPa√m" tone="amber" onChange={setKapp}/></div><div><PlotShell label="두께에 따른 apparent toughness / constraint"><svg viewBox="0 0 600 230" className="h-full w-full"><path d="M25 45 C160 45 235 85 320 130 S485 178 575 178" fill="none" stroke="#2563eb" strokeWidth="3"/><line x1={25+clamp(thickness/80,0,1)*550} x2={25+clamp(thickness/80,0,1)*550} y1="28" y2="202" stroke="#d97706" strokeWidth="2" strokeDasharray="5 5"/><line x1="25" x2="575" y1="178" y2="178" stroke="#0d9488" strokeWidth="2"/><text x="32" y="64" fontSize="11" fill="currentColor">얇음 · 낮은 constraint</text><text x="410" y="168" fontSize="11" fill="currentColor">KIc lower bound</text></svg></PlotShell><div className="mt-4"><Status danger={danger}>얇은 부품에서 더 큰 apparent Kc가 가능하다는 사실은 자동 credit가 아니다. Coupon thickness, crack-front constraint, orientation, temperature and process가 part와 맞는지 먼저 닫아야 한다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'Plane-strain screen',value:`${fmt(required,1)} mm`},{label:'Constraint',value:constraint},{label:'Usable resistance',value:`${fmt(usable,1)} MPa√m`},{label:'K margin',value:fmt(usable/Kapp-1,2),accent:!danger}]}/></div></LabFrame>
}

export function LefmValidityLab(){
  const[K,setK]=useState(28); const[yieldStrength,setYield]=useState(420); const[crack,setCrack]=useState(3); const[ligament,setLigament]=useState(18);
  const rpStress=1/(2*Math.PI)*(K/yieldStrength)**2*1000; const rpStrain=rpStress/3; const ratio=Math.max(rpStress/(crack),rpStress/ligament); const valid=ratio<.1;
  return <LabFrame icon={<Gauge className="h-4 w-4"/>} title="Plastic zone가 geometry scale보다 충분히 작은지 확인" status={valid?'SMALL-SCALE YIELDING SCREEN':'ELASTIC-PLASTIC HANDOFF'} danger={!valid}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.7fr)_minmax(0,1.3fr)]"><div className="space-y-5"><Range label="Applied K" value={K} min={5} max={75} unit=" MPa√m" onChange={setK}/><Range label="Yield strength" value={yieldStrength} min={150} max={900} step={10} unit=" MPa" tone="teal" onChange={setYield}/><Range label="Crack size" value={crack} min={.5} max={15} step={.5} unit=" mm" tone="amber" onChange={setCrack}/><Range label="Remaining ligament" value={ligament} min={2} max={60} unit=" mm" tone="violet" onChange={setLigament}/></div><div><div className="relative h-60 overflow-hidden rounded-md border border-border bg-muted/[.035]"><div className="absolute left-10 right-10 top-1/2 h-px bg-foreground"/><div className="absolute left-10 top-1/2 h-1 bg-blue-600" style={{width:`${clamp(crack/15*220,8,220)}px`}}/><div className={`absolute top-1/2 -translate-y-1/2 rounded-full border-2 ${valid?'border-amber-500 bg-amber-500/[.06]':'border-red-500 bg-red-500/[.06]'}`} style={{left:`${40+clamp(crack/15*220,8,220)-clamp(rpStress*2,5,85)}px`,width:`${clamp(rpStress*4,10,170)}px`,height:`${clamp(rpStress*4,10,170)}px`}}/><div className="absolute bottom-4 left-4 right-4 grid grid-cols-3 gap-px overflow-hidden rounded border border-border bg-border text-center text-[10px]"><div className="bg-background p-2">crack {fmt(crack,1)} mm</div><div className="bg-background p-2">plastic {fmt(rpStress,2)} mm</div><div className="bg-background p-2">ligament {ligament} mm</div></div></div><div className="mt-4"><Status danger={!valid}>여기서 0.1은 교육용 screening line이지 보편 표준이 아니다. Plastic zone가 crack, ligament, thickness or gradient scale과 경쟁하면 precise-looking LEFM result 대신 J-integral, elastic-plastic FAD, validated analysis or test가 필요하다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'Plane-stress rp',value:`${fmt(rpStress,2)} mm`},{label:'Plane-strain rp',value:`${fmt(rpStrain,2)} mm`},{label:'Worst scale ratio',value:fmt(ratio,3)},{label:'Model class',value:valid?'LEFM SCREEN':'EPFM / TEST',accent:valid}]}/></div></LabFrame>
}

export function ResidualStrengthLab(){
  const[crack,setCrack]=useState(2); const[Kmat,setKmat]=useState(35); const[Y,setY]=useState(1.18); const[service,setService]=useState(180);
  const residual=Kmat/(Y*Math.sqrt(Math.PI*crack/1000)); const danger=service>=residual; const points=Array.from({length:45},(_,i)=>{const a=.3+i/44*14.7;return `${28+i/44*546},${200-clamp((Kmat/(Y*Math.sqrt(Math.PI*a/1000)))/1000,0,1)*160}`}).join(' ');
  return <LabFrame icon={<ChartSpline className="h-4 w-4"/>} title="Crack state가 커질수록 남는 구조 강도 추적" status={danger?'RESIDUAL STRENGTH EXCEEDED':'SERVICE BELOW RESIDUAL'} danger={danger}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><Range label="Current crack a" value={crack} min={.3} max={15} step={.1} unit=" mm" onChange={setCrack}/><Range label="Material resistance" value={Kmat} min={15} max={90} unit=" MPa√m" tone="teal" onChange={setKmat}/><Range label="Geometry Y" value={Y} min={.8} max={2.2} step={.02} tone="violet" onChange={setY}/><Range label="Service stress" value={service} min={30} max={650} step={10} unit=" MPa" tone="amber" onChange={setService}/></div><div><PlotShell label="Residual strength σres(a)"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="3"/><line x1="28" x2="574" y1={200-clamp(service/1000,0,1)*160} y2={200-clamp(service/1000,0,1)*160} stroke="#d97706" strokeWidth="2"/><line x1={28+(crack-.3)/14.7*546} x2={28+(crack-.3)/14.7*546} y1="28" y2="202" stroke={danger?'#dc2626':'#0d9488'} strokeWidth="2" strokeDasharray="5 5"/></svg></PlotShell><div className="mt-4"><Status danger={danger}>Critical crack and residual strength are the same equation solved in opposite directions. Surface crack가 자라면 Y and a/c도 바뀌므로 이 plot의 constant-Y curve는 baseline, not final trajectory다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'Residual strength',value:`${fmt(residual,0)} MPa`},{label:'Service stress',value:`${service} MPa`},{label:'Stress ratio',value:fmt(service/residual,2)},{label:'State',value:danger?'UNSTABLE':'RESIDUAL MARGIN',accent:!danger}]}/></div></LabFrame>
}

export function CrackGrowthLab(){
  const[dK,setDK]=useState(12); const[R,setR]=useState(.2); const[environment,setEnvironment]=useState<'dry'|'marine'>('dry'); const[Kc,setKc]=useState(42);
  const threshold=(environment==='dry'?5.5:3.2)*(1-.25*R); const Kmax=dK/(1-R); const rate= dK<=threshold?1e-10:1.2e-11*(dK*(environment==='marine'?1.25:1))**3.1/Math.max(1-Kmax/Kc,.08); const region=dK<=threshold?'THRESHOLD':Kmax>Kc*.8?'INSTABILITY':'PARIS-LIKE'; const danger=Kmax>=Kc;
  const curve=useMemo(()=>Array.from({length:54},(_,i)=>{const x=2+i/53*40;const y=x<5?1e-10:1.2e-11*x**3.1/Math.max(1-x/45,.08);return `${28+i/53*546},${205-clamp((Math.log10(y)+10)/7,0,1)*170}`}).join(' '),[]);
  return <LabFrame icon={<ChartSpline className="h-4 w-4"/>} title="Threshold·Paris-like·instability를 하나의 growth curve에서 구분" status={danger?'KMAX ≥ KMAT':region} danger={danger}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><SegmentedControl label="Environment" value={environment} onChange={setEnvironment} options={[{value:'dry',label:'건조 공기'},{value:'marine',label:'염화물 노출'}]}/><Range label="ΔK" value={dK} min={1} max={38} step={.5} unit=" MPa√m" onChange={setDK}/><Range label="Load ratio R" value={R} min={-.5} max={.8} step={.05} tone="teal" onChange={setR}/><Range label="Instability resistance" value={Kc} min={18} max={90} unit=" MPa√m" tone="amber" onChange={setKc}/></div><div><PlotShell label="log(da/dN) vs ΔK"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={curve} fill="none" stroke="#2563eb" strokeWidth="3"/><line x1={28+(dK-1)/37*546} x2={28+(dK-1)/37*546} y1="28" y2="205" stroke={danger?'#dc2626':'#d97706'} strokeWidth="2" strokeDasharray="5 5"/><text x="34" y="195" fontSize="10" fill="currentColor">threshold</text><text x="255" y="112" fontSize="10" fill="currentColor">Paris-like</text><text x="485" y="52" fontSize="10" fill="currentColor">instability</text></svg></PlotShell><div className="mt-4"><Status danger={danger}>Paris `C(ΔK)^n`은 중간 regime의 local model이다. R, closure, environment, threshold and Kmax/Kc를 지우고 양 끝까지 외삽하면 remaining life가 정밀해 보여도 물리 범위가 틀린다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'ΔK threshold',value:`${fmt(threshold,1)} MPa√m`},{label:'Kmax',value:`${fmt(Kmax,1)} MPa√m`},{label:'Growth rate',value:`${rate.toExponential(2)} m/cycle`},{label:'Regime',value:region,accent:!danger}]}/></div></LabFrame>
}

export function SpectrumHistoryLab(){
  const[order,setOrder]=useState<'overload-first'|'overload-last'>('overload-first'); const[credit,setCredit]=useState(false); const[cycles,setCycles]=useState(24000); const[base,setBase]=useState(10);
  const overload=1.8; const nominal=cycles*1.1e-8*base**2.8; const factor=credit&&order==='overload-first'?.62:order==='overload-first'?1.08:1.22; const growth=nominal*factor; const history=order==='overload-first'?[.95,.28,.32,.3,.27,.34,.3]:[.28,.32,.3,.27,.34,.3,.95];
  return <LabFrame icon={<Activity className="h-4 w-4"/>} title="같은 cycle 집합도 sequence model에 따라 다른 crack state 생성" status={credit?'RETARDATION CREDIT EXPLICIT':'NO RETARDATION CREDIT'}><div className="p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><SegmentedControl label="Spectrum order" value={order} onChange={setOrder} options={[{value:'overload-first',label:'Overload → service'},{value:'overload-last',label:'Service → overload'}]}/><button type="button" aria-pressed={credit} onClick={()=>setCredit(v=>!v)} className="min-h-9 rounded border border-border bg-muted/20 px-3 text-xs font-semibold">{credit?'검증된 retardation ON':'Retardation credit OFF'}</button></div><div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1.25fr)_minmax(0,.75fr)]"><div><div className="space-y-5"><Range label="Service cycles" value={cycles} min={2000} max={80000} step={2000} onChange={setCycles}/><Range label="Base ΔK" value={base} min={4} max={22} step={.5} unit=" MPa√m" tone="teal" onChange={setBase}/></div><PlotShell label="ORDERED LOAD HISTORY"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={history.flatMap((v,i)=>{const x=32+i*82;return [`${x},${115-v*76}`,`${x+38},${115+v*76}`,`${x+76},${115-v*76}`]}).join(' ')} fill="none" stroke="#2563eb" strokeWidth="3"/></svg></PlotShell></div><div className="grid content-start gap-px overflow-hidden rounded-md border border-border bg-border"><div className="bg-background p-4"><p className="text-[10px] font-black text-blue-700 dark:text-blue-300">SAME HISTOGRAM</p><p className="mt-2 text-xs leading-relaxed">Service cycles and one {overload}× overload는 두 ordering에서 같다.</p></div><div className="bg-background p-4"><p className="text-[10px] font-black text-violet-700 dark:text-violet-300">STATEFUL RESULT</p><p className="mt-2 font-mono text-xl font-black">Δa {fmt(growth,3)} mm</p></div><div className="bg-background p-4"><Status>Retardation credit는 편리한 안전 여유가 아니다. Sequence-aware model, material data and representative spectrum evidence가 있을 때만 켠다.</Status></div></div></div></div></LabFrame>
}

export function FadLab(){
  const[primary,setPrimary]=useState(55); const[secondary,setSecondary]=useState(18); const[Kmat,setKmat]=useState(45); const[limit,setLimit]=useState(130);
  const Lr=primary/limit; const Kr=(primary*.48+secondary*.62)/Kmat; const boundary=Math.max((1-.14*Lr**2)*(0.3+0.7*Math.exp(-.65*Lr**6)),0); const danger=Kr>=boundary||Lr>=1.5;
  const fal=Array.from({length:50},(_,i)=>{const lr=i/49*1.5;const kr=Math.max((1-.14*lr**2)*(.3+.7*Math.exp(-.65*lr**6)),0);return `${35+lr/1.5*530},${200-kr*160}`}).join(' ');
  return <LabFrame icon={<Gauge className="h-4 w-4"/>} title="Fracture ratio와 plastic-collapse ratio를 같은 assessment point로 결합" status={danger?'OUTSIDE FAILURE ASSESSMENT LINE':'ASSESSMENT POINT INSIDE'} danger={danger}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><Range label="Primary mechanical load" value={primary} min={5} max={180} step={5} unit=" kN" onChange={setPrimary}/><Range label="Residual / thermal K-equivalent" value={secondary} min={0} max={65} unit="" tone="amber" onChange={setSecondary}/><Range label="Fracture resistance Kmat" value={Kmat} min={15} max={100} unit=" MPa√m" tone="teal" onChange={setKmat}/><Range label="Plastic limit load" value={limit} min={50} max={260} step={5} unit=" kN" tone="violet" onChange={setLimit}/></div><div><PlotShell label="FAILURE ASSESSMENT DIAGRAM"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={fal} fill="none" stroke="#0d9488" strokeWidth="3"/><polygon points={`${fal} 565,200 35,200`} fill="#0d94880a"/><line x1={35+clamp(Lr/1.5,0,1)*530} x2={35+clamp(Lr/1.5,0,1)*530} y1="35" y2="202" stroke="#94a3b8" strokeDasharray="4 5"/><circle cx={35+clamp(Lr/1.5,0,1)*530} cy={200-clamp(Kr,0,1.2)*160} r="7" fill="#fff" stroke={danger?'#dc2626':'#2563eb'} strokeWidth="3"/><text x="38" y="216" fontSize="10" fill="currentColor">Lr: plastic collapse →</text><text x="39" y="32" fontSize="10" fill="currentColor">Kr: fracture ↑</text></svg></PlotShell><div className="mt-4"><Status danger={danger}>Primary load는 K and limit-load coordinates 모두 움직인다. Residual/thermal secondary stress는 K에 영향을 주어도 같은 방식으로 collapse load를 만들지 않는다. 이 분류를 섞으면 FAD point가 물리적으로 다른 뜻을 갖는다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'Kr',value:fmt(Kr,3)},{label:'Lr',value:fmt(Lr,3)},{label:'FAL at Lr',value:fmt(boundary,3)},{label:'Assessment',value:danger?'FAIL':'INSIDE',accent:!danger}]}/></div></LabFrame>
}

export function NdeInspectionLab(){
  const[detect50,setDetect50]=useState(1.1); const[scatter,setScatter]=useState(.35); const[orientation,setOrientation]=useState(85); const[current,setCurrent]=useState(.55); const[growth,setGrowth]=useState(.12);
  const qualified=detect50+1.65*scatter+(100-orientation)/100; const critical=5.2; const window=critical-qualified; const interval=Math.max((critical-current)/growth/4,0); const danger=qualified>=critical||current>=critical;
  const curve=Array.from({length:50},(_,i)=>{const a=i/49*6;const pod=1/(1+Math.exp(-(a-detect50)/(Math.max(scatter,.05))));return `${28+i/49*546},${200-pod*160}`}).join(' ');
  return <LabFrame icon={<ScanSearch className="h-4 w-4"/>} title="POD capability를 assumed flaw와 observable inspection window로 연결" status={danger?'NO USABLE DETECTION WINDOW':'DETECTION WINDOW EXISTS'} danger={danger}><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.68fr)_minmax(0,1.32fr)]"><div className="space-y-5"><Range label="50% detection size" value={detect50} min={.2} max={3.5} step={.1} unit=" mm" onChange={setDetect50}/><Range label="Detection scatter" value={scatter} min={.1} max={1.2} step={.05} unit=" mm" tone="teal" onChange={setScatter}/><Range label="Probe orientation/access" value={orientation} min={35} max={100} unit="%" tone="amber" onChange={setOrientation}/><Range label="Current assumed flaw" value={current} min={.1} max={5.5} step={.05} unit=" mm" tone="violet" onChange={setCurrent}/><Range label="Predicted growth per life" value={growth} min={.02} max={.6} step={.01} unit=" mm" tone="amber" onChange={setGrowth}/></div><div><PlotShell label="PROBABILITY OF DETECTION / FLAW SIZE"><svg viewBox="0 0 600 230" className="h-full w-full"><polyline points={curve} fill="none" stroke="#2563eb" strokeWidth="3"/><line x1={28+qualified/6*546} x2={28+qualified/6*546} y1="30" y2="202" stroke="#d97706" strokeWidth="2" strokeDasharray="5 5"/><line x1={28+critical/6*546} x2={28+critical/6*546} y1="30" y2="202" stroke="#dc2626" strokeWidth="2"/><text x={clamp(18+qualified/6*546,30,500)} y="45" fontSize="10" fill="currentColor">qualified initial flaw</text><text x={clamp(18+critical/6*546,30,525)} y="195" fontSize="10" fill="currentColor">critical</text></svg></PlotShell><div className="mt-4"><Status danger={danger}>“No indication”은 “no crack”이 아니다. Qualified method가 실제 geometry, surface/volume access and orientation에서 분석이 가정한 flaw를 90/95 capability로 screen할 수 있어야 analysis initial state와 inspection이 연결된다.</Status></div></div></div><div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={[{label:'Qualified flaw',value:`${fmt(qualified,2)} mm`},{label:'Critical flaw',value:`${fmt(critical,1)} mm`},{label:'Observable window',value:`${fmt(window,2)} mm`},{label:'Screen interval',value:`${fmt(interval,1)} life units`,accent:!danger}]}/></div></LabFrame>
}

type Evidence = 'geometry'|'load'|'material'|'growth'|'inspection'|'identity';
export function FractureEvidenceLab(){
  const[focus,setFocus]=useState<Evidence>('geometry'); const[closed,setClosed]=useState<Record<Evidence,boolean>>({geometry:true,load:true,material:false,growth:false,inspection:true,identity:false});
  const items:Record<Evidence,{label:string;claim:string;next:string}>={geometry:{label:'Crack geometry',claim:'a/c, front, interaction and transition',next:'Replica/CT/sectioning or conservative virtual crack'},load:{label:'Load spectrum',claim:'primary, residual, thermal, order and dwell',next:'Time-synchronized strain/load acquisition'},material:{label:'Material resistance',claim:'lot, orientation, thickness, temperature and environment',next:'Representative KIc and da/dN coupon program'},growth:{label:'Growth model',claim:'SIF solution, closure/retardation and solver version',next:'Benchmark hand solution plus second solver'},inspection:{label:'NDE capability',claim:'method, access, orientation and 90/95 POD',next:'Representative flaw demonstration'},identity:{label:'Part identity',claim:'serial, process, repair and inspection history',next:'Configuration-controlled fracture ledger'}};
  const count=Object.values(closed).filter(Boolean).length; const ready=count===6;
  return <LabFrame icon={<ShieldCheck className="h-4 w-4"/>} title="Model·test·NDE·configuration을 같은 fracture-control ledger로 닫기" status={ready?'TRACEABLE DECISION':'EVIDENCE GAPS REMAIN'} danger={!ready}><div className="p-4 sm:p-6"><SegmentedControl label="Evidence layer" value={focus} onChange={setFocus} options={(Object.keys(items) as Evidence[]).map(value=>({value,label:items[value].label}))}/><div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.12fr)_minmax(0,.88fr)]"><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{(Object.keys(items) as Evidence[]).map(key=><button key={key} type="button" aria-pressed={closed[key]} onClick={()=>{setFocus(key);setClosed(state=>({...state,[key]:!state[key]}))}} className={`min-w-0 bg-background p-4 text-left ${focus===key?'ring-2 ring-inset ring-blue-500':''}`}><span className={`text-[10px] font-black ${closed[key]?'text-teal-700 dark:text-teal-300':'text-amber-700 dark:text-amber-300'}`}>{closed[key]?'EVIDENCE LINKED':'OPEN GAP'}</span><p className="mt-2 text-sm font-black">{items[key].label}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{items[key].claim}</p></button>)}</div><div className="grid content-start gap-px overflow-hidden rounded-md border border-border bg-border"><div className="bg-background p-4"><p className="text-[10px] font-black text-blue-700 dark:text-blue-300">SELECTED CLAIM</p><p className="mt-2 text-sm font-semibold leading-relaxed">{items[focus].claim}</p></div><div className="bg-background p-4"><p className="text-[10px] font-black text-teal-700 dark:text-teal-300">NEXT FALSIFYING EVIDENCE</p><p className="mt-2 text-sm leading-relaxed">{items[focus].next}</p></div><div className="bg-background p-4"><Status danger={!ready}>{ready?'계산 결과를 특정 part identity, inspection capability and approved evidence에 재현 가능하게 연결했다.':`${count}/6 layers closed. Green FAD point 하나만으로 release decision을 닫지 않는다.`}</Status></div></div></div></div></LabFrame>
}
