import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { TendermintLockTraceViz, TendermintRoundViz } from "./viz/ModernTendermintViz";

export default function ModernTendermintArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">Tendermint consensus를 처음부터</p><h2 className="text-3xl font-bold tracking-tight">한 block height에서 propose·prevote·precommit을 반복하며 lock으로 충돌을 막는다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">Tendermint는 알려진 validator 집합이 매 block height마다 하나의 block을 결정하는 round-based Byzantine consensus입니다. Validator는 key 개수가 아니라 voting power로 투표하며, 같은 round에서 특정 block에 전체 power의 2/3를 초과하는 precommit이 모이면 그 block을 commit합니다.</p>
      <p>Height는 결정할 block 위치이고 round는 그 height에서 proposer를 바꾸며 다시 시도하는 번호입니다. Step은 Propose, Prevote, Precommit, Commit처럼 현재 기다리는 evidence를 나타냅니다. Network가 느리거나 proposer가 offline이면 timeout으로 다음 step·round에 갈 수 있지만, timeout은 상대가 Byzantine이라는 증명도, 이전 lock을 지우는 권한도 아닙니다. 이 일반 원리의 정본은 <a className="text-primary underline-offset-4 hover:underline" href="/blockchain/bft-theory#safety-liveness">BFT lock·partial synchrony</a>에 있고 현재 CometBFT 구현의 event loop는 <a className="text-primary underline-offset-4 hover:underline" href="/blockchain/cometbft-consensus#overview">CometBFT consensus</a>에서 이어집니다.</p>
      <TendermintRoundViz />
      <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> prevote quorum은 “이 round에서 lock을 만들거나 바꿀 수 있는 근거”를 만들고, precommit quorum은 block을 결정합니다. Round가 올라가도 honest validator의 lock은 더 높은 round의 정당한 prevote evidence 없이는 바뀌지 않습니다.</aside>
    </section>

    <section id="protocol" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · Protocol</p><h2 className="mt-2 text-2xl font-bold">Block vote와 nil vote가 같은 round machine을 전진시킨다</h2></header>
      <p>Propose step에서 정해진 proposer가 block을 보냅니다. Validator는 현재 lock과 양립하고 application이 proposal을 유효하다고 판단하면 그 block을 prevote합니다. Proposal을 받지 못했거나 invalid하고 안전한 locked block도 없다면 nil을 prevote합니다. Nil은 빈 block을 commit한다는 뜻이 아니라 “현재 evidence로 특정 block을 지지하지 않는다”는 typed vote입니다.</p>
      <p>같은 (height, round)에서 block B에 +2/3 prevote를 보면 validator는 B에 lock하거나 relock하고 B를 precommit합니다. +2/3 nil prevote를 보면 nil을 precommit하고 다음 round 진행을 준비합니다. 같은 round B에 +2/3 precommit이 모이면 commit으로 갑니다. Vote sign bytes에는 chain ID, height, round, vote type과 BlockID를 묶어 다른 chain·round·phase의 signature를 재사용하지 못하게 해야 합니다.</p>
      <ExplainedFormula question="Voting power가 제각각일 때 block commit certificate가 threshold를 넘었는지 어떻게 판정하는가?" idea={<>Certificate의 distinct valid signers가 membership snapshot에서 가진 power를 더합니다. ‘2/3 이상’으로 반올림하지 않고 CometBFT 문서의 +2/3, 즉 전체 power의 2/3를 엄격히 초과하는지 정수 비교합니다.</>} formula={String.raw`3W_{signed}>2W_{total}`} terms={[{symbol:"W_{signed}",name:"Signed voting power",description:"같은 chain·height·round·precommit type·BlockID에 유효하게 서명한 validators의 power 합입니다."},{symbol:"W_{total}",name:"Total voting power",description:"해당 height를 검증하는 historical validator-set snapshot의 전체 power입니다."},{symbol:"3,2",name:"Integer comparison",description:"부동소수점 2/3와 rounding 대신 양변을 정수로 비교합니다."}]} assumptions={["Validator를 중복 세지 않고 해당 historical membership과 power를 사용합니다.","Signature, sign bytes, vote type, height·round와 BlockID를 검증합니다.","Byzantine voting power가 전체의 1/3 미만이라는 safety envelope를 둡니다.","Membership update의 적용 height와 proposer priority는 별도 versioned state입니다."]} interpretation="Total power 100이면 signed 67은 201>200이라 threshold를 넘지만 66은 198>200이 아니므로 부족합니다. Key 80개가 서명해도 power 합이 60이면 commit certificate가 아닙니다." />
      <div id="paper-tendermint-original"><CitationBlock source="Jae Kwon — Tendermint: Consensus without Mining" citeKey={1} href="https://tendermint.com/static/docs/tendermint.pdf"><p><strong>문제:</strong> PoW mining 없이 blockchain ledger에 BFT finality를 제공합니다.</p><p><strong>기여:</strong> Partial synchrony와 1/3 미만 Byzantine power 아래 round-based blockchain consensus 초기 설계를 제시했습니다.</p><p><strong>전제와 범위:</strong> 2014 draft v0.6의 역사적 설계 근거이며 문서 자체가 outdated임을 밝힙니다. 현재 CometBFT wire·ABCI++·state transition의 정본으로 사용하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="locking" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · Locking</p><h2 className="mt-2 text-2xl font-bold">Higher-round PoLC가 있어야 다른 block으로 lock을 옮길 수 있다</h2></header>
      <p>Proof of Lock Change(PoLC, 흔히 polka)는 같은 height·round에서 특정 block 또는 nil에 대한 +2/3 prevote 집합입니다. Validator가 r0에서 A의 PoLC를 보고 A를 precommit했다면 A에 lockedRound=0을 기록합니다. r1 proposer가 아무 근거 없이 B를 보내도 이 validator는 A를 prevote합니다. B로 바꾸려면 lockedRound보다 높은 round에서 B의 PoLC를 확인해야 합니다.</p>
      <TendermintLockTraceViz />
      <p>이 규칙이 필요한 이유를 n=4,f=1에서 볼 수 있습니다. A의 +2/3 precommit에는 power 기준 quorum이 참여했고, 충돌하는 B의 quorum도 honest power를 공유해야 합니다. 그 honest validator가 낮거나 근거 없는 round에서 lock을 버리지 않으므로 두 block이 같은 height에 commit되는 경로를 끊습니다. 다만 실제 safety proof는 proposal의 validRound/POLRound, vote gossip, round jump와 lock update 조건 전체를 사용하므로 위 한 문단을 구현 specification으로 대신할 수 없습니다.</p>
      <div id="paper-cometbft-consensus"><CitationBlock source="CometBFT v0.38 Specification — Byzantine Consensus Algorithm" citeKey={2} href="https://docs.cometbft.com/v0.38/spec/consensus/consensus"><p><strong>문제:</strong> Height·round·step별 proposal, prevote, precommit, commit과 round 전환 조건을 구현 가능한 상태 machine으로 규정합니다.</p><p><strong>기여:</strong> +2/3, PoLC, lock/unlock, common exit와 timeout semantics를 명시합니다.</p><p><strong>전제와 범위:</strong> 링크한 v0.38 specification의 의미입니다. 최신 main이나 다른 release의 정확한 code path는 배포 version·SHA와 다시 대조해야 합니다.</p></CitationBlock></div>
    </section>

    <section id="comparison" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · Liveness와 운영</p><h2 className="mt-2 text-2xl font-bold">Safety는 GST 전에도, progress는 network가 안정된 뒤 조건부로 검사한다</h2></header>
      <p>Partial synchrony에서 Global Stabilization Time(GST) 전에는 message delay 상한을 알 수 없으므로 여러 rounds가 timeout될 수 있습니다. Protocol은 이 구간에서 conflicting commit을 만들지 않는 safety를 지켜야 합니다. GST 뒤 message가 timeout 안에 전달되고 충분한 honest power가 online이며 proposal이 valid하고 proposer가 적절한 round에 오면 prevote·precommit quorum이 형성되어 liveness가 회복됩니다.</p>
      <p>Timeout을 짧게 잡으면 정상 jitter에서도 round가 자주 바뀌고, 길게 잡으면 실제 proposer 장애 회복이 느립니다. Round가 올라갈수록 timeout을 늘리는 정책은 unknown delay bound를 찾아가는 운영 근사지만 무한한 liveness를 보장하지 않습니다. 1/3 이상 power가 offline이면 safety가 깨지지 않더라도 +2/3 certificate를 만들 수 없어 chain이 멈춥니다. 1/3 이상 Byzantine power라는 fault-bound 위반에서는 정규 safety 보장을 주장하지 않습니다.</p>
      <div className="overflow-x-auto rounded-lg border border-border"><table className="min-w-[760px] w-full text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">주입 사건</th><th className="p-3">기대 동작</th><th className="p-3">검증 evidence</th></tr></thead><tbody className="divide-y divide-border text-muted-foreground"><tr><td className="p-3 font-medium text-foreground">Proposer offline</td><td className="p-3">nil vote·timeout 뒤 round 증가</td><td className="p-3">H/R/S trace·proposer·timeout receipt</td></tr><tr><td className="p-3 font-medium text-foreground">Stale conflicting proposal</td><td className="p-3">Lock 유지·unsafe prevote 거절</td><td className="p-3">lockedBlock·lockedRound·POLRound</td></tr><tr><td className="p-3 font-medium text-foreground">Minority partition</td><td className="p-3">Minority commit 불가, majority 조건부 진행</td><td className="p-3">Historical power와 signed sums</td></tr><tr><td className="p-3 font-medium text-foreground">1/3+ offline</td><td className="p-3">정지 허용, conflict 금지</td><td className="p-3">No commit·no conflicting state·recovery time</td></tr></tbody></table></div>
      <p>Tendermint algorithm, 현재 CometBFT consensus engine, ABCI++ application은 같은 말이 아닙니다. Consensus가 block order를 정해도 application의 non-deterministic transition이나 external payment를 exactly-once로 만들지 않습니다. Version-pinned consensus와 deterministic state hash parity를 확인하고 external effects는 outbox·idempotency receipt로 따로 조정해야 합니다.</p>
      <h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 height·round·step, block/nil prevote, strict +2/3 power 계산, commit, lock·PoLC, timeout을 다룹니다. 심화 4문제는 stale proposal safety trace, GST 전후 liveness, 1/3 power boundary, version-pinned failure release gate를 설계하게 합니다.</p>
    </section>
  </article>;
}
