import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import FirmwareRecoveryViz from "./firmware-update-and-recovery/viz/FirmwareRecoveryViz";

import NumericPath from "../world-systems/NumericPath";
import TeachCode from "./firmware-update-and-recovery/TeachCode";

export default function FirmwareUpdateAndRecoveryArticle(){
return <div className="space-y-16">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 새 프로그램이 고장 나도 이전 프로그램으로 돌아오려면</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">센서를 읽던 장치에 새 프로그램을 넣습니다. 파일을 받는 중 전원이 끊길 수 있고 새 프로그램이 시작된 뒤 센서를 못 읽을 수도 있습니다. 장치가 다시 켜졌을 때 무엇을 실행할지 정해 두어야 합니다.</p><p className="leading-7">
            기존 프로그램을 남겨 두고 새 프로그램을 시험한 뒤 정상 동작을 확인하는 교체를 따라가겠습니다. 어느 시점의 기록이 다음 부팅을 바꾸는지도 살펴봅니다.
          </p></div></section>

<section id="outside" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 새 파일과 현재 상태를 보고 다음에 실행할 버전을 고릅니다</h2><NumericPath title="프로그램 교체의 입구와 출구" steps={[{"label": "입력", "value": "현재 v1·새 파일 v2", "detail": "파일을 다 받았는지와 믿을 수 있는 파일인지 확인합니다."}, {"label": "보관과 시험", "value": "v1을 보존하고 v2 실행", "detail": "실제 센서 기능까지 확인합니다."}, {"label": "결과", "value": "정상 v2 유지 또는 v1 복귀", "detail": "다음 시작 때 사용할 버전과 그 근거를 남깁니다."}]} /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">새 파일을 받은 기록과 정상 동작을 확인한 기록은 서로 다릅니다. 다운로드 완료만으로 이전 버전을 버리면 새 버전의 기능 실패에서 돌아올 길이 사라집니다.</p></div></section>

<section id="case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. v2가 센서를 못 읽으면 확정하지 않고 v1로 돌아갑니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">가상의 장치에는 4 MiB 저장 공간과 프로그램 두 개를 둘 자리가 있습니다. 지금 v1이 센서를 정상적으로 읽습니다. 다른 자리에 v2를 완전히 받고 검사한 뒤 시험 실행합니다. 그런데 v2는 센서 읽기에 실패합니다.</p><p className="leading-7">이 제품은 센서 검사에 실패하면 새 버전을 확정하지 않고 재시작하도록 설계했다고 둡니다. 다시 켜졌을 때 확정되지 않은 시험 기록을 보고 v1을 복원합니다. 부팅 코드가 센서 실패를 저절로 알아채는 것은 아닙니다. 검사와 재시작은 제품의 동작입니다.</p><p className="leading-7">반대로 센서 읽기와 설정·주기 작업 검사를 통과하면 v2를 확정합니다. 그 뒤 재시작해도 v2를 사용합니다. 두 경우의 차이는 파일 이름보다 시험 뒤 남긴 기록입니다.</p></div></section>

<section id="picture" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 옛 파일을 지키는 자리와 새 파일을 시험하는 순서를 나눕니다</h2><NumericPath title="같은 v1→v2 요청의 경로" steps={[{"label": "보관", "value": "현재 v1을 유지", "detail": "v2는 별도 자리에 받습니다."}, {"label": "검사", "value": "완성·손상·서명 확인", "detail": "검사에 실패하면 v2를 시험 대상으로 표시하지 않습니다."}, {"label": "시험", "value": "v2의 실제 제품 기능 확인", "detail": "돌아올 수 있게 v1을 다른 자리에 남깁니다."}, {"label": "확정 또는 복귀", "value": "다음 부팅의 선택 기록", "detail": "정상이면 v2를 확정하고 미확정 재시작이면 v1로 돌아갑니다."}]} /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">
            파일을 옮기는 도중에도 전원이 끊길 수 있습니다. 어느 조각을 어디까지 옮겼는지 남겨 두어야 다시 켜졌을 때 이어서 교체할 수 있습니다. 마지막 성공 표시만으로 중간 복사가
            복구되지는 않습니다.
          </p></div></section>

<section id="why" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 두 자리가 있어도 검사와 진행 기록이 없으면 복구할 수 없습니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">새 파일을 현재 프로그램 위에 바로 덮어쓰다 전원이 끊기면 양쪽 모두 완성된 프로그램이 아닐 수 있습니다. 별도 저장 자리는 완성된 v1을 남기는 데 필요합니다.</p><p className="leading-7">파일이 다 도착해도 잘못 만들어진 v2일 수 있습니다. 파일의 손상·출처 검사와 센서 기능 검사는 다른 질문에 답합니다. 기능 확인 전에 영구 사용을 결정하면 정상적으로 서명된 고장 프로그램도 계속 실행할 수 있습니다.</p><p className="leading-7">전원이 끊기면 작업 중이던 메모리 내용은 사라집니다. 다음 부팅에서도 읽을 수 있는 곳에 교체 진행과 확정 여부를 남겨야 합니다. 그 기록 자체의 쓰기 단위와 전원 차단 중 동작도 저장 장치에 맞춰 확인해야 합니다.</p></div></section>

<section id="names" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 보관 자리·시험·확정·되돌리기에 이름을 붙입니다</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">앞에서 본 역할</th><th className="p-3">이름</th></tr></thead><tbody><tr><td className="p-3">장치에서 실행하는 프로그램 묶음</td><td className="p-3">펌웨어 이미지</td></tr><tr><td className="p-3">앱보다 먼저 실행할 버전을 정함</td><td className="p-3">부트로더</td></tr><tr><td className="p-3">평소 앱을 실행하는 자리</td><td className="p-3">주 슬롯 primary</td></tr><tr><td className="p-3">새 후보 또는 복귀할 옛 앱을 보관</td><td className="p-3">보조 슬롯 secondary</td></tr><tr><td className="p-3">두 슬롯의 내용을 맞바꿈</td><td className="p-3">swap</td></tr><tr><td className="p-3">한 번 시험할 교체</td><td className="p-3">TEST</td></tr><tr><td className="p-3">제품 검사를 통과했다는 확정 기록</td><td className="p-3">image OK</td></tr><tr><td className="p-3">미확정 시험 뒤 옛 앱으로 돌아감</td><td className="p-3">REVERT</td></tr><tr><td className="p-3">슬롯 뒤쪽의 상태 기록 영역</td><td className="p-3">트레일러</td></tr></tbody></table></div><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이제 실제 부트로더 구현인 MCUboot를 보겠습니다. 이 글은 v2.2.0의 scratch 공간을 쓰는 swap 방식을 고릅니다. scratch는 조각을 잠깐 보관하는 별도 공간입니다. 가상 RP2040 제품에 이를 이식했다고 두며 내장 ROM이 자동 제공하는 기능으로 보지는 않습니다.</p></div></section>

<section id="layout" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. 4 MiB 안에 두 이미지와 복구 공간을 함께 잡습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">가상 외부 플래시 4 MiB는 4096 KiB입니다. 부트·복구 코드 256 KiB, 현재 앱 슬롯 1536 KiB, 후보 앱 슬롯 1536 KiB를 두면 설정·교체 보조 공간으로 768 KiB가 남습니다. 256+1536+1536+768=4096입니다. 이미지 슬롯의 머리말·서명·꼬리말과 플래시 지우기 단위도 자리에서 빠지므로 실제 앱 파일의 최대 크기는 1536 KiB보다 작습니다.</p>
   <p className="leading-7">RP2040은 외부 QSPI 플래시를 XIP로 읽습니다. 칩 안 부트 ROM은 외부 플래시의 다음 부팅 단계를 찾고 USB BOOTSEL 복구 경로도 제공합니다. 이 하드웨어 경로 위에 두 앱 슬롯, 검증 키, 시험·확정 상태를 기록하는 사용자 부트로더와 메모리 배치가 추가로 필요합니다.</p>
   <p className="leading-7"><em>두 번째 앱을 보관할 자리를 먼저 남겨야 현재 앱을 쓰는 동안 후보를 받을 수 있습니다.</em></p>
  </div><FirmwareRecoveryViz /><ExplainedFormula question="가상 4 MiB 플래시에서 두 앱 슬롯 뒤 남는 공간은?" idea="전체 KiB에서 부트·복구와 두 이미지 슬롯을 뺍니다." formula={String.raw`R=F-B-2S`} annotatedFormula={String.raw`\underbrace{R}_{\text{남는 공간}}=F-B-2S`} operations={[{expression:String.raw`F=4\times1024=4096\,\mathrm{KiB}`,annotation:"4 MiB를 KiB로 바꿉니다."},{expression:String.raw`2S=2\times1536=3072\,\mathrm{KiB}`,annotation:"현재·후보 두 슬롯입니다."},{expression:String.raw`R=4096-256-3072=768`,annotation:"설정·교체 보조 영역으로 남기는 가정입니다."}]} terms={[{symbol:"F",name:"외부 플래시 전체",description:"가상 4096 KiB입니다."},{symbol:"B",name:"부트·복구 영역",description:"가상 256 KiB입니다."},{symbol:"S",name:"앱 슬롯 하나",description:"가상 1536 KiB입니다."},{symbol:"R",name:"기타 영역",description:"가상 768 KiB입니다."}]} assumptions={["4 MiB 플래시와 네 구획 크기는 교육용 가정입니다.","정렬·이미지 헤더·트레일러로 실제 저장 가능 크기는 줄어듭니다."]} interpretation="가상 배치의 나머지는 768 KiB입니다. 앱 두 개가 각각 1536 KiB까지 꽉 찬다는 뜻은 아닙니다." /><CitationBlock source="Raspberry Pi, RP2040 Datasheet, XIP flash·Bootrom, 원본 123·129–132·145쪽" citeKey={1} href="https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf">공식 데이터시트는 외부 QSPI 플래시 XIP, 다음 부팅 단계의 검사, USB BOOTSEL 경로를 설명합니다. 4 MiB와 두 앱 슬롯·자동 되돌리기는 본문에서 가정한 제품 설계입니다.</CitationBlock><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이번 scratch 방식에서는 기타 768 KiB 안에서 교체용 임시 공간을 따로 할당해야 합니다. 임시 공간은 교체할 가장 큰 지우기 구간을 담을 만큼 커야 합니다. 768 KiB 전체가 자유로운 사용자 설정 공간이라는 뜻은 아닙니다. 같은 크기의 두 슬롯·지우기 경계·상태 기록 공간을 실제 플래시 맵에서 맞춥니다.</p></div></section>

<section id="verify" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. v2를 다 받은 뒤 무결성과 출처를 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">v1을 그대로 둔 채 후보 슬롯에 v2를 내려받습니다. 도중에 전원이 끊겨 후보가 불완전하면 시험 부팅 상태로 표시하지 않고 v1을 계속 실행합니다. 다운로드가 끝났다면 이미지 길이와 해시로 손상을 확인하고 신뢰된 공개 키로 서명을 검증합니다. 신뢰한 기대 해시와 비교하면 손상을 찾을 수 있습니다. 공격자가 파일과 기대 해시를 함께 바꿀 수 있다면 해시 일치만으로 출처가 확인되지는 않습니다. 서명 검증이 실패하면 후보를 사용하지 않습니다.</p>
   <p className="leading-7">다운로드 프로토콜, 키를 신뢰할 수 있게 보관하는 방법, 버전·보안 카운터 정책은 제품에서 별도로 정해야 합니다. 후보를 받았다는 사실과 부팅해도 된다는 판단은 서로 다른 상태입니다.</p>
   <p className="leading-7"><em>후보가 완전히 기록되고 검증되기 전에는 작동 중인 v1을 버리지 않습니다.</em></p>
  </div><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">시험 요청을 기록하는 API와 이미지의 서명 검증은 서로 다른 동작입니다. 앱에서 먼저 검사하더라도 부트로더의 실제 이미지 검증 경로가 올바르게 구성되어 있어야 합니다. 아래 상태 표는 어떤 교체를 요청하는지 설명하며 그 자체가 서명을 검증하지는 않습니다.</p></div></section>

<section id="trial" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. v2는 한 번 시험하고 실제 기능을 본 뒤 확정합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">MCUboot의 <strong>swap 방식 시험 업데이트</strong>에서는 유효한 후보를 시험 상태로 표시하면 부트로더가 이미지를 교체해 v2를 실행합니다. 이전 v1은 되돌릴 수 있도록 다른 슬롯에 남습니다. v2가 센서 읽기, 설정 로드, 주기 작업 시작 같은 제품 자가 검사를 통과하면 앱이 이미지 OK를 기록해 v2를 확정합니다. 다음 부팅에도 v2가 유지됩니다.</p>
   <p className="leading-7">v2가 부팅만 하고 자가 검사에 실패하거나 확정 기록 전에 재시작하면, 이 시험·되돌리기 모드에서는 다음 부팅에 v1로 돌아갑니다. 업그레이드를 처음부터 영구로 표시하는 모드나 단순 덮어쓰기 방식에서는 같은 결과를 기대할 수 없습니다. 어느 업데이트 방식을 설정했는지 알아야 합니다.</p>
   <p className="leading-7"><em>‘CPU가 v2로 점프했다’와 ‘v2가 제품 기능을 정상 수행했다’는 확정 기준이 다릅니다.</em></p>
  </div><CitationBlock source="MCUboot, Bootloader design, image swapping·trailers·high-level operation" citeKey={2} href="https://docs.mcuboot.com/design.html">MCUboot 공식 설계 문서는 시험(TEST), 확정(PERM), 되돌리기(REVERT), 이미지 OK 상태와 서명·무결성 검사, 중단된 교체의 재개를 설명합니다. 본문은 그중 시험 swap 방식을 선택한 설계 사례입니다.</CitationBlock><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이번 실패 사례에서는 앱이 센서 실패를 확인해 재시작합니다. 앱이 멈춰 버릴 수 있다면 감시 타이머 같은 재시작 수단도 설계해야 합니다. 다음 부팅이 시작되어야 부트로더가 미확정 상태를 읽고 되돌리기를 수행합니다.</p></div></section>

<section id="power" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 전원이 끊기는 위치마다 돌아오는 경로가 다릅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">다운로드 도중 끊기면 후보 슬롯이 불완전하므로 v1을 유지합니다. 이미 시험 교체를 시작했다가 끊기면 MCUboot의 지원되는 swap 구현은 기록된 교체 상태를 읽어 중단된 작업을 재개합니다. v2를 시험 실행하다 확정 전에 끊기면 다음 부팅에서 v1로 되돌립니다. 확정이 끝난 뒤 재시작하면 v2가 남습니다.</p>
   <p className="leading-7">
            이 네 지점을 실험으로 끊어 보는 것이 설계 검증입니다. 옛 취약 버전의 설치를 제한하는 정책과 서명 키 관리도 함께 정합니다. 14절에서 시험 복귀와 이 정책이 충돌하는
            경우를 살펴봅니다. 복구용 BOOTSEL USB 진입은 현장 작업자가 다시 플래시를 쓰는 경로가 될 수 있지만 자동 앱 되돌리기와는 역할이 다릅니다. 외부 플래시가 고장 났거나
            부트 코드 자체가 손상된 경우의 복구 정책도 따로 필요합니다.
          </p>
   <p className="leading-7"><em>복구가 된다는 주장은 ‘어느 단계에서 전원을 끊었는가’까지 시험해야 의미가 있습니다.</em></p>
  </div></section>

<section id="source-state" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 실제 상태 표에 v2 시험과 미확정 재시작을 넣습니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">MCUboot v2.2.0 commit 2d61c318의 bootutil_public.c는 슬롯의 기록을 읽어 boot_swap_tables와 순서대로 비교합니다. 여기의 GOOD·SET·UNSET은 읽은 기록을 해석한 상태 이름입니다. 저장소의 임의 바이트에 true나 false를 쓰라는 뜻이 아닙니다.</p><p className="leading-7">scratch swap을 선택했으므로 offset 방식 전용 첫 항목은 제외됩니다. 보조 슬롯의 요청이 주 슬롯의 되돌리기 조건보다 먼저 검사됩니다. 아래 표는 새 요청이 없는 정상 교체 완료 상태까지 가정해 같은 v1·v2를 대입한 것입니다.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">시점</th><th className="p-3">주 슬롯 상태</th><th className="p-3">보조 슬롯 상태</th><th className="p-3">결과</th></tr></thead><tbody><tr><td className="p-3">v2 시험 요청 뒤</td><td className="p-3">v1, 기존 정상 기록</td><td className="p-3">v2, magic GOOD·image_ok UNSET</td><td className="p-3">TEST</td></tr><tr><td className="p-3">v2 교체 완료·미확정</td><td className="p-3">v2, magic GOOD·copy_done SET·image_ok UNSET</td><td className="p-3">v1, magic UNSET</td><td className="p-3">REVERT</td></tr><tr><td className="p-3">v2 교체 완료·확정</td><td className="p-3">v2, magic GOOD·copy_done SET·image_ok SET</td><td className="p-3">v1, magic UNSET</td><td className="p-3">NONE: v2 사용</td></tr></tbody></table></div><TeachCode codeKey="state" label="시험·영구 교체·되돌리기를 고르는 실제 표" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">미확정 줄은 주 슬롯의 완료 표시가 있고 정상 확인 표시가 없으므로 REVERT 항목과 맞습니다. 확정 뒤에는 이 항목과 맞지 않고 새 후보 요청도 없으므로 교체하지 않는 NONE으로 갑니다.</p><p className="leading-7">
            보조 슬롯에 처음부터 image_ok SET을 기록하면 PERM 항목이 먼저 맞습니다. 이는 v2의 제품 검사가 끝난 뒤 확정하는 이번 절차와 구분되는 요청입니다. 시험하려면
            처음에는 영구 요청으로 표시하지 않아야 합니다.
          </p></div></section>

<section id="source-api" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 이미지 묶음 0을 시험 표시한 뒤 정상 앱에서 확정합니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">boot_set_pending_multi(0, 0)의 첫 0은 이미지 묶음 번호이고 둘째 0은 영구 사용하지 않고 시험하겠다는 뜻입니다. v2라는 버전 이름의 2를 이 인자에 넣는 것이 아닙니다. 원문은 보조 슬롯을 열고 active=false·confirm=false로 boot_set_next를 부릅니다.</p></div><TeachCode codeKey="pending" label="보조 슬롯을 시험 대상으로 표시하는 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">보조 슬롯의 magic이 UNSET인 새 요청에서는 magic을 기록하고 TEST swap 정보를 씁니다. confirm이 false이므로 image OK는 쓰지 않습니다. 반환값 0을 확인해야 기록 요청의 성공을 알 수 있습니다. 이 호출만으로 파일 복사나 센서 검사가 수행되지는 않습니다.</p></div><TeachCode codeKey="set-next" label="시험 요청과 image OK 기록이 갈리는 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">정상 v2가 제품 검사를 마친 뒤 boot_set_confirmed_multi(0)를 부르면 이번에는 주 슬롯을 열고 active=true·confirm=true로 들어갑니다. 정상 magic과 미설정 image_ok 상태에서 boot_write_image_ok를 호출합니다. 확정 쓰기가 실패했다면 성공으로 간주하지 않고 반환값과 제품 정책에 따라 처리합니다.</p></div><TeachCode codeKey="confirm" label="실행 중인 주 슬롯을 확정하는 원문" /></section>

<section id="source-copy" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 한 조각도 새 내용 보관·옛 내용 이동·새 내용 배치 순으로 바꿉니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">swap_scratch.c의 한 구간을 보면 먼저 보조 슬롯의 v2 조각을 scratch에 복사합니다. 그다음 주 슬롯의 v1 조각을 보조 슬롯으로 옮깁니다. 마지막으로 scratch의 v2 조각을 주 슬롯에 씁니다. 각 단계 뒤에는 boot_write_status로 진행을 기록합니다.</p></div><NumericPath title="한 조각의 내용 이동" steps={[{"label": "처음", "value": "주=v1 · 보조=v2", "detail": "두 조각 모두 아직 제자리에 있습니다."}, {"label": "새 조각 보관", "value": "scratch=v2", "detail": "보조 자리를 지워도 새 조각이 남습니다."}, {"label": "옛 조각 보존", "value": "보조=v1", "detail": "주 자리를 지우기 전에 돌아갈 조각을 남깁니다."}, {"label": "새 조각 배치", "value": "주=v2 · 보조=v1", "detail": "진행을 기록하고 다음 조각으로 넘어갑니다."}]} /><TeachCode codeKey="copy" label="세 복사와 진행 기록의 실제 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">다시 켜졌을 때 swap_read_status_bytes는 지워지지 않은 진행 기록의 위치를 읽어 조각 번호와 단계를 복원합니다. RAM 변수만 기억했다가 재부팅 때 처음부터 덮어쓰는 구조가 아닙니다. 트레일러가 겹치는 마지막 구간과 기록 손상에는 원문의 별도 분기가 적용됩니다.</p></div><TeachCode codeKey="resume" label="중단 뒤 기록에서 조각·단계를 복원하는 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이 순서를 코드로 대조한 것과 실제 전원 차단 시험은 다릅니다. 플래시 드라이버의 지우기·쓰기 동작과 기록 단위가 전제에 맞는지 확인하고 각 복사·상태 쓰기 전후에서 실제로 전원을 끊어 보아야 합니다.</p></div><CitationBlock source="MCUboot v2.2.0 · commit 2d61c318 · bootutil_public.c·swap_scratch.c" citeKey={3} href="https://github.com/mcu-tools/mcuboot/tree/2d61c318933819a0f4954fb2a5a957a62c6128ce/boot/bootutil/src">전체 원본과 Apache 2.0 라이선스를 보존하고 TEST→미확정 REVERT 또는 확정 NONE을 상태 표에 대입했습니다. 복사·진행 기록 순서를 읽었으며 실제 제품의 전원 차단 복구를 실행한 결과는 아닙니다.</CitationBlock></section>

<section id="security-policy" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. 정상 복귀와 오래된 취약 버전 차단을 함께 정합니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">고장난 v2에서 검토한 v1로 돌아가는 기능과 공격자가 취약한 옛 버전을 강제로 설치하는 것은 구분해야 합니다. 허용할 버전과 보안 카운터를 정하고 서명 키 교체·폐기 정책도 함께 설계합니다.</p><p className="leading-7">보안 카운터를 올리는 시점이 복귀할 v1을 거부하게 만들면 시험 실패 시 돌아갈 수 없습니다. 선택한 MCUboot 설정과 카운터 저장 구현이 언제 값을 갱신하는지 확인해야 합니다. 모든 제품에서 시험 시작 순간에 올리면 된다고 일반화할 수 없습니다.</p><p className="leading-7">신뢰할 공개 키와 부트로더 자체를 공격자가 바꿀 수 있다면 서명 검사만 추가해도 기대한 신뢰가 생기지 않습니다. RP2040 기반 제품에서 외부 플래시·물리 접근을 어떤 위협으로 다룰지 정하고 키와 부팅 경로를 그 조건에 맞춰 보호해야 합니다.</p></div></section>

<section id="limits" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">15. 이 설계는 제품의 플래시·부팅·보안 조건에 맞춰야 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">RP2040 보드에 이 구조가 내장돼 있다고 볼 수 없습니다. 외부 플래시의 용량·지우기 단위·쓰기 중 코드 실행 제약, 사용자 부트로더 이식, 공개 키 신뢰 경로와 서명 키 관리, 확정 기록의 내구성을 제품 조건에 맞춰 검증해야 합니다. 오래된 버전으로의 보안상 위험과 고장난 v2에서 v1로 되돌아갈 필요도 함께 정책으로 정합니다.</p>
   <p className="leading-7"><strong>읽고 나서 예측해 보세요.</strong> 가상 4 MiB에서 기타 공간은? (답: 7절) v2가 시험 부팅 뒤 확정되지 않으면? (답: 9·11절) 다운로드 중과 교체 중 전원 차단의 처리가 왜 다릅니까? (답: 8·10·13절)</p>
   <p className="leading-7"><Link to="/electronics/embedded/scheduling-and-real-time#limits">앞 글의 제때 동작하는 펌웨어</Link>는 새 버전으로 바뀐 뒤에도 자가 검사와 마감 검증을 다시 받아야 합니다.</p>
  </div></section>
</div>;
}
