import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import TimerSamplingViz from "./timers-and-sampling/viz/TimerSamplingViz";
import NumericPath from "../world-systems/NumericPath";
import TeachCode from "./timers-and-sampling/TeachCode";

export default function TimersAndSamplingArticle(){
return <div className="space-y-16">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 시간표대로 남긴 값이 원래 움직임을 모두 알려 주지는 않습니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">
            장치가 바깥 신호를 일정한 간격으로 읽어 숫자를 저장합니다. 이 기록으로 원래 움직임을 알아내려면 두 가지를 알아야 합니다. 실제로 언제 읽었는지, 읽는 사이에 신호가 얼마나
            빠르게 바뀔 수 있는지입니다.
          </p><p className="leading-7">10 ms마다 값을 남기는 한 사례를 따라가겠습니다. 서로 다른 두 신호가 같은 숫자를 남기는 이유를 먼저 보고, 실제 SDK의 다음 시각 계산과 한 번 읽기 함수에 이 시간표를 적용합니다.</p></div></section>

<section id="outside" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 계속 바뀌는 전압이 시각과 숫자의 목록으로 바뀝니다</h2><NumericPath title="입력에서 기록까지" steps={[{"label": "바깥 입력", "value": "시간에 따라 변하는 전압", "detail": "신호는 장치가 읽지 않는 사이에도 바뀝니다."}, {"label": "읽는 장치", "value": "10 ms마다 한 값", "detail": "읽기로 정한 시각과 실제로 읽은 시각을 구별합니다."}, {"label": "남은 기록", "value": "시각·숫자의 목록", "detail": "목록만으로 원래 입력을 구분할 수 있는지 확인합니다."}]} /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">기록에 붙인 시간표만 일정하고 실제 읽기는 들쭉날쭉할 수도 있습니다. 또 실제로 정확한 간격을 지켰더라도, 너무 빠른 신호는 다른 느린 신호와 같은 목록을 만들 수 있습니다.</p></div></section>

<section id="case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 10 ms 간격에서 두 신호는 2.65·1.341·0.841 V를 함께 남깁니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">입력을 1.65 V 중심에서 1 V만큼 위아래로 움직이는 부드러운 파형으로 가정합니다. 값의 범위는 0.65–2.65 V입니다. 한 신호는 1초에 30번, 다른 신호는 70번 반복하며 둘 다 처음에 가장 높은 값에서 시작합니다. 전압과 연결, 반복 횟수는 설명용 <strong>가정</strong>입니다.</p><p className="leading-7">0·10·20 ms에서 이상적으로 읽으면 두 신호 모두 약 2.65·1.341·0.841 V를 남깁니다. 입력은 다르게 움직였는데 기록은 같습니다. 읽는 간격은 0.01초이므로 1초에 100개의 눈금이 있습니다. 아래에서 이 겹침을 식과 원문으로 확인합니다.</p><p className="leading-7">실제 RP2040에 연결할 때는 디지털 입출력 전원과 입력 허용 범위도 맞아야 합니다. 이 예는 그 전원을 3.3 V로 가정한 수학적 입력입니다. 실제 변환값에는 유한한 해상도와 잡음이 있으므로 위 전압 목록을 보드 실측값으로 읽지 않습니다.</p></div></section>

<section id="picture" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 목표 시각·실제 읽기·저장된 값을 나눠 봅니다</h2><NumericPath title="같은 10 ms 목표의 경로" steps={[{"label": "시간표", "value": "다음 목표 10000 µs", "detail": "읽어야 할 시각을 먼저 정합니다."}, {"label": "처리 시작", "value": "늦게 깨어나면 10400 µs", "detail": "다른 작업 때문에 기다릴 수 있습니다."}, {"label": "값 잡기", "value": "입력에서 숫자 만들기", "detail": "준비와 변환이 끝나야 결과를 읽습니다."}, {"label": "저장", "value": "실제 시각과 결과 함께 남기기", "detail": "지연을 숨긴 고정 시간표만 붙이지 않습니다."}]} /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">위 그림의 400 µs 늦음은 가정입니다. 앞 절에서 두 신호가 정확히 겹친 계산은 실제 읽기 시각도 0·10·20 ms인 이상적 조건을 사용했습니다. 그 조건이 달라졌는지 확인하려고 실제 시각을 따로 남깁니다.</p></div></section>

<section id="why" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 다음 약속을 늦은 처리 시각에 붙이면 시간표가 밀립니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">10000 µs에 할 일을 10400 µs에 시작했다고 합시다. 원래 간격을 유지하려면 다음 목표는 20000 µs입니다. 매번 늦게 깨어난 시각에서 다시 10000 µs를 기다리면 20400 µs가 되어 지연이 다음 시간표에 쌓입니다. 실제 처리 시간까지 더하면 그만큼 더 밀립니다.</p><p className="leading-7">읽기 간격을 관리하는 이유는 같은 기록을 비교하기 위해서입니다. 그러나 간격만 맞추면 모든 신호를 구별할 수 있다는 뜻은 아닙니다. 앞의 30번·70번 반복처럼, 눈금 사이의 움직임을 제한하지 않으면 둘 다 같은 기록의 원인이 될 수 있습니다.</p></div></section>

<section id="names" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 시간표·한 번 읽기·겹침에 이름을 붙입니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">일정한 눈금을 세고 목표 시각에 알리는 장치를 <strong>타이머</strong>, 연속 전압을 숫자로 바꾸는 장치를 <strong>ADC</strong>, 정한 시각에 값을 하나 얻는 동작을 <strong>샘플링</strong>이라고 합니다.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">앞에서 본 역할</th><th className="p-3">이름과 이 사례</th></tr></thead><tbody><tr><td className="p-3">두 읽기 사이 간격</td><td className="p-3">샘플 주기 10 ms</td></tr><tr><td className="p-3">1초 동안 읽는 횟수</td><td className="p-3">샘플 빈도 100 Hz</td></tr><tr><td className="p-3">실제 읽기 시각의 흔들림</td><td className="p-3">지터</td></tr><tr><td className="p-3">서로 다른 신호가 같은 기록을 만드는 겹침</td><td className="p-3">앨리어싱</td></tr><tr><td className="p-3">입력의 가장 높은 성분에 필요한 경계</td><td className="p-3">샘플 빈도의 절반 50 Hz</td></tr></tbody></table></div></section>

<section id="timer" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. RP2040 타이머의 1 µs 눈금에서 10 ms는 10000칸입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">RP2040의 시스템 타이머는 64비트 계수기를 1 µs마다 올리고 네 개의 비교 알람을 제공합니다. 가상 주기 10 ms는 10000 µs이므로 알람 목표는 0, 10000, 20000, 30000 µs처럼 이어집니다. 비교 목표 시각과 실제 처리 함수 진입 시각은 다를 수 있습니다. 인터럽트 대기나 다른 작업이 끼면 CPU가 늦게 반응합니다.</p>
   <p className="leading-7">목표 10000 µs의 처리가 10400 µs에 시작해도 다음 목표를 20000 µs로 두면 원래 눈금에 맞춥니다. 매번 처리한 시각에 10000 µs를 더해 20400 µs로 잡으면 늦은 만큼 위상이 밀립니다. 마감을 놓쳤을 때 건너뛸지 복구할지는 장치의 측정 목적에 맞게 정해야 합니다.</p>
   <p className="leading-7"><em>주기의 기준은 이전 목표 시각이지, 늦게 깨어난 시각이 아닙니다.</em></p>
  </div><CitationBlock source="Raspberry Pi, RP2040 Datasheet, Timer, build 3184e62-clean · §4.6.1–4.6.3, 인쇄 534–535쪽" citeKey={1} href="https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf">공식 데이터시트는 1 µs 단위 64비트 타이머, 네 알람과 비교 인터럽트를 설명합니다. 10 ms 주기와 400 µs 지연은 본문의 가상 일정입니다.</CitationBlock><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">공식 표에서 전체 계수기는 64비트이지만 네 하드웨어 알람의 비교는 하위 32비트를 사용합니다. 따라서 단일 비교 목표의 범위와 장기 시간 기록을 혼동하지 않습니다. 이 글의 10000 µs 간격은 그 범위 안의 짧은 시간표입니다.</p></div></section>

<section id="adc" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 알람이 울린 뒤에도 ADC가 값을 잡는 시간이 필요합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">RP2040의 ADC 입력 0은 GPIO26에 연결됩니다. ADC 클록을 48 MHz로 맞춘 조건에서 공식 데이터시트의 단일 변환은 96주기, 약 2 µs입니다. 이 2 µs는 ADC 변환 자체의 시간입니다. 알람에서 처리 함수가 시작되기까지의 지연, 입력 회로 안정화, 소프트웨어가 결과를 읽고 저장하는 시간은 포함하지 않습니다.</p>
   <p className="leading-7">가상 구현은 알람에서 일을 예약하고, ADC 준비 상태를 확인한 뒤 한 번 변환해 결과를 기록합니다. 신호가 빠르게 바뀐다면 <strong>알람 목표</strong>와 <strong>실제 샘플 시각</strong>을 함께 기록해야 시간 오차를 분석할 수 있습니다. 단순히 데이터 배열에 10 ms 간격의 시간표만 적으면 지터를 감춥니다.</p>
   <p className="leading-7"><em>타이머가 1 µs 눈금이라고 해서 샘플 시각의 오차가 1 µs 이하라는 뜻은 아닙니다.</em></p>
  </div><CitationBlock source="Raspberry Pi, RP2040 Datasheet, SAR ADC, build 3184e62-clean · §4.9.2·§4.9.2.1, 인쇄 559쪽" citeKey={2} href="https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf">공식 문서는 GPIO26/ADC0, 48 MHz ADC 클록에서 96주기 약 2 µs의 변환과 결과 레지스터를 설명합니다. CPU 알람과 센서 회로까지의 전체 시간은 별도입니다.</CitationBlock><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">데이터시트는 아날로그 입력의 허용 전압이 ADC 전원만으로 정해지지 않고 디지털 입출력 전원 IOVDD에도 제한된다고 명시합니다. 앞의 0.65–2.65 V는 이 전원도 3.3 V로 둔 가정입니다. 음수까지 움직이는 코사인 수학식을 그대로 핀에 넣으라는 지시가 아닙니다.</p></div></section>

<section id="rate" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 10 ms 간격은 초당 100개, 절반 경계는 50 Hz입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">샘플 간격 T<sub>s</sub>=0.01 s라면 빈도 f<sub>s</sub>=1/T<sub>s</sub>=100 Hz입니다. 이상적으로 대역이 제한된 신호를 왜곡 없이 복원하려면 입력의 가장 높은 주파수가 이 빈도의 절반인 50 Hz보다 낮아야 합니다. 가상의 30 Hz 성분은 이 조건 아래입니다. 실제로는 경계에 걸치는 신호, 필터의 완만한 전이 구간, 시각 지터를 고려해 여유를 둡니다.</p>
   <p className="leading-7">주파수 조건은 ADC의 변환 능력과도 다릅니다. RP2040 ADC가 이 조건에서 한 값을 2 µs에 변환할 수 있어도, 프로그램이 10 ms마다 한 값만 남기면 최종 샘플 빈도는 100 Hz입니다.</p>
   <p className="leading-7"><em>ADC의 최대 변환 속도보다 실제로 저장한 값의 간격이 이 분석의 기준입니다.</em></p>
  </div></section>

<section id="alias" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 70 Hz 코사인은 100 Hz 눈금에서 30 Hz와 같은 값을 남깁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">중심 전압을 빼고 1 V로 나눈 순수한 가상 코사인 파형을 0, 0.01, 0.02 s…에서 읽어 봅니다. 70 Hz의 n번째 값은 cos(2π·70n/100)이고, 30 Hz는 cos(2π·30n/100)입니다. 70=100−30이고 cos(2πn−θ)=cos θ이므로 정수 n의 샘플은 완전히 같습니다. 디지털 값만 보면 원래가 30 Hz인지 70 Hz인지 구분할 수 없습니다.</p>
   <p className="leading-7">70 Hz 성분이 ADC에 들어오기 전에 아날로그 낮은 주파수 통과 필터로 충분히 줄여야 합니다. 샘플링 뒤에 디지털 필터를 걸어도 이미 30 Hz로 겹친 두 원인을 분리할 수 없습니다. 이 사례는 연속 입력이 코사인이고 정확히 100 Hz로 샘플된다는 가정에 따른 것입니다.</p>
   <p className="leading-7"><em>나중에 계산을 더 많이 해도 서로 같은 샘플을 만든 두 파형의 출처는 복원할 수 없습니다.</em></p>
  </div><TimerSamplingViz /><ExplainedFormula question="100 Hz로 읽은 70 Hz 성분은 어떤 낮은 주파수로 보입니까?" idea="샘플 빈도와 입력 성분의 차이가 절반 경계 아래에 접혀 들어옵니다." formula={String.raw`f_a=|f_s-f|`} annotatedFormula={String.raw`\underbrace{f_a}_{\text{겹쳐 보이는 빈도}}=|f_s-f|`} operations={[{expression:String.raw`f_s=1/0.01=100\,\mathrm{Hz}`,annotation:"10 ms마다 하나를 남깁니다."},{expression:String.raw`f_N=100/2=50\,\mathrm{Hz}`,annotation:"이상적인 절반 경계입니다."},{expression:String.raw`f_a=|100-70|=30\,\mathrm{Hz}`,annotation:"70 Hz가 30 Hz 샘플과 겹칩니다."}]} terms={[{symbol:"fₛ",name:"샘플 빈도",description:"실제로 저장한 값은 초당 100개입니다."},{symbol:"f",name:"입력 성분",description:"가정한 70 Hz 코사인입니다."},{symbol:"fₐ",name:"겹쳐 보이는 빈도",description:"이 사례에서 30 Hz입니다."}]} assumptions={["등간격 100 Hz의 이상적인 점 샘플을 가정합니다.","입력은 순수한 70 Hz 코사인 성분입니다."]} interpretation="70 Hz와 30 Hz 코사인은 이 100 Hz 샘플 시각에서 같은 값을 남깁니다." /><CitationBlock source="MIT OpenCourseWare RES.6-007, Lecture 16, ‘Sampling’ (2011), 원본 1–2쪽" citeKey={3} href="https://ocw.mit.edu/courses/res-6-007-signals-and-systems-spring-2011/8708ec068ebdea2c4ee2f38fad39fb83_MITRES_6_007S11_lec16.pdf">MIT 공식 강의는 샘플 빈도의 절반을 넘는 입력 성분이 낮은 빈도로 겹쳐 보이는 앨리어싱을 설명합니다. 100·70·30 Hz는 본문에서 만든 예제입니다.</CitationBlock></section>

<section id="source-clock" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 실제 반복 함수는 지연의 부호로 다음 목표의 기준을 고릅니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">Pico SDK 2.2.0, 고정 commit a1438dff의 time.c를 읽습니다. 등록 시 delay_us에 −10000을 넣으면 첫 목표는 현재 시각에 절댓값 10000을 더해 잡습니다. 반복 상태에 부호 있는 지연을 보관하며 콜백이 true를 반환한 경우 그 값을 다음 계산에 사용합니다. 여기서는 등록 시각을 0으로 둡니다. 반환값이 false이면 알람 등록에 실패했으므로 정상 시간표가 생겼다고 가정하지 않습니다.</p></div><TeachCode codeKey="register" label="반복 시간표를 등록하는 실제 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이제 이전 목표 earliest_target=10000에 늦게 도착해 10400 µs부터 처리하고 20 µs를 쓴다고 가정합니다. 음수 지연 분기는 next_time=earliest_target−delta이므로 10000−(−10000)=20000입니다. 양수 +10000 분기는 콜백이 끝난 뒤의 현재 시각 10420에 더하므로 20420이 됩니다. 같은 지연 크기도 기준 시각에 따라 결과가 다릅니다.</p></div><TeachCode codeKey="reschedule" label="이전 목표와 현재 시각을 나누는 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">이 함수의 콜백은 알람 풀의 인터럽트 경로에서 실행됩니다. 콜백에서 긴 일을 기다리면 다른 알람도 영향을 받습니다. 실제 측정까지 일반 작업에 넘겼다면 작업이 시작되는 지연도 따로 세어야 합니다. 목표를 유지하는 음수 지연이 누락된 과거 샘플을 되살리지는 않습니다.</p></div></section>

<section id="source-sample" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 같은 입력을 읽는 adc_read는 시작 비트를 쓰고 완료를 기다립니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">
            ADC 하드웨어를 초기화하고 adc_gpio_init(26)으로 해당 핀의 디지털 출력·당김·입력 수신 기능을 끈 뒤, adc_select_input(0)으로 GPIO26에
            연결된 채널을 고른 상태를 가정합니다. 실제 adc_read 원문은 CS.START_ONCE를 세우고 CS.READY가 다시 1이 될 때까지 기다린 뒤 RESULT를
            반환합니다. 이는 입력을 새로 변환하여 결과를 반환하는 함수입니다.
          </p></div><TeachCode codeKey="read" label="한 번 변환을 시작하고 기다리는 실제 원문" /><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">데이터시트 §4.9.2.1은 START_ONCE 이후 READY가 낮아졌다가 ADC 클록 96주기 뒤 높아진다고 설명합니다. 48 MHz 조건에서 96/48000000초=2 µs입니다. CPU가 함수를 부르는 데 걸린 시간, 알람 대기, 결과 저장은 이 나눗셈에 포함되지 않습니다. 변환 시작 전후의 소프트웨어 시각도 정확한 아날로그 포착 순간과 자동으로 같다고 가정하지 않습니다.</p></div><CitationBlock source="Pico SDK 2.2.0 · a1438dff · time.c·time.h·adc.h" citeKey={4} href="https://github.com/raspberrypi/pico-sdk/blob/a1438dff1d38bd9c65dbd693f0e5db4b9ae91779/src/common/pico_time/time.c">전체 고정 원문과 라이선스를 보존하고 −10000 µs의 일정과 ADC0의 한 번 읽기를 해당 함수에 대입했습니다. 보드에서 실행한 실측 결과는 아닙니다.</CitationBlock></section>

<section id="source-model" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 원문의 복원 조건에 같은 100·30·70 Hz를 넣습니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">MIT Sampling 강의의 첫 두 쪽은 입력의 가장 높은 주파수보다 샘플 빈도가 두 배 넘게 커야 한다는 조건을 둡니다. 같은 조건을 만족하는 대역 안의 신호로 복원해야 원래 입력과 같아집니다. 샘플에 맞는 파형이 하나뿐이라는 주장은 입력 범위의 제한과 함께 성립합니다.</p><p className="leading-7">이 사례에서 100&gt;2×30은 성립하지만 100&gt;2×70은 성립하지 않습니다. 첫 여섯 정규화 값은 두 신호 모두 약 1, −0.309, −0.809, 0.809, 0.309, −1입니다. 1.65 V를 더하는 같은 변환을 거치면 2.65, 1.341, 0.841, 2.459, 1.959, 0.65 V가 됩니다. 따라서 동일한 전압 기록의 원인을 디지털 계산만으로 둘 중 하나로 확정할 수 없습니다.</p><p className="leading-7">앞의 |100−70|=30은 이 두 성분의 접힘을 계산한 식입니다. 임의의 높은 주파수에 한 번만 빼면 항상 0–50 Hz 안으로 들어온다는 뜻은 아닙니다. 여기서는 고정한 두 코사인의 같은 시각 값으로 겹침을 직접 증명했습니다.</p></div></section>

<section id="limits" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. 주기, 변환 시각, 입력 대역을 함께 확인합니다</h2><div className="prose prose-neutral my-6 max-w-none dark:prose-invert"><p className="leading-7">여러 목표 시각을 이미 놓쳤다면 콜백을 나중에 여러 번 불러도 그 사이의 실제 전압을 되찾을 수 없습니다. 건너뛴 횟수를 기록할지, 가장 최근 값만 쓸지, 다른 하드웨어 수집 경로를 사용할지는 측정 목적에 맞춰 정합니다. 지터가 생긴 실제 시각 목록은 위의 정확한 등간격 증명과 따로 분석해야 합니다.</p></div><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">타이머 목표 10 ms와 실제 ADC 시작 시각 사이의 변동은 주기 지터입니다. 클록의 정확도, 다른 ISR의 대기, ADC 준비 시간, 입력 회로의 아날로그 필터를 함께 확인해야 합니다. 신호의 높은 주파수 성분을 제한할 수 없다면 샘플 빈도도 다시 정해야 합니다.</p>
   <p className="leading-7"><strong>읽고 나서 예측해 보세요.</strong> 10 ms 주기는 몇 Hz입니까? (답: 9절) 70 Hz가 왜 30 Hz와 같게 보입니까? (답: 10·13절) 10.4 ms에 늦게 깨어나도 다음 목표는? (답: 7·11절)</p>
   <p className="leading-7"><Link to="/electronics/embedded/interrupts-and-latency-budget#budget">앞 글의 1 ms 처리 마감</Link>과 이번 10 ms 샘플 간격은 다른 제약입니다. 다음에는 센서 값을 I²C로 읽고 로그를 UART로 내보낼 때 각 버스가 어떤 비용을 만드는지 봅니다.</p>
  </div></section>
</div>;
}
