import type { CodeRef } from "@/components/code/types";
import servePy from "./codebase/vllm/benchmarks/serve.py?raw";
import endpointPy from "./codebase/vllm/benchmarks/lib/endpoint_request_func.py?raw";
export const codeRefs: Record<string, CodeRef> = {
"client-events": {...{"path": "vllm/benchmarks/lib/endpoint_request_func.py", "highlight": [374, 425], "desc": "vLLM v0.27.1 고정 원문입니다. Client 전송 전 시각·choices 이벤트·usage 이벤트가 측정 경계를 정하는 실제 chat streaming 경로입니다.", "annotations": [{"lines": [406, 412], "color": "sky", "note": "첫 choices 이벤트가 TTFT를 정하고 이후 choices 이벤트는 수신 시각 차이를 기록합니다. 빈 content도 이 경로를 통과할 수 있습니다."}, {"lines": [419, 424], "color": "amber", "note": "usage를 포함한 timestamp 갱신 뒤 마지막 수신 시각으로 latency를 계산합니다. 마지막 내용 토큰 시각과 다를 수 있습니다."}]}, code:endpointPy, lang:"python"},
"latency-metrics": {...{"path": "vllm/benchmarks/serve.py", "highlight": [584, 618], "desc": "같은 backend가 기록한 latency·ttft와 확인된 토큰 수를 사용합니다. 원시 이벤트 ITL 목록은 TPOT와 별개로 합칩니다.", "annotations": [{"lines": [590, 603], "color": "sky", "note": "서버가 토큰 수를 주지 않으면 tokenizer로 확인할 수 있습니다. Event 개수를 token 개수로 대신하지 않습니다."}, {"lines": [608, 616], "color": "emerald", "note": "5토큰에서는(1.327−1)/4=.08175초입니다. 한 토큰은 TPOT 통계 표본에서 제외하지만 goodput용 목록에는 0을 넣습니다."}]}, code:servePy, lang:"python"},
"throughput-goodput": {...{"path": "vllm/benchmarks/serve.py", "highlight": [622, 645], "desc": "설정된 요청별 지연 조건의 동시 만족을 세고 측정 기간으로 나눕니다. 본문의 구간별 percentile SLO는 별도 판정입니다.", "annotations": [{"lines": [641, 644], "color": "sky", "note": "설정된 모든 지연 조건을 통과한 요청만 good_completed에 더합니다."}, {"lines": [731, 734], "color": "emerald", "note": "120/60=2요청/s, 90/60=1.5 good requests/s, 24000/60=400 tokens/s입니다."}]}, code:servePy, lang:"python"},
"percentile-calculation": {...{"path": "vllm/benchmarks/serve.py", "highlight": [736, 756], "desc": "np.percentile에 method를 따로 지정하지 않은 실제 호출입니다. NumPy 기본 선형 보간은 본문의 nearest-rank와 다른 계산입니다.", "annotations": [{"lines": [739, 741], "color": "sky", "note": "TTFT 표본의 percentile을 구하고 초를 ms로 바꿉니다. 실제 설치 NumPy 버전도 보고해야 합니다."}, {"lines": [749, 756], "color": "amber", "note": "ITL은 합친 이벤트 간격 표본입니다. 요청별 TPOT 분포와 표본 단위가 다릅니다."}]}, code:servePy, lang:"python"},
};
