import { useMemo, useState, type ReactNode } from 'react';
import { Boxes, Layers3 } from 'lucide-react';
import { MetricGrid, SegmentedControl } from '../../nlp-shared';

const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const fmt=(v:number,d=1)=>Number.isFinite(v)?v.toFixed(d):'n/a';

function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(value:number)=>void}){
  return <label className="block min-w-0"><span className="mb-2 flex items-center justify-between gap-3 text-xs font-semibold"><span>{label}</span><span className="shrink-0 font-mono text-muted-foreground">{value}{unit}</span></span><input className="h-2 w-full cursor-pointer accent-blue-600" type="range" value={value} min={min} max={max} step={step} onChange={event=>onChange(Number(event.target.value))}/></label>;
}

function LabShell({index,title,status,children,metrics}:{index:string;title:string;status:string;children:ReactNode;metrics:Array<{label:string;value:string;accent?:boolean}>}){
  return <figure className="foundation-viz-explorer not-prose my-8 overflow-hidden rounded-md border border-border bg-background">
    <figcaption className="grid min-w-0 gap-2 border-b border-border py-4 pl-4 pr-16 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center sm:pl-6 sm:pr-20">
      <span className="flex items-center gap-2 font-mono text-xs font-black text-blue-700 dark:text-blue-300"><Layers3 className="h-4 w-4"/> COMPOSITE LAB {index}</span>
      <strong className="min-w-0 break-words text-sm leading-snug sm:text-center">{title}</strong>
      <span className="whitespace-nowrap text-[10px] font-black text-teal-700 dark:text-teal-300 sm:text-right">{status}</span>
    </figcaption>
    {children}
    <div className="border-t border-border p-4 sm:p-6"><MetricGrid mobileColumns={2} items={metrics}/></div>
  </figure>;
}

function PlotFrame({label,children}:{label:string;children:ReactNode}){
  return <div className="relative h-64 min-w-0 overflow-hidden rounded-md border border-border bg-[linear-gradient(to_right,rgba(148,163,184,.16)_1px,transparent_1px),linear-gradient(to_bottom,rgba(148,163,184,.16)_1px,transparent_1px)] bg-[size:16.66%_25%]">
    <span className="absolute left-3 top-3 z-10 text-[10px] font-black text-muted-foreground">{label}</span>{children}
  </div>;
}

export function FibreMatrixAxesLab(){
  const[angle,setAngle]=useState(0);const[fibre,setFibre]=useState(58);const c=Math.cos(angle*Math.PI/180);const axial=18+fibre*1.9*c*c;const transverse=6+(100-fibre)*.14;const shear=4+fibre*.08*Math.abs(Math.sin(2*angle*Math.PI/180));
  const fibres=Array.from({length:11},(_,i)=>i);
  return <LabShell index="01" title="Fibre가 방향을 만들고 matrix·interface가 하중을 전달한다" status="MATERIAL AXES" metrics={[{label:'Global axial modulus proxy',value:`${fmt(axial,0)} GPa`},{label:'Transverse modulus proxy',value:`${fmt(transverse,1)} GPa`},{label:'Shear demand proxy',value:fmt(shear,1)},{label:'Weak link',value:angle>55?'matrix/interface':'fibre alignment',accent:angle<20}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><Range label="Ply angle θ" value={angle} min={0} max={90} step={5} unit="°" onChange={setAngle}/><Range label="Fibre volume fraction" value={fibre} min={35} max={68} unit="%" onChange={setFibre}/><p className="text-xs leading-relaxed text-muted-foreground">같은 탄소섬유라도 global load와 fibre axis가 어긋나면 matrix shear와 interface load transfer가 커진다. 높은 E₁을 E₂로 복사할 수 없다.</p></div><PlotFrame label="GLOBAL x LOAD / ROTATED 1-2 MATERIAL AXES"><svg viewBox="0 0 620 260" className="h-full w-full"><defs><marker id="axis-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#2563eb"/></marker></defs><rect x="92" y="55" width="440" height="150" rx="8" fill="var(--muted)" fillOpacity=".55" stroke="var(--border)"/><g transform={`rotate(${angle} 312 130)`}>{fibres.map(i=><line key={i} x1="108" y1={75+i*11} x2="516" y2={75+i*11} stroke={i%3===0?'#0d9488':'#5eead4'} strokeWidth={i%3===0?3:1.5} opacity={.55+fibre/180}/>)}</g><line x1="42" y1="130" x2="570" y2="130" stroke="#2563eb" strokeWidth="3" markerEnd="url(#axis-arrow)"/><text x="44" y="117" fontSize="20" fontWeight="700" fill="#2563eb">global x</text><line x1="312" y1="130" x2={312+105*c} y2={130-105*Math.sin(angle*Math.PI/180)} stroke="#d97706" strokeWidth="2.5"/><text x={318+95*c} y={126-95*Math.sin(angle*Math.PI/180)} fontSize="20" fontWeight="700" fill="#b45309">1</text></svg></PlotFrame></div>
  </LabShell>;
}

export function LaminaTransformLab(){
  const[angle,setAngle]=useState(30);const[load,setLoad]=useState(160);const r=angle*Math.PI/180,m=Math.cos(r),n=Math.sin(r);const s1=load*m*m,s2=load*n*n,t12=-load*m*n;const points=Array.from({length:41},(_,i)=>{const a=i/40*Math.PI/2;return `${35+i/40*540},${210-(Math.cos(a)**2)*155}`}).join(' ');
  return <LabShell index="02" title="Global stress를 material-axis stress로 변환한다" status="OFF-AXIS PLY" metrics={[{label:'σ₁',value:`${fmt(s1,0)} MPa`,accent:Math.abs(s1)>Math.abs(s2)},{label:'σ₂',value:`${fmt(s2,0)} MPa`},{label:'τ₁₂',value:`${fmt(t12,0)} MPa`},{label:'Engineering shear',value:'γ₁₂ = 2ε₁₂'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><Range label="Material axis rotation" value={angle} min={0} max={90} step={2} unit="°" onChange={setAngle}/><Range label="Global σx" value={load} min={20} max={320} step={10} unit=" MPa" onChange={setLoad}/><p className="text-xs leading-relaxed text-muted-foreground">45° 근처에서는 fibre-axis normal stress만큼 material shear가 중요해진다. Stress와 engineering strain은 같은 transformation matrix를 그대로 쓰지 않는다.</p></div><PlotFrame label="ANGLE SWEEP / NORMAL-TO-SHEAR TRANSFER"><svg viewBox="0 0 620 260" className="h-full w-full"><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="3"/><path d="M35 210 C165 210 235 65 305 55 C375 65 455 210 575 210" fill="none" stroke="#d97706" strokeWidth="3"/><line x1={35+angle/90*540} x2={35+angle/90*540} y1="35" y2="215" stroke="#0d9488" strokeWidth="2" strokeDasharray="5 5"/><circle cx={35+angle/90*540} cy={210-clamp(s1/load,0,1)*155} r="6" fill="var(--background)" stroke="#2563eb" strokeWidth="3"/><text x="42" y="238" fontSize="20" fill="var(--muted-foreground)">0°</text><text x="535" y="238" fontSize="20" fill="var(--muted-foreground)">90°</text><text x="410" y="58" fontSize="20" fontWeight="700" fill="#2563eb">σ₁ 비중</text><text x="410" y="86" fontSize="20" fontWeight="700" fill="#b45309">|τ₁₂| 비중</text></svg></PlotFrame></div>
  </LabShell>;
}

type Stack='symmetric'|'balanced'|'unsymmetric';
export function LaminateAbdLab(){
  const[stack,setStack]=useState<Stack>('symmetric');const[plies,setPlies]=useState(8);const coupling=stack==='symmetric'?0:stack==='balanced'?.16:.58;const ext=plies*14.2;const bend=plies**3*.24;const layers=Array.from({length:plies},(_,i)=>({y:38+i*(174/plies),angle:stack==='unsymmetric'?[0,0,45,90][i%4]:[0,45,-45,90,90,-45,45,0][i%8]}));
  return <LabShell index="03" title="Ply order를 A·B·D stiffness ledger로 적분한다" status="LAMINATE ABD" metrics={[{label:'A stiffness proxy',value:fmt(ext,0)},{label:'B coupling index',value:fmt(coupling,2),accent:coupling===0},{label:'D stiffness proxy',value:fmt(bend,0)},{label:'Stack verdict',value:stack==='symmetric'?'B = 0':stack==='balanced'?'balanced ≠ symmetric':'membrane-bending coupled'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Layup condition" value={stack} onChange={setStack} options={[{value:'symmetric',label:'Symmetric'},{value:'balanced',label:'Balanced only'},{value:'unsymmetric',label:'Unsymmetric'}]}/><Range label="Ply count" value={plies} min={4} max={12} step={2} onChange={setPlies}/><p className="text-xs leading-relaxed text-muted-foreground">A는 두께에, D는 중립면에서 멀어진 정도의 세제곱 적분에 민감하다. 같은 ply 수라도 순서를 바꾸면 bending stiffness and coupling이 바뀐다.</p></div><PlotFrame label="STACK ORDER / ABD CONTRIBUTION"><svg viewBox="0 0 620 260" className="h-full w-full"><g>{layers.map((layer,i)=><g key={i}><rect x="56" y={layer.y} width="220" height={174/plies-2} rx="2" fill={layer.angle===0?'#bfdbfe':layer.angle===90?'#99f6e4':'#fde68a'} opacity=".78"/><text x="68" y={layer.y+174/plies*.67} fontSize="16" fontWeight="700" fill="#111827">{layer.angle}°</text></g>)}</g>{['A','B','D'].map((v,i)=><g key={v}><rect x={338+i*82} y={66} width="62" height="126" rx="6" fill={v==='B'&&coupling>.1?'#fef3c7':'var(--muted)'} fillOpacity={v==='B'&&coupling>.1?1:.72} stroke={v==='B'&&coupling>.1?'#d97706':'var(--border)'}/><text x={366+i*82} y="94" fontSize="22" fontWeight="700" textAnchor="middle" fill="var(--foreground)">{v}</text><rect x={351+i*82} y={174-(v==='A'?70:v==='B'?coupling*125:clamp(bend/8,30,115))} width="36" height={v==='A'?70:v==='B'?coupling*125:clamp(bend/8,30,115)} fill={v==='B'?'#d97706':v==='A'?'#2563eb':'#0d9488'} opacity=".8"/></g>)}</svg></PlotFrame></div>
  </LabShell>;
}

export function CouplingPlyRecoveryLab(){
  const[layup,setLayup]=useState<Stack>('unsymmetric');const[membrane,setMembrane]=useState(75);const coupling=layup==='symmetric'?0:layup==='balanced'?.18:.62;const curvature=membrane*coupling/85;const plyPeaks=[.42,.68,1,.74,.51].map((v,i)=>v*membrane*(1+curvature*(i-2)*.28));
  return <LabShell index="04" title="Mid-plane solution에서 curvature와 ply 표면 peak를 복원한다" status="PLY RECOVERY" metrics={[{label:'Mid-plane strain proxy',value:fmt(membrane/1400,4)},{label:'Curvature proxy',value:fmt(curvature,2)},{label:'Critical ply face',value:`Ply ${plyPeaks.indexOf(Math.max(...plyPeaks))+1} top/bottom`},{label:'Peak / average',value:fmt(Math.max(...plyPeaks)/(membrane*.67),2),accent:coupling===0}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Layup" value={layup} onChange={setLayup} options={[{value:'symmetric',label:'Symmetric'},{value:'balanced',label:'Balanced'},{value:'unsymmetric',label:'Unsymmetric'}]}/><Range label="Membrane load Nx" value={membrane} min={10} max={140} step={5} unit=" kN/m" onChange={setMembrane}/><p className="text-xs leading-relaxed text-muted-foreground">Solver의 laminate resultant는 끝이 아니다. `ε(z)=ε₀+zκ`를 각 ply top/bottom에 평가한 뒤 material axes로 돌려야 failure criterion input이 된다.</p></div><PlotFrame label="DEFORMED STRIP / THROUGH-THICKNESS PLY PEAKS"><svg viewBox="0 0 620 260" className="h-full w-full"><path d={`M48 105 Q310 ${105-curvature*75} 572 105 L572 132 Q310 ${132-curvature*75} 48 132 Z`} fill="#dbeafe" stroke="#2563eb" strokeWidth="2.5"/><line x1="48" y1="118" x2="572" y2={118-curvature*75} stroke="#d97706" strokeDasharray="6 5"/><g transform="translate(105 165)">{plyPeaks.map((v,i)=><g key={i}><rect x={i*82} y={58-v*.38} width="52" height={v*.38} rx="3" fill={v===Math.max(...plyPeaks)?'#dc2626':'#0d9488'} opacity=".78"/><text x={i*82+26} y="78" fontSize="18" fontWeight="700" textAnchor="middle" fill="var(--muted-foreground)">P{i+1}</text></g>)}</g></svg></PlotFrame></div>
  </LabShell>;
}

export function HygrothermalStateLab(){
  const[temp,setTemp]=useState(-35);const[moisture,setMoisture]=useState(.7);const symmetric=false;const free=-.02*temp+.85*moisture;const residual=Math.abs(temp)*.42+moisture*18;const warp=symmetric?0:free*.72;
  return <LabShell index="05" title="Cure-to-service 온도와 수분을 초기 구조 상태에 넣는다" status="HYGROTHERMAL" metrics={[{label:'Free strain proxy',value:fmt(free,2)},{label:'Residual load proxy',value:fmt(residual,1)},{label:'Warp index',value:fmt(warp,2)},{label:'Data state',value:moisture>.5?'wet / conditioned':'dry baseline',accent:moisture<=.2}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><Range label="Service minus cure ΔT" value={temp} min={-150} max={30} step={5} unit="°C" onChange={setTemp}/><Range label="Moisture state" value={moisture} min={0} max={1.2} step={.1} unit="%" onChange={setMoisture}/><p className="text-xs leading-relaxed text-muted-foreground">Applied load가 0이어도 constrained thermal/moisture strain은 ply stress and curvature를 만든다. Wet/high-temperature matrix allowables도 dry room data와 다르다.</p></div><PlotFrame label="FREE STRAIN MISMATCH / RESIDUAL CURVATURE"><svg viewBox="0 0 620 260" className="h-full w-full"><path d={`M70 150 Q310 ${150-warp*48} 550 150`} fill="none" stroke="#2563eb" strokeWidth="15" strokeLinecap="round"/><path d={`M70 175 Q310 ${175-warp*22} 550 175`} fill="none" stroke="#0d9488" strokeWidth="9" strokeLinecap="round"/><g stroke="#d97706" strokeWidth="2">{Array.from({length:9},(_,i)=><line key={i} x1={92+i*55} y1="112" x2={92+i*55+(temp<0?-10:10)} y2="132"/>)}</g><text x="72" y="82" fontSize="22" fontWeight="700" fill="#b45309">성형 기준 → 운용 상태</text><text x="72" y="220" fontSize="20" fill="var(--muted-foreground)">자유 변형률 차이가 잔류 힘·모멘트를 만든다</text></svg></PlotFrame></div>
  </LabShell>;
}

type Criterion='maximum'|'tsai-wu';
export function PlyFailureEnvelopeLab(){
  const[criterion,setCriterion]=useState<Criterion>('tsai-wu');const[s1,setS1]=useState(520);const[s2,setS2]=useState(45);const fi=criterion==='maximum'?Math.max(Math.abs(s1)/1200,Math.abs(s2)/55):(s1/1200)**2+(s2/55)**2+.35*(s1/1200)*(s2/55);const px=310+clamp(s1/1400,-1,1)*205,py=135-clamp(s2/90,-1,1)*92;
  return <LabShell index="06" title="Failure surface와 failure mode evidence를 분리한다" status="PLY FAILURE" metrics={[{label:'Failure index',value:fmt(fi,3),accent:fi<1},{label:'Criterion',value:criterion==='maximum'?'Maximum stress':'Tsai-Wu interaction'},{label:'State',value:fi>=1?'first-ply threshold':'inside envelope'},{label:'Mode knowledge',value:criterion==='tsai-wu'?'not identified':'component screen only'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Failure criterion" value={criterion} onChange={setCriterion} options={[{value:'maximum',label:'Maximum stress'},{value:'tsai-wu',label:'Tsai-Wu'}]}/><Range label="Ply σ₁" value={s1} min={-1100} max={1300} step={50} unit=" MPa" onChange={setS1}/><Range label="Ply σ₂" value={s2} min={-140} max={90} step={5} unit=" MPa" onChange={setS2}/><p className="text-xs leading-relaxed text-muted-foreground">Interaction criterion은 coupled envelope를 주지만 fibre/matrix mode를 자동 식별하지 않는다. FI=1은 해당 ply criterion의 onset이지 laminate ultimate load가 아니다.</p></div><PlotFrame label="σ₁–σ₂ FAILURE ENVELOPE"><svg viewBox="0 0 620 260" className="h-full w-full"><line x1="60" y1="135" x2="560" y2="135" stroke="var(--border)"/><line x1="310" y1="35" x2="310" y2="230" stroke="var(--border)"/>{criterion==='maximum'?<rect x="135" y="65" width="350" height="140" rx="3" fill="#ccfbf1" fillOpacity=".35" stroke="#0d9488" strokeWidth="3"/>:<ellipse cx="310" cy="135" rx="205" ry="82" transform="rotate(-12 310 135)" fill="#ccfbf1" fillOpacity=".35" stroke="#0d9488" strokeWidth="3"/>}<circle cx={px} cy={py} r="8" fill="var(--background)" stroke={fi>=1?'#dc2626':'#2563eb'} strokeWidth="4"/><text x="520" y="126" fontSize="22" fontWeight="700" fill="var(--muted-foreground)">σ₁</text><text x="318" y="50" fontSize="22" fontWeight="700" fill="var(--muted-foreground)">σ₂</text></svg></PlotFrame></div>
  </LabShell>;
}

export function ProgressiveDamageLab(){
  const[failed,setFailed]=useState(1);const[degrade,setDegrade]=useState(70);const shares=Array.from({length:6},(_,i)=>i===failed?(100-degrade)*.12:18+degrade/(6-1)*.12+(i%2)*5);const max=Math.max(...shares);
  return <LabShell index="07" title="First-ply failure 뒤의 load redistribution을 상태 전이로 본다" status="PROGRESSIVE DAMAGE" metrics={[{label:'Failed ply',value:`Ply ${failed+1}`},{label:'Stiffness retained',value:`${100-degrade}%`},{label:'Neighbor peak share',value:fmt(max,1)},{label:'Ultimate claim',value:'requires validated degradation'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><Range label="Selected damaged ply" value={failed+1} min={1} max={6} onChange={v=>setFailed(v-1)}/><Range label="Stiffness degradation" value={degrade} min={10} max={95} step={5} unit="%" onChange={setDegrade}/><p className="text-xs leading-relaxed text-muted-foreground">Degradation rule가 바뀌면 다음 failure 순서와 last-ply load도 바뀐다. Local softening은 element size에 의존할 수 있어 energy regularization and test correlation이 필요하다.</p></div><PlotFrame label="PLY STIFFNESS LOSS / LOAD REDISTRIBUTION"><svg viewBox="0 0 620 260" className="h-full w-full"><g transform="translate(72 38)">{shares.map((share,i)=><g key={i}><rect x={i*84} y={178-share*4.6} width="54" height={share*4.6} rx="4" fill={i===failed?'#fca5a5':share===max?'#fbbf24':'#60a5fa'} opacity=".85"/><text x={i*84+27} y="204" textAnchor="middle" fontSize="18" fontWeight="700" fill="var(--muted-foreground)">P{i+1}</text><text x={i*84+27} y={164-share*4.6} textAnchor="middle" fontSize="18" fontWeight="700" fill="var(--foreground)">{fmt(share,0)}%</text></g>)}</g></svg></PlotFrame></div>
  </LabShell>;
}

type JointMode='bearing'|'bypass';
export function HoleJointLoadLab(){
  const[mode,setMode]=useState<JointMode>('bearing');const[edge,setEdge]=useState(2.4);const[clampLoad,setClamp]=useState(35);const bearing=1.35-clampLoad*.006;const net=1/(1-.22/edge);const shear=1.6/edge;const pull=.45+clampLoad/85;const worst=Math.max(bearing,net,shear,pull);
  return <LabShell index="08" title="Fastener load를 bearing·bypass·net·shear-out paths로 나눈다" status="MECHANICAL JOINT" metrics={[{label:'Bearing index',value:fmt(bearing,2)},{label:'Net tension index',value:fmt(net,2)},{label:'Shear-out index',value:fmt(shear,2)},{label:'Governing path',value:worst===bearing?'bearing':worst===net?'net tension':worst===shear?'shear-out':'pull-through'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Load split emphasis" value={mode} onChange={setMode} options={[{value:'bearing',label:'Bearing transfer'},{value:'bypass',label:'Bypass load'}]}/><Range label="Edge distance / diameter" value={edge} min={1.2} max={5} step={.1} onChange={setEdge}/><Range label="Clamp proxy" value={clampLoad} min={0} max={70} step={5} unit="%" onChange={setClamp}/><p className="text-xs leading-relaxed text-muted-foreground">Clamp friction may reduce early bearing but cannot erase composite crushing, relaxation or pull-through. Joint geometry must close every competing path.</p></div><PlotFrame label="HOLE LOAD INTRODUCTION / COMPETING FAILURE PATHS"><svg viewBox="0 0 620 260" className="h-full w-full"><path d="M70 55H550V205H70Z" fill="#dbeafe" stroke="#2563eb" strokeWidth="2"/><circle cx="250" cy="130" r="46" fill="var(--background)" stroke="#0d9488" strokeWidth="5"/><circle cx="250" cy="130" r="24" fill="#94a3b8"/><path d={mode==='bearing'?'M250 76A54 54 0 0 1 250 184':'M70 105H204M296 105H550M70 155H204M296 155H550'} fill="none" stroke="#d97706" strokeWidth="10" opacity=".65"/><line x1="72" y1="130" x2="190" y2="130" stroke="#2563eb" strokeWidth="4"/><line x1="310" y1="130" x2="548" y2="130" stroke="#2563eb" strokeWidth="4"/><path d={`M${250+46} 84 L${250+edge*28} 55`} stroke="#dc2626" strokeWidth="2" strokeDasharray="5 4"/><text x="350" y="78" fontSize="20" fontWeight="700" fill="#b91c1c">가장자리 전단 파괴 경로</text></svg></PlotFrame></div>
  </LabShell>;
}

export function BondDelaminationLab(){
  const[flaw,setFlaw]=useState(8);const[overlap,setOverlap]=useState(55);const[mix,setMix]=useState(45);const gi=(flaw/20)**1.45*(80/overlap)*(.35+mix/100);const gii=(flaw/18)**1.3*(80/overlap)*(1.2-mix/140);const index=(gi/.42)**2+(gii/.85)**2;
  return <LabShell index="09" title="Bond edge의 peel·shear를 mixed-mode delamination driving force로 바꾼다" status="VCCT / CZM BOUNDARY" metrics={[{label:'Gᵢ proxy',value:fmt(gi,2)},{label:'Gᵢᵢ proxy',value:fmt(gii,2)},{label:'Mixed-mode index',value:fmt(index,2),accent:index<1},{label:'Analysis boundary',value:'test-verified toughness + mesh'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><Range label="Edge flaw length" value={flaw} min={1} max={22} unit=" mm" onChange={setFlaw}/><Range label="Overlap length" value={overlap} min={25} max={110} step={5} unit=" mm" onChange={setOverlap}/><Range label="Mode-I share" value={mix} min={5} max={90} step={5} unit="%" onChange={setMix}/><p className="text-xs leading-relaxed text-muted-foreground">Average bond shear가 낮아도 overlap end의 peel and re-entrant geometry가 지배할 수 있다. VCCT는 existing crack growth, CZM은 initiation/progression modeling에 쓰지만 모두 interface data and mesh contract가 필요하다.</p></div><PlotFrame label="OVERLAP END / MIXED-MODE ENERGY POINT"><svg viewBox="0 0 620 260" className="h-full w-full"><rect x="62" y="86" width={overlap*3.3} height="24" rx="4" fill="#93c5fd"/><rect x={510-overlap*3.3} y="150" width={overlap*3.3} height="24" rx="4" fill="#5eead4"/><path d={`M${510-overlap*3.3} 132 H${510-overlap*3.3+flaw*5}`} stroke="#dc2626" strokeWidth="6" strokeLinecap="round"/><path d={`M${510-overlap*3.3} 150 Q${510-overlap*3.3+flaw*5} ${150-mix*.5} ${510-overlap*3.3+flaw*8} 145`} fill="none" stroke="#d97706" strokeWidth="3"/><line x1="60" y1="98" x2="30" y2="98" stroke="#2563eb" strokeWidth="4"/><line x1="510" y1="162" x2="590" y2="162" stroke="#2563eb" strokeWidth="4"/><text x="62" y="62" fontSize="20" fontWeight="700" fill="var(--muted-foreground)">겹침부 끝에서 하중 전달이 집중된다</text></svg></PlotFrame></div>
  </LabShell>;
}

export function ImpactCaiLab(){
  const[energy,setEnergy]=useState(12);const[radius,setRadius]=useState(10);const[support,setSupport]=useState<'soft'|'stiff'>('stiff');const damage=energy*(support==='stiff'?1.35:.82)*(18/(radius+8));const dent=Math.sqrt(energy)/(radius*.25+2);const cai=clamp(100-damage*2.5,28,100);
  return <LabShell index="10" title="작은 dent와 큰 subsurface delamination을 분리한다" status="BVID / CAI" metrics={[{label:'Dent proxy',value:fmt(dent,2)},{label:'Hidden area proxy',value:fmt(damage,1)},{label:'CAI residual',value:`${fmt(cai,0)}%`,accent:cai>70},{label:'Visual verdict',value:dent<1?'barely visible ≠ benign':'visible + NDE required'}]}>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Local support" value={support} onChange={setSupport} options={[{value:'stiff',label:'Near stiff insert'},{value:'soft',label:'Compliant acreage'}]}/><Range label="Impact energy" value={energy} min={2} max={35} unit=" J" onChange={setEnergy}/><Range label="Impactor radius" value={radius} min={3} max={28} unit=" mm" onChange={setRadius}/><p className="text-xs leading-relaxed text-muted-foreground">Dent depth, delamination area and compression-after-impact strength are related but not interchangeable observables. Support and impactor shape change the damage state at the same energy.</p></div><PlotFrame label="SURFACE DENT / HIDDEN PLY-BY-PLY DAMAGE"><svg viewBox="0 0 620 260" className="h-full w-full"><path d={`M80 88H250 Q310 ${88+dent*12} 370 88H540`} fill="none" stroke="#2563eb" strokeWidth="8"/><circle cx="310" cy={50+radius*.45} r={clamp(radius*1.5,12,40)} fill="#94a3b8" opacity=".8"/><g>{Array.from({length:5},(_,i)=>{const w=clamp(damage*(i<3?7-i:3),18,250);return <path key={i} d={`M${310-w/2} ${132+i*18} Q310 ${142+i*18+(i%2)*4} ${310+w/2} ${132+i*18}`} fill="none" stroke={i===2?'#dc2626':'#d97706'} strokeWidth={i===2?4:2.5}/>})}</g><text x="78" y="225" fontSize="20" fontWeight="700" fill="var(--muted-foreground)">표면 자국만으로 내부 박리 폭을 한정할 수 없다</text></svg></PlotFrame></div>
  </LabShell>;
}

type NdeMethod='visual'|'ultrasound'|'thermography';
export function ManufacturingNdeLab(){
  const[method,setMethod]=useState<NdeMethod>('ultrasound');const[depth,setDepth]=useState(4);const[access,setAccess]=useState(72);const capability=method==='visual'?clamp(18-depth*3,4,45):method==='ultrasound'?clamp(92-Math.abs(depth-5)*7,20,94):clamp(76-depth*4,12,82);const effective=capability*access/100;const missed=100-effective;
  return <LabShell index="11" title="Flaw type·depth·access에 맞춰 NDE와 residual threat를 연결한다" status="PROCESS + NDE" metrics={[{label:'Method capability',value:`${fmt(capability,0)}%`},{label:'Accessible area',value:`${access}%`},{label:'Effective screen',value:`${fmt(effective,0)}%`,accent:effective>75},{label:'Residual threat',value:`${fmt(missed,0)}% remains bounded`}] }>
    <div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><div className="space-y-5"><SegmentedControl label="Inspection method" value={method} onChange={setMethod} options={[{value:'visual',label:'Visual'},{value:'ultrasound',label:'Ultrasound'},{value:'thermography',label:'Thermography'}]}/><Range label="Flaw depth" value={depth} min={0} max={12} unit=" mm" onChange={setDepth}/><Range label="Physical access" value={access} min={20} max={100} unit="%" onChange={setAccess}/><p className="text-xs leading-relaxed text-muted-foreground">Uninspectable area는 `no flaw`가 아니다. 대표 결함을 가정해 tolerance를 보이거나, access를 설계하거나, protection and process evidence로 residual threat를 다시 정의해야 한다.</p></div><PlotFrame label="METHOD COVERAGE / BLIND ZONE"><svg viewBox="0 0 620 260" className="h-full w-full"><rect x="62" y="74" width="496" height="118" rx="8" fill="#e2e8f0"/><rect x="62" y="74" width={496*access/100} height="118" rx="8" fill="#ccfbf1"/><path d={`M62 74H${62+496*access/100}V192H62Z`} fill="#0d9488" opacity={effective/180}/><ellipse cx={90+depth*31} cy="135" rx="32" ry="12" fill="#dc2626" opacity=".72"/><path d={`M${62+496*access/100} 58V208`} stroke="#d97706" strokeWidth="4" strokeDasharray="7 5"/><text x="70" y="56" fontSize="20" fontWeight="700" fill="#0f766e">검증된 검사 접근 영역</text><text x={Math.min(430,72+496*access/100)} y="222" fontSize="20" fontWeight="700" fill="#b45309">검사 사각지대</text></svg></PlotFrame></div>
  </LabShell>;
}

type EvidenceLevel='coupon'|'element'|'subcomponent'|'component';

const evidenceItems: Array<{key:EvidenceLevel;label:string;claim:string}> = [
  {key:'coupon',label:'01 쿠폰',claim:'재료·공정 분산'},
  {key:'element',label:'02 요소',claim:'구멍·접착·충격'},
  {key:'subcomponent',label:'03 부분 구조',claim:'경계·하중 경로'},
  {key:'component',label:'04 완성 구조',claim:'전체 상호작용'},
];

export function BuildingBlockEvidenceLab(){
  const[level,setLevel]=useState<EvidenceLevel>('element');const[correlation,setCorrelation]=useState(78);const coverage={coupon:24,element:52,subcomponent:76,component:92}[level];const confidence=coverage*correlation/100;const gaps=level==='coupon'?'joint, impact, geometry':level==='element'?'global load path, environment':level==='subcomponent'?'full boundary and variability':'fleet/process transfer';
  return <LabShell index="12" title="Coupon에서 component까지 claim과 evidence를 단계적으로 닫는다" status="BUILDING BLOCK RELEASE" metrics={[{label:'Selected level',value:level},{label:'Claim coverage',value:`${coverage}%`},{label:'Correlated confidence',value:`${fmt(confidence,0)}%`,accent:confidence>70},{label:'Still open',value:gaps}]}>
    <div className="p-4 sm:p-6">
      <SegmentedControl label="Evidence level" value={level} onChange={setLevel} options={[{value:'coupon',label:'Coupon'},{value:'element',label:'Element'},{value:'subcomponent',label:'Subcomponent'},{value:'component',label:'Component'}]}/>
      <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]">
        <div className="space-y-5"><Range label="Model-test correlation" value={correlation} min={30} max={100} unit="%" onChange={setCorrelation}/><p className="text-xs leading-relaxed text-muted-foreground">Building block은 시험 수를 줄이는 피라미드가 아니라 각 scale의 variability and failure mode로 analysis를 교정하는 반복 loop다. 높은 단계도 material/process traceability를 대체하지 않는다.</p></div>
        <PlotFrame label="CLAIM COVERAGE GROWS WITH GEOMETRIC FIDELITY">
          <svg viewBox="0 0 340 260" className="h-full w-full sm:hidden">
            <defs><marker id="evidence-arrow-mobile" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#0d9488"/></marker><marker id="feedback-arrow-mobile" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#d97706"/></marker></defs>
            {evidenceItems.map((item,index)=>{const x=index===0||index===3?18:178;const y=index<2?58:148;const active=evidenceItems.indexOf(item)<=evidenceItems.findIndex(entry=>entry.key===level);return <g key={item.key}><rect x={x} y={y} width="144" height="62" rx="6" fill={active?'#dbeafe':'var(--muted)'} fillOpacity={active?.96:.74} stroke={active?'#2563eb':'var(--border)'} strokeWidth="1.6"/><text x={x+11} y={y+25} fontSize="13" fontWeight="800" fill={active?'#1d4ed8':'var(--foreground)'}>{item.label}</text><text x={x+11} y={y+47} fontSize="11.5" fill="var(--muted-foreground)">{item.claim}</text></g>})}
            <path d="M162 89H172" stroke="#0d9488" strokeWidth="2.5" markerEnd="url(#evidence-arrow-mobile)"/><path d="M250 120V140" stroke="#0d9488" strokeWidth="2.5" markerEnd="url(#evidence-arrow-mobile)"/><path d="M178 179H168" stroke="#0d9488" strokeWidth="2.5" markerEnd="url(#evidence-arrow-mobile)"/><path d="M18 179C4 179 4 89 12 89" fill="none" stroke="#d97706" strokeWidth="2.5" strokeDasharray="5 4" markerEnd="url(#feedback-arrow-mobile)"/><text x="20" y="238" fontSize="11.5" fontWeight="700" fill="#b45309">시험 불일치 → 하위 모델·가정 교정</text>
          </svg>
          <svg viewBox="0 0 620 260" className="hidden h-full w-full sm:block">
            <defs><marker id="evidence-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#0d9488"/></marker><marker id="feedback-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#d97706"/></marker></defs>
            {evidenceItems.map((item,index)=>{const x=index===0||index===3?46:326;const y=index<2?52:146;const active=evidenceItems.indexOf(item)<=evidenceItems.findIndex(entry=>entry.key===level);return <g key={item.key}><rect x={x} y={y} width="248" height="68" rx="7" fill={active?'#dbeafe':'var(--muted)'} fillOpacity={active?.95:.72} stroke={active?'#2563eb':'var(--border)'} strokeWidth="2"/><text x={x+18} y={y+28} fontSize="20" fontWeight="800" fill={active?'#1d4ed8':'var(--foreground)'}>{item.label}</text><text x={x+18} y={y+54} fontSize="17" fill="var(--muted-foreground)">{item.claim}</text></g>})}
            <path d="M294 86H318" stroke="#0d9488" strokeWidth="3" markerEnd="url(#evidence-arrow)"/><path d="M450 120V138" stroke="#0d9488" strokeWidth="3" markerEnd="url(#evidence-arrow)"/><path d="M326 180H302" stroke="#0d9488" strokeWidth="3" markerEnd="url(#evidence-arrow)"/><path d="M46 180C20 180 20 86 38 86" fill="none" stroke="#d97706" strokeWidth="3" strokeDasharray="7 5" markerEnd="url(#feedback-arrow)"/><text x="50" y="238" fontSize="17" fontWeight="700" fill="#b45309">시험 불일치 → 하위 모델·가정 교정</text>
          </svg>
        </PlotFrame>
      </div>
    </div>
  </LabShell>;
}

export function CompositeMiniMap(){
  return <div className="not-prose my-6 flex items-center gap-3 rounded-md border border-border p-4 text-sm"><Boxes className="h-5 w-5 shrink-0 text-blue-600"/><span><strong>상태 사슬:</strong> constituent → lamina axes → laminate ABD → detail/joint → damage → NDE → building-block evidence</span></div>;
}
