import type {CodeRef,FileNode,ProjectMeta} from "@/components/code/types";
import source from "./codebase/flash_attn/cute/softmax.py?raw";
export const codeRefs:Record<string,CodeRef>={
"softmax":{...{"path": "flash-attention/flash_attn/cute/softmax.py", "highlight": [188, 251], "desc": "e9515d5의 전체 원문입니다. 최대값은 네 lane이 합치고 지수합은 lane별 부분합으로 남깁니다. 이미 조정한 사례에서 scale_log2=log₂e입니다.", "annotations": [{"lines": [210, 219], "color": "sky", "note": "각 lane의 최대를 네 lane 사이에서 다시 합칩니다."}, {"lines": [234, 248], "color": "sky", "note": "옛 부분합에 e⁻²를 곱하고 새 부분합을 더합니다. 아직 행 전체 합이 아닙니다."}], "lang": "python"},code:source},
"finalize":{...{"path": "flash-attention/flash_attn/cute/softmax.py", "highlight": [253, 288], "desc": "마지막에 네 부분합을 더합니다. 별도 배율과 sink가 없는 사례에서 역수는 최종 정규화 배율입니다. row_sum 칸은 종료 전에 로그 지수합으로 바뀝니다.", "annotations": [{"lines": [260, 264], "color": "sky", "note": "0.068103+1.135335+0+0≈1.203438입니다."}, {"lines": [276, 287], "color": "sky", "note": "역수와 로그 지수합을 계산합니다. 합이 0이거나 NaN인 경우는 별도 처리합니다."}], "lang": "python"},code:source},
"rescale":{...{"path": "flash-attention/flash_attn/cute/softmax.py", "highlight": [291, 301], "desc": "분자에 해당하는 출력 누적값에도 같은 배율을 곱합니다. e⁻²를 넘기면 첫 가중합 4.270671이 약 0.577972로 바뀝니다. 새 값의 행렬곱은 함수 바깥에서 수행합니다.", "annotations": [{"lines": [298, 301], "color": "sky", "note": "한 행의 출력 성분 전부를 같은 row_scale로 곱합니다."}], "lang": "python"},code:source},
"conditional":{...{"path": "flash-attention/flash_attn/cute/softmax.py", "highlight": [340, 360], "desc": "Blackwell용 scalar 기준 갱신 분기입니다. 임계값은 2의 지수 단위이며 양수일 때만 적용합니다. 가정한 임계값 3은 기준 3 유지, 2는 기준 5 갱신입니다.", "annotations": [{"lines": [346, 348], "color": "sky", "note": "첫 조각은 옛 누적값이 없으므로 배율 0을 반환합니다."}, {"lines": [352, 358], "color": "sky", "note": "−2.885390≥−3은 참, −2.885390≥−2는 거짓입니다. 경계의 등호는 유지 분기입니다."}], "lang": "python"},code:source},
};
export const fileTrees:Record<string,FileNode>={"flash-attention":{name:"flash-attention",type:"dir",children:[{name:"softmax.py",type:"file",path:"flash-attention/flash_attn/cute/softmax.py",codeKey:"softmax"}]}};
export const projectMetas:Record<string,ProjectMeta>={"flash-attention":{id:"flash-attention",label:"FlashAttention · e9515d5",badgeClass:"bg-primary/10 text-primary"}};
