import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
const scenes=[
 {label:"고정 순서의 처음",order:"① → ② → ③ → ④ → ⑤ → ⑥",balances:[100,20,0],total:120,headline:"첫 지급을 위한 100과 뒤 지급을 위한 20",note:"A가 100을 보내고 B가 90을 돌려주면 B는 30을 남겨 ③번을 처리합니다. 처음 B의 20이 없다면 ③번에서 멈춥니다."},
 {label:"고정 순서의 마지막",order:"같은 순서로 여섯 건 완료",balances:[90,20,10],total:120,headline:"받은 돈은 다음 지급에 다시 쓰였습니다",note:"총 260을 주고받아도 잔액 합은 120입니다. A는 10 줄고 C는 10 늘었습니다. 지시 총액과 최초 자금은 다릅니다."},
 {label:"순서를 바꾼 처음",order:"① → ③ → ④ → ② → ⑤ → ⑥",balances:[100,0,0],total:100,headline:"B가 C에게 먼저 보내고 20을 돌려받습니다",note:"B가 100을 받은 뒤 30을 보내고 20을 받으면 90이 됩니다. 그때 A에게 90을 돌려줍니다. 최초 합 100으로 모두 처리할 수 있습니다."},
 {label:"순서를 바꾼 마지막",order:"바꾼 순서로 여섯 건 완료",balances:[90,0,10],total:100,headline:"같은 최종 변화, 더 적은 최초 자금",note:"A−10·B 0·C+10이라는 변화는 같습니다. 지시를 쪼개거나 추가로 빌리지 않는 모형에서는 100 지시 때문에 최초 합도 최소 100입니다."},
 {label:"묶음 처리의 후보",order:"여섯 건을 함께 처리할 별도 분기",balances:[10,0,0],total:10,headline:"건별 100은 대기하지만 합산 변화는 처리 후보입니다",note:"A 10·B 0·C 0에 변화 −10·0·+10을 더하면 0·0·10입니다. 모든 지시의 수락·한도·법적 효력과 묶음 전체의 원자적 이행이 필요합니다."},
];
export default function LiquidityOrderViz(){const scene=useAnimatedScenes(scenes.length,5000);const s=scenes[scene.active];return <figure data-viz="liquidity-order" className="my-8 border-y border-border py-4"><figcaption className="mb-3 text-sm leading-6">무신용·분할 불가의 설명용 모형 · 단위: 억 원</figcaption><div data-viz-canvas tabIndex={0} role="group" aria-label="처리 순서와 최초 필요한 돈의 다섯 장면" onKeyDown={scene.onKeyDown} className="flex h-[min(600px,calc(100svh-150px))] flex-col outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><div className="min-h-0 flex-1 overflow-y-auto px-1 py-3"><h3 className="mb-4 text-lg font-semibold">{s.headline}</h3><p className="mb-5 text-sm leading-7">{s.order}</p><div className="grid grid-cols-3 gap-4">{s.balances.map((v,i)=><div key={i} className="border-b border-border pb-3"><p className="text-sm">{"ABC"[i]} 잔액</p><p className="my-2 text-2xl font-semibold tabular-nums">{v}</p><div className="flex h-14 items-end"><div aria-hidden className="w-full bg-primary/30" style={{height:`${v}%`}}/></div></div>)}</div><p className="my-4 text-lg font-semibold tabular-nums">잔액 합 {s.total}</p><p className="text-sm leading-7">{s.note}</p></div><AnimatedSceneControls {...scene} labels={scenes.map(s=>s.label)}/></div></figure>;}
