import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
const scenes=[
 {label:"여섯 지시",title:"각 지시의 금액을 먼저 확인합니다",note:"같은 여섯 건을 계속 사용합니다. 총액 260은 지시 금액의 합입니다. 처음 준비할 돈과는 다릅니다."},
 {label:"받을 합과 보낼 합",title:"은행마다 들어오고 나갈 금액을 맞춥니다",note:"각 은행의 받을 합에서 보낼 합을 뺍니다. B의 변화가 0이어도 B가 처리하는 지시는 있습니다."},
 {label:"마지막 차이",title:"A가 10을 내면 C가10을 받습니다",note:"유효한 약정과 이행 조건을 갖춰 차이만 처리하는 분기입니다. 지급량 차이 250으로 손실 위험을 알 수는 없습니다."},
];
const flows=["① A → B: 100","② B → A: 90","③ B → C: 30","④ C → B: 20","⑤ A → C: 10","⑥ C → A: 10"];
export default function SettlementCaseViz(){const scene=useAnimatedScenes(scenes.length,4500);const s=scenes[scene.active];return <figure data-viz="settlement-case" className="my-8 border-y border-border py-4"><figcaption className="mb-3 text-sm leading-6">같은 통화로 주고받을 여섯 지시 · 단위: 억 원</figcaption><div data-viz-canvas tabIndex={0} role="group" aria-label="여섯 지시에서 마지막 차이까지" onKeyDown={scene.onKeyDown} className="flex h-[min(530px,calc(100svh-150px))] flex-col outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><div className="min-h-0 flex-1 overflow-y-auto px-1 py-3"><h3 className="mb-4 text-lg font-semibold">{s.title}</h3>{scene.active===0?<ol className="grid grid-cols-2 gap-x-4 gap-y-3">{flows.map(f=><li key={f} className="border-b border-border pb-2 text-sm tabular-nums">{f}</li>)}</ol>:scene.active===1?<div className="space-y-3">{[["A",100,110,-10],["B",120,120,0],["C",40,30,10]].map(([bank,received,sent,net])=><div key={bank} className="grid grid-cols-[2rem_1fr] gap-3 border-b border-border pb-2"><strong>{bank}</strong><div className="text-sm leading-7 tabular-nums">받음 {received} − 보냄 {sent}<br/><strong>변화 {Number(net)>0?"+":""}{net}</strong></div></div>)}</div>:<div className="space-y-4"><div className="grid grid-cols-3 items-center text-center text-xl font-semibold"><span>A</span><span className="text-primary">10 →</span><span>C</span></div><p className="border-b border-border pb-3 text-center text-sm">B의 마지막 변화는 0입니다.</p><p className="text-base tabular-nums">총 지시 260 → 이동 10<br/>지급량 차이 250</p></div>}<p className="mt-5 text-sm leading-7">{s.note}</p></div><AnimatedSceneControls {...scene} labels={scenes.map(s=>s.label)}/></div></figure>;}
