import VizFrame from "@/components/viz/VizFrame";
import { RecurrentSceneControls } from "./RecurrentVizControls";
import { useRecurrentScenes } from "./useRecurrentScenes";

const SCENES = ["역방향 합산", "Jacobian 배율", "detach 경계"] as const;

export default function BPTTLearningFlowViz(){const scenes=useRecurrentScenes(SCENES.length);return <VizFrame eyebrow="Animated BPTT" title="Forward state는 이어지고 backward credit은 선택한 경계까지만 돌아간다" description="공유 weight gradient, 반복 Jacobian의 크기, truncated BPTT의 value-carry/graph-detach 차이를 한 시간축에서 봅니다."><div data-viz-canvas tabIndex={0} role="group" aria-label="BPTT gradient and truncation animation" onKeyDown={scenes.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary">
  <div className={`border p-5 ${scenes.active===0?"border-primary bg-primary/10":"border-border"}`}><p className="text-xs font-bold text-emerald-700">FORWARD →</p><div className="mt-4 grid grid-cols-4 gap-2">{[1,2,3,4].map(n=><div key={n} className="relative border border-border bg-background p-3 text-center font-mono font-bold">h{n}{n<4?<span className="absolute -right-2 top-3 text-primary">→</span>:null}</div>)}</div><p className="mt-5 text-right text-xs font-bold text-rose-700">← BACKWARD · ∂W contributions add</p></div>
  <div className={`mt-5 grid gap-3 sm:grid-cols-3 ${scenes.active===1?"opacity-100":"opacity-60"}`}>{[["0.7⁸","vanish","bg-sky-500"],["1.0⁸","stable","bg-emerald-500"],["1.3⁸","explode","bg-rose-500"]].map(([value,label,tone])=><div key={label} className="border border-border bg-background p-4"><p className="font-mono text-lg font-black">{value}</p><div className="mt-3 h-2 bg-muted"><div className={`h-full ${tone}`} style={{width:label==="vanish"?"10%":label==="stable"?"48%":"100%"}} /></div><p className="mt-2 text-xs font-bold">{label}</p></div>)}</div>
  <div className={`mt-5 border p-5 ${scenes.active===2?"border-amber-500 bg-amber-500/10":"border-border"}`}><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr]"><div className="border border-border bg-background p-4 text-center"><p className="font-bold">chunk A</p><p className="mt-2 font-mono text-xs">h₀ … h₁₂₈</p></div><div className="flex flex-col items-center justify-center"><span className="text-primary">value →</span><span className="my-2 h-8 border-l border-dashed border-rose-500"/><span className="text-xs text-rose-600">gradient ✕</span></div><div className="border border-border bg-background p-4 text-center"><p className="font-bold">chunk B</p><p className="mt-2 font-mono text-xs">detach(h₁₂₈) …</p></div></div></div>
  <RecurrentSceneControls {...scenes} labels={SCENES}/></div></VizFrame>}
