import type { EngineeringDepthData } from "../../cloud/EngineeringDepthBlocks";

const checkedAt = "2026-10-08";

export const b300BlueprintDepth = {
  ledgers: [
    {
      section: "mechanism",
      title: "16노드 기준 BOM 초안",
      question: "공개 기준만으로 확정할 수 있는 수량과 OEM·현장 결정 뒤에 확정할 수 있는 수량은 무엇입니까?",
      columns: ["항목", "16노드 기준선", "계산·근거", "발주 전 닫을 값"],
      rows: [
        ["8-GPU compute node", "16대", "128 GPU ÷ 8 GPU/node", "DGX 완제품인지 OEM HGX인지, 지원 기간과 spare"],
        ["B300 GPU", "128개", "16 node × 8 GPU", "실제 workload가 요구하는 수량인지 별도 benchmark"],
        ["분산 HBM", "36,864GB", "128 × 288GB", "모델 병렬화 뒤 rank별 여유와 allocator headroom"],
        ["East/West SuperNIC", "128개", "HGX 기준 8 ConnectX-8/node", "InfiniBand·Ethernet, 800G native·2×400G breakout"],
        ["North/South DPU", "미확정", "HGX 권장안과 DGX 완제품 구성이 다름", "포트 수, storage·service·tenant 경계"],
        ["compute fabric switch", "미확정", "서버 포트 수만으로 switch 수는 정해지지 않음", "port radix, dual plane, blocking ratio, 32노드 확장"],
        ["rack·power·cooling", "4개 high-density rack 또는 8개 low-density rack 후보", "공개 배치안은 rack당 4대 또는 2대", "건물 전력, 바닥 하중, RDHx·air, cable reach"],
      ],
      conclusion: "서버와 GPU 수는 계산되지만 switch·optic·cable·DPU·facility 행은 토폴로지와 현장 조건이 정해질 때까지 ‘미확정’으로 남겨야 합니다.",
    },
    {
      section: "mechanism",
      title: "요구사항에서 시험까지 이어지는 추적 원장",
      question: "BOM 한 행이 ‘왜 필요한가’와 ‘어떻게 합격시킬 것인가’를 설명할 수 있습니까?",
      columns: ["요구 ID", "입력·가정", "설계 결정", "BOM 영향", "검수 증거"],
      rows: [
        ["REQ-TRN-01", "(가정) 16노드 한 작업, 완료 시간 24시간", "non-blocking dual-plane 후보", "NIC·leaf·spine·optic·cable", "16-node all-reduce와 실제 training step time"],
        ["REQ-STO-02", "(가정) 8TB checkpoint를 120초 안에 저장", "sustained 66.7GB/s 이상과 여유", "storage node·client NIC·mount", "IOR/fio 뒤 application checkpoint"],
        ["REQ-EXP-03", "32노드까지 증설", "첫 단계에서 uplink·rack·배관 경로 확보", "빈 port·optic 보류·cable tray", "32노드 증설 BOM에서 교체 항목 0개인지 검토"],
        ["REQ-OPS-04", "노드 한 대 격리 후 나머지 운영", "scheduler drain과 spare 절차", "spare·support entitlement", "node drain→job 재실행→repair→return 절차"],
      ],
      conclusion: "면접에서는 장비 이름보다 이 한 행을 설명하는 편이 낫습니다. 요구가 설계와 발주, 시험 결과까지 이어지면 ‘왜 이 부품인가’에 답할 수 있습니다.",
    },
    {
      section: "mechanism",
      title: "모델 이름을 인프라 입력으로 바꾸는 장부",
      question: "‘GLM 계열 모델을 돌린다’는 한 문장을 GPU 수와 검수 조건으로 바꾸려면 무엇을 더 받아야 합니까?",
      columns: ["확인할 값", "실제 GLM-5.3-Flash 공개값", "교육용 축소 모델", "인프라 결정"],
      rows: [
        ["전체 가중치", "320B total parameters", "25,730,592 parameters", "Checkpoint dtype별 payload와 모든 expert의 residency를 계산"],
        ["token당 활성 경로", "18B active parameters", "약 9,805,344 active parameters", "한 token의 compute·expert 통신량을 추정하되 전체 weight 저장량과 분리"],
        ["문맥·상태", "요구 workload의 실제 input/output 길이와 동시 요청으로 재산정", "192-token 교육용 context", "KV·recurrent state, batch, workspace와 allocator 여유를 별도 계산"],
        ["구조", "Hybrid sparse·linear attention, MoE, multimodal", "단순화한 sparse/linear rhythm과 MoE", "지원 runtime·kernel·parallelism을 실제 checkpoint와 대조"],
        ["검수", "Target model·precision·batch·context로 benchmark", "Synthetic Python task 결과", "교육용 정확도나 VRAM을 production 처리량 근거로 사용하지 않음"],
      ],
      conclusion: "Total parameter는 저장·weight residency, active parameter는 token당 계산 경로의 한 입력입니다. 둘 가운데 하나만으로 GPU 수를 정하지 않고 context·batch·runtime state와 실제 checkpoint 형식을 함께 봅니다.",
    },
    {
      section: "mechanism",
      title: "가속기 한 장을 납품 일정으로 바꾸는 공급 위험 원장",
      question: "완제품 서버 수량만 적으면 어떤 병목과 대체 불가능성을 놓칩니까?",
      columns: ["경로", "막히면 보이는 결과", "발주 전에 받을 증거", "설계 대응"],
      rows: [
        ["Logic die·yield", "GPU module 공급량·일정 변동", "OEM 확정 allocation·lead time·지원 SKU", "납기 가정과 대체 SKU의 성능 재검수"],
        ["HBM", "용량·대역폭·module 수량 제약", "정확한 GPU memory 구성과 승인된 module", "Model residency·checkpoint 형식·GPU 수 재산정"],
        ["Advanced package", "Logic과 HBM을 함께 묶는 package 병목", "완제품 part number·revision·qualification", "서로 다른 board revision을 같은 baseline으로 간주하지 않음"],
        ["Server·fabric", "NIC·optic·switch가 없어 node만 대기", "Port map·optic 양 끝·cable 길이·firmware matrix", "Compute와 network를 별도 납기가 아닌 통합 ready date로 관리"],
        ["Power·cooling", "장비는 도착했지만 rack에 energize 못함", "A/B feed·peak kW·air/liquid boundary·site readiness", "FAT 이전에 facility hold point를 닫음"],
      ],
      conclusion: "공급망은 회사 이름을 외우는 문제가 아니라 한 부품의 지연이 어느 BOM 행과 합격 시험을 막는지 추적하는 일입니다. 공개 roadmap은 위험 신호일 뿐 계약된 납기 증거가 아닙니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · 납품 노드 inventory",
      title: "문서의 8개가 실제 노드에서도 8개인지 확인합니다",
      question: "발주한 기준 구성과 설치된 PCIe 장치·GPU topology가 일치합니까?",
      body: "아래 명령은 제품명을 추측하려는 도구가 아니라 납품된 노드의 실물을 BOM과 대조하는 출발점입니다. 각 노드의 원문 출력을 보관하고 serial·BMC inventory와 같은 node ID로 묶습니다.",
      language: "shell",
      command: [
        "nvidia-smi -L",
        "nvidia-smi topo -m",
        "lspci -Dnn | grep -Ei 'NVIDIA|Mellanox|Non-Volatile'",
        "ip -br link",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "GPU 0 ... GPU 7                    # 8 GPU",
          "mlx5_0 ... mlx5_7                  # 8 E/W adapters",
          "GPU0↔GPU7: NVLink/NVSwitch 경로",
        ].join("\n"),
        reading: "GPU·SuperNIC 수와 GPU 간 경로가 기준 구성과 맞아야 합니다. 이름만 세지 말고 PCIe 주소와 NUMA·NIC 인접성을 node inventory에 남깁니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "GPU 0 ... GPU 7",
          "mlx5_0 ... mlx5_6                  # 한 장 부족",
          "GPU5 ↔ NIC: SYS                    # 예상보다 먼 경로",
        ].join("\n"),
        reading: "한 NIC가 없거나 예상 topology가 다르면 곧바로 케이블 문제로 단정하지 않습니다. PCIe inventory, slot population, firmware, BIOS와 OEM 설계를 순서대로 대조합니다.",
      },
      source: {
        label: "NVIDIA DGX B300 User Guide",
        href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/introduction-to-dgxb300.html",
        location: "Feature Summary의 GPU·NVSwitch·network·storage inventory",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 2 · 확장 전 port budget",
      title: "32노드 확장에서 교체할 부품을 먼저 찾습니다",
      question: "16노드를 먼저 설치한 뒤 32노드로 늘릴 때 무엇을 새로 추가하고 무엇을 교체해야 합니까?",
      body: "switch 수를 임의로 정하지 않고 endpoint·uplink·예비·장애 port를 한 표에서 셉니다. 공식 32·64·128노드 reference architecture는 비교 기준이며, 16노드안을 그대로 보증하는 제품 BOM은 아닙니다.",
      language: "text",
      command: [
        "port_budget = endpoint_ports + uplink_ports + spare_ports",
        "endpoint_ports = nodes × E/W_ports_per_node",
        "usable_ports_per_switch = physical_ports - fabric_uplinks - reserved_ports",
        "switch_count = ceil(endpoint_ports / usable_ports_per_switch)",
        "",
        "반드시 따로 기록: plane A/B, rail, breakout, optic 양 끝, cable 길이",
      ].join("\n"),
      normal: {
        label: "통과 조건",
        output: [
          "(설계 판정 예시)",
          "16→32노드: leaf 추가와 cable 추가",
          "기존 16노드 cable 재배선: 없음",
          "기존 spine 교체: 없음",
        ].join("\n"),
        reading: "증설이 add-only라면 첫 단계의 선투자 항목과 두 번째 단계의 추가 항목을 분리해 설명할 수 있습니다.",
      },
      failure: {
        label: "재설계 조건",
        output: [
          "(설계 판정 예시)",
          "32노드 확장 시 기존 leaf 전량 교체",
          "plane B uplink 공간 없음",
          "rack 간 cable reach 초과",
        ].join("\n"),
        reading: "초기 CAPEX가 싸더라도 확장 때 운영 중단과 전량 교체가 필요하면 별도 대안으로 표시해야 합니다.",
      },
      source: {
        label: "NVIDIA HGX AI Factory Logical Architecture",
        href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/network-logical-architecture.html",
        location: "4-node scalable unit, dual-plane fabric와 32·64·128-node 구성",
      },
    },
    {
      section: "source",
      eyebrow: "실물 3 · model intake receipt",
      title: "Model card의 숫자를 그대로 GPU 수로 바꾸지 않습니다",
      question: "Total 320B·active 18B라는 두 숫자에서 확정할 수 있는 것과 아직 모르는 것은 무엇입니까?",
      body: "아래 장부는 모델 이름을 받은 첫날 작성합니다. GLM-5.3-Flash 교육 과정의 축소 모델은 구조를 배우는 실험이며 production checkpoint의 대용량 계측값이 아닙니다. 실제 배포 전에는 tensor index와 dtype별 byte, target runtime의 memory profile을 다시 수집합니다.",
      language: "text",
      command: [
        "model_revision = zai-org/GLM-5.3-Flash@<commit>",
        "total_parameters = 320B                 # weight residency 입력",
        "active_parameters_per_token = 18B       # compute 경로 입력",
        "checkpoint_bytes_by_dtype = 미확정",
        "target_context / batch / concurrency = 미확정",
        "KV·recurrent_state / workspace / headroom = 미확정",
        "acceptance = target runtime에서 TTFT·TPS·p99·OOM 측정",
      ].join("\n"),
      normal: {
        label: "통과한 intake",
        output: "Model revision·dtype별 payload·context·batch·parallelism·runtime digest가 한 workload ID에 연결됨",
        reading: "이 상태라야 weight가 들어가는지와 목표 처리량이 나오는지를 서로 다른 시험으로 검증할 수 있습니다.",
      },
      failure: {
        label: "잘못된 sizing",
        output: "18B active × 2 byte만 계산해 전체 checkpoint도 한 GPU에 들어간다고 판정",
        reading: "MoE의 비활성 expert도 저장하거나 가져올 위치가 필요합니다. Active 수만으로 weight residency를 지우면 첫 배포에서 OOM 또는 offload 병목을 만납니다.",
      },
      source: {
        label: "Z.ai GLM-5.3-Flash model card",
        href: "https://huggingface.co/zai-org/GLM-5.3-Flash",
        location: "320B total·18B active와 hybrid sparse/linear architecture",
      },
    },
  ],
  sources: [
    { label: "NVIDIA HGX AI Factory · Components", href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/components.html", claim: "HGX B300 한 노드의 8 GPU, 8 ConnectX-8, GPU당 800Gb/s 외부 연결과 BlueField 권장안을 확인했습니다.", checkedAt },
    { label: "NVIDIA HGX AI Factory · Logical Architecture", href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/network-logical-architecture.html", claim: "4-node scalable unit, dual-plane rail-optimized fabric, storage·customer·management 연결의 규모별 기준을 확인했습니다.", checkedAt },
    { label: "NVIDIA DGX B300 User Guide", href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/introduction-to-dgxb300.html", claim: "DGX 완제품의 GPU·memory·network·local storage·BMC·전력 사양을 HGX 기준과 구분했습니다.", checkedAt },
    { label: "NVIDIA DGX B300 Data Center Best Practices", href: "https://docs.nvidia.com/dgx-pdf/data-center-best-practices-with-dgx-b300-v1.pdf", claim: "rack당 4대와 2대 배치, 평균·피크 전력, cable reach와 site survey 항목을 확인했습니다.", checkedAt },
    { label: "NVIDIA SuperPOD B300 Reference Architecture", href: "https://docs.nvidia.com/dgx-superpod/reference-architecture/scalable-infrastructure-b300/latest/", claim: "compute·network·storage·management가 하나의 납품 architecture로 결합되는 범위와 64-node SU 기준을 확인했습니다.", checkedAt },
    { label: "NVIDIA B300 Deployment Guide", href: "https://docs.nvidia.com/dgx-basepod/deployment-guides/dgx-basepod-b200/latest/b300/b300-nmc.html", claim: "설계 뒤 provisioning·Slurm·GPU·NCCL 검증으로 이어지는 실제 배포 순서를 확인했습니다.", checkedAt },
    { label: "Z.ai · GLM-5.3-Flash model card", href: "https://huggingface.co/zai-org/GLM-5.3-Flash", claim: "실제 공개 모델의 320B total·18B active와 hybrid sparse/linear 구조를 workload intake의 현재 근거로 확인했습니다.", checkedAt },
    { label: "GLM-5.3-Flash educational course repository", href: "https://github.com/vukrosic/glm-5.3-flash-from-scratch", claim: "25.7M 축소 모델의 코드·측정은 학습용이며 실제 320B 모델 재현이나 B300 sizing evidence가 아니라는 경계를 확인했습니다.", checkedAt },
    { label: "TSMC · 2025 Annual Report, 3DFabric", href: "https://investor.tsmc.com/static/annualReports/2025/english/pdf/2025_tsmc_ar_e_ch5.pdf", claim: "CoWoS가 logic과 HBM을 통합하는 advanced packaging 단계라는 공식 역할을 확인해 package를 독립 BOM·납기 위험으로 분리했습니다.", checkedAt },
    { label: "CHIPS · AI hardware engine course source", href: "https://github.com/kiankyars/chips", claim: "가속기를 설계·foundry·HBM·packaging·network·data center로 추적하는 강의를 gap discovery에 사용했습니다. 시장 수치와 roadmap은 공식 계약·사양 근거로 사용하지 않았습니다.", checkedAt },
    { label: "Google Cloud Engineering · AI 시대의 데이터센터 네트워크", href: "https://cloud.google.com/blog/products/networking/data-center-and-global-networks-built-for-ai-era", claim: "대규모 AI cluster에서 scale-up·scale-out·storage·front-end network를 하나의 장애 영역으로 뭉개지 않는 운영 관점을 참고했습니다. B300 BOM 수치의 근거로는 사용하지 않았습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;

export const softwareCompatibilityDepth = {
  ledgers: [
    {
      section: "source",
      title: "DGX OS 7 공개 조합의 시점 고정",
      question: "‘최신 버전’이 아니라 어느 날짜의 검증 조합을 canary에 올릴 것입니까?",
      columns: ["층", "2026-09-14 공개값", "함께 확인할 경계", "현장 기록"],
      rows: [
        ["OS·kernel", "DGX OS 7.6.0 / Ubuntu 24.04.5 / kernel 6.8.0-138", "B300 최소 지원 release와 OEM support", "/etc/dgx-release, uname -r"],
        ["GPU driver·CUDA", "580.178.04 / CUDA Toolkit 13.0 U3", "driver가 container CUDA runtime 요구를 충족하는지", "nvidia-smi, nvcc 또는 image manifest"],
        ["collective", "NCCL 2.31.2", "framework container가 실제로 load한 libnccl", "ldconfig·package·NCCL_DEBUG=VERSION"],
        ["NIC user/kernel stack", "DOCA OFED 3.2.3 LTS", "inbox OFED와 혼용 여부, kernel module build", "ofed_info, modinfo, rdma link"],
        ["NIC firmware", "ConnectX-8 40.47.3576", "adapter PSID·OEM 승인 image", "mstflint query, devlink info"],
        ["container runtime", "NVIDIA Container Toolkit 1.20.0", "containerd·Docker와 GPU injection", "nvidia-ctk, runtime config"],
      ],
      conclusion: "이 표는 2026-09-14 release notes의 공개 snapshot이지 그대로 설치하라는 처방이 아닙니다. 선택한 DGX/OEM support matrix와 application test를 통과한 행만 production baseline이 됩니다.",
    },
    {
      section: "mechanism",
      title: "한 노드 canary에서 16노드 rollout까지",
      question: "패키지 설치 성공이 아니라 어떤 순서로 계산·RDMA·collective를 다시 증명합니까?",
      columns: ["단계", "범위", "통과 증거", "실패 시 멈출 지점"],
      rows: [
        ["0. rollback 준비", "기존 image·firmware·config", "복구 image와 out-of-band 접속", "rollback 경로가 없으면 변경 금지"],
        ["1. canary host", "1 node", "GPU 8개, NIC 8개, module·firmware 일치", "inventory 차이면 package 확대 금지"],
        ["2. device path", "1 node", "CUDA sample·DCGM·PCIe·NVLink", "GPU/PCIe failure면 network test로 넘어가지 않음"],
        ["3. RDMA pair", "2 nodes", "link·GID·route·verbs transfer", "socket fallback이면 collective 숫자를 승인하지 않음"],
        ["4. collective", "2→4→16 nodes", "NCCL transport log와 bandwidth baseline", "첫 실패 규모와 rank를 보존"],
        ["5. application", "대표 training/inference", "step time·error·checkpoint와 rollback", "microbenchmark만으로 rollout 금지"],
      ],
      conclusion: "한 층이 실패하면 그 아래 시험 결과까지 함께 보존하고 확대를 멈춥니다. 1→2→4→16노드로 넓혀야 처음 어긋난 경계를 찾을 수 있습니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · host manifest",
      title: "한 번의 수집으로 여덟 층을 같은 node ID에 묶습니다",
      question: "컨테이너 digest가 같아도 host driver·NIC firmware가 다른 노드를 찾을 수 있습니까?",
      body: "출력 전문을 노드별 파일로 보관하고 package version만 복사하지 않습니다. kernel module, 실제로 load된 library, PCIe device와 firmware가 같은 node ID 아래 있어야 차이를 비교할 수 있습니다.",
      language: "shell",
      command: [
        "cat /etc/dgx-release",
        "uname -r",
        "nvidia-smi --query-gpu=name,uuid,driver_version --format=csv",
        "ldconfig -p | grep libnccl",
        "ofed_info -s",
        "rdma link show",
        "ibv_devinfo -v",
        "mstflint -d <pci-address> query",
        "nvidia-ctk --version",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "16/16 nodes: kernel=6.8.0-138-generic",
          "16/16 nodes: driver=580.178.04",
          "128/128 GPUs visible",
          "128/128 E/W RDMA ports ACTIVE",
          "firmware exception: 0",
        ].join("\n"),
        reading: "같음 자체가 성능을 보장하지는 않지만, 서로 다른 노드 하나 때문에 communicator 전체가 기다리는 위험을 먼저 제거합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "dgx-07: kernel=6.8.0-136-generic",
          "dgx-07 mlx5_4: state DOWN",
          "dgx-12: libnccl.so.2 => image-local 2.30.x",
        ].join("\n"),
        reading: "kernel 차이, link down, container 안 NCCL 차이는 서로 다른 장애입니다. ‘버전 불일치’ 하나로 묶지 말고 해당 노드를 drain한 뒤 층별로 고칩니다.",
      },
      source: {
        label: "NVIDIA DGX OS 7 Release Notes",
        href: "https://docs.nvidia.com/dgx/dgx-os-7-user-guide/release_notes.html",
        location: "Current Software Versions와 matching firmware tables",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 2 · communicator 초기화",
      title: "NCCL이 RDMA를 골랐는지 log에서 확인합니다",
      question: "all-reduce가 실행됐다는 사실과 의도한 NIC·transport를 썼다는 사실을 구분할 수 있습니까?",
      body: "debug 변수는 문제를 찾을 때만 켜고 production script에 영구 고정하지 않습니다. host별로 다른 파일에 기록해야 rank 로그가 서로 덮이지 않습니다.",
      language: "shell",
      command: [
        "export NCCL_DEBUG=INFO",
        "export NCCL_DEBUG_SUBSYS=INIT,NET,GRAPH",
        "export NCCL_DEBUG_FILE=/var/tmp/nccl.%h.%p.log",
        "srun -N2 --gpus-per-node=8 <nccl-tests-image> \\",
        "  all_reduce_perf_mpi -b 1G -e 16G -f 2 -g 8",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "NET/IB : Using [0]mlx5_0:1 ...",
          "Connected all rings",
          "Out of bounds values : 0",
        ].join("\n"),
        reading: "NET/IB transport, 선택된 HCA·port, 모든 rank 연결, data validation을 함께 봅니다. bandwidth 값은 같은 message size와 node 수의 baseline과 비교합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "NET/IB : No device found",
          "NET/Socket : Using bond0",
          "rank 13: communicator init timeout",
        ].join("\n"),
        reading: "작업이 socket fallback으로 끝날 수도 있으므로 exit code 0만 보면 놓칩니다. HCA visibility, GID·route, memory registration, firewall 순서로 좁힙니다.",
      },
      source: {
        label: "NVIDIA NCCL Environment Variables",
        href: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html",
        location: "NCCL_DEBUG·NCCL_DEBUG_SUBSYS·NCCL_DEBUG_FILE과 IB transport controls",
      },
    },
    {
      section: "limits",
      eyebrow: "실패 추적 · upgrade regression",
      title: "MOFED 의존 application이 DOCA-OFED 전환 뒤 멈춘 경우",
      question: "‘driver update가 문제’라는 추측을 재현 가능한 원인으로 어떻게 바꿉니까?",
      body: "먼저 변경 전 manifest와 canary manifest를 diff하고, 동일 image로 verbs test와 NCCL test를 각각 실행합니다. verbs부터 실패하면 application이나 NCCL을 고치지 않습니다. verbs는 통과하고 NCCL만 실패할 때 library load path와 transport log를 확인합니다.",
      language: "text",
      command: [
        "증상: canary 1대에서 multi-node job init timeout",
        "격리 1: ibv_devinfo 실패 → RDMA stack/firmware 경계",
        "격리 2: verbs 통과, NCCL socket fallback → NCCL/HCA 선택 경계",
        "격리 3: NCCL 통과, application 실패 → framework/plugin ABI 경계",
        "복구: canary rollback 후 node 재등록",
        "재발 방지: manifest diff + pair test를 rollout gate에 추가",
      ].join("\n"),
      normal: {
        label: "증거가 닫힌 상태",
        output: "변경 전·후 manifest, 첫 실패 명령, exit code, host/rank log, rollback 결과가 한 incident ID에 연결됨",
        reading: "이 정도가 있어야 ‘호환성 문제였다’가 아니라 어느 경계가 어긋났는지 설명할 수 있습니다.",
      },
      failure: {
        label: "원인을 모르는 상태",
        output: "패키지를 여러 개 동시에 갱신함 / debug log 없음 / 실패 node를 재부팅해 상태 소실 / rollback image 없음",
        reading: "원인을 증명할 수 없으므로 해결됐다고 닫지 않고, 다시 나타났을 때 수집할 증거와 변경 절차를 남깁니다.",
      },
      source: {
        label: "NVIDIA DGX OS Upgrade Advisory",
        href: "https://docs.nvidia.com/dgx/dgx-os-7-user-guide/upgrading-the-os.html",
        location: "MLNX_OFED→DOCA-OFED 전환과 selected-system validation 권고",
      },
    },
  ],
  sources: [
    { label: "NVIDIA DGX OS 7 Release Notes", href: "https://docs.nvidia.com/dgx/dgx-os-7-user-guide/release_notes.html", claim: "OS·kernel·driver·CUDA·NCCL·DOCA OFED·firmware의 공개 조합과 B300 최소 지원 release를 확인했습니다.", checkedAt },
    { label: "NVIDIA DGX OS Upgrade Guide", href: "https://docs.nvidia.com/dgx/dgx-os-7-user-guide/upgrading-the-os.html", claim: "DGX OS 6→7에서 MOFED가 DOCA-OFED로 바뀌며 일부 의존 application을 먼저 canary 검증하라는 경계를 확인했습니다.", checkedAt },
    { label: "NVIDIA DOCA Profiles", href: "https://docs.nvidia.com/doca/sdk/doca-profiles/", claim: "doca-ofed profile은 OFED driver·tool 범위이고 추가 DOCA 기능 전체와 같지 않음을 확인했습니다.", checkedAt },
    { label: "NVIDIA NCCL User Guide", href: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/index.html", claim: "NCCL은 process launcher나 scheduler가 아닌 collective communication library라는 역할을 확인했습니다.", checkedAt },
    { label: "NVIDIA NCCL Environment Variables", href: "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html", claim: "transport·interface·debug log의 공식 변수와 debug override를 production에 남기지 말라는 경고를 확인했습니다.", checkedAt },
    { label: "NVIDIA GPU Operator Platform Support", href: "https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html", claim: "Operator·driver·toolkit·device plugin·GDS와 OS·Kubernetes·runtime의 지원 조합을 별도 matrix로 확인해야 함을 반영했습니다.", checkedAt },
    { label: "NVIDIA MFT mstflint Guide", href: "https://docs.nvidia.com/networking/display/mstflint-package-firmware-burning-and-diagnostics-tools-documentation-v4-30-0.0.pdf", claim: "NIC firmware query와 image query를 구분하고 실제 adapter firmware를 manifest에 수집하는 명령을 확인했습니다.", checkedAt },
    { label: "Clio Labs · Multi-node GPU training 장애 사례", href: "https://blog.cliolabs.dev/blog/debugging-multi-node-gpu-training/", claim: "NCCL 증상에서 host network·interface 선택·container 경계로 내려가는 현장 조사 순서를 보조 사례로 검토했습니다. version 호환성의 정본은 NVIDIA 문서로 유지했습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;

export const schedulerChoiceDepth = {
  ledgers: [
    {
      section: "mechanism",
      title: "128 GPU workload를 실행 생애로 분해한 선택표",
      question: "같은 GPU 수를 요구해도 어떤 작업은 Slurm에, 어떤 작업은 Kubernetes에 더 자연스럽습니까?",
      columns: ["관찰할 조건", "8노드 training job", "상시 inference service", "선택에 주는 영향"],
      rows: [
        ["시작 조건", "64 GPU가 함께 준비돼야 함", "replica가 한 개씩 늘어도 됨", "gang·topology allocation 대 rollout"],
        ["끝 조건", "exit code와 checkpoint로 종료", "요청을 받으며 계속 실행", "batch accounting 대 controller reconciliation"],
        ["실패 처리", "전체 step 재시작·requeue", "개별 replica 교체", "job state 대 readiness·service routing"],
        ["우선순위", "queue·fair-share·reservation", "SLO·autoscaling·disruption", "사용자 대기 공정성 대 서비스 가용성"],
        ["운영 객체", "node·partition·job·step", "node·Pod·Job·Service", "같은 GPU를 두 control plane이 소유하지 않게 함"],
      ],
      conclusion: "도구 기능의 개수보다 작업이 언제 함께 시작하고, 언제 끝나며, 실패 뒤 무엇을 다시 만드는지가 선택을 가릅니다.",
    },
    {
      section: "comparison",
      title: "Operator가 같은 객체를 안전하게 되돌리는 원장",
      question: "GPU software 상태를 자동화할 때 scheduler와 다른 어떤 실패 경계를 다뤄야 합니까?",
      columns: ["관찰한 사건", "확인할 필드·동작", "잘못된 구현", "안전한 경계"],
      rows: [
        ["사용자가 spec 변경", "metadata.generation과 observedGeneration", "status 갱신도 새 설치 요청으로 처리", "Spec 변경과 status-only event를 구분하고 condition으로 완료 표시"],
        ["두 worker가 update", "metadata.resourceVersion·HTTP 409", "오래된 객체를 그대로 재전송", "충돌 때 최신 객체를 다시 읽어 RetryOnConflict"],
        ["같은 event 재전달", "동일 desired/observed state", "매번 외부 작업을 다시 생성", "Reconcile을 idempotent하게 만들고 이미 맞으면 no-op"],
        ["삭제 요청", "deletionTimestamp·finalizers", "외부 driver artifact를 남긴 채 CR 삭제", "외부 정리를 확인한 뒤 자기 finalizer만 제거"],
        ["worker 수 증가", "MaxConcurrentReconciles·queue key", "공유 외부 API와 node state를 무제한 병렬 변경", "객체 key별 직렬성에 기대지 말고 rate·shared state·idempotency 검증"],
      ],
      conclusion: "Operator는 GPU를 어느 작업에 줄지 결정하는 scheduler가 아닙니다. 선언한 GPU software 상태로 반복해서 수렴시키는 controller이며, 충돌·삭제·재전달에서도 같은 결과를 만들어야 합니다.",
    },
    {
      section: "limits",
      title: "Slurm과 Kubernetes를 함께 둘 때의 소유권 원장",
      question: "두 scheduler가 같은 16노드를 동시에 할당하지 않도록 어느 경계를 고정합니까?",
      columns: ["자원·상태", "정본 owner", "다른 쪽의 허용 범위", "충돌 신호"],
      rows: [
        ["bare-metal node allocation", "Slurm 또는 Kubernetes 중 하나", "API를 통한 요청만", "동일 GPU가 두 workload에 노출"],
        ["GPU health·driver", "공통 platform team", "scheduler는 label/state를 소비", "driver를 양쪽 operator가 갱신"],
        ["training queue", "Slurm", "Kubernetes portal은 submit·status UI", "Pod와 Slurm job이 별도 quota 소비"],
        ["inference replica", "Kubernetes", "Slurm은 전용 partition을 건드리지 않음", "service node를 batch가 선점"],
        ["accounting", "통합 cost ledger", "각 scheduler의 원자료 보존", "같은 GPU-hour 이중 집계"],
      ],
      conclusion: "공존은 두 scheduler를 같은 노드에 겹쳐 설치하는 뜻이 아닙니다. node pool·시간대·API gateway 가운데 하나로 ownership을 분리해야 합니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · Slurm GPU allocation",
      title: "8개 GPU가 있는 노드 16대를 scheduler inventory에 맞춥니다",
      question: "구성값 128과 실제 감지값 128이 다르면 node가 자동으로 격리됩니까?",
      body: "아래는 구조를 보여 주는 최소 예시입니다. CPU·memory·socket·partition 정책은 실제 B300 inventory와 site policy로 채워야 하며, 그대로 production에 복사하는 완성 설정은 아닙니다.",
      language: "slurm.conf + gres.conf",
      command: [
        "# slurm.conf (설명용 최소 예시)",
        "GresTypes=gpu",
        "SelectType=select/cons_tres",
        "NodeName=dgx-[01-16] Gres=gpu:b300:8 State=UNKNOWN",
        "PartitionName=train Nodes=dgx-[01-16] Default=YES State=UP",
        "",
        "# gres.conf",
        "AutoDetect=nvml",
        "NodeName=dgx-[01-16] Name=gpu Type=b300 File=/dev/nvidia[0-7]",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "PARTITION NODES STATE NODELIST",
          "train        16 idle  dgx-[01-16]",
          "Gres=gpu:b300:8  CfgTRES=...gres/gpu=128",
        ].join("\n"),
        reading: "node inventory와 GRES 합계가 맞아야 합니다. job은 --nodes와 --gpus-per-node를 함께 요구해 노드 수와 GPU 밀도를 명시합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "dgx-07 DRAIN Invalid gres specification",
          "configured gpu:b300:8, detected 7",
        ].join("\n"),
        reading: "부족한 GPU를 숨기고 scheduling하지 않습니다. PCIe/GPU health와 gres mapping을 고친 뒤 node를 resume합니다.",
      },
      source: {
        label: "SchedMD GRES Scheduling",
        href: "https://slurm.schedmd.com/gres.html",
        location: "GresTypes·AutoDetect·GPU request와 mismatch 시 DRAIN 동작",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 2 · 8노드 job",
      title: "allocation과 job step을 분리해 실행합니다",
      question: "64 GPU를 확보한 것과 그 위에 64개 rank를 띄운 것을 구분할 수 있습니까?",
      body: "sbatch가 node와 GPU를 예약하고, srun이 그 allocation 안에서 process를 시작합니다. pending reason을 보지 않고 ‘scheduler가 느리다’고 결론내리지 않습니다.",
      language: "bash",
      command: [
        "#!/usr/bin/env bash",
        "#SBATCH --job-name=llm-train",
        "#SBATCH --partition=train",
        "#SBATCH --nodes=8",
        "#SBATCH --gpus-per-node=8",
        "#SBATCH --exclusive",
        "#SBATCH --time=24:00:00",
        "",
        "srun --ntasks-per-node=8 \\",
        "  --gpu-bind=closest \\",
        "  ./launch-training.sh",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: "4821  train  llm-train  RUNNING  8  dgx-[01-08]",
        reading: "allocation이 8노드에 걸쳐 RUNNING이며 step의 rank 수와 CUDA_VISIBLE_DEVICES를 별도로 확인합니다.",
      },
      failure: {
        label: "대기 판독 · 예시 출력",
        output: "4821  train  llm-train  PENDING  8  (Resources)",
        reading: "PENDING은 실패가 아닙니다. Reason이 Resources인지 Priority인지, topology·reservation 조건인지 확인하고 예상 시작 시각과 fair-share를 설명합니다.",
      },
      source: {
        label: "SchedMD Quick Start and Job States",
        href: "https://slurm.schedmd.com/quickstart.html",
        location: "allocation·job step 역할과 PENDING/RUNNING 상태",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 3 · Kubernetes batch Job",
      title: "Pod 여덟 개가 생긴 것과 여덟 개가 함께 시작한 것을 구분합니다",
      question: "parallelism=8만으로 8노드 분산 학습의 공동 시작이 보장됩니까?",
      body: "아래 Job은 각 Pod가 GPU 8개를 요구한다는 사실만 표현합니다. 기본 scheduler가 Pod를 하나씩 bind할 수 있으므로, all-or-nothing 시작과 topology co-location은 사용 중인 Kubernetes version과 Kueue·JobSet 같은 통합 기능으로 별도 검증해야 합니다.",
      language: "yaml",
      command: [
        "apiVersion: batch/v1",
        "kind: Job",
        "metadata:",
        "  name: train-8x8",
        "spec:",
        "  completions: 8",
        "  parallelism: 8",
        "  completionMode: Indexed",
        "  template:",
        "    spec:",
        "      restartPolicy: Never",
        "      containers:",
        "        - name: trainer",
        "          image: registry.example/train@sha256:<digest>",
        "          resources:",
        "            limits:",
        "              nvidia.com/gpu: 8",
      ].join("\n"),
      normal: {
        label: "의도한 상태 · 예시 출력",
        output: "8 Pods: Running / 8 nodes / GPU limit 8 each / workload admitted as one group",
        reading: "Pod 수만 보지 않고 admission group, node topology, rank rendezvous와 실패 시 전체 job 동작을 확인합니다.",
      },
      failure: {
        label: "부분 시작 · 예시 출력",
        output: "6 Pods Running, 2 Pods Pending (Insufficient nvidia.com/gpu)",
        reading: "여섯 Pod가 GPU를 잡은 채 rendezvous에서 기다릴 수 있습니다. queue admission이나 gang policy가 없으면 cluster utilization도 나빠집니다.",
      },
      source: {
        label: "Kubernetes Jobs",
        href: "https://kubernetes.io/docs/concepts/workloads/controllers/job/",
        location: "parallel Jobs와 scheduling intent의 현재 semantics",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 4 · reconcile 상태",
      title: "Ready=True 한 줄보다 generation과 condition을 함께 봅니다",
      question: "Status가 바뀔 때마다 controller가 자기 자신을 다시 깨우는 loop와 오래된 완료 표시를 어떻게 구분합니까?",
      body: "아래 명령은 GPU Operator의 ClusterPolicy를 예로 든 관측 절차입니다. Custom resource의 실제 field는 설치한 Operator version의 CRD를 기준으로 확인합니다. 핵심은 desired spec의 generation과 controller가 처리했다고 기록한 observed generation, finalizer와 condition을 같은 시각에 보관하는 것입니다.",
      language: "shell",
      command: [
        "kubectl get clusterpolicy -o json | jq '{",
        "  name: .items[0].metadata.name,",
        "  generation: .items[0].metadata.generation,",
        "  resourceVersion: .items[0].metadata.resourceVersion,",
        "  deletionTimestamp: .items[0].metadata.deletionTimestamp,",
        "  finalizers: .items[0].metadata.finalizers,",
        "  status: .items[0].status",
        "}'",
        "kubectl get events -A --sort-by=.lastTimestamp | tail -n 30",
        "kubectl logs -n gpu-operator deploy/gpu-operator --since=10m",
      ].join("\n"),
      normal: {
        label: "수렴 판독 · 예시 출력",
        output: "(예시 출력 — 실측 아님)\ngeneration=7 / observedGeneration=7 / Ready=True\n같은 spec에서 반복 외부 생성 없음",
        reading: "현재 spec을 처리한 상태가 Ready이며 재전달된 event가 no-op으로 끝났는지 log와 함께 확인합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: "(예시 출력 — 실측 아님)\ngeneration=8 / observedGeneration=7 / Ready=True\n409 Conflict 반복 또는 Terminating+finalizer 정체",
        reading: "Ready가 이전 generation의 결과일 수 있습니다. Conflict면 refetch 후 제한된 재시도를, 삭제 정체면 finalizer owner의 외부 정리 실패를 먼저 찾습니다.",
      },
      source: {
        label: "Kubernetes API concepts and finalizers",
        href: "https://kubernetes.io/docs/reference/using-api/api-concepts/",
        location: "resourceVersion semantics와 finalizer deletion lifecycle",
      },
    },
  ],
  sources: [
    { label: "SchedMD Quick Start", href: "https://slurm.schedmd.com/quickstart.html", claim: "Slurm이 resource allocation, job execution, queue arbitration을 나누는 기본 모델을 확인했습니다.", checkedAt },
    { label: "SchedMD GRES Scheduling", href: "https://slurm.schedmd.com/gres.html", claim: "GPU inventory·request·CUDA_VISIBLE_DEVICES·accounting과 감지 수량 불일치 시 DRAIN 동작을 확인했습니다.", checkedAt },
    { label: "SchedMD Topology Guide", href: "https://slurm.schedmd.com/topology.html", claim: "tree·block topology가 multi-node job placement와 fragmentation에 미치는 공식 선택 기준을 확인했습니다.", checkedAt },
    { label: "SchedMD Job State Codes", href: "https://slurm.schedmd.com/job_state_codes.html", claim: "PENDING·RUNNING·FAILED·NODE_FAIL 등 state와 reason을 분리해 읽는 기준을 확인했습니다.", checkedAt },
    { label: "Kubernetes Jobs", href: "https://kubernetes.io/docs/concepts/workloads/controllers/job/", claim: "완료형 workload의 Pod 생성·재시도·parallelism과 현재 scheduling intent 범위를 확인했습니다.", checkedAt },
    { label: "Kubernetes Scheduling Framework", href: "https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/", claim: "Pod 하나의 scheduling cycle과 binding cycle이 기본 판단 단위임을 확인했습니다.", checkedAt },
    { label: "NVIDIA GPU Operator Platform Support", href: "https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html", claim: "Kubernetes에서 driver·toolkit·device plugin·DCGM을 운영할 때 OS·runtime·operator version matrix를 확인해야 함을 반영했습니다.", checkedAt },
    { label: "Kubebuilder · Good Practices", href: "https://go.kubebuilder.io/reference/good-practices.html", claim: "한 Kind당 한 controller, idempotent reconciliation과 status condition의 기본 경계를 확인했습니다.", checkedAt },
    { label: "Kubernetes · API Concepts", href: "https://kubernetes.io/docs/reference/using-api/api-concepts/", claim: "resourceVersion이 watch와 optimistic update에서 가리키는 버전 의미와 오래된 상태 처리 경계를 확인했습니다.", checkedAt },
    { label: "Kubernetes · Finalizers", href: "https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/", claim: "deletionTimestamp 뒤 외부 정리를 마칠 때까지 객체가 남고 controller가 finalizer를 제거하는 생애를 확인했습니다.", checkedAt },
    { label: "controller-runtime · predicates", href: "https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/predicate", claim: "GenerationChangedPredicate의 status-only event filter와 API별 generation caveat를 확인했습니다.", checkedAt },
    { label: "controller-runtime · controller Options", href: "https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller", claim: "MaxConcurrentReconciles가 workqueue worker 수를 정하며 같은 key는 현재 reconcile 뒤 다시 처리되는 동시성 경계를 확인했습니다.", checkedAt },
    { label: "client-go · RetryOnConflict", href: "https://pkg.go.dev/k8s.io/client-go/util/retry", claim: "409 conflict 때 매 시도 최신 객체를 다시 읽고 제한된 backoff로 update를 재시도하는 공식 패턴을 확인했습니다.", checkedAt },
    { label: "NVIDIA B300 Deployment Guide", href: "https://docs.nvidia.com/dgx-basepod/deployment-guides/dgx-basepod-b200/latest/b300/b300-nmc.html", claim: "B300 cluster에서 Slurm 설치, sinfo, GPU job과 NCCL validation의 실제 흐름을 확인했습니다.", checkedAt },
    { label: "CoreWeave Engineering · AI infrastructure goodput", href: "https://coreweave.com/blog/achieve-ai-infrastructure-goodput-of-up-to-96-with-3-key-strategies", claim: "scheduler 선택을 GPU 할당률 하나가 아니라 queue·장애 복구·checkpoint를 포함한 useful work 관점에서 보는 운영 사례를 참고했습니다. 제품 성능 보장값으로 인용하지 않았습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;

export const storageIoDepth = {
  ledgers: [
    {
      section: "mechanism",
      title: "숫자를 받기 전에 고정할 workload fingerprint",
      question: "8GB/s라는 한 줄을 실제로 재현할 입력으로 바꿀 수 있습니까?",
      columns: ["항목", "(가정) dataset read", "(가정) checkpoint write", "합격값"],
      rows: [
        ["접근 모양", "4MiB sequential, file-per-rank", "16MiB sequential, rank별 shard", "실제 trace와 같은 request size·pattern"],
        ["동시성", "16 clients × 8 ranks", "16 nodes × 8 ranks", "achieved depth와 slowest rank 기록"],
        ["완료 조건", "batch가 GPU memory에 도착", "shard·global metadata publish 완료", "application wall time과 restore 성공"],
        ["cache 상태", "cold·warm을 별도 실행", "새 checkpoint path", "page/local cache hit ratio 명시"],
        ["분포", "파일 수·p50/p99 size·directory fan-out", "shard·metadata file 수", "mdtest와 실제 open/stat trace 일치"],
        ["시간 모양", "지속 read와 shuffle", "주기적 burst, dataset read와 중첩", "평균·peak window를 따로 통과"],
      ],
      conclusion: "Request size·concurrency·sync·cache를 쓰지 않은 GB/s는 재현 가능한 요구사항이 아닙니다. 같은 수치라도 4KiB random과 4MiB sequential은 전혀 다른 system을 요구합니다.",
    },
    {
      section: "mechanism",
      title: "학습 한 회차의 I/O 예산",
      question: "200GB/s라는 기준선이 어느 데이터 이동을 위해 필요한지 설명할 수 있습니까?",
      columns: ["흐름", "설명용 입력", "필요 처리량", "별도 관측값"],
      rows: [
        ["dataset streaming", "(가정) worker 128개 × 1.0GB/s", "128GB/s read", "sample decode 뒤 GPU data starvation"],
        ["checkpoint write", "(가정) 8TB ÷ 120초", "66.7GB/s sustained write", "fsync·metadata 포함 wall time"],
        ["restart read", "(가정) 8TB ÷ 180초", "44.4GB/s sustained read", "job restart RTO와 rank별 skew"],
        ["NVIDIA sizing guideline", "12.5Gb/s/GPU × 128", "1.6Tb/s = 200GB/s aggregate", "공식 guideline이며 workload 보장은 아님"],
        ["headroom", "(가정) 목표 부하를 70% 이하로 운영", "필요치 ÷ 0.7", "failure·rebuild·동시 job에서 재검산"],
      ],
      conclusion: "dataset 128GB/s와 checkpoint 66.7GB/s가 항상 동시에 일어나는지는 workload trace로 확인해야 합니다. 둘을 무조건 더하거나 200GB/s guideline 하나로 덮지 않습니다.",
    },
    {
      section: "comparison",
      title: "benchmark를 application 요구에 연결하는 원장",
      question: "microbenchmark 숫자가 실제 training step과 checkpoint 시간을 예측합니까?",
      columns: ["시험", "고정할 조건", "관측값", "통과 판단"],
      rows: [
        ["local NVMe fio", "node·NUMA·file size·direct I/O·iodepth", "GB/s·latency percentile·achieved depth", "node staging/cache baseline"],
        ["shared IOR", "16 nodes·128 ranks·file-per-process·transfer size", "aggregate·per-rank bandwidth와 min/max", "dataset·checkpoint 큰 파일 경로"],
        ["metadata mdtest", "directory tree·files/rank·create/stat/remove", "ops/s와 rank skew", "작은 shard·checkpoint manifest 경로"],
        ["GDS gdsio", "GPU·NIC·filesystem·O_DIRECT·topology", "GPU-direct path와 fallback", "CPU bounce path와 구분"],
        ["application replay", "실제 shard·loader·checkpoint format", "step time·GPU idle·checkpoint wall time", "최종 acceptance"],
      ],
      conclusion: "fio·IOR·mdtest·gdsio는 병목 층을 분리하는 도구입니다. 최종 합격은 같은 software manifest에서 실제 data loader와 checkpoint를 다시 실행해 닫습니다.",
    },
    {
      section: "limits",
      title: "Raw에서 복구 가능한 effective capacity까지",
      question: "구매한 drive 합계와 고객이 안전하게 쓸 수 있는 용량을 구분했습니까?",
      columns: ["단계", "(가정) 2PB raw·8+2 EC", "추가 차감·확인", "승인 질문"],
      rows: [
        ["raw", "2.00PB", "제조사 단위·실제 namespace size", "실장 drive와 spare가 BOM과 같은가"],
        ["보호 후 usable", "2.00×8/10=1.60PB", "작은 object·stripe padding·metadata", "failure domain이 k+m shard를 실제로 분리하는가"],
        ["운영 reserve", "1.60×0.8=1.28PB", "rebuild·rebalance·불균형·성장", "한 node/rack 상실 뒤에도 backfill 공간이 남는가"],
        ["effective", "1.28PB에서 추가 차감", "snapshot·version·trash·compaction temp", "정책별 보존량을 실측했는가"],
        ["recoverable", "마지막 검증 checkpoint", "RPO·RTO·checksum·restore 권한", "다른 node 수로 실제 load했는가"],
      ],
      conclusion: "Raw 2PB를 usable 2PB로 제안하지 않습니다. 보호 비용, 운영 여유, snapshot·metadata와 실제 restore 가능한 세대를 별도 숫자로 남깁니다.",
    },
    {
      section: "comparison",
      title: "국내 운영 사례에서 가져온 질문",
      question: "사례의 제품과 숫자가 아니라 어떤 판단 구조를 재사용할 것입니까?",
      columns: ["사례·시점", "당시 workload와 선택", "가져올 질문", "가져오지 않을 결론"],
      rows: [
        ["Elice · 2024-06-11·2026-09-29", "ECI의 block·object·PFS 구분, DataHub S3 호환, B300 host/guest topology·동일 조건 검증", "고객 data lifecycle을 어느 interface에 두고 VM path와 physical path를 어떻게 대조할까", "미공개 PFS 제품·보호 방식·storage GB/s 추정, NCCL 결과를 storage 결과로 전용"],
        ["NAVER D2 · 2022-05-27", "Kubernetes AI platform↔HDFS 사이 Alluxio FUSE·locality cache·CACHETHROUGH", "원본은 어디며 cache invalidation과 metadata sync owner는 누구인가", "Alluxio 2.4.1의 6.4GB test 결과를 현재 보장값으로 사용"],
        ["Kakao · 2025 게시물", "Commit 간격 단축 뒤 작은 파일 증가, compaction·snapshot/orphan cleanup", "freshness를 높일 때 file count·maintenance cost·retention이 어떻게 변하는가", "약 256MB를 모든 AI dataset의 최적 shard로 사용"],
        ["우아한형제들 · 2019-03-22", "Aurora sort·group·temp와 sysbench로 R3/R4/R5 비교", "media 이름보다 실제 query·engine·instance 조합을 쟀는가", "옛 instance 결과를 현재 세대에 적용"],
        ["당근 · 2021-12-27", "온라인 DynamoDB scan 대신 change stream→S3 목적별 partition", "원본 부하를 격리하고 query pattern이 layout을 정하는가", "당시 cloud quota·buffer 값을 현재 기준으로 사용"],
      ],
      conclusion: "회사 사례는 운영 질문과 trade-off의 1차 증언입니다. Syscall·protocol semantics와 현재 version·quota는 공식 문서에서 다시 확인합니다.",
    },
    {
      section: "limits",
      title: "정상·degraded·rebuild·restore acceptance",
      question: "최고 성능 한 번이 아니라 장애 뒤에도 고객의 일을 끝낼 수 있습니까?",
      columns: ["상태", "주입·조건", "함께 볼 지표", "통과 기준 예"],
      rows: [
        ["정상 steady state", "precondition 후 30분 이상 대표 workload", "app wall time·p99·slowest rank·client/NIC/server/drive", "dataset·checkpoint SLO와 error 0"],
        ["degraded", "허용된 drive·node·path 하나 중단", "retry·queue·tail·GPU wait·data availability", "무중단 또는 합의한 failover 시간"],
        ["rebuild/backfill", "복구 traffic과 실제 workload 동시 실행", "rebuild ETA·foreground SLO·공간·두 번째 실패 여유", "SLO 하한과 reserve 유지"],
        ["metadata fault", "metadata service failover·작은 파일 폭주", "create/open/stat p99·lock·client recovery", "namespace 일관성과 mdtest/application 목표"],
        ["restore", "마지막 complete checkpoint를 다른 node 수에 load", "checksum·RPO·RTO·optimizer step parity", "목표 step에서 training 재개"],
      ],
      conclusion: "Replication과 snapshot이 있다는 설명은 restore 증거가 아닙니다. 장애를 주입하고 마지막 complete 세대를 실제 application으로 읽은 기록이 acceptance artifact입니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · local file commit 의사코드",
      title: "write 반환과 crash-safe publish를 같은 말로 부르지 않습니다",
      question: "완료 표시가 보일 때 data와 directory entry도 전원 장애 뒤 남습니까?",
      body: "아래는 같은 local filesystem에서 임시 파일을 완성한 뒤 이름을 바꾸는 최소 순서입니다. Distributed filesystem과 object storage의 commit semantics는 해당 제품 문서와 fault test로 다시 확인해야 합니다.",
      language: "python · 의사코드",
      command: [
        "# 설명용 축약 코드: 실제 checkpoint는 checksum·rank coordination이 더 필요",
        "with open(tmp_path, 'wb') as f:",
        "    f.write(payload)",
        "    f.flush()",
        "    os.fsync(f.fileno())       # file data와 필요한 metadata 완료 대기",
        "os.replace(tmp_path, final_path) # 같은 mount 안에서 이름 교체",
        "dir_fd = os.open(parent, os.O_DIRECTORY)",
        "os.fsync(dir_fd)               # 새 directory entry의 durability 경계",
        "os.close(dir_fd)",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시",
        output: "(예시 출력 — fault injection 필요)\nfsync(file)=0 → rename=0 → fsync(directory)=0 → checksum/restore PASS",
        reading: "각 반환값과 마지막 complete manifest를 보존합니다. 전원을 끊거나 process를 죽인 뒤 final_path만 restart 후보로 보이는지 확인해야 합니다.",
      },
      failure: {
        label: "위험한 완료 정의",
        output: "write() bytes == payload bytes → checkpoint complete 표시\nprocess crash 뒤 zero-length·missing shard 또는 stale manifest",
        reading: "User buffer를 kernel이 받았다는 사실만으로 durable checkpoint라고 판정한 경우입니다. O_DIRECT도 이 durability 단계를 자동으로 대신하지 않습니다.",
      },
      source: {
        label: "Linux man-pages · fsync(2), open(2), rename(2)",
        href: "https://man7.org/linux/man-pages/man2/fsync.2.html",
        location: "file·directory fsync, O_DIRECT와 O_SYNC의 경계, 같은 filesystem rename의 atomic replacement",
      },
    },
    {
      section: "source",
      eyebrow: "실물 2 · Linux 원문 구조체",
      title: "Page cache와 block request가 맡은 상태를 원문에서 읽습니다",
      question: "4MiB 요청을 추적할 때 kernel의 어느 구조가 cached page와 block 전송 상태를 들고 있습니까?",
      body: "아래는 Linux master의 `include/linux/fs.h`에 있는 `struct address_space`에서 이 글의 경로에 필요한 필드만 연속으로 발췌한 것입니다. `i_pages`는 file의 cached page를 찾는 mapping이고 `nrpages`는 현재 page 수, `a_ops`는 filesystem별 동작, `wb_err`는 뒤늦게 발견된 writeback error를 보존합니다.",
      language: "c · Linux 원문 발췌",
      command: [
        "struct address_space {",
        "    struct inode *host;",
        "    struct xarray i_pages;",
        "    struct rw_semaphore invalidate_lock;",
        "    gfp_t gfp_mask;",
        "    atomic_t i_mmap_writable;",
        "    struct rb_root_cached i_mmap;",
        "    unsigned long nrpages;",
        "    pgoff_t writeback_index;",
        "    const struct address_space_operations *a_ops;",
        "    unsigned long flags;",
        "    errseq_t wb_err;",
        "    spinlock_t i_private_lock;",
        "    struct rw_semaphore i_mmap_rwsem;",
        "} __attribute__((aligned(sizeof(long)))) __randomize_layout;",
      ].join("\n"),
      normal: {
        label: "4MiB 사례에 적용",
        output: "pread64(..., 4194304, offset)\n→ i_pages에서 cache hit/miss 확인\n→ miss이면 a_ops를 통해 filesystem read 경로 시작\n→ 완료 뒤 4MiB가 user buffer로 반환",
        reading: "이 구조체만으로 device queue 시간은 보이지 않습니다. `bio`와 blk-mq `request`, 원격 filesystem이면 client·NIC·server 측 시간을 이어야 처음 느려진 구간이 닫힙니다.",
      },
      failure: {
        label: "원문이 막아 주는 오해",
        output: "pread64가 빨리 반환됨 → NVMe가 빨랐음",
        reading: "`i_pages`의 cache hit였을 수 있으므로 이 결론은 성립하지 않습니다. 그래서 buffered read와 direct I/O 시험을 분리합니다.",
      },
      source: {
        label: "Linux source · include/linux/fs.h",
        href: "https://github.com/torvalds/linux/blob/master/include/linux/fs.h",
        location: "struct address_space; 확인일 2026-10-08",
      },
    },
    {
      section: "source",
      eyebrow: "실물 3 · 한 요청의 관측 경로",
      title: "Application syscall과 device queue를 같은 시각에 봅니다",
      question: "느린 4MiB read가 page cache, filesystem, network, device 중 어디에서 기다렸습니까?",
      body: "먼저 mount와 backing device를 확인하고, 한 process의 syscall 시간을 좁혀 본 뒤 같은 시간의 extended device 지표를 대조합니다. Production 전체에 무분별하게 strace를 붙이지 않고 대표 process와 짧은 창에서 영향도를 확인합니다.",
      language: "shell",
      command: [
        "findmnt -T /checkpoint -o TARGET,SOURCE,FSTYPE,OPTIONS",
        "lsblk -o NAME,KNAME,TYPE,SIZE,FSTYPE,MOUNTPOINTS,MODEL,SERIAL",
        "strace -ff -ttT -e trace=openat,read,pread64,write,pwrite64,fsync,fdatasync,rename \\",
        "  -o /tmp/checkpoint.trace -- <representative-checkpoint-command>",
        "iostat -xmd 1",
        "# NVMe가 backing device일 때 read-only health 확인",
        "nvme smart-log /dev/nvme0",
      ].join("\n"),
      normal: {
        label: "상관관계가 닫힌 예 · 예시 출력",
        output: "(예시 출력 — 실측 아님)\n12:00:04.120 pwrite64(..., 4194304, ...) = 4194304 <0.0041>\n12:00:04.125 fsync(17) = 0 <0.0182>\nnvme0n1 await=3.9ms aqu-sz=8.3 util=71%",
        reading: "4MiB write의 syscall 시간, fsync 대기와 device queue가 같은 window에서 움직입니다. Remote filesystem이면 client protocol·NIC·server 지표를 이 사이에 추가합니다.",
      },
      failure: {
        label: "경로가 닫히지 않은 예",
        output: "GPU util 20% / disk util 99% / filesystem·mount·process timestamp 없음",
        reading: "Disk busy와 GPU idle이 같은 원인이라는 증거가 없습니다. Page cache hit, CPU decode, 다른 tenant I/O도 같은 증상을 만들 수 있습니다.",
      },
      source: {
        label: "Linux Kernel · VFS and blk-mq",
        href: "https://docs.kernel.org/block/blk-mq.html",
        location: "address_space writeback, bio/request, software staging queue와 hardware dispatch queue의 책임",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 4 · Elice 공개 자료의 사용법",
      title: "공개된 interface와 미공개 구현을 한 문장에 섞지 않습니다",
      question: "ECI에 block·object·PFS가 있다는 사실만으로 고객 데이터의 배치와 성능을 결정할 수 있습니까?",
      body: "Elice Cloud 도움말은 사용할 수 있는 저장 interface를 확인하는 출발점입니다. B300 기술 글은 GPU·NIC·NVMe inventory, physical topology, host/guest의 동일 version과 동일 benchmark를 대조하는 검증법을 보여 줍니다. 하지만 공개 자료만으로 PFS 제품·보호 방식·metadata 구조·보장 처리량을 확정할 수는 없습니다.",
      language: "text",
      command: [
        "공개 자료로 확인한 사실",
        "  ECI: block storage / object storage / parallel file system",
        "  DataHub: S3-compatible object storage",
        "  B300 검증: GPU·NIC·NVMe inventory와 topology 확인",
        "             host/guest의 driver·Fabric Manager·CUDA·NCCL 조건 통제",
        "",
        "제안 전에 답을 받아야 할 질문",
        "  1. 원본 dataset·hot shard·checkpoint·artifact의 source of truth는 어디인가?",
        "  2. PFS의 namespace·striping·metadata·failure domain은 어떻게 구성되는가?",
        "  3. VM virtual block I/O는 어느 physical device·network·cache를 통과하는가?",
        "  4. 정상·degraded·rebuild 중 어떤 workload로 몇 GB/s·p99를 보장하는가?",
        "  5. object upload 완료와 학습 재시작 가능 시점은 같은가?",
      ].join("\n"),
      normal: {
        label: "근거에 맞는 답",
        output: "공개 문서로 interface와 검증 방법을 확인했습니다. 제품·보호 방식·성능은 discovery와 PoC에서 확정하겠습니다.",
        reading: "확인된 사실, 설계 가정, 고객에게 물을 질문, 시험할 항목이 분리되어 있습니다.",
      },
      failure: {
        label: "근거를 넘은 답",
        output: "Elice PFS는 128 B300에 200GB/s를 보장하고 Ceph EC로 보호됩니다.",
        reading: "공개되지 않은 제품과 수치를 지어냈고 NCCL·GPU 검증 결과를 storage 성능으로 바꿨습니다. 제안서에 쓰면 안 됩니다.",
      },
      source: {
        label: "Elice Cloud 도움말과 B300 기술 블로그",
        href: "https://help.elice.io/help/docs/cloud-overview",
        location: "ECI storage interface와 B300 host/guest 검증 절차의 공개 범위",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 5 · local NVMe",
      title: "page cache가 아니라 장치를 읽었는지 확인합니다",
      question: "메모리 cache 속도를 NVMe 성능으로 잘못 보고 있지 않습니까?",
      body: "아래 read test는 미리 준비한 benchmark 전용 파일에서만 실행합니다. production dataset이나 filesystem에 임의로 write test를 실행하지 않습니다. direct=1과 achieved depth를 함께 확인해야 합니다.",
      language: "shell",
      command: [
        "fio --name=local-seq-read \\",
        "  --filename=/benchmark-only/fio-1t.bin \\",
        "  --readonly --rw=read --bs=1M \\",
        "  --ioengine=io_uring --iodepth=32 --direct=1 \\",
        "  --numjobs=8 --time_based --runtime=300 \\",
        "  --group_reporting --output-format=json",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "read.bw_bytes: 25000000000",
          "read.iops: 23841",
          "iodepth_level[32]: 99.4%",
          "clat_ns.p99: 4200000",
        ].join("\n"),
        reading: "25GB/s만 보지 않고 iodepth 32가 실제로 유지됐는지, p99 latency와 thermal throttling이 안정적인지 봅니다.",
      },
      failure: {
        label: "잘못된 시험 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "direct=0",
          "runtime=5s",
          "read bandwidth > device specification",
          "iodepth_level[1]: 100%",
        ].join("\n"),
        reading: "짧은 buffered read가 page cache를 읽었거나 synchronous path에서 depth가 적용되지 않았을 수 있습니다. 이 결과로 storage BOM을 승인하지 않습니다.",
      },
      source: {
        label: "fio Documentation",
        href: "https://fio.readthedocs.io/en/latest/fio_doc.html",
        location: "direct I/O, ioengine, iodepth와 achieved depth 해석",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 6 · 16노드 shared storage",
      title: "큰 파일 처리량과 metadata 처리량을 따로 잽니다",
      question: "체크포인트는 빠른데 수백만 shard를 열 때 느린 storage를 구분할 수 있습니까?",
      body: "IOR는 큰 payload 경로를, mdtest는 create·stat·remove 같은 metadata 경로를 봅니다. 경로·rank 수·file layout을 실제 workload와 맞추지 않으면 높은 숫자도 의미가 없습니다.",
      language: "shell",
      command: [
        "# 비어 있는 benchmark 전용 경로에서만 실행",
        "srun -N16 -n128 ior -a POSIX -w -r -F -e \\",
        "  -i 3 -t 4m -b 64g -o /benchmark-only/ior/file",
        "",
        "srun -N16 -n128 mdtest \\",
        "  -d /benchmark-only/mdtest -n 10000 -i 3",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "IOR write aggregate: 82 GB/s, rank min/max gap 11%",
          "IOR read aggregate: 146 GB/s",
          "mdtest create: 510k ops/s, stat: 1.4M ops/s",
        ].join("\n"),
        reading: "checkpoint 목표 66.7GB/s는 넘었지만 200GB/s guideline에는 못 미칩니다. 어떤 요구를 통과했고 어떤 headroom이 부족한지 따로 기록합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "IOR average: 94 GB/s, slowest rank: 0.9 GB/s",
          "mdtest create collapses after 500k files",
        ].join("\n"),
        reading: "aggregate 평균이 높아도 한 rank가 느리면 synchronous training이 기다립니다. client mount, metadata server, network path와 storage rebuild 상태를 분리해 봅니다.",
      },
      source: {
        label: "HPC IOR and mdtest",
        href: "https://github.com/hpc/ior",
        location: "parallel payload I/O와 metadata benchmark의 공식 project",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 7 · async checkpoint 원문",
      title: "GPU가 다시 계산하기 시작한 시각과 저장 완료 시각을 나눕니다",
      question: "async_save 호출 뒤 training이 재개됐다는 사실을 durable checkpoint 완료로 기록하고 있지 않습니까?",
      body: "아래 발췌는 PyTorch 공식 recipe에서 설명 주석만 덜어낸 부분입니다. `async_save()`가 돌려준 Future를 다음 저장 전에 `result()`로 기다립니다. 공식 설명처럼 state는 먼저 CPU buffer로 복사되므로 GPU 정지 시간, background 저장 시간, rank당 CPU memory를 따로 재야 합니다.",
      language: "python · PyTorch 공식 예제 발췌",
      command: [
        "checkpoint_future = None",
        "for step in range(10):",
        "    optimizer.zero_grad()",
        "    model(torch.rand(8, 16, device=\"cuda\")).sum().backward()",
        "    optimizer.step()",
        "    if checkpoint_future is not None:",
        "        checkpoint_future.result()",
        "    state_dict = { \"app\": AppState(model, optimizer) }",
        "    checkpoint_future = dcp.async_save(state_dict, checkpoint_id=f\"{CHECKPOINT_DIR}_step{step}\")",
      ].join("\n"),
      normal: {
        label: "두 시간을 기록한 예",
        output: "GPU pause 8.4s / background write 71.2s / Future success / restore checksum PASS",
        reading: "Training은 staging 뒤 재개됐지만 복구 가능한 완료 시점은 Future와 publish 이후입니다. CPU·pinned memory peak와 동시 checkpoint 수도 함께 기록합니다.",
      },
      failure: {
        label: "완료를 앞당겨 기록한 예",
        output: "async_save returned → checkpoint complete\nnode failure during background write → latest generation cannot restore",
        reading: "함수 반환을 durable completion으로 오해했습니다. 직전 complete generation을 유지하고 Future 실패·timeout을 운영 상태로 노출해야 합니다.",
      },
      source: {
        label: "PyTorch Distributed Checkpoint",
        href: "https://docs.pytorch.org/tutorials/recipes/distributed_async_checkpoint_recipe.html",
        location: "CPU staging, background save, Future 관리와 memory overhead",
      },
    },
    {
      section: "limits",
      eyebrow: "실물 8 · degraded와 rebuild",
      title: "복제 수와 EC 비율을 복구 성능으로 대신하지 않습니다",
      question: "한 저장 장치나 node가 빠진 뒤 foreground workload와 rebuild가 함께 살아남습니까?",
      body: "아래 명령은 Ceph를 예로 cluster state와 placement group의 recovery를 읽는 방법을 보여 줍니다. Elice가 Ceph를 사용한다는 뜻은 아닙니다. 실제 제품에서도 동등한 health·degraded object·rebuild progress·failure-domain 증거를 받아야 합니다.",
      language: "shell",
      command: [
        "ceph -s",
        "ceph health detail",
        "ceph pg stat",
        "ceph osd df tree",
        "",
        "# 같은 시간에 대표 dataset read·checkpoint write를 계속 실행",
        "# application p99, slowest rank, error, rebuild ETA, free reserve를 함께 저장",
      ].join("\n"),
      normal: {
        label: "정상과 복구를 구분한 예",
        output: "steady: all PGs active+clean\nfault: degraded objects observed\nrecovery: recovering/backfilling + foreground SLO PASS\nend: active+clean + checksum/restore PASS",
        reading: "장애 감지, 데이터 가용성, 복구 중 성능, 복구 종료와 무결성을 한 사건의 시간축으로 보존합니다.",
      },
      failure: {
        label: "구성만 확인한 예",
        output: "8+2 EC이므로 drive 두 개 장애까지 안전함 → acceptance PASS",
        reading: "Shard가 같은 failure domain에 놓였거나 reserve가 부족하고 rebuild 중 두 번째 장애가 생길 수 있습니다. 설정값은 실제 배치·복구·restore 증거가 아닙니다.",
      },
      source: {
        label: "Ceph PG monitoring and recovery",
        href: "https://docs.ceph.com/en/latest/rados/operations/monitoring-osd-pg/",
        location: "active+clean, degraded, recovering, backfilling state와 health 관측",
      },
    },
    {
      section: "limits",
      eyebrow: "실패 추적 · GPU starvation",
      title: "GPU 사용률이 출렁일 때 storage부터 탓하지 않습니다",
      question: "data loader, CPU decode, network, filesystem 가운데 어느 구간이 GPU를 굶겼습니까?",
      body: "한 training step에서 read 요청 시각, storage latency, CPU decode queue, host-to-device copy, GPU kernel 시작 시각을 같은 timeline에 놓습니다. storage가 200GB/s를 냈다는 별도 시험만으로 application 병목을 부정할 수 없습니다.",
      language: "text",
      command: [
        "증상: GPU util 95%→20%가 주기적으로 반복",
        "1. per-rank dataloader wait와 queue depth 기록",
        "2. client read latency·throughput과 NIC counter 대조",
        "3. CPU decode·memory pressure·NUMA placement 확인",
        "4. local cache hit/miss와 shared filesystem 요청 분리",
        "5. 같은 batch를 local NVMe에서 replay",
        "6. 원인 층을 고친 뒤 실제 step time 재측정",
      ].join("\n"),
      normal: {
        label: "storage 원인으로 닫힌 예",
        output: "shared read latency 상승과 dataloader wait가 같은 시각에 증가하고 local NVMe replay에서는 사라짐",
        reading: "재현과 대조군이 있으므로 shared path를 다음 조사 대상으로 좁힐 수 있습니다.",
      },
      failure: {
        label: "성급한 결론의 예",
        output: "GPU util이 낮음 → storage가 느림 / storage vendor benchmark가 높음 → storage 문제 아님",
        reading: "둘 다 요청 경로를 측정하지 않은 추측입니다. application과 subsystem 시간을 같은 축에 놓기 전에는 원인으로 확정하지 않습니다.",
      },
      source: {
        label: "NVIDIA GPUDirect Storage Benchmarking Guide",
        href: "https://docs.nvidia.com/gpudirect-storage/configuration-guide/",
        location: "page cache·filesystem·network·GDS path를 분리하는 benchmark 원칙",
      },
    },
  ],
  sources: [
    { label: "NVIDIA HGX AI Factory · Certified Storage", href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/nvidia-certified-storage.html", claim: "GPU당 약 12.5Gb/s를 배정하는 storage sizing guideline과 certified 범위를 확인했습니다.", checkedAt },
    { label: "NVIDIA HGX AI Factory · Logical Architecture", href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/network-logical-architecture.html", claim: "규모별 storage connection 수와 GPU당 최소 bandwidth가 network architecture에 어떻게 반영되는지 확인했습니다.", checkedAt },
    { label: "NVIDIA HGX AI Factory · Node Configurations", href: "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/appendix-node-configurations.html", claim: "training node의 local NVMe 기준을 shared source of truth가 아닌 staging/cache 설계 입력으로 사용했습니다.", checkedAt },
    { label: "NVIDIA GPUDirect Storage Documentation", href: "https://docs.nvidia.com/gpudirect-storage/index.html", claim: "storage와 GPU memory 사이 direct DMA path, cuFile·cuObject, validation 문서의 범위를 확인했습니다.", checkedAt },
    { label: "NVIDIA GDS Benchmarking Guide", href: "https://docs.nvidia.com/gpudirect-storage/configuration-guide/", claim: "page cache를 우회한 측정, filesystem·network·PCIe 병목과 gdsio 사용 경계를 확인했습니다.", checkedAt },
    { label: "fio Documentation", href: "https://fio.readthedocs.io/en/latest/fio_doc.html", claim: "direct I/O, ioengine, iodepth, achieved depth와 JSON 결과를 재현 가능하게 고정하는 옵션을 확인했습니다.", checkedAt },
    { label: "HPC IOR and mdtest", href: "https://github.com/hpc/ior", claim: "MPI 기반 parallel I/O와 metadata benchmark를 다른 질문에 사용하는 공식 project 문서를 확인했습니다.", checkedAt },
    { label: "Linux Virtual File System", href: "https://docs.kernel.org/filesystems/vfs.html", claim: "page cache의 address_space, dirty·writeback과 filesystem operation 경계를 확인했습니다.", checkedAt },
    { label: "Linux blk-mq", href: "https://docs.kernel.org/block/blk-mq.html", claim: "bio가 request로 합쳐지고 software staging queue와 hardware dispatch queue를 통과하는 block I/O 경로를 확인했습니다.", checkedAt },
    { label: "Linux man-pages · fsync(2)", href: "https://man7.org/linux/man-pages/man2/fsync.2.html", claim: "write 반환, file fsync와 directory entry durability가 서로 다른 완료 경계임을 확인했습니다.", checkedAt },
    { label: "CMU · Little's Law", href: "https://www.cs.cmu.edu/~harchol/Perfclass/NotesFall25/chpt6prep.pdf", claim: "처리량과 평균 응답 시간에서 평균 in-flight 요청 수를 검산하는 관계를 확인했습니다.", checkedAt },
    { label: "NVM Express Base Specification", href: "https://nvmexpress.org/specification/nvm-express-base-specification/", claim: "NVMe queue·command semantics를 장치의 지속 성능과 분리했습니다.", checkedAt },
    { label: "Ceph Erasure Coding", href: "https://docs.ceph.com/en/umbrella/rados/operations/erasure-code/", claim: "k+m shard, failure-domain 배치와 EC의 capacity·recovery trade-off를 확인했습니다. Elice 구현으로 추정하지 않았습니다.", checkedAt },
    { label: "Ceph PG Monitoring", href: "https://docs.ceph.com/en/latest/rados/operations/monitoring-osd-pg/", claim: "degraded·recovering·backfilling·active+clean 상태를 acceptance 시간축에 넣었습니다.", checkedAt },
    { label: "MLCommons Storage", href: "https://github.com/mlcommons/storage", claim: "AI training과 checkpointing을 file·object backend에서 workload 조건과 함께 재현하는 benchmark 원칙을 확인했습니다.", checkedAt },
    { label: "PyTorch Distributed Checkpoint", href: "https://docs.pytorch.org/tutorials/recipes/distributed_async_checkpoint_recipe.html", claim: "async checkpoint의 CPU staging, Future 완료와 memory overhead 경계를 확인했습니다.", checkedAt },
    { label: "Elice Cloud Overview", href: "https://help.elice.io/help/docs/cloud-overview", claim: "ECI의 block·object·parallel filesystem과 Elice AI Cloud의 block·DataHub object interface 공개 범위를 확인했습니다.", checkedAt },
    { label: "Elice · B300 GPU 가상화", href: "https://elice.io/ko/resources/blog/eci-b300-gpu-virtualization", claim: "GPU·NIC·NVMe inventory, physical topology와 host/guest 동일 version·benchmark 대조법을 참고했습니다. Storage 성능 주장으로 확대하지 않았습니다.", checkedAt },
    { label: "NAVER D2 · Alluxio 도입기", href: "https://d2.naver.com/helloworld/3863967", claim: "AI platform과 HDFS 사이 locality cache·CACHETHROUGH·metadata sync trade-off를 당시 사례로 확인했습니다.", checkedAt },
    { label: "Kakao · Iceberg 운영", href: "https://tech.kakao.com/posts/694", claim: "Commit 주기, small file, compaction·snapshot expiration·orphan cleanup이 함께 움직이는 운영 사례를 확인했습니다.", checkedAt },
    { label: "우아한형제들 · Aurora storage 비교", href: "https://techblog.woowahan.com/2621/", claim: "Storage media 이름이 아니라 실제 sort·group·temporary workload와 engine 조합을 측정하는 방법을 참고했습니다.", checkedAt },
    { label: "당근 · DynamoDB change pipeline", href: "https://medium.com/daangn/dynamodb-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B3%80%EA%B2%BD-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-feat-kinesis-1733db06066", claim: "Online source 부하를 change stream으로 격리하고 S3 layout을 access pattern에 맞춘 사례를 확인했습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;

export const rackPowerCoolingDepth = {
  ledgers: [
    {
      section: "mechanism",
      title: "16대의 전력 숫자를 배전 방식별로 다시 계산",
      question: "14.5kW와 19kW를 AC 구성에도 그대로 쓰고 있지 않습니까?",
      columns: ["구성", "노드 평균", "노드 피크", "16대 평균", "16대 피크", "빠진 부하"],
      rows: [
        ["DC busbar + active RDHx", "14.5kW", "19.0kW", "232.0kW", "304.0kW", "power shelf·RDHx·CDU·network·storage"],
        ["AC rack PDU + air", "15.0kW", "19.7kW", "240.0kW", "315.2kW", "rack PDU loss·network·storage·room cooling"],
        ["high-density 4 systems/rack", "58.0kW/rack", "76.0kW/rack", "4 racks", "4 racks", "DC power shelf와 water-side equipment"],
        ["low-density 2 systems/rack", "30.0kW/rack", "39.4kW/rack", "8 racks", "8 racks", "airflow·aisle·CRAH capacity"],
      ],
      conclusion: "GPU server만 합산한 232kW를 facility 요구량이라고 부르면 안 됩니다. 배전 방식과 auxiliary load를 확정한 뒤 IT load, rack input, cooling plant load를 서로 다른 행으로 유지합니다.",
    },
    {
      section: "mechanism",
      title: "전력과 열 제거를 같은 단위로 잇는 원장",
      question: "rack input이 늘었을 때 어느 전기 경로와 어느 열 제거 경로가 먼저 한계에 닿습니까?",
      columns: ["경계", "평균 조건", "피크·N−1 조건", "필요한 현장 증거"],
      rows: [
        ["utility→UPS/PDU", "compute 232kW + auxiliary", "304kW + 한 feed/모듈 고장", "single-line diagram, breaker·cable·protection study"],
        ["rack input", "DC rack 58kW", "DC rack 76kW", "busbar/power shelf rating과 A/B 실제 분담"],
        ["server air", "노드당 최대 약 2,145 CFM 요구", "inlet·altitude·filter pressure 반영", "rack inlet temperature와 fan telemetry"],
        ["RDHx water side", "(가정) 평균 열의 90% 포집 시 rack당 52.2kW", "(가정) peak 68.4kW", "vendor duty point의 flow·ΔT·pressure drop"],
        ["room air", "RDHx가 못 잡은 열 + 다른 장비", "door·pump failure와 bypass", "CRAH/CRAC capacity와 aisle temperature"],
      ],
      conclusion: "전력과 냉각을 따로 승인하지 않습니다. 한 feed나 pump를 잃은 상태에서도 server inlet과 전기 보호 한계를 넘지 않는지 같은 load case로 계산합니다.",
    },
    {
      section: "comparison",
      title: "물 유량은 열교환기의 첫 검산일 뿐",
      question: "평균 부하에서 구한 5kg/s를 pipe·pump 설계값으로 오해하고 있지 않습니까?",
      columns: ["조건", "제거할 열 Q", "가정 ΔT", "필요 질량유량 Q/(cp·ΔT)", "해석"],
      rows: [
        ["16대 평균의 90% 포집", "208.8kW", "10°C", "약 4.99kg/s", "전체 4 rack 합계의 첫 검산"],
        ["16대 피크의 90% 포집", "273.6kW", "10°C", "약 6.54kg/s", "peak와 redundancy 검토 입력"],
        ["rack당 평균", "52.2kW", "10°C", "약 1.25kg/s", "manifold·door duty point와 대조"],
        ["rack당 피크", "68.4kW", "10°C", "약 1.63kg/s", "한 pump/CDU 경로 고장 상태 별도"],
      ],
      conclusion: "물의 비열 4.186kJ/(kg·K)를 쓴 설명용 계산입니다. 실제 유량은 glycol 비율, 공급·환수 온도, pressure drop, fouling, water quality와 vendor curve를 넣어 설비 엔지니어가 승인해야 합니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · electrical sanity check",
      title: "rack kW를 삼상 전류로 바꿔 회로표와 대조합니다",
      question: "76kW peak rack이 400V 삼상 feed 한 개에 들어간다는 가정을 검산했습니까?",
      body: "아래 식은 balanced three-phase와 power factor 0.99를 가정한 첫 계산입니다. breaker, cable, harmonic, protection coordination과 지역 법규를 대신하지 않습니다.",
      language: "calculation",
      command: [
        "I = P / (sqrt(3) × V_line × PF)",
        "",
        "P = 76,000 W",
        "V_line = 400 V",
        "PF = 0.99",
        "I ≈ 110.8 A",
        "",
        "80% continuous-load derating을 적용하는 관할권의 단일 125A 회로:",
        "usable ≈ 100 A → 76kW peak를 단일 경로로 감당하지 못함",
      ].join("\n"),
      normal: {
        label: "올바른 판독",
        output: "공식 high-density 표는 utility source당 여러 3상 회로와 2N 구성을 제시하며, rack peak와 한 경로 고장을 함께 검토함",
        reading: "단순 전류 계산을 공식 회로표와 single-line diagram의 교차 검산으로 사용합니다.",
      },
      failure: {
        label: "위험한 판독",
        output: "평균 58kW < 회로 명판 63kW이므로 통과",
        reading: "평균과 peak를 섞었고 voltage·PF·derating·A/B failure를 빠뜨렸습니다. 이 계산으로 breaker나 cable을 선정하면 안 됩니다.",
      },
      source: {
        label: "NVIDIA DGX B300 Data Center Best Practices",
        href: "https://docs.nvidia.com/dgx-pdf/data-center-best-practices-with-dgx-b300-v1.pdf",
        location: "Power Provisioning tables의 voltage·current·derating·circuit count",
      },
    },
    {
      section: "comparison",
      eyebrow: "실물 2 · RDHx와 DLC 경계",
      title: "B300 고밀도 rack은 물이 칩으로 들어가는 구성이 아닙니다",
      question: "rear door water loop를 direct-to-chip liquid cooling이라고 부르고 있지 않습니까?",
      body: "DGX B300 DC busbar high-density 기준은 server 내부 fan이 공기로 열을 운반하고, active rear door heat exchanger가 rack 배기 공기에서 물로 열을 넘깁니다. cold plate와 server liquid connector를 쓰는 DLC와 failure boundary가 다릅니다.",
      language: "text",
      command: [
        "DGX B300 server",
        "  GPU/CPU → server fan → hot exhaust air",
        "  hot air → active RDHx coil → facility water",
        "  cooled air → room",
        "",
        "DLC system",
        "  GPU/CPU → cold plate → technology cooling loop → CDU",
        "",
        "공통점: 최종 열은 water side로 이동",
        "차이: 물이 server/chip 경계 안으로 들어가는가",
      ].join("\n"),
      normal: {
        label: "RDHx 검수 항목",
        output: "door fan·pump power, water supply/return, flow, pressure drop, condensate risk, door-open/bypass, residual room heat",
        reading: "rack rear door와 room airflow가 열 제거 경로의 일부이므로 door·fan·water failure를 함께 시험합니다.",
      },
      failure: {
        label: "DLC 항목을 잘못 적용한 경우",
        output: "server cold plate leak sensor와 quick disconnect만 검수하고 rack exhaust·door fan을 확인하지 않음",
        reading: "냉각 방식의 경계를 잘못 잡으면 실제 주요 장애점이 시험에서 빠집니다.",
      },
      source: {
        label: "NVIDIA DGX B300 Data Center Best Practices",
        href: "https://docs.nvidia.com/dgx-pdf/data-center-best-practices-with-dgx-b300-v1.pdf",
        location: "DC busbar high-density의 active RDHx와 AC low-density의 air cooling",
      },
    },
    {
      section: "limits",
      eyebrow: "실물 3 · 운영 telemetry",
      title: "설계값과 실제 rack power를 같은 시간축에 놓습니다",
      question: "nameplate·예상 평균·실제 평균·짧은 peak를 서로 다른 숫자로 저장합니까?",
      body: "BMC의 Redfish service root에서 실제 chassis ID와 지원 resource를 먼저 찾습니다. 아래 URI의 <chassis-id>를 임의로 고정하지 말고 설치된 BMC가 반환한 링크를 사용합니다.",
      language: "shell",
      command: [
        "curl -ksu '<user>:<password>' https://<bmc>/redfish/v1/Chassis",
        "curl -ksu '<user>:<password>' \\",
        "  https://<bmc>/redfish/v1/Chassis/<chassis-id>/Power",
        "curl -ksu '<user>:<password>' \\",
        "  https://<bmc>/redfish/v1/Chassis/<chassis-id>/Thermal",
      ].join("\n"),
      normal: {
        label: "정상 evidence",
        output: "(예시 출력 — 실측 아님)\nnode ID·timestamp·power W·inlet °C·fan state가 16노드 모두 수집되고 rack PDU meter와 시간 정렬됨",
        reading: "server BMC와 rack PDU가 재는 경계가 다르므로 차이를 loss·auxiliary load·clock skew로 설명합니다.",
      },
      failure: {
        label: "부족한 evidence",
        output: "nvidia-smi GPU power만 수집 / timestamp 없음 / rack PDU 합계와 node 합계를 비교하지 않음",
        reading: "GPU board power는 server input이나 rack facility load가 아닙니다. 어떤 계측 경계를 읽었는지 함께 저장합니다.",
      },
      source: {
        label: "NVIDIA DGX B300 Redfish Support",
        href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/redfish-api-supp.html",
        location: "power·thermal·cooling sensor와 inventory를 조회하는 지원 범위",
      },
    },
  ],
  sources: [
    { label: "NVIDIA DGX B300 Data Center Best Practices", href: "https://docs.nvidia.com/dgx-pdf/data-center-best-practices-with-dgx-b300-v1.pdf", claim: "DC 14.5/19kW, AC 15/19.7kW, 4대/2대 rack, 회로표, airflow·temperature 조건을 확인했습니다.", checkedAt },
    { label: "NVIDIA DGX B300 User Guide", href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/introduction-to-dgxb300.html", claim: "10RU, PSU/busbar, heat output, BMC와 node-level power specification의 경계를 확인했습니다.", checkedAt },
    { label: "NVIDIA DGX B300 Redfish Support", href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/redfish-api-supp.html", claim: "power·thermal·cooling sensor, inventory와 power cap을 BMC API로 읽을 수 있는 지원 범위를 확인했습니다.", checkedAt },
    { label: "NVIDIA SuperPOD B300 Reference Architecture", href: "https://docs.nvidia.com/dgx-superpod/reference-architecture/scalable-infrastructure-b300/latest/", claim: "compute rack뿐 아니라 network·storage·CDU·RDHx auxiliary power를 facility total에 포함하는 기준을 확인했습니다.", checkedAt },
    { label: "Singapore IMDA Tropical DC Standard", href: "https://www.imda.gov.sg/how-we-can-help/green-dc-roadmap/tropical-dc-standard", claim: "26°C 이상 운영은 단계적 시험과 equipment envelope를 확인하는 별도 방법이지 임의 setpoint 상향이 아님을 확인했습니다.", checkedAt },
    { label: "NVIDIA DGX B300 Quickstart", href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/quickstart-basics.html", claim: "설치는 partner/field engineer 범위이며 production 전 health·stress validation이 필요하다는 운영 경계를 확인했습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;

export const commissioningAcceptanceDepth = {
  ledgers: [
    {
      section: "mechanism",
      title: "FAT→SAT→성능→운영 인수 evidence matrix",
      question: "각 시험이 무엇을 증명하며 무엇은 아직 증명하지 못합니까?",
      columns: ["단계", "대표 시험", "합격 조건 예", "남기는 원본", "다음 단계로 넘기는 위험"],
      rows: [
        ["FAT", "serial·GPU/NIC/drive·firmware inventory", "BOM과 16/16 node 일치", "signed inventory·사진·firmware dump", "현장 전원·cable·cooling은 미검증"],
        ["SAT", "rack·A/B feed·port map·BMC·sensor", "도면과 실제 연결 일치", "rack elevation·cable ledger·Redfish snapshot", "cluster performance는 미검증"],
        ["node validation", "NVSM health·20분 stress·DCGM", "필수 test Pass, error 0", "JSON/log·exit code·manifest", "internode fabric은 미검증"],
        ["cluster validation", "RDMA pair·2→4→16 node NCCL", "transport·validation·baseline threshold 통과", "host/rank log·counter snapshot", "application SLA는 미검증"],
        ["workload validation", "training·inference·checkpoint", "SLA·RTO·오류 기준 통과", "config·dataset fingerprint·metrics", "운영팀 복구 능력은 미검증"],
        ["operational acceptance", "drain·replace·restore·escalation", "운영팀이 runbook 재현", "ticket·timeline·서명·예외", "장기 soak와 patch regression은 계속 관리"],
      ],
      conclusion: "64개 node-level 결과가 모두 통과해도 cluster와 facility, 실제 workload, 운영 인수는 남습니다. 시험 단계마다 증명 범위를 문장으로 제한해야 합니다.",
    },
    {
      section: "mechanism",
      title: "acceptance ledger 한 행",
      question: "합격·실패·예외를 나중에 다시 재현할 수 있습니까?",
      columns: ["필드", "예시", "왜 필요한가", "빠졌을 때 생기는 문제"],
      rows: [
        ["requirement/test ID", "REQ-NET-03 / TEST-NCCL-07", "계약 요구와 시험을 연결", "benchmark가 어느 요구를 증명했는지 모름"],
        ["environment fingerprint", "node 16, image digest, driver, NCCL, firmware", "같은 조건 재실행", "patch 뒤 숫자를 비교할 수 없음"],
        ["command·start/end·exit", "원문 script와 exit code", "실행 자체와 diagnostic 결과 분리", "화면 캡처만 남아 자동 판독 불가"],
        ["threshold·result", "(가정) baseline 대비 −10% 이내 / actual", "사후 합격선 변경 방지", "결과를 본 뒤 기준을 맞춤"],
        ["artifact URI·hash", "log bundle SHA-256", "원본 무결성과 보존 위치", "요약표만 남고 rank log 소실"],
        ["exception owner·due", "vendor case·risk·재시험일", "미해결을 완료로 숨기지 않음", "temporary waiver가 영구화"],
      ],
      conclusion: "체크 표시보다 환경과 원본 증거가 중요합니다. 시험을 실행한 command와 결과를 판정한 threshold가 같은 행에 있어야 합니다.",
    },
  ],
  evidence: [
    {
      section: "source",
      eyebrow: "실물 1 · node preflight",
      title: "health와 stress를 다른 질문으로 실행합니다",
      question: "현재 sensor가 정상인 것과 부하 아래 20분 동안 안정적인 것을 구분합니까?",
      body: "NVSM health는 현재 component 상태를 요약하고, stress-test는 GPU·CPU·memory·storage에 부하를 줍니다. 둘의 start/end time, exit code와 원본 log를 각각 보존합니다.",
      language: "shell",
      command: [
        "sudo nvsm show health",
        "sudo nvsm stress-test --force",
        "",
        "# JSON이 필요한 자동 gate는 지원 release의 DCGM syntax 확인",
        "dcgmi diag --run 1 --json",
      ].join("\n"),
      normal: {
        label: "정상 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "NVSM overall: Healthy",
          "stress-test: Completed",
          "DCGM exit: 0 / tests: Pass",
        ].join("\n"),
        reading: "command return과 test result를 함께 저장합니다. Skip이 있으면 Pass로 합산하지 않고 지원 여부와 준비 실패를 확인합니다.",
      },
      failure: {
        label: "실패 판독 · 예시 출력",
        output: [
          "(예시 출력 — 실측 아님)",
          "NVSM overall: Healthy",
          "stress-test: Fail at GPU 5 under targeted power",
          "DCGM exit: 226",
        ].join("\n"),
        reading: "idle health가 정상이더라도 부하 test가 실패할 수 있습니다. 해당 node를 drain하고 error code·temperature·power·XID timeline을 보존합니다.",
      },
      source: {
        label: "NVIDIA DGX B300 Quickstart",
        href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/quickstart-basics.html",
        location: "nvsm show health와 약 20분 pre-flight stress test",
      },
    },
    {
      section: "source",
      eyebrow: "실물 2 · 2→16노드 NCCL",
      title: "실패 범위를 한 번에 16노드로 키우지 않습니다",
      question: "어느 node pair와 어느 규모에서 처음 실패했는지 남길 수 있습니까?",
      body: "공식 B300 deployment guide의 srun·NCCL test 형태를 기준으로 pair, 4-node group, 16-node 순서로 확대합니다. image tag와 command를 현장 승인 digest로 고정합니다.",
      language: "shell",
      command: [
        "srun -N2 --exclusive --gpus-per-node=8 --mpi=pmix \\",
        "  --container-image='<approved-nccl-tests-image>' \\",
        "  all_reduce_perf_mpi -b 1G -e 16G -f 2 -g 8",
        "",
        "# pair 통과 뒤 같은 command shape로 -N4, 마지막에 -N16",
      ].join("\n"),
      normal: {
        label: "정상 evidence",
        output: "(예시 출력 — 실측 아님)\n2/4/16 node: validation errors 0\ntransport: NET/IB\nbusbw: 각 규모 baseline 허용범위 안",
        reading: "algbw·busbw·wire counter의 뜻을 구분하고, 동일 message size와 topology의 baseline으로 판정합니다.",
      },
      failure: {
        label: "격리 evidence",
        output: "(예시 출력 — 실측 아님)\n2 node pass\n4 node group containing dgx-07 fail\nrank 29 NET/IB timeout\nport counter increment on one link",
        reading: "실패 group을 반으로 줄이거나 node를 교차 대체해 endpoint와 fabric 경계를 좁힙니다. 재부팅 전에 log와 counter를 먼저 보존합니다.",
      },
      source: {
        label: "NVIDIA B300 Deployment Guide",
        href: "https://docs.nvidia.com/dgx-basepod/deployment-guides/dgx-basepod-b200/latest/b300/b300-nmc.html",
        location: "Slurm validation, single-node와 multi-node NCCL test command",
      },
    },
    {
      section: "limits",
      eyebrow: "실패 추적 · 합격 뒤 간헐 장애",
      title: "짧은 benchmark가 놓친 열·link·checkpoint 문제를 soak에서 잡습니다",
      question: "한 번 통과한 결과가 다음 patch와 장시간 부하에서도 유지되는지 어떻게 압니까?",
      body: "대표 workload를 여러 시간 실행하면서 power·temperature·ECC/XID·RDMA counter·checkpoint 시간을 같은 timeline에 기록합니다. threshold 초과가 한 번이라도 나오면 정확한 node·rank·시각으로 replay할 수 있어야 합니다.",
      language: "text",
      command: [
        "soak window: workload owner와 합의한 지속 시간",
        "동시 수집: node power·temperature·GPU error·NIC counter",
        "주기 작업: checkpoint write + restore verification",
        "failure drill: node drain 또는 승인된 component N−1",
        "종료 판정: SLA·error budget·복구 시간·data integrity",
        "재검증 trigger: firmware/driver/kernel/network/storage 변경",
      ].join("\n"),
      normal: {
        label: "인수 가능한 상태",
        output: "threshold 사전 합의 / raw telemetry 보존 / 실패 drill과 restore 통과 / 운영팀이 runbook 재현",
        reading: "성능 숫자뿐 아니라 고장 감지, 서비스 영향, 복구와 인수 주체까지 닫혔습니다.",
      },
      failure: {
        label: "인수를 보류할 상태",
        output: "평균 bandwidth만 기록 / checkpoint restore 미실행 / alarm owner 없음 / 예외 재시험일 없음",
        reading: "장비는 켜져 있어도 운영 가능한 서비스로 인수할 증거가 부족합니다.",
      },
      source: {
        label: "NVIDIA DCGM Diagnostics",
        href: "https://docs.nvidia.com/datacenter/dcgm/latest/reference/diagnostics/index.html",
        location: "Pass·Fail·Skip, diagnostic error와 실행 실패를 구분하는 결과 model",
      },
    },
  ],
  sources: [
    { label: "NVIDIA DGX B300 Quickstart", href: "https://docs.nvidia.com/dgx/dgxb300-user-guide/quickstart-basics.html", claim: "production 전 NVSM health와 약 20분 stress test, container에서 driver visibility를 확인하는 절차를 사용했습니다.", checkedAt },
    { label: "NVIDIA B300 Deployment Guide", href: "https://docs.nvidia.com/dgx-basepod/deployment-guides/dgx-basepod-b200/latest/b300/b300-nmc.html", claim: "sinfo·GPU job·container·single/multi-node NCCL을 실제 cluster validation 순서에 반영했습니다.", checkedAt },
    { label: "NVIDIA DCGM dcgmi diag", href: "https://docs.nvidia.com/datacenter/dcgm/latest/reference/command-line-reference/dcgmi/dcgmi-diag.html", claim: "active diagnostic command, JSON, exit status와 test result를 분리해 기록하는 기준을 확인했습니다.", checkedAt },
    { label: "NVIDIA DCGM Multi-Node Diagnostics", href: "https://docs.nvidia.com/datacenter/dcgm/latest/reference/multi-node-diagnostics/index.html", claim: "orchestration outcome과 diagnostic outcome이 다르며 workload별 지원 GPU 경계를 확인했습니다.", checkedAt },
    { label: "NVIDIA NCCL Tests Deployment Example", href: "https://docs.nvidia.com/dgx-basepod/deployment-guides/dgx-basepod-b200/latest/b300/b300-nmc.html", claim: "B300 환경의 srun, container image, all_reduce_perf_mpi command shape와 validation 출력 항목을 확인했습니다.", checkedAt },
    { label: "KISA CSAP", href: "https://isms.kisa.or.kr/main/csap/notice/?boardId=bbs_0000000000000004&mode=list", claim: "hardware acceptance와 cloud service 보안인증의 대상·범위를 같은 합격 주장으로 섞지 않도록 공식 안내 경계를 확인했습니다.", checkedAt },
  ],
} satisfies EngineeringDepthData;
