import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { PdpChallengeViz } from "./PdpChallengeViz";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefs } from "./codeRefs";
import { pdpTree } from "./fileTrees";

const PDP_DESIGN = "https://github.com/FilOzone/pdp/blob/4d2a930194367477050302792de89e29275a6047/docs/design.md";
const PDP_VERIFIER = "https://github.com/FilOzone/pdp/blob/4d2a930194367477050302792de89e29275a6047/src/PDPVerifier.sol";
const PDP_SCHEDULE = "https://github.com/FilOzone/pdp/blob/4d2a930194367477050302792de89e29275a6047/src/IPDPProvingSchedule.sol";
const CURIO_PDP = "https://github.com/filecoin-project/curio/blob/550f2ee0aadd3491da2bc71df13673075a803ccb/pdp/README.md";

export default function ModernFilecoinPdp() {
  const sidebar = useCodeSidebar();
  return <>
  <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">60-leaf piece와 40-leaf piece를 한 100-leaf dataset으로 증명하기</p><h2 className="text-3xl font-bold tracking-tight">PDP는 provider가 등록 dataset의 sampled leaves를 현재 열 수 있다는 주기적 possession receipt다</h2></header><p className="text-lg leading-8 text-foreground/90"><a className="text-primary hover:underline" href="/blockchain/pos-theory#por">sampling 기반 possession 정본</a>은 challenge 수와 detection probability를 설명합니다. 이 글은 current pinned PDP contract가 ordered pieces를 logical leaf array로 만들고, period별 seed로 indices를 고른 뒤 Merkle paths와 schedule state를 검증하는 구현 경계만 맡습니다. 이는 PoRep의 replica-specific encoding도, 사용자가 원하는 byte를 즉시 내려받는 retrieval SLA도 아닙니다.</p><PdpChallengeViz /><ContentBoundary article="filecoin-pdp" /></section>

    <section id="dataset-artifact" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Dataset artifact</p><h2 className="mt-2 text-2xl font-bold">Ordered piece roots와 leaf counts를 하나의 logical array로 고정하고 contract schedule에 연결한다</h2></header><p>Dataset receipt에는 set ID, provider/listener, ordered piece identifiers·roots·leaf counts, total challenge range, mutation revision, next challenge epoch와 source artifact digests를 기록합니다. 예제에서 piece A는 60 leaves, B는 40 leaves이므로 logical indices 0–59는 A, 60–99는 B입니다. Piece order나 leaf count를 바꾸면 root bytes가 같아도 다른 dataset입니다.</p><ExplainedFormula question="Logical challenge index가 어느 piece의 어느 leaf인지 어떻게 찾을까?" idea={<>앞선 pieces의 leaf counts를 누적한 prefix offset으로 전체 배열을 구간화합니다.</>} formula={String.raw`o_i=\sum_{j<i}L_j,\qquad o_i\le c<o_i+L_i,\qquad local=c-o_i`}
    annotatedFormula={String.raw`o_i=\underbrace{\sum_{j<i}L_j,\qquad o_i\le c<o_i+L_i,\qquad local=c-o_i}_{\text{허용 경계 판정}}`}
    operations={[
      { expression: String.raw`\sum_{j<i}L_j,\qquad o_i\le c<o_i+L_i,\qquad local=c-o_i`, annotation: ["계산한 양을 허용 경계와 비교해 상태를 판정합니다.","앞선 pieces의 leaf counts를 누적한 prefix","offset으로 전체 배열을 구간화합니다."] },
    ]} terms={[{symbol:"o_i",name:"Piece offset",description:"i번째 piece 앞에 놓인 전체 leaves 수입니다."},{symbol:"L_j",name:"Piece leaf count",description:"j번째 registered piece의 Merkle leaves 수입니다."},{symbol:"c",name:"Logical challenge",description:"0 이상 total leaf count 미만의 dataset-wide index입니다."},{symbol:"i",name:"Selected piece",description:"Challenge c를 포함하는 ordered piece index입니다."},{symbol:"local",name:"Piece-local index",description:"선택된 piece 안에서 열어야 하는 leaf 위치입니다."}]} assumptions={["Piece order와 leaf counts는 challenge seed가 정해지기 전에 commitment된 dataset revision입니다.","Leaf encoding과 Merkle tree shape는 pinned PDP profile을 따릅니다."]} interpretation="A=60, B=40인 dataset에서 c=73이면 oB=60이고 B의 local index는 13입니다. Piece 순서를 바꾸면 같은 c가 전혀 다른 leaf를 가리킵니다." /><div id="paper-pdp-design"><CitationBlock type="code" citeKey={1} source="FilOzone PDP design · commit 4d2a930" href={PDP_DESIGN}><p><strong>문제:</strong> 여러 pieces를 dataset으로 등록하고 fresh challenges와 proving periods로 possession을 반복 확인해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned design은 dataset/piece commitments, challenge sampling, proving schedule, fault handling과 detection model을 설명합니다.</p><p><strong>중요 가정:</strong> commit 4d2a930의 contract model, Merkle profile, chain randomness/finality와 configured challenge count를 고정합니다.</p><p><strong>근거 범위:</strong> FilOzone PDP design snapshot의 protocol·contract intent에 한정합니다.</p><p><strong>일반화 금지:</strong> Possession proof가 retrieval bandwidth, application-level durability, PoRep encoding 또는 미래의 모든 period 성공을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="challenge-proof" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Challenge proof receipt</p><h2 className="mt-2 text-2xl font-bold">Period seed와 set ID에서 logical indices를 결정한 뒤 각 piece root까지 Merkle path를 검증한다</h2></header><p>Verifier는 provider가 고른 index를 신뢰하지 않습니다. Seed, proof set ID와 proof index를 hash해 total leaf range 안의 challenge를 만들고, dataset prefix offsets로 piece-local leaf를 찾습니다. Receipt에는 schedule/seed source, set revision, challenge indices, leaves·paths, expected piece roots, proof bytes와 contract call result를 넣습니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="pdp.go — challenge·proof·verify" onClick={() => sidebar.open("pdp-main", codeRefs["pdp-main"])} /></div><ExplainedFormula question="PDP challenge index는 어떻게 dataset range 안에서 결정될까?" idea={<>Fresh seed와 set identity, proof 순번을 hash한 뒤 total leaf count로 나머지를 취합니다.</>} formula={String.raw`c_i=\operatorname{uint}(keccak256(seed\|setId\|i))\bmod L`}
    annotatedFormula={String.raw`c_i=\underbrace{\operatorname{uint}(keccak256(seed\|setId\|i))\bmod L}_{\text{Challenge hash 계산}}`}
    operations={[
      { expression: String.raw`\operatorname{uint}(keccak256(seed\|setId\|i))\bmod L`, annotation: ["Challenge hash이(가) 식의 결과에 기여하는 방식을","계산합니다.","Fresh seed와 set identity, proof","순번을 hash한 뒤 total leaf count로 나머지를"] },
    ]} terms={[{symbol:"c_i",name:"Challenge index",description:"i번째 proof가 열어야 하는 dataset-wide leaf index입니다."},{symbol:"keccak256",name:"Challenge hash",description:"Pinned Solidity verifier가 사용하는 deterministic hash입니다."},{symbol:"seed",name:"Period seed",description:"해당 proving period의 fresh challenge source입니다."},{symbol:"setId",name:"Proof set ID",description:"검증 대상 dataset을 식별합니다."},{symbol:"i",name:"Proof index",description:"0부터 challenge count 직전까지의 순번입니다."},{symbol:"L",name:"Challenge range",description:"Dataset의 admitted total leaf count입니다."},{symbol:String.raw`\bmod`,name:"Modulo",description:"Hash integer를 0부터 L-1 범위로 매핑합니다."}]} assumptions={["L은 0보다 크고 seed는 provider가 dataset 내용을 본 뒤 자유롭게 grinding할 수 없는 source에서 옵니다.","Hash-to-range의 modulo bias와 security parameters는 pinned protocol profile에서 평가합니다."]} interpretation="L=100이고 hash integer의 마지막 나머지가 73이면 cᵢ=73이며 앞 예제의 piece B, local leaf 13을 열어야 합니다." /><div id="paper-pdp-verifier"><CitationBlock type="code" citeKey={2} source="PDPVerifier.sol · commit 4d2a930" href={PDP_VERIFIER}><p><strong>문제:</strong> Contract가 dataset과 period에 맞는 challenges를 재구성하고 submitted Merkle proofs를 검증해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned Solidity source는 seed·set ID·proof index challenge derivation, logical-to-piece mapping, Merkle verification와 success/fault transitions를 구현합니다.</p><p><strong>중요 가정:</strong> Exact contract revision, dataset state, listener, challenge range, tree/proof serialization과 chain environment를 사용합니다.</p><p><strong>근거 범위:</strong> PDPVerifier의 on-chain verification behavior snapshot에 한정합니다.</p><p><strong>일반화 금지:</strong> Contract verify 성공이 off-chain bytes의 즉시 retrieval, provider hardware 상태 또는 다른 contract revisions의 호환성을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="period-state" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Proving period and fault state</p><h2 className="mt-2 text-2xl font-bold">한 period의 success·miss·fault를 확정한 뒤 next challenge epoch를 갱신한다</h2></header><p>Schedule receipt는 previous/next challenge epoch, proving deadline, challenge count/range, submission tx와 block, listener callback/events, success 또는 fault, reorg/finality 상태를 함께 보존합니다. Proof가 cryptographically valid해도 너무 이르거나 늦은 period에 제출되면 운영 완료가 아닙니다. 한 period의 성공은 다음 period의 possession을 미리 증명하지 않습니다.</p><ExplainedFormula question="일부 data를 잃은 provider를 여러 sampled challenges로 찾을 확률은 얼마일까?" idea={<>각 sample이 손실 영역을 피할 확률을 모두 곱한 뒤 1에서 뺍니다.</>} formula={String.raw`P_{detect}=1-(1-\alpha)^{K T}`}
    annotatedFormula={String.raw`P_{detect}=\underbrace{1-(1-\alpha)^{K T}}_{\text{Detection probability 계산}}`}
    operations={[
      { expression: String.raw`1-(1-\alpha)^{K T}`, annotation: ["Detection probability이(가) 식의 결과에","기여하는 방식을 계산합니다.","각 sample이 손실 영역을 피할 확률을 모두 곱한 뒤","1에서 뺍니다."] },
    ]} terms={[{symbol:"P_{detect}",name:"Detection probability",description:"T periods 안에 적어도 한 challenge가 missing fraction을 맞힐 확률입니다."},{symbol:String.raw`\alpha`,name:"Missing fraction",description:"Dataset logical leaves 가운데 열 수 없는 비율입니다."},{symbol:"K",name:"Challenges per period",description:"한 proving period에서 검증하는 independently sampled leaves 수입니다."},{symbol:"T",name:"Observed periods",description:"같은 loss 상태를 관찰하는 proving periods 수입니다."},{symbol:"1-\\alpha",name:"Single-sample miss",description:"한 sample이 남아 있는 data를 골라 손실을 발견하지 못할 확률입니다."}]} assumptions={["Challenges는 분석상 독립·균등하며 fresh, provider의 missing fraction α가 T periods 동안 일정합니다.","Correlated sampling, adaptive repair, biased randomness 또는 changing dataset에서는 이 식을 그대로 쓰지 않습니다."]} interpretation="α=0.1, K=5, T=1이면 Pdetect=1-0.9⁵≈0.4095입니다. 약 41%는 availability 보장이 아니라 이 단순 모델에서 한 period 안에 손실을 발견할 확률입니다." /><div id="paper-pdp-schedule"><CitationBlock type="code" citeKey={3} source="IPDPProvingSchedule.sol · commit 4d2a930" href={PDP_SCHEDULE}><p><strong>문제:</strong> Proof set별 challenge epoch, proving deadline, success와 missed-period fault를 명시적인 contract state로 제공해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned interface는 proving schedule 조회·proof 제출·next-period/fault 관련 contract boundary와 events를 정의합니다.</p><p><strong>중요 가정:</strong> Deployed verifier/listener implementations, chain epoch/finality rules와 exact ABI revision을 함께 고정합니다.</p><p><strong>근거 범위:</strong> commit 4d2a930의 PDP proving-schedule interface에 한정합니다.</p><p><strong>일반화 금지:</strong> Interface가 scheduler liveness, transaction inclusion, economic sufficiency 또는 off-chain retry 성공을 스스로 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Contract-provider release gate</p><h2 className="mt-2 text-2xl font-bold">Provider artifact와 contract statement를 대조하고 malformed proof·deadline·reorg를 함께 실패 주입한다</h2></header><p>두-piece 예제로 wrong order/root/count/range, missing upload, corrupted leaf/path, duplicate index, wrong seed/set/period, early·late submission, reverted tx, callback failure와 retry duplication을 검사합니다. Curio 측 piece upload·CommP 확인과 dataset task receipt를 contract set revision에 연결하고, independent local verifier와 on-chain result를 대조합니다. Candidate failure 시 이전 provider worker·contract allowlist·ABI/config로 rollback하며 이미 포함된 submission은 idempotency key로 재전송하지 않습니다.</p><ExplainedFormula question="PDP period를 release하려면 어떤 조건을 모두 만족해야 할까?" idea={<>Dataset artifact, schedule, every Merkle proof, transaction finality와 provider receipt를 AND로 결합합니다.</>} formula={String.raw`A=D_{ok}\land S_{ok}\land\left(\bigwedge_{i=0}^{K-1}M_i\right)\land T_{final}\land R_{provider}`}
    annotatedFormula={String.raw`A=\underbrace{D_{ok}\land S_{ok}\land\left(\bigwedge_{i=0}^{K-1}M_i\right)\land T_{final}\land R_{provider}}_{\text{판정 조건 결합}}`}
    operations={[
      { expression: String.raw`D_{ok}\land S_{ok}\land\left(\bigwedge_{i=0}^{K-1}M_i\right)\land T_{final}\land R_{provider}`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","Dataset artifact, schedule, every","Merkle proof, transaction","finality와 provider receipt를 AND로"] },
    ]} terms={[{symbol:"A",name:"Release acceptance",description:"이번 PDP period receipt를 승인하면 1입니다."},{symbol:"D_{ok}",name:"Dataset admission",description:"Ordered pieces, roots, counts와 revision이 expected state와 같으면 1입니다."},{symbol:"S_{ok}",name:"Schedule admission",description:"Seed, period, challenge epoch/range와 deadline이 유효하면 1입니다."},{symbol:"M_i",name:"Merkle verification",description:"i번째 derived challenge leaf/path가 expected piece root에 열리면 1입니다."},{symbol:"K",name:"Challenge count",description:"Profile이 요구한 proof samples 수입니다."},{symbol:"T_{final}",name:"Final transaction",description:"Submission이 요구 confidence까지 canonical chain에 남으면 1입니다."},{symbol:"R_{provider}",name:"Provider receipt",description:"Upload·CommP/dataset task artifact가 contract revision과 일치하면 1입니다."}]} assumptions={["Independent local reconstruction과 on-chain contract가 같은 ABI, set revision과 canonical encoding을 사용합니다.","Finality threshold와 deadline은 pinned deployment/network policy에서 읽습니다."]} interpretation="Merkle proofs가 모두 valid해도 transaction이 reorg되거나 provider dataset receipt가 다른 revision이면 A=0입니다. Retrieval 테스트는 별도 service gate입니다." /><div id="paper-curio-pdp"><CitationBlock type="code" citeKey={4} source="Curio PDP provider API · commit 550f2ee" href={CURIO_PDP}><p><strong>문제:</strong> Provider가 piece upload와 commitment 확인, dataset lifecycle을 PDP proving work와 연결해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned Curio documentation은 PDP HTTP/API workflow, piece upload·CommP v2 checks와 dataset operations의 provider-side boundary를 설명합니다.</p><p><strong>중요 가정:</strong> Curio commit 550f2ee의 API, storage backend, task engine, credentials와 compatible PDP contract revision을 고정합니다.</p><p><strong>근거 범위:</strong> Provider-side integration snapshot에 한정하며 on-chain verifier semantics는 PDP contracts에서 확인합니다.</p><p><strong>일반화 금지:</strong> API 문서가 production durability, fixed upload speed, data retrieval SLA 또는 contract proof 성공을 자동 보장하지 않습니다.</p></CitationBlock></div><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> PDP/PoRep/retrieval 경계, dataset offset, challenge derivation, Merkle receipt, detection probability, period/fault state, provider-contract parity, reorg와 rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>
  <CodeSidebar
    codeRefKey={sidebar.codeRefKey}
    codeRef={sidebar.codeRef}
    onClose={sidebar.close}
    onNavigate={sidebar.navigate}
    codeRefs={codeRefs}
    fileTrees={{ curio: pdpTree }}
    projectMetas={{
      curio: {
        id: "curio",
        label: "Curio · Go",
        badgeClass: "bg-blue-500/10 border-blue-500 text-blue-700",
      },
    }}
  />
  </>;
}
