import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { PlatformPathViz, ServerDecisionViz } from "./viz/ModernServerPlatformViz";

const REDFISH="https://www.dmtf.org/standards/redfish";
const ENERGY="https://www.energystar.gov/products/spec/energy_star_computer_servers_version_4_0_pd";

export default function ModernArticle(){return <article className="space-y-14">
<section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">서버와 데스크톱을 고르는 출발점</p><h2 className="text-3xl font-bold tracking-tight">서버는 더 빠른 PC가 아니라, workload를 계속 운영하고 고장 난 부분을 교체할 수 있게 만든 플랫폼이다</h2></header><p className="text-lg leading-8 text-foreground/90">CPU 이름부터 비교하면 필요한 memory channel, PCIe lane, 원격 복구와 정비 경로를 놓치기 쉽습니다. 이 글은 예제로 8 TiB active data와 2 TiB scratch를 쓰고 accelerator·NIC·NVMe를 동시에 움직이는 24시간 작업을 고정합니다. 숫자는 제품 권장이 아니라 계산 방법을 보여 주는 입력입니다.</p><p>먼저 용량·동시 실행·SLO(service-level objective, 허용 지연과 가용성 목표)를 요구량으로 바꾸고, CPU root complex에서 각 장치까지 실제 lane과 NUMA 경로를 그립니다. 마지막으로 BMC(baseboard management controller, 운영체제와 별도로 서버를 관리하는 제어기), hot-swap과 장애 복구가 필요한지 판단합니다. Memory 계산은 <a href="/gpu/hw-memory#memory-workload-capacity-path" className="text-primary hover:underline">memory 정본</a>, PCIe raw/goodput은 <a href="/gpu/hw-network#pcie-transaction-bandwidth-latency" className="text-primary hover:underline">network 정본</a>을 재사용합니다.</p><ServerDecisionViz/><ContentBoundary article="hw-server-vs-desktop"/></section>

<section id="workload-envelope" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Workload envelope</p><h2 className="mt-2 text-2xl font-bold">부품표보다 먼저 peak demand와 운영 여유를 적는다</h2></header><p><strong>Resource envelope</strong>는 workload가 동시에 요구하는 CPU threads, working memory, PCIe devices·lanes, storage throughput/capacity, network와 unavailable time의 범위입니다. 예제에서는 데이터 처리 phase와 metadata phase가 겹칠 수 있으므로 각각의 최고값을 무조건 더하지 않고 실제 동시 trace를 기록합니다.</p><ExplainedFormula question="표기 용량이 아니라 실제 필요한 memory를 어떻게 예산화할까?" idea={<>활성 데이터 전체가 아니라 peak resident working set에 OS·page cache·동시 작업과 성장 여유를 더해 실사용 가능 memory와 비교합니다.</>} formula={String.raw`M_{need}=(M_{work}+M_{OS}+C M_{job})(1+h)\le M_{usable}`} terms={[{symbol:"M_{need}",name:"필요 memory",description:"Peak phase에 동시에 resident해야 할 byte 수입니다."},{symbol:"M_{work}",name:"Working set",description:"현재 계산이 반복 접근하는 데이터입니다."},{symbol:"M_{OS}",name:"OS·cache",description:"Kernel, daemon과 page cache 예산입니다."},{symbol:"C",name:"동시 작업 수",description:"같은 시점에 살아 있는 job 수입니다."},{symbol:"M_{job}",name:"작업별 state",description:"Job 하나의 buffer·queue·temporary memory입니다."},{symbol:"h",name:"Headroom",description:"변동과 성장에 둔 비율 여유입니다."},{symbol:"M_{usable}",name:"실사용 가능 memory",description:"Firmware·reserved 영역을 제외하고 검증한 용량입니다."}]} assumptions={["동일 workload trace와 NUMA placement에서 peak를 측정합니다.","공유 cache나 비례하지 않는 state는 실측 함수로 바꿉니다."]} interpretation="예를 들어 40+8+2×12=72 GiB에 h=0.25를 두면 90 GiB가 필요합니다. 이 식은 bandwidth나 latency가 충분하다는 뜻은 아닙니다."/></section>

<section id="platform-topology" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Platform topology</p><h2 className="mt-2 text-2xl font-bold">슬롯 수가 아니라 어느 CPU root와 lane을 공유하는지 확인한다</h2></header><p>Desktop board는 target workload에 충분할 수 있지만 slot spacing, bifurcation, memory capacity와 장시간 full-load cooling을 직접 검증해야 합니다. Server platform은 더 많은 channel·lane·socket 선택지를 제공할 수 있지만, 두 socket을 넘는 접근은 NUMA(non-uniform memory access) 비용이 생기며 switch uplink를 여러 장치가 공유하면 aggregate traffic은 그 uplink를 넘지 못합니다.</p><PlatformPathViz/><ExplainedFormula question="여러 장치를 꽂았을 때 경로가 workload 요구를 만족하는지 어떻게 표현할까?" idea={<>장치별 negotiated width와 공유 uplink를 topology에 적고, 각 공유 구간의 동시 요구량 합을 그 구간의 achieved capacity와 비교합니다.</>} formula={String.raw`\forall e:\quad \sum_{i\in users(e)} B_i\le B^{achieved}_e`} terms={[{symbol:"e",name:"공유 경로",description:"PCIe link·switch uplink·socket interconnect 중 하나입니다."},{symbol:"users(e)",name:"경로 사용자",description:"같은 구간을 동시에 지나는 장치 집합입니다."},{symbol:"B_i",name:"장치 요구량",description:"고정 trace에서 장치 i가 요구하는 payload byte/s입니다."},{symbol:"B^{achieved}_e",name:"실측 경로 용량",description:"같은 payload·direction에서 측정한 goodput입니다."}]} assumptions={["동시 phase와 traffic direction을 고정합니다.","Raw GT/s가 아니라 protocol overhead와 contention이 포함된 achieved value를 씁니다."]} interpretation="x16 모양의 슬롯도 x4로 협상되거나 다른 장치와 uplink를 나눌 수 있습니다. 부등식 통과는 작은 I/O의 tail latency까지 보장하지 않습니다."/></section>

<section id="serviceability" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Serviceability</p><h2 className="mt-2 text-2xl font-bold">원격 관리와 hot-swap은 downtime의 범위를 줄이지만 무중단을 보장하지 않는다</h2></header><p>BMC와 Redfish는 power, sensor, inventory와 firmware 같은 관리 surface를 표준화해 OS가 멈춘 상황에서도 상태를 읽고 제어할 길을 줍니다. 그러나 Redfish API가 있다고 redundant PSU, data durability나 자동 복구가 생기는 것은 아닙니다. 교체 가능한 FRU(field-replaceable unit), LED/slot 식별, spare, runbook과 application replication이 함께 있어야 합니다.</p><div id="paper-redfish"><CitationBlock type="code" citeKey={1} source="DMTF Redfish DSP0266 1.23.1 · 2026-01-16" href={REDFISH}><p><strong>문제:</strong> 서로 다른 서버의 out-of-band 관리 interface를 일관되게 표현합니다.</p><p><strong>핵심 기여:</strong> HTTP 기반 resource model로 systems·chassis·power·thermal·update 등 관리 경계를 정의합니다.</p><p><strong>중요 가정:</strong> 정확한 Redfish release, vendor profile과 인증·network isolation을 함께 고정합니다.</p><p><strong>근거 범위:</strong> DMTF 표준의 protocol과 data-model semantics입니다.</p><p><strong>일반화 금지:</strong> API 지원만으로 hardware redundancy·service availability·firmware 안전성이 보장되지는 않습니다.</p></CitationBlock></div></section>

<section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">호환성·성능·고장 복구를 같은 candidate chassis에서 재생한다</h2></header><p>정확한 CPU·board·BIOS/BMC·DIMM population·slot wiring·PSU·cooling BOM을 pin하고 cold boot, memory stress, GPU/NVMe/NIC 동시 부하를 실행합니다. 그 다음 PSU 하나, drive 하나, fan 또는 OS를 의도적으로 잃고 telemetry, 작업 영향, 교체·remote recovery와 데이터 검증 시간을 기록합니다. 실패하면 이전 검증 platform으로 rollback합니다.</p><ExplainedFormula question="운영 가용성을 관찰 기간 안에서 어떻게 계산할까?" idea={<>사용자가 실제로 작업을 완료하지 못한 시간을 모두 합쳐 관찰 시간에서 뺍니다.</>} formula={String.raw`A_{obs}=1-\frac{T_{unavailable}}{T_{observed}}`} terms={[{symbol:"A_{obs}",name:"관찰 가용성",description:"정해진 관찰 기간에서 service가 usable했던 비율입니다."},{symbol:"T_{unavailable}",name:"Unavailable time",description:"SLO 기준상 요청을 완료하지 못한 시간의 합입니다."},{symbol:"T_{observed}",name:"관찰 시간",description:"동일 workload와 monitoring이 유효했던 전체 시간입니다."}]} assumptions={["Unavailable의 사용자 관점 정의와 planned maintenance 포함 여부를 먼저 고정합니다.","충분히 긴 표본과 동일한 incident clock을 사용합니다."]} interpretation="24시간 중 15분이 unusable이면 약 98.96%입니다. 이 짧은 관찰값을 연간 고장 확률로 일반화하면 안 됩니다."/><div id="paper-energy-star-server"><CitationBlock type="paper" citeKey={2} source="ENERGY STAR Computer Servers Version 4.0 · 2023-04-12" href={ENERGY}><p><strong>문제:</strong> Computer server의 분류와 energy reporting·test 조건을 일관되게 둡니다.</p><p><strong>핵심 기여:</strong> Server category, active/idle reporting과 SERT 기반 시험 경계를 제공합니다.</p><p><strong>중요 가정:</strong> Version 4.0 scope와 eligible configuration을 확인합니다.</p><p><strong>근거 범위:</strong> ENERGY STAR 인증·측정 specification입니다.</p><p><strong>일반화 금지:</strong> 인증 결과가 target workload의 throughput, availability나 platform 적합성을 대신하지 않습니다.</p></CitationBlock></div></section>
</article>}
