import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { QuicFlowViz, QuicStackViz } from "./viz/ModernQuicViz";

export default function ModernLibp2pQuicArticle() { return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">rust-libp2p 0.56.0 구현 읽기</p><h2 className="text-3xl font-bold tracking-tight">QUIC transport는 보안과 stream multiplexing을 품지만 application 검증까지 맡지는 않는다</h2></header><p className="text-lg leading-8">Bob의 provider record에서 <code>/ip4/…/udp/…/quic-v1/p2p/&lt;PeerId&gt;</code> 주소를 얻었다고 하겠습니다. rust-libp2p QUIC은 UDP 위에서 TLS 1.3 handshake로 expected PeerId를 확인하고 connection을 만든 뒤 bidirectional stream을 엽니다. Application은 stream에서 CID 요청을 보내고 받은 <code>payroll-report-v1</code> block을 CID로 검증합니다.</p><p>TCP 경로의 <a className="text-primary hover:underline" href="/p2p/libp2p-tcp#overview">socket lifecycle</a>, <a className="text-primary hover:underline" href="/p2p/libp2p-noise#overview">Noise identity binding</a>, <a className="text-primary hover:underline" href="/p2p/libp2p-yamux#overview">Yamux multiplexing</a>을 재사용하되 QUIC에는 Noise와 Yamux를 다시 쌓지 않습니다. ACK·loss·connection ID와 migration의 일반 이론은 <a className="text-primary hover:underline" href="/p2p/quic-fundamentals#overview">QUIC 정본</a>이 소유합니다.</p><QuicStackViz/></section>

  <section id="identity-stream" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · dial과 stream</p><h2 className="mt-2 text-2xl font-bold">Multiaddr의 expected PeerId와 handshake identity가 맞아야 connection을 release한다</h2></header><p>Transport는 IP·UDP·<code>quic-v1</code> multiaddr와 optional <code>/p2p/PeerId</code>를 해석합니다. Expected PeerId가 있으면 authenticated certificate에서 얻은 remote identity와 비교합니다. mismatch는 다른 application protocol로 넘기지 않고 dial 실패로 닫습니다.</p><p>Connection 뒤 outbound substream은 QUIC bidirectional stream입니다. 그러나 “stream open”은 remote handler가 payroll protocol을 수락했거나 bytes를 durable하게 저장했다는 뜻이 아닙니다. libp2p의 상위 stream protocol negotiation, request/response timeout과 CID verification receipt가 별도로 필요합니다.</p><div id="paper-rust-libp2p-quic-transport-056"><CitationBlock source="rust-libp2p 0.56.0 — quic transport.rs · connecting.rs" citeKey={1} type="code" href="https://github.com/libp2p/rust-libp2p/tree/libp2p-v0.56.0/transports/quic/src"><p><strong>문제:</strong> QUIC multiaddr를 authenticated libp2p peer connection으로 바꿉니다.</p><p><strong>기여:</strong> address parsing, expected PeerId check, TLS handshake와 transport output lifecycle의 pinned 구현을 제공합니다.</p><p><strong>전제:</strong> rust-libp2p 0.56.0 QUIC config와 compatible remote certificate identity를 사용합니다.</p><p><strong>근거 범위:</strong> dial/listen setup, remote PeerId binding과 connection establishment입니다.</p><p><strong>말하지 않는 것:</strong> application protocol authorization, content availability, payload integrity를 보장하지 않습니다.</p></CitationBlock></div><div id="paper-rust-libp2p-quic-stream-056"><CitationBlock source="rust-libp2p 0.56.0 — quic connection/stream.rs" citeKey={2} type="code" href="https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.56.0/transports/quic/src/connection/stream.rs"><p><strong>문제:</strong> 한 QUIC connection 위에서 독립적인 libp2p byte streams를 제공합니다.</p><p><strong>기여:</strong> bidirectional stream open, read/write, reset와 close mapping을 구현합니다.</p><p><strong>전제:</strong> handshake가 완료되고 connection/stream flow-control credit가 남아 있습니다.</p><p><strong>근거 범위:</strong> local stream API와 QUIC stream lifecycle adapter입니다.</p><p><strong>말하지 않는 것:</strong> remote business handler 처리, exactly-once request, durable acknowledgement를 제공하지 않습니다.</p></CitationBlock></div></section>

  <section id="hole-punching" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · socket reuse와 hole punch</p><h2 className="mt-2 text-2xl font-bold">Hole punching은 expected PeerId와 재사용 가능한 UDP socket이 있는 제한된 dial mode다</h2></header><p>Port reuse dial은 eligible listener socket을 활용해 NAT mapping을 유지할 수 있습니다. Hole punch 경로는 listener/socket과 expected PeerId를 요구하고 같은 remote에 진행 중인 attempt를 중복 시작하지 않으며 handshake timeout 안에 끝나야 합니다. 주소가 없거나 NAT가 symmetric하면 relay·다른 path가 필요할 수 있습니다.</p><p>성공 가능성을 높인다는 것과 연결을 보장한다는 것은 다릅니다. attempt ID, local/remote address, socket reuse 여부, expected/observed PeerId, timeout과 fallback reason을 receipt로 남기고 retry에는 backoff와 상한을 둡니다.</p><div id="paper-rust-libp2p-quic-holepunch-056"><CitationBlock source="rust-libp2p 0.56.0 — quic hole_punching.rs · config.rs" citeKey={3} type="code" href="https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.56.0/transports/quic/src/hole_punching.rs"><p><strong>문제:</strong> NAT 뒤 peer끼리 기존 UDP mapping을 이용해 direct QUIC handshake를 시도합니다.</p><p><strong>기여:</strong> eligible endpoint/socket reuse, in-progress attempt dedup과 timeout-bound coordination을 구현합니다.</p><p><strong>전제:</strong> 양쪽 address coordination, expected PeerId와 재사용 가능한 listening endpoint가 있습니다.</p><p><strong>근거 범위:</strong> 한 node의 simultaneous direct dial orchestration과 failure cleanup입니다.</p><p><strong>말하지 않는 것:</strong> 모든 NAT 유형에서 direct reachability나 relay 없는 liveness를 보장하지 않습니다.</p></CitationBlock></div></section>

  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · flow control과 release</p><h2 className="mt-2 text-2xl font-bold">보낼 수 있는 양은 stream·connection·network 세 창 중 가장 작은 값에 묶인다</h2></header><p>Stream credit가 남아도 connection 전체 credit가 소진되거나 congestion window가 작으면 write가 진행되지 않습니다. 반대로 큰 buffer를 허용해도 remote application이 읽지 않으면 memory와 latency만 늘 수 있습니다. 이 관계는 QUIC 정본의 flow-control 개념을 구현 운영으로 가져온 것입니다.</p><QuicFlowViz/><ExplainedFormula question="한 stream이 지금 전송할 수 있는 in-flight byte의 상한은 무엇일까?" idea={<>수신측 stream credit, connection 전체 credit, congestion controller의 network budget을 동시에 만족해야 하므로 가장 작은 창이 현재 병목입니다.</>} formula={String.raw`W_{eff}=\min(W_{stream},W_{conn},W_{cwnd})`}
  annotatedFormula={String.raw`W_{eff}=\underbrace{\min(W_{stream},W_{conn},W_{cwnd})}_{\text{경계 후보 선택}}`}
  operations={[
    { expression: String.raw`\min(W_{stream},W_{conn},W_{cwnd})`, annotation: ["허용 후보 중 목적에 맞는 경계값을 선택합니다.","수신측 stream credit, connection 전체","credit, congestion controller의","network budget을 동시에 만족해야 하므로 가장 작은"] },
  ]} terms={[{symbol:"W_{stream}",name:"stream credit",description:"해당 stream에 대해 receiver가 허용한 미소비 byte 범위입니다."},{symbol:"W_{conn}",name:"connection credit",description:"모든 stream이 공유하는 connection-level flow-control 여유입니다."},{symbol:"W_{cwnd}",name:"congestion window",description:"ACK와 loss 관측으로 network에 둘 수 있다고 판단한 in-flight budget입니다."}]} assumptions={["세 값은 같은 시점의 byte 단위 available budget으로 비교합니다.","TLS/QUIC framing overhead와 scheduler fairness는 단순 예에서 제외합니다.","64/256/96 KiB 예는 설명용이며 library default나 throughput 수치가 아닙니다.","Application reader가 계속 consume하며 connection이 closing state가 아니라고 가정합니다."]} interpretation="64 KiB, 256 KiB, 96 KiB라면 stream credit 64 KiB가 병목입니다. Stream reset은 그 stream을 실패시키지만 connection close는 sibling streams까지 중단할 수 있으므로 error scope를 receipt에 구분합니다."/><p>Release test는 PeerId mismatch, protocol negotiation failure, stream reset, connection close, flow-control stall, hole-punch timeout과 relay fallback을 분리합니다. 검증되지 않은 partial file은 삭제하고 stream·connection handle을 닫으며, retry는 idempotent CID request에만 bounded하게 적용합니다.</p><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 QUIC stack, PeerId binding, multiaddr, bidirectional stream, flow control과 CID 경계를 확인합니다. 심화 4문제는 window 계산, identity mismatch, hole-punch retry와 stream/connection failure scope release test를 설계하게 합니다.</p></section>
</article>; }
