import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { BroadcastCacheViz, BroadcastReceiptViz } from "./viz/ModernCommonwareBroadcastViz";

export default function ModernCommonwareBroadcastArticle() { return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">commonware-broadcast v2026.7.0</p><h2 className="text-3xl font-bold tracking-tight">Broadcast 요청이 local queue에 들어간 것과 recipient가 검증한 것은 같은 성공이 아니다</h2></header><p className="text-lg leading-8">Alice가 <code>payroll-report-v1</code> descriptor를 Bob에게 broadcast한다고 하겠습니다. <code>Feedback::Ok</code>는 Alice의 local mailbox가 요청을 받아들였다는 뜻입니다. Bob의 authenticated P2P receiver가 typed message를 decode하고 expected digest, sender와 application schema를 확인해야 비로소 verified receive receipt가 생깁니다.</p><p>이 current crate는 wide-area data dissemination과 bounded cache를 제공합니다. Total-order broadcast나 BFT commit은 <a className="text-primary hover:underline" href="/blockchain/smr-theory#total-order">SMR 정본</a>의 별도 계약이며, Reed–Solomon 복원도 <a className="text-primary hover:underline" href="/blockchain/erasure-coding#overview">erasure coding 정본</a>의 책임입니다. 레거시 글처럼 Ordered·DSMR·ZODA를 현재 broadcast crate의 한 pipeline으로 묶지 않습니다.</p><BroadcastReceiptViz/></section>
  <section id="broadcast-subscribe" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · broadcast와 subscribe</p><h2 className="mt-2 text-2xl font-bold">Broadcaster는 전송을 시도하고, digest subscriber는 local item receipt를 기다린다</h2></header><p><code>Broadcaster::broadcast</code>는 recipients와 Codec message를 local engine에 enqueue합니다. Trait 문서도 Feedback은 local processing acceptance일 뿐 recipient receipt가 아니라고 명시합니다. Buffered mailbox의 <code>subscribe(digest)</code>는 item이 cache에 있으면 즉시, 아니면 matching digest의 message가 들어올 때 waiter를 깨웁니다.</p><p>
            Subscribe completion은 typed item을 local process가 얻었다는 강한 receipt입니다. 다만 consensus delivery나
            durable storage는 아닙니다. Authenticated transport가 돌려준 peer key와 message digest, 거기에 schema revision과
            업무 authorization을 함께 검사합니다. 실제 range/piece bytes는 별도 transfer protocol에서 content hash를 검증합니다.
          </p><div id="paper-commonware-broadcaster-v2026"><CitationBlock source="commonware-broadcast v2026.7.0 — Broadcaster trait" citeKey={1} type="code" href="https://github.com/commonwarexyz/monorepo/blob/v2026.7.0/broadcast/src/lib.rs"><p><strong>문제:</strong> Application이 recipients에게 typed message replication을 요청하는 최소 interface를 제공합니다.</p><p><strong>기여:</strong> Codec message, recipient type과 local broadcast Feedback의 정확한 성공 경계를 정의합니다.</p><p><strong>전제:</strong> v2026.7.0 Broadcaster implementation과 caller가 supplied recipients/message를 사용합니다.</p><p><strong>근거 범위:</strong> Local broadcast request admission interface와 message serialization contract입니다.</p><p><strong>말하지 않는 것:</strong> Recipients 수신, total order, durable storage, Byzantine agreement를 보장하지 않습니다.</p></CitationBlock></div><div id="paper-commonware-mailbox-v2026"><CitationBlock source="commonware-broadcast v2026.7.0 — buffered/ingress.rs" citeKey={2} type="code" href="https://github.com/commonwarexyz/monorepo/blob/v2026.7.0/broadcast/src/buffered/ingress.rs"><p><strong>문제:</strong> Broadcast, digest subscription과 cache get 요청을 bounded actor mailbox로 연결합니다.</p><p><strong>기여:</strong> Overflow policy, cancelable waiters, broadcast_shared와 local Feedback lifecycle을 구현합니다.</p><p><strong>전제:</strong> Digestible+Codec message와 running buffered Engine, bounded mailbox configuration을 사용합니다.</p><p><strong>근거 범위:</strong> Node-local command enqueue, waiter cancellation과 response delivery입니다.</p><p><strong>말하지 않는 것:</strong> Network retransmission, recipient acknowledgement, application side-effect commit을 제공하지 않습니다.</p></CitationBlock></div></section>
  <section id="cache-eligibility" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · bounded cache</p><h2 className="mt-2 text-2xl font-bold">같은 digest를 여러 peer가 보냈어도 item은 하나만 저장하고 reference를 센다</h2></header><p>Engine은 peer별 최신 digest deque를 두고 global <code>items</code>에는 digest당 message 하나를 저장합니다. 같은 digest가 여러 eligible peers의 deque에 있으면 <code>counts</code>를 늘리고, 한 peer의 oldest digest가 evict될 때 count만 줄입니다. Count가 0이 될 때만 shared item을 제거합니다.</p><p>Cache residence는 최신 <code>primary</code> peer set의 sender에게만 허용됩니다. Ineligible peer가 matching waiter를 깨울 수는 있지만 resident entry로 남지는 않습니다. 따라서 “받았다”와 “cache에 남아 있다”, “primary가 보냈다”는 서로 다른 state입니다.</p><BroadcastCacheViz/><ExplainedFormula question="Digest d의 shared cache item을 언제 제거해야 할까?" idea={<>각 eligible peer의 bounded deque에 digest가 존재하는지를 세어 reference count를 만듭니다. 한 deque에서 evict해도 다른 peer reference가 남으면 item을 보존하고 count가 0일 때만 제거합니다.</>} formula={String.raw`c(d)=\sum_{p\in P_{primary}}\mathbf 1[d\in Q_p],\qquad d\in Items\iff c(d)>0`}
  annotatedFormula={String.raw`c(d)=\underbrace{\sum_{p\in P_{primary}}\mathbf 1[d\in Q_p],\qquad d\in Items\iff c(d)>0}_{\text{허용 경계 판정}}`}
  operations={[
    { expression: String.raw`\sum_{p\in P_{primary}}\mathbf 1[d\in Q_p],\qquad d\in Items\iff c(d)>0`, annotation: ["계산한 양을 허용 경계와 비교해 상태를 판정합니다.","각 eligible peer의 bounded deque에","digest가 존재하는지를 세어 reference count를","만듭니다."] },
  ]} terms={[{symbol:"P_{primary}",name:"eligible peers",description:"Latest primary update에서 cache residence를 허용한 peer 집합입니다."},{symbol:"Q_p",name:"peer digest deque",description:"Peer p가 보낸 최신 digest를 configured deque_size까지 보관하는 LRU-like queue입니다."},{symbol:"c(d)",name:"digest refcount",description:"Digest d를 현재 참조하는 eligible peer deques 수입니다."},{symbol:"Items",name:"shared item map",description:"Digest당 Arc message 하나를 저장하는 global cache입니다."}]} assumptions={["각 peer deque에는 같은 digest가 최대 한 번 존재합니다.","Primary update와 deque eviction은 같은 Engine event loop에서 순서대로 적용됩니다.","Digest equality가 application이 요구하는 collision/security contract를 만족해야 합니다.","Cache residence는 durable disk persistence나 recipient quorum이 아닙니다."]} interpretation="A와 B deque에 d7이 있으면 count는 2입니다. A에서 d7을 evict해도 1이라 item은 남고, B에서도 빠져 0이 될 때 제거합니다. Deque size를 키우면 hit window와 memory가 함께 늘어납니다."/><div id="paper-commonware-engine-v2026"><CitationBlock source="commonware-broadcast v2026.7.0 — buffered/engine.rs" citeKey={3} type="code" href="https://github.com/commonwarexyz/monorepo/blob/v2026.7.0/broadcast/src/buffered/engine.rs"><p><strong>문제:</strong> 중복 wide-area message를 bounded memory에서 공유하고 digest waiter에게 전달합니다.</p><p><strong>기여:</strong> Peer deques, digest refcount/items, duplicate/ineligible outcomes와 latest-primary eviction을 구현합니다.</p><p><strong>전제:</strong> Single Engine loop, configured deque_size와 authoritative peer-provider latest update를 사용합니다.</p><p><strong>근거 범위:</strong> Node-local decoded message cache, waiter notification과 eligibility-based residence입니다.</p><p><strong>말하지 않는 것:</strong> Global reliable broadcast, consensus finality, persistent storage durability를 보장하지 않습니다.</p></CitationBlock></div></section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · failure와 release</p><h2 className="mt-2 text-2xl font-bold">Mailbox·network·decode·cache·application failure를 같은 retry로 묶지 않는다</h2></header><p><code>Rejected</code>나 <code>Closed</code>는 local admission failure이고, receiver error는 Engine loop 중단, decode error는 해당 message invalid, ineligible은 cache residence 거절입니다. Expected digest의 waiter가 취소되면 responder를 정리하며, primary set 변경 뒤 stale peer references도 evict합니다. Broadcast timeout 후 무조건 재전송하려면 operation ID와 idempotent application handler가 필요합니다.</p><p>
            Release test에는 mailbox overflow, network disconnect, malformed codec이 들어갑니다. 여기에 duplicate digest,
            peer deque overflow, latest-primary 변경, waiter cancellation과 restart까지 더합니다. Verified receipt에는
            authenticated sender, digest, decoded schema, local cache outcome과 application acceptance를 남깁니다.
            Feedback::Ok 하나만 보고 payroll artifact를 publish하지는 않습니다.
          </p><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 Feedback, recipients, Digestible/Codec, subscribe/get, peer deque와 primary eligibility를 확인합니다. 심화 4문제는 refcount 계산, ineligible waiter 반례, overflow retry와 verified receipt release test를 설계하게 합니다.</p></section>
</article>; }
