import type { CodeRef } from "@/components/code/types";
import source0 from "./codebase/vllm/vllm/v1/attention/backend.py?raw";
import source1 from "./codebase/vllm/vllm/v1/core/block_pool.py?raw";
import source2 from "./codebase/vllm/vllm/v1/attention/backends/flash_attn.py?raw";
import source3 from "./codebase/vllm/vllm/v1/core/kv_cache_coordinator.py?raw";
import source4 from "./codebase/vllm/vllm/v1/core/kv_cache_manager.py?raw";
import source5 from "./codebase/vllm/vllm/v1/core/kv_cache_utils.py?raw";
import source6 from "./codebase/sglang/python/sglang/srt/mem_cache/radix_cache.py?raw";
import source7 from "./codebase/sglang/python/sglang/srt/managers/schedule_batch.py?raw";
import source8 from "./codebase/sglang/python/sglang/srt/managers/schedule_policy.py?raw";
import source9 from "./codebase/vllm/vllm/v1/core/single_type_kv_cache_manager.py?raw";
export const codeRefs: Record<string, CodeRef> = {
"radix-match": {...{"path": "sglang/python/sglang/srt/mem_cache/radix_cache.py", "highlight": [637, 661], "desc": "앞에서 이어지는 일치 구간을 찾고 분기점을 드러냅니다.", "annotations": [{"lines": [637, 661], "color": "sky", "note": "R1과 R2는 6 위치가 같아 길이 8의 가지를 6과 2로 나눕니다. 결과는 KV 값이 아닌 저장 위치 목록입니다."}]},code:source6,lang:"python"},
"radix-split": {...{"path": "sglang/python/sglang/srt/mem_cache/radix_cache.py", "highlight": [663, 686], "desc": "한 번 계산한 기록을 두 경로가 함께 가리키도록 index 구간을 나눕니다.", "annotations": [{"lines": [663, 686], "color": "sky", "note": "앞 6개의 위치 index와 뒤 2개의 index를 나눕니다. clone 대상은 index tensor이며 모든 층의 GPU KV를 복사하는 명령은 아닙니다."}]},code:source6,lang:"python"},
"radix-key": {...{"path": "sglang/python/sglang/srt/mem_cache/radix_cache.py", "highlight": [164, 220], "desc": "namespace와 페이지 단위를 맞춘 뒤 입력 ID의 일치를 셉니다.", "annotations": [{"lines": [164, 220], "color": "sky", "note": "같은 namespace에서 6개가 같아도 page_size=4이면 match=4입니다. 다른 namespace는 다른 child key로 찾습니다."}]},code:source6,lang:"python"},
"sglang-last-token": {...{"path": "sglang/python/sglang/srt/managers/schedule_batch.py", "highlight": [1715, 1725], "desc": "마지막 출력 점수를 계산할 위치를 남깁니다.", "annotations": [{"lines": [1715, 1725], "color": "sky", "note": "입력 8이면 상한 7입니다. 출력 logprob나 별도 모델 조건은 더 짧게 만들 수 있습니다."}]},code:source7,lang:"python"},
"hash-key": {...{"path": "vllm/vllm/v1/core/kv_cache_utils.py", "highlight": [596, 624], "desc": "현재 묶음과 그 앞의 문맥을 하나의 조회 키에 넣습니다.", "annotations": [{"lines": [596, 624], "color": "sky", "note": "B=4의 [1,2,3,4]는 같지만 [5,6,7,8]과 [5,6,9,10]은 다른 키입니다. parent와 extra_keys도 비교에 포함합니다."}]},code:source5,lang:"python"},
"vllm-last-token": {...{"path": "vllm/vllm/v1/core/kv_cache_manager.py", "highlight": [245, 264], "desc": "입력 전체의 KV와 새 출력 점수 계산을 구분합니다.", "annotations": [{"lines": [245, 264], "color": "sky", "note": "전체 8이 저장되어 있어도 최대 7까지만 조회하고, hash 단위와 block이 4이면 결과 4라 마지막 4개를 다시 계산합니다."}]},code:source4,lang:"python"},
"block-hit": {...{"path": "vllm/vllm/v1/core/single_type_kv_cache_manager.py", "highlight": [722, 774], "desc": "full block과 더 작은 hash 경계의 실제 조회를 구분합니다.", "annotations": [{"lines": [722, 774], "color": "sky", "note": "이 글의 B=4 모형은 alignment=4인 첫 경로입니다. fine-grained 경로에서는 내부 hash 경계를 따로 찾아 같은 내림식으로 일반화할 수 없습니다."}]},code:source9,lang:"python"},
"radix-evict": {...{"path": "sglang/python/sglang/srt/mem_cache/radix_cache.py", "highlight": [551, 615], "desc": "사용 중인 경로를 보호하고 비어 있는 leaf부터 자리를 돌려줍니다.", "annotations": [{"lines": [551, 615], "color": "sky", "note": "공유 6+R3의 2를 잠그면 8이 보호되고 나머지 4만 반환할 수 있습니다. 요청 5보다 작아도 heap이 비면 반환량 4로 끝납니다."}]},code:source6,lang:"python"},
"reverse-free": {...{"path": "vllm/vllm/v1/core/single_type_kv_cache_manager.py", "highlight": [519, 527], "desc": "요청의 뒤 block을 먼저 반환 후보로 전달합니다.", "annotations": [{"lines": [519, 527], "color": "sky", "note": "R2의 [5,9]는 9부터 전달하지만 다른 요청이 5를 참조하면 5는 free 후보가 되지 않습니다."}]},code:source9,lang:"python"},
"free-queue": {...{"path": "vllm/vllm/v1/core/block_pool.py", "highlight": [702, 743], "desc": "참조 수와 hash 유무를 보고 실제 free queue를 갱신합니다.", "annotations": [{"lines": [702, 743], "color": "sky", "note": "touch는 ref 0 block을 queue에서 빼고, 반환은 hash 없는 block을 앞에 둡니다. 모든 반환을 tail에 넣는 단순 LRU와 다릅니다."}]},code:source1,lang:"python"},
"lpm-sort": {...{"path": "sglang/python/sglang/srt/managers/schedule_policy.py", "highlight": [487, 498], "desc": "실제 match 길이를 정렬하되 이번 배치에서 미루는 요청도 구분합니다.", "annotations": [{"lines": [487, 498], "color": "sky", "note": "hit 6인 A가 temporary_deprioritized이면 hit 6 B, miss 0, A 순서가 될 수 있습니다. 길이만 보는 고정 정렬이 아닙니다."}]},code:source8,lang:"python"},
"lpm-fallback": {...{"path": "sglang/python/sglang/srt/managers/schedule_policy.py", "highlight": [340, 353], "desc": "대기열이 길면 이 정책의 비싼 matching·정렬 경로를 바꿉니다.", "annotations": [{"lines": [340, 353], "color": "sky", "note": "고정 버전의 LPM과 HRRN은 대기 129개에서 FCFS를 반환합니다. 128과 129의 경계입니다."}]},code:source8,lang:"python"},
"metadata": {...{"path": "vllm/vllm/v1/attention/backend.py", "highlight": [411, 438], "desc": "새 query와 기존 기록의 읽기·쓰기 위치를 kernel에 전달합니다.", "annotations": [{"lines": [411, 438], "color": "sky", "note": "R2 하나의 새 query 4개라면 query_start_loc=[0,4], seq_lens=[8], block table=[5,9], slot=[36,37,38,39]입니다."}]},code:source0,lang:"python"},
"cascade": {...{"path": "vllm/vllm/v1/attention/backends/flash_attn.py", "highlight": [1537, 1561], "desc": "공유 길이만으로 cascade를 켜지 않도록 지원 조건을 검사합니다.", "annotations": [{"lines": [1537, 1561], "color": "sky", "note": "prefix 4는 256보다 짧고, prefix 2496도 요청 3개는 8보다 작아 false입니다. 남은 비용 휴리스틱도 확인해야 합니다."}]},code:source2,lang:"python"},
"hybrid-hit": {...{"path": "vllm/vllm/v1/core/kv_cache_coordinator.py", "highlight": [711, 814], "desc": "서로 다른 cache group에 모두 유효한 길이로 결과를 맞춥니다.", "annotations": [{"lines": [711, 814], "color": "sky", "note": "full 2496·window 2080이면 결과 2080입니다. 단순 두 group은 1회 처리하고 full group은 다시 조회하지 않고 필요한 길이만큼 줄입니다."}]},code:source3,lang:"python"},
};
