import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { SubmissionControlViz } from "../competition-workflow/viz/ModernCompetitionViz";

export default function SubmissionControlArticle(){return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Upload 횟수와 external score가 다음 결정을 바꾼 횟수는 다릅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">Schema 오류 수정이나 동일 candidate 재실행은 submission이지만 model 선택을 바꾸는 feedback이 아닐 수 있습니다. Public score를 본 뒤 feature·weight·split·candidate를 바꾼 사건만 adaptive feedback ledger에 더합니다.</p></div><TermBreakdown title="외부 평가의 네 상태" items={[{term:"Submission",description:"External evaluator에 prediction artifact를 보낸 사건입니다."},{term:"Observed feedback",description:"Score·rank·error message처럼 외부에서 돌아온 정보입니다."},{term:"Decision-changing feedback",description:"후속 model·feature·protocol 선택을 실제로 바꾼 feedback입니다."},{term:"Frozen candidate",description:"Feedback budget과 종료 조건 뒤 더 바꾸지 않기로 한 recipe입니다."}]}/><SubmissionControlViz/><ContentBoundary article="competition-submission-control"/></section>
  <section id="feedback" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Decision-changing indicator만 더해 feedback budget을 셉니다</h2><ExplainedFormula question="20 submissions 중 adaptive feedback used가 6일 수 있는 이유는 무엇인가요?" idea={<p>각 external result가 후속 결정을 바꿨는지 indicator를 둡니다. Schema fix·동일 artifact 재실행은 0, score를 보고 후보를 바꾼 사건은 1로 합산합니다.</p>} formula={String.raw`B_{\mathrm{used}}=\sum_{t=1}^{N_{\mathrm{sub}}}\mathbf1[d_{t+1}\ne d_t\;\text{because of }f_t]`} annotatedFormula={String.raw`\begin{aligned}a_t&=\underbrace{\mathbf1[d_{t+1}\ne d_t\text{ because of }f_t]}_{\text{feedback이 다음 결정을 바꿨는지 표시}}\\B_{\mathrm{used}}&=\underbrace{\sum_{t=1}^{N_{\mathrm{sub}}}a_t}_{\text{decision-changing feedback만 누적}}\\\mathrm{freeze}&=\underbrace{\mathbf1[B_{\mathrm{used}}\ge B_{\max}]}_{\text{사전 budget 도달 시 선택을 동결}}\end{aligned}`} operations={[{expression:String.raw`\mathbf1[d_{t+1}\ne d_t\text{ because of }f_t]`,annotation:["feedback 전후 결정을 비교해","인과적으로 바뀐 사건만 1"]},{expression:String.raw`\sum_ta_t`,annotation:["adaptive indicators를 더해","사용한 feedback 횟수 계산"]},{expression:String.raw`\mathbf1[B_{\mathrm{used}}\ge B_{\max}]`,annotation:["사용량을 사전 한도와 비교해","freeze 조건을 발동"]}]} terms={[{symbol:String.raw`f_t`,name:"External feedback",description:"Submission t 뒤 관측한 score·rank·error입니다."},{symbol:String.raw`d_t`,name:"Selection decision",description:"시점 t의 candidate·feature·protocol 선택입니다."},{symbol:String.raw`B_{\max}`,name:"Feedback budget",description:"실험 전에 정한 adaptive change 한도입니다."}]} assumptions={["Decision log가 feedback 전후를 시간순으로 보존합니다.","Budget은 generalization theorem이 아니라 운영 통제입니다."]} interpretation="20회 중 schema fix 4·동일 재실행 2가 있고 score로 다음 선택을 바꾼 6회라면 B_used=6입니다."/></section>
  <section id="manifest" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Final manifest는 candidate부터 제출 file까지 rollback 가능한 lineage를 봉인합니다</h2><TermBreakdown title="Manifest를 한 줄씩 기록" items={[{term:"Candidate lineage",description:"Run ID·code·data·split·preprocess·checkpoint입니다."},{term:"Retrain receipt",description:"Full-data refit 여부·seed·새 checkpoint와 OOF candidate의 관계입니다."},{term:"Inference receipt",description:"Environment image·batch·postprocess·row ID count와 order입니다."},{term:"File integrity",description:"Missing·range checks와 submission checksum입니다."}]}/></section>
  <section id="boundary" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Manifest는 나쁜 선택을 고치지 않지만 재생·diff·rollback을 가능하게 합니다</h2><div id="paper-submission-control" className="not-prose"><CitationBlock source="Blum & Hardt — The Ladder" citeKey={1} type="paper" href="https://proceedings.mlr.press/v37/blum15.html">Adaptive submission이 holdout에 overfit하는 문제와 제한적 score update mechanism을 분석합니다. 제출 횟수만 줄이면 private score가 보장된다는 뜻은 아닙니다.</CitationBlock></div></section>
</div>}
