import ExplainedFormula from "@/components/ui/explained-formula";
import LangGraphViz from "./viz/LangGraphViz";

export default function LangGraph() {
  return <section id="langgraph" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">LangGraph에서는 대화 전체보다 state channel과 reducer가 병렬 실행의 의미를 결정합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>현재 Graph API는 state·node·edge를 중심으로 workflow를 구성합니다. Node는 partial update를 반환하고 state key별 reducer가 기존 값과 새 값을 합칩니다. 기본 overwrite, append, set union, single owner는 의미가 다르므로 같은 key에 병렬 branch가 쓰기 전에 고정해야 합니다.</p><p>동적 fan-out은 task ID별 <code>pending·success·timeout·failed</code> 상태와 artifact checksum을 typed state로 저장합니다. ID-keyed set reducer는 duplicate retry를 한 번만 반영하고, 같은 artifact ID의 다른 checksum은 conflict로 올립니다. Timeout과 retry budget을 소진한 뒤에는 required receipt coverage와 global validator를 join gate로 검사하고, 모든 전이를 trace에 남깁니다.</p></div><ExplainedFormula question="병렬 branch의 실행 순서가 달라도 같은 join 결과를 얻으려면 reducer에 어떤 성질이 필요할까요?" idea={<>재시도와 도착 순서 변화에 강한 set-like merge라면 결합법칙·교환법칙·멱등성을 확인합니다. 모든 state에 무조건 필요한 법칙은 아니지만 unordered parallel join의 좋은 안전 조건입니다.</>} formula={String.raw`\begin{aligned}
\rho(\rho(x,a),b)&=\rho(x,\rho(a,b))\\
\rho(x,a)&=\rho(a,x)\\
\rho(\rho(x,a),a)&=\rho(x,a)
\end{aligned}`} terms={[{symbol:"rho",name:"reducer",description:"현재 channel 값과 branch update를 새 state로 합치는 함수입니다."},{symbol:"x",name:"accumulated state",description:"Join 전까지 저장된 기존 channel 값입니다."},{symbol:"a,b",name:"parallel updates",description:"같은 super-step 또는 retry에서 들어온 worker 결과입니다."}]} assumptions={["순서가 의미 있는 log는 commutative set이 아니라 stable event ID와 ordered reducer를 사용합니다.","같은 artifact ID의 내용 충돌은 조용히 dedup하지 않고 conflict로 올립니다.","Reducer property를 unit/property test하고 framework default overwrite를 그대로 가정하지 않습니다."]} interpretation="Set union은 같은 receipt가 retry로 두 번 와도 결과가 같지만 list append는 중복됩니다. Ordered history가 필요하면 event ID·sequence와 dedup 규칙을 따로 둡니다."/><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Checkpointer는 node 중간이 아니라 정해진 경계의 state를 저장하며, resume 시 node가 처음부터 재실행될 수 있습니다. Database insert와 outbox event는 stable operation key의 unique constraint로 같은 transaction에 쓰고, sender는 provider receipt를 저장해 duplicate를 막습니다. Commit 전·후와 message 발송 전·후에 crash를 주입한 뒤 두 번 resume해도 DB row와 외부 동작이 한 번뿐인지 검사하며, provider가 idempotency를 지원하지 않는 되돌릴 수 없는 동작에는 interrupt·사람 승인·compensation 절차를 둡니다.</p></div><div className="not-prose my-8"><LangGraphViz /></div><div id="standard-langgraph" className="not-prose my-8 scroll-mt-24 border-l border-primary/50 pl-4"><p className="text-xs font-bold text-primary">공식 문서 · LangGraph Graph API</p><p className="mt-2 text-sm leading-6 text-muted-foreground">공식 문서는 state·node·edge, key별 reducer, Send 기반 분기, checkpoint 뒤 node 재실행과 idempotency를 현재 API로 설명합니다. 이 글의 join 수식은 구현 원칙을 명시한 계약이며 LangGraph 자체의 수학 정리로 표현하지 않습니다.</p><a className="mt-3 inline-block text-sm font-medium text-primary hover:underline" href="https://docs.langchain.com/oss/python/langgraph/graph-api" target="_blank" rel="noreferrer">State·reducer·re-execution 문서 보기</a></div></section>;
}
