import type { Article } from "../types";

export const philosophyTopicsArticles: Article[] = [
  {
    slug: "identity-through-change",
    title: "부품을 모두 바꾼 자전거는 같은 자전거인가: 변화 속 정체성",
    subcategory: "topics-identity",
    sections: [
      { id: "overview", title: "오래 탄 자전거의 부품 하나를 바꾸는 데서 시작합니다" },
      { id: "black-box", title: "물질·연속성·기능·역사의 네 단서를 나눕니다" },
      { id: "case", title: "부품 10개를 10년에 걸쳐 바꾸고 옛 부품을 다시 조립합니다" },
      { id: "picture", title: "닮음과 바로 그 하나임을 다른 선에 놓습니다" },
      { id: "need", title: "변하면서도 같은 것이라고 말할 기준이 필요합니다" },
      { id: "names", title: "수적 동일성·질적 변화·지속 기준에 이름을 붙입니다" },
      { id: "mechanism", title: "교체 시점마다 네 기준이 어떤 답을 만드는지 추적합니다" },
      { id: "source", title: "플루타르코스의 테세우스 배를 두 자전거에 대입합니다" },
      { id: "comparison", title: "지속 이론은 시간이 흐르는 존재 방식을 다르게 그립니다" },
      { id: "limits", title: "사물의 기준을 사람의 정체성과 곧장 같게 두지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/identity-through-change"),
  },
  {
    slug: "free-will-control-and-responsibility",
    title: "다른 선택이 가능해야 책임질 수 있는가: 자유의지와 통제",
    subcategory: "topics-freedom",
    sections: [
      { id: "overview", title: "위협을 받고 창고 문을 연 직원의 책임에서 시작합니다" },
      { id: "black-box", title: "선택지·이유·강제·책임의 흐름을 나눕니다" },
      { id: "case", title: "통제 조건 100을 정보·대안·이유·강제 없음으로 나눕니다" },
      { id: "picture", title: "원인이 있다는 것과 억지로 시켰다는 것을 구분합니다" },
      { id: "need", title: "칭찬과 비난에는 행위자가 통제했다는 근거가 필요합니다" },
      { id: "names", title: "대안 가능성·행위의 원천·책임 통제에 이름을 붙입니다" },
      { id: "mechanism", title: "같은 문 열기라도 네 조건이 책임을 바꾸는 경로를 봅니다" },
      { id: "source", title: "에픽테토스의 통제 구분을 현대 자유의지 논쟁과 분리해 읽습니다" },
      { id: "comparison", title: "프랑크푸르트 사례는 다른 선택지가 꼭 필요한지 묻습니다" },
      { id: "limits", title: "무작위 선택이나 느낌만으로 자유를 증명하지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/free-will-control-and-responsibility"),
  },
  {
    slug: "reference-context-and-speech-acts",
    title: "말은 무엇을 가리키고 무엇을 하는가: 지시·맥락·말행위",
    subcategory: "topics-language",
    sections: [
      { id: "overview", title: "은행 앞에서 만나자는 한 문장의 모호함에서 시작합니다" },
      { id: "black-box", title: "낱말·맥락·가리키는 대상·말의 힘을 연결합니다" },
      { id: "case", title: "100명의 해석과 10만원을 갚겠다는 약속을 나눠 봅니다" },
      { id: "picture", title: "문장이 담은 내용과 문장으로 한 일을 구분합니다" },
      { id: "need", title: "사전 뜻만으로 실제 대화의 성공과 실패를 설명할 수 없습니다" },
      { id: "names", title: "지시와 기술·맥락 의미·발화수반력에 이름을 붙입니다" },
      { id: "mechanism", title: "장소 단서와 관계 규칙이 해석과 의무를 바꾸는 경로를 봅니다" },
      { id: "source", title: "러셀의 기술 이론으로 존재하지 않는 대상을 말하는 법을 봅니다" },
      { id: "comparison", title: "말행위 이론은 참과 거짓 밖의 성공 조건을 묻습니다" },
      { id: "limits", title: "말뜻을 화자의 속마음이나 사전 정의 하나로 줄이지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/reference-context-and-speech-acts"),
  },
  {
    slug: "consciousness-pain-and-other-minds",
    title: "내 통증과 남의 통증을 어떻게 아는가: 의식과 다른 마음",
    subcategory: "topics-consciousness",
    sections: [
      { id: "overview", title: "통증 8점이라는 말과 검사 수치에서 시작합니다" },
      { id: "black-box", title: "느낌·보고·행동·측정의 네 창을 나눕니다" },
      { id: "case", title: "통증 8점과 세 가지 관찰 자료를 한 진료표에 놓습니다" },
      { id: "picture", title: "당사자의 접근과 관찰자의 접근을 겹쳐 봅니다" },
      { id: "need", title: "의식은 공개 자료만으로도 혼자 느낌만으로도 다 설명되지 않습니다" },
      { id: "names", title: "현상적 성격·1인칭과 3인칭 증거·다른 마음 추론에 이름을 붙입니다" },
      { id: "mechanism", title: "말·행동·몸의 변화가 신뢰 가능한 판단으로 모이는 경로를 봅니다" },
      { id: "source", title: "의식 연구가 구분하는 질감과 접근 가능성을 진료 사례에 대입합니다" },
      { id: "comparison", title: "다른 마음은 유추·최선의 설명·증언으로 접근할 수 있습니다" },
      { id: "limits", title: "뇌의 상관관계와 경험의 완전한 설명을 같은 주장으로 두지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/consciousness-pain-and-other-minds"),
  },
  {
    slug: "aesthetic-taste-judgment-and-context",
    title: "취향인데도 더 나은 판단이 있을까: 미적 경험·훈련·맥락",
    subcategory: "topics-aesthetics",
    sections: [
      { id: "overview", title: "같은 공연을 두고 갈린 100명의 평가에서 시작합니다" },
      { id: "black-box", title: "느낌·작품의 특징·비교 경험·맥락을 연결합니다" },
      { id: "case", title: "첫 감상 60대 40과 반복 감상 뒤의 이유를 비교합니다" },
      { id: "picture", title: "좋아하는 마음·다수의 표·근거 있는 판단을 나눕니다" },
      { id: "need", title: "취향 차이를 인정하면서도 이유를 주고받을 길이 필요합니다" },
      { id: "names", title: "미적 판단·훈련된 취향·미적 맥락에 이름을 붙입니다" },
      { id: "mechanism", title: "주의와 비교가 전에는 안 들리던 구조를 드러내는 경로를 봅니다" },
      { id: "source", title: "흄의 취미 기준이 요구한 연습과 편견 점검을 봅니다" },
      { id: "comparison", title: "현대 미학은 미적 성질과 판단의 여러 조건을 나눕니다" },
      { id: "limits", title: "전문가 합의나 다수결을 작품 가치의 자동 판정기로 쓰지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/aesthetic-taste-judgment-and-context"),
  },
  {
    slug: "meaning-in-life-attraction-worth-and-commitment",
    title: "즐거움만으로 충분한가: 삶의 의미와 가치 있는 참여",
    subcategory: "topics-meaning",
    sections: [
      { id: "overview", title: "깨어 있는 100시간을 어디에 쓰는지부터 봅니다" },
      { id: "black-box", title: "끌림·가치·지속적 참여·삶의 이야기를 연결합니다" },
      { id: "case", title: "한 주 100시간을 생계·돌봄·관계·선택한 일로 나눕니다" },
      { id: "picture", title: "행복한 기분·도덕적 옳음·의미 있는 삶을 구분합니다" },
      { id: "need", title: "좋아하지만 해로운 일과 가치 있지만 무관심한 일을 함께 설명해야 합니다" },
      { id: "names", title: "주관적 끌림·객관적 가치·결합 관점에 이름을 붙입니다" },
      { id: "mechanism", title: "작은 약속이 능력과 관계와 삶의 방향을 만드는 경로를 봅니다" },
      { id: "source", title: "아리스토텔레스의 잘 삶을 순간 감정과 구분해 읽습니다" },
      { id: "comparison", title: "현대 논쟁은 주관주의·객관주의·결합설을 비교합니다" },
      { id: "limits", title: "삶의 의미를 행복·도덕·우주의 목적 하나와 같게 두지 않습니다" },
    ],
    component: () => import("@/pages/articles/philosophy-topics/meaning-in-life-attraction-worth-and-commitment"),
  },
];
