import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { TripletMiningViz } from "../contrastive-learning/viz/ModernContrastiveViz";

export default function TripletMetricLearningArticle(){return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Triplet learning은 세 sample의 상대 거리 조건을 학습합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">Triplet은 기준 <strong>anchor</strong>, 같은 의미의 <strong>positive</strong>, 구분해야 할 <strong>negative</strong>로 구성됩니다. 목표는 negative가 positive보다 일정 margin만큼 더 멀게 만드는 것입니다.</p></div><TermBreakdown title="Triplet의 세 자리" items={[{term:"Anchor a",description:"두 관계를 비교하는 기준 embedding입니다."},{term:"Positive p",description:"Anchor와 가까워져야 하는 embedding입니다."},{term:"Negative n",description:"Anchor와 구분되어 멀어져야 하는 embedding입니다."},{term:"Margin m",description:"Negative distance가 positive distance보다 더 커야 하는 최소 여유입니다.",boundary:"Distance 종류와 normalization scale에 따라 같은 숫자의 뜻이 달라집니다."}]}/><TripletMiningViz/><ContentBoundary article="triplet-metric-learning"/></section>
  <section id="geometry" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Unit embedding에서 cosine 순위와 squared distance 순위는 반대 방향으로 같습니다</h2><ExplainedFormula question="왜 정규화된 embedding에서는 cosine이 큰 이웃이 Euclidean distance도 작나요?" idea={<p>차이 vector의 제곱을 전개하면 두 norm 제곱과 내적이 나옵니다. 두 norm이 1이면 상수 2에서 cosine의 두 배를 뺀 식이 됩니다.</p>} formula={String.raw`\lVert z_i-z_j\rVert_2^2=2-2z_i^\top z_j`} annotatedFormula={String.raw`\begin{aligned}d_{ij}^2&=\underbrace{\lVert z_i-z_j\rVert_2^2}_{\text{두 unit embedding의 차이를 제곱}}\\&=\underbrace{\lVert z_i\rVert_2^2+\lVert z_j\rVert_2^2-2z_i^\top z_j}_{\text{차이 제곱을 norm과 내적으로 전개}}\\&=\underbrace{2-2\operatorname{sim}(i,j)}_{\text{두 unit norm을 1로 대입}}\end{aligned}`} operations={[{expression:String.raw`\lVert z_i-z_j\rVert_2^2`,annotation:["두 vector의 성분 차이를 만들고","제곱해 모두 더하여 거리 계산"]},{expression:String.raw`\lVert z_i\rVert_2^2+\lVert z_j\rVert_2^2-2z_i^\top z_j`,annotation:["차이 제곱을 전개해","개별 길이와 방향 일치로 분해"]},{expression:String.raw`2-2\operatorname{sim}(i,j)`,annotation:["unit norm 두 개를 1+1로 바꾸고","cosine이 클수록 거리가 작게 변환"]}]} terms={[{symbol:String.raw`d_{ij}^2`,name:"Squared Euclidean distance",description:"두 embedding 사이 직선 거리의 제곱입니다."},{symbol:String.raw`z_i^\top z_j`,name:"Unit-vector inner product",description:"두 vector가 정규화됐을 때 cosine similarity입니다."}]} assumptions={["두 embedding의 L2 norm이 1입니다.","다른 learned metric에는 이 동치가 자동 적용되지 않습니다."]} interpretation="Cosine 0.8이면 squared distance는 0.4입니다. 정규화하지 않은 (1,0)과 (2,0)은 cosine 1이지만 distance 1이라 반례가 됩니다."/></section>
  <section id="margin" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Hinge는 margin을 위반한 triplet에만 loss를 남깁니다</h2><ExplainedFormula question="Positive 0.4, negative 0.5, margin 0.2이면 왜 loss가 0.1인가요?" idea={<p>
            positive 거리에서 negative 거리를 빼고 필요한 여유를 더합니다. 결과가 양수면 부족한 거리이고 음수면 이미 조건을 만족했으므로 0으로 자릅니다.
          </p>} formula={String.raw`\begin{aligned}u&=d(a,p)-d(a,n)+m\\\mathcal L_{tri}&=\max(0,u)\end{aligned}`} annotatedFormula={String.raw`\begin{aligned}d_p&=\underbrace{d(a,p)}_{\text{anchor와 positive 거리}}\\d_n&=\underbrace{d(a,n)}_{\text{anchor와 negative 거리}}\\u&=\underbrace{d_p-d_n}_{\text{현재 상대 거리 차이}}+\underbrace{m}_{\text{필요한 여유}}\\\mathcal L_{tri}&=\underbrace{\max(0,u)}_{\text{위반량만 loss로 남김}}\end{aligned}`} operations={[{expression:String.raw`d(a,p)-d(a,n)`,annotation:["가까워야 할 거리에서 먼 거리 값을 빼","현재 relative ordering을 측정"]},{expression:"+m",annotation:["negative가 더 멀어야 할","최소 안전 여유를 요구"]},{expression:String.raw`\max(0,u)`,annotation:["조건을 만족한 음수 위반량은 0으로 자르고","부족한 거리만 gradient로 전달"]}]} terms={[{symbol:String.raw`d(a,p)`,name:"Positive distance",description:"Anchor와 positive 사이 거리입니다."},{symbol:String.raw`d(a,n)`,name:"Negative distance",description:"Anchor와 negative 사이 거리입니다."},{symbol:"m",name:"Margin",description:"Negative가 추가로 멀어야 하는 여유입니다."}]} assumptions={["Pair relation이 정확합니다.","학습·평가가 같은 distance convention을 씁니다.","Margin은 embedding scale에 맞춰 선택합니다."]} interpretation="0.4−0.5+0.2=0.1이 남습니다. Negative가 0.9이면 −0.3을 max가 0으로 잘라 easy triplet이 됩니다."/></section>
  <section id="mining" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Hard negative는 sample이 아니라 versioned mining 결과입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            가장 가까운 후보가 실제 negative라는 보장은 없어도 현재 encoder가 가까이 놓은 후보를 쓰면 정보량은 커집니다. Miner receipt에는 encoder
            hash와 corpus/index snapshot을 남기고 candidate depth, duplicate·multi-positive filter, selection rule도
            함께 적습니다.
          </p><p>
            random·semi-hard·hard bucket별 loss와 downstream metric을 나누고 hidden positive 비율을 확인합니다. offline
            candidate는 encoder가 바뀌면 낡으므로 재생성 조건을 release gate에 둡니다.
          </p></div><div id="paper-facenet" className="not-prose mt-8 scroll-mt-24"><CitationBlock type="paper" citeKey={1} source="Schroff et al. — FaceNet" href="https://openaccess.thecvf.com/content_cvpr_2015/html/Schroff_FaceNet_A_Unified_2015_CVPR_paper.html">Unit hypersphere embedding·triplet loss·online semi-hard mining을 얼굴 verification·recognition·clustering에 적용합니다. 논문의 margin과 mining recipe를 임의 retrieval corpus의 보편 설정으로 사용하지 않습니다.</CitationBlock></div></section>
</div>}
