import { motion } from "framer-motion";
import type { ReactNode } from "react";
import { AnimatedSceneControls, useAnimatedScenes } from "@/components/viz/AnimatedSceneControls";
import VizFrame from "@/components/viz/VizFrame";

const border = "var(--border)";
const muted = "var(--muted-foreground)";
const accent = "var(--primary)";

function Arrow({ x1, y1, x2, y2, id, active = false }: { x1: number; y1: number; x2: number; y2: number; id: string; active?: boolean }) {
  return <g><defs><marker id={id} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill={active ? accent : muted}/></marker></defs><motion.line x1={x1} y1={y1} x2={x2} y2={y2} stroke={active ? accent : muted} strokeWidth="1.25" markerEnd={`url(#${id})`} initial={false} animate={{ pathLength: active ? 1 : .84 }}/></g>;
}

function Box({ x, y, w, h, label, detail, active = false, shape = "rect" }: { x:number; y:number; w:number; h:number; label:string; detail?:string; active?:boolean; shape?:"rect"|"diamond"|"circle" }) {
  const common = { fill: active ? "color-mix(in srgb, var(--primary) 10%, transparent)" : "var(--background)", stroke: active ? accent : border, strokeWidth: 1.25 };
  return <motion.g initial={false} animate={{ opacity: active ? 1 : .64, scale: active ? 1.02 : 1 }} style={{ transformOrigin: `${x+w/2}px ${y+h/2}px` }}>
    {shape === "diamond" ? <path d={`M${x+w/2} ${y}L${x+w} ${y+h/2}L${x+w/2} ${y+h}L${x} ${y+h/2}Z`} {...common}/> : shape === "circle" ? <circle cx={x+w/2} cy={y+h/2} r={Math.min(w,h)/2} {...common}/> : <rect x={x} y={y} width={w} height={h} rx="7" {...common}/>} 
    <text x={x+w/2} y={y+h/2-(detail?4:-3)} textAnchor="middle" className="fill-foreground text-[12px] font-bold sm:text-[10px]">{label}</text>
    {detail && <text x={x+w/2} y={y+h/2+13} textAnchor="middle" className="fill-muted-foreground text-[10px] sm:text-[8px]">{detail}</text>}
  </motion.g>;
}

function Scene({ id, eyebrow, title, description, labels, notes, children }: { id:string; eyebrow:string; title:string; description:string; labels:readonly string[]; notes:readonly string[]; children:(active:number)=>ReactNode }) {
  const controls = useAnimatedScenes(labels.length, 3000);
  return <VizFrame title={title} description={description} className="my-8"><div id={id} data-viz tabIndex={0} onKeyDown={controls.onKeyDown} className="min-w-0 overflow-hidden border-y border-border/70 bg-background px-4 py-6 outline-none focus-visible:ring-2 focus-visible:ring-primary sm:px-6"><p className="text-[11px] font-black uppercase tracking-[0.16em] text-primary">{eyebrow} · {String(controls.active+1).padStart(2,"0")}</p><h3 className="mt-2 text-lg font-bold leading-7">{labels[controls.active]}</h3><div data-viz-canvas className="mt-5 min-w-0 overflow-hidden">{children(controls.active)}</div><p className="mt-4 border-l border-primary/50 pl-4 text-sm leading-6 text-muted-foreground">{notes[controls.active]}</p><AnimatedSceneControls labels={[...labels]} {...controls}/></div></VizFrame>;
}

export function PairContractViz() {
  const labels=["관계를 먼저 정의","Positive·negative·unknown","Encoder h","Projection z와 비교"] as const;
  const notes=["Loss보다 먼저 현재 task에서 무엇을 같고 다르게 볼지 적습니다.","근거가 부족한 pair는 억지 negative가 아니라 unknown으로 제외합니다.","Encoder h는 downstream이 재사용할 표현입니다.","Projection head는 loss 전용 z를 만들고 normalization 뒤 방향을 비교합니다."] as const;
  return <Scene id="pair-contract-viz" eyebrow="Meaning before loss" title="Sample 관계가 embedding geometry로 바뀌는 흐름" description="Pair label→encoder→projection→comparison을 한 장면씩 봅니다." labels={labels} notes={notes}>{active=><svg viewBox="0 0 360 210" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={10} y={68} w={72} h={54} label="task rule" detail="same? different?" active={active===0}/><Arrow x1={83} y1={95} x2={111} y2={95} id="pair-a" active={active===1}/><Box x={114} y={20} w={86} h={42} label="positive" detail="pull together" active={active===1}/><Box x={114} y={76} w={86} h={42} label="negative" detail="push apart" active={active===1}/><Box x={114} y={132} w={86} h={42} label="unknown" detail="exclude" active={active===1}/><Arrow x1={202} y1={95} x2={228} y2={95} id="pair-b" active={active===2}/><Box x={232} y={68} w={48} h={54} label="fθ" detail="h" active={active===2} shape="circle"/><Arrow x1={281} y1={95} x2={299} y2={95} id="pair-c" active={active===3}/><Box x={302} y={68} w={48} h={54} label="gφ" detail="unit z" active={active===3} shape="circle"/><text x="326" y="148" textAnchor="middle" className="fill-muted-foreground text-[10px] sm:text-[8px]">cosine</text></svg>}</Scene>;
}

export function SimCLRObjectiveViz() {
  const labels=["원본에서 두 view","2B 후보 batch","Positive 확률","Temperature lens"] as const;
  const notes=["Augmentation 두 번이 같은 원본의 positive pair를 만듭니다.","Anchor 자신을 빼면 후보는 2B−1개이고 그중 positive는 하나입니다.","Positive score를 모든 후보 score 합으로 나누어 in-batch 분류 문제를 만듭니다.","작은 temperature는 가까운 후보 차이를 확대하므로 false negative도 더 세게 반영합니다."] as const;
  return <Scene id="simclr-objective-viz" eyebrow="SimCLR batch" title="Augmentation pair가 NT-Xent 분류 문제로 바뀝니다" description="View·candidate·probability·temperature를 순서대로 봅니다." labels={labels} notes={notes}>{active=><svg viewBox="0 0 360 210" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={14} y={76} w={54} h={48} label="x" detail="source" active={active===0}/><Arrow x1={69} y1={100} x2={98} y2={63} id="sim-a" active={active===0}/><Arrow x1={69} y1={100} x2={98} y2={139} id="sim-b" active={active===0}/><Box x={102} y={38} w={62} h={44} label="view i" detail="augment A" active={active===0}/><Box x={102} y={118} w={62} h={44} label="view j" detail="augment B" active={active===0}/><Arrow x1={165} y1={100} x2={190} y2={100} id="sim-c" active={active===1}/><g>{[0,1,2,3,4].map((i)=><circle key={i} cx={215+(i%2)*34} cy={54+Math.floor(i/2)*48} r="15" fill={i===0?accent:"var(--background)"} fillOpacity={i===0?.16:1} stroke={active>=1?(i===0?accent:border):border} strokeWidth="1.25"/>)}<text x="232" y="190" textAnchor="middle" className="fill-muted-foreground text-[10px] sm:text-[8px]">2B−1 candidates</text></g><Arrow x1={270} y1={100} x2={300} y2={100} id="sim-d" active={active===2}/><Box x={304} y={71} w={46} h={58} label="−log" detail="p(j|i)" active={active===2} shape="diamond"/><motion.circle cx="232" cy="54" r="25" fill="none" stroke={accent} strokeWidth="1.25" strokeDasharray="4 4" animate={{ opacity:active===3?1:0, scale:active===3?1.08:.9 }} style={{transformOrigin:"232px 54px"}}/><text x="232" y="22" textAnchor="middle" className="fill-foreground text-[11px] font-bold sm:text-[9px]" opacity={active===3?1:.42}>τ lens</text></svg>}</Scene>;
}

export function TripletMiningViz() {
  const labels=["Unit-vector geometry","Anchor·positive·negative","Margin gate","Versioned miner"] as const;
  const notes=["Unit vector에서는 cosine이 커질수록 squared Euclidean distance가 작아집니다.","Anchor를 기준으로 positive와 negative 거리를 따로 잽니다.","Negative가 positive보다 margin만큼 멀지 않을 때만 hinge loss가 남습니다.","가까운 후보는 label 누락일 수 있으므로 miner·index·filter revision을 함께 저장합니다."] as const;
  return <Scene id="triplet-mining-viz" eyebrow="Relative geometry" title="거리 조건과 negative mining을 같은 입력 계약으로 봅니다" description="Geometry→triplet→margin→snapshot 흐름입니다." labels={labels} notes={notes}>{active=><svg viewBox="0 0 360 210" role="img" aria-label={labels[active]} className="block h-auto w-full"><circle cx="74" cy="101" r="43" fill="none" stroke={active===0?accent:border} strokeWidth="1.25"/><line x1="74" y1="101" x2="105" y2="72" stroke={accent} strokeWidth="1.25"/><line x1="74" y1="101" x2="39" y2="79" stroke={muted} strokeWidth="1.25"/><text x="74" y="163" textAnchor="middle" className="fill-muted-foreground text-[10px] sm:text-[8px]">||z||₂=1</text><Box x={135} y={78} w={42} h={42} label="a" active={active===1} shape="circle"/><Box x={205} y={38} w={42} h={42} label="p" active={active===1} shape="circle"/><Box x={205} y={125} w={42} h={42} label="n" active={active===1} shape="circle"/><line x1="177" y1="91" x2="205" y2="68" stroke={active>=1?accent:muted} strokeWidth="1.25"/><line x1="177" y1="108" x2="205" y2="138" stroke={active>=1?accent:muted} strokeWidth="1.25"/><Box x={268} y={76} w={80} h={50} label="margin" detail="dₙ ≥ dₚ+m" active={active===2} shape="diamond"/><motion.g animate={{opacity:active===3?1:.48}}><rect x="258" y="144" width="94" height="46" rx="5" fill="var(--background)" stroke={active===3?accent:border} strokeWidth="1.25"/><text x="305" y="162" textAnchor="middle" className="fill-foreground text-[10px] font-bold sm:text-[8px]">miner receipt</text><text x="305" y="177" textAnchor="middle" className="fill-muted-foreground text-[9px] sm:text-[7px]">encoder·index·filter</text></motion.g></svg>}</Scene>;
}

export function SupervisedPositiveViz() {
  const labels=["Batch label 보기","Positive set P(i)","여러 log-prob 평균","빈 positive guard"] as const;
  const notes=["Label은 pair 관계를 만드는 입력이지 모든 same-label sample이 완전히 같다는 선언은 아닙니다.","Anchor와 같은 label인 다른 sample만 P(i)에 들어갑니다.","각 positive의 log-probability를 |P(i)|로 나눠 anchor 하나의 loss로 만듭니다.","P(i)가 비면 분모가 정의되지 않으므로 sampler나 explicit exclusion이 필요합니다."] as const;
  const points=[[48,66,"A₁"],[102,48,"A₂"],[96,105,"A₃"],[178,61,"B₁"],[225,118,"C₁"]] as const;
  return <Scene id="supervised-positive-viz" eyebrow="Multi-positive" title="Class label을 anchor별 positive 집합으로 바꿉니다" description="Batch→P(i)→평균→empty-set guard를 봅니다." labels={labels} notes={notes}>{active=><svg viewBox="0 0 360 210" role="img" aria-label={labels[active]} className="block h-auto w-full"><g>{points.map(([x,y,t],i)=><g key={t}><circle cx={x} cy={y} r="18" fill={t.startsWith("A")?accent:"var(--background)"} fillOpacity={t.startsWith("A")?.13:1} stroke={(active===1&&t.startsWith("A"))?accent:border} strokeWidth="1.25"/><text x={x} y={y+4} textAnchor="middle" className="fill-foreground text-[11px] font-bold sm:text-[9px]">{t}</text>{active===1&&i>0&&i<3&&<line x1="48" y1="66" x2={x} y2={y} stroke={accent} strokeWidth="1.25" strokeDasharray="4 3"/>}</g>)}</g><Arrow x1={247} y1={98} x2={271} y2={98} id="sup-a" active={active===2}/><Box x={276} y={54} w={72} h={88} label="mean" detail="Σ log p / |P|" active={active===2} shape="diamond"/><motion.g animate={{opacity:active===3?1:0}}><circle cx="225" cy="118" r="28" fill="none" stroke={accent} strokeWidth="1.25"/><text x="225" y="163" textAnchor="middle" className="fill-foreground text-[10px] font-bold sm:text-[8px]">P(C₁)=∅ → exclude</text></motion.g></svg>}</Scene>;
}

export function ContrastiveEvaluationViz() {
  const labels=["Miner candidate receipt","Stratified pair audit","Paired downstream test","Revision decision"] as const;
  const notes=["Similarity·domain bucket과 miner revision이 있어야 어떤 negative를 검토했는지 재현됩니다.","각 bucket에서 무작위 표본을 뽑아 hidden positive 비율과 agreement를 계산합니다.","같은 split·seed에서 baseline과 후보 embedding의 실제 task metric을 짝지어 비교합니다.","Pair·augmentation·miner 중 무엇을 고칠지 receipt로 남기고 독립 test를 다시 열지 않습니다."] as const;
  return <Scene id="contrastive-evaluation-viz" eyebrow="Evidence loop" title="Loss가 아니라 pair 품질과 downstream gain으로 release합니다" description="Candidate→audit→paired test→revision을 연결합니다." labels={labels} notes={notes}>{active=><svg viewBox="0 0 360 210" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={8} y={72} w={74} h={58} label="candidate" detail="bucket·revision" active={active===0}/><Arrow x1={83} y1={101} x2={106} y2={101} id="eval-a" active={active===1}/><Box x={110} y={66} w={72} h={70} label="pair audit" detail="FN rate" active={active===1}/><Arrow x1={183} y1={101} x2={206} y2={101} id="eval-b" active={active===2}/><Box x={210} y={66} w={72} h={70} label="paired test" detail="same seed" active={active===2}/><Arrow x1={283} y1={101} x2={304} y2={101} id="eval-c" active={active===3}/><Box x={308} y={72} w={44} h={58} label="gate" detail="revise" active={active===3} shape="diamond"/><motion.path d="M330 144C280 193 91 193 44 143" fill="none" stroke={accent} strokeWidth="1.25" strokeDasharray="5 4" initial={false} animate={{pathLength:active===3?1:0,opacity:active===3?1:0}}/><text x="186" y="188" textAnchor="middle" className="fill-muted-foreground text-[10px] sm:text-[8px]">failure pair → next data revision</text></svg>}</Scene>;
}
