import type { Article } from "../types";

const sections: Article["sections"] = [
  { id: "overview", title: "먼저 겪는 문제와 답" },
  { id: "black-box", title: "결정이 끝나는 전체 경로" },
  { id: "case", title: "같은 사건을 숫자로 확인" },
  { id: "picture", title: "첫 번째 선택 지점" },
  { id: "need", title: "역할을 나눈 이유" },
  { id: "names", title: "이제 붙이는 공식 이름" },
  { id: "mechanism", title: "한 요청을 끝까지 추적" },
  { id: "source", title: "실제 명령과 공식 문서" },
  { id: "comparison", title: "시험과 현장에서 달라지는 범위" },
  { id: "limits", title: "어디까지 적용할 수 있는가" },
];

const kubernetesNetworkSections: Article["sections"] = [
  { id: "overview", title: "한 번에 한 경계를 확인하는 이유" },
  { id: "map", title: "여섯 패킷 경계" },
  { id: "case", title: "GET 한 건의 수치 사례" },
  { id: "pod-boundary", title: "namespace·pause·veth" },
  { id: "service-path", title: "Service backend 선택" },
  { id: "calico-path", title: "Calico route·overlay" },
  { id: "mtu-egress", title: "MTU·SNAT·conntrack" },
  { id: "policy-dataplane", title: "policy와 데이터 플레인" },
  { id: "edge-mesh", title: "Gateway·service mesh" },
  { id: "evidence", title: "증거 수집 runbook" },
  { id: "source-map", title: "오래된 실습에서 다시 확인할 다섯 가지" },
  { id: "limits", title: "한계와 예측 질문" },
];

export const cloudArticles: Article[] = [
  {
    slug: "cloud-certification-roadmap-2026",
    title: "취업용 AWS·Azure 자격증은 목표 직무에서 거꾸로 고릅니다",
    subcategory: "cloud-roadmap",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-certification-roadmap-2026"),
  },
  {
    slug: "cloud-foundations-responsibility-regions",
    title: "클라우드는 서버보다 책임·위치·용량의 경계를 바꿉니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-foundations-responsibility-regions"),
  },
  {
    slug: "cloud-identity-access-hierarchy",
    title: "클라우드 권한은 주체·행동·대상·범위를 함께 판정합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-identity-access-hierarchy"),
  },
  {
    slug: "cloud-networking-request-path",
    title: "DNS에서 사설 데이터까지 요청 경로를 한 칸씩 추적합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-networking-request-path"),
  },
  {
    slug: "cloud-compute-selection",
    title: "VM·컨테이너·PaaS·함수는 운영할 단위로 고릅니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-compute-selection"),
  },
  {
    slug: "cloud-storage-database-selection",
    title: "객체·블록·파일·데이터베이스는 접근 약속으로 고릅니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-storage-database-selection"),
  },
  {
    slug: "cloud-reliability-observability-iac",
    title: "복구 목표에서 관측·IaC·백업·비용을 거꾸로 설계합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-reliability-observability-iac"),
  },
  {
    slug: "kubernetes-request-path-and-cka",
    title: "Kubernetes 요청 경로와 CKA v1.35: Pending에서 복구까지",
    subcategory: "cloud-kubernetes",
    sections,
    component: () => import("@/pages/articles/cloud/kubernetes-request-path-and-cka"),
  },
  {
    slug: "kubernetes-network-packet-path",
    title: "Kubernetes 패킷 경로: namespace에서 Calico·Gateway·eBPF까지",
    subcategory: "cloud-kubernetes",
    sections: kubernetesNetworkSections,
    component: () => import("@/pages/articles/cloud/kubernetes-network-packet-path"),
  },
  {
    slug: "aws-clf-c02-fast-study",
    title: "AWS CLF-C02 빠른 공부 지도: 역할과 시점으로 서비스를 가릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-clf-c02-fast-study"),
  },
  {
    slug: "aws-saa-c03-fast-study",
    title: "AWS SAA-C03 빠른 공부 지도: 제약표로 구조를 고릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-saa-c03-fast-study"),
  },
  {
    slug: "aws-developer-cloudops-paths",
    title: "AWS DVA-C02와 SOA-C03: 개발과 CloudOps 경로를 가릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-developer-cloudops-paths"),
  },
  {
    slug: "azure-az900-fast-study",
    title: "Azure AZ-900 빠른 공부 지도: 자원 계층과 관리 도구를 잇습니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-az900-fast-study"),
  },
  {
    slug: "azure-az104-fast-study",
    title: "Azure AZ-104 빠른 공부 지도: 만들고 끊고 복구합니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-az104-fast-study"),
  },
  {
    slug: "azure-ai200-fast-study",
    title: "Azure AI-200 빠른 공부 지도: AI 백엔드 한 요청을 끝까지 잇습니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-ai200-fast-study"),
  },
  {
    slug: "azure-architect-devops-paths",
    title: "Azure AZ-305와 AZ-400: 설계와 DevOps 경로를 가릅니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-architect-devops-paths"),
  },
];
