import type { Article } from "../types";

const sections: Article["sections"] = [
  { id: "overview", title: "한 문장 답과 공부할 이유" },
  { id: "black-box", title: "전체 흐름" },
  { id: "case", title: "작은 수치 사례" },
  { id: "picture", title: "이름 없는 선택 지도" },
  { id: "need", title: "이 구성이 필요한 이유" },
  { id: "names", title: "공식 용어와 서비스 이름" },
  { id: "mechanism", title: "한 경로를 끝까지 추적" },
  { id: "source", title: "공식 문서에 사례 적용" },
  { id: "comparison", title: "시험 범위와 선택 기준" },
  { id: "limits", title: "한계와 다음 학습" },
];

export const cloudArticles: Article[] = [
  {
    slug: "cloud-certification-roadmap-2026",
    title: "취업용 AWS·Azure 자격증은 목표 직무에서 거꾸로 고릅니다",
    subcategory: "cloud-roadmap",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-certification-roadmap-2026"),
  },
  {
    slug: "cloud-foundations-responsibility-regions",
    title: "클라우드는 서버보다 책임·위치·용량의 경계를 바꿉니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-foundations-responsibility-regions"),
  },
  {
    slug: "kubernetes-request-path-and-cka",
    title: "Kubernetes 요청 경로와 CKA v1.35: Pending에서 복구까지",
    subcategory: "cloud-roadmap",
    sections,
    component: () => import("@/pages/articles/cloud/kubernetes-request-path-and-cka"),
  },
  {
    slug: "cloud-identity-access-hierarchy",
    title: "클라우드 권한은 주체·행동·대상·범위를 함께 판정합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-identity-access-hierarchy"),
  },
  {
    slug: "cloud-networking-request-path",
    title: "DNS에서 사설 데이터까지 요청 경로를 한 칸씩 추적합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-networking-request-path"),
  },
  {
    slug: "cloud-compute-selection",
    title: "VM·컨테이너·PaaS·함수는 운영할 단위로 고릅니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-compute-selection"),
  },
  {
    slug: "cloud-storage-database-selection",
    title: "객체·블록·파일·데이터베이스는 접근 약속으로 고릅니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-storage-database-selection"),
  },
  {
    slug: "cloud-reliability-observability-iac",
    title: "복구 목표에서 관측·IaC·백업·비용을 거꾸로 설계합니다",
    subcategory: "cloud-foundations",
    sections,
    component: () => import("@/pages/articles/cloud/cloud-reliability-observability-iac"),
  },
  {
    slug: "aws-clf-c02-fast-study",
    title: "AWS CLF-C02 빠른 공부 지도: 역할과 시점으로 서비스를 가릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-clf-c02-fast-study"),
  },
  {
    slug: "aws-saa-c03-fast-study",
    title: "AWS SAA-C03 빠른 공부 지도: 제약표로 구조를 고릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-saa-c03-fast-study"),
  },
  {
    slug: "aws-developer-cloudops-paths",
    title: "AWS DVA-C02와 SOA-C03: 개발과 CloudOps 경로를 가릅니다",
    subcategory: "cloud-aws",
    sections,
    component: () => import("@/pages/articles/cloud/aws-developer-cloudops-paths"),
  },
  {
    slug: "azure-az900-fast-study",
    title: "Azure AZ-900 빠른 공부 지도: 자원 계층과 관리 도구를 잇습니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-az900-fast-study"),
  },
  {
    slug: "azure-az104-fast-study",
    title: "Azure AZ-104 빠른 공부 지도: 만들고 끊고 복구합니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-az104-fast-study"),
  },
  {
    slug: "azure-ai200-fast-study",
    title: "Azure AI-200 빠른 공부 지도: AI 백엔드 한 요청을 끝까지 잇습니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-ai200-fast-study"),
  },
  {
    slug: "azure-architect-devops-paths",
    title: "Azure AZ-305와 AZ-400: 설계와 DevOps 경로를 가릅니다",
    subcategory: "cloud-azure",
    sections,
    component: () => import("@/pages/articles/cloud/azure-architect-devops-paths"),
  },
];
