import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import ModernProviderDutyViz from "./viz/ModernProviderDutyViz";

const SEAL = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/storage/pipeline/states_sealing.go";
const WINDOW = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/storage/wdpost/wdpost_run.go";
const WINNING = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/storage/winning_prover.go";
const CURIO = "https://docs.curiostorage.org/design/sealing";

export default function ModernLotusMinerArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Sector 42의 계산을 어느 worker가 이어받아도 같은 결과로 만드는 법</p><h2 className="text-3xl font-bold tracking-tight">Provider scheduler는 sealing·WinningPoSt·WindowPoSt를 서로 다른 job contracts로 운영한다</h2></header><p className="text-lg leading-8 text-foreground/90">번들된 <code>lotus-miner</code> source는 sector state machine과 proof scheduling의 중요한 역사적·현행 release snapshot이지만, provider architecture는 Curio의 database-backed task model도 사용합니다. 구현이 달라도 공통 질문은 같습니다. 어느 sector·randomness·profile의 작업인지, 어느 upstream artifact를 소비했는지, proof 생성 뒤 어떤 chain receipt까지 완료했는지를 추적해야 합니다.</p><ModernProviderDutyViz /><ContentBoundary article="lotus-miner" /></section>

    <section id="sealing-jobs" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Sector jobs and chain milestones</p><h2 className="mt-2 text-2xl font-bold">PC1→PC2→commit의 compute artifacts와 active sector state를 분리한다</h2></header><p>Sector 42에 pieces를 배치하면 PC1이 replica-specific labels를 만들고 PC2가 encoded replica와 CommD·CommR tree artifacts를 완성합니다. PreCommit message inclusion 뒤 challenge seed를 기다려 commit proof를 생성·검증하고, ProveCommit이 canonical actor state에 반영돼야 sector가 proving set으로 이동합니다. <a className="text-primary hover:underline" href="/blockchain/proofs-porep">PoRep 정본</a>이 cryptographic phase 의미를 소유하며 이 글은 scheduler와 chain milestone bridge만 맡습니다.</p><ExplainedFormula question="Retry가 이전 sector artifact를 잘못 소비하지 않게 job을 어떻게 식별할까?" idea={<>Revision, miner·sector, task kind, upstream digest와 proof profile을 canonical bytes로 hash합니다.</>} formula={String.raw`J=H(v\parallel m\parallel s\parallel k\parallel u\parallel p)`}
    annotatedFormula={String.raw`J=\underbrace{H(v\parallel m\parallel s\parallel k\parallel u\parallel p)}_{\text{Job generation 계산}}`}
    operations={[
      { expression: String.raw`H(v\parallel m\parallel s\parallel k\parallel u\parallel p)`, annotation: ["Job generation이(가) 식의 결과에 기여하는 방식을","계산합니다.","Revision, miner·sector, task kind,","upstream digest와 proof profile을"] },
    ]} terms={[{symbol:"J",name:"Job generation",description:"Worker lease와 output receipt가 참조할 immutable job identity입니다."},{symbol:"v",name:"Revision",description:"Scheduler/source와 artifact schema version입니다."},{symbol:"m,s",name:"Miner and sector",description:"예제 miner f01000과 sector 42의 identity입니다."},{symbol:"k",name:"Task kind",description:"PC1, PC2, commit, Window 또는 Winning처럼 분리된 작업 종류입니다."},{symbol:"u",name:"Upstream digest",description:"같은 sector generation의 승인된 선행 artifact입니다."},{symbol:"p",name:"Proof profile",description:"Registered proof type·parameters·network context입니다."}]} assumptions={["각 field는 type·length·domain이 고정된 canonical encoding입니다.","Lease token은 generation과 함께 fencing되며 hash는 output correctness·fsync를 대신하지 않습니다."]} interpretation="같은 크기의 sector라도 u나 s가 다르면 J가 달라야 합니다. 서로 다른 PC1/PC2 generation을 섞으면 chain submission 전에 거절합니다." /><div id="paper-lotus-sealing"><CitationBlock type="code" citeKey={1} source="Lotus sealing pipeline · v1.36.0 commit 154c0c3" href={SEAL}><p><strong>문제:</strong> Sealing artifacts와 precommit/provecommit messages를 recoverable transitions로 연결해야 합니다.</p><p><strong>핵심 기여:</strong> PC1/PC2, precommit wait, seed/commit와 retry handlers의 pinned legacy Lotus 구현을 제공합니다.</p><p><strong>중요 가정:</strong> v1.36.0 actors/proof APIs, network policy와 storage backend를 고정합니다.</p><p><strong>근거 범위:</strong> Pinned legacy lotus-miner sealing state-machine source입니다.</p><p><strong>일반화 금지:</strong> Curio schema, NI-PoRep 전체, fixed sealing time이나 activation 성공을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="proof-duties" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Winning and Window duties</p><h2 className="mt-2 text-2xl font-bold">같은 PoSt primitives를 써도 목적·randomness·sector snapshot·destination이 다르다</h2></header><div className="grid gap-3 md:grid-cols-2"><article className="rounded-lg border border-border p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">WinningPoSt</p><h3 className="mt-2 font-semibold">한 epoch의 block eligibility</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Base tipset·epoch election randomness, miner와 challenged sectors를 고정합니다. Proof는 valid block candidate의 한 입력이며 message deadline 전체를 유지하는 증명이 아닙니다.</p></article><article className="rounded-lg border border-border p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">WindowPoSt</p><h3 className="mt-2 font-semibold">Deadline sector set의 지속 보관</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Deadline·partition snapshot, challenge randomness, ordered sectors/CommR와 skips/faults를 고정합니다. Proof message inclusion까지 추적합니다.</p></article></div><p>Wrong type, epoch/deadline, randomness 또는 sector order를 하나씩 바꿨을 때 independent verifier가 모두 거절해야 합니다. Winning proof generation 성공을 block assembly·propagation·selection으로, Window proof generation 성공을 submission·canonical inclusion·confidence로 확대하지 않습니다.</p><div id="paper-lotus-winningpost"><CitationBlock type="code" citeKey={2} source="Lotus WinningPoSt prover · v1.36.0 commit 154c0c3" href={WINNING}><p><strong>문제:</strong> Election randomness에서 challenged sectors와 Winning proof를 계산해야 합니다.</p><p><strong>핵심 기여:</strong> Winning sector challenge와 GenerateWinningPoSt 호출 adapter를 제공합니다.</p><p><strong>중요 가정:</strong> Winning profile, miner, eligible sectors, chain base/randomness와 proof backend를 고정합니다.</p><p><strong>근거 범위:</strong> Pinned WinningPoSt prover adapter behavior입니다.</p><p><strong>일반화 금지:</strong> Election 승리, block assembly·inclusion, Window maintenance나 fixed latency를 보장하지 않습니다.</p></CitationBlock></div><div id="paper-lotus-windowpost"><CitationBlock type="code" citeKey={3} source="Lotus WindowPoSt runner · v1.36.0 commit 154c0c3" href={WINDOW}><p><strong>문제:</strong> Deadline snapshot·randomness·partitions·proof를 chain submission에 연결해야 합니다.</p><p><strong>핵심 기여:</strong> Sector checks, Window proof generation/verification, batching과 message preparation/submission을 구현합니다.</p><p><strong>중요 가정:</strong> Network version, deadline state, proof type, miner, wallet/mpool과 storage availability를 고정합니다.</p><p><strong>근거 범위:</strong> Pinned WindowPoSt runner implementation입니다.</p><p><strong>일반화 금지:</strong> WinningPoSt, all reorg recovery, fixed deadline success나 future architecture를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="scheduler" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Scheduler and deadline</p><h2 className="mt-2 text-2xl font-bold">평균 task time 대신 verified chain completion까지 남은 slack을 계산한다</h2></header><p>Worker A의 lease가 만료돼 worker B가 같은 job을 가져갈 수 있지만, old lease 결과는 fencing token으로 거절해야 합니다. Output은 content digest와 completion marker를 가져야 하고 chain message는 job generation을 idempotency key로 사용합니다. Retry 전에는 actor/mpool을 조회해 이미 포함되거나 replacement 중인 effect를 확인합니다.</p><ExplainedFormula question="Deadline 전에 실제로 남은 운영 여유는 얼마일까?" idea={<>Close time에서 queue·storage read·proof·submit·confidence와 운영 reserve를 모두 뺍니다.</>} formula={String.raw`S=t_{close}-t_{now}-T_q-T_r-T_p-T_s-T_c-R`}
    annotatedFormula={String.raw`S=\underbrace{t_{close}-t_{now}-T_q-T_r-T_p-T_s-T_c-R}_{\text{Remaining window 계산}}`}
    operations={[
      { expression: String.raw`t_{close}-t_{now}-T_q-T_r-T_p-T_s-T_c-R`, annotation: ["Remaining window이(가) 식의 결과에 기여하는","방식을 계산합니다.","Close time에서 queue·storage","read·proof·submit·confidence와 운영"] },
    ]} terms={[{symbol:"S",name:"Deadline slack",description:"모든 필수 stage와 reserve 뒤 남는 시간입니다."},{symbol:"t_{close}-t_{now}",name:"Remaining window",description:"Pinned chain clock에서 deadline close까지의 시간입니다."},{symbol:"T_q,T_r",name:"Queue and read",description:"Task admission/lease와 challenged sector storage read 시간입니다."},{symbol:"T_p,T_s",name:"Prove and submit",description:"Proof generation/verification과 message preparation·send 시간입니다."},{symbol:"T_c",name:"Confidence",description:"Inclusion과 운영 policy의 confirmation 대기입니다."},{symbol:"R",name:"Operations reserve",description:"Retry·reorg·worker/storage fault를 위한 명시적 여유입니다."}]} assumptions={["실제 deadline/profile과 stage overlap을 pinned network·scheduler에서 wall time으로 측정합니다.","예제 숫자는 산술 설명이며 Filecoin protocol 상수가 아닙니다."]} interpretation="120분에서 10+15+25+5+10+20=85분을 빼면 S=35분입니다. S≤0이면 평균 proof가 빨라도 release할 수 없습니다." /><div id="paper-curio-sealing"><CitationBlock type="code" citeKey={4} source="Curio sealing design · official docs" href={CURIO}><p><strong>문제:</strong> 여러 provider nodes가 sealing stages를 durable task system으로 분산해야 합니다.</p><p><strong>핵심 기여:</strong> HarmonyTasks와 database-backed sealing pipeline design을 설명합니다.</p><p><strong>중요 가정:</strong> 2026-08-14 docs와 exact Curio commit/schema·deployment topology를 함께 고정합니다.</p><p><strong>근거 범위:</strong> Curio sealing task orchestration design입니다.</p><p><strong>일반화 금지:</strong> Legacy lotus-miner state 호환, HA 보장 또는 fixed throughput을 뜻하지 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release and rollback</p><h2 className="mt-2 text-2xl font-bold">Artifact parity·lease races·wrong proof·reorg를 넣어 본 뒤 scheduler를 채택한다</h2></header><p>Canary는 source/config/database schema, registered proof·parameters, miner/sector inventory와 chain head를 고정합니다. 서로 다른 sectors의 PC1/PC2를 섞고, worker loss 직후 stale lease output을 늦게 도착시키며, Winning/Window type·randomness·snapshot을 바꾸고, proof submission 직후 reorg를 일으킵니다. 각 실패는 typed reason으로 external effect 전에 거절되거나 같은 generation으로 안전하게 retry돼야 합니다.</p><p>같은 sector/profile에서 independent proof verification, CommD/CommR·actor state parity, queue/read/prove/submit/confidence stage time, p50/p99와 slack을 기록합니다. Scheduler candidate가 duplicate chain message, stale artifact acceptance, deadline reserve 부족 또는 restart parity 실패를 보이면 이전 compatible binary·database schema와 task routing으로 rollback합니다.</p><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> Sector job fields·identity 식, sealing→activation milestones, Winning/Window 비교, 35분 slack 계산, proof/chain 완료 차이, mixed artifact·lease race·wrong proof fixtures와 canary rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>;
}
