import { Link } from "react-router-dom";
import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import AlgorithmBlock from "@/components/ui/algorithm-block";
import { CitationBlock } from "@/components/ui/citation";
import { ContextWindowViz } from "../context-engineering/viz/ModernContextEngineeringViz";
import LostInMiddleViz from "./viz/LostInMiddleViz";

export default function ContextWindowOptimizationArticle() {
  return <div className="space-y-16">
    <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">긴 context의 capacity·utilization·prefill reuse는 다른 문제입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">
            Window에 token이 들어간다고 model이 그 evidence를 안정적으로 사용하는 것은 아닙니다. 같은 prefix 계산을 cache했다고 내용이 최신이 되는 것도
            아닙니다. 먼저 output reserve를 포함한 token 장부를 맞추고 position·distractor 평가로 utilization을 측정하고 마지막으로 stable
            prefix 계산을 재사용합니다.
          </p><p>이 세 판단은 모두 <strong>context engineering</strong>이라는 상위 설계 층 아래에 있습니다. Context engineering은 문장을 다듬는 <Link to="/ai/prompt-engineering">prompt engineering</Link>과 달리, retrieval 결과·tool 결과·대화 기록·system instruction 가운데 무엇을 이번 요청의 예산 안에 넣을지 고르는 layer입니다.</p><p>그 선택 자체(select→inject→compact→isolate)는 <Link to="/ai/context-engineering#curation">Context engineering의 curation lifecycle</Link>이 정본이고, 후보를 무엇으로 채울지는 <Link to="/ai/rag-pipeline">RAG pipeline</Link>이 다룹니다. 이 글은 선택된 항목이 예산·활용률·계산 재사용을 실제로 통과하는지만 봅니다.</p></div><TermBreakdown title="세 문제를 따로 측정" items={[{term:"Capacity",description:"Request가 허용하는 input+output token 상한과 source별 사용량입니다."},{term:"Utilization",description:"Context에 있는 relevant evidence를 model이 실제 answer와 citation에 사용하는 정도입니다.",boundary:"명목 max context length와 동일하지 않습니다."},{term:"Stable prefix",description:"여러 request에서 byte/token identity가 같은 앞부분입니다.",example:"Versioned system instruction과 tool schema"},{term:"Prompt cache",description:"동일 prefix의 prefill 계산을 provider 조건에 따라 재사용합니다.",boundary:"Cache hit는 freshness·correctness·authorization 증명이 아닙니다."}]}/><ContextWindowViz/><ContentBoundary article="context-window-optimization"/></section>
    <section id="budget" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Output reserve를 먼저 떼고 token을 실제 serialization으로 셉니다</h2><ExplainedFormula question="128k limit에서 context가 답변 공간을 잠식하지 않게 어떻게 계산하나요?" idea={<p>
            System·task·retrieval·history·tool result의 실제 serialized token을 더하고 생성할 answer와 후속 tool call
            reserve를 별도 항으로 포함합니다. 합이 한도를 넘으면 low-value source를 제외하거나 원문을 artifact로 이동합니다.
          </p>} formula={String.raw`B_{used}=B_{sys}+B_{task}+B_{ret}+B_{hist}+B_{tool}+B_{out}\le B_{max}`} annotatedFormula={String.raw`\begin{aligned}B_{control}&=\underbrace{B_{sys}+B_{task}}_{\substack{\text{행동 규칙과}\\\text{현재 질문}}}\\B_{evidence}&=\underbrace{B_{ret}+B_{hist}+B_{tool}}_{\substack{\text{근거·대화·}\\\text{tool observation}}}\\B_{input}&=\underbrace{B_{control}+B_{evidence}}_{\text{전체 input token}}\\B_{used}&=\underbrace{B_{input}+B_{out}}_{\substack{\text{생성 전에}\\\text{output reserve 포함}}}\\H&=\underbrace{B_{max}-B_{used}}_{\text{남은 headroom}}\ge0\end{aligned}`} operations={[{expression:String.raw`B_{sys}+B_{task}`,annotation:["고정 instruction과 현재 task를 더해","반드시 유지할 control input 계산"]},{expression:String.raw`B_{ret}+B_{hist}+B_{tool}`,annotation:["retrieval·history·tool result를 더해","선택 가능한 evidence 비용 계산"]},{expression:String.raw`B_{input}+B_{out}`,annotation:["입력 사용량에 생성 reserve를 더해","request 전체 예산 계산"]},{expression:String.raw`B_{max}-B_{used}`,annotation:["허용량에서 전체 사용량을 빼","남은 headroom 확인"]}]} terms={[{symbol:String.raw`B_{sys}`,name:"Instruction tokens",description:"System/developer instruction과 stable tool definition입니다."},{symbol:String.raw`B_{task}`,name:"Task tokens",description:"현재 user request와 acceptance condition입니다."},{symbol:String.raw`B_{ret}`,name:"Retrieved tokens",description:"선택한 evidence와 provenance metadata입니다."},{symbol:String.raw`B_{hist}`,name:"History tokens",description:"Recent messages와 compacted working state입니다."},{symbol:String.raw`B_{tool}`,name:"Tool-result tokens",description:"현재 판단에 필요한 typed observation입니다."},{symbol:String.raw`B_{out}`,name:"Output reserve",description:"Answer·tool call·후속 generation을 위해 남긴 공간입니다."},{symbol:"H",name:"Headroom",description:"모든 serialization 뒤 남은 token 여유입니다."}]} assumptions={["Provider의 실제 tokenizer와 chat/tool wrapper로 셉니다.","Input·output의 별도 hard limit와 billing rule을 함께 확인합니다.","H≥0은 capacity 통과일 뿐 answer quality 통과가 아닙니다."]} interpretation="128k에서 sys 8k, task 4k, retrieval 40k, history 30k, tool 20k, output 16k이면 118k를 쓰고 headroom은 10k입니다."/></section>
    <section id="relevance" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Context가 길어져도 정확도가 오르지 않는 이유는 relevance 하락 때문입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">긴 context가 항상 더 정확한 답을 만들지는 않습니다. 늘어난 token 가운데 정답 생성에 실제로 쓰이는 fragment의 비율이 오히려 낮아지기 때문입니다. 이 비율을 <strong>context relevance</strong>라고 부릅니다.</p><p>관련 없는 문서나 발화가 함께 들어가면 그 자체가 model의 attention을 나눠 가져 정답 fragment의 사용을 방해합니다. 이런 무관한 조각을 <strong>context noise</strong>라고 하며, 존재만으로 노이즈가 되지 정답을 지우지는 않습니다.</p><p>Noise를 더하지 않아도 문제가 생깁니다. 같은 relevant fragment 하나를 유지한 채 무관한 fragment를 9개에서 19개로 늘리면 relevant 비율은 10%에서 5%로 떨어집니다. 이 비율 하락 자체를 <strong>context dilution</strong>이라고 부르며, 나머지가 유해한 내용이 아니어도 일어납니다.</p></div><TermBreakdown title="Relevance·noise·dilution을 구분" items={[{term:"Context relevance",description:"Context에 들어간 fragment가 현재 질문의 정답을 만드는 데 실제로 쓰이는 정도입니다.",boundary:"Retrieval score가 높다고 relevance가 보장되지 않으며, 실제 answer·citation 사용 여부로 다시 재야 합니다."},{term:"Context noise",description:"정답과 무관하지만 context에 함께 들어간 fragment입니다.",example:"20개 문서 중 19개가 무관한 topic이면 그 19개가 noise입니다.",boundary:"Noise가 있어도 정답 fragment 자체가 사라지지는 않으며, 정답을 사용할 확률이 낮아질 뿐입니다."},{term:"Context dilution",description:"전체 길이가 늘어나며 relevant token 대비 총 token 비율이 낮아지는 현상입니다.",example:"Relevant fragment 1개 + distractor 9개면 비율 10%, distractor 19개면 5%입니다.",boundary:"Dilution은 noise 없이도, 즉 나머지가 무해한 filler여도 일어날 수 있습니다."}]}/></section>
    <section id="position" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">같은 evidence를 앞·가운데·끝에 옮겨 utilization을 측정합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Relevant fragment와 질문, distractor 종류와 개수, model과 prompt를 고정하고 evidence 위치만 바꿉니다. 예를 들어 exact answer뿐 아니라 citation support와 multi-hop slice를 함께 측정해야 단순 retrieval과 reasoning failure를 구분할 수 있습니다.</p><p>실제 수치로 보면 차이가 큽니다. Liu et al.(2023)의 20-document multi-document QA에서 GPT-3.5-Turbo는 정답 fragment가 1번째 문서일 때 정확도 75.8%, 10번째(가운데)일 때 53.8%, 20번째(마지막)일 때 63.2%를 기록했습니다. 앞·끝보다 가운데에서 최대 22.0%p 낮은 이 U자형 패턴을 <strong>lost-in-the-middle effect</strong>라고 부릅니다.</p></div><LostInMiddleViz/><div id="paper-lost-in-middle" className="not-prose mt-8 scroll-mt-24"><CitationBlock type="paper" citeKey={1} source="Lost in the Middle: How Language Models Use Long Contexts" href="https://arxiv.org/abs/2307.03172">Multi-document QA와 key-value retrieval에서 relevant evidence 위치를 바꿔 long-context utilization을 측정합니다. 논문의 model·task에서 관찰한 위치 민감도를 모든 최신 model·업무의 고정 U자 곡선으로 일반화하지 않습니다.</CitationBlock></div></section>
    <section id="cache" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Stable prefix cache는 계산을 재사용하고 version마다 identity를 바꿉니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>공통 instruction과 tool schema를 앞에 두고 user-specific content를 뒤에 두면 provider 조건이 맞을 때 prefill을 재사용할 수 있습니다. 그러나 policy-v7로 바뀌었는데 v6 prefix를 유지하면 hit rate는 높아져도 correctness가 무너집니다. Prefix key에 policy·tool schema·model·tokenizer revision을 포함하고 변경 시 invalidate합니다.</p><p>Session compaction의 구체적인 state 보존은 <Link to="/ai/agent-memory-lifecycle">Agent memory lifecycle</Link>과 <Link to="/ai/claw-compaction">Claw compaction 구현</Link>에서 이어집니다.</p></div></section>
    <section id="compression" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Budget이 부족하면 evidence는 요약하고 prompt는 token 단위로 지웁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">Budget이 부족할 때 흔한 답은 원문을 그대로 잘라내는 것이지만, <strong>context compression</strong>은 검색 결과나 대화 기록을 요약·추출로 줄여 정보 손실을 통제하는 별도 기법입니다.</p><p><strong>Prompt compression</strong>은 그 중 token 단위 기법입니다. LLMLingua는 작은 language model의 신호로 정보량이 낮은 token을 지워, 성능 손실을 거의 남기지 않으면서 최대 20배까지 압축했다고 보고했습니다.</p><p>
            후속 LongLLMLingua는 질문과 무관한 부분을 더 강하게 지우고 남은 조각의 순서를 재배치해 lost-in-the-middle 위치 편향까지 함께 줄입니다.
            NaturalQuestions에서 token을 4배 줄이면서 GPT-3.5-Turbo 성능을 최대 21.4% 끌어올렸고 LooGLE에서는 비용을 94.0% 줄였습니다. 두 수치
            모두 저자 자기보고입니다.
          </p></div><TermBreakdown title="압축 두 계층과 caching과의 차이" items={[{term:"Context compression",description:"검색 결과·대화 기록처럼 부피가 큰 원문을 요약·추출로 줄여 token budget 안에 맞추는 일반 기법입니다.",boundary:"압축은 정보 손실 위험을 동반하므로 압축 뒤에도 필요한 답이 남는지 별도로 검증해야 합니다."},{term:"Prompt compression",description:"작은 model의 perplexity·중요도 신호로 원문 안의 저정보 token을 지워 의미를 최대한 보존하며 길이를 줄이는 token 단위 방법입니다.",example:"LLMLingua는 budget controller와 반복적 token 삭제로 최대 20배 압축을 보고했습니다."},{term:"압축과 caching의 차이",description:"압축은 내용을 바꿔 다시 계산해야 하지만, prefix cache는 내용을 바꾸지 않고 계산만 재사용합니다.",boundary:"압축한 prefix는 매 요청마다 내용이 달라 stable-prefix cache 대상이 아닙니다."}]}/><AlgorithmBlock title="Context compression pipeline" input={["원본 context item 목록(source, token 수, priority)","목표 token budget B","필수 evidence checklist"]} steps={[{code:"for item in items: rank[item] = utility(item, task)",note:"Task 관련성과 priority로 항목별 utility를 매깁니다."},{code:"if total_tokens(items) <= B: return items",note:"이미 budget 안이면 압축 없이 통과합니다."},{code:"for item in low_utility_items: item = extract_or_summarize(item)",note:"긴 evidence·history부터 추출·요약으로 줄입니다 — context compression."},{code:"prompt_text = compress_tokens(prompt_text, target_ratio)",note:"남은 지시문·질문 자체는 token 단위로 압축합니다 — prompt compression."},{code:"assert checklist ⊆ surviving_spans else restore_or_reject()",note:"필수 evidence가 빠졌으면 복원하거나 request를 거부합니다."}]} output="Budget 이하로 줄었고 checklist가 보존된 context"/><div className="prose prose-neutral max-w-none dark:prose-invert"><p>대화 기록을 줄인 뒤 무엇을 반드시 남겨야 하는지는 <Link to="/ai/agent-memory-lifecycle#compaction">Agent memory lifecycle의 compaction fidelity</Link>가 정본입니다. 이 절은 압축이라는 선택지 자체와 token compression 기법만 다룹니다.</p></div><div id="paper-llmlingua" className="not-prose mt-8 scroll-mt-24"><CitationBlock type="paper" citeKey={2} source="LLMLingua: Compressing Prompts for Accelerated Inference of Large Language Models" href="https://arxiv.org/abs/2310.05736">작은 language model의 perplexity 신호로 저정보 token을 반복적으로 제거하는 budget controller와 token-level 압축 알고리즘을 제안합니다. GSM8K·BBH 등 저자 데이터셋에서 최대 20배 압축을 보고했으며, 다른 model·domain에서 같은 배수를 보장하지 않습니다.</CitationBlock></div><div id="paper-longllmlingua" className="not-prose mt-8 scroll-mt-24"><CitationBlock type="paper" citeKey={3} source="LongLLMLingua: Accelerating and Enhancing LLMs in Long Context Scenarios via Prompt Compression" href="https://arxiv.org/abs/2310.06839">질문 인지 압축과 조각 재배치로 긴 context의 비용·성능·위치 편향을 함께 다룹니다. NaturalQuestions에서 token 4배 감소로 GPT-3.5-Turbo 성능을 최대 21.4% 끌어올렸다는 수치는 저자 자기보고이며, 모든 model·workload에 같은 폭으로 재현된다는 뜻은 아닙니다.</CitationBlock></div></section>
  </div>;
}
