import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { BellpersonSnarkViz } from "./BellpersonSnarkViz";

const PROVER = "https://github.com/filecoin-project/bellperson/blob/728306c8ee52f53dbd55ea02557affcdfb546ae7/src/groth16/prover/mod.rs";
const SUPRASEAL = "https://github.com/filecoin-project/bellperson/blob/728306c8ee52f53dbd55ea02557affcdfb546ae7/src/groth16/prover/supraseal.rs";
const GPU = "https://github.com/filecoin-project/bellperson/blob/728306c8ee52f53dbd55ea02557affcdfb546ae7/src/gpu/mod.rs";

export default function ModernProofsSnark() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">같은 크기 회로 8개를 Groth16 proof batch로 만들기</p><h2 className="text-3xl font-bold tracking-tight">Bellperson 구현에서 먼저 볼 것은 SNARK 공식이 아니라 assignment가 어느 prover path로 넘어가는가이다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">고정 workload는 같은 회로 8개에 서로 다른 witness를 넣어 proof 8개를 만드는 작업입니다. <a className="text-primary hover:underline" href="/crypto/groth16">Groth16 정본</a>은 QAP와 pairing 검증을 설명하고, <a className="text-primary hover:underline" href="/gpu/filecoin-gpu-proofs">GPU proof pipeline</a>은 FFT·MSM 가속의 공통 경계를 설명합니다. 이 글은 pinned bellperson 코드에서 assignment artifact, feature-selected dispatch, SupraSeal FFI receipt가 어떻게 이어지는지만 소유합니다.</p>
      <BellpersonSnarkViz /><ContentBoundary article="proofs-snark" />
    </section>

    <section id="assignment-artifact" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · Assignment artifact</p><h2 className="mt-2 text-2xl font-bold">Circuit synthesis 결과를 A·B·C evaluations, inputs, auxiliary variables와 density maps로 고정한다</h2></header>
      <p>ProvingAssignment는 witness 숫자만 담는 배열이 아닙니다. Public input과 auxiliary assignment, A/B/C query가 실제로 참조하는 auxiliary 위치의 density까지 함께 기록합니다. 회로·field·parameter digest, public-input order와 expected vector lengths를 artifact header에 넣어야 잘못된 proving key나 다른 회로의 assignment가 조용히 섞이지 않습니다.</p>
      <ExplainedFormula question="Density map은 왜 별도 artifact인가?" idea={<>0이 아닌 query 항만 MSM에 보내면 결과는 유지하면서 불필요한 scalar-point 곱을 피할 수 있기 때문입니다.</>} formula={String.raw`M_A=\sum_{i=0}^{N_{aux}-1}\mathbf{1}[D_A(i)=1],\quad \rho_A=M_A/N_{aux}`} terms={[{symbol:"D_A(i)",name:"A-query density bit",description:"Auxiliary variable i가 A query MSM에 포함되는지 나타냅니다."},{symbol:"N_{aux}",name:"Auxiliary count",description:"회로가 만든 private auxiliary assignments 수입니다."},{symbol:"M_A",name:"Active A terms",description:"A-query MSM이 실제 처리할 항 수입니다."},{symbol:String.raw`\rho_A`,name:"A density",description:"0과 1 사이의 활성 비율입니다."},{symbol:String.raw`\mathbf{1}[\cdot]`,name:"Indicator",description:"조건이 참이면 1, 아니면 0입니다."}]} assumptions={["Density bit와 query vector index가 같은 circuit synthesis 순서를 사용합니다.","Density는 correctness를 바꾸지 않으며, 빠진 nonzero term은 proof를 깨뜨립니다."]} interpretation="보조 변수 100개 중 A query가 24개만 쓰이면 MA=24, ρA=0.24입니다. 이 값은 성능 입력이지 Groth16 security parameter가 아닙니다." />
      <div id="paper-bellperson-assignment"><CitationBlock type="code" citeKey={1} source="bellperson Groth16 prover · commit 728306c" href={PROVER}><p><strong>문제:</strong> Constraint synthesis 결과를 Groth16 prover의 FFT·MSM 입력으로 변환해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 ProvingAssignment의 A/B/C evaluations, input/aux assignments와 density trackers, native/SupraSeal compile-time path를 보여 줍니다.</p><p><strong>중요 가정:</strong> commit 728306c와 동일한 feature set, scalar engine, parameters를 사용합니다.</p><p><strong>근거 범위:</strong> bellperson의 prover data layout과 dispatch 경계입니다.</p><p><strong>일반화 금지:</strong> 임의 SNARK의 assignment 형식이나 GPU speedup을 보장하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="prover-dispatch" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · Prover dispatch</p><h2 className="mt-2 text-2xl font-bold">Native와 cuda-supraseal은 런타임 자동 fallback이 아니라 빌드 feature로 갈리는 prover 구현이다</h2></header>
      <p>Pinned 코드에서는 <code>cuda-supraseal</code> feature가 켜지면 SupraSeal module을, 아니면 native module을 선택합니다. Native path 안에서도 CUDA/OpenCL feature가 있으면 CpuGpuMultiexpKernel을 사용할 수 있습니다. 따라서 receipt에는 binary revision과 feature manifest를 남겨야 합니다. SupraSeal 실패 뒤 native로 재시도하려면 운영자가 명시한 별도 binary/job이어야 하며, 한 receipt 안에서 path를 숨겨 바꾸면 재현할 수 없습니다.</p>
      <ExplainedFormula question="한 job의 prover path를 어떻게 결정적으로 기록할까?" idea={<>빌드 feature와 admitted batch preconditions를 path identity에 포함합니다.</>} formula={String.raw`P=\begin{cases}SS,& f_{ss}=1\land E=1\land S=1\\Native,& f_{ss}=0\end{cases}`} terms={[{symbol:"P",name:"Prover path",description:"이번 receipt가 사용한 SupraSeal 또는 native implementation입니다."},{symbol:"f_{ss}",name:"SupraSeal feature",description:"Binary가 cuda-supraseal로 컴파일됐는지 나타냅니다."},{symbol:"E",name:"Equal-size admission",description:"Batch circuits가 요구된 동일 크기 조건을 만족하면 1입니다."},{symbol:"S",name:"SRS admission",description:"Pinned SRS가 성공적으로 로드되고 확인되면 1입니다."},{symbol:"SS",name:"SupraSeal path",description:"FFI batch prover 경로입니다."},{symbol:"Native",name:"Native path",description:"Bellperson의 기본 prover 경로입니다."}]} assumptions={["fss=1인데 E 또는 S가 0이면 식의 결과가 없으므로 fail-closed합니다.","Feature-selected 구현을 런타임 heuristic으로 바꾸지 않습니다."]} interpretation="크기가 다른 회로가 하나라도 섞이면 SupraSeal batch를 거절합니다. 같은 프로세스에서 몰래 native로 바꾸는 것은 이 식이 허용하는 동작이 아닙니다." />
      <div id="paper-bellperson-gpu-dispatch"><CitationBlock type="code" citeKey={2} source="bellperson GPU module · commit 728306c" href={GPU}><p><strong>문제:</strong> 같은 prover interface에서 CPU-only와 CUDA/OpenCL MSM 구현을 선택해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned module은 cfg feature에 따른 CpuGpuMultiexpKernel 또는 no-GPU surface를 정의합니다.</p><p><strong>중요 가정:</strong> 빌드 artifact와 runtime device/runtime libraries가 일치합니다.</p><p><strong>근거 범위:</strong> bellperson 내부의 accelerator selection입니다.</p><p><strong>일반화 금지:</strong> 특정 GPU의 availability, 성능, 자동 fallback 성공을 뜻하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="supraseal-boundary" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · SupraSeal boundary</p><h2 className="mt-2 text-2xl font-bold">Rust assignments를 batch FFI payload로 바꾸고 SRS·proof count·output order를 receipt로 되받는다</h2></header>
      <p>SupraSeal adapter는 assignments를 FFI 표현으로 변환하고 동일 크기를 확인한 뒤 pinned SRS handle과 함께 batch prover를 호출합니다. Rust 쪽 circuit index와 반환 proof index가 일치하는지, 모든 proof가 원래 public input을 검증하는지 확인해야 합니다. FFI 성공 code만으로 승인하면 안 됩니다.</p>
      <ExplainedFormula question="Batch latency에서 무엇을 분리해 기록해야 할까?" idea={<>병렬 synthesis, FFI 변환, GPU prover와 독립 검증을 한 숫자로 뭉개지 않습니다.</>} formula={String.raw`T_{e2e}=\max_i T_{synth,i}+T_{pack}+T_{ffi}+T_{prove}+T_{verify}`} terms={[{symbol:"T_{e2e}",name:"End-to-end latency",description:"Assignment 시작부터 모든 proof 검증까지의 wall time입니다."},{symbol:"T_{synth,i}",name:"Circuit synthesis",description:"i번째 circuit assignment 생성 시간입니다."},{symbol:"T_{pack}",name:"FFI packing",description:"Rust values를 backend payload로 바꾸는 시간입니다."},{symbol:"T_{ffi}",name:"FFI overhead",description:"Boundary call과 result materialization 시간입니다."},{symbol:"T_{prove}",name:"Batch proving",description:"SupraSeal이 batch proof를 만드는 시간입니다."},{symbol:"T_{verify}",name:"Independent verification",description:"각 proof/public input을 검증하는 시간입니다."}]} assumptions={["Synthesis가 실제로 병렬 실행될 때만 max로 모델링합니다.","동기화와 device transfer는 측정된 stage에 빠짐없이 포함합니다."]} interpretation="각 synthesis가 8ms, pack 3ms, FFI 1ms, prove 20ms, verify 4ms라면 e2e는 36ms입니다. stage 합을 숨긴 고정 speedup 주장은 하지 않습니다." />
      <div id="paper-bellperson-supraseal"><CitationBlock type="code" citeKey={3} source="bellperson SupraSeal adapter · commit 728306c" href={SUPRASEAL}><p><strong>문제:</strong> 여러 Groth16 assignments를 external batch prover와 안전하게 연결해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 equal-size check, assignment conversion, SRS acquisition과 batch proof call을 보여 줍니다.</p><p><strong>중요 가정:</strong> 같은 commit의 FFI ABI, parameter cache와 cuda-supraseal dependency를 고정합니다.</p><p><strong>근거 범위:</strong> Bellperson–SupraSeal integration boundary입니다.</p><p><strong>일반화 금지:</strong> 완전한 memory safety, constant-time, 모든 circuit size 지원이나 고정 speedup을 보장하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="release-gate" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">CPU/GPU/SupraSeal parity를 먼저 닫고 verified proofs/s와 peak memory를 함께 비교한다</h2></header>
      <p>Positive fixture와 unsatisfied witness, public input reorder, 잘못된 parameter/SRS, unequal batch, corrupted FFI length, proof reorder와 한 byte 변조를 테스트합니다. 모든 proof가 독립 verifier를 통과한 뒤 cold/warm, batch size, synthesis/transfer/kernel/verify와 peak host/device memory를 기록합니다. 새 binary나 driver에서 parity가 깨지면 pinned native artifact로 rollback합니다.</p>
      <ExplainedFormula question="Batch prover의 유효 처리량은 무엇인가?" idea={<>정확한 public input으로 검증된 proof만 전체 wall time으로 나눕니다.</>} formula={String.raw`Q_v=\frac{N_{ok}}{T_{e2e}},\quad r_f=1-\frac{N_{ok}}{N_{submitted}}`} terms={[{symbol:"Q_v",name:"Verified throughput",description:"초당 승인된 Groth16 proofs입니다."},{symbol:"N_{ok}",name:"Verified proofs",description:"Expected public inputs와 pinned VK로 검증된 proof 수입니다."},{symbol:"T_{e2e}",name:"End-to-end time",description:"Synthesis부터 verification까지 wall time입니다."},{symbol:"r_f",name:"Failure rate",description:"제출했지만 승인되지 않은 비율입니다."},{symbol:"N_{submitted}",name:"Submitted circuits",description:"Batch에 넣은 전체 circuit 수입니다."}]} assumptions={["동일 circuit/parameters/input distribution과 cold/warm 조건을 비교합니다.","한 건이라도 unexpected failure면 release gate는 실패합니다."]} interpretation="8개 중 7개만 검증돼도 Qv는 계산할 수 있지만 rf=0.125이므로 배포는 막아야 합니다." />
      <aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> assignment fields, density, 두 native/GPU 층의 구분, compile-time dispatch, equal-size/SRS admission, FFI order, latency ledger, negative fixtures, 측정과 rollback을 이 글만으로 답할 수 있습니다.</aside>
    </section>
  </article>;
}
