import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";

const Flow=()=> <figure data-viz="libiop-reduction-flow" className="not-prose rounded-xl border border-border bg-card p-4 sm:p-5"><figcaption className="mb-4 text-sm font-semibold">R1CS에서 non-interactive oracle proof까지</figcaption><div className="grid gap-3 sm:grid-cols-4">{[['01','R1CS relation'],['02','Encoded oracles'],['03','Public-coin IOP'],['04','BCS artifact']].map(([n,t])=><div key={n} className="min-w-0 rounded-lg border border-border bg-background p-4"><span className="text-xs font-semibold text-primary">{n}</span><p className="mt-2 break-words text-sm font-semibold">{t}</p></div>)}</div></figure>;

export default function ModernArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-5"><h2 className="text-3xl font-bold">libiop: witness 전체 대신 encoded oracle를 묻는다</h2><p className="text-lg leading-8">a=3,b=4,c=12인 R1CS row를 verifier가 witness 전체를 읽지 않고 확인하려면 prover가 redundancy가 있는 oracle를 먼저 제시하고 verifier가 random positions과 algebraic relations을 묻는 방식을 쓸 수 있습니다. libiop는 Aurora·Ligero·Fractal 계열의 IOP components와 BCS transformation을 탐구하는 research implementation입니다.</p><Flow/><p>각 protocol은 reduction, code rate, query count, polynomial commitment, setup·security assumptions이 다르므로 이름이 비슷한 API를 섞어 하나의 보안·성능 claim으로 만들면 안 됩니다.</p></section>
  <section id="r1cs-iop" className="space-y-5"><h2 className="text-2xl font-bold">R1CS를 encoded-oracle profile로 낮춘다</h2><p>Toy rate 1/2 code라고 하면 4개 witness symbols는 8개 encoded symbols로 늘어납니다. 이 숫자는 직관을 위한 예이며, 실제 domain·code·distance는 protocol profile이 정합니다. Redundancy로 오류가 넓게 퍼져야 random query가 false oracle를 찾을 확률적 근거가 생깁니다.</p><ExplainedFormula question="몇 번의 query가 오류를 놓칠 수 있는가?" idea={<>오류가 oracle의 δ 비율을 차지하고 q개 positions를 독립·균일하게 샘플한다는 단순화 아래에서 모두 정상 위치만 고를 확률을 계산합니다.</>} formula={String.raw`\Pr[\text{all queries miss corruption}]\le (1-\delta)^q`}
  annotatedFormula={String.raw`\Pr[\text{all queries miss corruption}]\le \underbrace{(1-\delta)^q}_{\text{Query count 계산}}`}
  operations={[
    { expression: String.raw`(1-\delta)^q`, annotation: ["Query count이(가) 식의 결과에 기여하는 방식을","계산합니다.","오류가 oracle의 δ 비율을 차지하고 q개","positions를 독립·균일하게 샘플한다는 단순화 아래에서"] },
  ]} terms={[{symbol:"δ",name:"Relative corruption",description:"Claimed oracle와 nearest valid codeword가 다른 위치의 비율입니다."},{symbol:"q",name:"Query count",description:"Verifier가 확인하는 sampled positions의 수입니다."},{symbol:"(1-δ)^q",name:"Toy miss bound",description:"독립 균일 샘플링에서 오류를 모두 피할 확률입니다."}]} assumptions={["Queries가 commitment 후에 균일·예측 불가능하게 정해집니다.","실제 protocol의 code distance·round dependencies·soundness error는 별도 분석을 따릅니다."]} interpretation="δ=1/4,q=4인 toy 경우 miss bound는 (3/4)^4≈0.316입니다. 이 값이 크다는 사실은 query·code·repetition parameter를 security target에 맞춰야 함을 보여 줍니다." /></section>
  <section id="bcs" className="space-y-5"><h2 className="text-2xl font-bold">BCS는 commit-first 순서를 artifact로 만든다</h2><p>Interactive IOP에서 verifier가 던지던 public coins을 non-interactive proof에서는 transcript hash로 도출합니다. Prover는 oracle Merkle root R0를 먼저 absorb하고 challenge α를 받으며, 다음 root R1을 넣은 후 query q를 정합니다. Query value와 authentication path가 root에 속함을 보여도 oracle 전체가 올바르다거나 hiding된다는 사실까지 자동으로 보여 주지는 않습니다.</p><p>반례는 query를 root 전에 정하는 경우입니다. Prover가 q를 먼저 알면 그 주변만 정상인 oracle를 골라 commit할 수 있으므로 statement, round root, challenge, query, opening의 canonical encoding·domain·order를 receipt에 남겨야 합니다.</p></section>
  <section id="release" className="space-y-5"><h2 className="text-2xl font-bold">Protocol profile을 고정하고 stage별로 측정한다</h2><p>Source SHA, protocol, field, code/domain/rate, query·repetition, hash/MMCS, PCS/setup, transcript schema와 target soundness error를 manifest에 넣습니다. Bad oracle symbol, Merkle path, degree, out-of-range query, reordered round의 한 변수만 바꾸는 fixture를 모두 fail closed한 뒤 같은 constraints·security·hardware에서 encode/prove/verify ms, proof bytes, RSS를 나뉩니다.</p><div id="paper-aurora"><CitationBlock source="Aurora: Transparent Succinct Arguments for R1CS" citeKey={1} href="https://eprint.iacr.org/2018/828.pdf"><p><b>문제:</b> Trusted setup 없는 R1CS succinct argument를 만듭니다.</p><p><b>기여:</b> IOP-based R1CS reduction과 transparent construction을 제시합니다.</p><p><b>전제:</b> 논문의 field·code·hash·random-oracle parameters입니다.</p><p><b>근거 범위:</b> Aurora protocol/reduction과 security analysis입니다.</p><p><b>말하지 않는 것:</b> libiop의 모든 profile·API·benchmark와 동일하지 않습니다.</p></CitationBlock></div><div id="paper-libiop-source"><CitationBlock source="scipr-lab/libiop pinned source a2ed2ec" citeKey={2} href="https://github.com/scipr-lab/libiop/tree/a2ed2ec2f3e85f29b6035951553b02cb737c817a"><p><b>문제:</b> IOP components와 BCS implementation seam을 고정합니다.</p><p><b>기여:</b> Official research code·tests snapshot입니다.</p><p><b>전제:</b> Commit a2ed2ec와 build·dependency·parameter profile을 pin합니다.</p><p><b>근거 범위:</b> 선택 commit의 implementation behavior입니다.</p><p><b>말하지 않는 것:</b> Moving main, production readiness, 고정 security level을 보장하지 않습니다.</p></CitationBlock></div></section>
</article>}
