import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { ProofComparisonViz, RollupPipelineViz } from "./viz/ModernRollupViz";
const spec="https://github.com/ethereum-optimism/specs/blob/f7cefd23a79e072ea90e033dae5d2e3685d0f10c/specs/";
export default function ModernRollupArticle(){return <article className="space-y-14 [&_section]:space-y-5 [&_h2]:text-2xl [&_h2]:font-bold [&_p]:leading-8">
<section id="overview" data-teach-level="S"><h2>1. 계산을 나누되 다른 사람도 결과를 확인하게 합니다</h2><p>모든 참여자가 모든 거래를 같은 곳에서 계산하면 처리량을 늘리기 어렵습니다. 별도 공간에서 먼저 거래를 처리하고 여러 결과를 묶어 주 장부에 연결하면 계산 부담을 나눌 수 있습니다. 하지만 빠른 처리자가 잘못된 잔액을 써도 그대로 받아들여서는 안 됩니다.</p><p>다른 참여자가 입력을 구하고 같은 계산을 재현할 수 있어야 합니다. 주 장부에는 어떤 결과를 받아들일지 판정하는 규칙도 필요합니다. Rollup은 이 연결을 만드는 구조입니다. 먼저 두 송금의 결과를 별도 공간에서 계산한 뒤 어떻게 확인하고 받아들이는지 보겠습니다.</p></section>
<section id="black-box" data-teach-level="B"><h2>2. 요청 수신·입력 공개·재계산·결과 채택으로 나눕니다</h2><ol className="list-decimal space-y-3 pl-6"><li>요청 수신 → 서명한 송금을 받아 순서를 정합니다.</li><li>입력 공개 → 다른 사람이 읽을 수 있도록 묶은 거래 데이터를 게시합니다.</li><li>재계산 → 게시된 입력과 앞선 상태로 같은 잔액을 계산합니다.</li><li>결과 채택 → 잘못된 결과를 거절하는 규칙에 따라 외부에서 쓸 결과를 정합니다.</li></ol><p>빠른 응답은 첫 단계에서 나올 수 있습니다. 다른 사람이 결과를 확인할 수 있는 시점과 돈을 외부로 옮길 수 있는 시점은 다를 수 있습니다. 같은 두 송금으로 이 차이를 추적합니다.</p></section>
<section id="case" data-teach-level="0"><h2>3. 100에서 10을 보내고 5를 돌려받으면 95입니다</h2><p>처음 A는 100, B는 0을 갖습니다. 거래 T1은 A가 B에게 10을 보내고 T2는 B가 A에게 5를 돌려주는 송금입니다(가정). 이 순서로 실행하면 A는 100→90→95, B는 0→10→5가 됩니다. 수수료를 생략한 설명용 장부이며 실제 체인 거래를 제출한 결과는 아닙니다.</p><p>처리자가 A=96이라고 발표하면 두 거래를 가진 검증자는 95를 재현해 오류를 발견합니다. 그런데 T2를 구할 수 없다면 마지막 잔액을 확인할 수 없습니다. ‘입력을 구할 수 있음’과 ‘그 입력으로 계산이 맞음’은 서로 다른 조건입니다.</p><p>순서도 입력입니다. B가 0인 상태에서 T2를 먼저 실행하면 보낼 5가 부족합니다. 앞선 상태와 거래 순서, 적용 규칙을 함께 고정해야 같은 결과가 나옵니다.</p></section>
<section id="parts" data-teach-level="1"><h2>4. 빠르게 답하는 사람과 검증할 자료를 남기는 사람을 나눕니다</h2><p>요청을 먼저 받은 처리자는 T1과 T2의 순서를 정하고 결과를 계산합니다. 게시 담당자는 거래 묶음을 다른 참여자가 얻을 수 있는 장소에 올립니다. 검증자는 앞선 장부와 게시된 묶음을 읽어 95와 5를 재현합니다. 결과를 채택하는 계약은 잘못된 주장이나 증거를 거절합니다.</p><p>한 운영자가 여러 역할을 수행하더라도 책임은 나뉩니다. 처리자가 멈췄을 때 어떤 입력이 남고 누가 재계산할 수 있는지 확인하려면 이 구분이 필요합니다. 자료와 판정 중 하나를 없애 보면 이유가 더 분명해집니다.</p></section>
<section id="why-parts" data-teach-level="2"><h2>5. 계산 증명만 있어도 숨겨진 거래를 읽을 수는 없습니다</h2><p>처리자가 결과를 가리키는 짧은 식별자만 게시하고 T1과 T2를 숨기면 다른 참여자는 자신의 잔액과 거래 이력을 재구성하기 어렵습니다. 식별자는 받은 자료가 맞는지 대조하는 데 쓰지만 자료 자체를 가져오는 기능은 아닙니다.</p><p>반대로 거래를 모두 공개해도 주 장부가 발표된 96을 무조건 받아들이면 검증자가 찾은 오류가 반영되지 않습니다. 자료를 구하는 규칙과 잘못된 결과를 배제하는 규칙을 함께 두어야 합니다. 이제 각각의 이름을 붙입니다.</p></section>
<section id="names" data-teach-level="3"><h2>6. L2 실행·데이터 가용성·L1 정산은 다른 책임입니다</h2><dl className="space-y-4"><div><dt className="font-semibold">별도 실행 공간 → L2</dt><dd>거래를 실행하고 상태와 처리 결과를 계산합니다. 순서를 먼저 제안하는 담당자는 sequencer입니다.</dd></div><div><dt className="font-semibold">주 장부 → L1</dt><dd>묶은 입력과 결과 판정 계약을 연결하는 기반 체인입니다. 입력 묶음을 게시하는 담당자는 batcher입니다.</dd></div><div><dt className="font-semibold">검증 자료를 구할 수 있음 → data availability, DA</dt><dd>T1과 T2 등 상태를 재구성할 자료에 접근할 수 있는 성질입니다.</dd></div><div><dt className="font-semibold">L1 입력으로 L2를 만들기 → derivation</dt><dd>거래 묶음뿐 아니라 L1 입금 사건과 시스템 설정을 읽어 같은 L2 실행 입력을 만듭니다.</dd></div><div><dt className="font-semibold">결과에 외부 효력을 부여하기 → settlement</dt><dd>정해진 증거·이의 제기 규칙에 따라 결과를 받아들이고 출금 등에 사용합니다.</dd></div></dl><p>실행 결과 전체를 짧게 나타내는 값이 state root입니다. 아래 R95는 ‘A=95, B=5를 포함한 상태의 루트’에 붙인 설명용 이름입니다. 잔액 숫자 95가 실제 해시가 되는 것은 아닙니다.</p><RollupPipelineViz/></section>
<section id="derivation" data-teach-level="4"><h2>7. 공개된 두 거래를 같은 순서로 복원합니다</h2><p>Sequencer가 T1, T2를 실행해 R95를 알립니다. Batcher는 거래가 담긴 묶음을 압축해 L1의 blob이나 calldata 경로로 게시합니다. 검증 노드는 해당 L1 블록과 입금 사건, 당시 설정을 확인한 뒤 게시된 조각을 모으고 압축을 풀어 실행 입력을 만듭니다. 이 입력을 앞선 상태에 적용하면 같은 R95가 나와야 합니다.</p><p>거래 묶음인 batch와 전체 복원 절차인 derivation은 다릅니다. 어느 L1 블록을 기준으로 삼는지, 입금을 어느 순서에 넣는지, 누락된 조각을 얼마나 기다리는지, 적용 중인 fork의 규칙이 무엇인지도 결과에 영향을 줍니다.</p><p>OP Stack에서 sequencer에게 직접 받은 결과는 아직 L1 입력으로 확인되지 않은 <strong>unsafe</strong>일 수 있습니다. 현재 L1 체인의 데이터에서 복원한 결과는 <strong>safe</strong>입니다. 그 결과를 도출하는 데 필요한 L1 데이터가 확정되면 <strong>finalized</strong>로 표시할 수 있습니다. 단순히 관련 L1 블록 하나가 확정됐다는 뜻으로 줄이면 안 됩니다.</p><p>이 표시와 출금 정산은 다릅니다. L2 데이터가 finalized여도 결과 주장에 대한 이의 제기와 출금 조건이 남을 수 있습니다. 실제 대기 시간과 조건은 해당 체인의 계약과 배포 버전에서 확인합니다. 다음은 ‘조각을 다 모았다’는 판단을 원문에 대입해 보겠습니다.</p></section>
<section id="derivation-source" data-teach-level="5"><h2>8. 조각 번호가 이어지고 마지막 조각이 있어야 읽습니다</h2><div id="paper-op-derivation"><CitationBlock source="OP Stack f7cefd2 · L2 Chain Derivation, Frame Format / Reading" citeKey={1} href={spec+"protocol/derivation.md"}><p>원문 형식은 <code className="break-all">frame = channel_id ++ frame_number ++ frame_data_length ++ frame_data ++ is_last</code>입니다. Reading 규칙은 채널이 닫혀 있고 마지막까지 연속된 조각이 있어야 읽을 준비가 됐다고 정합니다.</p></CitationBlock></div><p>T1과 T2가 담긴 압축 데이터를 조각 0과 1로 나눴다고 합시다(가정). 두 조각의 channel_id는 같고 조각 1의 is_last=1입니다. 조각 1만 받으면 끝 번호를 알아도 0이 빠져 있으므로 완성된 입력으로 읽을 수 없습니다. 0을 얻으면 번호 순으로 연결합니다. 도착 순서가 거래의 실행 순서를 바꾸지 않습니다.</p><p>형식의 고정 부분은 16+2+4+1=23바이트입니다. 조각의 데이터가 100바이트라면 조각 하나는 123바이트이고 두 개는 246바이트입니다. 둘을 한 version 0 게시 데이터에 넣으면 맨 앞 버전 1바이트를 더해 247바이트입니다. 실제 거래 외피와 blob 포장 비용까지 센 값은 아닙니다.</p><p>명세는 알 수 없는 버전을 무시하고 중복 조각을 버리며 오래된 채널을 제한 시간 후 제거합니다. 다른 버전의 압축 형식과 누락 batch 처리도 정해진 규칙을 따릅니다. 이 원문은 저장소 commit으로 보존했으며 전체 OP 노드를 돌려 이 사례를 재현한 기록은 아닙니다.</p></section>
<section id="optimistic" data-teach-level="6"><h2>9. 96이라는 주장을 두고 틀린 계산 지점을 좁힙니다</h2><p><strong>Optimistic rollup</strong>은 결과 주장을 올리고 정해진 기간과 규칙에 따라 잘못을 지적할 수 있게 합니다. 사례의 R96 주장에 검증자가 R95를 재현하면 이의를 제기합니다. 함께 인정한 시작 상태와 같은 입력에서 어느 계산 단계의 결과가 갈라지는지 좁힌 뒤 계약이 작은 단계의 옳고 그름을 확인합니다. 이를 fault proof라고 합니다.</p><p>1024개 명령 단계의 실행 기록을 놓고 매번 불일치 구간을 절반으로 줄이는 단순 모델을 생각해 봅시다. 남은 단계 수는 1024→512→256→128→64→32→16→8→4→2→1입니다. 열 번 줄이면 한 단계가 남습니다. 이것은 T1과 T2가 실제로 1024개 명령으로 실행됐다는 측정값이 아닙니다.</p><ExplainedFormula question="몇 번의 구간 축소로 한 단계가 남을까요?" idea="한 번 줄일 때 남는 후보가 절반이므로 r번 뒤 N/2^r이 1 이하가 되면 됩니다." formula={String.raw`N/2^r\le1\quad\Rightarrow\quad r=\lceil\log_2N\rceil`} annotatedFormula={String.raw`\underbrace{N/2^r}_{\text{남은 단계}}\le1\quad\Rightarrow\quad r=\underbrace{\lceil\log_2N\rceil}_{\text{필요한 축소 횟수}}`} operations={[{expression:String.raw`N/2^r`,annotation:"r번 절반으로 줄인 뒤 남는 후보 단계 수입니다."},{expression:String.raw`\log_2N`,annotation:"2를 몇 번 곱해야 N이 되는지 구해 필요한 축소 횟수를 찾습니다."},{expression:String.raw`\lceil\log_2N\rceil`,annotation:"단계를 절반만 수행할 수 없으므로 남은 후보를 없애도록 정수 횟수로 올립니다."}]} terms={[{symbol:"N",name:"후보 단계 수",description:"불일치 구간에 처음 포함된 실행 단계 수입니다."},{symbol:"r",name:"축소 횟수",description:"불일치 구간을 한 단계로 좁히는 정수 횟수입니다."}]} assumptions={["매번 거의 절반으로 나누고 중간 상태의 약속을 검증할 수 있습니다.","실제 dispute game 전체의 메시지 수나 처리 시간을 이 식으로 단정하지 않습니다."]} interpretation="N=1024이면 10회, N=1000000이면 20회입니다. 각 응답의 L1 포함 대기와 시간 제한, 마지막 검증 비용은 별도로 듭니다."/>
<div id="paper-op-fault-proof"><CitationBlock source="OP Stack f7cefd2 · Fault Proof, Epilogue" citeKey={2} href={spec+"fault-proof/index.md"}><p>원문 마지막 판정은 재계산한 output-root와 claim을 비교해 같으면 exit code 0, 다르면 1을 반환합니다. 이 output-root는 상태 루트만의 별칭이 아니며 블록 해시와 출금 저장 루트 등의 속성으로 계산합니다.</p></CitationBlock></div><p>사례에서 올바른 95 상태를 포함한 output-root와 96 주장의 값이 다르면 그 주장은 실패합니다. 실제 구현은 프로그램, 실행을 한 단계씩 증명하는 가상 기계, 구간을 좁히는 분쟁 계약을 함께 고정합니다. 정확한 게임은 여러 참여자와 시간·담보 규칙을 포함하므로 위 10회 계산을 전체 프로토콜과 같다고 보면 안 됩니다.</p><div id="paper-optimistic-rollup"><CitationBlock source="Ethereum.org · Optimistic rollups" citeKey={3} href="https://ethereum.org/developers/docs/scaling/optimistic-rollups/"><p>이 개요는 입력 게시와 결과 주장, 이의 제기를 연결하는 일반 구조의 보충 자료입니다. 특정 배포의 출금 시간이나 분쟁 참여 권한은 개별 계약으로 확인합니다.</p></CitationBlock></div></section>
<section id="validity" data-teach-level="6"><h2>10. 95로 이어지는 계산의 증명을 먼저 확인할 수도 있습니다</h2><p><strong>Validity rollup</strong>에서도 운영자는 T1과 T2를 실행합니다. 증명자는 앞선 상태에서 이 입력을 지정된 프로그램으로 계산하면 R95가 된다는 증명을 만들고 L1의 검증 계약이 이를 확인합니다. 잘못된 R96을 받아들이지 않는 조건을 이의 제기 후 검증에서 증명 확인으로 옮깁니다.</p><p>검증자가 보는 공개 입력에는 이전·새 상태 루트와 거래 데이터에 대한 약속 등이 들어갑니다. 증명자가 사용하는 거래와 중간 실행 상태는 witness라고 부릅니다. 실제 필드와 무엇을 숨기는지는 증명 시스템과 회로가 정합니다. 프로그램과 공개 입력의 연결이 틀리면 엉뚱한 계산을 올바르게 증명할 수도 있습니다.</p><p>계산이 맞다는 validity와 정보를 숨기는 zero knowledge는 별도 성질입니다. 또한 증명이 맞아도 T2 자료를 얻지 못하면 사용자의 상태 복원 문제가 남습니다. 데이터를 별도 위원회 등에 맡기는 구조의 신뢰 가정도 따로 읽어야 합니다. 증명 생성의 지연과 장애는 처리 진행에 영향을 줄 수 있습니다.</p></section>
<section id="comparison" data-teach-level="7"><h2>11. 누락·틀린 결과·기반 체인의 변경을 따로 검수합니다</h2><ProofComparisonViz/><p>Sequencer가 T2를 빼놓으면 요청의 포함과 진행이 문제입니다. 프로토콜이 제공하는 L1 직접 포함 경로와 지연을 확인합니다. 게시한 자료를 얻지 못하면 여러 제공자와 보관·복원 경로를 확인합니다. A=96이라는 결과는 fault proof나 validity 검증에서 거절해야 합니다. 이 세 문제의 대응은 서로 다릅니다.</p><p>입력을 담은 L1 가지가 바뀌는 reorg가 생기면 그 가지에서 만든 L2 결과를 그대로 두지 않습니다. 이전·새 L1 가지와 fork 버전을 고정하고 되돌릴 지점, 버릴 채널 상태, 다시 실행할 입력을 정합니다. T1과 T2가 새 가지에도 같은 순서로 남아 있다면 재계산 뒤 R95와 처리 결과가 일치해야 합니다.</p><p>검수에는 정상 조각, 조각 0 누락, 중복 게시, 처리자 중단, 틀린 주장·증명, 이의 제기 시간 초과를 넣습니다. 같은 앞선 상태와 설정으로 두 구현의 복원한 입력과 잔액, 실패 상태를 비교합니다. 일치한 뒤에 처리 지연과 증명 비용을 비교하고 일부 노드에 적용한 결과를 보고 확대하거나 이전 버전으로 되돌립니다. 실제 실행을 마친 시험 목록이 아니라 구현을 채택할 때 필요한 검사 설계입니다.</p><ul className="list-disc space-y-3 pl-6"><li>마지막 조각 1을 받았지만 0이 없다면 T1과 T2를 완성된 입력으로 실행할까요? (답: 8절)</li><li>1024단계를 10번 줄일 수 있다면 출금도 즉시 끝날까요? (답: 9절)</li><li>R95의 계산 증명이 맞으면 숨겨진 T2의 원본도 자동으로 얻을까요? (답: 10절)</li></ul></section>
</article>}
