import { Link } from "react-router-dom";
import ProgressiveDetail from "@/components/articles/progressive-detail";
import AlgorithmBlock from "@/components/ui/algorithm-block";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import NumericPath from "@/pages/articles/world-systems/NumericPath";
import ReviewPrompts from "@/pages/articles/world-systems/ReviewPrompts";
import SourceApplication from "@/pages/articles/world-systems/SourceApplication";
import ReadyWorkViz from "./viz/ReadyWorkViz";
export default function Article(){return <div className="space-y-16">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 일이 많이 남아 있어도 지금 시작할 수 있는 일은 없을 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">계산 결과가 도착하기 전에 그 결과를 쓰는 다음 계산을 시작할 수는 없습니다. 기다리는 동안 다른 일을 내보내면 장치를 계속 사용할 수 있지만, 모든 일이 같은 순간 기다리면 빈 시간이 생깁니다.</p>
<p className="leading-8">이 글은 네 작업 묶음이 기다림을 번갈아 가리는 모습을 따라갑니다. 얼마나 많이 배치했는지와 지금 무엇을 시작할 수 있는지를 구별하면 GPU가 덜 바빠 보이는 이유를 좁힐 수 있습니다.</p></div></section>
<section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 맡은 일 중 준비된 명령을 하나 골라 내보냅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">한 선택 장치가 여러 작업 묶음을 맡습니다. 입력은 각 묶음의 다음 명령, 그 명령에 필요한 값의 도착 여부, 명령을 받을 처리 장치의 여유입니다. 출력은 이번에 내보낼 명령 하나이거나 아무것도 내보내지 않는 상태입니다.</p>
<p className="leading-8">명령을 내보내는 순간과 계산이 끝나는 순간은 다릅니다. 앞서 보낸 계산이 진행되는 동안 다음 기회에 다른 일을 시작할 수 있습니다. 먼저 이 동작을 작은 시간표로 그립니다.</p></div><NumericPath title="한 번의 선택" steps={[{label:"맡은 일",value:"여러 묶음의 다음 명령"},{label:"준비 확인",value:"입력 도착 · 받을 여유"},{label:"이번 선택",value:"명령 하나 또는 빈 자리"}]}/></section>
<section id="case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 네 묶음 중 한 묶음의 첫 결과가 더 늦게 도착합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">A·B·C·D 네 묶음이 한 선택 장치에 배치됐다고 가정합니다. 시간 눈금마다 명령 하나를 내보낼 수 있고, 각 묶음의 다음 계산에는 바로 앞 결과가 필요합니다. 네 묶음의 첫 명령은 모두 준비되어 있습니다(가정).</p>
<p className="leading-8">A·C·D의 계산 결과는 발행한 눈금에서 4만큼 뒤에 준비됩니다. B의 첫 명령은 값을 읽어 오며 8만큼 뒤에 준비됩니다. 1에서 시작한 A는 5에, 2에서 시작한 B는 10에 다음 계산을 낼 수 있습니다. 여기서 4와 8은 모형의 가정값입니다.</p>
<p className="leading-8">선택 순서를 A·B·C·D·A로 놓습니다. 이 순서가 실제 하드웨어의 우선순위라는 뜻은 아닙니다. 명령 해독과 처리 장치의 여유는 모두 준비되어 있다고 두고, 앞 결과를 기다리는 효과만 봅니다.</p></div></section>
<section id="picture" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 먼저 보낸 결과를 기다리는 동안 다른 묶음을 선택합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">처음 네 눈금에는 서로 다른 묶음을 한 번씩 선택합니다. 다섯째에는 A의 결과가 도착해 A를 다시 선택합니다. 여섯째에는 아직 받을 결과가 남아 네 묶음 모두 다음 계산을 시작하지 못합니다.</p>
<p className="leading-8">아래 그림은 매 눈금의 시작 상태를 보여 줍니다. B의 첫 읽기 대기를 8에서 4로 줄이면 여섯째에 B가 준비됩니다. 배치된 묶음 수는 같은 네 개지만 빈 발행 기회가 사라지는 변화를 비교합니다.</p></div><ReadyWorkViz/></section>
<section id="why" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 기다리는 값과 선택할 일을 따로 관리해야 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">한 묶음의 결과를 기다린다고 전체 장치를 멈출 필요는 없습니다. 다른 묶음에 준비된 일이 있으면 그것을 선택합니다. 앞선 계산의 결과가 언제 필요한지를 관리해야 값이 오기 전에 다음 계산을 잘못 시작하지 않습니다.</p>
<p className="leading-8">입력 값이 도착했어도 다음 명령이 아직 해독되지 않았거나 처리 장치가 받을 수 없으면 후보가 되지 못합니다. 준비 여부에는 이 조건들이 함께 들어갑니다. 기다리는 이유를 나누어야 일을 더 배치하는 방법이 효과가 있을지 판단할 수 있습니다.</p></div></section>
<section id="names" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 작업 묶음과 세 상태를 이름으로 구별합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"></div><div className="my-6 overflow-x-auto rounded-xl border"><table className="w-full table-fixed text-left text-sm leading-7"><caption className="sr-only">앞에서 본 역할과 이름</caption><tbody><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">명령을 함께 진행하는 작업 묶음</th><td className="block break-words p-3 align-top sm:table-cell">Warp는 32개 thread의 묶음이며 그 안의 각 자리가 lane입니다. 조건에 따라 일부 lane만 현재 명령에 참여할 수 있습니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">묶음을 맡는 GPU 내부 구역</th><td className="block break-words p-3 align-top sm:table-cell">SM은 Streaming Multiprocessor입니다. 여기서는 H100의 SM을 네 subpartition으로 나누어 봅니다. Profiler는 subpartition을 SMSP로 표기합니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">자기 묶음에서 명령을 고르는 장치</th><td className="block break-words p-3 align-top sm:table-cell">Warp scheduler입니다. 발행할 warp를 고르고 명령을 내보내는 동작을 issue라고 합니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">이 구역에 배치된 상태</th><td className="block break-words p-3 align-top sm:table-cell">Active 또는 resident입니다. 이 글의 A·B·C·D는 여섯째 눈금에도 모두 배치되어 있습니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">다음 명령을 낼 수 있는 상태</th><td className="block break-words p-3 align-top sm:table-cell">Eligible입니다. 명령 해독, 입력 의존 해소, 실행 장치의 가용성이 모두 필요합니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">후보에서 실제 선택된 상태</th><td className="block break-words p-3 align-top sm:table-cell">Issued warp입니다. 준비되어도 다른 warp가 선택되면 그 순간은 not selected입니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">앞 결과를 기다리는 관계</th><td className="block break-words p-3 align-top sm:table-cell">Dependency입니다. 미완료 결과를 기다리는 상태를 scoreboard로 추적합니다. 결과가 필요한 시점까지의 기다림을 dependency latency로 읽습니다.</td></tr><tr className="block border-t sm:table-row"><th scope="row" className="block p-3 align-top font-medium sm:table-cell sm:w-[30%]">명령을 보내는 기회와 실행 경로</th><td className="block break-words p-3 align-top sm:table-cell">Issue slot은 발행 기회입니다. 선택한 명령을 해당 execution pipe로 보내는 동작을 dispatch라고 부릅니다. Pipe도 명령을 받을 여유가 있어야 합니다.</td></tr></tbody></table></div></section>
<section id="trace" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. 여섯째 clock에는 네 warp가 모두 다음 결과를 기다립니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">이제 시간 눈금을 clock이라 부릅니다. Clock 1에서 A가 명령을 내면 결과가 5에 준비됩니다. Clock 2의 B는 10, clock 3의 C는 7, clock 4의 D는 8에 다음 의존 명령을 낼 수 있습니다.</p>
<p className="leading-8">Clock 5에는 A가 준비되어 두 번째 명령을 냅니다. 그 새 결과는 9에 준비됩니다. 따라서 clock 6의 다음 준비 시점은 A=9, B=10, C=7, D=8입니다. 아직 모두 미래이므로 active는 4, eligible은 0, issued는 0입니다.</p>
<p className="leading-8">이 여섯 번에는 다섯 번 발행하고 한 번 비었습니다. A·B·C·D를 배치했다는 사실만으로 모든 clock을 채우지는 못합니다. B의 첫 대기를 4로 바꾼 비교에서는 B가 clock 6에 준비되어 그 자리를 채웁니다.</p></div></section>
<section id="sm-structure" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 실제 배치 단위와 발행 상한을 연결합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">CUDA에서 프로그래머는 grid·block·thread로 일을 구성합니다. Block이 어느 SM에 배치되고 어느 warp가 먼저 명령을 내는지는 특정 순서로 약속되지 않습니다. Block의 thread는 32개씩 warp가 되며 block은 한 SM에서 실행됩니다.</p>
<p className="leading-8">예를 들어 256-thread block은 여덟 warp를 만듭니다. GPU가 이 warp들을 scheduler에 배정하지만 프로그램이 특정 subpartition의 순서나 동시 진전을 가정하면 안 됩니다. 본문의 A·B·C·D는 배치 뒤 한 scheduler가 맡은 네 warp를 골라 본 모형입니다.</p>
<p className="leading-8">H100의 SM에는 네 warp scheduler가 있습니다. Scheduler당 clock마다 warp instruction 하나를 낸다는 발행 모형이면 SM당 최대 4개입니다. NVIDIA가 공개한 H100 SXM5의 132 SM 구성에 적용하면 132×4=528개/clock입니다.</p>
<p className="leading-8">이 값은 해당 구성의 모형 상한입니다. 모든 SM과 scheduler가 그만큼 발행할 수 있는 일이 있어야 하며 명령 종류와 실행 장치도 허용해야 합니다. 명령 하나의 활성 lane 수와 연산 개수가 다르므로 이 숫자를 곧바로 FP32 연산 처리량으로 바꾸지 않습니다.</p></div><SourceApplication source="CUDA C++ Programming Guide · CC 9.0 Architecture" excerpt="4 warp schedulers" application="사례의 선택 장치는 네 scheduler 중 하나를 확대해 본 것입니다. 네 구역 모두가 매 clock 하나씩 낼 때만 SM당4개라는 발행 모형의 상한에 닿습니다."/></section>
<section id="issue-scoreboard" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 공식 후보 조건에 같은 여섯째 clock을 넣습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">Nsight Compute Profiling Guide의 SM 설명은 eligible에 세 조건을 둡니다. 다음 명령이 해독되어 있고, 필요한 입력 의존이 모두 풀렸으며, 실행 장치가 사용 가능해야 합니다. Scoreboard가 비었다는 조건 하나만으로 후보를 만들 수 없습니다.</p>
<p className="leading-8">사례의 clock 6에서 명령 해독과 실행 장치의 여유는 가정상 준비되어 있습니다. 그러나 A·B·C·D의 다음 명령이 요구하는 결과는 각각 clock 9·10·7·8에 도착합니다. 입력 의존 조건이 실패하므로 후보 집합이 비어 이번 slot을 사용하지 못합니다.</p>
<p className="leading-8">Clock 5에는 A의 입력 의존이 풀렸고 나머지 조건도 만족해 후보가 됩니다. B·C·D는 여전히 기다립니다. 이때 active 4개와 eligible 1개는 다른 숫자이며, 하나만 준비돼 있어도 그 clock의 발행은 가능합니다.</p></div><SourceApplication source="Nsight Compute Profiling Guide · SM / warp state" excerpt="a decoded instruction, all input dependencies resolved, and for the function unit to be available" application="clock6의 네 warp는 가운데 조건을 만족하지 못합니다. B의 대기를4로 바꾸면 clock6의 B는 세 조건을 모두 만족해 선택할 수 있습니다."/><AlgorithmBlock title="학습용 의사코드: 후보를 만든 뒤 한 명령을 선택" input={["Resident warp와 각 next instruction", "미완료 입력 의존, 해독 상태, 실행 pipe 가용성"]} steps={[{code:"eligible = { w : decoded(w) && inputs_ready(w) && pipe_available(w) }",note:"세 조건을 함께 확인합니다. 실제 하드웨어의 scoreboard 구현 소스가 아닙니다."},{code:"if eligible is empty: leave this issue slot unused",note:"사례의 clock6에서는 네 warp의 입력 의존이 남아 있습니다."},{code:"w = select(eligible); issue_and_dispatch(w.next)",note:"선택 정책은 이 모형에서 정하지 않습니다. 발행과 실행 완료는 다른 시점입니다."},{code:"record pending result; clear dependency when ready",note:"결과가 준비되면 이를 쓰는 명령을 다시 평가합니다. 다른 조건도 만족해야 후보입니다."}]} output="이번 clock의 warp instruction 하나 또는 빈 issue slot"/></section>
<section id="profiler-states" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 어디에서 기다리는지와 후보에서 밀렸는지를 구별합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">Profiler가 not selected로 기록한 warp는 명령을 낼 수 있었지만 다른 warp가 선택된 경우입니다. 사례의 clock 1에서 B·C·D가 이에 해당합니다. 이것은 입력이 아직 없어 막힌 상태와 다릅니다.</p>
<p className="leading-8">Long scoreboard는 L1TEX 경로의 local·global·surface·texture 연산 결과에 대한 의존 대기입니다. 표본은 결과를 기다리는 소비 명령에 나타날 수 있습니다. 비율만으로 어느 load가 몇 clock 걸렸는지 또는 HBM 자체의 지연을 직접 측정했다고 말할 수 없습니다.</p>
<p className="leading-8">Short scoreboard는 L1TEX가 아닌 MIO 연산의 의존 대기입니다. Shared memory가 흔한 원인이지만 특수 수학 명령과 동적 분기 등도 포함될 수 있습니다. Wait는 고정 지연을 가진 실행 의존과 연결되며 각 항목은 target과 도구의 정의를 확인합니다.</p>
<p className="leading-8">Math pipe throttle은 해당 실행 pipe가 사용 가능해지기를 기다리는 상태입니다. 모든 입력이 와도 특정 pipe에 일이 몰리면 발행이 막힐 수 있습니다. 일반적인 발행 이후 대기열의 길이로 설명하지 않습니다. Barrier 대기와 명령을 가져오지 못한 상태도 별도 원인입니다.</p></div><ProgressiveDetail title="Not selected가 높거나 eligible이 낮으면 무엇부터 확인하나요?" preview="표본의 분모와 issue 사용률을 먼저 보고, 입력 의존과 실행 pipe 병목을 나누어 확인합니다."><p className="leading-8">Not selected가 높으면 준비된 후보가 여럿 있다는 신호일 수 있습니다. 그렇다고 모든 실행 구간에서 warp가 충분하거나 수를 바꿔도 절대 효과가 없다는 뜻은 아닙니다. Issue 사용률과 같은 구간의 지표를 보고 자원 점유·cache 지역성까지 비교합니다.</p>
<p className="leading-8">Resident 16개인데 eligible이 평균 1개 미만이라는 관찰만으로 모든 warp가 같은 long scoreboard를 기다린다고 확정할 수 없습니다. 의존, barrier, 명령 공급과 pipe 가용성 등 실제 stall 구성을 봐야 합니다. Cache·coalescing·독립 연산을 바꾸는 처방도 확인한 원인에 맞춥니다.</p>
<p className="leading-8">실행 pipe 자체의 처리량이 이미 포화라면 warp만 추가해 그 폭을 넓힐 수는 없습니다. 반대로 비어 있는 시간이 남으면 다른 독립 작업의 배치가 일부 기다림을 가릴 수 있습니다. 하나의 stall 비율을 실행 시간 개선률로 옮기지 않습니다.</p></ProgressiveDetail></section>
<section id="latency-hiding" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 매 순간 네 후보보다 네 개의 독립된 일이 필요합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">모든 warp의 의존 지연이 4 clock이고 한 scheduler가 매 clock 하나를 낸다고 가정하면 A·B·C·D를 돌아가며 선택해 A가 다시 준비될 때까지 빈자리를 메울 수 있습니다. 한 clock의 eligible 수가 하나여도 이 패턴이 이어질 수 있습니다.</p>
<p className="leading-8">CUDA C++ Programming Guide는 CC 7.x의 대부분 산술 명령에서 보통 4 clock인 지연과 최대 처리량 조건을 설명합니다. 네 scheduler를 가진 SM에서 warp마다 의존 사슬 하나라면 4×4=16 active warps라는 계산입니다. 이 수치를 모든 H100 명령의 실측 지연이라고 사용하지 않습니다.</p>
<p className="leading-8">
            평균적으로 진행 중인 일의 수는 도착·완료까지의 시간과 처리 속도의 곱으로 읽을 수 있습니다. 이 관계를 Little’s law라고 부릅니다. Warp 네 개가 독립된 일
            하나씩을 갖는 방법은 thread-level parallelism, TLP입니다. Warp 두 개가 독립된 일 두 개씩을 갖는 방법은 instruction-level
            parallelism, ILP입니다.
          </p>
<p className="leading-8">여기서 필요한 warp 수는 독립된 일을 제공할 resident 자원의 모형 하한입니다. 매 순간 준비된 후보 수인 eligible과 같지 않습니다. 본문의 B가 8 clock을 기다리는 경우처럼 지연이 달라지면 같은 네 warp가 있어도 빈자리가 생깁니다.</p></div><ExplainedFormula question="지연 L 동안 발행을 이어 가려면 독립된 일이 얼마나 필요합니까?" idea="평균 지연과 발행 속도를 곱해 진행 중인 일을 구합니다. Warp당 독립 일을 몇 개 유지할 수 있는지로 필요한 배치 수의 모형 하한을 계산합니다." formula={String.raw`\begin{aligned}\bar I&=Lr\\W_{\rm res}&\ge\left\lceil\bar I/P\right\rceil\end{aligned}`} annotatedFormula={String.raw`\begin{aligned}\bar I&=\underbrace{L}_{\text{지연}}\;\underbrace{r}_{\text{발행률}}\\W_{\rm res}&\ge\underbrace{\left\lceil\bar I/P\right\rceil}_{\text{독립 일로 나누고 올림}}\end{aligned}`} operations={[{expression:"Lr",annotation:["Clock 단위 지연과 clock당 warp instruction 수를 곱합니다."]},{expression:"\\lceil\\bar I/P\\rceil",annotation:["Warp당 동시에 유지하는 독립 일의 수 P로 나누어 올림합니다."]}]} terms={[{symbol:"L",name:"평균 의존 지연",description:"발행에서 해당 결과가 준비될 때까지의 clock 수입니다."},{symbol:"r",name:"목표 평균 발행률",description:"이 모형은 scheduler당1 warp instruction/clock을 사용합니다."},{symbol:"P",name:"Warp당 독립 일",description:"앞 결과를 기다리지 않고 겹쳐 유지할 수 있는 명령 수의 모형입니다."},{symbol:"Wres",name:"독립 일을 제공하는 resident warp",description:"한 시점의 eligible 개수와 다릅니다."}]} assumptions={["안정된 평균 흐름과 서로 맞는 명령 단위를 전제로 합니다.","실행 pipe·대역폭·요청 큐·register가 필요한 병렬성을 허용해야 합니다.","시작과 끝의 채우기·비우기, 변동 지연과 명령 배치는 따로 봅니다."]} interpretation="L=4,r=1이면 평균4개의 진행 중인 일이 필요합니다. P=1이면 warp4개, P=2이면2개라는 하한입니다. 충분한 배치 수만으로 발행 성공을 보장하지는 않습니다."/></section>
<section id="memory-and-bubbles" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 긴 읽기 지연은 요청 수와 실제 수용량을 함께 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">같은 모형에 읽기 지연 500 clock과 발행률 1 warp-load/clock을 넣으면 평균 500개 요청이 진행 중이어야 합니다(가정). Resident warp를 16개로 제한하면 warp당 필요한 독립 요청의 평균은 500/16=31.25개입니다. 각 warp에 같은 정수 용량을 둔 모형에서는 32개씩 수용할 여지가 필요합니다. 모든 warp가 실제로 매 순간 32개씩 진행해야 한다는 뜻은 아닙니다.</p>
<p className="leading-8">
            여기서 요청 단위는 warp의 load 명령입니다. 각 lane의 주소나 메모리 sector 500개를 뜻하지 않습니다. 이런 독립 메모리 작업의 겹침을 memory-level
            parallelism, MLP라고 부릅니다. 이 계산으로 Hardware의 실제 큐가 500개를 수용하는지 알 수는 없습니다.
          </p>
<p className="leading-8">요청 큐·대역폭·cache·register와 실제 명령 순서가 이 병렬성을 허용해야 합니다. MLP를 늘리는 unroll이 register를 늘려 resident warp를 줄이면 다른 비용이 생깁니다. 더 적은 바이트를 요청하거나 cache에서 더 빨리 공급하는 방법도 함께 비교합니다.</p>
<p className="leading-8">후보가 없어 발행 slot이 비는 현상을 이 글에서는 issue pipeline bubble이라고 부릅니다. 1000 clock 중 600번 발행한 단일 slot 모형이면 사용률60%, 빈 비율40%입니다. 다만 실제 측정의 모든 미발행을 자동으로 No Eligible과 같다고 놓지 말고 지표의 분모와 원인을 확인합니다.</p>
<p className="leading-8">이번 여섯 clock의 빈 비율은 1/6입니다. 이는 짧은 가정 시간표의 결과이며 kernel 전체의 평균이나 분산 추론 pipeline stage의 빈 시간과 다른 단위입니다.</p></div></section>
<section id="divergence" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 조건이 갈리면 같은 명령의 참여 자리도 줄어듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">지금까지는 다음 명령을 낼 수 있는지를 봤습니다. 명령을 계속 내더라도 warp 안 일부 lane만 참여하면 유효한 일의 비율이 낮아질 수 있습니다. 조건에 따라 lane이 서로 다른 경로를 따라가는 현상을 divergence라고 합니다.</p>
<p className="leading-8">분기·재합류 명령을 제외한 모형에서 lane16개가 명령10개의 경로A를, 나머지16개가 명령10개의 경로B를 실행한다고 가정합니다. 두 경로를 각각 발행하면 slot20개를 쓰며 유효한 lane 명령은160+160=320개입니다. 가능한32×20=640개 자리의50%입니다.</p>
<p className="leading-8">Lane 하나가 명령30개의 예외 경로로 가고 나머지31개가 명령10개의 경로를 가면 slot은40개입니다. 유효한 lane 명령은30+310=340개이므로 이용 비율은340/1280=26.5625%입니다. 모두10명령 경로를 가는 비교의4배 slot이지, 실행 시간이 반드시4배라는 뜻은 아닙니다.</p>
<p className="leading-8">이 비용은 후보가 없어 쉬는 시간과 다릅니다. 서로 다른 경로를 발행하는 동안 참여 mask가 달라집니다. 실제 compiler가 짧은 분기를 predication으로 바꾸거나 경로를 최적화할 수 있으므로 원본 if 수를 곧바로 기계 명령 수로 세지 않습니다.</p></div><ProgressiveDetail title="입력을 같은 경로끼리 모으면 항상 빠릅니까?" preview="Warp 안의 갈림을 줄여도 주소가 흩어지거나 분류 비용이 늘 수 있습니다."><p className="leading-8">조건이 threadIdx/warpSize처럼 warp 경계와 맞으면 한 warp 안의 thread들은 같은 쪽으로 갑니다. 해당 조건의 내부 갈림을 피할 수 있습니다. 다른 데이터 의존 조건까지 없어졌다는 보장은 아닙니다.</p>
<p className="leading-8">같은 분기끼리 모으는 일과 메모리 주소를 연속으로 모으는 coalescing은 목표가 다릅니다. 분류가 주소 접근과 균형을 악화시킬 수 있으므로 분류·재배치 비용과 전체 실행 시간을 함께 비교합니다.</p></ProgressiveDetail></section>
<section id="thread-scheduling" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. Lane별 진행 상태가 있어도 동기화 규칙은 필요합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">
            Volta 이후 independent thread scheduling은 thread별 program counter와 call stack을 관리해 갈라진 경로를 더 유연하게
            진행할 수 있게 합니다. 그렇다고 모든 spin lock의 교착이 사라지거나 잘못된 통신이 자동으로 안전해지지는 않습니다.
          </p>
<p className="leading-8">필요한 값이 쓰이기 전에 읽거나, 일부 참여자가 도달하지 않는 대기를 만들면 여전히 문제가 생깁니다. 같은 warp라는 이유만으로 thread들이 매번 같은 지점에 도착한다고 가정하지 않습니다.</p>
<p className="leading-8">__syncwarp(mask)는 지정한 참여 thread들의 대기와 메모리 순서를 보장하는 도구입니다. 각 호출 thread의 bit가 mask에 있어야 하며 mask에 포함된 종료하지 않은 thread들은 같은 mask의 대응 호출을 실행해야 합니다. 빠진 참여자를 아무 mask로 덮으면 안 됩니다.</p>
<p className="leading-8">Shuffle·vote의 *_sync 연산에도 참여 mask와 대응 호출 규칙이 있습니다. 필요한 동기화와 데이터 교환을 그 규칙에 맞춰 작성해야 합니다. __syncwarp 하나를 임의 위치에 넣으면 모든 후속 경로가 자동으로 안전해진다는 설명은 성립하지 않습니다.</p></div><ProgressiveDetail title="오래된 warp 동기 코드가 왜 다시 확인되어야 하나요?" preview="독립 진행을 허용하는 실행 모델에서는 thread들이 저절로 보조를 맞춘다고 가정할 수 없습니다."><p className="leading-8">서로의 데이터를 warp 안에서 교환하는 기존 코드는 어느 thread가 무엇을 쓰고 언제 다른 thread가 읽는지 확인해야 합니다. __syncwarp는 참여 범위 안의 메모리 순서를 제공하지만 block 전체나 다른 block의 순서를 제공하지 않습니다.</p>
<p className="leading-8">CC6.x 이하의 __syncwarp에는 참여 thread가 수렴된 상태에서 호출해야 하는 추가 조건이 있습니다. 대상 세대에 맞는 문서 조건을 사용합니다. 이 글의 slot 산수는 lane별 진행 상태가 있어도 유효한 경로의 일을 수행해야 한다는 비용을 보여 주며 실제 scheduler의 선택 정책을 재현하지 않습니다.</p></ProgressiveDetail></section>
<section id="evidence" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">15. 원문의 정의와 모형의 가정값을 구별합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">네 warp의 시간표와 읽기 지연8·500은 설명을 위해 둔 값입니다. 실제 하드웨어 구현 코드나 GPU에서 얻은 실행 로그가 아닙니다. 원문은 실행 단위·후보 조건·동기화·지표 의미를 확인하는 데 사용합니다.</p>
<p className="leading-8">산술4 clock과 active16의 공식 설명은 CC7.x와 최대 처리량 조건에 묶입니다. H100 SXM5의132 SM·네 scheduler 구성은 별도의 제품 자료입니다. 같은 숫자가 보인다는 이유로 서로 다른 범위의 근거를 하나의 측정처럼 섞지 않습니다.</p></div><div id="paper-cuda-simt-multithreading" className="scroll-mt-20"><CitationBlock source="CUDA C++ Programming Guide 12.8.1 · SIMT, Hardware Multithreading, Multiprocessor Level" citeKey={1} href="https://docs.nvidia.com/cuda/archive/12.8.1/cuda-c-programming-guide/index.html">32-thread warp와 의존 지연, CC7.x의4 clock·active16 조건, divergence와 참여 mask 규칙을 확인합니다. 본문의 가정 clock표를 실제 명령 지연으로 확대하지 않습니다.</CitationBlock></div><div id="paper-nsight-compute-scheduler" className="scroll-mt-20"><CitationBlock source="Nsight Compute Profiling Guide · SM, Scheduler Statistics, Warp Stall Reasons" citeKey={2} href="https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html">2026-10-04 확인한 후보의 세 조건과 stalled/not selected의 의미입니다. 표본의 소비 명령과 실행 시간의 인과를 구별합니다.</CitationBlock></div><div id="paper-hopper-sm-diagram" className="scroll-mt-20"><CitationBlock source="NVIDIA Hopper Architecture In-Depth · H100 SXM5와 SM 구성" citeKey={3} href="https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/">SM132개와 네 scheduler 구성으로528 warp instruction/clock 모형을 계산합니다. 다른SKU·세대의 공통값이나 실제 kernel 처리량을 주장하지 않습니다.</CitationBlock></div></section>
<section id="limits" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">16. 명령을 더 낼 수 있는 이유와 유효한 일을 구별합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">사례의 여섯째 clock은 일이 없어서 빈 것이 아닙니다. 네 warp의 다음 명령이 필요한 결과를 기다리고 있었습니다. B의 결과를 더 일찍 받으면 같은 배치 수로도 그 자리를 채울 수 있습니다.</p>
<p className="leading-8">실제 kernel에서는 준비된 후보, 발행률, 활성 lane, 자원 점유와 메모리·실행 pipe를 함께 봅니다. Warp 수를 늘리거나 의존을 줄이는 변경이 전체 시간에서 이득인지 같은 조건으로 비교합니다.</p></div><p className="leading-8">저장 자리가 동시 배치 수를 줄이는 계산은 <Link className="text-sky-700 underline" to="/cs/gpu/cuda-register-pressure#residency">register residency</Link>, 바이트와 연산량의 한계는 <Link className="text-sky-700 underline" to="/cs/gpu/gpu-memory-hierarchy-and-roofline">메모리 계층과 roofline</Link>에서 이어 봅니다. <Link className="text-sky-700 underline" to="/cs/gpu/amd-gpu-execution-and-hip#names">AMD의 wavefront와 CU</Link>는 해당 구조의 단위로 비교합니다.</p><ReviewPrompts questions={["B의 첫 읽기 지연을8에서4로 바꾸면 clock6의 active·eligible·issued 수가 어떻게 바뀝니까? (답: 7·9절)","지연4와발행률1의 모형에서 필요한 warp4개를 매 순간 eligible4개라고 읽으면 왜 틀립니까? (답: 11절)","Lane1개의30명령과31개의10명령 경로를 함께 처리할 때 slot 수와 이용 비율은 얼마이며 시간 배율까지 확정할 수 있습니까? (답: 13절)"]}/></section>
</div>;}
