import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { IpfsFilecoinBoundaryViz } from "./IpfsFilecoinBoundaryViz";

const IPFS_REV = "ff7230ffe47f6aa765a105271f6294299e5f233f";
const BITSWAP = `https://github.com/ipfs/specs/blob/${IPFS_REV}/src/bitswap-protocol.md`;
const ROUTING = `https://github.com/ipfs/specs/blob/${IPFS_REV}/src/routing/http-routing-v1.md`;
const KUBO = "https://github.com/ipfs/kubo/tree/v0.42.0";
const FILECOIN = "https://github.com/storacha/specs/blob/3b6791869635735ddb1a54aed7450ad6ef687c06/w3-filecoin.md";

export default function ModernIpfsFilecoinStorage() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">10 MiB 파일 하나를 IPFS에서 찾고 Filecoin 보관 evidence까지 연결하기</p><h2 className="text-3xl font-bold tracking-tight">IPFS는 content를 찾고 검증하는 경로이고 Filecoin은 보관 약속과 storage proof를 기록하는 경로다</h2></header><p className="text-lg leading-8 text-foreground/90">두 시스템은 같은 content를 다룰 수 있지만 같은 보장을 하지 않습니다. IPFS의 CID·Merkle DAG는 bytes의 identity를 고정하고 routing/Bitswap은 provider 후보와 block transfer를 찾습니다. Filecoin pipeline은 CAR/Piece commitment, deal lifecycle와 PoRep·PoSt evidence를 만듭니다. “IPFS에 add했다”, “Filecoin deal이 있다”, “지금 빠르게 내려받았다”는 서로 다른 receipts입니다. <a className="text-primary hover:underline" href="/p2p/content-addressing#overview">content addressing 정본</a>과 <a className="text-primary hover:underline" href="/blockchain/filecoin-proofs#overview">Filecoin proof stack 정본</a>은 재사용하고 integration 경계만 설명합니다.</p><IpfsFilecoinBoundaryViz /><ContentBoundary article="ipfs-filecoin-storage" /></section>

    <section id="identity-map" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Identity map artifact</p><h2 className="mt-2 text-2xl font-bold">Root CID·block CIDs·CAR shard·PieceCID와 deal ID를 같은 값으로 취급하지 않는다</h2></header><p>예제 파일을 UnixFS DAG로 만들면 root CID와 여러 block CIDs가 생깁니다. Deal용 CAR/piece로 포장하면 별도 commitment(PieceCID/CommP)와 padding/profile이 생기며, on-chain deal ID는 다시 lifecycle record의 식별자입니다. Mapping manifest에는 original file digest·size, UnixFS/importer/chunker profile, root CID, ordered block list, CAR/shard digests, piece commitment·size, deal/proof references와 tool revisions을 기록합니다.</p><ExplainedFormula question="서로 다른 identifier를 어떻게 한 artifact chain으로 묶을까?" idea={<>각 단계의 identifier와 변환 profile을 canonical manifest에 넣고 manifest 자체를 hash합니다.</>} formula={String.raw`M=H(C_{root}\|\{C_i\}\|D_{car}\|C_{piece}\|P_{enc}\|V)`}
    annotatedFormula={String.raw`M=\underbrace{H(C_{root}\|\{C_i\}\|D_{car}\|C_{piece}\|P_{enc}\|V)}_{\text{Piece commitment 계산}}`}
    operations={[
      { expression: String.raw`H(C_{root}\|\{C_i\}\|D_{car}\|C_{piece}\|P_{enc}\|V)`, annotation: ["Piece commitment이(가) 식의 결과에 기여하는","방식을 계산합니다.","각 단계의 identifier와 변환 profile을","canonical manifest에 넣고 manifest"] },
    ]} terms={[{symbol:"M",name:"Identity-map digest",description:"Content→storage 변환 chain 전체를 식별합니다."},{symbol:"H",name:"Cryptographic hash",description:"Canonical manifest serialization에 적용하는 hash입니다."},{symbol:"C_{root}",name:"Root CID",description:"UnixFS/IPLD DAG의 진입 content identifier입니다."},{symbol:"C_i",name:"Block CIDs",description:"DAG를 구성하는 ordered/referenced block identifiers입니다."},{symbol:"D_{car}",name:"CAR digest",description:"Storage artifact로 전송한 CAR/shard bytes의 digest입니다."},{symbol:"C_{piece}",name:"Piece commitment",description:"Filecoin piece encoding/profile에 따른 commitment입니다."},{symbol:"P_{enc}",name:"Encoding profile",description:"Chunker, codec, CAR order, padding과 piece size 규칙입니다."},{symbol:"V",name:"Tool revisions",description:"Importer와 commitment generator의 pinned versions입니다."}]} assumptions={["Manifest field 순서와 serialization을 canonical하게 고정합니다.","Root CID와 PieceCID가 우연히 비슷해 보여도 의미·codec·검증식이 다릅니다."]} interpretation="파일 bytes가 같아도 chunker나 CAR/padding profile을 바꾸면 mapping M이 달라지므로 이전 deal receipt를 새 artifact에 붙이지 않습니다." /><div id="paper-ipfs-bitswap"><CitationBlock type="code" citeKey={1} source="IPFS Bitswap protocol · commit ff7230f" href={BITSWAP}><p><strong>문제:</strong> Peer가 원하는 content-addressed blocks를 발견·요청·전송하고 response를 요청과 연결해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned Bitswap spec은 wantlist, block/presence messages와 peer exchange의 wire-level roles를 정의합니다.</p><p><strong>중요 가정:</strong> commit ff7230f의 protocol revision, libp2p transport와 CID/multihash verification을 함께 사용합니다.</p><p><strong>근거 범위:</strong> Bitswap block-exchange specification snapshot에 한정합니다.</p><p><strong>일반화 금지:</strong> Provider record·HAVE response가 현재 block possession, low latency, durability 또는 Filecoin deal을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="retrieve-path" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Retrieval policy router</p><h2 className="mt-2 text-2xl font-bold">Local blockstore, IPFS peers/gateway와 Filecoin retrieval 후보를 순서·timeout 정책으로 선택한다</h2></header><p>Routing은 content를 가진 것으로 광고된 provider 후보를 줄 뿐 bytes receipt는 아닙니다. Router는 local pin/cache, delegated routing/DHT, Bitswap 또는 gateway, Filecoin retrieval path를 policy에 따라 시도하고, 매번 받은 block bytes를 requested CID로 재검증합니다. Receipt에는 route order, provider identity, dial/first-byte/transfer/verify time, bytes, retries, final source와 failure reason을 기록합니다.</p><ExplainedFormula question="Retrieval latency를 어느 단계로 나눠야 병목을 찾을 수 있을까?" idea={<>Provider 탐색, 연결, 첫 byte, transfer와 content verification을 따로 더합니다.</>} formula={String.raw`T_{get}=T_{route}+T_{dial}+T_{first}+T_{transfer}+T_{verify}`}
    annotatedFormula={String.raw`T_{get}=\underbrace{T_{route}+T_{dial}+T_{first}+T_{transfer}+T_{verify}}_{\text{Transfer time 계산}}`}
    operations={[
      { expression: String.raw`T_{route}+T_{dial}+T_{first}+T_{transfer}+T_{verify}`, annotation: ["Transfer time이(가) 식의 결과에 기여하는 방식을","계산합니다.","Provider 탐색, 연결, 첫 byte, transfer와","content verification을 따로 더합니다."] },
    ]} terms={[{symbol:"T_{get}",name:"Verified retrieval time",description:"요청부터 CID 검증된 bytes receipt까지 걸린 wall time입니다."},{symbol:"T_{route}",name:"Routing time",description:"Provider candidates를 찾는 시간입니다."},{symbol:"T_{dial}",name:"Connection time",description:"선택한 provider/endpoint와 연결하는 시간입니다."},{symbol:"T_{first}",name:"First-byte wait",description:"요청 뒤 첫 payload byte를 받기까지의 시간입니다."},{symbol:"T_{transfer}",name:"Transfer time",description:"Expected bytes를 모두 받는 시간입니다."},{symbol:"T_{verify}",name:"Verification time",description:"Decode와 CID/multihash 재계산 시간입니다."}]} assumptions={["Monotonic clock, 동일 root/block CID와 timeout/retry policy를 사용합니다.","Cache hit·network path·block size가 다르면 값을 직접 비교하지 않습니다."]} interpretation="Routing 20ms, dial 30ms, first-byte 50ms, transfer 400ms, verify 5ms면 Tget=505ms입니다. 단순히 ‘IPFS 505ms’라 쓰지 않고 transfer 병목을 드러냅니다." /><div id="paper-ipfs-routing"><CitationBlock type="code" citeKey={2} source="IPFS HTTP Routing V1 · commit ff7230f" href={ROUTING}><p><strong>문제:</strong> Content·peer·IPNS routing records를 interoperable HTTP API로 질의해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned spec은 provider lookup request/response와 records의 transport schema를 정의합니다.</p><p><strong>중요 가정:</strong> Exact endpoint profile, response signatures/TTL policy와 downstream transfer verifier를 사용합니다.</p><p><strong>근거 범위:</strong> HTTP routing API snapshot의 candidate discovery semantics에 한정합니다.</p><p><strong>일반화 금지:</strong> Provider response를 current possession, successful transfer, CID integrity, low latency 또는 retention proof로 해석하지 않습니다.</p></CitationBlock></div></section>

    <section id="retention" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Retention and proof receipt</p><h2 className="mt-2 text-2xl font-bold">Pin/cache 정책과 Filecoin deal·PoRep·PoSt evidence를 각자 보존하고 연결한다</h2></header><p>Kubo pin은 local garbage collection retention boundary이고 network-wide durability 계약이 아닙니다. Filecoin deal proposal/activation과 PoRep·WindowPoSt receipts는 보관 evidence지만 사용자 retrieval 경로·속도를 보장하지 않습니다. Retention receipt에는 local pin/GC state, replica targets, Filecoin offer/aggregate/deal identifiers, PieceCID mapping, activation/expiration, latest storage proof status와 repair owner를 기록합니다.</p><ExplainedFormula question="여러 복제 경로의 가용성을 간단히 추정할 때 어떤 식을 쓸 수 있을까?" idea={<>각 replica가 독립적으로 reachable하다는 강한 가정 아래 모두 실패할 확률을 1에서 뺍니다.</>} formula={String.raw`P_{reachable}=1-\prod_{i=1}^{n}(1-a_i)`}
    annotatedFormula={String.raw`P_{reachable}=\underbrace{1-\prod_{i=1}^{n}(1-a_i)}_{\text{At-least-one 계산}}`}
    operations={[
      { expression: String.raw`1-\prod_{i=1}^{n}(1-a_i)`, annotation: ["At-least-one reachability이(가) 식의","결과에 기여하는 방식을 계산합니다.","각 replica가 독립적으로 reachable하다는 강한","가정 아래 모두 실패할 확률을 1에서 뺍니다."] },
    ]} terms={[{symbol:"P_{reachable}",name:"At-least-one reachability",description:"관찰 window에 최소 한 경로가 응답할 모델 확률입니다."},{symbol:"n",name:"Replica/path count",description:"서로 독립이라고 가정한 retrieval paths 수입니다."},{symbol:"a_i",name:"Path availability",description:"같은 window에서 i번째 path가 verified bytes를 반환할 확률입니다."},{symbol:"1-a_i",name:"Path failure",description:"i번째 path가 verified receipt를 만들지 못할 확률입니다."},{symbol:String.raw`\prod`,name:"Product",description:"독립 failures가 동시에 생길 확률을 곱합니다."}]} assumptions={["Failures가 독립이고 aᵢ가 측정 window 동안 일정하다는 단순 모델입니다.","같은 datacenter, DNS, gateway, billing 또는 software bug를 공유하면 상관 실패 때문에 식이 과대평가합니다."]} interpretation="독립 경로 두 개가 각 0.9라면 모델상 0.99입니다. 같은 gateway를 공유하면 독립 가정이 깨지므로 99% SLA라고 주장할 수 없습니다." /><div id="paper-ipfs-kubo"><CitationBlock type="code" citeKey={3} source="Kubo v0.42.0 stable source" href={KUBO}><p><strong>문제:</strong> IPFS node에서 blockstore, pin/GC, routing, exchange와 gateway 기능을 실제 운영 artifact로 결합해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned v0.42.0 tree는 stable Kubo implementation snapshot과 configuration/code boundaries를 제공합니다.</p><p><strong>중요 가정:</strong> v0.42.0 binary/build, repository schema, pin mode, datastore, routing/gateway config와 peers를 기록합니다.</p><p><strong>근거 범위:</strong> Kubo release source snapshot의 local node implementation에 한정합니다.</p><p><strong>일반화 금지:</strong> Local pin이 remote replication, Filecoin contract, uninterrupted gateway access 또는 영구 보존을 의미하지 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · End-to-end release gate</p><h2 className="mt-2 text-2xl font-bold">Identity map, verified retrieval, retention evidence와 repair/rollback을 모두 통과시킨다</h2></header><p>10 MiB fixture에서 changed chunker, reordered/truncated CAR, wrong PieceCID, stale provider ad, Bitswap corrupt block, gateway 200 with wrong bytes, local GC, expired deal, missing PoSt status, slow provider와 correlated outage를 주입합니다. Cold/cache-hit retrieval과 local/network/Filecoin paths를 분리 측정합니다. Candidate 실패 시 이전 importer/Kubo/router/manifest를 rollback하고 content-addressed artifacts는 검증된 digest가 같을 때만 재사용합니다.</p><ExplainedFormula question="IPFS–Filecoin service를 release할 최종 조건은 무엇일까?" idea={<>Identity, content verification, retention policy와 실제 retrieval sample을 독립 gates로 묶습니다.</>} formula={String.raw`A=M_{ok}\land B_{cid}\land S_{policy}\land R_{sample}\land O_{repair}`}
    annotatedFormula={String.raw`A=\underbrace{M_{ok}\land B_{cid}\land S_{policy}\land R_{sample}\land O_{repair}}_{\text{판정 조건 결합}}`}
    operations={[
      { expression: String.raw`M_{ok}\land B_{cid}\land S_{policy}\land R_{sample}\land O_{repair}`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","Identity, content verification,","retention policy와 실제 retrieval","sample을 독립 gates로 묶습니다."] },
    ]} terms={[{symbol:"A",name:"Release acceptance",description:"사용자-facing storage profile을 채택하면 1입니다."},{symbol:"M_{ok}",name:"Identity map",description:"Root CID→CAR→Piece/deal mapping과 versions가 완전하면 1입니다."},{symbol:"B_{cid}",name:"Byte integrity",description:"Retrieved blocks가 requested CIDs와 모두 일치하면 1입니다."},{symbol:"S_{policy}",name:"Storage policy",description:"Pin/replica/deal/proof stages가 상품 요구사항을 만족하면 1입니다."},{symbol:"R_{sample}",name:"Retrieval sample",description:"정해진 routes·sizes·regions에서 verified retrieval tests를 통과하면 1입니다."},{symbol:"O_{repair}",name:"Operational readiness",description:"Alert, retry, repair owner와 rollback artifacts가 준비되면 1입니다."}]} assumptions={["Policy에 proof freshness, retrieval regions, timeouts와 confidence를 수치·version으로 명시합니다.","한 번의 성공 sample을 미래 가용성 또는 storage permanence로 확대하지 않습니다."]} interpretation="Filecoin deal·PoSt evidence가 있어도 current retrieval test가 모두 실패하면 A=0입니다. 반대로 빠른 cache hit만으로 장기 retention을 승인하지 않습니다." /><div id="paper-ipfs-filecoin"><CitationBlock type="code" citeKey={4} source="Storacha–Filecoin pipeline spec · commit 3b67918" href={FILECOIN}><p><strong>문제:</strong> Content upload artifacts를 Filecoin piece aggregation, deal workflow와 status receipts로 연결해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned spec은 offer, aggregate, dealer와 tracker roles를 통해 content/piece/deal boundary를 드러냅니다.</p><p><strong>중요 가정:</strong> Exact spec maturity, piece encoding, UCAN receipts와 deployed Filecoin service/network versions을 확인합니다.</p><p><strong>근거 범위:</strong> Storacha의 Filecoin integration protocol snapshot에 한정하며 generic IPFS retrieval은 별도 spec을 따릅니다.</p><p><strong>일반화 금지:</strong> Offer·deal status가 current retrieval success, permanent availability, fixed duration 또는 PoRep·PoSt 전체 semantics를 대신하지 않습니다.</p></CitationBlock></div><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> CID와 PieceCID 차이, mapping manifest, provider candidate와 verified bytes, pin/deal/proof/retrieval 경계, latency·availability assumptions와 rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>;
}
