import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { KuboGcViz, KuboReceiptViz } from "./viz/ModernKuboViz";

export default function ModernKuboArticle() { return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Kubo v0.43.0 구현 읽기</p><h2 className="text-3xl font-bold tracking-tight">CID를 안다는 것, provider를 찾는 것, block을 받는 것은 서로 다른 단계다</h2></header><p className="text-lg leading-8">Alice가 <code>payroll-report-v1</code>을 Kubo에 추가하면 chunk와 DAG가 만들어지고 root CID가 생깁니다. Bob은 routing에서 provider 후보를 얻고 secure libp2p connection을 만든 뒤 Bitswap으로 필요한 block을 요청합니다. 받은 각 block은 CID로 검증되며, 오래 보관하려면 pin이 GC root에 들어가야 합니다.</p><p>이 글은 CID와 Merkle DAG를 다시 정의하지 않고 <a className="text-primary hover:underline" href="/p2p/content-addressing#overview">content addressing 정본</a>을, provider lookup의 탐색 원리는 <a className="text-primary hover:underline" href="/p2p/kademlia#overview">Kademlia 정본</a>을 재사용합니다. Kubo 고유의 핵심은 provider composer, Bitswap receipt, pin/GC와 gateway가 그 정본 사이에서 어떤 책임을 맡는지입니다.</p><KuboReceiptViz/></section>

  <section id="routing-bitswap" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · routing과 exchange</p><h2 className="mt-2 text-2xl font-bold">FindProvidersAsync는 후보를 만들고, Bitswap과 CID 검증이 수신을 확정한다</h2></header><p>v0.43.0의 routing composer는 <code>Provide</code>와 <code>FindProvidersAsync</code>를 별도 router에 위임합니다. provider record는 “이 peer가 이 CID를 제공한다고 알렸다”는 routing 정보입니다. stale record, offline peer, 사라진 block이 가능하므로 첫 후보 timeout 때 다음 후보로 넘어가야 합니다.</p><p>Bitswap은 candidate peer에게 필요한 block을 요청하고 local blockstore에 넣습니다. 응답 성공이나 secure channel만으로는 충분하지 않으며 block bytes에서 다시 계산한 CID가 요청 CID와 같아야 release할 수 있습니다. provider discovery 실패는 CID invalid와 다르고, hash mismatch는 단순 network retry보다 악성·손상 응답으로 기록해야 합니다.</p><div id="paper-kubo-routing-v043"><CitationBlock source="Kubo v0.43.0 — routing/composer.go · core/node/bitswap.go" citeKey={1} type="code" href="https://github.com/ipfs/kubo/tree/v0.43.0/routing"><p><strong>문제:</strong> content provider discovery와 block exchange를 조합하되 성공 의미를 섞지 않습니다.</p><p><strong>기여:</strong> Provide·FindProvidersAsync delegation과 Bitswap exchange wiring의 pinned 구현을 제공합니다.</p><p><strong>전제:</strong> Kubo v0.43.0 node, configured routing system과 reachable libp2p peers를 사용합니다.</p><p><strong>근거 범위:</strong> provider candidate stream, exchange setup과 local block receipt 경계입니다.</p><p><strong>말하지 않는 것:</strong> provider의 현재 possession, 응답 latency, payload의 업무 의미를 보장하지 않습니다.</p></CitationBlock></div><div id="paper-kubo-provider-v043"><CitationBlock source="Kubo v0.43.0 — core/node/provider.go" citeKey={2} type="code" href="https://github.com/ipfs/kubo/blob/v0.43.0/core/node/provider.go"><p><strong>문제:</strong> local block과 pin/DAG 상태에서 advertise·reprovide할 key를 구성합니다.</p><p><strong>기여:</strong> provider subsystem과 reprovider strategy의 concrete source wiring을 보여 줍니다.</p><p><strong>전제:</strong> 선택한 provider strategy, local repository와 routing backend가 정상 동작합니다.</p><p><strong>근거 범위:</strong> 이 node가 어떤 CID를 provider system에 공급하는지에 한정합니다.</p><p><strong>말하지 않는 것:</strong> remote routing table의 즉시 갱신이나 영구적 network availability를 약속하지 않습니다.</p></CitationBlock></div></section>

  <section id="pinning-gc" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · retention</p><h2 className="mt-2 text-2xl font-bold">Pin은 remote 복제본이 아니라 이 repository의 GC root다</h2></header><p>Recursive pin은 root뿐 아니라 따라갈 수 있는 DAG block을 보호합니다. GC는 pin, MFS와 internal root에서 reachable block을 표시한 뒤 나머지를 sweep합니다. Pin을 지워도 다른 root가 같은 block을 가리킬 수 있으므로 즉시 삭제한다고 말할 수 없습니다. 반대로 pin receipt는 remote peer 복제나 disk durability까지 증명하지 않습니다.</p><KuboGcViz/><ExplainedFormula question="GC가 local blockstore에서 제거할 후보는 어떻게 정할까?" idea={<>먼저 pin·MFS·internal root에서 도달 가능한 block을 보호 집합으로 칠하고, 전체 blockstore에서 그 집합을 뺀 나머지만 sweep 후보로 둡니다.</>} formula={String.raw`R=R_{\mathrm{pin}}\cup R_{\mathrm{MFS}}\cup R_{\mathrm{internal}},\qquad D=B\setminus R`}
  annotatedFormula={String.raw`R=\underbrace{R_{\mathrm{pin}}\cup R_{\mathrm{MFS}}\cup R_{\mathrm{internal}},\qquad D=B\setminus R}_{\text{blockstore 계산}}`}
  operations={[
    { expression: String.raw`R_{\mathrm{pin}}\cup R_{\mathrm{MFS}}\cup R_{\mathrm{internal}},\qquad D=B\setminus R`, annotation: ["blockstore이(가) 식의 결과에 기여하는 방식을","계산합니다.","먼저 pin·MFS·internal root에서 도달 가능한","block을 보호 집합으로 칠하고, 전체"] },
  ]} terms={[{symbol:"B",name:"blockstore",description:"GC 시작 snapshot에서 local repository가 보유한 block key 집합입니다."},{symbol:"R",name:"protected set",description:"모든 retention root에서 reachability traversal로 칠한 block 집합입니다."},{symbol:"D",name:"delete candidates",description:"다른 root가 보호하지 않아 sweep할 수 있는 block 집합입니다."}]} assumptions={["GC와 write의 locking/snapshot 규칙이 v0.43.0 repository 구현대로 지켜집니다.","DAG link traversal이 성공하고 손상 block은 별도 error로 기록합니다.","Pin은 local retention이며 replication·backup 계약은 별도입니다.","Disk failure와 repository corruption은 단순 집합식 밖의 위험입니다."]} interpretation="B={A,B,C,D,E}, R={A,B,C,E}이면 D 하나만 삭제 후보입니다. A의 pin을 풀어도 E가 B를 가리키면 B는 남습니다. 따라서 unpin receipt와 실제 reclaimed bytes를 구분해 측정합니다."/><div id="paper-kubo-gc-v043"><CitationBlock source="Kubo v0.43.0 — gc/gc.go · core/coreapi/pin.go" citeKey={3} type="code" href="https://github.com/ipfs/kubo/blob/v0.43.0/gc/gc.go"><p><strong>문제:</strong> bounded repository에서 protected DAG block을 보존하며 회수 가능한 block을 제거합니다.</p><p><strong>기여:</strong> colored/protected key 계산, sweep error reporting과 pin API의 local retention 경계를 구현합니다.</p><p><strong>전제:</strong> Kubo v0.43.0 repo lock과 pin/MFS/internal roots가 일관된 상태입니다.</p><p><strong>근거 범위:</strong> 한 node의 blockstore reachability와 garbage collection입니다.</p><p><strong>말하지 않는 것:</strong> remote replica 수, backup 복구 가능성, 규제 보존 기간을 보장하지 않습니다.</p></CitationBlock></div></section>

  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · gateway와 release</p><h2 className="mt-2 text-2xl font-bold">HTTP 200도 provider record도 content verification을 대신하지 않는다</h2></header><p>Gateway는 CID path를 HTTP representation으로 제공하는 접근면입니다. trusted gateway가 아니라면 response bytes와 CID를 검증하고 redirect·size·content-type 정책을 둡니다. Bitswap timeout은 다른 provider 후보로 재시도하지만 CID mismatch, repository corruption과 authorization failure는 같은 retry queue에 넣지 않습니다.</p><p>Release gate는 add→provide→다른 node find→Bitswap fetch→CID verify→pin→GC survival을 한 trace ID로 시험합니다. Offline provider, stale record, partial DAG, gateway oversized response, unpin 뒤 shared block 보존도 포함합니다. 실패한 임시 download는 지우고 열린 stream과 iterator를 닫으며, 검증 전 파일은 업무 시스템에 publish하지 않습니다.</p><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 CID·provider 후보·Bitswap·block receipt·pin·gateway의 성공 의미를 구분합니다. 심화 4문제는 stale provider retry, shared DAG의 GC 계산, hash mismatch fail-closed와 end-to-end release gate를 설계하게 합니다.</p></section>
</article>; }
