import ContentBoundary from "@/components/articles/content-boundary";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import HyperPlonkFlowViz from "./HyperPlonkFlowViz";

export default function ModernHyperPlonkArticle(){return <article className="space-y-14">
<section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">PLONK table을 Boolean hypercube로 옮기기</p><h2 className="text-3xl font-bold tracking-tight">2^μ rows를 μ변수 polynomial로 바꿔 FFT 없이 전체 gate를 검사한다</h2></header><p className="text-lg leading-8 text-foreground/90">PLONK가 roots-of-unity domain의 univariate polynomials를 쓰는 반면 HyperPlonk는 row index를 μ bits로 보고 table을 Boolean hypercube {`{0,1}`}^μ 위 multilinear extensions(MLEs)로 만듭니다. Gate constraints의 hypercube sum을 sumcheck로 한 random point evaluation까지 줄입니다.</p><p>이 변화는 FFT를 제거하고 high-degree custom gate를 더 직접 평가하게 하지만, permutation argument, multilinear PCS opening, transcript와 field soundness는 남습니다. “Linear-time prover”도 논문 model과 pinned workload에 귀속해야 합니다.</p><aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> 2^μ table entries를 모두 직접 검증하지 않고 μ rounds의 partial sums로 압축한 뒤 마지막 MLE point를 commitment로 엽니다.</aside><ContentBoundary article="hyperplonk"/><HyperPlonkFlowViz/></section>
<section id="multilinear" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Multilinear extension</p><h2 className="mt-2 text-2xl font-bold">Boolean corners를 일치시키는 유일한 개별차수 1 polynomial</h2></header><ExplainedFormula question="네 table values를 두 변수 MLE로 어떻게 확장하는가?" idea={<>각 Boolean point b에 그 corner에서만 1인 equality basis χ_b를 만들고 table value를 coefficient로 합합니다.</>} formula={String.raw`\widetilde v(r_1,r_2)=\sum_{b\in\{0,1\}^2}v_b\,\chi_b(r),\qquad \chi_b(r)=\prod_{j=1}^{2}\bigl(b_jr_j+(1-b_j)(1-r_j)\bigr)`}
annotatedFormula={String.raw`\widetilde v(r_1,r_2)=\underbrace{\sum_{b\in\{0,1\}^2}v_b\,\chi_b(r),\qquad \chi_b(r)=\prod_{j=1}^{2}\bigl(b_jr_j+(1-b_j)(1-r_j)\bigr)}_{\text{Unique MLE 계산}}`}
operations={[
  { expression: String.raw`\sum_{b\in\{0,1\}^2}v_b\,\chi_b(r),\qquad \chi_b(r)=\prod_{j=1}^{2}\bigl(b_jr_j+(1-b_j)(1-r_j)\bigr)`, annotation: ["Unique MLE이(가) 식의 결과에 기여하는 방식을","계산합니다.","각 Boolean point b에 그 corner에서만 1인","equality basis χ_b를 만들고 table"] },
]} terms={[{symbol:"v_b",name:"Table value",description:"Row bit-index b의 값입니다."},{symbol:"\\chi_b",name:"Boolean equality basis",description:"r=b에서 1이고 다른 Boolean corners에서 0입니다."},{symbol:"r_1,r_2",name:"Field coordinates",description:"Verifier가 Boolean domain 밖에서도 고르는 evaluation point입니다."},{symbol:"\\widetilde v",name:"Unique MLE",description:"각 변수 차수가 최대 1인 interpolation입니다."}]} assumptions={["Table ordering과 bit endianness를 circuit/commitment profile에 고정합니다.","2^μ entries를 같은 field에서 해석하고 padding rows의 의미를 고정합니다.","Non-Boolean evaluation은 algebraic extension이며 실제 새 table row로 해석하지 않습니다."]} interpretation="F17에서 (v00,v01,v10,v11)=(3,4,12,1), r=(2,3)이면 bases는 2,−3,−4,6입니다. Weighted sum은 −48≡3입니다. 이 계산은 MLE evaluation이지 네 값이 모두 같은 constraint를 만족한다는 증명은 아닙니다."/></section>
<section id="sumcheck" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Sumcheck</p><h2 className="mt-2 text-2xl font-bold">전체 Boolean 합을 변수 하나씩 random point에 고정한다</h2></header><ExplainedFormula question="g(b₁,b₂)=b₁b₂의 hypercube 합 1을 어떻게 두 rounds로 검증하는가?" idea={<>Prover가 첫 변수의 partial-sum polynomial을 보내면 verifier는 endpoints 합을 현재 claim과 맞추고 random r₁에 고정합니다. 다음 변수에도 같은 과정을 반복합니다.</>} formula={String.raw`p_1(t)=\sum_{b_2\in\{0,1\}}g(t,b_2)=t,\quad p_2(t)=g(r_1,t)=r_1t;\quad p_i(0)+p_i(1)=\text{previous claim}`}
annotatedFormula={String.raw`p_1(t)=\underbrace{\sum_{b_2\in\{0,1\}}g(t,b_2)=t,\quad p_2(t)=g(r_1,t)=r_1t;\quad p_i(0)+p_i(1)=\text{previous claim}}_{\text{Round invariant 계산}}`}
operations={[
  { expression: String.raw`\sum_{b_2\in\{0,1\}}g(t,b_2)=t,\quad p_2(t)=g(r_1,t)=r_1t;\quad p_i(0)+p_i(1)=\text{previous claim}`, annotation: ["Round invariant이(가) 식의 결과에 기여하는","방식을 계산합니다.","Prover가 첫 변수의 partial-sum","polynomial을 보내면 verifier는"] },
]} terms={[{symbol:"g",name:"Constraint polynomial",description:"Boolean rows에서 합을 주장하는 bounded-degree polynomial입니다."},{symbol:"p_i",name:"Round polynomial",description:"남은 Boolean variables를 합한 univariate polynomial입니다."},{symbol:"r_i",name:"Verifier challenge",description:"p_i가 고정된 뒤 transcript에서 뽑습니다."},{symbol:"previous claim",name:"Round invariant",description:"직전 round random point의 claimed value입니다."}]} assumptions={["각 p_i degree가 protocol bound 이하인지 검사합니다.","p_i coefficients를 받은 뒤 r_i를 균일하게 생성합니다.","Final g(r₁,…,rμ)는 committed MLE openings와 일치해야 합니다."]} interpretation="합은 g(00)+g(01)+g(10)+g(11)=1입니다. r₁=2면 p₁(2)=2, p₂(t)=2t이고 endpoints 합은 2입니다. r₂=3에서 p₂(3)=6=g(2,3)으로 끝납니다."/><ExplainedFormula question="거짓 sum claim이 random rounds를 통과할 단순 soundness 상한은 무엇인가?" idea={<>각 round의 정답 polynomial과 거짓 polynomial 차이는 nonzero degree≤d이므로 random challenge에서 같을 확률이 d/|F| 이하입니다. μ rounds를 union bound합니다.</>} formula={String.raw`\Pr[\mathrm{false\ sum\ accepted}]\le \frac{\mu d}{|\mathbb F|}`}
annotatedFormula={String.raw`\Pr[\mathrm{false\ sum\ accepted}]\le \underbrace{\frac{\mu d}{|\mathbb F|}}_{\text{기준량당 비율}}`}
operations={[
  { expression: String.raw`\frac{\mu d}{|\mathbb F|}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","각 round의 정답 polynomial과 거짓","polynomial 차이는 nonzero degree≤d이므로","random challenge에서 같을 확률이 d/|F|"] },
]} terms={[{symbol:"\\mu",name:"Variable/round count",description:"Boolean index bits 수입니다."},{symbol:"d",name:"Per-round degree bound",description:"Verifier가 허용하는 univariate degree입니다."},{symbol:"|\\mathbb F|",name:"Field size",description:"Challenge sampling 공간 크기입니다."}]} assumptions={["Challenges는 각 round message 뒤 독립·균일하게 파생됩니다.","Claimed degree와 final point opening을 검사합니다.","이는 구체 HyperPlonk 전체 error의 단순 구성요소이며 PCS/transcript error를 별도로 더합니다."]} interpretation="μ=2,d=1,F17이면 2/17입니다. Challenge를 항상 0으로 고르면 error polynomial X가 늘 0이므로 이 bound를 적용할 수 없습니다."/></section>
<section id="hyperplonk-boundary" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · HyperPlonk 고유 경계</p><h2 className="mt-2 text-2xl font-bold">Gate와 copy 의미는 유지하고 검증 polynomial만 multilinear로 바꾼다</h2></header><p>a=3,b=4,c=12 row의 ab−c=0을 포함한 gate table을 MLE로 만들고 random mixing과 sumcheck로 모든 Boolean rows의 gate identity를 검사합니다. Copy constraints는 별도 permutation relation이며 마지막 random point values는 multilinear PCS로 열어야 합니다.</p><p>FFT-free는 NTT 비용을 피한다는 뜻이지만 high-degree gate evaluation operations, sumcheck messages, MLE commitment/opening MSM, permutation과 memory traversal은 남습니다. Custom gate degree가 높으면 d와 field soundness budget도 함께 바뀝니다.</p><div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-5 text-sm leading-6"><strong>실패 반례:</strong> p₁ endpoints는 맞지만 degree-bound를 넘는 polynomial을 허용하면 prover가 challenge point에 맞출 자유도가 늘어납니다. Wrong corner·row order·copy permutation·final PCS opening을 각각 reject해야 합니다.</div></section>
<section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Linear-time 표기는 pinned phase breakdown으로 확인한다</h2></header><p>Commit SHA, circuit/table order, μ, gate degree, PCS, transcript와 hardware를 고정합니다. Valid table 뒤 wrong row, p_i endpoint, degree overflow, challenge order, permutation, final opening을 주입하고 phase별 MLE/sumcheck/PCS/proof/verify time, RSS와 bytes를 측정합니다. Reference repository가 외부 audit 미완료임도 release receipt에 남깁니다.</p><div id="paper-hyperplonk"><CitationBlock source="Chen et al. · HyperPlonk (2022)" citeKey={1} href="https://eprint.iacr.org/2022/1355.pdf"><p><strong>문제:</strong> PLONK의 FFT와 high-degree custom gate prover overhead를 줄여야 합니다.</p><p><strong>기여:</strong> Boolean hypercube·sumcheck 기반 multilinear IOP와 linear-time prover 방향을 제시합니다.</p><p><strong>전제:</strong> Multilinear PCS, field/challenge, permutation과 논문 security model을 사용합니다.</p><p><strong>근거 범위:</strong> Protocol·asymptotic analysis·논문 benchmark입니다.</p><p><strong>말하지 않는 것:</strong> 모든 구현의 linear wall time, audit 완료나 PCS 비용 제거를 뜻하지 않습니다.</p></CitationBlock></div><div id="paper-hyperplonk-source"><CitationBlock source="EspressoSystems/hyperplonk · pinned 2a3b55c" citeKey={2} type="code" href="https://github.com/EspressoSystems/hyperplonk/tree/2a3b55c97ad8a5d6627108a2e7def2aeccb7f3b9"><p><strong>문제:</strong> Arithmetic·subprotocol·transcript와 benchmark를 재현 가능한 source로 확인해야 합니다.</p><p><strong>기여:</strong> 공식 Rust reference implementation과 scripts를 제공합니다.</p><p><strong>전제:</strong> Commit 2a3b55c, dependency/toolchain과 repository disclaimer를 따릅니다.</p><p><strong>근거 범위:</strong> 해당 source/tests/bench scripts입니다.</p><p><strong>말하지 않는 것:</strong> 외부 security audit·production readiness·다른 hardware 성능을 보장하지 않습니다.</p></CitationBlock></div><p>10문항은 hypercube/MLE 계산, sumcheck 두 rounds·bound, PLONK 비교, uniqueness, biased challenge, high-degree cost와 release를 묻고 본문에 답이 있습니다.</p></section>
</article>}
