import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
const scenes=[
 {label:"부모 없음",request:"CL → EL: H101 검증 요청",el:"H100 상태 없음",response:"SYNCING",cl:"계산 결과를 아직 모름",detail:"잔액 89.999958을 확인할 이전 상태가 없습니다. 잘못됐다는 판정으로 저장하지 않습니다."},
 {label:"검증 성공",request:"CL → EL: H101 다시 검증",el:"100 − 10 − 0.000042",response:"VALID · latestValidHash=H101",cl:"유효한 후보임을 확인",detail:"A=89.999958 ETH, B=10 ETH를 재현했습니다. 아직 현재 head나 finalized를 뜻하지 않습니다."},
 {label:"가지 선택",request:"CL → EL: head=H101",el:"해당 유효한 가지를 선택",response:"forkchoice 응답",cl:"safe=H99 · finalized=H96",detail:"세 식별자는 다른 판단을 담습니다. 이 예에서 H99와 H96은 H101의 조상입니다."},
 {label:"재수신",request:"CL → EL: 같은 H101",el:"이미 본 유효한 후보",response:"VALID · 내부 중복 표시 true",cl:"중복 차감 없음",detail:"already_seen은 Reth 내부 값입니다. Engine API 응답에 새 필드를 추가하는 뜻이 아니며 같은 블록의 송금을 다시 적용하지 않습니다."},
]as const;
export function EngineBoundaryViz(){const state=useAnimatedScenes(scenes.length),scene=scenes[state.active];return <div data-viz="engine-boundary" data-viz-keyboard tabIndex={0} onKeyDown={state.onKeyDown} className="not-prose flex min-w-0 flex-col rounded-lg border border-border p-4 sm:p-6"><p className="mb-4 font-semibold">후보 H101의 검증과 선택</p><div data-viz-canvas className="h-[30rem] min-w-0 overflow-auto sm:h-[26rem]"><p className="break-words text-sm">{scene.request}</p><div className="mt-4 border border-border p-4"><p className="text-xs text-muted-foreground">실행 클라이언트 EL</p><p className="mt-2 font-semibold">{scene.el}</p><p className="mt-2 break-words font-mono text-xs">{scene.response}</p></div><svg aria-hidden="true" className="mx-auto my-3 h-5 w-8" viewBox="0 0 32 20"><path d="M16 1V18M11 13L16 18L21 13" fill="none" stroke="currentColor" strokeWidth="1"/></svg><div className="border border-primary/40 p-4"><p className="text-xs text-muted-foreground">합의 클라이언트 CL</p><p className="mt-2 break-words font-semibold">{scene.cl}</p></div><p className="mt-4 text-sm leading-7" aria-live="polite">{scene.detail}</p></div><AnimatedSceneControls labels={scenes.map(x=>x.label)} {...state}/></div>}
export function PayloadStateViz(){return <figure className="not-prose rounded-lg border border-border p-4 sm:p-6"><figcaption className="mb-4 font-semibold">실행 유효성 상태와 기록 선택의 구분</figcaption><dl className="space-y-5">{[["VALID","H101의 실행 결과가 부모 상태에서 유효합니다."],["INVALID","후보 또는 조상에 잘못된 내용이 확인되었습니다."],["SYNCING","H100 같은 필요한 자료가 없어 판정을 기다립니다."],["ACCEPTED","허용된 경로에서 수신했지만 전체 유효성을 확정하지 않았습니다."]].map(([t,d])=><div key={t} className="border-t border-border pt-3"><dt className="font-mono text-sm font-semibold">{t}</dt><dd className="mt-2 text-sm leading-7">{d}</dd></div>)}</dl><p className="mt-4 text-sm leading-7">반환 가능한 상태는 메서드와 버전별로 확인합니다. VALID인 H101도 현재 head로 선택되지 않을 수 있고 head도 finalized와 다릅니다.</p></figure>}
