const Card = ({ label, title, body, tone = "border-border" }: { label: string; title: string; body: string; tone?: string }) => <div className={`min-w-0 rounded-lg border ${tone} bg-background p-4`}><p className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 break-words font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></div>;

export function IrohBoundaryViz() {
  return <figure data-viz="iroh-boundary" className="my-8 min-w-0 rounded-xl border border-border/70 bg-muted/15 p-4 sm:p-6"><figcaption className="mb-5 text-sm font-semibold">payroll-report-v1: 콘텐츠를 찾는 일과 Iroh가 연결하는 일</figcaption><div data-viz-canvas className="grid min-w-0 gap-3 md:grid-cols-4"><Card label="1 · app/IPFS" title="CID 계산" body="bytes의 내용 주소를 만들고 provider 후보를 찾습니다." tone="border-sky-500/40"/><Card label="2 · app lookup" title="EndpointAddr 획득" body="Bob의 EndpointId와 direct·relay 주소를 얻습니다."/><Card label="3 · Iroh" title="QUIC + identity" body="EndpointId를 인증하며 도달 가능한 path로 연결합니다." tone="border-emerald-500/40"/><Card label="4 · protocol" title="ALPN dispatch" body="합의한 app protocol이 CID 요청과 block 검증을 맡습니다."/></div><p className="mt-4 text-xs leading-5 text-muted-foreground">경계: Iroh는 CID provider 검색기나 파일 의미 검증기가 아닙니다. EndpointAddr 이후의 authenticated transport를 맡습니다.</p></figure>;
}

export function IrohPathViz() {
  return <figure data-viz="iroh-path-selection" className="my-8 min-w-0 rounded-xl border border-border/70 bg-muted/15 p-4 sm:p-6"><figcaption className="mb-5 text-sm font-semibold">v1.0.3 path selector: tier를 먼저, biased RTT를 나중에</figcaption><div data-viz-canvas className="grid min-w-0 gap-3 sm:grid-cols-3"><Card label="primary" title="direct IPv6 · 21 ms" body="−3 ms bias를 적용하면 18 ms입니다." tone="border-emerald-500/40"/><Card label="current" title="direct IPv4 · 20 ms" body="같은 tier에서는 5 ms 이상 좋아야 교체합니다."/><Card label="backup" title="relay · 12 ms" body="더 빠르게 보여도 direct path가 살아 있으면 backup tier입니다." tone="border-amber-500/40"/></div><div className="mt-4 rounded-lg border border-border bg-background p-4 text-sm leading-6"><strong>이 예의 결정:</strong> IPv6의 biased RTT는 2 ms만 유리하므로 path를 바꾸지 않습니다. 14 ms로 측정되어 biased RTT가 11 ms가 되면 9 ms 유리하므로 바꿉니다.</div></figure>;
}
