import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["네 기록","개수로 바꾸기","같은 값 모으기","평균 기여"];
const records=["앞 · 앞","앞 · 뒤","뒤 · 앞","뒤 · 뒤"],values=[2,1,1,0];
const details=["가능한 네 기록의 비중을 각각 1/4로 정했습니다. 아직 숫자로 합치지 않았습니다.","앞면을 세면 네 기록은 차례로 2·1·1·0입니다. 가운데 두 기록은 같은 숫자 1로 갑니다.","숫자 1에는 두 기록의 비중이 합쳐집니다. 0·1·2의 비중은 각각 1/4·1/2·1/4입니다.","값에 비중을 곱하면 0·1/2·1/2가 기여합니다. 세 기여를 더한 평균은 1입니다."];
export default function RandomVariableMapViz(){const c=useAnimatedScenes(labels.length);return <VizFrame eyebrow="같은 네 기록 · 숫자로 모으기" title="두 기록이 합쳐진 자리에는 비중도 함께 모인다" description="앞면 개수로 바꾸는 규칙은 고정되어 있습니다. 장면을 넘기며 기록별 비중이 값별 비중과 평균 기여로 옮겨가는 과정을 봅니다." note="공정하고 서로 영향을 주지 않는 두 던짐을 가정합니다. 관측 네 번에 각 기록이 반드시 한 번씩 나온다는 뜻은 아닙니다.">
<div data-viz-canvas tabIndex={0} role="group" aria-label="기록에서 값과 평균으로" onKeyDown={c.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary">
<svg viewBox="0 0 320 265" className="mx-auto block w-full max-w-[480px]" role="img" aria-label={details[c.active]}>
{c.active<2?<>{records.map((r,i)=><g key={r}><rect x="22" y={14+i*57} width="276" height="45" rx="4" fill="none" stroke="currentColor" strokeWidth="1"/><text x="79" y={42+i*57} textAnchor="middle" fontSize="14" fill="currentColor">{r}</text><text x="158" y={42+i*57} textAnchor="middle" fontSize="13" fill="currentColor">1/4</text><text x="249" y={42+i*57} textAnchor="middle" fontSize="14" fill="currentColor">{c.active===1?'→ '+values[i]:'기록 '+(i+1)}</text></g>)}<text x="160" y="255" textAnchor="middle" fontSize="11" fill="currentColor">{c.active===1?'비중은 그대로 · 값만 계산':'네 비중의 합 = 1'}</text></>:<><text x="62" y="24" textAnchor="middle" fontSize="12" fill="currentColor">앞면 수</text><text x="163" y="24" textAnchor="middle" fontSize="12" fill="currentColor">모인 비중</text><text x="265" y="24" textAnchor="middle" fontSize="12" fill="currentColor">{c.active===3?'평균 기여':'원래 기록'}</text>{[0,1,2].map((v,i)=><g key={v}><rect x="22" y={40+i*61} width="276" height="49" rx="4" fill="none" stroke="currentColor" strokeWidth={v===1?2:1}/><text x="62" y={70+i*61} textAnchor="middle" fontSize="17" fill="currentColor">{v}</text><text x="163" y={70+i*61} textAnchor="middle" fontSize="15" fill="currentColor">{v===1?'1/2':'1/4'}</text><text x="265" y={70+i*61} textAnchor="middle" fontSize="13" fill="currentColor">{c.active===3?(v===0?'0':'1/2'):(v===1?'2개':'1개')}</text></g>)}<text x="160" y="247" textAnchor="middle" fontSize="13" fill="currentColor">{c.active===3?'0 + 1/2 + 1/2 = 1':'전체 비중 1/4 + 1/2 + 1/4 = 1'}</text></>}
</svg><p className="min-h-[7rem] text-sm leading-7" aria-live="polite">{details[c.active]}</p><AnimatedSceneControls {...c} labels={labels}/>
</div></VizFrame>;}
