import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";

type ArticleKey = "keylime" | "tee-sealing" | "tee-sidechannel" | "isms-encryption";
type Row = readonly [string, string, string];
type Failure = readonly [string, string];
type Citation = { id: string; title: string; href: string; problem: string; contribution: string; assumptions: string; scope: string; notClaim: string };
type Config = {
  key: ArticleKey; eyebrow: string; title: string; lead: string; boundary: string;
  firstId: string; firstTitle: string; secondId: string; secondTitle: string; releaseId: string;
  stages: readonly Row[]; details: readonly Row[]; failures: readonly Failure[];
  question: string; idea: string; formula: string; annotatedFormula: string;
  operations: readonly { expression: string; annotation: string | readonly string[] }[];
  terms: readonly { symbol: string; name: string; description: string }[];
  assumptions: readonly string[]; interpretation: string; citations: readonly Citation[];
};

const CONFIG: Record<ArticleKey, Config> = {
  keylime: {
    key: "keylime", eyebrow: "원격 검증 · 증거에서 키 반출까지", title: "Keylime은 TPM quote를 곧바로 신뢰하지 않고 정책 판정과 키 반출 사이를 잇는다",
    lead: "급여 처리 노드 한 대가 부팅된 뒤 파일 하나가 바뀌는 사례를 따라갑니다. Agent가 보낸 TPM quote가 진짜라는 사실, PCR과 측정 로그가 서로 맞는다는 사실, 그 상태가 조직의 허용 목록에 있다는 사실, 그래서 비밀을 내줘도 된다는 결정은 각각 다른 단계입니다.",
    boundary: "TPM·PCR·Measured Boot·RATS 역할의 공통 원리는 기초 글을 재사용합니다. 이 글은 Keylime agent·registrar·verifier·tenant, runtime IMA policy와 measured-boot policy를 연결하는 부분만 소유합니다.",
    firstId: "quote-policy", firstTitle: "Fresh quote와 reference policy를 분리한다", secondId: "ima-measured-boot", secondTitle: "IMA와 measured boot는 서로 다른 시점의 상태를 설명한다", releaseId: "release-gate",
    stages: [["REGISTER", "Registrar", "EK·AK와 agent identity를 등록하지만 현재 상태가 안전하다고 판정하지는 않습니다."], ["CHALLENGE", "Verifier ↔ Agent", "예측하기 어려운 nonce와 PCR selection으로 fresh quote·IMA log·boot log를 요청합니다."], ["APPRAISE", "Verifier policy", "서명·nonce·PCR replay를 확인한 뒤 runtime·measured-boot reference policy와 비교합니다."], ["AUTHORIZE", "Tenant / relying party", "통과한 attestation result와 업무 policy를 함께 확인한 뒤 payload·key 반출을 결정합니다."]],
    details: [["Quote", "AK signature·nonce·PCR selection", "서명 성공은 freshness와 policy match를 대신하지 않습니다."], ["IMA runtime policy", "파일 hash·서명 key allowlist", "PCR 10과 measurement list를 replay하고 기대 file/key와 비교합니다."], ["Measured-boot policy", "Firmware·boot component reference state", "Boot event log를 replay해 signed PCR과 비교한 뒤 허용 상태를 판정합니다."], ["Policy receipt", "agent·policy revision·evidence digest·reason", "빈 accept-all policy와 missing evidence는 운영 승인이 아닙니다."]],
    failures: [["Reused nonce / old quote", "Freshness 실패, key/payload 0"], ["PCR은 맞지만 IMA file hash drift", "Runtime policy mismatch, 격리와 reason receipt"], ["Boot log self-consistent but unknown image", "Reference policy mismatch, release 0"], ["Verifier pass 뒤 agent identity/channel 교체", "Recipient binding 실패, 재검증"]],
    question: "Keylime node에 비밀을 내줄 수 있는 최소 조건은 무엇인가?", idea: "Quote 검증, freshness, log replay, reference policy, recipient channel을 모두 같은 attempt에 묶은 경우만 허용합니다.", formula: String.raw`R=Q\land N\land L\land P\land C`,
    annotatedFormula: String.raw`R=\underbrace{Q\land N\land L\land P\land C}_{\text{판정 조건 결합}}`,
    operations: [
      { expression: String.raw`Q\land N\land L\land P\land C`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","Quote 검증, freshness, log replay,","reference policy, recipient","channel을 모두 같은 attempt에 묶은 경우만"] },
    ],
    terms: [{symbol:"Q",name:"Quote validity",description:"AK signature와 요청한 PCR selection이 유효한 조건입니다."},{symbol:"N",name:"Nonce freshness",description:"Verifier가 발급한 현재 challenge와 quote가 결속된 조건입니다."},{symbol:"L",name:"Log consistency",description:"IMA·boot log replay 결과가 signed PCR과 일치하는 조건입니다."},{symbol:"P",name:"Policy appraisal",description:"측정값이 versioned runtime·boot reference policy에 허용되는 조건입니다."},{symbol:"C",name:"Channel binding",description:"검증된 agent identity가 실제 key 수신자와 같은 조건입니다."},{symbol:"R",name:"Release decision",description:"모든 조건이 참일 때만 payload 또는 key를 내주는 결과입니다."}],
    assumptions:["같은 agent·nonce·policy revision·evidence digest를 하나의 receipt에 기록합니다.","Missing·unknown·expired 상태를 allow로 바꾸지 않습니다.","IMA policy helper가 만든 초안은 조직의 완전한 golden state를 자동 제공하지 않습니다."], interpretation:"예를 들어 quote와 PCR replay가 성공해도 허용 image 목록에 없는 boot component라면 P=0이므로 release하지 않습니다.",
    citations:[
      {id:"paper-keylime-architecture",title:"Keylime Remote Attestation architecture",href:"https://keylime.dev/blog/2024/02/07/remote-attestation-blog-part1.html",problem:"Agent·registrar·verifier·tenant의 책임을 분리해야 합니다.",contribution:"Keylime 공식 설명이 네 구성요소와 attestation 흐름을 소개합니다.",assumptions:"연결한 문서와 배포 release·pull/push mode를 고정합니다.",scope:"Keylime 구성요소와 원격 증명 흐름입니다.",notClaim:"특정 배포가 안전하거나 key release가 자동으로 exactly-once임을 보장하지 않습니다."},
      {id:"paper-keylime-verifier-api",title:"Keylime verifier API",href:"https://keylime.readthedocs.io/en/latest/rest_apis/2_5/verifier.html",problem:"검증 요청과 evidence field를 재현해야 합니다.",contribution:"Nonce·quote·PCR·runtime/boot policy·measurement list surface를 정의합니다.",assumptions:"API revision과 client/agent compatibility를 고정합니다.",scope:"Verifier REST API의 request·response field입니다.",notClaim:"API schema가 policy의 적절성이나 host 무결성을 증명하지 않습니다."},
      {id:"paper-keylime-runtime-ima",title:"Keylime runtime IMA",href:"https://keylime.readthedocs.io/en/latest/user_guide/runtime_ima.html",problem:"부팅 뒤 file·key 상태를 지속 평가해야 합니다.",contribution:"PCR 10 quote와 IMA measurement list·runtime policy의 연결을 설명합니다.",assumptions:"Kernel IMA mode·policy·keyring·measurement source를 고정합니다.",scope:"Keylime runtime IMA 측정과 policy 작성 지침입니다.",notClaim:"도구가 만든 allowlist가 완전하거나 악성 허용 file의 의미를 판정하지 않습니다."},
      {id:"paper-keylime-measured-boot",title:"Keylime measured boot",href:"https://keylime.readthedocs.io/en/latest/user_guide/use_measured_boot.html",problem:"Boot log의 자기 일관성과 허용 상태를 구분해야 합니다.",contribution:"Measured-boot log·policy/reference state와 named policy 사용을 설명합니다.",assumptions:"Firmware 측정 범위·event parser·policy revision을 고정합니다.",scope:"Keylime measured-boot appraisal 설정입니다.",notClaim:"빈 accept-all policy나 replay 성공이 secure boot·runtime correctness를 보장하지 않습니다."}
    ]
  },
  "tee-sealing": {
    key:"tee-sealing",eyebrow:"지속성 · identity-bound secret",title:"TEE sealing은 암호화 파일이 아니라 누가 어느 버전에서 다시 열 수 있는지 정하는 정책이다",
    lead:"급여 서명 키를 enclave에서 만들고 재부팅 뒤 다시 여는 사례를 따라갑니다. Sealing은 비밀을 평문으로 저장하지 않게 해 주지만 backup·rollback·복제·upgrade 정책을 대신 정해 주지는 않습니다.",boundary:"TEE identity·AEAD·KDF의 공통 정의는 재사용합니다. 이 글은 MRENCLAVE와 MRSIGNER policy 선택, key derivation context, sealed blob schema와 upgrade migration을 소유합니다.",
    firstId:"identity-policy",firstTitle:"정확한 build와 signer 계열 중 어느 범위를 허용할지 먼저 정한다",secondId:"blob-migration",secondTitle:"Ciphertext보다 먼저 blob schema·counter·migration receipt를 설계한다",releaseId:"release-gate",
    stages:[["SCOPE","Identity policy","MRENCLAVE는 정확한 enclave identity에, MRSIGNER는 signer와 product/SVN policy에 복구 범위를 묶습니다."],["DERIVE","Seal key context","CPU/platform root에서 identity·product·SVN·purpose·schema generation을 넣어 scoped key를 얻습니다."],["SEAL","AEAD envelope","Nonce·ciphertext·tag와 authenticated metadata·schema version·counter를 atomic blob으로 저장합니다."],["UNSEAL / MIGRATE","Verified upgrade","Policy와 tag를 검증한 뒤 plaintext를 최소 시간만 쓰고, 허용 source가 새 identity용 blob을 다시 봉인합니다."]],
    details:[["MRENCLAVE","Exact measurement","작은 code/config change도 기존 blob을 못 열 수 있어 엄격하지만 upgrade가 어렵습니다."],["MRSIGNER","Signer·product·SVN","같은 signer의 허용 version 계열을 지원하지만 signer key와 SVN policy가 더 큰 trust anchor가 됩니다."],["AEAD metadata","identity policy·schema·purpose·counter","Metadata를 인증하지 않으면 valid ciphertext를 다른 용도나 version으로 바꿔 끼울 수 있습니다."],["Migration","old decrypt → validate → new seal","두 blob과 migration attempt를 receipt로 남기고 crash 뒤 어느 세대가 authoritative인지 재조정합니다."]],
    failures:[["Blob bit flip / wrong tag","Unseal 거부, plaintext/effect 0"],["Old valid blob replay","Counter/generation policy mismatch, rollback 거부"],["Unapproved signer or lower SVN","Key derivation 또는 policy appraisal 거부"],["Migration write 중 crash","Old/new generation reconcile, blind delete 금지"]],
    question:"Sealed blob을 개봉할 수 있는 identity 범위를 어떻게 표현하는가?",idea:"Platform root에서 identity policy와 product·SVN·purpose·schema generation을 domain-separated context로 파생합니다.",formula:String.raw`K_s=\operatorname{KDF}(K_{root},I\,\|\,p\,\|\,v\,\|\,u\,\|\,g)`,
    annotatedFormula: String.raw`K_s=\underbrace{\operatorname{KDF}(K_{root},I\,\|\,p\,\|\,v\,\|\,u\,\|\,g)}_{\text{Platform root 계산}}`,
    operations: [
      { expression: String.raw`\operatorname{KDF}(K_{root},I\,\|\,p\,\|\,v\,\|\,u\,\|\,g)`, annotation: ["Platform root이(가) 식의 결과에 기여하는 방식을","계산합니다.","Platform root에서 identity policy와","product·SVN·purpose·schema"] },
    ],
    terms:[{symbol:"K_{root}",name:"Platform root",description:"TEE hardware가 보호하는 key derivation root입니다."},{symbol:"I",name:"Identity policy",description:"MRENCLAVE 또는 MRSIGNER 기반 허용 identity입니다."},{symbol:"p",name:"Product identity",description:"같은 signer 아래 서로 다른 product를 분리합니다."},{symbol:"v",name:"Security version",description:"허용 minimum SVN과 downgrade policy에 쓰입니다."},{symbol:"u",name:"Purpose",description:"급여 서명·DB key처럼 key 사용 영역을 분리합니다."},{symbol:"g",name:"Schema generation",description:"Blob format·migration 세대를 구분합니다."},{symbol:"K_s",name:"Sealing key",description:"정해진 identity·purpose·generation에서만 쓰는 derived key입니다."}],
    assumptions:["실제 SGX EGETKEY 구조와 SDK API는 pinned platform 문서를 따릅니다.","Context serialization과 AEAD nonce uniqueness를 보장합니다.","Sealing은 side channel·host rollback·backup availability를 자동 해결하지 않습니다."],interpretation:"Code upgrade를 허용하려면 단순히 MRSIGNER를 고르는 것으로 끝나지 않습니다. Product ID·minimum SVN·migration source/target을 함께 제한해야 합니다.",
    citations:[{id:"paper-intel-sgx-sealing",title:"Intel SGX sealing introduction",href:"https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-intel-sgx-sealing.html",problem:"재부팅 뒤 secret을 어떤 enclave 계열이 다시 열지 결정해야 합니다.",contribution:"MRENCLAVE와 MRSIGNER sealing policy 및 SDK sealing API 차이를 설명합니다.",assumptions:"SGX platform·SDK·CPU migration 조건을 고정합니다.",scope:"Intel SGX sealing identity policy의 공식 개요입니다.",notClaim:"Rollback protection·backup·migration atomicity·application authorization을 자동 제공하지 않습니다."},{id:"paper-nist-aead",title:"NIST SP 800-38D: GCM",href:"https://csrc.nist.gov/pubs/sp/800/38/d/final",problem:"저장한 secret의 기밀성과 metadata 무결성을 함께 검증해야 합니다.",contribution:"GCM authenticated-encryption 동작과 IV·tag 요구를 정의합니다.",assumptions:"Approved primitive·key/nonce lifecycle·tag length을 고정합니다.",scope:"GCM mode의 기밀성·인증 경계입니다.",notClaim:"TEE identity binding·rollback freshness·atomic file update를 제공하지 않습니다."}]
  },
  "tee-sidechannel": {
    key:"tee-sidechannel",eyebrow:"관찰 가능한 실행 · TEE의 비보장",title:"메모리가 암호화돼도 secret이 실행 시간·cache·speculation 흔적으로 새어 나갈 수 있다",
    lead:"Enclave가 급여 서명 키로 table lookup을 하는 한 요청을 따라갑니다. 공격자는 private page의 평문을 직접 읽지 않아도 secret-dependent access가 남긴 shared microarchitectural state를 반복 측정해 후보를 좁힐 수 있습니다.",boundary:"Cache·분기 예측·out-of-order execution의 일반 원리는 재사용합니다. 이 글은 secret→observable→measurement→inference의 leakage model과 TEE release 검증만 소유합니다.",
    firstId:"leakage-model",firstTitle:"Secret에서 관측값까지 네 단계를 끊어 본다",secondId:"spectre-cache",secondTitle:"Cache contention과 transient execution은 같은 공격이 아니지만 같은 관측 경계를 공유한다",releaseId:"mitigation-release",
    stages:[["SECRET","Secret-dependent operation","Branch·lookup index·loop count가 key·token·private input에 따라 달라집니다."],["STATE","Shared microarchitecture","Cache set·predictor·TLB·execution port·page fault 같은 host-observable state가 달라집니다."],["MEASURE","Noisy samples","Prime+Probe·Flush+Reload·timing 같은 방법으로 반복 관측하고 noise를 기록합니다."],["INFER","Candidate ranking","관측 분포를 후보별 model과 비교합니다. 정확도·sample 수·false positive를 함께 봅니다."]],
    details:[["Cache attack","Victim access ↔ cache set","Shared line·set contention을 시간으로 추정하며 memory encryption이 cache occupancy를 숨기지는 않습니다."],["Spectre","Mistrained prediction ↔ transient access","Architecturally commit되지 않은 access도 cache 같은 covert channel에 흔적을 남길 수 있습니다."],["Constant-time","Secret-independent control/address","Source 모양이 아니라 compiler output·target CPU·input distribution에서 관측 차이를 검증합니다."],["Isolation / partition","Reduce sharing","Core pinning·cache partition·SMT disable은 공격면을 줄일 수 있지만 threat model·비용을 측정해야 합니다."]],
    failures:[["Secret-indexed lookup fixture","Welch test/MI threshold 초과 시 release 중단"],["Compiler update reintroduces branch","Binary diff와 timing corpus에서 regression"],["SMT noisy neighbor","Leakage·p99 변화와 availability cost 함께 기록"],["Mitigation passes one CPU only","다른 microcode/model은 unsupported, fail closed"]],
    question:"관측값이 secret과 무관하다는 주장을 어떻게 검사하는가?",idea:"두 secret class의 timing 평균 차이를 pooled uncertainty로 나눠 반복 측정의 noise와 비교합니다.",formula:String.raw`t=\frac{\bar{x}_0-\bar{x}_1}{\sqrt{s_0^2/n_0+s_1^2/n_1}}`,
    annotatedFormula: String.raw`t=\underbrace{\frac{\bar{x}_0-\bar{x}_1}{\sqrt{s_0^2/n_0+s_1^2/n_1}}}_{\text{기준량당 비율}}`,
    operations: [
      { expression: String.raw`\frac{\bar{x}_0-\bar{x}_1}{\sqrt{s_0^2/n_0+s_1^2/n_1}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","두 secret class의 timing 평균 차이를","pooled uncertainty로 나눠 반복 측정의","noise와 비교합니다."] },
    ],
    terms:[{symbol:String.raw`\bar{x}_i`,name:"Class mean",description:"Secret class i에서 측정한 timing 또는 counter의 평균입니다."},{symbol:"s_i^2",name:"Class variance",description:"환경 noise를 포함한 class i sample variance입니다."},{symbol:"n_i",name:"Sample count",description:"Class i에서 수집한 독립에 가까운 반복 수입니다."},{symbol:"t",name:"Welch statistic",description:"두 평균 차이를 추정 불확실성으로 정규화한 탐지 신호입니다."}],
    assumptions:["표본 수·clock·core·frequency·input distribution·binary·microcode를 receipt에 기록합니다.","큰 |t|는 누출 후보 신호이지 secret 복구 성공이나 원인을 단독 증명하지 않습니다.","Timing test 하나로 cache·power·EM·controlled-channel 전체를 배제하지 않습니다."],interpretation:"평균 차이가 작아도 표본이 많고 분산이 작으면 재현 가능한 신호일 수 있습니다. 임계값을 정한 corpus와 별도 holdout에서 확인합니다.",
    citations:[{id:"paper-spectre",title:"Spectre Attacks",href:"https://arxiv.org/abs/1801.01203",problem:"Speculative execution이 architectural isolation을 우회해 정보를 전달할 수 있습니다.",contribution:"Mistraining과 transient access·cache covert channel의 실증 공격을 제시합니다.",assumptions:"공격 gadget·CPU·timer·cache sharing 조건을 고정합니다.",scope:"논문에서 실증한 Spectre class와 stated mitigations입니다.",notClaim:"모든 CPU·TEE가 같은 gadget으로 취약하거나 한 mitigation이 모든 variant를 막는다는 뜻이 아닙니다."},{id:"paper-cache-aes",title:"Cache Attacks and Countermeasures: the Case of AES",href:"https://eprint.iacr.org/2005/271",problem:"Secret-dependent table access가 cache timing으로 드러납니다.",contribution:"AES cache attack과 관측·countermeasure 분석을 제시합니다.",assumptions:"해당 table implementation·cache architecture·measurement capability를 전제로 합니다.",scope:"논문의 software cache attack model과 실험입니다.",notClaim:"AES 자체의 수학적 안전성이 깨졌거나 모든 구현이 같은 정도로 누출된다는 뜻이 아닙니다."},{id:"paper-intel-timing-guidance",title:"Intel timing side-channel guidance",href:"https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/secure-coding/mitigate-timing-side-channel-crypto-implementation.html",problem:"Crypto 구현의 secret-dependent timing을 줄여야 합니다.",contribution:"Timing channel 종류와 constant-time coding·verification guidance를 정리합니다.",assumptions:"현재 CPU·compiler·microcode와 linked guidance revision을 고정합니다.",scope:"Intel의 secure coding guidance입니다.",notClaim:"지침 준수가 모든 side channel 제거 또는 특정 binary의 constant-time을 인증하지 않습니다."}]
  },
  "isms-encryption": {
    key:"isms-encryption",eyebrow:"조직 암호화 · 데이터와 키의 수명주기",title:"ISMS 암호화는 AES를 고르는 일이 아니라 데이터·비밀번호·키의 서로 다른 수명주기를 운영하는 일이다",
    lead:"급여 계좌번호와 로그인 비밀번호를 저장하고 백업에서 복구하는 한 흐름을 따라갑니다. 계좌번호는 업무상 다시 읽어야 하므로 encryption 대상이고, 비밀번호는 원문 복원이 필요 없으므로 password hashing 대상입니다. 둘을 같은 ‘암호화’ 상자에 넣으면 접근 통제와 사고 대응이 무너집니다.",boundary:"AES·AEAD·TLS·hash의 수학 원리는 재사용합니다. 이 글은 데이터 분류→보호 primitive 선택→KMS/HSM key lifecycle→rotation·backup·revocation·audit를 ISMS 운영 증거로 묶는 부분을 소유합니다.",
    firstId:"data-password-boundary",firstTitle:"복원이 필요한 데이터와 검증만 필요한 비밀번호를 먼저 나눈다",secondId:"key-lifecycle",secondTitle:"Key를 생성할 때부터 폐기·복구까지 owner와 receipt를 둔다",releaseId:"release-gate",
    stages:[["CLASSIFY","Data inventory","목적·민감도·보존기간·접근자·복원 필요 여부를 기록합니다."],["PROTECT","Primitive selection","복원 데이터는 AEAD/TLS, 비밀번호는 salt가 있는 memory-hard password hash를 사용합니다."],["CUSTODY","KMS / HSM envelope","Data key와 wrapping key를 분리하고 purpose·tenant·version·권한을 결속합니다."],["OPERATE","Rotate·backup·revoke·destroy","Read-old/write-new 전환, 복구 훈련, compromise revoke와 audit evidence를 수명주기로 관리합니다."]],
    details:[["Reversible sensitive data","AEAD + access policy","Ciphertext·nonce·tag·key ID·schema를 저장하고 복호화 호출을 별도 authorize/audit합니다."],["Passwords","Argon2id 등 password hash","계정별 salt·parameter·algorithm/version을 저장하고 login 때 재계산해 비교합니다."],["Transport","TLS endpoint identity","TLS는 이동 구간을 보호하지만 endpoint에서의 과도한 권한·log·backup 평문을 막지 않습니다."],["Key hierarchy","DEK ↔ KEK/KMS","Data 대량 재암호화와 wrapping-key rotation을 구분하고 blast radius를 줄입니다."]],
    failures:[["DB dump + hash dump","Plaintext 0, offline guess 비용과 breached-password policy 측정"],["App role steals KMS decrypt","Least privilege/approval 실패로 decrypt 0"],["Rotation 중 partial failure","Old-read/new-write dual window와 version receipt로 재개"],["Backup key unavailable or revoked","복구 훈련 실패, release 중단"]],
    question:"Envelope encryption에서 실제로 다시 암호화해야 하는 범위를 어떻게 나누는가?",idea:"Data는 DEK로 암호화하고 작은 DEK만 KMS의 KEK로 감싸면, wrapping-key 교체와 data-key 교체의 비용·위험을 분리할 수 있습니다.",formula:String.raw`\begin{aligned}C&=\operatorname{AEAD}_{K_D}(M,A)\\W&=\operatorname{Wrap}_{K_E}(K_D)\end{aligned}`,
    annotatedFormula: String.raw`\begin{aligned}C&=\underbrace{\operatorname{AEAD}_{K_D}(M,A)}_{\text{Data-encryption key 계산}}\\W&=\underbrace{\operatorname{Wrap}_{K_E}(K_D)}_{\text{Data-encryption key 계산}}\end{aligned}`,
    operations: [
      { expression: String.raw`\operatorname{AEAD}_{K_D}(M,A)`, annotation: ["Data-encryption key이(가) 식의 결과에","기여하는 방식을 계산합니다.","Data는 DEK로 암호화하고 작은 DEK만 KMS의 KEK로","감싸면, wrapping-key 교체와 data-key 교체의"] },
      { expression: String.raw`\operatorname{Wrap}_{K_E}(K_D)`, annotation: ["Data-encryption key이(가) 식의 결과에","기여하는 방식을 계산합니다.","Data는 DEK로 암호화하고 작은 DEK만 KMS의 KEK로","감싸면, wrapping-key 교체와 data-key 교체의"] },
    ],
    terms:[{symbol:"M",name:"Plaintext data",description:"복원이 필요한 계좌번호 같은 업무 데이터입니다."},{symbol:"A",name:"Authenticated metadata",description:"Tenant·record·purpose·schema처럼 바꿔 끼우면 안 되는 context입니다."},{symbol:"K_D",name:"Data-encryption key",description:"한 dataset·tenant·generation의 data를 암호화하는 DEK입니다."},{symbol:"K_E",name:"Key-encryption key",description:"KMS/HSM이 보호하며 DEK를 감싸는 KEK입니다."},{symbol:"C",name:"Ciphertext envelope",description:"Nonce·ciphertext·tag·key ID와 함께 저장하는 data envelope입니다."},{symbol:"W",name:"Wrapped DEK",description:"KEK 접근 정책 아래 보관하는 작은 key artifact입니다."}],
    assumptions:["AEAD nonce uniqueness·algorithm/key version·authenticated metadata를 기록합니다.","KMS authorize와 application business authorize를 모두 통과해야 decrypt합니다.","Password는 W나 C로 저장하지 않고 별도의 password-hash 정책을 사용합니다."],interpretation:"KEK만 교체할 때는 검증한 DEK를 새 KEK로 rewrap할 수 있습니다. DEK compromise나 crypto policy 변경이면 data ciphertext까지 계획적으로 다시 암호화합니다.",
    citations:[{id:"paper-nist-key-management",title:"NIST SP 800-57 Part 1 Rev. 5",href:"https://csrc.nist.gov/pubs/sp/800/57/pt1/r5/final",problem:"암호키를 생성부터 폐기까지 일관되게 관리해야 합니다.",contribution:"Key lifecycle·cryptoperiod·protection·backup/recovery·compromise 원칙을 정리합니다.",assumptions:"조직 규제·algorithm profile·system threat model을 별도 적용합니다.",scope:"일반 cryptographic key-management 지침입니다.",notClaim:"특정 KMS 제품·법적 준수·application authorization을 자동 보장하지 않습니다."},{id:"paper-owasp-password-storage",title:"OWASP Password Storage Cheat Sheet",href:"https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",problem:"Password DB 유출 뒤 offline guessing 비용을 높여야 합니다.",contribution:"현재 password-hash algorithm·salt·work factor·pepper·upgrade guidance를 제공합니다.",assumptions:"검증 시점의 guidance와 service latency·hardware를 기준으로 parameter를 측정합니다.",scope:"Password 저장과 hash parameter 운영 지침입니다.",notClaim:"추천 algorithm이 약한 password·credential stuffing·pepper custody를 모두 해결하지 않습니다."},{id:"paper-owasp-crypto-storage",title:"OWASP Cryptographic Storage Cheat Sheet",href:"https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html",problem:"데이터별 threat와 보호 위치에 맞는 암호화 경계를 골라야 합니다.",contribution:"Data minimization·at-rest layer·algorithm·key storage와 password 비가역 저장 경계를 설명합니다.",assumptions:"법령·platform·data classification·현재 algorithm guidance를 함께 확인합니다.",scope:"Application cryptographic storage의 일반 설계 지침입니다.",notClaim:"FDE·DB crypto·TLS 하나가 endpoint authorization·backup·log를 모두 보호하지 않습니다."}]
  }
};

function ReleaseViz({ config }: { config: Config }) {
  return <figure data-viz={`${config.key}-release-map`} data-viz-canvas className="not-prose my-8 min-w-0 overflow-hidden rounded-xl border border-border/70 bg-card">
    <figcaption className="border-b border-border/70 p-4 sm:p-5"><p className="text-sm font-semibold">{config.eyebrow}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">각 칸은 같은 보안 상자가 아니라 서로 다른 입력·판정·owner를 가진 단계입니다.</p></figcaption>
    <div className="grid gap-px bg-border/70 sm:grid-cols-2 lg:grid-cols-4">{config.stages.map(([tag,title,body],index)=><div key={tag} className="min-w-0 bg-background p-4 sm:p-5"><div className="flex items-center gap-2"><span className="text-[11px] font-bold text-primary">{String(index+1).padStart(2,"0")}</span><span className="text-[11px] font-bold tracking-[.1em] text-muted-foreground">{tag}</span></div><p className="mt-3 break-keep text-sm font-semibold">{title}</p><p className="mt-2 break-words text-xs leading-5 text-muted-foreground">{body}</p></div>)}</div>
  </figure>;
}

function Evidence({ item, index }: { item: Citation; index: number }) { return <div><span id={item.id}/><CitationBlock source={item.title} citeKey={index+1} href={item.href}><p><strong>문제:</strong> {item.problem}</p><p><strong>기여:</strong> {item.contribution}</p><p><strong>전제:</strong> {item.assumptions}</p><p><strong>근거 범위:</strong> {item.scope}</p><p><strong>하지 않는 주장:</strong> {item.notClaim}</p></CitationBlock></div>; }

export default function SecurityReleaseArticle({ article }: { article: ArticleKey }) {
  const c=CONFIG[article];
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">{c.eyebrow}</p><h2 className="text-3xl font-bold tracking-tight">{c.title}</h2></header><p className="text-lg leading-8 text-foreground/90">{c.lead}</p><aside className="rounded-lg border border-border p-4 text-sm leading-6">{c.boundary}</aside><ReleaseViz config={c}/><ContentBoundary article={c.key}/></section>
    <section id={c.firstId} className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · 경계부터</p><h2 className="mt-2 text-2xl font-bold">{c.firstTitle}</h2></header><div className="grid gap-3 md:grid-cols-2">{c.details.map(([tag,title,body])=><div key={tag} className="min-w-0 rounded-lg border border-border p-4"><p className="text-xs font-bold tracking-[.08em] text-primary">{tag}</p><p className="mt-2 font-semibold">{title}</p><p className="mt-2 break-words text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div></section>
    <section id={c.secondId} className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · 계산과 증거</p><h2 className="mt-2 text-2xl font-bold">{c.secondTitle}</h2></header><ExplainedFormula question={c.question} idea={c.idea} formula={c.formula} annotatedFormula={c.annotatedFormula} operations={c.operations} terms={c.terms} assumptions={c.assumptions} interpretation={c.interpretation}/>{c.citations.map((item,index)=><Evidence key={item.id} item={item} index={index}/>)}</section>
    <section id={c.releaseId} className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · 실패와 release gate</p><h2 className="mt-2 text-2xl font-bold">정상 demo가 아니라 오래된 증거·변조·중간 crash를 재생한다</h2></header><div className="overflow-hidden rounded-lg border border-border"><div className="grid grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] bg-muted/40 px-4 py-3 text-xs font-semibold"><span>실패 주입</span><span>기대 oracle</span></div>{c.failures.map(([fault,oracle])=><div key={fault} className="grid grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] gap-3 border-t border-border px-4 py-3 text-sm"><span className="font-medium">{fault}</span><span className="text-muted-foreground">{oracle}</span></div>)}</div><p className="leading-7">Base와 candidate에 같은 input corpus·policy·clock·platform/runtime·external stub을 사용합니다. Unauthorized decrypt/release와 plaintext leak을 0으로 두고 reason code·artifact digest·recovery time·p50/p99를 비교합니다. 실패하면 이전 binary·policy·key generation·data snapshot으로 돌아가며, 이미 발생한 외부 effect는 별도 receipt로 reconcile합니다.</p></section>
  </article>;
}
