import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { GossipPathViz, ScoreViz } from "./viz/ModernGossipsubViz";

export default function ModernGossipsubArticle() { return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">rust-libp2p 0.56.0 구현 읽기</p><h2 className="text-3xl font-bold tracking-tight">GossipSub은 payroll 파일이 아니라 “이 CID가 있다”는 작은 소식을 퍼뜨린다</h2></header><p className="text-lg leading-8">Alice가 <code>payroll-report-v1</code>의 CID와 version, 서명을 announcement로 publish한다고 하겠습니다. Mesh peer에는 full announcement가 전달되고, 나머지 peer에는 heartbeat 때 IHAVE metadata가 전달되어 필요한 peer가 IWANT로 요청합니다. Bob이 실제 파일을 받는 일은 Bitswap이나 별도 QUIC stream이 맡고 CID를 다시 검증합니다.</p><p>이 이중 경로의 일반 원리는 <a className="text-primary hover:underline" href="/p2p/gossip-fundamentals#gossipsub">GossipSub 정본</a>을 재사용합니다. 이 글은 rust-libp2p의 publish cache, heartbeat, validation과 peer score 상태를 소유합니다. Message ID dedup은 같은 announcement를 덜 처리하게 할 뿐 content integrity나 exactly-once delivery를 증명하지 않습니다.</p><GossipPathViz/></section>

  <section id="publish-heartbeat" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · publish와 heartbeat</p><h2 className="mt-2 text-2xl font-bold">publish 성공은 local cache와 전송 대상 선택까지의 receipt다</h2></header><p><code>publish</code>는 message transform과 size를 확인하고 message ID를 계산해 duplicate cache에 기록한 뒤 mesh·direct·fanout peer로 전송합니다. 대상이 없거나 configured rule을 만족하지 못하면 error가 날 수 있습니다. 성공했어도 모든 subscriber가 처리했다는 ack는 아닙니다.</p><p>Heartbeat는 mesh의 부족·과잉 peer를 GRAFT/PRUNE으로 조정하고 fanout 만료, message cache shift와 gossip promise를 처리합니다. IHAVE를 받은 peer가 IWANT를 보냈는데 message가 오지 않으면 promise failure가 score에 반영될 수 있습니다. Retry는 bounded request와 cache retention 안에서만 가능하므로 durable queue가 필요하면 application 계층에 별도로 둡니다.</p><div id="paper-rust-gossipsub-behaviour-056"><CitationBlock source="rust-libp2p 0.56.0 — gossipsub behaviour.rs · mcache.rs" citeKey={1} type="code" href="https://github.com/libp2p/rust-libp2p/tree/libp2p-v0.56.0/protocols/gossipsub/src"><p><strong>문제:</strong> bounded local state로 publish, duplicate suppression과 mesh/gossip 전파를 수행합니다.</p><p><strong>기여:</strong> message transform·ID·cache, publish peer selection과 heartbeat maintenance의 pinned 구현을 제공합니다.</p><p><strong>전제:</strong> rust-libp2p 0.56.0 gossipsub Behaviour와 configured heartbeat/cache parameters를 사용합니다.</p><p><strong>근거 범위:</strong> 한 node의 publish admission, cache lifecycle과 control-message generation입니다.</p><p><strong>말하지 않는 것:</strong> 모든 subscriber 수신, durable delivery, CID payload availability를 보장하지 않습니다.</p></CitationBlock></div></section>

  <section id="peer-scoring" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · peer score</p><h2 className="mt-2 text-2xl font-bold">Peer score는 local 관측의 가중합이며 global reputation이 아니다</h2></header><p>Topic별 delivery·mesh behavior, application score, IP colocation과 behavior penalty를 가중합하고 topic contribution에는 cap을 둘 수 있습니다. 점수는 decay하며 publish·gossip·graylist threshold에 따라 local action이 달라집니다. 다른 node는 다른 관측과 설정으로 같은 peer에 다른 점수를 줄 수 있습니다.</p><ScoreViz/><ExplainedFormula question="여러 topic과 penalty를 한 peer score로 어떻게 합칠까?" idea={<>Topic별 contribution의 weighted sum을 cap으로 제한한 뒤 application score와 IP·behavior 항을 더합니다. 계산 결과는 configured threshold와 비교해 local forwarding action을 정합니다.</>} formula={String.raw`S(p)=\min\!\left(\sum_t w_tP_t(p),C_{topic}\right)+w_aP_a(p)+w_iP_i(p)+w_bP_b(p)`}
  annotatedFormula={String.raw`S(p)=\underbrace{\min\!\left(\sum_t w_tP_t(p),C_{topic}\right)+w_aP_a(p)+w_iP_i(p)+w_bP_b(p)}_{\text{경계 후보 선택}}`}
  operations={[
    { expression: String.raw`\min\!\left(\sum_t w_tP_t(p),C_{topic}\right)+w_aP_a(p)+w_iP_i(p)+w_bP_b(p)`, annotation: ["허용 후보 중 목적에 맞는 경계값을 선택합니다.","Topic별 contribution의 weighted sum을","cap으로 제한한 뒤 application score와","IP·behavior 항을 더합니다."] },
  ]} terms={[{symbol:"P_t",name:"topic evidence",description:"mesh time, first delivery, invalid delivery 등 topic별 local 관측 항입니다."},{symbol:"C_{topic}",name:"topic cap",description:"많은 topic의 양수 contribution이 전체 score를 독점하지 않게 하는 상한입니다."},{symbol:"P_a",name:"application score",description:"application이 별도 정책으로 공급하는 local 항입니다."},{symbol:"P_i,P_b",name:"penalties",description:"IP colocation과 behavior 관측에 대한 configured penalty 항입니다."}]} assumptions={["Weight, cap, decay와 action threshold를 같은 deployment configuration으로 고정합니다.","Score evidence는 local observation이며 Sybil-resistant global identity가 아닙니다.","예시 12→10,+2,−3,−1은 계산 설명용이며 default를 주장하지 않습니다.","Network topology가 바뀌면 false positive와 partition 위험을 다시 측정합니다."]} interpretation="Topic 합 12를 cap 10으로 제한하고 app +2, IP −3, behavior −1을 더하면 score는 8입니다. 그러나 8 자체의 의미는 없습니다. 실제 publish·gossip·graylist threshold와 비교해야 action이 정해집니다."/><div id="paper-rust-gossipsub-score-056"><CitationBlock source="rust-libp2p 0.56.0 — peer_score.rs · peer_score/params.rs" citeKey={2} type="code" href="https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.56.0/protocols/gossipsub/src/peer_score.rs"><p><strong>문제:</strong> spam·under-delivery peer의 영향은 줄이면서 useful peers와 mesh를 유지합니다.</p><p><strong>기여:</strong> topic cap, application/IP/behavior 항, decay와 threshold input의 local score state를 구현합니다.</p><p><strong>전제:</strong> 운영자가 topology와 threat model에 맞는 parameters를 검증해 제공합니다.</p><p><strong>근거 범위:</strong> node-local peer observation을 수치화하는 state transition입니다.</p><p><strong>말하지 않는 것:</strong> 보편적으로 안전한 weight, peer의 실제 신원, Byzantine consensus를 제공하지 않습니다.</p></CitationBlock></div></section>

  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · validation과 release</p><h2 className="mt-2 text-2xl font-bold">Accept·Reject·Ignore를 고른 뒤 forwarding과 rollback 한계를 기록한다</h2></header><p>Application validation을 켜면 message를 받은 뒤 accept, reject 또는 ignore를 보고할 수 있습니다. Payroll announcement라면 schema, signature, allowed topic, timestamp와 CID 형식을 검사한 뒤 accept해야 합니다. Reject는 invalid delivery penalty에 영향을 줄 수 있고, ignore는 peer를 처벌하지 않고 forwarding하지 않는 용도로 구분합니다.</p><p>검증 전에 forwarded된 message는 network 전체에서 되돌릴 수 없습니다. 그래서 strict validation에서는 publish/receive timeout을 두고, rejected message는 local application state에 반영하지 않습니다. Release test는 duplicate ID, delayed validation, invalid signature, IHAVE 뒤 missing IWANT response, score decay와 mesh churn을 포함하며 queue·cache size와 reject reason을 receipt로 남깁니다.</p><div id="paper-rust-gossipsub-config-056"><CitationBlock source="rust-libp2p 0.56.0 — config.rs · gossip_promises.rs" citeKey={3} type="code" href="https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.56.0/protocols/gossipsub/src/config.rs"><p><strong>문제:</strong> validation, heartbeat, message cache와 gossip retry의 시간·용량 경계를 구성합니다.</p><p><strong>기여:</strong> validation mode와 bounded gossip-promise lifecycle에 필요한 configuration surface를 제공합니다.</p><p><strong>전제:</strong> application이 정해진 시간 안에 validation result를 Behaviour에 보고합니다.</p><p><strong>근거 범위:</strong> local forwarding gate, retry bookkeeping과 configuration validation입니다.</p><p><strong>말하지 않는 것:</strong> 이미 전달된 message의 global rollback이나 exactly-once processing을 보장하지 않습니다.</p></CitationBlock></div><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 CID announcement, mesh full-message, IHAVE/IWANT, message ID, heartbeat와 validation 결과를 확인합니다. 심화 4문제는 score 계산, promise failure retry, delayed validation 반례와 partition을 피하는 release test를 설계하게 합니다.</p></section>
</article>; }
