import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
const states=[
 {label:"처음",point:"P = (5,4)",value:"1",op:"맨 앞 1에서 시작",note:"5=101의 맨 앞 1은 처음 점과 누적값 1로 표현합니다."},
 {label:"두 배",point:"2P = (9,15)",value:"3 + 16u",op:"1² × (3 + 16u)",note:"다음 비트 0을 읽습니다. 점을 두 배 하고 누적값도 제곱한 뒤 선의 비를 곱합니다."},
 {label:"다시 두 배",point:"4P = (5,15)",value:"8 + 10u",op:"(3 + 16u)² × (10 + 11u)",note:"마지막 비트를 읽기 전에 먼저 두 배 합니다. 이전 누적값의 제곱은 u입니다."},
 {label:"P 더하기",point:"5P = O",value:"15 + 14u",op:"(8 + 10u) × 9",note:"마지막 비트 1에 맞춰 P를 더합니다. 점은 O가 되고 누적값은 0 아닌 15+14u입니다."},
];
export default function PairingTraceViz(){const scene=useAnimatedScenes(states.length,4500);const s=states[scene.active];return <figure data-viz="pairing-trace" className="my-8 border-y border-border py-4"><figcaption className="mb-3 text-sm leading-6">같은 P와 Q에서 점 R과 누적값 f를 함께 따라갑니다. 계수는 19로 나누며 u²=−1입니다.</figcaption><div data-viz-canvas tabIndex={0} role="group" aria-label="페어링의 네 계산 장면" onKeyDown={scene.onKeyDown} className="flex h-[min(530px,calc(100dvh-150px))] flex-col outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><div className="min-h-0 flex-1 overflow-y-auto px-1 py-3"><div className="grid gap-4 sm:grid-cols-2"><div className="border-b border-border pb-3"><h3 className="text-sm">현재 점 R</h3><p className="my-3 text-xl font-semibold">{s.point}</p></div><div className="border-b border-border pb-3"><h3 className="text-sm">누적값 f</h3><p className="my-3 text-xl font-semibold">{s.value}</p></div></div><p className="my-5 break-words text-base font-semibold">{s.op}</p><p className="text-sm leading-7">{s.note}</p><p className="mt-5 border-t border-border pt-3 text-sm leading-6">마지막 누적값의 72승은 7+3u입니다. 이 마지막 계산은 점 더하기와 다른 단계입니다.</p></div><AnimatedSceneControls {...scene} labels={states.map(x=>x.label)}/></div></figure>}
