import type { CodeRef, FileNode, ProjectMeta } from "@/components/code/types";
import paillier from "./codebase/phe/paillier.py?raw";
import encoding from "./codebase/phe/encoding.py?raw";
import trace from "./verification/trace.py?raw";
export const codeRefs:Record<string,CodeRef>={
"public":{code:paillier,"path": "phe/paillier.py", "highlight": [86, 142], "lang": "python", "desc": "공개키에 n=15, g=16, nsquare=225를 저장합니다. 1+15×4=61에 난수 성분 143을 곱해 173을 만듭니다.", "annotations": [{"lines": [86, 142], "color": "sky", "note": "공개키에 n=15, g=16, nsquare=225를 저장합니다. 1+15×4=61에 난수 성분 143을 곱해 173을 만듭니다."}]},
"encoded":{code:paillier,"path": "phe/paillier.py", "highlight": [167, 193], "lang": "python", "desc": "정수와 실수를 먼저 인코딩하고 필요할 때 재무작위화합니다. 직접 지정한 난수와 기본 getter 경로를 구분합니다.", "annotations": [{"lines": [167, 193], "color": "sky", "note": "정수와 실수를 먼저 인코딩하고 필요할 때 재무작위화합니다. 직접 지정한 난수와 기본 getter 경로를 구분합니다."}]},
"private":{code:paillier,"path": "phe/paillier.py", "highlight": [217, 235], "lang": "python", "desc": "p=3, q=5에서 hp=1, hq=3과 p의 mod q 역원 2를 준비합니다. 이 생성자의 검사와 전체 키 설정 검증을 구분합니다.", "annotations": [{"lines": [217, 235], "color": "sky", "note": "p=3, q=5에서 hp=1, hq=3과 p의 mod q 역원 2를 준비합니다. 이 생성자의 검사와 전체 키 설정 검증을 구분합니다."}]},
"decrypt":{code:paillier,"path": "phe/paillier.py", "highlight": [328, 376], "lang": "python", "desc": "92를 p²과 q²에서 나눠 복호해 나머지 1과 2를 얻고 CRT로 7을 합칩니다.", "annotations": [{"lines": [328, 376], "color": "sky", "note": "92를 p²과 q²에서 나눠 복호해 나머지 1과 2를 얻고 CRT로 7을 합칩니다."}]},
"add":{code:paillier,"path": "phe/paillier.py", "highlight": [678, 721], "lang": "python", "desc": "같은 키와 지수로 맞춘 뒤 암호문 173과 154를 곱합니다. 평문의 합이 7인 암호문 92가 됩니다.", "annotations": [{"lines": [678, 721], "color": "sky", "note": "같은 키와 지수로 맞춘 뒤 암호문 173과 154를 곱합니다. 평문의 합이 7인 암호문 92가 됩니다."}]},
"obfuscate":{code:paillier,"path": "phe/paillier.py", "highlight": [531, 573], "lang": "python", "desc": "기본 ciphertext()는 필요하면 obfuscate를 부릅니다. 실제 새 난수 곱은 603–628행에 있습니다.", "annotations": [{"lines": [531, 573], "color": "sky", "note": "기본 ciphertext()는 필요하면 obfuscate를 부릅니다. 실제 새 난수 곱은 603–628행에 있습니다."}]},
"encode":{code:encoding,"path": "phe/encoding.py", "highlight": [180, 199], "lang": "python", "desc": "정수 계수의 범위를 검사한 뒤 음수를 mod n으로 바꿉니다. 지수는 별도 공개 정보로 남습니다.", "annotations": [{"lines": [180, 199], "color": "sky", "note": "정수 계수의 범위를 검사한 뒤 음수를 mod n으로 바꿉니다. 지수는 별도 공개 정보로 남습니다."}]},
"decode":{code:encoding,"path": "phe/encoding.py", "highlight": [201, 237], "lang": "python", "desc": "n=15의 max_int=4에서 나머지 7은 중간 구간이라 넘침 오류가 납니다. 나머지 1로 감긴 정수 16은 여기서 구별하지 못합니다.", "annotations": [{"lines": [201, 237], "color": "sky", "note": "n=15의 max_int=4에서 나머지 7은 중간 구간이라 넘침 오류가 납니다. 나머지 1로 감긴 정수 16은 여기서 구별하지 못합니다."}]},
"run":{code:trace,"path": "case/trace.py", "highlight": [67, 85], "lang": "python", "desc": "같은 4와 3을 실제 원문 API에 넣고 합산·raw 복호·signed 오류 및 재무작위화를 확인합니다.", "annotations": [{"lines": [67, 85], "color": "sky", "note": "같은 4와 3을 실제 원문 API에 넣고 합산·raw 복호·signed 오류 및 재무작위화를 확인합니다."}]},
"checks":{code:trace,"path": "case/trace.py", "highlight": [26, 47], "lang": "python", "desc": "원문 raw API 바깥의 별도 입력 검사입니다. 정상 키가 이미 정해졌다는 조건에서 정규 범위와 unit 여부를 검사합니다.", "annotations": [{"lines": [26, 47], "color": "sky", "note": "원문 raw API 바깥의 별도 입력 검사입니다. 정상 키가 이미 정해졌다는 조건에서 정규 범위와 unit 여부를 검사합니다."}]},
};
export const fileTrees:Record<string,FileNode>={"phe": {"name": "phe 1.5.0 고정 원문", "type": "dir", "children": [{"name": "paillier.py", "type": "file", "path": "phe/paillier.py", "codeKey": "public"}, {"name": "encoding.py", "type": "file", "path": "phe/encoding.py", "codeKey": "encode"}]}, "case": {"name": "별도 호출과 독립 정수 검산", "type": "dir", "children": [{"name": "trace.py", "type": "file", "path": "case/trace.py", "codeKey": "run"}]}};
export const projectMetas:Record<string,ProjectMeta>={"phe": {"id": "phe", "label": "phe 1.5.0 고정 원문", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}, "case": {"id": "case", "label": "별도 호출과 독립 정수 검산", "badgeClass": "bg-emerald-50 border-emerald-300 text-emerald-800"}};
