import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import ReviewPrompts from "@/pages/articles/world-systems/ReviewPrompts";
import PaillierJourneyViz from "./viz/PaillierJourneyViz";
import { codeRefs, fileTrees, projectMetas } from "./codeRefs";
export default function ModernArticle(){const sidebar=useCodeSidebar();return <div className="space-y-16 [overflow-wrap:anywhere]">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 개별 수를 열어 보지 않고 4와 3을 합칩니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">두 부서가 이번 주 처리한 건수 4와 3을 집계 서버에 보냅니다. 서버에는 각 숫자를 그대로 주지 않고 암호화한 값만 보냅니다. 서버가 이 두 암호문을 곱하면 복호 담당자는 결과에서 합계 7을 얻을 수 있습니다. 이것이 Paillier의 덧셈 동형 성질입니다.</p>
<p className="leading-8">이 기능만으로 모든 사람에게 개별 값이 숨겨지는 것은 아닙니다. 비밀키를 가진 담당자가 개별 암호문도 받으면 각각 복호할 수 있습니다. 담당자의 접근을 제한하거나 키를 여러 사람에게 나누는 절차는 별도입니다.</p>
<p className="leading-8">먼저 같은 4와 3을 작은 수로 암호화하고 합산해 복호합니다. 그다음 실제 Python 원문에 같은 입력을 넣고, 수학식의 입력 조건과 API가 실제 검사하는 조건의 차이를 확인합니다. 작은 키와 고정 난수는 계산을 재현하기 위한 예입니다.</p>
</div></section>
<section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 서버는 곱하고 비밀키 담당자는 합을 읽습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">공개키는 누구나 사용할 수 있는 암호화 규칙입니다. 각 부서는 공개키와 새 난수로 건수를 암호화합니다. 집계 서버에는 이 암호문들이 들어오고, 서버는 정해진 나머지 연산 안에서 곱한 결과 하나를 돌려줍니다.</p>
<p className="leading-8">비밀키 담당자는 합산 암호문을 복호해 수를 읽습니다. 서버가 집계에 포함할 대상을 바꾸거나 값을 더했는지는 암호문만으로 확인되지 않습니다. 참여자 목록, 값의 허용 범위와 결과의 진위까지 확인하려면 별도 규칙이 필요합니다.</p>
</div></section>
<section id="case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 이번 두 숫자는 173과 154로 바뀝니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">작은 소수 3과 5를 곱해 n=15를 만듭니다. 원래 값은 0부터 14까지이고 암호문 계산은 n²=225로 나눈 나머지를 씁니다. 공개된 바탕값 g는 n+1=16입니다. 예를 들어 226은 이 계산에서 1과 같습니다.</p>
<p className="leading-8">첫 부서의 4에는 재현용 난수 2를 넣어 173을 얻습니다. 둘째 부서의 3에는 난수 4를 넣어 154를 얻습니다. 서버가 173×154를 225로 나눈 나머지는 92입니다. 이 92를 비밀키로 복호하면 7이 됩니다.</p>
<p className="leading-8">지금의 2와 4는 안전한 난수 생성기가 내놓은 관측값이라는 뜻이 아닙니다. 실제 암호화는 매번 독립적으로 뽑은 적절한 난수를 써야 합니다. 왜 그래야 하는지도 같은 숫자로 돌아와 확인합니다.</p>
</div></section>
<section id="picture" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 같은 두 건수가 지나가는 네 단계를 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">숫자 4와 3, 암호문 173과 154, 합산 암호문 92, 복호 결과 7의 순서입니다. 서버가 하는 곱셈과 복호한 뒤 보이는 덧셈이 서로 다른 단계에 있다는 점을 그림에서 확인하세요.</p>
</div><PaillierJourneyViz/></section>
<section id="why" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. n+1의 거듭제곱에는 숫자를 읽어 낼 자리가 남습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">g=n+1을 m번 곱해 펼치면 1+nm 뒤에 n² 이상의 배수를 가진 항들이 나옵니다. n²로 나눈 나머지만 남기면 이 뒤쪽 항들은 사라집니다. 그래서 g^m은 1+nm으로 줄어듭니다.</p>
<p className="leading-8">n=15,m=4에서는 16⁴ mod 225=61=1+15×4입니다. 이것만 보내면 누구나 1을 빼고 15로 나눠 4를 읽습니다. 따라서 매번 고른 난수 r의 n제곱을 곱해 이 자리를 가립니다.</p>
<p className="leading-8">복호에서는 비밀키로 정한 거듭제곱을 사용해 난수 성분을 없앱니다. 그러고 나면 다시 1+n×어떤 값의 형태가 남습니다. 1을 빼고 n으로 나누는 연산이 등장하는 이유입니다.</p>
</div><ExplainedFormula question="왜 공개 바탕값을 n+1로 고르면 계산이 줄어드나요?" idea="나머지 계산에서 n²을 포함한 항은 0입니다." formula={String.raw`\begin{gathered}(1+n)^m\equiv1+nm\pmod{n^2}\\m=4,\quad n=15\\16^4\bmod225=61\\61=1+15\cdot4\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}(1+n)^m\equiv1+nm\pmod{n^2}\\m=4,\quad n=15\\16^4\bmod225=61\\61=1+15\cdot4\end{gathered}`} operations={[{"expression": "(1+n)^m\\equiv1+nm\\pmod{n^2}", "annotation": ["이항 전개에서 n² 이상을 곱한 항이 모두 사라집니다."]}, {"expression": "61=1+15\\cdot4", "annotation": ["난수로 가리지 않은 값은 공개적으로 4를 드러냅니다."]}]} terms={[{"symbol": "n", "name": "평문 나머지의 크기", "description": "이번에는 15입니다."}, {"symbol": "n²", "name": "암호문 나머지의 크기", "description": "이번에는 225입니다."}, {"symbol": "m", "name": "암호화할 수", "description": "이번 예는 0부터 n−1까지입니다."}]} assumptions={["이 식은 g=n+1인 설정입니다.", "작은 n=15는 안전한 키가 아닙니다."]} interpretation="거듭제곱을 쉽게 계산하면서도 난수 성분을 별도로 곱할 수 있습니다."/></section>
<section id="names" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 평문·암호문·난수·동형성의 역할을 연결합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">암호화하기 전의 4와 3을 평문 m이라고 하고, 보낸 173과 154를 암호문 c라고 합니다. 공개키는 이번 설정에서 n과 g이며 비밀키에는 n을 나눈 소수 p,q 또는 복호에 필요한 비밀 지수와 계수가 들어갑니다.</p>
<p className="leading-8">난수 r은 0보다 크고 n보다 작으며 n과 서로소여야 합니다. 이런 원소는 mod n에서 곱셈 역원이 있어 unit이라고 부릅니다. n=15에서는 1,2,4,7,8,11,13,14가 해당합니다.</p>
<p className="leading-8">암호문끼리 하는 연산이 평문 연산으로 옮겨지는 성질이 동형성입니다. Paillier에서는 암호문의 곱이 평문의 합이 됩니다. 암호문 두 개로 두 평문의 일반적인 곱까지 구하는 완전동형암호는 아닙니다.</p>
</div></section>
<section id="key-generation" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. 비밀 지수 4와 되돌리는 계수 4를 만듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">서로 다른 소수 p=3,q=5에서 p−1=2,q−1=4입니다. 둘의 최소공배수 λ는 4입니다. λ는 n과 서로소이므로 λ에 곱해 mod n에서 1을 만드는 역원 μ가 있습니다. 여기서는 4×4=16≡1 mod 15여서 μ=4입니다.</p>
<p className="leading-8">일반적인 g를 쓰는 식에서는 L(g^λ mod n²)의 역원이 있어야 합니다. L(u)=(u−1)/n이며 입력은 u≡1 mod n인 형태여야 합니다. g=n+1을 선택한 이번 설정에서는 그 값이 λ mod n으로 단순해집니다.</p>
<p className="leading-8">따라서 이번 λ 복호식을 쓰기 전에 gcd(λ,n)=1을 확인합니다. 서로 다른 소수 두 개라는 말만으로 이 조건을 생략하지 않습니다. 19절에서 조건을 어긴 작은 키가 일부 코드 경로에서는 왕복 계산에 성공하는 반례도 보겠습니다.</p>
</div></section>
<section id="encryption" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 난수의 n제곱을 곱해 같은 4를 다르게 보냅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">첫 부서는 4에 대해 16⁴ mod225=61을 계산합니다. 난수 2의 성분은 2¹⁵ mod225=143입니다. 61×143 mod225=173이 첫 암호문입니다. 둘째 부서는 16³ mod225=46과 4¹⁵ mod225=199를 곱해 154를 얻습니다.</p>
<p className="leading-8">같은 4에 난수 7을 쓰면 암호문은 223으로 바뀝니다. 173과 223은 모두 4로 복호됩니다. 독립적인 새 난수는 같은 메시지의 암호문이 항상 같아지는 것을 피하게 하지만, 확률적으로 같은 난수가 다시 나올 가능성 자체가 0이 되는 것은 아닙니다.</p>
<p className="leading-8">난수 3은 15와 서로소가 아니므로 이번 암호화의 허용 입력이 아닙니다. 뒤에서 실제 라이브러리의 낮은 수준 API가 이런 입력을 받아도 안전하게 거부해 주는지 확인합니다.</p>
</div><ExplainedFormula question="같은 메시지를 어떻게 매번 다르게 가리나요?" idea="메시지 성분과 새로운 unit의 n제곱을 곱합니다." formula={String.raw`\begin{gathered}c=\operatorname{Enc}(m;r)\\=g^m r^n\bmod n^2\\g^4\bmod225=61\\2^{15}\bmod225=143\\61\cdot143\bmod225=173\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}c=\operatorname{Enc}(m;r)\\=g^m r^n\bmod n^2\\g^4\bmod225=61\\2^{15}\bmod225=143\\61\cdot143\bmod225=173\end{gathered}`} operations={[{"expression": "g^4\\bmod225=61", "annotation": ["첫 부서의 값 4가 들어간 공개 성분입니다."]}, {"expression": "2^{15}\\bmod225=143", "annotation": ["재현용 r=2가 만드는 난수 성분입니다."]}, {"expression": "61\\cdot143\\bmod225=173", "annotation": ["두 성분을 같은 modulus에서 곱합니다."]}]} terms={[{"symbol": "r", "name": "새로 고르는 unit 난수", "description": "실제 사용에서는 정한 분포에서 독립적으로 생성합니다."}, {"symbol": "c", "name": "암호문", "description": "0<c<n²인 unit입니다."}, {"symbol": "g", "name": "공개 바탕값", "description": "이번에는 n+1=16입니다."}]} assumptions={["0≤m<n이며 1≤r<n, gcd(r,n)=1입니다.", "고정한 난수는 이번 수치 재현에만 씁니다."]} interpretation="같은 4라도 r=7이면 223이 됩니다."/></section>
<section id="decryption" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 173에서 4를, 92에서 7을 꺼냅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">첫 암호문 173을 비밀 지수 4로 거듭제곱한 나머지는 16입니다. L(16)=(16−1)/15=1을 얻고 μ=4를 곱해 mod15로 줄이면 4입니다.</p>
<p className="leading-8">합산 암호문 92도 같은 순서입니다. 92⁴ mod225=196이므로 L(196)=13입니다. 13×4 mod15=7이 두 건수의 합입니다. L에서 쓰는 나눗셈은 정해진 형태에서 정확하게 나누는 정수 연산이며 임의 입력에 대한 바닥 나눗셈으로 대체하면 안 됩니다.</p>
</div><ExplainedFormula question="비밀키는 가려진 수를 어떻게 되돌리나요?" idea="난수 성분을 없앤 뒤 n의 계수를 읽고 비밀 배율을 되돌립니다." formula={String.raw`\begin{gathered}m=L(c^\lambda\bmod n^2)\mu\bmod n\\L(u)=(u-1)/n\\92^4\bmod225=196\\L(196)=13\\13\cdot4\bmod15=7\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}m=L(c^\lambda\bmod n^2)\mu\bmod n\\L(u)=(u-1)/n\\92^4\bmod225=196\\L(196)=13\\13\cdot4\bmod15=7\end{gathered}`} operations={[{"expression": "92^4\\bmod225=196", "annotation": ["정상 암호문에서 난수 성분이 없어집니다."]}, {"expression": "L(196)=13", "annotation": ["196=1+15×13에서 계수 13을 꺼냅니다."]}, {"expression": "13\\cdot4\\bmod15=7", "annotation": ["λ=4의 역원 μ=4를 곱해 원래 합의 나머지를 복원합니다."]}]} terms={[{"symbol": "λ", "name": "비밀 지수", "description": "lcm(p−1,q−1)입니다."}, {"symbol": "μ", "name": "복호 배율의 역원", "description": "일반식에서는 L(g^λ)의 mod n 역원입니다."}, {"symbol": "L", "name": "n의 계수를 꺼내는 함수", "description": "u≡1 mod n인 정상 입력에서 (u−1)/n을 계산합니다."}]} assumptions={["공개키 설정과 정상 unit 암호문을 가정합니다.", "이번 g=n+1 설정은 gcd(λ,n)=1을 만족합니다."]} interpretation="결과는 정수의 무한한 합이 아니라 mod n의 값입니다."/></section>
<section id="correctness" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 왜 난수만 없어지고 메시지는 남나요</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">r이 정상 unit이면 r^(nλ)≡1 mod n²입니다. p²에서는 지수 nλ가 p(p−1)의 배수이고 q²에서도 q(q−1)의 배수이므로 각각 1이며, 두 나머지를 합쳐 mod n²에서도 1입니다.</p>
<p className="leading-8">따라서 c^λ=(1+n)^(mλ)r^(nλ)≡1+nmλ mod n²입니다. L을 적용하면 mλ mod n이 나오고 μ=λ⁻¹을 곱하면 m입니다. 일반 g에서는 g^λ≡1+nt mod n²로 쓰면 (g^λ)^m≡1+nmt여서 L 값이 mt mod n입니다. t=L(g^λ)의 역원을 곱해 되돌리는 같은 구조입니다.</p>
<p className="leading-8">이것은 정상 입력의 복호가 맞다는 증명입니다. 비밀키 없이 메시지를 알아내기 어렵다는 보안 주장은 다른 문제입니다. 원논문의 Scheme 1은 합성 잉여류의 계산·판정 가정을 구분하며, 의미론적 보안은 판정 가정 DCRA와 연결합니다.</p>
</div><CitationBlock source="Paillier 1999 · Scheme 1과 정리 4·5" citeKey={1} href="https://www.cs.tau.ac.il/~fiat/crypt07/papers/Pai99pai.pdf"><p className="leading-8">저자의 논문 사본과 출판사 DOI의 제목을 대조하고 2–4절, 7절의 CRT 복호, 8절의 동형 항등식을 읽었습니다. 7쪽의 Scheme 1과 12쪽의 CRT 식도 실제 페이지로 확인했습니다.</p>
</CitationBlock></section>
<section id="homomorphism" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 암호문 173과 154의 곱이 평문 4와 3의 합을 만듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">두 암호문을 곱하면 g의 지수는 4+3=7로 더해지고 난수는 2×4=8로 곱해집니다. 같은 설정에서 Enc(7;8)=92입니다. 서버가 평문을 알지 않고 계산한 값과 정확히 같습니다.</p>
<p className="leading-8">이번 g=n+1은 g^n≡1 mod n²이므로 평문의 합을 mod n으로 줄여도 됩니다. 원래 값 13과 4를 합하면 17이 아니라 2로 복호됩니다. 정수 합을 원한다면 가능한 전체 합이 감기는 범위를 넘지 않도록 정해야 합니다.</p>
<p className="leading-8">일반 g를 쓰고 합이 n을 넘어가면 같은 난수곱을 그대로 쓰는 항등식에 주의해야 합니다. 합이 s+kn이면 g^(kn)=(g^k)^n이므로 난수곱에도 (g mod n)^k가 흡수됩니다. 이번 g=n+1은 g mod n=1이어서 그 추가 항이 사라집니다.</p>
<p className="leading-8">암호문 173을 공개된 정수 3제곱하면 17이 되고 복호 결과는 3×4 mod15=12입니다. 이는 알려진 스칼라와 평문을 곱하는 기능입니다. 암호화된 다른 값 3과의 일반 곱셈을 지원한다는 뜻은 아닙니다.</p>
</div><ExplainedFormula question="암호문의 곱이 왜 평문의 합으로 옮겨지나요?" idea="같은 바탕의 지수는 더해지고 난수 성분은 하나로 묶입니다." formula={String.raw`\begin{gathered}c_1c_2\equiv\\g^{m_1+m_2}(r_1r_2)^n\pmod{n^2}\\g=n+1\ \Longrightarrow\\\operatorname{Enc}(m_1;r_1)\operatorname{Enc}(m_2;r_2)\\\equiv\operatorname{Enc}(m_1+m_2\bmod n;\\r_1r_2\bmod n)\pmod{n^2}\\173\cdot154\bmod225=92\\\operatorname{Dec}(92)=7\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}c_1c_2\equiv\\g^{m_1+m_2}(r_1r_2)^n\pmod{n^2}\\g=n+1\ \Longrightarrow\\\operatorname{Enc}(m_1;r_1)\operatorname{Enc}(m_2;r_2)\\\equiv\operatorname{Enc}(m_1+m_2\bmod n;\\r_1r_2\bmod n)\pmod{n^2}\\173\cdot154\bmod225=92\\\operatorname{Dec}(92)=7\end{gathered}`} operations={[{"expression": "g^{m_1+m_2}", "annotation": ["평문들이 지수 안에서 더해집니다."]}, {"expression": "(r_1r_2)^n", "annotation": ["두 unit 난수의 곱도 unit입니다."]}, {"expression": "173\\cdot154\\bmod225=92", "annotation": ["같은 키의 두 암호문을 곱해 합산 암호문을 얻습니다."]}]} terms={[{"symbol": "m₁,m₂", "name": "합산할 값", "description": "이번에는 4와 3입니다."}, {"symbol": "r₁,r₂", "name": "두 독립 난수", "description": "재현용 2와 4의 곱은 8입니다."}]} assumptions={["같은 정상 공개키를 사용합니다.", "표시한 정규 난수곱 항등식은 g=n+1 설정입니다.", "동형성은 누가 보냈는지나 허용 범위를 보장하지 않습니다."]} interpretation="서버의 곱셈 뒤 비밀키 담당자가 읽는 것은 7입니다."/></section>
<section id="rerandomization" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 같은 합을 유지하면서 암호문을 다시 가릴 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">합산 암호문 92에 새 unit 7의 15제곱을 곱하면 56이 됩니다. 이는 암호화한 0을 곱한 것이므로 복호 결과는 여전히 7입니다. 합산된 난수 8은 8×7 mod15=11로 바뀌며 Enc(7;11)=56입니다.</p>
<p className="leading-8">고정된 유효 암호문에 신선하고 균등한 unit을 곱하면 새 난수의 분포도 균등합니다. 이렇게 암호문을 재무작위화할 수 있지만 잘못된 합계가 올바른 합계로 고쳐지지는 않습니다. 원래 암호문과 공개 연산 결과의 직접 관계를 가리는 일과 결과의 진위를 증명하는 일은 다릅니다.</p>
</div></section>
<section id="source-encrypt" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 원문 raw_encrypt에 같은 4와 난수 2를 넣습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">실행한 구현은 CSIRO Data61의 python-paillier, 커밋 7d9911eb과 phe 1.5.0입니다. PaillierPublicKey(15)는 g=16, nsquare=225, signed 인코딩용 max_int=4를 저장합니다. 마지막 값은 수학적 평문 전체 범위 0–14와 다릅니다.</p>
<p className="leading-8">raw_encrypt(4,2)는 지수 함수를 그대로 반복하지 않습니다. g=n+1 식을 써서 nude_ciphertext=(15×4+1) mod225=61을 만들고 powmod(2,15,225)=143을 곱해 173을 반환합니다. raw_encrypt(3,4)도 같은 경로에서 154입니다.</p>
<p className="leading-8">encrypt는 그 위에 정수·실수 인코딩을 얹습니다. r_value를 주지 않은 정상 경로에서는 난수로 가리는 단계도 호출합니다. 이번 수치 대조는 난수를 직접 지정한 재현용 호출이며 실제 엔트로피나 난수 생성기의 안전성을 시험한 결과가 아닙니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("public",codeRefs["public"])} label="원문 공개키와 암호화"/>
<CodeViewButton onClick={()=>sidebar.open("encoded",codeRefs["encoded"])} label="원문 인코딩 후 암호화"/>
<CitationBlock source="CSIRO Data61 · phe 1.5.0 고정 원문" citeKey={2} href="https://github.com/data61/python-paillier/tree/7d9911eb03c3c2d64399bc15405feb5e628379d1"><p className="leading-8">원문 파일을 변경 없이 보존하고 CPython 3.12.13에서 핵심 모듈을 가져와 같은 입력과 경계 사례를 실행했습니다. GMP·Crypto 선택 의존성 없이 기본 Python 연산 경로를 사용했습니다.</p>
</CitationBlock></section>
<section id="source-decrypt" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. 원문은 9와 25에서 나눠 복호한 뒤 합칩니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">선택한 원문의 raw_decrypt는 앞의 λ 식을 직접 계산하지 않습니다. p²=9와 q²=25에서 각각 복호한 다음 중국인의 나머지 정리, CRT로 합칩니다. 이 경로도 원논문 12쪽에 설명되어 있습니다.</p>
<p className="leading-8">미리 계산한 hp=1,hq=3과 p의 mod q 역원 2를 씁니다. 합산 암호문 92에서는 92² mod9=4이므로 Lp(4)=1이고 mp=1입니다. 92⁴ mod25=21이므로 Lq(21)=4이고 mq=4×3 mod5=2입니다.</p>
<p className="leading-8">이제 mod3에서 1이고 mod5에서 2인 값을 찾습니다. 원문은 u=(mq−mp)×2 mod5=2를 계산하고 mp+u×p=1+2×3=7을 반환합니다. 첫 암호문 173에는 mp=1,mq=4,u=1이어서 4를 반환합니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("private",codeRefs["private"])} label="원문의 CRT 준비값"/>
<CodeViewButton onClick={()=>sidebar.open("decrypt",codeRefs["decrypt"])} label="원문 raw_decrypt와 CRT"/>
<ExplainedFormula question="더 작은 두 modulus에서 같은 합 7을 어떻게 복원하나요?" idea="두 소수의 나머지를 먼저 얻고 두 조건을 동시에 만족시키는 값을 만듭니다." formula={String.raw`\begin{gathered}m_p=L_p(c^{p-1}\bmod p^2)h_p\bmod p\\m_q=L_q(c^{q-1}\bmod q^2)h_q\bmod q\\u=(m_q-m_p)p^{-1}\bmod q\\m=m_p+up\\c=92:\quad m_p=1,\ m_q=2\\u=(2-1)\cdot2\bmod5=2\\m=1+2\cdot3=7\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}m_p=L_p(c^{p-1}\bmod p^2)h_p\bmod p\\m_q=L_q(c^{q-1}\bmod q^2)h_q\bmod q\\u=(m_q-m_p)p^{-1}\bmod q\\m=m_p+up\\c=92:\quad m_p=1,\ m_q=2\\u=(2-1)\cdot2\bmod5=2\\m=1+2\cdot3=7\end{gathered}`} operations={[{"expression": "u=(2-1)\\cdot2\\bmod5=2", "annotation": ["mp에 p의 몇 배를 더하면 mod q 조건도 맞는지 찾습니다."]}, {"expression": "m=1+2\\cdot3=7", "annotation": ["7은 mod3에서 1이고 mod5에서 2입니다."]}]} terms={[{"symbol": "Lp,Lq", "name": "각 소수의 계수 함수", "description": "각각 (x−1)/p와 (x−1)/q입니다."}, {"symbol": "hp,hq", "name": "미리 구한 역원", "description": "각 소수에서 g의 복호 배율을 되돌립니다."}, {"symbol": "u", "name": "CRT 보정 배수", "description": "여기서는 앞의 L 함수 입력 기호와 다른 지역 변수입니다."}]} assumptions={["같은 정상 키·unit 암호문의 CRT 경로입니다.", "λ 계산과 실제 소스의 CRT 계산을 구분합니다."]} interpretation="같은 92를 두 방식으로 복호해 모두 7인지 대조했습니다."/></section>
<section id="source-operations" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">15. 원문에서 더하기 기호는 암호문 곱셈으로 내려갑니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">EncryptedNumber 두 개를 +로 더하면 _add_encrypted가 같은 공개키인지 확인합니다. 표현의 지수가 다르면 먼저 맞춘 뒤 _raw_add에서 암호문을 n² 안에서 곱합니다. 이번 두 정수는 지수가 둘 다 0이라 173과 154를 바로 곱해 92를 만듭니다.</p>
<p className="leading-8">반면 암호문 객체 둘을 *로 곱하면 NotImplementedError가 납니다. 공개된 정수와의 곱은 가능하지만 두 비밀 평문의 곱을 구현한 API는 아닙니다.</p>
<p className="leading-8">중간 계산마다 새 난수를 곱하지 않는 경로도 있습니다. ciphertext(False)는 내부 값을 그대로 읽고, 기본 ciphertext()는 필요하면 obfuscate를 부릅니다. 재현용 호출 예제에서 난수 getter를 7로 통제해 같은 92가 56으로 바뀌는 경로를 확인했습니다. 이 통제는 시험용이며 실제 난수 호출을 검증한 것은 아닙니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("add",codeRefs["add"])} label="원문의 암호문 더하기"/>
<CodeViewButton onClick={()=>sidebar.open("obfuscate",codeRefs["obfuscate"])} label="원문의 결과 재무작위화"/>
<CodeViewButton onClick={()=>sidebar.open("run",codeRefs["run"])} label="같은 4와 3을 실행한 호출 예제"/>
</section>
<section id="encoding" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">16. 수학적 나머지 7과 signed 정수 7의 허용 범위는 다릅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">이번 구현의 max_int는 n//3−1입니다. n=15에서는 0부터 4를 양수로, 11부터 14를 −4부터 −1로 읽습니다. 가운데 5부터 10은 넘침을 발견하는 구간으로 남겨 둡니다.</p>
<p className="leading-8">그래서 encrypt(4)+encrypt(3)의 raw 복호는 정상적으로 7이지만 signed decode는 OverflowError를 냅니다. 암호화의 덧셈이 틀린 것이 아니라 이 작은 키에서 정수 표현의 허용 범위를 넘은 것입니다.</p>
<p className="leading-8">이 감지가 모든 넘침을 잡는 것은 아닙니다. 암호화한 4를 네 번 더하면 정수 합은 16인데 mod15 결과는 1입니다. 1은 정상 양수 구간이라 decode는 경고 없이 1을 돌려줍니다. 최댓값과 합산 횟수로 전체 범위를 미리 계산해야 합니다.</p>
<p className="leading-8">실수는 정수 계수와 공개된 16진 지수로 표현합니다. 별도로 명시한 n=323의 작은 키에서는 정밀도 1/16으로 1.5를 계수 24·지수 −1, 0.25를 계수 4·지수 −1로 넣었습니다. 합 계수 28을 16으로 나눠 1.75를 얻었습니다. 이 지수는 암호화되지 않으므로 표현 정밀도도 프로토콜의 공개 정보입니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("encode",codeRefs["encode"])} label="원문의 정수·실수 인코딩"/>
<CodeViewButton onClick={()=>sidebar.open("decode",codeRefs["decode"])} label="원문의 signed 범위와 decode"/>
</section>
<section id="randomness" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">17. 난수를 재사용하면 두 평문의 차이가 드러납니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">같은 난수 2를 다시 써서 3을 암호화하면 53입니다. 앞의 4에 대한 암호문 173을 53의 mod225 역원과 곱하면 16입니다. 같은 난수 성분이 나눗셈에서 사라졌기 때문입니다.</p>
<p className="leading-8">g=n+1이므로 이 비율은 1+n×(4−3) mod n²입니다. 공개적으로 L(16)=1을 계산하면 두 평문의 차이 1 mod15가 드러납니다. 그중 하나를 알면 다른 값의 나머지도 알 수 있습니다.</p>
<p className="leading-8">따라서 난수는 독립적이고 예측하기 어려운 분포에서 새로 뽑아야 합니다. 계산 검산용 r=2나 재무작위화 시험용 getter=7을 실제 암호화 설정으로 가져가면 안 됩니다.</p>
</div></section>
<section id="validation" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">18. 낮은 수준 API가 조건을 자동으로 검사하지는 않습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">선택한 raw_encrypt는 정수 타입을 확인하지만 모든 정규 범위와 서로소 조건을 검사하지 않습니다. 실제로 m=15를 넣으면 0과 같은 메시지 성분으로 줄어듭니다. r=3을 넣으면 잘못된 암호문 27을 반환하고 gcd(27,15)=3으로 작은 키의 인수가 드러납니다.</p>
<p className="leading-8">r_value=0은 거부되지도, 0을 그대로 사용하지도 않습니다. 원문의 r_value or getter 때문에 기본 난수 getter로 넘어갑니다. 시험에서 getter를 7로 통제하자 223을 반환했습니다. 문서에 r=0 거부라고 써 놓는 것과 실제 호출 결과는 다릅니다.</p>
<p className="leading-8">raw_decrypt(0)도 오류 대신 2를 반환했습니다. 정상 unit에 대한 복호식이 성립하는 상황이 아닌데 정수 바닥 나눗셈과 CRT가 숫자를 만든 것입니다. 함수가 숫자를 반환했다는 사실만으로 정상 암호문이라고 판단하면 안 됩니다.</p>
<p className="leading-8">별도 검산 코드는 평문 0≤m&lt;n, 난수 0&lt;r&lt;n과 gcd(r,n)=1, 암호문 0&lt;c&lt;n²와 gcd(c,n)=1을 먼저 검사합니다. 이것은 이미 정상이라고 고정한 이번 키에 대한 입력 검사입니다. 임의 공개키의 생성 근거와 참여자별 허용 값·증명까지 확인해 주지는 않습니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("checks",codeRefs["checks"])} label="별도 입력 검사와 실제 실패 경로"/>
</section>
<section id="key-boundary" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">19. 왕복 복호 성공만으로 키 설정을 검증할 수 없습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">별도 작은 반례로 p=3,q=7,n=21을 고릅니다. λ=6이고 gcd(6,21)=3이므로 λ의 mod21 역원이 없습니다. 앞에서 선택한 g=n+1의 λ 복호 설정을 만족하지 않습니다.</p>
<p className="leading-8">그런데 실제 라이브러리 생성자는 이 값을 받아들이고 CRT 경로는 21개 메시지와 12개 unit 난수의 252개 조합을 모두 올바르게 복호했습니다. 따라서 “λ의 역원이 없으니 이 구현의 CRT 복호도 항상 실패한다”고 말하면 틀립니다.</p>
<p className="leading-8">차이는 난수 분포에서 보입니다. 12개 unit으로 0을 암호화했는데 서로 다른 출력은 1,197,244,440의 네 개뿐입니다. 처음의 n=15에서는 15×8개 메시지·난수 쌍이 120개 서로 다른 unit 암호문으로 이어졌습니다. 정상 왕복 검사와 선택한 전단사·보안 설정 검사는 구별해야 합니다.</p>
</div></section>
<section id="security" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">20. 더할 수 있다는 기능은 변조를 막아 주지 않습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">공개된 g=16을 암호문 173에 곱하면 68이 됩니다. 이 값은 5로 복호됩니다. 비밀키를 몰라도 평문에 1을 더하는 변조가 가능하며, 이는 집계에 쓰는 바로 그 동형성입니다.</p>
<p className="leading-8">이 성질 때문에 기본 Paillier를 그대로 쓰는 API는 임의 변조 암호문의 복호까지 허용하는 공격 모델에서 안전하지 않습니다. 도전 암호문에 g를 곱해 복호를 요청할 수 있으면 결과에서 1을 빼 원래 평문을 얻기 때문입니다. 허용 연산과 복호 권한을 제한하고 필요한 관계·범위 증명을 별도 설계해야 합니다.</p>
<p className="leading-8">정상 키의 인수분해를 알면 복호할 수 있지만, 그래서 DCRA가 인수분해의 어려움과 동치로 증명됐다는 뜻은 아닙니다. 원논문은 이 환원 방향을 구분합니다. 또한 이 인수분해 기반 구조는 양자 내성 암호라고 분류하지 않습니다.</p>
<p className="leading-8">통계 합을 공개할 때도 참여자가 한 명뿐이거나 다른 참여자의 값을 이미 알면 개별 값이 드러날 수 있습니다. 암호화는 공개 결과가 담고 있는 정보를 없애지 않습니다. 이 글은 threshold 복호나 악의적 참여자용 전체 MPC 프로토콜을 구현하지 않습니다.</p>
</div></section>
<section id="verification" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">21. 실제로 실행한 범위와 남은 범위를 나눕니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">고정한 원문 핵심 모듈을 CPython 3.12.13에서 불러와 실행했습니다. 원문 파일·라이선스·SHA와 별도 호출 예제 및 관측 결과를 보존했습니다. 15개 메시지와 8개 unit의 120개 암호화를 독립 정수 모형·λ 복호·원문 CRT 복호와 대조했고 암호문도 120개 서로 달랐습니다.</p>
<p className="leading-8">합산·공개 스칼라곱·난수 재사용·재무작위화·잘못된 raw 입력·별도 정규 검사 10건·signed 넘침·고정소수점 예·n=21 반례도 실행했습니다. 통제한 난수 getter는 그 호출 경로를 확인하는 시험 장치이며 실제 SystemRandom의 분포나 엔트로피를 검증하지 않았습니다.</p>
<p className="leading-8">전체 upstream 테스트, 큰 키의 무작위 생성, 상수 시간, 성능, 선택암호문·threshold·범위 증명 프로토콜과 보안 감사를 수행한 것은 아닙니다. 원논문의 옛 성능 표도 저자가 실제 구현 측정이 아닌 연산 비용 추정이라고 명시하므로 현재 장비의 측정값으로 읽지 않습니다.</p>
</div></section>
<section id="limits" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">22. 같은 두 값에서 달라질 결과를 예측합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">암호문 곱으로 평문 합을 만들 수 있는 이유와, 같은 기능이 변조를 허용하는 이유를 함께 보았습니다. 실제 원문에서는 수학식의 형태뿐 아니라 signed 인코딩과 CRT, 입력 검사와 재무작위화 경로도 확인해야 합니다.</p>
<p className="leading-8">평문 합이 15를 넘으면 무엇이 돌아오는지 먼저 예상해 보세요. 암호화한 4를 네 번 더할 때 signed decode가 반드시 오류를 낼지도 생각해 보세요. 마지막으로 두 메시지에 같은 난수를 쓰면 관찰자가 어떤 관계를 계산할 수 있는지 설명해 보세요.</p>
</div><ReviewPrompts questions={["같은 키에서 평문 13과 4를 합하면 17 대신 무엇을 복호하나요? (답: 11절)","암호화한 4를 네 번 더하면 signed decode가 항상 넘침을 알려 주나요? (답: 16절)","같은 난수로 만든 173과 53을 나누면 어떤 평문 관계가 드러나나요? (답: 17절)"]}/></section>
<CodeSidebar codeRefKey={sidebar.codeRefKey} codeRef={sidebar.codeRef} onClose={sidebar.close} onNavigate={sidebar.navigate} codeRefs={codeRefs} fileTrees={fileTrees} projectMetas={projectMetas}/></div>}
