import type { Article } from "../types";

export const globalHistoryArticles: Article[] = [
  {
    slug: "empires-roads-taxes-and-law",
    title: "제국은 넓은 땅을 도로·세금·여러 법의 겹침으로 묶었습니다",
    subcategory: "global-history-empires",
    sections: [
      { id: "overview", title: "지도에서 한 색으로 보이는 제국도 안쪽은 하나가 아니었습니다" },
      { id: "black-box", title: "명령·세금·병력·정보의 네 흐름을 나눕니다" },
      { id: "case", title: "곡물 100자루를 수도와 변경에 나눠 보냅니다" },
      { id: "picture", title: "도로는 시장과 군대를 함께 움직였습니다" },
      { id: "need", title: "먼 지방을 다스리려면 현지 권력과 번역이 필요했습니다" },
      { id: "names", title: "제국 물류·재정 가시성·법의 중첩에 이름을 붙입니다" },
      { id: "mechanism", title: "100자루가 세금·급료·구휼로 바뀌는 길을 추적합니다" },
      { id: "source", title: "아소카 칙령의 돌기둥이 누구에게 말을 거는지 봅니다" },
      { id: "comparison", title: "페르시아·한·로마의 도로를 같은 기능과 다른 제도로 비교합니다" },
      { id: "limits", title: "도로 길이와 제국의 통제력을 같은 숫자로 보지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/empires-roads-taxes-and-law"),
  },
  {
    slug: "trade-religion-and-translation-networks",
    title: "중세의 연결망은 물건과 함께 종교·언어·지식을 옮겼습니다",
    subcategory: "global-history-networks",
    sections: [
      { id: "overview", title: "600~1500년의 세계는 고립된 대륙들의 정지 화면이 아니었습니다" },
      { id: "black-box", title: "바람·항구·상인 공동체·번역 기관을 연결합니다" },
      { id: "case", title: "향신료 100묶음이 계절풍을 타고 세 항구를 지납니다" },
      { id: "picture", title: "배의 항로와 신앙·지식의 경로는 겹치지만 같지 않습니다" },
      { id: "need", title: "낯선 곳에서 거래하려면 신뢰와 통역의 장소가 필요했습니다" },
      { id: "names", title: "계절풍 항해·디아스포라·번역 기관에 이름을 붙입니다" },
      { id: "mechanism", title: "100묶음과 한 권의 책이 다른 속도로 퍼지는 길을 봅니다" },
      { id: "source", title: "실크로드를 육상 한 줄이 아닌 여러 길의 묶음으로 읽습니다" },
      { id: "comparison", title: "마르코 폴로 필사본은 여행·전언·전설을 함께 담습니다" },
      { id: "limits", title: "교류를 평화로운 융합이나 한 문명의 선물로만 쓰지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/trade-religion-and-translation-networks"),
  },
  {
    slug: "conquest-disease-silver-and-oceanic-exchange",
    title: "대양 정복은 질병·은·강제 노동을 한 세계 장부에 묶었습니다",
    subcategory: "global-history-oceanic",
    sections: [
      { id: "overview", title: "1492년 뒤의 연결은 상품 교환만으로 설명되지 않습니다" },
      { id: "black-box", title: "정복·생물 이동·광산 노동·은 결제를 연결합니다" },
      { id: "case", title: "포토시 은 100단위가 안데스에서 유럽과 아시아로 갑니다" },
      { id: "picture", title: "은의 이동과 사람·질병의 이동은 비용을 다르게 남겼습니다" },
      { id: "need", title: "세계 교역의 결제 수요는 광산 생산과 강제력을 밀어 올렸습니다" },
      { id: "names", title: "생물 교환·은 회로·강제 광산 노동에 이름을 붙입니다" },
      { id: "mechanism", title: "100단위의 은과 기록 밖 손실을 같은 경로에서 봅니다" },
      { id: "source", title: "포토시의 미타를 노동 제도와 생산 조건으로 읽습니다" },
      { id: "comparison", title: "콜럼버스 교환은 작물 이동과 대규모 죽음을 함께 만들었습니다" },
      { id: "limits", title: "유럽의 항해를 세계 연결의 유일한 시작으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/conquest-disease-silver-and-oceanic-exchange"),
  },
  {
    slug: "revolutions-citizenship-and-industrial-empires",
    title: "혁명의 보편 권리는 시민의 경계와 산업 제국의 팽창 속에서 충돌했습니다",
    subcategory: "global-history-revolutions",
    sections: [
      { id: "overview", title: "권리를 선언한 사람과 실제 시민으로 센 사람은 같지 않았습니다" },
      { id: "black-box", title: "주권·시민권·동원·제국 팽창의 네 흐름을 봅니다" },
      { id: "case", title: "주민 100명 중 30명만 정치에 참여하는 공화국을 봅니다" },
      { id: "picture", title: "보편 문장과 제한된 명부를 두 장으로 나눕니다" },
      { id: "need", title: "국가는 권리를 약속하면서 세금과 병역을 더 넓게 요구했습니다" },
      { id: "names", title: "혁명적 주권·시민 경계·제국적 민족주의에 이름을 붙입니다" },
      { id: "mechanism", title: "30명의 시민 명부가 확대되거나 식민지에서 닫히는 길을 봅니다" },
      { id: "source", title: "1789년 권리 선언의 보편 문장을 실제 정치 경계에 대입합니다" },
      { id: "comparison", title: "1884~1885년 베를린의 외교 문서는 아프리카를 누가 나눴는지 보여 줍니다" },
      { id: "limits", title: "한 혁명과 한 국민국가 모형을 모든 지역의 순서로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/revolutions-citizenship-and-industrial-empires"),
  },
  {
    slug: "world-wars-depression-and-mass-states",
    title: "세계대전과 대공황은 국가가 사람·생산·정보를 동원하는 범위를 넓혔습니다",
    subcategory: "global-history-world-wars",
    sections: [
      { id: "overview", title: "1914~1945년은 전쟁 두 개 사이에 평화가 끼어든 단순 연표가 아닙니다" },
      { id: "black-box", title: "병력·생산·부채·선전·식민지를 한 동원 체계로 봅니다" },
      { id: "case", title: "100가구의 노동과 식량을 전시 장부로 옮겨 봅니다" },
      { id: "picture", title: "전선과 후방, 본국과 식민지의 비용을 나눕니다" },
      { id: "need", title: "총력전은 민간 생산과 일상까지 군사 목표에 묶었습니다" },
      { id: "names", title: "총력전 동원·전간기 불황·위임통치에 이름을 붙입니다" },
      { id: "mechanism", title: "100가구의 동원과 전후 약속이 정치 요구로 바뀌는 길을 봅니다" },
      { id: "source", title: "국제연맹 규약의 평화 약속과 위임통치를 함께 읽습니다" },
      { id: "comparison", title: "대공황과 2차대전의 미국 자료는 한 지역의 국가 확대를 보여 줍니다" },
      { id: "limits", title: "유럽 전선과 미국 정책만으로 세계대전의 세계성을 대신하지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/world-wars-depression-and-mass-states"),
  },
  {
    slug: "cold-war-decolonization-and-globalization",
    title: "탈식민의 새 국가들은 냉전 양극과 세계 규칙 사이에서 선택지를 만들었습니다",
    subcategory: "global-history-postwar",
    sections: [
      { id: "overview", title: "1945년 뒤 세계는 미국과 소련 두 칸만으로 읽히지 않습니다" },
      { id: "black-box", title: "안보 동맹·독립·개발·비동맹·다자 규칙을 연결합니다" },
      { id: "case", title: "예산 100인 신생 국가가 안보와 개발을 나눕니다" },
      { id: "picture", title: "두 강대국의 압력과 새 국가의 선택을 다른 축에 놓습니다" },
      { id: "need", title: "법적 독립 뒤에도 기술·자본·시장·군사 지원이 필요했습니다" },
      { id: "names", title: "양극 질서·반둥 비동맹·탈식민 개발 질서에 이름을 붙입니다" },
      { id: "mechanism", title: "예산 100과 외부 지원 조건이 정책 공간을 바꾸는 길을 봅니다" },
      { id: "source", title: "1955년 반둥 최종 공동성명이 만든 제3의 언어를 읽습니다" },
      { id: "comparison", title: "1994년 마라케시 협정은 무역 규칙의 범위를 넓혔습니다" },
      { id: "limits", title: "냉전 종식과 세계화를 한 방향의 수렴으로 쓰지 않습니다" },
    ],
    component: () => import("@/pages/articles/global-history/cold-war-decolonization-and-globalization"),
  },
];
