import type { Article } from "../types";

export const hwArticles: Article[] = [
  /* ── Compute ── */
  {
    slug: "hw-gpu-comparison",
    title: "GPU 비교: RTX 4090 vs 5090 vs A100 vs H100",
    subcategory: "hw-compute",
    sections: [
      { id: "overview", title: "제품보다 workload부터" },
      { id: "workload-envelope", title: "Capacity·SLA 요구사항" },
      { id: "consumer", title: "RTX 4090·5090 경계" },
      { id: "datacenter", title: "A100·H100과 fabric" },
      { id: "blockchain", title: "Workload별 paired benchmark" },
      { id: "release-gate", title: "Procurement gate" },
    ],
    component: () => import("@/pages/articles/hw/gpu-comparison"),
  },
  {
    slug: "ai-accelerator-vendor-comparison",
    title: "가속기 비교는 스펙표가 아니라 네 축으로 합니다",
    subcategory: "hw-compute",
    sections: [
      { id: "overview", title: "스펙표를 나란히 놓는 것으로는 결론이 안 납니다" },
      { id: "memory-axis", title: "용량은 올라가느냐를, 대역폭은 얼마나 빠르냐를 정합니다" },
      {
        id: "link-axis",
        title: "가속기를 잇는 방식에서 셋이 갈라집니다",
        subsections: [{ id: "scale-up-vs-out", title: "노드 안과 노드 밖을 구분해서 봐야 합니다" }],
      },
      { id: "form-factor", title: "폼팩터가 전력과 냉각, 그리고 조달 선택지를 함께 정합니다" },
      { id: "software-axis", title: "같은 코드가 그대로 도는지가 네 번째 축입니다" },
      { id: "snapshot-gate", title: "스냅샷은 기준일과 함께 읽습니다" },
    ],
    component: () => import("@/pages/articles/hw/ai-accelerator-vendor-comparison"),
  },
  {
    slug: "hw-server-vs-desktop",
    title: "서버 vs 데스크톱: 부품 차이 완전 정리",
    subcategory: "hw-compute",
    sections: [
      { id: "overview", title: "서버는 운영 플랫폼이다" },
      { id: "workload-envelope", title: "Workload resource envelope" },
      { id: "platform-topology", title: "Lane·memory·NUMA topology" },
      { id: "serviceability", title: "BMC·Redfish·serviceability" },
      { id: "release-gate", title: "Platform release gate" },
    ],
    component: () => import("@/pages/articles/hw/server-vs-desktop"),
  },
  {
    slug: "server-cpu-lineup-comparison",
    title: "GPU 서버의 CPU는 레인과 채널로 고릅니다",
    subcategory: "hw-compute",
    sections: [
      { id: "overview", title: "가속기 서버에서 CPU는 연산보다 통로를 담당합니다" },
      {
        id: "lane-budget",
        title: "레인은 나눠 쓰는 자원이라 먼저 예산을 짭니다",
        subsections: [{ id: "lane-arithmetic", title: "나눠 쓰면 언제 문제가 되는지 계산합니다" }],
      },
      { id: "memory-channels", title: "채널 수가 대역폭과 최대 용량을 함께 정합니다" },
      {
        id: "core-character",
        title: "코어는 개수보다 성격과 배치가 중요합니다",
        subsections: [{ id: "numa-placement", title: "어느 소켓에 붙은 가속기인지가 성능을 바꿉니다" }],
      },
      { id: "product-tiers", title: "제품군 경계는 코어가 아니라 플랫폼 기능이 정합니다" },
      { id: "selection-gate", title: "구성표를 먼저 적고 그다음에 제품을 고릅니다" },
    ],
    component: () => import("@/pages/articles/hw/server-cpu-lineup-comparison"),
  },

  /* ── Storage ── */
  {
    slug: "hw-nvme-storage",
    title: "NVMe 스토리지: M.2 vs U.2 vs E1.S",
    subcategory: "hw-storage",
    sections: [
      { id: "overview", title: "NVMe와 form factor 분리" },
      { id: "protocol-form-factor", title: "Protocol·mechanical 계약" },
      { id: "path-budget", title: "Lane·shared path budget" },
      { id: "thermal-serviceability", title: "Thermal·serviceability" },
      { id: "release-gate", title: "NVMe device release gate" },
    ],
    component: () => import("@/pages/articles/hw/nvme-storage"),
  },
  {
    slug: "hw-storage-comparison",
    title: "스토리지 비교: SATA vs NVMe vs SAS",
    subcategory: "hw-storage",
    sections: [
      { id: "overview", title: "Workload tier부터 고정" },
      { id: "io-path", title: "Command·transport·topology" },
      { id: "endurance-reserve", title: "Endurance·capacity reserve" },
      { id: "workload-placement", title: "Failure-domain placement" },
      { id: "release-gate", title: "Storage tier release gate" },
    ],
    component: () => import("@/pages/articles/hw/storage-comparison"),
  },

  /* ── Memory ── */
  {
    slug: "hw-memory",
    title: "메모리: DDR4 vs DDR5, ECC, RDIMM",
    subcategory: "hw-memory",
    sections: [
      { id: "overview", title: "왜 메모리 선택이 중요한가" },
      { id: "ddr", title: "DDR4와 DDR5: 채널·대역폭·지연시간" },
      { id: "ecc", title: "ECC: 보호 범위와 오류 운영" },
      { id: "rdimm", title: "UDIMM·RDIMM·3DS·MRDIMM" },
    ],
    component: () => import("@/pages/articles/hw/memory"),
  },

  /* ── Infrastructure ── */
  {
    slug: "hw-power-cooling",
    title: "서버 전력·냉각: 입력 전력부터 랙 열 제거까지",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "Wall power에서 heat rejection까지" },
      { id: "power-heat", title: "Input power·heat balance" },
      { id: "rack-power", title: "A/B feed·N−1 headroom" },
      { id: "cooling-path", title: "Air·liquid cooling path" },
      { id: "release-gate", title: "Power·cooling release gate" },
    ],
    component: () => import("@/pages/articles/hw/power-cooling"),
  },
  {
    slug: "datacenter-site-readiness",
    title: "랙에 들어가는지는 무게와 냉각으로 먼저 갈립니다",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "사양서에 없는 조건에서 막히는 경우가 많습니다" },
      {
        id: "cooling-type",
        title: "같은 카드라도 바람을 어디로 버리느냐가 다릅니다",
        subsections: [{ id: "airflow-direction", title: "섀시 기류 방향이 랙 배치와 맞아야 합니다" }],
      },
      {
        id: "power-sizing",
        title: "명판 전력과 실제 전력은 다른 숫자입니다",
        subsections: [{ id: "redundancy", title: "이중화 표기는 감당 범위를 말합니다" }],
      },
      {
        id: "floor-load",
        title: "가속기 랙은 바닥 허용치를 먼저 넘습니다",
        subsections: [{ id: "load-arithmetic", title: "숫자를 한 번 넣어 봅니다" }],
      },
      { id: "seismic", title: "고정하지 않은 랙은 흔들림에 먼저 쓰러집니다" },
      { id: "readiness-gate", title: "건물이 정한 제약에서 거꾸로 올라옵니다" },
    ],
    component: () => import("@/pages/articles/hw/datacenter-site-readiness"),
  },
  {
    slug: "hw-network",
    title: "서버 네트워크 기초: Workload · Goodput · Ethernet Fabric",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "서버 네트워크는 workload에서 시작한다" },
      { id: "workload-contract", title: "Traffic matrix의 형태" },
      { id: "goodput-boundary", title: "Line rate와 payload goodput" },
      { id: "ethernet", title: "Ethernet 링크와 leaf-spine fabric" },
    ],
    component: () => import("@/pages/articles/hw/network"),
  },
  {
    slug: "gpu-interconnects",
    title: "GPU Interconnects: PCIe · NVLink · Device Topology",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "GPU buffer의 실제 device path" },
      { id: "pcie-transaction-bandwidth-latency", title: "PCIe raw rate와 payload 경계" },
      { id: "pcie-topology-peer-path", title: "Switch · root · NUMA topology" },
      { id: "nvlink-device-fabric-boundary", title: "NVLink와 node-external 경계" },
    ],
    component: () => import("@/pages/articles/hw/gpu-interconnects"),
  },
  {
    slug: "rdma-roce",
    title: "RDMA · RoCE: Memory Registration에서 GPUDirect까지",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "Control과 data path 분리" },
      { id: "rdma-control-data-path", title: "Work request와 NIC DMA" },
      { id: "rdma-memory-registration", title: "Range · key · lifetime" },
      { id: "roce-gid-routing", title: "RoCE v2 GID와 route" },
      { id: "gpudirect-topology", title: "GPU–HCA direct path" },
    ],
    component: () => import("@/pages/articles/hw/rdma-roce"),
  },
  {
    slug: "gpu-collective-network",
    title: "GPU Collective Network: Rank · Fabric · NCCL 측정",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "Rank buffer에서 collective 완료까지" },
      { id: "collective-rank-semantics", title: "Operation · count · datatype 계약" },
      { id: "nccl-bandwidth-boundary", title: "algbw · busbw · wire counter" },
      { id: "infiniband", title: "Fabric 선택과 acceptance ledger" },
    ],
    component: () => import("@/pages/articles/hw/gpu-collective-network"),
  },
  {
    slug: "modded-rtx4090-moe-serving",
    title: "개조 RTX 4090 48GB와 MoE Serving: NVLink 공백을 엔지니어링으로 메우기",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "용량은 늘어도 링크는 그대로" },
      { id: "capacity-mod", title: "48GB 개조의 회로 수준 메커니즘" },
      { id: "nvlink-gap-quantified", title: "4090 · 3090 · A100 · H100 대역폭 정량 대조" },
      { id: "moe-communication-sensitivity", title: "MoE all-to-all이 dense all-reduce보다 예민한 이유" },
      { id: "engineering-recovery", title: "Expert 배치 · 병렬화 선택 · quantization · batching" },
      { id: "release-gate", title: "용량 병목 vs 통신 병목 판단 순서" },
    ],
    component: () => import("@/pages/articles/hw/modded-rtx4090-moe-serving"),
  },
  {
    slug: "b300-switchless-network",
    title: "DGX B300 Switchless: ConnectX-8 직결 RoCE 클러스터",
    subcategory: "hw-infra",
    sections: [
      { id: "overview", title: "스위치를 없애면 fabric을 직접 구현한다" },
      { id: "ports", title: "8 OSFP와 16 logical 400GbE" },
      { id: "topology", title: "노드 수·케이블 수·대역폭 설계" },
      { id: "addressing", title: "링크별 /30과 자동 설정" },
      { id: "nccl", title: "Peer-aware GID 선택 patch" },
      { id: "measurement", title: "787GB/s가 의미하는 범위" },
      { id: "operations", title: "지원·복구·확장 한계" },
    ],
    component: () => import("@/pages/articles/hw/b300-switchless-network"),
  },
  {
    slug: "ai-infrastructure-b300-128-blueprint",
    title: "B300 128 GPU 설계: 요구사항에서 BOM까지",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · 128개를 사기 전에 완료할 일을 정합니다" },
      { id: "black-box", title: "2 · 요구사항이 여섯 설계 원장으로 내려갑니다" },
      { id: "case", title: "3 · GPU 128개를 8개짜리 노드 16대로 셉니다" },
      { id: "picture", title: "4 · 학습·추론·혼합 용도에서 망 구성이 갈립니다" },
      { id: "need", title: "5 · 결정과 미확정을 같은 표에서 분리합니다" },
      { id: "names", title: "6 · 기준 구성과 BOM에 이름을 붙입니다" },
      { id: "mechanism", title: "7 · 고객 질문을 납품 가능한 구성으로 바꿉니다" },
      { id: "source", title: "8 · 공개 B300 기준 구성에 수량을 대입합니다" },
      { id: "comparison", title: "9 · 128개와 256개 확장 경계를 비교합니다" },
      { id: "limits", title: "10 · 이 설계는 실제 벤더 견적이 아닙니다" },
    ],
    component: () => import("@/pages/articles/hw/ai-infrastructure-b300-128-blueprint"),
  },
  {
    slug: "ai-cluster-software-compatibility",
    title: "GPU 클러스터 호환성: OS부터 NCCL·DOCA-OFED까지",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · 설치 성공보다 조합의 재현성을 확인합니다" },
      { id: "black-box", title: "2 · 계산 경로와 통신 경로를 나눠 봅니다" },
      { id: "case", title: "3 · 16대 중 한 대의 버전 차이가 전체 작업을 막습니다" },
      { id: "picture", title: "4 · 바꿀 수 있는 층과 묶어서 바꿀 층을 가릅니다" },
      { id: "need", title: "5 · 컨테이너만 고정해서는 호스트 차이를 못 막습니다" },
      { id: "names", title: "6 · NCCL·DOCA·OFED가 맡는 자리를 붙입니다" },
      { id: "mechanism", title: "7 · 한 행짜리 호환성 원장으로 검증합니다" },
      { id: "source", title: "8 · DGX OS release 조합을 원장에 옮깁니다" },
      { id: "comparison", title: "9 · DOCA profile을 필요한 기능으로 고릅니다" },
      { id: "limits", title: "10 · 최신 버전이 곧 안전한 조합은 아닙니다" },
    ],
    component: () => import("@/pages/articles/hw/ai-cluster-software-compatibility"),
  },
  {
    slug: "kubernetes-vs-slurm-gpu-scheduling",
    title: "Kubernetes와 Slurm: GPU 작업을 어디에 맡길까",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · 도구 이름보다 작업의 생애를 먼저 봅니다" },
      { id: "black-box", title: "2 · 요청·대기·할당·실행·회수를 추적합니다" },
      { id: "case", title: "3 · 16개 노드에서 8개짜리 작업 네 개를 받습니다" },
      { id: "picture", title: "4 · 서비스와 배치 작업의 우선순위가 다릅니다" },
      { id: "need", title: "5 · GPU 개수만 맞아도 함께 시작하지 않으면 멈춥니다" },
      { id: "names", title: "6 · Job·Pod·partition·allocation을 구분합니다" },
      { id: "mechanism", title: "7 · 작업 형태에서 스케줄러를 선택합니다" },
      { id: "source", title: "8 · Slurm의 자원 할당과 job step을 적용합니다" },
      { id: "comparison", title: "9 · Kubernetes의 Job과 GPU Operator를 적용합니다" },
      { id: "limits", title: "10 · 둘을 함께 쓸 때 소유권부터 정합니다" },
    ],
    component: () => import("@/pages/articles/hw/kubernetes-vs-slurm-gpu-scheduling"),
  },
  {
    slug: "ai-cluster-storage-io",
    title: "AI 클러스터 스토리지: 한 번의 I/O에서 복구까지",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · 저장 완료 표시가 있었지만 복구하지 못했습니다" },
      { id: "black-box", title: "2 · 요청은 네 책임 구간을 지나갑니다" },
      { id: "case", title: "3 · 4MiB read를 2,048 IOPS로 바꿉니다" },
      { id: "picture", title: "4 · 전부 가까이 두면 node 하나와 함께 사라집니다" },
      { id: "need", title: "5 · 데이터마다 살아남아야 하는 시간이 다릅니다" },
      { id: "names", title: "6 · 앞에서 본 역할에 storage 이름을 붙입니다" },
      { id: "mechanism", title: "7 · 같은 4MiB read와 checkpoint를 끝까지 따라갑니다" },
      { id: "source", title: "8 · Linux에서 처음 느려진 지점을 찾습니다" },
      { id: "comparison", title: "9 · Elice 공개 정보로 PoC 질문을 만듭니다" },
      { id: "limits", title: "10 · Restore가 끝나야 storage를 채택합니다" },
    ],
    component: () => import("@/pages/articles/hw/ai-cluster-storage-io"),
  },
  {
    slug: "b300-rack-power-cooling",
    title: "B300 128 GPU 전력·냉각: 랙과 열 제거를 계산합니다",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · GPU 수를 전기와 열의 요구로 바꿉니다" },
      { id: "black-box", title: "2 · 콘센트에서 실외 열 방출까지 이어 봅니다" },
      { id: "case", title: "3 · 16대의 평균 232kW와 피크 304kW를 셉니다" },
      { id: "picture", title: "4 · 저밀도와 고밀도 랙을 현장 제약으로 고릅니다" },
      { id: "need", title: "5 · RDHx와 DLC를 같은 수랭으로 부르지 않습니다" },
      { id: "names", title: "6 · PDU·UPS·RDHx·CDU의 경계를 붙입니다" },
      { id: "mechanism", title: "7 · 전력과 냉각 예산을 같은 원장으로 만듭니다" },
      { id: "source", title: "8 · B300 공개 평균·피크를 랙 수에 적용합니다" },
      { id: "comparison", title: "9 · 싱가포르의 고온 운영 기준을 별도로 확인합니다" },
      { id: "limits", title: "10 · 유량 계산은 설비 승인 도면이 아닙니다" },
    ],
    component: () => import("@/pages/articles/hw/b300-rack-power-cooling"),
  },
  {
    slug: "ai-infrastructure-commissioning-acceptance",
    title: "AI 인프라 구축·검수: 납품을 재현 가능한 증거로 닫습니다",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · 장비가 켜진 상태와 납품 완료를 구분합니다" },
      { id: "black-box", title: "2 · 설계 기준이 시험과 인수 증거로 이어집니다" },
      { id: "case", title: "3 · 16대의 네 단계 검수에서 64개 증거를 남깁니다" },
      { id: "picture", title: "4 · 공장·현장·성능·운영 인수를 나눕니다" },
      { id: "need", title: "5 · 합격 기준을 발주 뒤에 정하면 분쟁이 생깁니다" },
      { id: "names", title: "6 · FAT·SAT·acceptance ledger에 이름을 붙입니다" },
      { id: "mechanism", title: "7 · 요구사항을 검수 항목으로 바꿉니다" },
      { id: "source", title: "8 · NVSM·Slurm·NCCL로 층별 상태를 확인합니다" },
      { id: "comparison", title: "9 · 공공 제안에서는 CSAP 범위를 따로 적습니다" },
      { id: "limits", title: "10 · 벤치마크 한 번으로 운영 인수를 끝내지 않습니다" },
    ],
    component: () => import("@/pages/articles/hw/ai-infrastructure-commissioning-acceptance"),
  },
  {
    slug: "nvidia-nca-aiio-study-guide",
    title: "NCA-AIIO 준비: 시험 범위를 AI 인프라 현장 증거로 바꾸기",
    subcategory: "hw-ai-cluster",
    sections: [
      { id: "overview", title: "1 · GPU는 열여섯 개 모두 보이는데 작업은 시작하지 못합니다" },
      { id: "black-box", title: "2 · 작업 하나가 준비되고 끝나는 네 구간을 엽니다" },
      { id: "case", title: "3 · 공식 38·40·22%를 19·20·11개의 학습 장부로 바꿉니다" },
      { id: "picture", title: "4 · 같은 장애도 첫 확인 문은 세 갈래입니다" },
      { id: "need", title: "5 · 합격 점수와 현장 수행 증거를 분리해야 합니다" },
      { id: "names", title: "6 · Blueprint·증거 지도·역할 경계에 이름을 붙입니다" },
      { id: "mechanism", title: "7 · 한 목표를 설명·실행·증거·복습의 고리로 바꿉니다" },
      { id: "source", title: "8 · 공식 Study Guide를 실제 첫 점검과 연결합니다" },
      { id: "comparison", title: "9 · 현행 시험 범위와 다음 Professional 단계를 구분합니다" },
      { id: "limits", title: "10 · 자격증은 BOM·RFP·시설 승인과 장애 복구를 대신하지 않습니다" },
    ],
    component: () => import("@/pages/articles/hw/nvidia-nca-aiio-study-guide"),
  },
];
