import type { Category } from "../types";
import { hwArticles } from "./articlesHw";

const gpu: Category = {
  slug: "gpu",
  name: "HW / GPU",
  description: "GPU 병렬처리, CUDA, 서버 하드웨어, 스토리지",
  subcategories: [
    {
      slug: "hw-basics",
      name: "Hardware Basics",
      description: "서버/워크스테이션 부품, 스토리지, 메모리",
      icon: "🔩",
      children: [
        {
          slug: "hw-compute",
          name: "Compute",
          description: "CPU, GPU, 서버 vs 데스크톱",
          icon: "⚙️",
        },
        {
          slug: "hw-storage",
          name: "Storage",
          description: "NVMe, M.2, U.2, SAS, 엔터프라이즈 SSD",
          icon: "💿",
        },
        {
          slug: "hw-memory",
          name: "Memory",
          description: "DDR4/DDR5, ECC, RDIMM",
          icon: "🧠",
        },
        {
          slug: "hw-infra",
          name: "Infrastructure",
          description: "전력, 냉각, 네트워크, 랙마운트",
          icon: "🏗️",
        },
      ],
    },
    {
      slug: "gpu-fundamentals",
      name: "GPU Fundamentals",
      description: "SIMT, 메모리 계층, CUDA 기초",
      icon: "🖥️",
    },
    {
      slug: "zk-acceleration",
      name: "ZK Acceleration",
      description: "MSM, NTT, 증명 GPU 가속 기법",
      icon: "⚡",
    },
  ],
  articles: [
    ...hwArticles,
    {
      slug: "gpu-architecture",
      title: "GPU 아키텍처 기초 (SIMT, 메모리 계층, 워프)",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "CPU vs GPU & SIMT 모델" },
        { id: "memory-hierarchy", title: "메모리 계층 구조" },
        { id: "warp", title: "워프 스케줄링 & 점유율" },
        { id: "optimization", title: "GPU 최적화 기법" },
      ],
      component: () => import("@/pages/articles/blockchain/gpu-architecture"),
    },
    {
      slug: "cuda-basics",
      title: "CUDA 실행 기초: Host·Kernel·Memory·Workload Fit",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "Host에서 device execution까지" },
        { id: "memory-model", title: "메모리 계층과 이동 비용" },
        { id: "blockchain-gpu", title: "Workload fit과 측정 경계" },
      ],
      component: () => import("@/pages/articles/blockchain/cuda-basics"),
    },
    {
      slug: "cuda-thread-hierarchy",
      title: "CUDA 스레드 계층: 그리드, 블록, 워프, 인덱싱",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "스레드 계층 구조" },
        { id: "builtin-vars", title: "내장 변수와 레이아웃 설정" },
        { id: "indexing-1d", title: "1D 인덱싱" },
        { id: "indexing-2d", title: "2D 인덱싱" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-thread-hierarchy"),
    },
    {
      slug: "cuda-matrix-multiply",
      title: "CUDA 행렬 곱셈: 기초 → 공유메모리 타일링",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "행렬 곱을 traffic 문제로 읽기" },
        { id: "naive", title: "Output thread mapping" },
        { id: "tiled", title: "Shared-memory tile reuse" },
        { id: "performance", title: "GEMM 측정 방법" },
        { id: "release-gate", title: "Tile 선택과 채택 기준" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-matrix-multiply"),
    },
    {
      slug: "cuda-shared-memory",
      title: "CUDA 공유 메모리: 뱅크 충돌, Coalescing",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "공유 메모리란?" },
        { id: "bank-conflict", title: "뱅크 충돌" },
        { id: "coalescing", title: "Coalescing" },
        { id: "aos-soa", title: "AoS vs SoA" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-shared-memory"),
    },
    {
      slug: "cuda-sync-streams",
      title: "CUDA 동기화 & 스트림",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "동기화 메커니즘" },
        { id: "streams", title: "CUDA 스트림" },
        { id: "events", title: "CUDA 이벤트" },
        { id: "multi-gpu", title: "다중 GPU" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-sync-streams"),
    },
    {
      slug: "gpu-arch-hopper",
      title: "Hopper 아키텍처: SM, TMA, Cluster",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "Hopper data pipeline" },
        { id: "sm-structure", title: "SM과 latency hiding" },
        { id: "tma", title: "TMA producer–consumer" },
        { id: "cluster", title: "Cluster와 DSM" },
        { id: "transformer-engine", title: "FP8 precision contract" },
        { id: "release-gate", title: "Feature compatibility gate" },
      ],
      component: () => import("@/pages/articles/gpu/gpu-arch-hopper"),
    },
    {
      slug: "cuda-perf-analysis",
      title: "CUDA 성능 분석: timing, Roofline, profiler",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "병목 가설 분석 loop" },
        { id: "measurement-protocol", title: "Warm-up과 timing 경계" },
        { id: "throughput-ledger", title: "Amdahl과 achieved ledger" },
        { id: "profiling", title: "Nsight 분석 순서" },
        { id: "release-gate", title: "Performance ablation gate" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-perf-analysis"),
    },
    {
      slug: "cuda-register-pressure",
      title: "CUDA register pressure: live range, occupancy, spill",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "Register와 live range" },
        { id: "live-range", title: "겹치는 value lifetime" },
        { id: "residency", title: "Residency와 occupancy" },
        { id: "spill-path", title: "Local-memory spill 경로" },
        { id: "release-gate", title: "Resource release gate" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-register-pressure"),
    },
    {
      slug: "cuda-kernel-fusion",
      title: "CUDA kernel fusion과 Megakernel",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "Fusion 범위 구분" },
        { id: "small-fusion", title: "작은 elementwise fusion" },
        { id: "megakernel", title: "Megakernel 자원 trade-off" },
        { id: "flash-attention", title: "Tile-budgeted fusion" },
        { id: "kernel-stack", title: "CUTLASS·CuTe·Triton 선택 층" },
        { id: "release-gate", title: "Fusion release gate" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-kernel-fusion"),
    },
    {
      slug: "cuda-persistent-kernels",
      title: "CUDA persistent kernel: queue, worker, shutdown",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "overview", title: "Long-lived worker model" },
        { id: "worker-residency", title: "Worker resource budget" },
        { id: "queue-progress", title: "Queue와 backpressure" },
        { id: "shutdown", title: "Drain과 종료" },
        { id: "release-gate", title: "Persistent release gate" },
      ],
      component: () => import("@/pages/articles/gpu/cuda-persistent-kernels"),
    },
    {
      slug: "cfd-finite-volume-gpu",
      title: "CFD 기초: finite volume에서 GPU mapping까지",
      subcategory: "gpu-fundamentals",
      sections: [
        { id: "conservation", title: "보존 법칙과 CFD 경계" },
        { id: "finite-volume", title: "Finite-volume cell balance" },
        { id: "time-step", title: "CFL time-step budget" },
        { id: "gpu-mapping", title: "Stencil과 GPU memory mapping" },
        { id: "verification", title: "Verification·validation gate" },
      ],
      component: () =>
        import("@/pages/articles/gpu/cfd-finite-volume-gpu"),
    },
    {
      slug: "msm-ntt",
      title: "MSM·NTT GPU workload: bucket, stage, residency",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "같은 GPU, 다른 dependency" },
        { id: "workload-contract", title: "고정 proof workload" },
        { id: "parallel-frontier", title: "Bucket과 stage 경계" },
        { id: "residency-budget", title: "Resident memory 예산" },
        { id: "release-gate", title: "Correctness-first 측정" },
      ],
      component: () => import("@/pages/articles/blockchain/msm-ntt"),
    },
    {
      slug: "filecoin-gpu-proofs",
      title: "Filecoin 증명 GPU: phase artifact와 검증 gate",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Sector에서 proof까지" },
        { id: "phase-chain", title: "Phase artifact chain" },
        { id: "parameter-binding", title: "Parameter·cache binding" },
        { id: "accelerator-split", title: "Bellperson accelerator split" },
        { id: "release-gate", title: "Deadline release gate" },
      ],
      component: () =>
        import("@/pages/articles/blockchain/filecoin-gpu-proofs"),
    },
    // ── ZK GPU 심화 ──
    {
      slug: "ec-gpu-ops",
      title: "타원곡선 GPU 연산: Fp 곱셈, 점 덧셈 CUDA 커널",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "표현부터 point output까지" },
        { id: "field-layout", title: "Field work-item layout" },
        { id: "fp-montgomery", title: "Carry와 Montgomery schedule" },
        { id: "point-ops", title: "Jacobian kernel lowering" },
        { id: "msm-mapping", title: "MSM window/group mapping" },
        { id: "release-gate", title: "Field·point parity gate" },
      ],
      component: () => import("@/pages/articles/gpu/ec-gpu-ops"),
    },
    {
      slug: "msm-gpu-impl",
      title: "MSM GPU 구현: 버킷 누적과 커널 설계",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "MSM 입력부터 결과까지" },
        { id: "work-plan", title: "Signed window 작업표" },
        { id: "bucket-ownership", title: "Bucket ownership" },
        { id: "reduction", title: "Running-sum reduction" },
        { id: "release-gate", title: "Parity·measurement gate" },
      ],
      component: () => import("@/pages/articles/gpu/msm-gpu-impl"),
    },
    {
      slug: "ntt-gpu-impl",
      title: "NTT GPU 구현: Butterfly 커널과 메모리 전략",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "NTT 호출의 전체 계약" },
        { id: "stage-tile", title: "Butterfly stage tile" },
        { id: "twiddle-contract", title: "Twiddle artifact" },
        { id: "permutation-plan", title: "Permutation·buffer plan" },
        { id: "release-gate", title: "Round-trip release gate" },
      ],
      component: () => import("@/pages/articles/gpu/ntt-gpu-impl"),
    },
    {
      slug: "gpu-proof-pipeline",
      title: "GPU 증명 파이프라인: Groth16/PLONK 전체 흐름",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Kernel 목록에서 DAG로" },
        { id: "stage-dag", title: "Proof stage dependency" },
        { id: "buffer-liveness", title: "Buffer lifetime과 peak" },
        { id: "overlap", title: "Stream overlap과 critical path" },
        { id: "release-gate", title: "Verifier-first release gate" },
      ],
      component: () => import("@/pages/articles/gpu/gpu-proof-pipeline"),
    },
    {
      slug: "icicle-framework",
      title: "ICICLE: backend·memory·primitive runtime contract",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Framework의 실제 경계" },
        { id: "backend-dispatch", title: "Backend dispatch" },
        { id: "memory-stream", title: "Memory·stream ownership" },
        { id: "primitive-config", title: "Primitive config" },
        { id: "release-gate", title: "Backend release gate" },
      ],
      component: () => import("@/pages/articles/gpu/icicle-framework"),
    },
    {
      slug: "poseidon-gpu",
      title: "Poseidon GPU: parameter artifact와 batch kernel",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Profile에서 proof root까지" },
        { id: "parameter-artifact", title: "Parameter artifact" },
        { id: "round-kernel", title: "Round kernel mapping" },
        { id: "batch-tree", title: "Batch·tree frontier" },
        { id: "release-gate", title: "Poseidon release gate" },
      ],
      component: () => import("@/pages/articles/gpu/poseidon-gpu"),
    },
    {
      slug: "poly-ops-gpu",
      title: "다항식 연산 GPU: coset NTT, 나눗셈, 다점 평가",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Polynomial workload 전체 지도" },
        { id: "form-domain", title: "Form·domain artifact" },
        { id: "coset-plan", title: "Coset NTT plan" },
        { id: "recurrence-map", title: "Horner·division dependency" },
        { id: "release-gate", title: "Representation release gate" },
      ],
      component: () => import("@/pages/articles/gpu/poly-ops-gpu"),
    },
    {
      slug: "kzg-gpu",
      title: "KZG 커밋먼트 GPU: SRS, MSM 기반 커밋, Batch Opening",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Polynomial부터 receipt까지" },
        { id: "srs-residency", title: "SRS validation·residency" },
        { id: "commit-job", title: "Commitment MSM binding" },
        { id: "opening-dag", title: "Opening job DAG" },
        { id: "release-gate", title: "Verifier-first release gate" },
      ],
      component: () => import("@/pages/articles/gpu/kzg-gpu"),
    },
    {
      slug: "ec-gpu-gen",
      title: "ec-gpu-gen: 커브별 CUDA/OpenCL 커널 자동 생성",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Type에서 artifact까지" },
        { id: "parameter-contract", title: "GpuField parameter 계약" },
        { id: "codegen", title: "Source specialization" },
        { id: "artifact-lifecycle", title: "CUDA/OpenCL artifact" },
        { id: "runtime-dispatch", title: "Program runtime dispatch" },
        { id: "release-gate", title: "Codegen release gate" },
      ],
      component: () => import("@/pages/articles/gpu/ec-gpu-gen"),
    },
    {
      slug: "rapidsnark-gpu",
      title: "rapidsnark: Groth16 GPU Prover 구현 분석",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Current CPU vs GPU boundary" },
        { id: "input-contract", title: "WTNS·zkey admission" },
        { id: "cpu-stage-map", title: "Pinned CPU stage map" },
        { id: "gpu-boundary", title: "Proposed GPU adapter" },
        { id: "release-gate", title: "Hybrid release gate" },
      ],
      component: () => import("@/pages/articles/gpu/rapidsnark-gpu"),
    },
    {
      slug: "gpu-witness-gen",
      title: "GPU Witness 생성: dataflow frontier와 검증 gate",
      subcategory: "zk-acceleration",
      sections: [
        { id: "overview", title: "Witness program의 경계" },
        { id: "dataflow-dag", title: "Signal dataflow DAG" },
        { id: "frontier-schedule", title: "Level frontier schedule" },
        { id: "residency-plan", title: "Live buffer residency" },
        { id: "release-gate", title: "Witness release gate" },
      ],
      component: () => import("@/pages/articles/gpu/gpu-witness-gen"),
    },
  ],
};

export default gpu;
