import type { CodeRef } from '@/components/code/types';

const NETWORK_BEHAVIOUR = `pub trait NetworkBehaviour: 'static {
    /// Handler for all the protocols the network behaviour supports.
    type ConnectionHandler: ConnectionHandler;

    /// Event generated by the NetworkBehaviour and that the swarm will report back.
    type ToSwarm: Send + 'static;

    /// Callback that is invoked for every new inbound connection.
    fn handle_pending_inbound_connection(
        &mut self,
        _connection_id: ConnectionId,
        _local_addr: &Multiaddr,
        _remote_addr: &Multiaddr,
    ) -> Result<(), ConnectionDenied> {
        Ok(())
    }

    /// Callback that is invoked for every established inbound connection.
    /// In order to actually use this connection, this function must
    /// return a ConnectionHandler.
    fn handle_established_inbound_connection(
        &mut self,
        _connection_id: ConnectionId,
        peer: PeerId,
        local_addr: &Multiaddr,
        remote_addr: &Multiaddr,
    ) -> Result<THandler<Self>, ConnectionDenied>;

    /// Callback that is invoked for every outbound connection attempt.
    fn handle_pending_outbound_connection(
        &mut self,
        _connection_id: ConnectionId,
        _maybe_peer: Option<PeerId>,
        _addresses: &[Multiaddr],
        _effective_role: Endpoint,
    ) -> Result<Vec<Multiaddr>, ConnectionDenied> {
        Ok(vec![])
    }

    /// Callback that is invoked for every established outbound connection.
    fn handle_established_outbound_connection(
        &mut self,
        _connection_id: ConnectionId,
        peer: PeerId,
        addr: &Multiaddr,
        role_override: Endpoint,
        port_use: PortUse,
    ) -> Result<THandler<Self>, ConnectionDenied>;

    /// Informs the behaviour about an event from the Swarm.
    fn on_swarm_event(&mut self, event: FromSwarm);

    /// Informs the behaviour about an event generated by the
    /// ConnectionHandler dedicated to the peer identified by peer_id.
    fn on_connection_handler_event(
        &mut self,
        _peer_id: PeerId,
        _connection_id: ConnectionId,
        _event: THandlerOutEvent<Self>,
    );

    /// Polls for things that swarm should do.
    fn poll(&mut self, cx: &mut Context<'_>)
        -> Poll<ToSwarm<Self::ToSwarm, THandlerInEvent<Self>>>;
}`;

export const behaviourCodeRefs: Record<string, CodeRef> = {
  'network-behaviour': {
    path: 'swarm/src/behaviour.rs — NetworkBehaviour 트레이트',
    code: NETWORK_BEHAVIOUR,
    lang: 'rust',
    highlight: [1, 67],
    annotations: [
      { lines: [4, 5], color: 'sky', note: 'ConnectionHandler 연관 타입 — 프로토콜별 핸들러' },
      { lines: [23, 29], color: 'emerald', note: '인바운드 연결 핸들러 생성' },
      { lines: [53, 60], color: 'amber', note: '이벤트 수신 — Swarm과 Handler에서 오는 이벤트 처리' },
      { lines: [65, 67], color: 'violet', note: 'ToSwarm 커맨드 생성 — Behaviour→Swarm 명령 발행' },
    ],
    desc:
`NetworkBehaviour 트레이트는 libp2p 프로토콜의 핵심 추상화입니다.

ConnectionHandler 연관 타입으로 연결당 핸들러를 지정하고,
handle_established_inbound/outbound_connection에서 핸들러 인스턴스를 생성합니다.

on_swarm_event로 연결 상태 변화를, on_connection_handler_event로
핸들러에서 올라오는 프로토콜 이벤트를 수신합니다.

poll()은 ToSwarm 열거형을 반환하여 Swarm에게 다이얼, 이벤트 전달,
연결 종료 등의 명령을 내립니다.`,
  },
};
