import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { StorageStackViz, TierPlacementViz } from "./viz/ModernStorageViz";
const SATA="https://sata-io.org/developers/sata-naming-guidelines";
const T10="https://t10.t10.org/";
const PTS="https://www.snia.org/solid-state-sss";
export default function ModernArticle(){return <article className="space-y-14">
<section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">SATA·SAS·NVMe를 고르는 순서</p><h2 className="text-3xl font-bold tracking-tight">인터페이스 순위표가 아니라 command·transport·failure domain을 workload에 배치한다</h2></header><p className="text-lg leading-8 text-foreground/90">8 TiB active data와 2 TiB scratch, 작은 metadata·log가 함께 움직이는 24시간 작업을 생각해 봅시다. Scratch는 다시 만들 수 있지만 metadata 유실은 전체 작업을 무효화할 수 있습니다. 그래서 “가장 빠른 drive” 하나를 고르지 않고 I/O shape, 쓰기 예산, 복구 비용과 failure domain을 tier마다 따로 적습니다.</p><p>NVMe form factor와 lane 경로는 <a href="/gpu/hw-nvme-storage" className="text-primary hover:underline">NVMe 정본</a>, byte/s 환산은 <a href="/gpu/gpu-interconnects#pcie-transaction-bandwidth-latency" className="text-primary hover:underline">PCIe 정본</a>을 사용합니다. 이 글은 SATA·SAS·NVMe의 command/transport/topology 계약과 workload placement만 소유합니다.</p><StorageStackViz/><ContentBoundary article="hw-storage-comparison"/></section>
<section id="io-path" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Command와 transport</p><h2 className="mt-2 text-2xl font-bold">SATA, SAS, NVMe는 queue와 연결 topology가 다르다</h2></header><p>SATA는 ATA command와 SATA link를 사용하며 NCQ(native command queuing)로 여러 명령을 대기시킬 수 있습니다. SAS는 SCSI command 생태계, dual-port와 expander topology를 server storage에 제공할 수 있습니다. NVMe는 NVM subsystem을 위한 queue 중심 protocol이며 PCIe와 fabric transport에 결합됩니다. SSD라는 매체 종류가 이 command·transport 차이를 지우지는 않습니다.</p><div id="paper-sata"><CitationBlock type="paper" citeKey={1} source="SATA-IO SATA Naming Guidelines · SATA Revision 3.x" href={SATA}><p><strong>문제:</strong> SATA revision과 transfer-rate 이름을 혼동하지 않게 합니다.</p><p><strong>핵심 기여:</strong> SATA Revision 3.x와 SATA 6Gb/s라는 정확한 명칭·rate 경계를 제시합니다.</p><p><strong>중요 가정:</strong> 실제 host/device가 협상한 link와 지원 feature를 별도로 확인합니다.</p><p><strong>근거 범위:</strong> SATA-IO가 공개한 naming·interface-rate guidance입니다.</p><p><strong>일반화 금지:</strong> 6Gb/s가 payload 750MB/s, SSD steady throughput 또는 latency를 뜻하지 않습니다.</p></CitationBlock></div><div id="paper-sas-t10"><CitationBlock type="paper" citeKey={2} source="INCITS T10 SCSI Storage Interfaces · SAS projects" href={T10}><p><strong>문제:</strong> SCSI command와 Serial Attached SCSI 표준 작업의 공식 owner를 확인합니다.</p><p><strong>핵심 기여:</strong> SAS protocol layer와 SCSI architecture의 표준·draft 경로를 제공합니다.</p><p><strong>중요 가정:</strong> 정확한 SAS/SPL/SPC revision과 vendor implementation을 pin합니다.</p><p><strong>근거 범위:</strong> T10이 관리하는 SCSI·SAS specification family입니다.</p><p><strong>일반화 금지:</strong> SAS라는 이름만으로 dual-port, multipath, drive class나 application 성능이 보장되지는 않습니다.</p></CitationBlock></div></section>
<section id="endurance-reserve" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Endurance와 reserve</p><h2 className="mt-2 text-2xl font-bold">Capacity fit과 daily write budget을 따로 계산한다</h2></header><p>DWPD(drive writes per day)는 보증 기간 동안 drive usable capacity만큼의 host write를 하루에 몇 번 허용하는지 나타내는 표기입니다. TBW(total bytes written), workload profile, sector size와 보증 조건을 실제 datasheet에서 함께 읽어야 합니다. Controller 내부 write amplification은 workload와 spare area에 따라 달라지므로 host write만으로 NAND wear를 단정하지 않습니다.</p><ExplainedFormula question="Workload의 하루 쓰기량이 drive endurance 표기와 맞는지 어떻게 검사할까?" idea={<>하루 host write bytes를 drive usable capacity로 나눠 요구 DWPD를 구하고, 같은 보증 기간·workload 조건의 rated value와 비교합니다.</>} formula={String.raw`DWPD_{req}=\frac{H_{day}}{C_{usable}}`}
annotatedFormula={String.raw`DWPD_{req}=\underbrace{\frac{H_{day}}{C_{usable}}}_{\text{기준량당 비율}}`}
operations={[
  { expression: String.raw`\frac{H_{day}}{C_{usable}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","하루 host write bytes를 drive usable","capacity로 나눠 요구 DWPD를 구하고, 같은 보증","기간·workload 조건의 rated value와"] },
]} terms={[{symbol:"DWPD_{req}",name:"필요 DWPD",description:"하루에 usable capacity 전체를 몇 번 쓴 셈인지 나타냅니다."},{symbol:"H_{day}",name:"하루 host writes",description:"Application과 filesystem이 device에 요청한 write byte입니다."},{symbol:"C_{usable}",name:"Drive usable capacity",description:"Host에서 사용할 수 있는 표기 byte capacity입니다."}]} assumptions={["동일 보증 기간과 vendor가 명시한 workload profile을 비교합니다.","Compression, dedupe, RAID와 write amplification의 측정 경계를 기록합니다."]} interpretation="3.84TB drive에 하루 1.92TB를 쓰면 0.5 DWPD가 필요합니다. 순간 burst와 power-loss protection, 실제 NAND wear는 이 비율 하나로 판단할 수 없습니다."/></section>
<section id="workload-placement" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Tier와 failure domain</p><h2 className="mt-2 text-2xl font-bold">재생성 가능한 scratch와 복구 기준인 metadata를 분리한다</h2></header><TierPlacementViz/><p>Sequential scratch는 큰 block throughput과 재생성 시간을, metadata·log는 fsync semantics와 p99 latency·power-loss recovery를, durable data는 checksum·replication·rebuild bandwidth와 서로 다른 failure domain을 우선합니다. RAID는 drive failure availability를 높일 수 있지만 controller bug, 삭제, corruption과 site loss를 막는 backup은 아닙니다.</p><ExplainedFormula question="Drive 실패 뒤 rebuild가 서비스 시간 안에 끝날지 어떻게 거칠게 계산할까?" idea={<>복구해야 할 실제 bytes를 rebuild에 지속적으로 할당할 수 있는 유효 bandwidth로 나눕니다.</>} formula={String.raw`T_{rebuild}\ge\frac{D_{recover}}{B_{rebuild,achieved}}`}
annotatedFormula={String.raw`T_{rebuild}\ge\underbrace{\frac{D_{recover}}{B_{rebuild,achieved}}}_{\text{기준량당 비율}}`}
operations={[
  { expression: String.raw`\frac{D_{recover}}{B_{rebuild,achieved}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","복구해야 할 실제 bytes를 rebuild에 지속적으로","할당할 수 있는 유효 bandwidth로 나눕니다."] },
]} terms={[{symbol:"T_{rebuild}",name:"Rebuild 시간 하한",description:"Replacement가 목표 redundancy에 돌아오기까지 걸리는 시간입니다."},{symbol:"D_{recover}",name:"복구 bytes",description:"읽고 재구성해 써야 할 실제 데이터량입니다."},{symbol:"B_{rebuild,achieved}",name:"유효 rebuild bandwidth",description:"Foreground workload와 오류를 포함해 지속된 복구 byte/s입니다."}]} assumptions={["복구량과 측정 boundary를 동일하게 두고 foreground 부하를 포함합니다.","재시도·checksum·seek·network 병목은 achieved 값에 들어갑니다."]} interpretation="8TB를 500MB/s로 지속해도 단순 하한은 약 4.4시간입니다. 이 값은 그동안 추가 실패가 없다는 보장이나 복구 후 integrity proof가 아닙니다."/></section>
<section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Fresh-drive peak를 버리고 steady state·tail·복구를 함께 측정한다</h2></header><p>Exact drive/firmware, HBA/controller, cable/backplane, filesystem, block size, queue depth, read/write mix, compressibility와 dataset fill을 pin합니다. Precondition 뒤 steady state에서 IOPS·GB/s·median/p99·CPU·power·temperature를 보고, power interruption, full device, media error, hot-plug/multipath와 rebuild 중 foreground SLO를 재생합니다. Checksum과 application oracle까지 맞지 않으면 이전 tier/BOM으로 rollback합니다.</p><div id="paper-snia-pts"><CitationBlock type="paper" citeKey={3} source="SNIA Solid State Storage Performance Test Specification 2.0.2 · 2020-10-01" href={PTS}><p><strong>문제:</strong> SSD 성능을 repeatable·comparable하게 측정할 device-level 방법을 정의합니다.</p><p><strong>핵심 기여:</strong> Purge, workload-dependent preconditioning과 steady-state IOPS·throughput·latency 시험 경계를 제공합니다.</p><p><strong>중요 가정:</strong> PTS 2.0.2, test platform과 target workload matrix를 기록합니다.</p><p><strong>근거 범위:</strong> SNIA SSS PTS의 device performance methodology입니다.</p><p><strong>일반화 금지:</strong> Device PTS 결과는 filesystem, RAID, application durability나 production tail을 자동 예측하지 않습니다.</p></CitationBlock></div></section>
</article>}
