import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { SimplexRecoveryViz, SimplexVoteViz } from "./viz/ModernCommonwareSimplexViz";

export default function ModernCommonwareSimplexArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Commonware Simplex · v2026.7.0</p><h2 className="text-3xl font-bold tracking-tight">Simplex는 payload를 notarize한 뒤 application certification을 통과한 것만 별도 finalize vote로 확정한다</h2></header>
    <p className="text-lg leading-8 text-foreground/90">네 validator 가운데 최대 한 대가 Byzantine인 <code>n=4,f=1</code> 예를 보겠습니다. View 8 leader가 Alice→Bob 10 payload <code>c8</code>를 제안하면, validator들은 parent와 건너뛴 view의 nullification evidence를 확인한 뒤 <code>notarize(c8,8)</code>를 보냅니다. 세 표가 모이면 notarization이고, application이 payload를 certify한 validator 세 곳의 finalize 표가 모여야 finalization입니다.</p>
    <p>Notarization은 “quorum이 이 digest를 지지했다”는 certificate이고, certification은 “application이 이 payload를 복구·검증해 finalization에 동의한다”는 local deterministic verdict입니다. 이름이 비슷해도 같은 단계가 아닙니다.</p><SimplexVoteViz />
  </section>
  <section id="certificate-path" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · certificate path</p><h2 className="mt-2 text-2xl font-bold">Notarize·nullify·finalize는 같은 threshold를 쓰지만 서로 다른 사실을 증명한다</h2></header>
    <ExplainedFormula question="n=3f+1에서 certificate마다 왜 2f+1명의 서로 다른 signer가 필요한가?" idea={<>서로 충돌하는 두 quorum을 만들더라도 교집합에는 적어도 f+1명이 남습니다. Byzantine이 최대 f명이므로 그중 한 명 이상은 honest이며, honest vote rule을 동시에 어길 수 없습니다.</>} formula={String.raw`\begin{aligned}q&=2f+1\\|Q_1\cap Q_2|&\ge 2q-n\\&=f+1\end{aligned}`}
    annotatedFormula={String.raw`\begin{aligned}q&=\underbrace{2\underbrace{f+1}_{\text{fault bound 계산}}}_{\text{fault bound 계산}}\\|Q_1\cap Q_2|&\ge \underbrace{2q-n}_{\text{participants 계산}}\\&=f+1\end{aligned}`}
    operations={[
      { expression: String.raw`2f+1`, annotation: ["fault bound이(가) 식의 결과에 기여하는 방식을","계산합니다.","서로 충돌하는 두 quorum을 만들더라도 교집합에는 적어도","f+1명이 남습니다."] },
      { expression: String.raw`2q-n`, annotation: ["participants이(가) 식의 결과에 기여하는 방식을","계산합니다.","서로 충돌하는 두 quorum을 만들더라도 교집합에는 적어도","f+1명이 남습니다."] },
      { expression: String.raw`f+1`, annotation: ["fault bound이(가) 식의 결과에 기여하는 방식을","계산합니다.","서로 충돌하는 두 quorum을 만들더라도 교집합에는 적어도","f+1명이 남습니다."] },
    ]} terms={[{symbol:"n",name:"participants",description:"고정 epoch committee의 validator 수입니다."},{symbol:"f",name:"fault bound",description:"Byzantine일 수 있는 최대 validator 수입니다."},{symbol:"q",name:"quorum",description:"Notarize·nullify·finalize certificate를 만드는 distinct signer 수입니다."},{symbol:"Q₁,Q₂",name:"two quorums",description:"같은 epoch·view·message type의 후보 signer sets입니다."}]} assumptions={["n=3f+1의 authenticated fixed committee를 사용합니다.","Signer index 중복과 wrong epoch/view/domain signature를 거절합니다.","Honest validator는 protocol의 phase-specific vote rule을 따릅니다.","Threshold 교집합은 payload availability나 application execution을 보장하지 않습니다."]} interpretation="n=4,f=1이면 q=3이고 두 quorum의 교집합은 최소 2명입니다. Byzantine 한 명을 빼도 honest 한 명이 남으므로 같은 phase의 conflicting certificate를 막는 기반이 됩니다." />
    <p>Leader가 없거나 advance timer가 끝나거나 payload가 영구적으로 invalid라면 validator는 <code>nullify(v)</code>를 보냅니다. Nullification 2f+1개는 view v를 건너뛸 수 있게 하지만 다른 view의 finalization을 취소하지 않습니다. 반대로 notarization 뒤 certification이 성공하면 finalize vote를 보내며, 이 vote들은 뒤 view가 timeout되어도 원래 view에 대해 계속 모일 수 있습니다.</p>
    <div id="paper-commonware-simplex"><CitationBlock source="commonware-consensus Simplex protocol docs · v2026.7.0" citeKey={1} type="code" href="https://docs.rs/commonware-consensus/2026.7.0/commonware_consensus/simplex/index.html"><p><strong>문제:</strong> Partial synchrony에서 빠른 view와 finalization을 제공하면서 invalid·unavailable payload를 application이 차단해야 합니다.</p><p><strong>기여:</strong> Notarize/nullify/finalize votes와 certificates, certification hook, gap recovery와 unchained finalization protocol을 문서화합니다.</p><p><strong>전제:</strong> v2026.7.0 exact API, authenticated n=3f+1 committee, deterministic certification과 configured timers를 사용합니다.</p><p><strong>근거 범위:</strong> Commonware Simplex implementation documentation과 해당 version의 protocol behavior에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Simplex paper의 모든 변형과 동일하거나 2·3 network hops가 임의 network의 wall-clock SLA라는 뜻은 아닙니다.</p></CitationBlock></div>
  </section>
  <section id="component-boundary" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · non-blocking components</p><h2 className="mt-2 text-2xl font-bold">Batcher는 서명을 모으고, Voter는 view를 진행하며, Resolver는 빠진 evidence를 찾는다</h2></header>
    <p>Batcher는 peer messages를 signer별로 모으고, batchable scheme에서는 quorum 후보가 될 때 lazy batch verification을 수행합니다. Invalid signature를 발견하면 모음을 반복 이분해 offending message를 찾습니다. 이 최적화는 authenticated P2P처럼 재접속 identity를 통제할 수 있을 때에만 안전한 운영 효과를 가집니다.</p>
    <p>Voter는 timer·proposal·vote state를 진행하고, Resolver는 현재 floor와 view 사이 빠진 notarization/nullification/finalization을 가져옵니다. Application의 Automaton은 payload propose·verify를, CertifiableAutomaton은 notarized payload의 certify verdict를 제공합니다. Temporary missing data를 곧바로 <code>false</code>로 끝내면 honest nodes가 서로 다른 parent를 영구 거부해 liveness를 해칠 수 있으므로 pending과 permanent rejection을 구분해야 합니다.</p>
    <div id="paper-commonware-simplex-source"><CitationBlock source="Commonware Simplex source · tag v2026.7.0 commit 5950bf7" citeKey={2} type="code" href="https://github.com/commonwarexyz/monorepo/blob/5950bf7179bb0650a57ed58b9e0478822944b335/consensus/src/simplex/mod.rs"><p><strong>문제:</strong> Vote collection·view participation·artifact recovery·application validation을 block하지 않고 연결해야 합니다.</p><p><strong>기여:</strong> Batcher, Voter, Resolver, Application 구조와 lazy verification·missing-certificate recovery를 구현·설명합니다.</p><p><strong>전제:</strong> Exact commit, selected certificate scheme, authenticated peer blocker와 configured mailbox/timeouts를 고정합니다.</p><p><strong>근거 범위:</strong> Pinned Simplex source의 component split과 message-processing rules에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Lazy verification이 signature 검증을 생략하거나 unauthenticated network에서도 peer 차단이 유지된다는 뜻은 아닙니다.</p></CitationBlock></div>
  </section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · recovery and release</p><h2 className="mt-2 text-2xl font-bold">Gap certificate와 journal을 복구한 뒤 application state까지 확인한다</h2></header>
    <SimplexRecoveryViz /><p>Restart한 validator는 durable floor와 journal을 읽고 current round를 복원합니다. View 8 notarization만 있고 certification이 끝나지 않았다면 같은 <code>(round,payload)</code> 요청이 다시 올 수 있으므로 application은 idempotent해야 합니다. View 9 proposal이 view 7 parent를 가리키면 view 8 nullification이 없이는 vote하지 않습니다.</p>
    <p>Release suite는 duplicate signer, wrong epoch/view, conflicting notarization/finalization, invalid batch signature, missing payload, certification pending, crash-before-journal과 partition recovery를 포함합니다. Safety는 지연 중 conflicting finalization 0으로, liveness는 partial synchrony가 회복된 뒤 valid leader·payload가 finalization되는지로 따로 봅니다. Client success는 finalization certificate뿐 아니라 payload execution과 durable state receipt 뒤에만 냅니다.</p>
    <h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 한 view trace, 세 certificate, n=4 threshold, certification, component 책임과 gap evidence를 묻습니다. 심화 4문제는 lazy verification 공격, nondeterministic certification, restart replay와 safety/liveness fault suite를 설계하게 합니다.</p>
  </section>
</article>}
