import type {CodeRef,FileNode,ProjectMeta} from "@/components/code/types";
import call from "./verification/main.rs?raw";
import structures from "./codebase/src/data_structures.rs?raw";
import qap from "./codebase/src/r1cs_to_qap.rs?raw";
import setup from "./codebase/src/generator.rs?raw";
import prove from "./codebase/src/prover.rs?raw";
import verify from "./codebase/src/verifier.rs?raw";
import decode from "./codebase/dependencies/ark-ec-0.6.0/src/models/short_weierstrass/affine.rs?raw";
export const codeRefs:Record<string,CodeRef>={
"call":{code:call,"path": "case/main.rs", "highlight": [13, 27], "lang": "rust", "desc": "같은 공개 3·144와 비공개 4·12를 두 곱셈 제약에 넣습니다. 원문과 구별한 실제 호출 예제입니다.", "annotations": [{"lines": [13, 27], "color": "sky", "note": "같은 공개 3·144와 비공개 4·12를 두 곱셈 제약에 넣습니다. 원문과 구별한 실제 호출 예제입니다."}]} ,
"structures":{code:structures,"path": "ark/src/data_structures.rs", "highlight": [7, 44], "lang": "rust", "desc": "증명은 G₁·G₂·G₁의 세 점이며 공개 입력은 별도 인자입니다. 확인 키에는 공개 변수별 준비점이 있습니다.", "annotations": [{"lines": [7, 44], "color": "sky", "note": "증명은 G₁·G₂·G₁의 세 점이며 공개 입력은 별도 인자입니다. 확인 키에는 공개 변수별 준비점이 있습니다."}]} ,
"qap":{code:qap,"path": "ark/src/r1cs_to_qap.rs", "highlight": [188, 254], "lang": "rust", "desc": "제약 2와 공개 자리 3을 수용하는 8개 평가점의 배열을 만들고 잉여류 FFT로 몫을 계산합니다.", "annotations": [{"lines": [188, 254], "color": "sky", "note": "제약 2와 공개 자리 3을 수용하는 8개 평가점의 배열을 만들고 잉여류 FFT로 몫을 계산합니다."}]} ,
"setup":{code:setup,"path": "ark/src/generator.rs", "highlight": [88, 123], "lang": "rust", "desc": "영역 밖의 평가점을 고르고 공개 계수는 γ로, 비공개 계수는 δ로 나누어 준비합니다.", "annotations": [{"lines": [88, 123], "color": "sky", "note": "영역 밖의 평가점을 고르고 공개 계수는 γ로, 비공개 계수는 δ로 나누어 준비합니다."}]} ,
"prove":{code:prove,"path": "ark/src/prover.rs", "highlight": [67, 144], "lang": "rust", "desc": "H·비공개 합과 sA+rB−rsδ가 C를 만듭니다. r이 0이면 C에 필요한 G₁의 B 계산을 생략합니다.", "annotations": [{"lines": [67, 144], "color": "sky", "note": "H·비공개 합과 sA+rB−rsδ가 C를 만듭니다. r이 0이면 C에 필요한 G₁의 B 계산을 생략합니다."}]} ,
"satisfaction":{code:prove,"path": "ark/src/prover.rs", "highlight": [182, 222], "lang": "rust", "desc": "만족 여부는 debug_assert로 검사합니다. 실제 불량 답안은 개발 빌드에서 panic, release에서 proof 반환 뒤 verify=false였습니다.", "annotations": [{"lines": [182, 222], "color": "sky", "note": "만족 여부는 debug_assert로 검사합니다. 실제 불량 답안은 개발 빌드에서 panic, release에서 proof 반환 뒤 verify=false였습니다."}]} ,
"inputs":{code:verify,"path": "ark/src/verifier.rs", "highlight": [22, 35], "lang": "rust", "desc": "zip에 길이 검사가 없어 [3,144,999]의 마지막 값은 무시됐습니다. 해당 고정 버전과 호출 경로의 관찰입니다.", "annotations": [{"lines": [22, 35], "color": "sky", "note": "zip에 길이 검사가 없어 [3,144,999]의 마지막 값은 무시됐습니다. 해당 고정 버전과 호출 경로의 관찰입니다."}]} ,
"verify":{code:verify,"path": "ark/src/verifier.rs", "highlight": [42, 80], "lang": "rust", "desc": "세 Miller 항과 최종 지수승 한 번을 계산해 미리 준비한 e(α,β)와 비교합니다.", "annotations": [{"lines": [42, 80], "color": "sky", "note": "세 Miller 항과 최종 지수승 한 번을 계산해 미리 준비한 e(α,β)와 비교합니다."}]} ,
"decode":{code:decode,"path": "algebra/affine.rs", "highlight": [398, 431], "lang": "rust", "desc": "검사하는 역직렬화는 곡선과 부분군을 확인합니다. 항등원의 군 유효성과 응용의 증명 판정을 구분합니다.", "annotations": [{"lines": [398, 431], "color": "sky", "note": "검사하는 역직렬화는 곡선과 부분군을 확인합니다. 항등원의 군 유효성과 응용의 증명 판정을 구분합니다."}]} ,
"wrapper":{code:call,"path": "case/main.rs", "highlight": [31, 39], "lang": "rust", "desc": "고정 BN254 압축형의 길이와 공개 입력 수를 제한하고 검사하는 역직렬화와 전체 소비를 확인하는 별도 호출 예제입니다.", "annotations": [{"lines": [31, 39], "color": "sky", "note": "고정 BN254 압축형의 길이와 공개 입력 수를 제한하고 검사하는 역직렬화와 전체 소비를 확인하는 별도 호출 예제입니다."}]} ,
};
export const fileTrees:Record<string,FileNode>={"ark": {"name": "ark-groth16 0.6.0 원문", "type": "dir", "children": [{"name": "data_structures.rs", "type": "file", "path": "ark/src/data_structures.rs", "codeKey": "structures"}, {"name": "r1cs_to_qap.rs", "type": "file", "path": "ark/src/r1cs_to_qap.rs", "codeKey": "qap"}, {"name": "generator.rs", "type": "file", "path": "ark/src/generator.rs", "codeKey": "setup"}, {"name": "prover.rs", "type": "file", "path": "ark/src/prover.rs", "codeKey": "prove"}, {"name": "verifier.rs", "type": "file", "path": "ark/src/verifier.rs", "codeKey": "inputs"}]}, "algebra": {"name": "ark-ec 0.6.0 의존 원문", "type": "dir", "children": [{"name": "affine.rs", "type": "file", "path": "algebra/affine.rs", "codeKey": "decode"}]}, "case": {"name": "별도 실행한 호출 예제", "type": "dir", "children": [{"name": "main.rs", "type": "file", "path": "case/main.rs", "codeKey": "call"}]}};
export const projectMetas:Record<string,ProjectMeta>={"ark": {"id": "ark", "label": "ark-groth16 0.6.0 원문", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}, "algebra": {"id": "algebra", "label": "ark-ec 0.6.0 의존 원문", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}, "case": {"id": "case", "label": "별도 실행한 호출 예제", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}};
