import type { PaperStudySpec } from './FoundationalPaperStudy';
import { HamrockDowson1978Lab, SkfConversionLayers2023Lab } from './viz/TribologySourceLabs';

const raw=String.raw;

export const hamrockDowson1978Spec:PaperStudySpec={
  shortTitle:'Hamrock-Dowson 1978',
  citation:'B. J. Hamrock and D. Dowson, Minimum Film Thickness in Elliptical Contacts for Different Regimes of Fluid-Film Lubrication, NASA Technical Paper 1342, October 1978, 26 PDF pages.',
  yearVenue:'1978 · NASA Lewis Research Center · NASA TP-1342',
  sourceUrl:'https://ntrs.nasa.gov/citations/19780025504',
  appendixUrl:'https://ntrs.nasa.gov/api/citations/19780025504/downloads/19780025504.pdf',
  before:'Elliptical conjunction의 hydrodynamic/EHD 연구는 여러 limiting equation에 흩어져 있었다. Contact가 circular에서 near-rectangular로 바뀔 때 viscosity-pressure and elastic-deformation influence를 하나의 읽을 수 있는 map으로 옮길 공통 좌표가 필요했다.',
  authorIntent:'저자들은 새 universal solver 하나를 제안한 것이 아니다. 자신들의 앞선 elliptical-contact 이론 결과를 네 fluid-film limiting regime의 minimum-film equations로 다시 쓰고, viscosity parameter와 elasticity parameter의 log-log plane에 contour를 조립해 입력에서 맞는 equation family를 먼저 고르게 만들었다.',
  thesis:'Elliptical fluid-film contact는 viscosity-pressure effect와 elastic deformation의 상대적 중요도로 네 regime에 놓이며, reduced dimensionless group과 ellipticity k를 알면 regime and approximate film contour를 찾은 뒤 해당 equation으로 더 정확한 minimum film을 계산할 수 있다.',
  reconstruction:[
    {label:'Dimensional contact',value:'h, u, F, R_x/R_y, E, η₀, α',note:'Film, speed, load, local geometry, solid and lubricant inputs를 선언한다.'},
    {label:'Five groups',value:'H · U · W · G · k',note:'Physical units를 지우되 각 group의 source convention을 유지한다.'},
    {label:'Reduced plane',value:'Ĥ · gV · gE · k',note:'Film contour를 viscosity and elasticity influence의 두 축에 놓는다.'},
    {label:'Four limits',value:'IR · VR · IE · VE',note:'각 regime에서 negligible effect를 제거한 equation을 선택한다.'},
    {label:'Map and return',value:'contour → regime → equation',note:'Map은 approximate location, selected equation은 final parameter calculation을 맡는다.'},
  ],
  mechanism:[
    'Physical minimum film h를 rolling-direction radius Rx로 나눠 dimensionless H를 만든다.',
    'Mean surface speed u, paper-specific combined modulus E-prime, normal load F, pressure-viscosity scale and contact ellipse k를 U/W/G/k로 묶는다.',
    'H/U/W/G를 dimensional analysis로 Ĥ, gV and gE로 줄여 contour axes를 만든다.',
    'Isoviscous-rigid는 viscosity-pressure and elasticity를, viscous-rigid는 elasticity를, isoviscous-elastic는 pressure-viscosity change를 limiting assumption에서 제거한다.',
    'Viscous-elastic equation은 둘을 모두 보존하고 34 prior theoretical cases의 fitted mean coefficient를 사용한다.',
    'k=1,2,3,4,6 map에서 approximate regime/contour를 읽은 뒤 equation 14, 19, 24 or 30으로 돌아가 minimum film parameter를 계산한다.',
  ],
  equations:[
    {latex:raw`\begin{aligned}\underbrace{H}_{\text{무차원 막 두께}}&=\underbrace{\frac{h}{R_x}}_{\text{막을 구름방향 곡률로 나눔}}\\[3pt]\underbrace{\frac1{R_x}}_{\text{결합 x곡률}}&=\underbrace{\frac1{r_{Ax}}+\frac1{r_{Bx}}}_{\text{두 물체의 국소 곡률 합}}\end{aligned}`,meaning:'논문 식 1-2. 막 두께를 구름 방향 유효 반경으로 나누어 형상이 다른 접촉을 같은 척도에서 비교한다. 국소 반경의 부호와 논문의 좌표 관례를 함께 보존해야 한다.',symbols:[[raw`H`,'Dimensionless physical film thickness'],[raw`h`,'Minimum or central physical film selected by the equation'],[raw`R_x`,'Rolling-direction effective radius']]},
    {latex:raw`\begin{aligned}\underbrace{u}_{\text{평균 표면 속도}}&=\underbrace{\frac{u_A+u_B}{2}}_{\text{두 표면 속도의 평균}}\\[3pt]\underbrace{E'}_{\text{논문의 결합 탄성계수}}&=\underbrace{\frac{2}{(1-\nu_A^2)/E_A+(1-\nu_B^2)/E_B}}_{\text{두 물체의 탄성 유연도를 결합}}\end{aligned}`,meaning:'논문 식 4-5. 원문은 E-prime을 분자 2가 들어간 관례로 정의한다. 다른 문헌의 축소 탄성계수 E-star와 비교하면 E-prime은 2E-star다. 이 차이를 놓치면 U, W, G가 모두 조용히 달라진다.',symbols:[[raw`u`,'Mean surface speed'],[raw`E'`,'Hamrock-Dowson combined modulus convention'],[raw`E_A,E_B,\nu_A,\nu_B`,'Elastic properties of the two solids']]},
    {latex:raw`\begin{aligned}\underbrace{U}_{\text{속도군}}&=\underbrace{\frac{\eta_0u}{E'R_x}}_{\text{점성 운반 대비 탄성·곡률}}&\underbrace{W}_{\text{하중군}}&=\underbrace{\frac{F}{E'R_x^2}}_{\text{곡률·탄성으로 정규화한 하중}}\\[2pt]\underbrace{G}_{\text{재료군}}&=\underbrace{\alpha E'}_{\text{압력점도와 탄성의 결합}}&\underbrace{k}_{\text{타원비}}&=\underbrace{\frac ab}_{\text{접촉 장축 대비 단축}}\end{aligned}`,latexCompact:raw`\begin{aligned}\underbrace{U}_{\text{속도군}}&=\frac{\eta_0u}{E'R_x}\\[2pt]\underbrace{W}_{\text{하중군}}&=\frac{F}{E'R_x^2}\\[2pt]\underbrace{G}_{\text{재료군}}&=\alpha E'\\[2pt]\underbrace{k}_{\text{타원비}}&=\frac ab\end{aligned}`,meaning:'논문 식 3, 6-8. 각 무차원군은 서로 다른 원인 입력 묶음을 분리한다. 섞인 정의로 그럴듯한 무차원 숫자를 재현하는 것보다 네 변수를 모두 같은 E-prime과 R_x 관례로 계산하는 것이 중요하다.',symbols:[[raw`\eta_0,\alpha`,'Ambient-pressure viscosity and pressure-viscosity coefficient'],[raw`F`,'Normal applied load'],[raw`a,b`,'Contact ellipse semimajor and semiminor axes']]},
    {latex:raw`\begin{aligned}\underbrace{\widehat H}_{\text{축약 막 변수}}&=\underbrace{H\left(\frac WU\right)^2}_{\text{하중·속도 척도 제거}}\\[3pt]\underbrace{g_V}_{\text{점성 변수}}&=\underbrace{\frac{GW^3}{U^2}}_{\text{압력점도 영향}}&\underbrace{g_E}_{\text{탄성 변수}}&=\underbrace{\frac{W^{8/3}}{U^2}}_{\text{탄성변형 영향}}\end{aligned}`,meaning:'논문 식 11-13. 차원해석으로 다섯 무차원군을 네 변수로 줄여 지도 좌표를 만든다. 이 축약은 그래프를 간결하게 만들 뿐, 원래 물리 입력과 그 불확실성을 없애지는 않는다.',symbols:[[raw`\widehat H`,'Reduced dimensionless film parameter'],[raw`g_V`,'Reduced viscosity parameter'],[raw`g_E`,'Reduced elasticity parameter']]},
    {latex:raw`\begin{aligned}\underbrace{\{\widehat H_{\min}\}_{VR}}_{\text{점성-강체 최소 막}}&=\underbrace{1.66g_V^{2/3}(1-e^{-0.68k})}_{\text{탄성 효과를 뺀 식}}\\[2pt]\underbrace{\{\widehat H_{\min}\}_{IE}}_{\text{등점성-탄성 최소 막}}&=\underbrace{8.70g_E^{0.67}(1-0.85e^{-0.31k})}_{\text{압력점도 변화를 뺀 식}}\end{aligned}`,meaning:'논문 식 19와 24. 각 한계식은 물리 효과 하나를 의도적으로 제외한다. 따라서 적용 영역 밖에서 숫자가 잘 맞아도 잘못된 모델이다. IE 계수는 앞선 이론 사례 17개에서 얻었다.',symbols:[[raw`VR,IE`,'Viscous-rigid and isoviscous-elastic regimes'],[raw`k`,'Ellipticity parameter retaining contact geometry']]},
    {latex:raw`\begin{aligned}\underbrace{\{\widehat H_{\min}\}_{VE}}_{\text{점성-탄성 최소 막}}&=\underbrace{3.42g_V^{0.49}g_E^{0.17}(1-e^{-0.68k})}_{\text{두 영향과 타원 형상}}\\[2pt]\underbrace{\{\widehat H_c\}_{VE}}_{\text{점성-탄성 중앙 막}}&=\underbrace{3.61g_V^{0.53}g_E^{0.13}(1-0.61e^{-0.73k})}_{\text{중앙 위치의 별도 적합식}}\end{aligned}`,meaning:'논문 식 30-31. 최소 막과 중앙 막은 계수, 지수, 형상 보정이 서로 다르다. 최소 막 계수 3.42는 앞선 이론 사례 34개의 산술평균이며, 논문은 표준편차를 ±0.03으로 보고했다.',symbols:[[raw`\widehat H_{\min},\widehat H_c`,'Reduced minimum and central film parameters'],[raw`VE`,'Viscous-elastic regime'],[raw`g_V,g_E,k`,'Map coordinates and contact ellipticity']]},
  ],
  mechanismViz:HamrockDowson1978Lab,
  evidence:[
    {label:'네 regime',question:'저자는 어떤 physical effects를 기준으로 solution space를 나눴는가?',intervention:'Viscosity-pressure change and elastic surface deformation를 significant/negligible의 두 축으로 조합했다.',observation:'IR, VR, IE and VE의 네 limiting regimes가 정의됐다.',supports:'하나의 EHL formula를 모든 material/contact에 쓰지 않고 equation family를 먼저 고르는 구조.',limit:'Boundary/mixed/full-film asperity regimes, thermal, starvation and wear를 분류하지 않는다.'},
    {label:'변수 축약',question:'왜 H/U/W/G/k 다섯 group을 다시 줄였는가?',intervention:'Pressure-scale reasoning과 dimensional analysis로 Ĥ/gV/gE/k를 만들었다.',observation:'Regime contour를 two-dimensional log grid plus fixed k로 표현할 수 있었다.',supports:'Map lookup and comparison을 위한 compact coordinate system.',limit:'축약 변수가 dimensional inputs, units and uncertainty를 대체하지 않는다.'},
    {label:'강체 한계',question:'Elastic deformation이 negligible하면 무엇이 남는가?',intervention:'Fully flooded isothermal isoviscous rigid study and Blok viscous-rigid relation에 ellipticity effect를 반영했다.',observation:'IR film은 geometry function, VR reduced film은 gV and k function으로 정리됐다.',supports:'Rigid regimes에서 elastic parameter를 넣지 않아야 하는 limiting logic.',limit:'High Hertz pressure, soft material or edge compliance가 큰 contact에는 rigid assumption을 먼저 검사해야 한다.'},
    {label:'탄성 한계',question:'Pressure-viscosity change가 negligible한 elastic contact는 어떻게 fitted됐는가?',intervention:'k 1-12, U and W each one order 범위의 17 theoretical cases를 사용했다.',observation:'IE minimum coefficient A mean 8.70, reported standard deviation plus/minus 0.05.',supports:'gE exponent and ellipticity form inside the simulated scope.',limit:'17 cases는 hardware experiment, grease, roughness or transient reversal evidence가 아니다.'},
    {label:'점성-탄성',question:'Viscosity and elastic effects가 모두 중요할 때 exponents는 어떻게 정해졌는가?',intervention:'k 1-8, U nearly two orders, W one order, bronze/steel/silicon nitride and paraffinic/naphthenic oils의 34 prior cases를 비교했다.',observation:'Original Hmin equation 26 and reduced equation 30; B mean 3.42, reported standard deviation plus/minus 0.03.',supports:'Declared theoretical dataset에서 VE scaling and material influence.',limit:'Coefficient scatter는 model-form, experiment, inlet supply or lubricant rheology uncertainty 전체가 아니다.'},
    {label:'지도 조립',question:'Four equations를 어떻게 continuous lookup map으로 만들었는가?',intervention:'Equations 14, 19, 24, 30을 rearrange해 boundaries and contours를 반복 계산했다.',observation:'k=1,2,3,4,6에 대해 figures 2-6, alternative axes figures 7-11 and 3D figure 12가 생성됐다.',supports:'Given k/gV/gE에서 approximate regime and H-hat contour를 찾는 절차.',limit:'Plot에서 읽은 approximate H를 final calculation처럼 쓰지 말고 selected equation으로 돌아가야 한다.'},
    {label:'저자 경계',question:'저자가 complete solution이라고 부른 범위는 어디까지인가?',intervention:'Elliptical fluid-film conjunction의 four theoretical regimes를 하나의 representation으로 결합했다.',observation:'Conclusion은 practical lubrication problems에 useful하다고 기대했다.',supports:'Smooth, fully flooded, isothermal model family 안에서의 complete film-parameter coverage.',limit:'Grease replenishment, starvation, thermal shear, roughness contact, friction, wear, life and robot release를 입증하지 않는다.'},
  ],
  implementation:[
    'Contact pair, signed Rx/Ry curvature, normal load, surface speeds, solid elastic data and lubricant η0/α를 one state record로 선언한다.',
    'Paper E-prime convention and mean speed u를 그대로 구현하고 unit tests로 E-prime equals two times common E-star를 확인한다.',
    'H/U/W/G/k and reduced Ĥ/gV/gE를 double precision으로 계산하며 original inputs and units를 result에 보존한다.',
    'k range and selected regime를 map or equation-based boundary logic로 결정하되 boundary proximity를 uncertainty로 남긴다.',
    'Minimum versus central and IR/VR/IE/VE equation identity를 enum으로 강제해 coefficient mixing을 막는다.',
    'Paper figures 2-6 topology and selected equation output를 reproduction check로 비교한다.',
    'Actual robot calculation에서는 temperature, roughness, inlet supply, transient motion and contact model validity를 별도 layers로 추가한다.',
  ],
  assumptions:[
    'Elliptical, smooth, nonconforming conjunction and source curvature convention.',
    'Isothermal fluid-film formulations assembled from earlier theoretical studies.',
    'Fully flooded inlet for the underlying film equations.',
    'Pressure-viscosity and elastic effects represented by the declared dimensionless groups.',
    'Minimum and central film equations are distinct fitted results over finite prior theoretical cases.',
  ],
  failures:[
    'Using common E-star in a formula coded for paper E-prime changes every dimensionless group.',
    'Mixing coefficient 3.42 from reduced equation 30 with U/G/W exponents from original equation 26 creates a formula that appears plausible but is not in the paper.',
    'Reading IE/VE or VR/VE map boundaries as Stribeck boundary/mixed lubrication boundaries changes the physical question.',
    'Applying fully flooded steady film at oscillation reversal hides inlet depletion and squeeze/transient behavior.',
    'A calculated film cannot prove friction, wear, contamination tolerance or bearing life without surface and system evidence.',
  ],
  legacy:'The durable contribution is not one famous coefficient. It is the separation of physical effects, dimensionless state construction and map-to-equation workflow. Modern EHL solvers add thermal, non-Newtonian, transient, roughness and starvation effects, but still need exact contact geometry, speed, load, material and lubricant identity.',
  nextReading:'Concept article로 돌아가 film estimate를 composite roughness, inlet supply, friction heat and wear evidence에 연결한다. Current company research article에서는 smooth theoretical film이 실제 running-in topography and bearing torque experiment와 어떻게 만나는지 확인한다.',
  capabilities:[
    'Hamrock-Dowson paper E-prime and common reduced-modulus conventions를 구분한다.',
    'H/U/W/G/k에서 Ĥ/gV/gE/k로 줄이는 이유와 물리적 의미를 설명한다.',
    'IR, VR, IE and VE를 boundary/mixed/full-film 분류와 혼동하지 않는다.',
    'Minimum and central film, original and reduced equations의 coefficient identity를 보존한다.',
    'Regime map이 지지하는 claim과 fully flooded theoretical boundary를 설명한다.',
  ],
};

export const skfConversionLayers2023Spec:PaperStudySpec={
  documentKind:'회사 리서치 논문',
  shortTitle:'SKF Conversion Layers 2023',
  citation:'E. Broitman, A. Ruellan, R. Meeuwenoord, D. Nijboer, V. Brizmer et al., Comparison of Various Conversion Layers for Improved Friction Performance of Railway Wheel-End Bearings, Coatings 13(12), 1980, 2023, DOI 10.3390/coatings13121980. SKF Research & Technology Development. CC BY 4.0.',
  yearVenue:'2023 · SKF Research & Technology Development · Coatings',
  sourceUrl:'https://doi.org/10.3390/coatings13121980',
  appendixUrl:'https://mdpi-res.com/d_attachment/coatings/coatings-13-01980/article_deploy/coatings-13-01980.xml',
  before:'Railway wheel-end bearing rings에는 corrosion, anti-fretting and mounting purposes의 conversion coating이 쓰였지만, different layers를 same tribological conditions에서 single contact부터 grease-lubricated bearing torque까지 연결해 비교한 evidence는 부족했다.',
  authorIntent:'저자들은 coating name ranking이 아니라 softer conversion layer를 rougher counterpart에 놓으면 running-in and asperity smoothening이 쉬워져 friction을 줄일 수 있다는 mechanism hypothesis를 시험했다. 그래서 fretting, WAM rolling/sliding and double cylindrical-roller-bearing rigs를 연결하고 hardness, roughness tracks and torque를 함께 측정했다.',
  thesis:'Tested railway-bearing conditions에서 tribological black oxide는 initial roughness를 크게 높이지 않으면서 rougher ring/disk의 running-in을 촉진해 가장 일관된 friction reduction을 보였고, application-level torque benefit의 큰 부분은 flange sliding contact에서 왔다.',
  reconstruction:[
    {label:'Surface state',value:'Steel · TBO · MnPh · ZnCaPh',note:'Microstructure, thickness, hardness and initial roughness가 다르다.'},
    {label:'Single contact',value:'Fretting + WAM raceway/flange',note:'Motion, pressure, SRR and coating placement를 isolate한다.'},
    {label:'Running-in',value:'start → end friction + track roughness',note:'Color/remaining thickness보다 topography transition을 추적한다.'},
    {label:'Bearing rig',value:'double CRB · grease · 60°C',note:'Ring coating을 load, speed, flange and grease가 있는 system에서 확인한다.'},
    {label:'Transfer gate',value:'tested domain only',note:'Railway geometry와 lubricant chemistry limit를 robot claim에 남긴다.'},
  ],
  mechanism:[
    'TBO, manganese phosphate and zinc-calcium phosphate의 microstructure, thickness and nanoindentation hardness/modulus를 uncoated steel과 비교한다.',
    'Reciprocating test에서 small-amplitude fretting friction and wear scar를 screen한다.',
    'Ball-on-disk raceway and roller-on-disk flange configurations에서 rougher coated disk versus smoother steel rolling element placement를 유지한다.',
    'Lambda 0.3 mixed-lubrication duration step의 start/end traction and post-test track roughness로 running-in hypothesis를 검사한다.',
    'Double NU2207/NJ2207 CRB setup에서 10-hour run-in, repeated speed and axial-load cycles, CW/CCW averaging으로 bearing torque를 비교한다.',
    'Single-contact coefficient, full-bearing torque, track roughness and no-increasing-torque repeat traces가 같은 mechanism story를 지지하는지 확인한다.',
  ],
  equations:[
    {latex:raw`\begin{aligned}\underbrace{u_e}_{\text{유체 운반 속도}}&=\underbrace{\frac{u_1+u_2}{2}}_{\text{두 표면 속도의 평균}}\\[3pt]\underbrace{SRR}_{\text{미끄럼 비}}&=\underbrace{\frac{2(u_1-u_2)}{u_1+u_2}}_{\text{상대속도를 평균속도로 정규화}}\end{aligned}`,meaning:'WAM은 디스크와 볼·롤러 속도를 독립적으로 제어한다. 이 재구성식은 그 설정을 유체 운반 속도와 미끄럼비로 바꾼다. 논문은 궤도 접촉에서 5%, 스핀이 포함된 플랜지 접촉에서 9.6% SRR을 보고한다.',symbols:[[raw`u_1,u_2`,'Two independently controlled surface speeds'],[raw`u_e`,'Entrainment speed'],[raw`SRR`,'Slide-to-roll ratio']]},
    {latex:raw`\begin{aligned}\underbrace{\lambda}_{\text{혼합윤활 시험 설정}}&=\underbrace{\frac{h_c}{R_q}}_{\text{중앙 막을 초기 RMS로 나눔}}\\[3pt]&=\underbrace{0.3}_{\text{지속 시험의 선언값}}\end{aligned}`,meaning:'연구는 λ를 중앙 막 두께와 RMS 거칠기의 비로 정의하고, 디스크의 초기 거칠기를 사용해 WAM 지속 시험 조건을 0.3으로 맞췄다. 이는 러닝인을 시험하기 위한 혼합윤활 조건이지 모든 베어링에 통하는 운전점이 아니다.',symbols:[[raw`h_c`,'Central film thickness used by the test definition'],[raw`R_q`,'Declared initial RMS roughness'],[raw`\lambda`,'Test lubrication parameter']]},
    {latex:raw`\begin{aligned}\underbrace{r_{track}}_{\text{주행 흔적 거칠기 비}}&=\underbrace{\frac{R_{a,track}}{R_{a,outside}}}_{\text{흔적을 바깥과 비교}}\\[3pt]\underbrace{\Delta R_a}_{\text{주행 적응 변화}}&=\underbrace{R_{a,track}-R_{a,outside}}_{\text{평탄화의 부호 있는 차이}}\end{aligned}`,meaning:'이 재구성 지표는 마찰 변화를 코팅 이름이 아니라 측정된 표면 형상 변화와 연결한다. 트랙 밖과 안의 값에는 시험 설정과 표면 식별자를 유지해야 하며, Ra와 Rq를 서로 바꿔 쓰면 안 된다.',symbols:[[raw`R_{a,track}`,'Post-test roughness inside the running track'],[raw`R_{a,outside}`,'Post-test roughness outside the track']]},
    {latex:raw`\begin{aligned}\underbrace{M^*}_{\text{정규화 베어링 토크}}&=\underbrace{\frac{M}{M_{steel,3100\,rpm,250\,N}}}_{\text{공통 강철 기준으로 나눔}}\\[3pt]\underbrace{G_M}_{\text{토크 감소율}}&=\underbrace{1-\frac{M_{coated}}{M_{steel}}}_{\text{같은 조건의 짝 비교}}\end{aligned}`,meaning:'논문은 3100 rpm, 축하중 250 N에서 무코팅 링의 측정 토크를 기준으로 베어링 토크를 정규화한다. 이 감소율은 속도, 하중, 그리스, 시험 이력이 짝지어진 조건에서만 유효하다.',symbols:[[raw`M^*`,'Normalized torque'],[raw`M_{coated},M_{steel}`,'Matched coated and baseline bearing torque'],[raw`G_M`,'Condition-specific torque reduction fraction']]},
    {latex:raw`\begin{aligned}\underbrace{\bar x}_{\text{반복 측정 평균}}&=\underbrace{\frac1n\sum_{i=1}^{n}x_i}_{\text{반복 결과를 모음}}\\[3pt]\underbrace{s_x}_{\text{반복 산포}}&=\underbrace{\sqrt{\frac{\sum_i(x_i-\bar x)^2}{n-1}}}_{\text{평균 주변의 표본 변동}}\end{aligned}`,meaning:'막대와 오차 막대는 반복 시험 또는 반복 주기에서 나온다. 평균은 선언한 반복의 중심을, 표본 표준편차는 반복성을 보여 준다. 다만 재료 로트, 전체 장비군, 환경, 모델 전이의 불확실성까지 포함하지는 않는다.',symbols:[[raw`x_i`,'One declared repeat/cycle measurement'],[raw`n`,'Number of repeats for that test state'],[raw`s_x`,'Sample standard deviation']]},
    {latex:raw`\begin{aligned}\underbrace{\mathcal D_{test}}_{\text{직접 지지하는 시험 영역}}=\{&\underbrace{P_H,u_e,SRR,\lambda,T}_{\text{접촉·운동·윤활 상태}},\\&\underbrace{L_r,L_a,n,\mathcal G,C,S}_{\text{하중·속도·형상·표면 상태}}\}\end{aligned}`,meaning:'이 집합은 방법 표에서 재구성한 명시적 전이 계약이다. 로봇 응용은 논문의 작동 원리를 가설로 사용할 수 있지만, 수치 이득은 형상·접촉·윤활·운동·온도·재료·반복 조건이 대표적임을 보인 뒤에만 옮길 수 있다.',symbols:[[raw`P_H,u_e,SRR,\lambda,T`,'Contact and lubrication state'],[raw`L_r,L_a,n,\mathcal G`,'Radial/axial load, speed and geometry'],[raw`C,S`,'Coating placement and surface topography state']]},
  ],
  mechanismViz:SkfConversionLayers2023Lab,
  evidence:[
    {label:'Rig 사다리',question:'One friction bar가 full bearing claim을 대신하지 않게 어떻게 구성했는가?',intervention:'Fretting rig, WAM ball/roller-on-disk and isolated-housing double-CRB torque rig를 사용했다.',observation:'Surface-scale friction, running-in track and application-proximate torque를 서로 다른 level에서 측정했다.',supports:'Mechanism hypothesis를 scale up하며 확인하는 evidence architecture.',limit:'Railway wheel-end bearing rig도 robot reducer/joint의 exact geometry and duty는 아니다.'},
    {label:'표면 물성',question:'Layers가 steel과 어떤 mechanical/topographic state 차이를 가졌는가?',intervention:'SEM, nanoindentation and interferometry를 coating outside/inside track에 적용했다.',observation:'Outside-track hardness was steel 8.98 GPa, TBO 2.5, MnPh 1.49, ZnCaPh 2.73; crystalline phosphate layers also increased initial roughness.',supports:'Softer layer and initial topography가 running-in response를 바꿀 mechanism basis.',limit:'Nanoindentation values alone do not predict lubricated friction or fatigue reliability.'},
    {label:'Fretting',question:'Small-amplitude sliding에서 conversion layers가 무엇을 바꿨는가?',intervention:'15.3 N, initial 1 GPa, 100 micrometre stroke, 20 Hz, 72,000 cycles를 비교했다.',observation:'After short run-in all coatings had constant friction; conversion layers had lower friction, while TBO about 1 micrometre layer was gone before test end but low friction remained.',supports:'Visual coating persistence보다 adapted track state가 friction과 연결될 수 있음.',limit:'Room-temperature dry/declared fretting configuration을 rolling bearing torque로 바로 전이할 수 없다.'},
    {label:'WAM 접촉',question:'Raceway and flange rolling/sliding에서 start-to-end friction은 어떻게 달랐는가?',intervention:'Raceway 1.3 GPa/0.5 m/s/5% SRR/70 h and flange 0.27 GPa/0.3 m/s/9.6% SRR plus spin/4.5 h, both 60 C and lambda 0.3.',observation:'TBO showed lowest friction from the start; MnPh/ZnCaPh gains depended more on running-in. TBO track Ra was 125 nm raceway and 80 nm flange versus steel 182/198 nm.',supports:'Friction reduction과 smoother running track의 co-observation.',limit:'Correlation plus mechanism discussion, not direct proof that roughness alone causes every torque difference.'},
    {label:'배치 비교',question:'왜 softer layer를 rougher counterpart에 놓는 것이 중요한가?',intervention:'Uncoated smooth balls against coated rough disks를 coated-both-sides variants와 비교했다.',observation:'Under tested conditions lower TBO/MnPh friction occurred when only the rougher disk was coated.',supports:'Hard rough surface가 soft smooth counterpart coating을 손상시키는 반대 배치를 피하는 hypothesis.',limit:'Different roughness ordering, coating adhesion, contact pressure or lubricant can reverse the result.'},
    {label:'Bearing torque',question:'Single-contact trend가 grease-lubricated double bearing에서 남았는가?',intervention:'7000 N radial load, speed 300-4500 rpm, axial 200-1000 N, 60 C, 10 h run-in and repeated CW/CCW cycles.',observation:'TBO rings consistently had lowest torque. Abstract reports up to 30% at low/intermediate intercity-relevant speeds; high axial-load cycles showed up to 75% versus uncoated with the first grease and no increasing torque over 16 repeats.',supports:'TBO benefit and strong flange contribution in that rig/domain.',limit:'Up-to-75% is not the general headline, lifetime guarantee or robot-joint multiplier; 16 cycles do not prove long fleet endurance.'},
    {label:'저자 한계',question:'Discussion이 명시적으로 남긴 open mechanism은 무엇인가?',intervention:'Mechanical interpretation used roughness, hardness, pressure and running-in comparisons.',observation:'Authors state interpretations do not include potential interaction with lubricant.',supports:'Mechanical surface-placement hypothesis inside tested lubricant states.',limit:'Additive/coating chemistry, other greases, contamination, corrosion exposure and long-term grease ageing remain outside the causal proof.'},
  ],
  implementation:[
    'Official JATS에서 authors, affiliations, Methods tables, all 14 figure captions and Conclusions를 extraction하고 figure/table IDs를 evidence ledger에 보존한다.',
    'Coating variant마다 thickness/microstructure, outside-track hardness/modulus and initial/post-track roughness를 structured record로 만든다.',
    'Fretting, WAM raceway, WAM flange and bearing rig의 pressure, motion, lubricant, temperature, duration and repeats를 separate test domains로 유지한다.',
    'Start/end traction and inside/outside roughness를 pair하고 coating placement identity를 rougher/smoother side와 함께 기록한다.',
    'Bearing torque는 exact speed/load/grease/history state에서 steel baseline과 paired normalize한다.',
    'Up-to-30 and up-to-75 claims를 서로 다른 conditions and rhetorical roles로 분리한다.',
    'Robot transfer 전 representative contact pressure, SRR/spin, roughness order, lubricant chemistry, oscillation, ingress and endurance test gap을 작성한다.',
  ],
  assumptions:[
    'AISI 52100 through-hardened steel counterparts and declared conversion processes.',
    'WAM mineral oil ISO VG32 without EP/AW additives at 60 C and declared lambda 0.3.',
    'Double CRB NU2207 plus NJ2207, railway grease and specified load/speed cycles.',
    'Track roughness and friction/torque are interpreted as linked running-in evidence within tested states.',
    'Mechanical interpretation excludes potential lubricant interaction, as stated by the authors.',
  ],
  failures:[
    'Quoting up to 75 percent as the paper-wide torque headline ignores that it came from a high axial-load comparison; the abstract headline is up to 30 percent in low/intermediate speed conditions.',
    'Treating black visual coating loss as loss of function ignores the measured adapted track and oxygen-rich residual layer discussion.',
    'Applying a soft layer to the smoother side can expose it to a harder rough counterface and produce the opposite outcome.',
    'Replacing track roughness with coating name erases why MnPh/ZnCaPh sometimes increased bearing friction.',
    'Transferring the numeric gain to an oscillating robot bearing without lubricant, geometry, pressure, SRR, seal, contamination and life tests exceeds the source evidence.',
  ],
  legacy:'The durable lesson is a research architecture: formulate a surface mechanism, isolate it at single contact, measure the topographic state transition, restore application load/grease/geometry, and preserve adverse variants. It shows why current company research can be a valuable source when Methods, repeats, negative evidence and transfer limits remain visible.',
  nextReading:'Use this paper after the Hamrock-Dowson foundation, not instead of it. Film and pressure explain the contact state; the SKF work shows running-in, placement and bearing-level torque within a specific experimental domain. The concept article then connects both to seals, contamination, thermal feedback and robot evidence.',
  capabilities:[
    'Company research의 author affiliation, product motivation and scientific evidence를 구분한다.',
    'Fretting, WAM and full-bearing rigs가 각각 닫는 claim을 설명한다.',
    'Start/end friction, inside/outside roughness and coating placement를 running-in mechanism으로 연결한다.',
    'Up-to-30 and up-to-75 results의 exact condition boundary를 보존한다.',
    'Railway bearing result를 robot joint hypothesis로 바꾸되 숫자 transfer를 test gate 뒤에 둔다.',
  ],
};
