import type { PaperStudySpec } from './FoundationalPaperStudy';
import LiuLaylandScheduleLab from './viz/LiuLaylandScheduleLab';

const raw = String.raw;

export const liuLaylandRealtimeScheduling1973Spec: PaperStudySpec = {
  shortTitle: 'Hard Real-Time Scheduling',
  citation: 'C. L. Liu and James W. Layland - Scheduling Algorithms for Multiprogramming in a Hard-Real-Time Environment',
  yearVenue: '1973 · Journal of the ACM 20(1), 46-61',
  sourceUrl: 'https://doi.org/10.1145/321738.321743',
  appendixUrl: 'https://www.cs.cmu.edu/~ssaewong/research/liu_layland.pdf',
  appendixLabel: '접근용 원문 PDF mirror',
  appendixNote: '공식 DOI의 논문 내용을 읽기 위한 공개 PDF다. 출판 기록의 권위는 DOI에 둔다.',
  before: 'Process-control computers already had multiple periodic monitoring and control functions sharing one processor, but engineers lacked a compact way to decide whether every request could receive guaranteed service before its deadline. Statistical response-time descriptions from time-sharing systems did not answer a hard-deadline question, and fixed schedules did not scale cleanly when multiple periods interacted.',
  authorIntent: 'Liu and Layland deliberately narrowed the environment until a task could be characterized by request period and maximum execution time. Inside that model they asked three precise questions: which fixed priority order is best, how much utilization is universally safe under that order, and whether dynamic deadline priorities can use the processor more fully.',
  thesis: 'For independent periodic tasks on one preemptive processor with deadline equal to period and bounded execution, the worst fixed-priority response begins at simultaneous release; shorter periods should receive higher fixed priority; the rate-monotonic universal sufficient utilization threshold is m(2^(1/m)-1); and deadline-driven scheduling is feasible exactly when total utilization does not exceed one.',
  readerBridge: [
    { term: '주기', latex: raw`T_i`, plain: '센서 읽기나 제어 계산이 다시 요청되기까지의 시간이다. 5 ms 주기라면 5 ms마다 새 일이 생긴다.', role: 'CPU가 장기적으로 얼마나 바쁜지와 다음 마감 시점을 함께 정한다.' },
    { term: '최악 실행 시간', latex: raw`C_i`, plain: '평균 실행 시간이 아니라, 드문 분기와 선점 비용까지 포함해 한 번의 요청이 CPU를 가장 오래 쓰는 시간이다.', role: '보장 문제에서는 빠른 평상시 값이 아니라 이 상한을 사용한다.' },
    { term: '마감', latex: raw`D_i`, plain: '계산이 끝나야 하는 물리적 시점이다. 원 논문은 다음 요청 시각이 곧 마감이라는 특별한 경우만 다룬다.', role: '함수 반환 시각이 아니라 PWM 반영이나 센서 소비 시각까지 무엇을 마감으로 볼지 정하게 한다.' },
    { term: '선점', plain: '더 급한 일이 도착하면 실행 중인 일을 잠시 멈추고 CPU를 넘겨주는 규칙이다.', role: '짧은 주기의 일이 긴 주기의 일을 방해하는 횟수를 계산할 수 있게 한다.' },
  ],
  reconstruction: [
    { label: 'Environment', value: 'five assumptions', note: 'Periodicity, D=T, independence, bounded execution and special aperiodic work define the theorem world.' },
    { label: 'Critical instant', value: 'simultaneous release', note: 'Move higher-priority releases earlier until they coincide with the analyzed task.' },
    { label: 'Static priority', value: 'shorter T → higher priority', note: 'Adjacent priority swaps reconstruct the rate-monotonic optimality result.' },
    { label: 'Demand threshold', value: 'RM bound / deadline driven', note: 'A universal sufficient fixed-priority threshold is separated from a dynamic-priority feasibility result.' },
  ],
  mechanism: [
    'Define hard real time as guaranteed service before a fixed elapsed time after each request, rather than an acceptable statistical distribution of response times.',
    'State five assumptions before deriving anything: hard-deadline requests are periodic; each deadline is the next request; tasks are independent; each task has constant or maximum execution time; nonperiodic initialization/recovery work is special and displaces periodic work without an ordinary hard critical deadline.',
    'Represent each periodic task tau_i by request period T_i and uninterrupted run time C_i. Use preemptive priority-driven scheduling so a newly released higher-priority task interrupts the running lower-priority task.',
    'Define overflow, feasibility, response time, critical instant and critical time zone. The analysis target becomes the longest response of a task request, not average CPU occupancy.',
    'Prove Theorem 1 by advancing every higher-priority request toward the analyzed lower-priority release. Advancing cannot make the lower task complete earlier, so all higher-priority tasks released simultaneously create a critical instant.',
    'Use the critical-instant result to compare two adjacent fixed priorities. If the longer-period task can be above the shorter-period task in a feasible ordering, swapping them preserves feasibility. Repeating adjacent swaps yields rate-monotonic order.',
    'Define utilization U as the sum of C_i/T_i. This expresses long-run CPU demand, while deadline feasibility still depends on how requests pack inside critical time zones.',
    'Construct fully utilizing task sets and minimize their utilization to find the least upper bound that guarantees every rate-monotonic task set. Theorem 5 removes the intermediate period-ratio restriction and yields m(2^(1/m)-1), approaching ln 2 as m grows.',
    'Keep the logical direction straight: below the RM threshold is sufficient; above it is inconclusive, not a proof of failure. Harmonic periods and task-specific response analysis can remain feasible above the universal bound.',
    '조화 주기는 긴 task의 period가 짧은 task period의 정수배인 경우다. 이때 높은 우선순위 job들이 경계에 가지런히 맞아 남는 CPU 조각이 덜 흩어진다. 그래서 같은 이용률이라도 period 비율에 따라 실제 schedulability가 달라진다. 이용률 합 하나는 평균 수요만 말하고, deadline 전의 간섭 배치는 critical instant와 response-time 계산이 말한다.',
    'Introduce deadline-driven priority assignment, later commonly called earliest-deadline-first: at each instant, the active request with the nearest current deadline has highest priority.',
    'Prove that no idle interval precedes an overflow under deadline-driven scheduling, then compare total demand over the common period with processor supply. Under the paper assumptions, feasibility is equivalent to sum C_i/T_i <= 1.',
    'Combine fixed-priority tasks with deadline-driven lower tasks through an availability function. The mixed result exposes a design space but does not retain the universal 100 percent property.',
    'Return to the five assumptions in the conclusion. The authors explicitly say the analysis fails when periodicity and execution bounds are unknown and suggest using the shortest request interval and longest run time as conservative design inputs.',
  ],
  equations: [
    {
      latex: raw`\underbrace{\tau_i}_{\text{periodic task}}=\underbrace{(T_i,C_i)}_{\text{request period와 최대 실행시간}}\,,\qquad\underbrace{D_i=T_i}_{\text{다음 request가 deadline}}`,
      meaning: '원 논문은 다섯 환경 가정을 먼저 선언한 뒤 task 하나를 두 숫자로 압축합니다. C_i는 bookkeeping과 선점 비용을 포함한 최대 연속 CPU 시간으로 읽을 수 있지만, blocking·jitter·task 의존성은 이 원래의 두 숫자에 들어 있지 않습니다.',
      symbols: [[raw`T_i`, 'Task i requests 사이의 constant period'], [raw`C_i`, 'Task i one request의 constant 또는 maximum processor execution'], [raw`D_i`, 'Request release에서 deadline까지의 relative interval']],
    },
    {
      latex: raw`\underbrace{t_i^{critical}}_{\text{task }i\text{의 최악 release}}:\quad\underbrace{release(\tau_i)}_{\text{분석 task}}=\underbrace{release(\tau_h)\ \forall h\in hp(i)}_{\text{모든 higher-priority task와 동시 release}}`,
      meaning: '정리 1은 분석할 task와 모든 상위 우선순위 task가 동시에 요청될 때 critical instant가 생긴다고 말합니다. 이는 고정 우선순위·독립·주기·선점 가정 안의 최악 구성입니다. 임의의 mutex blocking이나 release jitter가 있으면 확장 응답 모델이 필요합니다.',
      symbols: [[raw`hp(i)`, 'Fixed priority가 task i보다 높은 task 집합'], [raw`release(\tau)`, 'A task request가 processor scheduling에 ready가 되는 instant'], [raw`t_i^{critical}`, 'Task i response가 largest가 되는 critical instant']],
    },
    {
      latex: raw`\underbrace{T_a<T_b}_{\text{task }a\text{가 더 자주 요청}}\quad\Longrightarrow\quad\underbrace{priority(\tau_a)>priority(\tau_b)}_{\text{짧은 주기를 더 높은 고정 우선순위로}}`,
      meaning: '정리 2는 고정 우선순위 배치들 사이에서의 최적성을 보입니다. 어떤 고정 순서로 가능한 task set이면 rate-monotonic 순서로도 가능합니다. 동적 scheduler가 처리할 수 있는 모든 feasible task set을 RM도 처리한다는 뜻은 아닙니다.',
      symbols: [[raw`T_a,T_b`, 'Two periodic task request intervals'], [raw`priority(\tau)`, 'Static priority assigned once for the task']],
    },
    {
      latex: raw`\begin{aligned}\underbrace{U}_{\text{CPU 이용률}}&=\sum_{i=1}^{m}\underbrace{\frac{C_i}{T_i}}_{\text{task }i\text{의 장기 수요}}\\\underbrace{U\le U_{RM}(m)}_{\text{모든 task set의 충분조건}}&=\underbrace{m\left(2^{1/m}-1\right)}_{\text{RM 보장선}}\xrightarrow[m\to\infty]{}\underbrace{\ln2}_{\text{약 }69.3\%}\end{aligned}`,
      latexCompact: raw`\begin{aligned}U&=\sum_{i=1}^{m}\frac{C_i}{T_i}\\U\le U_{RM}(m)&=m(2^{1/m}-1)\to\ln2\end{aligned}`,
      meaning: '정리 5는 rate-monotonic 고정 우선순위 모델의 최소 상한 이용률을 줍니다. 가정 아래에서 이 부등식을 통과하면 feasibility가 보장됩니다. 반대로 넘었다는 사실은 이 값싼 충분 인증서를 잃었다는 뜻일 뿐, 실제 deadline miss를 증명하지 않습니다.',
      symbols: [[raw`m`, 'Independent periodic task count'], [raw`U`, 'Sum of execution-to-period fractions'], [raw`U_{RM}(m)`, 'Worst-case universal sufficient threshold for m RM tasks']],
    },
    {
      latex: raw`\underbrace{U_{RM}(3)}_{\text{세 task 충분조건}}=\underbrace{3\left(2^{1/3}-1\right)}_{\text{task count를 대입}}\approx\underbrace{0.78}_{\text{78\% 아래면 보장}}`,
      meaning: '원 논문은 task 세 개의 값을 보장선이 ln 2로 접근하는 예로 제시합니다. 이 78%는 권장 CPU 목표나 현대 MCU의 안전 여유가 아닙니다. ISR·lock·scheduler overhead·비주기 작업을 먼저 수요에 포함해야 합니다.',
      symbols: [[raw`3`, 'The number of periodic tasks in this numerical example'], [raw`0.78`, 'Rounded sufficient utilization threshold, not a failure boundary']],
    },
    {
      latex: raw`\begin{aligned}w_i^{(0)}&=C_i\\w_i^{(k+1)}&=\underbrace{C_i}_{\text{자기 실행}}+\underbrace{\sum_{h\in hp(i)}\left\lceil\frac{w_i^{(k)}}{T_h}\right\rceil C_h}_{\text{응답 구간에 도착하는 높은 우선순위 간섭}}\end{aligned}`,
      latexCompact: raw`\begin{aligned}w^{(0)}&=C_i\\w^{(k+1)}&=C_i+\sum_{h\in hp(i)}\left\lceil w^{(k)}/T_h\right\rceil C_h\end{aligned}`,
      provenance: '원문의 critical-time-zone 논리를 현대 fixed-point response-time 표기로 재구성',
      meaning: '원 논문의 critical-time-zone 논리를 현대적인 fixed-point response-time 표기로 옮긴 다리다. 천장함수는 응답 구간이 주기의 일부만 포함해도 그 안에 도착한 job 한 개를 온전히 세기 위해 필요하다. 값이 deadline 이하에서 고정되면 해당 task가 통과하고, deadline을 넘으면 그 우선순위 배치에서 실패한다. Blocking과 jitter가 있는 시스템에는 항을 추가해야 한다.',
      symbols: [[raw`w_i^{(k)}`, 'k번째 반복에서 추정한 task i의 응답 시간'], [raw`hp(i)`, 'Task i보다 높은 fixed-priority task 집합'], [raw`\lceil w/T_h\rceil`, '길이 w 구간 안에 task h가 release될 수 있는 최대 횟수'], [raw`C_h`, 'Higher-priority job 한 개의 최악 실행 시간']],
    },
    {
      latex: raw`\underbrace{feasible_{deadline\ driven}}_{\text{현재 마감이 가까운 요청을 먼저}}\Longleftrightarrow\underbrace{\sum_{i=1}^{m}\frac{C_i}{T_i}\le1}_{\text{주기 수요가 한 CPU의 공급 이하}}`,
      latexCompact: raw`\begin{aligned}deadline\ driven\ feasible\\[-2pt]\Longleftrightarrow\sum_{i=1}^{m}\frac{C_i}{T_i}\le1\end{aligned}`,
      meaning: '정리 7은 원래 task 가정 아래에서 deadline-driven 알고리즘의 필요충분 feasibility 결과입니다. 후대의 EDF라는 이름은 유용하지만, 실제 MCU의 overhead·blocking·비선점 구간·release jitter·제약 deadline을 빼고 100% 사용 가능하다고 읽으면 안 됩니다.',
      symbols: [[raw`deadline\ driven`, 'Highest priority goes to the active request with nearest current deadline'], [raw`1`, 'One preemptive processor’s normalized long-run capacity']],
    },
  ],
  mechanismViz: LiuLaylandScheduleLab,
  evidence: [
    {
      label: 'Environment assumptions',
      question: 'What makes it possible to characterize every hard-deadline task using only period and execution time?',
      intervention: 'Section 3 explicitly imposes five assumptions before defining the scheduling algorithms and task parameters.',
      observation: 'Requests are periodic; deadlines equal the next request; tasks are independent; each run time is constant or treated as a maximum; nonperiodic work is reserved for initialization or failure recovery and is not modeled as ordinary hard-deadline demand.',
      supports: 'Every later theorem is conditional on a deliberately simplified pure process-control environment rather than a universal property of all RTOS programs.',
      limit: 'Real firmware commonly adds release jitter, constrained deadlines, mutexes, ISR nesting, DMA/I/O wait, dependencies, caches, aperiodic faults and multiple cores.',
    },
    {
      label: 'Critical instant',
      question: 'Can the largest fixed-priority response be found without enumerating every relative phase forever?',
      intervention: 'Theorem 1 advances each higher-priority task release toward the analyzed task release and compares completion time.',
      observation: 'Advancing a higher-priority request cannot make the lower-priority task finish sooner. Repeating for every higher task produces simultaneous release and the critical time zone.',
      supports: 'A synchronous-release schedule is the correct worst-case starting point for the paper’s fixed-priority task model.',
      limit: 'The proof does not include priority inversion, self-suspension, nonpreemptive sections, arbitrary jitter or dependent task graphs.',
    },
    {
      label: 'RM priority and bound',
      question: 'Which fixed ordering is optimal and how much load is universally guaranteed?',
      intervention: 'Theorem 2 swaps adjacent priorities until shorter periods are above longer periods; Theorems 4 and 5 minimize utilization over fully utilizing task sets.',
      observation: 'Rate-monotonic ordering is optimal among fixed-priority assignments, and the least upper utilization bound is m(2^(1/m)-1), about 0.78 for three tasks and approaching ln 2.',
      supports: 'Static priority assignment and a cheap universal sufficient admission test can be derived from the periodic task structure.',
      limit: 'The utilization bound is sufficient, not exact. RM can schedule many sets above it; dynamic deadline scheduling can schedule task sets no fixed priority order can.',
    },
    {
      label: 'Deadline-driven result',
      question: 'Can dynamic current-deadline priority use all processor capacity in the same task model?',
      intervention: 'Theorems 6 and 7 show that no idle interval occurs before an overflow and compare total periodic demand with the available processor interval.',
      observation: 'Under the assumptions, deadline-driven scheduling is feasible if and only if total utilization is at most one.',
      supports: 'Dynamic priority can achieve a stronger feasibility region than the universal fixed-priority bound in the idealized model.',
      limit: 'One hundred percent is not deployable headroom. Scheduling overhead, ISR, resource blocking, dependency, execution variation and fault work consume or reshape supply.',
    },
    {
      label: 'Limits stated by the authors',
      question: 'Did the original paper itself treat aperiodic requests and variable run time as solved?',
      intervention: 'The conclusion revisits assumptions A1 and A4 and considers what happens when detailed periodicity or run-time bounds are unavailable.',
      observation: 'The authors state that none of the analytic work remains valid under the uncontrolled case and suggest conservative shortest request interval and longest run time inputs; tighter deadlines change the fixed-priority ordering toward deadline monotonic.',
      supports: 'Assumption auditing is part of the original contribution, not a modern disclaimer added after the fact.',
      limit: 'The paper does not provide current response-time analysis with blocking/jitter, multicore theory, probabilistic WCET, mixed-criticality or hardware/software co-analysis.',
    },
  ],
  workedTransfer: {
    title: '이용률 80%인 세 제어 task를 “위험”이라고 바로 버려도 될까?',
    setup: '한 코어에서 A=(T=5 ms, C=1 ms), B=(8 ms, 2 ms), C=(20 ms, 7 ms)가 선점형 rate-monotonic priority로 돈다고 하자. 세 task는 독립이고 D=T이며 blocking·jitter가 없다는 원 논문 조건만 먼저 적용한다. 이 예는 충분조건이 실패한 뒤 무엇을 해야 하는지 보여 준다.',
    steps: [
      {
        label: '싼 1차 검사',
        reasoning: '이용률은 1/5+2/8+7/20=0.80이다. 세 task의 Liu–Layland 보장선은 3(2^(1/3)-1)≈0.7798이다. 0.80이 더 크므로 universal certificate는 얻지 못한다.',
        result: '“마감 실패”가 아니라 “이 한 줄 검사로는 모름”이다.',
      },
      {
        label: '우선순위 고정',
        reasoning: '주기가 짧은 A, B, C 순으로 priority를 둔다. C가 시작되는 순간 A와 B도 동시에 release되는 critical instant를 검사하면 원 모델 안에서 C의 최악 간섭을 잡을 수 있다.',
        result: '무한한 phase 조합을 모두 돌리지 않고 최악 후보 하나로 좁힌다.',
      },
      {
        label: '응답 시간 반복',
        reasoning: 'A는 방해받지 않아 R_A=1 ms다. B는 R=2+ceil(R/5)×1을 반복해 2→3→3 ms가 된다. C는 R=7+ceil(R/5)×1+ceil(R/8)×2를 반복해 7→11→14→14 ms로 수렴한다. 각각의 1, 3, 14 ms가 마감 5, 8, 20 ms보다 작다.',
        result: '세 task가 모두 통과한다. 이 task set은 78% 보장선을 넘지만 원 모델의 RM schedule에서는 여전히 가능하다.',
      },
      {
        label: '짧은 그림의 함정',
        reasoning: '0~20 ms 그림만 보고 끝내면 16 ms에 release된 B의 다음 job과 20 ms 경계에서 생기는 새 job이 아직 남아 있을 수 있다. 화면 끝은 deadline도, hyperperiod 종료도 아니다. 따라서 Viz는 남은 ready job을 따로 표시하고 20~40 ms 구간도 이어서 보여 준다.',
        result: '“그림에 miss가 안 보인다”보다 task별 최악 응답시간이 deadline 안에 고정되는지가 더 강한 판정이다.',
      },
      {
        label: '현실 계약 복원',
        reasoning: '실제 MCU라면 mutex blocking B_i, release jitter J_i, ISR, flash/cache 상태와 scheduler overhead를 식에 넣어야 한다. 제어 함수가 14 ms 안에 끝나도 PWM latch가 늦으면 물리적 마감은 놓칠 수 있다.',
        result: '정리는 출발점이고, 측정한 WCET와 실제 출력 반영 trace가 최종 증거다.',
      },
    ],
    decision: '80%라는 숫자만으로 승인하거나 거절하지 않는다. 먼저 값싼 충분조건을 쓰고, 실패하면 critical instant와 task별 response-time 분석으로 내려간 뒤 hardware trace에서 마감을 닫는다.',
    boundary: '이 결론은 독립 periodic task, D=T, single preemptive CPU라는 바닥에서만 성립한다. Lock, dependency, self-suspension, multicore 또는 fault-recovery task가 보이면 이 논문의 식에 억지로 끼우지 말고 해당 확장 분석으로 이동한다.',
  },
  implementation: [
    'List every safety-relevant MCU execution entity: timer/ADC/encoder ISR, DMA completion, current/velocity/position tasks, fieldbus, diagnostics, watchdog, logging and fault recovery.',
    'For each periodic entity record hardware release source, T, physical D, measured/validated C, release jitter J, priority, stack and resources. Do not default D to T without locating the physical latch/fault deadline.',
    'Map interrupt priorities separately from RTOS task priorities and add the maximum higher-IRQ delay and ISR execution to task release or execution demand.',
    'Replace average execution with an upper bound covering input-dependent branches, compiler/optimization, flash/cache/memory state, nested interrupts, tracing and context switches.',
    'Audit Liu–Layland assumptions one by one. Classify dependencies, locks, self-suspension, aperiodic faults, multicore and constrained deadlines as model extensions rather than silent details.',
    'For the subset that matches the original assumptions, assign shorter periods higher fixed priority and compute U and the m-task RM sufficient threshold.',
    'Treat U above the threshold as inconclusive. Run exact fixed-priority response-time iteration with blocking/jitter or a schedule-specific analysis rather than rejecting by folklore.',
    'If evaluating EDF/deadline-driven scheduling, include runtime priority-queue cost, nonpreemptive regions, ISR demand, constrained deadlines and overload behavior before using U<=1.',
    'Construct the critical simultaneous-release fixture and compare analytical completion times with a cycle-accurate or traceable scheduler harness.',
    'Inject the declared maximum release jitter, lock hold, interrupt nesting and bus delay; confirm the extended response model contains every observed completion.',
    'Measure actual PWM latch and applied sequence rather than treating task function return as actuator completion.',
    'Keep headroom and a fault policy even after a proof passes: late/missing input, WCET overrun, stack fault and driver trip must close PWM independently of schedule admission.',
  ],
  assumptions: [
    'All ordinary hard-deadline requests are periodic with constant request interval.',
    'Each request deadline occurs at the next request, so D_i equals T_i.',
    'Tasks are independent; their requests do not depend on initiation or completion of other tasks.',
    'Each task has a constant execution time or a trustworthy maximum uninterrupted execution time including modeled overhead.',
    'Nonperiodic initialization and recovery routines are special and are not ordinary hard-critical deadline tasks in the analyzed set.',
    'One processor runs a preemptive priority-driven scheduler; the original results do not model multicore execution or shared-resource blocking.',
  ],
  failures: [
    'Using m(2^(1/m)-1) as a target CPU percentage without checking the five assumptions turns a sufficient theorem into an unsafe rule of thumb.',
    'Rejecting every RM task set above the bound wastes feasible systems; the bound is not a necessary condition.',
    'Claiming EDF safely supports 100 percent real CPU utilization ignores dispatcher cost, ISR, locks, nonpreemptive drivers, cache/memory contention and recovery work.',
    'Treating average task time or one observed maximum as C_i hides rare branches, logging, fault handling and worst memory state.',
    'A lower-priority mutex owner can block a higher task; unrelated medium work can extend the block unless a bounded resource protocol is modeled.',
    'ADC/DMA/fieldbus jobs released with jitter can create more higher-priority interference than the synchronous zero-jitter model predicts.',
    'Task dependencies, pipelines and self-suspension violate independence and can make utilization alone miss cause-effect latency.',
    'SMP/AMP execution changes interference and resource semantics; a single-core RM/EDF proof cannot be copied to a multicore MCU.',
    'A schedulable software task set can still apply stale identity, wrong units, numerically overflowed output or unsafe power because functional correctness is outside the theorem.',
  ],
  legacy: 'The paper’s durable contribution is not the folklore number 69 percent. It is the method: declare a task model, locate the worst release pattern, derive priority and feasibility results inside that model, and revisit the assumptions before deployment. Modern response-time analysis adds blocking, jitter, constrained deadlines, nonpreemptive sections, servers, multicore and richer workload models, but still depends on the same discipline of separating theorem inputs from measured averages and physical consequences.',
  nextReading: 'Next read Sha, Rajkumar and Lehoczky on priority inheritance and priority-ceiling protocols to add bounded resource sharing to fixed-priority response. Then connect Giotto/Logical Execution Time to deterministic data age, and finally descend into Park/Clarke transforms, FOC current loops, inverter timing and hardware protection.',
  nextLinks: [
    { slug: 'robot-embedded-realtime-control', label: 'Robot Embedded Real-Time Control로 돌아가기', reason: '원 논문의 T·C·D 모델에 ISR, jitter, blocking, DMA와 실제 PWM latch를 다시 붙여 production task contract를 완성한다.' },
  ],
  capabilities: [
    'State the five Liu–Layland environment assumptions before using any result.',
    'Explain why simultaneous release is the critical instant for the original fixed-priority task model.',
    'Distinguish RM optimality among fixed-priority assignments from global scheduling optimality.',
    'Compute utilization and the m-task RM sufficient threshold without treating a failed bound as a deadline miss.',
    'Explain why harmonic task periods can achieve higher feasible utilization than the universal threshold.',
    'Read deadline-driven/EDF U<=1 as a conditional theorem rather than practical 100 percent headroom.',
    'Separate theoretical feasibility, finite schedule trace, measured WCET evidence and physical PWM latch evidence.',
    'Identify ISR, blocking, jitter, dependencies, aperiodic work and multicore as explicit model extensions.',
    'Turn an MCU task list into an auditable scheduling contract with T, C, D, J, B, priority, stack and resources.',
  ],
};
