import type { PaperStudySpec } from './FoundationalPaperStudy';
import { WilliamsonSeaLab } from './viz/ActuatorSourceLabs';

const raw = String.raw;

export const williamsonSeriesElasticActuators1995Spec: PaperStudySpec = {
  documentKind: '석사 논문·AI Technical Report',
  shortTitle: 'Series Elastic Actuators',
  citation: 'Matthew M. Williamson, “Series Elastic Actuators,” MIT Artificial Intelligence Laboratory Technical Report 1524 / M.S. thesis, January 1995.',
  yearVenue: '1995 · MIT AI Laboratory',
  sourceUrl: 'https://hdl.handle.net/1721.1/6776',
  appendixUrl: 'https://bitsavers.trailing-edge.com/pdf/mit/ai/aim/AITR-1524.pdf',
  before: 'Geared robot actuators were commonly pushed toward high stiffness and position bandwidth. The same gear train reflected motor inertia and transmitted friction, backlash, torque ripple and impact to the environment; accurate low-impedance force interaction remained difficult.',
  authorIntent: 'Williamson은 “더 단단할수록 더 좋은 actuator”라는 default를 뒤집습니다. Gearbox와 load 사이에 측정 가능한 spring을 일부러 넣으면 spring deflection으로 force를 제어하고, high-frequency shock와 gearbox nonlinearity가 output으로 곧장 전달되는 경로를 약화할 수 있는지 model, performance limits and hardware experiments로 검증하려 했습니다.',
  thesis: 'A deliberately compliant series element can trade maximum force and bandwidth for better low-frequency force control, lower high-frequency output impedance, shock tolerance and filtering of friction/backlash/torque ripple; the trade must be evaluated with motor current/velocity saturation and measured plant mismatch rather than an ideal spring model alone.',
  readerBridge: [
    { term: '직렬 탄성', plain: '모터와 부하 사이 힘 전달 경로에 스프링을 일부러 넣는 설계다. 고장을 뜻하는 헐거움과 다르다.', role: '충격을 바로 전달하지 않고, 변형량을 힘 센서처럼 쓰게 한다.' },
    { term: '출력 임피던스', latex: raw`Z(s)`, plain: '환경이 관절을 움직이려 할 때 actuator가 얼마나 큰 반대 토크를 만드는지를 주파수별로 나타낸다.', role: '위치가 단단한가와 사람·환경 접촉에 부드럽게 반응하는가를 분리한다.' },
    { term: '고유 주파수', latex: raw`\omega_n`, plain: '모터 쪽 관성과 스프링이 가장 쉽게 흔들리는 속도다.', role: '힘 제어 bandwidth와 진동 위험을 하나의 stiffness 숫자만으로 정하지 않게 한다.' },
    { term: '포화', plain: '제어기가 원하는 토크나 속도를 모터·전압·전류 한계 때문에 더 이상 만들지 못하는 상태다.', role: '이상적인 전달 함수가 맞아도 실제 힘 추종이 무너지는 조건을 드러낸다.' },
  ],
  reconstruction: [
    { label: 'Stiff geared actuator', value: 'Motor → gearbox → load', note: 'High position bandwidth, but reflected inertia·friction·backlash·impact reach the environment.' },
    { label: 'Series elastic element', value: 'Motor → gear → spring → load', note: 'The spring becomes both a mechanical filter and a force-sensing state.' },
    { label: 'Force estimate', value: 'Tₗ = kₛ(θₘ − θₗ)', note: 'Relative deformation converts to output torque under a calibrated elastic model.' },
    { label: 'Control + limits', value: 'Feedforward + servo + saturation', note: 'Force tracking must coexist with current, velocity, voltage and stability constraints.' },
    { label: 'Measured evidence', value: 'Sweep sine → contact tests', note: 'Ideal response is compared with stiction, clipping, phase lag, backlash and moving output.' },
  ],
  mechanism: [
    'Start from the physical series path: motor/gear inertia Jm moves motor-side angle theta_m, the load moves theta_l, and the spring deflection between them creates output torque.',
    'Apply Newton’s law to the motor inertia and spring. Keep the author’s torque-direction convention visible before transforming to Laplace form.',
    'Clamp the output only as one experiment. The resulting force transfer exposes the motor–spring natural frequency but cannot explain a moving environment.',
    'Define output impedance as output torque divided by imposed output motion. Low output impedance is an interaction objective distinct from high position stiffness.',
    'Add feedforward and a force servo, then check passivity/stability against possible environments rather than tuning one free-space response.',
    'Apply motor current/torque and velocity/voltage saturation. The spring requires extra motor motion to generate force, so compliance can help or hurt depending on frequency and desired impedance.',
    'Identify the built hardware with sweep-sine data and compare fitted and theoretical transfer functions. Treat discrepancies as evidence about omitted inertia, stiction, scaling and electronics.',
    'Test hard contact, soft contact and moving output. Preserve where feedforward, noise, clipping and backlash make measured behavior worse than the simple model.',
  ],
  equations: [
    {
      latex: raw`\underbrace{T_m}_{\text{모터가 가한 토크}}+\underbrace{k_s(\theta_l-\theta_m)}_{\text{모터를 되미는 스프링 토크}}=\underbrace{J_m\ddot\theta_m}_{\text{모터 쪽 관성 가속}}`,
      meaning: 'Thesis Eq. 3.1의 motor-side Newton equation입니다. Spring torque sign은 theta_m과 theta_l의 declared directions에 묶입니다. Gearbox and spring moving inertia를 Jm에 포함한 정도가 measurement와 model agreement를 바꿉니다.',
      symbols: [[raw`T_m`, 'Motor/gear side applied torque [N·m]'], [raw`k_s`, 'Series spring torsional stiffness [N·m/rad]'], [raw`\theta_m,\theta_l`, 'Motor-side and load-side angles [rad]'], [raw`J_m`, 'Motor-side equivalent moving inertia [kg·m²]']],
    },
    {
      latex: raw`\underbrace{T_l}_{\text{출력 토크}}=-\underbrace{k_s(\theta_l-\theta_m)}_{\text{출력에 전달된 스프링 토크}}=\underbrace{k_s(\theta_m-\theta_l)}_{\text{상대 변형으로 측정}}`,
      meaning: 'Thesis Eq. 3.2의 spring/output relation을 equivalent sign form으로 썼습니다. Force sensing이 별도 load cell 없이 가능해지는 핵심이지만 spring calibration, hysteresis, sensor alignment and non-spring deformation을 무시하면 torque estimate가 biased합니다.',
      symbols: [[raw`T_l`, 'Load/output torque under the thesis direction convention [N·m]'], [raw`\theta_m-\theta_l`, 'Series spring relative deformation [rad]'], [raw`k_s`, 'Calibrated series spring stiffness [N·m/rad]']],
    },
    {
      latex: raw`\underbrace{T_m(s)}_{\text{필요 모터 토크}}=\underbrace{\left(1+\frac{J_m}{k_s}s^2\right)T_l(s)}_{\text{원하는 출력 토크와 스프링 감기}}+\underbrace{J_ms^2\theta_l(s)}_{\text{움직이는 출력을 따라가는 관성 토크}}`,
      meaning: 'Thesis Eq. 3.3입니다. Desired output force를 만들기 위한 motor motion과 moving output을 따라가기 위한 motion이 합쳐집니다. 이 식 때문에 elastic actuator의 force bandwidth는 spring alone가 아니라 environment motion과 motor velocity/current limits에 따라 달라집니다.',
      symbols: [[raw`s`, 'Laplace complex frequency [s⁻¹]'], [raw`T_m,T_l`, 'Motor and load torque transforms'], [raw`\theta_l`, 'Output motion transform'], [raw`J_m/k_s`, 'Motor–spring time-scale squared']],
    },
    {
      latex: raw`\left.\frac{T_l}{T_m}(s)\right|_{\dot\theta_l=0}=\underbrace{\frac1{1+s^2J_m/k_s}}_{\text{출력을 고정한 힘 전달 함수}}`,
      meaning: 'Thesis Eq. 3.4의 clamped-output transfer입니다. Imaginary-axis poles를 가진 ideal undamped second-order form이며 실제 hardware에는 damping, friction, electronics and omitted inertia가 들어갑니다. Clamped condition을 soft or moving contact에 그대로 전이하지 않습니다.',
      symbols: [[raw`T_l/T_m`, 'Motor torque to output torque transfer'], [raw`\dot\theta_l=0`, 'Output shaft clamped condition'], [raw`J_m/k_s`, 'Natural-frequency-setting ratio [s²]']],
    },
    {
      latex: raw`\underbrace{\omega_n}_{\text{모터와 스프링의 고유 각주파수}}=\sqrt{\frac{\underbrace{k_s}_{\text{스프링 강성}}}{\underbrace{J_m}_{\text{모터 쪽 등가 관성}}}}`,
      meaning: 'Ideal clamped model의 natural frequency입니다. Thesis measurement에서 quoted rotor inertia alone가 predicted frequency를 설명하지 못했고 gearbox/spring inertia를 포함한 effective Jm이 필요했습니다. 이는 catalog inertia와 assembled plant identification을 구분해야 하는 직접 evidence입니다.',
      symbols: [[raw`\omega_n`, 'Ideal clamped natural angular frequency [rad/s]'], [raw`k_s`, 'Series stiffness [N·m/rad]'], [raw`J_m`, 'Effective motor/gear/spring-side inertia [kg·m²]']],
    },
    {
      latex: raw`\underbrace{Z(s)}_{\text{출력에서 본 기계 임피던스}}=\frac{\underbrace{T_l(s)}_{\text{환경에 가한 토크}}}{\underbrace{\theta_l(s)}_{\text{환경이 만든 출력 운동}}}=\underbrace{\frac{-s^2J_m}{1+s^2J_m/k_s}}_{\text{이상 모델의 출력 저항}}`,
      latexCompact: raw`\begin{aligned}Z(s)&=\frac{T_l(s)}{\theta_l(s)}\\&=\frac{-s^2J_m}{1+s^2J_m/k_s}\end{aligned}`,
      meaning: 'Thesis가 output motion에 대한 resisting torque로 정의한 impedance transfer입니다. Negative sign은 torque and motion directions의 convention에서 옵니다. Low impedance claim은 frequency-dependent하며 contact stability, controller and sensor dynamics를 포함해 검증해야 합니다.',
      symbols: [[raw`Z(s)`, 'Output mechanical impedance in torque/angle form'], [raw`T_l(s)`, 'Output torque transform'], [raw`\theta_l(s)`, 'Imposed output angle transform'], [raw`J_m,k_s`, 'Ideal plant inertia and stiffness']],
    },
  ],
  mechanismViz: WilliamsonSeaLab,
  evidence: [
    {
      label: '이상 모델',
      question: 'Series spring은 motor torque를 output force로 어떤 dynamics를 거쳐 전달하는가?',
      intervention: 'PDF pp. 23–25에서 Jm, ks, theta_m, theta_l, Tm, Tl의 minimal model을 세우고 output을 clamp한 transfer와 output impedance를 유도한다.',
      observation: 'Force transfer는 zeros 없이 motor–spring natural frequency의 second-order poles를 가지며, output motion은 motor torque demand에 별도 inertial term으로 들어간다.',
      supports: 'Spring deflection force sensing과 bandwidth/impedance trade의 calculable baseline을 지지한다.',
      limit: 'Undamped linear spring, concentrated inertia and ideal sensing/electronics가 actual gearbox friction, backlash, saturation and structural modes를 포함하지 않는다.',
    },
    {
      label: '성능 한계',
      question: 'Compliance는 모든 frequency에서 force control을 개선하는가?',
      intervention: 'PDF pp. 31–40에서 stiff and elastic actuators를 current/torque saturation and velocity/voltage saturation 아래 비교한다.',
      observation: 'Spring을 감기 위한 extra motor motion이 desired force and output motion의 phase에 따라 constructive or destructive하게 작용하며 natural frequency 전후의 feasible force/impedance envelope가 달라진다.',
      supports: 'Elasticity가 unconditional improvement가 아니라 frequency, desired impedance and motor limits에 따른 trade라는 명제를 지지한다.',
      limit: 'Simple saturation envelope가 thermal duty, nonlinear drive electronics and multi-axis robot constraints를 모두 포함하지 않는다.',
    },
    {
      label: '식별 불일치',
      question: 'Theoretical motor–spring transfer가 built actuator의 frequency response를 정확히 예측하는가?',
      intervention: 'PDF pp. 59–65에서 sweep-sine identification으로 force transfer and impedance를 측정하고 fitted second-order model과 theory를 비교한다.',
      observation: 'Measured low-frequency gain and phase lag differ; stiction and clipped current are suspected. Measured natural frequency implies more inertia than quoted motor inertia because gearbox and spring inertia were omitted.',
      supports: 'Model의 qualitative shape와 natural-mode origin을 지지하면서 effective inertia and nonlinearity identification 필요성을 보여준다.',
      limit: 'A fitted transfer at one hardware configuration does not identify every friction source or transfer to another actuator geometry.',
    },
    {
      label: '과한 feedforward',
      question: 'Model-based feedforward를 높이면 tracking error가 항상 줄어드는가?',
      intervention: 'PDF pp. 65–68에서 closed-loop response and different feedforward gains를 compare한다.',
      observation: 'Excess feedforward can worsen measured response as noise, phase/model error and current saturation become significant.',
      supports: 'Feedforward term is only as reliable as model, scaling and actuator headroom.',
      limit: 'One controller architecture does not bound modern robust, adaptive or disturbance-observer designs.',
    },
    {
      label: 'Contact 실험',
      question: 'Force controller는 hard and soft environments and moving output에서도 useful response를 유지하는가?',
      intervention: 'PDF pp. 68–69의 square/sine force experiments compare hard contact, soft contact and moving output conditions.',
      observation: 'The actuator tracks low-frequency force across multiple contacts, while transient shape and motion coupling vary with the environment.',
      supports: 'Series elasticity can support interaction force control beyond a single clamped bench transfer.',
      limit: 'The experiments do not establish arbitrary contact stability, modern safety, long-duration life or multi-axis manipulation performance.',
    },
    {
      label: '저자의 한계',
      question: 'Thesis conclusion이 어떤 disadvantages and unfinished work를 직접 인정하는가?',
      intervention: 'PDF pp. 74, 77–78에서 theoretical/actual comparison, conclusion and future work를 함께 읽는다.',
      observation: 'Benefits include force control, shock isolation and filtering of friction/backlash/torque ripple; disadvantages include maximum force, bandwidth, bulk and complexity, while efficiency, backlash, electronics and design optimization remain future work.',
      supports: 'The contribution is a bounded actuator architecture and trade analysis, not a claim that compliance dominates every design.',
      limit: 'Later SEA, variable-stiffness, torque-sensor and direct-drive research must be read separately rather than projected backward into 1995.',
    },
  ],
  workedTransfer: {
    title: '20 N·m 접촉 힘을 잘 재려면 스프링을 더 부드럽게 만들수록 좋을까?',
    setup: '출력측 torsional spring이 1000 N·m/rad이고 motor-side 등가 관성이 0.025 kg·m²인 관절을 생각하자. 목표 접촉 토크는 20 N·m다. Encoder는 motor와 load 양쪽에 있지만 reducer lost motion과 timestamp 오차가 있다.',
    steps: [
      {
        label: '필요 변형',
        reasoning: '이상적인 선형 spring에서는 Δθ=T/k=20/1000=0.02 rad, 약 1.15°가 필요하다. 이 변형은 측정하기 쉬울 수 있지만 motor가 그만큼 더 움직여야 하고 package travel도 소비한다.',
        result: '작은 k는 센서 분해능만 좋아지는 선택이 아니라 motor motion과 공간을 함께 요구한다.',
      },
      {
        label: '동역학 위치',
        reasoning: '이상 clamped model의 고유 각주파수는 sqrt(1000/0.025)=200 rad/s, 약 31.8 Hz다. 원하는 힘 변화가 이 근처로 가면 phase와 amplitude가 급격히 달라지고 실제 damping·friction이 결과를 좌우한다.',
        result: '힘 bandwidth 목표를 먼저 놓고 spring과 effective inertia를 함께 선택해야 한다.',
      },
      {
        label: '움직이는 환경',
        reasoning: '부하가 움직이면 motor는 spring을 감는 일뿐 아니라 J_m s²θ_l 항에 해당하는 관성 운동도 따라가야 한다. 빠른 접촉면이나 보행 충격에서는 current와 motor velocity 한계가 먼저 닫힐 수 있다.',
        result: '고정 벽에서 잘 된 힘 제어를 움직이는 사람·지면 접촉에 그대로 전이하지 않는다.',
      },
      {
        label: '측정 분리',
        reasoning: '20 N·m를 계산한 0.02 rad 안에는 spring deformation만 있어야 한다. Reducer backlash, housing/link bending, encoder offset와 비동기 sample이 섞이면 kΔθ는 그럴듯하지만 틀린 torque를 낸다. Load cell과 sweep test로 bias와 mode를 분리한다.',
        result: 'Spring calibration과 plant identification이 controller tuning보다 먼저다.',
      },
    ],
    decision: '이 stiffness를 채택하려면 20 N·m 변형 범위, 약 31.8 Hz 주변의 measured response, motor current·velocity envelope와 hard/soft/moving contact 안정성을 모두 통과시킨다. 단순히 “부드러우면 안전하다”로 선택하지 않는다.',
    boundary: '1995 thesis의 최소 모델은 architecture trade를 설명하는 바닥이다. 현대 관절의 reducer hysteresis, digital delay, nonlinear spring, output bearing, thermal duty, brake handover와 사람 안전 claim은 별도 모델·시험으로 올라가야 한다.',
  },
  implementation: [
    'Recreate the physical model with an explicit sign convention and units. Put motor/gear/spring moving inertia in Jm and keep load motion theta_l as an external input before clamping anything.',
    'Implement spring torque from relative encoder angle and inject zero offset, stiffness error, backlash and sensor noise one at a time. Compare estimated torque with a load-cell ground truth.',
    'Verify the clamped transfer with a low-amplitude sweep that stays below current/velocity saturation. Estimate natural frequency and damping from the response rather than forcing the theoretical value.',
    'Repeat identification with gearbox and spring inertia added. Record whether the measured natural frequency moves toward the reconstructed model.',
    'Implement force feedback and bounded feedforward. Log current command, motor velocity, spring deflection, output motion, saturation state and force error on the same clock.',
    'Sweep desired force and environment motion below, near and above the motor–spring natural frequency. Map feasible force against desired output impedance.',
    'Test clamped/hard, soft and moving environments with conservative energy and safety limits. Do not infer free-space stability from contact response or vice versa.',
    'Increase feedforward until error first improves and then degrades. Attribute the transition using noise, phase, clipping and model residual rather than reporting one best gain.',
    'Preserve theory and measurement as separate artifacts: predicted transfer, fitted transfer, raw frequency response and time-domain contact traces.',
    'For a modern robot, add reducer lost motion, full two-inertia/load dynamics, thermal duty, output bearing, brake handover and digital delay before calling the reconstruction deployable.',
  ],
  assumptions: [
    'The series elastic element has a calibrated, sufficiently repeatable torque–deflection relation over the operating range.',
    'Motor-side and load-side motions are measured with aligned sign, scale and timing.',
    'The minimal clamped model treats the motor/gear/spring moving mass as one effective inertia and ignores higher structural modes.',
    'Linear transfer analysis applies only while current, velocity/voltage and spring-yield constraints are inactive.',
    'Output impedance and contact stability depend on the declared torque/motion direction convention and environment class.',
    'The 1995 analog/digital hardware, fixed-point measurement and gearbox are not equivalent to a modern torque-controlled robot joint.',
  ],
  failures: [
    'Making the spring arbitrarily soft lowers high-frequency impedance but can exceed motor travel/velocity, reduce force bandwidth and consume package space.',
    'Using quoted rotor inertia alone shifts the predicted natural frequency because gearbox, spring and coupling inertia remain unmodeled.',
    'Stiction, backlash and current clipping alter low-frequency gain and phase even when the second-order response shape looks plausible.',
    'Aggressive feedforward amplifies model error and noise and can drive current saturation, so lower nominal error does not guarantee better contact behavior.',
    'A clamped-output transfer omits environment motion; a moving load adds Jm s² theta_l demand and can consume motor headroom.',
    'Treating spring deflection as pure torque ignores mounting/link compliance, hysteresis, encoder timing and off-axis loads.',
    'Calling compliance “safe” without brake, bearing, structural, impact-energy and functional-safety evidence exceeds the thesis scope.',
  ],
  legacy: 'Williamson’s durable contribution is not merely putting a spring in a joint. The thesis reframed actuator quality around controllable force and output impedance, made intentional deformation observable, and evaluated the design against motor saturation and real contact. It also left a valuable negative result: the simple motor–spring transfer gets the shape right but stiction, clipped current, omitted inertia, backlash and electronics decide whether the implementation matches. Modern SEA and torque-controlled robot joints inherit this architecture-level trade even when sensors, motors and controllers are much better.',
  nextReading: 'Return to Robot Actuator Mechanics to place the SEA inside ratio, reflected inertia, output-bearing and brake constraints. Multi-link flexible dynamics and modern variable-stiffness work are later branches that extend this thesis, not results that should be silently attributed to it.',
  nextLinks: [{ slug: 'robot-actuator-mechanics-transmission-holding-brake', label: 'Robot Actuator Mechanics로 돌아가기', reason: 'SEA의 의도적 compliance를 감속비, 반사 관성, 출력 베어링, lost motion과 holding brake를 포함한 전체 joint 계약에 배치한다.' }],
  capabilities: [
    'Explain why deliberate series compliance can improve force control while reducing position/force bandwidth.',
    'Derive motor torque balance, spring force, clamped force transfer, natural frequency and output impedance under explicit signs.',
    'State why output motion adds motor demand and interacts with current/velocity saturation.',
    'Distinguish ideal transfer-function evidence from identified plant and contact experiments.',
    'Use the thesis measurements to diagnose omitted inertia, stiction, clipping, backlash and feedforward failure.',
    'Reconstruct a bounded SEA experiment with synchronized states, saturation logs and theory/measurement separation.',
    'Connect the 1995 contribution to modern compliant robot joints without projecting later capabilities backward.',
  ],
};
