import type { PaperStudySpec } from './FoundationalPaperStudy';
import { MansonDoubleLinearFatigueLab, NasaBoltLoadIntroductionLab } from './viz/StructuralSourceLabs';

const raw = String.raw;

export const nasaPreloadedBoltLoadIntroduction2025Spec: PaperStudySpec = {
  documentKind: '현재 기술 보고서',
  shortTitle: 'Ramsey (2025), Preloaded Bolt의 Load Introduction',
  citation: 'John K. Ramsey, Mechanics of Preloaded Bolt Tensile Loading With Focus on Load Introduction Factor, NASA/TM-20250005284, May 2025',
  yearVenue: '2025 · NASA Glenn Research Center Technical Memorandum · 112 PDF pages',
  sourceUrl: 'https://ntrs.nasa.gov/api/citations/20250005284/downloads/TM-20250005284_final_06042025.pdf',
  before: '전통적인 preloaded bolted-joint 식은 bolt와 clamped member의 stiffness factor에 geometric load-introduction factor(GLIF)를 곱하는 형태로 널리 쓰였다. Thickness ratio인 GLIF는 external load가 실제 어느 stiffness path로 들어오는지와 path position/material distribution을 충분히 표현하지 못할 수 있었다.',
  authorIntent: '저자는 preload 뒤 external tensile load가 clamping and relieving paths로 나뉘는 free-body and compatibility에서 bolt-load equation을 다시 유도한다. 그 과정에서 load introduction factor를 별도 empirical knob가 아니라 path stiffness에서 자연스럽게 나오는 quantity로 만들고, geometry approximation·FEA·기존 experiment와 비교하려 했다.',
  thesis: 'Bolt tensile load는 preload, thermal load and external-load increment의 합이며, external increment의 slope는 bolt/member stiffness factor와 stiffness-based load introduction factor(SBLIF)의 product다. SBLIF, stiffness factor and thermal load는 같은 load-path stiffness에 의존하므로 독립 변수로 조정하면 안 된다.',
  reconstruction: [
    { label: 'Joint state', value: 'P₀ + contact', note: 'Bolt elongation and member compression이 preload equilibrium을 만든다.' },
    { label: 'Load paths', value: 'clamping + relieving', note: 'Loading planes 사이와 바깥 경로가 같은 interface displacement를 공유한다.' },
    { label: 'Stiffness IR', value: 'K_b, K_a, K₂₋₄, K*', note: 'Bolt, tensile member, relieving path and compressed region을 분리한다.' },
    { label: 'Factors', value: 'n · φ', note: 'SBLIF and stiffness factor를 derivation에서 얻되 dependence를 보존한다.' },
    { label: 'Evidence', value: 'analytic ↔ FEA ↔ test', note: 'GLIF and SBLIF를 benchmark와 비교하고 approximation error를 남긴다.' },
  ],
  mechanism: [
    'PDF report pp. 1-6에서 preloaded joint의 bolt, compression zone, clamping path and relieving path를 FBD로 분리한다.',
    'Report pp. 8-13에서 각 path를 stiffness elements로 바꾸고 동일 interface displacement와 equilibrium을 적용해 traditional bolt tensile-load equation을 유도한다.',
    'Report pp. 14-15에서 SBLIF n을 relieving-path or compressed-region stiffness distribution의 flexibility sum으로 표현한다.',
    'Report p. 16 and Appendix E(pp. 59-62)에서 bolt/member CTE mismatch and temperature change가 만드는 thermal load를 compatible displacement로 유도한다.',
    'Report pp. 17-19에서 n, φ and thermal load의 common stiffness dependency를 드러내는 fundamental equation으로 다시 합친다.',
    'Report pp. 20-29에서 thickness-only GLIF와 stiffness-based SBLIF가 같아지는 제한 조건, loading-plane position and modulus/area distribution 차이를 비교한다.',
    'Report pp. 26-32 and Appendices G-I에서 FEA-derived slope and Boenick experiment-derived load factor와 두 analytical factors를 비교한다.',
    'Report pp. 32-38 and Appendix J에서 joint diagram, separation/rupture trajectories and nonlinear FEA extraction procedure로 engineering use를 닫는다.',
  ],
  equations: [
    {
      latex: raw`\underbrace{\phi}_{\text{강성 분담률}}=\frac{\underbrace{K_b}_{\text{볼트 인장 강성}}}{\underbrace{K_a+K_b}_{\text{부재 인장 경로와 볼트 강성의 합}}}`,
      meaning: 'Report Eq. 25의 stiffness factor입니다. 같은 opening displacement에서 bolt and clamped-member tension paths의 force increment를 나누기 위해 stiffness ratio를 사용합니다. Historical compression-zone Kc substitution은 tractable하지만 report Appendix B가 physically inconsistent approximation으로 구분합니다.',
      symbols: [[raw`K_b`, 'Bolt tensile stiffness [N/m]'], [raw`K_a`, 'Clamped members의 external tensile-load-path stiffness [N/m]'], [raw`\phi`, 'Dimensionless joint stiffness factor']],
    },
    {
      latex: raw`\underbrace{n}_{\text{강성 기반 하중 도입 계수}}=\frac{\underbrace{K_{2-4}}_{\text{완화 경로 강성}}}{\underbrace{K_a}_{\text{부재 전체 인장 경로 강성}}}`,
      meaning: 'Report Eq. 45의 SBLIF form입니다. External load가 들어오는 loading planes 사이의 relieving path stiffness를 전체 tensile path와 비교합니다. 단순 distance ratio 대신 stiffness를 쓰는 이유는 area, modulus and path position 변화를 반영하기 위해서입니다.',
      symbols: [[raw`K_{2-4}`, 'Report points 2-4 사이 relieving load-path stiffness [N/m]'], [raw`K_a`, 'Clamped-member tensile path stiffness [N/m]'], [raw`n`, 'Dimensionless stiffness-based LIF']],
    },
    {
      latex: raw`\underbrace{n}_{\text{압축 영역으로 본 같은 계수}}=\frac{\underbrace{K^{*}_{1-2,4-5}}_{\text{압축 영역 강성}}}{\underbrace{K_{2-4}+K^{*}_{1-2,4-5}}_{\text{두 부재 경로 강성의 합}}}`,
      meaning: 'Report Eq. 46의 alternative SBLIF입니다. Superscript star는 bolt flexibility를 뺀 compressed region을 뜻합니다. 같은 n을 서로 다른 path decomposition으로 얻는 이유는 model consistency를 검사하고 selected stiffness approximations가 bolt load를 어떻게 바꾸는지 보이기 위해서입니다.',
      symbols: [[raw`K^{*}_{1-2,4-5}`, 'Bolt를 제외한 compressed-region stiffness [N/m]'], [raw`K_{2-4}`, 'Relieving path stiffness [N/m]'], [raw`n`, '동일 SBLIF의 compressed-region representation']],
    },
    {
      latex: raw`\underbrace{P_{th}}_{\text{볼트 열하중}}=\underbrace{\phi K_a}_{\text{호환 변위를 힘으로 바꾸는 강성}}\underbrace{L\Delta T(\alpha_a-\alpha_b)}_{\text{부재와 볼트의 자유 팽창 차이}}`,
      meaning: 'Report Eq. 34 and Appendix E의 thermal load입니다. Bolt and members가 다르게 자유 팽창하려는 길이를 compatible stiffness로 internal force로 바꿉니다. Uniform temperature and linear behavior assumption에 묶이며 multi-material member의 alpha_a는 length-weighted effective CTE입니다.',
      symbols: [[raw`P_{th}`, 'Sign convention이 붙은 thermal bolt load [N]'], [raw`\alpha_a,\alpha_b`, 'Member effective and bolt CTE [1/K]'], [raw`L`, 'Clamped-member thickness/effective grip length [m]'], [raw`\Delta T`, 'Preload equilibrium temperature에서의 change [K]']],
    },
    {
      latex: raw`\underbrace{P_b}_{\text{전체 볼트 인장 하중}}=\underbrace{P_0}_{\text{프리로드}}+\underbrace{n\phi P_{ext}}_{\text{외력에 의한 증가}}+\underbrace{P_{th}}_{\text{열에 의한 변화}}`,
      meaning: 'Report Eq. 36의 traditional complete form입니다. Linear superposition을 쓰므로 attached contact and linear material range에 한정됩니다. n과 phi를 곱하는 이유는 external load의 path-entry fraction and compatible stiffness share가 모두 bolt increment를 제한하기 때문입니다.',
      symbols: [[raw`P_0`, 'Installed preload at reference temperature [N]'], [raw`P_{ext}`, 'External tensile-load component [N]'], [raw`n\phi`, 'Bolt-load trajectory의 linear slope before path change'], [raw`P_b`, 'Pre-separation total bolt tensile load [N]']],
    },
    {
      latex: raw`\underbrace{n\phi}_{\text{FEA에서 추출할 기울기}}=\frac{d\underbrace{(P_b-P_0-P_{th})}_{\text{프리로드와 열하중 위의 볼트 증가}}}{d\underbrace{P_{ext}}_{\text{외부 인장 하중}}}`,
      meaning: 'Report pp. 34-36의 FEA extraction procedure를 derivative form으로 정리했습니다. Local contour maximum 대신 bolt-load trajectory slope를 쓰는 이유는 modeling artifact에 덜 민감한 joint-level quantity로 analytical equation과 직접 비교하기 위해서입니다. Nonlinear gap/prying에서는 slope가 load에 따라 바뀝니다.',
      symbols: [[raw`d(P_b-P_0-P_{th})`, 'External increment에 대응한 bolt tensile-load change [N]'], [raw`dP_{ext}`, 'Applied tensile-load increment [N]'], [raw`n\phi`, 'Preloaded joint trajectory의 local dimensionless slope']],
    },
  ],
  mechanismViz: NasaBoltLoadIntroductionLab,
  evidence: [
    {
      label: '유도',
      question: 'SBLIF와 stiffness factor는 기존 식에 임의로 붙인 correction인가?',
      intervention: 'Report pp. 2-19에서 preload joint를 bolt, compression, clamping and relieving paths로 나누고 equilibrium/compatibility에서 식을 순서대로 유도한다.',
      observation: 'Pb=P0+nφPext+Pth가 나오며 n, φ and Pth가 common stiffness paths에 의존한다.',
      supports: 'Load introduction이 physical load-path mechanics의 일부라는 report thesis를 지지한다.',
      limit: 'Linear spring path derivation은 contact opening, prying, plasticity and frictional slip 뒤 behavior를 완전히 기술하지 않는다.',
    },
    {
      label: 'GLIF 비교',
      question: 'Loading-plane distance ratio만으로 load introduction을 일반적으로 표현할 수 있는가?',
      intervention: 'Report pp. 20-29에서 variable E(x), A(x), path position and frustum/cylinder models로 GLIF and SBLIF equality condition을 비교한다.',
      observation: 'Constant stiffness distribution이라는 제한 상황에서만 simple geometric interpretation이 맞고 position/material distribution이 달라지면 두 factor가 갈라진다.',
      supports: 'Stiffness path가 thickness ratio보다 broader representation이라는 명제를 지지한다.',
      limit: 'SBLIF accuracy도 analyst가 선택한 frustum angle, area and stiffness approximations에 제한된다.',
    },
    {
      label: 'FEA 비교',
      question: 'Analytical factors는 nonlinear finite-element joint response와 얼마나 맞는가?',
      intervention: 'Report pp. 26-28 and Appendices G-H에서 explicit bolt/member/contact/preload FEA의 bolt-load slope와 GLIF/SBLIF를 비교한다.',
      observation: 'Selected pure-tension joint에서 SBLIF가 GLIF보다 FEA-derived factor에 가까운 cases가 있지만 assumed compression-zone half angle and bolt-head flexibility가 result를 바꾼다.',
      supports: 'Path stiffness approximation을 개선하면 analytical bolt-load prediction이 좋아질 가능성을 지지한다.',
      limit: '한 geometry and model setup의 agreement는 mesh/contact/material choices 또는 다른 joint type을 검증하지 않는다.',
    },
    {
      label: '실험 비교',
      question: 'Loading plane position을 바꾼 real joint에서도 SBLIF trend가 관찰되는가?',
      intervention: 'Report pp. 30-32 and Appendix I에서 Boenick의 7.8 mm fastener, four flange diameters, four preload levels experiment를 digitize and compare한다.',
      observation: '80/60/40 mm flanges에서 GLIF는 대부분 experimental LIF보다 크고 SBLIF가 더 가깝지만 unconservative points가 있다. 20 mm sleeve-like flange에서는 둘 다 잘 track한다.',
      supports: 'Geometry-only factor의 systematic limitation and stiffness-aware trend를 지지한다.',
      limit: 'Experiment-derived factor도 Kc를 Ka 대신 쓴 approximation 때문에 upper bound이며 report 자체가 SBLIF unconservatism을 인정한다.',
    },
    {
      label: 'Thermal',
      question: 'Compression-zone stiffness를 tensile-path stiffness 대신 쓰면 thermal bolt load도 같은가?',
      intervention: 'Appendices B and E, conclusion에서 Kc substitution이 phi and Pth에 미치는 sign/magnitude를 유도한다.',
      observation: 'Historical Kc substitution은 positive thermal load를 더 positive, negative load를 더 negative로 amplify할 수 있다.',
      supports: 'Mechanical and thermal joint analyses가 같은 stiffness-model consistency를 요구함을 지지한다.',
      limit: 'Uniform temperature and effective CTE는 spatial gradients, transient contact and temperature-dependent properties를 포함하지 않는다.',
    },
    {
      label: '비선형 단서',
      question: 'Bolt-load trajectory는 preload 뒤 항상 한 개의 양의 직선인가?',
      intervention: 'Report pp. 34-37에서 preload sweep FEA slope extraction and initial bolt unloading case를 제시한다.',
      observation: 'Washer ID/OD pressure redistribution and prying 때문에 external tension 초기 bolt load가 감소한 뒤 증가하는 negative-to-positive local slope가 나타날 수 있다.',
      supports: 'Simple linear factor가 geometry/contact state에 따라 load-dependent해질 수 있음을 지지한다.',
      limit: 'Illustrated computational scenario alone가 every washer/head geometry의 unloading mechanism을 입증하지 않는다.',
    },
    {
      label: '저자 결론',
      question: '저자는 SBLIF를 GLIF의 무조건 안전한 replacement로 주장하는가?',
      intervention: 'Report pp. 37-38의 Conclusions를 main derivation and benchmarks와 함께 읽는다.',
      observation: 'SBLIF는 greater accuracy가 가능하지만 stiffness approximations에 따라 mechanical bolt load를 underpredict해 unconservative할 수 있고, average/combination with GLIF 고려를 언급한다.',
      supports: 'Contribution이 stiffness-aware reasoning and programmable equations임을 지지한다.',
      limit: '보고서는 design standard, universal safety factor or certification method를 제공하지 않는다.',
    },
  ],
  implementation: [
    'Exact joint CAD에서 faying surface, bolt axis, washer/head contacts and external loading planes를 표시한다.',
    'Preload-only FBD를 만든 뒤 external tension 아래 clamping and relieving load paths를 분리한다.',
    'Bolt, tensile member, relieving path and compressed region의 stiffness를 units and geometry assumptions와 함께 계산한다.',
    'Eq. 45/46 두 representation으로 SBLIF를 계산해 algebra and path decomposition consistency를 확인한다.',
    'Current report의 Ka and historical Kc substitution을 각각 계산해 phi, mechanical increment and thermal load sensitivity를 남긴다.',
    'Attached linear state에서 Pb, remaining clamp, separation and rupture loads를 계산한다.',
    'Contact/preload FEA에서 preload sweep and external-load sweep을 수행하고 bolt total force minus preload의 slope nφ를 추출한다.',
    'Peak contour보다 reaction balance, contact pressure, gap/prying onset and bolt-load trajectory를 보존한다.',
    'At least one physical preload and tensile-load test에서 bolt tension and interface displacement를 동기화한다.',
    'Analytical, FEA and test factor가 갈리면 stiffness distribution, head/washer flexibility, loading plane and Kc/Ka assumption을 먼저 audit한다.',
  ],
  assumptions: [
    'Main traditional equation section uses linear behavior and superposition before major contact-state change.',
    'External tensile component and loading planes are declared in the report coordinate/path convention.',
    'Stiffness elements approximate actual area, modulus, head/washer flexibility and member path sufficiently for the claim.',
    'Thermal derivation uses an effective member CTE and temperature change from preload equilibrium.',
    'FEA-derived nφ depends on correct preload, contact, force extraction and the relevant external-load interval.',
  ],
  failures: [
    'Using GLIF because it is easy can overpredict bolt load and add mass, but switching to a poorly approximated SBLIF can underpredict and become unconservative.',
    'Treating n and phi as independent design knobs violates their common dependence on relieving and compressed-region stiffness.',
    'Using compression stiffness Kc in place of tensile-path Ka changes both mechanical and thermal predictions.',
    'Joint separation, prying, washer pressure redistribution and material nonlinearity make the one-slope equation load-dependent.',
    'Torque-controlled preload scatter can dominate the refined load-factor difference if installed preload is not measured or bounded.',
    'Pure tensile PBJ conclusions do not automatically transfer to eccentric multi-bolt, shear, slip-critical or composite joints.',
  ],
  legacy: '이 2025 report의 가치는 새로운 empirical factor 하나가 아니다. Bolt load를 load-plane distance 그림에서 stiffness-resolved paths and compatibility로 되돌리고, mechanical increment, thermal load, joint diagram and FEA slope가 같은 physical decomposition을 공유하게 만든 점이다. 동시에 source는 자신의 preferred SBLIF가 approximation 때문에 unconservative할 수 있음을 숨기지 않는다. 이는 current company/research artifact를 읽을 때 method, evidence and transfer boundary를 함께 보존해야 하는 좋은 사례다.',
  nextReading: '먼저 Robot Structural Mechanics 글에서 FBD, stiffness, preload, slip and thermal compatibility를 익힌다. 이어 NASA RP-1228로 torque/preload and fatigue vocabulary를 확인하고, NASA-STD-5020 current revision and project-specific allowables를 실제 설계 requirement로 사용한다. 이 report 하나를 standard 대신 쓰지 않는다.',
  capabilities: [
    'Preload, external tensile increment and thermal load를 한 bolt-load ledger로 구성한다.',
    'Stiffness factor and SBLIF를 load-path compatibility에서 설명한다.',
    'GLIF와 SBLIF가 같아지는 제한과 갈라지는 geometry/material conditions를 말한다.',
    'Ka/Kc substitution이 mechanical and thermal load에 미치는 영향을 분리한다.',
    'FEA contour 대신 bolt-load trajectory slope nφ를 추출하고 해석한다.',
    'Experiment, FEA and analytical comparison이 지지하는 범위와 unconservative risk를 보존한다.',
    'Pure-tension report 결과를 다른 robot joint에 옮기기 전 필요한 evidence를 열거한다.',
  ],
};

export const mansonDoubleLinearFatigue1967Spec: PaperStudySpec = {
  shortTitle: 'Manson·Freche·Ensign (1967), Double Linear Fatigue Damage',
  citation: 'S. S. Manson, J. C. Freche, C. R. Ensign, Application of a Double Linear Damage Rule to Cumulative Fatigue, NASA TN D-3839, April 1967',
  yearVenue: '1967 · NASA Technical Note D-3839 · 41 PDF pages',
  sourceUrl: 'https://ntrs.nasa.gov/api/citations/19670013955/downloads/19670013955.pdf',
  before: 'Miner linear damage rule은 서로 다른 stress level의 applied life fractions n_i/N_f,i를 하나로 합해 1에서 failure를 예측한다. Simple and practical하지만 high→low and low→high loading order, residual stress, changed fatigue limit and coaxing effect를 직접 표현하지 못했다.',
  authorIntent: '저자들은 fatigue life를 crack initiation and propagation이라는 두 phase로 나누고 각 phase 안에서는 linear damage를 적용하면 order effect를 표현하면서 Miner rule의 practicality를 유지할 수 있는지 검증하려 했다. 기존 14N_f^0.6 phase split을 비판적으로 평가하고 experimental Phase I/II alternative까지 제안한다.',
  thesis: 'One linear sum 대신 transition point B를 공유하는 two linear relations를 사용하면 two-level loading의 order-dependent remaining life를 더 잘 표현할 수 있다. 그러나 phase split은 material, stress extremes and specimen geometry에 묶이며 universal crack law가 아니다.',
  reconstruction: [
    { label: 'Baseline', value: 'Σ n/Nf = 1', note: 'Order-independent conventional linear damage.' },
    { label: 'Phase split', value: 'N₀ + ΔN', note: 'Initiation-like and propagation-like life portions.' },
    { label: 'Two lines', value: 'A → B → C', note: 'Remaining cycle ratio plane에서 transition B를 만든다.' },
    { label: 'Two-level test', value: 'high ↔ low', note: 'Material and stress-extreme-specific B를 experiment로 찾는다.' },
    { label: 'Bounded use', value: 'smooth 1/4 in', note: 'Complex structure로의 전이는 future work로 남긴다.' },
  ],
  mechanism: [
    'PDF pp. 3-4에서 Miner linear rule의 simplicity and order-effect limitation을 정리한다.',
    'PDF pp. 5-7에서 total life Nf를 effective crack initiation N0 and propagation ΔNf로 나누고 각 phase에 separate linear sum을 둔다.',
    'Figure 1에서 first-level applied ratio x and second-level remaining ratio y plane의 A-B-C two-line geometry를 만든다.',
    'PDF pp. 8-10에서 rotating-bending and reversed axial-strain specimen, material and baseline constant-amplitude curves를 고정한다.',
    'Figures 5-6 and pp. 10-16에서 maraging and SAE 4130 steels, high→low and low→high combinations의 prediction and experimental points를 비교한다.',
    'PDF pp. 16-20에서 original 14Nf^0.6 split의 mismatch를 인정하고 physical crack labels 대신 experimentally determined effective Phase I and II curves를 제안한다.',
    'Appendices A-C에서 two-step and alternating-block histories를 phase sum으로 계산하는 execution order를 상세히 보인다.',
    'Tables I-VII의 raw material, constant-amplitude and two-level data가 headline curves 뒤의 evidence population임을 확인한다.',
  ],
  equations: [
    {
      latex: raw`\underbrace{D_{Miner}}_{\text{기존 선형 손상}}=\sum_i\frac{\underbrace{n_i}_{\text{적용 주기 수}}}{\underbrace{N_{f,i}}_{\text{해당 수준의 전체 수명}}}=1`,
      meaning: 'Paper Eq. 5의 conventional linear damage rule입니다. 각 applied cycles를 matched constant-level life로 나눠 dimensionless life fraction을 만들고 합합니다. 이 operation은 order를 지우므로 same bins를 순서만 바꾼 histories에 같은 prediction을 냅니다.',
      symbols: [[raw`n_i`, 'Stress/strain level i에서 실제 적용 cycles'], [raw`N_{f,i}`, 'Level i만 계속 적용할 때 cycles to failure'], [raw`D_{Miner}`, 'Order-independent cumulative life fraction']],
    },
    {
      latex: raw`\underbrace{(\Delta N)_f}_{\text{제안된 전파 구간 수명}}=\underbrace{14}_{\text{제한된 자료의 계수}}\underbrace{N_f^{0.6}}_{\text{전체 수명에 따른 경험적 스케일}}`,
      meaning: 'Paper Eq. 1의 original propagation-period proposal입니다. Exponent 0.6 and coefficient 14는 smooth 1/4-inch notch-ductile specimens의 limited data에서 정해졌습니다. Power law를 쓰는 이유는 total life가 바뀔 때 propagation fraction이 선형 비율로 유지되지 않는 observed trend를 단순화하기 위해서지만 universal material law가 아닙니다.',
      symbols: [[raw`N_f`, 'Constant stress/strain level의 total cycles to failure'], [raw`(\Delta N)_f`, 'Authors가 정의한 effective propagation-period cycles'], [raw`14,0.6`, 'Source-bound empirical coefficient and exponent']],
    },
    {
      latex: raw`\underbrace{N_0}_{\text{제안된 개시 구간 수명}}=\underbrace{N_f}_{\text{전체 수명}}-\underbrace{(\Delta N)_f}_{\text{전파 구간 수명}}`,
      meaning: 'Paper Eq. 2의 initiation-period definition입니다. Total life에서 proposed propagation portion을 빼 두 phase가 life를 partition하도록 만듭니다. Nf below about 730 cycles에서는 source가 N0≈0으로 두지만 이 cutoff 역시 source model and specimen boundary 안에서만 씁니다.',
      symbols: [[raw`N_0`, 'Effective crack-initiation/Phase-I cycles'], [raw`N_f`, 'Total constant-level fatigue life'], [raw`(\Delta N)_f`, 'Effective propagation/Phase-II cycles']],
    },
    {
      latex: raw`\underbrace{D_I}_{\text{1단계 손상}}=\sum_i\frac{\underbrace{n_i^{(I)}}_{\text{1단계에 소비한 주기}}}{\underbrace{N_{0,i}}_{\text{그 수준의 1단계 수명}}}=1`,
      meaning: 'Paper Eq. 3의 Phase I linear sum을 readable form으로 썼습니다. Total-life denominator 대신 phase-specific N0를 쓰는 이유는 loading order에 따라 transition B에 도달하는 시점을 별도로 계산하기 위해서입니다. Literal crack initiation interpretation은 later alternative view에서 effective phase로 완화됩니다.',
      symbols: [[raw`n_i^{(I)}`, 'Phase I 동안 level i에서 소모한 cycles'], [raw`N_{0,i}`, 'Level i의 Phase-I capacity'], [raw`D_I`, 'Phase-I linear fraction sum']],
    },
    {
      latex: raw`\underbrace{D_{II}}_{\text{2단계 손상}}=\sum_i\frac{\underbrace{n_i^{(II)}}_{\text{2단계에 소비한 주기}}}{\underbrace{(\Delta N)_{f,i}}_{\text{그 수준의 2단계 수명}}}=1`,
      meaning: 'Paper Eq. 4의 Phase II linear sum입니다. Transition 이후 cycles를 propagation/effective Phase-II capacity로 normalize합니다. 두 separate sums가 같은 total history를 순서에 따라 다르게 partition하므로 one-line Miner rule이 놓친 order effect를 표현할 수 있습니다.',
      symbols: [[raw`n_i^{(II)}`, 'Phase II 동안 level i에서 소모한 cycles'], [raw`(\Delta N)_{f,i}`, 'Level i의 Phase-II capacity'], [raw`D_{II}`, 'Phase-II linear fraction sum']],
    },
    {
      latex: raw`\underbrace{B}_{\text{단계 전환점}}=\underbrace{\operatorname{intersect}}_{\text{실험선 교점}}\!\left(\underbrace{\ell_I}_{\text{작은 수명비}},\underbrace{\ell_{II}}_{\text{큰 수명비}}\right)`,
      meaning: 'Paper pp. 18-20의 alternative experimental viewpoint를 conceptual operation으로 표시했습니다. Authors는 high-stress first fraction near 0.2 and 0.5의 two tests를 제안하고 each point를 endpoint와 잇는 two lines의 intersection으로 B를 정합니다. Intersect를 쓰는 이유는 physical crack threshold를 가정하지 않고 observed remaining-life geometry에서 phase capacity를 식별하기 위해서입니다.',
      symbols: [[raw`\ell_I,\ell_{II}`, '두 two-level fatigue test points를 통과하는 fitted lines'], [raw`B`, 'Material and chosen stress extremes에 묶인 effective phase transition'], [raw`\operatorname{intersect}`, '두 선의 common coordinate를 찾는 geometric operation']],
    },
  ],
  mechanismViz: MansonDoubleLinearFatigueLab,
  evidence: [
    {
      label: '기준선 실패',
      question: 'Conventional linear sum은 loading order를 설명하는가?',
      intervention: 'Introduction and Figure 1에서 high→low and low→high two-level tests의 remaining life plane을 45-degree Miner line과 비교한다.',
      observation: 'High first can produce sum below 1 and low first sum above 1; one 45-degree line has no state that remembers order.',
      supports: 'Order-dependent fatigue needs at least one additional state/phase라는 문제 정의를 지지한다.',
      limit: 'Order effect의 존재만으로 proposed double-linear split의 exact equations가 참임을 증명하지 않는다.',
    },
    {
      label: '초기 계수',
      question: '14Nf^0.6 propagation proposal은 어떤 evidence에서 왔는가?',
      intervention: 'Figure 3에서 maraging steel rotating bending의 one high/low combination에 coefficient values를 바꾼 predicted A-B-G lines를 experimental points와 비교한다.',
      observation: 'Coefficient 14가 이 selected data에 reasonable agreement를 보여 original tentative proposal로 채택된다.',
      supports: 'Simple two-phase power-law split의 initial empirical plausibility를 지지한다.',
      limit: 'One material and one stress pair의 fit은 exponent/coefficient의 generality를 입증하지 않는다.',
    },
    {
      label: 'Maraging 확장',
      question: '다른 life-level combinations에서도 original double-linear rule이 Miner보다 낫나?',
      intervention: 'Figures 4-5에서 rotating bending and axial reversed strain, low/high initial life and both orders를 비교한다.',
      observation: 'Large high-to-low life separation에서 double-linear prediction이 많은 points를 더 잘 따르지만 both life levels가 high일 때와 일부 axial cases에서 data가 prediction 양쪽으로 벗어난다.',
      supports: 'Order trend capture and some accuracy improvement를 지지한다.',
      limit: 'Original phase equation이 every regime에서 consistently superior하지 않다.',
    },
    {
      label: '4130 steel',
      question: 'Material hardness and different steel에서도 same split이 유지되는가?',
      intervention: 'Figure 6 and related tables에서 hard/soft SAE 4130 rotating-bending two-level tests를 original rule and Miner line과 비교한다.',
      observation: 'Many high→low cases show reasonable behavior, but discrepancies and material/stress-level dependence remain.',
      supports: 'Two-phase geometry가 one maraging dataset만의 artifact는 아닐 가능성을 지지한다.',
      limit: 'Smooth small steel specimens가 notched full-scale robot structure, aluminum or welded joint를 대표하지 않는다.',
    },
    {
      label: 'Phase 재해석',
      question: 'N0 and ΔN을 literal crack initiation/propagation으로 total life만에서 정할 수 있는가?',
      intervention: 'PDF pp. 16-20에서 cyclic response and two-level results를 재검토하고 experimental transition-point method를 제안한다.',
      observation: 'Authors는 hardening/softening and stress levels가 phase boundary를 바꾸므로 original total-life-only representation이 inadequate할 수 있음을 인정하고 effective Phase I/II로 바꾼다.',
      supports: 'Experimentally identified two-line rule이 original literal crack split보다 defensible하다는 저자 결론을 지지한다.',
      limit: '두 tests로 얻은 B도 selected material and extreme stresses 밖으로 자동 transfer되지 않는다.',
    },
    {
      label: '교대 블록',
      question: 'Two-line phase ledger를 alternating multiple blocks에 실행할 수 있는가?',
      intervention: 'Appendix C and Table VII에서 8000-cycle alternating high/low blocks를 phase sums로 순차 계산한다.',
      observation: 'Algorithm은 block를 Phase I capacity에 먼저 배분하고 transition 뒤 remaining cycles를 Phase II ledger로 옮긴다.',
      supports: 'Method가 single two-step graph를 넘어 spectrum execution rule을 갖는다는 점을 지지한다.',
      limit: 'Alternating two-level blocks는 arbitrary random multiaxial mission spectrum의 validation이 아니다.',
    },
    {
      label: '저자의 경계',
      question: 'Paper가 complex structures의 fatigue life를 해결했다고 주장하는가?',
      intervention: 'Summary and Concluding Remarks를 equations, figures and appendices와 함께 읽는다.',
      observation: 'Authors는 limited verification, smooth 1/4-inch specimens and material/load-extreme-specific phases를 명시하며 complex geometry prediction을 future direction으로 둔다.',
      supports: 'Contribution이 order-aware bounded model and experimental identification procedure임을 지지한다.',
      limit: 'Modern notch, surface, probabilistic scatter, crack growth, multiaxiality and variable environment는 별도 evidence가 필요하다.',
    },
  ],
  implementation: [
    'Reproduce constant-amplitude S-N/life points for each selected stress or strain level before any cumulative rule.',
    'Implement Miner sum as an explicit order-independent baseline and verify order permutations give identical D.',
    'Implement original source equations for N0 and DeltaN with the Nf≈730-cycle branch and source units/limits visible.',
    'Recreate Figure-1 coordinates x=n1/Nf,1 and y=n2/Nf,2 and draw Miner line plus A-B-C double-linear prediction.',
    'Run at least two two-level tests with separated first-level fractions to estimate an experimental transition B rather than forcing 14Nf^0.6.',
    'Repeat both high→low and low→high orders and keep specimen-level scatter, runouts and failure criterion.',
    'Implement phase accounting for alternating blocks as in Appendix C, preserving the exact cycle remainder at transition.',
    'Compare predicted total life, remaining ratio and sum-of-ratios distributions, not one average curve alone.',
    'For robot hardware, rebuild local stress histories with notch/surface/process/temperature corrections and do not transfer the source coefficient.',
    'Use detail/coupon fatigue tests and NDE/crack-growth evidence before converting the historical rule into a service interval.',
  ],
  assumptions: [
    'The source experiments use smooth 1/4-inch-diameter specimens and the documented materials/machines.',
    'Constant-amplitude lives for each level are known with the relevant failure criterion.',
    'Within each effective phase, normalized damage accumulation is linear.',
    'Original 14Nf^0.6 equations are empirical and source-bound; alternative Phase I/II is material and stress-extreme specific.',
    'Two-level axial/rotating-bending histories do not represent multiaxial nonproportional service loading.',
  ],
  failures: [
    'Miner sum cannot distinguish high→low from low→high and can be nonconservative or conservative depending on sequence.',
    'Original total-life-only phase split misses material hardening/softening and stress-level dependence.',
    'Fitting transition B with too few noisy tests gives unstable Phase I/II curves even though the graph looks simple.',
    'Stress cycles below the initial fatigue limit can matter after prior damage changes the material state.',
    'Notches, residual stress, surface finish, size, mean stress and environment can dominate a robot detail absent from the source specimens.',
    'Calling Phase I literal crack initiation without direct crack evidence overstates the later alternative interpretation.',
  ],
  legacy: '이 논문의 지속적인 가치는 Miner rule을 단순히 버린 것이 아니라 왜 실패하는지 state-memory 관점으로 드러낸 데 있다. 같은 cycle bins라도 순서가 다르면 material state and remaining life가 달라질 수 있다. Authors는 첫 power-law split의 mismatch를 보고 스스로 literal crack story를 effective experimentally determined phases로 완화했다. 좋은 foundational paper reading은 최종 식만 외우는 일이 아니라 이 revision and self-imposed boundary까지 보존하는 일이다.',
  nextReading: 'Robot Structural Mechanics의 mission-spectrum section으로 돌아가 rainflow, local detail and evidence chain에 이 order-effect lesson을 배치한다. 이후 modern strain-life, fracture mechanics, probabilistic fatigue and damage-tolerance sources를 별도 spine으로 읽는다. Miner or this double-linear rule 하나를 service-life certification으로 사용하지 않는다.',
  capabilities: [
    'Miner linear sum이 간단하고 order-blind인 이유를 설명한다.',
    'Original N0/DeltaN phase equations and source-bound coefficient를 재현한다.',
    'A-B-C remaining-life graph에서 transition B가 order effect를 만드는 방식을 설명한다.',
    'Maraging and SAE 4130 evidence가 지지한 부분과 mismatch regimes를 구분한다.',
    'Literal crack initiation/propagation에서 effective experimental Phase I/II로 바뀐 저자 revision을 말한다.',
    'Alternating blocks를 phase ledger로 실행하고 transition remainder를 보존한다.',
    'Smooth small-specimen conclusion을 robot structural detail로 옮기기 전 필요한 corrections and tests를 열거한다.',
  ],
};
