import type { PaperStudySpec } from './FoundationalPaperStudy';
import {
  BahdanauMechanismViz,
  BertMechanismViz,
  LongTermGradientMechanismViz,
  LstmMechanismViz,
  Seq2SeqMechanismViz,
} from './viz/NlpPaperMechanismViz';

export const longTermDependenciesSpec: PaperStudySpec = {
  mechanismViz: LongTermGradientMechanismViz,
  shortTitle: 'Learning Long-Term Dependencies',
  citation: 'Bengio, Simard, Frasconi — Learning Long-Term Dependencies with Gradient Descent is Difficult', yearVenue: '1994 · IEEE Transactions on Neural Networks', sourceUrl: 'https://doi.org/10.1109/72.279181',
  before: 'Recurrent network는 이론상 과거 전체를 state에 담을 수 있었지만, gradient descent가 먼 과거의 원인을 실제로 학습하는지는 분리되어 있지 않았다.',
  authorIntent: '시간을 따라 반복되는 Jacobian이 gradient를 어떻게 줄이거나 키우는지 분석하고, 단순 recurrent network가 장기 의존성 task에서 실패하는 이유가 표현력 부족이 아니라 optimization 구조에 있음을 보이려 했다.',
  thesis: '장기 기억을 유지하려는 dynamics와 gradient가 안정적으로 흐르는 dynamics 사이에 근본적 긴장이 있으며, 일반 gradient descent는 긴 시간 간격의 credit assignment에 어렵다.',
  reconstruction: [{ label: 'Input history', value: 'x₁…xₜ', note: '먼 과거에 원인 배치' }, { label: 'Shared recurrence', value: 'hₜ=f(Whₜ₋₁+Uxₜ)', note: '같은 Jacobian 반복' }, { label: 'Temporal credit', value: '∂Lₜ/∂hₖ', note: 't에서 k까지 역전파' }, { label: 'Observed failure', value: 'decay or explosion', note: '긴 delay에서 학습 붕괴' }],
  mechanism: ['Recurrent graph를 시간축으로 펼쳐 같은 transition의 미분이 반복 곱해지는 형태를 만든다.', 'Jacobian의 singular value 또는 eigenvalue 크기가 1보다 작거나 큰 경우 gradient norm이 지수적으로 변하는 이유를 분리한다.', '정보를 오래 유지하는 forward dynamics와 빠른 optimization에 필요한 backward dynamics가 충돌하는 task를 실험한다.'],
  equations: [{ latex: String.raw`\frac{\partial h_t}{\partial h_k}=\prod_{j=k+1}^{t}\frac{\partial h_j}{\partial h_{j-1}}`, meaning: '먼 state hₖ가 현재 state hₜ에 미치는 영향은 사이 timestep의 local Jacobian을 모두 곱한 값이다. 각 factor의 norm이 반복적으로 1보다 작으면 사라지고 크면 폭발하므로 distance가 직접 optimization 난이도가 된다.', symbols: [[String.raw`h_k,h_t`, '과거와 현재 hidden state'], [String.raw`\partial h_j/\partial h_{j-1}`, '한 recurrent transition의 local Jacobian']] }],
  evidence: [{ label: 'Synthetic delay', question: '정답에 필요한 신호와 예측 사이의 delay가 늘어날 때 학습되는가?', intervention: '같은 recurrent 학습법에서 dependency span을 늘리고 short-term component와 long-term component를 비교한다.', observation: '짧은 의존성은 먼저 맞추지만 긴 의존성에 필요한 gradient 신호가 약해져 optimization이 정체된다.', supports: '문제가 단순 capacity가 아니라 gradient-based credit assignment에 있음을 지지한다.', limit: '현대 activation, initialization, normalization, optimizer를 사용한 모든 RNN의 실패를 입증하지는 않는다.' }],
  implementation: ['작은 tanh RNN과 delay가 조절되는 synthetic sequence task를 만든다.', '각 timestep의 recurrent Jacobian과 누적 gradient norm을 hook으로 기록한다.', 'Sequence length만 바꾸고 hidden size·data·optimizer를 고정해 success rate와 gradient norm을 그린다.', 'Gradient clipping은 explosion만 제어하며 vanishing을 복구하지 못하는지 분리한다.'],
  assumptions: ['긴 의존성 신호가 data에 존재하고 loss가 이를 요구한다.', '같은 recurrent transition이 여러 timestep에 공유된다.'], failures: ['작은 최종 loss만 보면 short-term shortcut으로 푼 것을 장기 기억으로 오해할 수 있다.', 'Gradient norm 하나만으로 방향 소실과 task-relevant subspace를 모두 설명할 수 없다.'],
  legacy: '이 논문은 “RNN이 기억할 수 있는가”와 “gradient descent가 그 기억을 찾을 수 있는가”를 분리했다. 이후 LSTM의 constant error carousel, orthogonal/unitary recurrence, residual path, clipping의 설계 이유를 읽는 기준이 되었다.', nextReading: '다음 LSTM 논문은 반복 곱의 경로를 gate가 제어하는 additive cell-state 경로로 바꾸려 한다.', nextLinks: [{ slug: 'paper-lstm-1997', label: 'LSTM 1997로 이어가기', reason: '반복 Jacobian 곱의 병목을 additive cell state와 gate가 어떻게 바꾸는지 확인한다.' }], capabilities: ['BPTT gradient를 Jacobian product로 전개할 수 있다.', 'Vanishing과 exploding을 spectral 관점에서 구분할 수 있다.', 'Clipping이 해결하는 문제와 해결하지 않는 문제를 설명할 수 있다.'],
};

export const lstmPaperSpec: PaperStudySpec = {
  mechanismViz: LstmMechanismViz,
  shortTitle: 'Long Short-Term Memory', citation: 'Hochreiter & Schmidhuber — Long Short-Term Memory', yearVenue: '1997 · Neural Computation', sourceUrl: 'https://direct.mit.edu/neco/article/9/8/1735/6109/Long-Short-Term-Memory',
  before: '기존 recurrent unit은 long delay에서 gradient가 사라지거나 폭발했고, 학습이 최근 신호에 치우쳤다.', authorIntent: 'Error가 시간축을 따라 일정하게 흐르는 memory cell과 multiplicative gate를 설계해 long-term credit assignment를 gradient descent로 학습 가능하게 만들려 했다.', thesis: 'Constant error carousel과 학습 가능한 input/output gate를 사용하면 기존 recurrent algorithms가 실패하는 긴 time lag task를 학습할 수 있다.',
  reconstruction: [{ label: 'Candidate input', value: 'g(net_c)', note: '쓸 내용' }, { label: 'Input gate', value: 'yⁱⁿ', note: 'memory write 제어' }, { label: 'CEC state', value: 's_c(t)', note: 'self-loop weight 1' }, { label: 'Output gate', value: 'yᵒᵘᵗ', note: 'memory read 제어' }],
  mechanism: ['Memory cell의 self-connection weight를 1로 고정해 error가 시간에 따라 multiplicative decay하지 않는 경로를 만든다.', 'Input gate가 외부 신호가 cell state를 교란하는 시점을 제어한다.', 'Output gate가 저장 정보가 network output과 다른 units에 노출되는 시점을 제어한다.', '현대식 forget gate는 원 1997 구조에 없으며 2000년 Gers 계열에서 추가되었다는 계보를 분리한다.'],
  equations: [{ latex: String.raw`s_c(t)=s_c(t-1)+y^{\mathrm{in}}(t)\,g(\mathrm{net}_c(t))`, meaning: '원 논문의 핵심 cell update는 이전 state에 gated candidate를 더하는 additive 경로다. Self-loop의 derivative가 1이므로 write가 없을 때 error가 줄지 않는 CEC가 된다. 현대 LSTM의 fₜcₜ₋₁와 달리 이 식에는 forget gate가 없다.', symbols: [[String.raw`s_c(t)`, 'memory cell internal state'], [String.raw`y^{\mathrm{in}}`, 'input gate activation'], [String.raw`g(\mathrm{net}_c)`, 'candidate cell input']] }],
  evidence: [{ label: 'Long lag tasks', question: '관련 input과 target 사이가 천 timestep 이상 떨어져도 학습 가능한가?', intervention: '기존 recurrent algorithms와 LSTM을 artificial long-time-lag task에서 비교한다.', observation: 'LSTM은 짧은 irrelevant signals 사이에서 필요한 event를 보존해 기존 방법이 풀지 못한 task를 학습한다.', supports: 'Gated CEC가 long-lag optimization을 실질적으로 개선함을 지지한다.', limit: '현대 NLP benchmark나 forget-gate LSTM 전체의 성능을 직접 입증하지 않는다.' }],
  implementation: ['Original cell과 modern forget-gate LSTM을 별도 구현해 혼동을 방지한다.', 'Write·read 시점이 분리된 synthetic task에서 cell state와 gate activation을 기록한다.', 'Delay를 늘리며 success curve와 ∂L/∂s_c의 norm을 비교한다.', 'Forget gate가 없을 때 continuous stream에서 state reset 문제가 생기는지 후속 구조와 비교한다.'],
  assumptions: ['Gate가 포화되기 전에 유용한 write/read 신호를 학습할 수 있다.', 'Cell state를 보존하는 것이 task의 long-term dependency와 맞는다.'], failures: ['원 논문 구조를 현대 3-gate LSTM 공식으로 설명하면 역사적 기여와 후속 개선이 섞인다.', 'Gate visualization만 보고 실제 causal memory 사용을 단정할 수 없다.'],
  legacy: 'Additive memory path와 multiplicative gate는 이후 gated recurrent models의 기본 언어가 되었다. Forget gate, peephole, GRU 등은 memory 보존과 reset의 계약을 다르게 조정했다.', nextReading: 'Seq2Seq 논문은 LSTM을 단일 sequence 기억 장치가 아니라 가변 길이 source를 target generator로 연결하는 시스템으로 사용한다.', nextLinks: [{ slug: 'paper-seq2seq-2014', label: 'Seq2Seq 2014로 이어가기', reason: 'LSTM memory를 가변 길이 source와 target을 잇는 encoder-decoder 시스템으로 확장한다.' }], capabilities: ['Original LSTM과 modern forget-gate LSTM을 구분할 수 있다.', 'CEC derivative가 왜 constant error path인지 계산할 수 있다.', 'Input/output/forget gate의 도입 시기와 역할을 혼동하지 않는다.'],
};

export const seq2seqPaperSpec: PaperStudySpec = {
  mechanismViz: Seq2SeqMechanismViz,
  shortTitle: 'Sequence to Sequence Learning', citation: 'Sutskever, Vinyals, Le — Sequence to Sequence Learning with Neural Networks', yearVenue: '2014 · NeurIPS', sourceUrl: 'https://research.google/pubs/sequence-to-sequence-learning-with-neural-networks/', appendixUrl: 'https://arxiv.org/abs/1409.3215',
  before: 'Deep neural networks는 고정 차원 input·output에는 강했지만 source와 target 길이가 모두 가변인 translation을 하나의 end-to-end objective로 다루기 어려웠다.', authorIntent: '복잡한 feature engineering 없이 두 deep LSTM이 source sequence를 fixed vector로 encode하고 target sequence를 decode할 수 있는지 대규모 번역에서 검증하려 했다.', thesis: '충분히 큰 multilayer LSTM은 variable-length sequence를 fixed-dimensional representation으로 매핑하고 다른 LSTM이 이를 high-quality target sequence로 복원할 수 있다.',
  reconstruction: [{ label: 'Source sentence', value: 'x₁…xₘ', note: 'reverse order 사용' }, { label: 'Encoder LSTM', value: 'c = stateₘ', note: '고정 vector' }, { label: 'Decoder LSTM', value: '<BOS>→y₁…', note: 'conditional generation' }, { label: 'Beam search', value: 'top-k prefixes', note: 'sequence decoding' }],
  mechanism: ['Source token을 LSTM이 순서대로 읽고 마지막 hidden/cell state를 fixed representation으로 사용한다.', 'Decoder를 encoder final state로 초기화하고 이전 target token을 조건으로 다음 token probability를 학습한다.', 'Training에서는 target 전체를 알고 teacher forcing으로 위치별 log likelihood를 병렬 축적한다.', 'Source word order reversal로 source의 앞부분과 대응 target의 앞부분 사이 minimal time lag를 줄여 optimization을 돕는다.'],
  equations: [{
    latex: String.raw`p(y_{1:T'}\mid x_{1:T})=\prod_{t=1}^{T'}p(y_t\mid y_{<t},c)`,
    latexCompact: String.raw`\begin{gathered}
\underbrace{p_t=p(y_t\mid y_{<t},c)}_{\text{t번째 다음 token 확률}}\\[4pt]
\underbrace{p(y_{1:T'}\mid x_{1:T})=\prod_{t=1}^{T'}p_t}_{\text{target 전체 확률}}
\end{gathered}`,
    meaning: '가변 길이 target 전체의 조건부 확률을 chain rule로 각 timestep의 next-token 확률 곱으로 분해한다. Encoder가 만든 c는 모든 decoder step에 조건으로 작용하고 EOS가 길이를 결정한다.',
    symbols: [[String.raw`x_{1:T}`, 'source token sequence'], [String.raw`y_{1:T'}`, 'target token sequence'], [String.raw`c`, 'encoder final representation'], [String.raw`y_{<t}`, '이전 target prefix']],
  }],
  evidence: [{ label: 'Source reversal', question: '고정 vector 모델의 optimization을 architecture 변경 없이 개선할 수 있는가?', intervention: '같은 source 문장의 word order를 뒤집어 target과의 short-term dependency를 가깝게 만든다.', observation: 'Reversal은 optimization을 쉽게 하고 translation performance를 크게 높이는 핵심 recipe로 보고된다.', supports: 'Dependency path length가 recurrent optimization에 중요함을 지지한다.', limit: 'Reversal이 언어적으로 올바른 alignment model이거나 모든 sequence task에 유리함을 뜻하지 않는다.' }, { label: 'Representation', question: '학습한 fixed vector가 sentence structure를 포착하는가?', intervention: '문장 representation의 neighborhood를 조사하고 length·word order가 다른 문장을 비교한다.', observation: 'Model이 word order에 민감하면서 의미가 유사한 문장을 가까운 표현으로 배치하는 사례를 보인다.', supports: 'Encoder state가 단순 bag-of-words를 넘어선 정보를 보존함을 시사한다.', limit: '몇 개의 nearest-neighbor 예시가 전체 geometry의 일관성을 입증하지는 않는다.' }],
  implementation: ['Source·target vocabulary, BOS/EOS, padding contract를 고정한다.', 'Multilayer LSTM encoder final state가 decoder layer별 state에 어떻게 전달되는지 shape를 명시한다.', 'Teacher-forced negative log likelihood로 학습하고 validation perplexity를 추적한다.', 'Greedy와 beam search, source normal/reversed, length bucket별 성능을 분리 비교한다.'],
  assumptions: ['Final state width가 source의 task-relevant 정보를 압축할 수 있다.', 'Train과 inference prefix distribution 차이가 감당 가능하다.'], failures: ['평균 BLEU만 보면 긴 문장에서 fixed bottleneck이 악화되는 현상을 놓친다.', 'Beam width 증가를 model improvement로 오해할 수 있다.'],
  legacy: 'Encoder–decoder conditional generation과 teacher forcing·beam search의 표준 pipeline을 확립했다. 동시에 모든 source 정보를 final state 하나에 넣는 fixed bottleneck을 선명하게 드러냈다.', nextReading: 'Bahdanau attention은 encoder state 전체를 memory로 남기고 decoder가 매 step 필요한 위치를 다시 조회해 fixed vector 병목을 제거한다.', capabilities: ['가변 길이 target 확률을 chain rule로 분해할 수 있다.', 'Source reversal이 time lag를 줄이는 이유를 계산 graph로 설명할 수 있다.', 'Model probability와 beam-search decoding을 구분할 수 있다.'],
};

export const bahdanauPaperSpec: PaperStudySpec = {
  mechanismViz: BahdanauMechanismViz,
  shortTitle: 'Jointly Learning to Align and Translate', citation: 'Bahdanau, Cho, Bengio — Neural Machine Translation by Jointly Learning to Align and Translate', yearVenue: '2015 · ICLR', sourceUrl: 'https://arxiv.org/abs/1409.0473',
  before: 'Seq2Seq는 source 길이와 무관한 fixed vector 하나에 모든 정보를 압축해 긴 문장에서 세부 정보가 손실되었다.', authorIntent: 'Decoder가 target word를 생성할 때마다 source annotation 중 관련 부분을 soft search하도록 만들어 alignment와 translation을 end-to-end로 함께 학습하려 했다.', thesis: 'Fixed-length vector 병목을 없애고 target 위치별 context를 만들면 긴 문장에서 translation 성능 저하를 완화하면서 interpretable alignment를 얻을 수 있다.',
  reconstruction: [{ label: 'BiRNN encoder', value: 'h₁…hₘ', note: '양방향 annotations' }, { label: 'Decoder state', value: 'sₜ₋₁', note: '현재 query' }, { label: 'Alignment model', value: 'eₜᵢ', note: 'additive score' }, { label: 'Dynamic context', value: 'cₜ=Σαₜᵢhᵢ', note: 'step별 source read' }],
  mechanism: ['Bidirectional encoder가 각 source 위치에 앞·뒤 문맥을 포함한 annotation hᵢ를 만든다.', '작은 feed-forward alignment model이 이전 decoder state와 각 hᵢ의 compatibility score를 계산한다.', 'Source 위치 축 softmax가 αₜᵢ를 만들고 weighted sum cₜ가 decoder의 현재 source context가 된다.', 'Translation loss의 gradient가 alignment network와 encoder까지 흐르므로 별도 word alignment label 없이 함께 학습된다.'],
  equations: [{ latex: String.raw`e_{ti}=v_a^\top\tanh(W_s s_{t-1}+W_h h_i),\qquad \alpha_{ti}=\frac{\exp(e_{ti})}{\sum_j\exp(e_{tj})}`, meaning: '이전 decoder state가 찾는 내용과 source 위치 hᵢ를 공통 hidden space에 투영해 scalar compatibility를 만든다. Source 위치에 대한 softmax가 differentiable alignment distribution을 만든다.', symbols: [[String.raw`s_{t-1}`, '이전 decoder hidden state'], [String.raw`h_i`, 'source 위치 i의 bidirectional annotation'], [String.raw`e_{ti}`, 'target t와 source i의 unnormalized score'], [String.raw`\alpha_{ti}`, '정규화된 alignment weight']] }, { latex: String.raw`c_t=\sum_{i=1}^{T_x}\alpha_{ti}h_i`, meaning: 'Target timestep마다 다른 source weighted sum을 만든다. Fixed c와 달리 cₜ의 내용은 decoder query에 따라 바뀌며, 모든 hᵢ가 external memory 역할을 한다.', symbols: [[String.raw`c_t`, 'target t 전용 context'], [String.raw`T_x`, 'source length']] }],
  evidence: [{ label: 'Length analysis', question: '긴 source에서 fixed vector의 성능 저하를 완화하는가?', intervention: 'Conventional encoder–decoder와 attention 모델을 sentence length bucket으로 비교한다.', observation: 'Attention 모델은 source length가 늘 때 기존 모델보다 성능이 덜 급격히 나빠진다.', supports: 'Dynamic source access가 fixed bottleneck을 완화한다는 핵심 주장을 지지한다.', limit: '모든 장문 문제나 quadratic attention 비용을 해결한 것은 아니다.' }, { label: 'Alignment plots', question: '학습한 weight가 언어 간 대응 관계를 포착하는가?', intervention: 'Target timestep × source position attention matrix를 heatmap으로 시각화한다.', observation: '대각선·재배열 패턴과 구문 단위의 soft alignment가 나타난다.', supports: 'Translation loss만으로 유용한 location selection이 emergent함을 보여준다.', limit: 'Attention heatmap이 번역 결정의 완전한 인과 설명이라는 뜻은 아니다.' }],
  implementation: ['Bidirectional encoder output을 [B,Tₓ,2h] memory로 보존한다.', '각 decoder step에서 state를 [B,1,a]로 projection하고 encoder projection과 broadcast 합한다.', 'Source padding 위치를 score softmax 전에 −∞로 mask한다.', 'Weight sum=1, context shape, length bucket metric, alignment heatmap을 함께 검증한다.'],
  assumptions: ['Soft alignment가 task loss만으로 충분히 식별된다.', 'Source annotation에 번역에 필요한 local·global context가 담긴다.'], failures: ['Padding mask 누락은 짧은 문장에서 padding에 weight를 배분한다.', '좋아 보이는 heatmap만 선택하면 systematic error와 diffuse attention을 숨긴다.'],
  legacy: 'Query–key compatibility, normalized weights, value weighted sum이라는 현대 attention의 연산 계약을 확립했다. 후속 dot-product와 Transformer self-attention은 score 함수와 병렬화 범위를 바꿨다.', nextReading: 'Attention Is All You Need는 decoder 보조 조회였던 attention을 sequence modeling의 주 연산으로 올리고 recurrence를 제거한다.', capabilities: ['Additive score의 tensor broadcast shape를 구현할 수 있다.', 'Padding mask가 softmax 전에 필요한 이유를 설명할 수 있다.', 'Alignment plot의 증거와 해석 한계를 구분할 수 있다.'],
};

export const transformerPaperSpec: PaperStudySpec = {
  shortTitle: 'Attention Is All You Need', citation: 'Vaswani et al. — Attention Is All You Need', yearVenue: '2017 · NeurIPS', sourceUrl: 'https://research.google/pubs/attention-is-all-you-need/', appendixUrl: 'https://arxiv.org/abs/1706.03762',
  before: 'NMT의 encoder와 decoder는 RNN·CNN을 주 backbone으로 사용하고 attention은 그 위의 보조 alignment 연산이었다. Recurrent dependency는 timestep 병렬화를 막았다.', authorIntent: 'Recurrence와 convolution을 제거하고 attention만으로 source·target dependency를 모델링해 품질과 training parallelism을 동시에 개선할 수 있는지 검증하려 했다.', thesis: 'Scaled multi-head self-attention, position encoding, residual·FFN block만으로 state-of-the-art translation quality를 더 적은 training cost에 달성할 수 있다.',
  reconstruction: [{ label: 'Embedded tokens', value: 'X + PE', note: 'content와 순서' }, { label: 'Multi-head attention', value: 'softmax(QKᵀ/√dₖ)V', note: 'token mixing' }, { label: 'Residual + FFN', value: 'Add & Norm', note: 'feature mixing' }, { label: 'Encoder/decoder stack', value: '6 + 6 layers', note: 'cross·causal 연결' }],
  mechanism: ['Self-attention으로 각 위치가 모든 위치를 한 layer에서 직접 조회하게 한다.', 'Head마다 별도 projection을 두어 서로 다른 representation subspace의 관계를 병렬 학습한다.', 'Position encoding으로 permutation-invariant attention에 순서 정보를 주입한다.', 'Decoder causal mask와 encoder–decoder attention으로 autoregressive target과 source condition을 동시에 만족한다.'],
  equations: [{ latex: String.raw`\operatorname{Attention}(Q,K,V)=\operatorname{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right)V`, meaning: '모든 query–key dot product를 matrix multiplication으로 계산하고, dₖ가 커질 때 score variance가 커져 softmax가 포화되는 것을 scaling으로 완화한 뒤 value를 합친다.', symbols: [[String.raw`Q,K,V`, 'query, key, value matrices'], [String.raw`d_k`, 'key/query dimension']] }, { latex: String.raw`\operatorname{MultiHead}(Q,K,V)=\operatorname{Concat}(head_1,\dots,head_h)W^O`, meaning: '여러 축소 projection 공간에서 attention을 독립 계산하고 concat·output projection으로 model width에 복귀한다. Head는 계산을 복제하는 것이 아니라 parameterized comparison space를 나눈다.', symbols: [[String.raw`h`, 'head count'], [String.raw`W^O`, 'head output mixing projection']] }],
  evidence: [{ label: 'Translation', question: 'Recurrence 없이 translation quality를 유지하거나 높일 수 있는가?', intervention: 'WMT14 English–German·English–French에서 Transformer base/big를 기존 recurrent·convolution systems와 비교한다.', observation: 'Transformer는 당시 강한 BLEU 결과와 낮은 training cost를 함께 보고한다.', supports: 'Attention-only backbone이 대규모 sequence transduction에서 실용적임을 지지한다.', limit: 'Architecture 외 data·regularization·optimization recipe의 기여를 완전히 분리하지 않는다.' }, { label: 'Attention variants', question: 'Head 수와 key/value dimension은 성능에 어떤 영향을 주는가?', intervention: 'Head count, dₖ/dᵥ, model size·dropout 변형을 제한된 ablation으로 비교한다.', observation: '단일 head보다 여러 head가 유리하지만 지나치게 많은 작은 head가 항상 개선되지는 않는다.', supports: '여러 representation subspace 가설을 부분 지지한다.', limit: '개별 head가 특정 언어 기능을 필연적으로 담당함을 입증하지 않는다.' }],
  implementation: ['Tokenizer·batching 후 [B,N,d_model] residual stream 계약을 먼저 고정한다.', 'QKV projection, head reshape, scaling, padding·causal mask, softmax, concat을 shape assertion과 함께 구현한다.', 'Post-LN residual block, FFN, sinusoidal position을 원 논문대로 재현한 뒤 modern variant와 분리한다.', 'Learning-rate warmup, label smoothing, beam search까지 architecture 외 recipe를 기록한다.'],
  assumptions: ['Dense N² attention이 target sequence length에서 감당 가능하다.', 'Position signal이 order-sensitive task에 충분히 학습 가능한 단서를 준다.'], failures: ['Pre-LN·RoPE·SwiGLU를 넣고 원 Transformer 재현이라고 부르면 기여가 섞인다.', 'Training throughput만 비교하고 inference KV cache·memory 비용을 놓칠 수 있다.'],
  legacy: 'Transformer는 sequence architecture의 공통 substrate가 되었지만 원 논문의 Post-LN, sinusoidal position, encoder–decoder 구성은 현대 decoder-only LLM의 전부가 아니다. 이후 연구는 normalization, position, attention sparsity, FFN, caching을 지속적으로 교체했다.', nextReading: 'BERT는 같은 encoder stack을 양방향 MLM으로 대규모 사전학습해 task별 architecture engineering을 pretrain–fine-tune paradigm으로 바꾼다.', capabilities: ['원 논문 block을 현대 LLM 변형과 구분할 수 있다.', 'Attention·FFN의 shape와 복잡도를 계산할 수 있다.', 'Ablation이 multi-head 가설을 어느 범위까지 지지하는지 평가할 수 있다.'],
};

export const bertPaperSpec: PaperStudySpec = {
  mechanismViz: BertMechanismViz,
  shortTitle: 'BERT', citation: 'Devlin et al. — BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding', yearVenue: '2018 · NAACL 2019', sourceUrl: 'https://arxiv.org/abs/1810.04805',
  before: 'Pretrained representations는 feature-based ELMo 또는 left-to-right language model fine-tuning에 의존해, 모든 layer에서 양쪽 문맥을 동시에 사용하는 범용 encoder가 부족했다.', authorIntent: 'Transformer encoder를 unlabeled text에서 deep bidirectional하게 사전학습하고 최소한의 task head로 다양한 NLP benchmark에 전이할 수 있는지 보이려 했다.', thesis: 'Masked LM과 sentence-pair pretraining으로 양방향 representation을 학습하면 task-specific architecture를 크게 만들지 않고도 token·sentence task를 개선할 수 있다.',
  reconstruction: [{ label: 'WordPiece input', value: '[CLS] A [SEP] B', note: 'token·segment·position' }, { label: 'Bidirectional encoder', value: 'L Transformer layers', note: 'padding만 mask' }, { label: 'Pretraining heads', value: 'MLM + NSP', note: 'unlabeled corpus' }, { label: 'Task fine-tuning', value: 'small output head', note: 'backbone 함께 update' }],
  mechanism: ['Prediction 대상 15%를 골라 80% [MASK], 10% random, 10% unchanged로 손상한다.', '양방향 encoder가 손상된 위치의 왼쪽·오른쪽 문맥을 모두 사용해 원 token을 복원한다.', '원 논문은 sentence A와 B가 실제 연속 문장인지 NSP로 함께 예측한다.', 'Downstream task별로 [CLS], 모든 token, start/end 위치를 읽는 최소 head를 붙이고 전체 parameter를 fine-tune한다.'],
  equations: [{
    latex: String.raw`\mathcal L=\mathcal L_{\mathrm{MLM}}+\mathcal L_{\mathrm{NSP}}`,
    latexCompact: String.raw`\begin{gathered}
\underbrace{\mathcal L_{\mathrm{MLM}}}_{\text{가린 token 복원}}\\[-1pt]
{}+\underbrace{\mathcal L_{\mathrm{NSP}}}_{\text{문장 연속 여부}}\\[3pt]
=\underbrace{\mathcal L}_{\text{원 BERT 학습 목표}}
\end{gathered}`,
    meaning: '원 BERT pretraining은 선택 token 복원 loss와 sentence-pair binary classification loss를 더한다. 이후 연구가 NSP를 제거하거나 다른 objective로 바꿨으므로 이것은 BERT 계열 전체의 필수 공식이 아니라 원 논문의 recipe다.',
    symbols: [[String.raw`\mathcal L_{\mathrm{MLM}}`, '선택 위치 vocabulary cross entropy'], [String.raw`\mathcal L_{\mathrm{NSP}}`, '[CLS] 기반 IsNext/NotNext loss']],
  }],
  evidence: [{ label: 'Task transfer', question: '하나의 pretrained encoder가 서로 다른 output structure에 전이되는가?', intervention: 'GLUE, SQuAD, SWAG 등에서 거의 같은 backbone에 task-specific output layer만 바꿔 fine-tune한다.', observation: 'Sentence classification, token/span prediction 등 여러 benchmark에서 당시 state of the art를 갱신한다.', supports: 'Deep bidirectional pretraining representation의 범용 전이 가능성을 지지한다.', limit: 'MLM·NSP 각각의 기여나 data·compute scaling 효과를 한 비교로 완전히 분리하지 않는다.' }, { label: 'Feature ablation', question: 'Bidirectionality와 pretraining objective가 성능에 기여하는가?', intervention: 'No NSP, left-to-right, shallow feature combinations 등 변형을 task별로 비교한다.', observation: '양방향 deep representation과 pretraining이 여러 downstream task에서 유리한 경향을 보인다.', supports: '단순 left-to-right representation보다 bidirectional conditioning이 이해 task에 유용함을 지지한다.', limit: '후속 RoBERTa가 보인 것처럼 원 실험 예산에서 NSP의 필수성을 확정하지 못한다.' }],
  implementation: ['Basic/large config, WordPiece vocab, max length, corpus preprocessing을 명시한다.', '15% selection과 80/10/10 corruption을 label mask와 분리 구현한다.', 'MLM·NSP loss curve와 masked-token accuracy를 따로 기록한다.', 'Task head별 input representation과 learning rate·epoch sensitivity를 재현한다.'],
  assumptions: ['Pretrain corpus의 문맥 통계가 downstream label에 유용하다.', 'Input corruption과 downstream clean input의 mismatch가 80/10/10으로 충분히 완화된다.'], failures: ['Random seed와 learning rate에 민감한 작은 dataset에서 단일 run을 결론으로 쓸 수 없다.', '[CLS]를 별도 sentence embedding objective 없이 cosine 검색에 바로 쓰면 품질이 낮을 수 있다.'],
  legacy: 'BERT는 pretrained encoder를 NLP의 기본 출발점으로 만들었다. 그러나 NSP, static mask, 512 absolute positions, [CLS] pooling은 후속 연구가 바꾼 원 설계 선택이며 현대 encoder의 필수 조건이 아니다.', nextReading: 'RoBERTa, ALBERT, ELECTRA, Sentence-BERT를 읽을 때는 BERT의 어느 축인 data recipe, parameter sharing, objective, pooling을 바꿨는지 비교하면 된다.', capabilities: ['MLM selection과 corruption 비율을 정확히 계산할 수 있다.', 'Ablation이 NSP 필수성을 확정하지 못한 이유를 설명할 수 있다.', 'Task별 output head의 representation·shape contract를 복원할 수 있다.'],
};
