import ContentBoundary from "@/components/articles/content-boundary";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import HashConstructionViz from "./HashConstructionViz";

export default function ModernHashTheoryArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Bit string에서 protocol digest까지</p><h2 className="text-3xl font-bold tracking-tight">Hash는 내용을 이해하지 않는다—정확히 같은 bytes만 같은 입력이다</h2></header><p className="text-lg leading-8">문자 <code>A</code>는 ASCII에서 <code>0x41</code>, bit로는 <code>01000001</code>입니다. Hash가 받는 것은 이 bit string이고, 출력은 고정 길이 digest입니다. 따라서 알고리즘보다 먼저 text normalization, 길이, endianness, field 순서와 type tag를 protocol로 고정해야 합니다.</p><aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> 안전한 hash 사용은 <em>canonical input → 검토된 construction → domain-separated output → 용도별 검증</em>의 연속 계약입니다. Digest 한 개가 맞는 것만으로 이 계약이 성립하지 않습니다.</aside><ContentBoundary article="hash-theory"/><HashConstructionViz/></section>
  <section id="input-security" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · 입력과 공격 game</p><h2 className="mt-2 text-2xl font-bold">Tuple ambiguity와 세 가지 보안 목표를 먼저 분리한다</h2></header><p><code>("ab","c")</code>와 <code>("a","bc")</code>를 그대로 이어 붙이면 둘 다 <code>abc</code>입니다. <code>type || length || value</code>를 각 field에 넣어야 서로 다른 논리 입력이 다른 bytes가 됩니다. Unicode NFC 여부나 integer byte order도 같은 이유로 명시해야 합니다.</p><ExplainedFormula question="n-bit ideal hash에서 세 공격의 generic work는 어떻게 다른가?" idea={<>Preimage는 정해진 digest의 입력을, second-preimage는 정해진 message와 충돌하는 다른 입력을, collision은 공격자가 고른 아무 두 입력을 찾습니다. 마지막에는 birthday effect가 적용됩니다.</>} formula={String.raw`W_{\mathrm{pre}}\approx2^n,\qquad W_{\mathrm{2nd}}\approx2^n,\qquad W_{\mathrm{coll}}\approx2^{n/2}`} terms={[{symbol:"n",name:"Digest bits",description:"Protocol이 실제로 비교하는 출력 bit 수입니다."},{symbol:"W",name:"Generic work",description:"Idealized black-box 공격의 대략적 hash evaluation 수입니다."},{symbol:"2^{n/2}",name:"Birthday scale",description:"약 2^(n/2) samples에서 pair 수가 2^n 규모가 됩니다."}]} assumptions={["Hash를 n-bit random function처럼 보는 idealized generic model입니다.","출력을 truncation하면 n은 원래 width가 아니라 실제 비교하는 bit 수입니다.","구조적 cryptanalysis, side channel, protocol misuse는 이 식 밖입니다."]} interpretation="256-bit digest는 generic preimage 약 2^256, collision 약 2^128 규모입니다. 그래서 collision resistant라는 말만으로 password hashing이나 MAC 적합성을 결론 내릴 수 없습니다."/><p><strong>반례:</strong> 256-bit hash를 64 bits로 잘라 ID로 저장하면 collision scale은 약 2³²로 내려갑니다. 원 primitive 이름만 보고 128-bit collision security라고 부르면 안 됩니다.</p></section>
  <section id="constructions" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · 두 construction</p><h2 className="mt-2 text-2xl font-bold">Compression chaining과 sponge는 경계가 다르다</h2></header><ExplainedFormula question="Fixed-size compression으로 여러 blocks를 어떻게 처리하는가?" idea={<>Merkle–Damgård 계열은 이전 chaining value와 다음 padded block을 compression function에 넣습니다. 마지막 block에는 delimiter와 원래 길이가 포함되어 parse를 유일하게 합니다.</>} formula={String.raw`h_0=IV,\qquad h_i=C(h_{i-1},m_i),\qquad H(M)=h_k`} terms={[{symbol:"IV",name:"Initial value",description:"Algorithm/version이 고정한 시작 state입니다."},{symbol:"m_i",name:"Padded block",description:"Padding과 length encoding 뒤의 i번째 fixed-size block입니다."},{symbol:"C",name:"Compression",description:"이전 state와 block을 새 state로 압축합니다."}]} assumptions={["Padding이 prefix-free 또는 표준이 요구하는 unique parse를 제공합니다.","Compression과 IV, block order, length encoding이 같은 algorithm profile입니다.","Toy arithmetic은 실제 collision resistance를 제공하지 않습니다."]} interpretation="Toy C(h,m)=3h+m mod17, h0=5, m1=7, m2=2이면 h1=5, h2=0입니다. 작은 field라 충돌이 쉬우므로 오직 chaining 계산 설명용입니다."/><ExplainedFormula question="Sponge state의 rate와 capacity는 어떻게 나뉘는가?" idea={<>Permutation state 중 rate 부분에 message를 흡수하고 출력도 rate에서 꺼냅니다. Capacity는 직접 노출하지 않아 generic security margin에 기여합니다.</>} formula={String.raw`t=r+c,\qquad S\leftarrow P\bigl(S\oplus(m_i\parallel0^c)\bigr)`} terms={[{symbol:"t",name:"State width",description:"Permutation이 처리하는 전체 state 폭입니다."},{symbol:"r",name:"Rate",description:"한 번에 흡수·squeeze하는 공개 I/O 부분입니다."},{symbol:"c",name:"Capacity",description:"직접 입출력하지 않는 내부 security 부분입니다."},{symbol:"P",name:"Permutation",description:"고정된 invertible state transformation입니다."}]} assumptions={["Padding/suffix가 message 끝과 hash/XOF 용도를 분리합니다.","선택 capacity·round 수가 요구 security level의 검토된 profile입니다.","XOR 표기는 bit sponge 기준이며 field sponge는 field addition/encoding profile을 따릅니다."]} interpretation="t=5,r=3,c=2이면 세 words를 흡수할 때마다 P를 적용합니다. r을 늘려 throughput을 높이면 c가 줄 수 있으므로 같은 width에서는 security와 맞바꿈입니다."/><p><strong>경계:</strong> Merkle–Damgård digest를 <code>H(secret || message)</code> 형태의 naive MAC으로 쓰면 length extension이 가능한 계열이 있습니다. 검토된 HMAC 또는 keyed construction을 사용합니다.</p></section>
  <section id="merkle-boundary" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Merkle로 넘기는 경계</p><h2 className="mt-2 text-2xl font-bold">Hash와 tree schema는 서로 다른 책임이다</h2></header><p>Merkle tree는 hash의 collision resistance를 이용해 일부 leaf만 열지만, leaf encoding·inner child order·tree size·odd-node rule을 별도 schema로 고정해야 합니다. <code>H(0x00 || len || leaf)</code>와 <code>H(0x01 || left || right)</code>처럼 domain을 나누면 leaf가 internal preimage로 재해석되는 위험을 줄입니다. 선택적 opening의 증명과 비용은 <a className="text-primary underline" href="/crypto/merkle-tree">Merkle 정본</a>이 소유합니다.</p></section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Known vector와 실패 fixture를 통과한 뒤 속도를 잰다</h2></header><p>Algorithm/version, input encoding, domain, output length를 receipt에 고정합니다. Empty·<code>abc</code>·block−1/block/block+1·one-shot/chunked·tag swap·truncation·cross-library vectors가 같은 결과 또는 의도한 reject를 내야 합니다. 그 다음에야 같은 CPU와 message-size distribution에서 latency·throughput·allocation을 비교하며 old artifact rollback을 보존합니다.</p>
  <div id="paper-fips-180-4"><CitationBlock source="NIST · FIPS 180-4 Secure Hash Standard" citeKey={1} href="https://csrc.nist.gov/pubs/fips/180-4/upd1/final"><p><strong>문제:</strong> SHA-2 계산을 bit-level로 상호운용해야 합니다.</p><p><strong>기여:</strong> Padding, functions와 digest의 normative contract를 제공합니다.</p><p><strong>전제:</strong> 선택 variant와 표준 message convention을 사용합니다.</p><p><strong>근거 범위:</strong> 표준에 명시된 SHA-2 construction입니다.</p><p><strong>말하지 않는 것:</strong> 모든 protocol 사용이나 구현 side-channel 안전성을 보장하지 않습니다.</p></CitationBlock></div>
  <div id="paper-fips-202"><CitationBlock source="NIST · FIPS 202 SHA-3 Standard" citeKey={2} href="https://csrc.nist.gov/pubs/fips/202/final"><p><strong>문제:</strong> Permutation-based hash와 XOF를 표준화해야 합니다.</p><p><strong>기여:</strong> KECCAK-p, SHA3, SHAKE와 suffix contract를 제공합니다.</p><p><strong>전제:</strong> 표준 parameter·padding을 그대로 사용합니다.</p><p><strong>근거 범위:</strong> FIPS SHA-3/SHAKE construction입니다.</p><p><strong>말하지 않는 것:</strong> 임의 sponge profile을 승인하지 않습니다.</p></CitationBlock></div>
  <div id="paper-rustcrypto-hashes"><CitationBlock source="RustCrypto · hashes pinned source f6c786d" citeKey={3} href="https://github.com/RustCrypto/hashes/tree/f6c786d72ed4d37a32dcd32daa2e7277dd4683e1"><p><strong>문제:</strong> 실제 Rust streaming source seam을 확인해야 합니다.</p><p><strong>기여:</strong> Implementations와 tests의 pinned snapshot입니다.</p><p><strong>전제:</strong> Commit과 dependencies/target을 고정합니다.</p><p><strong>근거 범위:</strong> 선택 commit의 source/API입니다.</p><p><strong>말하지 않는 것:</strong> 모든 target audit나 향후 release를 보장하지 않습니다.</p></CitationBlock></div></section>
</article>}
