import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { BullsharkOrderingViz, BullsharkWaveViz } from "./viz/ModernBullsharkViz";

export default function ModernBullsharkArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">Certificate DAG · ordering plane</p><h2 className="text-3xl font-bold tracking-tight">Bullshark는 Narwhal certificate DAG의 edges를 leader vote로 읽고 한 sequence를 만든다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">Narwhal이 Alice→Bob batch의 bytes를 분산 저장하고 certificate vertex를 만들었다고 하겠습니다. 이 시점에는 availability와 causal history는 있지만 transaction의 전역 순서는 없습니다. Bullshark는 rounds를 wave로 묶고 미리 정한 leader certificate가 다음 round children에게 충분히 참조됐는지 봅니다. Supported leader를 찾으면 그 leader가 도달하는 과거 leaders와 아직 출력하지 않은 ancestors를 오래된 순서로 펼칩니다.</p>
      <p>따라서 책임은 세 층입니다. Narwhal certificate가 data availability를 맡고, Bullshark가 leader decision과 deterministic certificate order를 맡으며, application이 certificate가 가리키는 transactions를 실행합니다. Leader를 local에서 먼저 봤다는 사실이나 certificate arrival order는 합의 근거가 아닙니다.</p>
      <BullsharkWaveViz />
      <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> Bullshark가 추가 ordering vote messages를 보내는 대신 이미 certificate DAG에 들어 있는 causal references를 vote evidence로 해석합니다. 하지만 어떤 leader·threshold·timing 전제를 쓰는지는 protocol variant와 pinned 구현별로 구분해야 합니다.</aside>
    </section>

    <section id="wave-anchor" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · wave와 leader support</p><h2 className="mt-2 text-2xl font-bold">Current supported leader에서 reachable earlier leaders를 찾아 oldest-first로 결정한다</h2></header>
      <p>Round는 validators가 certificate vertices를 만드는 logical step이고, wave는 여러 rounds를 묶어 leader 판정을 반복하는 단위입니다. Leader schedule은 특정 round의 validator를 anchor 후보로 정합니다. Archived standalone implementation은 even-round leader를 찾고, 다음 round certificate authors 가운데 그 leader를 parent로 참조한 distinct authors의 stake가 validity threshold에 닿는지 검사합니다. Equal-weight n=4,f=1 예에서는 <code>f+1=2</code> support입니다. 이는 historical implementation의 조건이며 다른 paper variant의 모든 threshold로 일반화하지 않습니다.</p>
      <ExplainedFormula question="Archived n=4,f=1 구현에서 leader support를 어떻게 계산하는가?" idea={<>다음 round의 distinct certificate authors 가운데 causal parents로 leader를 지지한 voting power를 더해 validity threshold와 비교합니다. Equal-weight 예에서 threshold는 f+1=2입니다.</>} formula={String.raw`\begin{aligned}S(L_r)&=\sum_{a\in C_{r+1}}w(a)I_a(L_r)\\I_a(L_r)&=1\iff L_r\in parents(a)\\S(L_r)&\ge f+1\end{aligned}`} terms={[{symbol:"Lᵣ",name:"predefined leader",description:"Leader schedule이 round r에 고른 certificate입니다."},{symbol:"Cᵣ₊₁",name:"next-round authors",description:"Round r+1 valid certificates를 만든 distinct validators입니다."},{symbol:"w(a)",name:"voting power",description:"Pinned historical committee에서 author a의 weight입니다."},{symbol:"Iₐ(Lᵣ)",name:"support indicator",description:"Child가 leader를 causal parent로 지지하면 1, 아니면 0입니다."}]} assumptions={["Archived commit e67f915 standalone partial-synchrony implementation의 판정입니다.","Certificate·parent links와 distinct author voting power를 먼저 검증합니다.","Equal-weight n=4,f=1 예에서 validity threshold f+1은 2입니다.","Support 판정은 application execution이나 모든 Bullshark variants의 고정 threshold가 아닙니다."]} interpretation="A와 B의 round r+1 certificates가 Lr을 참조하면 support=2라 threshold를 만족합니다. A의 certificate를 중복 수신해 두 표로 세거나, parent edge가 없는 C를 더해서는 안 됩니다." />
      <p>새 leader L4가 supported이고 L4의 causal history가 이전 leader L2에 닿으면 L2를 먼저, L4를 나중에 결정합니다. L2를 당시 직접 commit하지 못했더라도 later anchor가 공통 evidence를 제공해 회수할 수 있습니다. 반대로 L4에서 L2로 가는 certified link가 없다면 local 추측으로 L2를 끼워 넣지 않습니다. 모든 replica가 같은 DAG에서 같은 oldest-first leader list를 얻어야 합니다.</p>
      <div id="paper-bullshark"><CitationBlock source="Bullshark: DAG BFT Protocols Made Practical" citeKey={1} href="https://arxiv.org/abs/2201.05677"><p><strong>문제:</strong> Certified DAG에서 별도 ordering messages를 늘리지 않고 practical atomic broadcast를 만들어야 합니다.</p><p><strong>기여:</strong> Wave·leader interpretation과 synchronous fast path를 갖는 Bullshark protocol variants를 제시합니다.</p><p><strong>전제:</strong> n=3f+1 authenticated committee와 variant별 partial synchrony 또는 asynchronous common-coin model을 사용합니다.</p><p><strong>근거 범위:</strong> Bullshark variants의 constructions, correctness proofs와 paper evaluation입니다.</p><p><strong>말하지 않는 것:</strong> 모든 DAG protocol·implementation이 같은 wave length, threshold, fairness나 latency를 가진다는 뜻은 아닙니다.</p></CitationBlock></div>
      <div id="paper-bullshark-e67"><CitationBlock source="MystenLabs/narwhal commit e67f915 — bullshark.rs" citeKey={2} type="code" href="https://github.com/MystenLabs/narwhal/blob/e67f91530e6bd4ef7808e42f548f07e58764ec5b/consensus/src/bullshark.rs"><p><strong>문제:</strong> Certificate arrival마다 supported leaders와 commit sequence를 deterministic하게 갱신해야 합니다.</p><p><strong>기여:</strong> Even-round leader selection, f+1 support, prior-leader recovery와 sub-DAG ordering을 구현합니다.</p><p><strong>전제:</strong> Archived exact commit e67f915의 Committee, ConsensusState, leader schedule과 GC configuration을 사용합니다.</p><p><strong>근거 범위:</strong> Historical standalone partially synchronous Bullshark implementation에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Current Sui consensus나 asynchronous coin variant의 구현, 보편 parameter를 나타내지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="ordering" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · deterministic sub-DAG</p><h2 className="mt-2 text-2xl font-bold">Leader의 새 ancestors만 stable key로 펼치고 이미 출력한 vertex는 제외한다</h2></header>
      <p>Leader decision은 아직 transaction sequence 전체가 아닙니다. Node는 committed leader가 도달하는 certificates를 거슬러 올라가되 이미 committed한 vertices를 제외하고, round가 오래된 것부터 stable author/digest tie-break로 정렬합니다. Certificate 안의 transaction batch order까지 고정한 뒤 output digest를 계산합니다. HashMap iteration이나 local network arrival order를 tie-break로 사용하면 같은 DAG를 가진 replicas도 state root가 갈릴 수 있습니다.</p>
      <BullsharkOrderingViz />
      <p>예를 들어 node A가 C3→A1→B2 순서로 받고 node B가 B2→C3→A1 순서로 받더라도 검증된 DAG set과 edges가 같으면 결과가 같아야 합니다. L2 sub-DAG를 먼저 출력한 뒤 L4를 commit했다면 L4 history에서 L2 이전 vertices를 중복 출력하지 않고 새 causal suffix만 이어 붙입니다. 이는 certificate order이며 application validity, transaction fairness와 successful execution은 별도 receipt입니다.</p>
      <div id="paper-bullshark-utils-e67"><CitationBlock source="MystenLabs/narwhal commit e67f915 — consensus ordering utilities" citeKey={3} type="code" href="https://github.com/MystenLabs/narwhal/blob/e67f91530e6bd4ef7808e42f548f07e58764ec5b/consensus/src/utils.rs"><p><strong>문제:</strong> Committed leader의 causal history를 arrival order와 무관한 duplicate-free sequence로 바꿔야 합니다.</p><p><strong>기여:</strong> Reachable certificates를 수집하고 stable ordering으로 sub-DAG를 평탄화하는 historical utility를 제공합니다.</p><p><strong>전제:</strong> Exact archived commit e67f915, validated certificate DAG와 matching consensus state를 사용합니다.</p><p><strong>근거 범위:</strong> 이 pinned implementation의 leader sub-DAG traversal과 deterministic ordering 경로입니다.</p><p><strong>말하지 않는 것:</strong> Transaction 내부 fairness, application success, current Sui linearizer나 모든 DAG의 보편 tie-break를 규정하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="release" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · variant·failure·release</p><h2 className="mt-2 text-2xl font-bold">Safety는 conflict 없음으로, liveness는 해당 timing model에서 eventual commit으로 따로 검사한다</h2></header>
      <p>Network partition이나 leader omission 중 commit이 멈춰도 서로 다른 honest replicas가 conflicting sequences를 확정하지 않았다면 safety는 유지될 수 있습니다. Liveness는 variant가 요구하는 조건이 회복된 뒤 새 supported leader와 contiguous output이 결국 생기는지를 묻습니다. Partial-synchrony variant는 GST 이후 bounded delay와 honest leader/support를 재생하고, asynchronous variant는 논문의 common-coin 경로를 따로 검증해야 합니다. 두 설명을 하나의 implementation 특성처럼 합치면 안 됩니다.</p>
      <p>Release suite는 unsupported L2와 supported L4를 만들고 L4→L2 causal link가 있는 경우 L2→L4, 없는 경우 L4만 나오는지 비교합니다. 같은 certificates를 여러 arrival permutations과 map insertion orders로 replay해 output digest가 같은지도 봅니다. Leader omission·Byzantine equivocation에서는 invalid support를 배제하고 conflict 0을 safety oracle로, network recovery 뒤 eventual commit을 liveness oracle로 둡니다.</p>
      <p>Crash·restart에서는 exact source commit과 variant manifest, last-committed leader map, DAG/GC watermark를 고정합니다. Persisted boundary에서 DAG를 재구성해 state parity를 확인하고, 불완전한 local output만 rollback합니다. Ordered certificate가 가리키는 payload를 hash-verify하고 application state receipt가 생긴 뒤에만 Bob의 balance 변경을 release합니다.</p>
      <h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 Narwhal/Bullshark 경계, round·wave·leader·support, f+1 예, direct/indirect leader 회수, sub-DAG order와 safety/liveness를 묻습니다. 심화 4문제는 causal-link 두 traces, arrival-order parity, partition/equivocation oracle와 archived restart·GC suite를 설계하게 합니다.</p>
    </section>
  </article>;
}
