import type {CodeRef,FileNode,ProjectMeta} from "@/components/code/types";
import call from "./verification/main.go?raw";
import setup from "./codebase/gnark/backend/plonk/bn254/setup.go?raw";
import ratio from "./codebase/gnark-crypto/ecc/bn254/fr/iop/ratios.go?raw";
import config from "./codebase/gnark/backend/backend.go?raw";
import prove from "./codebase/gnark/backend/plonk/bn254/prove.go?raw";
import verify from "./codebase/gnark/backend/plonk/bn254/verify.go?raw";
import encoding from "./codebase/gnark/backend/plonk/bn254/marshal.go?raw";
export const codeRefs:Record<string,CodeRef>={
"call":{code:call,"path": "case/main.go", "highlight": [25, 36], "lang": "go", "desc": "별도 작성해 실행한 회로입니다. 공개 X·Y와 비공개 W로 v=XW, Y=v+X를 같은 변수의 흐름으로 제약합니다.", "annotations": [{"lines": [25, 36], "color": "sky", "note": "별도 작성해 실행한 회로입니다. 공개 X·Y와 비공개 W로 v=XW, Y=v+X를 같은 변수의 흐름으로 제약합니다."}]} ,
"selectors":{code:setup,"path": "gnark/backend/plonk/bn254/setup.go", "highlight": [164, 213], "lang": "go", "desc": "공개 입력 2줄에는 −L+공개값을 적용하고 뒤에 컴파일한 산술 제약 3줄을 붙입니다. 실제 영역 크기는 8입니다.", "annotations": [{"lines": [164, 213], "color": "sky", "note": "공개 입력 2줄에는 −L+공개값을 적용하고 뒤에 컴파일한 산술 제약 3줄을 붙입니다. 실제 영역 크기는 8입니다."}]} ,
"copy":{code:setup,"path": "gnark/backend/plonk/bn254/setup.go", "highlight": [289, 342], "lang": "go", "desc": "숫자 값이 아닌 변수 번호를 묶습니다. 실제 중간값 변수의 위치 18과 11은 한 순환입니다.", "annotations": [{"lines": [289, 342], "color": "sky", "note": "숫자 값이 아닌 변수 번호를 묶습니다. 실제 중간값 변수의 위치 18과 11은 한 순환입니다."}]} ,
"ratio":{code:ratio,"path": "crypto/ecc/bn254/fr/iop/ratios.go", "highlight": [138, 245], "lang": "go", "desc": "값에 원래 위치와 순열 위치를 각각 섞어 n개의 누적 평가를 만듭니다. 마지막 줄의 닫힘 검사는 뒤의 다항식 관계에 남습니다.", "annotations": [{"lines": [138, 245], "color": "sky", "note": "값에 원래 위치와 순열 위치를 각각 섞어 n개의 누적 평가를 만듭니다. 마지막 줄의 닫힘 검사는 뒤의 다항식 관계에 남습니다."}]} ,
"config":{code:config,"path": "gnark/backend/backend.go", "highlight": [59, 82], "lang": "go", "desc": "기본 StatisticalZK는 false입니다. 같은 파일 140–147행의 WithStatisticalZeroKnowledge가 true로 바꿉니다.", "annotations": [{"lines": [59, 82], "color": "sky", "note": "기본 StatisticalZK는 false입니다. 같은 파일 140–147행의 WithStatisticalZeroKnowledge가 true로 바꿉니다."}]} ,
"blinding":{code:prove,"path": "gnark/backend/plonk/bn254/prove.go", "highlight": [61, 75], "lang": "go", "desc": "wire의 무작위 다항식은 일차, Z는 이차입니다. 같은 파일 259–265행에서 실제로 생성합니다.", "annotations": [{"lines": [61, 75], "color": "sky", "note": "wire의 무작위 다항식은 일차, Z는 이차입니다. 같은 파일 259–265행에서 실제로 생성합니다."}]} ,
"split":{code:prove,"path": "gnark/backend/plonk/bn254/prove.go", "highlight": [689, 724], "lang": "go", "desc": "옵션이 켜졌을 때 세 조각에 rX^(n+2), −r+sX^(n+2), −s를 넣어 결합을 보존합니다.", "annotations": [{"lines": [689, 724], "color": "sky", "note": "옵션이 켜졌을 때 세 조각에 rX^(n+2), −r+sX^(n+2), −s를 넣어 결합을 보존합니다."}]} ,
"transcript":{code:verify,"path": "gnark/backend/plonk/bn254/verify.go", "highlight": [87, 123], "lang": "go", "desc": "공개 데이터와 wire 약정 뒤 γ·β, Z 뒤 α, 몫 약정 뒤 ζ를 얻습니다. 325–365행은 공개 입력을 넣는 부분입니다.", "annotations": [{"lines": [87, 123], "color": "sky", "note": "공개 데이터와 wire 약정 뒤 γ·β, Z 뒤 α, 몫 약정 뒤 ζ를 얻습니다. 325–365행은 공개 입력을 넣는 부분입니다."}]} ,
"verify":{code:verify,"path": "gnark/backend/plonk/bn254/verify.go", "highlight": [39, 85], "lang": "go", "desc": "공개 입력 2개와 평가값 6개 등 구조를 먼저 검사하고 점의 유효성을 확인합니다. 이번 긴 입력은 길이 오류였습니다.", "annotations": [{"lines": [39, 85], "color": "sky", "note": "공개 입력 2개와 평가값 6개 등 구조를 먼저 검사하고 점의 유효성을 확인합니다. 이번 긴 입력은 길이 오류였습니다."}]} ,
"proof":{code:prove,"path": "gnark/backend/plonk/bn254/prove.go", "highlight": [78, 96], "lang": "go", "desc": "wire 3개·Z 1개·몫 3개와 두 열기를 저장합니다. 이번 회로의 부가 약정은 없습니다.", "annotations": [{"lines": [78, 96], "color": "sky", "note": "wire 3개·Z 1개·몫 3개와 두 열기를 저장합니다. 이번 회로의 부가 약정은 없습니다."}]} ,
"encoding":{code:encoding,"path": "gnark/backend/plonk/bn254/marshal.go", "highlight": [23, 89], "lang": "go", "desc": "점과 평가값 및 배열 길이를 쓰고 다시 읽습니다. 실제 압축 크기는 520바이트이며 ReadFrom은 뒤에 붙인 한 바이트를 남겼습니다.", "annotations": [{"lines": [23, 89], "color": "sky", "note": "점과 평가값 및 배열 길이를 쓰고 다시 읽습니다. 실제 압축 크기는 520바이트이며 ReadFrom은 뒤에 붙인 한 바이트를 남겼습니다."}]} ,
"missing":{code:call,"path": "case/main.go", "highlight": [38, 50], "lang": "go", "desc": "비교용으로 의도적으로 V와 XW의 연결을 빠뜨린 별도 회로입니다. 원래 회로의 키를 사용하는 검증과 구별합니다.", "annotations": [{"lines": [38, 50], "color": "sky", "note": "비교용으로 의도적으로 V와 XW의 연결을 빠뜨린 별도 회로입니다. 원래 회로의 키를 사용하는 검증과 구별합니다."}]} ,
};
export const fileTrees:Record<string,FileNode>={"gnark": {"name": "gnark 0.16.3 원문", "type": "dir", "children": [{"name": "setup.go", "type": "file", "path": "gnark/backend/plonk/bn254/setup.go", "codeKey": "selectors"}, {"name": "backend.go", "type": "file", "path": "gnark/backend/backend.go", "codeKey": "config"}, {"name": "prove.go", "type": "file", "path": "gnark/backend/plonk/bn254/prove.go", "codeKey": "blinding"}, {"name": "verify.go", "type": "file", "path": "gnark/backend/plonk/bn254/verify.go", "codeKey": "transcript"}, {"name": "marshal.go", "type": "file", "path": "gnark/backend/plonk/bn254/marshal.go", "codeKey": "encoding"}]}, "crypto": {"name": "gnark-crypto 0.21.0 원문", "type": "dir", "children": [{"name": "ratios.go", "type": "file", "path": "crypto/ecc/bn254/fr/iop/ratios.go", "codeKey": "ratio"}]}, "case": {"name": "실제 실행한 별도 호출 예제", "type": "dir", "children": [{"name": "main.go", "type": "file", "path": "case/main.go", "codeKey": "call"}]}};
export const projectMetas:Record<string,ProjectMeta>={"gnark": {"id": "gnark", "label": "gnark 0.16.3 원문", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}, "crypto": {"id": "crypto", "label": "gnark-crypto 0.21.0 원문", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}, "case": {"id": "case", "label": "실제 실행한 별도 호출 예제", "badgeClass": "border-sky-300 bg-sky-50 text-sky-800"}};
