import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import { CitationBlock } from "@/components/ui/citation";
import AlgorithmBlock from "@/components/ui/algorithm-block";
import { ChangelogEvidenceViz } from "../architecture-decision-records/viz/OperationalRecordsViz";
export default function ModernArticle() { return <div className="space-y-16"><section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 무엇이 달라졌는지 사용자가 확인할 수 있어야 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>수정이 여러 번 쌓이면 작업 기록을 모두 읽어도 사용자가 무엇을 주의해야 하는지 찾기 어렵습니다. 저장 오류를 고쳤다면 어떤 데이터가 보존되는지, 어느 버전에서 쓸 수 있는지, 무엇으로 확인했는지가 필요합니다.</p><p>이 글은 빈 결과가 기존 기록을 덮어쓰던 오류 하나를 고친 뒤 검증하고 공개 이력에 싣는 과정을 따라갑니다.</p></div></section><section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 변화의 영향과 검사와 공개 상태를 잇습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            먼저 누가 알아야 할 변화인지 고릅니다. 같은 조건에서 바뀐 동작을 검사하고 아직 배포 전이면 예정된 변화로 둡니다. 실제 공개를 확인하면 날짜와 버전을 붙이고 상세 근거로
            돌아갈 길을 남깁니다.
          </p></div><ol className="my-8 grid list-none gap-4 p-0 sm:grid-cols-2"><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">1</span><span>독자에게 달라진 동작을 고른다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">2</span><span>같은 조건의 결과를 검사한다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">3</span><span>공개한 위치와 버전을 확인한다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">4</span><span>짧은 항목에서 상세 근거로 연결한다</span></li></ol></section><section id="small-case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 빈 결과가 기존 기록 12개를 지웠습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>프로필 A에 기록 12개가 있습니다. 정리 작업이 실패해 빈 결과 0개를 반환했는데 이를 정상 결과로 받아 기존 내용을 교체했다고 합시다. 사용자는 12개를 잃습니다. 수정 후에는 이 경로를 막고 기존 12개를 보존해야 합니다. (가정)</p><p>검사는 빈 결과 0개, 불완전한 결과 5개, 검증한 전체 결과 12개, 명시적으로 허용한 삭제 0개의 4가지로 정합니다. 앞의 두 경우는 보존, 전체 결과는 검증 후 교체, 삭제는 별도 권한과 대상 확인 후 처리합니다. 단순히 길이가 양수인지 보는 수정은 충분하지 않습니다. (가정)</p></div></section><section id="inside-entry" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 결과 문장 뒤에 검사와 공개 위치를 둡니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>짧은 변경 항목에는 빈 결과의 자동 덮어쓰기를 막았다는 결과와 프로필 기록 보존이라는 영향을 적습니다. 검사 4개를 어디서 실행했는지, 어떤 코드로 했는지, 공개한 버전이 무엇인지 상세 기록에 연결합니다.</p><p>
            검사를 통과했어도 운영 환경이 예전 코드를 쓰면 사용자는 같은 오류를 만날 수 있습니다. 구현, 검사, 병합, 공개를 한 단어의 “완료”로 합치지 않습니다.
          </p></div></section><section id="why-entry" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 수정 횟수보다 실제 동작의 변화가 필요합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            들여쓰기를 세 번 고쳤다는 기록과 빈 결과가 12개를 지우지 않게 됐다는 기록은 독자에게 주는 정보가 다릅니다. 사용자와 운영자가 알아야 할 동작 변화에 집중하고 상세 작업
            과정은 연결한 실행 기록에 남깁니다.
          </p><p>반대로 항목을 짧게 만들려고 검사 근거를 모두 없애면 누가 어떤 조건에서 확인했는지 검토하기 어렵습니다. 결과 문장과 상세 근거의 역할을 나누어 연결해야 합니다.</p></div></section><section id="entry-terms" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 변경 항목과 공개 상태의 이름을 붙입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>버전별로 독자가 알아야 할 변화를 골라 시간순으로 남기는 문서가 Changelog입니다. 이 글의 결과·영향·검사·근거 형식은 내부 기록을 위한 확장이고 모든 프로젝트의 의무 양식은 아닙니다.</p></div><TermBreakdown title="역할을 이해한 뒤 이름을 붙입니다" items={[{"term": "Curated entry / notable change", "description": "사람에게 필요한 변화를 골라 적은 항목과 포함할 만한 변화입니다.", "boundary": "Commit 수가 아니라 독자와 관찰 가능한 영향으로 판단합니다."}, {"term": "Unreleased / released", "description": "다음 공개에 포함할 변화와 실제 공개한 버전의 구분입니다.", "boundary": "패키지 출시와 각 운영 환경의 배포 상태도 필요하면 구분합니다."}, {"term": "Verification / publication", "description": "정한 검사를 통과한 사실과 독자가 사용할 수 있게 공개한 사실입니다.", "boundary": "검사 성공만으로 모든 환경의 반영을 주장하지 않습니다."}, {"term": "Stable evidence link", "description": "실행·코드·검사·결정을 같은 식별자로 찾게 하는 참조입니다.", "boundary": "식별자만 고정해도 대상 삭제나 접근권한 변경을 자동으로 막지는 못합니다."}]} /><ChangelogEvidenceViz /></section><section id="publication" data-teach-level="4" className="scroll-mt-20"><span id="notability" className="scroll-mt-20" /><h2 className="mb-6 text-2xl font-bold">7. 검사 4개가 끝나도 아직 Unreleased일 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            수정 코드의 run-1842에서 빈 결과와 부분 결과는 기존 12개를 보존하고 전체 결과는 허용된 교체를 수행하며 명시적 삭제는 별도 경로에서 0개가 됐다고 합시다. 각 검사에
            기대값과 실제값을 남겨 4/4 통과를 확인합니다. (가정)
          </p><p>이때 문서 상단의 Unreleased에 “빈 정리 결과가 기존 프로필을 자동으로 덮어쓰지 않도록 수정”이라고 적습니다. 운영 반영 전이라면 날짜가 있는 배포 완료 항목으로 옮기지 않습니다. (가정)</p><p>예시 서비스의 v1.4.0을 2026-04-16에 배포하고 같은 공개 위치를 확인한 뒤 해당 버전 아래로 옮깁니다. 실제 사건을 보고한 날짜가 아니라 설명용 날짜입니다. 공개 대상이 패키지라면 릴리스 확인과 각 설치 환경의 업그레이드는 별도입니다. (가정)</p></div></section><section id="entry-source" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 공식 예시의 Unreleased와 Fixed에 같은 변화를 넣습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Keep a Changelog 1.1.0 페이지의 실제 문서 예시는 상단에 Unreleased를 두고 날짜가 있는 버전 아래에 Added·Fixed 같은 구분을 사용합니다. 사례는 기존 동작의 오류를 고쳤으므로 Fixed에 해당합니다.</p><p>원문의 원칙은 버전과 절을 링크할 수 있게 하라고 설명합니다. 이 글에서는 그 원칙을 확장해 run-1842와 고정 코드·검사 결과를 연결합니다. 실제 식별자 대신 이 예시의 문자열을 운영 증거처럼 링크해서는 안 됩니다. (가정)</p></div><div id="paper-keep-a-changelog" className="mt-8 scroll-mt-20"><CitationBlock source="Keep a Changelog 1.1.0 — Guiding Principles" citeKey={1} href="https://keepachangelog.com/en/1.1.0/"><q>Versions and sections should be linkable.</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            사용자가 v1.4.0의 Fixed 항목을 바로 찾게 하고 내부 검토자는 같은 항목에서 4개 검사의 실행 근거로 이동하게 합니다. 공개 문서에는 이해에 필요한 결과를 쓰고 민감한
            원문은 접근을 제한한 자료에 보존합니다.
          </p></div></div><AlgorithmBlock title="예시 변경 항목을 만드는 순서 — 실제 배포 기록이 아닌 가정" input={["기대값과 실제값을 남긴 검사 4개", "공개 대상의 버전 및 반영 확인"]} steps={[{"code": "Unreleased → Fixed: 빈 정리 결과의 자동 교체를 차단", "note": "검증 후에도 공개 전 상태를 유지합니다."}, {"code": "Evidence: run-1842; test-empty / partial / full / delete", "note": "4가지 결과와 코드 버전을 같은 실행에 묶습니다."}, {"code": "After release check: v1.4.0 — 2026-04-16", "note": "정해진 공개 대상에서 반영을 확인하고 옮깁니다."}, {"code": "Link entry → immutable run / code / verification record", "note": "실제 기록에서는 완전한 식별자와 보존 위치를 사용합니다."}]} output="동작 변화·공개 상태·검증 근거를 찾을 수 있는 항목" /></section><section id="links" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 상세 자료를 옮겨도 같은 검사로 돌아가야 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>코드의 변경 번호, 실행 ID, 검사 결과, 필요하면 ADR-005를 연결합니다. 코드 파일의 현재 main 링크만 남기면 나중에 내용이 달라져 run-1842가 무엇을 검사했는지 불명확해집니다. 고정 revision과 결과의 hash 등으로 같은 자료인지 확인할 수 있게 합니다.</p><p>링크가 열리는지, 이동 뒤 다른 자료가 됐는지, 검토자가 읽을 권한이 있는지, 자료를 언제까지 보존하는지 담당자를 정합니다. 고객 기록 12개의 원문이나 비밀 키는 공개 변경 이력에 복사하지 않습니다. 필요한 영향과 검사 요약만 공개합니다.</p></div></section><section id="entry-limits" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 통과한 네 가지 조건 밖의 안정성은 따로 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>4/4 통과는 정한 예시의 통과입니다. 동시 쓰기, 저장 도중 중단, 다른 데이터 형식까지 검증한 것은 아닙니다. 실제 릴리스의 범위와 남은 문제를 과장하지 않습니다.</p><p>
            사용자에게 중요한 제거·지원 종료·호환성 변경도 누락하지 않아야 합니다. Formatting 같은 변화는 대개 사용자 항목에서 빼지만 출력 형식 자체가 계약이면 의미 있는
            변경일 수 있어 독자와 영향을 먼저 봅니다.
          </p></div><ContentBoundary article="agent-changelog-evidence" /></section><section id="prediction-questions" data-teach-level="review" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 검사와 공개 상태를 구분할 수 있나요</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>검사 4개가 통과했지만 운영 서비스는 이전 버전입니다. 항목은 어디에 두어야 하나요? (답: 7절)</p><p>결과가 5개로 줄었지만 0개는 아닙니다. 길이가 양수라는 이유만으로 정상 교체라고 발표해도 될까요? (답: 3절)</p><p>실행 근거가 이동했고 링크는 열리지만 내용이 바뀌었습니다. 어떤 정보를 함께 남겨야 같은 검사인지 확인할 수 있나요? (답: 9절)</p></div></section></div>; }
