import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { EvmFailureViz, EvmStepTraceViz } from "./viz/ModernEvmFundamentalsViz";

export default function ModernEvmFundamentalsArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">EVM fundamentals · deterministic execution</p><h2 className="text-3xl font-bold tracking-tight">EVM은 코인을 보내는 장치가 아니라, 같은 transaction과 앞선 상태에서 같은 다음 상태를 계산하는 256-bit stack machine이다</h2></header>
    <p className="text-lg leading-8 text-foreground/90">Alice가 Bob에게 10을 보내는 transaction을 생각해 보겠습니다. Node는 서명과 nonce 같은 block-level 조건을 확인하고 실행 환경을 만든 뒤 bytecode를 한 opcode씩 실행합니다. EVM의 출력은 성공 여부 하나가 아니라 변경된 world state, 남은 gas, logs와 return data입니다.</p><p><strong>Stack</strong>은 opcode가 바로 꺼내 쓰는 256-bit word 저장소이고, <strong>memory</strong>는 한 call frame 동안만 사는 byte array이며, <strong>storage</strong>는 account에 귀속되어 transaction 뒤에도 남을 수 있는 key-value 상태입니다. 이 셋을 섞으면 비용과 rollback 범위를 잘못 판단합니다.</p><EvmStepTraceViz />
    <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>책임 분리:</strong> EVM은 후보 block 안 transaction의 deterministic state transition을 계산합니다. 어떤 block을 canonical head로 고를지는 consensus client와 fork choice의 책임입니다.</aside>
  </section>
  <section id="machine-step" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · machine state and one step</p><h2 className="mt-2 text-2xl font-bold">Program counter가 opcode를 읽고, stack·memory·gas를 한 단계 전이한다</h2></header>
    <p>Execution environment에는 현재 contract address, original sender, immediate caller, call value, input bytes, code, block header, call depth와 static write permission이 들어갑니다. Machine state에는 available gas, program counter, memory, active memory size와 stack이 있습니다. <code>ADD</code>라면 stack 위 두 word를 꺼내 2²⁵⁶ modular addition 결과를 다시 올립니다.</p>
    <ExplainedFormula question="왜 EVM 정수 덧셈은 2²⁵⁶을 넘으면 처음부터 다시 시작하는가?" idea={<>Stack word 폭이 256-bit로 고정되어 있기 때문입니다. 결과의 하위 256 bits만 남기는 것은 구현 편의가 아니라 machine semantics입니다.</>} formula={String.raw`z=(x+y)\bmod 2^{256}`} terms={[{symbol:"x,y",name:"입력 words",description:"Stack에서 꺼낸 0 이상 2²⁵⁶ 미만의 정수입니다."},{symbol:"z",name:"결과 word",description:"Stack에 다시 넣는 하위 256-bit 값입니다."},{symbol:"mod",name:"나머지",description:"고정 word 폭을 넘는 carry를 버립니다."}]} assumptions={["ADD opcode의 unsigned word 표현을 설명합니다.","Signed 비교는 같은 bits를 two's complement로 해석하는 별도 opcode 규칙입니다.","Gas가 부족하거나 stack item이 모자라면 수식보다 먼저 exceptional halt가 납니다.","Solidity의 checked arithmetic과 EVM word arithmetic을 같은 층으로 보지 않습니다."]} interpretation="x=2²⁵⁶-1, y=1이면 z=0입니다. 다만 고수준 언어 compiler가 그 전에 overflow check와 REVERT code를 넣을 수 있습니다." />
    <div id="paper-yellow-paper"><CitationBlock source="Ethereum Yellow Paper · Shanghai version" citeKey={1} href="https://ethereum.github.io/yellowpaper/paper.pdf"><p><strong>문제:</strong> 모든 node가 transaction execution과 world-state transition을 같은 수학적 규칙으로 계산해야 합니다.</p><p><strong>기여:</strong> 256-bit stack machine, execution environment·machine state, opcode transition과 gas·exception semantics를 형식화합니다.</p><p><strong>전제:</strong> Yellow Paper가 명시한 Shanghai ruleset과 valid transaction·block context를 사용합니다.</p><p><strong>근거 범위:</strong> EVM core semantics와 해당 문서 revision의 protocol rules에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Shanghai 이후 fork의 최신 opcode·gas schedule이나 특정 client의 내부 architecture를 영구히 고정하지 않습니다.</p></CitationBlock></div>
  </section>
  <section id="gas-state" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · gas and journaled state</p><h2 className="mt-2 text-2xl font-bold">Gas를 먼저 확인하고, 상태 변경은 frame이 끝날 때까지 되돌릴 수 있게 기록한다</h2></header>
    <p>Gas는 단순한 결제 단위가 아니라 한 execution이 사용할 계산·memory·state resource의 상한입니다. 다음 opcode 비용보다 남은 gas가 적으면 그 opcode의 partial effect를 남기지 않고 exceptional halt합니다. Storage write나 log 역시 journal에 기록되어 바깥 frame까지 정상 반환될 때만 살아남습니다.</p><p>Memory는 word 주소가 아니라 byte-addressed이며 높은 offset을 처음 건드리면 확장 비용이 붙습니다. Storage는 persistent하지만 곧바로 disk commit을 뜻하지 않습니다. Client는 transaction/block execution 중 overlay와 journal을 사용한 뒤 valid block 경계에서 canonical state에 반영합니다.</p>
  </section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · halt, revert, release</p><h2 className="mt-2 text-2xl font-bold">성공·REVERT·예외 종료를 같은 실패 한 칸으로 합치지 않는다</h2></header><EvmFailureViz />
    <p><code>REVERT</code>는 현재 frame의 state changes를 취소하면서 return data를 caller에게 돌려주는 명시적 종료입니다. Out-of-gas, invalid opcode, stack underflow는 exceptional halt이며 해당 frame 변경을 취소합니다. Nested call 실패를 caller가 검사하고 계속할 수 있으므로 child 실패가 항상 transaction 전체 실패는 아닙니다.</p><p>Release fixture는 stack underflow, 2²⁵⁶ wraparound, memory expansion, storage write 뒤 REVERT, child out-of-gas와 duplicate replay를 넣습니다. Pinned execution-specs와 candidate client가 status·gas used·logs·post-state root를 모두 같게 내야 하며, 하나라도 다르면 새 runtime을 채택하지 않습니다.</p>
    <div id="paper-execution-specs"><CitationBlock source="Ethereum execution-specs · tests@v20.0.1 snapshot" citeKey={2} type="code" href="https://github.com/ethereum/execution-specs/tree/87aba1a38a476b31f819a2390eb481527e6dc683"><p><strong>문제:</strong> Fork별 execution rules를 사람이 읽는 문서와 실행 가능한 reference 사이에서 일관되게 유지해야 합니다.</p><p><strong>기여:</strong> Python으로 block·transaction·EVM transition을 구현하고 fork별 tests artifact를 제공합니다.</p><p><strong>전제:</strong> Tag tests@v20.0.1의 commit 87aba1a와 선택한 fork·test fixture를 고정합니다.</p><p><strong>근거 범위:</strong> 해당 snapshot의 executable semantics와 generated tests에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Reference Python 구현이 production client의 성능·storage·network architecture를 정한다는 뜻은 아닙니다.</p></CitationBlock></div>
    <p>다음 단계는 <a className="text-primary underline underline-offset-4" href="/blockchain/evm-advanced">nested call·CREATE2 심화</a>이며, state root 자료구조는 <a className="text-primary underline underline-offset-4" href="/blockchain/merkle-patricia-trie">Ethereum MPT</a>가 소유합니다.</p><h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 EVM 책임, stack·memory·storage, environment, 한 opcode step, gas와 세 종료 상태를 묻습니다. 심화 4문제는 wraparound, journal rollback, nested failure와 cross-client release fixture를 설계하게 합니다.</p>
  </section>
</article>}
