import type { Article } from "../types";

export const zkpVmArticles: Article[] = [
  {
    slug: "circom",
    title: "Circom: signal·R1CS lowering과 reproducible artifact",
    subcategory: "zkp-groth16-impl",
    sections: [
      { id: "overview", title: "3·4=12에서 compiler pipeline까지" },
      { id: "lowering", title: "Signal·witness·constraint lowering" },
      { id: "artifacts", title: "R1CS·witness·public layout artifact" },
      { id: "release", title: "snarkjs release·rollback gate" },
    ],
    component: () => import("@/pages/articles/blockchain/circom"),
  },
  {
    slug: "scroll-zkevm",
    title: "Scroll zkEVM: Halo2 기반 EVM 회로 (ExecutionGadget)",
    subcategory: "zkp-plonk-impl",
    sections: [
      { id: "overview", title: "개요 & 서브회로 구조" },
      { id: "gadget", title: "ExecutionGadget — 오퍼코드 회로 구현" },
      { id: "circuit-overview", title: "서브회로 전체 구조" },
      { id: "opcode-circuits", title: "Opcode 처리 회로" },
      { id: "table-system", title: "테이블 시스템" },
      { id: "witness-system", title: "Witness 시스템" },
      { id: "lookup-mechanisms", title: "Lookup 메커니즘" },
      { id: "proof-pipeline", title: "증명 생성 파이프라인" },
      { id: "halo2-integration", title: "Halo2 통합" },
      { id: "gadget-system", title: "Gadget 시스템" },
    ],
    component: () => import("@/pages/articles/blockchain/scroll-zkevm"),
  },
  {
    slug: "sp1",
    title: "SP1: Plonky3 기반 RISC-V zkVM",
    subcategory: "zkp-stark-impl",
    sections: [
      { id: "overview", title: "개요 & 아키텍처" },
      { id: "project-structure", title: "크레이트 구조 & 빌드" },
      { id: "execution", title: "Core Executor & 실행 모드" },
      { id: "executor-detail", title: "Executor 심층 분석" },
      { id: "memory-system", title: "메모리 관리 시스템" },
      { id: "syscall-system", title: "시스템 콜 처리" },
      { id: "air", title: "AIR 칩 시스템 & STARK" },
      { id: "chip-architecture", title: "칩 아키텍처" },
      { id: "alu-chips", title: "ALU 칩 상세" },
      { id: "stark-proving", title: "STARK 증명 생성" },
      { id: "shard-parallel", title: "샤드 분할 & 병렬 처리" },
      { id: "recursion-compression", title: "재귀적 압축" },
      { id: "snark-wrapping", title: "SNARK 래핑" },
      { id: "cuda-acceleration", title: "CUDA 가속" },
      { id: "sdk", title: "SDK & 재귀 압축" },
      { id: "cli-tools", title: "CLI & 개발 도구" },
      { id: "examples", title: "실전 예제" },
    ],
    component: () => import("@/pages/articles/blockchain/sp1"),
  },
  {
    slug: "risc0",
    title: "RISC Zero: RISC-V zkVM & STARK 증명 시스템",
    subcategory: "zkp-stark-impl",
    sections: [
      { id: "overview", title: "개요 & 핵심 개념" },
      { id: "execution", title: "실행 엔진 & 세그먼트" },
      { id: "proof-system", title: "증명 시스템 & 재귀 압축" },
      { id: "ethereum", title: "Ethereum 통합 & 온체인 검증" },
    ],
    component: () => import("@/pages/articles/blockchain/risc0"),
  },
  {
    slug: "jolt",
    title: "Jolt: instruction lookup·sumcheck lowering과 proof receipt",
    subcategory: "zkp-vm",
    sections: [
      { id: "overview", title: "ADD instruction에서 zkVM claim까지" },
      { id: "lookup-sumcheck", title: "Lookup·MLE·sumcheck lowering" },
      { id: "artifact", title: "Bytecode·trace·claim artifact" },
      { id: "release", title: "Interpreter parity·release gate" },
    ],
    component: () => import("@/pages/articles/blockchain/jolt"),
  },
];
