import type { Article } from "../types";

export const ethereum2Articles: Article[] = [
  /* ── Scaling & L2 ── */
  {
    slug: "rollup-fundamentals",
    title: "롤업 기초: Optimistic vs ZK Rollup",
    subcategory: "eth-scaling",
    sections: [
      { id: "glossary", title: "핵심 용어 & 배경 지식" },
      { id: "overview", title: "개요 & L1 vs L2" },
      { id: "optimistic", title: "Optimistic Rollup (사기 증명)" },
      { id: "zk-rollup", title: "ZK Rollup (유효성 증명)" },
      { id: "comparison", title: "Optimistic vs ZK 비교" },
    ],
    component: () => import("@/pages/articles/blockchain/rollup-fundamentals"),
  },
  {
    slug: "da-theory",
    title: "데이터 가용성 이론: DAS, DA Layer, EIP-4844",
    subcategory: "eth-scaling",
    sections: [
      { id: "glossary", title: "핵심 용어 & 배경 지식" },
      { id: "overview", title: "개요 & DA 문제" },
      { id: "das", title: "Data Availability Sampling" },
      { id: "da-layer", title: "Celestia, EigenDA, Avail" },
      { id: "eip-4844", title: "Blob 트랜잭션 & Proto-Danksharding" },
    ],
    component: () => import("@/pages/articles/blockchain/da-theory"),
  },

  /* ── Privacy (심층 코드 추적) ── */
  {
    slug: "railgun",
    title: "RAILGUN: note·nullifier·proof/contract artifact 경계",
    subcategory: "eth-privacy",
    sections: [
      { id: "overview", title: "10→6+4 private transfer 입구" },
      { id: "note-state", title: "Note·commitment·nullifier 상태 전이" },
      { id: "proof-artifact", title: "Proof·contract·relayer artifact" },
      { id: "release", title: "Privacy·soundness release gate" },
    ],
    component: () => import("@/pages/articles/blockchain/railgun"),
  },
  /* ── Helios (Light Client) ── */
  {
    slug: "helios",
    title: "Helios 아키텍처 개요",
    subcategory: "eth-helios",
    sections: [{ id: "overview", title: "아키텍처 개요" }],
    component: () => import("@/pages/articles/ethereum/helios"),
  },
  {
    slug: "helios-bootstrap",
    title: "Helios Checkpoint Sync & 부트스트랩",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "Trusted root에서 store까지" },
      { id: "checkpoint-sources", title: "체크포인트 source와 provenance" },
      { id: "weak-subjectivity", title: "Weak subjectivity와 freshness" },
      { id: "fetch-checkpoint", title: "요청·decode 경계" },
      { id: "bootstrap-response", title: "응답의 세 증거" },
      { id: "committee-branch", title: "Committee Merkle branch" },
      { id: "store-init", title: "Store 원자적 초기화" },
      { id: "first-update", title: "첫 update와 확정성" },
      { id: "error-cases", title: "실패 분류와 release gate" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-bootstrap"),
  },
  {
    slug: "helios-consensus",
    title: "Helios Sync Committee BLS 검증 & 교체",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "Update의 전체 검증 경로" },
      { id: "verify-trace", title: "Participation·domain·BLS·branch" },
      { id: "committee-lifecycle", title: "Committee period와 핸드오프" },
      { id: "sync-loop", title: "Sync loop와 release gate" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-consensus"),
  },
  {
    slug: "helios-update",
    title: "Helios Light Client Update",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "왜 Update가 필요한가" },
      { id: "update-types", title: "OptimisticUpdate vs FinalityUpdate" },
      {
        id: "validate-update",
        title: "validate_light_client_update() 3가지 검사",
      },
      {
        id: "slot-comparison",
        title: "헤더 슬롯 비교 (optimistic vs finalized)",
      },
      { id: "apply-update", title: "apply_store_update() 내부" },
      { id: "best-update", title: "Best Update 선택 (다수 Update 도착 시)" },
      { id: "reorg-handling", title: "경량 클라이언트의 Reorg 처리" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-update"),
  },
  {
    slug: "helios-state",
    title: "Helios State Proof & Merkle-Patricia 검증",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "왜 상태 증명인가 (로컬 상태 없이 검증)" },
      { id: "eip1186", title: "EIP-1186 eth_getProof 포맷" },
      { id: "account-proof", title: "Account Proof 검증 (keccak 경로)" },
      { id: "storage-proof", title: "Storage Proof 검증 (중첩 트라이)" },
      {
        id: "rlp-decode",
        title: "RLP 디코딩 (nonce · balance · storageRoot · codeHash)",
      },
      { id: "proof-caching", title: "증명 캐싱 전략" },
      { id: "error-cases", title: "에러 케이스 (누락 · 잘못된 증명)" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-state"),
  },
  {
    slug: "helios-execution",
    title: "Helios Execution RPC",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "왜 로컬 실행인가 (RPC 결과를 신뢰할 수 없음)" },
      { id: "proof-db", title: "ProofBeacon DB는 block·state·checkpoint를 서로 다른 조회 축으로 저장한다 (증명 기반 가상 DB)" },
      { id: "eth-call", title: "eth_call: revm 로컬 실행" },
      { id: "get-balance", title: "eth_getBalance 구현" },
      { id: "get-code", title: "eth_getCode 구현" },
      { id: "get-storage", title: "eth_getStorageAt 구현" },
      { id: "get-logs", title: "eth_getLogs: Bloom Filter 필터링" },
      { id: "send-tx", title: "eth_sendRawTransaction (유일한 신뢰 지점)" },
      { id: "gas-estimation", title: "가스 추정 (경량 클라이언트 기반)" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-execution"),
  },
  {
    slug: "helios-types",
    title: "Helios 타입 시스템",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "타입과 검증 책임의 경계" },
      { id: "core-types", title: "Header · Aggregate · Update · Store" },
      { id: "encoding", title: "SSZ · Fork · Domain" },
      { id: "ssz-internal", title: "Merkle root · generalized index" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-types"),
  },
  {
    slug: "helios-config",
    title: "Helios 설정 · 캐싱 · 네트워크",
    subcategory: "eth-helios",
    sections: [
      { id: "overview", title: "설정과 trust boundary" },
      { id: "network-config", title: "Network · fork · endpoint" },
      { id: "client-init", title: "Builder · startup · readiness" },
      { id: "persistence", title: "Checkpoint cache · fallback" },
    ],
    component: () => import("@/pages/articles/ethereum/helios-config"),
  },
  {
    slug: "kohaku-provider",
    title: "Kohaku Provider: 공통 API와 method별 신뢰 경계",
    subcategory: "eth-privacy",
    sections: [
      { id: "overview", title: "Provider adapter가 통일하는 것" },
      { id: "provider-capabilities", title: "공통 method와 의미 정규화" },
      { id: "trust-signing", title: "검증 경로·bypass·signer 분리" },
      { id: "release", title: "Parity·privacy·release gate" },
    ],
    component: () => import("@/pages/articles/blockchain/kohaku-provider"),
  },
  {
    slug: "pq-account",
    title: "Post-Quantum Account Abstraction",
    subcategory: "eth-privacy",
    sections: [
      { id: "overview", title: "UserOperation에서 receipt까지" },
      { id: "account-abstraction-validation", title: "AA validation과 execution 경계" },
      { id: "ml-dsa-signature-boundary", title: "ML-DSA signature artifact" },
      { id: "migration-release", title: "Hybrid migration release gate" },
    ],
    component: () => import("@/pages/articles/blockchain/pq-account"),
  },
];
