import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { IrohBoundaryViz, IrohPathViz } from "./viz/ModernIrohViz";

export default function ModernIrohArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Iroh v1.0.3 구현 읽기</p><h2 className="text-3xl font-bold tracking-tight">Iroh는 콘텐츠를 찾는 계층이 아니라, 찾은 endpoint까지 연결하는 계층이다</h2></header><p className="text-lg leading-8">Alice가 <code>payroll-report-v1</code>을 Bob에게서 받는다고 하겠습니다. 먼저 application이 bytes로부터 content ID를 알고 Bob이 provider라는 사실과 그의 <code>EndpointAddr</code>를 얻습니다. 그다음 Iroh가 endpoint identity를 인증하고 direct 또는 relay path 위에 QUIC connection을 만들며, ALPN으로 선택한 application protocol이 CID 요청과 block 검증을 처리합니다.</p><p>따라서 <a className="text-primary hover:underline" href="/p2p/content-addressing#overview">content addressing</a>과 <a className="text-primary hover:underline" href="/p2p/kademlia#overview">Kademlia routing</a>은 앞단 정본으로 재사용합니다. Iroh 연결 성공은 Bob의 endpoint key와 통신했다는 receipt이지, Bob이 그 CID를 보유하거나 파일 내용이 payroll report라는 증명은 아닙니다.</p><IrohBoundaryViz/><aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 경계:</strong> content ID → provider/routing → EndpointAddr까지는 application의 책임이고, Iroh는 EndpointAddr → authenticated QUIC → ALPN protocol dispatch를 소유합니다.</aside></section>

    <section id="endpoint-alpn" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · identity와 protocol</p><h2 className="mt-2 text-2xl font-bold">EndpointAddr는 신원과 후보 주소를 묶고, ALPN은 연결 뒤 handler를 고른다</h2></header><p><code>EndpointAddr</code>에는 endpoint identity와 direct IP·relay·custom transport 주소가 들어갑니다. 주소가 하나도 없다면 별도 discovery가 identity를 경로로 해석해야 합니다. <code>connect_with_opts</code>는 비어 있지 않은 ALPN을 요구하고, endpoint ID를 TLS server name에 넣어 상대 identity를 확인한 뒤 connection을 만듭니다.</p><p>ALPN(Application-Layer Protocol Negotiation)은 같은 endpoint에서 어떤 상위 protocol을 실행할지 합의하는 이름입니다. 예를 들어 <code>/payroll/cid-fetch/1</code>을 선택해도 authorization은 끝나지 않습니다. handler는 요청자, CID allowlist, 최대 응답 크기와 received block hash를 다시 검사해야 합니다.</p><div id="paper-iroh-endpoint-v103"><CitationBlock source="iroh v1.0.3 — endpoint.rs · endpoint_addr.rs" citeKey={1} type="code" href="https://github.com/n0-computer/iroh/tree/v1.0.3/iroh/src"><p><strong>문제:</strong> endpoint identity, candidate address와 application protocol을 한 connection 시도에 결합합니다.</p><p><strong>기여:</strong> EndpointAddr, connect_with_opts, TLS identity와 ALPN dispatch의 pinned 구현을 제공합니다.</p><p><strong>전제:</strong> iroh v1.0.3 API와 해당 QUIC/TLS transport 구성을 사용합니다.</p><p><strong>근거 범위:</strong> local address resolution, authenticated connection setup과 protocol handler 선택입니다.</p><p><strong>말하지 않는 것:</strong> CID provider 발견, payload authorization, durable file delivery를 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="path-selection" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · direct와 relay</p><h2 className="mt-2 text-2xl font-bold">경로는 RTT 최솟값 하나가 아니라 tier와 hysteresis로 고른다</h2></header><p>v1.0.3의 기본 selector는 direct IP와 custom transport를 primary로, relay를 backup으로 둡니다. 같은 tier에서는 IPv6에 3 ms bias를 주며 candidate가 현재 path보다 최소 5 ms 좋아야 교체합니다. 작은 RTT 흔들림마다 path가 바뀌는 flapping을 줄이려는 hysteresis입니다. 이 상수는 Iroh의 pinned 구현값이지 모든 네트워크의 최적값은 아닙니다.</p><IrohPathViz/><ExplainedFormula question="현재 path를 유지할지 candidate로 바꿀지 어떻게 판단할까?" idea={<>먼저 transport tier를 비교하고, 같은 tier에서만 측정 RTT에 address-family bias를 더합니다. candidate가 switch threshold만큼 더 좋아야 이동합니다.</>} formula={String.raw`K(x)=(T_x,\;r_x+b_x),\qquad \text{switch if }T_c<T_o\ \lor\ (T_c=T_o\land r_c+b_c+5\mathrm{ms}\le r_o+b_o)`}
    annotatedFormula={String.raw`K(x)=\underbrace{(T_x,\;r_x+b_x),\qquad \text{switch if }T_c<T_o\ \lor\ (T_c=T_o\land r_c+b_c+5\mathrm{ms}\le r_o+b_o)}_{\text{판정 조건 결합}}`}
    operations={[
      { expression: String.raw`(T_x,\;r_x+b_x),\qquad \text{switch if }T_c<T_o\ \lor\ (T_c=T_o\land r_c+b_c+5\mathrm{ms}\le r_o+b_o)`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","먼저 transport tier를 비교하고, 같은","tier에서만 측정 RTT에 address-family","bias를 더합니다."] },
    ]} terms={[{symbol:"T_x",name:"transport tier",description:"direct/custom primary와 relay backup의 우선순위입니다."},{symbol:"r_x",name:"measured RTT",description:"path x에서 관측한 round-trip time입니다."},{symbol:"b_x",name:"address-family bias",description:"v1.0.3 기본 selector가 IPv6에 주는 −3 ms 보정입니다."},{symbol:"5\\mathrm{ms}",name:"switch threshold",description:"같은 tier의 작은 측정 흔들림으로 path가 계속 바뀌지 않게 하는 문턱입니다."}]} assumptions={["Iroh v1.0.3 기본 BiasedRttPathSelector의 ordering과 상수를 설명합니다.","RTT sample이 충분히 새롭고 path가 usable state라고 가정합니다.","비용·privacy·relay quota는 이 식 밖의 운영 정책입니다.","다른 version이나 custom selector에는 같은 상수를 적용하지 않습니다."]} interpretation="IPv6 21 ms는 bias 후 18 ms이고 현재 IPv4 20 ms보다 2 ms만 유리하므로 유지합니다. IPv6가 14 ms이면 bias 후 11 ms로 9 ms 유리해 교체합니다. Relay 12 ms는 더 빨라도 primary가 살아 있는 동안 backup입니다."/><div id="paper-iroh-path-v103"><CitationBlock source="iroh v1.0.3 — biased_rtt_path_selector.rs" citeKey={2} type="code" href="https://github.com/n0-computer/iroh/blob/v1.0.3/iroh/src/socket/biased_rtt_path_selector.rs"><p><strong>문제:</strong> direct·custom·relay 후보 사이에서 안정적인 active path를 선택합니다.</p><p><strong>기여:</strong> transport tier, IPv6 bias와 same-tier switching threshold를 구현합니다.</p><p><strong>전제:</strong> v1.0.3 기본 selector와 usable RTT observation을 사용합니다.</p><p><strong>근거 범위:</strong> 한 remote endpoint에 대한 local path ordering과 전환 판단입니다.</p><p><strong>말하지 않는 것:</strong> 최저 end-to-end application latency나 모든 NAT 환경의 direct 연결을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · failure와 release</p><h2 className="mt-2 text-2xl font-bold">연결 retry와 파일 검증 retry를 분리한다</h2></header><p>Path는 Open·Abandoned·Failed·Unknown 같은 상태로 관리되고 실패한 hole-punch path는 후보에서 제거될 수 있습니다. Direct가 실패하면 relay로 계속 통신하며 새 후보를 탐색할 수 있지만, 무한 retry 대신 attempt count·last error·selected tier를 receipt로 남깁니다. Endpoint identity mismatch나 허용하지 않은 ALPN은 다른 path로 우회할 문제가 아니라 즉시 실패시켜야 합니다.</p><p>Release test는 direct 성공, relay fallback, path flapping, endpoint ID mismatch, unknown ALPN, stream reset을 각각 재현합니다. 받은 bytes는 CID로 다시 계산하고 크기 제한과 authorization을 통과한 뒤에만 저장합니다. 실패 중간 파일과 열린 stream은 닫고, 검증 실패 artifact는 publish하지 않습니다.</p><div id="paper-iroh-path-state-v103"><CitationBlock source="iroh v1.0.3 — path_state.rs · protocol.rs" citeKey={3} type="code" href="https://github.com/n0-computer/iroh/blob/v1.0.3/iroh/src/socket/remote_map/remote_state/path_state.rs"><p><strong>문제:</strong> 변하는 network path와 protocol handler lifecycle을 bounded state로 관리합니다.</p><p><strong>기여:</strong> path state·pruning과 ALPN handler routing의 실패 경계를 구현합니다.</p><p><strong>전제:</strong> v1.0.3 endpoint runtime이 관측과 connection lifecycle을 계속 poll합니다.</p><p><strong>근거 범위:</strong> node-local path 실패·교체와 handler dispatch cleanup입니다.</p><p><strong>말하지 않는 것:</strong> remote content의 존재, CID 의미, application transaction commit을 증명하지 않습니다.</p></CitationBlock></div><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 EndpointAddr, identity, ALPN, direct/relay tier, CID 경계와 connection receipt를 확인합니다. 심화 4문제는 biased RTT 계산, flapping 반례, identity mismatch의 fail-closed 처리와 relay fallback release test를 설계하게 합니다.</p></section>
  </article>;
}
