import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import LithographyViz from "./lithography-and-resolution/viz/LithographyViz";

/** Invented optics λ=193 nm, NA=.8, k1=.4/.3; separate overlay sketch: 200 nm line, 120 nm opening, offset 0/30/50 nm. */
export default function LithographyAndResolutionArticle() {
 return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">같은 자리에 두 번 찍어야 연결됩니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="text-lg leading-8">앞 글에서는 산화막 가운데 창을 내고 불순물을 들였습니다. 실제로 창의 무늬를 여러 위치에 옮기려면 빛에 반응하는 막을 바르고, 마스크 무늬를 비춘 뒤 드러난 부분을 가공합니다. 첫 번째 문제는 한 번에 얼마나 가는 무늬를 찍을 수 있느냐입니다.</p>
   <p className="leading-7">하지만 잘 찍은 두 층이 서로 어긋나면 연결이 끊어집니다. 가상으로 이전 층의 선 폭을 200 nm, 새 층의 접촉 창을 120 nm로 둡니다. 두 중심이 같으면 양쪽에 40 nm씩 남지만, 새 층이 50 nm 밀리면 한쪽 창은 선 밖으로 10 nm 나갑니다. 노광의 <strong>해상도</strong>와 층 사이의 <strong>정렬 오차</strong>를 같은 말로 부를 수 없는 이유입니다.</p>
   <p className="leading-7"><em>얼마나 작은 무늬인가와 어디에 놓였는가는 별도의 질문입니다.</em></p>
  </div></section>
  <section id="transfer" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">빛은 보호막이 아니라 감광막에 먼저 무늬를 남깁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">웨이퍼 위에 빛에 반응하는 <strong>감광막</strong>을 바르고, 무늬가 담긴 레티클을 통해 빛을 비춥니다. 광학계가 그 무늬를 줄여 감광막에 기록합니다. 이후 굽고 현상하면 선택한 부분이 씻겨 나가 창이 생깁니다. 그 창을 통해 아래 막을 식각하거나 필요한 물질을 바꾸고, 남은 감광막은 제거합니다. 앞 글의 ‘산화막 창’은 이 단계들을 거쳐 아래 산화막에 실제로 옮겨진 결과입니다.</p>
   <p className="leading-7">빛을 비춘 자리와 최종적으로 열린 자리가 언제나 같다고 단정하지 않습니다. 감광막의 종류와 현상·식각 조건이 바뀌면 어느 쪽이 남는지도 달라집니다. 따라서 이 글은 특정 양성·음성 감광막의 색을 고정하지 않고, 무늬가 감광막을 거쳐 아래 층으로 전달된다는 순서에 집중합니다.</p>
   <p className="leading-7"><em>레티클 무늬는 감광막에 기록된 뒤 가공을 거쳐 아래 층의 창이 됩니다.</em></p>
  </div><CitationBlock source="ASML, ‘How microchips are made’, Photoresist coating·Exposure·Baking & developing·Etching 절" citeKey={1} href="https://www.asml.com/en/technology/all-about-microchips/how-microchips-are-made">장비 제조사의 공식 설명은 감광막 도포, 레티클 투영 노광, 베이크·현상, 열린 자리의 식각을 순서대로 제시합니다. 이 글의 200·120 nm 선과 창은 해당 공정의 제품 치수가 아닙니다.</CitationBlock></section>
  <section id="resolution" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">193 nm 빛으로 계산한 가상 경계는 96.5 nm입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">ASML은 인쇄할 수 있는 가장 작은 무늬의 기준인 <strong>임계 치수 CD</strong>를 CD=k<sub>1</sub>λ/NA로 설명합니다. λ는 빛의 파장, NA는 빛을 모으는 광학계의 수치 개구, k<sub>1</sub>은 광학·감광막·공정 최적화를 묶는 계수입니다. 이 식 안에서는 파장이 작을수록, NA가 클수록 CD가 작아집니다. k<sub>1</sub>도 독립된 마법 숫자가 아니라 공정 조건의 결과입니다.</p>
   <p className="leading-7">설명용으로 λ=193 nm, NA=0.8, k<sub>1</sub>=0.4를 함께 <strong>가정</strong>하면 CD=0.4×193/0.8=96.5 nm입니다. 다른 조건을 모두 유지하고 k<sub>1</sub>만 0.3으로 바뀌었다고 가정하면 약 72.4 nm입니다. 이것은 실제 특정 ASML 장비의 보증 선폭이나 ‘공정 노드’가 아닙니다. 120 nm 접촉 창과 200 nm 선의 별도 정렬 예도 이 96.5 nm보다 크게 골랐습니다.</p>
   <p className="leading-7"><em>식은 가능한 무늬 크기를 따지는 출발점이고, 인쇄된 모든 모양의 보증서는 아닙니다.</em></p>
  </div><ExplainedFormula question="가상 λ=193 nm·NA=0.8·k₁=0.4에서 CD는?" idea="파장에 공정 계수를 곱한 뒤 광학계의 수치 개구로 나눕니다." formula={String.raw`\mathrm{CD}=k_1\frac{\lambda}{\mathrm{NA}}`} annotatedFormula={String.raw`\underbrace{\mathrm{CD}}_{\text{임계 치수}}=k_1\frac{\lambda}{\mathrm{NA}}`} operations={[{expression:String.raw`0.4\times193\,\mathrm{nm}=77.2\,\mathrm{nm}`,annotation:"가정한 파장과 계수입니다."},{expression:String.raw`77.2/0.8=96.5\,\mathrm{nm}`,annotation:"NA는 무차원입니다."},{expression:String.raw`0.3\times193/0.8\approx72.4\,\mathrm{nm}`,annotation:"k₁만 바꾼 별도 가정입니다."}]} terms={[{symbol:"CD",name:"임계 치수",description:"이 광학·공정식의 최소 무늬 기준입니다."},{symbol:String.raw`\lambda`,name:"빛의 파장",description:"가상 193 nm입니다."},{symbol:"NA",name:"수치 개구",description:"가상 0.8이며 빛 수집 범위를 나타냅니다."},{symbol:"k₁",name:"공정 계수",description:"가상 0.4 또는 0.3입니다."}]} assumptions={["λ·NA·k₁ 조합은 설명용 가정이며 특정 장비의 승인 조건이 아닙니다.","CD 식만으로 초점, 감광막, 식각 뒤 모양과 수율을 결정하지 않습니다."]} interpretation="가상 CD는 96.5 nm입니다. 층 정렬이 맞는지는 이 수치로 알 수 없습니다." /><CitationBlock source="ASML, ‘The Rayleigh criterion for resolution’, CD=k₁·λ/NA 절" citeKey={2} href="https://www.asml.com/en/technology/lithography-principles/rayleigh-criterion">ASML 공식 설명에서 CD·λ·NA·k₁의 뜻과 식을 확인했습니다. 193 nm·0.8·0.4 조합 및 96.5 nm 계산은 이 글의 가정이며 제품 사양 인용이 아닙니다.</CitationBlock></section>
  <section id="overlay" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">새 창이 옆으로 밀리면 좁은 쪽의 여유가 먼저 사라집니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">이전 층의 200 nm 선 가운데에 120 nm 연결 창을 얹는 가상 단면을 봅니다. 중심이 같으면 남는 폭은 (200−120)/2=40 nm씩입니다. 새 창 중심이 한쪽으로 30 nm 밀리면 가까운 쪽 여유는 40−30=10 nm, 먼 쪽은 70 nm입니다. 50 nm 밀리면 가까운 쪽은 −10 nm, 곧 창이 이전 선의 경계를 10 nm 넘습니다.</p>
   <p className="leading-7">이처럼 두 층의 위치 차이를 <strong>오버레이</strong>라고 부릅니다. CD=96.5 nm를 달성해도 위치가 어긋나면 이 연결은 부족할 수 있습니다. 반대로 위치가 정확해도 무늬 자체가 너무 넓거나 좁게 인쇄되면 별도의 문제입니다. 아래 그림의 폭은 설명용이며 실제 장비의 오버레이 성능이나 생산 수율을 뜻하지 않습니다.</p>
   <p className="leading-7"><em>가장 가까운 한쪽의 거리만 봐도 어떤 오차가 연결을 먼저 위협하는지 알 수 있습니다.</em></p>
  </div><LithographyViz /><ExplainedFormula question="새 창 중심이 30 nm 밀리면 가까운 쪽 여유는?" idea="가운데 정렬일 때의 절반 여유에서 중심 이동 거리를 뺍니다." formula={String.raw`M_{\min}=M_0-|\Delta x|`} annotatedFormula={String.raw`\underbrace{M_{\min}}_{\text{가까운 쪽 여유}}=M_0-|\Delta x|`} operations={[{expression:String.raw`(200-120)/2=40\,\mathrm{nm}`,annotation:"정렬이 정확할 때 한쪽 여유입니다."},{expression:String.raw`40-30=10\,\mathrm{nm}`,annotation:"30 nm 밀리면 가까운 쪽에 남습니다."},{expression:String.raw`40-50=-10\,\mathrm{nm}`,annotation:"50 nm면 창이 선 밖으로 10 nm 나갑니다."}]} terms={[{symbol:"M₀",name:"중앙 정렬 한쪽 여유",description:"(이전 선 폭−새 창 폭)/2이며 가상 40 nm입니다."},{symbol:"Wline",name:"이전 층 선 폭",description:"가상 200 nm입니다."},{symbol:"Wwindow",name:"새 층 창 폭",description:"가상 120 nm입니다."},{symbol:String.raw`\Delta x`,name:"중심 위치 차이",description:"두 층 사이 가상 이동 거리입니다."}]} assumptions={["두 무늬가 직사각형이며 폭 변동 없이 옆으로만 이동합니다.","거리는 기하학적 명목값이며 식각·전기 접촉 품질을 보증하지 않습니다."]} interpretation="30 nm 이동이면 최소 여유 10 nm, 50 nm면 −10 nm입니다. CD와는 다른 측정입니다." /><CitationBlock source="ASML, ‘Measuring accuracy’, YieldStar·Fast, accurate wafer metrology 절" citeKey={3} href="https://www.asml.com/en/technology/lithography-principles/measuring-accuracy">공식 자료는 오버레이를 두 칩 층의 정렬 정확도로 설명하고, 계측 표적에서 오버레이와 초점을 측정한다고 밝힙니다. 200·120·30·50 nm는 본문의 가상 정렬 기하입니다.</CitationBlock></section>
  <section id="limits" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">찍힌 감광막과 식각 뒤 실제 구조를 다시 재야 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
   <p className="leading-7">노광 장비는 위치와 초점을 맞추지만, 아래 층의 높낮이·감광막 화학·식각은 최종 구조를 바꿉니다. ASML은 오버레이와 초점을 계측 표적에서 살피고, 식각 뒤 구조도 따로 측정한다고 설명합니다. 따라서 이 글의 CD 계산과 10 nm 여유는 ‘검사 없이 양품’이라는 뜻이 아닙니다. 원하는 전기적 연결이 되는지의 확인은 이후 공정과 검사까지 이어집니다.</p>
   <p className="leading-7">다음 글은 창 안에 넣은 불순물이 열을 받는 동안 어디까지 퍼지는지 계산합니다. 창의 위치를 잘 잡아도 이후 가열에서 접합 깊이와 옆 범위가 달라질 수 있기 때문입니다.</p>
   <p className="leading-7"><strong>읽고 나서 예측해 보세요.</strong> λ·NA·k₁에서 CD가 무엇입니까? (답: 3절) 30 nm 오버레이 오차가 생기면 한쪽 여유는 얼마입니까? (답: 4절) CD=96.5 nm가 실제 접촉 성공을 보증합니까? (답: 4·5절)</p>
   <p className="leading-7"><Link to="/electronics/semiconductors/wafer-and-planar-process#mask">앞 글의 산화막 창</Link>은 이번 무늬 전달 순서가 아래 층까지 내려간 결과입니다.</p>
  </div></section>
 </div>;
}
