import type { CodeRef, FileNode, ProjectMeta } from "@/components/code/types";
import poseidon from "./codebase/poseidon.rs?raw";
import poseidon2 from "./codebase/poseidon2.rs?raw";
import profile from "./codebase/poseidon_instance_bn256.rs?raw";
import profile2 from "./codebase/poseidon2_instance_bn256.rs?raw";
import field from "./codebase/bn256.rs?raw";
import decode from "./codebase/field-utils.rs?raw";
import native from "./verification/main.rs?raw";
import trace from "./verification/trace.py?raw";
export const codeRefs:Record<string,CodeRef>={
"toy":{code:trace,"path": "case/trace.py", "highlight": [72, 102], "lang": "python", "desc": "289개 입력의 full·partial 순열과 역변환, 분기 수, 빠진 제약의 잘못된 결과를 직접 검사합니다.", "annotations": [{"lines": [72, 102], "color": "sky", "note": "289개 입력의 full·partial 순열과 역변환, 분기 수, 빠진 제약의 잘못된 결과를 직접 검사합니다."}]},
"field":{code:field,"path": "rust/bn256.rs", "highlight": [1, 15], "lang": "rust", "desc": "타입 이름과 함께 실제 modulus를 확인합니다. 이 소수는 BN254의 스칼라체에 해당합니다.", "annotations": [{"lines": [1, 15], "color": "sky", "note": "타입 이름과 함께 실제 modulus를 확인합니다. 이 소수는 BN254의 스칼라체에 해당합니다."}]},
"profile":{code:profile,"path": "rust/poseidon_instance_bn256.rs", "highlight": [286, 289], "lang": "rust", "desc": "3·5·8·56과 MDS3·RC3를 함께 고정합니다. 원논문 표의 partial 57 설정과 구별합니다.", "annotations": [{"lines": [286, 289], "color": "sky", "note": "3·5·8·56과 MDS3·RC3를 함께 고정합니다. 원논문 표의 partial 57 설정과 구별합니다."}]},
"profile2":{code:profile2,"path": "rust/poseidon2_instance_bn256.rs", "highlight": [291, 292], "lang": "rust", "desc": "Poseidon2의 별도 상수와 행렬을 확인합니다. 지수와 횟수가 같아도 원래 Poseidon과 출력이 다릅니다.", "annotations": [{"lines": [291, 292], "color": "sky", "note": "Poseidon2의 별도 상수와 행렬을 확인합니다. 지수와 횟수가 같아도 원래 Poseidon과 출력이 다릅니다."}]},
"plain":{code:poseidon,"path": "rust/poseidon.rs", "highlight": [53, 75], "lang": "rust", "desc": "입력 세 칸을 복사하고 앞 네 full·가운데 56 partial·끝 네 full round를 실행합니다.", "annotations": [{"lines": [53, 75], "color": "sky", "note": "입력 세 칸을 복사하고 앞 네 full·가운데 56 partial·끝 네 full round를 실행합니다."}]},
"power":{code:poseidon,"path": "rust/poseidon.rs", "highlight": [82, 97], "lang": "rust", "desc": "지수 5 분기에서 제곱, 다시 제곱, 원래 값 곱셈으로 작은 예의 u·v·y를 계산합니다.", "annotations": [{"lines": [82, 97], "color": "sky", "note": "지수 5 분기에서 제곱, 다시 제곱, 원래 값 곱셈으로 작은 예의 u·v·y를 계산합니다."}]},
"native":{code:native,"path": "case/main.rs", "highlight": [23, 32], "lang": "rust", "desc": "수정하지 않은 원문 모듈을 연결한 별도 호출 예제입니다. 다섯 입력과 실제 compress 호출을 검사했습니다.", "annotations": [{"lines": [23, 32], "color": "sky", "note": "수정하지 않은 원문 모듈을 연결한 별도 호출 예제입니다. 다섯 입력과 실제 compress 호출을 검사했습니다."}]},
"optimized":{code:poseidon,"path": "rust/poseidon.rs", "highlight": [22, 50], "lang": "rust", "desc": "변환한 상수와 행렬을 함께 쓰며 cheap_matmul의 순서를 역으로 읽습니다. 111–130행에서 실제 혼합을 볼 수 있습니다.", "annotations": [{"lines": [22, 50], "color": "sky", "note": "변환한 상수와 행렬을 함께 쓰며 cheap_matmul의 순서를 역으로 읽습니다. 111–130행에서 실제 혼합을 볼 수 있습니다."}]},
"poseidon2":{code:poseidon2,"path": "rust/poseidon2.rs", "highlight": [22, 49], "lang": "rust", "desc": "첫 상수보다 먼저 외부 혼합을 수행하고 partial에서는 첫 칸에만 상수를 더합니다.", "annotations": [{"lines": [22, 49], "color": "sky", "note": "첫 상수보다 먼저 외부 혼합을 수행하고 partial에서는 첫 칸에만 상수를 더합니다."}]},
"mix2":{code:poseidon2,"path": "rust/poseidon2.rs", "highlight": [129, 137], "lang": "rust", "desc": "세 칸 외부 혼합은 각 칸에 전체 합을 더합니다. 178–188행의 내부 혼합은 마지막 칸을 두 배 한 뒤 합을 더합니다.", "annotations": [{"lines": [129, 137], "color": "sky", "note": "세 칸 외부 혼합은 각 칸에 전체 합을 더합니다. 178–188행의 내부 혼합은 마지막 칸을 두 배 한 뒤 합을 더합니다."}]},
"compress":{code:poseidon,"path": "rust/poseidon.rs", "highlight": [160, 164], "lang": "rust", "desc": "두 원소 뒤에 0을 붙여 순열에 넣고 첫 칸을 반환합니다. 임의 길이 문자열의 패딩 함수가 아닙니다.", "annotations": [{"lines": [160, 164], "color": "sky", "note": "두 원소 뒤에 0을 붙여 순열에 넣고 첫 칸을 반환합니다. 임의 길이 문자열의 패딩 함수가 아닙니다."}]},
"decode":{code:decode,"path": "rust/field-utils.rs", "highlight": [9, 12], "lang": "rust", "desc": "고정 상수의 16진수를 읽어 mod p로 바꿉니다. 범위 밖 외부 입력을 거부하는 정규 파서가 아닙니다.", "annotations": [{"lines": [9, 12], "color": "sky", "note": "고정 상수의 16진수를 읽어 mod p로 바꿉니다. 범위 밖 외부 입력을 거부하는 정규 파서가 아닙니다."}]},
"checks":{code:trace,"path": "case/trace.py", "highlight": [36, 70], "lang": "python", "desc": "별도 Python 모형의 두 순열과 실제 네이티브 결과, 원문 [0,1,2]의 알려진 출력을 대조합니다.", "annotations": [{"lines": [36, 70], "color": "sky", "note": "별도 Python 모형의 두 순열과 실제 네이티브 결과, 원문 [0,1,2]의 알려진 출력을 대조합니다."}]},
};
export const fileTrees:Record<string,FileNode>={"rust": {"name": "고정 원문", "type": "dir", "children": [{"name": "poseidon.rs", "type": "file", "path": "rust/poseidon.rs", "codeKey": "plain"}, {"name": "poseidon2.rs", "type": "file", "path": "rust/poseidon2.rs", "codeKey": "poseidon2"}, {"name": "poseidon_instance_bn256.rs", "type": "file", "path": "rust/poseidon_instance_bn256.rs", "codeKey": "profile"}, {"name": "poseidon2_instance_bn256.rs", "type": "file", "path": "rust/poseidon2_instance_bn256.rs", "codeKey": "profile2"}, {"name": "bn256.rs", "type": "file", "path": "rust/bn256.rs", "codeKey": "field"}, {"name": "field-utils.rs", "type": "file", "path": "rust/field-utils.rs", "codeKey": "decode"}]}, "case": {"name": "직접 실행한 검사", "type": "dir", "children": [{"name": "main.rs", "type": "file", "path": "case/main.rs", "codeKey": "native"}, {"name": "trace.py", "type": "file", "path": "case/trace.py", "codeKey": "toy"}]}};
export const projectMetas:Record<string,ProjectMeta>={"rust": {"id": "rust", "label": "HorizenLabs 055bde3 원문", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}, "case": {"id": "case", "label": "본문의 검산 코드", "badgeClass": "bg-emerald-50 border-emerald-300 text-emerald-800"}};
