import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { ChannelBackpressureViz, P2PStackViz } from "./viz/ModernP2PViz";

export default function ModernCometBFTP2PArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">CometBFT v0.40.0 구현 읽기</p><h2 className="text-3xl font-bold tracking-tight">P2P는 message를 옮기고, protocol reactor가 그 의미를 판단한다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">사용자가 <code>alice→bob 10</code> transaction을 한 node에 보냈다고 하겠습니다. 이 bytes가 다른 peer의 socket에 도착했다는 사실은 아직 유효한 transaction이라는 뜻도, block에 들어갔다는 뜻도 아닙니다. P2P stack은 연결을 만들고 channel별 message를 운반하며, mempool reactor가 bytes를 풀어 CheckTx 경계로 넘긴 뒤에야 admission 판단이 시작됩니다.</p>
      <p>CometBFT의 legacy P2P stack은 transport, MConnection, Switch, Reactor를 겹쳐 놓습니다. Transport는 peer 연결과 handshake를, MConnection은 한 연결 위의 여러 logical channel을, Switch는 peer와 channel owner의 lifecycle을, Reactor는 consensus·mempool 같은 protocol별 message 처리를 맡습니다. 이 글은 현재 저장소가 기준으로 삼은 <code>v0.40.0</code> tag의 구현에 한정합니다. 일반적인 process·message·failure model은 <a className="text-primary hover:underline" href="/blockchain/distributed-systems#overview">분산 시스템 정본</a>, 합의의 safety·liveness는 <a className="text-primary hover:underline" href="/blockchain/smr-theory#overview">SMR 정본</a>으로 이어집니다.</p>
      <P2PStackViz />
      <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>먼저 기억할 경계:</strong> peer ID는 연결 상대를 가리키고 channel ID는 message owner를 가리킵니다. 둘 다 application validity나 consensus commit certificate를 대신하지 않습니다.</aside>
    </section>

    <section id="mconnection" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · MConnection</p><h2 className="mt-2 text-2xl font-bold">한 TCP connection 안에서도 channel마다 queue와 priority가 따로 있다</h2></header>
      <p><code>ChannelDescriptor</code>는 byte ID, 양수 priority, send queue capacity와 receive message capacity를 선언합니다. <code>Send</code>는 해당 channel queue에 넣을 자리가 날 때까지 기다리는 blocking API이고, <code>TrySend</code>는 자리가 없으면 즉시 false를 돌려주는 non-blocking API입니다. 따라서 “호출 성공”은 remote peer가 처리했다는 ack가 아니라 local send queue가 message를 받아들였다는 뜻입니다.</p>
      <p>전송 loop는 각 channel의 <code>recentlySent / priority</code>가 가장 작은 대상을 골라 packet을 보냅니다. 큰 message는 설정된 packet payload ceiling에 맞춰 여러 packet으로 나뉘고, 수신측은 channel별 buffer에 다시 조립합니다. priority 10인 consensus channel과 priority 5인 mempool channel이 모두 계속 밀려오면 전자는 대략 더 자주 선택되지만, OS socket·rate limiter·remote CPU까지 포함한 latency SLA는 아닙니다.</p>
      <ChannelBackpressureViz />
      <ExplainedFormula question="여러 channel이 동시에 밀려올 때 MConnection은 다음 전송 대상을 어떻게 고르는가?" idea={<>각 channel이 최근에 보낸 byte 양을 priority로 나눈 정규화 비용을 비교합니다. 높은 priority는 같은 byte를 보냈을 때 비용을 더 작게 만들어 다음 선택 기회를 앞당깁니다.</>} formula={String.raw`i^*=\arg\min_i\frac{R_i}{p_i},\qquad R_i\leftarrow R_i+b_i`} terms={[{symbol:"i^*",name:"선택 channel",description:"이번 packet을 보낼 channel index입니다."},{symbol:"R_i",name:"recently sent",description:"channel i가 최근에 전송한 양을 누적·감쇠해 관리하는 scheduler 상태입니다."},{symbol:"p_i",name:"priority",description:"ChannelDescriptor의 양수 weight입니다. 절대 대역폭 예약량은 아닙니다."},{symbol:"b_i",name:"packet bytes",description:"이번 선택으로 실제 기록되는 전송량입니다."}]} assumptions={["서로 다른 channel이 같은 MConnection의 sender loop를 공유합니다.","priority는 양수이며 queue가 비어 있는 channel은 선택 후보가 아닙니다.","socket·rate limiter·remote 처리 지연은 이 식 밖에서 별도로 측정합니다.","v0.40.0 connection.go의 scheduler 동작을 설명하는 식이며 다른 transport 구현에 자동 적용하지 않습니다."]} interpretation="priority를 두 배로 올리면 혼잡한 sender 안에서 상대적 선택 몫이 커질 수 있지만, 느린 peer의 connection 전체가 빨라지지는 않습니다. Queue full·TrySend false·send rate와 disconnect를 함께 계측해야 합니다." />
      <div id="paper-cometbft-p2p-connection-v040"><CitationBlock source="CometBFT v0.40.0 — p2p/conn/connection.go" citeKey={1} type="code" href="https://github.com/cometbft/cometbft/blob/v0.40.0/p2p/conn/connection.go"><p><strong>문제:</strong> 한 peer connection에서 여러 protocol message를 bounded queue와 packet으로 운반합니다.</p><p><strong>기여:</strong> ChannelDescriptor, Send·TrySend, weighted scheduler, packet 분할·재조립의 실제 구현을 제공합니다.</p><p><strong>전제:</strong> v0.40.0 legacy P2P MConnection과 해당 configuration을 사용합니다.</p><p><strong>근거 범위:</strong> local queue admission, channel scheduling과 connection-level I/O 동작입니다.</p><p><strong>말하지 않는 것:</strong> remote application 처리, consensus commit, end-to-end delivery SLA를 보장하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="switch" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · Switch</p><h2 className="mt-2 text-2xl font-bold">Switch는 peer 집합과 channel ownership을 한곳에서 관리한다</h2></header>
      <p>Reactor가 등록될 때 Switch는 <code>GetChannels()</code>를 읽어 channel ID를 reactor에 매핑합니다. v0.40.0 구현은 두 reactor가 같은 channel을 소유하려 하면 panic하므로, byte 하나가 어느 protocol parser로 가는지 모호하게 두지 않습니다. 새 peer가 추가되면 peer set에 넣고 각 reactor의 <code>InitPeer</code>·<code>AddPeer</code>를 호출하며, 제거할 때는 반대로 <code>RemovePeer</code>를 알립니다.</p>
      <p>오류로 peer를 끊을 때 persistent peer이거나 transient error로 분류되면 reconnect를 시도할 수 있습니다. 그렇다고 연결 복구가 protocol liveness를 자동 복구하는 것은 아닙니다. 필요한 voting power와 block parts가 제시간에 도착해야 consensus가 진행되며, 잘못된 message·느린 peer·중복 연결을 어떤 이유로 끊었는지 운영 receipt를 남겨야 network 장애와 consensus 장애를 구분할 수 있습니다.</p>
      <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-border p-4"><p className="font-semibold">peer lifecycle receipt</p><p className="mt-2 text-sm text-muted-foreground">peer ID · inbound/outbound · persistent 여부 · connect/disconnect reason · retry count</p></div><div className="rounded-lg border border-border p-4"><p className="font-semibold">channel health receipt</p><p className="mt-2 text-sm text-muted-foreground">queue fill · TrySend failure · packet bytes · decode error · reactor handling latency</p></div></div>
    </section>

    <section id="reactor" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · Reactor와 release gate</p><h2 className="mt-2 text-2xl font-bold">Envelope dispatch 뒤에는 protocol별 검증과 backpressure 정책이 남는다</h2></header>
      <p>Reactor interface는 channel descriptors를 선언하고 peer가 추가·제거될 때 lifecycle callback을 받으며, <code>Receive(Envelope)</code>에서 channel message를 처리합니다. 예시 transaction은 mempool reactor에 도착한 뒤에야 decode, sender 추적과 CheckTx로 넘어갑니다. Consensus reactor라면 같은 P2P framework를 쓰더라도 vote의 chain·height·round·signature를 검증합니다. 공통 운반층이 payload 의미까지 공유하는 것은 아닙니다.</p>
      <p>Release test는 정상 peer 하나, queue를 읽지 않는 slow peer, oversized·malformed packet을 보내는 peer를 동시에 둡니다. channel별 queue가 bounded인지, TrySend false가 caller까지 전달되는지, malformed frame이 다른 peer의 reactor를 멈추지 않는지, disconnect 뒤 persistent peer retry가 폭주하지 않는지 확인합니다. 그 뒤에야 consensus channel에서 fault bound와 partial synchrony 아래 commit이 계속되는지를 별도 liveness gate로 둡니다.</p>
      <div id="paper-cometbft-p2p-switch-v040"><CitationBlock source="CometBFT v0.40.0 — p2p/switch.go · base_reactor.go" citeKey={2} type="code" href="https://github.com/cometbft/cometbft/blob/v0.40.0/p2p/switch.go"><p><strong>문제:</strong> peer lifecycle과 channel별 protocol handler를 일관되게 결합합니다.</p><p><strong>기여:</strong> unique channel ownership, reactor 등록, peer add/remove, error disconnect와 persistent reconnect 경로를 구현합니다.</p><p><strong>전제:</strong> v0.40.0 Switch와 Reactor interface, legacy transport stack을 기준으로 합니다.</p><p><strong>근거 범위:</strong> node-local peer set과 message dispatch owner의 구현입니다.</p><p><strong>말하지 않는 것:</strong> 악성 peer 분류의 완전성, Internet reachability, BFT safety·liveness를 단독으로 증명하지 않습니다.</p></CitationBlock></div>
      <h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>기초 6문제는 네 계층, Send와 TrySend, channel descriptor, weighted scheduler, peer lifecycle, Reactor dispatch를 확인합니다. 심화 4문제는 slow-peer backpressure, duplicate channel owner, malformed packet 격리와 consensus liveness를 포함한 release gate를 설계하게 합니다.</p>
    </section>
  </article>;
}
