import { motion } from "framer-motion";
import type { ReactNode } from "react";
import { AnimatedSceneControls, useAnimatedScenes } from "@/components/viz/AnimatedSceneControls";
import VizFrame from "@/components/viz/VizFrame";

const accent = "var(--primary)";
const border = "var(--border)";
const muted = "var(--muted-foreground)";

function Arrow({ x1, y1, x2, y2, id, active }: { x1: number; y1: number; x2: number; y2: number; id: string; active: boolean }) {
  return <g><defs><marker id={id} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill={active ? accent : muted} /></marker></defs><motion.line x1={x1} y1={y1} x2={x2} y2={y2} stroke={active ? accent : muted} strokeWidth="1.25" markerEnd={`url(#${id})`} initial={false} animate={{ opacity: active ? 1 : .28, pathLength: active ? 1 : .72 }} /></g>;
}

function Box({ x, y, w, h, label, detail, active, dashed = false }: { x: number; y: number; w: number; h: number; label: string; detail?: string; active: boolean; dashed?: boolean }) {
  return <motion.g initial={false} animate={{ opacity: active ? 1 : .46, scale: active ? 1.025 : 1 }} style={{ transformOrigin: `${x+w/2}px ${y+h/2}px` }}><rect x={x} y={y} width={w} height={h} rx="7" fill={active ? "color-mix(in srgb, var(--primary) 10%, transparent)" : "var(--background)"} stroke={active ? accent : border} strokeWidth="1.25" strokeDasharray={dashed ? "5 4" : undefined}/><text x={x+w/2} y={y+h/2-(detail?4:-3)} textAnchor="middle" className="fill-foreground text-[9px] font-bold sm:text-[10px]">{label}</text>{detail ? <text x={x+w/2} y={y+h/2+12} textAnchor="middle" className="fill-muted-foreground text-[7px] sm:text-[8px]">{detail}</text> : null}</motion.g>;
}

function Scene({ id, eyebrow, title, description, labels, notes, children }: { id: string; eyebrow: string; title: string; description: string; labels: readonly string[]; notes: readonly string[]; children: (active: number) => ReactNode }) {
  const controls = useAnimatedScenes(labels.length, 3300);
  return <VizFrame title={title} description={description} className="my-8"><div id={id} data-viz tabIndex={0} onKeyDown={controls.onKeyDown} className="min-w-0 overflow-hidden border-y border-border/70 bg-background px-4 py-6 outline-none focus-visible:ring-2 focus-visible:ring-primary sm:px-6"><p className="text-[11px] font-black uppercase tracking-[.16em] text-primary">{eyebrow} · {String(controls.active+1).padStart(2,"0")}</p><h3 className="mt-2 text-lg font-bold leading-7">{labels[controls.active]}</h3><div data-viz-canvas className="mt-5 min-w-0 overflow-hidden">{children(controls.active)}</div><p className="mt-4 border-l border-primary/50 pl-4 text-sm leading-6 text-muted-foreground">{notes[controls.active]}</p><AnimatedSceneControls labels={[...labels]} {...controls}/></div></VizFrame>;
}

export function Word2VecPairViz() {
  const labels = ["Word ID가 row를 선택", "Input·output table 분리", "Window로 이웃을 관찰", "Pair receipt를 고정"] as const;
  const notes = ["Word ID는 의미 자체가 아니라 embedding matrix에서 trainable row 하나를 찾는 주소입니다.", "Center 역할의 input row와 context 역할의 output row는 같은 word라도 다른 update를 받습니다.", "Center 주변의 실제 radius 안에서 center–context pair를 만들며 sentence boundary는 넘지 않습니다.", "Tokenizer·corpus·window draw·subsampling·seed를 묶어야 같은 training pairs를 재현할 수 있습니다."] as const;
  return <Scene id="word2vec-pair-viz" eyebrow="Corpus to pairs" title="Word ID가 학습 pair가 되는 경로" description="주소→두 table→window→receipt를 도형으로 따라갑니다." labels={labels} notes={notes}>{active => <svg viewBox="0 0 360 220" role="img" aria-label={labels[active]} className="block h-auto w-full"><g>{[0,1,2,3,4].map(i=><motion.rect key={i} x={8} y={28+i*32} width="52" height="24" rx="4" fill={i===2&&active===0?"color-mix(in srgb, var(--primary) 12%, transparent)":"var(--background)"} stroke={i===2&&active===0?accent:border} strokeWidth="1.25"/>)}</g><text x="34" y="204" textAnchor="middle" className="fill-muted-foreground text-[9px]">vocab rows</text><Arrow x1={61} y1={110} x2={85} y2={110} id="w2v-pair-a" active={active>=1}/><Box x={89} y={45} w={67} h={48} label="W input" detail="center" active={active===1}/><Box x={89} y={128} w={67} h={48} label="W′ output" detail="context" active={active===1}/><Arrow x1={157} y1={110} x2={175} y2={110} id="w2v-pair-b" active={active>=2}/><g>{[0,1,2,3,4].map(i=><motion.rect key={i} x={180+i*24} y="87" width="18" height="42" rx="4" fill={i===2?"color-mix(in srgb, var(--primary) 12%, transparent)":"var(--background)"} stroke={active===2?accent:border} strokeWidth="1.25"/>)}</g><path d="M186 143 Q234 181 282 143" fill="none" stroke={active===2?accent:border} strokeWidth="1.25"/><Arrow x1={296} y1={110} x2={308} y2={110} id="w2v-pair-c" active={active===3}/><Box x={311} y={72} w={41} h={76} label="pair" detail="receipt" active={active===3}/></svg>}</Scene>;
}

export function PredictionObjectiveViz() {
  const labels = ["같은 window, 반대 방향", "CBOW는 주변을 모음", "Skip-gram은 pair로 펼침", "Tree path로 vocabulary 선택"] as const;
  const notes = ["CBOW와 Skip-gram은 같은 local observation을 쓰지만 조건과 target의 방향이 반대입니다.", "CBOW는 여러 context row를 평균해 center word 하나의 distribution을 예측합니다.", "Skip-gram은 center row 하나에서 context word마다 별도 example을 만듭니다.", "Hierarchical softmax는 vocabulary 전체 score 대신 root에서 target leaf까지 binary decisions를 곱합니다."] as const;
  return <Scene id="word2vec-objective-viz" eyebrow="Prediction direction" title="한 window에서 세 objective 모양 보기" description="주변→center, center→주변, root→leaf path를 한 장면씩 봅니다." labels={labels} notes={notes}>{active => <svg viewBox="0 0 360 220" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={12} y={84} w={54} h={48} label="left" detail="context" active={active<=1}/><Box x={92} y={84} w={54} h={48} label="center" detail="target/input" active={active<=2}/><Box x={172} y={84} w={54} h={48} label="right" detail="context" active={active<=1}/>{active===1?<g><Arrow x1={67} y1={108} x2={91} y2={108} id="obj-cbow-a" active/><Arrow x1={171} y1={108} x2={147} y2={108} id="obj-cbow-b" active/></g>:null}{active===2?<g><Arrow x1={92} y1={101} x2={67} y2={101} id="obj-sg-a" active/><Arrow x1={147} y1={115} x2={171} y2={115} id="obj-sg-b" active/></g>:null}<Arrow x1={227} y1={108} x2={249} y2={108} id="obj-tree" active={active===3}/><g>{[[267,108],[302,72],[302,144],[338,48],[338,93],[338,132],[338,177]].map(([x,y],i)=><motion.circle key={i} cx={x} cy={y} r={i===0?11:8} fill="var(--background)" stroke={active===3&&[0,2,6].includes(i)?accent:border} strokeWidth="1.25"/>)}<path d="M278 104L294 76M278 112L294 140M310 68L330 50M310 75L330 91M310 140L330 134M310 147L330 174" fill="none" stroke={active===3?accent:border} strokeWidth="1.25"/></g></svg>}</Scene>;
}

export function NegativeSamplingViz() {
  const labels = ["관측 pair는 positive", "Noise context k개", "Sigmoid pair loss", "선택한 row만 update"] as const;
  const notes = ["Corpus window에서 실제 나온 center–context pair에 label 1을 줍니다.", "Noise distribution은 비교할 context k개를 뽑아 label 0인 pairs를 만듭니다.", "Positive dot score는 올리고 negative dot scores는 내리는 binary logistic objective를 계산합니다.", "한 step은 center·positive·sampled negative rows만 읽고 바꾸므로 vocabulary 전체를 정규화하지 않습니다."] as const;
  return <Scene id="word2vec-negative-viz" eyebrow="Observed versus noise" title="SGNS 한 step에서 실제로 읽는 row" description="Positive pair와 sampled negatives가 sparse update가 되는 흐름입니다." labels={labels} notes={notes}>{active => <svg viewBox="0 0 360 220" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={10} y={80} w={58} h={54} label="center" detail="input row" active={active!==1}/><Arrow x1={69} y1={107} x2={96} y2={107} id="neg-a" active={active>=0}/><Box x={101} y={40} w={68} h={44} label="positive" detail="label 1" active={active===0}/>{[0,1,2].map(i=><Box key={i} x={101} y={99+i*38} w={68} h={30} label={`noise ${i+1}`} detail="label 0" active={active===1}/>) }<Arrow x1={170} y1={107} x2={198} y2={107} id="neg-b" active={active>=2}/><Box x={203} y={70} w={64} h={74} label="σ(dot)" detail="binary loss" active={active===2}/><Arrow x1={268} y1={107} x2={294} y2={107} id="neg-c" active={active===3}/><g>{[0,1,2].map(i=><motion.rect key={i} x={300} y={49+i*51} width="48" height="34" rx="5" fill={active===3?"color-mix(in srgb, var(--primary) 10%, transparent)":"var(--background)"} stroke={active===3?accent:border} strokeWidth="1.25"/>)}</g></svg>}</Scene>;
}

export function SubwordArtifactViz() {
  const labels = ["Word row만 쓰는 경계", "Character n-gram으로 분해", "여러 subword row를 합성", "Static artifact로 release"] as const;
  const notes = ["일반 Word2Vec lookup은 vocabulary 밖 word에 대응할 trainable row가 없습니다.", "fastText는 boundary가 포함된 character n-grams를 만들고 hash bucket IDs로 바꿉니다.", "해당 n-gram rows를 더해 OOV도 vector를 만들지만 문장별 sense를 구분하지는 않습니다.", "Matrix·vocabulary·hash·normalization·corpus·recipe·evaluation을 같은 artifact revision으로 배포합니다."] as const;
  return <Scene id="subword-artifact-viz" eyebrow="Characters to static vector" title="처음 보는 word를 subword rows로 조립하기" description="OOV 경계에서 n-gram 합성과 release manifest까지 연결합니다." labels={labels} notes={notes}>{active => <svg viewBox="0 0 360 220" role="img" aria-label={labels[active]} className="block h-auto w-full"><Box x={8} y={82} w={62} h={52} label="running" detail="word" active={active===0}/><Arrow x1={71} y1={108} x2={91} y2={108} id="subword-a" active={active>=1}/><g>{["<ru","run","unn","ing","ng>"].map((v,i)=><Box key={v} x={96+(i%3)*46} y={48+Math.floor(i/3)*62} w={39} h={34} label={v} active={active===1}/>)}</g><Arrow x1={233} y1={108} x2={251} y2={108} id="subword-b" active={active>=2}/><motion.circle cx="271" cy="108" r="19" fill="color-mix(in srgb, var(--primary) 10%, transparent)" stroke={active===2?accent:border} strokeWidth="1.25" animate={{scale:active===2?1.12:1}}/><text x="271" y="112" textAnchor="middle" className="fill-foreground text-[10px] font-bold">Σg</text><Arrow x1={291} y1={108} x2={307} y2={108} id="subword-c" active={active===3}/><Box x={310} y={70} w={42} h={76} label="release" detail="manifest" active={active===3}/></svg>}</Scene>;
}
