import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { CallContextMatrixViz, CreateLifecycleViz } from "./viz/ModernEvmAdvancedViz";

export default function ModernEvmAdvancedArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">EVM advanced · nested frames</p><h2 className="text-3xl font-bold tracking-tight">EVM 심화의 핵심은 opcode 이름 암기가 아니라, 새 frame이 누구의 code·storage·sender·value를 쓰는지 추적하는 일이다</h2></header><p className="text-lg leading-8 text-foreground/90">Alice가 proxy contract를 호출하고 proxy가 implementation code를 실행한다고 해보겠습니다. 바깥 transaction 하나 안에서도 call frame은 여러 개 생깁니다. 각 frame은 gas, stack, memory, return data와 journal checkpoint를 따로 가지며, opcode가 context authority를 정합니다.</p><p><code>CALL</code>은 다른 account의 context로 들어가지만 <code>DELEGATECALL</code>은 다른 code를 현재 account의 storage와 sender/value로 실행합니다. <code>STATICCALL</code>은 child graph 전체에 write 금지 flag를 전달합니다. 이 차이를 모르면 proxy storage corruption이나 read-only 우회를 놓칩니다.</p></section>
  <section id="memory-create" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · memory expansion and CREATE2</p><h2 className="mt-2 text-2xl font-bold">높은 memory offset은 quadratic 비용을 만들고, CREATE2 주소는 init code에 commit한다</h2></header><CreateLifecycleViz />
    <p><code>CREATE</code>와 <code>CREATE2</code>는 전달한 bytes를 곧바로 runtime code로 저장하지 않습니다. 먼저 새 child frame에서 <strong>init code</strong>를 실행하고, 정상 반환된 bytes가 runtime code가 됩니다. Init frame이 REVERT/OOG이면 account creation과 그 안의 state changes가 취소됩니다.</p>
    <ExplainedFormula question="CREATE2 주소는 왜 아직 실행하지 않은 init code에도 묶이는가?" idea={<>Deployer와 salt만 같아도 서로 다른 contract가 같은 주소를 예약하면 안 됩니다. 그래서 init code bytes의 hash를 주소 preimage에 포함합니다.</>} formula={String.raw`\begin{aligned}h_i&=keccak256(i)\\u&=keccak256(0xff\parallel d\parallel s\parallel h_i)\\a&=last_{20}(u)\end{aligned}`} terms={[{symbol:"d",name:"deployer",description:"CREATE2 opcode를 실행한 account의 20-byte address입니다."},{symbol:"s",name:"salt",description:"Caller가 정한 32-byte 값입니다."},{symbol:"i",name:"init code",description:"새 frame에서 실행되어 runtime code를 반환할 bytes입니다."},{symbol:"a",name:"created address",description:"Digest의 마지막 20 bytes입니다."}]} assumptions={["각 항목은 EIP-1014의 고정 길이와 순서로 이어 붙입니다.","Formula는 runtime code가 아니라 init-code hash에 commit합니다.","주소에 이미 nonce나 code가 있으면 collision rule에 따라 creation이 실패합니다.","Hash collision 저항성은 cryptographic assumption이며 execution success를 보장하지 않습니다."]} interpretation="같은 deployer와 salt라도 init code의 한 byte가 바뀌면 다른 주소가 됩니다. 반대로 같은 preimage는 같은 candidate address라 기존 account 충돌을 검사해야 합니다." />
    <div id="paper-eip1014"><CitationBlock source="EIP-1014 · Skinny CREATE2" citeKey={1} href="https://eips.ethereum.org/EIPS/eip-1014"><p><strong>문제:</strong> 아직 chain에 없는 contract와도 미리 정한 주소를 기준으로 상호작용할 수 있어야 합니다.</p><p><strong>기여:</strong> 0xff·deployer·salt·init-code hash로 CREATE2 address를 계산하는 opcode semantics를 정의합니다.</p><p><strong>전제:</strong> EIP-1014가 활성화된 ruleset과 exact init-code bytes·deployer·salt를 사용합니다.</p><p><strong>근거 범위:</strong> CREATE2 address derivation, gas surcharge와 collision behavior에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Counterfactual address의 contract가 반드시 배포되거나 같은 runtime behavior를 영구 유지한다는 뜻은 아닙니다.</p></CitationBlock></div>
  </section>
  <section id="call-context" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · context authority matrix</p><h2 className="mt-2 text-2xl font-bold">Code를 빌려 쓰는 것과 상대 account의 상태를 바꾸는 것은 다르다</h2></header><CallContextMatrixViz /><p>Proxy가 implementation에 <code>DELEGATECALL</code>하면 implementation bytecode의 <code>SSTORE</code>는 proxy storage를 바꿉니다. 따라서 storage layout과 implementation codehash가 upgrade receipt에 포함되어야 합니다. <code>STATICCALL</code>에서는 직접 <code>SSTORE</code>뿐 아니라 하위 call graph의 state-changing operation도 실패합니다.</p><p>Memory는 frame-local이라 child가 caller memory를 직접 수정하지 못합니다. Caller가 정한 output range로 return bytes를 복사할 뿐입니다. Gas도 child에 전달된 budget과 call overhead를 분리해 추적해야 합니다.</p></section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · nested revert and release</p><h2 className="mt-2 text-2xl font-bold">Child가 실패해도 parent가 그 실패를 처리하면 transaction은 계속될 수 있다</h2></header><p>Nested call은 success bit와 return data를 parent stack에 돌려줍니다. Child journal은 실패 시 checkpoint까지 되돌리지만 parent가 이미 한 변경까지 자동으로 지우지는 않습니다. Parent가 success bit를 무시하고 계속하면 전체 transaction status가 1일 수도 있으므로 receipt 하나만 보고 모든 내부 call 성공을 추정하면 안 됩니다.</p><p>Release fixture는 CREATE2 collision, init-code REVERT, 높은 memory offset, DELEGATECALL storage owner 착오, STATICCALL 아래 write, child failure를 무시하는 parent와 return-data truncation을 포함합니다. Candidate는 pinned execution-spec tests와 post-state·gas·logs·return bytes parity를 통과해야 하며 mismatch 시 이전 runtime으로 되돌립니다.</p>
    <div id="paper-yellow-paper-advanced"><CitationBlock source="Ethereum Yellow Paper · message-call and contract-creation semantics" citeKey={2} href="https://ethereum.github.io/yellowpaper/paper.pdf"><p><strong>문제:</strong> Nested message call과 contract creation이 state·gas·context를 어떻게 전달하고 실패 시 어디까지 되돌리는지 정해야 합니다.</p><p><strong>기여:</strong> Message-call 함수, creation 함수, substate와 exceptional-halt rollback을 형식적으로 정의합니다.</p><p><strong>전제:</strong> 문서의 Shanghai ruleset과 valid outer execution environment를 사용합니다.</p><p><strong>근거 범위:</strong> 해당 revision의 CALL family·CREATE family·memory와 halt semantics에 한정합니다.</p><p><strong>말하지 않는 것:</strong> 특정 proxy standard의 보안성이나 이후 fork에서 바뀐 opcode rules를 자동 보장하지 않습니다.</p></CitationBlock></div>
    <p>Stack·memory·storage와 기본 halt가 낯설면 먼저 <a className="text-primary underline underline-offset-4" href="/blockchain/evm-fundamentals">EVM 기초</a>로 돌아가면 됩니다.</p><h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 frame, memory 확장, init/runtime code, CREATE2 입력과 세 call context를 묻습니다. 심화 4문제는 collision, proxy storage, static transitivity와 nested rollback fixture를 설계하게 합니다.</p>
  </section>
</article>}
