import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { SupervisedPositiveViz } from "../contrastive-learning/viz/ModernContrastiveViz";

export default function SupervisedContrastiveArticle(){return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Supervised contrastive learning은 label을 여러 positive 관계로 펼칩니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">SimCLR은 같은 원본의 다른 view 하나를 positive로 둡니다. Supervised contrastive learning은 batch 안에서 anchor와 같은 label을 가진 다른 sample을 모두 positive 집합 P(i)에 넣습니다.</p></div><TermBreakdown title="Label에서 positive set까지" items={[{term:"Anchor i",description:"현재 loss를 계산할 기준 sample입니다."},{term:"Positive set P(i)",description:"Anchor 자신을 제외하고 positive relation을 만족하는 batch index 집합입니다."},{term:"Valid anchor",description:"P(i)가 비어 있지 않아 loss를 계산할 수 있는 anchor입니다."},{term:"Class-aware sampler",description:"각 class의 positive가 batch에 나타나도록 구성하는 sampler입니다.",boundary:"균형 batch가 실제 배포 class prior와 같다는 뜻은 아닙니다."}]}/><SupervisedPositiveViz/><ContentBoundary article="supervised-contrastive-learning"/></section>
  <section id="positive-set" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Same label은 relation 후보이지 의미 동일성의 자동 증명은 아닙니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Batch [A1,A2,A3,B1,C1]에서 anchor A1의 P(i)는 {`{A2,A3}`}입니다. C1은 같은 label의 다른 sample이 없어 P(i)가 빈 집합입니다. 구현은 C1을 valid-anchor 평균에서 제외하거나 sampler가 positive를 보장해야 합니다.</p><p>Coarse label·hierarchical label·multi-label에서는 같은 상위 class 안에도 중요한 subgroup 차이가 있습니다. Relation rule과 annotation confidence를 기록하고 subgroup retrieval과 calibration을 별도로 봅니다.</p></div></section>
  <section id="objective" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Anchor loss는 positive별 log-probability를 평균합니다</h2><ExplainedFormula question="Positive가 A2와 A3 두 개라면 anchor A1의 loss는 어떻게 하나가 되나요?" idea={<p>Anchor 자신을 제외한 후보 점수 합은 공통 분모로 두고, 각 positive가 선택될 log-probability를 계산합니다. 그 값을 positive 개수로 나눠 anchor 하나의 loss로 평균합니다.</p>} formula={String.raw`\begin{aligned}Z_i&=\sum_{a\ne i}\exp(s_{ia})\\\mathcal L_i^{sup}&=-\frac1{|P(i)|}\sum_{p\in P(i)}\log\frac{\exp(s_{ip})}{Z_i}\end{aligned}`} annotatedFormula={String.raw`\begin{aligned}P(i)&=\underbrace{\{p\ne i:y_p=y_i\}}_{\text{anchor를 빼고 같은 label positive를 수집}}\\Z_i&=\underbrace{\sum_{a\ne i}\exp(s_{ia})}_{\text{자기 자신을 뺀 모든 후보 score를 합산}}\\\mathcal L_i^{sup}&=\underbrace{-\frac1{|P(i)|}\sum_{p\in P(i)}\log\frac{\exp(s_{ip})}{Z_i}}_{\substack{\text{각 positive 선택 loss를 더하고}\\\text{positive 개수로 평균}}}\end{aligned}`} operations={[{expression:String.raw`\{p\ne i:y_p=y_i\}`,annotation:["anchor 자신은 제외하고","relation rule을 만족하는 positive index 수집"]},{expression:String.raw`\sum_{a\ne i}\exp(s_{ia})`,annotation:["모든 비교 후보 score를 양수로 바꿔","공통 normalization 분모 생성"]},{expression:String.raw`\sum_{p\in P(i)}-\log(\exp(s_{ip})/Z_i)`,annotation:["positive마다 선택 실패량을 계산해","multi-positive 신호를 모두 합산"]},{expression:String.raw`1/|P(i)|`,annotation:["합친 loss를 positive 수로 나눠","class별 positive 개수 차이를 보정"]}]} terms={[{symbol:String.raw`P(i)`,name:"Positive index set",description:"Anchor i와 positive relation인 다른 sample index입니다."},{symbol:String.raw`|P(i)|`,name:"Positive count",description:"Anchor loss에 기여하는 positive 수입니다."},{symbol:String.raw`s_{ia}`,name:"Similarity logit",description:"Temperature가 적용된 anchor-candidate score입니다."}]} assumptions={["P(i)가 비지 않도록 sampler 또는 exclusion rule을 둡니다.","Same-label relation이 task 의미에 맞는지 hierarchy·noise slice에서 검증합니다.","유효 anchor 수와 class composition을 metric과 함께 기록합니다."]} interpretation="A1에는 A2와 A3 두 항이 평균됩니다. C1처럼 P(i)가 비면 1/0이므로 조용히 NaN이 나거나 sample이 사라지지 않게 valid-anchor count를 노출합니다."/></section>
  <section id="release" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Class compactness가 실제 task 성능으로 이어지는지 따로 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Frozen linear probe, full fine-tuning, retrieval 가운데 deployment task와 가까운 지표를 주지표로 고정합니다. Same-label subgroup의 worst slice와 원래 class prior에서 calibration을 확인한 뒤 sampler·positive rule·encoder artifact를 함께 release합니다.</p></div><div id="paper-supcon" className="not-prose mt-8 scroll-mt-24"><CitationBlock type="paper" citeKey={1} source="Khosla et al. — Supervised Contrastive Learning" href="https://papers.nips.cc/paper_files/paper/2020/hash/d89a66c7c80a29b1bdbab0f2a1a94af8-Abstract.html">같은 class의 여러 sample을 positive로 쓰는 objective를 제시하고 classification baseline과 비교합니다. Coarse·hierarchical·noisy label에서 모든 same-label pair가 의미상 같다는 보장은 아닙니다.</CitationBlock></div></section>
</div>}
