import { CORE_ROOT, articlePath, coreItemPath } from '@/lib/paths';
import type { Article } from './types';
import { aiArticles } from './ai/articles';
import softwareVerification from './software-verification';
import codebaseAnalysis from './codebase-analysis';

export type CoreItemKind = 'project' | 'deep-dive' | 'decision' | 'lab';
export type CoreItemStatus = 'active' | 'done' | 'draft';

export interface CoreItem {
  slug?: string;
  title: string;
  kind: CoreItemKind;
  status: CoreItemStatus;
  summary: string;
  stack: string[];
  href?: string;
  article?: Article;
  evidence?: string[];
  units?: string[];
  notes?: { title: string; body: string }[];
  concepts?: CoreConcept[];
}

export interface CoreConcept {
  term: string;
  summary: string;
  intent: string;
  details: string[];
  references?: { label: string; href: string }[];
}

export interface CoreTrack {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  focus: string[];
  items: CoreItem[];
}

const fmBoundaryPracticeArticle = softwareVerification.articles.find((article) => article.slug === 'fm-boundary-practice');
const gethBlobTxFmArticle = codebaseAnalysis.articles.find((article) => article.slug === 'geth-blob-tx-fm');
const blogBackedCoreSlugs = new Set([
  'llm-serving-ops',
  'open-r1',
  'llm-architecture-gallery',
  'llm-architecture-dense-transformers',
  'llm-architecture-sparse-moe',
  'llm-architecture-kv-long-context',
  'llm-architecture-hybrid-linear',
]);

function requireAiArticle(slug: string): Article {
  const article = aiArticles.find((item) => item.slug === slug);
  if (!article) {
    throw new Error(`Missing AI article for core item: ${slug}`);
  }
  return article;
}
const gethTestUnitsArticle: Article = {
  slug: 'geth-test-units',
  title: 'go-ethereum 기능별 코드 해설과 검증 단위',
  subcategory: 'verification-practice',
  summary: 'go-ethereum의 거대한 테스트 집합을 기능군과 함수 경계별로 탐색하고, 상세 불변조건·반례·실행 명령으로 내려가는 검증 레지스트리입니다.',
  level: '심화',
  estimatedMinutes: 28,
  prerequisites: ['FM 경계 절단 방식', 'Go package와 test command', 'go-ethereum의 큰 모듈 구분'],
  sections: [
    { id: 'overview', title: '코드베이스 단위 검증' },
    { id: 'procedures', title: '기능별 검증 주제' },
    { id: 'coverage', title: '필수 기능 커버리지' },
    { id: 'recent-prs', title: '최근 PR에서 나온 단위' },
    { id: 'core-chain', title: 'Core chain/state' },
    { id: 'engine-p2p', title: 'Engine, P2P, RPC' },
    { id: 'ledger', title: '다음 코드베이스로 확장' },
  ],
  component: () => import('@/pages/core/geth-test-units'),
};
const vllmTestUnitsArticle: Article = {
  slug: 'vllm-test-units',
  title: 'vLLM 기능별 코드 해설과 검증 단위',
  subcategory: 'ai-systems',
  summary: 'vLLM의 request lifecycle, scheduler, KV cache, serving과 speculative decoding을 함수별 검증 문서로 찾아가는 운영 레지스트리입니다.',
  level: '심화',
  estimatedMinutes: 24,
  prerequisites: ['Transformer 추론의 prefill과 decode', 'KV cache와 token budget', 'Python test와 request lifecycle'],
  sections: [
    { id: 'overview', title: '코드베이스 단위 검증' },
    { id: 'coverage', title: '필수 기능 범위' },
    { id: 'runtime', title: 'Runtime, scheduler, KV cache' },
    { id: 'serving', title: 'Serving API와 multimodal input' },
    { id: 'commands', title: '확인 명령' },
    { id: 'ledger', title: '확장 상태' },
  ],
  component: () => import('@/pages/core/vllm-test-units'),
};
function vllmFunctionCutArticle(slug: string, title: string): Article {
  return {
    slug,
    title,
    subcategory: 'ai-systems',
    sections: [
      { id: 'overview', title: '함수 경계' },
      { id: 'sources', title: '코드 소스와 한글 주석' },
      { id: 'procedure', title: '검증 절차' },
      { id: 'invariants', title: '불변조건' },
      { id: 'tests', title: '테스트 매트릭스' },
      { id: 'next', title: '다음 함수 후보' },
    ],
    component: () => import('@/pages/core/vllm-function-cut'),
  };
}

function codebaseRegistryArticle(slug: string, title: string): Article {
  return {
    slug,
    title,
    subcategory: 'codebase-registry',
    sections: [
      { id: 'overview', title: '코드베이스 단위 검증' },
      { id: 'units', title: '검증 단위' },
      { id: 'commands', title: '확인 명령' },
      { id: 'next', title: '확장 상태' },
    ],
    component: () => import('@/pages/core/codebase-registry'),
  };
}

function codeIdiomArticle(slug: string, title: string): Article {
  return {
    slug,
    title,
    subcategory: 'code-idioms',
    sections: [
      { id: 'overview', title: 'Idiom 기준' },
      { id: 'bad-good', title: 'Bad / Good 예시' },
      { id: 'review', title: '리뷰 질문' },
    ],
    component: () => import('@/pages/core/code-idiom-detail'),
  };
}

const vllmFunctionCutArticles = {
  engineStep: vllmFunctionCutArticle('vllm-fn-engine-step', 'EngineCore.step()이 한 추론 step을 닫는 부분'),
  workerExecuteModel: vllmFunctionCutArticle('vllm-fn-worker-execute-model', 'GPUWorker.execute_model()이 forward 실행을 위임하는 부분'),
  samplerForward: vllmFunctionCutArticle('vllm-fn-sampler-forward', 'Sampler.forward()가 logits를 token id로 바꾸는 부분'),
  schedulerSchedule: vllmFunctionCutArticle('vllm-fn-scheduler-schedule', 'Scheduler.schedule()이 prefill과 decode를 한 budget으로 묶는 부분'),
  schedulerPreempt: vllmFunctionCutArticle('vllm-fn-scheduler-preempt', 'Scheduler._preempt_request()가 메모리 부족 요청을 되돌리는 부분'),
  blockPoolCache: vllmFunctionCutArticle('vllm-fn-block-pool-cache', 'BlockPool.get_cached_block()이 prefix cache hit을 찾는 부분'),
  blockPoolFree: vllmFunctionCutArticle('vllm-fn-block-pool-free', 'BlockPool.free_blocks()가 KV block을 free queue로 돌리는 부분'),
  kvAllocateSlots: vllmFunctionCutArticle('vllm-fn-kv-allocate-slots', 'KVCacheManager.allocate_slots()가 새 토큰용 KV block을 배정하는 부분'),
  apiEngineClient: vllmFunctionCutArticle('vllm-fn-api-engine-client', 'build_async_engine_client()가 OpenAI 서버용 engine client를 여는 부분'),
  apiAppState: vllmFunctionCutArticle('vllm-fn-api-app-state', 'init_app_state()가 OpenAI route state를 묶는 부분'),
  apiRenderState: vllmFunctionCutArticle('vllm-fn-api-render-state', 'init_render_app_state()가 multimodal renderer 상태를 여는 부분'),
  rejectionSampler: vllmFunctionCutArticle('vllm-fn-rejection-sampler', 'RejectionSampler.forward()가 draft token을 검증하는 부분'),
  eagleProposer: vllmFunctionCutArticle('vllm-fn-eagle-proposer', 'SpecDecodeBaseProposer가 speculative draft 제안을 준비하는 부분'),
};
function gethFmCutArticle(slug: string, title: string): Article {
  return {
    slug,
    title,
    subcategory: 'verification-practice',
    sections: [
      { id: 'overview', title: '절단 경계' },
      { id: 'sources', title: '코드 소스와 한글 주석' },
      { id: 'procedure', title: '검증 절차' },
      { id: 'invariants', title: '불변조건' },
      { id: 'tests', title: '테스트 매트릭스' },
      { id: 'next', title: '다음 절단' },
    ],
    component: () => import('@/pages/core/geth-fm-cut'),
  };
}

const gethFmCutArticles = {
  headerRlp: gethFmCutArticle('geth-fm-002-header-rlp', '블록 헤더를 RLP 바이트에서 구조체로 읽는 부분'),
  getBlobs: gethFmCutArticle('geth-fm-003-getblobs-availability', '엔진 API가 Blob 데이터 보유 여부를 알려주는 부분'),
  graphqlRaw: gethFmCutArticle('geth-fm-004-graphql-raw-body', 'GraphQL이 본문이 없는 블록을 안전하게 보여주는 부분'),
  txArgs: gethFmCutArticle('geth-fm-005-transaction-args', 'RPC 트랜잭션 입력값이 타입에 맞는지 걸러내는 부분'),
  enginePayload: gethFmCutArticle('geth-fm-006-engine-payload-witness', '엔진 payload와 witness를 만들고 검증하는 부분'),
  chainReorg: gethFmCutArticle('geth-fm-007-chain-reorg', '체인 import와 재구성이 canonical 상태를 바꾸는 부분'),
  stateRecovery: gethFmCutArticle('geth-fm-008-state-recovery', '스냅샷과 원시 DB가 재시작 뒤 복구되는 부분'),
  blobpool: gethFmCutArticle('geth-fm-009-blobpool-limbo', 'Blob 트랜잭션 풀이 대기 데이터와 누락 데이터를 다루는 부분'),
  p2pSync: gethFmCutArticle('geth-fm-010-p2p-sync', 'P2P 피어 발견과 동기화가 나쁜 응답을 걸러내는 부분'),
  rpcNode: gethFmCutArticle('geth-fm-011-rpc-node-cli', 'RPC 서버와 노드 실행 명령 입력을 안전하게 받는 부분'),
  abiSigner: gethFmCutArticle('geth-fm-012-abi-signer', 'ABI 인코딩과 계정 서명이 사용자 입력을 처리하는 부분'),
  evmState: gethFmCutArticle('geth-fm-013-evm-state-transition', 'EVM 명령 실행과 상태 전이가 fork 규칙을 따르는 부분'),
  coreSetHead: gethFmCutArticle('geth-fm-014-core-sethead-matrix', '체인 head를 되감을 때 상태와 스냅샷을 정리하는 부분'),
  ethapiRpc: gethFmCutArticle('geth-fm-015-ethapi-rpc-semantics', 'Ethereum RPC 메서드가 실행 결과를 일관되게 반환하는 부분'),
  beaconLight: gethFmCutArticle('geth-fm-016-beacon-light-client', 'Beacon light client가 checkpoint와 head를 따라가는 부분'),
  txFetcher: gethFmCutArticle('geth-fm-017-tx-fetcher-state-machine', '트랜잭션 fetcher가 요청과 시간 초과 상태를 정리하는 부분'),
  snapMatrix: gethFmCutArticle('geth-fm-018-snap-sync-peer-matrix', 'Snap sync가 손상된 peer 응답을 격리하는 부분'),
  trieProof: gethFmCutArticle('geth-fm-019-trie-proof-sync', 'Trie proof와 iterator가 state root를 보존하는 부분'),
  pathdbHistory: gethFmCutArticle('geth-fm-020-pathdb-history', 'PathDB history와 prune이 읽기 가능한 상태를 지키는 부분'),
  encodingCommon: gethFmCutArticle('geth-fm-021-encoding-common', '공통 인코딩 라이브러리가 입력 모서리 값을 처리하는 부분'),
  cryptoFuzzers: gethFmCutArticle('geth-fm-022-crypto-fuzzers', '암호 primitive와 fuzz seed가 crash 없이 처리되는 부분'),
  specFixtures: gethFmCutArticle('geth-fm-023-spec-fixture-replay', 'Execution spec fixture를 재생해 consensus 결과를 확인하는 부분'),
  t8nFixtures: gethFmCutArticle('geth-fm-024-t8n-fixtures', 'EVM t8n fixture 출력이 fork별 JSON 형태를 지키는 부분'),
  abigenBindings: gethFmCutArticle('geth-fm-025-abigen-bindings', 'ABI binding 생성기가 Solidity ABI를 Go 코드로 바꾸는 부분'),
  metricsTracing: gethFmCutArticle('geth-fm-026-metrics-tracing', 'Metrics와 tracing이 기존 동작을 바꾸지 않고 관찰값을 남기는 부분'),
};
export const coreTracks: CoreTrack[] = [
  {
    slug: 'ai-systems',
    title: 'AI Model Code Units',
    eyebrow: 'llm runtime · serving · evals',
    summary: 'LLM 모델 서빙, 라우팅, KV cache, scheduler, eval처럼 실제 모델 코드에서 최소 검증 단위로 관리할 항목입니다.',
    focus: [
      'LLM runtime internals: scheduler, KV cache, batching, tokenizer, decoding',
      'Model gateway units: routing, fallback, rate limit, provider contract',
      'Eval and reliability units that can be tested without treating an agent product as the core object',
    ],
    items: [
      {
        slug: 'vllm-test-units',
        title: 'vLLM 기능별 코드 해설과 검증 단위',
        kind: 'project',
        status: 'active',
        summary: 'vLLM runtime, scheduler, KV cache, speculative decoding, OpenAI API, VLM input을 함수별 검증 단위로 관리합니다.',
        stack: ['Python', 'vLLM', 'LLM Serving'],
        href: coreItemPath('ai-systems', 'vllm-test-units'),
        article: vllmTestUnitsArticle,
        evidence: ['engine/core.py', 'scheduler.py', 'kv_cache_manager.py', 'api_server.py', 'multimodal input path'],
        units: [
          'Runtime loop: request state가 waiting/running/finished 경계에서 보존되는지 확인한다.',
          'KV cache: block allocation, prefix caching, eviction이 memory budget을 넘지 않는지 확인한다.',
          'Scheduler: prefill/decode budget, preemption, chunked prefill이 batch contract를 지키는지 확인한다.',
          'Serving API: OpenAI-compatible schema, streaming, error response가 route별로 일관적인지 확인한다.',
          'VLM input: image/video input이 renderer, IO processor, encoder budget, cache 경계를 통과하는지 확인한다.',
        ],
        notes: [
          {
            title: '분리 기준',
            body: 'context-manager 같은 에이전트 제품은 프로젝트 운영 보드에서 다루고, 코어 AI에는 모델/서빙 코드의 재사용 가능한 최소 단위만 둔다.',
          },
        ],
      },
      {
        slug: 'vllm-fn-engine-step',
        title: 'EngineCore.step()이 한 추론 step을 닫는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'vLLM runtime loop에서 schedule, execute, sample, update 순서와 request output 계약을 함수 단위로 자른다.',
        stack: ['Python', 'vLLM', 'Runtime'],
        href: coreItemPath('ai-systems', 'vllm-fn-engine-step'),
        article: vllmFunctionCutArticles.engineStep,
        evidence: ['vllm/v1/engine/core.py:378', 'EngineCore.step()'],
        units: ['schedule → execute_model → sample_tokens → update_from_output 순서', 'empty request guard', 'output ownership'],
      },
      {
        slug: 'vllm-fn-worker-execute-model',
        title: 'GPUWorker.execute_model()이 forward 실행을 위임하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'scheduler output이 GPU worker와 model runner 사이에서 forward 실행으로 넘어가는 경계를 함수 단위로 자른다.',
        stack: ['Python', 'vLLM', 'Worker'],
        href: coreItemPath('ai-systems', 'vllm-fn-worker-execute-model'),
        article: vllmFunctionCutArticles.workerExecuteModel,
        evidence: ['vllm/v1/worker/gpu_worker.py:759', 'GPUWorker.execute_model()'],
        units: ['scheduled token guard', 'pipeline parallel tensor receive', 'model_runner handoff'],
      },
      {
        slug: 'vllm-fn-sampler-forward',
        title: 'Sampler.forward()가 logits를 token id로 바꾸는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'logits, grammar mask, sampling params가 token id 출력으로 바뀌는 최소 sampling 경계를 함수 단위로 자른다.',
        stack: ['Python', 'vLLM', 'Sampling'],
        href: coreItemPath('ai-systems', 'vllm-fn-sampler-forward'),
        article: vllmFunctionCutArticles.samplerForward,
        evidence: ['vllm/v1/sample/sampler.py:67', 'Sampler.forward()'],
        units: ['logits shape contract', 'mask respect', 'deterministic greedy sampling'],
      },
      {
        slug: 'vllm-fn-scheduler-schedule',
        title: 'Scheduler.schedule()이 prefill과 decode를 한 budget으로 묶는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'RUNNING/WAITING request를 token budget과 KV block budget 안에 배치하는 스케줄러 핵심 함수를 자른다.',
        stack: ['Python', 'vLLM', 'Scheduler'],
        href: coreItemPath('ai-systems', 'vllm-fn-scheduler-schedule'),
        article: vllmFunctionCutArticles.schedulerSchedule,
        evidence: ['vllm/v1/core/sched/scheduler.py:341', 'Scheduler.schedule()'],
        units: ['token budget bound', 'running request order', 'KV allocation gate'],
      },
      {
        slug: 'vllm-fn-scheduler-preempt',
        title: 'Scheduler._preempt_request()가 메모리 부족 요청을 되돌리는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'KV block 부족 시 RUNNING request를 waiting queue로 되돌리고 cache를 정리하는 preemption 함수를 자른다.',
        stack: ['Python', 'vLLM', 'Scheduler'],
        href: coreItemPath('ai-systems', 'vllm-fn-scheduler-preempt'),
        article: vllmFunctionCutArticles.schedulerPreempt,
        evidence: ['vllm/v1/core/sched/scheduler.py:949', 'Scheduler._preempt_request()'],
        units: ['state reset', 'queue priority', 'resource release'],
      },
      {
        slug: 'vllm-fn-block-pool-cache',
        title: 'BlockPool.get_cached_block()이 prefix cache hit을 찾는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'block hash로 cached KV block을 찾고 prefix cache hit/miss를 나누는 함수를 자른다.',
        stack: ['Python', 'vLLM', 'KV Cache'],
        href: coreItemPath('ai-systems', 'vllm-fn-block-pool-cache'),
        article: vllmFunctionCutArticles.blockPoolCache,
        evidence: ['vllm/v1/core/block_pool.py:183', 'BlockPool.get_cached_block()'],
        units: ['same-prefix only', 'ref count safety', 'miss clarity'],
      },
      {
        slug: 'vllm-fn-block-pool-free',
        title: 'BlockPool.free_blocks()가 KV block을 free queue로 돌리는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'KVCacheBlock ref count를 줄이고 free queue/prefix cache 상태를 정리하는 함수를 자른다.',
        stack: ['Python', 'vLLM', 'KV Cache'],
        href: coreItemPath('ai-systems', 'vllm-fn-block-pool-free'),
        article: vllmFunctionCutArticles.blockPoolFree,
        evidence: ['vllm/v1/core/block_pool.py:409', 'BlockPool.free_blocks()'],
        units: ['no double free', 'prefix retention', 'free count'],
      },
      {
        slug: 'vllm-fn-kv-allocate-slots',
        title: 'KVCacheManager.allocate_slots()가 새 토큰용 KV block을 배정하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'computed, cache hit, external, new, lookahead 구간을 나눠 KV slot을 할당하는 함수를 자른다.',
        stack: ['Python', 'vLLM', 'KV Cache'],
        href: coreItemPath('ai-systems', 'vllm-fn-kv-allocate-slots'),
        article: vllmFunctionCutArticles.kvAllocateSlots,
        evidence: ['vllm/v1/core/kv_cache_manager.py:257', 'KVCacheManager.allocate_slots()'],
        units: ['layout partition', 'budget respect', 'cache isolation'],
      },
      {
        slug: 'vllm-fn-api-engine-client',
        title: 'build_async_engine_client()가 OpenAI 서버용 engine client를 여는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'OpenAI-compatible API server lifecycle에서 AsyncLLM engine client를 생성하고 닫는 함수를 자른다.',
        stack: ['Python', 'vLLM', 'OpenAI API'],
        href: coreItemPath('ai-systems', 'vllm-fn-api-engine-client'),
        article: vllmFunctionCutArticles.apiEngineClient,
        evidence: ['vllm/entrypoints/openai/api_server.py:77', 'build_async_engine_client()'],
        units: ['lifecycle close', 'arg fidelity', 'error surface'],
      },
      {
        slug: 'vllm-fn-api-app-state',
        title: 'init_app_state()가 OpenAI route state를 묶는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'chat/completions, completions, embeddings route가 공유할 engine client와 model config 상태를 초기화하는 함수를 자른다.',
        stack: ['Python', 'vLLM', 'OpenAI API'],
        href: coreItemPath('ai-systems', 'vllm-fn-api-app-state'),
        article: vllmFunctionCutArticles.apiAppState,
        evidence: ['vllm/entrypoints/openai/api_server.py:317', 'init_app_state()'],
        units: ['shared engine', 'model config consistency', 'route readiness'],
      },
      {
        slug: 'vllm-fn-api-render-state',
        title: 'init_render_app_state()가 multimodal renderer 상태를 여는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'image/video preprocessing용 render state가 일반 OpenAI route state와 섞이지 않는지 함수 단위로 자른다.',
        stack: ['Python', 'vLLM', 'Multimodal'],
        href: coreItemPath('ai-systems', 'vllm-fn-api-render-state'),
        article: vllmFunctionCutArticles.apiRenderState,
        evidence: ['vllm/entrypoints/openai/api_server.py:408', 'init_render_app_state()'],
        units: ['state separation', 'preprocess readiness', 'error clarity'],
      },
      {
        slug: 'vllm-fn-rejection-sampler',
        title: 'RejectionSampler.forward()가 draft token을 검증하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'draft_probs와 target logits로 accepted/recovered/bonus token을 만드는 speculative decoding 검증 함수를 자른다.',
        stack: ['Python', 'vLLM', 'Spec Decode'],
        href: coreItemPath('ai-systems', 'vllm-fn-rejection-sampler'),
        article: vllmFunctionCutArticles.rejectionSampler,
        evidence: ['vllm/v1/sample/rejection_sampler.py:60', 'RejectionSampler.forward()'],
        units: ['acceptance correctness', 'sequence length', 'fallback soundness'],
      },
      {
        slug: 'vllm-fn-eagle-proposer',
        title: 'SpecDecodeBaseProposer가 speculative draft 제안을 준비하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'target hidden state, draft model config, speculative token 수 제한이 맞는지 EAGLE proposer 경계를 자른다.',
        stack: ['Python', 'vLLM', 'Spec Decode'],
        href: coreItemPath('ai-systems', 'vllm-fn-eagle-proposer'),
        article: vllmFunctionCutArticles.eagleProposer,
        evidence: ['vllm/v1/spec_decode/eagle.py:60', 'SpecDecodeBaseProposer.__init__()'],
        units: ['hidden state contract', 'batch bound', 'lookahead agreement'],
      },
      {
        slug: 'ai-llm-ops-codebase',
        title: 'LLM 라우팅과 학습 운영 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'LiteLLM 라우터, fallback, latency strategy와 Open-R1 학습 스크립트를 블로그 글이 아니라 검증 단위 레지스트리로 관리합니다.',
        stack: ['LiteLLM', 'Open-R1', 'Routing', 'Evals'],
        href: coreItemPath('ai-systems', 'ai-llm-ops-codebase'),
        article: codebaseRegistryArticle('ai-llm-ops-codebase', 'LLM 라우팅과 학습 운영 코드베이스'),
        evidence: ['router.py', 'lowest_latency.py', 'proxy_server.py', 'sft.py', 'grpo.py', 'rewards.py'],
        units: [
          'LiteLLM router와 strategy 선택',
          'proxy fallback과 cooldown 처리',
          'Open-R1 SFT/GRPO/reward 흐름',
          'VLM serving gateway schema',
        ],
      },
      {
        slug: 'cnn-deep-learning-codebase',
        title: 'CNN 딥러닝 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'CNN/ResNet류 공개 구현을 conv block, residual path, forward, train/eval loop 검증 단위로 관리합니다.',
        stack: ['CNN', 'PyTorch', 'Deep Learning'],
        href: coreItemPath('ai-systems', 'cnn-deep-learning-codebase'),
        article: codebaseRegistryArticle('cnn-deep-learning-codebase', 'CNN 딥러닝 코드베이스'),
        evidence: ['cnn/model.py', 'resnet/block.py', 'train.py', 'evaluate.py'],
        units: ['Conv-BN-ReLU block', 'Residual block', 'classifier forward', 'train step', 'eval loop'],
      },
      {
        slug: 'gpt2-codebase',
        title: 'GPT-2 공개 LLM 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'GPT-2/nanoGPT류 decoder-only Transformer를 embedding, causal attention, block, loss, generate 단위로 관리합니다.',
        stack: ['GPT-2', 'LLM', 'Transformer'],
        href: coreItemPath('ai-systems', 'gpt2-codebase'),
        article: codebaseRegistryArticle('gpt2-codebase', 'GPT-2 공개 LLM 코드베이스'),
        evidence: ['model.py', 'CausalSelfAttention', 'Block', 'generate'],
        units: ['token/position embedding', 'causal self-attention', 'residual MLP block', 'LM loss', 'generate loop'],
      },
      {
        slug: 'vlm-codebase',
        title: '공개 VLM 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'CLIP/LLaVA류 VLM을 vision encoder, projector, image-token merge, multimodal forward/generate 단위로 관리합니다.',
        stack: ['VLM', 'CLIP', 'LLaVA'],
        href: coreItemPath('ai-systems', 'vlm-codebase'),
        article: codebaseRegistryArticle('vlm-codebase', '공개 VLM 코드베이스'),
        evidence: ['vision_encoder.py', 'mm_projector.py', 'multimodal.py', 'generation.py'],
        units: ['vision tower', 'projector', 'image token merge', 'multimodal forward', 'generate input prep'],
      },
      {
        slug: 'stable-diffusion-codebase',
        title: 'Stable Diffusion 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Stable Diffusion류 latent diffusion을 VAE, text conditioning, UNet, scheduler, CFG sample loop 단위로 관리합니다.',
        stack: ['Stable Diffusion', 'VAE', 'UNet'],
        href: coreItemPath('ai-systems', 'stable-diffusion-codebase'),
        article: codebaseRegistryArticle('stable-diffusion-codebase', 'Stable Diffusion 코드베이스'),
        evidence: ['autoencoder.py', 'pipeline.py', 'unet.py', 'scheduler.py'],
        units: ['VAE latent', 'text conditioning', 'UNet denoise', 'scheduler step', 'CFG sample loop'],
      },
      {
        slug: 'llm-serving-ops',
        title: 'LLM Serving 제어면',
        kind: 'deep-dive',
        status: 'active',
        summary: '사용자 요청과 SLO에서 시작해 호환되는 release, GPU capacity lease, attempt-aware gateway와 검증된 복구를 하나의 evidence chain으로 연결합니다.',
        stack: ['Kubernetes', 'GPU Fleet', 'LLM Gateway'],
        href: coreItemPath('ai-systems', 'llm-serving-ops'),
        article: requireAiArticle('llm-serving-ops'),
        evidence: ['release fingerprint', 'device/claim identity', 'attempt lineage', 'recovery execution id'],
        units: [
          'Release contract: model·tokenizer·runtime compatibility와 canary·rollback transaction을 검증한다.',
          'Fleet contract: advertised, scheduler-feasible, allocated, healthy와 warm capacity를 분리한다.',
          'Gateway contract: logical request와 실제 attempt, stream commit, 비용과 route reason을 추적한다.',
          'Recovery contract: 같은 identity와 idempotency key로 행동의 효과 또는 undo를 증명한다.',
        ],
      },
      {
        slug: 'open-r1',
        title: 'Open-R1 학습과 평가 파이프라인',
        kind: 'decision',
        status: 'active',
        summary: 'SFT, GRPO, reward function, data pipeline, evaluation을 모델 학습/평가 코드 단위로 관리합니다.',
        stack: ['Open-R1', 'Training', 'Evals'],
        href: coreItemPath('ai-systems', 'open-r1'),
        article: requireAiArticle('open-r1'),
        evidence: ['sft.py', 'grpo.py', 'rewards.py', 'evaluation harness'],
        units: [
          'SFT 데이터 흐름과 GRPO 학습 loop를 분리해서 본다.',
          'reward function은 모델 출력 contract와 평가 기준을 같이 둔다.',
          '평가 벤치마크와 배포 경계는 회귀 판단 단위로 남긴다.',
        ],
      },
      {
        slug: 'llm-architecture-gallery',
        title: 'LLM 구조 읽기 갤러리',
        kind: 'lab',
        status: 'active',
        summary: 'GPT-2부터 DeepSeek, Qwen, Gemma, Kimi까지 LLM 구조를 비교하는 작성 글을 코어 구조 읽기 항목으로 연결합니다.',
        stack: ['LLM Architecture', 'Transformer', 'MoE'],
        href: coreItemPath('ai-systems', 'llm-architecture-gallery'),
        article: requireAiArticle('llm-architecture-gallery'),
        evidence: ['architecture clusters', 'reading protocol', 'core equations'],
        units: [
          '새 모델 논문을 읽을 때 decoder block, attention, FFN, router, KV cache를 같은 순서로 확인한다.',
          '모델별 차이는 dense, MoE, KV/long context, hybrid attention 세부 항목으로 분리한다.',
        ],
      },
      {
        slug: 'llm-architecture-dense-transformers',
        title: 'Dense Transformer 구조',
        kind: 'lab',
        status: 'active',
        summary: 'GPT-2, Llama, Qwen, Gemma, OLMo 계열 dense decoder 구조를 실제 작성 글로 연결합니다.',
        stack: ['Transformer', 'Dense Decoder', 'LLM'],
        href: coreItemPath('ai-systems', 'llm-architecture-dense-transformers'),
        article: requireAiArticle('llm-architecture-dense-transformers'),
        evidence: ['decoder block', 'attention', 'MLP'],
        units: [
          'decoder block 내부 attention, MLP, normalization 배치를 비교한다.',
          'dense 계열 기본 구조를 다른 LLM 구조의 baseline으로 둔다.',
        ],
      },
      {
        slug: 'llm-architecture-sparse-moe',
        title: 'Sparse MoE 구조',
        kind: 'lab',
        status: 'active',
        summary: 'DeepSeek, Qwen MoE, GPT-OSS, GLM, Kimi 계열 router와 expert 구조를 실제 작성 글로 연결합니다.',
        stack: ['MoE', 'Router', 'LLM'],
        href: coreItemPath('ai-systems', 'llm-architecture-sparse-moe'),
        article: requireAiArticle('llm-architecture-sparse-moe'),
        evidence: ['router', 'active parameters', 'expert layout'],
        units: [
          'routing score와 active parameter 수를 분리해서 읽는다.',
          '서빙 병목은 expert parallelism, cache, dispatch cost 단위로 본다.',
        ],
      },
      {
        slug: 'llm-architecture-kv-long-context',
        title: 'KV Cache와 Long Context 구조',
        kind: 'lab',
        status: 'active',
        summary: 'GQA, MLA, sliding-window, RoPE/NoPE 등 long-context 구조를 실제 작성 글로 연결합니다.',
        stack: ['KV Cache', 'Long Context', 'Attention'],
        href: coreItemPath('ai-systems', 'llm-architecture-kv-long-context'),
        article: requireAiArticle('llm-architecture-kv-long-context'),
        evidence: ['GQA', 'MLA', 'SWA', 'RoPE/NoPE'],
        units: [
          'KV cache 크기와 attention head 구성이 메모리 사용량을 어떻게 바꾸는지 본다.',
          'long context 주장은 local/global attention과 실제 cache 비용으로 검증한다.',
        ],
      },
      {
        slug: 'llm-architecture-hybrid-linear',
        title: 'Hybrid/Linear Attention 구조',
        kind: 'lab',
        status: 'active',
        summary: 'Mamba, DeltaNet, Lightning, xLSTM 계열 state-space/linear-time 구조를 실제 작성 글로 연결합니다.',
        stack: ['Linear Attention', 'State Space', 'LLM'],
        href: coreItemPath('ai-systems', 'llm-architecture-hybrid-linear'),
        article: requireAiArticle('llm-architecture-hybrid-linear'),
        evidence: ['state update', 'linear-time attention', 'hybrid block'],
        units: [
          'attention을 줄이거나 대체하는 state update contract를 확인한다.',
          '장문 처리 장점은 품질, 병렬성, cache 비용을 같이 놓고 본다.',
        ],
      },
    ],
  },
  {
    slug: 'code-idioms',
    title: 'Code Idioms',
    eyebrow: 'go · rust · python · typescript',
    summary: '언어별 관용구와 AI가 반복해서 만드는 나쁜 코드를 코어에서 별도 항목으로 관리합니다.',
    focus: [
      'Language-level rules are reusable patterns, not project status',
      'Bad/good examples and review questions must be attached to each idiom',
      'Project-specific exceptions stay separate from general language idioms',
    ],
    items: [
      {
        slug: 'go-service-idioms',
        title: 'Go Service Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'context 전파, error wrapping, goroutine lifecycle, channel ownership, table test를 Go 리뷰 기준으로 관리합니다.',
        stack: ['Go', 'Service', 'Testing'],
        href: coreItemPath('code-idioms', 'go-service-idioms'),
        article: codeIdiomArticle('go-service-idioms', 'Go Service Idioms'),
        evidence: ['context propagation', 'error wrapping', 'goroutine shutdown', 'table tests'],
        units: [
          'context.Context는 request 경계에서 받고 내부에서 새 root context를 만들지 않는다.',
          'goroutine은 종료 신호와 wait 경계를 같이 가져야 한다.',
          'table test는 케이스 이름, 입력, 기대 결과, 실패 이유를 분리한다.',
        ],
      },
      {
        slug: 'rust-api-idioms',
        title: 'Rust API Idioms',
        kind: 'lab',
        status: 'active',
        summary: '소유권 경계, Result/thiserror, trait 남용 방지, clone 최소화, property test 기준을 관리합니다.',
        stack: ['Rust', 'API', 'Correctness'],
        href: coreItemPath('code-idioms', 'rust-api-idioms'),
        article: codeIdiomArticle('rust-api-idioms', 'Rust API Idioms'),
        evidence: ['ownership boundary', 'Result error type', 'property fixtures'],
        units: [
          '소유권 이동과 borrow 경계는 public API에서 의도가 드러나야 한다.',
          '도메인 오류는 문자열보다 타입으로 구분한다.',
          'clone은 비용과 의미가 보일 때만 허용한다.',
        ],
      },
      {
        slug: 'python-llm-idioms',
        title: 'Python LLM Code Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'LLM 서빙/평가 코드에서 typing, pathlib, structured parser, broad except 금지, pytest fixture를 관리합니다.',
        stack: ['Python', 'LLM', 'Testing'],
        href: coreItemPath('code-idioms', 'python-llm-idioms'),
        article: codeIdiomArticle('python-llm-idioms', 'Python LLM Code Idioms'),
        evidence: ['typing', 'structured parsing', 'pytest fixture', 'error boundary'],
        units: [
          'JSON/YAML/CSV는 문자열 split 대신 구조화 parser로 읽는다.',
          'broad except는 예외 타입, 로그, 재시도 여부가 분리될 때만 둔다.',
          'pytest fixture는 모델 호출과 deterministic unit을 분리한다.',
        ],
      },
      {
        slug: 'typescript-ui-idioms',
        title: 'TypeScript UI Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'React 상태 모델, async error, type narrowing, 긴 텍스트 overflow, 불필요한 wrapper hook 생성을 관리합니다.',
        stack: ['TypeScript', 'React', 'UI'],
        href: coreItemPath('code-idioms', 'typescript-ui-idioms'),
        article: codeIdiomArticle('typescript-ui-idioms', 'TypeScript UI Idioms'),
        evidence: ['state model', 'type narrowing', 'responsive text fit'],
        units: [
          'loading/error/empty/success 상태는 한 컴포넌트에서 서로 배타적으로 표현한다.',
          '긴 URL과 코드 토큰은 모바일에서 줄바꿈 또는 의도적 truncate를 가진다.',
          'wrapper hook은 중복 상태를 줄일 때만 만들고, 단순 전달용 hook은 만들지 않는다.',
        ],
      },
      {
        slug: 'rust-concurrency-idioms',
        title: 'Rust Concurrency Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'tokio task ownership, cancellation, bounded channel, shared state 비용을 Rust 동시성 리뷰 기준으로 관리합니다.',
        stack: ['Rust', 'Concurrency', 'Tokio'],
        href: coreItemPath('code-idioms', 'rust-concurrency-idioms'),
        article: codeIdiomArticle('rust-concurrency-idioms', 'Rust Concurrency Idioms'),
        evidence: ['JoinHandle ownership', 'CancellationToken', 'bounded channel'],
        units: [
          'spawn된 task는 종료 신호와 JoinHandle 수거 경계를 가진다.',
          'channel capacity는 backpressure contract로 문서화한다.',
          'shared state는 Arc/Mutex 비용과 lock 범위를 리뷰한다.',
        ],
      },
      {
        slug: 'go-testing-idioms',
        title: 'Go Testing Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'table test, subtest isolation, fake clock, race/leak check를 Go 테스트 코드 기준으로 관리합니다.',
        stack: ['Go', 'Testing', 'Determinism'],
        href: coreItemPath('code-idioms', 'go-testing-idioms'),
        article: codeIdiomArticle('go-testing-idioms', 'Go Testing Idioms'),
        evidence: ['table tests', 'fake clock', 'race test'],
        units: [
          'table test는 케이스 이름과 실패 이유를 분리한다.',
          '시간 의존 테스트는 sleep 대신 fake clock을 먼저 둔다.',
          'subtest는 공유 fixture를 오염시키지 않는다.',
        ],
      },
      {
        slug: 'typescript-async-idioms',
        title: 'TypeScript Async Pattern Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'AbortSignal, stale response, retry, optimistic update를 TypeScript 비동기 상태 모델로 관리합니다.',
        stack: ['TypeScript', 'Async', 'React'],
        href: coreItemPath('code-idioms', 'typescript-async-idioms'),
        article: codeIdiomArticle('typescript-async-idioms', 'TypeScript Async Pattern Idioms'),
        evidence: ['AbortSignal', 'stale response guard', 'retry policy'],
        units: [
          'fetch는 AbortSignal과 stale response 방어를 같이 둔다.',
          'retry는 idempotency와 backoff가 있을 때만 둔다.',
          'optimistic update는 rollback state를 같이 가진다.',
        ],
      },
      {
        slug: 'design-pattern-idioms',
        title: 'Design Pattern Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Strategy, Adapter, Factory 같은 패턴을 이름이 아니라 dependency direction과 테스트 경계 기준으로 관리합니다.',
        stack: ['Architecture', 'Patterns', 'Review'],
        href: coreItemPath('code-idioms', 'design-pattern-idioms'),
        article: codeIdiomArticle('design-pattern-idioms', 'Design Pattern Idioms'),
        evidence: ['dependency direction', 'adapter boundary', 'strategy variants'],
        units: [
          'strategy는 분기 폭이 외부 정책으로 바뀔 때만 둔다.',
          'adapter는 외부 API shape를 내부 도메인에서 격리한다.',
          'factory는 lifecycle과 validation이 같이 필요할 때 둔다.',
        ],
      },
      {
        slug: 'api-design-idioms',
        title: 'API Design Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Idempotency, cursor pagination, error envelope, versioning을 API 재사용 기준으로 관리합니다.',
        stack: ['API', 'Contracts', 'Reliability'],
        href: coreItemPath('code-idioms', 'api-design-idioms'),
        article: codeIdiomArticle('api-design-idioms', 'API Design Idioms'),
        evidence: ['idempotency key', 'cursor pagination', 'error envelope'],
        units: [
          'mutation API는 idempotency key를 먼저 설계한다.',
          'list API는 cursor와 stable ordering을 같이 둔다.',
          'error envelope는 machine code와 human message를 분리한다.',
        ],
      },
      {
        slug: 'transformer-architecture-idioms',
        title: 'Transformer Architecture Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Attention shape, mask semantics, KV cache, normalization 위치를 Transformer 구현 리뷰 기준으로 관리합니다.',
        stack: ['Transformer', 'LLM', 'Architecture'],
        href: coreItemPath('code-idioms', 'transformer-architecture-idioms'),
        article: codeIdiomArticle('transformer-architecture-idioms', 'Transformer Architecture Idioms'),
        evidence: ['qkv shape', 'causal mask', 'KV cache update'],
        units: [
          'attention 함수는 q/k/v shape와 mask 의미를 타입/검증으로 고정한다.',
          'KV cache update는 position source와 eviction 정책을 같이 가진다.',
          'normalization 위치는 pre-norm/post-norm contract로 문서화한다.',
        ],
      },
      {
        slug: 'mlops-idioms',
        title: 'ML Ops Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Dataset snapshot, model artifact, metric script, rollout guard를 같은 run id로 묶는 ML 운영 관용구를 관리합니다.',
        stack: ['MLOps', 'Evaluation', 'Deployment'],
        href: coreItemPath('code-idioms', 'mlops-idioms'),
        article: codeIdiomArticle('mlops-idioms', 'ML Ops Idioms'),
        evidence: ['dataset sha', 'model registry', 'canary guardrail'],
        units: [
          'dataset과 metric은 run id에 고정한다.',
          'online rollout은 offline metric과 guardrail을 둘 다 본다.',
          'prompt/config/model artifact는 같은 release 단위로 묶는다.',
        ],
      },
      {
        slug: 'solidity-gas-idioms',
        title: 'Gas Optimization Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Storage write, calldata/memory, unchecked scope, event 설계를 Solidity gas 최적화 기준으로 관리합니다.',
        stack: ['Solidity', 'Gas', 'EVM'],
        href: coreItemPath('code-idioms', 'solidity-gas-idioms'),
        article: codeIdiomArticle('solidity-gas-idioms', 'Gas Optimization Idioms'),
        evidence: ['SSTORE minimization', 'unchecked scope', 'calldata policy'],
        units: [
          'storage write는 상태 전이 의미가 있을 때만 수행한다.',
          'unchecked는 overflow 불변조건이 증명된 작은 범위에만 둔다.',
          'calldata/memory 선택은 copy 비용과 mutation 필요성으로 판단한다.',
        ],
      },
      {
        slug: 'solidity-reentrancy-idioms',
        title: 'Reentrancy Guard Idioms',
        kind: 'lab',
        status: 'active',
        summary: 'Checks-effects-interactions, pull payment, shared state lock, cross-function 재진입을 Solidity 보안 기준으로 관리합니다.',
        stack: ['Solidity', 'Security', 'EVM'],
        href: coreItemPath('code-idioms', 'solidity-reentrancy-idioms'),
        article: codeIdiomArticle('solidity-reentrancy-idioms', 'Reentrancy Guard Idioms'),
        evidence: ['checks-effects-interactions', 'nonReentrant', 'cross-function lock'],
        units: [
          '외부 call 전에 effect를 먼저 반영한다.',
          'guard는 함수 하나가 아니라 공유 상태 단위로 판단한다.',
          'hook/callback path는 공격 contract fixture로 검증한다.',
        ],
      },
    ],
  },
  {
    slug: 'blockchain-core',
    title: 'Blockchain Core',
    eyebrow: 'zkVM · protocol · storage',
    summary: 'Protocol internals, zkVM architecture, proof-friendly Rust implementations, node storage, and consensus systems.',
    focus: [
      'zkVM execution, proving pipeline, and guest-program constraints',
      'Rust implementations of ZK primitives and proof systems',
      'Node internals: execution, storage, mempool, consensus, and light clients',
    ],
    items: [
      {
        title: 'Rust ZK From Scratch',
        kind: 'project',
        status: 'active',
        summary: 'Field arithmetic, elliptic curves, Poseidon, Merkle proofs, Groth16, and PLONK implementation track.',
        stack: ['Rust', 'ZK', 'Cryptography'],
        href: articlePath('blockchain', 'impl-field-arithmetic'),
        evidence: ['Field arithmetic', 'Poseidon and Merkle', 'Groth16 implementation plan'],
      },
      {
        title: 'zkVM Architecture Notes',
        kind: 'deep-dive',
        status: 'active',
        summary: 'SP1, RISC Zero, and Jolt organized around execution traces, memory, AIR/STARK, recursion, and SDK flow.',
        stack: ['zkVM', 'RISC-V', 'STARK'],
        href: articlePath('blockchain', 'sp1'),
      },
      {
        title: 'Ethereum and Node Internals',
        kind: 'deep-dive',
        status: 'active',
        summary: 'Reth, Prysm, Helios, EVM execution, transaction pool, state, and client architecture study path.',
        stack: ['Rust', 'Ethereum', 'Go'],
        href: articlePath('blockchain', 'reth-block-execution'),
      },
      {
        slug: 'reth-codebase',
        title: 'Reth 실행 클라이언트 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Reth의 node builder, DB/provider, pipeline, txpool, network/sync/RPC 범위를 검증 단위 레지스트리로 관리합니다.',
        stack: ['Reth', 'Rust', 'Ethereum'],
        href: coreItemPath('blockchain-core', 'reth-codebase'),
        article: codebaseRegistryArticle('reth-codebase', 'Reth 실행 클라이언트 코드베이스'),
        evidence: ['builder.rs', 'provider refs', 'stage refs', 'txpool refs', 'session/snap/engine refs'],
        units: ['CLI와 NodeBuilder 구성', 'ChainSpec, alloy primitive, RLP', 'DB, provider, trie 상태 접근', 'Pipeline과 block execution', 'Txpool, EIP-1559, EIP-4844', 'Network, sync, RPC, payload builder'],
      },
      {
        slug: 'prysm-codebase',
        title: 'Prysm consensus client 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Prysm의 block processing, Engine API, epoch processing, sync committee, gossip, DB 경계를 검증 단위 레지스트리로 관리합니다.',
        stack: ['Prysm', 'Go', 'Consensus'],
        href: coreItemPath('blockchain-core', 'prysm-codebase'),
        article: codebaseRegistryArticle('prysm-codebase', 'Prysm consensus client 코드베이스'),
        evidence: ['process_block.go', 'engine_client.go', 'epoch_processing.go', 'sync_committee.go', 'validate_beacon_blocks.go'],
        units: ['block processing', 'operation validation', 'Engine API payload', 'epoch processing', 'reward/penalty', 'sync committee', 'gossip validation', 'beacon DB'],
      },
      {
        slug: 'helios-codebase',
        title: 'Helios 라이트 클라이언트 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'checkpoint sync, light client update, BLS committee 검증, execution proof RPC를 검증 단위 레지스트리로 관리합니다.',
        stack: ['Helios', 'Rust', 'Light Client'],
        href: coreItemPath('blockchain-core', 'helios-codebase'),
        article: codebaseRegistryArticle('helios-codebase', 'Helios 라이트 클라이언트 코드베이스'),
        evidence: ['bootstrap refs', 'consensus/src/update.rs', 'committee lifecycle', 'proof DB / eth_call flow'],
        units: ['Checkpoint bootstrap과 store 초기화', 'Light client update 검증과 적용', 'Sync committee BLS 검증과 교체', 'State proof와 execution RPC'],
      },
      {
        slug: 'lighthouse-codebase',
        title: 'Lighthouse consensus client 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Lighthouse beacon node, network, store, execution layer, validator client 범위를 검증 단위 레지스트리로 관리합니다.',
        stack: ['Lighthouse', 'Rust', 'Consensus'],
        href: coreItemPath('blockchain-core', 'lighthouse-codebase'),
        article: codebaseRegistryArticle('lighthouse-codebase', 'Lighthouse consensus client 코드베이스'),
        evidence: ['beacon_chain.rs', 'service.rs', 'sync/manager.rs', 'gossip_methods.rs', 'hot_cold_store.rs'],
        units: ['beacon node chain 상태와 block import', 'network service와 sync manager', 'gossip block 처리와 검증 입구', 'hot/cold store와 validator duties'],
      },
      {
        slug: 'sp1-codebase',
        title: 'SP1 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'SP1의 VM executor, opcode/syscall, SDK prover, recursion wrapping을 별도 레지스트리로 관리합니다.',
        stack: ['zkVM', 'SP1', 'Rust'],
        href: coreItemPath('blockchain-core', 'sp1-codebase'),
        article: codebaseRegistryArticle('sp1-codebase', 'SP1 코드베이스'),
        evidence: ['vm-advance', 'vm-alu', 'vm-ecall', 'prove_core', 'compress', 'wrap'],
        units: ['VM state', 'cycle/opcode', 'syscall', 'SDK prover', 'core proof/compress', 'shrink/wrap'],
      },
      {
        slug: 'risc0-codebase',
        title: 'RISC Zero 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'RISC Zero의 prover, session/segment, receipt pipeline, recursion을 별도 레지스트리로 관리합니다.',
        stack: ['zkVM', 'RISC Zero', 'Rust'],
        href: coreItemPath('blockchain-core', 'risc0-codebase'),
        article: codebaseRegistryArticle('risc0-codebase', 'RISC Zero 코드베이스'),
        evidence: ['prover_impl.rs', 'session.rs', 'recursion prove refs'],
        units: ['prove entry', 'session/segment', 'composite receipt', 'Groth16 receipt', 'recursion lift/join/identity'],
      },
      {
        slug: 'jolt-codebase',
        title: 'Jolt 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Jolt의 instruction lookup, prover stage, batched sumcheck, proof serialization을 별도 레지스트리로 관리합니다.',
        stack: ['zkVM', 'Jolt', 'Rust'],
        href: coreItemPath('blockchain-core', 'jolt-codebase'),
        article: codebaseRegistryArticle('jolt-codebase', 'Jolt 코드베이스'),
        evidence: ['instruction/mod.rs', 'prover.rs', 'sumcheck.rs', 'proof_serialization.rs'],
        units: ['instruction lookup', 'prover stage', 'batched sumcheck', 'proof serialization'],
      },
    ],
  },
  {
    slug: 'verification-practice',
    title: 'Verification Practice',
    eyebrow: '코드 위치 · 불변조건 · 테스트',
    summary: 'Production codebase analysis that turns code locations into boundary specs, invariants, counterexamples, and regression tests.',
    focus: [
      'Boundary slicing for legacy or production code',
      'Code-location-anchored invariants and counterexample tables',
      'Regression tests that preserve each verified cut as evidence',
    ],
    items: [
      {
        slug: 'fm-boundary-practice',
        title: '기존 코드를 검증 가능한 작은 경계로 나누는 방법',
        kind: 'deep-dive',
        status: 'active',
        summary: '기존 코드를 코드 위치, 주장, 불변조건, 테스트 가능한 실패 사례가 있는 검증 가능한 단위로 자르는 방법 기록.',
        stack: ['Formal Methods', 'Testing', 'Code Review'],
        href: coreItemPath('verification-practice', 'fm-boundary-practice'),
        article: fmBoundaryPracticeArticle,
        evidence: ['경계 자르기 프레임', '산출물 체크리스트', '실패 모드', '다음 절단 기준'],
        units: [
          '대상 절단: 함수/모듈 하나를 입력, 출력, 전제 조건이 보이는 크기로 제한한다.',
          '불변조건 기록: accepted/rejected 결과가 유지해야 하는 성질을 표로 고정한다.',
          '반례 고정: 각 불변조건을 하나씩 깨는 fixture를 만들어 회귀 테스트로 남긴다.',
        ],
      },
      {
        slug: 'geth-blob-tx-fm',
        title: 'geth Blob 트랜잭션을 정적으로 검증하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'geth의 validateBlobTx를 입력/출력, 불변조건, 반례, 회귀 테스트로 고정한 첫 번째 검증 단위.',
        stack: ['Go', 'Ethereum', 'Formal Methods', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-blob-tx-fm'),
        article: gethBlobTxFmArticle,
        evidence: ['소스 앵커', '경계 명세', '불변조건 표', '반례 매트릭스', '회귀 테스트'],
        units: [
          'validateBlobTx: 상태 DB 없이 tx/head/options만 보고 blob transaction을 허용하거나 거절하는 정적 검증 함수.',
          'fork/version gate: Cancun v0, Osaka v1처럼 fork가 sidecar 해석과 proof 검증 방식을 바꾸는 경계.',
          'cheap checks before KZG: sidecar 존재성, blob fee, 배열 길이, commitment hash를 먼저 검사해 비싼 proof 검증 전에 명백한 반례를 제거한다.',
          'proof verification boundary: KZG 내부 구현은 별도 oracle로 두고, 이 단위에서는 proof 검증 성공/실패 결과만 관찰값으로 고정한다.',
        ],
        concepts: [
          {
            term: 'Blob',
            summary: 'EIP-4844에서 실행 레이어 calldata 대신 별도 데이터 가용성 영역에 싣는 큰 데이터 조각.',
            intent: '롤업이 L1에 모든 데이터를 비싼 calldata로 남기지 않고, 합의 레이어가 일정 기간 보장하는 데이터로 게시하게 만드는 비용 절감 장치다.',
            details: [
              'EVM이 blob 내용을 직접 실행하지 않는다. 트랜잭션은 blob의 versioned hash만 참조한다.',
              '검증 경계에서는 blob 본문, commitment, proof가 같은 데이터 조각을 설명하는지 확인하는 것이 핵심이다.',
              'blob 데이터는 영구 상태가 아니라 데이터 가용성 보장 대상이므로, 실행 결과보다 게시 가능성과 검증 가능성이 중요하다.',
            ],
            references: [
              { label: 'Reth EIP-4844 Blob TX - Blob TX 구조', href: `${articlePath('blockchain', 'reth-eip4844')}#overview` },
              { label: '데이터 가용성 이론 - Blob 트랜잭션 배경', href: `${articlePath('blockchain', 'da-theory')}#eip-4844` },
            ],
          },
          {
            term: 'BlobTxSidecar',
            summary: 'blob transaction 본문 밖에서 blob, KZG commitment, proof, sidecar version을 함께 들고 다니는 부가 데이터 묶음.',
            intent: '트랜잭션 본문은 작게 유지하면서도 txpool과 검증자가 blob 데이터의 존재, commitment 연결, proof 유효성을 확인할 수 있게 한다.',
            details: [
              'sidecar는 transaction 자체가 아니라 transaction에 붙는 검증 재료다.',
              'Version은 fork별 해석 규칙을 고른다. Cancun은 v0 blob proof, Osaka는 v1 cell proof 경계로 갈라진다.',
              'Blobs, Commitments, Proofs 배열은 같은 인덱스의 blob을 설명해야 하므로 길이와 순서가 불변조건이 된다.',
            ],
            references: [
              { label: 'Reth EIP-4844 Blob TX - Blob TX 구조', href: `${articlePath('blockchain', 'reth-eip4844')}#overview` },
            ],
          },
          {
            term: 'Blob Transaction',
            summary: '일반 transaction 필드에 blob gas fee cap과 blob versioned hash 목록을 추가한 EIP-4844 transaction.',
            intent: '실행 레이어에는 blob의 약속값만 남기고, 실제 데이터 가용성은 sidecar와 consensus 검증 경로로 분리한다.',
            details: [
              'validateBlobTx는 서명, nonce, balance 같은 상태 검증이 아니라 blob 전용 정적 조건만 본다.',
              'accepted 상태라면 sidecar 존재, blob hash 개수, commitment 연결, proof 성공이 동시에 성립해야 한다.',
              'blob fee cap은 execution gas price와 별개로 blob gas 시장의 최소 가격을 만족해야 한다.',
            ],
            references: [
              { label: 'Reth EIP-4844 Blob TX', href: `${articlePath('blockchain', 'reth-eip4844')}#overview` },
              { label: '데이터 가용성 이론 - EIP-4844', href: `${articlePath('blockchain', 'da-theory')}#eip-4844` },
            ],
          },
          {
            term: 'Versioned Hash',
            summary: 'KZG commitment에서 계산한 hash에 버전 바이트를 붙여 transaction이 참조하는 blob 식별자.',
            intent: 'transaction 안의 blob hash가 sidecar의 commitment에서 나온 값인지 연결해, 다른 blob 데이터를 몰래 붙이는 경우를 막는다.',
            details: [
              '검증은 각 commitment에서 versioned hash를 다시 계산한 뒤 transaction의 BlobHashes 항목과 비교한다.',
              '버전 바이트는 향후 commitment/proof 형식이 바뀌어도 hash 의미를 구분하기 위한 프로토콜 경계다.',
            ],
          },
          {
            term: 'KZG Proof Boundary',
            summary: 'blob과 commitment가 맞다는 암호학적 검증을 수행하는 비싼 단계.',
            intent: '이 검증 화면에서는 KZG 내부 수학을 재증명하지 않고, proof 검증 성공/실패를 관찰 가능한 oracle 결과로 고정한다.',
            details: [
              '길이, nil, fee, hash mismatch 같은 싼 실패는 KZG 전에 제거한다.',
              'fork version에 따라 v0 blob proof 검증과 v1 cell proof 검증으로 분기한다.',
            ],
          },
        ],
      },
      {
        slug: 'geth-fm-002-header-rlp',
        title: '블록 헤더를 RLP 바이트에서 구조체로 읽는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'core/types header RLP decode 최적화가 semantic equivalence, stale field 제거, trailing input 거부, allocation budget을 유지하는지 자른다.',
        stack: ['Go', 'Ethereum', 'RLP', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-fm-002-header-rlp'),
        article: gethFmCutArticles.headerRlp,
        evidence: ['PR #35030', 'core/types', 'eth/protocols/eth', 'benchmark guard'],
        units: ['legacy/London header decode equivalence', 'reuse buffer stale field rejection', 'BlockHeaders response ownership', 'decode allocation budget'],
      },
      {
        slug: 'geth-fm-003-getblobs-availability',
        title: '엔진 API가 Blob 데이터 보유 여부를 알려주는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'eth/catalyst GetBlobs 계열에서 available count, partial availability, nil/empty blob list, tracing 추가가 API 의미를 바꾸지 않는지 자른다.',
        stack: ['Go', 'Ethereum', 'Engine API', 'Blobs'],
        href: coreItemPath('verification-practice', 'geth-fm-003-getblobs-availability'),
        article: gethFmCutArticles.getBlobs,
        evidence: ['PR #35028', 'PR #35026', 'PR #35019', 'eth/catalyst'],
        units: ['true count availability metric', 'partial blob short circuit', 'nil blob list JSON preservation', 'tracing without API shape drift'],
      },
      {
        slug: 'geth-fm-004-graphql-raw-body',
        title: 'GraphQL이 본문이 없는 블록을 안전하게 보여주는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'GraphQL Raw resolver가 block body 누락을 panic이 아니라 관찰 가능한 null/error 경계로 처리하는지 자른다.',
        stack: ['Go', 'GraphQL', 'Ethereum', 'API'],
        href: coreItemPath('verification-practice', 'geth-fm-004-graphql-raw-body'),
        article: gethFmCutArticles.graphqlRaw,
        evidence: ['PR #35027', 'graphql', 'missing body fixture'],
        units: ['header exists body missing', 'raw resolver panic guard', 'GraphQL response shape stability'],
      },
      {
        slug: 'geth-fm-005-transaction-args',
        title: 'RPC 트랜잭션 입력값이 타입에 맞는지 걸러내는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'internal/ethapi TransactionArgs에서 명시 tx type과 field 조합, fee defaulting, blob 전용 필드 경계를 검증한다.',
        stack: ['Go', 'Ethereum RPC', 'Transaction Types', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-fm-005-transaction-args'),
        article: gethFmCutArticles.txArgs,
        evidence: ['PR #34997', 'internal/ethapi', 'TestSetFeeDefaults'],
        units: ['explicit type-field compatibility', 'blob field gating', 'fee defaulting by tx type', 'send/fill blob transaction roundtrip'],
      },
      {
        slug: 'geth-fm-006-engine-payload-witness',
        title: '엔진 payload와 witness를 만들고 검증하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'miner/eth/catalyst payload 생성, newPayload, witness V5, request validation을 Engine API 관찰 경계로 자른다.',
        stack: ['Go', 'Ethereum', 'Engine API', 'Stateless'],
        href: coreItemPath('verification-practice', 'geth-fm-006-engine-payload-witness'),
        article: gethFmCutArticles.enginePayload,
        evidence: ['PR #35009', 'PR #35025', 'eth/catalyst', 'core/stateless'],
        units: ['payload ID determinism', 'prepare/getPayload/newPayload state preservation', 'witness V5 field ordering', 'Amsterdam t8n output shape'],
      },
      {
        slug: 'geth-fm-007-chain-reorg',
        title: '체인 import와 재구성이 canonical 상태를 바꾸는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'core/blockchain의 canonical import, fork choice, tx/log reorg 이벤트, fork rule 전환을 실행 가능한 chain 경계로 자른다.',
        stack: ['Go', 'Ethereum Core', 'Fork Choice', 'Reorg'],
        href: coreItemPath('verification-practice', 'geth-fm-007-chain-reorg'),
        article: gethFmCutArticles.chainReorg,
        evidence: ['core/blockchain tests', 'reorg tests', 'EIP transition tests'],
        units: ['shorter fork does not win', 'longer fork reorgs canonical chain', 'tx/log removed-rebirth semantics', 'fork transition rules'],
      },
      {
        slug: 'geth-fm-008-state-recovery',
        title: '스냅샷과 원시 DB가 재시작 뒤 복구되는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'snapshot restart/crash/setHead, freezer append/read/truncate, tx index repair를 복구 가능성 경계로 자른다.',
        stack: ['Go', 'Ethereum State', 'RawDB', 'Recovery'],
        href: coreItemPath('verification-practice', 'geth-fm-008-state-recovery'),
        article: gethFmCutArticles.stateRecovery,
        evidence: ['core snapshot tests', 'core/rawdb freezer tests', 'tx indexer repair'],
        units: ['snapshot root preserved across restart', 'crash recovery restores state', 'freezer operations are atomic', 'tx index repair fills missing ranges'],
      },
      {
        slug: 'geth-fm-009-blobpool-limbo',
        title: 'Blob 트랜잭션 풀이 대기 데이터와 누락 데이터를 다루는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'core/txpool/blobpool에서 legacy limbo blob, blob sidecar decode, blob tx pool 경계를 별도 절차로 자른다.',
        stack: ['Go', 'Ethereum Txpool', 'Blobpool', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-fm-009-blobpool-limbo'),
        article: gethFmCutArticles.blobpool,
        evidence: ['PR #34993', 'PR #34989', 'core/txpool/blobpool'],
        units: ['legacy limbo blob recovery', 'sidecar version preservation', 'blob tx sidecar/hash consistency', 'pool rejection reason stability'],
      },
      {
        slug: 'geth-fm-010-p2p-sync',
        title: 'P2P 피어 발견과 동기화가 나쁜 응답을 걸러내는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'p2p server, discv4/discv5, enode, downloader, snap sync를 peer/network 경계별로 검증한다.',
        stack: ['Go', 'Ethereum P2P', 'Discovery', 'Sync'],
        href: coreItemPath('verification-practice', 'geth-fm-010-p2p-sync'),
        article: gethFmCutArticles.p2pSync,
        evidence: ['PR #34988', 'p2p tests', 'eth/downloader tests', 'snap sync tests'],
        units: ['fallback UDP port range', 'peer cap and inbound throttle', 'discovery timeout/handshake vectors', 'snap corrupt peer handling'],
      },
      {
        slug: 'geth-fm-011-rpc-node-cli',
        title: 'RPC 서버와 노드 실행 명령 입력을 안전하게 받는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'JSON-RPC server/client, WebSocket/HTTP limits, node lifecycle, geth/devp2p CLI 입력 검증을 표면 계약으로 자른다.',
        stack: ['Go', 'JSON-RPC', 'Node', 'CLI'],
        href: coreItemPath('verification-practice', 'geth-fm-011-rpc-node-cli'),
        article: gethFmCutArticles.rpcNode,
        evidence: ['rpc tests', 'node tests', 'cmd/geth tests', 'cmd/devp2p tests'],
        units: ['batch/read-limit response shape', 'websocket origin/header guard', 'node start/close idempotency', 'CLI input validation'],
      },
      {
        slug: 'geth-fm-012-abi-signer',
        title: 'ABI 인코딩과 계정 서명이 사용자 입력을 처리하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'accounts/abi, keystore, signer/core, SIWE parser를 사용자 서명과 ABI 계약의 작은 검증 절차로 자른다.',
        stack: ['Go', 'ABI', 'Signer', 'Accounts'],
        href: coreItemPath('verification-practice', 'geth-fm-012-abi-signer'),
        article: gethFmCutArticles.abiSigner,
        evidence: ['PR #34986', 'accounts/abi tests', 'keystore tests', 'signer/core tests'],
        units: ['ABI pack/unpack/topic stability', 'keystore encrypt/sign/unlock boundaries', 'SIWE positive-negative fixtures', 'signed data display/sign path'],
      },
      {
        slug: 'geth-fm-013-evm-state-transition',
        title: 'EVM 명령 실행과 상태 전이가 fork 규칙을 따르는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'core/vm, state transition, eth_call, estimateGas, simulateV1을 fork rule과 override가 보이는 실행 경계로 자른다.',
        stack: ['Go', 'EVM', 'State Transition', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-fm-013-evm-state-transition'),
        article: gethFmCutArticles.evmState,
        evidence: ['core/vm tests', 'state_transition tests', 'internal/ethapi call/simulate tests'],
        units: ['opcode fixture determinism', 'intrinsic gas by tx type', 'state/block override isolation', 'revert/error distinction'],
      },
      {
        slug: 'geth-fm-014-core-sethead-matrix',
        title: '체인 head를 되감을 때 상태와 스냅샷을 정리하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'core/blockchain_sethead_test.go의 short/long, shallow/deep, finalized, snap synced, snapshot 축을 독립 절차로 승격한다.',
        stack: ['Go', 'Ethereum Core', 'SetHead', 'Recovery'],
        href: coreItemPath('verification-practice', 'geth-fm-014-core-sethead-matrix'),
        article: gethFmCutArticles.coreSetHead,
        evidence: ['core/blockchain_sethead_test.go', 'snapshot mode matrix', 'finalized root regression'],
        units: ['canonical head rewind', 'finalized guard', 'snapshot mode split', 'missing body/receipt tolerance'],
      },
      {
        slug: 'geth-fm-015-ethapi-rpc-semantics',
        title: 'Ethereum RPC 메서드가 실행 결과를 일관되게 반환하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'internal/ethapi method 의미, simulate chain linkage, block/header/tx/receipt JSON shape, sync send timeout을 검증한다.',
        stack: ['Go', 'Ethereum RPC', 'Ethapi', 'Fixtures'],
        href: coreItemPath('verification-practice', 'geth-fm-015-ethapi-rpc-semantics'),
        article: gethFmCutArticles.ethapiRpc,
        evidence: ['internal/ethapi tests', 'RPC marshal tests', 'ethapi testdata'],
        units: ['eth_call override fidelity', 'simulateV1 ordering/linkage', 'receipt/block JSON shape', 'SendRawTransactionSync split'],
      },
      {
        slug: 'geth-fm-016-beacon-light-client',
        title: 'Beacon light client가 checkpoint와 head를 따라가는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'beacon/light committee roots, checkpoint sync, fork update, reorg 처리를 light client 상태 경계로 자른다.',
        stack: ['Go', 'Ethereum Beacon', 'Light Client', 'Sync'],
        href: coreItemPath('verification-practice', 'geth-fm-016-beacon-light-client'),
        article: gethFmCutArticles.beaconLight,
        evidence: ['beacon/light tests', 'beacon/light/sync tests'],
        units: ['committee root proof', 'checkpoint progress', 'fork update shape', 'light client reorg tolerance'],
      },
      {
        slug: 'geth-fm-017-tx-fetcher-state-machine',
        title: '트랜잭션 fetcher가 요청과 시간 초과 상태를 정리하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'eth/fetcher transaction fetcher의 announce, wait, request, deliver, missing, timeout, rate-limit 상태기를 분리한다.',
        stack: ['Go', 'Ethereum P2P', 'Fetcher', 'State Machine'],
        href: coreItemPath('verification-practice', 'geth-fm-017-tx-fetcher-state-machine'),
        article: gethFmCutArticles.txFetcher,
        evidence: ['eth/fetcher/tx_fetcher_test.go'],
        units: ['announce ownership', 'failed/missing reschedule', 'timeout cleanup', 'rate/bandwidth DoS guard'],
      },
      {
        slug: 'geth-fm-018-snap-sync-peer-matrix',
        title: 'Snap sync가 손상된 peer 응답을 격리하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'eth/protocols/snap sync의 capped/corrupt/non-proving/misbehaving peer와 request range/sorting 경계를 검증한다.',
        stack: ['Go', 'Ethereum Snap', 'Sync', 'P2P'],
        href: coreItemPath('verification-practice', 'geth-fm-018-snap-sync-peer-matrix'),
        article: gethFmCutArticles.snapMatrix,
        evidence: ['eth/protocols/snap/sync_test.go', 'request sorting tests'],
        units: ['peer isolation', 'range determinism', 'proof requirement', 'sync progress compatibility'],
      },
      {
        slug: 'geth-fm-019-trie-proof-sync',
        title: 'Trie proof와 iterator가 state root를 보존하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'trie root, proof, iterator, sync, stacktrie, binary trie를 state root와 traversal 계약으로 검증한다.',
        stack: ['Go', 'Trie', 'Proof', 'Sync'],
        href: coreItemPath('verification-practice', 'geth-fm-019-trie-proof-sync'),
        article: gethFmCutArticles.trieProof,
        evidence: ['trie tests', 'trie/proof_test.go', 'trie/sync_test.go', 'stacktrie fuzz regression'],
        units: ['root determinism', 'proof soundness', 'iterator completeness', 'sync duplicate/incomplete safety'],
      },
      {
        slug: 'geth-fm-020-pathdb-history',
        title: 'PathDB history와 prune이 읽기 가능한 상태를 지키는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'triedb/pathdb generation, iterator, history encode/decode, history index, prune, preimage DB를 복구 가능한 DB 경계로 자른다.',
        stack: ['Go', 'PathDB', 'State Storage', 'Recovery'],
        href: coreItemPath('verification-practice', 'geth-fm-020-pathdb-history'),
        article: gethFmCutArticles.pathdbHistory,
        evidence: ['triedb tests', 'triedb/pathdb tests', 'preimages tests'],
        units: ['generation root', 'corruption detection', 'history readability', 'prune pause-resume safety'],
      },
      {
        slug: 'geth-fm-021-encoding-common',
        title: '공통 인코딩 라이브러리가 입력 모서리 값을 처리하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'rlp, hexutil, address/hash, bitutil, LRU, mclock 같은 공통 라이브러리 계약을 별도 검증 절차로 묶는다.',
        stack: ['Go', 'Encoding', 'Common', 'Utilities'],
        href: coreItemPath('verification-practice', 'geth-fm-021-encoding-common'),
        article: gethFmCutArticles.encodingCommon,
        evidence: ['rlp tests', 'common tests', 'hexutil tests', 'bitutil/lru/mclock tests'],
        units: ['encoding roundtrip', 'edge formatting', 'bit compression', 'utility resource bounds'],
      },
      {
        slug: 'geth-fm-022-crypto-fuzzers',
        title: '암호 primitive와 fuzz seed가 crash 없이 처리되는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'secp256k1, bn256, bls12-381, keccak test vectors와 fuzz seed corpus를 crash-free primitive API 경계로 자른다.',
        stack: ['Go', 'Cryptography', 'Fuzzing', 'Testing'],
        href: coreItemPath('verification-practice', 'geth-fm-022-crypto-fuzzers'),
        article: gethFmCutArticles.cryptoFuzzers,
        evidence: ['crypto tests', 'tests/fuzzers/secp256k1', 'tests/fuzzers/bn256', 'tests/fuzzers/bls12381'],
        units: ['signature edge cases', 'curve operation bounds', 'keccak vectors', 'fuzz crash-free seeds'],
      },
      {
        slug: 'geth-fm-023-spec-fixture-replay',
        title: 'Execution spec fixture를 재생해 consensus 결과를 확인하는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'execution-spec block/state/transaction/RLP/difficulty fixtures를 consensus 결과가 보이는 replay 경계로 승격한다.',
        stack: ['Go', 'Ethereum Spec', 'Fixtures', 'Consensus Tests'],
        href: coreItemPath('verification-practice', 'geth-fm-023-spec-fixture-replay'),
        article: gethFmCutArticles.specFixtures,
        evidence: ['tests package', 'execution-spec fixtures', 'state/block/transaction/RLP tests'],
        units: ['blocktests replay', 'statetests post-state root', 'transaction fixture validity', 'RLP/difficulty fixture compatibility'],
      },
      {
        slug: 'geth-fm-024-t8n-fixtures',
        title: 'EVM t8n fixture 출력이 fork별 JSON 형태를 지키는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'cmd/evm/internal/t8ntool과 cmd/evm/testdata 190개 fixture를 Amsterdam/BAL output shape와 golden result 경계로 자른다.',
        stack: ['Go', 'EVM', 'T8n', 'Fixtures'],
        href: coreItemPath('verification-practice', 'geth-fm-024-t8n-fixtures'),
        article: gethFmCutArticles.t8nFixtures,
        evidence: ['cmd/evm/internal/t8ntool tests', 'cmd/evm/testdata fixtures', 'PR #35025'],
        units: ['golden output replay', 'Amsterdam/BAL field shape', 'slotNum JSON compatibility', 'deterministic CLI output'],
      },
      {
        slug: 'geth-fm-025-abigen-bindings',
        title: 'ABI binding 생성기가 Solidity ABI를 Go 코드로 바꾸는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'accounts/abi bind v1/v2와 cmd/abigen generation을 Solidity ABI spec과 Go binding API 경계로 자른다.',
        stack: ['Go', 'ABI', 'Abigen', 'Bindings'],
        href: coreItemPath('verification-practice', 'geth-fm-025-abigen-bindings'),
        article: gethFmCutArticles.abigenBindings,
        evidence: ['accounts/abi tests', 'bind v1/v2 tests', 'cmd/abigen tests'],
        units: ['signature/topic stability', 'tuple/array type mapping', 'generation repeatability', 'malicious ABI bound'],
      },
      {
        slug: 'geth-fm-026-metrics-tracing',
        title: 'Metrics와 tracing이 기존 동작을 바꾸지 않고 관찰값을 남기는 부분',
        kind: 'lab',
        status: 'active',
        summary: 'metrics registry, RPC tracing, core tracing journal hook, GetBlobs tracing을 관찰 가능성 경계로 분리한다.',
        stack: ['Go', 'Metrics', 'Tracing', 'Observability'],
        href: coreItemPath('verification-practice', 'geth-fm-026-metrics-tracing'),
        article: gethFmCutArticles.metricsTracing,
        evidence: ['metrics tests', 'rpc tracing tests', 'core/tracing tests', 'GetBlobs tracing PR'],
        units: ['observability transparency', 'journal hook ordering', 'RPC tracing error attribution', 'metrics registry bounds'],
      },
      {
        slug: 'geth-test-units',
        title: 'go-ethereum 기능별 코드 해설과 검증 단위',
        kind: 'lab',
        status: 'active',
        summary: 'go-ethereum 테스트 코드와 2026-05-22 기준 최근 PR을 코드베이스별 최소 검증 단위와 기능별 검증 주제로 쪼갠 개요 허브.',
        stack: ['Go', 'Ethereum', 'Testing', 'PR Review'],
        href: coreItemPath('verification-practice', 'geth-test-units'),
        article: gethTestUnitsArticle,
        evidence: ['테스트 파일 432개', '테스트 함수 2148개', '퍼즈 대상 43개', '최근 PR 확인', '지식 메모 연결'],
        units: [
          'codebase: go-ethereum. 검증 단위는 PR, 패키지, 테스트 함수, 실행 명령을 함께 가진다.',
          'recent PR cuts: header RLP decode, getBlobs availability count, GraphQL missing body, witness payload, SIWE parser처럼 PR에서 바로 회귀 단위를 뽑는다.',
          'package cuts: core/state, eth/catalyst, internal/ethapi, p2p/discover, trie/pathdb, accounts/abi, crypto/common, spec fixtures처럼 패키지 경계별로 실행 가능한 go test 명령을 둔다.',
          '확장 상태: reth, prysm, helios 등 다른 코드베이스도 같은 코드베이스 > 분류 > 단위 구조로 이미 누적한다.',
        ],
      },
    ],
  },
  {
    slug: 'rust-go-systems',
    title: 'Rust / Go Systems',
    eyebrow: 'idioms · infra · correctness',
    summary: 'Systems programming practice for proof-oriented Rust code and service/indexer-oriented Go code.',
    focus: [
      'Idiomatic Rust APIs, ownership boundaries, and error handling',
      'Go service patterns: context, errors, concurrency, and testing',
      'Benchmarks, property tests, and regression checks as work evidence',
    ],
    items: [
      {
        slug: 'proof-oriented-rust-practice',
        title: 'Proof-Oriented Rust Practice',
        kind: 'lab',
        status: 'active',
        summary: 'ZK 개념을 Rust API, property test, benchmark, failure fixture까지 포함한 재사용 가능한 구현 단위로 바꾸는 작업 흐름.',
        stack: ['Rust', 'Testing', 'Benchmarks'],
        href: coreItemPath('rust-go-systems', 'proof-oriented-rust-practice'),
        evidence: ['field arithmetic API', 'hash commitment fixture', 'property-test boundary', 'criterion benchmark'],
        units: [
          'API 경계: 수학 개념을 타입과 trait로 고정하고, 불가능한 상태를 생성자에서 막는다.',
          '검증 경계: 예제값, 랜덤 property, 경계값 overflow/identity case를 별도 fixture로 유지한다.',
          '성능 경계: correctness test와 benchmark를 분리해 최적화가 의미를 바꾸지 않게 한다.',
        ],
        notes: [
          {
            title: '작업 단위',
            body: '해시 커밋먼트, finite field, Merkle proof처럼 작은 primitive 하나를 고르고, 먼저 입출력 계약을 문서화한 뒤 구현한다. 구현 후에는 성공 예제보다 실패 예제를 먼저 고정한다.',
          },
          {
            title: '완료 기준',
            body: 'README 수준 설명, public API, deterministic fixture, property test, benchmark가 함께 있어야 코어 단위로 완료 처리한다. 글 하나만 있거나 코드만 있으면 진행 상태로 둔다.',
          },
        ],
      },
      {
        slug: 'go-indexer-service-patterns',
        title: 'Go Indexer / Service Patterns',
        kind: 'lab',
        status: 'active',
        summary: '체인 인덱서와 백엔드 서비스에서 반복되는 context, retry, worker pool, idempotency, observability 패턴을 구현 단위로 축적한다.',
        stack: ['Go', 'Services', 'Indexing'],
        href: coreItemPath('rust-go-systems', 'go-indexer-service-patterns'),
        evidence: ['context cancellation policy', 'idempotent ingestion loop', 'retry/backoff table', 'worker pool shutdown checklist'],
        units: [
          'ingestion loop: 블록 높이, cursor, reorg 대응, 재시도 정책을 하나의 상태 전이로 관리한다.',
          'worker pool: 입력 큐, 종료 신호, partial failure, backpressure를 테스트 가능한 인터페이스로 자른다.',
          'repository boundary: DB write는 idempotent upsert와 transaction 범위가 보이게 분리한다.',
        ],
        notes: [
          {
            title: 'AI 코드 검토 기준',
            body: 'AI가 만든 Go 코드는 err 무시, context 미전파, goroutine leak, 너무 넓은 recover를 우선 검사한다. 이 기준을 CI gate와 리뷰 체크리스트로 연결한다.',
          },
          {
            title: '완료 기준',
            body: '단위 테스트, integration fixture, graceful shutdown test, 로그/메트릭 이름까지 있어야 재사용 가능한 코어 패턴으로 인정한다.',
          },
        ],
      },
    ],
  },
  {
    slug: 'trusted-runtime',
    title: 'Trusted Runtime',
    eyebrow: 'TEE · attestation · isolation',
    summary: 'SGX, SEV-SNP, OP-TEE, dstack, Oasis Core처럼 격리 실행과 원격 증명 코드베이스를 각각의 검증 단위로 관리합니다.',
    focus: [
      'Trusted execution environment lifecycle and memory isolation',
      'Attestation, sealing, key manager, and runtime boundary checks',
      'Project-specific commands that keep security claims tied to code evidence',
    ],
    items: [
      {
        slug: 'intel-sgx-codebase',
        title: 'Intel SGX 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'linux-sgx의 ECALL/OCALL, sealing, attestation 경계를 별도 레지스트리로 관리합니다.',
        stack: ['TEE', 'SGX', 'linux-sgx'],
        href: coreItemPath('trusted-runtime', 'intel-sgx-codebase'),
        article: codebaseRegistryArticle('intel-sgx-codebase', 'Intel SGX 코드베이스'),
        evidence: ['trts_ecall.cpp', 'trts_ocall.cpp', 'sgx_get_key.cpp', 'quote/report refs'],
        units: ['ECALL dispatch', 'OCALL return', 'sealing key/blob', 'report/quote', 'dynamic entry table'],
      },
      {
        slug: 'sev-snp-codebase',
        title: 'AMD SEV-SNP 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'SEV-SNP의 RMP, VMPL, PVALIDATE, guest attestation request를 별도 레지스트리로 관리합니다.',
        stack: ['TEE', 'SEV-SNP', 'KVM'],
        href: coreItemPath('trusted-runtime', 'sev-snp-codebase'),
        article: codebaseRegistryArticle('sev-snp-codebase', 'AMD SEV-SNP 코드베이스'),
        evidence: ['sev-common.h', 'sev.h', 'pvalidate refs', 'guest request refs'],
        units: ['RMP ownership', 'VMPL permission', 'PVALIDATE', 'attestation report', 'guest request'],
      },
      {
        slug: 'optee-codebase',
        title: 'OP-TEE OS 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'OP-TEE OS의 SMC 진입, TA 세션, secure storage key manager를 별도 레지스트리로 관리합니다.',
        stack: ['TEE', 'OP-TEE', 'TrustZone'],
        href: coreItemPath('trusted-runtime', 'optee-codebase'),
        article: codebaseRegistryArticle('optee-codebase', 'OP-TEE OS 코드베이스'),
        evidence: ['thread_optee_smc.c', 'entry_std.c', 'tee_fs_key_manager.c'],
        units: ['Fast SMC', 'Standard SMC', 'TA session dispatch', 'FEK/HMAC', 'SSK/TSK init'],
      },
      {
        slug: 'dstack-codebase',
        title: 'dstack TDX 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'dstack의 TDX VM 생성, manifest, KMS, quote, RA-TLS binding을 별도 레지스트리로 관리합니다.',
        stack: ['TEE', 'TDX', 'dstack'],
        href: coreItemPath('trusted-runtime', 'dstack-codebase'),
        article: codebaseRegistryArticle('dstack-codebase', 'dstack TDX 코드베이스'),
        evidence: ['td_vm.rs', 'manifest refs', 'kms refs', 'attestation refs'],
        units: ['TDX VM create', 'manifest policy', 'KMS key issue', 'quote verify', 'RA-TLS'],
      },
      {
        slug: 'oasis-core-codebase',
        title: 'Oasis Core 코드베이스',
        kind: 'project',
        status: 'active',
        summary: 'Oasis Core의 consensus mux, runtime dispatcher, executor worker, key manager secrets API를 별도 레지스트리로 관리합니다.',
        stack: ['TEE', 'Oasis Core', 'Go', 'Rust'],
        href: coreItemPath('trusted-runtime', 'oasis-core-codebase'),
        article: codebaseRegistryArticle('oasis-core-codebase', 'Oasis Core 코드베이스'),
        evidence: ['abci/mux.go', 'full.go', 'dispatcher.rs', 'worker.go', 'secrets/api.go'],
        units: ['ABCI mux', 'full service', 'runtime dispatcher', 'executor worker', 'keymanager secrets'],
      },
    ],
  },
  {
    slug: 'decisions',
    title: 'Engineering Decisions',
    eyebrow: 'adr · tradeoffs · review',
    summary: 'Short decision records that make project choices reusable in interviews and technical discussions.',
    focus: [
      'Why a design was chosen over alternatives',
      'What failed, what changed, and what remains risky',
      'How AI-generated code was reviewed and made idiomatic',
    ],
    items: [
      {
        slug: 'ai-as-reviewer-not-author',
        title: 'AI as Reviewer, Not Author',
        kind: 'decision',
        status: 'active',
        summary: 'AI를 코드 작성자 하나로 두지 않고, 구현자·리뷰어·검증자 역할을 분리해 의미 없는 테스트와 과도한 통과 처리를 막는 운영 결정.',
        stack: ['AI Coding', 'Review', 'Practice'],
        href: coreItemPath('decisions', 'ai-as-reviewer-not-author'),
        evidence: ['ai-quality-gates script', 'CI workflow', 'review-first prompt policy', 'local regression checks'],
        units: [
          '구현 에이전트는 작은 파일 범위와 완료 조건을 받는다.',
          '리뷰 에이전트는 코드 변경을 보지 말고 실패 모드와 누락 테스트부터 찾는다.',
          '로컬 gate는 skip test, assertion 없는 test, empty catch, broad swallow를 PR 전에 잡는다.',
        ],
        notes: [
          {
            title: '결정',
            body: 'AI가 만든 결과를 바로 신뢰하지 않고, 같은 작업 안에서 구현과 검증 책임을 분리한다. 사람은 최종 판단자이고, CI는 반복 가능한 최소 기준을 강제한다.',
          },
          {
            title: '위험',
            body: '검사가 너무 넓으면 개발을 막고, 너무 좁으면 의미 없는 통과가 남는다. 그래서 우선 로컬 gate는 명백한 냄새만 잡고, 프로젝트별 규칙은 점진적으로 추가한다.',
          },
        ],
      },
      {
        slug: 'tsx-articles-vs-core-workbench',
        title: 'TSX Articles vs Core Workbench',
        kind: 'decision',
        status: 'done',
        summary: '블로그는 긴 학습 글로 유지하고, 코어는 실제 작업 단위·검증 결과·결정 기록을 보여주는 운영 지도 역할로 분리한다.',
        stack: ['React', 'Information Architecture'],
        href: coreItemPath('decisions', 'tsx-articles-vs-core-workbench'),
        evidence: ['separate /lab/blog and /lab/core routes', 'route-scoped sidebar', 'core item detail pages'],
        units: [
          '블로그: 도메인 지식, 개념 설명, 긴 코드 리딩을 보관한다.',
          '코어: 현재 재사용 가능한 작업 단위와 그 검증 증거를 추적한다.',
          '랩 개요: 둘의 관계와 작업 흐름을 한 화면에서 설명한다.',
        ],
        notes: [
          {
            title: '결정',
            body: '같은 글 목록 안에 학습 글과 작업 산출물을 섞으면 방문자가 무엇을 봐야 하는지 헷갈린다. 그래서 블로그는 읽는 공간, 코어는 실행 단위 공간으로 나눴다.',
          },
          {
            title: '결과',
            body: '검증 실천 글은 블로그 그룹에서 제거하고 코어 Verification Practice로 옮긴다. 기존 레거시 링크는 코어 상세 페이지로 redirect해 끊어진 링크를 만들지 않는다.',
          },
        ],
      },
    ],
  },
];

function isPublishedCoreItem(item: CoreItem) {
  return Boolean(item.href?.startsWith(CORE_ROOT) && !blogBackedCoreSlugs.has(item.slug ?? ''));
}

export const publishedCoreTracks: CoreTrack[] = coreTracks
  .map((track) => ({
    ...track,
    items: track.items.filter(isPublishedCoreItem),
  }))
  .filter((track) => track.items.length > 0);

export function getCoreTrack(slug: string) {
  return publishedCoreTracks.find((track) => track.slug === slug);
}

export function coreItemSlug(item: CoreItem) {
  return item.slug ?? item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export function getCoreItem(trackSlug: string, itemSlug: string) {
  return getCoreTrack(trackSlug)?.items.find((item) => coreItemSlug(item) === itemSlug);
}
