import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { FeedFailureViz, HeatPathViz } from "./viz/ModernPowerCoolingViz";
const ENERGY="https://www.energystar.gov/products/spec/energy_star_computer_servers_version_4_0_pd";
const PUE="https://www.thegreengrid.org/node/372";
export default function ModernArticle(){return <article className="space-y-14">
<section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">서버 전력·냉각을 계산하는 순서</p><h2 className="text-3xl font-bold tracking-tight">TDP를 더하는 대신 wall power를 재고, 그 에너지가 rack 밖으로 빠져나가는 전체 경로를 설계한다</h2></header><p className="text-lg leading-8 text-foreground/90">
            CPU·GPU TDP(thermal design power)는 부품 냉각 설계의 입력이지 서버 콘센트에서 항상 소비하는 전력이 아닙니다. 예제 24시간 accelerator
            작업의 idle, sustained, burst와 p95 wall power를 실제 chassis에서 측정하고 A/B feed 하나와 fan 하나를 잃은 상태에서도 작업이
            지속되는지 확인합니다.
          </p><p>전력은 에너지의 시간당 전달률이며 1W=1J/s입니다. 정상 동작하는 서버가 소비한 전기 에너지는 fan을 포함해 거의 모두 실내 열로 바뀌므로, 전원과 냉각은 같은 budget의 두 면입니다. GPU workload·power 비교는 <a href="/gpu/hw-gpu-comparison#release-gate" className="text-primary hover:underline">GPU 조달 정본</a>을 재사용합니다.</p><HeatPathViz/><ContentBoundary article="hw-power-cooling"/></section>
<section id="power-heat" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Input power와 heat</p><h2 className="mt-2 text-2xl font-bold">Nameplate·TDP·실측 wall power의 역할을 구분한다</h2></header><p>Nameplate는 안전·공급 설계를 위한 최대 rating, component TDP는 해당 부품의 thermal design input, wall power는 특정 workload에서 PSU 입력에 실제로 들어간 값입니다. PSU loss와 fan, memory, drive도 wall measurement에 들어갑니다. 같은 firmware·power cap·ambient에서 idle, median, p95와 짧은 burst를 모두 기록해야 합니다.</p><ExplainedFormula question="서버가 방에 더하는 열 부하는 어느 정도일까?" idea={<>장시간 평균에서 서버 경계를 나가는 유용한 비열 에너지가 거의 없다고 보면 입력 전력이 같은 크기의 heat rate로 바뀝니다.</>} formula={String.raw`\dot Q_{room}\approx P_{server,input}`}
annotatedFormula={String.raw`\underbrace{\dot Q_{room}\approx P_{server,input}}_{\text{서버 입력 전력 계산}}`}
operations={[
  { expression: String.raw`\dot Q_{room}\approx P_{server,input}`, annotation: ["서버 입력 전력이(가) 식의 결과에 기여하는 방식을","계산합니다.","장시간 평균에서 서버 경계를 나가는 유용한 비열 에너지가 거의","없다고 보면 입력 전력이 같은 크기의 heat rate로"] },
]} terms={[{symbol:String.raw`\dot Q_{room}`,name:"실내 heat rate",description:"서버에서 방으로 전달되는 열 에너지율이며 단위는 J/s=W입니다."},{symbol:"P_{server,input}",name:"서버 입력 전력",description:"PDU 또는 calibrated meter에서 측정한 active power W입니다."}]} assumptions={["Steady averaging interval이며 배터리 충전·기계적 출력·외부로 직접 나가는 에너지는 작다고 봅니다.","측정 기준은 server inlet이며 facility loss는 포함하지 않습니다."]} interpretation="Wall input이 지속 2kW면 room heat load도 대략 2kW입니다. Component TDP 합이나 PSU 정격만으로 이 값을 대신하면 안 됩니다."/><div id="paper-energy-star-power"><CitationBlock type="paper" citeKey={1} source="ENERGY STAR Computer Servers Version 4.0 · 2023-04-12" href={ENERGY}><p><strong>문제:</strong> Server energy·performance를 공통 category와 test method로 보고합니다.</p><p><strong>핵심 기여:</strong> Active/idle efficiency와 power reporting의 표준 측정 경계를 제공합니다.</p><p><strong>중요 가정:</strong> Version 4.0 scope, eligible configuration과 SERT revision을 고정합니다.</p><p><strong>근거 범위:</strong> ENERGY STAR computer-server certification methodology입니다.</p><p><strong>일반화 금지:</strong> 인증값이나 idle power가 target accelerator workload의 p95 wall power·열 부하를 대신하지 않습니다.</p></CitationBlock></div></section>
<section id="rack-power" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Rack electrical redundancy</p><h2 className="mt-2 text-2xl font-bold">정상 합계가 아니라 한 feed를 잃은 뒤 남는 capacity를 계산한다</h2></header><FeedFailureViz/><p>
            Dual PSU를 A/B PDU에 나눠 꽂아도 두 feed가 같은 upstream breaker·UPS에 묶이면 독립 failure domain이 아닙니다. Voltage,
            current, power factor, phase, connector와 jurisdiction별 continuous-load rule을 시설 엔지니어와 확인합니다. 자동 전환
            때 PSU efficiency와 inrush, transient도 측정합니다.
          </p><ExplainedFormula question="한 feed가 사라진 상태에서도 rack workload가 유지되는가?" idea={<>남은 feed·PDU·UPS·냉각 경로 중 가장 작은 허용 capacity에서 rack p95 실측 부하를 뺍니다.</>} formula={String.raw`H_{N-1}=P_{remaining,allowed}-P_{rack,p95}`}
annotatedFormula={String.raw`H_{N-1}=\underbrace{P_{remaining,allowed}-P_{rack,p95}}_{\text{남은 허용 capacity 계산}}`}
operations={[
  { expression: String.raw`P_{remaining,allowed}-P_{rack,p95}`, annotation: ["남은 허용 capacity이(가) 식의 결과에 기여하는 방식을","계산합니다.","남은 feed·PDU·UPS·냉각 경로 중 가장 작은 허용","capacity에서 rack p95 실측 부하를 뺍니다."] },
]} terms={[{symbol:"H_{N-1}",name:"N−1 headroom",description:"한 전원 경로 상실 뒤 남는 허용 W입니다."},{symbol:"P_{remaining,allowed}",name:"남은 허용 capacity",description:"Breaker·PDU·UPS·cable·cooling limit 중 최소값입니다."},{symbol:"P_{rack,p95}",name:"Rack p95 부하",description:"고정 workload trace에서 측정한 95백분위 active power입니다."}]} assumptions={["A/B upstream failure domain과 보호장치 규칙을 실제 single-line diagram으로 확인합니다.","Failover transient와 phase imbalance를 별도 시험합니다."]} interpretation="남은 허용 capacity 12kW, p95 10.5kW면 headroom은 1.5kW입니다. 양수라는 사실만으로 transient trip이나 cooling 지속을 보장하지 않습니다."/></section>
<section id="cooling-path" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Cooling path</p><h2 className="mt-2 text-2xl font-bold">Chip junction에서 facility heat rejection까지 막힌 구간을 찾는다</h2></header><p>공랭은 heatsink와 fan이 열을 room air로, direct liquid cooling은 cold plate와 coolant loop로 옮깁니다. 침지 역시 열교환기와 facility water/air 경계가 필요합니다. 방법 이름보다 chip temperature, inlet 상태, flow, pressure, leak detection, fan/pump failure와 facility-side capacity를 같은 trace에서 확인합니다.</p><ExplainedFormula question="주어진 온도 상승으로 heat를 운반하려면 유체가 얼마나 흘러야 할까?" idea={<>유체가 단위 시간에 운반하는 질량에 비열과 inlet/outlet 온도차를 곱해 heat rate와 맞춥니다.</>} formula={String.raw`\dot Q=\dot m\,c_p\,\Delta T`}
annotatedFormula={String.raw`\dot Q=\underbrace{\dot m\,c_p\,\Delta T}_{\text{변화량 계산}}`}
operations={[
  { expression: String.raw`\dot m\,c_p\,\Delta T`, annotation: ["인접한 level의 차이를 남겨 변화량을 계산합니다.","유체가 단위 시간에 운반하는 질량에 비열과","inlet/outlet 온도차를 곱해 heat rate와","맞춥니다."] },
]} terms={[{symbol:String.raw`\dot Q`,name:"운반 heat rate",description:"유체가 제거하는 열의 W=J/s입니다."},{symbol:String.raw`\dot m`,name:"질량 유량",description:"초당 흐르는 유체 질량 kg/s입니다."},{symbol:"c_p",name:"정압 비열",description:"1kg을 1K 올리는 데 필요한 J/(kg·K)이며 유체·상태에 따라 달라집니다."},{symbol:String.raw`\Delta T`,name:"온도 상승",description:"Outlet minus inlet의 K이며 같은 차이값은 °C와 같습니다."}]} assumptions={["Steady single-phase flow, 균일한 bulk inlet/outlet과 알려진 cp를 가정합니다.","좌표계는 유체 흐름 방향이며 누설·상변화·국부 hotspot은 별도입니다."]} interpretation="2kW를 cp=1005J/(kg·K), ΔT=10K인 공기가 운반하려면 약 0.199kg/s가 필요합니다. Fan CFM으로 바꾸려면 현장 공기 밀도가 더 필요하며 이 식은 chip-to-sink thermal resistance를 보장하지 않습니다."/></section>
<section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">전력·온도·throttle·작업 결과를 같은 timestamp로 묶는다</h2></header><p>Ambient/inlet, workload revision, firmware, fan/pump policy, power cap과 meter 위치를 pin합니다. Idle→sustained→burst warm-up 뒤 wall power, PDU current, component temperature, clocks, throttling, fan/pump와 valid work/s를 동기화합니다. 한 feed·PSU·fan/pump를 잃고 alarm, graceful power cap, SLO와 복구를 확인하며 leak·over-temperature·sensor disagreement에서는 fail-safe 동작을 요구합니다. 실패하면 이전 cap과 rack population으로 rollback합니다.</p><ExplainedFormula question="Facility energy metric인 PUE는 무엇을 말하고 무엇을 말하지 않을까?" idea={<>같은 기간 전체 data-center energy를 IT equipment energy로 나눠 facility overhead를 봅니다.</>} formula={String.raw`PUE=\frac{E_{facility}}{E_{IT}}`}
annotatedFormula={String.raw`PUE=\underbrace{\frac{E_{facility}}{E_{IT}}}_{\text{기준량당 비율}}`}
operations={[
  { expression: String.raw`\frac{E_{facility}}{E_{IT}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","같은 기간 전체 data-center energy를 IT","equipment energy로 나눠 facility","overhead를 봅니다."] },
]} terms={[{symbol:"PUE",name:"Power usage effectiveness",description:"Facility energy가 IT energy의 몇 배인지 나타내는 무차원 비율입니다."},{symbol:"E_{facility}",name:"전체 facility energy",description:"IT와 cooling·power distribution 등 같은 기간 site energy입니다."},{symbol:"E_{IT}",name:"IT equipment energy",description:"정의된 IT measurement point에서 같은 기간의 energy입니다."}]} assumptions={["분자·분모의 경계와 동일 기간·energy source를 공개합니다.","연간 energy와 순간 power ratio를 섞지 않습니다."]} interpretation="PUE 1.3은 facility가 IT energy의 1.3배를 썼다는 뜻입니다. Server 자체의 compute efficiency, 탄소 집약도나 workload quality를 말하지 않습니다."/><div id="paper-pue"><CitationBlock type="paper" citeKey={2} source="The Green Grid · Power Usage Effectiveness definition" href={PUE}><p><strong>문제:</strong> Data-center infrastructure energy overhead를 공통 ratio로 표현합니다.</p><p><strong>핵심 기여:</strong> Total facility energy를 IT equipment energy로 나누는 PUE 경계를 정의합니다.</p><p><strong>중요 가정:</strong> Measurement point, 기간과 포함 energy source를 함께 보고합니다.</p><p><strong>근거 범위:</strong> Facility-level energy efficiency metric입니다.</p><p><strong>일반화 금지:</strong> PUE는 server efficiency, useful work, carbon·water impact나 reliability의 단독 지표가 아닙니다.</p></CitationBlock></div></section>
</article>}
