import ExplainedFormula from "@/components/ui/explained-formula"; import { CitationBlock } from "@/components/ui/citation-block";
const Flow=()=> <figure data-viz="extension-field-flow" className="not-prose rounded-xl border border-border bg-card p-5"><div className="grid gap-3 sm:grid-cols-4">{["Prime field","Irreducible quotient","Tower basis","Frobenius · pairing"].map((x,i)=><div key={x} className="rounded-lg border border-border bg-background p-4"><b className="text-xs text-primary">0{i+1}</b><p className="mt-2 text-sm font-semibold">{x}</p></div>)}</div></figure>;
export default function ModernArticle(){return <article className="space-y-14"><section id="overview" className="space-y-5"><h2 className="text-3xl font-bold">Extension field: 새 root를 붙여도 field 법칙을 지키는 방법</h2><p className="text-lg leading-8">F₃에는 X²+1의 root가 없습니다. 이 irreducible polynomial을 0으로 두고 α²=2인 새 원소 α를 붙이면 모든 원소를 a+bα로 표현하는 9원소 field가 됩니다.</p><Flow/></section><section id="minimal-polynomial" className="space-y-5"><h2 className="text-2xl font-bold">Minimal polynomial이 basis 길이를 정한다</h2><ExplainedFormula question="왜 degree d polynomial이 d개 basis elements를 만드는가?" idea={<>Polynomial division의 remainder는 degree d보다 작고 irreducibility가 nonzero element inverse를 보장합니다.</>} formula={String.raw`F(\alpha)\cong F[X]/(m_\alpha),\qquad [F(\alpha):F]=\deg m_\alpha=d`}
annotatedFormula={String.raw`F(\alpha)\cong F[X]/(m_\alpha),\qquad [F(\alpha):F]=\underbrace{\deg m_\alpha=d}_{\text{Extension degree 계산}}`}
operations={[
  { expression: String.raw`\deg m_\alpha=d`, annotation: ["Extension degree이(가) 식의 결과에 기여하는","방식을 계산합니다.","Polynomial division의 remainder는","degree d보다"] },
]} terms={[{symbol:"m_α",name:"Minimal polynomial",description:"α를 root로 갖는 monic irreducible polynomial입니다."},{symbol:"d",name:"Extension degree",description:"Basis 1,α,…,α^(d−1)의 길이입니다."}]} assumptions={["mα는 F[X]에서 irreducible입니다.","α는 mα의 residue class입니다."]} interpretation="F3에서 X²+1은 0,1,2 어느 값에서도 0이 아니므로 irreducible이고 basis는 1,α입니다. X²−1은 reducible이라 zero divisors가 생깁니다."/></section><section id="tower" className="space-y-5"><h2 className="text-2xl font-bold">Tower degree는 곱해진다</h2><p>
            K⊂L⊂M이면 [M:K]=[M:L][L:K]입니다. 2차 extension 위 3차 extension은 degree 6이고 이 theorem이 Fp²→Fp⁶→Fp¹²
            coefficient 수를 설명합니다.
          </p></section><section id="frobenius" className="space-y-5"><h2 className="text-2xl font-bold">Frobenius는 profile을 검사하고 빠르게 계산한다</h2><p>
            Fp^k에서 x↦x^p를 k번 적용하면 x로 돌아옵니다. Basis별 coefficient table은 이 automorphism을 빠르게 실행하지만
            polynomial·non-residue·basis order가 달라진 뒤에는 같은 table을 재사용할 수 없습니다.
          </p></section><section id="release" className="space-y-5"><h2 className="text-2xl font-bold">Release gate</h2><p>
            p와 irreducible polynomials, non-residues를 pin합니다. Tower degrees와 basis/serialization, Frobenius
            cycle도 함께 pin하고 inverse와 pairing vectors까지 고정합니다.
          </p><div id="paper-finite-fields"><CitationBlock source="Lidl & Niederreiter · Finite Fields" citeKey={1} href="https://doi.org/10.1017/CBO9780511525926"><p><b>문제:</b> Finite extensions의 구조를 정립합니다.</p><p><b>기여:</b> Minimal polynomial·tower·Frobenius theorem을 체계화합니다.</p><p><b>전제:</b> 각 theorem의 finite-field hypotheses를 사용합니다.</p><p><b>근거 범위:</b> 이 글의 수학적 정본입니다.</p><p><b>말하지 않는 것:</b> BN254 layout이나 성능은 규정하지 않습니다.</p></CitationBlock></div></section></article>}
