import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["첫 번째 표","두 번째 표","평균의 차이"];
const details=["A 두 개에 짧은 0을 붙입니다. 0·0·10·11의 총길이는 6자리, 네 글자의 평균은 1.5자리입니다.","같은 네 글자에 다른 표를 씁니다. 10·10·11·0의 총길이는 7자리, 평균은 1.75자리입니다. A에서 2자리를 더 쓰고 C에서 1자리를 아낍니다.","원래 비중 A 1/2, B와 C 각 1/4로 길이를 평균합니다. 표를 바꾸면서 네 글자당 1자리, 한 글자당 0.25자리가 늘었습니다."];
export default function CodeCostViz(){const c=useAnimatedScenes(3);const codes=c.active===0?["0","0","10","11"]:["10","10","11","0"];return <VizFrame eyebrow="같은 네 관측" title="A가 두 번 나오는 기록에 두 표를 적용한다" description="글자와 순서는 고정하고 그 글자에 붙일 코드만 바꿉니다." note="A·B·C의 원래 비중을 1/2·1/4·1/4로 둔 가정입니다. 코드를 미리 아는 수신자는 두 표 모두 모호함 없이 해독할 수 있습니다.">
<div data-viz-canvas tabIndex={0} role="group" aria-label="두 코드의 비용 비교" onKeyDown={c.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary">
<svg viewBox="0 0 320 270" className="mx-auto block w-full max-w-[450px]" role="img" aria-label={details[c.active]}>{c.active<2?<><text x="45" y="22" textAnchor="middle" fontSize="13" fill="currentColor">관측</text><text x="155" y="22" textAnchor="middle" fontSize="13" fill="currentColor">붙인 코드</text><text x="265" y="22" textAnchor="middle" fontSize="13" fill="currentColor">길이</text>{["A","A","B","C"].map((v,i)=><g key={i}><circle cx="45" cy={58+i*45} r="16" fill="none" stroke="currentColor"/><text x="45" y={63+i*45} textAnchor="middle" fontSize="15" fill="currentColor">{v}</text><path d={`M68 ${58+i*45} H108 l-5 -4 m5 4 l-5 4`} fill="none" stroke="currentColor"/>{codes[i].split('').map((bit,j)=><g key={j}><rect x={131+j*27} y={43+i*45} width="24" height="30" rx="3" fill="currentColor" fillOpacity=".1" stroke="currentColor"/><text x={143+j*27} y={63+i*45} textAnchor="middle" fontSize="15" fill="currentColor">{bit}</text></g>)}<text x="265" y={63+i*45} textAnchor="middle" fontSize="15" fill="currentColor">{codes[i].length}</text></g>)}<text x="160" y="247" textAnchor="middle" fontSize="14" fill="currentColor">{c.active===0?'총 6자리 / 4글자 = 1.5자리':'총 7자리 / 4글자 = 1.75자리'}</text></>:<><text x="160" y="28" textAnchor="middle" fontSize="14" fill="currentColor">글자당 평균 길이</text><line x1="40" x2="40" y1="55" y2="206" stroke="currentColor"/>{[1.5,1.75].map((v,i)=><g key={v}><rect x="40" y={70+i*65} width={v*110} height="30" fill="currentColor" fillOpacity={i===0?.15:.3} stroke="currentColor"/><text x={48+v*110} y={90+i*65} fontSize="14" fill="currentColor">{v}</text><text x="45" y={119+i*65} fontSize="12" fill="currentColor">{i===0?'첫 번째 표':'두 번째 표'}</text></g>)}<text x="160" y="239" textAnchor="middle" fontSize="14" fill="currentColor">추가 평균 길이 = 1.75 − 1.5 = 0.25</text></>}</svg>
<p className="min-h-[8rem] text-sm leading-7" aria-live="polite">{details[c.active]}</p><AnimatedSceneControls {...c} labels={labels}/></div></VizFrame>;}
