import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { Risc0ReceiptViz } from "./Risc0ReceiptViz";

const OVERVIEW = "https://github.com/risc0/risc0/blob/1cc70cf05033a79ebc90f07c679cb4bd1cd301b9/website/api/zkvm/zkvm-overview.md";
const RECEIPT = "https://github.com/risc0/risc0/blob/1cc70cf05033a79ebc90f07c679cb4bd1cd301b9/risc0/zkvm/src/receipt.rs";
const CLAIM = "https://github.com/risc0/risc0/blob/1cc70cf05033a79ebc90f07c679cb4bd1cd301b9/risc0/zkvm/src/claim/receipt.rs";

export default function ModernRisc0() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Fibonacci guest가 n=10의 결과 55를 공개하기</p><h2 className="text-3xl font-bold tracking-tight">RISC Zero의 핵심은 “Rust를 증명한다”가 아니라 고정된 guest ELF의 실행 claim과 journal을 receipt로 검증하는 것이다</h2></header><p className="text-lg leading-8 text-foreground/90">Host는 입력 n=10을 executor에 주고 guest는 RISC-V zkVM에서 실행해 55를 journal에 commit합니다. Guest Rust source가 직접 statement가 되는 것은 아닙니다. Build가 만든 ELF와 ImageID, execution session, receipt claim, 공개 journal이 차례로 연결됩니다. <a className="text-primary hover:underline" href="/crypto/stark">STARK 정본</a>은 trace·AIR·FRI를 소유하며, 이 글은 RISC Zero의 project-specific artifact와 receipt boundary만 설명합니다.</p><Risc0ReceiptViz /><ContentBoundary article="risc0" /></section>

    <section id="method-artifact" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Method artifact</p><h2 className="mt-2 text-2xl font-bold">Compiler/toolchain/profile을 고정한 guest ELF에서 ImageID를 만들고 verifier가 기대할 method로 배포한다</h2></header><p>Source가 같아도 compiler, target, features나 linker가 바뀌면 ELF bytes와 ImageID가 달라질 수 있습니다. Method artifact에는 source revision, RISC-V target/toolchain, build flags, ELF digest, ImageID, input/journal schema와 receipt format version을 기록합니다. Verifier가 ImageID를 configuration 밖에서 임의로 받게 두면 다른 guest의 정상 receipt를 잘못 승인할 수 있습니다.</p><ExplainedFormula question="Method identity는 무엇을 결속해야 할까?" idea={<>실제 실행되는 ELF와 재현에 필요한 build profile을 함께 digest receipt로 고정합니다.</>} formula={String.raw`A_M=H(d_{src}\|d_{tool}\|d_{cfg}\|H(ELF)\|ImageID)`} terms={[{symbol:"A_M",name:"Method artifact id",description:"배포한 guest method의 재현 가능한 식별자입니다."},{symbol:"d_{src}",name:"Source revision",description:"Guest와 dependency lock의 pinned revision입니다."},{symbol:"d_{tool}",name:"Toolchain digest",description:"Compiler, target과 linker toolchain identity입니다."},{symbol:"d_{cfg}",name:"Build configuration",description:"Features와 flags의 canonical digest입니다."},{symbol:"ELF",name:"Guest executable",description:"zkVM executor가 읽는 RISC-V binary입니다."},{symbol:"ImageID",name:"Expected method identity",description:"Verifier가 receipt와 대조할 RISC Zero image identifier입니다."}]} assumptions={["각 field는 length-delimited canonical encoding을 사용합니다.","ImageID 계산의 정확한 domain/algorithm은 pinned implementation을 따르며 이 개념식이 대체하지 않습니다."]} interpretation="Source commit이 같아도 compiler profile이 달라 ELF가 바뀌면 새 artifact와 ImageID를 배포해야 합니다." /><div id="paper-risc0-overview"><CitationBlock type="code" citeKey={1} source="RISC Zero zkVM overview · v3.0.6 commit 1cc70cf" href={OVERVIEW}><p><strong>문제:</strong> Guest program build부터 execution, proving, verification까지 사용자가 따라갈 lifecycle이 필요합니다.</p><p><strong>핵심 기여:</strong> Pinned official documentation은 Rust guest→ELF, executor session, prover receipt, ImageID verification과 journal 공개 경계를 설명합니다.</p><p><strong>중요 가정:</strong> RISC Zero v3.0.6 toolchain/API와 같은 receipt model을 사용합니다.</p><p><strong>근거 범위:</strong> 해당 release의 zkVM user lifecycle입니다.</p><p><strong>일반화 금지:</strong> 임의 zkVM의 artifact format, 고정 proof size나 성능을 보장하지 않습니다.</p></CitationBlock></div></section>

    <section id="session-segments" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Execution session</p><h2 className="mt-2 text-2xl font-bold">긴 RISC-V 실행을 segments로 나눠도 마지막 상태와 다음 시작 상태가 정확히 이어져야 한다</h2></header><p>Session은 단순 실행 로그가 아니라 guest program, input, exit, cycle/segment accounting과 public journal을 묶는 실행 receipt입니다. Segment를 병렬로 증명할 수 있어도 실행 의미가 병렬이 되는 것은 아닙니다. 이전 segment의 post-state가 다음 segment의 pre-state와 같아야 하나의 순차 실행입니다.</p><ExplainedFormula question="Segments가 하나의 실행이라는 조건은 무엇인가?" idea={<>모든 인접 segment의 machine-state boundary를 같게 하고 cycle 수를 합칩니다.</>} formula={String.raw`s_i^{post}=s_{i+1}^{pre}\;(0\le i<k-1),\quad C=\sum_{i=0}^{k-1}c_i`} terms={[{symbol:"s_i^{post}",name:"Post-state",description:"i번째 segment 종료의 machine-state commitment입니다."},{symbol:"s_{i+1}^{pre}",name:"Next pre-state",description:"다음 segment 시작 state commitment입니다."},{symbol:"k",name:"Segment count",description:"이번 session을 나눈 segment 수입니다."},{symbol:"c_i",name:"Segment cycles",description:"i번째 segment의 admitted cycle count입니다."},{symbol:"C",name:"Session cycles",description:"전체 guest execution cycle 수입니다."}]} assumptions={["같은 ELF/ImageID, input and execution semantics를 사용합니다.","State equality는 hash collision resistance와 정확한 serialization에 의존합니다."]} interpretation="세 segment가 10k, 10k, 3k cycles면 C=23k입니다. 중간 state가 하나라도 다르면 proof를 join하면 안 됩니다." /></section>

    <section id="receipt-claim" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Receipt claim</p><h2 className="mt-2 text-2xl font-bold">Seal의 무결성과 expected ImageID·exit·journal이 표현하는 claim을 둘 다 검증한다</h2></header><p>Receipt는 journal과 seal을 포함합니다. <code>verify(image_id)</code>는 seal만 확인하는 것이 아니라 expected ImageID와 정상 종료, journal digest가 들어간 expected ReceiptClaim을 만들고 실제 claim digest와 비교합니다. Journal은 공개 출력이므로 비밀 입력을 그대로 commit하면 영지식이 그것을 다시 숨겨 주지 않습니다.</p><ExplainedFormula question="Verifier가 승인하는 statement를 어떻게 표현할까?" idea={<>Expected method, 정상 종료, 공개 journal과 assumptions를 tagged claim digest로 결속합니다.</>} formula={String.raw`d_C=H_{claim}(ImageID\|exit\|H(journal)\|d_{assumptions})`} terms={[{symbol:"d_C",name:"Receipt claim digest",description:"Verifier가 receipt에서 기대하는 claim identity입니다."},{symbol:"H_{claim}",name:"Tagged claim hash",description:"ReceiptClaim encoding과 domain separation을 적용한 digest입니다."},{symbol:"ImageID",name:"Method identity",description:"허용된 guest ELF의 image identifier입니다."},{symbol:"exit",name:"Exit condition",description:"정상 종료 등 admitted final status입니다."},{symbol:"journal",name:"Public journal",description:"Guest가 공개하기로 commit한 bytes입니다."},{symbol:"d_{assumptions}",name:"Assumptions digest",description:"Composition에서 참조하는 unresolved/resolved assumptions입니다."}]} assumptions={["정확한 ReceiptClaim field order, tags와 pruning은 pinned source를 따릅니다.","Receipt integrity 검증과 expected claim comparison을 모두 성공해야 합니다."]} interpretation="Fibonacci 결과를 55 대신 54로 바꾸거나 다른 ImageID를 넣으면 expected claim digest가 달라져 검증이 실패해야 합니다." /><div id="paper-risc0-receipt"><CitationBlock type="code" citeKey={2} source="RISC Zero receipt.rs · v3.0.6 commit 1cc70cf" href={RECEIPT}><p><strong>문제:</strong> Receipt seal이 어떤 method와 공개 결과를 증명하는지 verifier가 확인해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 receipt.verify가 expected ReceiptClaim::ok와 pruned journal digest를 만들고 claim digest를 비교하는 경계를 보여 줍니다.</p><p><strong>중요 가정:</strong> v3.0.6 verifier parameters, receipt variants와 hash implementation을 사용합니다.</p><p><strong>근거 범위:</strong> RISC Zero receipt integrity/claim verification code입니다.</p><p><strong>일반화 금지:</strong> Guest business logic, journal privacy나 모든 recursion assumption의 유효성을 자동 보장하지 않습니다.</p></CitationBlock></div><div id="paper-risc0-claim"><CitationBlock type="code" citeKey={3} source="RISC Zero ReceiptClaim · v3.0.6 commit 1cc70cf" href={CLAIM}><p><strong>문제:</strong> 실행 전후 state, exit와 output을 stable proof statement로 표현해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned type은 pre/post state, exit code, input/output 및 journal·assumptions의 claim 구조를 정의합니다.</p><p><strong>중요 가정:</strong> Canonical digest/serialization과 해당 release의 claim semantics를 따릅니다.</p><p><strong>근거 범위:</strong> ReceiptClaim data model입니다.</p><p><strong>일반화 금지:</strong> Claim type만으로 guest correctness나 external assumption availability가 입증되지는 않습니다.</p></CitationBlock></div></section>

    <section id="release-gate" className="space-y-6"><header><p className="text-sm font-semibold text-primary">04 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Native execution parity 뒤 wrong image·journal·exit·segment·seal을 거절하고 verified cycles/s를 측정한다</h2></header><p>n=10→55 positive fixture와 wrong result, wrong ImageID, nonzero/pause exit, corrupted seal, missing/reordered segment, journal schema/version mismatch, limit 초과를 넣습니다. Native reference output과 journal bytes가 맞고 독립 verifier가 승인한 뒤 compile/load/execute/prove/verify, cycles, segments, receipt bytes와 peak memory를 기록합니다. 실패하면 이전 method artifact와 verifier allowlist로 rollback합니다.</p><ExplainedFormula question="증명기가 실제로 처리한 유효 실행량은 어떻게 측정할까?" idea={<>검증된 sessions의 admitted cycles만 end-to-end wall time으로 나눕니다.</>} formula={String.raw`Q_C=\frac{\sum_{j\in V}C_j}{T_{build}+T_{exec}+T_{prove}+T_{verify}}`} terms={[{symbol:"Q_C",name:"Verified cycle throughput",description:"초당 검증된 guest cycles입니다."},{symbol:"V",name:"Verified sessions",description:"Expected ImageID와 journal로 승인된 session 집합입니다."},{symbol:"C_j",name:"Session cycles",description:"검증된 j번째 실행의 cycle count입니다."},{symbol:"T_{build}",name:"Artifact preparation",description:"보고 조건에 포함하기로 한 build/load 시간입니다."},{symbol:"T_{exec}",name:"Execution",description:"Guest session 생성 시간입니다."},{symbol:"T_{prove}",name:"Proving",description:"Segments와 receipt 생성 시간입니다."},{symbol:"T_{verify}",name:"Verification",description:"Receipt claim 승인 시간입니다."}]} assumptions={["같은 artifact/input distribution/backend와 cold/warm 조건을 비교합니다.","Failed receipts의 cycles는 분자에 넣지 않으며 실패 자체는 release를 막습니다."]} interpretation="두 sessions가 각각 23k cycles이고 전체가 0.1초면 460k verified cycles/s입니다. 이 수치는 다른 guest로 일반화할 수 없습니다." /><aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> ELF/ImageID, build identity, session/segment continuity, cycles, claim fields, journal privacy, verification, negative fixtures, 측정과 rollback을 이 글만으로 답할 수 있습니다.</aside></section>
  </article>;
}
