import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import FeedbackViz from "./feedback-gain-and-stability/viz/FeedbackViz";

/** Invented linear two-pole A(s)=100/[(1+s/10)(1+s/100)], β=.1 or .5. */
export default function FeedbackGainAndStabilityArticle() {
  return <div className="space-y-16">
    <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">출력을 조금 돌려보내면 왜 목표에 더 가까워질까요?</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
      <p className="text-lg leading-8">입력 1 V를 10배로 키우려는 가상 증폭기를 떠올려 봅시다. 증폭기 자체의 직류 이득은 100배이지만, 출력의 10%를 입력에서 빼고 남은 차이를 증폭하면 출력은 9.09 V가 됩니다. 되돌아온 0.909 V 때문에 증폭기가 실제로 보는 차이는 약 0.091 V뿐입니다. 0.091 V×100≈9.09 V로 서로 맞습니다.</p>
      <p className="leading-7">출력을 보고 입력의 오차를 고치는 이 연결이 <strong>음의 되먹임</strong>입니다. ‘100배 증폭기’가 ‘약 10배 회로’가 되는 데 쓰지만, 되돌아오는 신호가 너무 늦으면 고치는 방향이 어긋날 수 있습니다. 같은 증폭기를 주파수까지 살펴 이득과 안정성을 함께 계산하겠습니다. 본문의 증폭기 숫자는 교육용 가정이며 특정 제품의 측정값이 아닙니다.</p>
      <p className="leading-7"><em>되먹임을 더 강하게 걸었을 때 이득 정확도와 흔들림이 함께 어떻게 변하는지가 질문입니다.</em></p>
    </div></section>
    <section id="loop" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">되돌린 0.909 V를 빼고 남은 차이가 새 출력을 만듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
      <p className="leading-7">입력 r, 출력 y, 되돌리는 비율 β를 둡니다. 증폭기에 들어가는 오차는 e=r−βy이고, 증폭기는 y=Ae를 만듭니다. 둘을 합쳐 y=A(r−βy)를 정리하면 출력÷입력인 <strong>폐루프 이득</strong>은 A/(1+Aβ)입니다. Aβ는 한 바퀴 돌아온 비율인 <strong>루프 이득</strong>입니다. 직류에서 A=100·β=0.1이면 루프 이득은 10이고 폐루프 이득은 100/11≈9.09입니다.</p>
      <p className="leading-7">루프 이득이 아주 클 때만 폐루프 이득은 1/β=10에 가까워집니다. 여기서는 9.09이므로 목표 10과 약 9.1% 다릅니다. β를 0.5로 바꾸면 목표는 2, 실제는 100/51≈1.96입니다. 루프 이득이 50이라 오차 비율은 줄지만 얻는 출력 배율도 낮아집니다. 두 결과는 ‘되먹임을 강화하면 언제나 출력 전압이 커진다’는 추측과 반대입니다.</p>
      <p className="leading-7"><em>출력을 되돌리는 길은 목표 배율을 만들면서 증폭기가 바로잡을 오차도 정합니다.</em></p>
    </div><ExplainedFormula question="1 V를 넣고 출력의 10%를 되돌리면 몇 V가 나옵니까?" idea="출력에서 돌아온 몫을 입력에서 빼고, 남은 오차에 증폭기 이득을 곱한 값이 다시 출력이어야 합니다." formula={String.raw`\frac{y}{r}=\frac{A}{1+A\beta}`} annotatedFormula={String.raw`\underbrace{\frac{y}{r}}_{\text{폐루프 이득}}=\frac{A}{1+A\beta}`} operations={[{expression:String.raw`A\beta=100\times0.1=10`,annotation:"직류 루프 이득입니다."},{expression:String.raw`y/r=100/11\approx9.09`,annotation:"목표 10배에 가깝지만 정확히 10은 아닙니다."},{expression:String.raw`e=1-0.1(9.09)\approx0.091\,\mathrm V`,annotation:"100배 하면 다시 약 9.09 V입니다."}]} terms={[{symbol:"A",name:"증폭기 자체 이득",description:"가정한 직류 100배입니다."},{symbol:String.raw`\beta`,name:"되돌림 비율",description:"출력에서 입력의 빼는 단자로 돌아오는 몫입니다."},{symbol:"e",name:"오차 전압",description:"입력 r에서 돌아온 βy를 뺀 값입니다."}]} assumptions={["증폭기는 1 V 입력에 필요한 출력 전압을 공급 전원 범위에서 낼 수 있습니다.","직류 이득 100배와 β=0.1인 선형 음의 되먹임입니다."]} interpretation="입력 1 V의 출력은 9.09 V입니다. 무한한 루프 이득일 때의 10 V와 구분합니다." /><CitationBlock source="Texas Instruments / Burr-Brown, Jerald G. Graeme, ‘Feedback Plots Define Op Amp AC Performance’ (1991 발행), 1쪽" citeKey={1} href="https://www.ti.com/lit/an/sboa015/sboa015.pdf">원본 첫 쪽은 β를 출력에서 되돌아오는 비율로 두고 폐루프 이득 A/(1+Aβ), 루프 이득 Aβ와 큰 루프 이득의 1/β 근사를 제시합니다. 이 글의 A=100·1 V·β=0.1은 해당 문서의 제품 수치가 아닌 가정입니다.</CitationBlock></section>
    <section id="delay" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">두 번 늦는 증폭기를 같은 계산에 넣습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
      <p className="leading-7">실제 증폭기의 이득은 빠른 신호에서 줄고, 출력 변화도 늦습니다. 이를 살피려고 직류 이득 100에 두 개의 속도 경계, 10 rad/s와 100 rad/s를 넣은 <strong>가상 선형 증폭기</strong>를 씁니다. A(s)=100/[(1+s/10)(1+s/100)]입니다. 여기서 s=jω를 대입하면 앞 글처럼 각 주파수에서 이득의 크기와 각도 지연을 구할 수 있습니다. 이 두 경계는 특정 소자 모델에서 가져온 값이 아닙니다.</p>
      <p className="leading-7">첫 경계보다 빠르면 한 번 늦고, 두 번째 경계보다도 빠르면 더 늦습니다. 되돌리는 신호가 처음에는 출력 오류를 줄이지만, 지연이 커져 출력과 거의 반대 각도로 돌아오면 빼려고 한 연결이 오히려 흔들림을 키울 수 있습니다. ‘음의’는 배선의 빼기 부호이며, 모든 주파수에서 항상 안정이라는 보증은 아닙니다.</p>
      <p className="leading-7"><em>증폭기의 이득뿐 아니라 돌아오는 데 걸리는 각도도 한 바퀴 계산해야 합니다.</em></p>
    </div><CitationBlock source="Texas Instruments / Burr-Brown, Graeme, ‘Feedback Plots Define Op Amp AC Performance’, 1–2쪽" citeKey={2} href="https://www.ti.com/lit/an/sboa015/sboa015.pdf">공식 자료는 열린 증폭기 이득과 1/β 곡선의 만나는 위치, 추가 극이 더하는 위상 지연, 루프 이득이 −1에 가까울 때의 발진 조건을 설명합니다. 본문의 10·100 rad/s 두 극은 설명을 위해 만든 모델입니다.</CitationBlock></section>
    <section id="margin" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">한 바퀴 크기가 1인 곳에서 남은 각도를 셉니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
      <p className="leading-7">루프 이득 L=Aβ의 크기가 1, 즉 0 dB가 되는 속도를 <strong>교차 각주파수</strong>라 합니다. 이때 L의 각도가 −180°이면 한 바퀴 뒤 원래 빼야 할 신호가 같은 방향으로 보태지는 셈입니다. 각도 −180°까지 얼마나 남았는지를 <strong>위상 여유</strong>라고 부릅니다. 한 교차점의 선형 모델에서 β=0.1은 약 78.2 rad/s에 크기 1, 위상 약 −120.7°이므로 여유가 약 59.3°입니다.</p>
      <p className="leading-7">β를 0.5로 높이면 루프 이득이 더 커져 교차점이 약 212.6 rad/s로 오른쪽으로 갑니다. 그곳에서는 두 번째 지연까지 더 많이 쌓여 위상은 약 −152.1°, 남은 여유는 약 27.9°입니다. 같은 증폭기라도 되먹임 비율 때문에 교차 속도와 지연이 함께 바뀝니다. 두 경우 모두 이 가상 2극 선형 모델에서는 안정한 극을 갖지만, 여유가 작은 쪽은 변화 뒤 더 오래 흔들릴 수 있습니다.</p>
      <p className="leading-7"><em>‘되먹임이 더 세다’는 정적 이득의 이야기이고, ‘얼마나 흔들리나’는 교차점의 위상까지 본 이야기입니다.</em></p>
    </div><FeedbackViz /><ExplainedFormula question="β=0.1인 가상 2극 회로의 위상 여유는?" idea="|Aβ|=1인 속도를 찾고, 그때 두 지연 각도를 더해 −180°까지의 차이를 셉니다." formula={String.raw`\mathrm{PM}=180^\circ+\angle L(j\omega_x)`} annotatedFormula={String.raw`\underbrace{\mathrm{PM}}_{\text{위상 여유}}=180^\circ+\angle L(j\omega_x)`} operations={[{expression:String.raw`|L(j\omega_x)|=1`,annotation:"β=0.1이면 ωx≈78.2 rad/s입니다."},{expression:String.raw`\angle L(j\omega_x)\approx-120.7^\circ`,annotation:"10·100 rad/s 두 경계의 지연을 합합니다."},{expression:String.raw`\mathrm{PM}\approx59.3^\circ`,annotation:"−180°까지 약 59.3° 남았습니다."}]} terms={[{symbol:"L",name:"루프 이득",description:"복소 증폭기 이득 A(jω)에 β를 곱합니다."},{symbol:String.raw`\omega_x`,name:"크기 1 교차 속도",description:"|L|=1 또는 0 dB인 각주파수입니다."},{symbol:"PM",name:"위상 여유",description:"교차점에서 −180°까지 남은 각도입니다."}]} assumptions={["β는 주파수와 무관한 양수이고 한 번의 교차점을 갖는 가상 선형 2극 모델입니다.","공급 전압·포화·부하·추가 지연은 모델에 넣지 않았습니다."]} interpretation="β=0.1의 약 59.3°와 β=0.5의 약 27.9°는 가상 모델의 계산 결과이며 실제 증폭기의 안정성 등급은 아닙니다." /><CitationBlock source="Texas Instruments / Burr-Brown, Graeme, ‘Feedback Plots Define Op Amp AC Performance’, 2쪽" citeKey={3} href="https://www.ti.com/lit/an/sboa015/sboa015.pdf">원본 2쪽은 열린 이득·1/β의 교차와 −180°에 대한 위상 여유를 설명하고, 극이 추가되면 여유가 달라진다고 밝힙니다. 78.2·212.6 rad/s와 59.3°·27.9°는 본문 모델에서 직접 계산한 값입니다.</CitationBlock></section>
    <section id="limits" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">계산한 여유는 연결한 부하까지 확인해야 쓸 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert">
      <p className="leading-7">위상 여유는 선형 모델의 교차점 근처에서 흔들림을 가늠하는 수치입니다. 공급 전압이 모자라 출력이 포화되거나, 부하의 축전기가 새 지연을 만들거나, 측정에서 여러 교차점이 나타나면 이 두 숫자만으로 안정성을 선언할 수 없습니다. 실제 회로에서는 증폭기 데이터시트의 허용 부하·이득 조건과 연결한 회로의 루프 응답, 계단 입력 뒤의 흔들림을 함께 확인합니다.</p>
      <p className="leading-7">앞 글에서 저역 통과 RC의 −20 dB/dec를 그릴 때는 축전기 출력 자체를 봤습니다. 여기서는 <strong>출력에서 입력으로 다시 돌아온 한 바퀴</strong>의 크기와 위상을 봅니다. 둘 다 보드 선도를 쓰지만 측정하는 경로가 다릅니다. 증폭기·되먹임망·부하를 바꾸면 루프도 다시 그려야 합니다.</p>
      <p className="leading-7"><strong>읽고 나서 예측해 보세요.</strong> β=0.1의 목표 10배가 왜 실제 9.09배입니까? (답: 2절) β를 0.5로 올리면 교차점은 어느 쪽으로 갑니까? (답: 4절) 위상 여유 27.9°만으로 실제 제품이 반드시 발진한다고 말할 수 있습니까? (답: 4·5절)</p>
      <p className="leading-7"><Link to="/electronics/circuits/frequency-shaping-and-bode#plot">앞 글의 보드 눈금</Link>을 알고 나면 같은 가로축에서 이번에는 루프가 0 dB를 지나는 위치를 읽을 수 있습니다.</p>
    </div></section>
  </div>;
}
