import ContentBoundary from "@/components/articles/content-boundary";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import BulletproofsFlowViz from "./BulletproofsFlowViz";

export default function ModernBulletproofsArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">Committed witness의 range에서 시작하기</p><h2 className="text-3xl font-bold tracking-tight">w=4를 공개하지 않고 0≤w&lt;8과 3w=12를 함께 증명한다</h2></header><p className="text-lg leading-8 text-foreground/90">Public input은 x=3,y=12이고 witness는 w=4입니다. Prover는 random r로 Pedersen commitment V=wG+rH를 공개한 뒤, 같은 w가 3w=12를 만족하고 3-bit unsigned range 안에 있다는 proof를 만듭니다. Bulletproofs는 이 relation을 vector inner product로 바꾸고 trusted setup 없이 짧게 접습니다.</p><p>여기서 “짧다”는 proof의 group/field elements가 witness 길이에 logarithmic하다는 뜻입니다. Prover와 verifier가 처리하는 vector·MSM work, generator capacity, transcript와 range의 integer encoding은 별도 비용과 전제입니다.</p><aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> Commitment와 bit vector가 같은 w를 가리키도록 결속한 다음, inner-product argument(IPA)가 dimension만 절반씩 줄입니다.</aside><ContentBoundary article="bulletproofs"/><BulletproofsFlowViz/></section>
  <section id="inner-product" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Inner-product argument</p><h2 className="mt-2 text-2xl font-bold">좌우 cross terms를 먼저 commit하고 challenge로 vector를 접는다</h2></header><p>
            길이 n vector a,b와 generator vectors G,H의 commitment P가 inner product c=⟨a,b⟩와 일치한다는 relation을
            생각합니다. Prover는 좌·우 halves의 cross inner products를 담은 L,R을 먼저 보내고 verifier가 transcript challenge u를
            만든 뒤 vector와 generators를 u,u⁻¹ coefficient로 합칩니다.
          </p><ExplainedFormula question="한 IPA round는 길이 n relation을 어떻게 n/2 relation으로 바꾸는가?" idea={<>L,R이 좌우 cross terms를 commitment에 고정합니다. 그 뒤 challenge u를 받아 같은 coefficient로 witnesses와 반대 coefficient로 generators를 접으면 새 commitment가 같은 inner product relation을 보존합니다.</>} formula={String.raw`\mathbf a'=u\mathbf a_L+u^{-1}\mathbf a_R,\quad \mathbf b'=u^{-1}\mathbf b_L+u\mathbf b_R,\quad \mathbf G'=u^{-1}\mathbf G_L+u\mathbf G_R,\quad \mathbf H'=u\mathbf H_L+u^{-1}\mathbf H_R`}
  annotatedFormula={String.raw`\mathbf a'=\underbrace{u\mathbf a_L+u^{-1}\mathbf a_R,\quad \mathbf b'=u^{-1}\mathbf b_L+u\mathbf b_R,\quad \mathbf G'=u^{-1}\mathbf G_L+u\mathbf G_R,\quad \mathbf H'=u\mathbf H_L+u^{-1}\mathbf H_R}_{\text{Round challenge 계산}}`}
  operations={[
    { expression: String.raw`u\mathbf a_L+u^{-1}\mathbf a_R,\quad \mathbf b'=u^{-1}\mathbf b_L+u\mathbf b_R,\quad \mathbf G'=u^{-1}\mathbf G_L+u\mathbf G_R,\quad \mathbf H'=u\mathbf H_L+u^{-1}\mathbf H_R`, annotation: ["Round challenge이(가) 식의 결과에 기여하는","방식을 계산합니다.","L,R이 좌우 cross terms를 commitment에","고정합니다."] },
  ]} terms={[{symbol:"\\mathbf a_L,\\mathbf a_R",name:"Witness halves",description:"원래 witness vector의 좌우 절반입니다."},{symbol:"L,R",name:"Cross-term commitments",description:"Challenge 전에 cross inner products와 generators를 고정합니다."},{symbol:"u",name:"Round challenge",description:"L,R과 statement를 transcript에 넣은 뒤 얻습니다."},{symbol:"\\mathbf a',\\mathbf b'",name:"Folded witnesses",description:"길이가 절반인 다음 relation vector입니다."},{symbol:"\\mathbf G',\\mathbf H'",name:"Folded generators",description:"Commitment equality를 보존하는 새 basis입니다."}]} assumptions={["n은 profile이 정한 power of two이거나 의미가 고정된 zero padding을 사용합니다.","Prime-order group과 독립 generator vectors, DLP hardness를 사용합니다.","L,R·statement·generator/range profile을 흡수한 뒤 u를 생성합니다."]} interpretation="n=8이면 8→4→2→1로 세 rounds입니다. Proof에 남는 round elements는 logarithmic하지만 첫 vector와 verifier MSM의 총 work가 자동으로 logarithmic이 되지는 않습니다."/><p><strong>증명 아이디어:</strong> k rounds 뒤 dimension은 n/2ᵏ이므로 1이 되는 k는 log₂n입니다. 반례로 n=6을 아무 표시 없이 8로 pad하면 verifier가 원래 length를 모를 수 있으므로 transcript에 logical length와 padding rule을 binding해야 합니다.</p></section>
  <section id="range-proof" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Range proof와 aggregation</p><h2 className="mt-2 text-2xl font-bold">Booleanity와 weighted sum이 integer range를 만든다</h2></header><ExplainedFormula question="w=4가 3-bit unsigned range 안에 있다는 relation은 무엇인가?" idea={<>Secret bits가 각각 0 또는 1이고 powers-of-two weighted sum이 commitment 속 w와 같으면 가능한 값은 0부터 7뿐입니다.</>} formula={String.raw`\mathbf a_L=(a_0,a_1,a_2),\quad a_i(a_i-1)=0,\quad w=\langle\mathbf a_L,(1,2,4)\rangle=4`}
  annotatedFormula={String.raw`\mathbf a_L=\underbrace{(a_0,a_1,a_2),\quad a_i(a_i-1)=0,\quad w=\langle\mathbf a_L,(1,2,4)\rangle=4}_{\text{Booleanity 계산}}`}
  operations={[
    { expression: String.raw`(a_0,a_1,a_2),\quad a_i(a_i-1)=0,\quad w=\langle\mathbf a_L,(1,2,4)\rangle=4`, annotation: ["Booleanity이(가) 식의 결과에 기여하는 방식을","계산합니다.","Secret bits가 각각 0 또는 1이고","powers-of-two weighted sum이"] },
  ]} terms={[{symbol:"a_i",name:"Secret bit",description:"Field에서 boolean constraint를 만족합니다."},{symbol:"a_i(a_i-1)",name:"Booleanity",description:"Field에 zero divisor가 없으므로 0 또는 1만 남깁니다."},{symbol:"(1,2,4)",name:"Bit weights",description:"Little-endian 3-bit unsigned integer를 복원합니다."},{symbol:"w",name:"Committed value",description:"Pedersen commitment V의 같은 witness와 연결돼야 합니다."}]} assumptions={["w의 canonical integer interpretation과 range bit length 3을 protocol profile에 고정합니다.","Bit relation과 V=wG+rH가 동일 witness variables를 공유합니다.","Silent truncation·signed encoding·field wraparound를 허용하지 않습니다."]} interpretation="aL=(0,0,1)이면 w=4입니다. w=9를 하위 3 bits 001로 잘라 1로 증명하면 원래 integer 9의 range proof가 아니므로 반드시 reject해야 합니다."/><p>여러 values는 bit vectors를 이어 붙여 aggregate할 수 있지만 generator capacity와 verifier MSM은 커집니다. Multi-party aggregation에서는 ordered commitments, 각 party nonce contribution, abort 뒤 nonce 재사용 금지와 range/context domain을 고정해야 합니다.</p><div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-5 text-sm leading-6"><strong>실패 반례:</strong> 3w=12 relation의 w와 range vector의 w를 따로 두면 각각 참인 witness를 골라 결합 statement를 위조할 수 있습니다. Constraint system은 두 경로가 같은 committed scalar를 공유하도록 해야 합니다.</div></section>
  <section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Range failure와 pinned source parity 뒤 성능을 비교한다</h2></header><p>w=4와 correct V는 accept하고 w=−1·8·9, altered V, wrong range bits, generator order, transcript domain, malformed point는 모두 reject해야 합니다. Single/aggregate workloads에서 prove/verify time, proof bytes, peak RSS와 batch verifier를 재되 commit SHA·curve·generator capacity·logical range를 함께 기록합니다.</p><p>
            업그레이드는 old/new verifier cross-matrix와 serialized proof/key rejection을 포함하고 실패하면 pinned
            binary·parameters로 돌아갈 rollback artifact를 남깁니다.
          </p><div id="paper-bulletproofs"><CitationBlock source="Bünz et al. · Bulletproofs (2017)" citeKey={1} href="https://eprint.iacr.org/2017/1066.pdf"><p><strong>문제:</strong> Trusted setup 없이 committed ranges와 arithmetic relations를 짧게 증명해야 합니다.</p><p><strong>기여:</strong> Logarithmic-size IPA, range proof와 aggregation을 제시합니다.</p><p><strong>전제:</strong> Prime-order DLP group, independent generators와 random-oracle Fiat–Shamir를 사용합니다.</p><p><strong>근거 범위:</strong> 논문 construction·security·당시 benchmark 범위입니다.</p><p><strong>말하지 않는 것:</strong> Verifier work가 logarithmic이거나 모든 구현이 audited/constant-time이라는 뜻은 아닙니다.</p></CitationBlock></div><div id="paper-dalek-bulletproofs"><CitationBlock source="dalek-cryptography/bulletproofs · pinned be67b6d" citeKey={2} type="code" href="https://github.com/dalek-cryptography/bulletproofs/tree/be67b6d5f5ad1c1f54d5511b52e6d645a1313d07"><p><strong>문제:</strong> 실제 Ristretto serialization·transcript·generator 구현을 고정해 확인해야 합니다.</p><p><strong>기여:</strong> Rust source와 tests/bench entry를 제공합니다.</p><p><strong>전제:</strong> Commit be67b6d, dependencies와 compiler profile을 pin합니다.</p><p><strong>근거 범위:</strong> 해당 snapshot의 public/source behavior입니다.</p><p><strong>말하지 않는 것:</strong> 최신 release나 모든 target의 production 안전성을 보장하지 않습니다.</p></CitationBlock></div><p>이 글의 10문항은 commitment ownership, 3-bit 계산, booleanity, IPA rounds/order/work, truncation, padding, aggregation, release/rollback을 묻고 위 계산·전제·반례로 모두 답할 수 있습니다.</p></section>
  </article>}
