import {useEffect,useRef} from "react";
import {AnimatedSceneControls} from "@/components/viz/AnimatedSceneControls";
import {useAnimatedScenes} from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["일곱 자리","한 경로","기록 모으기","세 글자"] as const;
const notes=["R 뒤에 A와 B를 두고 각각 X와 Y를 준비합니다. 같은 Y도 앞 글이 다르면 다른 자리입니다.","확인 결과 R 다음 A, RA 다음 Y를 고릅니다. 남기는 저장 번호는 0·1·4입니다.","기존 네 자리 뒤에서 골라낸 기록 4·5·8을 연속된 자리 4·5·6으로 옮깁니다.","RAY를 붙여 글과 계산 기록이 각각 일곱 자리가 됩니다. 다음 C의 점수는 보관하고 C는 다음 바퀴에서 고릅니다."];
const pseudocode=["tree ← proposeBranches(prefix, depth=3)","path ← verifyAndSelect(tree) = [0, 1, 4]","kv ← gather([4, 5, 8]); compact(to=[4, 5, 6])","commit(tokens[path]) = RAY; keepNextLogits(C)"] as const;
const nodes=[{t:"R",x:170,y:30},{t:"A",x:94,y:110},{t:"B",x:246,y:110},{t:"X",x:44,y:200},{t:"Y",x:126,y:200},{t:"X",x:214,y:200},{t:"Y",x:296,y:200}];
const edges=[[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]];
export default function TreeTraceViz(){const scenes=useAnimatedScenes(4,4300);const inner=useRef<HTMLDivElement>(null);useEffect(()=>{const outer=inner.current?.parentElement;if(outer)outer.scrollTop=0},[scenes.active]);return <VizFrame eyebrow="가정한 같은 글" title="일곱 자리에서 RAY 경로를 남깁니다" description="갈래를 고른 뒤 그 경로의 기록을 연속된 자리에 모읍니다." note="일곱 자리를 모두 계산해도 출력과 다음 회차에 남는 것은 승인된 RAY 경로 하나입니다."><div ref={inner} data-viz-canvas role="group" tabIndex={0} aria-label="RAY 경로와 기록 이동" onKeyDown={scenes.onKeyDown} className="flex min-h-full min-w-0 flex-col outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><div className="flex flex-none flex-col py-2"><h4 className="font-bold">{labels[scenes.active]}</h4><svg viewBox="0 0 340 295" className="mt-3 h-auto max-h-72 w-full" role="img" aria-label="R에서 A를 거쳐 Y로 내려가는 경로"><defs><marker id="tree19-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M1 1L7 4L1 7" fill="none" className="stroke-primary"/></marker></defs>{edges.map(([a,b])=>{const selected=scenes.active>0&&a===0&&b===1||scenes.active>0&&a===1&&b===4;return <path key={a+"-"+b} d={`M${nodes[a].x} ${nodes[a].y+17}L${nodes[b].x} ${nodes[b].y-17}`} className={selected?"stroke-primary":"stroke-border"} fill="none" markerEnd={selected?"url(#tree19-arrow)":undefined} strokeDasharray={scenes.active>0&&!selected?"4 4":undefined}/>})}{nodes.map((n,i)=>{const chosen=scenes.active>0&&[0,1,4].includes(i);return <g key={i}><rect x={n.x-23} y={n.y-17} width="46" height="34" rx="6" className={chosen?"fill-primary/10 stroke-primary":"fill-background stroke-border"}/><text x={n.x} y={n.y+5} textAnchor="middle" className="fill-foreground text-[15px]">{n.t}</text><text x={n.x} y={n.y+34} textAnchor="middle" className="fill-muted-foreground text-[12px]">{i}</text></g>})}<text x="170" y="279" textAnchor="middle" className="fill-foreground text-[14px]">{scenes.active===0?"1 + 2 + 4 = 7":scenes.active===1?"0 → 1 → 4":scenes.active===2?"4·5·8 → 4·5·6":"RAY · 글 7 · 기록 7"}</text></svg><ol aria-label="현재 장면과 함께 실행되는 의사코드" className="mb-4 space-y-1.5">{pseudocode.map((line,index)=><li key={line} aria-current={scenes.active===index?"step":undefined} className={`flex min-w-0 gap-2 rounded-md border-l-2 px-3 py-2 ${scenes.active===index?"border-primary bg-primary/[0.07]":index<scenes.active?"border-primary/30 text-muted-foreground":"border-border/60 text-muted-foreground"}`}><span className="shrink-0 font-mono text-[10px] font-bold text-primary">{index<scenes.active?"✓":String(index+1).padStart(2,"0")}</span><code className="min-w-0 break-words font-mono text-[11px] leading-5">{line}</code></li>)}</ol><p className="mt-3 border-l border-primary/50 pl-4 text-sm leading-7 text-muted-foreground">{notes[scenes.active]}</p></div><AnimatedSceneControls {...scenes} labels={labels}/></div></VizFrame>}
