import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["두 묶음","합을 재사용","차를 회전"];
const details=["위치 0·2의 값 1·3을 묶어 합 4와 차 −2를 만듭니다. 위치 1·3의 값 2·4에서는 합 6과 차 −2가 나옵니다.","중간 합 4와 6을 한 번 더하고 한 번 뺍니다. 첫 출력은 10, 세 번째 출력은 −2입니다. 같은 두 중간값을 함께 씁니다.","둘째 묶음의 차 −2를 아래 방향으로 90도 돌리면 세로 +2입니다. 가로 −2에 이를 더하고 빼면 (−2,2)와 (−2,−2)가 됩니다."];
export default function ButterflyCaseViz(){const c=useAnimatedScenes(3);return <VizFrame eyebrow="가정한 네 입력" title="1, 2, 3, 4의 중간값을 다시 쓴다" description="숫자는 실제 네 값의 계산 결과입니다. 가로와 세로 성분을 모두 보관합니다." note="그림은 두 갈래로 나누는 설명용 계산입니다. 14절의 실제 KISS FFT는 같은 입력에 네 갈래 경로를 선택합니다.">
<div data-viz-canvas tabIndex={0} role="group" aria-label="네 값의 합과 차 계산" onKeyDown={c.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary">
<svg viewBox="0 0 320 280" className="mx-auto block w-full max-w-[460px]" role="img" aria-label={details[c.active]}>{c.active===0?<><text x="83" y="25" textAnchor="middle" fontSize="14" fill="currentColor">위치 0, 2</text><text x="237" y="25" textAnchor="middle" fontSize="14" fill="currentColor">위치 1, 3</text>{[[83,"1, 3","합 4","차 −2"],[237,"2, 4","합 6","차 −2"]].map((v,i)=><g key={i}><rect x={Number(v[0])-60} y="42" width="120" height="47" rx="6" fill="currentColor" fillOpacity=".08" stroke="currentColor"/><text x={v[0]} y="71" textAnchor="middle" fontSize="18" fill="currentColor">{v[1]}</text><path d={`M${v[0]} 96 V124 l-4 -6 m4 6 l4 -6`} fill="none" stroke="currentColor"/><text x={v[0]} y="163" textAnchor="middle" fontSize="20" fill="currentColor">{v[2]}</text><text x={v[0]} y="208" textAnchor="middle" fontSize="20" fill="currentColor">{v[3]}</text></g>)}<text x="160" y="260" textAnchor="middle" fontSize="13" fill="currentColor">각 묶음의 합과 차를 보관</text></>:c.active===1?<><text x="90" y="36" textAnchor="middle" fontSize="17" fill="currentColor">합 4</text><text x="230" y="36" textAnchor="middle" fontSize="17" fill="currentColor">합 6</text><path d="M90 48 V111 M90 48 L230 111 M230 48 V111 M230 48 L90 111" fill="none" stroke="currentColor" strokeOpacity=".5"/><rect x="23" y="113" width="134" height="57" rx="6" fill="currentColor" fillOpacity=".08"/><rect x="163" y="113" width="134" height="57" rx="6" fill="currentColor" fillOpacity=".08"/><text x="90" y="147" textAnchor="middle" fontSize="17" fill="currentColor">4 + 6 = 10</text><text x="230" y="147" textAnchor="middle" fontSize="17" fill="currentColor">4 − 6 = −2</text><text x="90" y="204" textAnchor="middle" fontSize="14" fill="currentColor">첫 출력</text><text x="230" y="204" textAnchor="middle" fontSize="14" fill="currentColor">셋째 출력</text><text x="160" y="260" textAnchor="middle" fontSize="13" fill="currentColor">같은 합 두 개로 출력 두 개</text></>:<><text x="160" y="25" textAnchor="middle" fontSize="14" fill="currentColor">둘째 묶음의 차: 가로 −2 → 세로 +2</text><line x1="72" x2="238" y1="135" y2="135" stroke="currentColor" strokeOpacity=".4"/><line x1="192" x2="192" y1="52" y2="218" stroke="currentColor" strokeOpacity=".4"/><path d="M192 135 L122 65 M192 135 L122 205" stroke="currentColor" strokeWidth="1" fill="none"/><circle cx="122" cy="65" r="5" fill="currentColor"/><circle cx="122" cy="205" r="5" fill="currentColor"/><text x="95" y="52" textAnchor="middle" fontSize="15" fill="currentColor">(−2, 2)</text><text x="95" y="226" textAnchor="middle" fontSize="15" fill="currentColor">(−2, −2)</text><text x="247" y="140" fontSize="12" fill="currentColor">가로</text><text x="198" y="50" fontSize="12" fill="currentColor">세로</text><text x="160" y="260" textAnchor="middle" fontSize="13" fill="currentColor">가로 −2에 세로 +2를 더하거나 빼기</text></>}</svg>
<p className="min-h-[9rem] text-sm leading-7" aria-live="polite">{details[c.active]}</p><AnimatedSceneControls {...c} labels={labels}/></div></VizFrame>;}
