import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
const scenes=[
 {label:"입력",title:"같은 세 바이트에서 시작합니다",input:"abc → 61 62 63",operation:"3바이트 × 8 = 24비트",output:"줄바꿈 없이 세 글자",note:"16진수 61은 두 글자가 아니라 한 바이트의 표시입니다. 두 컴퓨터는 정확히 같은 바이트와 계산 규칙을 사용합니다."},
 {label:"패딩",title:"끝 표시와 길이로 한 블록을 채웁니다",input:"61 62 63 · 80 · 00 52개 · 길이 8바이트",operation:"3 + 1 + 52 + 8 = 64바이트",output:"첫 단어 61626380 · 마지막 00000018",note:"여기서 18은 길이 24의 16진수입니다. 55바이트 입력까지 한 블록에 들어가고 56바이트부터는 두 블록이 필요합니다."},
 {label:"반복",title:"첫 단계가 여덟 상태값을 바꿉니다",input:"입력 단어 W₀ = 61626380",operation:"T₁ = 54da50e8 · T₂ = 08909ae5",output:"새 a = 5d6aebcd · 새 e = fa2a4622",note:"덧셈은 32비트 나머지 덧셈입니다. 입력 단어와 상수를 바꾸며 64라운드를 돌고 시작 상태를 다시 더합니다."},
 {label:"출력",title:"여덟 정수를 32바이트로 내보냅니다",input:"여덟 32비트 정수 × 4바이트",operation:"각 정수의 큰 자리부터 출력",output:"ba7816bf 8f01cfea … f20015ad",note:"전체 결과는 32바이트이며 화면의 16진수는 64글자입니다. 그림은 가운데를 생략했고 본문에는 전체 결과를 보존했습니다."},
];
export default function HashJourneyViz(){const controls=useAnimatedScenes(scenes.length,5000);const s=scenes[controls.active];return <figure data-viz="hash-journey" className="my-8 border-y border-border py-4"><figcaption className="mb-3 text-sm leading-6">SHA-256에 abc를 넣는 네 장면입니다. 내부 정수는 16진수로 표시합니다.</figcaption><div data-viz-canvas tabIndex={0} role="group" aria-label="같은 abc의 네 단계" onKeyDown={controls.onKeyDown} className="flex h-[min(530px,calc(100dvh-150px))] flex-col outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><div className="min-h-0 flex-1 overflow-y-auto px-1 py-3"><h3 className="text-lg font-semibold">{s.title}</h3><div className="my-5 space-y-4"><p className="border-b border-border pb-3 text-base">{s.input}</p><p className="font-mono text-sm leading-7">{s.operation}</p><p className="border-t border-border pt-3 text-lg font-semibold">{s.output}</p></div><p className="text-sm leading-7">{s.note}</p></div><AnimatedSceneControls {...controls} labels={scenes.map(v=>v.label)}/></div></figure>}
