import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["처음 다섯 위치","세 출현을 제거","다시 고른 이웃"];
const details=["위치 2의 cat에서 반경 1을 보면 위치 1과 3의 saw가 이웃입니다. 번호가 같아도 두 출현을 따로 셉니다.","가정한 제거 결과에서 두 saw와 마지막 dog가 사라집니다. 이 그림의 구체적인 난수와 원본 조건은 17절에서 확인합니다.","남은 순서는 red cat입니다. cat의 새 반경 1 이웃은 red 하나입니다. 비교용 단어를 더한 것이 아니라 관찰을 만들 문장이 달라졌습니다."];
export default function FilterCaseViz(){const a=useAnimatedScenes(3);return <VizFrame eyebrow="같은 문장의 다른 단계" title="지운 뒤에는 거리가 달라집니다" description="남은 위치를 모은 다음 이웃을 고릅니다." note="제거는 모든 출현에 대한 가능성입니다. 이번 결과에서 dog도 제거되었습니다."><div data-viz-canvas tabIndex={0} role="group" aria-label="제거와 이웃 재구성" onKeyDown={a.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><svg viewBox="0 0 320 250" className="mx-auto block w-full max-w-[450px]" role="img" aria-label={details[a.active]}>
{["red","saw","cat","saw","dog"].map((w,i)=><g key={i} opacity={a.active>0&&[1,3,4].includes(i)?.25:1}><text x={34+i*63} y="27" textAnchor="middle" fontSize="14" fill="currentColor">{i}</text><rect x={8+i*63} y="43" width="52" height="44" rx="5" fill="currentColor" fillOpacity={i===2?.15:.04} stroke="currentColor"/><text x={34+i*63} y="71" textAnchor="middle" fontSize="16" fill="currentColor">{w}</text>{a.active===1&&[1,3,4].includes(i)?<path d={"M"+(12+i*63)+" 48 l44 34 m0 -34 l-44 34"} stroke="currentColor"/>:null}</g>)}
{a.active===0?<><path d="M97 96 V118 H223 V96" fill="none" stroke="currentColor"/><text x="160" y="159" textAnchor="middle" fontSize="18" fill="currentColor">cat의 이웃: saw · saw</text><text x="160" y="205" textAnchor="middle" fontSize="15" fill="currentColor">관찰 두 건</text></>:a.active===1?<><text x="160" y="150" textAnchor="middle" fontSize="18" fill="currentColor">남길 출현을 먼저 정합니다</text><text x="160" y="198" textAnchor="middle" fontSize="16" fill="currentColor">red와 cat만 통과</text></>:<><path d="M34 94 L106 139 M160 94 L214 139" fill="none" stroke="currentColor"/><rect x="68" y="151" width="76" height="43" rx="5" fill="none" stroke="currentColor"/><rect x="176" y="151" width="76" height="43" rx="5" fill="currentColor" fillOpacity=".1"/><text x="106" y="178" textAnchor="middle" fontSize="18" fill="currentColor">red</text><text x="214" y="178" textAnchor="middle" fontSize="18" fill="currentColor">cat</text><text x="160" y="232" textAnchor="middle" fontSize="16" fill="currentColor">cat의 새 이웃: red 한 건</text></>}
</svg><p aria-live="polite" className="min-h-[10rem] text-sm leading-7">{details[a.active]}</p><AnimatedSceneControls {...a} labels={labels}/></div></VizFrame>;}
