import { AnimatedSceneControls } from "@/components/viz/AnimatedSceneControls";
import { useAnimatedScenes } from "@/components/viz/useAnimatedScenes";
import VizFrame from "@/components/viz/VizFrame";
const labels=["관찰 한 건","비교 두 건","같은 점수 다른 요구"];
const details=["입력 saw의 [0,1,1]과 관찰 대상 cat의 [2,0,1]을 곱해 더하면 점수 1입니다. 관찰 표시는 1입니다.","같은 saw에서 red와 dog를 각각 비교합니다. 두 점수도 모두 1이지만 추첨으로 붙인 표시는 0입니다.","cat의 점수를 높이려는 요구와 red·dog를 낮추려는 요구가 같은 입력 saw에 모입니다. 공유한 줄이므로 실제 변화는 세 기여를 함께 계산해야 합니다."];
export default function SamplingCaseViz(){const a=useAnimatedScenes(3);return <VizFrame eyebrow="같은 가정의 세 비교" title="한 줄에서 세 대상으로" description="점수와 기록의 출처를 따로 표시합니다." note="화살표는 비교 방향입니다. 단어가 문장에서 출현할 확률을 나눈 그림이 아닙니다."><div data-viz-canvas tabIndex={0} role="group" aria-label="세 비교의 생성" onKeyDown={a.onKeyDown} className="outline-none focus-visible:outline focus-visible:outline-1 focus-visible:outline-primary"><svg viewBox="0 0 320 270" className="mx-auto block w-full max-w-[450px]" role="img" aria-label={details[a.active]}>
<rect x="92" y="10" width="136" height="58" rx="5" fill="currentColor" fillOpacity=".09"/><text x="160" y="33" textAnchor="middle" fontSize="16" fill="currentColor">입력 saw</text><text x="160" y="56" textAnchor="middle" fontSize="16" fill="currentColor">[0,1,1]</text>
{["cat","red","dog"].map((w,i)=>{const on=i===0||a.active>0,x=53+i*107;return <g key={w} opacity={on?1:.18}><path d={"M160 73 V96 H"+x+" V119 l-4 -6 m4 6 l4 -6"} fill="none" stroke="currentColor"/><rect x={x-46} y="128" width="92" height="59" rx="5" stroke="currentColor" fill="none"/><text x={x} y="151" textAnchor="middle" fontSize="17" fill="currentColor">{w}</text><text x={x} y="175" textAnchor="middle" fontSize="14" fill="currentColor">표시 {i===0?1:0}</text><text x={x} y="217" textAnchor="middle" fontSize="16" fill="currentColor">점수 1</text><text x={x} y="247" textAnchor="middle" fontSize="15" fill="currentColor">{a.active===2?(i===0?"높이기":"낮추기"):(i===0?"관찰":"추첨")}</text></g>})}
</svg><p aria-live="polite" className="min-h-[10rem] text-sm leading-7">{details[a.active]}</p><AnimatedSceneControls {...a} labels={labels}/></div></VizFrame>;}
