import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation-block";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { teachCodeRefs } from "./teachCodeRefs";
import { EngineBoundaryViz, PayloadStateViz } from "./viz/ModernNodeArchitectureViz";
export default function ModernNodeArchitectureArticle(){const sidebar=useCodeSidebar();return <><article className="space-y-14 [&_section]:space-y-5 [&_h2]:text-2xl [&_h2]:font-bold [&_p]:leading-8">
<section id="overview" data-teach-level="S"><h2>1. 계산이 맞는 기록과 모두가 따를 기록을 구분합니다</h2><p>송금을 처리한 두 기록이 같은 이전 장부에서 갈라질 수 있습니다. 각각의 잔액 계산은 맞아도 둘을 동시에 정식 기록으로 삼을 수는 없습니다. 새 장부를 직접 계산하는 일과 네트워크가 어느 기록을 따를지 판단하는 일을 연결해야 합니다.</p><p>Ethereum 노드는 이 두 책임을 서로 다른 프로그램에 나눕니다. 각각 전문화하고 따로 발전시킬 수 있지만 둘이 같은 시작점과 규칙을 사용하며 결과를 정확히 주고받아야 합니다. 프로그램 두 개가 살아 있다는 확인만으로 정상 동작을 알 수 없는 이유입니다.</p><p>이 글에서는 송금 하나가 들어간 후보를 검증한 뒤 현재 기록으로 선택하는 과정을 봅니다. 내부 모듈 이름보다 먼저 두 담당자의 입구와 출구를 나누겠습니다.</p></section>
<section id="black-box" data-teach-level="B"><h2>2. 하나는 계산하고 다른 하나는 선택합니다</h2><ol className="list-decimal space-y-3 pl-6"><li>요청 수신 → 서명한 송금과 후보 기록을 받습니다.</li><li>내용 계산 → 앞선 장부에서 거래를 실행해 후보의 결과를 검증합니다.</li><li>기록 선택 → 네트워크의 제안과 투표를 보고 현재 따를 가지를 고릅니다.</li><li>서로 알림 → 선택한 기록과 검증 결과를 교환합니다.</li></ol><p>검증 담당자가 ‘계산이 맞다’고 답해도 선택 담당자가 다른 유효한 후보를 고를 수 있습니다. 선택 담당자가 특정 후보를 원해도 계산이 틀린 후보를 받아들일 수는 없습니다. 한 송금의 숫자로 이 왕복을 보겠습니다.</p></section>
<section id="case" data-teach-level="0"><h2>3. 100에서 10과 처리 비용을 빼는 후보를 받습니다</h2><p>이전 기록 H100에서 A의 잔액은 100 ETH, B의 잔액은 0 ETH입니다. 후보 H101에는 A가 B에게 10 ETH를 보내고 처리 비용 0.000042 ETH를 내는 송금 하나가 있습니다(가정). A는 89.999958 ETH, B는 10 ETH가 되어야 합니다. H100·H101은 실제 해시 바이트 대신 읽기 쉽게 붙인 이름입니다.</p><p>처음에는 H101만 받고 그 부모 H100의 상태가 없을 수 있습니다. 계산 담당자는 아직 결과를 확인하지 못합니다. 이후 H100을 얻어 위 결과를 재현하면 계산이 유효하다고 답합니다. 이 응답 뒤에도 H101이 현재 선택된 기록인지, 더는 되돌리지 않을 기록인지는 별도로 남습니다.</p><p>이 사례는 호출 관계를 설명하기 위한 가정이며 메인넷에서 실제로 제출한 거래가 아닙니다. 입력 부족, 계산 통과, 현재 선택이라는 세 상태를 끝까지 같은 후보로 추적합니다.</p></section>
<section id="parts" data-teach-level="1"><h2>4. 양쪽은 서로 다른 장부 상태를 기억합니다</h2><p>계산 담당자는 계정 잔액과 프로그램 상태, 실행할 거래와 이미 검증한 블록을 관리합니다. 선택 담당자는 제안과 투표, 지금 따를 가지와 더 안정적인 과거 지점을 관리합니다. 각자 필요한 주변 통신과 저장 장치도 있습니다.</p><p>둘 사이의 요청에는 후보의 본문 또는 선택하려는 기록의 식별자가 들어갑니다. 응답에는 검증 성공·실패·자료 부족을 구분한 결과가 들어갑니다. 양쪽이 판단할 수 없는 일을 상대방의 응답 한 단어에 덧붙이지 않는 것이 중요합니다.</p><p>누가 어느 결정을 소유하는지 알면 두 프로그램을 연결한 이유도 설명할 수 있습니다. 한 응답으로 책임을 합쳐 버릴 때 생기는 오류를 확인하겠습니다.</p></section>
<section id="why-parts" data-teach-level="2"><h2>5. 자료가 없는 후보를 잘못된 후보로 저장하면 안 됩니다</h2><p>H100이 없어서 H101을 계산하지 못한 상태를 ‘잘못된 기록’으로 저장하면 나중에 H100이 도착해도 올바른 후보를 버릴 수 있습니다. 반대로 아직 계산하지 못한 후보를 성공으로 표시하면 틀린 잔액을 받아들일 수 있습니다. 자료를 기다리는 상태를 별도로 두어야 합니다.</p><p>계산 성공을 최종 확정으로 표시하는 것도 위험합니다. H101과 경쟁 후보 H101b가 모두 유효해도 현재 선택은 하나입니다. 새로운 투표가 보이면 선택이 달라질 수 있습니다. 어느 상태까지 확인했는지 사용자와 다른 프로그램에 정확히 전달해야 합니다.</p><p>이 구분을 통신의 필드와 상태 값으로 표현합니다. 이름을 붙인 뒤에는 같은 H101을 실제 요청 순서에 대응시키겠습니다.</p></section>
<section id="names" data-teach-level="3"><h2>6. 실행 클라이언트와 합의 클라이언트가 Engine API로 연결됩니다</h2><dl className="space-y-4"><div><dt className="font-semibold">내용 계산 담당 → 실행 클라이언트, EL</dt><dd>Execution Layer입니다. EVM 실행, 계정 상태, 거래 대기열과 실행 블록 검증을 맡습니다.</dd></div><div><dt className="font-semibold">기록 선택 담당 → 합의 클라이언트, CL</dt><dd>Consensus Layer입니다. 검증자 투표, 가지 선택, 체크포인트 확정을 맡습니다.</dd></div><div><dt className="font-semibold">둘 사이의 호출 계약 → Engine API</dt><dd>후보 검증·가지 선택 알림·후보 제작을 주고받는 버전별 메서드 규격입니다.</dd></div><div><dt className="font-semibold">실행할 블록 내용 → execution payload</dt><dd>거래 목록과 실행 결과를 나타내는 필드 등이 들어갑니다. H101이라는 식별자만으로 모든 내용을 대신하지는 못합니다.</dd></div><div><dt className="font-semibold">현재·더 안정적·최종 확정 지점 → head, safe, finalized</dt><dd>서로 다른 상태를 가리킵니다. safe의 의미에는 명세의 정직성·통신 가정이 들어갑니다.</dd></div></dl><EngineBoundaryViz/><p>3절의 처리 비용은 단순 송금에 계산 단위 21,000과 단위당 2 Gwei를 적용한 42,000 Gwei=0.000042 ETH입니다. 실제 거래의 종류와 적용 규칙이 다르면 비용도 달라집니다. 이 예에서 선택한 값으로 요청의 왕복을 따라갑니다.</p></section>
<section id="el-cl-boundary" data-teach-level="4"><h2>7. 새 후보를 검증하고 선택 상태를 따로 전달합니다</h2><p>CL은 H101의 실행 내용을 <code>engine_newPayload</code> 계열 호출로 EL에 보냅니다. EL에 H100이 없으면 <code>SYNCING</code>으로 답할 수 있습니다. 상태를 확보해 거래와 결과를 검증하면 <code>VALID</code>와 latestValidHash=H101을 반환합니다. 이름 H101은 실제 요청에서 32바이트 해시로 표현됩니다.</p><p>CL이 H101을 현재 가지로 선택했다면 <code>engine_forkchoiceUpdated</code> 계열 호출로 head=H101을 전달합니다. 예를 들어 safe=H99, finalized=H96이라고 함께 보낼 수 있습니다(가정). H99와 H96은 H101의 올바른 조상이어야 합니다. H101의 유효성 응답을 받았다는 이유만으로 finalized를 H101로 올리지 않습니다.</p><p>새 블록을 제작할 차례에는 이 호출에 제작 조건을 덧붙입니다. EL이 제작 작업을 시작하면 payloadId를 돌려줍니다. CL은 그 ID를 <code>engine_getPayload</code> 계열 호출에 넣어 후보를 가져옵니다. 받은 후보에도 제안과 선택의 나머지 절차가 필요합니다.</p><p>실제 호출의 V1·V2 같은 접미사와 추가 필드는 해당 fork에 맞춥니다. 여기서는 역할을 먼저 설명했고 다음 원문 절에서는 고정한 Paris의 기본 계약을 읽습니다. 최신 fork에 그 V1 형식을 그대로 보내라는 뜻은 아닙니다.</p></section>
<section id="wire-source" data-teach-level="5"><h2>8. 명세의 필드는 서로 다른 확인 결과를 담습니다</h2><div id="paper-engine-api"><CitationBlock source="execution-apis 5aebdfd · paris.md, PayloadStatusV1 / ForkchoiceStateV1" citeKey={1} href="https://github.com/ethereum/execution-apis/blob/5aebdfdd45cadeb723be4bd45b4611b71c8b1c85/src/engine/paris.md"><p>원문은 성공 응답을 <code>{'{status: VALID, latestValidHash: payload.blockHash}'}</code>로 적습니다. 이는 payload의 실행 유효성 응답입니다. 가지 선택 구조에는 별도 필드 headBlockHash·safeBlockHash·finalizedBlockHash가 있습니다.</p></CitationBlock></div><p>사례에서 payload.blockHash가 H101이면 검증 성공 응답의 latestValidHash도 H101입니다. 이 필드가 finalizedBlockHash를 대신하지 않습니다. 같은 명세의 forkchoiceUpdated 규칙은 safe나 finalized가 요청 head의 가지에 속하지 않으면 잘못된 가지 선택 상태로 거절하도록 정합니다.</p><p>실행 프로그램과 합의 프로그램은 같은 시작 블록과 fork 활성화 일정, 서로 지원하는 Engine 메서드를 사용해야 합니다. 접속 인증에 쓰는 JWT는 이 통신 창구에 누가 접근할 수 있는지 제한합니다. 거래 계산이 맞거나 원격 피어가 정직하다는 증명은 아닙니다. 그 다음 실제 구현이 자료 부족과 유효함을 어떻게 나누는지 보겠습니다.</p></section>
<section id="implementation" data-teach-level="6"><h2>9. Reth는 연결되지 않은 후보를 SYNCING으로 구분합니다</h2><p>Reth의 <code>try_insert_payload</code>는 삽입 결과가 유효한 블록이면 latest_valid_hash에 해당 블록 해시를 넣고 VALID 상태를 만듭니다. 부모에 아직 연결되지 않은 결과에는 SYNCING을 사용합니다. H100이 없는 H101과 H100에서 실행해 맞는 결과를 낸 H101이 이 분기로 나뉩니다.</p><CodeViewButton label="VALID·SYNCING 실제 분기" onClick={()=>sidebar.open("validation",teachCodeRefs.validation)}/><p>이미 본 유효한 H101에는 VALID를 다시 반환하면서 already_seen을 true로 둡니다. 같은 요청이 도착했다고 A의 잔액에서 10 ETH를 한 번 더 빼는 경로로 해석해서는 안 됩니다. 실제 재적용 여부는 블록 식별자와 앞선 상태 문맥을 함께 관리합니다.</p><p><code>on_forkchoice_updated</code>는 요청 상태를 먼저 검사하고 이미 맞는 head인지, 다른 가지로 갱신해야 하는지, 필요한 블록이 빠졌는지를 나눕니다. H101의 계산 결과를 아는 것과 정식 가지를 바꾸는 일을 별도 함수 경로로 확인할 수 있습니다.</p><CodeViewButton label="현재 head 유지·갱신 실제 분기" onClick={()=>sidebar.open("choice",teachCodeRefs.choice)}/><div id="paper-reth-node"><CitationBlock source="Reth v2.2.0 · 88505c7, crates/engine/tree/src/tree/mod.rs" citeKey={2} type="code" href="https://github.com/paradigmxyz/reth/blob/88505c7fcbfdebfd3b56d88c86b62e950043c6c4/crates/engine/tree/src/tree/mod.rs"><p>원본 파일을 이 commit에서 다시 받아 코드 패널에 연결했고 라이선스를 함께 보존했습니다. 설명은 이 구현의 분기에 한정합니다. 이 글에서 실제 Reth 노드로 H101 요청을 실행하거나 재시작 시험을 했다는 주장은 아닙니다.</p></CitationBlock></div><p>응답이 어떻게 만들어지는지 확인했습니다. 마지막에는 같은 응답을 장애 복구나 사용자 화면에서 과하게 해석하지 않도록 경계를 정리합니다.</p></section>
<section id="payload-state" data-teach-level="7"><h2>10. VALID·현재 head·최종 확정은 서로 다른 상태입니다</h2><PayloadStateViz/><p>SYNCING은 필요한 자료가 없어 판정을 기다린다는 뜻입니다. ACCEPTED는 일부 허용 경로에서 수신했지만 전체 검증을 끝냈다는 뜻은 아닙니다. INVALID는 잘못된 실행이나 조상 등 원인을 갖는 판정이므로 명세가 허용하는 latestValidHash와 오류 정보를 함께 처리합니다. 모든 메서드에서 같은 상태 집합을 반환할 수 있는 것도 아닙니다.</p><p>CL의 새 선택으로 H101 대신 H101b를 따라가면 EL은 그 가지의 앞선 상태에서 결과를 적용합니다. 이를 reorg라고 합니다. 이전 변경을 새 가지 위에 한 번 더 더하면 안 됩니다. 저장 구조와 상태 조회 구현은 <Link to="/cs/blockchain/reth">Reth 구조</Link>, 명령 한 단계의 계산은 <Link to="/cs/blockchain/evm-fundamentals">EVM 기초</Link>가 이어서 설명합니다.</p></section>
<section id="release" data-teach-level="7"><h2>11. 재시작 뒤에도 같은 후보를 두 번 적용하지 않습니다</h2><p>검증 응답 직후, 가지 선택 갱신 전후, 저장 확정 전후에 프로그램이 중단되는 상황을 나눠 검사합니다. 재시작한 EL은 남아 있는 블록과 상태를 재구성하고 CL은 현재 선택 정보를 다시 전달합니다. 성공 응답 하나가 데이터베이스의 모든 변경이 영구 저장됐다는 뜻인지는 실제 구현의 저장 계약에서 확인해야 합니다.</p><p>검수 입력에는 인증 키 불일치, 지원하지 않는 메서드 버전, H100 누락, 틀린 상태 루트, 경쟁하는 유효한 H101b, 이미 확정한 가지와 충돌하는 선택을 넣습니다. H100을 기다릴 때는 후보 식별자로 요청을 묶고 재시도 횟수와 보관 시간을 제한합니다. 자료 부족은 INVALID로 바꾸지 않으며 자료를 얻은 뒤 다시 검증합니다. 복구한 잔액과 상태 루트, 응답 상태를 이전 구현과 비교합니다. 같은 시작점이어도 활성화 규칙이 다르면 결과가 달라질 수 있습니다. 배포 전에는 양쪽의 정확한 버전과 시작 블록, fork 일정, 인증과 메서드 호환성을 기록합니다. 일부 노드에 먼저 적용해 요청·응답과 reorg 뒤 상태가 같은지 확인하고 문제가 생기면 호환되는 이전 버전 묶음으로 되돌립니다.</p><ul className="list-disc space-y-3 pl-6"><li>H100이 없어 H101을 실행하지 못했다면 INVALID로 영구 저장해도 될까요? (답: 9절)</li><li>H101에 VALID 응답이 왔다면 finalized도 H101로 표시해도 될까요? (답: 7절)</li><li>이미 검증한 H101이 다시 도착하면 A에게 10 ETH를 또 차감할까요? (답: 9절)</li></ul></section>
</article><CodeSidebar codeRefKey={sidebar.codeRefKey} codeRef={sidebar.codeRef} onClose={sidebar.close} onNavigate={sidebar.navigate} codeRefs={teachCodeRefs} fileTrees={{}} projectMetas={{reth:{id:"reth",label:"Reth · 88505c7",badgeClass:"border-sky-500 text-sky-700"}}}/></>}
