import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { Hotstuff2EntryViz, Hotstuff2PhaseViz } from "./viz/ModernHotstuff2Viz";

export default function ModernHotstuff2Article(){return <article className="space-y-14">
  <section id="overview" className="space-y-6">
    <header className="space-y-3"><p className="text-sm font-semibold text-primary">HotStuff-2 · two-phase responsive BFT</p><h2 className="text-3xl font-bold tracking-tight">HotStuff-2는 두 phase만 남기는 대신, 새 view가 숨은 lock을 놓치지 않는 방법까지 함께 설계한다</h2></header>
    <p className="text-lg leading-8 text-foreground/90">Alice가 Bob에게 10을 보내는 요청이 block B에 들어갔다고 하겠습니다. Steady path에서는 B의 첫 certificate와 그 certificate를 다시 확인하는 <em>double certificate</em>가 다음 view의 안전한 출발점이 됩니다. 이 두 겹의 evidence가 있으면 연속된 honest leader는 알려진 최대 지연 Δ를 매번 기다리지 않고 actual network delay에 맞춰 진행합니다.</p>
    <p>이를 “HotStuff의 세 phase를 두 phase로 줄였다”로만 이해하면 핵심을 놓칩니다. 직전 view의 double certificate가 없을 때는 leader가 replicas의 lock status를 모으며, 이 recovery path에서는 GST 뒤에도 O(Δ) wait가 들어갈 수 있습니다. Steady latency, failed-view recovery, communication과 pacemaker 비용을 따로 비교해야 합니다.</p>
    <Hotstuff2EntryViz />
    <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> Two-phase safety는 nested certificate에, responsiveness는 직전-view evidence가 있느냐에 달려 있습니다. Evidence가 없을 때의 wait는 safety rule을 약하게 만들지 않고 liveness를 복구하는 경계입니다.</aside>
  </section>
  <section id="two-phase" className="space-y-6">
    <header><p className="text-sm font-semibold text-primary">01 · two-phase와 double certificate</p><h2 className="mt-2 text-2xl font-bold">안쪽 certificate는 block을 인증하고, 바깥 certificate는 그 인증을 quorum이 다시 확인했음을 증명한다</h2></header>
    <p>Leader proposal을 검증한 replicas의 첫 votes 2f+1개는 block certificate가 됩니다. 다음 vote step에서는 replicas가 그 certificate 자체를 검증하고 다시 서명하며, 다시 2f+1 shares가 모이면 double certificate가 됩니다. 두 set은 모두 committee·view·digest domain에 결속되어야 하고 서로 다른 blocks의 shares를 섞을 수 없습니다.</p>
    <ExplainedFormula question="n=3f+1에서 두 겹 certificate가 갖춰야 할 최소 quorum은 무엇인가?" idea={<>안쪽과 바깥쪽 모두 2f+1 distinct signers를 요구하면 임의의 두 quorum이 적어도 f+1 participants에서 겹치므로 honest replica가 하나 이상 남습니다.</>} formula={String.raw`\begin{aligned}|Q_i|&\ge 2f+1\\|Q_o|&\ge 2f+1\\|Q_1\cap Q_2|&\ge f+1\end{aligned}`} terms={[{symbol:"Qᵢ",name:"inner voters",description:"같은 block·view에 첫 vote를 보낸 서로 다른 replicas입니다."},{symbol:"Qₒ",name:"outer voters",description:"검증된 inner certificate를 같은 protocol domain에서 다시 확인한 replicas입니다."},{symbol:"f",name:"Byzantine fault bound",description:"3f+1 replicas 가운데 arbitrary behavior를 할 수 있는 최대 수입니다."},{symbol:"f+1",name:"honest-intersection floor",description:"두 quorum 교집합의 최소 크기이며 적어도 한 honest signer를 포함합니다."}]} assumptions={["Signers를 중복 제거하고 historical committee를 고정합니다.","Inner digest·view·ancestry와 outer domain을 모두 검증합니다.","One-vote rule과 lock update를 함께 유지합니다.","Certificate는 payload execution·client settlement receipt가 아닙니다."]} interpretation="n=4,f=1이면 inner votes 3개와 outer votes 3개가 각각 필요합니다. 두 signer sets는 적어도 2명에서 겹치며 Byzantine replica가 최대 1명이므로 honest witness가 남습니다." />
    <p>Double certificate를 application finality로 곧바로 읽어서는 안 됩니다. Ordered block을 정한 뒤에도 payload availability, deterministic execution, state-root persistence와 client reply가 남으며 restart 때는 certificate 두 겹과 lock·view를 함께 복구해야 합니다.</p>
    <div id="paper-hotstuff2-steady"><CitationBlock source="HotStuff-2 paper §4 — Steady-State Protocol" citeKey={1} href="https://eprint.iacr.org/2023/397.pdf#page=4"><p><strong>문제:</strong> Linear communication을 유지하면서 한 view의 BFT commit을 two phase로 구성해야 합니다.</p><p><strong>기여:</strong> Block·certificate ranks, vote steps, lock update와 nested certificate handoff를 정의합니다.</p><p><strong>전제:</strong> Valid threshold shares, one-vote rules, chain extension과 exact view·rank comparisons를 따릅니다.</p><p><strong>근거 범위:</strong> Paper steady-state algorithm과 safety state transitions에 한정합니다.</p><p><strong>말하지 않는 것:</strong> Nested certificate가 application execution·disk durability나 임의 two-phase protocol의 safety를 자동 보장하지 않습니다.</p></CitationBlock></div>
  </section>
  <section id="view-sync" className="space-y-6">
    <header><p className="text-sm font-semibold text-primary">02 · responsive entry와 lock-status recovery</p><h2 className="mt-2 text-2xl font-bold">직전-view 증거가 있으면 바로 진행하고, 없으면 2f+1 status에서 가장 높은 lock을 찾는다</h2></header>
    <p>새 leader가 직전 view의 valid double certificate를 받았다면 그 branch를 이어 vote step으로 갑니다. Certificate가 없으면 higher lock이 network에 숨어 있는지 faulty leader가 evidence를 숨겼는지 구분할 수 없습니다. 이때 O(Δ) 동안 lock reports 2f+1개를 모아 status certificate를 만들고 가장 높은 valid certified block을 parent로 삼습니다.</p>
    <p>n=4,f=1에서 reports 2개만 받으면 빠진 honest replica가 더 높은 lock을 가질 수 있지만 reports 3개에는 이전 quorum과 honest intersection이 생깁니다. 이 liveness 논리는 GST 뒤 known Δ와 pacemaker의 view synchronization을 전제로 합니다. GST 전 stall은 허용되지만 conflicting commit은 언제나 허용되지 않습니다.</p>
    <Hotstuff2PhaseViz />
    <div id="paper-hotstuff2-pacemaker"><CitationBlock source="HotStuff-2 paper §4 — Pacemaker and View Entry" citeKey={2} href="https://eprint.iacr.org/2023/397.pdf#page=6"><p><strong>문제:</strong> Previous leader failure 뒤 hidden higher locks를 놓치지 않으면서 honest-leader sequence는 responsive해야 합니다.</p><p><strong>기여:</strong> Previous-view evidence fast case, O(Δ) status-wait recovery와 integrated pacemaker를 정의합니다.</p><p><strong>전제:</strong> Unknown GST 뒤 알려진 Δ, valid timeout coordination와 paper epoch·view synchronization을 사용합니다.</p><p><strong>근거 범위:</strong> HotStuff-2 liveness·view-entry construction과 communication complexity argument입니다.</p><p><strong>말하지 않는 것:</strong> Δ wait가 모든 view에 생기거나 actual-delay 관찰만으로 GST를 알 수 있다는 뜻은 아닙니다.</p></CitationBlock></div>
  </section>
  <section id="release" className="space-y-6">
    <header><p className="text-sm font-semibold text-primary">03 · 비용과 release envelope</p><h2 className="mt-2 text-2xl font-bold">Happy path 두 phase와 failed-view cascade를 따로 재고, state receipt까지 확인한 뒤 결과를 낸다</h2></header>
    <p>Benchmark는 같은 payload·committee·crypto에서 연속 honest leaders와 t명의 faulty leaders trace를 분리합니다. Phase latency뿐 아니라 status bytes, timeout certificates, pacemaker messages와 Δ waits를 기록해야 “two phase”가 장애 복구도 늘 빠르다는 과장을 막을 수 있습니다.</p>
    <p>Crash 뒤에는 persisted highest certificate, lock, view와 committed boundary를 불러오고 missing blocks를 hash로 동기화합니다. Double certificate와 deterministic state root를 재검증한 뒤 client receipt를 냅니다. Invalid nested digest, stale committee, status 미달, partition과 crash를 주입해 safety conflict 0과 GST 뒤 eventual progress를 따로 판정하며 rollback은 external receipt 전 speculation에만 허용합니다.</p>
    <div id="paper-hotstuff2"><CitationBlock source="HotStuff-2: Optimal Two-Phase Responsive BFT" citeKey={3} href="https://eprint.iacr.org/2023/397"><p><strong>문제:</strong> Two-phase optimistic latency, linear happy-path communication, responsiveness와 optimal worst-case complexity를 함께 달성해야 합니다.</p><p><strong>기여:</strong> Two-phase HotStuff variant와 previous-view certificate·status-aware pacemaker를 제시합니다.</p><p><strong>전제:</strong> n=3f+1 authenticated parties, 최대 f Byzantine faults, partial synchrony와 paper pacemaker를 사용합니다.</p><p><strong>근거 범위:</strong> HotStuff-2 protocol, safety·liveness proofs와 asymptotic analysis에 한정합니다.</p><p><strong>말하지 않는 것:</strong> 모든 view가 wait-free이거나 third-party implementation·고정 latency가 검증됐다는 뜻은 아닙니다.</p></CitationBlock></div>
    <h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 목표, nested certificate, n=4 quorum, status parent, 두 entry 경로와 비교축을 묻습니다. 심화 4문제는 invalid·missing evidence, hidden lock, faulty-leader 비용과 crash recovery를 설계하게 합니다.</p>
  </section>
</article>}
