import type { CodeRef, FileNode, ProjectMeta } from "@/components/code/types";
import tower from "./codebase/models/binius_models/finite_fields/tower.py?raw";
import sumcheck from "./codebase/models/binius_models/ips/sumcheck.py?raw";
import flock from "./codebase/flock/crates/flock-core/src/r1cs.rs?raw";
import trace from "./verification/trace.py?raw";
export const codeRefs:Record<string,CodeRef>={
"init":{code:sumcheck,"path": "models/sumcheck.py", "highlight": [59, 80], "lang": "python", "desc": "네 원소 배열 두 개와 곱 composition을 넣습니다. 기본 주소 순서는 낮은 비트부터입니다.", "annotations": [{"lines": [59, 80], "color": "sky", "note": "네 원소 배열 두 개와 곱 composition을 넣습니다. 기본 주소 순서는 낮은 비트부터입니다."}]},
"round":{code:sumcheck,"path": "models/sumcheck.py", "highlight": [93, 148], "lang": "python", "desc": "첫 메시지 [1,3]은 1과 비트 표기 2인 점의 평가값입니다. 0에서의 값은 이전 합으로 복원합니다.", "annotations": [{"lines": [93, 148], "color": "sky", "note": "첫 메시지 [1,3]은 1과 비트 표기 2인 점의 평가값입니다. 0에서의 값은 이전 합으로 복원합니다."}]},
"fold":{code:sumcheck,"path": "models/sumcheck.py", "highlight": [150, 178], "lang": "python", "desc": "질문을 받은 뒤 가중치를 확장하거나 표를 접습니다. 이번 첫 단계의 표 보존과 둘째 단계의 최종 한 칸을 구별합니다.", "annotations": [{"lines": [150, 178], "color": "sky", "note": "질문을 받은 뒤 가중치를 확장하거나 표를 접습니다. 이번 첫 단계의 표 보존과 둘째 단계의 최종 한 칸을 구별합니다."}]},
"interpolate":{code:sumcheck,"path": "models/sumcheck.py", "highlight": [180, 209], "lang": "python", "desc": "세 평가값을 보간해 새 주장을 계산합니다. 마지막 query는 보유한 표의 곱이며 PCS 열기 증명이 아닙니다.", "annotations": [{"lines": [180, 209], "color": "sky", "note": "세 평가값을 보간해 새 주장을 계산합니다. 마지막 query는 보유한 표의 곱이며 PCS 열기 증명이 아닙니다."}]},
"tower":{code:tower,"path": "models/tower.py", "highlight": [16, 40], "lang": "python", "desc": "특성 2에서 덧셈과 뺄셈은 XOR입니다. 위쪽 체의 곱셈은 별도 재귀 경로를 사용합니다.", "annotations": [{"lines": [16, 40], "color": "sky", "note": "특성 2에서 덧셈과 뺄셈은 XOR입니다. 위쪽 체의 곱셈은 별도 재귀 경로를 사용합니다."}]},
"multiply":{code:tower,"path": "models/tower.py", "highlight": [197, 207], "lang": "python", "desc": "낮은 체의 세 곱으로 교차항을 만들고 v²=1+uv에 맞춰 환원합니다. 1011과 0110은 1111이 됩니다.", "annotations": [{"lines": [197, 207], "color": "sky", "note": "낮은 체의 세 곱으로 교차항을 만들고 v²=1+uv에 맞춰 환원합니다. 1011과 0110은 1111이 됩니다."}]},
"encoding":{code:tower,"path": "models/tower.py", "highlight": [73, 104], "lang": "python", "desc": "from_int는 정수를 mod 2로 넣습니다. from_bytes의 길이 검사와 _is_valid 범위 검사는 서로 다릅니다.", "annotations": [{"lines": [73, 104], "color": "sky", "note": "from_int는 정수를 mod 2로 넣습니다. from_bytes의 길이 검사와 _is_valid 범위 검사는 서로 다릅니다."}]},
"flock":{code:flock,"path": "flock/r1cs.rs", "highlight": [208, 233], "lang": "rust", "desc": "각 비트의 AND를 C 결과와 대조합니다. 같은 네 기록은 [0,1,0,0]과 일치해야 합니다.", "annotations": [{"lines": [208, 233], "color": "sky", "note": "각 비트의 AND를 C 결과와 대조합니다. 같은 네 기록은 [0,1,0,0]과 일치해야 합니다."}]},
"flock-packed":{code:flock,"path": "flock/r1cs.rs", "highlight": [425, 440], "lang": "rust", "desc": "packed 표현에서도 lo와 hi 각각에 비트별 AND를 합니다. 일반 확장체 곱셈 호출이 아닙니다.", "annotations": [{"lines": [425, 440], "color": "sky", "note": "packed 표현에서도 lo와 hi 각각에 비트별 AND를 합니다. 일반 확장체 곱셈 호출이 아닙니다."}]},
"execute":{code:trace,"path": "case/trace.py", "highlight": [88, 110], "lang": "python", "desc": "고정 원문 정의에 실제 같은 A/B와 두 질문을 넣습니다. 원문 메시지와 직접 계산한 최종 곱을 대조합니다.", "annotations": [{"lines": [88, 110], "color": "sky", "note": "고정 원문 정의에 실제 같은 A/B와 두 질문을 넣습니다. 원문 메시지와 직접 계산한 최종 곱을 대조합니다."}]},
"checks":{code:trace,"path": "case/trace.py", "highlight": [114, 159], "lang": "python", "desc": "전체 작은 체와 질문 조합을 검사하고 오류표·잘못된 인코딩을 별도로 확인합니다.", "annotations": [{"lines": [114, 159], "color": "sky", "note": "전체 작은 체와 질문 조합을 검사하고 오류표·잘못된 인코딩을 별도로 확인합니다."}]},
};
export const fileTrees:Record<string,FileNode>={"models": {"name": "수학 모델 고정 원문", "type": "dir", "children": [{"name": "sumcheck.py", "type": "file", "path": "models/sumcheck.py", "codeKey": "init"}, {"name": "tower.py", "type": "file", "path": "models/tower.py", "codeKey": "tower"}]}, "flock": {"name": "Flock 고정 원문 · 미실행", "type": "dir", "children": [{"name": "r1cs.rs", "type": "file", "path": "flock/r1cs.rs", "codeKey": "flock"}]}, "case": {"name": "별도 호출과 독립 검산", "type": "dir", "children": [{"name": "trace.py", "type": "file", "path": "case/trace.py", "codeKey": "execute"}]}};
export const projectMetas:Record<string,ProjectMeta>={"models": {"id": "models", "label": "수학 모델 고정 원문", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}, "flock": {"id": "flock", "label": "Flock 고정 원문 · 미실행", "badgeClass": "bg-amber-50 border-amber-300 text-amber-800"}, "case": {"id": "case", "label": "별도 호출과 독립 검산", "badgeClass": "bg-emerald-50 border-emerald-300 text-emerald-800"}};
