import { Link } from "react-router-dom";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import ReviewPrompts from "@/pages/articles/world-systems/ReviewPrompts";
import BinaryProofJourneyViz from "./viz/BinaryProofJourneyViz";
import { codeRefs, fileTrees, projectMetas } from "./codeRefs";
export default function ModernArticle(){const sidebar=useCodeSidebar();return <div className="space-y-16 [overflow-wrap:anywhere]">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 네 비트 계산을 모두 다시 하지 않고 확인하려 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">서버가 1011과 0110을 받아 비트별 AND를 계산하고 0010이라고 보냈습니다. 네 비트라면 직접 확인하면 됩니다. 하지만 이런 연산이 해시 안에서 수백만 번 반복되면 검증자도 같은 일을 전부 하는 비용이 커집니다.</p>
<p className="leading-8">증명자는 계산 기록으로 짧은 증거를 만들고 검증자는 그 증거로 결과를 확인하려 합니다. 이 글에서는 같은 네 비트가 계산표, 다항식, 두 번의 질문, 실제 코드로 바뀌는 과정을 따라갑니다. 입력을 숨기는 성질은 이 과정만으로 생기지 않습니다.</p>
<p className="leading-8">먼저 손으로 계산할 수 있는 16원소의 작은 세계를 씁니다. 작은 확률과 고정한 질문은 설명용이며 실제 보안 설정이 아닙니다. 마지막에는 Binius 계열과 2026년 Flock이 무엇을 더 갖추는지 연결합니다.</p>
</div></section>
<section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 계산 기록을 먼저 고정하고 그 기록에 질문합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">전체 흐름은 계산 규칙과 공개 결과를 정하기, 기록을 고정하기, 무작위 질문으로 확인할 양을 줄이기, 마지막 값을 원래 기록에 연결하기입니다. 검증자가 질문을 낸 뒤 증명자가 기록 자체를 바꾸면 확인의 의미가 사라집니다.</p>
<p className="leading-8">여기서 만드는 작은 프로그램은 가운데의 합 확인 과정을 실행합니다. 마지막 기록을 직접 가지고 대조하므로 완성된 간결 증명 시스템은 아닙니다. 기록을 짧은 약속에 묶는 장치와 그 약속을 여는 증명은 뒤에서 역할을 구분합니다.</p>
</div></section>
<section id="bits" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 1011과 0110을 자리별로 계산합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">오른쪽 끝을 0번 자리로 정합니다. 첫 단어의 네 기록은 [1,1,0,1], 둘째는 [0,1,1,0]입니다. 두 비트가 다르면 1인 XOR는 [1,0,1,1]이므로 다시 왼쪽부터 쓰면 1101입니다. 둘 다 1일 때만 1인 AND는 [0,1,0,0], 즉 0010입니다.</p>
<p className="leading-8">정수로 읽은 11+6은 17, 이진수 10001입니다. 자리 올림이 있는 정수 덧셈과 자리별 XOR를 혼동하면 같은 입력에서 다른 결과가 됩니다. 지금의 네 비트는 해시 전체가 아니라 그 안에 들어갈 수 있는 작은 연산입니다.</p>
</div></section>
<section id="picture" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 네 기록이 마지막 한 점으로 줄어드는 모습을 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">그림의 1은 네 AND 결과를 더한 값입니다. 곧 정할 계산 규칙에서는 1+1=0이므로 이 합은 1의 정수 개수를 그대로 세는 값이 아닙니다. 각 질문을 거칠 때 아직 합해야 하는 주소 비트 하나가 사라지고 마지막에는 5라는 한 값이 남습니다.</p>
</div><BinaryProofJourneyViz/></section>
<section id="why" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 작은 비트를 큰 수의 칸마다 저장하는 비용을 줄입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">큰 소수로 나눈 나머지 계산에 비트 하나를 표현할 수도 있습니다. 그러나 큰 체 원소 한 칸에 실제 정보는 0 또는 1만 들어가면 기록 저장과 처리에서 낭비가 생길 수 있습니다. 비트가 원래 속한 작은 체와 확인에 쓰는 큰 체를 연결하면 이 비용을 줄일 여지가 있습니다.</p>
<p className="leading-8">비트를 묶어 저장하는 일과 그 묶음을 한 번 곱하는 일은 다릅니다. XOR는 묶은 뒤에도 각 자리의 XOR이지만 확장체 곱셈은 여러 자리가 서로 섞입니다. 곧 같은 1011과 0110에서 그 차이를 직접 확인합니다.</p>
<p className="leading-8">증명 비용은 저장 공간만으로 정해지지 않습니다. 다항식을 평가하고 약속을 열고 무작위 질문을 만드는 비용도 있습니다. 이진체를 쓴다는 사실 하나로 모든 계산이 더 빨라진다는 결론은 나오지 않습니다.</p>
</div></section>
<section id="names" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 역할을 본 뒤 체·기록·확장·합 확인의 이름을 붙입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">0과 1에 덧셈 XOR, 곱셈 AND를 정한 것이 F₂입니다. 1+1=0인 성질을 특성 2라고 합니다. 0이 아닌 원소로 나눌 수 있도록 더 많은 원소를 넣은 것이 이진 확장체입니다.</p>
<p className="leading-8">각 주소에 있던 계산값을 모은 표가 계산 기록입니다. 표를 주소 0과 1 밖에서도 계산할 수 있는 다항식으로 확장합니다. 각 주소 변수의 차수가 최대 1이면 다중선형 확장, 영어로 multilinear extension 또는 MLE라고 합니다.</p>
<p className="leading-8">표 위의 합 주장을 한 점의 값 주장으로 줄이는 대화가 sumcheck입니다. 여기서 검증자가 보내는 무작위 체 원소를 challenge라고 부릅니다. 표를 먼저 고정하고 나중에 특정 점의 값을 증명하는 장치가 다항식 약속, PCS입니다.</p>
</div></section>
<section id="tower" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. 같은 비트의 확장체 곱은 1111입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">먼저 u²=u+1이라는 규칙을 추가합니다. 0, 1, u, 1+u의 네 원소를 각각 00, 01, 10, 11로 표시합니다. 다음에는 v²=uv+1을 추가해 네 비트를 1, u, v, uv의 계수로 읽습니다. u는 0010, v는 0100입니다.</p>
<p className="leading-8">이 규칙에서는 1011=1+u+uv, 0110=u+v입니다. 낮은 두 비트와 높은 두 비트로 나누면 각각 (3,2), (2,1)입니다. 여기서 2와 3은 체 원소의 비트 표기이지 정수 2와 3을 반복해서 더한 값이 아닙니다.</p>
<p className="leading-8">두 식을 펼친 뒤 u²=u+1과 v²=uv+1로 줄이면 1+u+v+uv, 즉 1111이 됩니다. 앞에서 구한 비트별 AND 0010과 다릅니다. 네 비트 패킹 뒤의 한 번 곱셈을 네 개의 독립 AND로 바꾸어 쓰면 계산이 틀립니다.</p>
</div><ExplainedFormula question="확장체 곱셈이 비트별 AND와 다른 이유는?" idea="여러 계수끼리 곱한 뒤 v² 항을 낮은 항으로 돌려보냅니다." formula={String.raw`\begin{gathered}a=a_0+a_1v,\quad b=b_0+b_1v\\v^2=1+uv,\quad ab=c_0+c_1v\\c_0=a_0b_0+a_1b_1\\c_1=a_0b_1+a_1b_0+u a_1b_1\\a_0b_0=1,\quad a_1b_1=u\\a_0b_1+a_1b_0=0\\u a_1b_1=1+u\\(1+u+uv)(u+v)\\=(1+u)+(1+u)v\\\operatorname{enc}(ab)=1111_2\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}a=a_0+a_1v,\quad b=b_0+b_1v\\v^2=1+uv,\quad ab=c_0+c_1v\\c_0=a_0b_0+a_1b_1\\c_1=a_0b_1+a_1b_0+u a_1b_1\\a_0b_0=1,\quad a_1b_1=u\\a_0b_1+a_1b_0=0\\u a_1b_1=1+u\\(1+u+uv)(u+v)\\=(1+u)+(1+u)v\\\operatorname{enc}(ab)=1111_2\end{gathered}`} operations={[{"expression": "a_0b_0=1,\\quad a_1b_1=u", "annotation": ["F₄에서 (1+u)u=1, u×1=u입니다. 비트 표기는 1과 2입니다."]}, {"expression": "\\begin{gathered}a_0b_1+a_1b_0=0\\\\u a_1b_1=1+u\\end{gathered}", "annotation": ["교차항은 (1+u)+(1+u)=0입니다. v²를 환원하며 (1+u)v가 추가됩니다."]}]} terms={[{"symbol": "u", "name": "첫 확장 원소", "description": "u²=u+1을 만족합니다."}, {"symbol": "v", "name": "둘째 확장 원소", "description": "v²=uv+1을 만족합니다."}, {"symbol": "aᵢ,bᵢ", "name": "두 비트 계수", "description": "각 계수는 F₄ 원소입니다."}, {"symbol":"c₀,c₁","name":"곱의 두 계수","description":"v²를 환원한 뒤 상수항과 v항에 남는 F₄ 원소입니다."}, {"symbol":"enc","name":"기저의 비트 표기","description":"체 원소의 계수를 1,u,v,uv 순서로 담아 네 비트로 표시합니다."}]} assumptions={["이번 Fan–Paar 기저 1,u,v,uv와 낮은 계수부터 저장하는 순서를 고정합니다.", "모든 +는 특성 2의 덧셈입니다."]} interpretation="비트 표기로 낮은 계수는 1 XOR 2=3, 높은 계수는 0 XOR 3=3입니다. 두 계수의 비트를 합치면 1111입니다."/></section>
<section id="tower-proof" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 왜 이 규칙에서 0이 아닌 값으로 나눌 수 있나요</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">u²+u+1에 F₂의 0과 1을 넣으면 둘 다 1입니다. 근이 없는 이차식이므로 기약입니다. 그 나머지들로 만든 F₄에서는 0이 아닌 모든 원소에 역원이 있습니다.</p>
<p className="leading-8">이어 X²+uX+1에 F₄의 0, 1, u, 1+u를 넣으면 각각 1, u, 1, u입니다. 어느 것도 0이 아니므로 이 이차식도 기약이며 16원소 체가 됩니다. 그 결과 1,u,v,uv가 F₂ 위의 기저가 됩니다.</p>
<p className="leading-8">작은 체의 비트를 낮은 자리에 그대로 놓는 포함 관계는 F₂⊂F₄⊂F₁₆입니다. 원문은 같은 확장을 재귀적으로 만드는 Fan–Paar tower를 제공합니다. 체의 크기가 같아도 다른 기저를 쓰면 같은 비트열의 곱셈 표가 달라질 수 있으므로 기저까지 맞춰야 합니다.</p>
</div></section>
<section id="multilinear" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 네 기록에 주소를 붙여 다항식으로 만듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">주소의 낮은 비트는 x입니다. 높은 비트는 y입니다. 기록 순서는 (0,0), (1,0), (0,1), (1,1)입니다. 첫 표 A=[1,1,0,1]은 a(x,y)=1+y+xy, 둘째 표 B=[0,1,1,0]은 b(x,y)=x+y로 확장됩니다.</p>
<p className="leading-8">예를 들어 a(0,1)=1+1=0이고 a(1,1)=1+1+1=1이므로 원래 셋째와 넷째 기록을 돌려줍니다. 네 꼭짓점의 값이 정해지면 각 변수의 차수가 1 이하인 식은 하나로 정해집니다. 다른 주소 y에 대한 두 끝값을 x로 잇고 그 두 결과를 y로 다시 이으면 됩니다.</p>
<p className="leading-8">AND 계산을 확인할 때는 g(x,y)=a(x,y)b(x,y)를 씁니다. g는 각 변수의 차수가 최대 2입니다. AND 결과표 자체의 MLE c(x,y)=x(1+y)와는 다른 식입니다. 네 꼭짓점에서는 같지만 뒤의 (u,v)에서는 g=5, c=10입니다. 표의 곱과 확장한 식의 곱을 구분해야 합니다.</p>
</div><ExplainedFormula question="표를 어떻게 0과 1 밖으로 확장하나요?" idea="두 끝값을 잇는 식을 주소 비트마다 한 번 적용합니다." formula={String.raw`\begin{gathered}L_x(p_0,p_1)=p_0+(p_1-p_0)x\\L_0(p_0,p_1)=p_0\\L_1(p_0,p_1)=p_1\\\widetilde f(x,y)=L_y\bigl(L_x(f_{00},f_{10}),\\L_x(f_{01},f_{11})\bigr)\\a(x,y)=1+y+xy\\b(x,y)=x+y\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}L_x(p_0,p_1)=p_0+(p_1-p_0)x\\L_0(p_0,p_1)=p_0\\L_1(p_0,p_1)=p_1\\\widetilde f(x,y)=L_y\bigl(L_x(f_{00},f_{10}),\\L_x(f_{01},f_{11})\bigr)\\a(x,y)=1+y+xy\\b(x,y)=x+y\end{gathered}`} operations={[{"expression": "L_0(p_0,p_1)=p_0", "annotation": ["주소 0은 첫 기록을 돌려줍니다."]}, {"expression": "L_1(p_0,p_1)=p_1", "annotation": ["주소 1은 둘째 기록을 돌려줍니다."]}]} terms={[{"symbol": "x,y", "name": "기록 주소와 평가점", "description": "처음에는 비트이며 나중에는 확장체 원소를 넣습니다."}, {"symbol": "L", "name": "선형 보간", "description": "두 끝값을 잇는 차수 1 이하의 식입니다."}]} assumptions={["특성 2에서는 뺄셈과 덧셈이 같습니다.", "기록의 주소 순서는 낮은 비트 x부터입니다."]} interpretation="첫 표의 y=0인 줄은 상수 1, y=1인 줄은 x이므로 1+(x+1)y입니다."/></section>
<section id="sumcheck" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 첫 질문에서 주소 비트 하나를 없앱니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">처음 주장은 네 AND 값의 합 S=0+1+0+0=1입니다. 이 합은 체에서 계산하므로 1의 개수가 짝수면 0이 될 수 있습니다. 정수 개수를 증명하려면 별도 인코딩과 조건이 필요합니다.</p>
<p className="leading-8">증명자는 먼저 g₁(t)=g(t,0)+g(t,1)을 보냅니다. g(t,0)=t이고 g(t,1)=t(t+1)이므로 g₁(t)=t²입니다. 검증자는 차수가 2 이하인지와 g₁(0)+g₁(1)=1인지 확인합니다.</p>
<p className="leading-8">이 메시지를 받은 뒤 검증자가 r₁=u를 고르면 다음 주장은 g₁(u)=u²=u+1, 비트 표기로 3이 됩니다. x에 대한 합을 없애고 x=u인 줄의 y 합만 남겼습니다. 지금 u는 계산을 보여 주기 위한 고정값이며 실제 절차에서는 메시지 뒤에 정한 분포로 질문해야 합니다.</p>
</div><ExplainedFormula question="전체 합 주장이 한 줄의 합 주장으로 어떻게 바뀌나요?" idea="보낸 일변수 식의 두 끝값을 확인한 뒤 새 점을 고릅니다." formula={String.raw`\begin{gathered}S=\sum_{x,y\in\{0,1\}}g(x,y)=1\\g_1(t)=\sum_{y\in\{0,1\}}g(t,y)\\t+(t^2+t)=t^2\\g_1(0)+g_1(1)=1\\r_1=u\ \Longrightarrow\ S_1=u+1\\g_1(u)=u^2=u+1\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}S=\sum_{x,y\in\{0,1\}}g(x,y)=1\\g_1(t)=\sum_{y\in\{0,1\}}g(t,y)\\t+(t^2+t)=t^2\\g_1(0)+g_1(1)=1\\r_1=u\ \Longrightarrow\ S_1=u+1\\g_1(u)=u^2=u+1\end{gathered}`} operations={[{"expression": "t+(t^2+t)=t^2", "annotation": ["특성 2에서 두 t가 상쇄됩니다."]}, {"expression": "g_1(u)=u^2=u+1", "annotation": ["첫 질문 뒤의 새 주장은 원래 정수 1과 다릅니다."]}]} terms={[{"symbol": "g", "name": "두 확장식의 곱", "description": "각 변수의 차수는 최대 2입니다."}, {"symbol": "S₁", "name": "질문 뒤의 새 합", "description": "x=u로 고정한 줄에서 아직 y를 합합니다."}]} assumptions={["각 라운드 메시지의 차수 제한을 검사합니다.", "질문을 미리 공개한 고정 시험을 보안 실험으로 해석하지 않습니다."]} interpretation="네 점의 합 확인이 두 점의 합 확인으로 줄었습니다."/></section>
<section id="second" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 둘째 질문은 마지막 한 점 5를 남깁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">x=u를 넣으면 a(u,t)=1+(u+1)t, b(u,t)=u+t입니다. 곱을 펼칠 때 t의 계수는 1+u(u+1)=0입니다. 따라서 둘째 메시지는 g₂(t)=u+(u+1)t²입니다.</p>
<p className="leading-8">g₂(0)=u, g₂(1)=1이므로 두 끝값의 합은 앞 단계의 u+1과 같습니다. 둘째 질문 r₂=v를 넣으면 v²=1+uv를 써서 g₂(v)=1+v, 즉 5를 얻습니다.</p>
<p className="leading-8">같은 한 점에서 a(u,v)=1+v+uv=13, b(u,v)=u+v=6입니다. 확장체의 곱 13×6=5가 마지막 주장과 같습니다. 앞의 packed 단어 11×6=15와 입력이 다릅니다. 여기서는 원래 표를 (u,v)에서 평가한 값 13을 곱했습니다.</p>
</div></section>
<section id="source" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 원문의 Sumcheck에 같은 네 기록을 넣습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">실행한 소스는 IrreducibleOSS/binius-models의 7ac5ad72 커밋, 패키지 0.1.0입니다. A와 B를 네 원소 배열로 넣고 composition을 두 값의 곱으로 정합니다. 기본 high_to_low=False는 앞에서 정한 낮은 주소 비트부터 처리하는 순서입니다.</p>
<p className="leading-8">compute_round_polynomial은 계수를 보내지 않고 평가값을 보냅니다. 차수 2인 이번 예에서는 비트 표기로 1과 2인 점의 값만 반환합니다. 첫 반환은 [1,3]입니다. 2는 여기서 u이며 정수 2를 체에 더해 넣은 0이 아닙니다.</p>
<p className="leading-8">0에서의 값은 기존 합과 1에서의 값을 더해 0으로 복원합니다. 세 평가값 [0,1,3]을 interpolate에 넣으면 질문 u에서 3을 얻습니다. receive_challenge는 원문의 비용 모형에 따라 중간 가중치를 쌓거나 표를 접습니다. 이번 첫 단계에서는 원래 표가 아직 남고 둘째 단계에서 최종 [13]과 [6]으로 줄어듭니다.</p>
<p className="leading-8">둘째 반환은 [1,0]이며 기존 주장 3으로 0에서의 값 2를 복원해 [2,1,0]을 만듭니다. 질문 v에서 5를 얻고 query의 최종 곱도 5인지 비교했습니다. query는 여기서 가진 표의 계산일 뿐 PCS를 여는 증명이 아닙니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("init",codeRefs["init"]) } label="원문 배열과 차수 설정"/>
<CodeViewButton onClick={()=>sidebar.open("round",codeRefs["round"]) } label="원문 라운드 메시지"/>
<CodeViewButton onClick={()=>sidebar.open("fold",codeRefs["fold"]) } label="원문 질문 반영"/>
<CodeViewButton onClick={()=>sidebar.open("interpolate",codeRefs["interpolate"]) } label="원문 보간과 마지막 query"/>
<CitationBlock source="binius-models · 선택한 원문 정의" citeKey={1} href="https://github.com/IrreducibleOSS/binius-models/tree/7ac5ad72f2ba38740fe1122c16b94bcdbe7bcecf"><p className="leading-8">원문의 Sumcheck와 FanPaarTowerField 정의에 같은 입력을 대입했습니다. 선택 모듈 실행과 전체 패키지 실행의 차이는 22절에 기록합니다.</p>
</CitationBlock></section>
<section id="source-field" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 체 곱셈 원문은 낮은 체의 세 곱을 재사용합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">FanPaarTowerField(2)는 확장 높이 2, 즉 4비트 원소를 만드는 설정입니다. fanpaar_multiply_recursive는 a₀b₀, a₁b₁, (a₀+a₁)(b₀+b₁)의 세 곱으로 교차항을 얻습니다. 곱셈을 줄이는 Karatsuba 방식이지만 마지막에는 이 체의 환원 규칙을 적용해야 합니다.</p>
<p className="leading-8">원래 1011과 0110을 넣으면 z₀=1, z₂=2, 교차항 z₁=0입니다. z₂에 u를 곱한 값은 3이므로 반환한 낮은 계수는 1+2=3, 높은 계수는 0+3=3입니다. 원문의 from_subfield_tuple이 이를 다시 1111로 묶습니다.</p>
<p className="leading-8">가장 아래 F₂에서는 곱셈이 한 비트 AND로 끝납니다. 여러 층의 곱셈을 재귀적으로 내려가서 AND를 쓴다는 사실은 최상층의 네 비트 곱 전체가 단순 AND라는 뜻이 아닙니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("tower",codeRefs["tower"]) } label="원문 체 표현과 XOR"/>
<CodeViewButton onClick={()=>sidebar.open("multiply",codeRefs["multiply"]) } label="원문 재귀 곱셈과 환원"/>
<CodeViewButton onClick={()=>sidebar.open("execute",codeRefs["execute"]) } label="실제로 실행한 별도 호출 예제"/>
</section>
<section id="soundness" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. 질문을 0과 1에서만 고르면 거짓 식을 구분하지 못합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">첫 메시지 t² 대신 t를 보냈다고 해 봅시다. 둘 다 0과 1에서 같은 값이고 두 끝값의 합도 1입니다. 차이 다항식 t²+t는 비영이지만 F₂의 모든 점에서 0입니다. 질문을 계속 0과 1 중에서만 뽑으면 이 차이를 볼 수 없습니다.</p>
<p className="leading-8">F₁₆에서 같은 차이식의 근은 여전히 0과 1뿐입니다. 메시지가 먼저 고정되고 16원소에서 균등하게 질문하면 이 고정된 차이를 놓칠 확률은 2/16=1/8입니다. 질문 u에서는 u²+u=1이어서 차이가 드러납니다.</p>
<p className="leading-8">이는 한 차이식에 대한 계산입니다. 실제 sumcheck의 전체 오류 확률은 라운드별 조건과 마지막 값 확인을 함께 봐야 합니다. 각 변수 차수가 d 이하이고 m번의 독립 균등 질문을 메시지 뒤에 고르며 마지막 값을 올바르게 확인할 때 표준 상한은 md/|F|입니다. 작은 m=2,d=2,F₁₆에서는 1/4로 너무 큽니다.</p>
<p className="leading-8">실제 시스템은 더 큰 체와 별도의 보안 매개변수를 씁니다. 프로토콜에 따라 질문 일부를 특수하게 정하는 최적화도 있지만 그 설계의 별도 분석이 필요합니다. 여기의 균등 질문 상한을 그대로 가져와 붙일 수는 없습니다.</p>
</div></section>
<section id="zerocheck" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">15. 오류가 두 개면 단순 합에서 사라질 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">AND 결과표를 잘못 제출해 자리별 오류가 [1,1,0,0]이라고 합시다. 합은 1+1=0이지만 두 자리는 틀렸습니다. 모든 제약이 맞음을 확인하려면 오류의 단순 합만 검사해서는 안 됩니다.</p>
<p className="leading-8">이 오류표의 MLE는 1+y입니다. 무작위 주소 (rₓ,rᵧ)에 맞춘 가중치로 네 오류를 더하면 이 식의 평가값을 얻습니다. 같은 rᵧ=v를 넣으면 1+v=5여서 0이 아닙니다. 고정한 이 오류표는 균등한 rᵧ가 1일 때만 이 가중 평가에서 가려집니다.</p>
<p className="leading-8">가중치 eq(r,b)는 Boolean 주소 b에서 원하는 꼭짓점을 고르는 보간 기저의 곱입니다. 실제 zerocheck는 이런 가중 합이 0인지 sumcheck로 줄인 뒤 원래 기록과의 연결도 확인합니다. 임의로 바꾼 오류표를 질문 뒤에 고르게 해 주면 이 설명의 확률 조건이 무너집니다.</p>
</div><ExplainedFormula question="합이 0인 오류표를 어떻게 드러내나요?" idea="모든 자리를 같은 가중치로 더하지 않고 주소마다 다른 가중치를 줍니다." formula={String.raw`\begin{gathered}q_i=b_ir_i+(1-b_i)(1-r_i)\\\operatorname{eq}(r,b)=\prod_i q_i\\\widetilde E(r)=\sum_{b\in\{0,1\}^2}E(b)\operatorname{eq}(r,b)\\E=[1,1,0,0],\quad 1+1=0\\\widetilde E(r)=1+r_y\\\widetilde E(u,v)=1+v\\\widetilde E(u,v)=5\ne0\end{gathered}`} annotatedFormula={String.raw`\begin{gathered}q_i=b_ir_i+(1-b_i)(1-r_i)\\\operatorname{eq}(r,b)=\prod_i q_i\\\widetilde E(r)=\sum_{b\in\{0,1\}^2}E(b)\operatorname{eq}(r,b)\\E=[1,1,0,0],\quad 1+1=0\\\widetilde E(r)=1+r_y\\\widetilde E(u,v)=1+v\\\widetilde E(u,v)=5\ne0\end{gathered}`} operations={[{"expression": "1+1=0", "annotation": ["두 개의 오류가 같은 가중치로 더해지면 사라집니다."]}, {"expression": "\\widetilde E(u,v)=5\\ne0", "annotation": ["같은 오류표를 확장체 주소에서 평가하면 이 질문에서는 드러납니다."]}]} terms={[{"symbol": "E", "name": "자리별 오류표", "description": "정한 제약의 왼쪽과 오른쪽의 차이입니다."}, {"symbol": "eq", "name": "주소별 보간 가중치", "description": "Boolean 꼭짓점 값을 확장하는 기저입니다."}, {"symbol":"bᵢ,rᵢ,qᵢ","name":"주소와 질문의 한 좌표","description":"bᵢ는 기록 주소의 비트, rᵢ는 질문의 체 원소, qᵢ는 그 좌표에서 만드는 보간 가중치입니다."}]} assumptions={["기록과 제약은 질문 전에 고정되어야 합니다.", "가중 합 확인과 최종 기록 연결의 오류도 따로 계산합니다."]} interpretation="계산이 모두 맞다는 주장과 계산값들의 합이 0이라는 주장은 다릅니다."/></section>
<section id="commitment" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">16. 마지막 5가 처음 고정한 기록에서 나왔는지 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">정직한 프로그램은 실제 A와 B를 접어서 13과 6을 얻었습니다. 하지만 외부 증명자가 마지막에 두 수를 임의로 고르면 곱 5만 맞추는 다른 값을 낼 수 있습니다. 따라서 마지막 평가를 처음 고정한 다항식 약속에 연결해야 합니다.</p>
<p className="leading-8">PCS는 기록을 약속한 뒤 특정 점의 값이 그 기록과 일치하는지 확인하는 역할을 맡습니다. 여기에 기록이 정말 0과 1로 이루어졌는지, 회로의 각 연결과 공개 결과가 맞는지도 필요합니다. 단순히 확장체에 기록을 넣었다고 비트 범위가 저절로 증명되지는 않습니다.</p>
<p className="leading-8">대화를 비대화형으로 바꾸는 Fiat–Shamir는 앞선 메시지와 문맥을 해시해 질문을 만드는 방식입니다. 메시지 순서, 길이, 용도 구분을 포함한 정확한 transcript와 그 모델의 보안 분석이 필요합니다. 이 글의 고정 u,v 실행은 해당 변환을 구현하지 않습니다.</p>
</div></section>
<section id="binius" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">17. Binius라는 이름 아래 서로 다른 판과 구현을 구분합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">원래 Binius 논문은 작은 체의 기록을 큰 체 원소 하나씩으로 불필요하게 늘리지 않는 다항식 약속을 제안합니다. 2025년 최종 출판판은 Brakedown을 바탕으로 설명합니다. 후속 FRI-Binius와 모든 세부가 같은 프로토콜이라고 읽으면 안 됩니다.</p>
<p className="leading-8">이번 Python 저장소는 이해하기 쉬운 수학 모델과 최소 FRI-Binius 구현을 제공한다고 설명합니다. 여기서 실행한 것은 그 안의 Fan–Paar 체와 기본 sumcheck입니다. 원래 Binius Rust 저장소는 2025년 9월 보관 상태가 되었고 후속 Binius64는 64비트 단어 연산 회로와 CPU 구현에 초점을 맞춥니다.</p>
<p className="leading-8">작은 기록 체와 큰 질문 체를 연결하는 아이디어는 공통적으로 중요하지만 체 기저, 약속 방식, 회로 표현, 구현 버전은 각각 확인해야 합니다. 이번 4비트 실행을 Binius64 전체를 실행한 결과로 확대하지 않습니다.</p>
</div><CitationBlock source="Diamond·Posen · Binius 최종 출판판" citeKey={2} href="https://eprint.iacr.org/2023/1784"><p className="leading-8">2025-04-27 최종판의 공식 초록과 PDF 도입부·기술 개요를 읽었습니다. 전체 보안 증명은 재검증하지 않았습니다.</p>
</CitationBlock><CitationBlock source="Binius64 · 고정한 후속 구현 README" citeKey={3} href="https://github.com/binius-zk/binius64/tree/6a179536d90fcc76eeca0cee4e059f5e17efb459"><p className="leading-8">후속 구현의 목표와 공개된 인터페이스 설명을 읽었습니다. 이번 검산에서 전체 구현은 빌드하거나 실행하지 않았습니다.</p>
</CitationBlock></section>
<section id="flock" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">18. Flock은 같은 회로의 반복과 반복 사이 연결을 함께 다룹니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">Flock의 2026년 7월 arXiv v1은 같은 Boolean 회로의 여러 실행을 묶습니다. 제약 행렬의 반복 구조를 이용하고 기록을 묶어 처리합니다. 각 해시 계산이 맞는다는 주장만으로 앞 해시의 출력이 다음 해시의 입력이라는 연결까지 보장되지는 않습니다. v1의 4.6절은 이 연결과 공개 끝점을 따로 다룹니다.</p>
<p className="leading-8">고정한 Flock 원문의 satisfies는 각 자리에서 ai &amp; bi == ci를 검사합니다. packed 경로도 낮은 64비트와 높은 64비트에 각각 비트별 AND를 씁니다. 같은 표 [1,1,0,1]과 [0,1,1,0]에는 [0,1,0,0]이 맞는 구조입니다. 이것은 128비트 체 원소의 일반 곱셈으로 바꾸는 자리가 아닙니다.</p>
<p className="leading-8">원문 프로토콜 경로는 C=I 형태를 사용합니다. 이 코드 읽기를 일반 회로를 해당 형태로 바꾸는 과정이나 완전한 증명 실행과 혼동하면 안 됩니다. 이번에는 이 파일의 구조와 두 검사 경로를 읽었으며 Flock을 실행하지 않았습니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("flock",codeRefs["flock"]) } label="Flock 원문의 자리별 제약 검사"/>
<CodeViewButton onClick={()=>sidebar.open("flock-packed",codeRefs["flock-packed"]) } label="Flock 원문의 packed AND 검사"/>
<CitationBlock source="Flock · arXiv 2607.27491v1" citeKey={4} href="https://arxiv.org/html/2607.27491v1"><p className="leading-8">실제 PDF의 1.1·2·3·4.1·4.6·5절을 읽었습니다. v1은 간결성에 초점을 맞추며 영지식은 제공하지 않는다고 명시합니다.</p>
</CitationBlock></section>
<section id="measurements" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">19. 성능 표에는 단위와 비교 기능이 함께 붙습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">Flock v1의 SHA-256 수치는 M4 Max에서 초당 압축함수 수입니다. 단일 스레드 42.1k는 batch 2¹⁴, 10스레드 338k는 batch 2¹⁶의 값입니다. 메모리 36GB 환경에서 예열 후 세 실행 중 최고값을 택했습니다. 임의 길이 파일 전체의 해시 수나 여기서 직접 측정한 값이 아닙니다.</p>
<p className="leading-8">같은 표의 비교 구현 일부는 영지식을 제공하지만 Flock v1은 제공하지 않습니다. 기능 차이를 빼고 속도만 비교하면 필요한 요구를 놓칠 수 있습니다. 9월 19일 수정 ePrint와 현재 저장소의 별도 장비·인코더 결과도 이 7월 표와 섞지 않습니다.</p>
</div><CitationBlock source="Flock · 후속 ePrint 2026/1329" citeKey={5} href="https://eprint.iacr.org/2026/1329"><p className="leading-8">공식 초록과 2026-09-19 수정일을 확인했습니다. 이 수정판 PDF는 접근 오류로 읽지 못했으므로 여기의 자세한 설명과 표는 명시한 arXiv v1에 한정합니다.</p>
</CitationBlock></section>
<section id="selection" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">20. 해시와 증명 방식을 함께 결정할 수도 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">이미 정한 SHA 계열 출력을 유지해야 한다면 같은 비트 연산을 더 잘 표현하는 증명 방식을 검토할 수 있습니다. 새 프로토콜이 해시를 선택할 수 있다면 체 연산에 맞는 해시가 다른 비용을 줄일 수 있습니다. 기존 데이터와의 호환성부터 확인해야 합니다.</p>
<p className="leading-8">2026년 Poseidonb·Poseidon2b는 이진 확장체에 맞춰 해시와 증명 환경을 함께 설계하는 방향도 보여 줍니다. 따라서 선택을 기존 해시 또는 소수체 해시라는 두 칸으로만 나눌 필요는 없습니다. 해당 설계의 수정판·행렬·라운드·공격 목표를 별도로 검토해야 합니다.</p>
<p className="leading-8">예전보다 더 많은 축소 라운드를 다룬 공격이 나왔다는 사실은 전체 라운드 해독과 다릅니다. 가령 설명용 전체 80라운드에서 같은 공격 모델의 도달 범위가 30에서 55로 바뀌면 단순 간격은 50에서 25로 줄어듭니다. 이 간격은 보안 비트 수가 아니며 서로 다른 목표와 모드의 공격을 이 숫자로 비교해서도 안 됩니다.</p>
</div><CitationBlock source="Poseidon(2)b · 수정 ePrint 2025/1893" citeKey={6} href="https://eprint.iacr.org/2025/1893"><p className="leading-8">공식 초록과 2026-02-06의 128비트 Binius 구현 수정 안내를 확인했습니다. 논문 전문과 실제 이진체 해시 구현은 이번에 실행하거나 검증하지 않았습니다.</p>
</CitationBlock><p className="mt-4 leading-8"><Link className="text-primary underline" to="/cs/crypto/poseidon-hash#binary">Poseidon 글의 이진 확장체 설계와 후속 공격 범위</Link>도 같은 조건으로 연결해 읽을 수 있습니다.</p></section>
<section id="encoding" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">21. 비트 표기 11과 정수 11을 체에 넣는 함수는 다릅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">원문에서 E(11)은 비트열 1011을 담는 생성자입니다. 반면 E.from_int(11)은 정수 11을 특성 2의 체에 넣으므로 11 mod 2=1을 반환합니다. 두 인터페이스를 바꾸면 처음부터 다른 입력입니다.</p>
<p className="leading-8">from_bytes는 이 작은 설정에서 바이트 길이를 확인하지만 남는 높은 비트까지 정규 범위로 검사하지 않습니다. 실제로 한 바이트 ff는 내부값 255로 읽히며 _is_valid는 이를 F₁₆의 유효 표기로 보지 않습니다. 이 수학 모델을 외부 입력용 정규 파서라고 가정하면 안 됩니다.</p>
<p className="leading-8">별도 호출 예제에서는 한 바이트인지, 값이 0부터 15인지 먼저 검사합니다. 바이트 순서와 체 기저도 정합니다. 실제 프로토콜은 공개 입력, 비트 수, 같은 회로를 묶는 순서와 연결 관계를 함께 고정해야 합니다.</p>
</div><CodeViewButton onClick={()=>sidebar.open("encoding",codeRefs["encoding"]) } label="원문의 from_int와 from_bytes"/>
<CodeViewButton onClick={()=>sidebar.open("checks",codeRefs["checks"]) } label="별도 범위 검사와 반례 검산"/>
</section>
<section id="verification" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">22. 어디까지 실제 실행했는지 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">CPython 3.12.13에서 고정 원문의 체와 Sumcheck 정의를 실행했습니다. tower.py의 사용하지 않는 세 체 클래스와 galois.GF import만 AST 로딩에서 제외했습니다. 선택한 함수 본문은 바꾸지 않았고 원문 파일 전체와 SHA를 별도로 보존했습니다. 전체 패키지나 그 의존성 묶음을 실행한 것은 아닙니다.</p>
<p className="leading-8">별도의 단순 다항식 곱셈 모형으로 16×16개의 체 곱과 15개의 역원을 비교했습니다. 두 질문의 16×16 조합에서 원문 sumcheck의 마지막 값이 독립 MLE 곱과 같은지 확인했습니다. u,v 경로는 1→3→5이며 최종 표는 [13]과 [6]입니다.</p>
<p className="leading-8">잘못된 첫 식의 근 0과 1, 오류표의 값 5, AND 결과표 MLE의 다른 값 10, 정수 생성자와 비트 생성자의 차이, 0의 역원 거부 및 네 가지 잘못된 인코딩도 검사했습니다. 이는 작은 사례의 실행 일치 확인이며 악의적인 모든 증명자에 대한 보안 증명은 아닙니다.</p>
<p className="leading-8">PCS의 commit/open, Fiat–Shamir, Binius64와 Flock의 증명·검증, 영지식, 성능 및 양자 공격 모델은 실행하거나 입증하지 않았습니다. 해시 기반 구성이라는 말만으로 모든 양자 보안 요구가 자동 충족된다고 결론 내리지 않습니다.</p>
</div></section>
<section id="boundaries" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">23. 같은 입력에서 무엇이 달라질지 예측합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="leading-8">계산 기록은 작은 체에 두고 질문은 더 큰 체에서 하는 이유를 보았습니다. 다만 큰 체 곱셈이 비트별 AND가 되는 것은 아니고, 합 확인 하나가 모든 제약과 기록의 일치까지 보장하지도 않습니다.</p>
<p className="leading-8">먼저 1011과 0110을 확장체 곱셈에 넣으면 0010 대신 어떤 결과가 되는지 예상해 보세요. 다음으로 첫 메시지 t²를 t로 바꾸고 질문을 0과 1에만 제한하면 오류가 드러나는지 생각해 보세요. 마지막으로 오류 두 개의 합이 0이라는 사실이 계산의 정확성을 뜻하는지 설명해 보세요.</p>
</div><ReviewPrompts questions={["1011과 0110의 확장체 곱이 비트별 AND와 다른 이유는 무엇인가요? (답: 7절)","첫 메시지 t² 대신 t를 보내고 질문을 F₂에만 제한하면 무엇이 보이지 않나요? (답: 14절)","오류표 [1,1,0,0]의 합이 0이어도 틀린 계산을 드러내려면 무엇이 필요한가요? (답: 15절)"]}/></section>
<CodeSidebar codeRefKey={sidebar.codeRefKey} codeRef={sidebar.codeRef} onClose={sidebar.close} onNavigate={sidebar.navigate} codeRefs={codeRefs} fileTrees={fileTrees} projectMetas={projectMetas}/></div>}
