import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { MysticetiDecisionViz, MysticetiPatternViz } from "./viz/ModernMysticetiViz";

export default function ModernMysticetiArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">Uncertified DAG · ordering and fast path</p><h2 className="text-3xl font-bold tracking-tight">Mysticeti는 별도 block certificate round를 없애고 later blocks의 causal pattern을 vote로 읽는다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">Alice→Bob transaction이 signed block에 들어갔다고 하겠습니다. Narwhal 계열은 block/header에 votes를 모아 explicit certificate를 만든 뒤 DAG vertex로 사용합니다. Mysticeti-C는 매 round의 signed blocks가 이전 blocks를 참조하는 DAG 자체에서 support·vote·certificate pattern을 읽습니다. 이 때문에 block마다 별도 certificate를 방송하는 round를 줄이면서 leader slot을 commit·skip·undecided로 판정할 수 있습니다.</p>
      <p>그렇다고 raw reference 하나가 certificate가 되는 것은 아닙니다. Block signature, epoch·round·author, ancestor structure와 previous-round parent quorum을 검증한 뒤, 같은 author가 equivocate할 때 어떤 block을 처음 support했는지도 deterministic하게 계산해야 합니다. 이후 UniversalCommitter가 오래된 slot부터 연속 결정 prefix만 내보내고 Linearizer가 committed leader의 새 causal sub-DAG를 한 번씩 출력합니다.</p>
      <MysticetiPatternViz />
      <aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> “Uncertified”는 검증이 없다는 뜻이 아니라 per-block standalone certificate를 만들지 않는다는 뜻입니다. Consensus order, Mysticeti-FPC transaction fast execution, Sui checkpoint finality는 서로 다른 receipts입니다.</aside>
    </section>

    <section id="uncertified-votes" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · support, vote, certificate pattern</p><h2 className="mt-2 text-2xl font-bold">각 author의 first-supported block만 세어 equivocation을 quorum 두 곳에 중복 사용하지 않는다</h2></header>
      <p>Round r의 leader slot에 L과 L′이라는 conflicting blocks가 있다고 하겠습니다. Round r+1의 validator block이 causal ancestry에서 처음 지지한 leader block이 그 validator의 vote가 됩니다. 같은 author의 later references를 두 후보에 모두 세지 않으며, canonical traversal로 first support를 정합니다. Round r+2 blocks가 quorum의 vote blocks를 parents로 담으면 leader에 대한 certificate pattern을 만들 수 있습니다. Distinct voting power와 valid ancestry가 핵심이며 local arrival order는 의미가 없습니다.</p>
      <ExplainedFormula question="Mysticeti의 implicit certificate pattern에서 왜 distinct-author quorum과 first support를 함께 검사하는가?" idea={<>Signed later blocks가 leader vote를 운반하므로 각 author의 최초 causal support를 하나만 선택하고 그 distinct voting power를 더해야 합니다. 그래야 equivocation 두 후보가 같은 author stake를 동시에 사용하지 못합니다.</>} formula={String.raw`\begin{aligned}F(a)&=\operatorname{firstSupport}(B_a)\\V(L)&=\{a:F(a)=L\}\\\sum_{a\in V(L)}w(a)&\ge 2f+1\end{aligned}`} terms={[{symbol:"L",name:"leader block",description:"정해진 leader slot의 signed block candidate입니다."},{symbol:"Bₐ",name:"later block by author a",description:"Leader 뒤 round에서 a가 만든 검증된 block입니다."},{symbol:"F(a)",name:"canonical first support",description:"Causal ancestry에서 같은 slot 후보 중 protocol rule이 처음 지지로 인정한 block입니다."},{symbol:"V(L)",name:"distinct supporter set",description:"Leader L을 처음 지지한 중복 없는 authors의 집합입니다."},{symbol:"w(a)",name:"voting power",description:"Pinned committee에서 author a가 가진 검증 weight입니다."}]} assumptions={["설명을 위한 equal-weight n=3f+1 표기이며 current implementation은 committee voting power와 protocol config를 사용합니다.","Block signature·epoch·round·author·ancestor quorum과 causal links를 먼저 검증합니다.","같은 author의 equivocating blocks를 중복 집계하지 않고 deterministic traversal을 사용합니다.","Vote/certificate pattern은 leader decision evidence이며 application execution receipt가 아닙니다."]} interpretation="n=4,f=1에서 세 distinct authors의 valid vote pattern은 quorum입니다. Author A의 두 blocks를 A와 A′ 두 표로 세면 안 되며, L과 L′에 A의 stake를 동시에 더해서도 안 됩니다." />
      <p>Negative test는 같은 author-round에 두 digests를 만들고 node마다 반대 arrival order로 넣습니다. 두 nodes는 canonical ancestry traversal로 author당 하나의 supported leader만 계산하고 어느 candidate도 duplicate stake를 얻지 않아야 합니다. Wrong epoch, invalid signature, missing previous-round parent quorum과 malformed ancestor는 DAG state를 바꾸기 전에 거절합니다.</p>
      <div id="paper-mysticeti"><CitationBlock source="Mysticeti: Reaching the Limits of Latency with Uncertified DAGs" citeKey={1} href="https://arxiv.org/abs/2310.14821"><p><strong>문제:</strong> Certified DAG의 per-block certificate round를 없애면서 low-latency BFT order와 transaction fast path를 만들어야 합니다.</p><p><strong>기여:</strong> Mysticeti-C direct·indirect slot decisions와 DAG에 vote를 포함하는 Mysticeti-FPC를 제시합니다.</p><p><strong>전제:</strong> n=3f+1 Byzantine committee, authenticated signed blocks와 논문의 timing·liveness·object-conflict model을 사용합니다.</p><p><strong>근거 범위:</strong> Mysticeti-C/FPC constructions, safety·liveness argument와 paper evaluation에 한정합니다.</p><p><strong>말하지 않는 것:</strong> 논문의 throughput·0.5초 결과나 모든 FPC option이 current Sui deployment에서 항상 활성이라는 뜻은 아닙니다.</p></CitationBlock></div>
    </section>

    <section id="decision-linearize" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · direct, indirect, decided prefix</p><h2 className="mt-2 text-2xl font-bold">오래된 undecided slot이 있으면 newer commit도 보류해 모든 replica의 prefix를 지킨다</h2></header>
      <p>Commit pattern이 충분하면 leader slot을 direct commit하고, 충분한 non-support 또는 blame pattern이면 direct skip합니다. 어느 쪽 evidence도 충분하지 않으면 undecided입니다. 이는 실패나 임의 선택이 아니라 미래의 decided anchor를 기다리는 안전한 상태입니다. Later committed anchor가 older leader와 certified causal link를 가지면 indirect commit하고, 해당 link가 없음을 protocol rule로 판정하면 indirect skip할 수 있습니다.</p>
      <MysticetiDecisionViz />
      <p>UniversalCommitter는 여러 leader deciders의 결과를 slot 순서로 합쳐 longest contiguous decided prefix만 consumer에게 줍니다. <code>[commit L1, skip L2, undecided L3, commit L4]</code>라면 L1·L2까지만 외부화합니다. L4를 먼저 출력하면 나중에 L3이 indirect commit될 때 stable order 앞에 새 sub-DAG를 끼워야 하므로 replicas가 갈릴 수 있습니다.</p>
      <p>결정된 leader는 Linearizer가 causal ancestors를 거슬러 올라가 이미 committed한 blocks를 제외하고 stable order로 펼칩니다. Commit digest에는 sequence boundary를 묶어 restart 때 같은 sub-DAG output을 재구성하게 합니다. Leader schedule, wave length와 leaders 수는 versioned ProtocolConfig이므로 paper의 예를 current mainnet 상수로 옮겨 적지 않습니다.</p>
      <div id="paper-sui-committer-v1772"><CitationBlock source="Sui mainnet-v1.77.2 — base_committer.rs" citeKey={2} type="code" href="https://github.com/MystenLabs/sui/blob/mainnet-v1.77.2/consensus/core/src/base_committer.rs"><p><strong>문제:</strong> Uncertified DAG에서 leader slot의 support·blame·direct/indirect decision을 deterministic하게 판정해야 합니다.</p><p><strong>기여:</strong> Support traversal, vote/certificate patterns, direct commit·skip과 anchor-based indirect decision을 구현합니다.</p><p><strong>전제:</strong> Sui mainnet-v1.77.2 exact tag commit 51d177a와 matching Committee·ProtocolConfig·DagState를 사용합니다.</p><p><strong>근거 범위:</strong> 이 pinned current Sui consensus leader-decision implementation에 한정합니다.</p><p><strong>말하지 않는 것:</strong> 논문의 모든 pseudocode parameter, future mainnet config나 application execution을 고정하지 않습니다.</p></CitationBlock></div>
      <div id="paper-sui-linearizer-v1772"><CitationBlock source="Sui mainnet-v1.77.2 — UniversalCommitter and Linearizer" citeKey={3} type="code" href="https://github.com/MystenLabs/sui/tree/mainnet-v1.77.2/consensus/core/src"><p><strong>문제:</strong> Multiple leader decisions를 contiguous prefix와 duplicate-free committed sub-DAG sequence로 전달해야 합니다.</p><p><strong>기여:</strong> UniversalCommitter, Linearizer, block validation과 transaction vote tracking의 pinned implementation을 제공합니다.</p><p><strong>전제:</strong> mainnet-v1.77.2 exact tag, matching protocol config와 persisted DagState/commit chain을 사용합니다.</p><p><strong>근거 범위:</strong> Pinned Sui consensus core의 decision prefix, sub-DAG output과 fast-path vote integration입니다.</p><p><strong>말하지 않는 것:</strong> Application execution success, checkpoint durability나 모든 feature flag activation을 자동 보장하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="release" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · FPC·failure·release</p><h2 className="mt-2 text-2xl font-bold">Fast execution receipt와 consensus commit·checkpoint finality를 같은 완료 상태로 표시하지 않는다</h2></header>
      <p>Mysticeti-FPC는 transaction votes와 object-conflict exclusion을 DAG에 실어 특정 path에서 consensus order보다 먼저 실행할 수 있게 합니다. 그러나 실행 receipt는 later consensus checkpoint나 epoch-final durability와 같은 말이 아닙니다. Shared-object transaction은 consensus order를 기다리는 경로가 있으며, owned-object fast path와 현재 Sui feature/config activation도 별도로 기록해야 합니다.</p>
      <p>Release suite는 partition·crashed leader·GST recovery를 나눕니다. Partition 중 undecided가 늘고 output이 멈춰도 conflicting decided prefix가 0이면 safety oracle은 통과할 수 있습니다. Bounded delivery와 quorum parents가 회복된 뒤 timeout/leader progression으로 eventual decided prefix가 늘어야 liveness를 통과합니다. Conflict exclusion을 위반한 FPC votes, invalid blocks와 digest mismatch는 execution 전에 fail closed합니다.</p>
      <p>Restart에서는 exact mainnet-v1.77.2 tag/commit, ProtocolConfig, verified block store, last commit digest와 transaction-vote mode를 pin합니다. Leader decisions와 sub-DAG digest를 replay해 state parity를 확인하고 incomplete speculative execution만 rollback합니다. External success에는 selected path의 execution result와 필요한 checkpoint/finality receipt를 함께 요구합니다.</p>
      <div className="grid gap-4 md:grid-cols-2"><aside className="rounded-lg border border-border p-4"><h3 className="font-semibold">Consensus receipt</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Decided slot prefix, committed leader, sub-DAG digest, application state root와 checkpoint identifier.</p></aside><aside className="rounded-lg border border-border p-4"><h3 className="font-semibold">FPC receipt</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Transaction digest, object versions, distinct vote power, conflict check, execution result와 later-finality status.</p></aside></div>
      <h3 className="text-xl font-semibold">이 글만으로 확인할 10가지</h3><p>기초 6문제는 certified/uncertified evidence, first support, direct commit·skip·undecided, prefix barrier, sub-DAG order와 FPC/최종성 경계를 묻습니다. 심화 4문제는 equivocation parity, indirect commit·skip traces, partition/GST oracle와 pinned Sui release suite를 설계하게 합니다.</p>
    </section>
  </article>;
}
