import type { Article } from '../types';

export const p2pArticles: Article[] = [
  {
    slug: 'tls-fundamentals',
    title: 'TLS 1.3 기초: 핸드셰이크, AEAD, 키 스케줄',
    subcategory: 'p2p-fundamentals',
    sections: [
      { id: 'overview', title: '개요' },
      { id: 'handshake', title: '핸드셰이크 흐름' },
      { id: 'record-protocol', title: '레코드 프로토콜' },
      { id: 'key-schedule', title: '키 스케줄' },
    ],
    component: () => import('@/pages/articles/p2p/tls-fundamentals'),
  },
  {
    slug: 'quic-fundamentals',
    title: 'QUIC 프로토콜 기초: UDP 기반 차세대 전송 계층',
    subcategory: 'p2p-fundamentals',
    sections: [
      { id: 'overview', title: '개요: UDP 기반 전송' },
      { id: 'handshake', title: '핸드셰이크: 0-RTT & 1-RTT' },
      { id: 'streams', title: '스트림: 멀티플렉싱 & 흐름 제어' },
      { id: 'migration', title: '연결 마이그레이션' },
      { id: 'security', title: '보안: TLS 1.3 내장' },
    ],
    component: () => import('@/pages/articles/p2p/quic-fundamentals'),
  },
  {
    slug: 'nat-traversal',
    title: 'NAT Traversal 기초: STUN, TURN, ICE, Hole Punching',
    subcategory: 'p2p-fundamentals',
    sections: [
      { id: 'overview', title: '개요: NAT 유형' },
      { id: 'stun', title: 'STUN: 바인딩 요청' },
      { id: 'turn', title: 'TURN: 릴레이' },
      { id: 'ice', title: 'ICE: 연결성 검사' },
      { id: 'hole-punching', title: 'Hole Punching 기법' },
    ],
    component: () => import('@/pages/articles/p2p/nat-traversal'),
  },
  {
    slug: 'gossip-fundamentals',
    title: 'Gossip 프로토콜 기초: Epidemic 모델과 GossipSub',
    subcategory: 'p2p-fundamentals',
    sections: [
      { id: 'overview', title: '개요: Epidemic 모델' },
      { id: 'protocols', title: 'SWIM & HyParView' },
      { id: 'gossipsub', title: 'GossipSub 구현' },
      { id: 'reliability', title: '신뢰성 & 스코어링' },
    ],
    component: () => import('@/pages/articles/p2p/gossip-fundamentals'),
  },
  {
    slug: 'content-addressing',
    title: 'Content Addressing 기초: CID, Merkle DAG, 이름 해석',
    subcategory: 'p2p-ipfs',
    sections: [
      { id: 'overview', title: '개요: 위치 vs 내용 주소' },
      { id: 'cid', title: 'CID: Content Identifier' },
      { id: 'merkle-dag', title: 'Merkle DAG' },
      { id: 'resolution', title: '이름 해석: IPNS & DNSLink' },
    ],
    component: () => import('@/pages/articles/p2p/content-addressing'),
  },
  {
    slug: 'kademlia',
    title: 'Kademlia DHT: XOR 거리와 K-버킷',
    subcategory: 'p2p-discovery',
    sections: [
      { id: 'overview', title: '개요 & XOR 거리 메트릭' },
      { id: 'xor-distance', title: 'XOR 거리: 이진 트리 해석' },
      { id: 'routing', title: 'K-버킷 라우팅 테이블' },
      { id: 'bucket-ops', title: '버킷 연산: 추가, 교체, 삭제' },
      { id: 'revalidation', title: '2-tier 재검증 시스템' },
    ],
    component: () => import('@/pages/articles/p2p/kademlia'),
  },
  {
    slug: 'kad-lookup',
    title: 'Kademlia 탐색: 반복 FIND_NODE 알고리즘',
    subcategory: 'p2p-discovery',
    sections: [
      { id: 'overview', title: '탐색이란? — 왜 반복적인가' },
      { id: 'algorithm', title: '반복 탐색 알고리즘' },
      { id: 'geth-lookup', title: 'go-ethereum lookup.go 구현' },
      { id: 'refresh', title: '테이블 새로고침 & 부트스트랩' },
    ],
    component: () => import('@/pages/articles/p2p/kad-lookup'),
  },
  {
    slug: 'discv4',
    title: 'Ethereum discv4: UDP 노드 발견 프로토콜',
    subcategory: 'p2p-discovery',
    sections: [
      { id: 'overview', title: '개요 & 패킷 구조' },
      { id: 'wire', title: 'v4wire: 패킷 인코딩/디코딩' },
      { id: 'handshake', title: 'Ping↔Pong 핸드셰이크' },
      { id: 'findnode', title: 'FindNode↔Neighbors 흐름' },
      { id: 'enr', title: 'ENR: 자기서명 노드 레코드' },
    ],
    component: () => import('@/pages/articles/p2p/discv4'),
  },
  {
    slug: 'discv5',
    title: 'Ethereum discv5: 암호화 노드 발견 (TALKREQ)',
    subcategory: 'p2p-discovery',
    sections: [
      { id: 'overview', title: '개요: discv4의 한계 → discv5' },
      { id: 'handshake', title: 'WHOAREYOU 핸드셰이크' },
      { id: 'session', title: '세션 키 유도 (ECDH + HKDF)' },
      { id: 'findnode', title: 'FINDNODE: 거리 기반 질의' },
      { id: 'talk', title: 'TALKREQ/TALKRESP: 확장 프로토콜' },
    ],
    component: () => import('@/pages/articles/p2p/discv5'),
  },
  {
    slug: 'dht-security',
    title: 'DHT 보안: Sybil, Eclipse, 방어 구현',
    subcategory: 'p2p-discovery',
    sections: [
      { id: 'overview', title: '개요: DHT 공격 모델' },
      { id: 'sybil', title: 'Sybil 공격 & IP 쿼터' },
      { id: 'eclipse', title: 'Eclipse 공격 & 버킷 다양성' },
      { id: 'geth-defense', title: 'go-ethereum의 방어 구현' },
    ],
    component: () => import('@/pages/articles/p2p/dht-security'),
  },
];
