import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import { RqbitPipelineViz, RqbitRangeViz } from "./viz/ModernRqbitViz";

export default function ModernRqbitArticle() { return <article className="space-y-14">
  <section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">rqbit v8.1.1 stable source</p><h2 className="text-3xl font-bold tracking-tight">rqbit는 peer에게 받은 block을 piece로 조립하고 hash가 맞을 때만 파일 범위로 내보낸다</h2></header><p className="text-lg leading-8">Alice가 <code>payroll-report-v1.torrent</code>를 열면 rqbit는 metainfo의 info-hash로 DHT와 tracker에서 peer 후보를 얻습니다. Peer handshake 뒤 index·offset·length로 block을 요청해 piece를 조립하고, metainfo의 piece hash와 같을 때만 have bitfield와 file readiness를 갱신합니다. HTTP range reader는 필요한 verified pieces가 준비될 때까지 기다린 뒤 요청 byte만 읽습니다.</p><p>Metainfo·piece hash·peer discovery·wire transfer의 일반 원리는 <a className="text-primary hover:underline" href="/p2p/bittorrent#overview">BitTorrent 정본</a>을, DHT 탐색은 <a className="text-primary hover:underline" href="/p2p/kademlia#overview">Kademlia 정본</a>을 재사용합니다. 이 글은 rqbit의 peer queue, in-flight piece owner, hash admission과 range-read readiness를 다룹니다.</p><RqbitPipelineViz/></section>
  <section id="peer-piece" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · peer와 in-flight owner</p><h2 className="mt-2 text-2xl font-bold">후보 queue와 piece owner를 분리해야 timeout 뒤 안전하게 재배치할 수 있다</h2></header><p>v8.1.1의 live torrent state는 DHT·tracker가 공급한 peer queue, peer state와 chunk tracker를 함께 운용합니다. <code>TorrentStateLocked</code>가 have/need chunks의 source of truth이고 <code>inflight_pieces</code>는 한 시점에 어느 peer에게 완성 piece를 기대하는지 기록합니다. 더 빠른 peer가 작업을 steal하면 이전 peer의 같은 piece requests를 cancel합니다.</p><p>
            Candidate endpoint는 아직 연결과 handshake, unchoke를 통과하지 않았습니다. In-flight 등록 역시 byte receipt는 아닙니다.
            Connection failure는 exponential backoff로 재등록될 수 있지만 peer cap, retry count와 timeout을 두어 같은 offline
            candidate가 queue를 독점하지 않게 합니다.
          </p><div id="paper-rqbit-live-v811"><CitationBlock source="rqbit v8.1.1 — torrent_state/live/mod.rs" citeKey={1} type="code" href="https://github.com/ikatson/rqbit/blob/v8.1.1/crates/librqbit/src/torrent_state/live/mod.rs"><p><strong>문제:</strong> 여러 peer task가 같은 torrent pieces를 중복·충돌 없이 내려받고 실패 후 재배치합니다.</p><p><strong>기여:</strong> Peer queue/state, TorrentStateLocked, in-flight piece owner, stealing·cancel과 reconnect lifecycle을 구현합니다.</p><p><strong>전제:</strong> rqbit v8.1.1의 BTv1 torrent path와 pinned session options를 사용합니다.</p><p><strong>근거 범위:</strong> 한 process의 peer scheduling, block request bookkeeping과 piece completion transition입니다.</p><p><strong>말하지 않는 것:</strong> Candidate peer의 honesty, fixed throughput, permanent swarm availability를 보장하지 않습니다.</p></CitationBlock></div></section>
  <section id="piece-verify" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · piece admission</p><h2 className="mt-2 text-2xl font-bold">완성 piece의 SHA-1이 metainfo와 같아야 checked state로 넘어간다</h2></header><p>Block이 모두 도착하면 rqbit는 storage에서 piece byte를 읽어 hash를 계산하고 torrent metainfo의 expected hash와 비교합니다. Match일 때만 piece를 downloaded-and-checked로 표시하고 waiting stream을 깨웁니다. Mismatch면 piece를 broken으로 되돌리고 해당 peer를 disconnect해 다른 peer에서 다시 요청할 수 있게 합니다.</p><p>
            BTv1의 SHA-1은 collision resistance가 현대 신규 설계에 권장되는 hash는 아니지만 protocol compatibility 안에서는 expected
            piece digest와 exact bytes가 같은지 확인하는 admission gate입니다. 다만 그 범위는 admission gate까지이고 peer
            authentication이나 파일의 업무상 진위 증명으로는 이어지지 않습니다.
          </p><div id="paper-rqbit-file-ops-v811"><CitationBlock source="rqbit v8.1.1 — file_ops.rs · live piece completion" citeKey={2} type="code" href="https://github.com/ikatson/rqbit/blob/v8.1.1/crates/librqbit/src/file_ops.rs"><p><strong>문제:</strong> 여러 block으로 조립한 piece가 metainfo가 지시한 exact bytes인지 확인합니다.</p><p><strong>기여:</strong> Storage range hashing, expected piece hash comparison과 valid/broken typed outcome을 구현합니다.</p><p><strong>전제:</strong> BTv1 metainfo의 piece hashes와 rqbit storage mapping이 같은 torrent revision에 속합니다.</p><p><strong>근거 범위:</strong> Local completed-piece integrity admission과 mismatch retry input입니다.</p><p><strong>말하지 않는 것:</strong> Publisher identity, malware safety, SHA-1의 신규 cryptographic security를 보장하지 않습니다.</p></CitationBlock></div></section>
  <section id="range-release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · range와 restart</p><h2 className="mt-2 text-2xl font-bold">Byte range를 덮는 모든 piece가 검증된 뒤에만 response를 연다</h2></header><p>Streaming reader는 요청 byte range가 걸치는 piece index를 계산하고 해당 pieces의 completion notification을 기다립니다. 256 KiB piece에서 offset 400 KiB부터 200 KiB를 읽으면 마지막 포함 byte가 599 KiB이므로 piece 1과 2가 필요합니다. 마지막 piece와 여러 files를 가로지르는 storage mapping에서는 실제 torrent length로 bounds를 다시 검사합니다.</p><RqbitRangeViz/><ExplainedFormula question="Offset o부터 length n의 byte range가 걸치는 piece index는 무엇일까?" idea={<>첫 byte와 마지막 포함 byte를 piece length L로 나눈 몫을 각각 구합니다. n이 0이면 빈 요청으로 별도 처리하고, 마지막 piece의 짧은 길이는 torrent total length로 제한합니다.</>} formula={String.raw`p_{first}=\left\lfloor\frac{o}{L}\right\rfloor,\qquad p_{last}=\left\lfloor\frac{o+n-1}{L}\right\rfloor,\qquad N=p_{last}-p_{first}+1`}
  annotatedFormula={String.raw`p_{first}=\underbrace{\left\lfloor\frac{o}{L}\right\rfloor,\qquad p_{last}=\left\lfloor\frac{o+n-1}{L}\right\rfloor,\qquad N=p_{last}-p_{first}+1}_{\text{기준량당 비율}}`}
  operations={[
    { expression: String.raw`\left\lfloor\frac{o}{L}\right\rfloor,\qquad p_{last}=\left\lfloor\frac{o+n-1}{L}\right\rfloor,\qquad N=p_{last}-p_{first}+1`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","첫 byte와 마지막 포함 byte를 piece length","L로 나눈 몫을 각각 구합니다."] },
  ]} terms={[{symbol:"o",name:"range offset",description:"Torrent file view에서 요청이 시작하는 0-based byte 위치입니다."},{symbol:"n",name:"range length",description:"요청한 byte 수이며 0은 식 밖에서 빈 범위로 처리합니다."},{symbol:"L",name:"piece length",description:"Metainfo가 선언한 일반 piece 길이이며 마지막 piece는 더 짧을 수 있습니다."},{symbol:"N",name:"required pieces",description:"Range를 안전하게 읽기 전에 checked 상태여야 하는 연속 piece 수입니다."}]} assumptions={["o와 n은 같은 torrent byte coordinate이며 o+n이 overflow하지 않습니다.","0<n이고 requested end가 total torrent length 안에 있습니다.","각 piece는 metainfo hash를 통과한 뒤 ready로 표시됩니다.","파일 선택과 multi-file storage mapping은 piece 계산 뒤 별도 bounds를 적용합니다."]} interpretation="o=400 KiB, n=200 KiB, L=256 KiB이면 first=1, last=2, N=2입니다. o=300 KiB, n=200 KiB라면 마지막 byte가 499 KiB여서 piece 1 하나만 필요합니다. End-exclusive 값을 그대로 나누면 경계에서 한 piece를 더 기다리는 오류가 생깁니다."/><p>
            Release suite는 offline candidate와 choke/timeout, stolen request의 late block을 주입합니다. Hash mismatch,
            process restart와 partial storage, range cancel도 함께 넣습니다. Invalid piece는 have bitfield를 갱신하지 않고
            partial response를 닫습니다. Resume bitfield만 믿지 않고 configured validation policy와 disk state를 함께 확인합니다.
          </p><div id="paper-rqbit-streaming-v811"><CitationBlock source="rqbit v8.1.1 — torrent_state/streaming.rs · initializing.rs" citeKey={3} type="code" href="https://github.com/ikatson/rqbit/blob/v8.1.1/crates/librqbit/src/torrent_state/streaming.rs"><p><strong>문제:</strong> 아직 downloading 중인 torrent에서 verified byte range를 기다려 stream으로 제공합니다.</p><p><strong>기여:</strong> Range-to-piece mapping, completion wake-up과 restart fast-resume validation path를 제공합니다.</p><p><strong>전제:</strong> rqbit v8.1.1 storage, metainfo lengths와 selected-file mapping이 일치합니다.</p><p><strong>근거 범위:</strong> Local range readiness, cancellation과 initialization-time have-state recovery입니다.</p><p><strong>말하지 않는 것:</strong> HTTP consumer의 authorization, disk durability, unverified partial bytes의 correctness를 보장하지 않습니다.</p></CitationBlock></div><h3 className="text-xl font-semibold">이 글만으로 풀어야 하는 10문제</h3><p>
            기초 6문제는 info-hash와 candidate queue, in-flight owner부터 block/piece, hash admission과 range
            mapping까지를 확인합니다. 심화 4문제는 steal race, mismatch attribution, restart recovery와 verified range
            release test를 설계하게 합니다.
          </p></section>
</article>; }
