import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import { CitationBlock } from "@/components/ui/citation";
import ExplainedFormula from "@/components/ui/explained-formula";
import { EvaluationContractViz } from "./viz/ModernCompetitionViz";
export default function Article() { return <div className="space-y-16"><section id="overview" data-teach-level="S" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">1. 무엇을 언제 맞힌다는 것인지 먼저 정합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>같은 모델과 점수 이름을 써도 예측할 대상과 시간 범위가 다르면 서로 다른 시험입니다. 이미 알려진 사건을 맞히는지 아직 일어나지 않은 사건을 예측하는지부터 분명해야 합니다.</p><p>이 글은 한 번의 방문에서 다음 하루의 사건을 예측하는 작은 사례를 따라갑니다. 사용할 정보와 기다릴 결과, 점수를 보는 역할을 먼저 정하면 모델 비교가 같은 질문에 답하게 됩니다.</p></div></section>

<section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 한 행의 입력과 미래 결과를 연결합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>예측할 행과 기준 시각을 정하고 그때까지 도착한 정보로 입력을 만듭니다. 이후 정한 기간의 사건으로 정답을 만듭니다. 예측과 정답을 같은 행에 연결해 점수를 계산하고 그 점수로 바꿀 수 있는 결정의 범위를 정합니다.</p></div><ol className="my-8 grid list-none gap-4 p-0 sm:grid-cols-2"><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">1</span><span>예측 행과 기준 시각을 고정한다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">2</span><span>그때 도착한 입력만 사용한다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">3</span><span>이후의 정해진 기간을 관찰한다</span></li><li className="border-l border-border pl-4"><span className="block text-sm text-muted-foreground">4</span><span>같은 행의 예측과 정답을 비교한다</span></li></ol></section>

<section id="small-case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 10시에 예측하고 다음 날 10시까지 관찰합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>한 방문의 기준 시각을 2026년 4월 16일 10:00 UTC로 두고 다음 24시간 안에 사건이 생기는지 예측한다고 합시다. 사건은 다음 날 09:00에 생겼으므로 정한 미래 구간에 포함됩니다. 이는 계산용 사례이며 실제 의료 결과를 주장하지 않습니다. (가정)</p><p>입력 후보 중 하나는 09:00에 측정됐지만 10:05에 도착했고 다른 하나는 09:55에 도착했습니다. 10:00 예측에는 늦게 온 값을 쓸 수 없습니다. 나중에 완성된 표에 두 값이 모두 있어도 당시의 입력은 달라야 합니다. (가정)</p></div></section>

<section id="inside-contract" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 방문 식별자와 시간 경계와 결과를 함께 보관합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>한 사람에게 방문이 여러 번 있다면 사람 번호만으로는 예측 행을 구별할 수 없습니다. 사람과 방문 식별자를 함께 쓰고 그 방문의 기준 시각과 관찰 종료를 붙입니다. 예측을 다른 방문의 정답에 연결하면 점수의 의미가 깨집니다.</p><p>입력에는 측정 시각과 도착 시각을 함께 남깁니다. 정답 쪽에는 어떤 사건을 셀지와 구간의 양 끝을 포함할지 정합니다. 이 기록이 있어야 09:00 측정값을 쓰지 않은 이유와 다음 날 09:00 사건을 센 이유를 재현할 수 있습니다.</p></div></section>

<section id="why-complete" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 아직 사건을 못 봤다는 것과 사건이 없었다는 것은 다릅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>다음 날 08:00까지만 관찰했다면 목표 구간은 아직 2시간 남았습니다. 이때 사건을 못 봤다고 곧바로 음성 정답을 붙이면 실제로 09:00에 생길 사건을 놓칩니다. 정답이 미확정인 상태를 음성으로 바꾸지 않아야 합니다.</p><p>관찰이 끝나도 보고가 늦게 도착할 수 있습니다. 미래 사건을 정의하는 규칙과 그 정답을 학습에 쓸 수 있게 되는 시각은 별개입니다. 정답 창의 완결과 실제 가용성을 함께 확인합니다.</p></div></section>

<section id="evaluation-terms" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 예측 행과 입력 경계와 관찰 길이에 이름을 붙입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>출력 하나가 가리키는 대상과 방문의 조합이 prediction row입니다. 입력 정보의 기준 시각은 prediction cutoff이며 이후 관찰할 길이는 target horizon입니다.</p></div><TermBreakdown title="역할을 이해한 뒤 이름을 붙입니다" items={[{"term": "Evaluation contract", "description": "행·입력 시각·정답·지표·평가 자료의 역할을 미리 고정한 정의입니다.", "boundary": "이 글의 실무 설계이며 하나의 보편 API 표준을 뜻하지 않습니다."}, {"term": "Metric contract", "description": "손실의 방향·집계 단위·가중치·동률과 누락 처리까지 정한 계산 규칙입니다.", "boundary": "AUROC 같은 지표 이름 하나만으로 모두 결정되지 않습니다."}, {"term": "Label availability", "description": "정답을 시스템이 실제 조회해 학습에 쓸 수 있게 된 시점입니다.", "boundary": "사건 발생과 관찰 종료와 보고 도착을 구별합니다."}]} /><EvaluationContractViz /></section>

<section id="target" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. 열린 시작점과 닫힌 끝점에 사건을 넣어 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>이 사례는 시작 시각 뒤부터 끝 시각까지를 관찰하는 (시작, 끝] 규칙을 택합니다. 4월 16일 10:00은 제외하고 4월 17일 10:00은 포함합니다. 다음 날 09:00 사건은 이 구간 안에 있으므로 정답은 1입니다. (가정)</p><p>정확히 시작 시각에 난 사건은 이미 시작점의 사건이므로 이 미래 정답에는 포함하지 않습니다. 끝 시각에 난 사건은 포함합니다. 아래 식은 현실에서 정답을 정의하는 식이며 현재 그 정답을 관측할 수 있는지는 앞 절의 완결·도착 조건으로 따로 판단합니다.</p></div><ExplainedFormula question="Prediction row의 target은 왜 cutoff와 horizon으로 정의하나요?" idea={<p>Cutoff 전까지는 input, cutoff 뒤 정한 horizon 안의 outcome은 target입니다. 두 구간을 분리해야 같은 사건이 feature와 label에 동시에 들어가지 않습니다.</p>} formula={String.raw`y_i=\mathbf1\{\exists e:\;c_i<t_e\le c_i+h_i\}`} annotatedFormula={String.raw`\begin{aligned}W_i&=\underbrace{(c_i,c_i+h_i]}_{\text{cutoff 뒤 target 관측 구간을 생성}}\\E_i&=\underbrace{\{e:t_e\in W_i\}}_{\text{그 구간의 target event만 선택}}\\y_i&=\underbrace{\mathbf1[|E_i|>0]}_{\text{event 존재를 binary label로 변환}}\end{aligned}`} operations={[{expression:String.raw`(c_i,c_i+h_i]`,annotation:["cutoff에 horizon을 더해","target window를 생성"]},{expression:String.raw`\{e:t_e\in W_i\}`,annotation:["event time을 window와 비교해","target events만 필터"]},{expression:String.raw`\mathbf1[|E_i|>0]`,annotation:["event count가 양수인지 확인해","binary label로 변환"]}]} terms={[{symbol:"c_i",name:"Prediction cutoff",description:"Row i의 input 정보 경계입니다."},{symbol:"h_i",name:"Target horizon",description:"미래 outcome을 관찰할 길이입니다."},{symbol:"y_i",name:"Target label",description:"계약에 따라 생성한 정답입니다."}]} assumptions={["Window endpoint convention과 timezone을 고정합니다.","Label available time은 별도 availability 계약으로 검사합니다.","현실의 사건으로 정의한 정답과 현재 관측 가능한 정답을 구별합니다. 음성 확정에는 전체 창의 관찰 완료와 필요한 보고 도착이 필요합니다."]} interpretation="2026-04-16 10:00 UTC 뒤부터 04-17 10:00 UTC까지가 목표 구간입니다. 다음 날 09:00 사건이면 y=1이며 시작점 정확히 10:00의 사건은 제외하고 끝점 사건은 포함합니다."/></section>

<section id="source-availability" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 공식 누수 정의를 늦게 도착한 입력에 적용합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>scikit-learn 1.7.2 Common pitfalls §11.2는 예측 시점에 사용할 수 없었던 정보가 모델을 만드는 데 쓰이는 문제를 설명합니다. 모델 앞단의 자료 준비와 전처리도 이 경계에 포함됩니다.</p></div><div id="paper-evaluation-availability" className="mt-8 scroll-mt-20"><CitationBlock source="scikit-learn 1.7.2 — Data leakage" citeKey={1} href="https://scikit-learn.org/1.7/common_pitfalls.html#data-leakage"><q>information that would not be available at prediction time</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>09:00에 측정돼도 10:05에 도착한 값은 10:00 예측 시점에 조회할 수 없습니다. 해당 값을 과거 예측 입력에 넣으면 공식 정의의 경계를 어깁니다. 09:55에 도착한 값은 다른 사용 조건도 통과했다면 후보 입력이 됩니다. 이 예시는 원문의 새 수치 적용이며 문서가 방문별 정답 계약을 제공한다는 뜻은 아닙니다.</p></div></div></section>

<section id="metric" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. 점수의 평균 단위를 행의 의미와 맞춥니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>한 사람의 방문이 여러 개면 방문마다 같은 무게로 평균내는 것과 사람별 평균을 다시 평균내는 것은 다릅니다. 예측 행은 방문이어도 최종 목적이 사람별 피해라면 그 집계 규칙을 따로 적어야 합니다.</p><p>점수가 클수록 좋은지 작을수록 좋은지, 빠진 예측을 어떻게 처리할지, 같은 점수의 순위를 어떻게 다룰지 정합니다. 집계 순서와 표본 가중치도 버전과 함께 고정해야 같은 예측을 다시 넣었을 때 같은 값을 얻습니다.</p></div></section>

<section id="roles" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 점수를 본 뒤 바꿀 수 있는 결정을 미리 나눕니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Local 평가는 후보를 고르는 데 사용하고 public 점수는 공개된 피드백으로 취급합니다. Private 평가를 마지막 보고에만 남기는 방식은 선택과 최종 평가를 나누기 위한 설계입니다. 실제 대회의 역할과 허용 사용은 그 대회의 규칙을 따로 확인합니다.</p><p>최종 평가 점수를 본 뒤 특징이나 모델을 바꾸면 그 자료도 선택에 사용한 것입니다. 이름을 private로 붙였다고 독립성이 유지되지는 않습니다. 다시 독립적인 최종 성능을 주장하려면 선택에 쓰지 않은 평가가 필요합니다.</p></div></section>

<section id="boundary" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 같은 시각의 도착과 지연된 정답까지 규칙에 남깁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>10:00에 정확히 도착한 입력을 쓸 수 있는지는 시스템이 어느 순간의 자료를 확정해 읽는지에 달렸습니다. 시계 기준과 동률 처리, 자료 스냅샷 규칙을 정하고 실제 조회 가능 여부를 재현합니다.</p><p>결과 관찰이 불완전하거나 보고가 늦으면 정답을 미확정으로 보관할 수 있어야 합니다. 행·입력·정답의 계약이 정확해도 다른 나라나 이후 기간에 같은 성능을 보장하지는 않으므로 배포 상황에 맞춘 검증을 이어갑니다.</p></div><ContentBoundary article="competition-workflow" /></section>

<section id="prediction-questions" data-teach-level="review" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 같은 시험을 재현할 수 있나요</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>기준 시각과 정확히 같은 사건, 다음 날 09:00 사건, 다음 날 10:00 사건은 각각 정답 창에 포함되나요? (답: 7절)</p><p>09:00에 측정하고 10:05에 도착한 값은 10:00 예측의 입력으로 쓸 수 있나요? (답: 8절)</p><p>다음 날 08:00까지 사건이 없었다면 24시간 목표의 음성 정답으로 바로 확정해도 될까요? (답: 5절)</p></div></section></div>; }
