import type { Article } from "../types";

export const economicHistoryArticles: Article[] = [
  {
    slug: "agrarian-surplus-and-state",
    title: "곡물을 모아 나누는 순간 측정·장부·권한이 함께 생깁니다",
    subcategory: "economic-history-early-state",
    sections: [
      { id: "overview", title: "남은 곡물보다 누가 세고 나누는지가 중요합니다" },
      { id: "black-box", title: "수확·저장·기록·배분이 하나의 고리를 이룹니다" },
      { id: "case", title: "1200자루를 모아 다음 해까지 나눠 봅니다" },
      { id: "picture", title: "창고 안의 양과 장부 위의 청구권을 나눕니다" },
      { id: "need", title: "시간이 길어지고 사람이 많아지면 기억만으로 버티지 못합니다" },
      { id: "names", title: "잉여·공납·회계·배분 권한에 이름을 붙입니다" },
      { id: "mechanism", title: "같은 1200자루가 권리와 의무로 바뀌는 길을 추적합니다" },
      { id: "source", title: "기원전 3100~2900년 무렵의 곡물 장부를 읽습니다" },
      { id: "comparison", title: "장부는 국가의 존재를 혼자 증명하지 못합니다" },
      { id: "limits", title: "잉여가 자동으로 국가를 만든다는 한 줄 인과를 피합니다" },
    ],
    component: () => import("@/pages/articles/economic-history/agrarian-surplus-and-state"),
  },
  {
    slug: "trade-credit-and-long-distance-networks",
    title: "먼 거리의 교역은 물건보다 약속과 위험을 함께 옮깁니다",
    subcategory: "economic-history-trade",
    sections: [
      { id: "overview", title: "교역망은 한 상인이 처음부터 끝까지 걷는 한 줄 길이 아닙니다" },
      { id: "black-box", title: "물건·대금·정보·위험의 네 흐름을 나눕니다" },
      { id: "case", title: "은 6미나 대출과 두 번의 상환을 따라갑니다" },
      { id: "picture", title: "실물 이동과 장부의 약속이 다른 속도로 움직입니다" },
      { id: "need", title: "거리와 시간이 길어질수록 신용과 중개가 필요해집니다" },
      { id: "names", title: "중개·신용·결제·표준화에 이름을 붙입니다" },
      { id: "mechanism", title: "6미나가 주석·직물·은으로 돌아오는 경로를 추적합니다" },
      { id: "source", title: "기원전 20~19세기 은 대출 점토판을 읽습니다" },
      { id: "comparison", title: "실크로드는 하나의 도로가 아니라 갈아타는 여러 망이었습니다" },
      { id: "limits", title: "교역의 확대를 모두의 번영으로 곧장 바꾸지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/trade-credit-and-long-distance-networks"),
  },
  {
    slug: "colonial-plantations-slavery-and-extraction",
    title: "식민 상품망의 수익은 강제로 빼앗은 노동과 권리를 비용 밖에 숨겼습니다",
    subcategory: "economic-history-colonial",
    sections: [
      { id: "overview", title: "수출액이 늘었다는 말과 주민이 더 잘 살았다는 말은 다릅니다" },
      { id: "black-box", title: "토지·노동·상품·금융·권력의 흐름을 한 장부에 놓습니다" },
      { id: "case", title: "사탕 100단위의 판매액을 네 몫으로 나눕니다" },
      { id: "picture", title: "시장 가격에 잡힌 비용과 강제로 떠넘긴 손실을 구분합니다" },
      { id: "need", title: "강제력은 싼 원료와 높은 이윤을 가능하게 한 생산 조건이었습니다" },
      { id: "names", title: "플랜테이션·노예제·수탈·상품망에 이름을 붙입니다" },
      { id: "mechanism", title: "100단위 매출이 대서양 양쪽에 다르게 남는 길을 추적합니다" },
      { id: "source", title: "항해 기록이 보여 주는 수와 보여 주지 못하는 삶을 나눕니다" },
      { id: "comparison", title: "노예 무역과 식민 상품 특화의 긴 흔적을 대조합니다" },
      { id: "limits", title: "대서양 한 모형을 모든 제국과 강제 노동에 그대로 씌우지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/colonial-plantations-slavery-and-extraction"),
  },
  {
    slug: "industrial-revolution-wages-and-energy",
    title: "비싼 노동과 싼 에너지가 기계를 유리하게 만들었습니다",
    subcategory: "economic-history-industry",
    sections: [
      { id: "overview", title: "발명 목록보다 기계를 살 이유와 그 결과를 봅니다" },
      { id: "black-box", title: "가격·투자·생산성·생활 수준을 한 고리로 잇습니다" },
      { id: "case", title: "노동 10명과 석탄 기계 한 대의 비용을 비교합니다" },
      { id: "picture", title: "기업의 선택과 노동자의 생활 장부를 분리합니다" },
      { id: "need", title: "생산이 늘어도 생활이 같은 속도로 좋아지지는 않습니다" },
      { id: "names", title: "요소 가격·노동 절약 기술·실질임금에 이름을 붙입니다" },
      { id: "mechanism", title: "같은 기계가 두 지역에서 다른 선택이 되는 이유를 계산합니다" },
      { id: "source", title: "고임금·저에너지 가격 설명을 원 논문에서 확인합니다" },
      { id: "comparison", title: "1770~1840년 생산성과 임금의 다른 속도를 대조합니다" },
      { id: "limits", title: "영국 한 사례를 산업화의 보편 법칙으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/industrial-revolution-wages-and-energy"),
  },
  {
    slug: "gold-standard-depression-bretton-woods",
    title: "고정 환율의 약속은 위기 때 조정 비용을 누구에게 지울지 정합니다",
    subcategory: "economic-history-money",
    sections: [
      { id: "overview", title: "금에서 달러로 기준이 바뀌어도 조정 문제는 남았습니다" },
      { id: "black-box", title: "환율 약속·준비자산·국내 조정·국제 지원을 연결합니다" },
      { id: "case", title: "금 100단위와 국외 지급 20단위의 압박을 계산합니다" },
      { id: "picture", title: "바꿀 수 없는 값과 움직일 수 있는 값을 나눕니다" },
      { id: "need", title: "고정은 불확실성을 줄이지만 위기의 출구도 좁힙니다" },
      { id: "names", title: "금본위제·평가절하·자본통제·브레턴우즈에 이름을 붙입니다" },
      { id: "mechanism", title: "같은 20단위 적자가 세 제도에서 어떻게 처리되는지 봅니다" },
      { id: "source", title: "1870년대부터 1930년대 붕괴까지의 순서를 확인합니다" },
      { id: "comparison", title: "1944년의 조정 가능한 고정환율이 무엇을 바꿨는지 봅니다" },
      { id: "limits", title: "국가마다 들어오고 나간 시기와 비용은 달랐습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/gold-standard-depression-bretton-woods"),
  },
  {
    slug: "decolonization-oil-shocks-and-debt",
    title: "정치적 독립 뒤에도 수출 구조와 외화 부채는 선택지를 제한했습니다",
    subcategory: "economic-history-development",
    sections: [
      { id: "overview", title: "국기를 바꾼 날과 경제의 선택지가 바뀐 날은 같지 않습니다" },
      { id: "black-box", title: "원자재 수출·수입·유가·대출·금리를 연결합니다" },
      { id: "case", title: "수출 100과 석유 수입 40인 나라의 외화 장부를 봅니다" },
      { id: "picture", title: "정치적 주권과 외화 지급 능력을 다른 축에 놓습니다" },
      { id: "need", title: "개발 투자는 필요했지만 빌린 통화와 금리가 위험을 만들었습니다" },
      { id: "names", title: "탈식민·교역조건·페트로달러 재순환·외채에 이름을 붙입니다" },
      { id: "mechanism", title: "싼 대출이 금리 상승 뒤 부채 위기로 바뀌는 경로를 계산합니다" },
      { id: "source", title: "1945년 탈식민에서 1970년대 석유 충격까지 순서를 잇습니다" },
      { id: "comparison", title: "산유국·비산유국과 지역별 정책 선택은 같은 결과를 내지 않았습니다" },
      { id: "limits", title: "부채 위기를 국내 실책이나 외부 충격 하나로만 설명하지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/decolonization-oil-shocks-and-debt"),
  },
  {
    slug: "china-since-1800-households-markets-and-reform",
    title: "중국의 성장은 가구의 남는 몫에서 지역 실험과 세계 무역까지 이어졌습니다",
    subcategory: "economic-history-china",
    sections: [
      { id: "overview", title: "같은 수확 100도 누가 남는 몫을 갖는지에 따라 다음 선택이 달라집니다" },
      { id: "black-box", title: "토지 사용권·국가 납부·남는 몫·시장 가격을 나눕니다" },
      { id: "case", title: "의무 60을 채운 뒤 추가 생산 10을 남기는 구조를 계산합니다" },
      { id: "picture", title: "제국의 위기·집단화·가구 책임·특구 실험을 한 줄로 잇습니다" },
      { id: "need", title: "개혁을 민영화 한 단어로 부르면 실제 순서를 놓칩니다" },
      { id: "names", title: "가구 책임제·이중 경로·경제특구 실험에 이름을 붙입니다" },
      { id: "mechanism", title: "100자루 장부가 공장 주문과 지방 재정으로 이어지는 길을 봅니다" },
      { id: "source", title: "세계은행 개혁 연표는 가구·기업·가격·특구가 차례로 겹친 과정을 보여 줍니다" },
      { id: "comparison", title: "LSE 과정은 지리·국가·젠더·교육·재난을 성장률과 함께 보게 합니다" },
      { id: "limits", title: "중국 한 나라 안에서도 지역·세대·성별의 경제사는 같지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/china-since-1800-households-markets-and-reform"),
  },
  {
    slug: "japan-money-banks-industry-and-catchup",
    title: "일본 산업화는 엔·은행·공장·수출이 맞물린 결과였습니다",
    subcategory: "economic-history-japan",
    sections: [
      { id: "overview", title: "공장 자금 100은 정부 명령만으로도 자유시장만으로도 모이지 않았습니다" },
      { id: "black-box", title: "세금·통화·은행 신용·기업 투자를 따로 놓습니다" },
      { id: "case", title: "자기자금 20·은행대출 60·기반시설 20으로 공장 100을 채웁니다" },
      { id: "picture", title: "1871년 엔·1882년 중앙은행·전후 복구·고도성장의 순서를 잇습니다" },
      { id: "need", title: "산업정책의 존재와 산업정책이 모든 성장을 만들었다는 주장은 다릅니다" },
      { id: "names", title: "통화 통일·우선 생산·추격형 구조전환에 이름을 붙입니다" },
      { id: "mechanism", title: "공장 100의 자금이 생산·수출·상환으로 돌아오는 길을 추적합니다" },
      { id: "source", title: "일본은행 기록은 엔 도입과 은행권 정리를 산업화의 기반으로 보여 줍니다" },
      { id: "comparison", title: "RIETI 연구는 전후 정책의 역할을 민간 경쟁과 구조 이동에 대조합니다" },
      { id: "limits", title: "일본의 경로를 다른 나라의 복사 가능한 처방으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/japan-money-banks-industry-and-catchup"),
  },
  {
    slug: "south-asia-markets-colonial-railways-and-development-state",
    title: "남아시아의 시장은 식민 철도와 독립 뒤 국가 계획을 모두 거쳤습니다",
    subcategory: "economic-history-south-asia",
    sections: [
      { id: "overview", title: "두 시장의 곡물 가격 차이 6은 철도가 생겨도 모두 사라지지 않습니다" },
      { id: "black-box", title: "생산자 가격·운송비·세금·상인 권력을 나눕니다" },
      { id: "case", title: "가격 10과 16 사이에 운송비 2·세금 1·손실 1을 넣습니다" },
      { id: "picture", title: "무굴 시장·회사 지배·철도·계획경제·1991년 전환을 잇습니다" },
      { id: "need", title: "기반시설의 편익과 식민 통치의 목적을 한 점수로 합치지 않습니다" },
      { id: "names", title: "식민 시장 통합·개발국가·외환 자유화에 이름을 붙입니다" },
      { id: "mechanism", title: "가격 차이 6이 생산·세입·산업 허가와 외화 장부로 이어집니다" },
      { id: "source", title: "철도 연구는 실제 노선과 건설되지 않은 노선을 비교합니다" },
      { id: "comparison", title: "RBI 연표는 계획·은행 확대·1991년 위기를 서로 다른 시기로 나눕니다" },
      { id: "limits", title: "성장률 하나로 제국·분할·카스트·젠더의 분배를 닫지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/south-asia-markets-colonial-railways-and-development-state"),
  },
  {
    slug: "africa-slave-trades-colonial-tax-and-commodity-dependence",
    title: "아프리카와 세계경제의 연결은 노예무역·세금·원자재 가격에 서로 다른 흔적을 남겼습니다",
    subcategory: "economic-history-africa",
    sections: [
      { id: "overview", title: "현금세 10은 농가의 100자루 가운데 무엇을 팔지 바꿉니다" },
      { id: "black-box", title: "가족 소비·시장 판매·세금·강제력을 나눕니다" },
      { id: "case", title: "현금작물 매출 20에서 운송 4와 세금 10을 빼면 6이 남습니다" },
      { id: "picture", title: "여러 노예무역·식민 조세·독립·구조조정·중국 교역을 잇습니다" },
      { id: "need", title: "식민 철도와 현금작물은 연결과 추출을 동시에 만들 수 있습니다" },
      { id: "names", title: "노예무역의 장기 손상·식민 재정 추출·원자재 의존에 이름을 붙입니다" },
      { id: "mechanism", title: "농가의 남은 현금 6이 국가 외화와 국제 가격으로 이어집니다" },
      { id: "source", title: "노예무역 연구는 선적 기록과 출신 자료로 국가별 노출을 추정합니다" },
      { id: "comparison", title: "아프리카 경제사 교재는 식민 조세를 지역별 협상과 국가 역량으로 읽습니다" },
      { id: "limits", title: "50여 개 국가를 원자재 의존 한 문장으로 묶지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/africa-slave-trades-colonial-tax-and-commodity-dependence"),
  },
  {
    slug: "mena-land-debt-oil-and-diversification",
    title: "중동·북아프리카 경제는 토지와 외채 위에 석유 계약과 국가 예산이 겹쳤습니다",
    subcategory: "economic-history-mena",
    sections: [
      { id: "overview", title: "석유수입 100이 생겨도 정부가 자유롭게 쓸 수 있는 돈은 100이 아닙니다" },
      { id: "black-box", title: "생산 가치·기업 몫·국가 수입·주민 소득을 나눕니다" },
      { id: "case", title: "석유 100에서 기업 30과 부채 10을 빼 정부수입 60을 만듭니다" },
      { id: "picture", title: "토지·조세 개혁에서 외채 통제와 석유 국유화까지 잇습니다" },
      { id: "need", title: "석유가 많다는 사실보다 계약과 예산 연결이 경제 구조를 만듭니다" },
      { id: "names", title: "양허·자원 재정 연결·다각화에 이름을 붙입니다" },
      { id: "mechanism", title: "정부수입 60이 임금·수입품·송금·해외자산으로 흘러갑니다" },
      { id: "source", title: "LSE 과정은 토지·노동 권리와 주민 생활에서 지역 경제사를 시작합니다" },
      { id: "comparison", title: "IMF 자료는 1970년대 계약 변화와 현재의 다각화 한계를 연결합니다" },
      { id: "limits", title: "중동·북아프리카를 산유국·분쟁·종교라는 한 모습으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/mena-land-debt-oil-and-diversification"),
  },
  {
    slug: "latin-america-exports-import-substitution-and-debt",
    title: "라틴아메리카는 수출 호황·수입대체·외채 위기를 같은 세계시장 안에서 겪었습니다",
    subcategory: "economic-history-latin-america",
    sections: [
      { id: "overview", title: "수출 100의 흑자 10은 가격과 금리가 바뀌면 적자 18이 됩니다" },
      { id: "black-box", title: "수출 물량·가격·수입·외채를 네 칸으로 나눕니다" },
      { id: "case", title: "100−80−10=10이 80−80−18=−18로 바뀝니다" },
      { id: "picture", title: "식민 수출·독립·1870년대 세계화·수입대체·1982년 위기를 잇습니다" },
      { id: "need", title: "수입대체를 보호무역 성공이나 실패 한마디로 끝내지 않습니다" },
      { id: "names", title: "수출 주도 성장·수입대체 산업화·갑작스러운 자금 중단에 이름을 붙입니다" },
      { id: "mechanism", title: "적자 18이 환율·물가·임금·정부 예산으로 번지는 길을 봅니다" },
      { id: "source", title: "NBER 연구는 1870~1913년 수출 호황과 관세·불평등을 함께 봅니다" },
      { id: "comparison", title: "IMF 기록은 1982년 가격·금리·대출 중단이 함께 온 과정을 보여 줍니다" },
      { id: "limits", title: "라틴아메리카와 카리브해를 반복되는 위기 한 문장으로 만들지 않습니다" },
    ],
    component: () => import("@/pages/articles/economic-history/latin-america-exports-import-substitution-and-debt"),
  },
];
