import ContentBoundary from "@/components/articles/content-boundary";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";
import Halo2PipelineViz from "./Halo2PipelineViz";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefs } from "./codeRefs";
import { halo2Tree } from "./fileTree";

export default function ModernHalo2Article(){
const sidebar = useCodeSidebar();
return <>
<article className="space-y-14">
<section id="overview" className="space-y-6"><header className="space-y-3"><p className="text-sm font-semibold text-primary">한 row의 constraint에서 Halo2 전체로</p><h2 className="text-3xl font-bold tracking-tight">a=3,b=4,c=12를 columns에 놓고 무엇이 실제로 강제되는지 추적한다</h2></header><p className="text-lg leading-8 text-foreground/90">Public instance x=3,y=12와 private advice w=4를 한 row에 두고 selector qM=1일 때 qM(ab−c)=0을 검사합니다. Halo2는 이런 PLONKish identities를 instance·advice·fixed columns, rows·regions와 rotations로 조직하는 circuit framework입니다.</p><p>하지만 “Halo2”는 단일 proof format 이름이 아닙니다. Zcash 공식 repository는 IPA commitment profile을 사용하며, KZG를 쓰는 downstream forks는 setup·curve·transcript·serialization이 다릅니다. 이 글은 circuit model과 pinned Zcash source 경계를 소유합니다.</p><aside className="rounded-lg border border-primary/30 bg-primary/5 p-5 text-sm leading-6"><strong>핵심 아이디어:</strong> 값 assignment와 constraint를 분리하고, gate·copy·lookup이 실제로 강제한 relation만 신뢰합니다. MockProver 뒤에 pinned PCS verifier를 별도로 검사합니다.</aside><ContentBoundary article="halo2"/><Halo2PipelineViz/></section>
<section id="columns-regions" className="space-y-6"><header><p className="text-sm font-semibold text-primary">01 · Columns, regions, rotations</p><h2 className="mt-2 text-2xl font-bold">같은 값을 써 넣는 것과 같은 값이 되도록 제약하는 것은 다르다</h2></header><ExplainedFormula question="현재 row에서 multiplication gate가 무엇을 검사하는가?" idea={<>Fixed selector가 활성화된 row에서 advice columns a,b,c를 query합니다. Selector가 0인 row에는 같은 expression이 있어도 constraint가 적용되지 않습니다.</>} formula={String.raw`q_M(X)\bigl(a(X)b(X)-c(X)\bigr)=0\quad\text{on the row domain}`} terms={[{symbol:"a,b,c",name:"Advice columns",description:"Private witness cells를 담는 polynomial columns입니다."},{symbol:"q_M",name:"Fixed selector",description:"Multiplication gate가 적용되는 rows에서 1입니다."},{symbol:"X",name:"Row-domain point",description:"현재 row를 나타내는 evaluation-domain 원소입니다."},{symbol:"ab-c",name:"Gate expression",description:"예에서 3·4−12=0입니다."}]} assumptions={["Column type·row ordering·selector assignment가 keygen 때 고정됩니다.","Rotation query가 유효한 row와 wrap/boundary policy를 지킵니다.","Public instance와 advice cells는 필요한 copy/equality constraints로 연결됩니다."]} interpretation="qM=1이면 3·4−12=0입니다. qM=0이면 w=5,c=12처럼 틀린 witness도 이 gate에서는 걸리지 않으므로 selector coverage를 malicious fixtures로 검사해야 합니다."/><p>Instance는 공개 입력, advice는 private witness, fixed는 selector/table 같은 회로 고정값입니다. Region은 layout namespace일 뿐 보안 경계가 아닙니다. 현재/다음 행 transition은 Rotation::cur/next queries로 명시하고 마지막 row 적용 범위를 selector로 제한합니다.</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border/70 p-4 text-sm"><strong>Gate</strong><p className="mt-2 text-muted-foreground">Row-local polynomial identity</p></div><div className="rounded-lg border border-border/70 p-4 text-sm"><strong>Copy</strong><p className="mt-2 text-muted-foreground">Equality-enabled cells의 permutation relation</p></div><div className="rounded-lg border border-border/70 p-4 text-sm"><strong>Lookup</strong><p className="mt-2 text-muted-foreground">Value tuple의 fixed/dynamic table membership</p></div></div><p><strong>반례:</strong> 두 regions에 honest code가 같은 w=4를 assign해도 constrain_equal이 없으면 malicious prover는 서로 다른 값을 넣을 수 있습니다. Range lookup도 table expression과 input expression이 실제 lookup argument에 등록돼야 합니다.</p><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="plonk.rs — VK/PK struct" onClick={() => sidebar.open("plonk-mod", codeRefs["plonk-mod"])} /><CodeViewButton label="circuit.rs — Chip/Cell/Region/Layouter" onClick={() => sidebar.open("circuit-trait", codeRefs["circuit-trait"])} /></div></section>
<section id="proof-pipeline" className="space-y-6"><header><p className="text-sm font-semibold text-primary">02 · Keygen, prove, verify</p><h2 className="mt-2 text-2xl font-bold">Circuit shape와 implementation profile을 key에 고정한다</h2></header><p>Configure가 columns·gates·queries를 만들고 synthesis가 fixed assignments와 region layout을 실행합니다. Keygen은 params·circuit shape·fixed data로 VK/PK를 만들며, proof 생성은 advice witness와 public instances를 commitment·challenge·opening 순서로 transcript에 넣습니다. Verify는 같은 params/VK/instance/profile로 이를 검사합니다.</p><ExplainedFormula question="한 배포가 어떤 Halo2 proof profile을 사용했는지 최소 무엇으로 식별해야 하는가?" idea={<>Framework 이름 대신 source commit, curve, PCS, parameter degree와 transcript/serialization을 묶어 key와 proof compatibility를 고정합니다.</>} formula={String.raw`\mathsf{Profile}=H(\mathsf{repo\_commit}\parallel\mathsf{curve}\parallel\mathsf{PCS}\parallel k\parallel\mathsf{transcript}\parallel\mathsf{circuit\_hash})`} terms={[{symbol:"repo_commit",name:"Source pin",description:"검증한 정확한 implementation snapshot입니다."},{symbol:"PCS",name:"Commitment profile",description:"Zcash IPA 또는 별도 KZG fork 등입니다."},{symbol:"k",name:"Domain degree",description:"2^k rows를 수용하는 parameter입니다."},{symbol:"circuit_hash",name:"Circuit identity",description:"Constraint shape·fixed data·public layout을 식별합니다."},{symbol:"H",name:"Manifest digest",description:"운영 식별자이며 cryptographic proof 자체를 대체하지 않습니다."}]} assumptions={["Canonical serialization과 domain separation을 versioned manifest에 고정합니다.","VK/PK·params는 같은 profile에서 생성하고 cross-profile input을 reject합니다.","Digest는 source review·ceremony/parameter validation·negative tests와 함께 사용합니다."]} interpretation="Zcash halo2 commit cafc26e의 IPA proof와 KZG fork proof는 둘 다 Halo2-style circuit을 쓸 수 있어도 같은 profile이 아닙니다. 이름이 같다는 이유로 key/proof 호환성을 추정하지 않습니다."/><div className="not-prose flex flex-wrap gap-3"><CodeViewButton label="keygen_vk()" onClick={() => sidebar.open("keygen-vk", codeRefs["keygen-vk"])} /><CodeViewButton label="keygen_pk()" onClick={() => sidebar.open("keygen-pk", codeRefs["keygen-pk"])} /><CodeViewButton label="create_proof()" onClick={() => sidebar.open("create-proof", codeRefs["create-proof"])} /><CodeViewButton label="verify_proof()" onClick={() => sidebar.open("verify-proof", codeRefs["verify-proof"])} /></div></section>
<section id="release" className="space-y-6"><header><p className="text-sm font-semibold text-primary">03 · Release gate</p><h2 className="mt-2 text-2xl font-bold">Underconstraint를 먼저 찾고 cryptographic cost를 나중에 잰다</h2></header><p>Valid w=4와 invalid w=5, selector-off, missing copy, range overflow, wrong instance order, wrong VK/params, malformed proof를 차례로 실행합니다. MockProver의 semantic result와 실제 verifier result가 일치한 뒤 synthesis·keygen·prove·verify time, rows/k, FFT/MSM, peak RSS와 proof/key bytes를 측정합니다.</p><p>Migration은 old/new VK·proof cross-matrix와 persisted proof rejection을 포함하며 rollback manifest에는 source commit, binary, params, VK hash와 circuit hash를 남깁니다.</p><div id="paper-halo"><CitationBlock source="Bowe·Grigg·Hopwood · Halo (2019)" citeKey={1} href="https://eprint.iacr.org/2019/1021.pdf"><p><strong>문제:</strong> Trusted setup 없이 proof composition과 polynomial verification을 누적해야 합니다.</p><p><strong>기여:</strong> IPA commitment와 accumulation을 이용한 Halo construction을 제시합니다.</p><p><strong>전제:</strong> Curve cycle, DLP, random oracle와 논문의 model을 사용합니다.</p><p><strong>근거 범위:</strong> Halo protocol·experiment 범위입니다.</p><p><strong>말하지 않는 것:</strong> Halo2의 모든 PLONKish API와 현재 source behavior를 직접 규정하지 않습니다.</p></CitationBlock></div><div id="paper-zcash-halo2-source"><CitationBlock source="zcash/halo2 · pinned cafc26e" citeKey={2} type="code" href="https://github.com/zcash/halo2/tree/cafc26e269e4b1b123af8f2a0aa36bff6474448e"><p><strong>문제:</strong> Column/region/keygen/prover/verifier의 실제 IPA profile을 고정해야 합니다.</p><p><strong>기여:</strong> 공식 Rust source·gadgets·book snapshot을 제공합니다.</p><p><strong>전제:</strong> Commit cafc26e와 Cargo.lock/toolchain/features를 pin합니다.</p><p><strong>근거 범위:</strong> 선택 snapshot의 source/API/tests입니다.</p><p><strong>말하지 않는 것:</strong> KZG forks·모든 downstream gadgets·production audit를 보장하지 않습니다.</p></CitationBlock></div><p>10문항은 gate 계산, column ownership, rotations, gate/copy/lookup, pipeline, IPA/KZG profile, selector/copy 반례와 migration/release를 다루며 본문만으로 답할 수 있습니다.</p></section>
</article>
<CodeSidebar
  codeRefKey={sidebar.codeRefKey}
  codeRef={sidebar.codeRef}
  onClose={sidebar.close}
  onNavigate={sidebar.navigate}
  codeRefs={codeRefs}
  fileTrees={{ "halo2_proofs/src": halo2Tree }}
  projectMetas={{
    "halo2_proofs/src": {
      id: "halo2_proofs/src",
      label: "zcash/halo2 · Rust",
      badgeClass: "bg-orange-500/10 border-orange-500 text-orange-700",
    },
  }}
/>
</>}
