export const API_SURFACES = [
  {
    id: "registration",
    name: "validator registration",
    method: "POST",
    endpoint: "/eth/v1/builder/validators",
    caller: "mev-boost / CL-side integration",
    desc: "fee recipient와 gas limit preferences를 signed registration으로 relay에 알린다.",
    color: "#6366f1",
  },
  {
    id: "header",
    name: "blinded bid request",
    method: "GET",
    endpoint: "/eth/v1/builder/header/{slot}/{parent}/{pubkey}",
    caller: "proposer-side builder client",
    desc: "slot과 parent에 맞는 signed builder bid를 요청하고 policy에 따라 후보를 평가한다.",
    color: "#0ea5e9",
  },
  {
    id: "payload",
    name: "blinded block submission",
    method: "POST",
    endpoint: "/eth/v1/builder/blinded_blocks",
    caller: "proposer-side builder client",
    desc: "signed blinded beacon block을 제출하고 선택된 full execution payload를 받는다.",
    color: "#10b981",
  },
  {
    id: "bundle",
    name: "private bundle submission",
    method: "JSON-RPC",
    endpoint: "eth_sendBundle 계열",
    caller: "searcher → builder/relay service",
    desc: "ordered transactions와 target constraints를 전달하는 private orderflow API이며 validator Builder API와 별도 surface다.",
    color: "#f59e0b",
  },
] as const;
