import ExplainedFormula from "@/components/ui/explained-formula";
import TermBreakdown from "@/components/articles/term-breakdown";
import QualityFrontierViz from "./viz/QualityFrontierViz";
export default function SAEArchitecture(){return <section id="sae-architecture" className="mb-16 scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Reconstruction과 sparsity는 서로 다른 실패를 막는다</h2><div className="prose prose-neutral dark:prose-invert max-w-none"><p className="leading-7">Reconstruction만 최적화하면 넓은 latent를 모두 써서 activation을 복사할 수 있고, sparsity만 강하게 요구하면 대부분을 0으로 만들어 정보를 잃는다. L1-ReLU SAE는 encoder activation의 절댓값 합에 벌점을 주어 두 목표를 한 loss에서 맞바꾼다.</p></div><ExplainedFormula question="L1-ReLU SAE는 feature 선택과 activation 복원을 어떻게 함께 학습할까?" idea={<>Encoder는 bias를 뺀 activation을 넓은 latent로 보낸 뒤 ReLU로 음수를 0으로 만듭니다. Decoder는 활성 feature direction을 합치며, L1 term은 동시에 켜지는 latent를 줄입니다.</>} formula={String.raw`\begin{aligned}\mathbf z&=\operatorname{ReLU}(W_e(\mathbf x-\mathbf b_d)+\mathbf b_e)\\\widehat{\mathbf x}&=W_d\mathbf z+\mathbf b_d\\\mathcal L&=\|\mathbf x-\widehat{\mathbf x}\|_2^2+\lambda\|\mathbf z\|_1\end{aligned}`}
annotatedFormula={String.raw`\begin{aligned}\mathbf z&=\underbrace{\operatorname{ReLU}(W_e(\mathbf x-\mathbf b_d)+\mathbf b_e)}_{\text{encoder 계산}}\\\widehat{\mathbf x}&=\underbrace{W_d\mathbf z+\mathbf b_d}_{\text{dictionary 계산}}\\\mathcal L&=\underbrace{\|\mathbf x-\widehat{\mathbf x}\|_2^2+\lambda\|\mathbf z\|_1}_{\text{sparsity weight 계산}}\end{aligned}`}
operations={[
  { expression: String.raw`\operatorname{ReLU}(W_e(\mathbf x-\mathbf b_d)+\mathbf b_e)`, annotation: ["encoder이(가) 식의 결과에 기여하는 방식을 계산합니다.","Encoder는 bias를 뺀 activation을 넓은","latent로 보낸 뒤 ReLU로 음수를 0으로 만듭니다."] },
  { expression: String.raw`W_d\mathbf z+\mathbf b_d`, annotation: ["dictionary이(가) 식의 결과에 기여하는 방식을","계산합니다.","Encoder는 bias를 뺀 activation을 넓은","latent로 보낸 뒤 ReLU로 음수를 0으로 만듭니다."] },
  { expression: String.raw`\|\mathbf x-\widehat{\mathbf x}\|_2^2+\lambda\|\mathbf z\|_1`, annotation: ["sparsity weight이(가) 식의 결과에 기여하는","방식을 계산합니다.","Encoder는 bias를 뺀 activation을 넓은","latent로 보낸 뒤 ReLU로 음수를 0으로 만듭니다."] },
]} terms={[{symbol:"W_e",name:"encoder",description:"Activation을 m개의 candidate feature score로 투영합니다."},{symbol:"W_d",name:"dictionary",description:"각 latent를 원래 d차원 space의 decoder direction으로 되돌립니다."},{symbol:String.raw`\lambda`,name:"sparsity weight",description:"Reconstruction과 active magnitude 사이의 operating point를 정합니다."}]} assumptions={["Decoder column scale을 통제하지 않으면 z를 작게, decoder를 크게 만들어 L1 penalty를 우회할 수 있습니다.","Training corpus가 분석하려는 activation distribution을 충분히 대표해야 합니다."]} interpretation="L1은 differentiable하지만 작은 진짜 activation까지 줄이는 shrinkage bias가 있습니다. 따라서 λ 하나의 결과를 정답으로 보지 않고 sparsity–reconstruction frontier에서 여러 checkpoint를 비교합니다."/><div className="prose prose-neutral dark:prose-invert max-w-none"><h3>L1·Gated·JumpReLU·Top-K는 sparsity 계약이 다르다</h3><p>Gated SAE는 feature가 켜질지와 켜진 뒤 크기를 별도 경로로 추정해 L1 shrinkage를 줄이려 한다. JumpReLU는 학습한 threshold를 넘을 때만 activation을 통과시키며 threshold gradient에는 별도 estimator가 필요하다. Top-K는 sample마다 score가 큰 K개만 남겨 L0를 직접 고정하므로 sparsity tuning은 쉬워지지만 모든 sample에 같은 K가 적절하다는 가정을 둔다.</p></div><ExplainedFormula question="Top-K SAE는 sample당 active feature 수를 어떻게 직접 고정할까?" idea={<>Encoder score 중 가장 큰 K개 index만 유지하고 나머지를 0으로 만듭니다. L1 coefficient 대신 active count가 architecture에 들어갑니다.</>} formula={String.raw`\begin{aligned}\mathbf a&=W_e\mathbf x+\mathbf b_e\\\mathbf z&=\operatorname{TopK}_K(\mathbf a),\quad \|\mathbf z\|_0\le K\end{aligned}`}
annotatedFormula={String.raw`\begin{aligned}\mathbf a&=\underbrace{W_e\mathbf x+\mathbf b_e}_{\text{오른쪽 항으로 결과 계산}}\\\mathbf z&=\underbrace{\operatorname{TopK}_K(\mathbf a),\quad \|\mathbf z\|_0\le K}_{\text{허용 경계 판정}}\end{aligned}`}
operations={[
  { expression: String.raw`W_e\mathbf x+\mathbf b_e`, annotation: ["왼쪽 결과를 오른쪽의 실제 항으로 계산합니다.","Encoder score 중 가장 큰 K개 index만","유지하고 나머지를 0으로 만듭니다."] },
  { expression: String.raw`\operatorname{TopK}_K(\mathbf a),\quad \|\mathbf z\|_0\le K`, annotation: ["계산한 양을 허용 경계와 비교해 상태를 판정합니다.","Encoder score 중 가장 큰 K개 index만","유지하고 나머지를 0으로 만듭니다."] },
]} terms={[{symbol:String.raw`\operatorname{TopK}_K`,name:"top-K activation",description:"각 sample의 encoder score 중 K개 위치만 보존하는 연산입니다."},{symbol:"K",name:"sparsity budget",description:"한 activation을 설명할 최대 active latent 수입니다."}]} assumptions={["K가 corpus와 hook point의 feature density에 맞는지 validation합니다.","Discrete selection의 학습 방식과 decoder normalization은 구현별로 확인합니다."]} interpretation="Top-K는 sparsity를 정확히 비교하기 쉽지만 중요 feature가 K+1위로 밀리면 완전히 사라집니다. L1보다 항상 해석 가능하다는 뜻은 아니며 같은 compute와 recovery 조건에서 평가해야 합니다."/><QualityFrontierViz/><ExplainedFormula question="평균 activation을 예측하는 기준선보다 SAE reconstruction이 얼마나 나은지 어떻게 볼까?" idea={<>Fraction of variance explained(FVE)는 reconstruction residual variance를 원 activation의 centered variance와 비교합니다.</>} formula={String.raw`\operatorname{FVE}=1-\frac{\mathbb E\|\mathbf x-\widehat{\mathbf x}\|_2^2}{\mathbb E\|\mathbf x-\bar{\mathbf x}\|_2^2}`}
annotatedFormula={String.raw`\operatorname{FVE}=\underbrace{1-\frac{\mathbb E\|\mathbf x-\widehat{\mathbf x}\|_2^2}{\mathbb E\|\mathbf x-\bar{\mathbf x}\|_2^2}}_{\text{확률 가중 평균}}`}
operations={[
  { expression: String.raw`1-\frac{\mathbb E\|\mathbf x-\widehat{\mathbf x}\|_2^2}{\mathbb E\|\mathbf x-\bar{\mathbf x}\|_2^2}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","Fraction of variance","explained(FVE)는 reconstruction","residual variance를 원 activation의"] },
]} terms={[{symbol:String.raw`\widehat{\mathbf x}`,name:"SAE reconstruction",description:"Sparse latent를 decoder로 합친 activation 근사입니다."},{symbol:String.raw`\bar{\mathbf x}`,name:"mean baseline",description:"평가 activation corpus의 평균 vector입니다."}]} assumptions={["같은 held-out activation distribution에서 FVE를 계산합니다.","높은 FVE와 높은 interpretability는 같은 metric이 아닙니다."]} interpretation="FVE가 1에 가까울수록 activation variance를 많이 복원하지만 작은 behavior-critical direction을 놓칠 수 있습니다. 원본을 SAE reconstruction으로 교체했을 때 language-model loss가 얼마나 회복되는지도 함께 봅니다."/><TermBreakdown title="Dead latent가 생기는 이유와 되살리는 방법" items={[
  {
    term: "Dead latent",
    description: "Encoder가 학습 corpus의 어떤 activation에도 반응하지 않아(z_j=0이 항상 유지) 그 latent의 decoder column이 gradient를 전혀 받지 못하는 상태입니다. ReLU/Top-K 모두 활성화가 0이면 해당 방향의 gradient도 0이라 한 번 죽으면 스스로 되살아나지 않습니다.",
    example: "폭넓은 초기화 뒤 학습 초반 몇 step 안에 특정 latent가 우연히 한 번도 top-K에 들지 못하면, 그 latent는 이후 영원히 선택되지 않을 수 있습니다.",
    boundary: "Dead latent 비율이 높다는 것은 사실상 SAE의 유효 width가 명시된 width보다 작다는 뜻이라, width를 그대로 비교 지표로 쓰면 안 됩니다.",
  },
  {
    term: "Resurrection 기법",
    description: "주기적으로 오래 죽어 있던 latent의 encoder/decoder weight를 재초기화(reinit)하거나, 현재 reconstruction이 잘 설명하지 못하는 residual을 죽은 latent로 다시 맞추도록 별도 auxiliary loss를 추가해 gradient를 되돌려줍니다.",
    example: "Reinit은 죽은 latent의 encoder row를 최근 큰 reconstruction error를 낸 activation 방향으로 다시 설정합니다.",
    boundary: "Resurrection 자체가 목적이 아닙니다 — 되살린 latent가 실제로 해석 가능한 feature를 학습하는지 별도로 확인해야 합니다.",
  },
]}/></section>}
