import { Link } from "react-router-dom";
import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import { CitationBlock } from "@/components/ui/citation";
import AlgorithmBlock from "@/components/ui/algorithm-block";
import ProgressiveDetail from "@/components/articles/progressive-detail";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefs } from "./serving-memory-admission-and-preemption/codeRefs";
import { memorySourceTree } from "./serving-memory-admission-and-preemption/fileTree";
import ServingMemoryAdmissionAndPreemptionViz from "./serving-memory-admission-and-preemption/viz/ServingMemoryAdmissionAndPreemptionViz";

export default function Article() {
  const sidebar = useCodeSidebar();
  return <><div className="space-y-16">
<section id="overview" data-teach-level="S" className="scroll-mt-20"><span id="problem" className="scroll-mt-20" /><h2 className="mb-6 text-2xl font-bold">1. 처음 들어갔던 요청도 나중에는 자리를 잃을 수 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>답변을 이어 쓰는 동안 서버는 앞에서 계산한 결과를 계속 보관합니다. 처음에는 들어갈 자리가 있어도 답변이 길어지면 저장 공간이 모자랄 수 있습니다. 그러면 새 요청을 기다리게 하거나 진행 중인 요청을 잠시 멈춰야 합니다.</p><p>이 글은 요청 하나를 받았다가 공간이 부족해 멈추고 다시 이어 쓰는 과정을 따라갑니다. 언제 들어갈 수 있는지와 멈춘 결과를 어떻게 되살리는지를 구분하면 메모리 설정을 바꿀 때 무엇이 달라지는지 보입니다.</p></div></section>

<section id="black-box" data-teach-level="B" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">2. 들어갈 공간을 확인하고 성장한 만큼 다시 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>바깥에서 보면 네 단계입니다. 새 요청이 요구하는 공간을 셉니다. 현재 빈 공간과 비교합니다. 답변이 자라면 추가 공간을 배정합니다. 부족해 멈춘 요청은 결과를 다시 마련한 뒤 진행 목록으로 돌아옵니다.</p><p>계산할 시간이 남아 있어도 결과를 저장할 주소가 없으면 실행할 수 없습니다. 반대로 빈 공간이 있어도 이번 실행의 계산량이나 요청 개수 한도에 걸릴 수 있습니다. 아래에서는 그 다른 한도는 충분하다고 놓고 저장 공간의 변화만 봅니다.</p></div></section>

<section id="small-case" data-teach-level="0" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">3. 40칸 중 14칸이 비어 있고 C가 9칸을 원합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>같은 크기의 저장 칸 40개가 있다고 합시다. 먼저 온 A가 14칸, B가 12칸을 쓰므로 빈 칸은 14개입니다. 새 요청 C는 9칸을 요구합니다. 새 요청을 받은 뒤 최소 3칸을 남기기로 정합니다. 모든 숫자는 설명용 가정입니다. (가정)</p><p>C를 넣으면 14−9=5칸이 남습니다. 5는 하한 3보다 크므로 지금은 받을 수 있습니다. 그러나 이후 A·B·C가 계속 자라면 이 5칸도 줄어듭니다. 처음 통과했다는 사실이 끝까지 자리를 보장하지는 않습니다.</p><p>한 칸에 입력 위치 16개를 저장한다고 둡니다. C의 입력 144개가 9칸을 채웁니다. A와 B는 C가 처음 계산되는 실행에서 각각 224개와 192개 위치까지 채웁니다. 이 숫자를 뒤에서 그대로 이어 계산하겠습니다. (가정)</p></div></section>

<section id="inside-admission" data-teach-level="1" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">4. 공간 장부와 대기 목록이 서로 다른 일을 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>공간 장부는 누구에게 몇 칸을 연결했으며 몇 칸이 비었는지 기록합니다. 진행 목록은 이번에 계속 계산할 요청을 담고 대기 목록은 아직 들어갈 수 없는 요청을 담습니다. 선택한 요청에 실제 공간을 연결한 뒤에만 수용 성공으로 기록해야 합니다.</p><p>요청을 멈출 때도 두 기록을 함께 바꿉니다. 공간을 되찾았는데 여전히 진행 중이라고 기록하면 다음 실행이 유효하지 않은 주소를 읽을 수 있습니다. C의 위치와 9칸의 소유권을 함께 추적하는 이유입니다.</p></div></section>

<section id="why-headroom" data-teach-level="2" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">5. 남겨 둔 3칸은 다음 성장을 위한 여유입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>새 요청이 빈 칸을 전부 쓰면 먼저 들어온 A와 B가 바로 다음 위치를 저장하지 못할 수 있습니다. 그래서 새 요청을 받을 때만 얼마를 남길지 검사합니다. 이미 진행 중인 요청의 성장에는 이 사례의 하한을 적용하지 않습니다.</p><p>3칸은 특정한 마지막 주소 세 개를 잠그는 규칙이 아닙니다. 수용 뒤 남은 빈 칸의 개수에 대한 조건입니다. A·B·C가 자라면 빈 칸이 3보다 작아질 수 있고 결국 추가 수요를 못 채울 수도 있습니다.</p><p>여유를 크게 남기면 한꺼번에 받는 요청은 줄어듭니다. 중단 횟수가 얼마나 줄고 처리량이 어떻게 바뀌는지는 실제 요청 길이에 달려 있습니다. 이제 앞서 본 공간과 판정에 이름을 붙입니다.</p></div></section>

<section id="memory-terms" data-teach-level="3" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">6. 보관 공간과 수용 판정에 이름을 붙입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>이전에 계산한 key와 value를 보관한 것이 KV cache입니다. 일정 수의 토큰 위치를 담는 한 칸을 block, 그런 칸들을 모아 관리하는 공간을 pool이라고 합니다. </p><p>아래 이름은 이미 본 역할의 대응표입니다. C가 처음 들어오는 조건과 이후 중단 조건을 구분해서 읽으면 됩니다.</p></div><TermBreakdown title="역할을 이해한 뒤 이름을 붙입니다" items={[{"term":"Token", "description":"모델이 입력과 출력을 나눠 처리하는 단위입니다.","boundary":"문자나 단어 하나와 항상 일치하지 않습니다."},{"term": "Request memory footprint", "description": "요청이 보존할 계산 결과에 필요한 저장 용량입니다. C의 입력 144토큰은 이 사례에서 9block입니다.", "boundary": "최대 생성 길이의 용량과 지금 실제 배정한 용량은 다릅니다."}, {"term": "Memory admission control", "description": "새 요청의 저장 공간을 확보할 수 있는지 확인하는 수용 판정입니다.", "boundary": "계산량·진행 요청 수까지 함께 확인하는 전체 request admission control의 일부입니다."}, {"term": "Memory watermark", "description": "신규 수용 뒤 남길 free block 개수의 하한입니다. 여기서는 3입니다.", "boundary": "특정 주소 예약이 아니며 진행 요청의 성장까지 항상 막지는 않습니다."}, {"term": "Memory pressure", "description": "요청들이 더 요구하는 공간을 현재 빈 공간으로 충족하지 못하는 상태입니다.", "boundary": "전체 장비 용량만으로 결정되지 않고 현재 요청 길이와 수에도 달려 있습니다."}, {"term": "Preemption", "description": "진행 중인 요청을 잠시 빼서 다른 요청을 계속 처리하게 하는 조치입니다.", "boundary": "누구를 멈출지와 저장 결과를 어떻게 복구할지는 별도의 선택입니다."}]} /></section>

<section id="watermark-admission" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">7. C를 받으면 빈 공간이 14에서 5로 줄어듭니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>C의 입력을 읽는 첫 계산을 prefill이라고 합니다. 입력 144를 block 크기 16으로 나누면 정확히 9입니다. 요청 자리와 토큰 예산도 충분한 상태에서 14−9=5≥3이므로 C를 수용합니다. (가정)</p><p>이 규칙을 쓰는 동안 빈 공간이 11개였다면 11−9=2로 대기합니다. 공간 9개 자체는 들어가지만 수용 뒤 남길 하한을 만족하지 못하기 때문입니다. 하한 검사와 물리적으로 전혀 못 들어가는 상황은 다릅니다.</p><p>C가 입력을 끝내고 첫 답변 토큰을 만들었다고 합시다. 이때 저장된 C의 계산 위치는 144개입니다. 방금 만들어 낸 출력 토큰을 다음 실행의 입력으로 처리해야 그 위치의 KV가 생깁니다. 출력 토큰 개수와 이미 저장된 위치를 혼동하지 않습니다.</p></div></section>

<section id="growth-pressure" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">8. 16번 더 이어 쓰면 다음 한 칸이 부족합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>답변을 이어 쓰는 단계를 decode라고 합니다. 첫 실행 뒤 A·B·C의 저장된 위치는 224·192·144입니다. 각 요청이 16번 더 진행하면 240·208·160이 되고 각각 15·13·10block이 필요합니다. (가정)</p><p>합계 38block을 쓰므로 빈 공간은 2개입니다. 세 요청이 다음 위치인 241·209·161을 처리하려면 각각 한 block을 더 받아야 합니다. 수요 3이 잔여 2보다 큽니다. 이것이 같은 사례의 memory pressure입니다.</p><p>도착 순서 A→B→C로 처리한다고 둡니다. A와 B에 하나씩 배정한 뒤 C는 실패합니다. 가장 늦게 온 C를 멈춰 전용 block 10개를 반환하면 A16·B14·C0, 빈 공간 10개가 됩니다. 입력 재사용과 공유 참조, 비동기 실행은 없는 가정입니다.</p></div></section>

<section id="resume-trace" data-teach-level="4" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">9. C는 10칸을 돌려줬지만 11칸이 있어야 돌아옵니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>C의 토큰 이력에는 다음에 처리할 토큰까지 161개가 남아 있습니다. 저장 결과를 버리고 다시 계산하려면 ceil(161/16)=11block이 필요합니다. 빈 공간 10개로는 부족하고 하한 3도 만족하지 못합니다. 반환한 10개만 다시 받으면 된다고 계산해서는 안 됩니다.</p><p>A가 끝나 16block을 반환하면 빈 공간은 26개입니다. C가 11개를 받아도 15개가 남으므로 돌아올 수 있습니다. C의 이미 전달한 답변을 사용자에게 다시 생성해 보내는 것이 아니라 토큰 이력을 읽어 내부 저장 결과를 복원합니다. (가정)</p><p>아래 장면은 같은 C의 수용부터 재개까지 이어집니다. 가운데 성장 장면은 실행 한 번이 아니라 16번을 모은 결과입니다.</p></div><ServingMemoryAdmissionAndPreemptionViz /></section>

<section id="footprint" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">10. 한 block의 2MiB는 모델의 저장 모양에서 나옵니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>지금까지 block 개수만 셌습니다. byte로 바꾸려면 key와 value 각각의 저장 크기를 알아야 합니다. 32층이 각각 KV head 8개, head 차원 128, 숫자당 2byte를 저장한다고 둡니다. 토큰당 2×32×8×128×2=131072byte, 즉 128KiB입니다. (가정)</p><p>16토큰 block은 2MiB이므로 C의 첫 9block은 18MiB입니다. 같은 구조에서 입력 1000토큰은 63block, 126MiB입니다. 보존 길이가 1500까지 간다면 94block, 188MiB가 됩니다. 마지막 block의 빈 위치도 배정 용량에 포함합니다.</p><p>
            길이에 따라 늘어나는 이러한 공간이 sequence-length-dependent allocation입니다. 아래 식은 입력과 생성 상한을 합친 최대 보존 길이를 계산합니다.
            실제 종료 시 마지막 출력의 KV가 아직 없다면 한 위치 적을 수 있으며 수용 즉시 이 상한 전부를 예약한다는 식은 아닙니다.
          </p></div><ExplainedFormula
          question="요청 하나가 끝까지 갔을 때 GPU KV pool에서 차지하는 byte는 얼마인가요?"
          idea="Token 수를 block 단위로 올림해 block 수를 얻고, model 구조가 정하는 block당 byte를 곱합니다. 마지막 block의 빈자리도 이 요청의 몫입니다."
          formula={String.raw`F_r=\left\lceil \frac{L_p+L_g}{B}\right\rceil\cdot B\cdot 2\,n_{layer}\,n_{kv}\,d_h\,s`}
          annotatedFormula={String.raw`F_r=\underbrace{\left\lceil \frac{L_p+L_g}{B}\right\rceil}_{\text{필요 block 수}}\cdot\underbrace{B\cdot\underbrace{2\,n_{layer}\,n_{kv}\,d_h\,s}_{\text{token당 byte}}}_{\text{block당 byte}}`}
          operations={[
            { expression: String.raw`\left\lceil \frac{L_p+L_g}{B}\right\rceil`, annotation: ["prompt와 생성 상한을 더해 block 크기로 올림해", "마지막 block의 빈자리까지 포함한 block 수 계산"] },
            { expression: String.raw`2\,n_{layer}\,n_{kv}\,d_h\,s`, annotation: ["key와 value를 layer·head·dim·dtype로 곱해", "token 하나의 byte 결정"] },
            { expression: String.raw`B\cdot 2\,n_{layer}\,n_{kv}\,d_h\,s`, annotation: ["token당 byte에 block의 token 수를 곱해", "할당 단위 하나의 byte 확정"] },
          ]}
          terms={[
            { symbol: "L_p", name: "Prompt 길이", description: "조각으로 나눌 수도 있는 전체 입력 token 수입니다." },
            { symbol: "L_g", name: "생성 상한", description: "max_tokens처럼 요청이 만들 수 있는 최대 출력 token 수입니다." },
            { symbol: "B", name: "Block당 token 수", description: "이 사례는 16으로 가정합니다. 실제 지원값은 버전과 backend에 따라 확인합니다." },
            { symbol: String.raw`n_{layer}`, name: "KV를 저장하는 layer 수", description: "Full attention layer만 셉니다." },
            { symbol: String.raw`n_{kv}`, name: "KV head 수", description: "GQA에서는 query head보다 적습니다." },
            { symbol: "d_h", name: "Head dim", description: "Head 하나의 key 또는 value 차원입니다." },
            { symbol: "s", name: "Dtype byte", description: "FP16·BF16은 2, FP8은 1입니다." },
          ]}
          assumptions={["Full attention layer만 계산합니다. Sliding-window·MLA·quantized KV는 token당 byte가 달라집니다.", "Prefix cache hit은 0으로 두었습니다. Hit이 있으면 그만큼 block을 공유합니다."]}
          interpretation="이 식은 지정한 최대 보존 길이에 대한 byte 상한입니다. 미래 생성 상한의 예약, 전체 입력이 들어가는지 검사, 이번 조각의 실제 할당은 서로 다릅니다. 마지막 생성 토큰의 KV가 아직 만들어지지 않았다면 실제 보존 위치는 하나 적을 수 있습니다."
        /></section>

<section id="source-v0-admission" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">11. 과거 코드의 세 판정에 C를 넣어 봅니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>vLLM v0.6.6의 SelfAttnBlockSpaceManager.can_allocate 원문은 전체 용량부터 확인합니다. 전체에서 요청 몫을 빼도 하한을 못 남기면 NEVER입니다. 현재 free에서 뺀 값이 하한 이상이면 OK, 그 밖에는 LATER입니다.</p><p>C의 값 40·14·9·3을 넣으면 전체 조건 40−9≥3을 통과하고 현재 조건 14−9≥3도 통과합니다. 같은 요청에서 free만 11로 줄면 LATER입니다. 전체로도 못 받는 요청을 계속 대기시키는 것과 공간이 나기를 기다리는 것을 구분합니다.</p><p>이 버전의 생성자 기본 비율은 0.01입니다. 본문의 W=3은 pool40에 비율 0.075를 별도로 지정한 값입니다. 기본값과 설명용 사례를 혼동하지 않습니다.</p></div><CodeViewButton label="V0 원문: 하한의 기본값" onClick={() => sidebar.navigate("v0-watermark-default", codeRefs["v0-watermark-default"])} /><CodeViewButton label="V0 원문: NEVER·OK·LATER" onClick={() => sidebar.navigate("v0-admission", codeRefs["v0-admission"])} /><div id="v0-watermark" className="mt-8 scroll-mt-20"><CitationBlock source="vLLM v0.6.6 · block_manager.py L138–145" citeKey={1} href="https://github.com/vllm-project/vllm/blob/f49777ba62b4926d0f8c100ab06edb03c5c10098/vllm/core/block_manager.py#L138-L145"><q>num_free_gpu_blocks - num_required_blocks &gt;= self.watermark_blocks</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>free14에서 C의 9를 빼면 5이므로 하한 3을 넘습니다. 이 원문 적용은 재사용·sliding window·lookahead·encoder가 없는 단일 attention 사례입니다.</p></div></div><ExplainedFormula
          question="새 요청을 지금 받아들여도 되는지는 어떤 부등식으로 정하나요?"
          idea="Admission 뒤에 남을 free block이 watermark 하한 이상이어야 합니다. Pool 전체로도 못 채우는 요청은 기다려도 소용없으므로 따로 거절합니다."
          formula={String.raw`\begin{aligned}\text{OK}&\iff N_{free}-\left\lceil L_p/B\right\rceil\ge W\\\text{NEVER}&\iff N_{total}-\left\lceil L_p/B\right\rceil<W\\W&=\lfloor w\,N_{total}\rfloor\end{aligned}`}
          annotatedFormula={String.raw`\underbrace{N_{free}-\left\lceil L_p/B\right\rceil}_{\text{admission 뒤 남는 free block}}\ \ge\ \underbrace{\lfloor w\,N_{total}\rfloor}_{\text{watermark 예약 block}},\qquad \underbrace{N_{total}-\left\lceil L_p/B\right\rceil<W}_{\text{pool 전체로도 불가능하면 NEVER}}`}
          operations={[
            { expression: String.raw`\left\lceil L_p/B\right\rceil`, annotation: ["전체 입력을 담을 block 수를 세어", "생성 상한은 admission 조건에서 제외"] },
            { expression: String.raw`N_{free}-\left\lceil L_p/B\right\rceil`, annotation: ["현재 free에서 이 요청 몫을 빼", "받아들인 직후의 여유 계산"] },
            { expression: String.raw`\lfloor w\,N_{total}\rfloor`, annotation: ["비율 w를 전체 block 수에 곱해", "실행 중 요청의 성장을 위한 여유"] },
            { expression: String.raw`N_{total}-\left\lceil L_p/B\right\rceil<W`, annotation: ["pool 전체로도 못 채우는 요청을 걸러", "LATER가 아닌 NEVER로 거절"] },
          ]}
          terms={[
            { symbol: String.raw`N_{free}`, name: "현재 free block 수", description: "이번 step 시작 시점에 어느 요청도 소유하지 않은 GPU block입니다." },
            { symbol: String.raw`N_{total}`, name: "전체 GPU block 수", description: "Profiling으로 잰 KV pool byte를 block당 byte로 나눈 값입니다." },
            { symbol: "W", name: "Watermark block 수", description: "신규 수용 뒤 남길 빈 공간의 개수입니다. 특정 주소를 영구히 잠그지 않습니다." },
            { symbol: "w", name: "Watermark 비율", description: "고정 v0.6.6에서 SelfAttnBlockSpaceManager의 기본값은 0.01입니다." },
          ]}
          assumptions={["고정 v0.6.6의 SelfAttnBlockSpaceManager.can_allocate의 OK·LATER·NEVER 조건을 옮긴 것입니다.", "재사용·공유·sliding window·lookahead·encoder가 없는 단일 full-attention 사례입니다. V1의 조건은 별도 원문으로 확인합니다."]}
          interpretation="40개 중 빈 공간 14, 입력 9, 하한 3이면 14−9=5로 OK입니다. 하한을 크게 하면 신규 수용 여유가 줄지만 중단 빈도와 처리량의 실제 변화는 workload에 달려 있습니다."
        /></section>

<section id="pool-budget" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">12. 54GiB를 block 수로 바꾼 뒤 같은 판정을 합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>크기 80GiB인 가상 장비에서 엔진 몫을 90%로 잡으면 72GiB입니다. 가중치 16GiB와 프로파일링한 작업 공간 2GiB를 빼고 나머지 비용이 이미 포함됐다고 가정하면 KV 예산은 54GiB입니다. 실제 제품의 80GB 표기를 80GiB로 바꿔 읽은 수치가 아닙니다. (가정)</p><p>2MiB block으로 나누면 27648개입니다. V0의 1% 하한은 floor(276.48)=276개, 즉 552MiB입니다. 입력 1000토큰의 63block을 받으려면 free300에서는 237이 남아 LATER이고 free350에서는 287이 남아 OK입니다.</p><p>장비 메모리 비율은 전체 pool을 정하는 입력입니다. 매 순간의 압박은 그 안에서 요청들이 얼마나 자랐는지에 달려 있습니다. 가중치와 작업 공간 외의 비용을 빼지 않은 예산으로 동시 요청 수를 약속하면 안 됩니다.</p></div></section>

<section id="source-v1-admission" data-teach-level="5" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">13. 현재 코드는 전체 입력 검사와 조각 할당을 나눕니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>현재 고정한 vLLM v0.27.1은 scheduler_reserve_full_isl의 기본값이 True입니다. 전체 입력 길이가 들어가는지 먼저 검사하고 실제로는 이번 조각에 필요한 공간을 배정합니다. 이것은 아직 생성하지 않은 최대 출력 길이 전부를 예약하는 규칙이 아닙니다.</p><p>입력 1000토큰, block16, free50이라고 합시다. 첫 조각이 256토큰이면 실제 조각에는 16block만 필요하지만 전체 입력에는 63개가 필요합니다. 하한 0이어도 전체 입력 검사에서 실패합니다. free70이라면 이 검사를 통과한 뒤 첫 조각 16개를 배정할 수 있습니다. (가정)</p><p>같은 버전의 watermark 기본값은 0.0입니다. 하한을 켠 경우에도 waiting 또는 preempted 요청이며 이미 배정된 요청이 있을 때 적용합니다. 본문의 C에는 A·B가 있으므로 3을 지정했다면 하한이 적용됩니다.</p><p>원문의 available_blocks는 예약 중인 공간까지 free에서 뺍니다. 여기서는 그 추가 예약이 0입니다. 여러 cache group이나 입력 재사용이 있으면 coordinator가 계산한 실제 추가 수요를 사용해야 합니다. 단순 ceil 식을 모든 모델에 그대로 넣지 않습니다.</p></div><CodeViewButton label="V1 원문: scheduler가 넘기는 검사 조건" onClick={() => sidebar.navigate("v1-scheduler-call", codeRefs["v1-scheduler-call"])} /><CodeViewButton label="V1 원문: 전체 입력 검사와 기본 하한" onClick={() => sidebar.navigate("v1-config", codeRefs["v1-config"])} /><CodeViewButton label="V1 원문: 전체 입력이 들어가는지 검사" onClick={() => sidebar.navigate("v1-fit", codeRefs["v1-fit"])} /><CodeViewButton label="V1 원문: 이번 조각의 실제 필요량" onClick={() => sidebar.navigate("v1-allocation", codeRefs["v1-allocation"])} /></section>

<section id="preemption-modes" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">14. 버리고 다시 계산할지 복사해 둘지 선택합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>저장 결과를 돌려주고 토큰 이력에서 다시 계산하는 방식이 recompute preemption입니다. C는 10block을 돌려준 뒤 161토큰을 다시 처리합니다. 토큰 이력은 유지하되 이전 KV 결과를 다시 만드는 GPU 계산이 필요합니다.</p><p>결과의 byte를 CPU 메모리에 복사했다가 되가져오는 방식이 swap preemption입니다. C의 10block, 20MiB를 저장해 두면 이미 계산한 160위치의 KV를 다시 만들 필요는 없습니다. 다만 다음 161번째 위치를 위한 공간은 추가로 필요합니다.</p><p>CPU에 공간이 있는지와 어느 요청을 멈출지는 별도의 결정입니다. 복사 경로가 지원되는지, 어떤 방식을 기본으로 쓰는지는 버전과 설정을 확인해야 합니다. 아래에서는 현재 재계산 경로와 과거 교환 경로를 각각 원문으로 봅니다.</p></div></section>

<span id="paper-vllm-docs" className="scroll-mt-20" /><section id="source-v1-preemption" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">15. C의 진행 상태를 0으로 되돌리는 코드를 읽습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>v0.27.1의 _preempt_request는 요청의 block을 해제하고 상태를 PREEMPTED로 바꿉니다. 이어 num_computed_tokens를 0으로 만든 뒤 waiting 앞에 넣습니다. 동기식이고 추가 참조가 없는 C라면 10개가 풀리고 다시 계산할 위치가 0이 됩니다.</p><p>요청의 토큰 이력을 지우는 코드가 아니므로 재개 시 161토큰을 다시 처리할 수 있습니다. 비동기 실행에서는 아직 돌아오지 않은 결과를 따로 추적하는 분기도 있습니다. 본문의 즉시 반환 계산을 그 경로의 모든 수명 관리에 그대로 적용하지 않습니다.</p><p>누구를 뺄지는 이 함수 바깥의 scheduler가 결정합니다. 도착 순서에서는 늦게 온 C를 고르지만 우선순위 정책을 켜면 다른 요청이 대상이 될 수 있습니다. 먼저 온 요청 우대가 과부하에서도 모두의 유한 대기 시간을 보장하지는 않습니다.</p></div><CodeViewButton label="V1 원문: block 해제와 PREEMPTED 상태" onClick={() => sidebar.navigate("v1-preempt", codeRefs["v1-preempt"])} /><AlgorithmBlock title="C를 중단하고 되살리는 경로 (의사코드)" input={["전용 block만 쓰는 A·B·C, 동기식 실행", "pool40, 하한 3, block16토큰"]} steps={[{"code": "A15, B13, C10; free ← 2", "note": "세 요청이 다음 위치를 처리하면 각각 추가 block 하나가 필요합니다."}, {"code": "allocate A1 and B1; allocation for C fails", "note": "진행 중인 요청 성장에는 이 사례의 하한을 적용하지 않습니다."}, {"code": "release C10; set C.computed ← 0; enqueue C", "note": "A16·B14가 남고 free10입니다. C의 토큰 이력 161은 보존합니다."}, {"code": "wait until admission conditions hold", "note": "C는 11block이 필요합니다. 요청 자리와 계산 예산도 통과해야 합니다."}, {"code": "when A completes: free ← 26; admit C11", "note": "재계산 공간을 얻은 뒤 free15이고 B14·C11이 연결됩니다."}]} output="C의 저장 결과를 복원하고 다음 생성으로 이어갑니다." /></section>

<section id="source-v0-swap" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">16. CPU 공간 실패를 다른 방식으로 바꿔 읽지 않습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>v0.6.6은 사용자가 모드를 지정하지 않았을 때 단일 생성 경로에는 RECOMPUTE, 여러 경로인 그룹에는 SWAP을 선택합니다. 이 결정 뒤 _swap_out에서 CPU 공간을 검사합니다. 공간이 없으면 RuntimeError를 발생시키며 자동으로 재계산 모드로 바꾸지 않습니다.</p><p>이 버전의 swap_space 기본값은 GPU당 4GiB입니다. 2MiB 단위라면 2048block이며 94block 요청 21개 분량입니다. 이는 byte 용량 비교이며 실제 정책에서 그런 요청 21개를 동시에 교환한다는 보장이 아닙니다.</p><p>C를 되가져올 때도 저장된 10block만 세면 부족할 수 있습니다. 다음 위치를 추가할 공간과 원문의 lookahead 및 복사 관련 수요까지 확인합니다. 단순 사례에서는 10개를 되가져오고 한 개를 더 써야 하므로 free10으로는 재개할 수 없습니다.</p></div><CodeViewButton label="V0 원문: 재계산과 교환 모드 선택" onClick={() => sidebar.navigate("v0-mode", codeRefs["v0-mode"])} /><CodeViewButton label="V0 원문: CPU 공간 부족 시 오류" onClick={() => sidebar.navigate("v0-swap-failure", codeRefs["v0-swap-failure"])} /><CodeViewButton label="V0 원문: 되가져올 block과 추가 수요" onClick={() => sidebar.navigate("v0-swap-admission", codeRefs["v0-swap-admission"])} /><CodeViewButton label="V0 원문: swap_space의 기본 용량" onClick={() => sidebar.navigate("v0-swap-default", codeRefs["v0-swap-default"])} /></section>

<section id="recovery-cost" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">17. 계산 시간과 왕복 전송 시간을 같은 요청으로 비교합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>8B 모델의 161토큰을 다시 처리하는 큰 행렬 연산을 2Pn으로 근사하면 2×8×10⁹×161입니다. 유효 계산 속도를 400TFLOP/s로 가정하면 6.44ms입니다. C의 20MiB를 25GB/s로 왕복 복사하는 시간은 2×20×2²⁰/(25×10⁹)초, 약 1.678ms입니다. (가정)</p><p>더 긴 1500토큰 사례에서는 재계산이 24TFLOP, 약 60ms입니다. 188MiB 왕복은 약 15.77ms입니다. 20MiB와 188MiB는 각각 편도 크기이며 왕복이라 2를 곱했습니다. 두 수치는 실측이 아니며 재계산 근사는 attention의 길이 제곱 항과 실행 준비 비용을 생략하고 전송 근사는 경합과 복사 준비를 생략합니다.</p><p>전송 배열의 배치도 중요합니다. 각 층의 key와 value를 block별로 따로 복사한다면 94×32×2=6016조각이고 각 조각은 16×8×128×2=32768byte입니다. 실제 구현은 여러 복사를 묶거나 데이터를 다르게 배치할 수 있으므로 6016번의 개별 전송 호출로 단정하지 않습니다.</p><p>재계산은 GPU 연산을 쓰고 교환은 호스트 공간과 연결 대역폭을 씁니다. 길어진 재계산이 다른 요청의 토큰 간격을 늘릴 수 있고 교환도 같은 연결을 쓰는 작업을 지연시킬 수 있습니다. 전체 요청의 완료 시간과 중단 빈도를 함께 재야 선택할 수 있습니다.</p></div></section>

<section id="hybrid-fixed-state" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">18. 길이가 짧아도 처음부터 필요한 상태가 있습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>과거 토큰 전체의 KV 대신 정해진 모양의 상태를 갱신하는 recurrent 층이 섞이면 다른 항을 더해야 합니다. 이처럼 요청마다 필요한 고정 상태를 따로 확보하는 것이 fixed recurrent-state allocation입니다. 상태 한 벌은 길이에 따라 계속 자라지 않아도 첫 실행부터 저장할 수 있어야 합니다.</p><p>48층이 각각 48×128×128개의 2byte 숫자를 상태 한 벌로 가진다고 가정하면 층당 1.5MiB, 합계 72MiB입니다. attention 16층은 앞의 head 조건에서 토큰당 64KiB, 16토큰 block당 1MiB입니다. 특정 공개 모델의 실제 전체 할당량을 인용한 값은 아닙니다. (가정)</p><p>100토큰은 KV 7MiB에 고정 상태 72MiB를 더해 79MiB입니다. 1500토큰은 94+72=166MiB입니다. 짧은 요청에서도 고정 항이 커서 길이만 보고 수용 개수를 늘리기 어렵습니다.</p><p>이 합계에는 convolution history, 상태 복사본과 prefix checkpoint, allocator padding이 없습니다. 실제 engine은 상태 종류별 group과 병렬 분할을 처리하므로 논리 byte를 곧바로 같은 물리 block 개수로 보지 않습니다. 아래 식은 그 차이를 생략한 용량 모형입니다.</p></div><ExplainedFormula
          question="두 상태를 같은 byte 단위로 환산한다면 필요한 공간을 어떻게 셀까요?"
          idea="전체 입력의 attention KV와 요청당 고정 상태를 더하는 용량 모형입니다. 실제 engine의 chunk 할당과 group별 공간 배정은 별도로 확인합니다."
          formula={String.raw`N_{need}(r)=\left\lceil \frac{L_p}{B}\right\rceil+\left\lceil \frac{n_{rec}\,S_{rec}}{\beta}\right\rceil`}
          annotatedFormula={String.raw`N_{need}(r)=\underbrace{\left\lceil \frac{L_p}{B}\right\rceil}_{\text{길이 비례 prefill block}}+\underbrace{\left\lceil \frac{n_{rec}\,S_{rec}}{\beta}\right\rceil}_{\text{요청당 고정 state block}}`}
          operations={[
            { expression: String.raw`\left\lceil \frac{L_p}{B}\right\rceil`, annotation: ["attention layer가 있는 model의 prefill 몫을", "block으로 올림"] },
            { expression: String.raw`n_{rec}\,S_{rec}`, annotation: ["recurrent layer 수에 layer당 state byte를 곱해", "요청 하나의 고정 byte 계산"] },
            { expression: String.raw`\left\lceil \frac{n_{rec}\,S_{rec}}{\beta}\right\rceil`, annotation: ["고정 byte를 block당 byte로 나눠 올림해", "같은 pool의 block 수로 환산"] },
          ]}
          terms={[
            { symbol: String.raw`n_{rec}`, name: "Recurrent layer 수", description: "예시에서는 48입니다." },
            { symbol: String.raw`S_{rec}`, name: "Layer당 state byte", description: "48 × 128 × 128 × 2 B = 1.5 MiB입니다." },
            { symbol: String.raw`\beta`, name: "Block당 byte", description: "예시에서는 attention 16 layer 기준 1 MiB입니다." },
          ]}
          assumptions={["attention block의 byte가 β이며 고정 상태를 같은 byte 단위로 합칠 수 있는 설명용 모형입니다. 실제 group별 배정 식은 아닙니다.", "Convolution history, 상태 복사본, prefix checkpoint, padding 및 tensor parallel 분할은 생략했습니다."]}
          interpretation="β=1MiB라면 100토큰의 7개와 고정 72개를 더해 79MiB입니다. 1500토큰은 94+72=166MiB입니다. 이는 가정한 상태 한 벌의 논리 용량이며 실제 engine의 물리 용량과 구별합니다."
        /><p>상태를 교환한다면 이 가정에서는 층당 1.5MiB씩 48묶음으로 표현할 수 있습니다. 실제 복사 횟수와 전송 효율은 배치 방식에 달려 있습니다. 상태를 버렸다면 토큰 이력으로 복원해야 하며 checkpoint 재사용 여부도 확인합니다. <Link to="/cs/ai/hybrid-kv-cache-allocation">Hybrid KV Cache 글</Link>에서 실제 group별 용량을 이어 봅니다.</p></section>

<section id="paper-vllm" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">19. 논문의 복구 정책은 그 실험과 함께 읽습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>PagedAttention 논문 §4.5는 가장 늦게 온 요청을 먼저 중단하고 요청의 block을 함께 내보내는 정책을 설명합니다. C의 이전 위치를 모두 읽어야 다음 토큰을 계산할 수 있으므로 C의 일부 KV만 남기는 것으로 전체 계산을 계속할 수 없다는 대응입니다.</p><p>논문은 교환한 요청들이 끝날 때까지 새 요청을 받지 않는 정책 아래에서 CPU로 내보낸 block 수가 GPU 전체 block 수를 넘지 않는다고 설명합니다. 이 상한은 원문의 정책에 붙은 결과이며 모든 교환 시스템의 보편적인 CPU 용량 법칙이 아닙니다.</p><p>§7.3의 OPT-13B·ShareGPT 실험은 작은 block의 잘게 나뉜 전송이 불리하고 block16–64에서는 두 방식의 전체 성능이 비슷했다고 보고합니다. 본문의 6.44ms나 60ms가 그 논문의 실측값인 것은 아닙니다.</p></div><div id="paper-preemption" className="mt-8 scroll-mt-20"><CitationBlock source="PagedAttention · arXiv:2309.06180v1 §4.5" citeKey={1} href="https://arxiv.org/html/2309.06180v1#S4.SS5"><q>either evict all or none of the blocks of a sequence</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>C가 단일 생성 경로이며 공유가 없는 사례에서는 block10개를 함께 해제합니다. 실제 공유 block의 다른 참조가 살아 있으면 그 공간 전체가 곧바로 free가 된다고 계산할 수 없습니다.</p></div></div><ProgressiveDetail title="논문의 800KB와 본문의 128KiB는 왜 다른가요?" preview="모델 구조가 다르며 논문의 byte 표기도 다시 계산해야 합니다."><p>
            논문 §3의 OPT-13B 식은 2×5120×40×2=819200byte입니다. 원문은 800KB라고 쓰지만 이 값은 800KiB입니다. 본문의 128KiB는 다른 head
            구조를 가정했습니다. A100 40GB에서 가중치 약 65%·동적 상태 약 30%, 기존 시스템의 KV 활용률 20.4–38.2% 역시 논문 조건의 수치이며 모든 배포의 비율이
            아닙니다.
          </p></ProgressiveDetail></section>

<section id="engine-settings" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">20. SGLang은 수용의 보수성을 따로 조절합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>SGLang의 mem-fraction-static은 가중치와 KV pool에 쓰는 정적 할당 비율입니다. schedule-conservativeness는 수용의 보수성을 조절합니다. 2026-10-04에 확인한 공식 문서는 요청이 자주 retract되면 후자를 키우도록 안내합니다. C처럼 반복해서 빠지는 요청을 줄일 수 있는지 관찰할 때의 조정입니다.</p></div><div id="paper-sglang-scheduler" className="mt-8 scroll-mt-20"><CitationBlock source="SGLang · Server Arguments · Memory and scheduling" citeKey={1} href="https://docs.sglang.io/docs/advanced_features/server_arguments"><q>A larger value means more conservative scheduling.</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>이 문장은 schedule-conservativeness의 방향을 정합니다. C의 하한을 정확히 3으로 만든다는 수치 대응이나 모든 요청의 지연 개선을 보장하지는 않습니다.</p></div></div></section>

<section id="engine-pool-sizing" data-teach-level="6" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">21. 메모리 비율의 분모가 다르면 용량도 달라집니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>TensorRT-LLM의 free_gpu_memory_fraction은 남아 있는 GPU 메모리 가운데 KV에 쓸 비율이며 문서 기본값은 0.9입니다. max_tokens도 지정하면 두 설정을 byte 용량으로 바꿔 작은 쪽을 씁니다. 전체 장비 용량의 90%라는 뜻으로 바꾸어 읽지 않습니다.</p><p>예를 들어 남은 메모리 100MiB의 90%는 90MiB이고 max_tokens가 80MiB에 해당하면 80MiB를 씁니다. 본문의 2MiB 단위로 40개가 되는 설명용 대응입니다. 실제 manager 종류와 모델별 block 배치는 별도로 확인합니다. (가정)</p></div><div id="paper-trtllm-kvcache" className="mt-8 scroll-mt-20"><CitationBlock source="TensorRT-LLM · KV Cache System · How Much Memory is Allocated" citeKey={1} href="https://nvidia.github.io/TensorRT-LLM/features/kvcache.html"><q>The default is 90% (ratio of 0.9).</q></CitationBlock><div className="prose prose-neutral max-w-none dark:prose-invert"><p>분모는 free GPU memory입니다. 같은 0.9라도 가중치를 포함한 정적 할당 비율과 다른 값을 계산할 수 있습니다.</p><p>같은 문서는 host_cache_size로 재사용 block을 CPU에 보관할 용량을 byte 단위로 정하며 기본값은 0이라고 설명합니다. C의 20MiB를 보관하려면 그만한 호스트 용량이 필요합니다. 이런 재사용 block의 보관 설정을 요청 전체의 선점 정책과 같다고 보지는 않습니다.</p></div></div></section>

<section id="boundary" data-teach-level="7" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">22. 수용에 성공해도 끝까지의 여유를 보장하지 않습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>C는 처음 9block을 받아 성공했지만 성장 뒤 중단됐고 재개에는 11개가 필요했습니다. 이 세 값을 구분하면 신규 수용, 실행 중 성장, 중단 뒤 복원을 같은 공간 장부에서 볼 수 있습니다.</p><p>공유 입력과 prefix 재사용이 있으면 요청별 논리 block 합과 실제 사용 공간이 달라집니다. 상태 해제도 다른 참조나 복사 작업이 끝날 때까지 지연될 수 있습니다. 원문 코드의 버전과 설정 없이 watermark1%나 CPU 교환 지원을 보편 규칙으로 쓰지 않습니다.</p><p>반복 중단이 보이면 요청 길이와 실제 free 변화, 재계산량을 먼저 확인합니다. 진행 요청 상한이나 입력 조각 크기 변경은 처리량과 대기 시간에도 영향을 줍니다. 공간을 늘리는 선택 역시 가중치·작업 공간과 같은 예산 안에서 검토해야 합니다.</p><p><Link to="/cs/ai/vllm-paged-attention#block-pool">PagedAttention 글</Link>은 block의 소유와 재사용을, <Link to="/cs/ai/continuous-batching-step-anatomy">연속 배정 글</Link>은 요청 자리와 토큰 예산을 설명합니다. 장비 전체 예산은 <Link to="/cs/ai/model-vram-budgeting#runtime-state">VRAM budgeting</Link>, 서버 수까지의 확장은 <Link to="/cs/ai/llm-serving-capacity#capacity-admission">serving capacity</Link>로 이어집니다.</p></div><ContentBoundary article="serving-memory-admission-and-preemption" /></section>

<section id="prediction-questions" data-teach-level="review" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">23. 조건을 바꾸면 다음 판정은 어떻게 될까요</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>C가 10block을 돌려줬고 빈 공간도 10개가 됐습니다. 토큰 이력이 161개일 때 바로 재개할 수 있을까요? (답: 9절)</p><p>
            첫 조각 256토큰에 필요한 16block은 있지만 전체 입력 1000토큰은 들어가지 않습니다. 현재 V1의 기본 검사에서 수용될까요? (답: 13절)
          </p><p>고정 V0의 교환 경로에서 CPU 공간이 부족합니다. 자동으로 재계산으로 바뀐다고 예상해도 될까요? (답: 16절)</p></div></section>
</div><CodeSidebar codeRefKey={sidebar.codeRefKey} codeRef={sidebar.codeRef} onClose={sidebar.close} onNavigate={sidebar.navigate} codeRefs={codeRefs} fileTrees={{vllm:memorySourceTree}} projectMetas={{vllm:{id:"vllm",label:"vLLM v0.27.1 / legacy v0.6.6",badgeClass:"bg-blue-500/10 border-blue-500 text-blue-700"}}} /></>;
}
