import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { SelectionBiasViz } from "../competition-workflow/viz/ModernCompetitionViz";

export default function ModelSelectionBiasArticle(){return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Observed validation score는 true performance와 finite-sample noise의 합입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">후보의 실제 평균 성능이 같아도 validation rows·seed·training noise 때문에 관측 score는 흔들립니다. 여러 후보 중 가장 높은 값만 남기면 model quality뿐 아니라 우연히 큰 양의 noise도 함께 고르게 됩니다.</p></div><TermBreakdown title="선택 편향을 만드는 네 물체" items={[{term:"True score μⱼ",description:"같은 평가 분포를 반복했을 때 후보 j의 평균 성능입니다."},{term:"Validation noise εⱼ",description:"Finite rows·seed·training 때문에 한 번의 평가가 평균에서 벗어난 값입니다."},{term:"Observed score Xⱼ",description:"μⱼ+εⱼ로 관측되는 selection criterion입니다."},{term:"Selected score",description:"Argmax로 고른 후보의 관측 score입니다.",boundary:"새 data에서 다시 얻을 score와 같다고 보장되지 않습니다."}]}/><SelectionBiasViz/><ContentBoundary article="model-selection-bias"/></section>
  <section id="maximum" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Max는 true mean과 양의 noise를 함께 선택합니다</h2><ExplainedFormula question="왜 unbiased noise인데도 최고 score를 고르면 낙관이 생기나요?" idea={<p>각 후보의 noise 평균은 0이어도 maximum은 convex function입니다. 여러 관측값의 max 기대는 각 기대값의 max보다 작지 않습니다.</p>} formula={String.raw`\mathbb E[\max_j X_j]\ge\max_j\mathbb E[X_j],\quad X_j=\mu_j+\varepsilon_j`} annotatedFormula={String.raw`\begin{aligned}X_j&=\underbrace{\mu_j+\varepsilon_j}_{\text{true score와 validation noise를 합침}}\\j^*&=\underbrace{\arg\max_j X_j}_{\text{관측 최고점을 낸 후보를 선택}}\\\mathbb E[X_{j^*}]&=\underbrace{\mathbb E[\max_jX_j]\ge\max_j\mu_j}_{\text{maximum의 convexity로 낙관 가능}}\end{aligned}`} operations={[{expression:String.raw`\mu_j+\varepsilon_j`,annotation:["true mean에 finite-validation noise를 더해","관측 score를 생성"]},{expression:String.raw`\arg\max_jX_j`,annotation:["모든 관측 score를 비교해","가장 큰 후보를 선택"]},{expression:String.raw`\mathbb E[\max_jX_j]`,annotation:["반복 validation의 선택 최고점을 평균해","true 최고 mean과 비교"]}]} terms={[{symbol:String.raw`\mu_j`,name:"True score",description:"후보 j의 population performance입니다."},{symbol:String.raw`\varepsilon_j`,name:"Validation noise",description:"평균 0일 수 있는 finite-sample 흔들림입니다."},{symbol:String.raw`j^*`,name:"Selected candidate",description:"관측 score가 최대인 후보 index입니다."}]} assumptions={["Score는 higher-is-better 방향으로 맞춥니다.","Inequality가 매 시행마다 optimism을 뜻하지는 않습니다."]} interpretation="모두 true .70인 A·B·C가 .69·.74·.71로 관측되면 B를 고르며 관측 낙관은 .04입니다."/></section>
  <section id="budget" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">후보 수·noise·adaptive search가 selection pressure를 키웁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>
            독립 후보가 많고 validation이 작거나 같은 score를 보고 다음 후보를 설계할수록 우연한 고점을 찾기 쉽습니다. 그래서 candidate family와 search
            budget을 기록하고 같은 validation 최고점만으로는 효과 크기를 확정하지 않습니다.
          </p></div></section>
  <section id="boundary" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Candidate를 동결한 뒤 선택에 쓰지 않은 data에서 확인합니다</h2><div id="paper-model-selection-bias" className="not-prose"><CitationBlock source="Cawley & Talbot — On Over-fitting in Model Selection" citeKey={1} type="paper" href="https://www.jmlr.org/papers/v11/cawley10a.html">Model-selection criterion의 variance와 subsequent evaluation bias를 분석합니다. 모든 K-fold나 모든 maximum이 항상 같은 크기로 편향된다는 뜻은 아닙니다.</CitationBlock></div></section>
</div>}
