import type { CodeRef } from "@/components/code/types";
import proxy from "./codebase/vllm/tests/v1/kv_connector/nixl_integration/toy_proxy_server.py?raw";
import pullsched from "./codebase/vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_scheduler.py?raw";
import pullworker from "./codebase/vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_worker.py?raw";
import baseworker from "./codebase/vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/base_worker.py?raw";
import connector from "./codebase/vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/connector.py?raw";
import sched from "./codebase/vllm/v1/core/sched/scheduler.py?raw";
import routing from "./codebase/sglang/sgl-model-gateway/src/policies/cache_aware.rs?raw";
import routingconfig from "./codebase/sglang/sgl-model-gateway/src/policies/mod.rs?raw";
import tree from "./codebase/sglang/sgl-model-gateway/src/policies/tree.rs?raw";
export const codeRefs: Record<string, CodeRef> = {
"proxy-prefill": {...{"path": "vllm/tests/v1/kv_connector/nixl_integration/toy_proxy_server.py", "highlight": [161, 175], "desc": "P가 전체 생성을 반복하지 않도록 복사한 요청을 한 토큰 비스트리밍으로 만듭니다.", "annotations": [{"lines": [161, 175], "color": "sky", "note": "원래 max_tokens=8이어도 P 복사본만 1입니다. D의 원래 상한은 별도 요청에 남습니다."}]},code:proxy,lang:"python"},
"proxy-forward": {...{"path": "vllm/tests/v1/kv_connector/nixl_integration/toy_proxy_server.py", "highlight": [232, 253], "desc": "P의 첫 출력을 그대로 전달하면 출력 경로가 달라집니다. 이 예제는 전달 정보를 D 요청에 붙여 D 바이트만 보냅니다.", "annotations": [{"lines": [232, 253], "color": "sky", "note": "R의 4ms P 출력은 yield되지 않습니다. StreamingResponse의 공급자는 D입니다."}]},code:proxy,lang:"python"},
"remote-count": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_scheduler.py", "highlight": [58, 64], "desc": "로컬에 이미 있는 위치를 다시 옮기지 않도록 외부에서 받을 위치 수를 계산합니다.", "annotations": [{"lines": [58, 64], "color": "sky", "note": "일반 attention의 입력 4−로컬 0은 4입니다. recurrent 상태 모델의 actual은 별도 함수 조건을 봅니다."}]},code:pullsched,lang:"python"},
"pull-read": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_worker.py", "highlight": [315, 333], "desc": "비동기 시작과 완료를 혼동하지 않도록 READ handle을 저장합니다.", "annotations": [{"lines": [315, 333], "color": "sky", "note": "목적지 공간이 준비된 R의 128B를 읽기 시작한 뒤 추후 완료 검사에 handle을 사용합니다."}]},code:pullworker,lang:"python"},
"last-token": {...{"path": "vllm/v1/core/sched/scheduler.py", "highlight": [2667, 2676], "desc": "KV만 받은 완전한 입력 hit에서 다음 출력 점수를 얻도록 마지막 입력 위치를 다시 계산합니다.", "annotations": [{"lines": [2667, 2676], "color": "sky", "note": "R은 num_computed_tokens=4와 num_tokens=4라서 3으로 조정됩니다. P 출력을 입력에 붙이는 연산이 아닙니다."}]},code:sched,lang:"python"},
"pin-source": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_scheduler.py", "highlight": [237, 257], "desc": "P 계산 후 곧바로 공간을 반환하지 않도록 블록 보관 기한을 남깁니다.", "annotations": [{"lines": [237, 257], "color": "sky", "note": "블록이 있어 delay_free_blocks=true이며 R의 4ms 계산 완료 뒤에도 원본을 유지합니다."}]},code:pullsched,lang:"python"},
"consumer-notification": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_worker.py", "highlight": [379, 399], "desc": "한 consumer만 읽고 원본을 회수하지 않도록 필요한 수신자 수를 셉니다.", "annotations": [{"lines": [379, 399], "color": "sky", "note": "단일 rank 사례는 1개 통지로 충분하지만 D TP가 P보다 크면 모든 필요한 읽기를 기다립니다."}]},code:pullworker,lang:"python"},
"lease-renewal": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/base_worker.py", "highlight": [2189, 2200], "desc": "정상 대기 중인 요청을 너무 일찍 회수하지 않도록 기존 기한을 유지하거나 늘립니다.", "annotations": [{"lines": [2189, 2200], "color": "sky", "note": "기존 기한 30초에서 현재 25초+20초는 45초입니다. 현재 5초+20초는 25초라 기존 30초를 유지합니다."}]},code:baseworker,lang:"python"},
"local-hit": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/pull_worker.py", "highlight": [262, 285], "desc": "D에 필요한 기록이 있으면 중복 READ를 생략하면서 P의 보관을 끝내도록 알립니다.", "annotations": [{"lines": [262, 285], "color": "sky", "note": "로컬 블록 목록이 비어 있으면 send_notif 뒤 반환합니다. 예상 hit만으로 이 분기에 들어간 것으로 보지 않습니다."}]},code:pullworker,lang:"python"},
"layer-hooks": {...{"path": "vllm/vllm/distributed/kv_transfer/kv_connector/v1/nixl/connector.py", "highlight": [277, 289], "desc": "NIXL의 비동기 기능을 층별 저장으로 오해하지 않도록 실제 hook을 확인합니다.", "annotations": [{"lines": [277, 289], "color": "sky", "note": "두 함수는 pass입니다. R의 2ms·4ms 층별 전송 가정은 이 함수의 실행 결과가 아닙니다."}]},code:connector,lang:"python"},
"routing-threshold": {...{"path": "sglang/sgl-model-gateway/src/policies/cache_aware.rs", "highlight": [404, 423], "desc": "작은 절대 차이나 상대 차이를 함께 거르도록 AND 판정을 씁니다.", "annotations": [{"lines": [404, 423], "color": "sky", "note": "(40,8)은 false, (41,8)은 true, (1000,967)은 상대 1.1 조건에서 false입니다."}]},code:routing,lang:"rust"},
"routing-low-hit": {...{"path": "sglang/sgl-model-gateway/src/policies/cache_aware.rs", "highlight": [444, 467], "desc": "낮은 prefix 일치율에서는 가장 작은 load를 택합니다.", "annotations": [{"lines": [444, 467], "color": "sky", "note": "머리말의 최소 tree 크기 설명과 달리 실제 분기는 workers.load()를 비교합니다."}]},code:routing,lang:"rust"},
"routing-config": {...{"path": "sglang/sgl-model-gateway/src/policies/mod.rs", "highlight": [96, 116], "desc": "버전마다 바뀌는 기본값을 실제 타입과 Default 구현에 고정합니다.", "annotations": [{"lines": [96, 116], "color": "sky", "note": "이 CacheAwareConfig는 .5·32·1.1·30초·10000입니다. 별도 BalanceAbs/Rel 설정과 섞지 않습니다."}]},code:routingconfig,lang:"rust"},
"routing-eviction": {...{"path": "sglang/sgl-model-gateway/src/policies/tree.rs", "highlight": [745, 766], "desc": "주기마다 전체 tree를 비우는 대신 크기 기준을 넘는 tenant의 leaf만 정리합니다.", "annotations": [{"lines": [745, 766], "color": "sky", "note": "tenant_char_count가 max_size 이하면 계속 넘어갑니다. 이 숫자를 실제 KV byte로 해석하지 않습니다."}]},code:tree,lang:"rust"},
};
