import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { BaselineArtifactViz } from "../competition-workflow/viz/ModernCompetitionViz";

export default function CompetitionBaselineArticle(){return <div className="space-y-16">
  <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Baseline은 작은 model이 아니라 입력부터 제출까지 이어지는 첫 완결 system입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">복잡한 model 전에 data snapshot, split, preprocessing, OOF·test prediction, metric report, submission file을 같은 명령으로 다시 만들 수 있어야 합니다. 이 chain이 이후 모든 실험의 비교 기준입니다.</p></div><TermBreakdown title="Baseline artifact chain" items={[{term:"Data snapshot",description:"Schema·row identity·source revision이 고정된 입력입니다."},{term:"Split manifest",description:"각 row·group·time의 fold membership입니다."},{term:"OOF artifact",description:"모든 train row의 unseen prediction과 fold provenance입니다."},{term:"Submission artifact",description:"Test row order·value range·file checksum까지 봉인한 결과입니다."}]}/><BaselineArtifactViz/><ContentBoundary article="competition-baseline"/></section>
  <section id="coverage" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">표준 K-fold에서는 각 train row의 OOF coverage가 정확히 1이어야 합니다</h2><ExplainedFormula question="OOF coverage 0과 2는 각각 어떤 오류인가요?" idea={<p>
            Row i가 validation으로 들어간 fold마다 indicator를 더합니다. 합이 0이면 unseen prediction이 없고 2면 중복 prediction이 있어
            metric denominator가 깨집니다.
          </p>} formula={String.raw`c_i=\sum_{k=1}^{K}\mathbf1[i\in V_k],\quad c_i=1\;\forall i`} annotatedFormula={String.raw`\begin{aligned}m_{ik}&=\underbrace{\mathbf1[i\in V_k]}_{\text{row i가 fold k에서 validation인지 표시}}\\c_i&=\underbrace{\sum_{k=1}^{K}m_{ik}}_{\text{row i의 validation 등장 횟수를 합산}}\\\mathrm{valid}&=\underbrace{\mathbf1[\forall i,\;c_i=1]}_{\text{누락·중복 없는 OOF table만 허용}}\end{aligned}`} operations={[{expression:String.raw`\mathbf1[i\in V_k]`,annotation:["row membership을 확인해","fold별 validation indicator 생성"]},{expression:String.raw`\sum_km_{ik}`,annotation:["모든 folds의 indicator를 더해","row별 coverage count 계산"]},{expression:String.raw`\mathbf1[\forall i,c_i=1]`,annotation:["모든 row count를 검사해","완전한 OOF artifact만 승인"]}]} terms={[{symbol:String.raw`V_k`,name:"Validation fold k",description:"Fold k에서 unseen prediction을 받을 rows입니다."},{symbol:String.raw`c_i`,name:"OOF coverage",description:"Row i가 validation prediction을 받은 횟수입니다."},{symbol:"K",name:"Fold count",description:"Partition을 구성하는 fold 수입니다."}]} assumptions={["Repeated CV가 아닌 standard partition형 K-fold입니다.","Group·time leakage는 coverage와 별도 검사합니다."]} interpretation="[1,1,0,2,1]이면 세 번째 row는 누락, 네 번째 row는 중복이므로 metric 계산을 중단합니다."/></section>
  <section id="artifact" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">OOF·test·metric·submission을 같은 run lineage로 묶습니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>Data/schema hash, split manifest, config·seed·code·environment, checkpoint, OOF row/fold, test row order, global/fold/slice metric, submission checksum을 한 run ID에 연결합니다.</p></div></section>
  <section id="boundary" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">재현 가능한 낮은 score가 좋은 model은 아니지만 좋은 실험의 출발점입니다</h2><div id="paper-baseline-debt" className="not-prose"><CitationBlock source="Sculley et al. — Hidden Technical Debt in Machine Learning Systems" citeKey={1} type="paper" href="https://papers.nips.cc/paper/5656-hidden-technical-debt-in-machine-learning-systems">Data·configuration·feedback·consumer dependency가 model code 밖에 만드는 system risk를 분류합니다. 특정 manifest schema가 reliability를 자동 보장한다는 뜻은 아닙니다.</CitationBlock></div></section>
</div>}
