import type { Article } from '../types';

export const tsArticles: Article[] = [
  {
    slug: 'time-series-forecasting-evaluation',
    title: '시계열 예측 검증: Rolling Backtest에서 Foundation Model까지',
    subcategory: 'ai-timeseries-forecast',
    learningPath: 'ai-timeseries-forecasting',
    learningPaths: [
      'ai-timeseries-forecast-probabilistic',
      'ai-timeseries-forecast-statistical',
      'ai-timeseries-forecast-memory',
      'ai-timeseries-forecast-point-in-time',
    ],
    summary: '예측 시점의 정보 경계를 고정하고 시간 누출을 막은 뒤, rolling origin에서 고전 기준선과 TimesFM 2.5·Chronos-2·Moirai 2.0을 공정하게 비교합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['평균과 절대 오차', 'Train·validation·test의 역할', '시계열의 lag와 seasonality'],
    sections: [
      { id: 'forecast-contract', title: '예측 계약부터 고정하기' },
      { id: 'availability-leakage', title: '정보 가용성과 시간 누출' },
      { id: 'rolling-backtest', title: 'Rolling-origin backtest' },
      { id: 'baselines', title: '기준선과 공정한 비교' },
      { id: 'metrics-calibration', title: '오차와 불확실성 보정' },
      { id: 'foundation-models', title: '현재 Foundation Model 읽기' },
      { id: 'implementation', title: '구현과 Release gate' },
    ],
    component: () => import('@/pages/articles/ai/time-series-forecasting-evaluation'),
  },
  {
    slug: 'paper-deepar-2017',
    title: 'DeepAR 원문: 여러 시계열에서 하나의 확률 예측기를 배우는 법',
    subcategory: 'ai-timeseries-forecast',
    learningPath: 'ai-timeseries-forecast-probabilistic',
    summary: '관련 시계열이 공유하는 recurrent likelihood에서 시작해 teacher-forced 학습, autoregressive sample path, count likelihood, item scale, velocity sampling과 원문 evidence의 한계를 재구성합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['조건부 확률과 likelihood', '시계열의 forecast origin', 'LSTM hidden state의 역할'],
    curriculumRole: 'source',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'global-related-series', title: '하나의 전역 모델, 여러 시계열' },
      { id: 'joint-future-samples', title: '관측에서 미래 sample path까지' },
      { id: 'likelihood-support', title: 'Target에 맞는 likelihood' },
      { id: 'power-law-scale', title: 'Power-law scale 처리' },
      { id: 'source-evidence', title: '원문 근거와 joint calibration' },
      { id: 'limits-current-handoff', title: '한계와 현재 검증으로 인계' },
    ],
    component: () => import('@/pages/articles/ai/paper-deepar-2017'),
  },
  {
    slug: 'arima',
    title: 'ARIMA: 현재 모델을 검증하는 통계 기준선',
    subcategory: 'ai-timeseries-forecast',
    learningPath: 'ai-timeseries-forecast-statistical',
    summary: '차분·AR·MA의 계산을 바닥부터 이해하고, 분산·계절성·영구 level shift를 분리한 뒤 ACF/PACF·AICc·잔차 진단과 24-step rolling-origin 기준선 비교로 출시 여부를 결정합니다.',
    level: '입문',
    estimatedMinutes: 52,
    prerequisites: ['평균과 분산', '시계열의 lag', 'Train과 validation의 역할'],
    curriculumRole: 'core',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: '왜 지금도 필요한 기준선인가' },
      { id: 'components', title: 'I → AR → MA → 복원' },
      { id: 'modeling', title: '후보 생성과 실패 진단' },
      { id: 'applications', title: 'SARIMA와 실전 선택 경계' },
    ],
    component: () => import('@/pages/articles/ai/arima'),
  },
  {
    slug: 'lstm-timeseries',
    title: 'LSTM 시계열: 게이트 기억에서 Forecasting 기준선까지',
    subcategory: 'ai-timeseries-forecast',
    learningPath: 'ai-timeseries-forecast-memory',
    summary: 'Vanilla RNN의 곱셈 기울기 경로에서 시작해 forget·input·output gate와 cell state를 한 시점씩 계산하고, 누출 없는 window·rolling backtest에서 LSTM을 현재 Transformer·TSFM 후보와 비교합니다.',
    level: '중급',
    estimatedMinutes: 55,
    prerequisites: ['행렬곱과 sigmoid·tanh', '미분의 chain rule', '시계열의 forecast origin과 window'],
    sections: [
      { id: 'overview', title: 'RNN의 한계와 LSTM의 등장' },
      { id: 'cell-architecture', title: 'LSTM 셀 구조' },
      { id: 'training', title: '시계열 학습 파이프라인' },
      { id: 'applications', title: '언제 LSTM을 선택할까?' },
    ],
    component: () => import('@/pages/articles/ai/lstm-timeseries'),
  },
  {
    slug: 'time-series-anomaly-detection',
    title: '시계열 이상 탐지: 점 하나에서 운영 가능한 사건까지',
    subcategory: 'ai-timeseries-anomaly',
    learningPath: 'ai-timeseries-anomaly',
    learningPaths: ['ai-timeseries-anomaly-ecod'],
    summary: '극단값·맥락 이상·구간 이상을 구분하고 과거 정보만 쓴 예측 잔차를 alert event로 묶은 뒤, event recall·오탐률·탐지 지연으로 운영 가능한 이상 탐지를 검증합니다.',
    level: '중급',
    estimatedMinutes: 58,
    prerequisites: ['시계열의 forecast origin', '평균·중앙값·quantile', 'Precision과 recall'],
    sections: [
      { id: 'alert-contract', title: '알람 계약부터 고정하기' },
      { id: 'anomaly-types', title: '점·맥락·구간 이상' },
      { id: 'residual-baseline', title: '예측 잔차 기준선' },
      { id: 'event-threshold', title: '점수를 사건으로 묶기' },
      { id: 'evaluation', title: '사건·오탐·지연 평가' },
      { id: 'model-ladder', title: '모델 복잡도 승격' },
      { id: 'implementation', title: 'Replay와 release gate' },
    ],
    component: () => import('@/pages/articles/ai/time-series-anomaly-detection'),
  },
  {
    slug: 'ecod',
    title: 'ECOD: ECDF 기반 이상 탐지',
    subcategory: 'ai-timeseries-anomaly',
    learningPath: 'ai-timeseries-anomaly-ecod',
    summary: '각 피처의 경험적 양쪽 꼬리확률을 -log 점수로 바꾸고 합산해, 반복 학습 없는 tabular outlier ranking 기준선을 계산하고 한계를 진단합니다.',
    level: '입문',
    estimatedMinutes: 34,
    prerequisites: ['정렬과 순위', '확률과 로그', '피처·행으로 된 표 데이터'],
    sections: [
      { id: 'overview', title: '개요' },
      { id: 'algorithm', title: 'ECDF 기반 이상치 점수 계산' },
      { id: 'implementation', title: 'PyOD 구현 & 대규모 처리' },
      { id: 'comparison', title: '다른 기법과 비교' },
    ],
    component: () => import('@/pages/articles/ai/ecod'),
  },
];
