import type { Article } from '../types';

// ── A. 데이터 감사 & 독립 intervention branches ──
const dataArticles: Article[] = [
  {
    slug: 'eda-workflow',
    title: '데이터 감사: 모델보다 먼저 예측 계약을 검증한다',
    subcategory: 'ai-practical-data',
    summary: '한 행, prediction cutoff, target 확정 시점에서 시작해 schema·단위·sentinel·duplicate·missingness·leakage와 split handoff를 감사합니다.',
    level: '기초',
    estimatedMinutes: 55,
    prerequisites: ['지도학습의 입력 X와 정답 y', 'Train·validation·test의 역할'],
    learningPath: 'ai-practical-data-audit',
    sections: [
      { id: 'overview', title: 'EDA는 데이터 감사다' },
      { id: 'contract', title: 'Prediction contract' },
      { id: 'schema', title: 'Schema·단위·중복' },
      { id: 'missingness', title: '결측 생성 과정' },
      { id: 'leakage', title: 'Leakage map·split' },
      { id: 'handoff', title: '세 intervention 분기' },
    ],
    component: () => import('@/pages/articles/ai/eda-workflow'),
  },
  {
    slug: 'feature-engineering',
    title: '피처 설계: cutoff 이전 사실을 학습 신호로 바꾼다',
    subcategory: 'ai-practical-data',
    summary: 'Fit/transform 경계를 고정하고 numeric·categorical·target encoding·시간 집계를 point-in-time correct하게 만든 뒤 OOF ablation으로 채택합니다.',
    level: '중급',
    estimatedMinutes: 60,
    prerequisites: ['데이터 감사와 prediction cutoff', '교차 검증과 OOF prediction'],
    learningPath: 'ai-practical-feature-signals',
    sections: [
      { id: 'overview', title: '피처는 시점이 있는 주장' },
      { id: 'fit-boundary', title: 'Fit·transform 경계' },
      { id: 'numeric-categorical', title: '수치·범주·target encoding' },
      { id: 'time-aggregate', title: 'Point-in-time 집계' },
      { id: 'selection', title: 'Ablation·선택 안정성' },
      { id: 'evidence', title: 'Feature release evidence' },
    ],
    component: () => import('@/pages/articles/ai/feature-engineering'),
  },
  {
    slug: 'data-augmentation',
    title: '데이터 증강: 변환이 보존해야 할 의미를 먼저 쓴다',
    subcategory: 'ai-practical-data',
    summary: '모든 transform을 invariance·equivariance claim으로 감사하고 image와 box·mask·keypoint·text target을 동기화해 clean OOF에서 검증합니다.',
    level: '중급',
    estimatedMinutes: 55,
    prerequisites: ['데이터 감사와 고정 validation', '분류·탐지·분할 target의 차이'],
    learningPath: 'ai-practical-augmentation-contract',
    sections: [
      { id: 'overview', title: '의미 보존 계약' },
      { id: 'invariance', title: 'Invariance claim' },
      { id: 'target-sync', title: 'Target 동기화' },
      { id: 'mixing', title: 'Mixup·CutMix' },
      { id: 'tabular', title: 'Tabular 합성 경계' },
      { id: 'pipeline', title: 'Train·evaluation 분리' },
    ],
    component: () => import('@/pages/articles/ai/data-augmentation'),
  },
  {
    slug: 'imbalanced-data',
    title: '희귀 사건 의사결정: 학습 신호와 운영 기준을 분리한다',
    subcategory: 'ai-practical-data',
    summary: 'Prevalence와 절대 count에서 시작해 AP·top-k, fold 내부 resampling, class weight·focal loss, calibration과 capacity threshold를 분리합니다.',
    level: '중급',
    estimatedMinutes: 60,
    prerequisites: ['데이터 감사와 group/time split', 'Precision·recall·average precision', '확률과 threshold의 차이'],
    learningPath: 'ai-practical-rare-event-decision',
    sections: [
      { id: 'overview', title: '희귀 사건 의사결정' },
      { id: 'metrics', title: 'Count·ranking·action' },
      { id: 'resampling', title: 'Fold 내부 resampling' },
      { id: 'optimization', title: 'Class weight·focal loss' },
      { id: 'calibration-threshold', title: 'Calibration·threshold' },
      { id: 'release', title: 'Model·policy release' },
    ],
    component: () => import('@/pages/articles/ai/imbalanced-data'),
  },
];

// ── B. 테이블형 모델링 ──
const tabularArticles: Article[] = [
  {
    slug: 'gradient-boosting',
    title: 'Gradient Boosting: 강한 표 기준선의 원리와 증거',
    subcategory: 'ai-practical-tabular',
    summary: '손실의 음의 기울기를 tree가 보정하는 원리와 XGBoost leaf objective를 이해하고, XGBoost·LightGBM·CatBoost를 병목별 후보로 공정하게 검증합니다.',
    level: '중급',
    estimatedMinutes: 70,
    prerequisites: ['데이터 감사와 leakage-free split', '미분과 gradient descent의 직관', '분류·회귀 metric의 역할'],
    learningPath: 'ai-practical-tabular-static',
    sections: [
      { id: 'overview', title: '강한 기준선의 계약' },
      { id: 'residual-gradient', title: 'Residual과 음의 기울기' },
      { id: 'xgboost-objective', title: 'Leaf objective와 split gain' },
      { id: 'systems', title: 'XGBoost·LightGBM·CatBoost' },
      { id: 'validation', title: 'Fold 내부 early stopping' },
      { id: 'release', title: '승격 조건과 release evidence' },
    ],
    component: () => import('@/pages/articles/ai/gradient-boosting'),
  },
  {
    slug: 'tabular-deep-learning',
    title: '테이블 Neural·Foundation Model: Feature Token에서 TabPFN-3까지',
    subcategory: 'ai-practical-tabular',
    summary: 'Feature token, FT-Transformer, TabNet과 prior-data fitted network의 차이를 이해하고, 2026년 TabPFN-3까지 강한 tree 기준선과 같은 OOF·비용 계약으로 비교합니다.',
    level: '중급',
    estimatedMinutes: 75,
    prerequisites: ['Gradient boosting 기준선과 OOF prediction', 'Embedding과 self-attention의 기초', 'Calibration·latency·memory guardrail'],
    learningPath: 'ai-practical-tabular-static',
    sections: [
      { id: 'overview', title: '복잡도 승격 질문' },
      { id: 'tokenization', title: '수치·범주 feature token' },
      { id: 'ft-transformer', title: 'Feature interaction attention' },
      { id: 'tabnet', title: 'Sequential feature mask' },
      { id: 'tabpfn', title: 'Prior-data fitted network' },
      { id: 'decision', title: 'OOF·비용 승격 gate' },
    ],
    component: () => import('@/pages/articles/ai/tabular-deep-learning'),
  },
  {
    slug: 'time-features',
    title: 'Point-in-time 시간 피처: 발생·도착·예측 시각을 분리한다',
    subcategory: 'ai-practical-tabular',
    summary: 'Event time, availability time, prediction cutoff와 label horizon을 먼저 고정하고 lag·반열린 rolling·as-of join·주기 인코딩을 과거 시점에서 재생합니다.',
    level: '중급',
    estimatedMinutes: 70,
    prerequisites: ['데이터 감사와 prediction cutoff', '평균·집합·함수의 기초', 'Train·validation 시간 순서'],
    learningPath: 'ai-practical-tabular-temporal',
    learningPaths: [
      'ai-timeseries-forecast-point-in-time',
      'ai-timeseries-anomaly',
      'ai-timeseries-anomaly-ecod',
    ],
    sections: [
      { id: 'overview', title: 'Event time과 availability time' },
      { id: 'clock-contract', title: 'Cutoff·horizon 계약' },
      { id: 'lag-window', title: 'Lag·반열린 rolling' },
      { id: 'point-in-time', title: 'As-of join과 replay' },
      { id: 'calendar', title: '주기 인코딩의 경계' },
      { id: 'validation', title: 'Forward validation과 gap' },
      { id: 'release', title: 'Sequence 승격 조건' },
    ],
    component: () => import('@/pages/articles/ai/time-features'),
  },
  {
    slug: 'sequence-modeling-tabular',
    title: 'Event Sequence Modeling: 집계가 잃은 순서를 보존한다',
    subcategory: 'ai-practical-tabular',
    summary: 'Entity·episode·target cutoff로 leakage-free sample을 만들고 flat·n-gram 기준선에서 시작해 event token, padding·causal mask와 RNN·TCN·Transformer를 증거에 따라 선택합니다.',
    level: '중급',
    estimatedMinutes: 75,
    prerequisites: ['Point-in-time lag·rolling feature', 'Embedding·attention의 직관', '시간 순 교차 검증'],
    learningPath: 'ai-practical-tabular-temporal',
    sections: [
      { id: 'overview', title: '순서를 보존할 조건' },
      { id: 'sample-contract', title: 'Episode·cutoff·target sample' },
      { id: 'baselines', title: 'Flat·n-gram baseline ladder' },
      { id: 'order-loss', title: '동일 집계의 순서 손실' },
      { id: 'encoding-mask', title: 'Event token·padding·mask' },
      { id: 'model-choice', title: 'RNN·TCN·Transformer' },
      { id: 'evidence', title: 'Temporal OOF와 release' },
    ],
    component: () => import('@/pages/articles/ai/sequence-modeling-tabular'),
  },
];

// ── C. 학습 파이프라인 ──
const pipelineArticles: Article[] = [
  {
    slug: 'training-pipeline',
    title: '재현 가능한 Training Run: Batch에서 Resume까지',
    subcategory: 'ai-practical-pipeline',
    summary: 'Sample·batch·loss에서 accumulation·AMP update boundary, full checkpoint state와 untouched test까지 하나의 재현 가능한 run 계약으로 연결합니다.',
    level: '기초',
    estimatedMinutes: 58,
    prerequisites: ['Forward·loss·backward의 기본 순서', 'Train·validation·test의 역할'],
    learningPath: 'ai-practical-training-run',
    sections: [
      { id: 'overview', title: 'Run 계약' },
      { id: 'run-contract', title: 'Sample·batch·loss' },
      { id: 'update-boundary', title: 'Accumulation·AMP' },
      { id: 'resume', title: '전체 상태 Resume' },
      { id: 'evidence', title: '작은 실패 검사' },
    ],
    component: () => import('@/pages/articles/ai/training-pipeline'),
  },
  {
    slug: 'transfer-learning-practice',
    title: 'Transfer Learning: Probe에서 필요한 만큼만 적응하기',
    subcategory: 'ai-practical-pipeline',
    summary: 'Pretrained artifact 계약을 맞춘 뒤 scratch·linear probe·partial unfreeze·full tune과 continued pretraining을 같은 evidence로 비교합니다.',
    level: '중급',
    estimatedMinutes: 54,
    prerequisites: ['재현 가능한 training run', 'Pretraining과 supervised target loss의 차이'],
    learningPath: 'ai-practical-transfer-adaptation',
    sections: [
      { id: 'overview', title: '적응 범위 질문' },
      { id: 'artifact-contract', title: 'Pretrained 계약' },
      { id: 'probe-ladder', title: 'Probe·unfreeze 사다리' },
      { id: 'freeze-state', title: 'Optimizer state 경계' },
      { id: 'domain-shift', title: 'Domain·task shift' },
    ],
    component: () => import('@/pages/articles/ai/transfer-learning-practice'),
  },
  {
    slug: 'lr-scheduling',
    title: 'Learning-rate Control: Update Clock과 Horizon',
    subcategory: 'ai-practical-pipeline',
    summary: 'Microbatch와 optimizer update를 구분하고 fixed, metric-driven, branchable horizon에 맞춰 warmup·cosine·plateau·WSD 후보를 선택합니다.',
    level: '중급',
    estimatedMinutes: 52,
    prerequisites: ['Optimizer update와 learning rate의 의미', 'Gradient accumulation'],
    learningPath: 'ai-practical-update-control',
    sections: [
      { id: 'overview', title: 'Scheduler의 책임' },
      { id: 'clock', title: 'Update clock' },
      { id: 'schedules', title: 'Horizon별 후보' },
      { id: 'call-order', title: '호출 순서' },
      { id: 'resume-release', title: 'Resume·비교 evidence' },
    ],
    component: () => import('@/pages/articles/ai/lr-scheduling'),
  },
  {
    slug: 'regularization-practice',
    title: 'Generalization Control: 실패 진단에서 개입까지',
    subcategory: 'ai-practical-pipeline',
    summary: 'Train–validation gap을 곧바로 recipe로 덮지 않고 data·optimization·slice·calibration을 진단해 dropout·AdamW·soft target·stopping을 선택합니다.',
    level: '중급',
    estimatedMinutes: 56,
    prerequisites: ['재현 가능한 training run', 'Loss와 validation model selection'],
    learningPath: 'ai-practical-generalization-control',
    sections: [
      { id: 'overview', title: '실패 기반 개입' },
      { id: 'diagnosis', title: 'Data·slice·confidence 감사' },
      { id: 'interventions', title: '개입별 책임' },
      { id: 'early-stopping', title: 'Model selection 경계' },
      { id: 'release', title: '일반화 evidence' },
    ],
    component: () => import('@/pages/articles/ai/regularization-practice'),
  },
];

// ── D. 실전 컴퓨터 비전 ──
const cvArticles: Article[] = [
  {
    slug: 'image-classification-pipeline',
    title: '이미지 분류: 누수 없는 증거에서 배포까지',
    subcategory: 'ai-practical-cv',
    learningPath: 'ai-practical-cv-classification',
    summary: '파일이 아니라 독립 entity와 배포 shift를 기준으로 split하고, shortcut 반증부터 augmentation·representation·release evidence까지 연결합니다.',
    level: '기초',
    estimatedMinutes: 65,
    prerequisites: ['Train·validation·test 분할', '분류 지표와 confusion matrix', '같은 설정을 다시 실행할 수 있는 training run 기록'],
    sections: [
      { id: 'prediction-contract', title: '예측·분할 계약' },
      { id: 'data-evidence', title: 'Label·Group·Acquisition Audit' },
      { id: 'baseline', title: '가장 싼 반증 Baseline' },
      { id: 'interventions', title: '실패 모드별 Intervention' },
      { id: 'release', title: 'Release Evidence' },
    ],
    component: () => import('@/pages/articles/ai/image-classification-pipeline'),
  },
  {
    slug: 'vision-transformer',
    title: 'Vision Transformer: 패치에서 분류까지',
    subcategory: 'ai-vision-foundations',
    summary: '이미지를 patch token으로 바꾸고 self-attention으로 전역 관계를 계산하는 과정과 해상도·token 비용의 tradeoff를 연결합니다.',
    level: '기초',
    estimatedMinutes: 62,
    prerequisites: ['이미지를 patch 격자로 나눈다는 직관', 'Self-attention의 QKV 기초'],
    learningPath: 'ai-vision-patch-backbone-foundation',
    sections: [
      { id: 'overview', title: 'Pixel에서 Token으로' },
      { id: 'patch-embedding', title: 'Patch와 위치 계약' },
      { id: 'architecture', title: 'Token Mixing과 Backbone Branch' },
      { id: 'tradeoff', title: '해상도와 N² 비용' },
      { id: 'practice', title: 'Production Manifest' },
    ],
    component: () => import('@/pages/articles/ai/vision-transformer'),
  },
  {
    slug: 'multiview-fusion',
    title: '멀티뷰 퓨전: View-set 계약에서 상호작용까지',
    subcategory: 'ai-practical-cv',
    learningPath: 'ai-practical-cv-classification',
    summary: '여러 사진을 순서 없는 집합과 고정 camera 배열로 구분하고, 누락 뷰·masked pooling·cross-view interaction을 증거 순서로 검증합니다.',
    level: '중급',
    estimatedMinutes: 60,
    prerequisites: ['이미지 분류 pipeline', 'Set pooling과 attention 기초'],
    sections: [
      { id: 'view-contract', title: 'View-set 계약' },
      { id: 'set-baseline', title: 'Masked Set Baseline' },
      { id: 'fusion-gates', title: 'Fusion 선택 Gate' },
      { id: 'missing-views', title: '누락·순서·Ablation' },
      { id: 'release', title: 'Entity-level Release' },
    ],
    component: () => import('@/pages/articles/ai/multiview-fusion'),
  },
  {
    slug: 'deepfake-detection',
    title: '딥페이크 탐지: 보지 못한 생성 과정을 시험하기',
    subcategory: 'ai-practical-cv',
    learningPath: 'ai-practical-cv-video',
    summary: 'Pristine-source lineage로 누수를 막고 generator·codec·capture 이동을 감춘 평가에서 detector, provenance와 사람 검토의 경계를 세웁니다.',
    level: '중급',
    estimatedMinutes: 75,
    prerequisites: ['비디오 sampling과 source-level split', '분류 calibration과 open-set 평가'],
    sections: [
      { id: 'threat-contract', title: '위협 모델과 범위' },
      { id: 'lineage-split', title: 'Lineage Split과 Open-domain Gap' },
      { id: 'input-evidence', title: '얼굴·Track·Sampling' },
      { id: 'evidence-families', title: 'Spatial·Frequency·Temporal Evidence' },
      { id: 'benchmark-matrix', title: 'Dataset·Domain Matrix' },
      { id: 'decision-system', title: '탐지·Provenance·검토' },
    ],
    component: () => import('@/pages/articles/ai/deepfake-detection'),
  },
  {
    slug: 'video-understanding',
    title: '비디오 이해: 시간을 썼다는 증거부터',
    subcategory: 'ai-practical-cv',
    learningPath: 'ai-practical-cv-video',
    summary: 'Target horizon과 source-video split을 먼저 고정하고, single-frame·shuffle 반증 뒤에만 temporal architecture를 올립니다.',
    level: '중급',
    estimatedMinutes: 65,
    prerequisites: ['이미지 분류 baseline', 'Temporal sampling과 sequence modeling 기초'],
    sections: [
      { id: 'temporal-contract', title: 'Target Horizon과 Split' },
      { id: 'sampling', title: 'Sampling은 첫 Temporal Model' },
      { id: 'temporal-proof', title: 'Single-frame·Shuffle 반증' },
      { id: 'model-gates', title: 'Temporal Model 선택 Gate' },
      { id: 'release', title: 'Whole-video Release' },
    ],
    component: () => import('@/pages/articles/ai/video-understanding'),
  },
];

// ── E. 도메인 특화 임베딩 ──
const embeddingArticles: Article[] = [
  {
    slug: 'image-rag-defect-retrieval',
    title: '결함 이미지 검색: Relevance에서 Evidence Release까지',
    subcategory: 'ai-practical-embedding',
    summary: '검색해야 할 관계와 생산 계보 split을 먼저 고정하고, 같은 좌표계·Exact 기준선·ANN·filter·rerank·reindex를 거쳐 재검증 가능한 현장 근거를 출시합니다.',
    level: '중급',
    estimatedMinutes: 62,
    prerequisites: ['이미지를 숫자 vector로 바꿀 수 있다는 직관', 'Precision·Recall과 train·validation 분리'],
    learningPath: 'ai-practical-image-retrieval',
    sections: [
      { id: 'overview', title: '검색 행동과 Relevance 계약' },
      { id: 'embedding', title: '같은 좌표계 Manifest' },
      { id: 'retrieval', title: 'Exact·ANN·Filter·Rerank' },
      { id: 'operations', title: 'Metric·Slice·Reindex' },
      { id: 'release', title: '검색 Evidence Release' },
    ],
    component: () => import('@/pages/articles/ai/image-rag-defect-retrieval'),
  },
  {
    slug: 'contrastive-learning',
    title: 'Contrastive Learning: Pair에서 검색 Geometry까지',
    subcategory: 'ai-practical-embedding',
    summary: 'Positive·negative의 업무 의미를 먼저 고정하고 augmentation, false negative, mining, InfoNCE·triplet·SupCon이 실제 검색 순위를 어떻게 바꾸는지 검증합니다.',
    level: '중급',
    estimatedMinutes: 60,
    prerequisites: ['Embedding과 cosine similarity', 'Loss가 model parameter를 바꾼다는 직관'],
    learningPath: 'ai-practical-image-retrieval',
    sections: [
      { id: 'overview', title: 'Pair가 가까움의 뜻을 정한다' },
      { id: 'simclr', title: 'Augmentation·InfoNCE' },
      { id: 'triplet', title: 'Triplet·Mining' },
      { id: 'supervised', title: 'Multi-positive·SupCon' },
      { id: 'application', title: 'Pair Manifest·Reindex' },
    ],
    component: () => import('@/pages/articles/ai/contrastive-learning'),
  },
  {
    slug: 'domain-finetuning',
    title: 'Domain Adaptation: Shift 진단에서 Reindex까지',
    subcategory: 'ai-practical-embedding',
    summary: '획득 환경·전문 어휘·relevance 정의 중 무엇이 바뀌었는지 분리하고, continued pretraining과 supervised metric learning을 최소 개입으로 적용한 뒤 anchor regression과 index migration을 닫습니다.',
    level: '중급',
    estimatedMinutes: 62,
    prerequisites: ['사전학습과 fine-tuning의 차이', 'Contrastive pair와 검색 metric의 역할'],
    learningPath: 'ai-practical-image-retrieval',
    sections: [
      { id: 'overview', title: 'Shift를 먼저 분해한다' },
      { id: 'continued-pretrain', title: 'Continued Pretraining의 경계' },
      { id: 'task-finetune', title: 'Supervised Metric Adaptation' },
      { id: 'genomic', title: '도메인별 불변성과 실패' },
      { id: 'release', title: 'Anchor Regression·Reindex' },
    ],
    component: () => import('@/pages/articles/ai/domain-finetuning'),
  },
  {
    slug: 'sentence-embeddings',
    title: 'Text Embedding Retrieval: Query에서 Reindex까지',
    subcategory: 'ai-practical-embedding',
    summary: '질문과 문서의 relevance를 고정한 뒤 masked pooling, bi-encoder, role instruction, reranker와 최신 embedding 계보를 같은 corpus·latency·index 계약에서 비교합니다.',
    level: '중급',
    estimatedMinutes: 65,
    prerequisites: ['Token embedding과 attention mask', 'Cosine similarity와 검색의 Precision·Recall'],
    learningPath: 'ai-practical-text-embedding',
    sections: [
      { id: 'overview', title: 'Query·Document Relevance 계약' },
      { id: 'pooling', title: 'Mask-aware Pooling' },
      { id: 'sbert', title: 'Bi-encoder·Cross-encoder' },
      { id: 'modern', title: 'E5·BGE-M3·Qwen3 계보' },
      { id: 'evaluation', title: 'MTEB에서 Production Reindex까지' },
    ],
    component: () => import('@/pages/articles/ai/sentence-embeddings'),
  },
];

// ── F. 모델 경량화 ──
const compressionArticles: Article[] = [
  {
    slug: 'compression-pipeline',
    title: '모델 경량화: 배포 계약에서 출시 증거까지',
    subcategory: 'ai-practical-compression',
    learningPath: 'ai-practical-compression-budget',
    summary: '가중치·KV·연산·런타임·품질 병목을 분리하고 양자화·프루닝·증류 중 필요한 가지로 내려간 뒤 동일 workload에서 release를 검증합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['추론의 prefill·decode 기본 흐름', 'GPU memory와 latency·throughput의 기본 의미'],
    sections: [
      { id: 'deployment-contract', title: '배포 계약을 먼저 고정한다' },
      { id: 'memory-envelope', title: 'Weight·KV·runtime memory' },
      { id: 'baseline-profile', title: '고정밀 baseline과 병목 분해' },
      { id: 'controlled-branches', title: '기법별 독립 분기와 조합 실험' },
      { id: 'release-evidence', title: 'Pareto와 production release' },
    ],
    component: () => import('@/pages/articles/ai/compression-pipeline'),
  },
  {
    slug: 'quantization',
    title: '양자화: 숫자 눈금에서 실행 Kernel까지',
    subcategory: 'ai-practical-compression',
    learningPath: 'ai-practical-compression-quantization',
    summary: 'Affine quantization의 오차부터 weight-only·W8A8·KV·NF4, GPTQ·AWQ·SmoothQuant와 GGUF·runtime·kernel의 다른 층을 연결합니다.',
    level: '중급',
    estimatedMinutes: 58,
    prerequisites: ['모델 경량화 release loop', '행렬 곱과 실수·정수 표현의 기본 직관'],
    sections: [
      { id: 'number-line', title: '연속값을 제한된 눈금으로' },
      { id: 'range-granularity', title: 'Range·granularity·outlier' },
      { id: 'scheme-contract', title: 'Weight·activation·KV·training storage' },
      { id: 'ptq-methods', title: 'RTN·GPTQ·AWQ·SmoothQuant' },
      { id: 'runtime-stack', title: '알고리즘·포맷·runtime·kernel' },
      { id: 'qat-release', title: 'QAT와 최종 artifact 검증' },
    ],
    component: () => import('@/pages/articles/ai/quantization'),
  },
  {
    slug: 'pruning',
    title: '프루닝: 0을 실제 건너뛰는 실행 경로',
    subcategory: 'ai-practical-compression',
    learningPath: 'ai-practical-compression-pruning',
    summary: '논리 sparsity와 실제 속도를 분리하고 unstructured·2:4·structural pattern, 중요도 점수, SparseGPT·Wanda와 recovery를 runtime까지 연결합니다.',
    level: '중급',
    estimatedMinutes: 54,
    prerequisites: ['모델 경량화 release loop', 'Tensor shape와 dense matrix multiplication의 기본 직관'],
    sections: [
      { id: 'zero-vs-skip', title: '0과 skipped computation의 차이' },
      { id: 'pattern-runtime', title: 'Sparsity pattern과 runtime' },
      { id: 'importance-evidence', title: '중요도 점수의 증거' },
      { id: 'llm-one-shot', title: 'SparseGPT와 Wanda의 범위' },
      { id: 'recovery-order', title: 'Recovery와 조합 순서 실험' },
      { id: 'release-check', title: 'Mask·shape·kernel release' },
    ],
    component: () => import('@/pages/articles/ai/pruning'),
  },
  {
    slug: 'knowledge-distillation',
    title: '지식 증류: Teacher Signal에서 Student Release까지',
    subcategory: 'ai-practical-compression',
    learningPath: 'ai-practical-compression-distillation',
    summary: 'Teacher 접근과 tokenizer 계약에서 출발해 logit·feature·sequence·data distillation, 최소 논문 뼈대와 독립 production 평가를 잇습니다.',
    level: '중급',
    estimatedMinutes: 56,
    prerequisites: ['모델 경량화 release loop', 'Softmax·cross entropy·KL divergence의 기본 직관'],
    sections: [
      { id: 'teacher-contract', title: 'Teacher 접근과 신호 계약' },
      { id: 'soft-target', title: 'Soft target과 temperature' },
      { id: 'feature-contract', title: 'Feature·layer·shape 정렬' },
      { id: 'sequence-data', title: 'Sequence·data distillation lineage' },
      { id: 'paper-spine', title: '최소 논문 뼈대와 오해 교정' },
      { id: 'student-release', title: 'Student production release' },
    ],
    component: () => import('@/pages/articles/ai/knowledge-distillation'),
  },
];

// ── G. LLM 응용 ──
const llmAppArticles: Article[] = [
  {
    slug: 'rag-pipeline',
    title: 'RAG Pipeline: 검색에서 검증 가능한 Context Package까지',
    subcategory: 'ai-knowledge-systems',
    learningPath: 'ai-knowledge-system-core',
    summary: 'Dependency-aware routing, contextual chunking, hybrid retrieval, rerank와 evidence coverage 기반 packing을 runtime trace로 연결합니다.',
    level: '중급',
    estimatedMinutes: 58,
    prerequisites: ['Knowledge IR의 Block·Claim·Scope·Evidence', '문서 구조 복원: section·table·formula 경계', '벡터 내적과 검색 순위의 기본 직관'],
    sections: [
      { id: 'dependency-routing', title: 'Full-context와 decomposition routing' },
      { id: 'retrieval-units', title: 'Context를 잃지 않는 검색 단위' },
      { id: 'search-signals', title: 'Sparse·Dense·Late Interaction' },
      { id: 'fusion-rerank', title: 'Fusion·Rerank·Query decomposition' },
      { id: 'context-packing', title: 'Evidence coverage와 token budget' },
      { id: 'runtime-trace', title: 'Claim runtime trace' },
      { id: 'evaluation-release', title: '층별 평가와 release gate' },
    ],
    component: () => import('@/pages/articles/ai/rag-pipeline'),
  },
  {
    slug: 'lora-finetuning',
    title: 'LoRA & QLoRA: 행동 계약에서 Adapter Release까지',
    subcategory: 'ai-practical-llm',
    learningPath: 'ai-practical-llm-adaptation',
    summary: 'Fine-tuning 필요성 진단에서 저랭크 update, QLoRA 정밀도 장부, SFT loss mask, ablation과 adapter/merge release까지 잇습니다.',
    level: '중급',
    estimatedMinutes: 62,
    prerequisites: ['Transformer linear projection과 행렬 곱의 shape', '양자화에서 저장 dtype과 연산 dtype의 차이'],
    sections: [
      { id: 'behavior-contract', title: '행동 계약과 Intervention' },
      { id: 'low-rank-update', title: '저랭크 Update Geometry' },
      { id: 'qlora-precision', title: 'QLoRA 정밀도·메모리 장부' },
      { id: 'sft-contract', title: 'Template·Loss Mask·Split' },
      { id: 'training-diagnosis', title: '학습·Ablation·진단' },
      { id: 'release', title: 'Adapter·Merge Release' },
    ],
    component: () => import('@/pages/articles/ai/lora-finetuning'),
  },
];

// ── H. 대회 전략 & 실험 관리 ──
const strategyArticles: Article[] = [
  {
    slug: 'competition-workflow',
    title: '실전 ML 워크플로우: 점수보다 먼저 증거를 설계하기',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: 'Prediction cutoff와 업무 행동에서 시작해 metric, split, OOF, 실험 기록, 탐색과 최종 release를 하나의 검증 가능한 evidence loop로 연결합니다.',
    level: '기초',
    estimatedMinutes: 42,
    prerequisites: ['Train·validation·test의 기본 구분', '분류 score와 threshold의 기초 직관'],
    sections: [
      { id: 'overview', title: '대회는 증거 설계다' },
      { id: 'contract', title: '업무·Metric·Split 계약' },
      { id: 'first-day', title: '첫날의 네 가지 산출물' },
      { id: 'baseline', title: '첫 측정 장치 만들기' },
      { id: 'iteration', title: '한 번에 한 Claim만 검증' },
      { id: 'final', title: 'Evidence Freeze와 인계' },
    ],
    component: () => import('@/pages/articles/ai/competition-workflow'),
  },
  {
    slug: 'evaluation-metrics',
    title: '평가 지표: 업무 행동을 수치 계약으로 바꾸기',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: '회귀·분류·랭킹 metric을 오류 비용과 처리 용량으로 선택하고 calibration, threshold와 uncertainty를 metric bundle로 고정합니다.',
    level: '기초',
    estimatedMinutes: 50,
    prerequisites: ['평균·절댓값·제곱의 직관', '분류 확률과 threshold의 기본 개념'],
    sections: [
      { id: 'overview', title: 'Metric은 행동 계약이다' },
      { id: 'regression', title: '회귀: 큰 오류의 비용' },
      { id: 'classification', title: '분류: 오류 종류와 희귀 사건' },
      { id: 'ranking', title: '랭킹: 앞쪽 순서의 가치' },
      { id: 'calibration', title: '확률의 의미와 Calibration' },
      { id: 'metric-bundle', title: 'Primary·Guardrail·Policy 묶기' },
    ],
    component: () => import('@/pages/articles/ai/evaluation-metrics'),
  },
  {
    slug: 'cross-validation',
    title: '교차 검증: 미래 Test를 흉내 내는 Split 계약',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: 'IID·group·time·group+time 생성 구조를 구분하고 fold-local fit boundary, OOF evidence와 leaderboard audit까지 설계합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['평가 지표의 primary·guardrail 구분', 'Preprocessing의 fit과 transform 차이'],
    sections: [
      { id: 'overview', title: '검증은 작은 시간 여행이다' },
      { id: 'split-selection', title: '새로움의 축으로 Split 선택' },
      { id: 'fit-boundary', title: 'Fold 안의 Fit Boundary' },
      { id: 'nested', title: '선택과 평가의 경계' },
      { id: 'evidence', title: 'OOF·Fold·Slice Evidence' },
      { id: 'leaderboard', title: 'Leaderboard를 Audit로 쓰기' },
    ],
    component: () => import('@/pages/articles/ai/cross-validation'),
  },
  {
    slug: 'hyperparameter-tuning',
    title: '하이퍼파라미터 탐색: Validation Noise를 학습하지 않기',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: 'Mechanism 기반 search space, sampler와 pruning의 한계, 반복 noise와 compute를 포함한 stop gate 및 multi-objective 선택을 다룹니다.',
    level: '중급',
    estimatedMinutes: 44,
    prerequisites: ['고정 Split manifest와 OOF evidence', '하이퍼파라미터와 학습 파라미터의 차이'],
    sections: [
      { id: 'overview', title: 'Bounded Search의 목적' },
      { id: 'search-space', title: 'Mechanism 기반 탐색 공간' },
      { id: 'sampler', title: 'Random에서 Adaptive Search로' },
      { id: 'pruning', title: 'Pruning Bias 관리' },
      { id: 'stop-gate', title: 'Noise·Compute Stop Gate' },
      { id: 'multi-objective', title: 'Tradeoff를 보존하는 선택' },
    ],
    component: () => import('@/pages/articles/ai/hyperparameter-tuning'),
  },
  {
    slug: 'ensemble-methods',
    title: '앙상블: OOF 오류 다양성에서 Release까지',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: 'Aligned OOF prediction으로 오류 상관을 측정하고 probability/rank average와 leakage 없는 stacking을 release gate까지 연결합니다.',
    level: '중급',
    estimatedMinutes: 43,
    prerequisites: ['OOF prediction 생성 과정', '확률 calibration과 ranking metric의 차이'],
    sections: [
      { id: 'overview', title: '오류 다양성이 필요한 이유' },
      { id: 'averaging', title: 'Probability와 Rank Average' },
      { id: 'diversity', title: 'OOF 오류 상관 측정' },
      { id: 'stacking', title: 'Leakage 없는 Stacking' },
      { id: 'release', title: '복잡도를 포함한 Release Gate' },
    ],
    component: () => import('@/pages/articles/ai/ensemble-methods'),
  },
  {
    slug: 'experiment-tracking',
    title: '실험 관리: Score를 재현 가능한 Claim으로 바꾸기',
    subcategory: 'ai-practical-strategy',
    learningPath: 'ai-practical-competition',
    summary: 'Dataset digest, split manifest, code, environment, seed policy, OOF와 model artifact를 불변 run identity와 lineage로 연결합니다.',
    level: '중급',
    estimatedMinutes: 38,
    prerequisites: ['Dataset·Split version의 필요성', 'OOF prediction과 artifact의 기본 개념'],
    sections: [
      { id: 'overview', title: 'Tracking은 Claim의 계보다' },
      { id: 'run-identity', title: '불변 Run Identity' },
      { id: 'data-lineage', title: 'Dataset·Split Lineage' },
      { id: 'artifacts', title: '실패를 재생하는 Artifact' },
      { id: 'tool-implementation', title: 'W&B·MLflow 구현 경계' },
      { id: 'release', title: 'Evidence 기반 승격' },
    ],
    component: () => import('@/pages/articles/ai/experiment-tracking'),
  },
];

export const practicalArticles: Article[] = [
  ...dataArticles,
  ...tabularArticles,
  ...pipelineArticles,
  ...cvArticles,
  ...embeddingArticles,
  ...compressionArticles,
  ...llmAppArticles,
  ...strategyArticles,
];
