import type { Article } from "../types";
import { dlNlpArticles } from "./articlesDL2";
import { dlFoundation2Articles, dlVisionArticles } from "./articlesDL3";

// ── Foundations (읽기 순서: 공통 수학 → 퍼셉트론 → 신경망 → 활성화 → 역전파 → 옵티마이저 → 목적함수) ──
export const dlFoundationArticles: Article[] = [
  {
    slug: "deep-learning-overview",
    title: "딥러닝의 출발점: 표현을 층으로 쌓는 이유",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Representation은 무엇인가" },
      { id: "shape", title: "중간 표현의 형태" },
      { id: "depth", title: "깊이가 만드는 함수 합성" },
      { id: "boundaries", title: "표현·학습·일반화의 경계" },
    ],
    component: () => import("@/pages/articles/ai/deep-learning-overview"),
  },
  {
    slug: "supervised-learning-loop",
    title: "지도학습 한 바퀴: example에서 parameter update까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Input과 target" },
      { id: "tensor-batch", title: "Tensor와 batch" },
      { id: "training-step", title: "Forward에서 update까지" },
      { id: "inference", title: "학습과 inference의 경계" },
    ],
    component: () => import("@/pages/articles/ai/supervised-learning-loop"),
  },
  {
    slug: "train-validation-test",
    title: "Train·validation·test: 데이터 역할을 섞지 않는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "세 split의 역할" },
      { id: "selection-feedback", title: "Validation feedback" },
      { id: "generalization", title: "Generalization과 gap" },
      { id: "next-protocol", title: "Cross-validation으로 넘기는 경계" },
    ],
    component: () => import("@/pages/articles/ai/train-validation-test"),
  },
  {
    slug: "math-vectors-inner-products",
    title: "벡터·내적·norm: AI 수식을 읽는 최소 선형대수",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "좌표를 하나의 대상으로 묶기" },
      { id: "vectors", title: "Scalar와 vector" },
      { id: "norm", title: "Norm과 거리" },
      { id: "dot-product", title: "Dot product와 방향" },
      { id: "projection", title: "Projection으로 성분 읽기" },
      { id: "cauchy-schwarz", title: "Cauchy–Schwarz 부등식" },
      { id: "applications", title: "퍼셉트론·attention으로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-vectors-inner-products"),
  },
  {
    slug: "math-matrices-svd",
    title: "행렬·선형변환·SVD: embedding 압축을 읽는 최소 선형대수",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "행렬을 숫자 표 이상으로 읽기" },
      { id: "matrix-map", title: "행렬과 linear map" },
      { id: "multiplication", title: "행렬 곱과 함수 합성" },
      { id: "rank-basis", title: "Rank와 orthonormal basis" },
      { id: "svd", title: "SVD의 세 단계" },
      { id: "low-rank", title: "Low-rank approximation" },
      { id: "applications", title: "Embedding·PCA로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-matrices-svd"),
  },
  {
    slug: "math-complex-numbers-oscillations",
    title: "복소수·회전·Euler 공식: Fourier 수식을 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "복소수가 회전을 기록하는 이유" },
      { id: "radians", title: "Radian과 한 바퀴" },
      { id: "unit-circle", title: "Sine·cosine과 단위원" },
      { id: "complex-plane", title: "복소수와 복소평면" },
      { id: "euler-formula", title: "Euler 공식과 회전 곱셈" },
      { id: "roots-of-unity", title: "Roots of unity" },
      { id: "applications", title: "DFT·FFT로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-complex-numbers-oscillations"),
  },
  {
    slug: "text-unicode-encoding",
    title: "문자·Unicode·UTF-8: tokenizer를 읽는 최소 텍스트 기초",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "화면의 한 글자와 저장 단위 구분" },
      { id: "bits-bytes", title: "Bit와 byte" },
      { id: "code-points", title: "Code point와 grapheme cluster" },
      { id: "utf-8", title: "UTF-8 encoding" },
      { id: "normalization", title: "Unicode normalization" },
      { id: "offsets", title: "Offset 좌표와 round-trip" },
      { id: "applications", title: "Tokenizer로 연결" },
    ],
    component: () => import("@/pages/articles/ai/text-unicode-encoding"),
  },
  {
    slug: "math-functions-derivatives-gradients",
    title: "함수·미분·gradient: AI 수식을 읽는 최소 미적분",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "변화의 환율로 미분 읽기" },
      { id: "functions", title: "함수와 합성" },
      { id: "limits", title: "극한과 가까워짐" },
      { id: "derivatives", title: "Derivative와 local linearity" },
      { id: "chain-rule", title: "Chain rule" },
      { id: "partial-gradient", title: "편미분과 gradient" },
      { id: "nonsmooth", title: "Subgradient와 ReLU" },
      { id: "applications", title: "Activation·backprop으로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-functions-derivatives-gradients"),
  },
  {
    slug: "math-differential-equations-numerical-solvers",
    title: "미분방정식·수치적분: diffusion의 ODE·SDE를 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "변화 법칙에서 경로 만들기" },
      { id: "initial-value", title: "초기값 문제와 vector field" },
      { id: "euler-method", title: "Euler method와 오차" },
      { id: "stability", title: "Step size와 수치 안정성" },
      { id: "heun-runge-kutta", title: "Heun·Runge–Kutta" },
      { id: "ode-sde-boundary", title: "ODE와 SDE의 경계" },
      { id: "applications", title: "Diffusion·Neural ODE로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-differential-equations-numerical-solvers"),
  },
  {
    slug: "math-exponents-logarithms",
    title: "지수·로그: 확률과 정보량을 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "곱셈을 덧셈으로 옮기기" },
      { id: "exponents", title: "지수와 반복 배율" },
      { id: "logarithms", title: "로그는 지수의 역질문" },
      { id: "log-identities", title: "곱·나눗셈의 log 규칙" },
      { id: "log-bases", title: "밑과 단위" },
      { id: "applications", title: "정보량과 loss로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-exponents-logarithms"),
  },
  {
    slug: "math-probability-expectation-variance",
    title: "확률변수·기댓값·분산: mini-batch를 읽는 최소 확률",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "불확실성의 규칙" },
      { id: "outcomes", title: "Outcome과 distribution" },
      { id: "conditional-probability", title: "조건부확률과 연쇄법칙" },
      { id: "random-variable", title: "Random variable" },
      { id: "expectation", title: "Expectation" },
      { id: "variance", title: "Variance" },
      { id: "sample-mean", title: "Sample mean과 1/B" },
      { id: "gradient-noise", title: "Mini-batch gradient" },
      { id: "applications", title: "Optimizer로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-probability-expectation-variance"),
  },
  {
    slug: "math-optimization-convexity",
    title: "최적화·convexity·수렴: optimizer를 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Optimization 문제 계약" },
      { id: "objective", title: "Objective와 minimizer" },
      { id: "convexity", title: "Convexity" },
      { id: "gradient-descent", title: "Gradient descent" },
      { id: "smoothness", title: "Smoothness와 curvature" },
      { id: "convergence", title: "Convergence guarantee" },
      { id: "nonconvex", title: "Nonconvex 경계" },
      { id: "applications", title: "Optimizer로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-optimization-convexity"),
  },
  {
    slug: "perceptron",
    title: "퍼셉트론: 신경망의 기원",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "선형 결정 경계에서 시작하기" },
      { id: "convergence", title: "수렴 정리의 전제와 margin" },
      { id: "logic-gates", title: "논리 회로 구현" },
      { id: "limitation", title: "퍼셉트론의 한계" },
      { id: "multilayer", title: "다층 퍼셉트론" },
    ],
    component: () => import("@/pages/articles/ai/perceptron"),
  },
  {
    slug: "neural-network",
    title: "신경망: 퍼셉트론에서 다층 네트워크로",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "함수 합성과 learned representation" },
      { id: "activation", title: "Affine collapse와 비선형성" },
      { id: "forward", title: "Tensor shape와 signal scale" },
      { id: "output-layer", title: "Target의 확률 계약" },
      { id: "mnist", title: "MNIST 실험과 일반화 진단" },
    ],
    component: () => import("@/pages/articles/ai/neural-network"),
  },
  {
    slug: "activation-functions",
    title: "활성화 함수 기초: Step · Sigmoid · Tanh",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "값과 local slope" },
      { id: "step-function", title: "계단 함수와 gradient" },
      { id: "sigmoid", title: "Sigmoid와 saturation" },
      { id: "tanh", title: "Tanh와 signed state" },
      { id: "comparison", title: "출력 의미와 경계" },
    ],
    component: () => import("@/pages/articles/ai/activation-functions"),
  },
  {
    slug: "rectifier-activations",
    title: "Rectifier 활성화: ReLU · Dying ReLU · SELU",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "0에서 꺾이는 선" },
      { id: "relu", title: "ReLU hinge" },
      { id: "dying-relu", title: "Dying state" },
      { id: "negative-slope", title: "Leaky ReLU · PReLU" },
      { id: "self-normalization", title: "SELU 조건" },
      { id: "comparison", title: "측정과 선택" },
    ],
    component: () => import("@/pages/articles/ai/rectifier-activations"),
  },
  {
    slug: "gated-activations",
    title: "Smooth·Gated 활성화: GELU · SiLU · SwiGLU",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "값과 통과 비율" },
      { id: "gelu-silu", title: "GELU · SiLU" },
      { id: "gated-ffn", title: "SwiGLU 구조" },
      { id: "parameter-budget", title: "공정한 parameter 예산" },
      { id: "comparison", title: "구조·kernel 비교" },
    ],
    component: () => import("@/pages/articles/ai/gated-activations"),
  },
  {
    slug: "reverse-mode-autodiff",
    title: "Reverse-mode autodiff: Graph · Tape · VJP",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Computational graph" },
      { id: "tape", title: "Saved tape" },
      { id: "reverse-mode", title: "VJP와 branch sum" },
      { id: "save-recompute", title: "Save·recompute 경계" },
    ],
    component: () => import("@/pages/articles/ai/reverse-mode-autodiff"),
  },
  {
    slug: "softmax",
    title: "Softmax: Logit에서 공동 확률까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Logit과 공동 분모" },
      { id: "temperature", title: "Temperature" },
      { id: "output-boundary", title: "Categorical 경계" },
    ],
    component: () => import("@/pages/articles/ai/softmax"),
  },
  {
    slug: "backprop-optimization",
    title: "신경망 Backprop: Loss에서 Tensor Gradient까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "왜 역전파인가" },
      { id: "loss-function", title: "Scalar loss 만들기" },
      { id: "tensor-backward", title: "출력에서 weight까지" },
    ],
    component: () => import("@/pages/articles/ai/backprop-optimization"),
  },
  {
    slug: "optimizers",
    title: "옵티마이저: SGD에서 AdamW까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Gradient를 parameter update로 바꾸기" },
      { id: "sgd", title: "SGD (확률적 경사 하강법)" },
      { id: "batch-variants", title: "Batch / Stochastic / Mini-batch" },
      { id: "momentum", title: "Momentum (관성)" },
      { id: "adam", title: "Adam (적응적 학습률)" },
      { id: "adamw", title: "AdamW (Decoupled Weight Decay)" },
    ],
    component: () => import("@/pages/articles/ai/optimizers"),
  },
  {
    slug: "cross-entropy",
    title: "크로스 엔트로피: 정보 이론에서 손실 함수로",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Surprisal에서 loss까지" },
      { id: "expectation", title: "기대값과 empirical risk" },
      { id: "entropy", title: "Entropy: 피할 수 없는 불확실성" },
      { id: "cross-entropy", title: "Cross-entropy와 likelihood" },
      { id: "kl-divergence", title: "KL: 모델의 추가 비용" },
      { id: "ce-vs-mse", title: "Likelihood로 loss 고르기" },
      { id: "softmax-ce-gradient", title: "Softmax–CE fused gradient" },
    ],
    component: () => import("@/pages/articles/ai/cross-entropy"),
  },
  {
    slug: "fft",
    title: "FFT (Fast Fourier Transform) — AI 관점",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "DFT와 FFT의 역할 분리" },
      { id: "fourier", title: "Sampling·window·spectrum" },
      { id: "algorithm", title: "Cooley–Tukey의 계산 재사용" },
      { id: "ai-usage", title: "AI 적용과 실제 선택 기준" },
    ],
    component: () => import("@/pages/articles/ai/fft"),
  },
  {
    slug: "word2vec",
    title: "Word2Vec: 단어 임베딩의 원리",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Corpus window와 학습 pair" },
      { id: "models", title: "CBOW·Skip-gram과 softmax 병목" },
      { id: "training", title: "SGNS·negative sampling·shifted PMI" },
      { id: "applications", title: "Vector geometry와 표현의 경계" },
    ],
    component: () => import("@/pages/articles/ai/word2vec"),
  },
];

/** Combined DL articles: foundations + foundation2 + NLP + vision */
export const dlArticles: Article[] = [
  ...dlFoundationArticles,
  ...dlFoundation2Articles,
  ...dlNlpArticles,
  ...dlVisionArticles,
];
