import type { Article } from '../types';

export const fromScratchArticles: Article[] = [
  {
    slug: 'dezero-autodiff',
    title: '자동 미분 엔진 구현 (Rust)',
    subcategory: 'ai-from-scratch',
    learningPath: 'ai-from-scratch-rust',
    summary: '실행한 계산 그래프를 기록하고 공유 DAG의 기울기를 누적하며, 이차 미분과 Rust 수명 계약까지 테스트로 닫습니다.',
    level: '중급',
    estimatedMinutes: 32,
    prerequisites: ['미분과 chain rule', 'Rust Rc·RefCell의 기초'],
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: 'Variable & 계산 그래프' },
      { id: 'forward', title: '순전파 구현' },
      { id: 'backward', title: '역전파 & 그래디언트 누적' },
      { id: 'higher-order', title: '고차 미분 (double backprop)' },
      { id: 'memory', title: 'Rc/RefCell 메모리 관리' },
    ],
    component: () => import('@/pages/articles/ai/dezero-autodiff'),
  },
  {
    slug: 'dezero-nn',
    title: '신경망 레이어 구현 (Rust)',
    subcategory: 'ai-from-scratch',
    learningPath: 'ai-from-scratch-rust',
    summary: 'Parameter identity, Linear shape와 zero_grad→backward→SGD step을 실제 2→3→2→1 모델로 검증합니다.',
    level: '중급',
    estimatedMinutes: 30,
    prerequisites: ['자동 미분 엔진 구현', '행렬 곱과 평균제곱오차'],
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: 'Layer 트레이트 설계' },
      { id: 'linear', title: 'Linear (전결합) 레이어' },
      { id: 'activation', title: '활성화 함수 (ReLU, Sigmoid, Tanh)' },
      { id: 'optimizer', title: '옵티마이저 (SGD, Adam)' },
      { id: 'training', title: '학습 루프 & 손실 함수' },
    ],
    component: () => import('@/pages/articles/ai/dezero-nn'),
  },
  {
    slug: 'dezero-advanced',
    title: 'LSTM · 정규화 · Embedding 구현 (Rust)',
    subcategory: 'ai-from-scratch',
    learningPath: 'ai-from-scratch-rust',
    summary: '시간 state의 reset·detach, LSTM gradient 경로, LayerNorm 축, Dropout 기댓값과 반복 token 누적을 구현합니다.',
    level: '중급',
    estimatedMinutes: 34,
    prerequisites: ['자동 미분 엔진 구현', '신경망 Layer 구현', '기댓값의 기초'],
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: '시퀀스 모델 개요' },
      { id: 'rnn-vs-lstm', title: 'RNN → LSTM 비교' },
      { id: 'lstm', title: 'LSTM 셀 구현' },
      { id: 'normalization', title: 'LayerNorm 구현' },
      { id: 'dropout-embedding', title: 'Dropout & Embedding' },
    ],
    component: () => import('@/pages/articles/ai/dezero-advanced'),
  },
];
