import type { Article } from "../types";
import { vllmServingArticles } from "./articlesVLLM";

const llmBaseArticles: Article[] = [
  // ── LLM Theory: 학습, 정렬, 해석가능성 ──
  {
    slug: "llm-training-stages",
    title: "LLM 학습 단계: Pretraining에서 Agentic Training까지",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Capability와 behavior의 층위" },
      { id: "pretraining", title: "Pretraining·continued training" },
      { id: "post-training", title: "SFT·RLVR·OPD와 용어 경계" },
      { id: "agentic-training", title: "Trajectory·environment·verifier" },
      { id: "limits", title: "Soft limit·hard limit의 증거 경계" },
    ],
    component: () => import("@/pages/articles/ai/llm-training-stages"),
  },
  {
    slug: "supervised-fine-tuning",
    title: "SFT: demonstration을 response-token 학습으로 바꾸기",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Pretraining과 preference 사이" },
      { id: "data-contract", title: "Demonstration과 provenance" },
      { id: "response-loss", title: "Response-only loss mask" },
      { id: "teacher-forcing", title: "Teacher forcing과 prefix gap" },
      { id: "packing", title: "Packing과 sample boundary" },
      { id: "evaluation", title: "Loss와 행동 평가 분리" },
    ],
    component: () => import("@/pages/articles/ai/supervised-fine-tuning"),
  },
  {
    slug: "rlhf",
    title: "RLHF: feedback에서 reward model·PPO까지",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "핵심 아이디어와 최소 용어" },
      { id: "reward-model", title: "두 답의 비교를 점수로 바꾸기" },
      { id: "ppo", title: "새 응답을 만들며 학습하는 PPO-RLHF" },
    ],
    component: () => import("@/pages/articles/ai/rlhf"),
  },
  {
    slug: "dpo",
    title: "DPO: chosen·rejected pair를 direct policy loss로",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Pair에서 direct update까지" },
      { id: "pair-contract", title: "Prompt·chosen·rejected·reference" },
      { id: "dpo", title: "Log-ratio margin과 DPO loss" },
      { id: "evaluation", title: "Support·shortcut·배포 평가" },
    ],
    component: () => import("@/pages/articles/ai/dpo"),
  },
  {
    slug: "constitutional-ai",
    title: "Constitutional AI: 원칙→critique→revision→RLAIF",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "판단 기준의 provenance" },
      { id: "constitution", title: "원칙의 형태와 충돌" },
      { id: "constitutional-ai", title: "Critique·revision·AI feedback" },
      { id: "evaluation", title: "Judge와 human oversight" },
    ],
    component: () => import("@/pages/articles/ai/constitutional-ai"),
  },
  {
    slug: "orpo",
    title: "ORPO: chosen SFT와 odds separation을 한 stage에",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Imitation과 separation" },
      { id: "pair-contract", title: "Reference-free와 pair-free 구분" },
      { id: "orpo", title: "Odds-ratio preference objective" },
      { id: "evaluation", title: "절감량과 품질 회귀" },
    ],
    component: () => import("@/pages/articles/ai/orpo"),
  },
  {
    slug: "kto",
    title: "KTO: 짝 없는 binary feedback으로 preference 학습",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Binary label에서 utility까지" },
      { id: "binary-feedback", title: "Exposure·label·class balance" },
      { id: "kto", title: "KL reference point와 KTO loss" },
      { id: "evaluation", title: "Logging bias와 독립 평가" },
    ],
    component: () => import("@/pages/articles/ai/kto"),
  },
  {
    slug: "yarn-rope-extension",
    title: "RoPE에서 YaRN까지: 긴 문맥 확장의 원리와 검증",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "길이를 늘리는 것과 잘 쓰는 것" },
      { id: "rope-foundation", title: "RoPE의 회전과 주파수" },
      { id: "long-context-scope", title: "Long-context modeling의 위치·메모리·평가 3분할" },
      { id: "extension-attempts", title: "PI와 NTK-aware scaling" },
      { id: "yarn-method", title: "YaRN의 두 구성 요소" },
      {
        id: "implementation",
        title: "설정과 검증: vLLM · Transformers · llama.cpp",
      },
    ],
    component: () => import("@/pages/articles/ai/yarn-rope-extension"),
  },
  {
    slug: "grammar-constrained-generation",
    title: "Formal language: symbol에서 derivation까지",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "alphabet", title: "Symbol과 alphabet" },
      { id: "string-language", title: "String과 language membership" },
      { id: "derivation", title: "Terminal·nonterminal·production" },
      { id: "next", title: "중첩 memory로 이동" },
    ],
    component: () =>
      import("@/pages/articles/ai/grammar-constrained-generation"),
  },
  {
    slug: "cfg-pushdown-automata",
    title: "CFG와 PDA: recursive nesting을 stack으로 기억하기",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "finite-memory", title: "Finite-state memory 한계" },
      { id: "cfg-recursion", title: "Context-free recursion" },
      { id: "pda-stack", title: "Pushdown stack" },
      { id: "implementation-boundary", title: "이론과 parser 구현 경계" },
    ],
    component: () => import("@/pages/articles/ai/cfg-pushdown-automata"),
  },
  {
    slug: "incremental-parsing-tree-sitter",
    title: "Tree-sitter: source edit와 incremental syntax tree",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "source-tree", title: "Source와 concrete syntax tree" },
      { id: "incremental-update", title: "Edit와 subtree reuse" },
      { id: "error-recovery", title: "불완전 source의 error recovery" },
      { id: "decoder-boundary", title: "Decoder matcher와의 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/incremental-parsing-tree-sitter"),
  },
  {
    slug: "grammar-tokenizer-decoding",
    title: "Grammar decoding: tokenizer compilation과 token mask",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "token-boundary", title: "Grammar symbol과 model token" },
      {
        id: "tokenizer-compilation",
        title: "Vocabulary transition compilation",
      },
      { id: "token-mask", title: "Logit mask와 softmax" },
      { id: "matcher-boundary", title: "State accept·EOS·dead end" },
    ],
    component: () => import("@/pages/articles/ai/grammar-tokenizer-decoding"),
  },
  {
    slug: "structured-generation-serving",
    title: "Structured generation serving: cache·state·semantic gate",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "request-schema", title: "Request별 schema" },
      { id: "dynamic-schema-cache", title: "Compile cache identity" },
      { id: "sequence-state", title: "Sequence별 matcher state" },
      { id: "semantic-policy", title: "Syntax 뒤 semantic policy" },
    ],
    component: () =>
      import("@/pages/articles/ai/structured-generation-serving"),
  },
  {
    slug: "mixture-of-experts",
    title: "Mixture-of-Experts: router·Top-k·load·system cost를 함께 읽기",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Dense FFN에서 conditional expert로" },
      { id: "routing", title: "Router · Top-k · weighted mixture" },
      { id: "load-balancing", title: "Load balancing · capacity · overflow" },
      { id: "system-cost", title: "Total·active parameter와 통신 비용" },
      { id: "evolution", title: "Shared·fine-grained·latent expert" },
    ],
    component: () => import("@/pages/articles/ai/mixture-of-experts"),
  },
  {
    slug: "motif-3-architecture",
    title: "Motif 3 구조: GDLA·mHC·PolyNorm과 MOPD",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "314B MoE의 구성 장부" },
      { id: "gdla", title: "MLA와 GDA가 만나는 GDLA" },
      { id: "mhc", title: "Modified mHC residual mixing" },
      { id: "polynorm", title: "Expert-Specific PolyNorm" },
      { id: "post-training", title: "7개 teacher와 MOPD" },
      { id: "evidence", title: "Ablation·benchmark 근거 경계" },
    ],
    component: () => import("@/pages/articles/ai/motif-3-architecture"),
  },
  {
    slug: "kimi-k3-architecture",
    title: "Kimi K3 전체 구조: sequence·depth·width를 나눠 읽기",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "세 축을 먼저 분리하기" },
      { id: "axes", title: "세 독립 수업으로 이동" },
      { id: "configuration", title: "93층 구성 장부" },
      { id: "evidence", title: "근거 강도 구분" },
    ],
    component: () => import("@/pages/articles/ai/kimi-k3-architecture"),
  },
  {
    slug: "kimi-k3-sequence-mixer",
    title: "Kimi K3 sequence mixer: KDA state에서 Gated MLA까지",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "KDA state와 delta update" },
      { id: "decay", title: "Decay의 수치 경계" },
      { id: "hybrid", title: "KDA와 MLA 조합" },
      { id: "position", title: "NoPE와 순서 신호" },
    ],
    component: () => import("@/pages/articles/ai/kimi-k3-sequence-mixer"),
  },
  {
    slug: "kimi-k3-depth-routing",
    title: "Kimi K3 depth routing: Residual에서 Block AttnRes까지",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Residual 통로" },
      { id: "depth-attention", title: "Depth source 선택" },
      { id: "block-bound", title: "Block state bound" },
      { id: "evidence", title: "표현력·비용 경계" },
    ],
    component: () => import("@/pages/articles/ai/kimi-k3-depth-routing"),
  },
  {
    slug: "kimi-k3-latent-moe",
    title: "Kimi K3 Stable LatentMoE: width·activation·load",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "Routed width 분해" },
      { id: "activation", title: "SiTU-GLU soft cap" },
      { id: "balancing", title: "Quantile Balancing" },
      { id: "release", title: "세 안정화 경계 조합" },
    ],
    component: () => import("@/pages/articles/ai/kimi-k3-latent-moe"),
  },
  {
    slug: "sparse-autoencoder",
    title: "Sparse autoencoder: activation을 feature dictionary로 읽기",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "overview", title: "SAE의 관측·해석 계약" },
      {
        id: "residual-stream",
        title: "Measurement target과 hook point",
      },
      { id: "polysemanticity", title: "Superposition 가설" },
      { id: "sae-architecture", title: "Dictionary objective와 평가" },
      { id: "feature-steering", title: "해석과 causal test" },
      { id: "limitations", title: "Claim의 한계" },
    ],
    component: () => import("@/pages/articles/ai/sparse-autoencoder"),
  },

  // ── LLM Applied: 추론 모델 학습 ──
  {
    slug: "open-r1",
    title: "Open-R1: reasoning data·SFT·GRPO를 재현하는 법",
    subcategory: "ai-llm-applied",
    sections: [
      { id: "overview", title: "세 가지 재현 경로" },
      { id: "sft-process", title: "SFT token supervision" },
      { id: "grpo-process", title: "GRPO의 on-policy loop" },
      { id: "reward-system", title: "Verifier와 reward 경계" },
      { id: "data-pipeline", title: "Synthetic data lineage" },
      { id: "evaluation", title: "Sampling · uncertainty · cost" },
    ],
    component: () => import("@/pages/articles/ai/open-r1"),
  },

  // ── LLM Serving: 추론 최적화, 서빙 인프라 ──
  {
    slug: "sionic-glm-b300",
    title: "GLM-5.2를 B300에서 600 tok/s로: kernel·runtime·MTP 최적화",
    subcategory: "ai-llm-serving",
    sections: [
      { id: "overview", title: "FLOPS보다 bytes와 forward 횟수" },
      { id: "roofline", title: "가중치 traffic으로 하한 계산하기" },
      { id: "kernel", title: "Split-K·TMEM·PQ-GEMM" },
      { id: "runtime", title: "작은 kernel과 CPU 동기화 제거" },
      { id: "mtp", title: "MTP: 한 forward에서 여러 token 확정" },
      { id: "measurement", title: "실측 ledger와 수치 정확도" },
      { id: "production", title: "benchmark를 production으로 옮길 때" },
    ],
    component: () => import("@/pages/articles/ai/sionic-glm-b300"),
  },
  {
    slug: "llm-serving-ops",
    title: "LLM 서빙 운영: Gateway · GPU Fleet · 관측과 자동화",
    subcategory: "ai-llm-serving",
    sections: [
      { id: "overview", title: "Workload·SLO에서 운영 제어면으로" },
      { id: "litellm-gateway", title: "Capability · deadline · retry" },
      {
        id: "k8s-gpu-fleet",
        title: "Requested Pod에서 Ready GPU capacity까지",
        subsections: [
          { id: "paper-little-law", title: "Little's law 원 논문의 전제" },
        ],
      },
      { id: "serving-deployment", title: "Probe · canary · drain · HPA" },
      { id: "observability-aiops", title: "SLI · error budget · closed-loop" },
    ],
    component: () => import("@/pages/articles/ai/llm-serving-ops"),
  },
];

export const llmArticles: Article[] = [
  ...llmBaseArticles,
  ...vllmServingArticles,
  {
    slug: "llm-sampling-strategies",
    title: "Sampling 전략은 temperature 로 분포를 바꾸고 top-k·top-p 로 자릅니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "결정적 tie-break 과 확률 재정규화 축의 선택" },
      { id: "temperature", title: "Temperature 로 분포의 뾰족함을 조절" },
      { id: "top-k", title: "Top-k truncation 의 고정 개수 자르기", subsections: [{ id: "paper-top-k-sampling", title: "Fan 외 top-k sampling 논문의 문제와 기여" }] },
      { id: "top-p", title: "Top-p(nucleus) truncation 의 가변 개수 자르기", subsections: [{ id: "paper-nucleus-sampling", title: "Holtzman 외 nucleus sampling 논문의 문제와 기여" }] },
      { id: "test-time-compute", title: "Test-time compute: 추론 연산으로 품질 사기", subsections: [{ id: "paper-test-time-compute-scaling", title: "Snell 외 test-time compute scaling 논문의 문제와 기여" }] },
    ],
    component: () => import("@/pages/articles/ai/llm-sampling-strategies"),
  },
  {
    slug: "multi-head-latent-attention-mechanics",
    title: "MLA 는 latent 로 압축한 KV 를 흡수한 weight 로 곧장 소비합니다",
    subcategory: "ai-llm-theory",
    sections: [
      {
        id: "problem",
        title: "MLA 는 decode 에서 key·value 를 복원하지 않고 압축된 latent 를 그대로 쓴다",
        subsections: [{ id: "paper-deepseek-v2", title: "DeepSeek-V2 논문의 MLA 제안" }],
      },
      { id: "kv-projection", title: "Down/up-projection 과 low-rank KV bottleneck" },
      { id: "decoupled-rope", title: "RoPE 를 압축 경로 밖으로 빼는 decoupled RoPE" },
      { id: "content-position", title: "Content 와 위치로 갈라지는 attention score" },
      {
        id: "weight-absorption",
        title: "결합법칙으로 up-projection 을 옮겨 접는 weight absorption",
        subsections: [
          { id: "paper-deepseek-v3", title: "DeepSeek-V3 의 MLA 채택 확인" },
          { id: "paper-vllm-mla", title: "vLLM MLA 구현의 naive·absorbed 경로" },
        ],
      },
      { id: "boundary", title: "메모리 절감과 계산 증가의 교환, 그리고 한계" },
    ],
    component: () => import("@/pages/articles/ai/multi-head-latent-attention-mechanics"),
  },
  {
    slug: "fast-weight-memory-and-chunkwise-recurrence",
    title: "Fast weight memory 는 delta rule 로 쓰고 chunkwise scan 으로 병렬화합니다",
    subcategory: "ai-llm-theory",
    sections: [
      {
        id: "problem",
        title: "겹쳐 쓴 outer-product 기억은 지우거나 고칠 수 없다",
        subsections: [{ id: "paper-schlag", title: "Fast weight programmer 논문의 제안" }],
      },
      { id: "associative-memory", title: "k⊗v 외적의 합이 만드는 content-addressable 기억" },
      { id: "delta-rule", title: "예측 오차만 다시 쓰는 delta rule" },
      {
        id: "memory-gate",
        title: "Delta rule 이 못 하는 한꺼번에 지우기를 맡는 gate",
        subsections: [{ id: "paper-gated-deltanet", title: "Gated Delta Networks 논문의 제안" }],
      },
      {
        id: "chunkwise-scan",
        title: "Chunk 안 병렬 행렬곱과 chunk 사이 순차 전달",
        subsections: [{ id: "paper-deltanet-parallel", title: "DeltaNet chunkwise 병렬화 논문의 제안" }],
      },
      { id: "prefix-scan", title: "O(log n) 단계로 순차 누적을 없애는 parallel scan" },
      {
        id: "boundary",
        title: "병렬화의 계산 비용과 delta rule 의 한계",
        subsections: [{ id: "paper-blelloch", title: "Blelloch prefix scan 기술보고서" }],
      },
    ],
    component: () => import("@/pages/articles/ai/fast-weight-memory-and-chunkwise-recurrence"),
  },
  {
    slug: "linear-attention-and-state-space-models",
    title: "Linear attention과 SSM은 고정 크기 state로 attention의 KV 성장을 없앱니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "Sequence mixer: attention·linear attention·SSM의 공통 자리" },
      {
        id: "kernel-trick",
        title: "Kernel feature map과 φ(K)ᵀV 재결합",
        subsections: [{ id: "paper-linear-attention", title: "Transformers are RNNs 논문의 문제와 기여" }],
      },
      { id: "recurrent-state", title: "고정 크기 recurrent state와 linear-time 계산" },
      {
        id: "ssm",
        title: "State space model과 Mamba의 selective mechanism",
        subsections: [
          { id: "paper-s4", title: "S4 논문의 문제와 기여" },
          { id: "paper-mamba", title: "Mamba 논문의 문제와 기여" },
          { id: "paper-mamba2-ssd", title: "Mamba-2/SSD 논문의 문제와 기여" },
        ],
      },
      { id: "tradeoff", title: "Retrieval–compression tradeoff와 고정 state의 용량" },
      {
        id: "hybrid",
        title: "Hybrid sequence architecture와 attention layer 비율",
        subsections: [{ id: "paper-jamba", title: "Jamba 논문의 문제와 기여" }],
      },
    ],
    component: () => import("@/pages/articles/ai/linear-attention-and-state-space-models"),
  },
  {
    slug: "differential-attention",
    title: "Differential attention: 두 attention map 의 차로 noise 를 지웁니다",
    subcategory: "ai-llm-theory",
    sections: [
      {
        id: "problem",
        title: "표준 attention 이 무관한 context 에 점수를 흘리는 문제",
        subsections: [{ id: "paper-differential-transformer", title: "Differential Transformer 논문의 문제와 기여" }],
      },
      { id: "paired-maps", title: "독립적인 두 attention map: signal 과 noise" },
      { id: "mechanism", title: "λ 로 스케일한 차 A1−λA2 와 head 산수" },
      { id: "properties", title: "Attention selectivity·robustness 수치" },
      { id: "boundary", title: "MLA 와의 병목 차이·연산 비용·다음 읽기" },
    ],
    component: () => import("@/pages/articles/ai/differential-attention"),
  },
  {
    slug: "hyper-connections-residual-streams",
    title: "Hyper-connection: 여러 residual stream 이 signal 을 나눠 옮깁니다",
    subcategory: "ai-llm-theory",
    sections: [
      {
        id: "problem",
        title: "단일 residual stream 이 신호 전달의 유일한 통로인 문제",
        subsections: [
          { id: "paper-hyper-connections", title: "Hyper-Connections 논문의 문제와 기여" },
          { id: "paper-pre-ln", title: "Pre-LN 논문의 gradient 증명" },
        ],
      },
      { id: "streams", title: "n개로 복제한 hyper hidden matrix 와 확장률" },
      { id: "mixing", title: "한 layer 의 read·write·mix 세 행렬" },
      {
        id: "stability",
        title: "Doubly-stochastic 제약과 mHC 의 Sinkhorn 투영",
        subsections: [{ id: "paper-mhc", title: "mHC 논문의 문제와 기여" }],
      },
      {
        id: "boundary",
        title: "신호 전파 배경과 비용·다음 읽기",
        subsections: [{ id: "paper-resnet-identity", title: "ResNet identity mapping 논문" }],
      },
    ],
    component: () => import("@/pages/articles/ai/hyper-connections-residual-streams"),
  },
  {
    slug: "sparse-windowed-attention-patterns",
    title: "Attention 은 어디를 볼지 window·sparse·hybrid 로 정해 비용을 줄입니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "Mask 가 어느 (query, key) 쌍을 아예 계산하지 않을지 정한다" },
      {
        id: "window",
        title: "Sliding-window attention 과 rolling buffer cache",
        subsections: [{ id: "paper-mistral", title: "Mistral 7B 논문의 SWA 와 rolling buffer" }],
      },
      {
        id: "sparse-global",
        title: "Global token 과 sparse attention(Longformer·BigBird)",
        subsections: [
          { id: "paper-longformer", title: "Longformer 논문의 local+global 조합" },
          { id: "paper-bigbird", title: "BigBird 논문의 표현력 증명" },
        ],
      },
      {
        id: "hybrid",
        title: "Layer 단위로 나누는 hybrid attention(Gemma)",
        subsections: [
          { id: "paper-gemma2", title: "Gemma 2 논문의 1:1 local/global" },
          { id: "paper-gemma3", title: "Gemma 3 논문의 5:1 비율과 KV 절감" },
        ],
      },
      {
        id: "boundary",
        title: "고정 패턴과 Native Sparse Attention 의 학습된 선택",
        subsections: [{ id: "paper-nsa", title: "Native Sparse Attention 논문의 학습된 block 선택" }],
      },
    ],
    component: () => import("@/pages/articles/ai/sparse-windowed-attention-patterns"),
  },
  {
    slug: "moe-routing-and-load-balancing",
    title: "Load balancing loss는 router의 하드 배정을 미분 가능한 확률과 곱해 쏠림을 벌점으로 바꿉니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "Top-k router가 스스로 무너지는 되먹임" },
      { id: "loss", title: "Load balancing loss: f_i·P_i 벌점" },
      { id: "bias", title: "Auxiliary-loss-free balancing: bias 갱신" },
      { id: "collapse", title: "Expert collapse와 token dropping" },
      { id: "sparsity", title: "Sparsity ratio: active/total 비율" },
      {
        id: "evidence",
        title: "근거: GShard·Switch·ST-MoE·Mixtral·DeepSeek-V3",
        subsections: [
          { id: "paper-gshard", title: "GShard" },
          { id: "paper-switch", title: "Switch Transformers" },
          { id: "paper-st-moe", title: "ST-MoE" },
          { id: "paper-mixtral", title: "Mixtral of Experts" },
          { id: "paper-deepseek-v3", title: "DeepSeek-V3" },
        ],
      },
    ],
    component: () => import("@/pages/articles/ai/moe-routing-and-load-balancing"),
  },
  {
    slug: "synthetic-data-and-data-flywheel",
    title: "합성 데이터와 data flywheel: self-instruct·verifier filtering·trajectory mining",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "왜 데이터를 모델 스스로 만들어야 하는가" },
      { id: "generation-sources", title: "Teacher-generated, self-generated, Self-Instruct, Evol-Instruct" },
      { id: "verifier-filtering", title: "Best-of-N 생성과 verifier/model filtering, quality thresholding" },
      { id: "difficulty-curriculum", title: "Difficulty estimation, difficulty filtering, curriculum sampling" },
      { id: "trajectory-mining", title: "Failure mining, hard-example mining, success/failure trajectory mining" },
      { id: "flywheel-loop", title: "Data flywheel, feedback data, data feedback loop" },
      {
        id: "sources",
        title: "근거 문서",
        subsections: [
          { id: "paper-self-instruct", title: "Self-Instruct" },
          { id: "paper-evol-instruct", title: "WizardLM/Evol-Instruct" },
          { id: "paper-rft", title: "RFT" },
          { id: "paper-codex-passk", title: "Codex pass@k" },
          { id: "paper-nvidia-flywheel", title: "NVIDIA Data Flywheel" },
          { id: "paper-arena-learning", title: "Arena Learning" },
        ],
      },
    ],
    component: () => import("@/pages/articles/ai/synthetic-data-and-data-flywheel"),
  },
  {
    slug: "llm-monitoring-observability-and-drift",
    title: "LLM 운영 관측: trace·token/latency 분해·drift monitoring",
    subcategory: "ai-llm-applied",
    sections: [
      { id: "problem", title: "관측 대상 축과 drift 축을 분리하기" },
      { id: "monitoring-layers", title: "Production·model·system·input·output monitoring" },
      { id: "drift-taxonomy", title: "Data drift·concept drift·performance drift" },
      { id: "trace-tree", title: "Distributed tracing·trace span·LLM trace tree" },
      { id: "token-latency-breakdown", title: "Token usage·throughput·latency breakdown" },
      { id: "gpu-queue-monitoring", title: "GPU utilization/memory·queue depth/time" },
      { id: "error-sampling-debugging", title: "Trace sampling·error classification·production debugging" },
    ],
    component: () => import("@/pages/articles/ai/llm-monitoring-observability-and-drift"),
  },
  {
    slug: "llm-application-caching",
    title: "LLM 애플리케이션 캐시: exact-match·semantic·retrieval·staleness",
    subcategory: "ai-llm-applied",
    sections: [
      { id: "problem", title: "무엇을 캐싱하느냐로 다섯 갈래로 나뉘는 application cache" },
      { id: "cache-taxonomy", title: "Exact-match·semantic·retrieval·embedding·tool result cache" },
      { id: "semantic-threshold", title: "Semantic cache similarity threshold" },
      { id: "cache-key-ttl-staleness", title: "Cache key·invalidation·TTL·staleness" },
      { id: "hit-miss-rate", title: "Cache hit·miss·hit rate" },
      { id: "warming-eviction", title: "Cache warming·LRU eviction" },
    ],
    component: () => import("@/pages/articles/ai/llm-application-caching"),
  },
  {
    slug: "llm-gateway-and-model-routing",
    title: "LLM gateway: unified API·routing 정책·cascade·fallback",
    subcategory: "ai-llm-applied",
    sections: [
      { id: "problem", title: "Gateway는 API를, router는 model을 정리한다" },
      { id: "gateway-unified-api", title: "LLM gateway·model endpoint·unified model API" },
      { id: "routing-policy-taxonomy", title: "Load/latency/cost/capability/policy-based routing" },
      { id: "model-cascade", title: "Model cascade·confidence-based escalation" },
      { id: "fallback-model", title: "Fallback model·provider fallback" },
    ],
    component: () => import("@/pages/articles/ai/llm-gateway-and-model-routing"),
  },
  {
    slug: "rate-limiting-and-reliability-patterns",
    title: "Rate limiting·backpressure·circuit breaker·failover",
    subcategory: "ai-llm-applied",
    sections: [
      { id: "problem", title: "실패 종류마다 다른 방어 장치를 겹쳐 쓴다" },
      { id: "retry-backoff", title: "Request retry·exponential backoff·jitter" },
      { id: "circuit-breaker-health-check", title: "Circuit breaker(closed/open/half-open)·health check" },
      { id: "rate-limiting-algorithms", title: "Request/token/concurrency limit·token bucket·leaky bucket" },
      { id: "load-shedding-and-admission", title: "Load shedding·admission policy" },
      { id: "graceful-degradation-and-failover", title: "HA·fault tolerance·failover·graceful degradation·reliability" },
    ],
    component: () => import("@/pages/articles/ai/rate-limiting-and-reliability-patterns"),
  },
  {
    slug: "llm-dataset-engineering-and-cleaning",
    title: "데이터셋 엔지니어링은 필터링·dedup·mixture로 학습 데이터 품질을 만듭니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "LLM 데이터셋은 왜 원본 그대로 쓰지 못하는가" },
      { id: "pipeline", title: "Dataset engineering, data generation pipeline, data source, data curation" },
      { id: "quality", title: "Data quality, filtering, cleaning, normalization, canonicalization" },
      { id: "dedup-contamination", title: "Deduplication(exact/near-duplicate/semantic)과 contamination detection" },
      { id: "annotation", title: "Human/model annotation, weak supervision, pseudo-labeling" },
      { id: "mixture", title: "Data mixture, curriculum, diversity, coverage, balance" },
      {
        id: "sources",
        title: "근거 논문",
        subsections: [
          { id: "paper-the-pile", title: "The Pile" },
          { id: "paper-refinedweb", title: "RefinedWeb" },
          { id: "paper-dolma", title: "Dolma" },
          { id: "paper-broder-minhash", title: "Broder · MinHash" },
          { id: "paper-contamination-survey", title: "Contamination Detection Survey" },
          { id: "paper-doremi", title: "DoReMi" },
          { id: "paper-lima", title: "LIMA" },
          { id: "paper-curriculum-learning", title: "Curriculum Learning" },
          { id: "paper-snorkel", title: "Snorkel" },
          { id: "paper-pseudo-label", title: "Pseudo-Label" },
          { id: "paper-chatgpt-annotator", title: "ChatGPT vs Crowd-Workers" },
        ],
      },
    ],
    component: () => import("@/pages/articles/ai/llm-dataset-engineering-and-cleaning"),
  },
  {
    slug: "rl-foundations-for-llm-post-training",
    title: "Policy Gradient는 Return의 Credit을 Action 확률 변화로 바꿉니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "Return·on/off-policy·policy gradient·credit assignment 네 부품" },
      { id: "return", title: "Return: 감가율 적용 누적 reward" },
      { id: "on-vs-off-policy", title: "On-policy와 off-policy의 표본 효율 차이" },
      {
        id: "policy-gradient",
        title: "Policy gradient theorem과 REINFORCE",
        subsections: [{ id: "paper-policy-gradient", title: "Sutton et al. 1999 논문의 문제와 기여" }],
      },
      {
        id: "credit-assignment",
        title: "Credit assignment와 long-horizon 한계",
        subsections: [{ id: "paper-rl-textbook", title: "Sutton & Barto 교과서의 정식화" }],
      },
    ],
    component: () => import("@/pages/articles/ai/rl-foundations-for-llm-post-training"),
  },
  {
    slug: "reward-design-for-verifiable-rl",
    title: "Reward는 검증 가능성과 밀도로 설계되며 잘못 설계하면 hacking을 부릅니다",
    subcategory: "ai-llm-theory",
    sections: [
      { id: "problem", title: "검증 가능성·밀도·hacking 세 축" },
      { id: "rlvr", title: "RLVR: 자동 검증 결과를 그대로 reward로" },
      { id: "sparse-vs-dense", title: "Sparse reward와 dense reward의 신호 빈도" },
      {
        id: "outcome-vs-process",
        title: "Outcome reward와 process reward의 채점 대상",
        subsections: [{ id: "paper-prm", title: "Let's Verify Step by Step의 문제와 기여" }],
      },
      {
        id: "hacking",
        title: "Reward hacking과 specification gaming",
        subsections: [
          { id: "paper-reward-hacking", title: "Defining and Characterizing Reward Hacking" },
          { id: "paper-concrete-problems", title: "Concrete Problems in AI Safety" },
        ],
      },
      {
        id: "shaping",
        title: "Potential-based reward shaping과 optimal policy 보존",
        subsections: [{ id: "paper-reward-shaping", title: "Ng, Harada, Russell 1999 논문의 증명" }],
      },
      { id: "reward-shape-and-calibration", title: "Binary/continuous reward의 형태와 calibration" },
    ],
    component: () => import("@/pages/articles/ai/reward-design-for-verifiable-rl"),
  },
];
