import type { Article } from '../types';

const foundationalPaperSections = [
  { id: 'context', title: '논문 이전의 병목과 저자 의도' },
  { id: 'claim', title: '주장과 architecture 재구성' },
  { id: 'mechanism', title: '핵심 수식과 구현 의미' },
  { id: 'evidence', title: '표·그림·ablation의 증거' },
  { id: 'reproduction', title: '최소 재현과 실패 진단' },
  { id: 'legacy', title: '남은 기여와 다음 논문' },
];

export const reinforcementLearningArticles: Article[] = [
  {
    slug: 'rl-decision-system-contracts',
    title: '강화학습 적용 계약: 알고리즘보다 먼저 고정할 것',
    subcategory: 'ai-rl-orientation',
    sections: [
      { id: 'fit', title: '이 문제가 정말 RL인가' },
      { id: 'environment-contract', title: '환경과 feedback 계약' },
      { id: 'data-access', title: 'Data access가 정하는 분기' },
      { id: 'route', title: '목표별 최소 경로' },
      { id: 'release', title: '평가와 release gate' },
    ],
    summary: '행동이 미래 data를 바꾸는지부터 확인하고 observation·state·action·feedback·termination·constraint와 online/simulator/offline 접근을 고정해 필요한 RL 경로만 선택합니다.',
    level: '입문',
    estimatedMinutes: 72,
    prerequisites: ['확률과 평균의 직관', '학습과 평가 data를 나누는 이유'],
    learningPath: 'ai-rl-orientation-current-first',
    component: () => import('@/pages/articles/ai/rl-decision-system-contracts'),
  },
  {
    slug: 'rl-mdp-bellman',
    title: '순차 의사결정 실행 계약: MDP·Return·Bellman',
    subcategory: 'ai-rl-foundations',
    sections: [
      { id: 'interaction', title: 'Agent·policy·environment 경계' },
      { id: 'mdp', title: 'Markov state 충분성 검사' },
      { id: 'return', title: 'Reward에서 return 재귀로' },
      { id: 'value', title: 'V·Q·advantage 조건' },
      { id: 'bellman', title: 'Expectation과 optimality backup' },
    ],
    summary: '같은 관측이 Markov state인지 반례로 검사하고, return·V/Q/advantage·Bellman expectation과 max를 하나의 숫자 MDP에서 직접 계산합니다.',
    level: '기초',
    estimatedMinutes: 92,
    prerequisites: ['조건부 확률과 기대값', '함수와 합 기호'],
    learningPath: 'ai-reinforcement-learning',
    component: () => import('@/pages/articles/ai/rl-mdp-bellman'),
  },
  {
    slug: 'rl-temporal-difference-dqn',
    title: 'Value Target 실행 계약: MC·TD·Q-learning·DQN',
    subcategory: 'ai-rl-foundations',
    sections: [
      { id: 'prediction-targets', title: 'MC·n-step·λ-return' },
      { id: 'control', title: 'SARSA·Q-learning과 경계 mask' },
      { id: 'exploration', title: 'Behavior·target·coverage' },
      { id: 'dqn', title: 'DQN·Double DQN backup' },
      { id: 'diagnostics', title: 'Loss와 실제 성능 진단' },
    ],
    summary: 'MC·n-step·λ-return에서 관측과 bootstrap을 분리하고, termination·truncation, SARSA·Q-learning, DQN·Double DQN target을 같은 숫자로 끝까지 계산합니다.',
    level: '중급',
    estimatedMinutes: 96,
    prerequisites: ['MDP, return과 Bellman equation', '신경망과 optimizer'],
    learningPath: 'ai-reinforcement-learning',
    component: () => import('@/pages/articles/ai/rl-temporal-difference-dqn'),
  },
  {
    slug: 'rl-pomdp-state-estimation',
    title: '부분 관측 실행 계약: POMDP·Belief·State Estimation',
    subcategory: 'ai-rl-state-estimation',
    sections: [
      { id: 'observation-state', title: 'State와 observation의 분리' },
      { id: 'pomdp-contract', title: 'POMDP의 생성 계약' },
      { id: 'belief-update', title: 'Bayesian belief update' },
      { id: 'belief-control', title: 'Belief-space policy와 정보 가치' },
      { id: 'kalman-filter', title: 'Kalman predict-correct' },
      { id: 'learned-memory', title: 'Recurrent learned state' },
      { id: 'deployment-diagnostics', title: 'Robot state-estimation 진단' },
    ],
    summary: 'Observation과 latent state를 분리하고 transition을 포함한 exact belief update, active sensing의 가치, Kalman consistency, recurrent burn-in 계약을 같은 숫자로 계산합니다.',
    level: '중급',
    estimatedMinutes: 120,
    prerequisites: ['MDP와 Markov state', '조건부 확률과 Bayes rule', '행렬·covariance와 RNN'],
    learningPath: 'ai-rl-state-current-first',
    component: () => import('@/pages/articles/ai/rl-pomdp-state-estimation'),
  },
  {
    slug: 'rl-policy-gradient-actor-critic',
    title: 'Policy Gradient 실행 계약: REINFORCE·Baseline·Actor-Critic',
    subcategory: 'ai-rl-policy-control',
    sections: [
      { id: 'policy-objective', title: 'Policy objective와 trajectory 확률' },
      { id: 'score-function', title: 'Log-derivative와 policy gradient' },
      { id: 'baseline', title: 'Baseline, advantage와 variance' },
      { id: 'actor-critic', title: 'Actor와 critic의 결합' },
      { id: 'gae', title: 'GAE의 bias-variance 조절' },
    ],
    summary: 'Trajectory 확률, reward-to-go의 인과성, baseline 분산과 terminal-safe TD를 직접 계산해 REINFORCE에서 Actor-Critic·GAE까지 연결합니다.',
    level: '중급',
    estimatedMinutes: 96,
    prerequisites: ['확률분포와 log', 'Gradient와 연쇄 법칙', 'TD error'],
    learningPath: 'ai-rl-policy-control-current-first',
    component: () => import('@/pages/articles/ai/rl-policy-gradient-actor-critic'),
  },
  {
    slug: 'rl-ppo-continuous-control',
    title: 'PPO 실행 계약: GAE·Clipping과 연속 제어 선택',
    subcategory: 'ai-rl-policy-control',
    sections: [
      { id: 'policy-shift', title: 'Policy가 너무 빨리 바뀌는 문제' },
      { id: 'ppo', title: 'Importance ratio와 clipped objective' },
      { id: 'training-loop', title: 'PPO actor-critic 학습 루프' },
      { id: 'continuous-control', title: 'DDPG, TD3와 SAC' },
      { id: 'llm-bridge', title: 'RLHF, GRPO와 RLVR 연결' },
    ],
    summary: 'Stored old log-probability에서 ratio를 만들고 terminal mask로 GAE를 역산한 뒤, clipping·연속 제어·LLM post-training으로 전이합니다.',
    level: '중급',
    estimatedMinutes: 102,
    prerequisites: ['Policy gradient와 advantage', 'Actor-critic', 'Importance sampling의 직관'],
    learningPath: 'ai-rl-policy-control-current-first',
    component: () => import('@/pages/articles/ai/rl-ppo-continuous-control'),
  },
  {
    slug: 'rl-imitation-offline-learning',
    title: '행동 기록에서 배우기: 모방 학습과 Offline RL',
    subcategory: 'ai-rl-offline',
    sections: [
      { id: 'demonstration-contract', title: 'Demonstration의 실행 계약' },
      { id: 'covariate-shift', title: 'Closed-loop distribution shift' },
      { id: 'dagger', title: 'DAgger와 recovery data' },
      { id: 'offline-rl', title: 'CQL·IQL과 dataset support' },
      { id: 'offline-evaluation', title: 'Off-policy evaluation과 support' },
      { id: 'sequence-modeling', title: 'Decision Transformer와 선택 기준' },
    ],
    summary: '잘하는 사람의 행동 기록을 따라 배운 규칙이 자기 실수로 낯선 장면을 만드는 이유부터 시작해, 추가 연습이 가능한 경우와 과거 기록만 남은 경우의 학습·검증법을 잇습니다.',
    level: '중급',
    estimatedMinutes: 118,
    prerequisites: ['상황에서 행동을 고르는 규칙', '한 행동이 다음 상황과 점수를 바꾸는 강화학습의 기본', '시간 순서대로 다음 값을 예측하는 방법(마지막 절)'],
    learningPath: 'ai-rl-offline-current-first',
    component: () => import('@/pages/articles/ai/rl-imitation-offline-learning'),
  },
  {
    slug: 'rl-model-based-world-models',
    title: '미래를 미리 그려 계획하기: Model-based RL과 World Models',
    subcategory: 'ai-rl-world-model',
    sections: [
      { id: 'model-contract', title: 'Model-based RL의 계약' },
      { id: 'dyna', title: 'Dyna와 stale model' },
      { id: 'model-bias', title: 'Model bias와 planning horizon' },
      { id: 'world-models', title: 'World Models의 V·M·C' },
      { id: 'muzero', title: 'MuZero의 search target' },
      { id: 'dreamer', title: 'Dreamer의 prior imagination' },
    ],
    summary: '다음 한 장면의 작은 예측 오차가 긴 계획에서 커지는 이유부터 시작해, Dyna·World Models·MuZero·Dreamer가 무엇을 예측하고 현실 결과로 어떻게 검산하는지 연결합니다.',
    level: '심화',
    estimatedMinutes: 126,
    prerequisites: ['상황·행동·점수와 Bellman 갱신', '행동 규칙과 가치 함수의 기초', '정보 압축과 시간에 따른 기억'],
    learningPath: 'ai-rl-model-current-first',
    component: () => import('@/pages/articles/ai/rl-model-based-world-models'),
  },
  {
    slug: 'rl-safe-constrained-learning',
    title: '성과와 안전선을 따로 배우기: Safe & Constrained RL',
    subcategory: 'ai-rl-safety',
    sections: [
      { id: 'safety-contract', title: 'Expected budget와 사고 확률' },
      { id: 'penalty-duality', title: 'Multiplier가 바꾸는 행동 순위' },
      { id: 'cpo', title: 'CPO local feasible step' },
      { id: 'lyapunov', title: 'Lyapunov state별 slack' },
      { id: 'recovery-shield', title: 'Risk gate와 제동 시간' },
      { id: 'deployment-case', title: 'Training·runtime·hardware 증거' },
    ],
    summary: '빠른 성공 점수와 충돌·힘·온도 같은 안전 비용을 먼저 분리한 뒤, 학습 중 제약·실행 직전 차단·물리 정지 장치가 맡을 책임을 단계별로 계산합니다.',
    level: '심화',
    estimatedMinutes: 128,
    prerequisites: ['상황·행동·누적 점수의 기본', 'PPO가 행동 규칙을 조금씩 바꾸는 과정', '제약이 있는 최적화의 기초'],
    learningPath: 'ai-rl-safety-current-first',
    component: () => import('@/pages/articles/ai/rl-safe-constrained-learning'),
  },
  {
    slug: 'paper-q-learning-1992',
    title: '논문 재구성 · Q-learning의 수렴 계약 (1992)',
    subcategory: 'ai-rl-foundations',
    sections: foundationalPaperSections,
    summary: '한 전이의 off-policy TD update가 어떤 tabular 조건에서 optimal Q로 수렴하는지 증명 범위와 구현 조건을 분리합니다.',
    level: '심화',
    estimatedMinutes: 64,
    prerequisites: ['MDP와 Bellman optimality', 'TD error', '확률적 근사의 직관'],
    learningPath: 'ai-rl-value-paper-spine',
    component: () => import('@/pages/articles/ai/paper-q-learning-1992'),
  },
  {
    slug: 'paper-dqn-2015',
    title: '논문 재구성 · Deep Q-Network와 안정화 장치 (2015)',
    subcategory: 'ai-rl-foundations',
    sections: foundationalPaperSections,
    summary: 'Q table을 신경망으로 바꿀 때 replay와 target network가 맡은 책임, Atari 증거와 일반화 한계를 복원합니다.',
    level: '심화',
    estimatedMinutes: 70,
    prerequisites: ['Q-learning', 'Convolutional network', 'Off-policy bootstrap'],
    learningPath: 'ai-rl-value-paper-spine',
    component: () => import('@/pages/articles/ai/paper-dqn-2015'),
  },
  {
    slug: 'paper-reinforce-1992',
    title: '논문 재구성 · REINFORCE와 확률적 정책 미분 (1992)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: '환경을 미분하지 않고 log-probability와 reinforcement로 기대 보상 gradient를 얻는 원리와 variance 경계를 재구성합니다.',
    level: '심화',
    estimatedMinutes: 66,
    prerequisites: ['확률분포와 로그', '기대값과 gradient', 'Policy objective'],
    learningPath: 'ai-rl-policy-paper-spine',
    component: () => import('@/pages/articles/ai/paper-reinforce-1992'),
  },
  {
    slug: 'paper-gae-2015',
    title: '논문 재구성 · GAE의 Bias-Variance 설계 (2015)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: 'TD residual의 지수 가중합이 advantage의 시간척도와 critic bias를 어떻게 조절하는지 원 논문 실험까지 추적합니다.',
    level: '심화',
    estimatedMinutes: 68,
    prerequisites: ['REINFORCE', 'Value baseline', 'TD error'],
    learningPath: 'ai-rl-policy-paper-spine',
    component: () => import('@/pages/articles/ai/paper-gae-2015'),
  },
  {
    slug: 'paper-ppo-2017',
    title: '논문 재구성 · PPO Clipping의 실제 계약 (2017)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: 'Old-policy ratio와 advantage 부호를 따라 clipped surrogate가 제한하는 것과 KL을 보장하지 못하는 경계를 계산합니다.',
    level: '심화',
    estimatedMinutes: 72,
    prerequisites: ['Policy gradient', 'GAE', 'Importance ratio'],
    learningPath: 'ai-rl-policy-paper-spine',
    component: () => import('@/pages/articles/ai/paper-ppo-2017'),
  },
  {
    slug: 'paper-ddpg-2015',
    title: '논문 재구성 · DDPG와 연속 Action Gradient (2015)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: 'Deterministic actor가 critic의 action gradient를 따라가는 경로와 replay·slow target의 숨은 가정을 복원합니다.',
    level: '심화',
    estimatedMinutes: 70,
    prerequisites: ['Actor-critic', 'DQN target network', '연속 action distribution'],
    learningPath: 'ai-rl-continuous-paper-spine',
    component: () => import('@/pages/articles/ai/paper-ddpg-2015'),
  },
  {
    slug: 'paper-td3-2018',
    title: '논문 재구성 · TD3와 Critic Error의 차단 (2018)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: 'Twin critic, delayed actor, target smoothing이 actor-critic의 서로 다른 오차 증폭 경로를 어떻게 끊는지 ablation과 함께 읽습니다.',
    level: '심화',
    estimatedMinutes: 70,
    prerequisites: ['DDPG', 'Function approximation error', 'Bootstrap target'],
    learningPath: 'ai-rl-continuous-paper-spine',
    component: () => import('@/pages/articles/ai/paper-td3-2018'),
  },
  {
    slug: 'paper-sac-2018',
    title: '논문 재구성 · Soft Actor-Critic과 Maximum Entropy (2018)',
    subcategory: 'ai-rl-policy-control',
    sections: foundationalPaperSections,
    summary: 'Reward와 entropy의 교환비, stochastic actor의 reparameterization, 원 SAC와 현대 recipe의 차이를 출처 단위로 분리합니다.',
    level: '심화',
    estimatedMinutes: 74,
    prerequisites: ['Off-policy actor-critic', 'Entropy', 'Squashed Gaussian'],
    learningPath: 'ai-rl-continuous-paper-spine',
    component: () => import('@/pages/articles/ai/paper-sac-2018'),
  },
  {
    slug: 'paper-dagger-2011',
    title: '논문 재구성 · DAgger와 Policy-induced Distribution (2011)',
    subcategory: 'ai-rl-offline',
    sections: foundationalPaperSections,
    summary: 'Expert state에서의 낮은 imitation error가 rollout에서 T² 비용이 될 수 있는 이유와 learner state를 다시 label하는 data aggregation을 복원합니다.',
    level: '심화',
    estimatedMinutes: 72,
    prerequisites: ['Behavior cloning', 'Closed-loop trajectory', 'Classification loss'],
    learningPath: 'ai-rl-offline-paper-spine',
    component: () => import('@/pages/articles/ai/paper-dagger-2011'),
  },
  {
    slug: 'paper-cql-2020',
    title: '논문 재구성 · CQL과 Offline Value Pessimism (2020)',
    subcategory: 'ai-rl-offline',
    sections: foundationalPaperSections,
    summary: 'Static dataset 밖 action의 Q가 왜 과대평가되는지 추적하고 conservative penalty와 lower-bound 주장의 조건을 분리합니다.',
    level: '심화',
    estimatedMinutes: 76,
    prerequisites: ['Off-policy Q-learning', 'SAC 또는 DQN', 'Dataset support'],
    learningPath: 'ai-rl-offline-paper-spine',
    component: () => import('@/pages/articles/ai/paper-cql-2020'),
  },
  {
    slug: 'paper-decision-transformer-2021',
    title: '논문 재구성 · Decision Transformer와 Return Prompt (2021)',
    subcategory: 'ai-rl-offline',
    sections: foundationalPaperSections,
    summary: 'Offline trajectory를 return·state·action sequence로 바꾸고 supervised objective가 behavior improvement로 작동하는 조건과 support 한계를 읽습니다.',
    level: '심화',
    estimatedMinutes: 74,
    prerequisites: ['Offline trajectory', 'Causal Transformer', 'Return-to-go'],
    learningPath: 'ai-rl-offline-paper-spine',
    component: () => import('@/pages/articles/ai/paper-decision-transformer-2021'),
  },
  {
    slug: 'paper-dyna-1990',
    title: '논문 재구성 · Dyna의 Learning·Planning 통합 (1990)',
    subcategory: 'ai-rl-world-model',
    sections: foundationalPaperSections,
    summary: '실제 transition과 learned model의 simulated transition에 같은 value update를 적용하는 통합 architecture와 model bias의 출발점을 복원합니다.',
    level: '심화',
    estimatedMinutes: 68,
    prerequisites: ['Tabular Q-learning', 'Environment transition model', 'Dynamic programming'],
    learningPath: 'ai-rl-model-paper-spine',
    component: () => import('@/pages/articles/ai/paper-dyna-1990'),
  },
  {
    slug: 'paper-world-models-2018',
    title: '논문 재구성 · World Models와 Latent Dream (2018)',
    subcategory: 'ai-rl-world-model',
    sections: foundationalPaperSections,
    summary: 'VAE·MDN-RNN·작은 controller의 분리 학습과 dream-to-real transfer가 무엇을 보여주고 무엇을 보장하지 않는지 재구성합니다.',
    level: '심화',
    estimatedMinutes: 76,
    prerequisites: ['VAE', 'RNN과 mixture density', 'Continuous control'],
    learningPath: 'ai-rl-model-paper-spine',
    component: () => import('@/pages/articles/ai/paper-world-models-2018'),
  },
  {
    slug: 'paper-muzero-2020',
    title: '논문 재구성 · MuZero와 Planning-relevant Model (2020)',
    subcategory: 'ai-rl-world-model',
    sections: foundationalPaperSections,
    summary: 'Observation을 복원하지 않고 reward·policy·value만 예측하는 latent dynamics와 MCTS·replay target의 전체 순서를 복원합니다.',
    level: '심화',
    estimatedMinutes: 82,
    prerequisites: ['MCTS', 'Policy·value network', 'Latent dynamics'],
    learningPath: 'ai-rl-model-paper-spine',
    component: () => import('@/pages/articles/ai/paper-muzero-2020'),
  },
  {
    slug: 'paper-dreamerv3-2023',
    title: '논문 재구성 · DreamerV3와 Latent Imagination (2023)',
    subcategory: 'ai-rl-world-model',
    sections: foundationalPaperSections,
    summary: 'RSSM posterior·prior, imagined lambda-return과 scale-robust loss가 150개 이상 task의 fixed recipe로 이어지는 근거를 읽습니다.',
    level: '심화',
    estimatedMinutes: 86,
    prerequisites: ['World model', 'Actor-critic과 lambda-return', 'Variational latent state'],
    learningPath: 'ai-rl-model-paper-spine',
    component: () => import('@/pages/articles/ai/paper-dreamerv3-2023'),
  },
  {
    slug: 'paper-cpo-2017',
    title: '논문 재구성 · CPO와 근사 Constraint 보장 (2017)',
    subcategory: 'ai-rl-safety',
    sections: foundationalPaperSections,
    summary: 'CMDP의 reward·cost surrogate와 KL trust region을 한 local solve로 묶고 theoretical bound와 practical neural implementation의 간격을 읽습니다.',
    level: '심화',
    estimatedMinutes: 82,
    prerequisites: ['Policy gradient와 GAE', 'TRPO·PPO의 trust region 직관', 'Lagrangian과 quadratic form'],
    learningPath: 'ai-rl-safety-paper-spine',
    component: () => import('@/pages/articles/ai/paper-cpo-2017'),
  },
  {
    slug: 'paper-lyapunov-safe-rl-2018',
    title: '논문 재구성 · Lyapunov 기반 Safe RL (2018)',
    subcategory: 'ai-rl-safety',
    sections: foundationalPaperSections,
    summary: 'Global expected-cost budget을 state별 Bellman inequality와 local feasible policy set으로 바꾸는 원리, feasible baseline과 근사 오차의 경계를 복원합니다.',
    level: '심화',
    estimatedMinutes: 84,
    prerequisites: ['CMDP와 Bellman operator', 'Lyapunov 함수의 직관', 'Linear programming'],
    learningPath: 'ai-rl-safety-paper-spine',
    component: () => import('@/pages/articles/ai/paper-lyapunov-safe-rl-2018'),
  },
  {
    slug: 'paper-recovery-rl-2021',
    title: '논문 재구성 · Recovery RL과 Learned Recovery Zones (2021)',
    subcategory: 'ai-rl-safety',
    sections: foundationalPaperSections,
    summary: 'Offline violation data로 safety critic과 recovery policy를 pretrain하고 task action을 runtime에 교체하는 실행·relabeling·failure contract를 복원합니다.',
    level: '심화',
    estimatedMinutes: 80,
    prerequisites: ['Offline RL과 dataset coverage', 'Off-policy actor-critic', 'Model predictive control의 직관'],
    learningPath: 'ai-rl-safety-paper-spine',
    component: () => import('@/pages/articles/ai/paper-recovery-rl-2021'),
  },
  {
    slug: 'paper-pomdp-1998',
    title: '논문 재구성 · POMDP와 Belief-State Planning (1998)',
    subcategory: 'ai-rl-state-estimation',
    sections: foundationalPaperSections,
    summary: '부분 관측 agent를 state estimator와 belief policy로 분해하고 exact Bayesian update, policy-tree value geometry와 계산 복잡도의 경계를 복원합니다.',
    level: '심화',
    estimatedMinutes: 86,
    prerequisites: ['MDP와 Bellman equation', 'Bayes rule', 'Convex upper envelope의 직관'],
    learningPath: 'ai-rl-pomdp-paper-spine',
    component: () => import('@/pages/articles/ai/paper-pomdp-1998'),
  },
  {
    slug: 'paper-kalman-filter-1960',
    title: '논문 재구성 · Kalman Filtering과 Covariance Recursion (1960)',
    subcategory: 'ai-rl-state-estimation',
    sections: foundationalPaperSections,
    summary: 'Wiener filter의 impulse-response 문제를 state-transition과 recursive error covariance로 바꾼 저자 의도와 현대 predict-correct 구현을 연결합니다.',
    level: '심화',
    estimatedMinutes: 84,
    prerequisites: ['선형 dynamical system', '조건부 평균과 covariance', 'Matrix inverse의 직관'],
    learningPath: 'ai-rl-pomdp-paper-spine',
    component: () => import('@/pages/articles/ai/paper-kalman-filter-1960'),
  },
  {
    slug: 'paper-drqn-2015',
    title: '논문 재구성 · DRQN과 Learned Memory (2015)',
    subcategory: 'ai-rl-state-estimation',
    sections: foundationalPaperSections,
    summary: 'Single-frame DQN에 LSTM을 넣어 partial observation을 통합하는 계산 경로와 sequential·random recurrent replay의 숨은 상태 문제를 복원합니다.',
    level: '심화',
    estimatedMinutes: 78,
    prerequisites: ['DQN과 target network', 'LSTM', 'POMDP와 belief state'],
    learningPath: 'ai-rl-pomdp-paper-spine',
    component: () => import('@/pages/articles/ai/paper-drqn-2015'),
  },
];
