import type { Article } from '../types';

// ── Foundations (후반): 딥러닝 개요, 오토인코더 ──
export const dlFoundation2Articles: Article[] = [
  {
    slug: 'deep-learning-overview',
    title: '딥러닝 학습 루프: 데이터에서 업데이트까지',
    subcategory: 'ai-foundations',
    sections: [
      { id: 'overview', title: '학습 시스템의 다섯 역할' },
      { id: 'representation', title: '깊이와 표현 학습' },
      { id: 'learning-loop', title: '한 번의 학습 과정' },
      { id: 'compute', title: 'Tensor 계산과 GPU' },
      { id: 'limits', title: '학습과 일반화의 차이' },
      { id: 'roadmap', title: '다음 학습 순서' },
    ],
    summary: '데이터, 모델, 예측, 손실, 기울기, 업데이트가 하나의 학습 루프로 연결되는 과정을 먼저 그립니다.',
    level: '입문',
    estimatedMinutes: 30,
    prerequisites: ['사칙연산', '함수는 입력을 출력으로 바꾼다는 직관'],
    learningPath: 'ai-foundations-core',
    component: () => import('@/pages/articles/ai/deep-learning-overview'),
  },
  {
    slug: 'autoencoder',
    title: '오토인코더: 압축과 복원으로 배우는 표현 학습',
    subcategory: 'ai-foundations',
    sections: [
      { id: 'overview', title: 'Reconstruction objective' },
      { id: 'bottleneck', title: 'Bottleneck과 표현' },
      { id: 'forward-example', title: '2→1→2 숫자 예제' },
      { id: 'loss-backprop', title: '복원 오차의 역전파' },
      { id: 'evaluation', title: '평가와 실패 조건' },
      { id: 'variants', title: '변형과 생성 모델 연결' },
    ],
    summary: '압축·복원 목표에서 encoder gradient를 숫자로 검산하고, bottleneck의 PCA 한계와 VAE·latent diffusion의 경계까지 연결합니다.',
    level: '기초',
    estimatedMinutes: 64,
    prerequisites: ['신경망 순전파', '손실 함수', '역전파와 옵티마이저'],
    learningPath: 'ai-foundations-core',
    component: () => import('@/pages/articles/ai/autoencoder'),
  },
];

// ── Computer Vision ──
export const dlVisionArticles: Article[] = [
  {
    slug: 'vision-system-contracts',
    title: '컴퓨터 비전 작업 계약: 분류·박스·마스크·Tracking을 고르는 법',
    subcategory: 'ai-vision-overview',
    summary: '제품 질문을 class, box, mask와 stable ID 출력으로 번역하고 좌표 변환, IoU·AP, latency와 실패 slice를 하나의 검증 계약으로 묶습니다.',
    level: '입문',
    estimatedMinutes: 42,
    prerequisites: ['이미지는 숫자 격자라는 직관', '비율과 평균의 기초'],
    learningPath: 'ai-vision-contract-current-first',
    sections: [
      { id: 'product-question', title: '제품 질문을 출력으로 번역하기' },
      { id: 'task-contracts', title: 'Class·Box·Mask·ID 계약' },
      { id: 'coordinate-contract', title: 'Pixel과 좌표 변환' },
      { id: 'score-geometry', title: 'Score·IoU와 중복 판단' },
      { id: 'evaluation', title: 'AP와 Scenario slice' },
      { id: 'handoff', title: 'Detector·Segmenter·Tracker 연결' },
      { id: 'release', title: 'Release gate와 어려운 검산' },
    ],
    component: () => import('@/pages/articles/ai/vision-system-contracts'),
  },
  {
    slug: 'vision-promptable-segmentation-tracking',
    title: 'SAM 3.1: Promptable Segmentation과 Video Tracking',
    subcategory: 'ai-vision-promptable',
    summary: '점·박스와 text concept의 출력 계약부터 detector, streaming memory, object identity와 SAM 3.1 Object Multiplex의 실제 비용 구조까지 연결합니다.',
    level: '심화',
    estimatedMinutes: 54,
    prerequisites: ['Mask와 object identity의 직관', 'Embedding과 attention의 기초'],
    learningPath: 'ai-vision-promptable-current-first',
    sections: [
      { id: 'task-contract', title: 'PVS와 PCS의 출력 계약' },
      { id: 'contract-lineage', title: 'SAM 1 → 2 → 3 → 3.1' },
      { id: 'concept-detector', title: 'Concept detector와 Presence' },
      { id: 'video-memory', title: 'Video memory와 Identity' },
      { id: 'object-multiplex', title: 'Object Multiplex' },
      { id: 'evaluation', title: '품질·Identity·Runtime 평가' },
      { id: 'implementation', title: 'Session 구현과 Release gate' },
    ],
    component: () => import('@/pages/articles/ai/vision-promptable-segmentation-tracking'),
  },
  {
    slug: 'object-detection-systems',
    title: '객체 탐지 시스템: Real-time과 Open Vocabulary를 선택하는 법',
    subcategory: 'ai-vision-detection',
    summary: '고정 class의 빠른 검출과 자연어 기반 open-vocabulary grounding을 분리하고, D-FINE·Grounding DINO의 실행 흐름과 배포 gate를 비교합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['컴퓨터 비전 작업 계약', 'Bounding box와 feature의 직관'],
    learningPath: 'ai-vision-detection-current-first',
    sections: [
      { id: 'decision', title: '먼저 Vocabulary 계약을 고른다' },
      { id: 'fixed-vocabulary', title: 'Fixed vocabulary · D-FINE' },
      { id: 'open-vocabulary', title: 'Open vocabulary · Grounding DINO' },
      { id: 'postprocess', title: 'Threshold·NMS·Set prediction' },
      { id: 'runtime', title: 'Runtime과 Handoff' },
      { id: 'evaluation', title: '평가와 실패 Slice' },
      { id: 'implementation', title: '구현·Release gate' },
    ],
    component: () => import('@/pages/articles/ai/object-detection-systems'),
  },
  {
    slug: 'deformable-detr',
    title: 'Deformable DETR: Sparse Multi-Scale Object Detection',
    subcategory: 'ai-vision-detection',
    summary: 'DETR의 set prediction에서 시작해 learned offset과 multi-scale sparse sampling으로 작은 객체와 수렴 병목을 푸는 과정을 계산합니다.',
    level: '중급',
    estimatedMinutes: 52,
    prerequisites: ['CNN feature map', 'QKV attention', 'bounding box와 IoU의 직관'],
    learningPath: 'ai-vision-detection-current-first',
    sections: [
      { id: 'set-prediction', title: 'Set prediction과 matching' },
      { id: 'detr-source-evidence', title: 'DETR 원문 evidence와 한계' },
      { id: 'detr-bottleneck', title: 'DETR의 해상도 병목' },
      { id: 'deformable-attention', title: 'Sparse sampling 계산' },
      { id: 'multi-scale', title: 'Multi-scale과 작은 객체' },
      { id: 'diagnose', title: 'AP_small 실패 진단' },
    ],
    component: () => import('@/pages/articles/ai/deformable-detr'),
  },
  {
    slug: 'vision-representation-encoders-current',
    title: 'Vision Encoder 2025: PE·SigLIP 2·DINOv3를 출력 계약으로 고르는 법',
    subcategory: 'ai-vision-foundations',
    summary: 'Global retrieval, multilingual alignment, dense localization과 self-supervised transfer를 분리하고 PE·SigLIP 2·DINOv3에서 어느 layer의 어떤 tensor를 검증할지 정합니다.',
    level: '중급',
    estimatedMinutes: 46,
    prerequisites: ['이미지는 patch 또는 feature map으로 표현된다는 직관', '벡터 유사도의 기초'],
    learningPath: 'ai-vision-representation-foundations',
    learningPaths: [
      'ai-vision-language-alignment-foundation',
      'ai-vision-patch-backbone-foundation',
      'ai-vision-conv-backbone-foundation',
    ],
    sections: [
      { id: 'current-question', title: '현재 encoder를 한 순위로 고를 수 없는 이유' },
      { id: 'shared-contract', title: 'Layer·head·output 계약' },
      { id: 'pe', title: 'Perception Encoder와 intermediate feature' },
      { id: 'siglip2', title: 'SigLIP 2와 multilingual alignment' },
      { id: 'dinov3', title: 'DINOv3와 dense self-supervised feature' },
      { id: 'release', title: '선택적 바닥과 release evidence' },
    ],
    component: () => import('@/pages/articles/ai/vision-representation-encoders-current'),
  },
  {
    slug: 'clip-vision-language-model',
    title: 'CLIP이 뭐야: 이미지와 텍스트를 같은 좌표계에 놓는 모델',
    subcategory: 'ai-vision-foundations',
    summary: '이미지와 텍스트를 같은 좌표계에 정렬하는 contrastive objective를 계산하고, zero-shot 분류·검색과 region grounding의 경계를 구분합니다.',
    level: '기초',
    estimatedMinutes: 44,
    prerequisites: ['벡터와 내적의 직관', 'Softmax와 cross-entropy'],
    learningPath: 'ai-vision-language-alignment-foundation',
    sections: [
      { id: 'overview', title: 'CLIP의 한 문장 정의' },
      { id: 'training', title: '이미지-텍스트 contrastive learning' },
      { id: 'embedding-space', title: 'Shared embedding space와 cosine similarity' },
      { id: 'use-cases', title: 'Zero-shot 분류와 image retrieval' },
      { id: 'image-rag', title: 'Image RAG에서 CLIP을 쓰는 법' },
      { id: 'limits', title: '한계와 비교 기준' },
      { id: 'release', title: 'Release gate와 전이 검산' },
    ],
    component: () => import('@/pages/articles/ai/clip-vision-language-model'),
  },
  {
    slug: 'cnn',
    title: 'CNN: 공유 Kernel에서 공간 계약까지',
    subcategory: 'ai-vision-foundations',
    summary: '작은 kernel을 위치마다 공유해 local pattern을 찾고, stride·padding·receptive field가 공간 정보를 바꾸는 과정을 계산합니다.',
    level: '기초',
    estimatedMinutes: 52,
    prerequisites: ['행렬의 행·열', '가중합과 활성화 함수'],
    learningPath: 'ai-vision-conv-backbone-foundation',
    sections: [
      { id: 'overview', title: '같은 질문을 모든 위치에 묻기' },
      { id: 'convolution-layer', title: '한 출력값의 실제 계산' },
      { id: 'inductive-bias', title: '지역성과 평행이동 등변성' },
      { id: 'architectures', title: 'Shape와 수용야 추적' },
      { id: 'applications', title: '작은 신호 전이 문제' },
      { id: 'cnn-vs-transformer', title: '현대 Backbone 선택' },
    ],
    component: () => import('@/pages/articles/ai/cnn'),
  },
  {
    slug: 'resnet',
    title: 'ResNet: Degradation과 Identity 경로',
    subcategory: 'ai-vision-foundations',
    summary: '깊은 network가 단순히 층을 늘릴 때 악화되는 이유와 identity skip이 forward·gradient 경로를 보존하는 원리를 계산합니다.',
    level: '기초',
    estimatedMinutes: 58,
    prerequisites: ['CNN의 convolution과 feature map', 'Chain rule의 직관'],
    learningPath: 'ai-vision-conv-backbone-foundation',
    sections: [
      { id: 'overview', title: '깊이와 최적화의 차이' },
      { id: 'vanishing-gradient', title: 'Plain chain과 Identity gradient' },
      { id: 'skip-connection', title: 'Shortcut의 Shape 계약' },
      { id: 'residual-computation', title: 'Residual 누적 계산' },
      { id: 'architecture', title: 'Stage와 Block Type' },
      { id: 'impact', title: '현재 구조로 이어지는 기준점' },
    ],
    component: () => import('@/pages/articles/ai/resnet'),
  },
];
