import type { Article } from '../types';

export const mathFoundationArticles: Article[] = [
  {
    slug: 'linear-algebra-tensors',
    title: '선형대수와 Tensor Shape: 신경망 계산의 언어',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'objects-coordinates', title: '01 · 대상, 축, 좌표' },
      { id: 'linear-combinations', title: '02 · 선형 결합과 행렬' },
      { id: 'dot-projection', title: '03 · 내적, cosine과 projection' },
      { id: 'linear-maps', title: '04 · 행렬곱과 contraction' },
      { id: 'tensor-contraction', title: '05 · Tensor shape와 attention' },
      { id: 'broadcasting', title: '06 · Broadcasting의 의미 충돌' },
      { id: 'layout-memory', title: '07 · Stride, dtype와 memory' },
    ],
    summary: '같은 대상을 좌표로 기록하는 법부터 내적·행렬곱의 축 contraction, attention shape, broadcasting 의미 충돌, stride와 실제 GPU byte까지 한 흐름으로 연결합니다.',
    level: '입문',
    estimatedMinutes: 94,
    prerequisites: ['사칙연산', '좌표평면'],
    learningPath: 'ai-math-shape-foundations',
    component: () => import('@/pages/articles/ai/linear-algebra-tensors'),
  },
  {
    slug: 'linear-algebra-decompositions',
    title: '부분공간과 행렬 분해: Rank에서 SVD까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'subspaces', title: 'Span, basis, rank와 null space' },
      { id: 'least-squares', title: 'Projection과 least squares' },
      { id: 'eigen', title: 'Eigenvalue와 반복 dynamics' },
      { id: 'svd', title: 'SVD와 low-rank approximation' },
      { id: 'ai-bridge', title: 'Embedding, PCA와 gradient 진단' },
    ],
    summary: '부분공간, rank, 최소제곱, 고유값, SVD를 데이터 압축과 recurrent dynamics의 안정성으로 연결합니다.',
    level: '기초',
    estimatedMinutes: 68,
    prerequisites: ['벡터와 내적', '행렬곱과 전치'],
    learningPath: 'ai-math-shape-foundations',
    component: () => import('@/pages/articles/ai/linear-algebra-decompositions'),
  },
  {
    slug: 'calculus-computational-graphs',
    title: '미분과 계산 그래프: Local 변화에서 JVP·VJP까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'why-sensitivity', title: '01 · 상위 시스템의 공통 질문' },
      { id: 'derivative-linearization', title: '02 · Derivative와 local linearization' },
      { id: 'gradient-direction', title: '03 · Gradient와 방향 미분' },
      { id: 'chain-product-graph', title: '04 · Chain·product와 graph 합산' },
      { id: 'jacobian-products', title: '05 · Jacobian, JVP와 VJP' },
      { id: 'autograd-runtime', title: '06 · Autograd runtime 경계' },
      { id: 'gradient-check', title: '07 · 수치 gradient 검산' },
      { id: 'path-second-chain', title: '08 · Path 위의 2차 chain rule' },
      { id: 'return-up', title: '09 · LLM·Diffusion·RL·Robot 복귀' },
    ],
    summary: 'Derivative를 작은 변화 예측기로 시작해 gradient·directional derivative, chain/product rule, branch·broadcast 합산, Jacobian의 JVP·VJP, PyTorch autograd runtime, finite-difference 검산과 robot path의 2차 chain rule까지 하나의 sensitivity 흐름으로 연결합니다.',
    level: '기초',
    estimatedMinutes: 112,
    prerequisites: ['함수와 그래프', '벡터·행렬과 tensor shape'],
    learningPath: 'ai-math-change-foundations',
    component: () => import('@/pages/articles/ai/calculus-computational-graphs'),
  },
  {
    slug: 'integrals-fields-conservation',
    title: '적분·장·보존법칙: 작은 조각에서 시스템 총량까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'why-accumulation', title: '01 · 작은 조각의 기여' },
      { id: 'sum-to-integral', title: '02 · 합에서 적분으로' },
      { id: 'domain-and-fields', title: '03 · Domain과 field' },
      { id: 'resultant-moment', title: '04 · 합력과 모멘트' },
      { id: 'oriented-flux', title: '05 · 방향이 있는 flux' },
      { id: 'divergence-local-global', title: '06 · Local에서 global로' },
      { id: 'control-volume-ledger', title: '07 · Control-volume ledger' },
      { id: 'discrete-conservation', title: '08 · Discrete conservation' },
      { id: 'return-up', title: '09 · 상위 공학으로 복귀' },
    ],
    summary: 'Density와 measure의 작은 기여를 적분으로 모으는 법부터 line·surface·volume domain, scalar·vector field, 분포하중의 합력과 모멘트, oriented flux, divergence theorem, fixed control-volume balance와 보존적 finite-volume bookkeeping까지 한 흐름으로 연결합니다.',
    level: '기초',
    estimatedMinutes: 122,
    prerequisites: ['함수와 그래프', '벡터·내적', '미분의 변화율 직관'],
    learningPath: 'ai-math-change-foundations',
    component: () => import('@/pages/articles/ai/integrals-fields-conservation'),
  },
  {
    slug: 'differential-equations-phase-plane-numerical-integration',
    title: '미분방정식과 Phase Plane: 변화 규칙에서 궤적 적분까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'state-rate-ledger', title: '01 · State와 rate 원장' },
      { id: 'driven-state', title: '02 · 외부 입력과 schedule' },
      { id: 'euler-step', title: '03 · Euler 한 걸음' },
      { id: 'error-convergence', title: '04 · Local과 global error' },
      { id: 'stability-stiffness', title: '05 · Stability와 stiffness' },
      { id: 'phase-portrait', title: '06 · 위치·속도의 Phase Portrait' },
      { id: 'two-boundary-envelope', title: '07 · 양끝 경계와 speed cap' },
      { id: 'events-tolerance', title: '08 · Event와 tolerance' },
      { id: 'return-to-upper-questions', title: '09 · 상위 모델로 복귀' },
    ],
    summary: '적분의 rate 원장에서 출발해 driven state, Euler와 global error, explicit stability와 stiffness, 위치-속도 phase portrait, 양끝 경계와 speed cap, grid 사이 event를 한 흐름으로 연결하고 Diffusion·thermal·robot·SSM으로 돌아갑니다.',
    level: '기초',
    estimatedMinutes: 128,
    prerequisites: ['함수와 그래프', '도함수의 기울기 직관', 'rate를 interval에 누적하는 적분', '벡터 두 개를 한 묶음으로 보는 법'],
    learningPath: 'ai-math-change-foundations',
    component: () => import('@/pages/articles/ai/differential-equations-phase-plane-numerical-integration'),
  },
  {
    slug: 'optimization-geometry',
    title: '최적화의 기하: Convexity에서 KKT까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'objective', title: '목적함수와 feasible set' },
      { id: 'convexity', title: 'Convexity와 local/global optimum' },
      { id: 'curvature', title: 'Hessian, condition number와 update' },
      { id: 'constraints', title: 'Lagrangian과 KKT' },
      { id: 'deep-learning', title: '비볼록 딥러닝에서 남는 기준' },
    ],
    summary: '경사하강법을 공식으로 외우지 않고 곡률, condition number, line search, 제약과 KKT의 기하로 해석합니다.',
    level: '기초',
    estimatedMinutes: 72,
    prerequisites: ['Gradient와 Jacobian', '행렬과 고유값'],
    learningPath: 'ai-math-evidence-foundations',
    component: () => import('@/pages/articles/ai/optimization-geometry'),
  },
  {
    slug: 'probability-information-theory',
    title: '확률과 정보 이론: Logit에서 학습 Loss까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'score-distribution', title: 'Score에서 분포까지' },
      { id: 'joint-conditional-bayes', title: 'Joint, Conditional과 Bayes' },
      { id: 'probability-likelihood', title: 'Probability와 Likelihood' },
      { id: 'logit-loss', title: 'Logit에서 학습 Loss까지' },
      { id: 'information-costs', title: '정보 비용과 KL' },
      { id: 'probability-boundaries', title: '확률 출력의 경계' },
    ],
    summary: '가능한 결과와 관측을 분리하고, joint·Bayes·likelihood를 거쳐 logit이 softmax, NLL, cross-entropy와 KL로 이어지는 계산과 calibration의 경계를 추적합니다.',
    level: '기초',
    estimatedMinutes: 88,
    prerequisites: ['분수', '로그 함수의 직관'],
    learningPath: 'ai-math-evidence-foundations',
    component: () => import('@/pages/articles/ai/probability-information-theory'),
  },
  {
    slug: 'statistics-generalization',
    title: '통계와 일반화: 한 점수에서 배포 주장까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'target-population', title: '배포 주장과 estimand' },
      { id: 'independent-unit', title: '행과 독립 단위' },
      { id: 'paired-comparison', title: '같은 사례의 paired 차이' },
      { id: 'selection-boundary', title: '선택과 untouched audit' },
      { id: 'uncertainty-procedure', title: 'Group-aware uncertainty' },
      { id: 'shift-calibration', title: 'Shift, calibration, subgroup' },
      { id: 'claim-decision', title: 'Evidence claim lab' },
      { id: 'next-routes', title: '구현 글로 넘기기' },
    ],
    summary: '배포 모집단과 독립 단위를 고정하고 paired 차이, 선택 편향, group-aware uncertainty, shift와 guardrail을 하나의 검증 가능한 주장으로 연결합니다.',
    level: '기초',
    estimatedMinutes: 76,
    prerequisites: ['평균과 비율', '확률의 기초 직관', 'loss와 평가 지표'],
    learningPath: 'ai-math-evidence-foundations',
    learningPaths: ['ai-llm-interpretability-current-first'],
    component: () => import('@/pages/articles/ai/statistics-generalization'),
  },
  {
    slug: 'signals-systems-convolution',
    title: '신호와 시스템: 시간 기록에서 필터와 AI 기억까지',
    subcategory: 'ai-math-foundations',
    sections: [
      { id: 'signal-contract', title: '01 · 시간축과 system 계약' },
      { id: 'impulse-convolution', title: '02 · Impulse와 convolution' },
      { id: 'causality-stability', title: '03 · Causality와 stability' },
      { id: 'difference-equation-state', title: '04 · Difference equation과 state' },
      { id: 'frequency-execution', title: '05 · Frequency와 FFT 경계' },
      { id: 'sampling-information', title: '06 · Sampling과 aliasing' },
      { id: 'ai-runtime-bridge', title: '07 · Conv1d, S4와 Mamba' },
    ],
    summary: '온도·소리·robot sensor처럼 시간에 따라 달라지는 값을 기록하는 장면에서 시작해, 값을 섞는 filter와 과거를 기억하는 규칙이 AI 안에서 어떻게 쓰이는지 연결합니다.',
    level: '기초',
    estimatedMinutes: 112,
    prerequisites: [],
    learningPath: 'ai-math-signal-foundations',
    component: () => import('@/pages/articles/ai/signals-systems-convolution'),
  },
];
