import type { Article } from '../types';

export const currentFlowArticles: Article[] = [
  {
    slug: 'llm-pretraining-scaling',
    title: 'LLM은 처음 어떻게 배우나: Pre-training과 학습 예산',
    subcategory: 'ai-llm-data-scaling',
    summary: '대화를 시작하기 전 LLM이 수많은 문장의 다음 조각을 맞히는 방법부터, 더 큰 모델과 더 많은 연습 중 어디에 시간과 계산을 쓸지 차근차근 이해한다.',
    level: '기초',
    estimatedMinutes: 50,
    prerequisites: [],
    learningPath: 'ai-llm-pretraining-current-first',
    sections: [
      { id: 'deployment-first', title: 'LLM은 처음에 어떻게 배울까?' },
      { id: 'three-budgets', title: '크기·연습량·계산량은 어떻게 연결될까?' },
      { id: 'compute-frontier', title: '같은 계산량에서 가장 좋은 조합은?' },
      { id: 'inference-aware', title: '학습 뒤 많이 쓸수록 선택은 왜 달라질까?' },
      { id: 'data-constrained', title: '고유 데이터가 모자라면 반복은 언제 멈출까?' },
      { id: 'pilot-plan', title: '큰 학습 전에 어떤 작은 실험을 할까?' },
    ],
    component: () => import('@/pages/articles/ai/llm-pretraining-scaling'),
  },
  {
    slug: 'paper-chinchilla-2022',
    title: '논문 재구성 · Chinchilla Compute-Optimal Scaling (2022)',
    subcategory: 'ai-llm-data-scaling',
    summary: '세 scaling 추정법, 실제 fitted constant와 Gopher matched-compute 70B·1.4T 검증을 원문 수치와 한계까지 복원한다.',
    level: '심화',
    estimatedMinutes: 64,
    prerequisites: ['다음 token loss', '파라미터·token·FLOPs의 차이', '거듭제곱과 log-log graph'],
    learningPath: 'ai-llm-pretraining-current-first',
    sections: [
      { id: 'research-question', title: '같은 GPU 예산을 어디에 쓸까?' },
      { id: 'three-approaches', title: '세 추정법은 무엇을 다르게 볼까?' },
      { id: 'loss-fit', title: 'Loss의 세 항과 scaling exponent' },
      { id: 'matched-compute', title: '70B·1.4T matched-compute 검증' },
      { id: 'limits', title: '원문의 외삽과 data 한계' },
      { id: 'handoff', title: '현재 pre-training 설계로' },
    ],
    component: () => import('@/pages/articles/ai/paper-chinchilla-2022'),
  },
  {
    slug: 'llm-data-engine',
    title: 'LLM 데이터 엔진: 웹 문서에서 학습 신호까지',
    subcategory: 'ai-llm-data-pipeline',
    summary: '수집량이 아니라 추출·중복 제거·품질 점수·혼합·합성·오염 검사가 모델 능력을 만드는 과정을 바닥부터 연결한다.',
    level: '중급',
    estimatedMinutes: 38,
    prerequisites: ['다음 token 예측이 LLM의 기본 학습 목표라는 이해', 'train·validation·test의 차이'],
    learningPath: 'ai-llm-pretraining-current-first',
    sections: [
      { id: 'signal-not-volume', title: '데이터가 많다는 말로는 무엇을 놓칠까?' },
      { id: 'pipeline', title: '원문이 학습 token이 되기까지' },
      { id: 'selection', title: '필터와 혼합은 어떤 분포를 만드는가?' },
      { id: 'synthetic', title: '합성 데이터는 언제 새 신호가 되는가?' },
      { id: 'evaluation', title: '오염 없이 데이터 효과를 어떻게 검증할까?' },
      { id: 'small-model', title: '4B·9B 모델에서는 무엇을 우선할까?' },
    ],
    component: () => import('@/pages/articles/ai/llm-data-engine'),
  },
  {
    slug: 'llm-pretraining-run',
    title: 'LLM Pre-training Run: Token Batch에서 Resume·평가까지',
    subcategory: 'ai-llm-data-training',
    summary: '4B·9B 예산과 data recipe를 update당 유효 token, 분산 state, checkpoint·resume equivalence와 clean scale-up gate로 닫는다.',
    level: '중급',
    estimatedMinutes: 44,
    prerequisites: ['파라미터·token·compute 예산의 차이', 'Versioned data recipe와 clean held-out 평가'],
    learningPath: 'ai-llm-pretraining-current-first',
    sections: [
      { id: 'run-receipt', title: 'Model·data 결정을 run 영수증으로' },
      { id: 'token-batch', title: 'Update당 유효 token 계산' },
      { id: 'parallel-memory', title: '병렬화와 state 소유권' },
      { id: 'update-contract', title: '한 optimizer update의 순서' },
      { id: 'checkpoint-resume', title: 'Checkpoint와 resume equivalence' },
      { id: 'evaluation-stop', title: 'Clean 평가와 scale-up gate' },
    ],
    component: () => import('@/pages/articles/ai/llm-pretraining-run'),
  },
  {
    slug: 'on-device-llm-runtime',
    title: 'On-device LLM Runtime: Export에서 Thermal Release까지',
    subcategory: 'ai-llm-efficiency-runtime',
    summary: 'Checkpoint를 target별 실행 graph로 내리고 delegation·fallback·memory·device trace를 검증해 실제 앱 release로 닫는다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['Transformer의 prefill·decode 구분', 'byte·bandwidth·latency의 차이'],
    learningPath: 'ai-llm-on-device-runtime',
    sections: [
      { id: 'release-not-demo', title: '왜 데스크톱 성공이 device release는 아닐까?' },
      { id: 'export-contract', title: 'Export는 무엇을 실행 계약으로 고정할까?' },
      { id: 'partition-delegate', title: 'Partitioner는 graph를 어떻게 나눌까?' },
      { id: 'coverage-boundary', title: '위임률 94%인데 왜 느릴 수 있을까?' },
      { id: 'resident-state', title: '실행 중 memory는 어디에서 늘어날까?' },
      { id: 'app-runtime', title: '앱은 artifact를 어떤 순서로 실행할까?' },
      { id: 'thermal-release', title: '어떤 device trace가 있어야 배포할까?' },
    ],
    component: () => import('@/pages/articles/ai/on-device-llm-runtime'),
  },
  {
    slug: 'efficient-inference-on-device',
    title: '효율 추론과 On-device AI: parameter보다 이동 byte를 보라',
    subcategory: 'ai-llm-efficiency-budget',
    summary: '양자화·native low-bit·KV cache·MTP·speculative decoding·CPU/GPU/NPU 배치를 하나의 latency와 memory budget으로 읽는다.',
    level: '중급',
    estimatedMinutes: 42,
    prerequisites: ['Transformer decode가 token을 하나씩 반복한다는 이해', 'byte·bandwidth·latency의 차이'],
    learningPath: 'ai-llm-on-device-runtime',
    sections: [
      { id: 'budget-first', title: '왜 FLOPs보다 이동 byte가 먼저일까?' },
      { id: 'weight-precision', title: '양자화와 native low-bit는 무엇이 다른가?' },
      { id: 'token-parallelism', title: 'MTP와 speculative decoding은 시간을 어떻게 줄일까?' },
      { id: 'device-stack', title: 'CPU·GPU·NPU에는 무엇을 배치할까?' },
      { id: 'measurement', title: '실제 속도를 어떤 숫자로 검증할까?' },
      { id: 'small-model', title: '4B·9B 배포 설계는 어디서 시작할까?' },
    ],
    component: () => import('@/pages/articles/ai/efficient-inference-on-device'),
  },
  {
    slug: 'llm-disaggregated-serving',
    title: 'Disaggregated LLM Serving: Prefill·Decode와 KV 이동의 경계',
    subcategory: 'ai-llm-serving-runtime',
    summary: '평균 tokens/s가 아니라 TTFT·TPOT SLO에서 시작해 prefill/decode 분리, KV handoff, cache-aware routing과 배포 gate를 계산한다.',
    level: '중급',
    estimatedMinutes: 44,
    prerequisites: ['Transformer가 prefill 뒤 token을 순차 decode한다는 이해', 'byte와 bit, bandwidth와 latency의 차이'],
    learningPath: 'ai-llm-serving-engine',
    sections: [
      { id: 'slo-first', title: '왜 평균 tokens/s로는 사용자를 설명할 수 없을까?' },
      { id: 'phase-pressure', title: 'Prefill과 decode는 무엇을 두고 경쟁할까?' },
      { id: 'kv-handoff', title: '분리하면 어떤 KV 이동 빚이 생길까?' },
      { id: 'routing-state', title: 'Router는 load와 재사용 state를 어떻게 함께 볼까?' },
      { id: 'aggregation-boundary', title: '언제 한 pool이 더 나을까?' },
      { id: 'release-gate', title: '어떤 증거가 있어야 production에 올릴까?' },
    ],
    component: () => import('@/pages/articles/ai/llm-disaggregated-serving'),
  },
  {
    slug: 'speech-audio-models',
    title: 'Speech · Audio AI: 무엇부터 읽어야 할까?',
    subcategory: 'ai-speech-audio',
    summary: '하나의 음성 증상을 경계 시각으로 분해해 interaction, generation, recognition, representation 중 첫 고장 책임을 고르고 필요한 기반까지만 내려가는 경로 허브다.',
    level: '입문',
    estimatedMinutes: 20,
    prerequisites: [],
    learningPath: 'ai-speech-audio-current-first',
    sections: [
      { id: 'why-split', title: '현재 음성 제품과 네 실패 책임' },
      { id: 'boundary-trace', title: '경계 시각으로 첫 고장 찾기' },
      { id: 'route', title: '네 갈래 학습 경로' },
      { id: 'entry-choice', title: '내 질문에는 어디서 시작해야 할까?' },
    ],
    component: () => import('@/pages/articles/ai/speech-audio-models'),
  },
  {
    slug: 'realtime-duplex-voice-systems',
    title: 'Realtime Duplex Voice Systems: 듣고 말하고 멈추는 시스템',
    subcategory: 'ai-speech-audio-interaction',
    learningPath: 'ai-speech-audio-current-first',
    summary: 'GPT-Live와 Moshi를 출발점으로 continuous interaction, barge-in cancellation, background delegation, WebRTC와 release evidence를 한 실행 trace로 연결한다.',
    level: '중급',
    estimatedMinutes: 36,
    prerequisites: ['음성이 시간에 따라 도착하는 stream이라는 이해'],
    sections: [
      { id: 'current-top', title: '2026년의 상단: 모델에서 production voice agent로' },
      { id: 'continuous-policy', title: '대화는 token 생성 위의 interaction policy다' },
      { id: 'interruption-cancel', title: 'Barge-in을 end-to-end로 어떻게 취소할까?' },
      { id: 'delegation', title: '빠른 대화와 깊은 추론을 어떻게 나눌까?' },
      { id: 'human-handoff', title: '언제 사람에게 소유권을 넘길까?' },
      { id: 'media-latency', title: 'WebRTC와 first-audio budget' },
      { id: 'release-evidence', title: '좋은 demo를 release evidence로 바꾸기' },
    ],
    component: () => import('@/pages/articles/ai/realtime-duplex-voice-systems'),
  },
  {
    slug: 'paper-moshi-2024',
    title: 'Moshi (2024): 두 음성 Stream에서 160ms 대화가 나오기까지',
    subcategory: 'ai-speech-audio-interaction',
    learningPath: 'ai-speech-audio-current-first',
    summary: 'Mimi 12.5Hz codec, Temporal·Depth Transformer, Inner Monologue와 acoustic delay를 한 forward pass와 원문 ablation으로 복원한다.',
    level: '심화',
    estimatedMinutes: 54,
    prerequisites: ['음성이 시간에 따라 도착하는 stream이라는 이해', '다음 token을 앞의 token에 조건화한다는 이해'],
    sections: [
      { id: 'two-stream-dialogue', title: 'Full-duplex의 두 Stream' },
      { id: 'mimi-codec-clock', title: 'Mimi의 12.5Hz Codec Clock' },
      { id: 'temporal-depth-hierarchy', title: 'Temporal·Depth 생성 축' },
      { id: 'inner-monologue-delay', title: 'Inner Monologue와 Delay' },
      { id: 'source-evidence', title: '원문 Ablation과 수치' },
      { id: 'limits-current-handoff', title: '한계와 현재 시스템 Handoff' },
    ],
    component: () => import('@/pages/articles/ai/paper-moshi-2024'),
  },
  {
    slug: 'native-speech-generation',
    title: 'Native Speech Generation: 의미에서 말소리까지',
    subcategory: 'ai-speech-audio-generation',
    learningPath: 'ai-speech-audio-generation',
    summary: 'Cascade와 native speech path, Thinker–Talker, acoustic codebook, first-packet schedule과 음성 품질·안전 평가를 분리해 읽는다.',
    level: '중급',
    estimatedMinutes: 32,
    prerequisites: ['sequence model이 앞의 state를 조건으로 다음 출력을 만든다는 이해'],
    sections: [
      { id: 'two-system-contracts', title: 'Cascade와 native path의 계약' },
      { id: 'codec-language-model', title: 'Speech LM의 acoustic code 예측' },
      { id: 'thinker-talker', title: 'Thinker와 Talker의 책임 분리' },
      { id: 'streaming-schedule', title: 'First packet과 문장 전체 품질' },
      { id: 'generation-evaluation', title: '내용·음질·화자·표현·시간 평가' },
    ],
    component: () => import('@/pages/articles/ai/native-speech-generation'),
  },
  {
    slug: 'speech-recognition-objectives',
    title: 'Speech Recognition Objectives: 소리와 글자를 맞추는 법',
    subcategory: 'ai-speech-audio-recognition',
    learningPath: 'ai-speech-audio-recognition',
    summary: '긴 acoustic frame과 짧은 transcript를 정렬하는 CTC·RNN-T·attention objective를 partial stability와 endpointing까지 연결한다.',
    level: '중급',
    estimatedMinutes: 34,
    prerequisites: ['확률을 여러 가능한 경로에 배분할 수 있다는 이해'],
    sections: [
      { id: 'alignment-problem', title: '어느 frame이 어느 글자인가?' },
      { id: 'ctc', title: 'CTC의 blank와 경로 합산' },
      { id: 'rnnt', title: 'RNN-T의 시간·출력 lattice' },
      { id: 'encoder-decoder', title: 'Attention encoder-decoder' },
      { id: 'partial-and-endpoint', title: 'Partial transcript와 endpoint' },
      { id: 'objective-decision', title: 'Objective 선택과 검증' },
    ],
    component: () => import('@/pages/articles/ai/speech-recognition-objectives'),
  },
  {
    slug: 'audio-representation-neural-codecs',
    title: 'Audio Representation · Neural Codec: 파형을 모델의 단위로',
    subcategory: 'ai-speech-audio-representation',
    learningPath: 'ai-speech-audio-representation',
    summary: 'Sampling, STFT·mel, learned latent, residual vector quantization과 bitrate를 통해 파형이 streaming token이 되는 과정을 계산한다.',
    level: '중급',
    estimatedMinutes: 32,
    prerequisites: ['Sampling·주파수와 convolution의 기초 직관', '복소수·로그·벡터 norm과 argmin의 기초 직관'],
    sections: [
      { id: 'representation-contract', title: '표현은 무엇을 보존해야 할까?' },
      { id: 'frames-spectrum', title: 'Frame·STFT·mel이 시간과 주파수를 나누는 법' },
      { id: 'learned-and-discrete', title: 'Learned latent와 discrete code' },
      { id: 'rvq-bitrate', title: 'RVQ와 codec bitrate 계산' },
      { id: 'streaming-release', title: 'Streaming codec release gate' },
    ],
    component: () => import('@/pages/articles/ai/audio-representation-neural-codecs'),
  },
  {
    slug: 'world-model-physical-ai',
    title: 'World Model · Physical AI: 무엇을 예측해야 행동할 수 있을까?',
    subcategory: 'ai-world-models',
    learningPath: 'ai-world-model-current-first',
    summary: 'Cosmos 3, Genie 3, V-JEPA 2와 VLA를 입력·예측 target·action grounding·증거로 구분하고 필요한 세 판단 글을 고르는 current-first 허브다.',
    level: '입문',
    estimatedMinutes: 18,
    prerequisites: [],
    sections: [
      { id: 'why-split', title: '왜 하나의 world model 글로는 부족할까?' },
      { id: 'current-contracts', title: '현재 모델을 입력·출력·증거로 읽기' },
      { id: 'route', title: '현재 연구에서 기반으로 내려가는 네 단계' },
      { id: 'entry-choice', title: '내 질문에는 어디서 시작해야 할까?' },
    ],
    component: () => import('@/pages/articles/ai/world-model-physical-ai'),
  },
  {
    slug: 'predictive-world-representations',
    title: 'Predictive World Representations: pixel이 아니라 변화의 구조를 예측한다',
    subcategory: 'ai-world-models',
    learningPath: 'ai-world-model-current-first',
    summary: 'Observation과 hidden state를 구분하고, masked latent prediction·EMA target·temporal representation이 배우는 것과 action causality의 경계를 읽는다.',
    level: '중급',
    estimatedMinutes: 38,
    prerequisites: ['image·video를 patch token과 latent vector로 바꿀 수 있다는 이해'],
    sections: [
      { id: 'observation-not-state', title: 'Camera frame과 physical state의 차이' },
      { id: 'prediction-target', title: 'Pixel과 latent target의 차이' },
      { id: 'jepa-objective', title: 'JEPA의 context·target prediction' },
      { id: 'temporal-state', title: '시간 정보와 object permanence' },
      { id: 'action-free-boundary', title: '관찰 변화와 intervention의 경계' },
      { id: 'evaluation-transfer', title: 'Representation transfer 검증' },
    ],
    component: () => import('@/pages/articles/ai/predictive-world-representations'),
  },
  {
    slug: 'paper-vjepa2-2025',
    title: '논문 재구성 · V-JEPA 2: Video에서 Zero-shot Robot Planning까지 (2025)',
    subcategory: 'ai-world-models',
    learningPath: 'ai-world-model-vjepa2-source',
    summary: 'Action-free video pretraining, 7D DROID action post-training, latent CEM·MPC와 두 lab robot evidence를 원문 수치와 한계까지 복원한다.',
    level: '심화',
    estimatedMinutes: 68,
    prerequisites: ['Video patch와 latent representation', 'Robot pose와 delta action', 'L1 distance와 sampling'],
    sections: [
      { id: 'research-question', title: 'Action 없는 video에서 planning으로' },
      { id: 'action-free-pretraining', title: 'Masked representation pretraining' },
      { id: 'action-conditioned-training', title: '16 frame·15 action post-training' },
      { id: 'latent-planning', title: 'Image-goal CEM·MPC' },
      { id: 'evidence', title: 'Representation·robot·planner 증거' },
      { id: 'limits', title: 'Camera·horizon·goal 한계' },
      { id: 'handoff', title: '일반 world-model 설계로' },
    ],
    component: () => import('@/pages/articles/ai/paper-vjepa2-2025'),
  },
  {
    slug: 'action-conditioned-world-dynamics',
    title: 'Action-Conditioned World Dynamics: 행동이 미래를 어떻게 바꾸는가',
    subcategory: 'ai-world-models',
    learningPath: 'ai-world-model-current-first',
    summary: 'Action의 좌표·단위·timestamp, forward·inverse·joint conditional direction과 teacher forcing·rollout objective를 실제 trajectory 계약으로 연결한다.',
    level: '중급',
    estimatedMinutes: 42,
    prerequisites: ['observation과 learned representation의 차이', 'pose가 reference frame에 따라 달라진다는 직관'],
    sections: [
      { id: 'intervention-contract', title: '관찰 예측에서 intervention model로' },
      { id: 'coordinate-contract', title: 'Action의 좌표·단위·시간' },
      { id: 'generation-directions', title: 'Forward·inverse·joint mode' },
      { id: 'training-objectives', title: 'Teacher forcing과 rollout loss' },
      { id: 'uncertainty-ood', title: '가능한 미래와 OOD action' },
      { id: 'transfer-evidence', title: '새 camera·gripper transfer' },
    ],
    component: () => import('@/pages/articles/ai/action-conditioned-world-dynamics'),
  },
  {
    slug: 'world-model-planning-closed-loop',
    title: 'World Model Planning · Closed Loop: 예측을 실제 행동으로 닫는다',
    subcategory: 'ai-world-models',
    learningPath: 'ai-world-model-current-first',
    summary: 'Goal energy, CEM, receding-horizon MPC, uncertainty·constraint·transition residual과 real closed-loop evidence를 하나의 실행 trace로 연결한다.',
    level: '심화',
    estimatedMinutes: 44,
    prerequisites: ['action-conditioned transition을 여러 step rollout할 수 있다는 이해'],
    sections: [
      { id: 'model-not-planner', title: 'World model과 planner의 책임 분리' },
      { id: 'goal-and-cost', title: 'Goal latent와 safety cost' },
      { id: 'cem-search', title: 'CEM 후보 행동 탐색' },
      { id: 'mpc-belief', title: 'MPC와 부분 관측 갱신' },
      { id: 'ambiguity-exploitation', title: 'Goal ambiguity와 model exploitation' },
      { id: 'evidence-release', title: 'Real closed-loop release evidence' },
    ],
    component: () => import('@/pages/articles/ai/world-model-planning-closed-loop'),
  },
];
