import type { Article } from '../types';

export const openModelArticles: Article[] = [
  {
    slug: 'open-image-video-models',
    title: '2026 오픈 이미지·비디오 제작: 목표에서 모델·실행 경로 고르기',
    subcategory: 'ai-open-models-overview',
    summary: '한국어 typography, identity 편집, style 탐색과 5초 영상이라는 제작 목표에서 현재 공식 모델 근거를 좁히고 Image/Video branch, 재현, 예산과 적응 경로를 고릅니다.',
    level: '입문',
    estimatedMinutes: 34,
    prerequisites: ['이미지 생성 모델이 prompt를 받아 결과를 만든다는 직관'],
    learningPath: 'ai-open-image-current-first',
    learningPaths: ['ai-open-video-current-first'],
    sections: [
      { id: 'overview', title: '최신 이름보다 제작 목표를 먼저 고른다' },
      { id: 'model-map', title: '이미지 모델은 서로 다른 문제를 전면에 놓는다' },
      { id: 'video-map', title: '영상은 이미지 위에 시간 계약을 추가한다' },
      { id: 'selection', title: '두 branch는 따로 시작하고 증거 계약에서 합류한다' },
      { id: 'practice', title: '이 글을 읽고 설계할 비교 실험' },
    ],
    component: () => import('@/pages/articles/ai/open-image-video-models'),
  },
  {
    slug: 'stable-diffusion-open-models',
    title: 'Stable Diffusion 내부 구현: SD1.x, SDXL, SD3.5를 텐서 흐름으로 읽기',
    subcategory: 'ai-open-models-sd',
    summary: 'Stable Diffusion을 checkpoint 이름이 아니라 prompt encoding, latent denoising, scheduler, VAE decode의 실행 흐름으로 읽고 U-Net 계열과 MMDiT 계열의 차이를 연결합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['Diffusion이 noise를 단계적으로 제거한다는 직관', 'VAE latent 공간', 'Attention과 tensor shape의 기초'],
    learningPath: 'ai-open-model-sd',
    sections: [
      { id: 'overview', title: 'Stable Diffusion은 checkpoint 하나가 아니다' },
      { id: 'ldm-pipeline', title: 'Latent Diffusion 구현 흐름' },
      { id: 'tensor-shapes', title: 'Tensor shape로 읽기' },
      { id: 'unet-internals', title: 'U-Net 내부 구조' },
      { id: 'conditioning', title: 'Prompt, negative prompt, CFG' },
      { id: 'sdxl', title: 'SDXL 구조' },
      { id: 'sd3', title: 'SD3/SD3.5 구조' },
      { id: 'control-editing', title: 'ControlNet, IP-Adapter, Inpaint' },
      { id: 'finetuning', title: 'Fine-tuning target' },
      { id: 'debugging', title: '구현 관점 디버깅' },
    ],
    component: () => import('@/pages/articles/ai/stable-diffusion-open-models'),
  },
  {
    slug: 'krea-2-foundation-model',
    title: 'Krea 2 내부 구조: 넓은 Style 분포에서 RAW·Turbo까지',
    subcategory: 'ai-open-models-krea',
    summary: 'Krea 2를 aesthetic 순위가 아니라 data curation, single-stream DiT, resolution curriculum, post-training과 RAW→Turbo artifact handoff로 읽습니다.',
    level: '심화',
    estimatedMinutes: 62,
    prerequisites: ['오픈 이미지 모델 Runtime', 'DiT에서 text·image condition이 결합되는 직관'],
    learningPath: 'ai-open-model-krea',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: '한 장의 정답보다 탐색할 수 있는 분포' },
      { id: 'distribution-goal', title: '유효한 Style 방향이 남는다는 것' },
      { id: 'data-captioning', title: '분포를 만드는 Data와 Caption' },
      { id: 'architecture', title: 'Diffusion 목적의 Architecture Ablation' },
      { id: 'text-features', title: 'Qwen3-VL Multi-layer Feature' },
      { id: 'curriculum', title: '256→512→1024 학습 순서' },
      { id: 'post-training', title: 'SFT·Preference·RL Reward' },
      { id: 'raw-turbo', title: 'RAW에서 학습하고 Turbo에서 실행' },
      { id: 'release-evaluation', title: 'Release·License·Evaluation Gate' },
      { id: 'takeaway', title: 'Lifecycle로 기억하기' },
    ],
    component: () => import('@/pages/articles/ai/krea-2-foundation-model'),
  },
  {
    slug: 'z-image',
    title: 'Z-Image 내부 구조: 효율형 Single-Stream DiT 이미지 모델',
    subcategory: 'ai-open-models-z-image',
    summary: 'Z-Image를 샘플 순위가 아니라 data curation, S3-DiT token 흐름, 단계적 학습, Turbo·Edit 변형과 실제 runtime 비용으로 분해합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['오픈 이미지 모델 Runtime', 'DiT와 latent diffusion의 직관', 'Attention token과 VRAM 기초'],
    learningPath: 'ai-open-model-z-image',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'artifact-boundary', title: '공개 Artifact와 예정 변형' },
      { id: 't2i-token-path', title: '현재 T2I Tensor Path' },
      { id: 'base-turbo', title: 'Base와 Turbo의 NFE 계약' },
      { id: 'evidence-ledger', title: '결과를 소유하는 Evidence' },
      { id: 'verification-stop', title: '공개 경계에서 멈추기' },
    ],
    component: () => import('@/pages/articles/ai/z-image'),
  },
  {
    slug: 'ideogram-4-typography-layout',
    title: 'Ideogram 4 내부 구조: Typography·Layout을 납품 계약으로',
    subcategory: 'ai-open-models-ideogram',
    summary: 'Ideogram 4를 structured caption, bbox·palette control, Qwen3-VL 13-layer feature, 34-block single-stream DiT, flow runtime과 배포 권리로 분해합니다.',
    level: '심화',
    estimatedMinutes: 56,
    prerequisites: ['오픈 이미지 모델 Runtime', '공개 weight·API·license를 구분하는 직관'],
    learningPath: 'ai-open-model-ideogram',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'overview', title: '글자를 잘 그리는 모델보다 납품 시스템' },
      { id: 'input-contract', title: 'Structured Caption 계약' },
      { id: 'spatial-contract', title: '0–1000 Bounding Box' },
      { id: 'text-encoder', title: 'Qwen3-VL 13-layer Feature' },
      { id: 'single-stream', title: '34-block Single-stream DiT' },
      { id: 'flow-runtime', title: 'Euler·CFG·VAE Runtime' },
      { id: 'runtime-license', title: '2K·Weight·Commercial 경계' },
      { id: 'release-state', title: '현재 기능과 Layer Roadmap' },
      { id: 'evaluation', title: '다섯 납품 Gate' },
      { id: 'takeaway', title: 'Brief가 살아남는 경로' },
    ],
    component: () => import('@/pages/articles/ai/ideogram-4-typography-layout'),
  },
  {
    slug: 'illustrious-xl',
    title: 'Illustrious XL v1.1: 상속·변경·실험 근거 분리하기',
    subcategory: 'ai-open-models-illustrious',
    summary: 'SDXL에서 상속한 실행 계약, v1.1 카드가 밝힌 checkpoint delta와 직접 검증해야 할 tag·LoRA·merge 가설을 분리합니다.',
    level: '중급',
    estimatedMinutes: 44,
    prerequisites: ['Stable Diffusion 구현 기준선', 'LoRA가 weight 변화량을 더한다는 직관'],
    learningPath: 'ai-open-model-illustrious',
    mathAnnotations: true,
    visualSystem: 'technical',
    sections: [
      { id: 'evidence-layers', title: '상속·명시·실험의 세 층' },
      { id: 'inherited-runtime', title: '상속한 SDXL Runtime' },
      { id: 'v11-delta', title: 'v1.1 카드가 말한 Delta' },
      { id: 'controlled-workflow', title: '통제된 Prompt·Adapter 실험' },
      { id: 'regression-stop', title: 'Regression과 Stop Rule' },
    ],
    component: () => import('@/pages/articles/ai/illustrious-xl'),
  },
  {
    slug: 'image-model-runtime',
    title: '이미지 생성은 어떻게 한 장을 만드는가: Prompt에서 Pixel까지',
    subcategory: 'ai-open-models-overview',
    summary: '글과 참고 이미지를 읽고, 작은 작업 공간에서 그림을 여러 번 고친 뒤, 실제 pixel로 펼치는 순서를 실패 원인과 함께 따라갑니다.',
    level: '중급',
    estimatedMinutes: 44,
    prerequisites: ['어떤 이미지 결과를 실패라고 볼지 말할 수 있으면 충분합니다'],
    learningPath: 'ai-open-image-current-first',
    sections: [
      { id: 'overview', title: '한 장은 다섯 계약을 지나 만들어진다' },
      { id: 'prompt-encoding', title: 'Prompt와 reference가 조건이 되는 과정' },
      { id: 'latent-scheduler', title: 'Latent와 noise path' },
      { id: 'denoiser', title: 'Denoiser의 prediction contract' },
      { id: 'conditioning', title: 'Guidance·reference·LoRA의 개입 위치' },
      { id: 'vae-postprocess', title: 'VAE와 postprocess' },
      { id: 'debugging', title: '실패를 소유한 stage 찾기' },
      { id: 'takeaway', title: '다음 글로 넘길 계약' },
    ],
    component: () => import('@/pages/articles/ai/image-model-runtime'),
  },
  {
    slug: 'video-model-runtime',
    title: '비디오 생성은 어떻게 움직임을 이어 만드는가: 한 장에서 시간축까지',
    subcategory: 'ai-open-models-overview',
    summary: '좋은 그림을 여러 장 붙이는 것과 같은 대상을 자연스럽게 움직이게 만드는 것의 차이에서 시작해, 시간 기억과 소리 맞춤까지 따라갑니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['이미지 한 장이 만들어지는 순서(서두에서 다시 설명합니다)'],
    learningPath: 'ai-open-video-current-first',
    sections: [
      { id: 'overview', title: 'Video는 image runtime에 시간 상태를 추가한다' },
      { id: 'latent-video', title: '시간과 공간을 함께 압축한다' },
      { id: 'conditioning', title: 'T2V·I2V·V2V·Audio의 관측 계약' },
      { id: 'denoising', title: 'Motion과 detail이 복원되는 과정' },
      { id: 'postprocess', title: 'Decode 뒤 시간 일관성' },
      { id: 'memory', title: '24GB 실행 주장을 검증하는 법' },
      { id: 'debugging', title: '시간 실패를 좁히는 법' },
    ],
    component: () => import('@/pages/articles/ai/video-model-runtime'),
  },
  {
    slug: 'open-model-community-workflows',
    title: 'ComfyUI·Diffusers Workflow 감사: Graph를 재현 가능한 Run으로',
    subcategory: 'ai-open-models-overview',
    summary: 'Node graph, model artifact, custom code, input transform, runtime과 sampling state를 하나의 replay manifest로 묶습니다.',
    level: '중급',
    estimatedMinutes: 36,
    prerequisites: ['Image 또는 Video runtime branch 하나'],
    learningPath: 'ai-open-image-current-first',
    learningPaths: ['ai-open-video-current-first'],
    sections: [
      { id: 'overview', title: 'Workflow는 실행 가능한 주장이다' },
      { id: 'comfyui', title: 'ComfyUI port와 hidden dependency' },
      { id: 'diffusers', title: 'Diffusers component와 API snapshot' },
      { id: 'community-audit', title: '커뮤니티 Workflow 채택 감사' },
      { id: 'reproducibility', title: 'Manifest와 원인 추적 가능성' },
    ],
    component: () => import('@/pages/articles/ai/open-model-community-workflows'),
  },
  {
    slug: 'open-model-workflow-parameters',
    title: '워크플로우 수치와 생성 모델 이론: steps·CFG·sigma·해상도·프레임',
    subcategory: 'ai-open-models-overview',
    summary: 'UI 숫자를 복사 가능한 preset이 아니라 denoiser call, noise path, guidance와 latent token·memory budget으로 해석합니다.',
    level: '중급',
    estimatedMinutes: 34,
    prerequisites: ['Image 또는 Video runtime', '재현 가능한 workflow manifest'],
    learningPath: 'ai-open-image-current-first',
    learningPaths: ['ai-open-video-current-first'],
    sections: [
      { id: 'overview', title: '수치는 UI 옵션이 아니라 수학의 노브다' },
      { id: 'steps-sigma', title: 'steps·sampler·sigma' },
      { id: 'cfg-guidance', title: 'CFG·guidance scale' },
      { id: 'shape-cost', title: '해상도·프레임·latent shape' },
      { id: 'model-differences', title: '모델별로 같은 수치가 다르게 먹히는 이유' },
    ],
    component: () => import('@/pages/articles/ai/open-model-workflow-parameters'),
  },
  {
    slug: 'open-model-finetuning-theory',
    title: '오픈 이미지·비디오 모델 적응: Control에서 LoRA·Full Fine-tuning까지',
    subcategory: 'ai-open-models-overview',
    summary: '가장 작은 충분한 개입을 고르고 trainable scope, target·retention data, memory, regression과 release gate로 adaptation을 판정합니다.',
    level: '심화',
    estimatedMinutes: 52,
    prerequisites: ['Image 또는 Video runtime', 'Workflow manifest와 parameter budget'],
    learningPath: 'ai-open-image-current-first',
    learningPaths: ['ai-open-video-current-first'],
    sections: [
      { id: 'overview', title: '왜 방법론부터 알아야 하는가' },
      { id: 'mental-model', title: 'Full fine-tuning의 수학적 감각' },
      { id: 'model-anatomy', title: '모델별로 알아야 할 내부 장기' },
      { id: 'data-design', title: '데이터셋 설계' },
      { id: 'training-stack', title: '학습 스택' },
      { id: 'model-playbooks', title: '구조별 작업 지시 플레이북' },
      { id: 'agent-brief', title: '작업자에게 이렇게 시켜야 한다' },
      { id: 'failure-modes', title: '실패 모드와 판정 기준' },
      { id: 'takeaway', title: '핵심 정리' },
      { id: 'implementation-handoff', title: '판정 뒤 필요한 구현' },
    ],
    component: () => import('@/pages/articles/ai/open-model-finetuning-theory'),
  },
  {
    slug: 'comfyui-workflow-map',
    title: 'ComfyUI 실행 계약: Workflow를 Queue·Trace·Replay하는 법',
    subcategory: 'ai-open-models-comfyui',
    summary: '공유 workflow를 graph 그림으로 끝내지 않고 dependency inventory, API snapshot, prompt_id, 실행 trace와 replay bundle로 닫습니다.',
    level: '입문',
    estimatedMinutes: 28,
    prerequisites: ['생성 모델 pipeline의 입력과 출력', 'JSON과 파일 hash의 기초'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'Workflow는 실행 계약이다' },
      { id: 'execution-contract', title: 'Import와 실행 전 검증' },
      { id: 'queue-boundary', title: 'Queue가 만드는 시간 경계' },
      { id: 'replay-artifacts', title: '재현 artifact' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-workflow-map'),
  },
  {
    slug: 'comfyui-core-graph',
    title: 'ComfyUI 타입 그래프: Dependency·Cache·Partial Recompute 읽기',
    subcategory: 'ai-open-models-comfyui',
    summary: 'MODEL, CLIP, VAE, CONDITIONING, LATENT와 IMAGE의 type 경계를 따라 실행 순서, cache invalidation과 consumer 기반 디버깅을 이해합니다.',
    level: '입문',
    estimatedMinutes: 30,
    prerequisites: ['ComfyUI workflow snapshot과 prompt_id', '함수의 입력·출력 개념'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'Core graph를 읽는 두 축' },
      { id: 'type-contracts', title: '여섯 타입의 책임' },
      { id: 'execution-order', title: 'Dependency 실행 순서' },
      { id: 'cache-modes', title: 'Cache, Never, Bypass' },
      { id: 'debugging', title: 'Consumer 역추적' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-core-graph'),
  },
  {
    slug: 'comfyui-loaders-gguf',
    title: 'ComfyUI 모델 부품 로딩: Architecture·Precision·GGUF 계약',
    subcategory: 'ai-open-models-comfyui',
    summary: 'Checkpoint와 분리형 denoiser·text encoder·VAE를 component manifest로 만들고 BF16, FP8, GGUF의 memory·runtime 경계를 검증합니다.',
    level: '중급',
    estimatedMinutes: 34,
    prerequisites: ['ComfyUI typed graph', 'Parameter와 byte 단위의 기초'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'Loader는 component factory다' },
      { id: 'component-contract', title: 'Component manifest' },
      { id: 'precision-budget', title: 'Precision과 memory 하한' },
      { id: 'loader-decision', title: 'Loader 선택 순서' },
      { id: 'failure-modes', title: 'Component 실패 모드' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-loaders-gguf'),
  },
  {
    slug: 'comfyui-ksampler-parameters',
    title: 'ComfyUI Sampling Trace: Seed·CFG·Scheduler를 실험하는 법',
    subcategory: 'ai-open-models-comfyui',
    summary: 'KSampler를 추천값 모음이 아니라 latent noise trajectory 실행기로 이해하고 한 변수씩 통제하는 sampling 실험을 설계합니다.',
    level: '중급',
    estimatedMinutes: 34,
    prerequisites: ['검증된 MODEL·CLIP·VAE component', 'Latent와 denoising의 기초'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'KSampler는 trajectory 실행기다' },
      { id: 'parameter-roles', title: '여섯 값의 책임' },
      { id: 'cfg', title: 'CFG의 계산 이유' },
      { id: 'schedule-denoise', title: 'Scheduler와 Denoise' },
      { id: 'tuning-protocol', title: 'Controlled sweep' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-ksampler-parameters'),
  },
  {
    slug: 'comfyui-lora-control-conditioning',
    title: 'ComfyUI 조건 라우팅: LoRA·ControlNet·Image Adapter의 차이',
    subcategory: 'ai-open-models-comfyui',
    summary: 'Prompt embedding, LoRA weight patch, ControlNet 구조 신호와 reference embedding의 서로 다른 경로를 consumer 역추적과 ablation으로 검증합니다.',
    level: '중급',
    estimatedMinutes: 36,
    prerequisites: ['ComfyUI sampling baseline', 'MODEL과 CONDITIONING type 경계'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: '조건의 계산 경로' },
      { id: 'lora', title: 'LoRA weight patch' },
      { id: 'control-reference', title: 'Control과 Reference' },
      { id: 'ablation', title: '조건별 ablation' },
      { id: 'conflicts', title: '조건 충돌 디버깅' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-lora-control-conditioning'),
  },
  {
    slug: 'comfyui-edit-models-flux-qwen',
    title: 'ComfyUI 이미지 편집: FLUX.2와 Qwen-Image-Edit-2511 연결법',
    subcategory: 'ai-open-models-comfyui',
    summary: '이미지 편집을 txt2img와 구분하고 semantic·appearance·mask·reference의 소유 경로를 추적하며 FLUX.2, Qwen-Image-Edit-2511과 mask inpaint를 선택합니다.',
    level: '중급',
    estimatedMinutes: 32,
    prerequisites: ['ComfyUI node와 edge의 기본 조작', 'VAE encode/decode', 'Latent diffusion의 denoising 직관', 'Prompt·LoRA·Control의 condition routing'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'Edit 모델은 txt2img가 아니다' },
      { id: 'flux-kontext', title: 'FLUX.2와 Kontext의 현재 위치' },
      { id: 'qwen-image-edit', title: 'Qwen-Image-Edit-2511' },
      { id: 'workflow-wiring', title: 'ComfyUI 연결 패턴' },
      { id: 'model-choice', title: '언제 어떤 모델을 쓰는가' },
      { id: 'failure-modes', title: '실패 모드' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-edit-models-flux-qwen'),
  },
  {
    slug: 'comfyui-upscale-postprocess',
    title: 'ComfyUI 후처리 책임: Latent Pass·Upscale·Detailer 분리',
    subcategory: 'ai-open-models-comfyui',
    summary: 'Base, latent second pass, pixel upscale, detailer와 tile stage를 분리하고 crop 좌표와 earliest failure를 추적합니다.',
    level: '중급',
    estimatedMinutes: 32,
    prerequisites: ['ComfyUI sampling과 image editing', 'IMAGE·LATENT·MASK 좌표 경계'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: '후처리는 독립 생성 단계다' },
      { id: 'stage-ownership', title: 'Stage별 책임' },
      { id: 'coordinates', title: 'Crop 좌표 변환' },
      { id: 'tiling', title: 'Tiling과 전역 일관성' },
      { id: 'release-evidence', title: 'Before·After 증거' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-upscale-postprocess'),
  },
  {
    slug: 'comfyui-custom-nodes-ops',
    title: 'ComfyUI 노드 운영: Version·보안·Replay·Rollback',
    subcategory: 'ai-open-models-comfyui',
    summary: 'Custom node를 공급망 dependency로 다루고 package identity, version pin, 격리 검증, snapshot과 replay bundle로 운영합니다.',
    level: '중급',
    estimatedMinutes: 30,
    prerequisites: ['Stage별 output과 earliest-failure report', 'ComfyUI workflow replay artifact', 'Package version과 dependency의 기초'],
    learningPath: 'ai-open-model-comfyui',
    sections: [
      { id: 'overview', title: 'Custom node의 운영 책임' },
      { id: 'package-gates', title: '설치 전 여섯 gate' },
      { id: 'missing-node', title: 'Missing node 복구' },
      { id: 'threat-model', title: 'Dependency threat model' },
      { id: 'release-bundle', title: 'Replay와 rollback' },
    ],
    component: () => import('@/pages/articles/ai/comfyui-custom-nodes-ops'),
  },
];
