import type { Article } from "../types";

export const genArticles: Article[] = [
  {
    slug: "generative-theory",
    title: "생성 모델의 출발점: observation·distribution·평가",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "Observation과 distribution" },
      { id: "tractability", title: "직접 계산할 연산" },
      { id: "evaluation", title: "Likelihood와 평가 경계" },
      { id: "family-map", title: "다음 학습 경로" },
    ],
    component: () => import("@/pages/articles/ai/generative-theory"),
  },
  {
    slug: "autoregressive-generative-models",
    title: "자기회귀 생성 모델: prefix conditional을 곱하는 이유",
    subcategory: "ai-generative",
    sections: [
      { id: "sequence", title: "Token·prefix·conditional" },
      { id: "factorization", title: "Chain-rule factorization" },
      { id: "train-sample", title: "Training과 sampling" },
      { id: "boundary", title: "Ordering·exposure·latency" },
    ],
    component: () =>
      import("@/pages/articles/ai/autoregressive-generative-models"),
  },
  {
    slug: "latent-variable-generative-models",
    title: "잠재변수 생성 모델: 숨은 원인·marginalization·ELBO",
    subcategory: "ai-generative",
    sections: [
      { id: "latent-cause", title: "Latent cause와 네 분포" },
      { id: "marginalization", title: "숨은 원인을 가중해 합하기" },
      { id: "elbo", title: "Approximate posterior와 ELBO" },
      { id: "paper-aevb", title: "AEVB 근거와 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/latent-variable-generative-models"),
  },
  {
    slug: "normalizing-flows",
    title: "Normalizing flow: 가역 좌표와 density 보정",
    subcategory: "ai-generative",
    sections: [
      { id: "bijection", title: "Base·bijection·Jacobian" },
      { id: "change-of-variables", title: "Volume을 보정하는 이유" },
      { id: "failure-boundary", title: "가역성의 대가" },
      { id: "paper-real-nvp", title: "Real NVP 근거와 경계" },
    ],
    component: () => import("@/pages/articles/ai/normalizing-flows"),
  },
  {
    slug: "adversarial-density-ratios",
    title: "GAN density ratio: discriminator가 비교하는 것",
    subcategory: "ai-generative",
    sections: [
      { id: "two-sources", title: "Real과 generated source" },
      { id: "optimal-ratio", title: "Optimal discriminator ratio" },
      { id: "training-boundary", title: "이론과 실제 training" },
      { id: "paper-gan", title: "Original GAN 근거와 경계" },
    ],
    component: () => import("@/pages/articles/ai/adversarial-density-ratios"),
  },
  {
    slug: "score-based-generative-models",
    title: "Score 기반 생성 모델: local direction에서 diffusion까지",
    subcategory: "ai-generative",
    sections: [
      { id: "score-field", title: "Density와 score field" },
      { id: "gaussian-score", title: "Gaussian score의 minus" },
      { id: "noise-score", title: "Noise predictor와 score" },
      { id: "papers-score", title: "NCSN·DDPM 근거와 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/score-based-generative-models"),
  },
  {
    slug: "vae",
    title: "VAE: latent variable과 ELBO를 함께 이해하기",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "VAE가 푸는 문제" },
      { id: "ae-vs-vae", title: "Autoencoder와 VAE" },
      { id: "reparam-trick", title: "Encoder·decoder와 reparameterization" },
      { id: "vae-loss", title: "ELBO와 likelihood" },
      { id: "training", title: "학습과 failure mode" },
      { id: "applications", title: "변형 모델과 latent diffusion" },
    ],
    component: () => import("@/pages/articles/ai/vae"),
  },
  {
    slug: "gan",
    title: "GAN의 출발점: generator와 discriminator의 분포 게임",
    subcategory: "ai-generative",
    sections: [
      { id: "distribution", title: "Latent에서 sample distribution으로" },
      { id: "discriminator", title: "Real·fake를 구별하는 함수" },
      { id: "objective", title: "Generator가 받는 학습 신호" },
      { id: "boundary", title: "Density·encoder·수렴의 경계" },
    ],
    component: () => import("@/pages/articles/ai/gan"),
  },
  {
    slug: "gan-training-dynamics",
    title: "GAN training dynamics: 두 optimizer가 만드는 움직이는 game",
    subcategory: "ai-generative",
    sections: [
      { id: "alternating", title: "D step과 G step" },
      { id: "gradient-path", title: "Detach와 gradient path" },
      { id: "game-dynamics", title: "회전·TTUR·local convergence" },
      { id: "mode-collapse", title: "Mode collapse를 진단하는 법" },
    ],
    component: () => import("@/pages/articles/ai/gan-training-dynamics"),
  },
  {
    slug: "gan-wasserstein-critics",
    title: "Wasserstein GAN: Lipschitz critic과 안정화 제약",
    subcategory: "ai-generative",
    sections: [
      { id: "lipschitz", title: "Lipschitz 제약의 형태" },
      { id: "wasserstein-dual", title: "Transport distance를 critic으로 읽기" },
      { id: "gradient-penalty", title: "Sampled input-gradient penalty" },
      { id: "spectral-normalization", title: "Weight operator norm 제약" },
    ],
    component: () => import("@/pages/articles/ai/gan-wasserstein-critics"),
  },
  {
    slug: "gan-conditional-evaluation",
    title: "Conditional GAN 평가: 조건·품질·coverage를 분리하기",
    subcategory: "ai-generative",
    sections: [
      { id: "conditioning", title: "Condition을 양쪽에 주는 이유" },
      { id: "fid", title: "Feature mean·covariance와 FID" },
      { id: "precision-recall", title: "품질과 coverage 분리" },
      { id: "evaluation-protocol", title: "재현 가능한 평가 계약" },
    ],
    component: () => import("@/pages/articles/ai/gan-conditional-evaluation"),
  },
  {
    slug: "diffusion-models",
    title: "Diffusion 기초: noise pair·prediction target·score",
    subcategory: "ai-generative",
    sections: [
      { id: "corruption", title: "Training pair와 sampling loop" },
      { id: "schedule", title: "Gaussian cumulative schedule" },
      { id: "target", title: "Prediction target와 backbone" },
      { id: "loss-derivation", title: "L_simple의 ELBO 유도" },
      { id: "score", title: "Noise–score identity" },
    ],
    component: () => import("@/pages/articles/ai/diffusion-models"),
  },
  {
    slug: "diffusion-continuous-time",
    title: "Continuous diffusion: reverse SDE·flow ODE·solver",
    subcategory: "ai-generative",
    sections: [
      { id: "reverse-sde", title: "Reverse-time SDE" },
      { id: "probability-flow", title: "Probability-flow ODE" },
      { id: "flow-matching", title: "Conditional flow matching" },
      { id: "solver-budget", title: "Solver error와 NFE" },
    ],
    component: () => import("@/pages/articles/ai/diffusion-continuous-time"),
  },
  {
    slug: "latent-diffusion-guidance",
    title: "Latent diffusion: component pipeline·CFG·release gate",
    subcategory: "ai-generative",
    sections: [
      { id: "compression", title: "Latent bottleneck" },
      { id: "pipeline", title: "Component contract" },
      { id: "guidance", title: "Classifier-free guidance" },
      { id: "evaluation", title: "Conditional release gate" },
    ],
    component: () => import("@/pages/articles/ai/latent-diffusion-guidance"),
  },
  {
    slug: "visual-representation-tokenizers",
    title: "Visual representation: reconstruction latent와 semantic feature",
    subcategory: "ai-generative",
    sections: [
      { id: "objective", title: "무엇을 보존하도록 학습했는가" },
      { id: "reconstruction", title: "Reconstruction latent와 복원 상한" },
      { id: "semantic", title: "Semantic representation과 RAE" },
      { id: "world-state", title: "World-state 표현의 추가 조건" },
    ],
    component: () =>
      import("@/pages/articles/ai/visual-representation-tokenizers"),
  },
  {
    slug: "diffusion-transformer-architecture",
    title: "Diffusion Transformer: latent patch·conditioning·stream 구조",
    subcategory: "ai-generative",
    sections: [
      { id: "latent-patches", title: "Latent patch와 token 비용" },
      { id: "conditioned-block", title: "Time modulation과 condition" },
      { id: "multimodal-streams", title: "Single·dual·joint stream" },
      { id: "runtime-boundary", title: "NFE와 runtime 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/diffusion-transformer-architecture"),
  },
  {
    slug: "modern-image-model-stack",
    title: "현대 이미지 생성 모델: component stack에서 world model 경계까지",
    subcategory: "ai-generative",
    sections: [
      { id: "system-map", title: "전체 component map" },
      { id: "component-contract", title: "Tensor·정보 interface" },
      { id: "training-stack", title: "Data·caption·post-training" },
      { id: "world-model-boundary", title: "시간·행동·state transition" },
    ],
    component: () => import("@/pages/articles/ai/modern-image-model-stack"),
  },
  {
    slug: "diffusion-language-models",
    title: "Diffusion LLM: MASK corruption·반복 복원·block diffusion",
    subcategory: "ai-generative",
    sections: [
      { id: "ar-vs-diffusion", title: "AR과 masked diffusion" },
      { id: "forward-objective", title: "Forward mask와 objective" },
      { id: "reverse-sampling", title: "Parallel unmasking sampler" },
      { id: "runtime-blocks", title: "KV cache와 block diffusion" },
      { id: "world-model-boundary", title: "World model과의 경계" },
    ],
    component: () => import("@/pages/articles/ai/diffusion-language-models"),
  },
  {
    slug: "image-video-lora-architecture",
    title: "Image·Video LoRA: host architecture와 adapter 범위",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "같은 LoRA, 다른 host architecture" },
      { id: "image-scope", title: "Image denoiser의 target 범위" },
      { id: "video-scope", title: "공간·시간·교차모달 target" },
      { id: "training-evaluation", title: "Clip 학습과 평가 계약" },
    ],
    component: () =>
      import("@/pages/articles/ai/image-video-lora-architecture"),
  },
  {
    slug: "multi-component-finetuning-vram",
    title: "학습 때는 배우지 않는 부품까지 VRAM에 올라갑니다",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "추론과 학습은 올려 두는 집합이 다릅니다" },
      {
        id: "residency-set",
        title: "동결은 배우지 않는다는 뜻이지 없어도 된다는 뜻이 아닙니다",
        subsections: [{ id: "frozen-forward", title: "매 스텝 호출되기 때문에 내릴 수 없습니다" }],
      },
      {
        id: "component-budget",
        title: "부품마다 따로 세고 항목마다 따로 곱합니다",
        subsections: [{ id: "worked-budget", title: "예시 구성으로 합을 내 봅니다" }],
      },
      { id: "adapter-scope", title: "어댑터가 줄이는 항목은 하나뿐입니다" },
      { id: "precompute-offload", title: "바뀌지 않는 계산은 미리 해 두고 부품을 내립니다" },
      { id: "budget-gate", title: "어느 항이 넘치는지부터 가릅니다" },
    ],
    component: () => import("@/pages/articles/ai/multi-component-finetuning-vram"),
  },
  {
    slug: "generative-measurement-controls",
    title: "계측기도 답을 아는 입력으로 먼저 검증해야 합니다",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "계측기를 검증하지 않으면 결과 표가 조용히 비어 있습니다" },
      {
        id: "identity-metric",
        title: "얼굴 심판은 두 단계이고 앞 단계가 조용히 실패합니다",
        subsections: [{ id: "threshold-choice", title: "임계값은 남남 쌍의 분포에서 나옵니다" }],
      },
      { id: "style-coverage", title: "사진으로 학습된 심판을 그림에 쓰려면 범위를 먼저 재야 합니다" },
      { id: "roundtrip-floor", title: "마스크 밖 변화량은 모델이 아니라 오토인코더를 재고 있었습니다" },
      { id: "instrument-controls", title: "계측기마다 답을 아는 입력을 하나씩 같이 돌립니다" },
      { id: "measurement-gate", title: "숫자를 쓰기 전에 네 가지를 답할 수 있어야 합니다" },
    ],
    component: () => import("@/pages/articles/ai/generative-measurement-controls"),
  },
  {
    slug: "masked-edit-verb-routing",
    title: "\"편집\"은 한 동작이 아니라 요구가 서로 다른 여섯 동작입니다",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "요구가 다른 여섯 동작으로 먼저 나눕니다" },
      { id: "model-disposition", title: "같은 요청에 모델마다 일관된 성향이 나타납니다" },
      { id: "hand-hint", title: "손으로 그은 선을 살리는 모델은 하나뿐이었습니다" },
      { id: "mask-polarity", title: "마스크를 넓히는 방향이 동작마다 반대입니다" },
      { id: "style-scale", title: "같은 동작의 수치가 그림체에 따라 두 배씩 달라집니다" },
      { id: "routing-gate", title: "모델 이름은 사용자도 에이전트도 고르지 않습니다" },
    ],
    component: () => import("@/pages/articles/ai/masked-edit-verb-routing"),
  },
  {
    slug: "removal-is-not-inpainting",
    title: "지우기는 인페인팅의 한 종류가 아닙니다",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "일곱 모델이 같은 방식으로 실패했습니다" },
      { id: "absence-not-drawable", title: "디노이저에게 마스크를 채우라고 하면 채웁니다" },
      {
        id: "propagation",
        title: "물건을 지어낼 방법이 없다는 것이 곧 능력입니다",
        subsections: [{ id: "strength-cliff", title: "세기 손잡이에 중간이 없는 지점이 있습니다" }],
      },
      { id: "tool-contract", title: "무엇을 그릴지 말하지 않는 것이 작동하는 이유입니다" },
      { id: "two-stage-rejected", title: "싼 모델로 지우고 다시 그리는 조합은 기각했습니다" },
      { id: "remove-gate", title: "모델을 바꾸기 전에 도구의 종류를 먼저 의심합니다" },
    ],
    component: () => import("@/pages/articles/ai/removal-is-not-inpainting"),
  },
  {
    slug: "in-context-lora",
    title: "In-Context LoRA: reference·target을 한 context로 이어붙이기",
    subcategory: "ai-generative",
    sections: [
      { id: "overview", title: "새 아키텍처 대신 self-attention 재사용" },
      { id: "training", title: "Clean reference·noised target 학습" },
      { id: "applications", title: "ID-LoRA — identity guidance와 two-stage 생성" },
    ],
    component: () => import("@/pages/articles/ai/in-context-lora"),
  },
];
