import type { Article } from "../types";

export const agentArticles: Article[] = [
  /* ── 1. 프롬프트 기초 ── */
  {
    slug: "prompt-engineering",
    title: "프롬프트 요청 계약: 목표·근거·검증·회귀 평가",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "요청의 조건과 출력 형식 설계하기" },
      { id: "anti-patterns", title: "안티패턴 & 트러블슈팅" },
    ],
    component: () => import("@/pages/articles/ai/prompt-engineering"),
  },
  {
    slug: "prompt-reasoning",
    title: "Reasoning prompting: CoT·Self-consistency·Verifier",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Reasoning·answer·verifier 경계" },
      { id: "chain-of-thought", title: "Reasoning path와 외부 검증" },
      { id: "paper-chain-of-thought", title: "Chain-of-Thought 원 논문" },
      { id: "paper-self-consistency", title: "Self-consistency 원 논문" },
      { id: "paper-cot-faithfulness", title: "Faithfulness 경계" },
    ],
    component: () => import("@/pages/articles/ai/prompt-reasoning"),
  },
  {
    slug: "prompt-few-shot",
    title: "Few-shot prompting: Demonstration·순서·Context 비용",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Demonstration 한 개의 형태" },
      { id: "few-shot", title: "In-context demonstration의 형태" },
      { id: "paper-gpt3-few-shot", title: "GPT-3 few-shot 원 논문" },
      { id: "paper-calibrate-before-use", title: "순서·label bias 보정" },
    ],
    component: () => import("@/pages/articles/ai/prompt-few-shot"),
  },
  {
    slug: "prompt-structured-output",
    title: "Structured output: Parse·Schema·Domain·Fallback",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "문자열에서 record로" },
      { id: "structured-output", title: "Output record와 네 단계 validator" },
      { id: "output-paths", title: "Prompt·constraint·repair 경로" },
      { id: "output-measurement", title: "실패율·tail latency 측정" },
      { id: "output-release", title: "Bounded fallback과 release" },
    ],
    component: () => import("@/pages/articles/ai/prompt-structured-output"),
  },
  {
    slug: "xml-prompting",
    title: "XML 프롬프팅: 역할 경계·파싱·보안",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "XML 태그가 해결하는 문제와 한계" },
      { id: "basic-tags", title: "Root·중첩·escaping부터 시작하기" },
      { id: "advanced-tags", title: "여러 문서·예시와 runtime 경계" },
      { id: "parsing", title: "Parser·schema·의미 검증" },
      { id: "best-practices", title: "형식 비교와 배포 전 평가" },
    ],
    component: () => import("@/pages/articles/ai/xml-prompting"),
  },

  /* ── 2. 컨텍스트 & 도구 연결 ── */
  {
    slug: "context-engineering",
    title: "Context state 기초: 저장소에서 이번 generation까지",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Context와 저장소 구분" },
      { id: "context-state", title: "Select와 serialize" },
      { id: "curation", title: "Curation lifecycle" },
      { id: "boundary", title: "다음 학습 경계" },
    ],
    component: () => import("@/pages/articles/ai/context-engineering"),
  },
  {
    slug: "context-instruction-boundaries",
    title: "Context 권한 경계: Instruction · Data · Runtime",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "세 책임 층 정의" },
      { id: "three-layers", title: "Prompt priority와 capability" },
      { id: "attack-path", title: "Schema·authorization·policy gate" },
      { id: "release", title: "Effect path release test" },
    ],
    component: () =>
      import("@/pages/articles/ai/context-instruction-boundaries"),
  },
  {
    slug: "context-provenance-freshness",
    title: "Context provenance: Source · Revision · Freshness",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Fragment receipt 정의" },
      { id: "fragment-shape", title: "Typed fragment 형태" },
      { id: "conflict", title: "Version conflict 해결" },
      { id: "release", title: "Reverse trace와 stale fixture" },
    ],
    component: () => import("@/pages/articles/ai/context-provenance-freshness"),
  },
  {
    slug: "agent-memory-lifecycle",
    title: "Agent memory lifecycle: State · Memory · Artifact",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "상태 수명 분리" },
      { id: "lifetimes", title: "Owner·source·expiry·delete" },
      { id: "compaction", title: "Compaction fidelity" },
      { id: "resume", title: "Resume test" },
    ],
    component: () => import("@/pages/articles/ai/agent-memory-lifecycle"),
  },
  {
    slug: "context-window-optimization",
    title: "Context window: Token budget · Position · Cache",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Capacity와 utilization 구분" },
      { id: "budget", title: "Source별 token 장부" },
      { id: "position", title: "Position evaluation" },
      { id: "cache", title: "Stable prefix cache" },
    ],
    component: () => import("@/pages/articles/ai/context-window-optimization"),
  },
  {
    slug: "mcp-protocol",
    title: "MCP 기초: Host · Client · Server와 Stateless Core",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "MCP가 해결하는 연결 문제" },
      { id: "roles", title: "Host · Client · Server 한 역할씩" },
      { id: "request-envelope", title: "Stateless request와 explicit handle" },
      { id: "next-map", title: "Primitive · transport · 운영으로 확장" },
    ],
    component: () => import("@/pages/articles/ai/mcp-protocol"),
  },
  {
    slug: "mcp-primitives",
    title: "MCP Primitives: Tool · Resource · Prompt",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Primitive를 control 방식으로 구분" },
      { id: "three-primitives", title: "Tool · Resource · Prompt의 형태" },
      { id: "tool-contract", title: "Schema · result · input required" },
      { id: "list-cache", title: "목록 cache와 실행 권한 분리" },
    ],
    component: () => import("@/pages/articles/ai/mcp-primitives"),
  },
  {
    slug: "mcp-transports",
    title: "MCP Transports: stdio · Streamable HTTP",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Message와 운반 경로 분리" },
      { id: "stdio", title: "Local child process와 pipe" },
      { id: "streamable-http", title: "Remote endpoint와 routing" },
      { id: "lifetimes", title: "Response · cancel · subscription 수명" },
    ],
    component: () => import("@/pages/articles/ai/mcp-transports"),
  },
  {
    slug: "mcp-server-operations",
    title: "MCP Server 운영: Authorization · Retry · Receipt",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Proposal에서 effect까지" },
      { id: "authorization", title: "네 단계 trust gate" },
      { id: "retry-receipt", title: "Operation ID와 effect receipt" },
      { id: "release", title: "Extension · failure · rollback" },
    ],
    component: () => import("@/pages/articles/ai/mcp-server-operations"),
  },

  /* ── 3. 에이전트 패턴 & 하네스 ── */
  {
    slug: "agent-loop-foundations",
    title: "Agent Loop 기초: State · Action · Observation · Exit",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "State transition의 네 대상" },
      { id: "transition", title: "Proposal에서 effect까지" },
      { id: "observation-contract", title: "Typed observation" },
      { id: "exit-states", title: "Terminal state 분리" },
    ],
    component: () => import("@/pages/articles/ai/agent-loop-foundations"),
  },
  {
    slug: "agent-plan-replanning",
    title: "Agent Plan: Artifact · Replanning · Reflection",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Executable plan state" },
      { id: "executable-plan", title: "Task와 artifact receipt" },
      { id: "replanning", title: "영향 범위 invalidation" },
      { id: "reflection", title: "Feedback 기반 다음 trial" },
    ],
    component: () => import("@/pages/articles/ai/agent-plan-replanning"),
  },
  {
    slug: "agent-delegation-contracts",
    title: "Agent Delegation: Artifact · Manager · Handoff",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "위임의 네 소유권" },
      { id: "delegation-contract", title: "Typed delegation" },
      { id: "manager-handoff", title: "User state owner" },
      { id: "parallel-merge", title: "Parallel merge 조건" },
    ],
    component: () => import("@/pages/articles/ai/agent-delegation-contracts"),
  },
  {
    slug: "agent-extension-boundaries",
    title: "Agent 확장 경계: Hook · Skill · Guardrail · Verifier",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "네 decision owner" },
      { id: "hook", title: "Event callback 경계" },
      { id: "skill-guardrail", title: "지식과 권한 분리" },
      { id: "verifier", title: "Artifact·trajectory·effect" },
    ],
    component: () => import("@/pages/articles/ai/agent-extension-boundaries"),
  },
  {
    slug: "llm-harness",
    title: "LLM harness: model proposal과 runtime enforcement",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "모델과 하네스의 책임 경계" },
      { id: "proposal-runtime", title: "Capability와 authority" },
      { id: "feedback-loop", title: "Effect receipt와 observation" },
      { id: "paper-effective-agents", title: "Workflow·agent 근거 경계" },
    ],
    component: () => import("@/pages/articles/ai/llm-harness"),
  },
  {
    slug: "agent-run-contract",
    title: "Agent run contract: context·capability·artifact·recovery",
    subcategory: "ai-agents",
    sections: [
      { id: "contract", title: "Objective와 acceptance" },
      { id: "context-capability", title: "Context path와 capability" },
      { id: "artifact-continuity", title: "Versioned artifact continuity" },
      { id: "recovery-handoff", title: "Recovery와 handoff" },
    ],
    component: () => import("@/pages/articles/ai/agent-run-contract"),
  },
  {
    slug: "agent-verification",
    title: "Agent verification: artifact·trajectory·effect gate",
    subcategory: "ai-agents",
    sections: [
      { id: "layers", title: "Layered verifier" },
      { id: "trajectory-effect", title: "네 acceptance gate" },
      { id: "regression", title: "Trace와 regression fixture" },
      { id: "release", title: "Judge와 human review" },
    ],
    component: () => import("@/pages/articles/ai/agent-verification"),
  },
  {
    slug: "harness-failure-ablation",
    title: "Harness failure ablation: 고장 난 layer 찾기",
    subcategory: "ai-agents",
    sections: [
      { id: "failure-layer", title: "Replay fixture와 failure layer" },
      { id: "classify", title: "실패 원인 분류" },
      { id: "ablation", title: "Single-change paired test" },
      { id: "paper-harness-ablation", title: "Long-running harness 근거" },
    ],
    component: () => import("@/pages/articles/ai/harness-failure-ablation"),
  },
  {
    slug: "agent-control-boundaries",
    title: "Agent control boundary: workflow·loop·checkpoint",
    subcategory: "ai-agents",
    sections: [
      { id: "workflow-agent", title: "Workflow와 agent loop" },
      { id: "selection", title: "불확실성과 effect 위험" },
      { id: "loop-authority", title: "두 loop의 권한 분리" },
      { id: "paper-loop-control", title: "운영 어휘의 근거 경계" },
    ],
    component: () => import("@/pages/articles/ai/agent-control-boundaries"),
  },
  {
    slug: "agent-code-mode",
    title: "Code Mode: Tool 왕복을 Program으로 접는 실행 패턴",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Tool 왕복과 Program IR" },
      { id: "tool-discovery", title: "선택적 Schema Loading" },
      { id: "data-reduction", title: "Local Data와 Token 경계" },
      { id: "decision", title: "실행 방식 선택" },
    ],
    component: () => import("@/pages/articles/ai/agent-code-mode"),
  },
  {
    slug: "code-mode-runtime-contracts",
    title: "Code Mode Runtime: Capability·Result·Effect 계약",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Deterministic Control Flow" },
      { id: "capability", title: "Capability Binding" },
      { id: "result-contract", title: "Result Disclosure" },
      { id: "effects", title: "Partial Effect와 Retry" },
    ],
    component: () => import("@/pages/articles/ai/code-mode-runtime-contracts"),
  },
  {
    slug: "agent-sandbox-security",
    title: "Container 보안 기초: Process · Namespace · Cgroup · Attack Path",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Container보다 먼저 Process" },
      { id: "namespace", title: "보이는 자원: Namespace" },
      { id: "cgroup", title: "쓸 수 있는 양: Cgroup" },
      { id: "attack-path", title: "Signal에서 Impact까지" },
      { id: "container-root", title: "Container Root 경계" },
    ],
    component: () => import("@/pages/articles/ai/agent-sandbox-security"),
  },
  {
    slug: "sandbox-runtime-isolation",
    title: "Sandbox Runtime 격리: Syscall · Seccomp · gVisor · Kata",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "System Call 처리 경로" },
      { id: "seccomp", title: "Seccomp는 Filter" },
      { id: "application-kernel", title: "gVisor Application Kernel" },
      { id: "guest-kernel", title: "Kata Guest Kernel" },
      { id: "runtime-spectrum", title: "Runtime Acceptance Gate" },
    ],
    component: () => import("@/pages/articles/ai/sandbox-runtime-isolation"),
  },
  {
    slug: "sandbox-gpu-isolation",
    title: "GPU Sandbox 격리: Ioctl Proxy · VFIO · IOMMU",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "GPU Device 경계" },
      { id: "ioctl-proxy", title: "nvproxy Ioctl 중개" },
      { id: "vfio", title: "VFIO Device 할당" },
      { id: "compatibility", title: "Support Generation과 Release" },
    ],
    component: () => import("@/pages/articles/ai/sandbox-gpu-isolation"),
  },
  {
    slug: "sandbox-deployment-controls",
    title: "Sandbox 배포 통제: Identity · Egress · Storage · Release",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "서로 대신하지 않는 네 Gate" },
      { id: "service-account-token", title: "ServiceAccount와 Token" },
      { id: "rbac", title: "RBAC Authorization" },
      { id: "egress", title: "Egress Allowlist" },
      { id: "writable-surface", title: "Writable Surface 수명" },
      { id: "control-matrix", title: "Workload Control Matrix" },
    ],
    component: () => import("@/pages/articles/ai/sandbox-deployment-controls"),
  },
  {
    slug: "skills-anatomy",
    title: "Agent Skills 해부: Trigger에서 Distribution까지",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Tool · Skill · Plugin 역할" },
      { id: "format", title: "SKILL.md와 선택 resource" },
      { id: "loading", title: "Progressive disclosure와 trigger" },
      { id: "execution", title: "Permission을 보존하는 실행 흐름" },
      { id: "registry", title: "Codex scope와 plugin distribution" },
    ],
    component: () => import("@/pages/articles/ai/skills-anatomy"),
  },

  /* ── 4. 프레임워크 & 실제 구현체 ── */
  {
    slug: "agent-frameworks",
    title: "에이전트 프레임워크: 직접 구현부터 Durable Runtime까지",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "직접 Tool Loop와 Framework 경계" },
      { id: "langchain", title: "State·Checkpoint·Interrupt" },
      { id: "comparison", title: "요구사항과 복구 비용으로 비교하기" },
    ],
    component: () => import("@/pages/articles/ai/agent-frameworks"),
  },
  {
    slug: "claude-code",
    title: "Claude Code: Workspace·Context·Permission·Hooks",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Coding Agent Harness와 실행 Loop" },
      { id: "agent-architecture", title: "Context·Delegation·Extension 경계" },
      { id: "tools-permissions", title: "Tool·Permission·Hook·Checkpoint" },
    ],
    component: () => import("@/pages/articles/ai/claude-code"),
  },
  {
    slug: "qwen-korean-consistency",
    title: "Qwen 한국어 일관성: 진단·Smoothing·Post-training",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "언어 혼용을 먼저 진단하기" },
      { id: "prompt-level", title: "Prompt policy의 역할과 한계" },
      {
        id: "smoothie-qwen",
        title: "Smoothie-Qwen: lm_head row scaling",
      },
      { id: "rl-approach", title: "SFT와 Oracle-guided Dr.GRPO" },
      { id: "runtime-guard", title: "Checker·Judge·Bounded retry" },
      { id: "decision-matrix", title: "Paired evaluation과 배포 결정" },
    ],
    component: () => import("@/pages/articles/ai/qwen-korean-consistency"),
  },
  {
    slug: "openclaw-assistant",
    title: "OpenClaw: Gateway·Session·Runtime·Sandbox 경계",
    subcategory: "ai-agents",
    sections: [
      { id: "overview", title: "Inbound event와 Gateway 책임" },
      { id: "routing-sessions", title: "Binding·Agent·Session 격리" },
      { id: "runtime-resources", title: "Provider·Model·Runtime·Resource" },
      { id: "security-reply", title: "Tool policy·Sandbox·Reply route" },
    ],
    component: () => import("@/pages/articles/ai/openclaw-assistant"),
  },
];
