import type { Article } from '../types';

export const llmArchitectureArticles: Article[] = [
  {
    slug: 'llm-architecture-gallery',
    title: 'LLM 아키텍처: 최신 모델을 바닥부터 읽는 법',
    subcategory: 'ai-llm-architectures-overview',
    sections: [
      { id: 'current-anchor', title: 'LLM 구조에서 2026 변화까지' },
      { id: 'foundation-contract', title: '먼저 고정할 Transformer 계약' },
      { id: 'architecture-fingerprint', title: '처음 보는 모델을 숫자로 판독하기' },
      { id: 'five-milestones', title: '최소 다섯 구조의 기준 계보' },
      { id: 'branch-reading', title: '병목별 학습 경로' },
      { id: 'paper-protocol', title: '새 모델 논문을 읽는 여섯 질문' },
    ],
    summary: '다음 token을 만드는 공통 흐름부터 시작해 GPT-2, Llama, Gemma, DeepSeek, Kimi를 거쳐 2026년의 입력·깊이 변화까지 문맥·용량·상태 비용으로 연결합니다.',
    level: '중급',
    estimatedMinutes: 56,
    prerequisites: ['신경망의 hidden vector와 residual', 'softmax와 행렬곱의 직관', 'Transformer attention 기초'],
    learningPath: 'ai-llm-architecture-current-first',
    mathAnnotations: true,
    component: () => import('@/pages/articles/ai/llm-architecture-gallery'),
  },
  {
    slug: 'llm-architecture-dense-transformers',
    title: 'Dense Transformer: 공통 블록에서 최신 설계까지',
    subcategory: 'ai-llm-architectures-dense',
    sections: [
      { id: 'overview', title: '현재 모델을 읽는 최소 Dense 기준' },
      { id: 'decoder-block', title: '두 residual과 projection 비용' },
      { id: 'gpt2-flow', title: 'GPT-2 XL 최소 기준점' },
      { id: 'model-catalog', title: '다섯 번의 설계 전환' },
      { id: 'takeaway', title: '처음 보는 모델 판독 순서' },
    ],
    summary: '두 residual 식과 projection 비용을 먼저 고정하고 GPT-2, Llama, Qwen, Gemma, OLMo가 안정성·KV·긴 문맥 병목을 어떻게 바꿨는지 시대순으로 추적합니다.',
    level: '중급',
    estimatedMinutes: 72,
    prerequisites: ['Transformer attention 기초', 'embedding과 residual connection'],
    learningPath: 'ai-llm-architecture-current-first',
    component: () => import('@/pages/articles/ai/llm-architecture-dense-transformers'),
  },
  {
    slug: 'llm-architecture-kv-long-context',
    title: 'KV Cache와 Long Context: GQA, MLA, SWA, NoPE/RoPE 실전 해석',
    subcategory: 'ai-llm-architectures-kv-context',
    sections: [
      { id: 'overview', title: '긴 문맥을 두 병목으로 읽기' },
      { id: 'prefill-decode', title: 'Prefill과 decode가 다른 이유' },
      { id: 'kv-layout', title: 'MHA → GQA → MLA' },
      { id: 'local-global', title: 'SWA와 global layer' },
      { id: 'lineage', title: '최소 설계 계보' },
      { id: 'takeaway', title: '현재 모델 판독 순서' },
    ],
    summary: 'Prefill과 decode를 나눈 뒤 batch-aware KV byte, GQA·MLA 저장 좌표, local/global cache와 직접·간접 가시 범위를 계산하고 현재 모델을 다시 판독합니다.',
    level: '심화',
    estimatedMinutes: 68,
    prerequisites: ['Dense Transformer block', 'Q·K·V attention', 'GPU 메모리의 기초'],
    learningPath: 'ai-llm-architecture-current-first',
    component: () => import('@/pages/articles/ai/llm-architecture-kv-long-context'),
  },
  {
    slug: 'llm-architecture-sparse-moe',
    title: 'Sparse MoE: expert bank, routing, capacity, GPU 통신',
    subcategory: 'ai-llm-architectures-moe',
    sections: [
      { id: 'overview', title: '수백 B 모델에서 켜지는 길' },
      { id: 'expert-ledger', title: 'Expert parameter 장부' },
      { id: 'routing-capacity', title: 'Routing·capacity·통신' },
      { id: 'lineage', title: '다섯 번의 최소 설계 전환' },
      { id: 'takeaway', title: '새 MoE 모델 판독 순서' },
    ],
    summary: 'Gated expert의 matrix shape부터 total bank와 token당 활성 경로를 복원하고, Top-k capacity·overflow·no-drop straggler·expert parallel 통신을 최소 논문 계보와 함께 판독합니다.',
    level: '심화',
    estimatedMinutes: 70,
    prerequisites: ['Dense Transformer block', 'softmax와 Top-k', 'GPU 간 통신의 기초'],
    learningPath: 'ai-llm-architecture-current-first',
    component: () => import('@/pages/articles/ai/llm-architecture-sparse-moe'),
  },
  {
    slug: 'llm-architecture-hybrid-linear',
    title: 'Hybrid·Linear Attention: state 메모리부터 Qwen3.6까지',
    subcategory: 'ai-llm-architectures-hybrid',
    sections: [
      { id: 'overview', title: 'Qwen3.6에서 시작하기' },
      { id: 'memory-ledger', title: 'KV와 state 메모리 장부' },
      { id: 'recurrence-duality', title: 'Recurrence와 SSD' },
      { id: 'delta-update', title: 'Delta·gate·KDA' },
      { id: 'parallel-runtime', title: 'Decode와 chunkwise 학습' },
      { id: 'lineage', title: '최소 설계 계보' },
      { id: 'takeaway', title: '현재 보고서 판독법' },
    ],
    summary: 'Qwen3.6의 3:1 hybrid에서 출발해 KV와 고정 state의 byte, Mamba·SSD의 두 실행 형태, Delta 덮어쓰기, Gated DeltaNet·KDA와 FlashQLA까지 계산합니다.',
    level: '심화',
    estimatedMinutes: 72,
    prerequisites: ['KV cache와 full attention 비용', 'Matrix outer product', '이전 state와 현재 입력으로 다음 state를 만든다는 recurrence 직관', 'Sparse MoE active path'],
    learningPath: 'ai-llm-architecture-current-first',
    component: () => import('@/pages/articles/ai/llm-architecture-hybrid-linear'),
  },
  {
    slug: 'research-deepseek-v3-2-2025',
    title: '실전 보고서 검산 · DeepSeek-V3.2: Sparse Attention, RL, Agent Synthesis',
    subcategory: 'ai-llm-architectures-case-study',
    sections: [
      { id: 'context', title: '보고서 이전의 세 병목과 저자 의도' },
      { id: 'claim', title: 'DSA·RL·Agent pipeline 재구성' },
      { id: 'mechanism', title: 'Indexer·Top-k·GRPO 핵심 수식' },
      { id: 'evidence', title: 'Parity·비용·Agent ablation의 경계' },
      { id: 'reproduction', title: '최소 재현과 실패 진단' },
      { id: 'legacy', title: '남는 계약과 다음 기반 델타' },
    ],
    summary: '앞의 네 구조 기반을 23쪽 기술 보고서에 적용해 DSA, stable GRPO, 1,827개 합성 환경과 context management를 수식·실행 순서·증거 한계로 검산합니다.',
    level: '심화',
    estimatedMinutes: 82,
    prerequisites: ['Dense Transformer와 KV cache', 'Sparse MoE routing', 'Hybrid·state memory의 구분'],
    learningPath: 'ai-llm-architecture-current-first',
    curriculumRole: 'core',
    component: () => import('@/pages/articles/ai/research-deepseek-v3-2-2025'),
  },
];
