import type { Article } from '../types';

export const multimodalArticles: Article[] = [
  {
    slug: 'multimodal-foundation-models-current',
    title: '통합 멀티모달 모델: 입력·출력·표현·근거부터 읽기',
    subcategory: 'ai-multimodal',
    summary: 'Gemma 4, Llama 4, Qwen3-VL, Qwen VLo, Janus-Pro, Emu3와 Transfusion을 순위표가 아니라 입력·출력 modality, visual path, objective와 증거 강도로 분해합니다.',
    level: '중급',
    estimatedMinutes: 42,
    prerequisites: ['Transformer가 token sequence를 처리한다는 이해', 'Image를 patch로 나눌 수 있다는 직관'],
    learningPath: 'ai-multimodal-current-first',
    sections: [
      { id: 'contract-first', title: '멀티모달 계약부터 펼치기' },
      { id: 'current-models', title: '현재 모델을 하나씩 읽기' },
      { id: 'deployment-transfer', title: '입력 예산과 실행 근거 계산' },
      { id: 'six-questions', title: '새 모델 판독 여섯 질문' },
      { id: 'route', title: '다음 한 글 고르기' },
    ],
    component: () => import('@/pages/articles/ai/multimodal-foundation-models-current'),
  },
  {
    slug: 'multimodal-fusion-interleaved-context',
    title: 'Multimodal Fusion: Visual Token과 Interleaved Context',
    subcategory: 'ai-multimodal',
    summary: 'Encoder·projector·resampler가 image를 visual token으로 바꾸는 순서와 patch·merge·context 장부, text·image·audio interleaving과 위치 좌표를 계산합니다.',
    level: '중급',
    estimatedMinutes: 58,
    prerequisites: ['Vision Transformer의 patch-token shape와 readout', '행렬 projection의 직관', 'Transformer context window의 의미'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'entry-pipeline', title: 'Raw input에서 backbone까지' },
      { id: 'token-ledger', title: 'Visual token 장부' },
      { id: 'fusion-topology', title: 'Early Fusion과 Cross-attention' },
      { id: 'interleaved-sequence', title: 'Interleaved sequence와 context' },
      { id: 'position-and-boundary', title: '공간·시간 위치와 근거 경계' },
    ],
    component: () => import('@/pages/articles/ai/multimodal-fusion-interleaved-context'),
  },
  {
    slug: 'video-long-context-memory',
    title: 'Long Video Memory: 시간 Token·압축·Streaming',
    subcategory: 'ai-multimodal',
    summary: '긴 영상을 시간 sampling, visual token과 KV byte로 계산하고 full·window·계층형 memory를 고른 뒤, 이해와 생성의 압축·streaming·sequence parallel 실패 조건을 최신 원문으로 검증합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['Image가 여러 visual token이 된다는 이해', 'Transformer context와 KV cache의 역할'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'why-long-video', title: '긴 영상은 무엇을 기억해야 하는가' },
      { id: 'token-budget', title: '시간을 Token과 Byte로 계산' },
      { id: 'memory-regimes', title: 'Full·Window·계층형 Memory' },
      { id: 'understanding-memory', title: '이해 모델의 Memory' },
      { id: 'generation-memory', title: '생성 모델의 Memory' },
      { id: 'training-runtime', title: '긴 Sample의 분산 실행' },
      { id: 'evaluation-release', title: '일곱 Release Gate' },
    ],
    component: () => import('@/pages/articles/ai/video-long-context-memory'),
  },
  {
    slug: 'multimodal-visual-tokenization',
    title: 'Visual Tokenization: 의미 Feature에서 복원 가능한 Code까지',
    subcategory: 'ai-multimodal',
    summary: 'CLIP형 semantic feature, continuous latent와 VQ discrete code를 분리하고 nearest code, straight-through, commitment loss와 Janus의 두 visual path를 계산합니다.',
    level: '중급',
    estimatedMinutes: 48,
    prerequisites: ['Vector 거리의 직관', 'Encoder와 decoder의 역할'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'two-representations', title: '이해와 복원이 요구하는 정보' },
      { id: 'representation-budget', title: '표현별 Token · Bit 장부' },
      { id: 'nearest-code', title: '가장 가까운 Code 선택' },
      { id: 'straight-through-loss', title: 'Straight-through와 VQ Loss' },
      { id: 'janus-decision', title: 'Janus의 두 Visual Path' },
    ],
    component: () => import('@/pages/articles/ai/multimodal-visual-tokenization'),
  },
  {
    slug: 'multimodal-unified-generation-objectives',
    title: '통합 생성 Objective: Visual AR, Diffusion과 Flow',
    subcategory: 'ai-multimodal',
    summary: 'Emu3·Janus의 visual next-token, Transfusion의 AR+diffusion과 JanusFlow를 representation, loss, generation schedule과 gradient budget으로 비교합니다.',
    level: '심화',
    estimatedMinutes: 48,
    prerequisites: ['Visual discrete code와 continuous latent의 차이', '확률과 평균제곱오차의 직관'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'one-backbone-many-losses', title: '한 Backbone과 여러 Loss' },
      { id: 'ar-objective', title: 'Discrete Visual AR' },
      { id: 'continuous-objective', title: 'Diffusion·Flow Objective' },
      { id: 'evidence-and-choice', title: 'Generation Schedule과 증거' },
    ],
    component: () => import('@/pages/articles/ai/multimodal-unified-generation-objectives'),
  },
  {
    slug: 'paper-janus-2024',
    title: '논문 재구성 · Janus: Visual Encoding을 왜 분리했는가',
    subcategory: 'ai-multimodal',
    summary: 'Janus 논문의 문제 설정, SigLIP·VQ 두 visual path, shared autoregressive objective, 세 단계 학습과 ablation의 증거 경계를 원문 순서에서 구현 가능한 구조로 복원합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['Semantic feature와 reconstructable VQ code의 차이', 'Autoregressive next-token loss의 의미'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'research-question', title: '문제 설정 · 왜 분리하는가' },
      { id: 'architecture-objective', title: '두 Visual Path와 공유 Objective' },
      { id: 'training-curriculum', title: '세 단계 학습 Curriculum' },
      { id: 'ablation-evidence', title: 'Ablation 증거와 일반화 경계' },
    ],
    component: () => import('@/pages/articles/ai/paper-janus-2024'),
  },
  {
    slug: 'janus-pro-multimodal-runtime',
    title: 'Janus-Pro Runtime: 이해와 이미지 생성 Code Path',
    subcategory: 'ai-multimodal',
    summary: '공식 repository revision을 고정하고 VLChatProcessor, visual embedding 대입, autoregressive visual code, CFG와 VQ decoder를 tensor 영수증으로 추적합니다.',
    level: '심화',
    estimatedMinutes: 66,
    prerequisites: ['Multimodal fusion의 projector·packing 계약', 'Janus 원 논문의 두 visual path', 'Visual tokenization과 VQ code', 'Autoregressive generation과 KV cache'],
    learningPath: 'ai-multimodal-current-first',
    mathAnnotations: true,
    sections: [
      { id: 'runtime-contract', title: '공식 Code의 두 실행 경로' },
      { id: 'understanding-path', title: 'Multimodal Understanding Path' },
      { id: 'generation-path', title: 'Text-to-Image Generation Path' },
      { id: 'reproduction-gates', title: '재현 영수증과 Release Gate' },
    ],
    component: () => import('@/pages/articles/ai/janus-pro-multimodal-runtime'),
  },
];
