import type { Article } from '../types';

export const vllmServingArticles: Article[] = [
  {
    slug: 'vllm-serving',
    title: 'vLLM Serving: SLO에서 KV·Scheduler까지',
    subcategory: 'ai-llm-serving-runtime',
    learningPath: 'ai-llm-serving-engine',
    summary: '대화형·배치 workload의 지표 계약에서 시작해 API Server, EngineCore, KV block, unified scheduler와 GPU worker의 소유 경계를 추적하고 네 개 심화 장부로 내려갑니다.',
    level: '중급',
    estimatedMinutes: 38,
    curriculumRole: 'core',
    visualSystem: 'technical',
    mathAnnotations: true,
    prerequisites: ['Prefill·decode와 TTFT·TPOT의 차이', '요청별 KV cache가 memory를 점유한다는 이해'],
    sections: [
      { id: 'overview', title: 'Workload와 SLO 계약' },
      { id: 'paged-attention', title: 'KV block과 admission' },
      { id: 'serving-architecture', title: '병목별 최적화와 심화 경로' },
    ],
    component: () => import('@/pages/articles/ai/vllm-serving'),
  },
  {
    slug: 'vllm-paged-attention',
    title: 'vLLM PagedAttention: token에서 물리 KV block까지',
    subcategory: 'ai-llm-serving-runtime',
    learningPath: 'ai-llm-serving-engine',
    summary: 'GQA model shape에서 KV bytes/token과 block 수를 계산하고 logical-to-physical block table, refcount, prefix cache와 pool headroom을 실제 코드까지 추적합니다.',
    level: '심화',
    estimatedMinutes: 42,
    prerequisites: ['Transformer decode와 KV cache의 역할', 'GQA의 KV head', 'byte와 GiB 단위'],
    sections: [
      { id: 'overview', title: '연속 주소가 필요 없는 이유' },
      { id: 'byte-ledger', title: 'KV byte와 block 장부' },
      { id: 'block-pool', title: 'BlockPool: 물리 블록 관리' },
      { id: 'kv-cache-manager', title: 'KVCacheManager: 할당 전략' },
      { id: 'prefix-caching', title: 'Prefix Cache와 refcount' },
      { id: 'handoff', title: 'Scheduler로 넘길 산출물' },
      { id: 'paged-attention-field-guide', title: '전체 KV Cache 설계서' },
    ],
    component: () => import('@/pages/articles/ai/vllm-paged-attention'),
  },
  {
    slug: 'vllm-scheduler',
    title: 'vLLM Scheduler: 한 GPU step의 token·KV 장부',
    subcategory: 'ai-llm-serving-runtime',
    learningPath: 'ai-llm-serving-engine',
    summary: 'Prefill과 decode의 물리 차이를 유지한 채 token budget, KV headroom, chunked prefill, admission과 preemption을 한 step plan으로 계산합니다.',
    level: '심화',
    estimatedMinutes: 44,
    prerequisites: ['PagedAttention의 block table과 free pool', 'TTFT와 TPOT의 차이'],
    sections: [
      { id: 'overview', title: 'Continuous batching 질문' },
      { id: 'step-budget', title: '한 step의 작업 계획' },
      { id: 'schedule-method', title: 'schedule() 코드 추적' },
      { id: 'prefill-decode', title: '통합 장부와 다른 물리 비용' },
      { id: 'preemption', title: 'Admission과 preemption' },
      { id: 'handoff', title: 'Verifier로 넘길 산출물' },
      { id: 'scheduler-field-guide', title: '전체 스케줄러 설계서' },
    ],
    component: () => import('@/pages/articles/ai/vllm-scheduler'),
  },
  {
    slug: 'vllm-spec-decode',
    title: 'vLLM Speculative Decoding: 제안에서 검증된 commit까지',
    subcategory: 'ai-llm-serving-runtime',
    learningPath: 'ai-llm-serving-engine',
    summary: 'Draft q와 target p의 올바른 acceptance·recovery를 계산하고 verifier당 기대 token과 실제 draft·verify 비용을 분리해 speedup을 판단합니다.',
    level: '심화',
    estimatedMinutes: 46,
    prerequisites: ['Scheduler token budget과 lookahead slot', '조건부 확률과 분포 정규화'],
    sections: [
      { id: 'overview', title: '제안과 확정의 경계' },
      { id: 'acceptance-math', title: 'Acceptance·recovery·속도' },
      { id: 'draft-verify', title: 'Draft-Verify 파이프라인' },
      { id: 'eagle-mtp', title: 'EAGLE vs Draft Model vs MTP' },
      { id: 'handoff', title: 'VLM으로 넘길 commit 경계' },
      { id: 'spec-decode-field-guide', title: '전체 Spec Decode 설계서' },
    ],
    component: () => import('@/pages/articles/ai/vllm-spec-decode'),
  },
  {
    slug: 'vllm-vlm-serving',
    title: 'vLLM VLM Serving: media 입구에서 decoder state까지',
    subcategory: 'ai-llm-serving-runtime',
    learningPath: 'ai-llm-serving-engine',
    summary: 'Media URL·UUID, processor, encoder position·cache, placeholder alignment, scheduler budget와 speculative fallback을 하나의 admission evidence로 연결합니다.',
    level: '심화',
    estimatedMinutes: 45,
    prerequisites: ['PagedAttention의 decoder KV 장부', 'Scheduler의 token·encoder budget', 'Speculative decoding의 commit 경계'],
    sections: [
      { id: 'overview', title: 'VLM serving 경계' },
      { id: 'media-contract', title: 'Media payload와 cache identity' },
      { id: 'render-preprocess', title: 'Render와 input processor' },
      { id: 'scheduler-budget', title: 'Multimodal scheduler budget' },
      { id: 'runtime-cache', title: 'Runtime cache와 speculative decode' },
      { id: 'handoff', title: 'Media admission evidence' },
      { id: 'vlm-serving-field-guide', title: '전체 VLM Serving 설계서' },
    ],
    component: () => import('@/pages/articles/ai/vllm-vlm-serving'),
  },
];
