import type { Article } from '../types';

// ── NLP & Attention ──
export const dlNlpArticles: Article[] = [
  {
    slug: 'distributional-semantics',
    title: '분산 표현: 단어를 벡터로',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: '왜 단어를 숫자로 바꿔야 하는가' },
      { id: 'distributional', title: '분포 가설과 동시발생' },
      { id: 'dimensionality', title: '차원 축소' },
      { id: 'neural-approach', title: '신경망 기반 접근' },
    ],
    component: () => import('@/pages/articles/ai/distributional-semantics'),
  },
  {
    slug: 'rnn',
    title: 'RNN: 시퀀스를 기억하는 신경망',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: '왜 시퀀스 모델이 필요한가' },
      { id: 'language-model', title: '언어 모델' },
      { id: 'architecture', title: 'RNN 구조' },
      { id: 'bptt', title: '시간 역전파 (BPTT)' },
    ],
    component: () => import('@/pages/articles/ai/rnn'),
  },
  {
    slug: 'lstm',
    title: 'LSTM: 장기 의존성을 학습하는 게이트 구조',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: 'RNN의 한계' },
      { id: 'gates', title: '게이트 메커니즘' },
      { id: 'cell-state', title: '셀 상태와 정보 흐름' },
      { id: 'variants', title: 'LSTM 변형과 GRU' },
    ],
    component: () => import('@/pages/articles/ai/lstm'),
  },
  {
    slug: 'seq2seq',
    title: 'Seq2Seq: 시퀀스를 시퀀스로 변환',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: 'Seq2Seq란' },
      { id: 'encoder', title: '인코더: 문장을 벡터로 압축' },
      { id: 'decoder', title: '디코더: 벡터에서 번역 생성' },
      { id: 'training', title: '학습: 역전파' },
      { id: 'limitations', title: '한계와 발전' },
      { id: 'attention-mechanism', title: '어텐션 메커니즘 도입' },
      { id: 'attention-computation', title: '어텐션 계산 (구체적 숫자)' },
      { id: 'attention-visualization', title: '어텐션 히트맵' },
    ],
    component: () => import('@/pages/articles/ai/seq2seq'),
  },
  {
    slug: 'attention-theory',
    title: '어텐션 메커니즘 이론: Bahdanau에서 Transformer까지',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: 'Seq2Seq 한계와 어텐션의 등장' },
      { id: 'additive', title: 'Bahdanau (Additive) Attention' },
      { id: 'multiplicative', title: 'Luong & Scaled Dot-Product' },
      { id: 'self-attention', title: 'Self-Attention & Multi-Head' },
    ],
    component: () => import('@/pages/articles/ai/attention-theory'),
  },
  {
    slug: 'tokenizer',
    title: '토크나이저: 텍스트를 토큰으로',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: '토크나이저 개요' },
      { id: 'bpe', title: 'BPE (Byte Pair Encoding)' },
      { id: 'wordpiece', title: 'WordPiece (BERT)' },
      { id: 'sentencepiece', title: 'SentencePiece & Unigram' },
      { id: 'comparison', title: '토크나이저 비교 & 한국어' },
    ],
    component: () => import('@/pages/articles/ai/tokenizer'),
  },
  {
    slug: 'transformer-architecture',
    title: 'Transformer 아키텍처',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: '개요' },
      { id: 'data-prep', title: '데이터 준비' },
      { id: 'input-embedding', title: '입력 임베딩 + 위치 인코딩' },
      { id: 'qkv-computation', title: 'Q, K, V 행렬 생성' },
      { id: 'attention-score', title: '어텐션 스코어 계산' },
      { id: 'self-attention', title: 'Self-Attention 메커니즘' },
      { id: 'multi-head', title: 'Multi-Head Attention' },
      { id: 'masked-attention', title: '마스크 어텐션 (디코더)' },
      { id: 'cross-attention', title: '크로스 어텐션 (디코더)' },
      { id: 'positional-encoding', title: 'Positional Encoding' },
      { id: 'feed-forward', title: 'Feed-Forward Network' },
      { id: 'layer-norm', title: 'Layer Normalization' },
      { id: 'linear-softmax', title: '최종 출력 (Linear + Softmax)' },
      { id: 'training', title: '학습 기법 (Warmup, AdamW)' },
      { id: 'scaling-laws', title: '스케일링 법칙 (Chinchilla)' },
      { id: 'summary', title: '정리' },
    ],
    component: () => import('@/pages/articles/ai/transformer-architecture'),
  },
  {
    slug: 'bert',
    title: 'BERT: 양방향 사전학습의 혁신',
    subcategory: 'ai-nlp',
    sections: [
      { id: 'overview', title: 'BERT 등장 배경' },
      { id: 'self-attention', title: 'Self-Attention & 특수 토큰' },
      { id: 'pre-training', title: '사전학습: MLM + NSP' },
      { id: 'fine-tuning', title: '파인튜닝 & 변형 모델' },
    ],
    component: () => import('@/pages/articles/ai/bert'),
  },
];
