import type { Article } from "../types";
import { dlNlpArticles } from "./articlesDL2";
import { dlFoundation2Articles, dlVisionArticles } from "./articlesDL3";

// ── Foundations (읽기 순서: 공통 수학 → 퍼셉트론 → 신경망 → 활성화 → 역전파 → 옵티마이저 → 목적함수) ──
export const dlFoundationArticles: Article[] = [
  {
    slug: "deep-learning-overview",
    title: "딥러닝의 출발점: 표현을 층으로 쌓는 이유",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Representation은 무엇인가" },
      { id: "shape", title: "중간 표현의 형태" },
      { id: "depth", title: "깊이가 만드는 함수 합성" },
      { id: "boundaries", title: "표현·학습·일반화의 경계" },
    ],
    component: () => import("@/pages/articles/ai/deep-learning-overview"),
  },
  {
    slug: "supervised-learning-loop",
    title: "지도학습 한 바퀴: example에서 parameter update까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Input과 target" },
      { id: "tensor-batch", title: "Tensor와 batch" },
      { id: "training-step", title: "Forward에서 update까지" },
      { id: "inference", title: "학습과 inference의 경계" },
    ],
    component: () => import("@/pages/articles/ai/supervised-learning-loop"),
  },
  {
    slug: "train-validation-test",
    title: "Train·validation·test: 데이터 역할을 섞지 않는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "세 split의 역할" },
      { id: "selection-feedback", title: "Validation feedback" },
      { id: "generalization", title: "Generalization과 gap" },
      { id: "next-protocol", title: "Cross-validation으로 넘기는 경계" },
    ],
    component: () => import("@/pages/articles/ai/train-validation-test"),
  },
  {
    slug: "math-vectors-inner-products",
    title: "벡터·내적·norm: AI 수식을 읽는 최소 선형대수",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "좌표를 하나의 대상으로 묶기" },
      { id: "vectors", title: "Scalar와 vector" },
      { id: "norm", title: "Norm과 거리" },
      { id: "dot-product", title: "Dot product와 방향" },
      { id: "projection", title: "Projection으로 성분 읽기" },
      { id: "cauchy-schwarz", title: "Cauchy–Schwarz 부등식" },
      { id: "applications", title: "퍼셉트론·attention으로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-vectors-inner-products"),
  },
  {
    slug: "math-matrices-svd",
    title: "행렬·선형변환·SVD: embedding 압축을 읽는 최소 선형대수",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "행렬을 숫자 표 이상으로 읽기" },
      { id: "matrix-map", title: "행렬과 linear map" },
      { id: "multiplication", title: "행렬 곱과 함수 합성" },
      { id: "rank-basis", title: "Rank와 orthonormal basis" },
      { id: "svd", title: "SVD의 세 단계" },
      { id: "low-rank", title: "Low-rank approximation" },
      { id: "applications", title: "Embedding·PCA로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-matrices-svd"),
  },
  {
    slug: "math-complex-numbers-oscillations",
    title: "복소수·회전·Euler 공식: Fourier 수식을 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "복소수가 회전을 기록하는 이유" },
      { id: "radians", title: "Radian과 한 바퀴" },
      { id: "unit-circle", title: "Sine·cosine과 단위원" },
      { id: "complex-plane", title: "복소수와 복소평면" },
      { id: "euler-formula", title: "Euler 공식과 회전 곱셈" },
      { id: "roots-of-unity", title: "Roots of unity" },
      { id: "applications", title: "DFT·FFT로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-complex-numbers-oscillations"),
  },
  {
    slug: "text-unicode-encoding",
    title: "문자·Unicode·UTF-8: tokenizer를 읽는 최소 텍스트 기초",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "화면의 한 글자와 저장 단위 구분" },
      { id: "bits-bytes", title: "Bit와 byte" },
      { id: "code-points", title: "Code point와 grapheme cluster" },
      { id: "utf-8", title: "UTF-8 encoding" },
      { id: "normalization", title: "Unicode normalization" },
      { id: "offsets", title: "Offset 좌표와 round-trip" },
      { id: "applications", title: "Tokenizer로 연결" },
    ],
    component: () => import("@/pages/articles/ai/text-unicode-encoding"),
  },
  {
    slug: "math-functions-composition",
    title: "함수와 합성: input→output 규칙을 읽는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Input과 output" },
      { id: "shape", title: "Domain과 codomain" },
      { id: "composition", title: "함수 합성의 실행 순서" },
      { id: "boundaries", title: "순서·shape·domain 경계" },
    ],
    component: () => import("@/pages/articles/ai/math-functions-composition"),
  },
  {
    slug: "math-functions-derivatives-gradients",
    title: "Derivative와 chain rule: local rate를 연결하는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Difference quotient와 limit" },
      { id: "derivative", title: "Derivative의 세 연산" },
      { id: "local-linearity", title: "Local linear approximation" },
      { id: "chain-rule", title: "연결된 rate를 곱하는 이유" },
      { id: "nonsmooth", title: "Subgradient와 구현 경계" },
    ],
    component: () => import("@/pages/articles/ai/math-functions-derivatives-gradients"),
  },
  {
    slug: "math-gradients-jacobians",
    title: "Gradient와 Jacobian: 여러 입력의 민감도를 묶는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "손잡이 하나씩 움직이기" },
      { id: "gradient-direction", title: "Gradient와 방향 변화율" },
      { id: "jacobian", title: "Jacobian과 JVP" },
      { id: "boundaries", title: "Gradient·JVP·VJP 경계" },
    ],
    component: () => import("@/pages/articles/ai/math-gradients-jacobians"),
  },
  {
    slug: "math-differential-equations-numerical-solvers",
    title: "미분방정식·수치적분: diffusion의 ODE·SDE를 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "변화 법칙에서 경로 만들기" },
      { id: "initial-value", title: "초기값 문제와 vector field" },
      { id: "euler-method", title: "Euler method와 오차" },
      { id: "stability", title: "Step size와 수치 안정성" },
      { id: "heun-runge-kutta", title: "Heun·Runge–Kutta" },
      { id: "ode-sde-boundary", title: "ODE와 SDE의 경계" },
      { id: "applications", title: "Diffusion·Neural ODE로 연결" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-differential-equations-numerical-solvers"),
  },
  {
    slug: "math-exponents-logarithms",
    title: "지수·로그: 확률과 정보량을 읽는 최소 수학",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "곱셈을 덧셈으로 옮기기" },
      { id: "exponents", title: "지수와 반복 배율" },
      { id: "logarithms", title: "로그는 지수의 역질문" },
      { id: "log-identities", title: "곱·나눗셈의 log 규칙" },
      { id: "log-bases", title: "밑과 단위" },
      { id: "applications", title: "정보량과 loss로 연결" },
    ],
    component: () => import("@/pages/articles/ai/math-exponents-logarithms"),
  },
  {
    slug: "math-probability-expectation-variance",
    title: "Probability experiment와 conditional probability: 경우를 먼저 세는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "실험·sample space·outcome" },
      { id: "outcomes", title: "Distribution과 event" },
      { id: "conditional-probability", title: "조건 뒤에 다시 정규화" },
      { id: "chain-rule", title: "Joint probability를 곱으로 분해" },
      { id: "independence-boundary", title: "독립과 상호배타 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-probability-expectation-variance"),
  },
  {
    slug: "math-random-variables-expectation",
    title: "Random variable과 expectation: outcome을 숫자로 요약하는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Outcome에서 숫자로" },
      { id: "mapping", title: "Random variable의 함수 형태" },
      { id: "distribution", title: "값별 probability mass" },
      { id: "expectation", title: "가중 무게중심" },
      { id: "transform-boundary", title: "선형성과 비선형 경계" },
    ],
    component: () =>
      import("@/pages/articles/ai/math-random-variables-expectation"),
  },
  {
    slug: "math-variance-sampling",
    title: "Variance·sample mean·mini-batch: 흔들림을 추정하는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "중심과 흔들림 분리" },
      { id: "variance", title: "Variance와 standard deviation" },
      { id: "sample-estimation", title: "Sample mean·sample variance" },
      { id: "law-of-large-numbers", title: "큰 수의 법칙과 1/B" },
      { id: "gradient-estimator", title: "Mini-batch gradient" },
      { id: "boundaries", title: "상관·편향·heavy-tail 경계" },
    ],
    component: () => import("@/pages/articles/ai/math-variance-sampling"),
  },
  {
    slug: "math-optimization-objectives",
    title: "Optimization objective와 feasible set: 문제를 먼저 정의하는 법",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "선택·점수·허용 범위" },
      { id: "feasible-set", title: "Constraint와 feasible set" },
      { id: "minimizer", title: "Argmin과 minimum value" },
      { id: "boundaries", title: "Constrained 문제 경계" },
    ],
    component: () => import("@/pages/articles/ai/math-optimization-objectives"),
  },
  {
    slug: "math-optimization-convexity",
    title: "Convexity·smoothness: 보장을 가능하게 하는 함수 구조",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "함수 지형의 네 조건" },
      { id: "convexity", title: "Chord inequality" },
      { id: "smoothness", title: "L-smoothness와 descent lemma" },
      { id: "curvature-range", title: "Strong convexity와 condition number" },
    ],
    component: () => import("@/pages/articles/ai/math-optimization-convexity"),
  },
  {
    slug: "math-gradient-descent-convergence",
    title: "Gradient descent와 convergence: 보폭·전제·실패 경계",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "반복 규칙과 보폭" },
      { id: "update", title: "Negative gradient update" },
      { id: "step-size", title: "수축·진동·발산" },
      { id: "convergence", title: "Convergence guarantee" },
      { id: "stopping-boundary", title: "Stationary와 stopping signal" },
    ],
    component: () => import("@/pages/articles/ai/math-gradient-descent-convergence"),
  },
  {
    slug: "perceptron",
    title: "퍼셉트론: 신경망의 기원",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "선형 결정 경계에서 시작하기" },
      { id: "convergence", title: "수렴 정리의 전제와 margin" },
      { id: "logic-gates", title: "논리 회로 구현" },
      { id: "limitation", title: "퍼셉트론의 한계" },
      { id: "multilayer", title: "다층 퍼셉트론" },
    ],
    component: () => import("@/pages/articles/ai/perceptron"),
  },
  {
    slug: "neural-network",
    title: "신경망: 퍼셉트론에서 다층 네트워크로",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "함수 합성과 learned representation" },
      { id: "activation", title: "Affine collapse와 비선형성" },
      { id: "forward", title: "Tensor shape와 signal scale" },
      { id: "output-layer", title: "Target의 확률 계약" },
      { id: "mnist", title: "MNIST 실험과 일반화 진단" },
    ],
    component: () => import("@/pages/articles/ai/neural-network"),
  },
  {
    slug: "activation-functions",
    title: "활성화 함수 기초: Step · Sigmoid · Tanh",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "값과 local slope" },
      { id: "step-function", title: "계단 함수와 gradient" },
      { id: "sigmoid", title: "Sigmoid와 saturation" },
      { id: "tanh", title: "Tanh와 signed state" },
      { id: "comparison", title: "출력 의미와 경계" },
    ],
    component: () => import("@/pages/articles/ai/activation-functions"),
  },
  {
    slug: "rectifier-activations",
    title: "Rectifier 활성화: ReLU · Dying ReLU · SELU",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "0에서 꺾이는 선" },
      { id: "relu", title: "ReLU hinge" },
      { id: "dying-relu", title: "Dying state" },
      { id: "negative-slope", title: "Leaky ReLU · PReLU" },
      { id: "self-normalization", title: "SELU 조건" },
      { id: "comparison", title: "측정과 선택" },
    ],
    component: () => import("@/pages/articles/ai/rectifier-activations"),
  },
  {
    slug: "gated-activations",
    title: "Smooth·Gated 활성화: GELU · SiLU · SwiGLU",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "값과 통과 비율" },
      { id: "gelu-silu", title: "GELU · SiLU" },
      { id: "gated-ffn", title: "SwiGLU 구조" },
      { id: "parameter-budget", title: "공정한 parameter 예산" },
      { id: "comparison", title: "구조·kernel 비교" },
    ],
    component: () => import("@/pages/articles/ai/gated-activations"),
  },
  {
    slug: "reverse-mode-autodiff",
    title: "Reverse-mode autodiff: Graph · Tape · VJP",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Computational graph" },
      { id: "tape", title: "Saved tape" },
      { id: "reverse-mode", title: "VJP와 branch sum" },
      { id: "save-recompute", title: "Save·recompute 경계" },
    ],
    component: () => import("@/pages/articles/ai/reverse-mode-autodiff"),
  },
  {
    slug: "softmax",
    title: "Softmax: Logit에서 공동 확률까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Logit과 공동 분모" },
      { id: "temperature", title: "Temperature" },
      { id: "output-boundary", title: "Categorical 경계" },
    ],
    component: () => import("@/pages/articles/ai/softmax"),
  },
  {
    slug: "backprop-optimization",
    title: "신경망 Backprop: Loss에서 Tensor Gradient까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "왜 역전파인가" },
      { id: "loss-function", title: "Scalar loss 만들기" },
      { id: "tensor-backward", title: "출력에서 weight까지" },
    ],
    component: () => import("@/pages/articles/ai/backprop-optimization"),
  },
  {
    slug: "optimizers",
    title: "옵티마이저: SGD에서 AdamW까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Gradient를 parameter update로 바꾸기" },
      { id: "sgd", title: "SGD (확률적 경사 하강법)" },
      { id: "batch-variants", title: "Batch / Stochastic / Mini-batch" },
      { id: "momentum", title: "Momentum (관성)" },
      { id: "adam", title: "Adam (적응적 학습률)" },
      { id: "adamw", title: "AdamW (Decoupled Weight Decay)" },
    ],
    component: () => import("@/pages/articles/ai/optimizers"),
  },
  {
    slug: "cross-entropy",
    title: "크로스 엔트로피: 정보 이론에서 손실 함수로",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Surprisal에서 loss까지" },
      { id: "expectation", title: "기대값과 empirical risk" },
      { id: "entropy", title: "Entropy: 피할 수 없는 불확실성" },
      { id: "cross-entropy", title: "Cross-entropy와 likelihood" },
      { id: "kl-divergence", title: "KL: 모델의 추가 비용" },
      { id: "ce-vs-mse", title: "Likelihood로 loss 고르기" },
      { id: "softmax-ce-gradient", title: "Softmax–CE fused gradient" },
    ],
    component: () => import("@/pages/articles/ai/cross-entropy"),
  },
  {
    slug: "fft",
    title: "FFT (Fast Fourier Transform) — AI 관점",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "DFT와 FFT의 역할 분리" },
      { id: "fourier", title: "Sampling·window·spectrum" },
      { id: "algorithm", title: "Cooley–Tukey의 계산 재사용" },
      { id: "ai-usage", title: "AI 적용과 실제 선택 기준" },
    ],
    component: () => import("@/pages/articles/ai/fft"),
  },
  {
    slug: "word2vec",
    title: "Word2Vec 기초: Word ID에서 Context Pair까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "ID에서 trainable row로" },
      { id: "dual-tables", title: "Input·output table" },
      { id: "window", title: "Context window의 형태" },
      { id: "pairs", title: "Versioned pair receipt" },
    ],
    component: () => import("@/pages/articles/ai/word2vec"),
  },
  {
    slug: "word2vec-prediction-objectives",
    title: "Word2Vec Objectives: CBOW·Skip-gram·Hierarchical Softmax",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "예측 방향 먼저 고르기" },
      { id: "cbow", title: "Context에서 center로" },
      { id: "skipgram", title: "Center에서 context로" },
      { id: "hierarchical", title: "Vocabulary를 tree path로" },
    ],
    component: () => import("@/pages/articles/ai/word2vec-prediction-objectives"),
  },
  {
    slug: "word2vec-negative-sampling",
    title: "Word2Vec Negative Sampling: Pair Discrimination과 Update",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Full softmax에서 sampled pair로" },
      { id: "sgns", title: "Positive·noise logistic loss" },
      { id: "noise", title: "Noise distribution과 k" },
      { id: "subsampling", title: "고빈도 token을 덜 보기" },
    ],
    component: () => import("@/pages/articles/ai/word2vec-negative-sampling"),
  },
  {
    slug: "subword-static-embeddings",
    title: "Subword Static Embeddings: fastText에서 Release까지",
    subcategory: "ai-foundations",
    sections: [
      { id: "overview", title: "Word row의 OOV 경계" },
      { id: "ngrams", title: "Character n-gram 합" },
      { id: "static-contextual", title: "Static과 contextual" },
      { id: "release", title: "Vocabulary·matrix artifact" },
    ],
    component: () => import("@/pages/articles/ai/subword-static-embeddings"),
  },
];

/** Combined DL articles: foundations + foundation2 + NLP + vision */
export const dlArticles: Article[] = [
  ...dlFoundationArticles,
  ...dlFoundation2Articles,
  ...dlNlpArticles,
  ...dlVisionArticles,
];
