import type { Article } from '../types';

export const systemsFoundationArticles: Article[] = [
  {
    slug: 'systems-foundation-map',
    title: 'AI 기술을 처음 읽는 법: 입력에서 성공 판정까지',
    subcategory: 'ai-systems-foundation',
    summary: '택배가 접수되어 도착하는 익숙한 흐름에서 시작해, 처음 보는 AI 기술이 무엇을 받고 누가 처리하며 결과를 어떻게 확인하는지 차근차근 따라간다.',
    level: '입문',
    estimatedMinutes: 20,
    prerequisites: [],
    learningPath: 'ai-systems-reading-frame',
    sections: [
      { id: 'why-common-lens', title: '낯선 AI 기술은 어디서부터 볼까?' },
      { id: 'shared-foundations', title: '다섯 질문은 무엇을 분리할까?' },
      { id: 'failure-localization', title: '첫 파손 지점은 어디일까?' },
      { id: 'apply-lens', title: '같은 질문 뒤 공부가 왜 달라질까?' },
      { id: 'choose-next-path', title: '어느 글로 내려가야 할까?' },
      { id: 'finish-line', title: '이 글을 읽고 무엇을 할 수 있을까?' },
    ],
    component: () => import('@/pages/articles/ai/systems-foundation-map'),
  },
  {
    slug: 'knowledge-compiler',
    title: 'Knowledge Compiler: 원문에서 검증 가능한 답까지',
    subcategory: 'ai-knowledge-systems',
    learningPath: 'ai-knowledge-system-core',
    summary: 'Source·structure·meaning·retrieval·maintenance의 다섯 계약으로 지식 시스템의 현재 경로와 책임을 고른다.',
    level: '기초',
    estimatedMinutes: 18,
    prerequisites: ['문서가 제목·문단·표·그림 같은 구조를 가진다는 이해', 'LLM이 확률적으로 텍스트를 생성한다는 이해'],
    sections: [
      { id: 'why-contracts', title: '왜 다섯 계약으로 나눌까?' },
      { id: 'current-boundary', title: '현재 연구가 바꾼 경계' },
      { id: 'route', title: '한 source에서 지속 갱신까지' },
      { id: 'finish-line', title: '어디에서 멈출까?' },
    ],
    component: () => import('@/pages/articles/ai/knowledge-compiler'),
  },
  {
    slug: 'knowledge-source-ingestion',
    title: 'Source Ingestion · Structure Recovery: 원문 구조와 주소를 잃지 않는 법',
    subcategory: 'ai-knowledge-systems',
    learningPath: 'ai-knowledge-system-core',
    summary: 'PDF·영상·웹·코드에서 reading order, 표·수식·caption과 source coordinate를 복구하고 fixture로 검증한다.',
    level: '기초',
    estimatedMinutes: 42,
    prerequisites: ['문서가 block과 관계로 이루어진다는 감각', '파일 version과 hash가 입력을 고정한다는 기본 이해'],
    sections: [
      { id: 'source-envelope', title: '원문 identity와 version 고정' },
      { id: 'parser-routing', title: '형식별 parser routing' },
      { id: 'structure-recovery', title: '표·수식·caption 관계 복구' },
      { id: 'source-coordinates', title: '원문으로 돌아가는 주소' },
      { id: 'ingestion-release', title: 'Fixture와 release gate' },
    ],
    component: () => import('@/pages/articles/ai/knowledge-source-ingestion'),
  },
  {
    slug: 'knowledge-ir-evidence-lineage',
    title: 'Knowledge IR · Evidence Lineage: Claim과 수정 이력을 보존하는 법',
    subcategory: 'ai-knowledge-systems',
    learningPath: 'ai-knowledge-system-core',
    summary: 'DocumentVersion·Block·Claim·Scope·Evidence·Transformation을 분리하고 revision의 downstream 영향만 다시 계산한다.',
    level: '중급',
    estimatedMinutes: 46,
    prerequisites: ['Source Ingestion의 block·artifact·locator', '방향 graph에서 edge를 따라간다는 직관'],
    sections: [
      { id: 'document-versus-ir', title: 'Document와 Knowledge IR' },
      { id: 'ir-schema', title: 'Claim·Scope·Evidence schema' },
      { id: 'lineage', title: 'Build-time lineage와 runtime trace' },
      { id: 'multilingual-artifacts', title: '다국어와 artifact alignment' },
      { id: 'revision-impact', title: '수정본의 downstream 영향' },
      { id: 'ir-release', title: 'IR release gate' },
    ],
    component: () => import('@/pages/articles/ai/knowledge-ir-evidence-lineage'),
  },
  {
    slug: 'knowledge-research-watcher',
    title: 'Research Watcher: 새 연구를 학습 경로로 승격하는 법',
    subcategory: 'ai-knowledge-systems',
    learningPath: 'ai-knowledge-system-core',
    summary: '논문·회사 연구 글·코드 릴리스를 versioned queue로 모으고, 현재 top 교체와 최소 기반 추가를 근거로 판정하는 운영 파이프라인.',
    level: '중급',
    estimatedMinutes: 42,
    prerequisites: ['Knowledge IR과 claim-evidence provenance', 'RAG의 retrieval·generation·evaluation 경계', '집합 차이와 방향 그래프 도달 가능성의 직관'],
    sections: [
      { id: 'queue-contract', title: '발견 queue는 curriculum이 아니다' },
      { id: 'source-identity', title: 'URL보다 오래가는 identity를 만든다' },
      { id: 'discovery-routing', title: '수집과 routing은 해도, publishing은 하지 않는다' },
      { id: 'mechanism-diff', title: '모델 이름이 아니라 다섯 계약을 비교한다' },
      { id: 'promotion', title: '현재 글 교체와 기반 추가를 분리한다' },
      { id: 'invalidation', title: '정정은 다음 전체 재작성까지 기다리지 않는다' },
      { id: 'small-model-packet', title: '4B·9B 모델은 판단 범위를 좁혀 쓴다' },
      { id: 'implementation-evaluation', title: '현재 구현에서 다음으로 무엇을 붙일까?' },
    ],
    component: () => import('@/pages/articles/ai/research-watcher-curriculum'),
  },
  {
    slug: 'research-codar-2026',
    title: '논문 재구성 · CoDaR: 긴 문서를 언제 나누면 안 되는가',
    subcategory: 'ai-knowledge-systems',
    summary: 'RAG·agent·memory·compression이 dataset에 따라 Full-Context보다 나빠지는 이유를 context dependency로 추적하고, DCDS와 adaptive routing을 수식·실험·구현 trace로 복원합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['RAG 또는 chunk retrieval의 기본 흐름', '평균과 상대 변화율의 직관', '문서 안에서 대명사·전제·결론이 이어진다는 이해'],
    mathAnnotations: true,
    curriculumRole: 'source',
    sections: [
      { id: 'failure-question', title: '분해가 실패하는 질문' },
      { id: 'dcds', title: 'DCDS 계산' },
      { id: 'routing', title: 'CoDaR routing' },
      { id: 'evidence', title: 'Dataset·controlled experiment 증거' },
      { id: 'production-transfer', title: '평균 점수의 제품 경계' },
      { id: 'implementation-boundary', title: '구현 trace와 한계' },
    ],
    component: () => import('@/pages/articles/ai/research-codar-2026'),
  },
  {
    slug: 'paper-rag-2020',
    title: '논문 재구성 · RAG: 검색 문서를 생성 확률에 넣는 법',
    subcategory: 'ai-knowledge-systems',
    summary: 'Parametric·non-parametric memory, latent document, RAG-Sequence·RAG-Token의 marginalization, retriever ablation과 index hot-swap을 원문에서 구현 가능한 구조로 복원합니다.',
    level: '심화',
    estimatedMinutes: 62,
    prerequisites: ['Softmax와 조건부 확률의 직관', 'Seq2Seq next-token generation', 'Dense retrieval의 vector 내적'],
    mathAnnotations: true,
    curriculumRole: 'source',
    sections: [
      { id: 'research-question', title: '두 기억을 왜 결합했는가' },
      { id: 'retriever-generator', title: 'Retriever와 generator' },
      { id: 'sequence-token', title: 'RAG-Sequence와 RAG-Token' },
      { id: 'evidence-boundary', title: '실험 증거와 현재 경계' },
    ],
    component: () => import('@/pages/articles/ai/paper-rag-2020'),
  },
  {
    slug: 'research-pi07-2026',
    title: '연구 재구성 · π0.7: 서로 다른 Robot 경험을 하나의 Policy로 묶는 법',
    subcategory: 'ai-robotics-overview',
    summary: 'Camera history, semantic subtask, visual subgoal, 품질 metadata와 real-time action chunking이 mixed-quality·cross-embodiment data를 어떻게 하나의 generalist VLA로 묶는지 원문에서 복원합니다.',
    level: '심화',
    estimatedMinutes: 66,
    prerequisites: ['Robot observation·policy·controller의 역할 구분', '모방 학습과 mixed-quality trajectory의 직관', '주파수의 역수와 latency budget'],
    curriculumRole: 'source',
    sections: [
      { id: 'prompt-contract', title: 'Task-only prompt의 실패' },
      { id: 'observation-action-path', title: '관측에서 action chunk까지' },
      { id: 'mixed-quality-data', title: 'Mixed-quality data와 context' },
      { id: 'asynchronous-runtime', title: '비동기 runtime과 cadence' },
      { id: 'evidence-boundary', title: 'Generalization evidence 경계' },
    ],
    component: () => import('@/pages/articles/ai/research-pi07-2026'),
  },
  {
    slug: 'paper-openvla-2024',
    title: '논문 재구성 · OpenVLA: Image와 언어를 Robot Action Token으로 바꾸는 법',
    subcategory: 'ai-robotics-overview',
    summary: 'Fused vision encoder, action discretization, Open X data mixture, 실제 robot rollout과 quantization cadence를 따라 공개 VLA의 재현 가능한 최소 기준을 복원합니다.',
    level: '심화',
    estimatedMinutes: 62,
    prerequisites: ['Image encoder와 autoregressive next-token prediction', '분위수·구간 양자화의 직관', 'Robot control frequency와 closed loop'],
    curriculumRole: 'source',
    sections: [
      { id: 'input-output-contract', title: 'VLA input-output contract' },
      { id: 'action-tokenization', title: '연속 action tokenization' },
      { id: 'data-training-receipt', title: 'Data mixture와 training receipt' },
      { id: 'real-robot-evidence', title: 'Real-robot evidence와 adaptation' },
      { id: 'closed-loop-boundary', title: 'Quantization과 closed-loop 경계' },
    ],
    component: () => import('@/pages/articles/ai/paper-openvla-2024'),
  },
  {
    slug: 'robot-ai-top-down',
    title: 'Robot AI 탑다운: 명령에서 물리 효과까지',
    subcategory: 'ai-robotics-overview',
    summary: '한 명령이 observation, state, policy, trajectory, feedback control, ROS 2 runtime, motor drive와 측정 증거를 통과하는 실행 계약을 따라가며 필요한 기반으로 내려갑니다.',
    level: '기초',
    estimatedMinutes: 54,
    prerequisites: ['Python으로 모델 추론을 호출해 본 경험', '함수가 입력을 받아 출력을 만든다는 기본 이해'],
    learningPath: 'ai-robot-system-overview',
    sections: [
      { id: 'execution-contract', title: '명령에서 물리 효과까지' },
      { id: 'feedback-contract', title: 'Feedback과 disturbance' },
      { id: 'ros-contract', title: 'ROS 2 실행 계약' },
      { id: 'foundation-descent', title: '필요한 기반으로 내려가기' },
      { id: 'orchard-case', title: '과수원 end-to-end 사례' },
      { id: 'sim-real-release', title: 'Simulation에서 현실 release까지' },
    ],
    component: () => import('@/pages/articles/ai/robot-ai-top-down'),
  },
  {
    slug: 'robot-ros2-runtime-communication',
    title: '로봇의 통신과 시간: ROS 2 메시지에서 모터 마감시간까지',
    subcategory: 'ai-robotics-runtime-embedded',
    summary: '보낸 명령이 도착했다는 사실만으로 로봇이 제때 올바르게 움직이는 것은 아닙니다. 메시지의 뜻, 최신성, 실행 순서와 시간 제한을 차례로 연결한 뒤 ROS 2의 정식 용어를 붙입니다.',
    level: '중급',
    estimatedMinutes: 128,
    prerequisites: ['메시지를 보내고 받는 프로그램의 기본', '일정한 측정 간격과 전달 지연의 직관', '프로그램이 여러 일을 번갈아 처리한다는 직관'],
    learningPath: 'ai-robot-ros2-runtime',
    sections: [
      { id: 'runtime-contract', title: 'Graph와 runtime contract' },
      { id: 'discovery-readiness', title: 'Discovery·matching·readiness·health' },
      { id: 'qos-contract', title: 'Requested/Offered QoS' },
      { id: 'queue-overload', title: 'Queue overload와 sample age' },
      { id: 'executor-callbacks', title: 'Executor·callback group·deadlock' },
      { id: 'lifecycle-supervision', title: 'Managed lifecycle와 supervision' },
      { id: 'composition-ownership', title: 'Composition과 ownership' },
      { id: 'time-tf', title: 'Clock·acquisition time·TF' },
      { id: 'end-to-end-deadline', title: 'End-to-end deadline과 health gate' },
      { id: 'qualification', title: 'Fault injection과 release gate' },
    ],
    component: () => import('@/pages/articles/ai/robot-ros2-runtime-communication'),
  },
  {
    slug: 'paper-casini-ros2-response-time-2019',
    title: '원 논문 · Casini et al. (2019): ROS 2 Processing Chain의 Response-Time 분석',
    subcategory: 'ai-robotics-runtime-embedded',
    summary: 'Callback graph, Crystal executor polling semantics, arrival curve, CPU reservation과 fixed-point response bound를 복원하고 move_base evidence와 current ROS 2에서 달라진 경계를 분리합니다.',
    level: '심화',
    estimatedMinutes: 92,
    prerequisites: ['ROS 2 executor·callback·QoS', 'WCET·jitter·queue와 scheduling', 'Fixed point와 함수 upper bound의 직관'],
    learningPath: 'ai-robot-ros2-runtime-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: 'Callback graph와 분석 구조' },
      { id: 'mechanism', title: 'Arrival·supply·response 수식' },
      { id: 'evidence', title: 'Executor trace와 move_base 증거' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'Current executor 분석으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-casini-ros2-response-time-2019'),
  },
  {
    slug: 'robot-embedded-realtime-control',
    title: '명령을 실제 PWM으로 만드는 법: 임베디드 실시간 제어',
    subcategory: 'ai-robotics-runtime-embedded',
    summary: '컴퓨터가 보낸 목표값이 작은 제어 칩 안에서 언제 읽히고 계산되어 실제 전기 신호가 되는지 따라갑니다. 그 흐름을 이해한 뒤 MCU, interrupt, DMA, RTOS와 PWM을 배웁니다.',
    level: '중급',
    estimatedMinutes: 126,
    prerequisites: ['로봇 명령이 네트워크를 지나 전달되는 흐름', '일정한 간격으로 측정하고 고치는 제어의 직관', '메모리와 정수 계산의 기본'],
    learningPath: 'ai-robot-embedded-realtime',
    sections: [
      { id: 'command-envelope', title: 'Setpoint envelope와 applied identity' },
      { id: 'physical-deadline', title: 'Physical deadline과 PWM latch' },
      { id: 'sample-actuate', title: 'Hardware sample-compute-actuate' },
      { id: 'isr-dma', title: 'NVIC·ISR·DMA ownership' },
      { id: 'rtos-schedule', title: 'RTOS task model과 schedulability' },
      { id: 'priority-inversion', title: 'Priority inversion과 blocking' },
      { id: 'fieldbus-time', title: 'Fieldbus와 distributed time' },
      { id: 'numeric-memory', title: 'Memory와 numeric bounds' },
      { id: 'fault-ladder', title: 'Hardware trip과 supervised restart' },
    ],
    component: () => import('@/pages/articles/ai/robot-embedded-realtime-control'),
  },
  {
    slug: 'paper-liu-layland-realtime-scheduling-1973',
    title: '원 논문 · Liu & Layland (1973): Hard Real-Time Scheduling의 출발점',
    subcategory: 'ai-robotics-runtime-embedded',
    summary: '다섯 환경 가정, critical instant, rate-monotonic fixed priority, m(2^(1/m)-1) 충분조건과 deadline-driven scheduling의 U<=1 결과를 현대 MCU 경계와 함께 복원합니다.',
    level: '심화',
    estimatedMinutes: 78,
    prerequisites: ['RTOS task·priority·preemption', 'Period·WCET·deadline·utilization', '합·비율·천장함수의 기본'],
    learningPath: 'ai-robot-embedded-realtime-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '다섯 가정과 scheduling 구조' },
      { id: 'mechanism', title: 'Critical instant·RM·deadline-driven 수식' },
      { id: 'evidence', title: '정리와 증명 범위' },
      { id: 'reproduction', title: '현대 MCU 재현과 숨은 가정' },
      { id: 'legacy', title: 'Response-time analysis와 FOC runtime으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-liu-layland-realtime-scheduling-1973'),
  },
  {
    slug: 'robot-motor-drive-foc',
    title: '원하는 힘을 모터 전류로 바꾸는 법: FOC와 3상 인버터',
    subcategory: 'ai-robotics-actuation-power',
    summary: '관절에 원하는 힘을 내라는 명령은 그대로 모터에 넣을 수 없습니다. 세 전선의 전류와 스위치 시간을 만드는 과정을 눈으로 확인한 뒤 FOC, 좌표 변환, 전류 제어와 인버터를 연결합니다.',
    level: '중급',
    estimatedMinutes: 148,
    prerequisites: ['화살표로 크기와 방향을 나타내는 벡터', '오차를 재어 반복해서 줄이는 제어의 직관', '전기를 빠르게 켰다 끄면 평균 세기가 달라진다는 직관'],
    learningPath: 'ai-robot-motor-drive-foc',
    sections: [
      { id: 'torque-contract', title: 'Torque-to-duty physical contract' },
      { id: 'rotating-field', title: 'Three-phase rotating field' },
      { id: 'clarke-transform', title: 'Clarke projection과 scaling' },
      { id: 'park-angle', title: 'Electrical angle과 Park frame' },
      { id: 'pmsm-model', title: 'PMSM d-q voltage와 torque' },
      { id: 'current-loop', title: 'Discrete current PI와 anti-windup' },
      { id: 'svpwm-inverter', title: 'SVPWM·DC bus·dead time' },
      { id: 'sensing-alignment', title: 'Current sensing과 rotor alignment' },
      { id: 'operating-envelope', title: 'MTPA·field weakening·regeneration' },
      { id: 'commissioning', title: 'Protection과 physical commissioning' },
    ],
    component: () => import('@/pages/articles/ai/robot-motor-drive-foc'),
  },
  {
    slug: 'paper-blaschke-field-orientation-1973',
    title: '원 논문 · Blaschke (1973): Field Orientation으로 결합된 Motor를 분리하기',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'DC machine의 직교 field/current 직관에서 시작해 field coordinates, measured/model field, parameter detuning, synchronous/induction specialization, stability와 TRANSVEKTOR physical realization을 264쪽 원전 흐름으로 복원합니다.',
    level: '심화',
    estimatedMinutes: 112,
    prerequisites: ['Three-phase rotating vector와 coordinate transform', 'Motor Drive & FOC의 d-q frame 직관', 'Feedback·model mismatch·stability의 기본'],
    learningPath: 'ai-robot-motor-drive-foc-paper-spine',
    sections: [
      { id: 'context', title: '결합된 machine과 저자 의도' },
      { id: 'claim', title: 'Field coordinates와 measured/model 구조' },
      { id: 'mechanism', title: 'Coordinate·decoupling 수식' },
      { id: 'evidence', title: '원문 evidence와 입증 범위' },
      { id: 'reproduction', title: '재현과 hidden assumptions' },
      { id: 'legacy', title: 'Modern PMSM FOC로 이어진 유산' },
    ],
    component: () => import('@/pages/articles/ai/paper-blaschke-field-orientation-1973'),
  },
  {
    slug: 'robot-power-electronics-motor-driver',
    title: '모터 힘을 만드는 전력 회로: 전원에서 실제 전류까지',
    subcategory: 'ai-robotics-actuation-power',
    summary: '제어기가 만든 스위치 시간표가 배터리, 전력 스위치와 센서를 지나 실제 모터 전류가 되는 과정을 에너지·열·보호 증거로 확인합니다.',
    level: '중급',
    estimatedMinutes: 156,
    prerequisites: ['전압·전류·전력과 에너지의 기본', '모터 힘과 세 선의 전류가 이어지는 과정', '제어기와 실제 하드웨어 결과를 구분하는 감각'],
    learningPath: 'ai-robot-power-electronics',
    sections: [
      { id: 'power-contract', title: 'Duty-to-power physical contract' },
      { id: 'dc-link', title: 'DC-link energy·precharge·regeneration' },
      { id: 'commutation', title: 'Half-bridge commutation과 device stress' },
      { id: 'gate-drive', title: 'Gate charge·Miller·dead time' },
      { id: 'parasitics-layout', title: 'Parasitic loop·ringing·probe' },
      { id: 'loss-budget', title: 'Conduction·switching loss budget' },
      { id: 'thermal', title: 'Steady·transient thermal path' },
      { id: 'current-sense', title: 'Shunt·Kelvin·PWM settling' },
      { id: 'protection', title: 'Protection latency·fault energy' },
      { id: 'pcb-bringup', title: 'PCB zoning과 evidence bring-up' },
    ],
    component: () => import('@/pages/articles/ai/robot-power-electronics-motor-driver'),
  },
  {
    slug: 'reference-ti-tida-010956-2025',
    title: '회사 리서치 · TI TIDA-010956 (2025): 48 V·85 Arms Inverter를 Claim-Evidence로 읽기',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'TI의 guide·schematic·PCB·waveform·thermal evidence를 energy/gate/sense/shutdown path로 재구성하고, 85 Arms title claim과 26.2 Arms 공개 thermal point 및 STO 경계를 분리합니다.',
    level: '심화',
    estimatedMinutes: 96,
    prerequisites: ['Motor-driver energy·gate·sense·protection path', 'MOSFET switching·thermal·PCB loop의 기본', '시험 조건과 claim boundary를 구분하는 능력'],
    learningPath: 'ai-robot-power-electronics-reference',
    sections: [
      { id: 'context', title: 'Reference design 이전의 병목과 저자 의도' },
      { id: 'claim', title: 'Energy·gate·sense·shutdown architecture' },
      { id: 'mechanism', title: 'OCP·timing·settling·thermal 수식' },
      { id: 'evidence', title: '85 Arms·waveform·thermal evidence 경계' },
      { id: 'reproduction', title: 'Schematic·PCB·test 재현' },
      { id: 'legacy', title: 'Company research를 읽는 claim-evidence 방식' },
    ],
    component: () => import('@/pages/articles/ai/reference-ti-tida-010956-2025'),
  },
  {
    slug: 'robot-drive-energy-braking-safety',
    title: '움직이던 로봇을 안전하게 멈추는 법: 에너지와 제동',
    subcategory: 'ai-robotics-actuation-power',
    summary: '멈추라는 명령 뒤에도 남은 회전·중력·탄성 에너지를 세고, 배터리·다른 축·제동 저항 중 실제로 받아 줄 곳을 골라 안전한 끝 상태까지 증명합니다.',
    level: '중급',
    estimatedMinutes: 138,
    prerequisites: ['에너지·전력과 토크×속도의 의미', '모터가 힘을 내거나 발전기로 바뀌는 조건', '전원 회로가 에너지를 저장하고 보호하는 기본'],
    learningPath: 'ai-robot-drive-energy-braking',
    sections: [
      { id: 'energy-contract', title: 'Stop과 energy destination contract' },
      { id: 'mechanical-inventory', title: 'Mechanical energy inventory' },
      { id: 'quadrants-trajectory', title: 'Four quadrants와 braking trajectory' },
      { id: 'bus-headroom', title: 'DC-link headroom과 response deadline' },
      { id: 'sink-selection', title: 'Battery·source·peer·dump sink' },
      { id: 'brake-chopper', title: 'Brake chopper·resistor feasibility' },
      { id: 'common-bus', title: 'Multi-axis common DC arbitration' },
      { id: 'power-lifecycle', title: 'Contactor·precharge·discharge state' },
      { id: 'braking-supervisor', title: 'Sink-aware torque supervisor' },
      { id: 'commissioning', title: 'Energy-ledger commissioning' },
    ],
    component: () => import('@/pages/articles/ai/robot-drive-energy-braking-safety'),
  },
  {
    slug: 'reference-abb-electrical-braking-2018',
    title: '회사 리서치 · ABB Technical Guide No. 8 (2018): Electrical Braking을 Energy로 읽기',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'ABB의 mechanics-first braking method, fan power example, DC capacitor 약 6 ms example, motor-loss·resistor·regenerative alternatives와 common DC를 source condition과 robot transfer boundary로 재구성합니다.',
    level: '심화',
    estimatedMinutes: 82,
    prerequisites: ['Torque·speed·inertia와 signed power', 'DC-link capacitor와 brake chopper', 'Battery/Common-bus sink availability의 기본'],
    learningPath: 'ai-robot-drive-energy-braking-reference',
    sections: [
      { id: 'context', title: 'Guide 이전의 병목과 저자 의도' },
      { id: 'claim', title: 'Mechanics-first braking architecture' },
      { id: 'mechanism', title: 'Power·energy·headroom·common DC 수식' },
      { id: 'evidence', title: 'Fan·6 ms·chopper·comparison evidence' },
      { id: 'reproduction', title: 'Robot adaptation과 숨은 가정' },
      { id: 'legacy', title: 'Company guide를 transfer하는 방법' },
    ],
    component: () => import('@/pages/articles/ai/reference-abb-electrical-braking-2018'),
  },
  {
    slug: 'robot-drive-isolation-emc-functional-safety',
    title: 'Robot Drive Isolation, EMC & Functional Safety: 절연 장벽에서 STO Evidence까지',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'Isolation intent와 coordination inputs, CMTI·barrier current, CM/DM EMC path와 evidence, controlled stop·STO·holding, dual-channel diagnostics와 safety lifecycle을 한 physical claim chain으로 연결합니다.',
    level: '중급',
    estimatedMinutes: 154,
    prerequisites: ['DC link·gate driver·PCB parasitic의 물리 경로', 'Drive Energy & Braking의 controlled stop과 stored energy', '신호·filter·delay·frequency response의 기본'],
    learningPath: 'ai-robot-drive-isolation-emc-safety',
    sections: [
      { id: 'contract-boundary', title: 'Isolation·EMC·STO·hold contract' },
      { id: 'insulation-coordination', title: 'Insulation-coordination inputs' },
      { id: 'barrier-transient', title: 'Barrier current·CMTI·timing skew' },
      { id: 'common-mode', title: 'Common-mode closed current path' },
      { id: 'emc-coupling', title: 'Source·path·victim mitigation' },
      { id: 'emc-evidence', title: 'Emission·immunity evidence' },
      { id: 'function-allocation', title: 'Controlled stop·STO·holding' },
      { id: 'dual-channel', title: '1oo2·HFT1·diagnostics·CCF' },
      { id: 'sto-timing', title: 'Electronics response와 motion-safe time' },
      { id: 'safety-case', title: 'Safety case와 lifecycle' },
    ],
    component: () => import('@/pages/articles/ai/robot-drive-isolation-emc-functional-safety'),
  },
  {
    slug: 'reference-ti-tida-01599-sto-2022',
    title: '회사 리서치 · TI TIDA-01599 + TÜV (2022): STO Concept를 Evidence로 읽기',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'Dual-channel primary/secondary gate-power removal, external assumptions, HFT1 truth table, board-specific timing, E1.0→E2.1 revision과 TÜV concept-review scope를 final machine claim과 분리합니다.',
    level: '심화',
    estimatedMinutes: 94,
    prerequisites: ['Isolation·EMC·STO의 서로 다른 hazard contract', 'Dual-channel·fault·diagnostic-test interval의 기본', 'Board revision과 test evidence provenance'],
    learningPath: 'ai-robot-drive-sto-reference',
    sections: [
      { id: 'context', title: 'Reference 이전 병목과 저자 의도' },
      { id: 'claim', title: 'Dual-channel gate-power architecture' },
      { id: 'mechanism', title: 'HFT1·diagnostic·timing 수식' },
      { id: 'evidence', title: 'Assumption·timing·revision·TÜV 경계' },
      { id: 'reproduction', title: 'Final machine 재현과 숨은 가정' },
      { id: 'legacy', title: 'Concept evidence를 transfer하는 방법' },
    ],
    component: () => import('@/pages/articles/ai/reference-ti-tida-01599-sto-2022'),
  },
  {
    slug: 'robot-actuator-mechanics-transmission-holding-brake',
    title: '작은 모터를 로봇 관절로 바꾸는 법: 감속기·강성·브레이크',
    subcategory: 'ai-robotics-actuation-power',
    summary: '모터의 빠른 회전이 감속기, 휘어지는 축, 베어링, 센서와 기계 브레이크를 지나 실제 관절의 힘과 움직임이 되는 과정을 재구성합니다.',
    level: '중급',
    estimatedMinutes: 176,
    prerequisites: ['회전력·속도·전력과 관성의 기본', '스프링과 질량이 흔들리는 공진의 직관', '감속과 전원 차단과 고정의 차이'],
    learningPath: 'ai-robot-actuator-mechanics',
    sections: [
      { id: 'physical-boundary', title: 'Motor-to-link physical boundary' },
      { id: 'ratio-power', title: 'Ratio·speed·torque·power' },
      { id: 'reflected-inertia', title: 'Reflected inertia와 acceleration' },
      { id: 'duty-life', title: 'Mission duty·RMS·life' },
      { id: 'accuracy-vocabulary', title: 'Backlash·lost motion·accuracy' },
      { id: 'compliance-energy', title: 'Torsional compliance와 energy' },
      { id: 'two-mass-resonance', title: 'Two-mass resonance와 bandwidth' },
      { id: 'dual-encoder', title: 'Dual encoder observability' },
      { id: 'output-bearing', title: 'Output-bearing force·moment·life' },
      { id: 'friction-backdrive', title: 'Friction·efficiency·backdrive' },
      { id: 'brake-handover', title: 'Vertical-axis brake handover' },
      { id: 'commissioning', title: 'Joint evidence commissioning' },
    ],
    component: () => import('@/pages/articles/ai/robot-actuator-mechanics-transmission-holding-brake'),
  },
  {
    slug: 'reference-harmonic-drive-mechatronics-2026',
    title: '회사 리서치 · Harmonic Drive Mechatronics (2026): Actuator Catalog를 Evidence로 읽기',
    subcategory: 'ai-robotics-actuation-power',
    summary: 'Issue 1053524 05/2026의 selection, RMS duty, 서로 다른 WG·output-bearing 수명식, piecewise stiffness, resonance, zero backlash·lost motion, brake·feedback와 시험 기반·비보증 경계를 exact product·page에 묶어 재구성합니다.',
    level: '심화',
    estimatedMinutes: 102,
    prerequisites: ['Robot actuator ratio·duty·stiffness의 기본', 'Bearing load와 holding-brake handover', '제조사 average와 system evidence를 구분하는 능력'],
    learningPath: 'ai-robot-actuator-mechanics-source-spine',
    sections: [
      { id: 'artifact', title: 'Catalog identity와 selection intent' },
      { id: 'selection-duty', title: 'Duty·RMS·bearing life' },
      { id: 'stiffness-resonance', title: 'Piecewise stiffness·resonance' },
      { id: 'accuracy', title: 'Zero backlash·lost motion·accuracy' },
      { id: 'bearing-brake-feedback', title: 'Bearing·brake·feedback' },
      { id: 'transfer-boundary', title: 'Average value와 transfer boundary' },
    ],
    component: () => import('@/pages/articles/ai/reference-harmonic-drive-mechatronics-2026'),
  },
  {
    slug: 'paper-williamson-series-elastic-actuators-1995',
    title: '원 논문 · Williamson (1995): Series Elastic Actuator로 Force를 제어하기',
    subcategory: 'ai-robotics-actuation-power',
    summary: '의도적 series compliance의 motor–spring model, force transfer, output impedance, current·velocity saturation, system identification, contact experiment와 저자가 인정한 bandwidth·bulk·model mismatch를 83쪽 원전 흐름으로 복원합니다.',
    level: '심화',
    estimatedMinutes: 118,
    prerequisites: ['Actuator stiffness·stored energy·two-mass mode', 'Laplace transfer function과 mechanical impedance', 'Feedback·feedforward·saturation의 기본'],
    learningPath: 'ai-robot-actuator-mechanics-source-spine',
    sections: [
      { id: 'context', title: 'Stiff actuator의 병목과 저자 의도' },
      { id: 'claim', title: 'Motor·gear·spring·load architecture' },
      { id: 'mechanism', title: 'Force transfer·impedance 수식' },
      { id: 'evidence', title: '식별·contact·failure evidence' },
      { id: 'reproduction', title: 'SEA 재현과 hidden assumptions' },
      { id: 'legacy', title: 'Modern compliant joint로 이어진 유산' },
    ],
    component: () => import('@/pages/articles/ai/paper-williamson-series-elastic-actuators-1995'),
  },
  {
    slug: 'robot-structural-mechanics-materials-fatigue-thermal',
    title: '로봇 팔은 어디에서 휘고 지치는가: 구조·재료·피로',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: '로봇의 무게와 충격이 구조를 지나가는 길에서 시작해 휘어짐, 파손, 반복 피로, 진동과 열 변형을 계산하고 실물 측정으로 맞춥니다.',
    level: '중급',
    estimatedMinutes: 184,
    prerequisites: ['힘·회전시키는 힘·에너지와 단위의 기본', '관절의 강성·베어링·브레이크가 하는 일', '물체가 흔들리는 고유 진동의 직관'],
    learningPath: 'ai-robot-structural-mechanics',
    sections: [
      { id: 'load-path', title: 'Load case와 자유물체도' },
      { id: 'stress-strain', title: 'Stress·strain·displacement' },
      { id: 'section-mechanics', title: '단면 기하·bending·deflection' },
      { id: 'combined-loading', title: 'Torsion과 combined stress' },
      { id: 'local-stability', title: 'Notch·allowable·buckling' },
      { id: 'bolted-joints', title: 'Preload·slip·separation' },
      { id: 'fatigue-spectrum', title: 'Mission spectrum과 fatigue' },
      { id: 'structural-dynamics', title: 'Mode·excitation·damping' },
      { id: 'fea-evidence', title: 'FEA convergence와 evidence' },
      { id: 'thermal-mechanics', title: 'Heat·expansion·preload drift' },
      { id: 'evidence-closure', title: 'Physical correlation과 revision' },
    ],
    component: () => import('@/pages/articles/ai/robot-structural-mechanics-materials-fatigue-thermal'),
  },
  {
    slug: 'research-nasa-preloaded-bolt-load-introduction-2025',
    title: '현재 리서치 · NASA (2025): Preloaded Bolt Load Introduction',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'NASA/TM-20250005284 전체 112쪽에서 preload, clamping·relieving stiffness paths, SBLIF·GLIF, thermal load, FEA slope and experiment를 유도 순서와 unconservative boundary까지 복원합니다.',
    level: '심화',
    estimatedMinutes: 126,
    prerequisites: ['Axial stiffness와 compatibility', 'Bolt preload·contact·separation의 기본', 'FEA와 experiment evidence를 구분하는 능력'],
    learningPath: 'ai-robot-structural-mechanics-source-spine',
    sections: [
      { id: 'context', title: 'GLIF 이전 기준선과 저자 의도' },
      { id: 'claim', title: 'Clamping·relieving load-path 구조' },
      { id: 'mechanism', title: 'SBLIF·thermal·bolt-load 수식' },
      { id: 'evidence', title: 'FEA·experiment 비교와 경계' },
      { id: 'reproduction', title: 'Preloaded joint 재현 절차' },
      { id: 'legacy', title: 'Current joint analysis로의 전이' },
    ],
    component: () => import('@/pages/articles/ai/research-nasa-preloaded-bolt-load-introduction-2025'),
  },
  {
    slug: 'paper-manson-double-linear-fatigue-1967',
    title: '원 논문 · Manson et al. (1967): Double Linear Fatigue Damage',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'Miner linear sum의 load-order 맹점에서 시작해 initiation/propagation two-phase rule, maraging·SAE 4130 evidence, experimentally defined Phase I/II revision과 smooth 1/4-inch specimen 한계를 41쪽 원문 전체로 복원합니다.',
    level: '심화',
    estimatedMinutes: 112,
    prerequisites: ['Stress cycle·S-N curve·fatigue life fraction', '선형 누적 손상과 mission spectrum', '실험 curve와 model assumption을 분리하는 능력'],
    learningPath: 'ai-robot-structural-mechanics-source-spine',
    sections: [
      { id: 'context', title: 'Miner rule의 order-effect 병목' },
      { id: 'claim', title: 'A-B-C two-phase architecture' },
      { id: 'mechanism', title: 'N₀·ΔN·Phase sum 수식' },
      { id: 'evidence', title: '재료·stress order evidence' },
      { id: 'reproduction', title: 'Two-level and block 재현' },
      { id: 'legacy', title: 'Modern fatigue model로의 전이' },
    ],
    component: () => import('@/pages/articles/ai/paper-manson-double-linear-fatigue-1967'),
  },
  {
    slug: 'robot-fracture-mechanics-damage-tolerance',
    title: '작은 흠집은 언제 위험해지는가: 균열과 검사 주기',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: '검사에서 보인 흠집을 균열 모양으로 바꾸고, 남은 강도와 성장 속도, 검사 탐지 능력을 연결해 다음 검사 전까지 안전한지 판단합니다.',
    level: '심화',
    estimatedMinutes: 212,
    prerequisites: ['구조의 응력·반복 피로·해석 모델의 기본', '미분·적분과 저장 에너지의 직관', '확률과 실험 증거를 구분하는 능력'],
    learningPath: 'ai-robot-fracture-mechanics',
    sections: [
      { id: 'flaw-model', title: 'Indication과 crack geometry' },
      { id: 'energy-balance', title: 'Griffith energy balance' },
      { id: 'crack-tip-field', title: 'Crack-tip mode와 K field' },
      { id: 'geometry-factor', title: 'Geometry factor와 stress decomposition' },
      { id: 'constraint-toughness', title: 'Constraint와 fracture toughness' },
      { id: 'lefm-validity', title: 'Plastic zone와 LEFM validity' },
      { id: 'residual-strength', title: 'Residual strength와 critical crack' },
      { id: 'crack-growth', title: 'Subcritical crack growth regimes' },
      { id: 'spectrum-history', title: 'Spectrum order와 history state' },
      { id: 'fad', title: 'FAD와 residual stress' },
      { id: 'inspection', title: 'NDE POD와 inspection interval' },
      { id: 'evidence-ledger', title: 'Evidence와 traceability' },
    ],
    component: () => import('@/pages/articles/ai/robot-fracture-mechanics-damage-tolerance'),
  },
  {
    slug: 'paper-griffith-rupture-flow-solids-1921',
    title: '원 논문 · Griffith (1921): Rupture를 Energy Balance로 바꾸다',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: '37쪽 원문 전체에서 flaw-size energy criterion, glass bulb·fibre evidence, historical molecular speculation과 마지막 numerical correction note를 분리해 현대 균열역학의 출발점을 복원합니다.',
    level: '심화',
    estimatedMinutes: 116,
    prerequisites: ['Elastic strain energy와 potential energy', 'Crack geometry와 energy release rate', '원 논문 claim과 후대 해석을 분리하는 능력'],
    learningPath: 'ai-robot-fracture-mechanics-source-spine',
    sections: [
      { id: 'context', title: 'Ordinary strength criterion의 병목' },
      { id: 'claim', title: 'Elastic energy와 new surface 구조' },
      { id: 'mechanism', title: 'G·critical stress·size effect 수식' },
      { id: 'evidence', title: 'Glass bulbs·fibres와 correction' },
      { id: 'reproduction', title: 'Energy criterion 재현과 가정' },
      { id: 'legacy', title: 'Irwin LEFM으로 이어진 유산' },
    ],
    component: () => import('@/pages/articles/ai/paper-griffith-rupture-flow-solids-1921'),
  },
  {
    slug: 'research-nasa-nasgro-fitness-for-service-2025',
    title: '현재 리서치 · NASA (2025): NASGRO Crack-Like Flaw FFS',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'NASA/CR-20250011200 전체 109쪽에서 flaw idealization, SIF/FAD, full-range growth, residual stress, material·solution sensitivity와 unresolved NASGRO/INSPECT Lr 차이를 재구성합니다.',
    level: '심화',
    estimatedMinutes: 138,
    prerequisites: ['Stress-intensity factor와 toughness', 'Fatigue crack growth와 FAD', 'Solver result와 code/inspection evidence를 구분하는 능력'],
    learningPath: 'ai-robot-fracture-mechanics-source-spine',
    sections: [
      { id: 'context', title: 'API 579와 NASGRO 사이의 병목' },
      { id: 'claim', title: 'Flaw·SIF·FAD·growth architecture' },
      { id: 'mechanism', title: 'SIF·Kr/Lr·NASGRO growth 수식' },
      { id: 'evidence', title: 'Four examples와 solver discrepancy' },
      { id: 'reproduction', title: 'FFS 재현과 hidden inputs' },
      { id: 'legacy', title: 'Current damage-tolerance workflow' },
    ],
    component: () => import('@/pages/articles/ai/research-nasa-nasgro-fitness-for-service-2025'),
  },
  {
    slug: 'robot-composite-structures-joints-damage',
    title: '탄소섬유 로봇 팔을 설계하는 법: 적층·연결·손상',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: '한 방향으로 강한 얇은 층을 돌려 쌓아 전체 판을 만드는 과정부터 볼트 구멍, 접착부, 층간 박리와 보이지 않는 충격 손상까지 연결합니다.',
    level: '심화',
    estimatedMinutes: 236,
    prerequisites: ['구조의 힘 전달·응력·피로·열 변형의 기본', '행렬로 좌표를 바꾸고 두께 방향으로 더하는 법', '균열 에너지와 비파괴 검사의 기본'],
    learningPath: 'ai-robot-composite-structures',
    sections: [
      { id: 'material-hierarchy', title: 'Fibre·matrix·interface와 material axes' },
      { id: 'off-axis-lamina', title: 'Off-axis lamina와 Qbar' },
      { id: 'laminate-abd', title: 'Laminate A·B·D' },
      { id: 'coupling-ply-recovery', title: 'Coupling과 ply recovery' },
      { id: 'hygrothermal', title: 'Hygrothermal residual state' },
      { id: 'ply-failure', title: 'Ply failure criteria' },
      { id: 'progressive-damage', title: 'Progressive damage boundary' },
      { id: 'joints-holes', title: 'Holes·fasteners·inserts' },
      { id: 'delamination', title: 'Bonded joint와 delamination' },
      { id: 'impact-cai', title: 'BVID와 compression after impact' },
      { id: 'manufacturing-nde', title: 'Manufacturing flaws와 NDE' },
      { id: 'building-block', title: 'Building-block release evidence' },
    ],
    component: () => import('@/pages/articles/ai/robot-composite-structures-joints-damage'),
  },
  {
    slug: 'paper-tsai-strength-characteristics-composites-1965',
    title: '원 자료 · Tsai (1965): Composite Strength를 Material Axes에서 Laminate로',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'NASA CR-224 전체 105쪽에서 measured X·Y·S, signed off-axis transformation, A/B/D thermal interaction, cross/angle-ply experiments와 저자가 밝힌 네 가지 한계를 복원합니다.',
    level: '심화',
    estimatedMinutes: 124,
    prerequisites: ['Orthotropic lamina와 coordinate transformation', 'Laminate A/B/D와 ply stress recovery', 'Source-era model과 modern damage law를 구분하는 능력'],
    learningPath: 'ai-robot-composite-structures-source-spine',
    sections: [
      { id: 'context', title: 'Netting estimate의 병목과 저자 의도' },
      { id: 'claim', title: 'Lamina-to-laminate 계산 구조' },
      { id: 'mechanism', title: 'Transformation·A/B/D·thermal 수식' },
      { id: 'evidence', title: 'Off-axis·cross-ply·angle-ply evidence' },
      { id: 'reproduction', title: '1965 method 재현과 가정' },
      { id: 'legacy', title: '남은 mechanics와 교체된 damage model' },
    ],
    component: () => import('@/pages/articles/ai/paper-tsai-strength-characteristics-composites-1965'),
  },
  {
    slug: 'reference-nasa-composite-fracture-control-handbook-2024',
    title: '현재 자료 · NASA (2024): Composite Damage Tolerance Handbook',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'NASA-HDBK-5010 Rev A 907쪽에서 BBA, DTA·IDMP·RTD, impact/CAI, NDE·proof boundary, delamination VCCT/CZM와 example-specific transfer limits를 재구성합니다.',
    level: '심화',
    estimatedMinutes: 152,
    prerequisites: ['Composite ply/joint/delamination mechanics', 'NDE와 representative flaw의 기본', 'Analysis·test·certification claim을 구분하는 능력'],
    learningPath: 'ai-robot-composite-structures-source-spine',
    sections: [
      { id: 'context', title: 'Composite fracture-control 병목과 handbook 의도' },
      { id: 'claim', title: 'DTA·IDMP·RTD·BBA architecture' },
      { id: 'mechanism', title: 'Delamination·margin·traceability 수식' },
      { id: 'evidence', title: 'Impact·joint·COPV examples와 경계' },
      { id: 'reproduction', title: 'Damage-tolerance evidence 재현' },
      { id: 'legacy', title: 'Current production evidence workflow' },
    ],
    component: () => import('@/pages/articles/ai/reference-nasa-composite-fracture-control-handbook-2024'),
  },
  {
    slug: 'robot-contact-tribology-lubrication-wear',
    title: '기어와 베어링은 왜 닳는가: 접촉·윤활·마모',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: '기어·베어링·씰이 맞닿는 작은 영역의 압력과 움직임에서 시작해 기름막, 마찰열, 마모 조각, 오염과 수명 변화를 추적합니다.',
    level: '심화',
    estimatedMinutes: 228,
    prerequisites: ['관절의 회전력·속도·베어링 힘의 기본', '응력·탄성 변형·반복 피로의 기본', '열평형·미분방정식·통계 증거를 구분하는 능력'],
    learningPath: 'ai-robot-contact-tribology',
    sections: [
      { id: 'contact-inventory', title: 'Contact pair와 local load' },
      { id: 'hertz-contact', title: 'Hertz patch·pressure·approach' },
      { id: 'rough-surfaces', title: 'Roughness·real area·running-in' },
      { id: 'contact-kinematics', title: 'Entrainment·sliding·reversal' },
      { id: 'viscosity-state', title: 'Viscosity temperature-pressure state' },
      { id: 'film-regimes', title: 'Reynolds wedge와 four regimes' },
      { id: 'minimum-film', title: 'Minimum film과 lambda' },
      { id: 'starvation-grease', title: 'Starvation·grease replenishment' },
      { id: 'friction-thermal-loop', title: 'Friction-power-thermal feedback' },
      { id: 'life-wear-damage', title: 'Rating life와 wear modes' },
      { id: 'seals-contamination', title: 'Seal·contamination·debris' },
      { id: 'evidence-release', title: 'Observer·rigs·release evidence' },
    ],
    component: () => import('@/pages/articles/ai/robot-contact-tribology-lubrication-wear'),
  },
  {
    slug: 'paper-hamrock-dowson-film-regimes-1978',
    title: '원 논문 · Hamrock-Dowson (1978): Elliptical Contact의 Four Film Regimes',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'NASA TP-1342 전체 26쪽에서 H/U/W/G/k, reduced gV/gE, IR·VR·IE·VE limiting equations, minimum/central film and k별 regime map을 원문 표기와 transfer boundary까지 복원합니다.',
    level: '심화',
    estimatedMinutes: 124,
    prerequisites: ['Hertz contact와 local curvature', 'Viscosity-temperature-pressure와 film formation', 'Dimensionless group와 log-log map의 기본'],
    learningPath: 'ai-robot-contact-tribology-source-spine',
    sections: [
      { id: 'context', title: 'Scattered film equations의 병목과 저자 의도' },
      { id: 'claim', title: 'H/U/W/G/k에서 regime map까지' },
      { id: 'mechanism', title: 'Reduced parameters와 limiting 수식' },
      { id: 'evidence', title: '17/34 cases·k maps와 evidence 경계' },
      { id: 'reproduction', title: 'Equation identity 재현과 hidden assumptions' },
      { id: 'legacy', title: 'Modern EHL로 이어진 유산' },
    ],
    component: () => import('@/pages/articles/ai/paper-hamrock-dowson-film-regimes-1978'),
  },
  {
    slug: 'research-skf-bearing-conversion-layers-2023',
    title: '회사 리서치 · SKF (2023): Running-in Surface와 Bearing Friction',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'SKF RTD의 CC BY 논문 전체 JATS·14 figures·9 tables에서 TBO·MnPh·ZnCaPh의 hardness, rougher-side placement, fretting/WAM/double-CRB rigs, track roughness, up-to-30% headline와 condition-specific 75% result를 재구성합니다.',
    level: '심화',
    estimatedMinutes: 128,
    prerequisites: ['Contact pressure·roughness·mixed lubrication', 'Running-in과 bearing friction torque', 'Company research의 claim·evidence·transfer boundary를 구분하는 능력'],
    learningPath: 'ai-robot-contact-tribology-source-spine',
    sections: [
      { id: 'context', title: 'Conversion-layer friction 병목과 저자 의도' },
      { id: 'claim', title: 'Surface-to-bearing evidence architecture' },
      { id: 'mechanism', title: 'SRR·lambda·roughness·torque 수식' },
      { id: 'evidence', title: 'Fretting·WAM·bearing evidence와 adverse variants' },
      { id: 'reproduction', title: 'Rig domains와 transfer contract' },
      { id: 'legacy', title: 'Current surface-engineering workflow' },
    ],
    component: () => import('@/pages/articles/ai/research-skf-bearing-conversion-layers-2023'),
  },
  {
    slug: 'robot-system-verification-validation-qualification',
    title: 'Robot System Verification & Qualification: 요구사항에서 Release Evidence까지',
    subcategory: 'ai-robotics-mechanics-qualification',
    summary: 'Mission·ODD에서 measurable requirements, interface budgets, hazards, V&V, test ladder, environmental tailoring, reliability confidence, AI TEVV, configuration and field monitoring까지 하나의 release case로 연결합니다.',
    level: '심화',
    estimatedMinutes: 196,
    prerequisites: ['Robot AI subsystem의 역할 경계', '확률·통계와 confidence의 기본', 'Hardware/software test와 failure mode의 기본'],
    learningPath: 'ai-robot-system-verification-qualification',
    sections: [
      { id: 'mission-odd', title: 'Mission·ConOps·ODD' },
      { id: 'requirements-budgets', title: 'Atomic requirements와 budgets' },
      { id: 'traceability', title: 'Traceability와 interface ownership' },
      { id: 'hazard-risk', title: 'Hazard chain과 risk reduction' },
      { id: 'failure-logic', title: 'FMEA·FTA·common cause' },
      { id: 'verification-validation', title: 'Verification·validation·methods' },
      { id: 'evidence-ladder', title: 'SIL·HIL·subsystem·full robot' },
      { id: 'environment-tailoring', title: 'Environmental tailoring' },
      { id: 'reliability-confidence', title: 'Reliability와 confidence' },
      { id: 'ai-tevv', title: 'AI와 autonomy TEVV' },
      { id: 'configuration-regression', title: 'Configuration·anomaly·regression' },
      { id: 'release-field', title: 'Release case와 field feedback' },
    ],
    component: () => import('@/pages/articles/ai/robot-system-verification-validation-qualification'),
  },
  {
    slug: 'robot-camera-geometry-calibration',
    title: '사진의 한 점을 로봇의 3D 위치로 바꾸는 법: 카메라 기하와 보정',
    subcategory: 'ai-robotics-perception-state',
    summary: '사진 속 한 점은 방향만 알려 주고 거리는 알려 주지 않습니다. 방향과 거리를 복원하고, 사진을 찍은 순간의 카메라 위치를 이용해 로봇 몸체 기준의 3차원 점으로 옮깁니다.',
    level: '중급',
    estimatedMinutes: 96,
    prerequisites: ['화살표와 표로 위치 변화를 나타내는 벡터·행렬', '여러 측정값 사이의 오차를 가장 작게 맞춘다는 직관', '어느 기준에서 언제 측정했는지 구분하는 습관'],
    learningPath: 'ai-robot-camera-calibration',
    sections: [
      { id: 'pixel-ray', title: 'Pixel과 projective ray' },
      { id: 'image-geometry', title: 'Intrinsic과 image geometry' },
      { id: 'distortion', title: 'Lens distortion과 rectification' },
      { id: 'planar-calibration', title: 'Planar multi-view calibration' },
      { id: 'validation', title: 'Reprojection과 holdout 검증' },
      { id: 'hand-eye', title: 'Hand-eye AX=XB' },
      { id: 'time-alignment', title: 'Acquisition time과 rolling shutter' },
      { id: 'metric-uncertainty', title: 'Metric point와 uncertainty gate' },
    ],
    component: () => import('@/pages/articles/ai/robot-camera-geometry-calibration'),
  },
  {
    slug: 'paper-zhang-camera-calibration-2000',
    title: '원 논문 · Zhang (2000): 평면 Homography로 Camera Calibration하기',
    subcategory: 'ai-robotics-perception-state',
    summary: '서로 다른 orientation의 planar homography가 intrinsic constraint를 만드는 이유, closed-form Vb=0과 reprojection refinement, pose degeneracy와 target non-planarity를 원문 증거로 복원합니다.',
    level: '심화',
    estimatedMinutes: 66,
    prerequisites: ['Pinhole projection과 intrinsic matrix', 'Homography와 homogeneous coordinate', 'Least squares·SVD와 reprojection residual'],
    learningPath: 'ai-robot-camera-calibration-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: '원문 경계와 Localization으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-zhang-camera-calibration-2000'),
  },
  {
    slug: 'robot-localization-slam',
    title: '움직이며 자기 위치를 잃지 않는 법: 위치 추정과 SLAM',
    subcategory: 'ai-robotics-perception-state',
    summary: '바퀴 회전만 더하면 작은 오차가 계속 쌓입니다. 카메라와 거리 센서로 익숙한 장소를 다시 확인해 현재 위치와 지도를 함께 고치는 과정을 차근차근 설명합니다.',
    level: '중급',
    estimatedMinutes: 124,
    prerequisites: ['서로 다른 기준에서 위치와 방향을 표현하는 법', '측정에는 오차 범위가 있다는 직관', '센서가 일정한 간격과 약간의 지연을 두고 도착한다는 직관'],
    learningPath: 'ai-robot-localization-slam',
    sections: [
      { id: 'problem-contract', title: 'Odometry·localization·mapping·SLAM' },
      { id: 'measurement-time', title: 'Acquisition time과 deskew' },
      { id: 'dead-reckoning', title: 'Dead reckoning과 covariance drift' },
      { id: 'fusion', title: 'Innovation·gate·correlation' },
      { id: 'frame-split', title: 'map·odom·base_link 분리' },
      { id: 'front-end', title: 'Scan matching과 observability' },
      { id: 'factor-graph', title: 'Pose graph·gauge·global solve' },
      { id: 'loop-closure', title: 'Robust loop closure' },
      { id: 'rebase-health', title: 'Atomic rebase와 localization health' },
    ],
    component: () => import('@/pages/articles/ai/robot-localization-slam'),
  },
  {
    slug: 'paper-lu-milios-scan-alignment-1997',
    title: '원 논문 · Lu & Milios (1997): Pose Relation Network로 Global Scan Alignment하기',
    subcategory: 'ai-robotics-perception-state',
    summary: 'Local scans와 odometry/scan-match relation의 uncertainty를 보존하고, gauge를 고정한 maximum-likelihood global solve로 loop inconsistency를 모든 poses에 분산하는 원 논문을 복원합니다.',
    level: '심화',
    estimatedMinutes: 84,
    prerequisites: ['SE(2) pose composition', 'Covariance-weighted least squares', 'Scan matching과 graph의 기본'],
    learningPath: 'ai-robot-localization-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'Pose graph와 robust SLAM으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-lu-milios-scan-alignment-1997'),
  },
  {
    slug: 'robot-perception-scene-construction',
    title: '사진 속 물체를 로봇이 피할 3D 세계로 만드는 법',
    subcategory: 'ai-robotics-perception-state',
    summary: '사진에 보인 물체의 윤곽과 거리를 로봇 기준 3차원 위치로 옮기고, 같은 물체의 움직임과 빈 공간의 증거를 이어 안전한 장면으로 만듭니다.',
    level: '중급',
    estimatedMinutes: 112,
    prerequisites: ['Camera ray·depth·acquisition-time transform', 'Probability·log odds·covariance', 'State prediction과 one-to-one assignment의 직관'],
    learningPath: 'ai-robot-perception-scene',
    sections: [
      { id: 'observation-contract', title: 'Model output과 observation contract' },
      { id: 'metric-support', title: 'Mask·depth에서 3D support로' },
      { id: 'association', title: 'Prediction·gate·assignment' },
      { id: 'track-lifecycle', title: 'Occlusion과 track lifecycle' },
      { id: 'scene-representations', title: 'Planner query와 scene 표현' },
      { id: 'inverse-sensor-model', title: 'Ray의 free·occupied·unknown' },
      { id: 'occupancy-fusion', title: 'Bounded log-odds와 octree' },
      { id: 'static-dynamic-layers', title: 'Static·dynamic scene layers' },
      { id: 'planning-scene-snapshot', title: 'Atomic PlanningScene snapshot' },
    ],
    component: () => import('@/pages/articles/ai/robot-perception-scene-construction'),
  },
  {
    slug: 'paper-octomap-2013',
    title: '원 논문 · OctoMap (2013): 확률적 3D Occupancy와 Octree',
    subcategory: 'ai-robotics-perception-state',
    summary: 'Range ray를 free·occupied·unknown evidence로 바꾸고 bounded log odds, reversible pruning과 conservative multi-resolution query를 원문 실험 범위까지 복원합니다.',
    level: '심화',
    estimatedMinutes: 72,
    prerequisites: ['Probability·odds·logarithm', 'Range sensor ray와 voxel', 'Tree 구조와 spatial resolution'],
    learningPath: 'ai-robot-perception-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: '동적·semantic scene으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-octomap-2013'),
  },
  {
    slug: 'robot-kinematics-coordinate-frames',
    title: '카메라의 한 점을 로봇 관절 움직임으로 바꾸는 법',
    subcategory: 'ai-robotics-perception-state',
    summary: '서로 다른 기준에서 표현한 같은 점을 옮기고, 손끝이 목표에 닿게 하는 관절 각도와 속도를 구한 뒤 위험한 자세를 판별합니다.',
    level: '중급',
    estimatedMinutes: 78,
    prerequisites: ['벡터·행렬곱과 inverse', 'Rank·SVD·least squares', '미분과 Jacobian의 직관'],
    learningPath: 'ai-robot-kinematics',
    sections: [
      { id: 'frame-contract', title: 'Frame·time·unit contract' },
      { id: 'rigid-transform', title: 'Rigid transform와 tf2' },
      { id: 'forward-kinematics', title: 'Forward kinematics와 PoE' },
      { id: 'inverse-kinematics', title: 'Reachability와 numerical IK' },
      { id: 'jacobian', title: 'Jacobian과 singular values' },
      { id: 'singularity-dls', title: 'Singularity와 damped least squares' },
      { id: 'production-handoff', title: 'Planning·control handoff' },
    ],
    component: () => import('@/pages/articles/ai/robot-kinematics-coordinate-frames'),
  },
  {
    slug: 'paper-denavit-hartenberg-1955',
    title: '원 논문 · Denavit–Hartenberg (1955): 네 매개변수 운동학 표기의 탄생',
    subcategory: 'ai-robotics-perception-state',
    summary: 'Joint axis와 common normal에 frame을 제한해 lower-pair mechanism을 네 parameter matrix로 기술한 원 논문의 의도와 한계를 복원합니다.',
    level: '심화',
    estimatedMinutes: 48,
    prerequisites: ['Homogeneous transform', 'Forward kinematics', 'Revolute·prismatic joint'],
    learningPath: 'ai-robot-kinematics-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'D-H와 PoE의 경계' },
    ],
    component: () => import('@/pages/articles/ai/paper-denavit-hartenberg-1955'),
  },
  {
    slug: 'paper-whitney-coordinated-control-1972',
    title: '원 논문 · Whitney (1972): Task 좌표 명령을 Joint 속도로 바꾸기',
    subcategory: 'ai-robotics-perception-state',
    summary: 'Hand-coordinate rate를 inverse Jacobian과 weighted generalized inverse로 joint rate에 연결하고 singularity·redundancy의 경계를 읽습니다.',
    level: '심화',
    estimatedMinutes: 54,
    prerequisites: ['Forward kinematics와 Jacobian', 'Matrix inverse와 least squares', 'Joint velocity control'],
    learningPath: 'ai-robot-kinematics-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'DLS와 motion planning으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-whitney-coordinated-control-1972'),
  },
  {
    slug: 'robot-motion-planning',
    title: 'Robot Motion Planning: C-space에서 PRM·RRT와 실행 궤적까지',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Workspace 충돌을 configuration-space 문제로 바꾸고, state·edge validity, A-star, PRM·RRT, smoothing과 time parameterization을 하나의 실행 pipeline으로 연결합니다.',
    level: '중급',
    estimatedMinutes: 86,
    prerequisites: ['Robot coordinate frames와 forward kinematics', 'Graph와 vector distance의 기본', 'Joint limit와 feedback control의 구분'],
    learningPath: 'ai-robot-motion-planning',
    sections: [
      { id: 'pose-not-route', title: 'IK pose와 collision-free route' },
      { id: 'configuration-space', title: 'C-space와 C-obstacle' },
      { id: 'edge-validity', title: 'State와 edge validity' },
      { id: 'graph-search', title: 'Graph representation과 A-star' },
      { id: 'prm', title: 'Probabilistic Roadmap' },
      { id: 'rrt', title: 'Rapidly-Exploring Random Tree' },
      { id: 'guarantees', title: 'Completeness와 optimality' },
      { id: 'execution-handoff', title: 'Smoothing·timing·execution gate' },
    ],
    component: () => import('@/pages/articles/ai/robot-motion-planning'),
  },
  {
    slug: 'paper-lozano-perez-cspace-1983',
    title: '원 논문 · Lozano-Perez (1983): Configuration Space로 공간 계획 다시 쓰기',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Extended-body collision truth를 configuration point membership으로 보존하면서 obstacle shape·metric·timing은 어떻게 달라지는지, Findspace와 Findpath의 정확한 환원과 원 논문의 geometry evidence ceiling을 복원합니다.',
    level: '심화',
    estimatedMinutes: 58,
    prerequisites: ['Rigid transform와 configuration topology', 'Set intersection와 Minkowski sum', 'Graph shortest path와 clearance의 구분'],
    learningPath: 'ai-robot-motion-planning-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '보존되는 것과 바뀌는 표현' },
      { id: 'mechanism', title: 'Collision preimage와 safe path' },
      { id: 'evidence', title: 'Exact geometry의 증거 ceiling' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'Exact geometry에서 implicit validity로' },
    ],
    component: () => import('@/pages/articles/ai/paper-lozano-perez-cspace-1983'),
  },
  {
    slug: 'paper-kavraki-prm-1996',
    title: '원 논문 · Kavraki et al. (1996): 고차원 공간의 Probabilistic Roadmap',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Collision-free sampling·local planner·learning/query split을 복원하고, 1996 experiments와 later probabilistic-completeness 조건, LazyPRM·PRM* practice의 evidence layer를 분리합니다.',
    level: '심화',
    estimatedMinutes: 64,
    prerequisites: ['C-space collision preimage와 free path', 'Graph search·local planner·topology-aware metric', 'Sampling support와 조건부 확률'],
    learningPath: 'ai-robot-motion-planning-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: 'Sampling에서 query까지의 계약' },
      { id: 'mechanism', title: 'Node·edge·connector와 completeness 조건' },
      { id: 'evidence', title: '1996 evidence와 later theorem 경계' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'PRM에서 LazyPRM·PRM*으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-kavraki-prm-1996'),
  },
  {
    slug: 'robot-trajectory-generation',
    title: 'Robot Trajectory Generation: Path에 실행 가능한 시간을 붙이기',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Geometric path와 time scaling을 분리하고 cubic·quintic, waypoint continuity, 다관절 동기화, torque 기반 retiming과 jerk-limited online generation을 실행 계약으로 연결합니다.',
    level: '중급',
    estimatedMinutes: 92,
    prerequisites: ['Robot kinematics와 Jacobian', 'Motion planning의 geometric path', '부등식의 부호와 구간 교집합', '미분방정식·phase plane 수치 적분'],
    learningPath: 'ai-robot-trajectory-generation',
    sections: [
      { id: 'path-time', title: 'Path와 time scaling' },
      { id: 'boundary-conditions', title: 'Cubic·quintic 경계조건' },
      { id: 'waypoint-continuity', title: 'Waypoint와 derivative 연속성' },
      { id: 'limit-retiming', title: 'Joint limit와 동기화' },
      { id: 'dynamic-retiming', title: 'Torque 기반 time-optimal retiming' },
      { id: 'jerk-online', title: 'Jerk-limited online generation' },
      { id: 'execution-contract', title: 'Production 실행 계약' },
    ],
    component: () => import('@/pages/articles/ai/robot-trajectory-generation'),
  },
  {
    slug: 'paper-shin-mckay-time-optimal-1985',
    title: '원 논문 · Shin & McKay (1985): 고정 경로의 Minimum-Time Retiming',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Specified geometric path의 full manipulator dynamics를 scalar path-acceleration bound로 바꾸고 forward·backward switching으로 minimum-time profile을 만든 원 논문을 복원합니다.',
    level: '심화',
    estimatedMinutes: 62,
    prerequisites: ['Path와 trajectory의 구분', 'Robot dynamics와 torque', '미분방정식·수치 적분·phase plane의 기본'],
    learningPath: 'ai-robot-trajectory-generation-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: 'TOPP와 online generation으로' },
    ],
    component: () => import('@/pages/articles/ai/paper-shin-mckay-time-optimal-1985'),
  },
  {
    slug: 'robot-dynamics-feedback-control',
    title: '로봇이 목표 움직임을 계속 따라가게 하는 법: 피드백 제어',
    subcategory: 'ai-robotics-planning-control',
    summary: '한 번의 명령이 실제 세계에서 어긋나는 이유부터 시작해, 결과를 다시 측정하며 PID·LQR·MPC로 안정적인 다음 입력을 만드는 과정을 연결합니다.',
    level: '중급',
    estimatedMinutes: 72,
    prerequisites: ['벡터·행렬곱과 eigenvalue의 직관', '신호와 시스템의 memory·sampling', 'POMDP와 Kalman state estimation'],
    learningPath: 'ai-robot-control',
    sections: [
      { id: 'plant-loop', title: '왜 폐루프가 필요한가?' },
      { id: 'state-space', title: '상태공간으로 plant 쓰기' },
      { id: 'stability-feedback', title: 'Feedback과 안정성' },
      { id: 'structural-tests', title: '제어·관측가능성' },
      { id: 'pid', title: 'PID와 anti-windup' },
      { id: 'lqr', title: 'LQR과 Riccati recursion' },
      { id: 'mpc', title: 'Constrained MPC' },
      { id: 'estimator-controller', title: '추정기와 controller 결합' },
    ],
    component: () => import('@/pages/articles/ai/robot-dynamics-feedback-control'),
  },
  {
    slug: 'paper-kalman-optimal-control-1960',
    title: '원 논문 · Kalman (1960): 제어가능성·관측가능성과 최적 Regulator',
    subcategory: 'ai-robotics-planning-control',
    summary: '정확한 full state를 가정한 Problem (B), controllability·dual observability, quadratic value와 Riccati feedback, infinite-horizon stability의 조건을 원문 정리별로 분리합니다.',
    level: '심화',
    estimatedMinutes: 72,
    prerequisites: ['Continuous-time 상태공간 model', '행렬 rank·positive definiteness와 transition matrix', 'Quadratic objective·Hamilton-Jacobi의 직관'],
    learningPath: 'ai-robot-control-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: '남은 것과 교체된 것' },
    ],
    component: () => import('@/pages/articles/ai/paper-kalman-optimal-control-1960'),
  },
  {
    slug: 'paper-mayne-mpc-2000',
    title: '원 논문 · Mayne et al. (2000): 제약 MPC의 조건부 안정성과 최적성',
    subcategory: 'ai-robotics-planning-control',
    summary: 'Survey 원문의 A1-A4와 shifted-candidate proof를 복원해 nominal recursive feasibility·stability의 충분조건을 닫고, 선형 QP·비선형 NLP·후대 deployment 관행의 증거 범위를 분리합니다.',
    level: '심화',
    estimatedMinutes: 68,
    prerequisites: ['Discrete 상태공간과 feedback stability', 'LQR·Lyapunov value decrease', 'Feasible set과 제약 최적화'],
    learningPath: 'ai-robot-control-paper-spine',
    sections: [
      { id: 'context', title: '논문 이전의 병목과 저자 의도' },
      { id: 'claim', title: '주장과 계산 구조' },
      { id: 'mechanism', title: '핵심 수식과 구현 의미' },
      { id: 'evidence', title: '증거와 입증 범위' },
      { id: 'reproduction', title: '재현과 숨은 가정' },
      { id: 'legacy', title: '남은 것과 교체된 것' },
    ],
    component: () => import('@/pages/articles/ai/paper-mayne-mpc-2000'),
  },
  {
    slug: 'post-training-rlvr',
    title: 'Post-training 신호 선택: RAG·CPT에서 SFT·DPO·RLVR까지',
    subcategory: 'ai-llm-post-training-foundation',
    summary: '지식 부족, 정답 demonstration, 상대 선호, 실행 가능한 verifier를 구분해 RAG·CPT·SFT·DPO/RLHF·RLVR 중 첫 신호와 조합 순서를 결정한다.',
    level: '기초',
    estimatedMinutes: 38,
    prerequisites: ['다음 토큰 예측이 언어 모델 학습의 기본 목표라는 이해', '확률이 높을수록 토큰이 더 자주 선택된다는 감각'],
    learningPath: 'ai-llm-post-training-current-first',
    sections: [
      { id: 'evidence-first', title: '방법보다 부족한 증거부터 묻기' },
      { id: 'knowledge-behavior', title: '지식과 행동을 분리하기' },
      { id: 'four-contracts', title: '네 feedback contract' },
      { id: 'compose-signals', title: '신호의 소유권을 조합하기' },
      { id: 'handoff', title: '알고리즘과 구현으로 내려가기' },
    ],
    component: () => import('@/pages/articles/ai/post-training-rlvr'),
  },
  {
    slug: 'moe-ssd-streaming',
    title: 'MoE SSD Streaming: RAM보다 큰 모델을 일부씩 읽어 실행하는 법',
    subcategory: 'ai-llm-architectures-moe',
    summary: 'total parameter, active compute, resident weights를 분리하고 router·cache·prefetch·random I/O 병목을 추적한다.',
    level: '중급',
    estimatedMinutes: 24,
    prerequisites: ['Dense Transformer의 FFN이 큰 가중치 행렬이라는 이해', 'RAM이 SSD보다 빠른 작업 메모리라는 이해'],
    learningPath: 'ai-llm-moe-ssd-streaming',
    sections: [
      { id: 'three-numbers', title: '744B·40B·25GB는 왜 동시에 참일 수 있을까?' },
      { id: 'router-working-set', title: 'Router는 어떤 weight가 필요한지 어떻게 정할까?' },
      { id: 'memory-tiers', title: 'VRAM·RAM·SSD를 한 계층으로 쓰면 무슨 일이 일어날까?' },
      { id: 'cache-prefetch', title: 'Cache와 prefetch는 대기를 얼마나 숨길 수 있을까?' },
      { id: 'honest-throughput', title: '왜 빠른 SSD에서도 대화 속도는 느릴까?' },
      { id: 'fit-check', title: '어떤 작업에 쓸 수 있고 무엇을 먼저 계산해야 할까?' },
    ],
    component: () => import('@/pages/articles/ai/moe-ssd-streaming'),
  },
];
