import type { Article } from "../types";

// ── NLP & Attention ──
export const dlNlpArticles: Article[] = [
  {
    slug: "distributional-semantics",
    title: "분산 의미론: 동시발생 행렬에서 단어 벡터까지",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "가정·측정·의미 경계" },
      { id: "distributional", title: "Context matrix·PMI" },
      { id: "dimensionality", title: "SVD·cosine·평가 경계" },
      { id: "neural-approach", title: "SGNS·GloVe·contextual 연결" },
    ],
    component: () => import("@/pages/articles/ai/distributional-semantics"),
  },
  {
    slug: "rnn",
    title: "RNN 기초: hidden state와 시간축 계산",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Hidden state는 무엇을 기억하는가" },
      { id: "architecture", title: "Parameter 공유와 시간축 계산" },
    ],
    component: () => import("@/pages/articles/ai/rnn"),
  },
  {
    slug: "rnn-language-model",
    title: "RNN Language Model: shifted token에서 perplexity까지",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "입력과 정답을 한 칸 이동" },
      { id: "language-model", title: "State·logits·NLL·perplexity" },
    ],
    component: () => import("@/pages/articles/ai/rnn-language-model"),
  },
  {
    slug: "bptt",
    title: "BPTT: 시간축 gradient와 truncation",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "시간축 credit assignment" },
      { id: "bptt", title: "Jacobian·clipping·detach" },
    ],
    component: () => import("@/pages/articles/ai/bptt"),
  },
  {
    slug: "lstm",
    title: "LSTM: 장기 의존성을 학습하는 게이트 구조",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "두 recurrent state의 계산 계약" },
      { id: "gates", title: "Channel별 보존·기록·공개 정책" },
      { id: "cell-state", title: "Forget gate와 direct gradient" },
    ],
    component: () => import("@/pages/articles/ai/lstm"),
  },
  {
    slug: "gru",
    title: "GRU: reset candidate와 update interpolation",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Reset과 update를 따로 보기" },
      { id: "state-update", title: "Candidate·interpolation·budget" },
    ],
    component: () => import("@/pages/articles/ai/gru"),
  },
  {
    slug: "seq2seq",
    title: "Seq2Seq: 시퀀스를 시퀀스로 변환",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "조건부 sequence probability" },
      { id: "encoder", title: "Encoder–decoder state handoff" },
      { id: "decoder", title: "Autoregressive decoding과 search" },
      { id: "training", title: "Teacher forcing과 prefix gap" },
      { id: "limitations", title: "Fixed context에서 attention으로" },
    ],
    component: () => import("@/pages/articles/ai/seq2seq"),
  },
  {
    slug: "attention-theory",
    title: "어텐션 메커니즘 이론: Bahdanau에서 Transformer까지",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Score → weight → aggregate" },
      { id: "additive", title: "Additive attention" },
      { id: "multiplicative", title: "Dot-product attention" },
      { id: "self-attention", title: "Self-attention과 multi-head" },
    ],
    component: () => import("@/pages/articles/ai/attention-theory"),
  },
  {
    slug: "tokenizer",
    title: "토크나이저: 텍스트를 토큰으로",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Text·pipeline·model 계약" },
      { id: "bpe", title: "BPE merge와 byte alphabet" },
      { id: "wordpiece", title: "WordPiece greedy match" },
      { id: "sentencepiece", title: "SentencePiece와 Unigram" },
      { id: "comparison", title: "Corpus 평가와 배포" },
    ],
    component: () => import("@/pages/articles/ai/tokenizer"),
  },
  {
    slug: "transformer-architecture",
    title: "Transformer 아키텍처",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Sequence 계산 경로" },
      { id: "input-contract", title: "ID·position·mask 계약" },
      { id: "position-information", title: "위치 신호의 개입 지점" },
      { id: "attention-boundary", title: "Source·visibility·비용" },
      { id: "transformer-block", title: "두 mixer·residual·norm" },
      { id: "output-head", title: "Logits·loss·decoding 경계" },
      { id: "training", title: "재현 가능한 training recipe" },
      { id: "scaling-laws", title: "Scaling law와 예산 목적" },
      { id: "next-reading", title: "다음 읽기 경로" },
    ],
    component: () => import("@/pages/articles/ai/transformer-architecture"),
  },
  {
    slug: "bert",
    title: "BERT Encoder: 양방향 Visibility에서 Contextual State까지",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Token·Query·Visible Key" },
      { id: "visibility", title: "Bidirectional Attention 범위" },
      { id: "encoder-boundary", title: "Causal·Streaming 경계" },
      { id: "paper-bert", title: "원 논문의 증거 범위" },
    ],
    component: () => import("@/pages/articles/ai/bert"),
  },
  {
    slug: "bert-input-packing",
    title: "BERT Input Packing: Special Token과 네 Tensor",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "네 입력 Tensor" },
      { id: "special-tokens", title: "CLS·SEP·PAD" },
      { id: "aligned-tensors", title: "Embedding Row 합성" },
      { id: "boundary", title: "Checkpoint 입력 경계" },
    ],
    component: () => import("@/pages/articles/ai/bert-input-packing"),
  },
  {
    slug: "bert-mlm-corruption",
    title: "BERT MLM: 15% 선택과 80·10·10 Corruption",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Target과 Corrupted Input" },
      { id: "corruption", title: "두 단계 Sampling" },
      { id: "objective", title: "Selected-token NLL" },
      { id: "boundary", title: "Masking Recipe 경계" },
    ],
    component: () => import("@/pages/articles/ai/bert-mlm-corruption"),
  },
  {
    slug: "bert-pretraining-objectives",
    title: "BERT 후속 Objective: NSP·SOP·RTD 비교",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Supervision Unit" },
      { id: "nsp-sop", title: "Segment-level Label" },
      { id: "rtd", title: "Token-level Detection" },
      { id: "comparison", title: "공정한 Recipe 비교" },
    ],
    component: () => import("@/pages/articles/ai/bert-pretraining-objectives"),
  },
  {
    slug: "bert-task-heads",
    title: "BERT Task Heads: Sequence·Token·Span·Retrieval",
    subcategory: "ai-nlp",
    sections: [
      { id: "overview", title: "Prediction Unit" },
      { id: "task-head", title: "Sequence Head" },
      { id: "token-span", title: "Token·Span Head" },
      { id: "retrieval", title: "Cross·Bi Encoder" },
    ],
    component: () => import("@/pages/articles/ai/bert-task-heads"),
  },
];
