import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";

const Flow=()=> <figure data-viz="scroll-zkevm-proof-flow" className="not-prose rounded-xl border border-border bg-card p-4 sm:p-5"><figcaption className="mb-4 text-sm font-semibold">EVM ADD step에서 L1 validity-proof receipt까지</figcaption><div className="grid gap-3 sm:grid-cols-4">{[['01','Native trace','stack 3,4 → 7'],['02','Circuit tables','execution · RW · bytecode'],['03','Halo2 proof','gate · copy · lookup'],['04','L1 receipt','data · roots · VK']].map(([n,t,d])=><div key={n} className="min-w-0 rounded-lg border border-border bg-background p-4"><span className="text-xs font-semibold text-primary">{n}</span><p className="mt-2 break-words text-sm font-semibold">{t}</p><p className="mt-1 break-words text-xs text-muted-foreground">{d}</p></div>)}</div></figure>;

export default function ModernArticle(){return <article className="space-y-14">
  <section id="overview" className="space-y-5"><h2 className="text-3xl font-bold">Scroll zkEVM: EVM state transition을 table-linked witness로 다시 표현한다</h2><p className="text-lg leading-8">EVM이 stack의 3과 4를 ADD해 7을 만드는 한 step을 증명한다고 해 봅시다. Arithmetic row만 맞아서는 부족하며 opcode가 실제 bytecode에 있었고 operands가 스택에서 읽혔으며 result가 다음 machine state에 쓰였다는 사실까지 연결해야 합니다.</p><Flow/><p>이 글은 Halo2·validity proof의 수학을 다시 소유하지 않고, pinned Scroll zkevm-circuits source의 trace/table/witness·proof artifact 경계만 다룹니다. 해당 repository snapshot을 current production deployment와 자동 동일시하지 않습니다.</p></section>
  <section id="trace-tables" className="space-y-5"><h2 className="text-2xl font-bold">Local opcode equation과 global table consistency를 함께 강제한다</h2><p>ADD execution row는 before stack [3,4], opcode ADD, result 7, program-counter/gas·stack-pointer transition을 나타냅니다. RW table에는 stack reads 3·4와 write 7이 여러 event IDs와 함께 있고 bytecode table에는 해당 PC의 ADD opcode가 있어야 합니다. Gate·copy·lookup/permutation이 이 사실들을 연결합니다.</p><ExplainedFormula question="ADD row는 무엇을 강제하고 무엇을 table에 물어야 하는가?" idea={<>Local polynomial은 field에서 result relation을 강제하고, lookup/copy relations은 a·b·c가 같은 execution event의 bytecode·RW records에서 왔는지 강제합니다.</>} formula={String.raw`q_{ADD}(a+b-c)=0,\qquad (a,b,c,pc,rw)\in T_{\mathrm{EVM/RW/bytecode}}`}
  annotatedFormula={String.raw`q_{ADD}(a+b-c)=\underbrace{0,\qquad (a,b,c,pc,rw)\in T_{\mathrm{EVM/RW/bytecode}}}_{\text{기준량당 비율}}`}
  operations={[
    { expression: String.raw`0,\qquad (a,b,c,pc,rw)\in T_{\mathrm{EVM/RW/bytecode}}`, annotation: ["분자에 둔 관심량을 분모의 기준량으로 정규화합니다.","Local polynomial은 field에서 result","relation을 강제하고, lookup/copy","relations은 a·b·c가 같은 execution"] },
  ]} terms={[{symbol:"q_ADD",name:"Opcode selector",description:"ADD row에서만 local arithmetic relation을 활성화합니다."},{symbol:"a,b,c",name:"Stack operands·result",description:"Toy row에서 a=3,b=4,c=7입니다."},{symbol:"pc,rw",name:"Execution identities",description:"Bytecode position과 read/write events를 shared tables에 연결합니다."},{symbol:"T",name:"Shared tables",description:"Execution·RW·bytecode·transaction·block·state data의 pinned table family입니다."}]} assumptions={["Exact columns, selectors, lookup semantics와 field profile은 pinned circuit version에 귀속합니다.","Witness generator와 native EVM이 같은 fork·gas·opcode semantics를 사용합니다."]} interpretation="3+4-7=0이어도 RW table가 operand 5를 주거나 bytecode table의 opcode가 다르면 global relation이 fail해야 합니다. Local equation 하나는 EVM semantics 전체의 sufficient condition이 아닙니다." /></section>
  <section id="proof-artifact" className="space-y-5"><h2 className="text-2xl font-bold">State·data·circuit·key·aggregation layer를 proof에 결속한다</h2><p>Receipt에는 chain/fork, block·chunk identity와 limits, transaction-data commitment, pre-state root S, post-state root S′, public-input schema, trace/table shape, source·circuit·configuration·verifying-key hashes, proof/aggregation layer를 넣습니다. Valid proof를 다른 pre-root, data commitment, fork, VK에 붙이는 것은 다른 statement이므로 거절되어야 합니다.</p><p>Validity proof가 보이는 것은 pinned program의 transition S,T→S′입니다. Transaction data를 network에서 제때 얻을 수 있는지, sequencer가 계속 progress하는지, transaction content가 private한지는 각각 DA·liveness·privacy의 별도 질문입니다.</p></section>
  <section id="release" className="space-y-5"><h2 className="text-2xl font-bold">Native EVM·witness·circuit parity 후 stage cost를 측정한다</h2><p>Fork edge opcodes, stack underflow/overflow, memory/storage, gas/PC, invalid bytecode, state-root boundaries에 대해 native execution, witness generation, circuit accept/reject가 같은지 differential corpus로 확인합니다. Wrong ADD result·RW order·lookup·gas/PC·state root·public input·key/proof/aggregation mutation을 fail closed한 뒤 같은 fork, block/chunk limits, security profile, hardware에서 witness/prove/aggregate/verify time, peak RSS, proof bytes를 나뉩니다. Regression 시 이전 circuit/key/verifier manifest로 rollback합니다.</p><div id="paper-scroll-docs"><CitationBlock source="Scroll zkEVM Overview" citeKey={1} href="https://docs.scroll.io/en/technology/zkevm/zkevm-overview/"><p><b>문제:</b> Ethereum state transition을 validity proof로 검증하는 architecture를 설명합니다.</p><p><b>기여:</b> Initial state, transaction, result state와 proving layer의 official boundary를 제공합니다.</p><p><b>전제:</b> Official documentation의 해당 protocol/version context입니다.</p><p><b>근거 범위:</b> Scroll zkEVM state-transition·architecture claim입니다.</p><p><b>말하지 않는 것:</b> Pinned legacy circuit source와 current production release가 항상 동일하다고 주장하지 않습니다.</p></CitationBlock></div><div id="paper-scroll-source"><CitationBlock source="scroll-tech/zkevm-circuits pinned source 18f5bc2" citeKey={2} href="https://github.com/scroll-tech/zkevm-circuits/tree/18f5bc268ca11988690c7cf59fc4615372ce99f2"><p><b>문제:</b> Halo2 EVM trace/table/gadget implementation seam을 고정합니다.</p><p><b>기여:</b> Official circuit source·tests의 pinned snapshot입니다.</p><p><b>전제:</b> Commit 18f5bc2와 toolchain·features·circuit profile을 pin합니다.</p><p><b>근거 범위:</b> 선택 commit의 code structure/behavior입니다.</p><p><b>말하지 않는 것:</b> Current mainnet version·complete audit·moving main을 대신하지 않습니다.</p></CitationBlock></div></section>
</article>}
