import type { CodeRef, FileNode, ProjectMeta } from "@/components/code/types";
import runtime from "./codebase/mpyc/runtime.py?raw";
import thresha from "./codebase/mpyc/thresha.py?raw";
import sectypes from "./codebase/mpyc/sectypes.py?raw";
import call from "./verification/party.py?raw";
import round1 from "./codebase/tss-lib/ecdsa/keygen/round_1.go?raw";
import round3 from "./codebase/tss-lib/ecdsa/keygen/round_3.go?raw";
import vss from "./codebase/tss-lib/crypto/vss/feldman_vss.go?raw";
import message from "./codebase/tss-lib/tss/message.go?raw";
export const codeRefs:Record<string,CodeRef>={
"input":{code:runtime,"path": "mpyc/runtime.py", "highlight": [403, 510], "lang": "python", "desc": "input이 송신자를 정하고 _distribute가 원문 random_split으로 같은 4,3,5의 조각을 각 주소에 보냅니다.", "annotations": [{"lines": [403, 510], "color": "sky", "note": "input이 송신자를 정하고 _distribute가 원문 random_split으로 같은 4,3,5의 조각을 각 주소에 보냅니다."}]},
"split":{code:thresha,"path": "mpyc/thresha.py", "highlight": [23, 45], "lang": "python", "desc": "상수항과 새 계수로 다항식을 만든 뒤 주소 1부터 m까지 평가합니다. 검산 호출에서는 계수 2,5,3을 통제했습니다.", "annotations": [{"lines": [23, 45], "color": "sky", "note": "상수항과 새 계수로 다항식을 만든 뒤 주소 1부터 m까지 평가합니다. 검산 호출에서는 계수 2,5,3을 통제했습니다."}]},
"call":{code:call,"path": "case/party.py", "highlight": [12, 29], "lang": "python", "desc": "각 프로세스는 자기 입력 하나를 읽고 같은 (x+y)*z를 계산합니다. 실제 기본 난수로 실행했으며 output은 35입니다.", "annotations": [{"lines": [12, 29], "color": "sky", "note": "각 프로세스는 자기 입력 하나를 읽고 같은 (x+y)*z를 계산합니다. 실제 기본 난수로 실행했으며 output은 35입니다."}]},
"arithmetic":{code:runtime,"path": "mpyc/runtime.py", "highlight": [1010, 1098], "lang": "python", "desc": "add는 두 조각을 더합니다. mul은 조각 곱 뒤 비밀 피연산자일 때 _reshare를 호출합니다.", "annotations": [{"lines": [1010, 1098], "color": "sky", "note": "add는 두 조각을 더합니다. mul은 조각 곱 뒤 비밀 피연산자일 때 _reshare를 호출합니다."}]},
"reshare":{code:runtime,"path": "mpyc/runtime.py", "highlight": [601, 693], "lang": "python", "desc": "2t+1명의 곱 조각을 다시 나눠 받은 점들을 재결합합니다. t=1인 이번 실행에서는 세 명이 모두 참여합니다.", "annotations": [{"lines": [601, 693], "color": "sky", "note": "2t+1명의 곱 조각을 다시 나눠 받은 점들을 재결합합니다. t=1인 이번 실행에서는 세 명이 모두 참여합니다."}]},
"recombine":{code:thresha,"path": "mpyc/thresha.py", "highlight": [67, 118], "lang": "python", "desc": "주소에서 보간 무게를 구한 뒤 같은 열의 값들을 합칩니다. 주소 1,2,3의 0에서의 무게는 mod67에서 3,64,1입니다.", "annotations": [{"lines": [67, 118], "color": "sky", "note": "주소에서 보간 무게를 구한 뒤 같은 열의 값들을 합칩니다. 주소 1,2,3의 0에서의 무게는 mod67에서 3,64,1입니다."}]},
"output":{code:runtime,"path": "mpyc/runtime.py", "highlight": [512, 598], "lang": "python", "desc": "지정한 수신자는 다른 t개와 자기 조각을 합쳐 t+1개로 복원합니다. 기본 수신자는 모든 참여자입니다.", "annotations": [{"lines": [512, 598], "color": "sky", "note": "지정한 수신자는 다른 t개와 자기 조각을 합쳐 t+1개로 복원합니다. 기본 수신자는 모든 참여자입니다."}]},
"type":{code:sectypes,"path": "mpyc/sectypes.py", "highlight": [568, 627], "lang": "python", "desc": "SecFld(67)의 기본 signed=False는 체의 값을 0부터 66까지 읽도록 정합니다. 부호 표현과 체 연산을 구분합니다.", "annotations": [{"lines": [568, 627], "color": "sky", "note": "SecFld(67)의 기본 signed=False는 체의 값을 0부터 66까지 읽도록 정합니다. 부호 표현과 체 연산을 구분합니다."}]},
"dkg-start":{code:round1,"path": "tss/ecdsa/keygen/round_1.go", "highlight": [39, 110], "lang": "go", "desc": "키 기여분과 VSS를 준비합니다. 세션 nonce는 호출자가 주면 복사하고 없으면 0이므로 매번 고유하게 생성된다고 가정할 수 없습니다.", "annotations": [{"lines": [39, 110], "color": "sky", "note": "키 기여분과 VSS를 준비합니다. 세션 nonce는 호출자가 주면 복사하고 없으면 0이므로 매번 고유하게 생성된다고 가정할 수 없습니다."}]},
"dkg-verify":{code:round3,"path": "tss/ecdsa/keygen/round_3.go", "highlight": [32, 130], "lang": "go", "desc": "받은 조각을 Xi에 합친 뒤 약속과 VSS·증명 설정을 확인합니다. 이 Go 경로는 읽기만 했으며 실행하지 않았습니다.", "annotations": [{"lines": [32, 130], "color": "sky", "note": "받은 조각을 Xi에 합친 뒤 약속과 VSS·증명 설정을 확인합니다. 이 Go 경로는 읽기만 했으며 실행하지 않았습니다."}]},
"vss":{code:vss,"path": "tss/crypto/vss/feldman_vss.go", "highlight": [95, 113], "lang": "go", "desc": "조각의 스칼라곱이 공개 계수 약속의 주소별 합과 같은지 확인합니다. 본문의 작은 곱셈군 예와 실제 곡선 구현은 구분합니다.", "annotations": [{"lines": [95, 113], "color": "sky", "note": "조각의 스칼라곱이 공개 계수 약속의 주소별 합과 같은지 확인합니다. 본문의 작은 곱셈군 예와 실제 곡선 구현은 구분합니다."}]},
"transport":{code:message,"path": "tss/tss/message.go", "highlight": [18, 64], "lang": "go", "desc": "송신자·수신자와 방송 표시를 전송 계층에 넘깁니다. README가 요구하는 실행 식별·암호화·신뢰할 수 있는 방송은 별도 호출자 조건입니다.", "annotations": [{"lines": [18, 64], "color": "sky", "note": "송신자·수신자와 방송 표시를 전송 계층에 넘깁니다. README가 요구하는 실행 식별·암호화·신뢰할 수 있는 방송은 별도 호출자 조건입니다."}]},
};
export const fileTrees:Record<string,FileNode>={"mpyc": {"name": "MPyC 0.11.2 고정 원문", "type": "dir", "children": [{"name": "runtime.py", "type": "file", "path": "mpyc/runtime.py", "codeKey": "input"}, {"name": "thresha.py", "type": "file", "path": "mpyc/thresha.py", "codeKey": "split"}, {"name": "sectypes.py", "type": "file", "path": "mpyc/sectypes.py", "codeKey": "type"}]}, "case": {"name": "별도 실행 예제", "type": "dir", "children": [{"name": "party.py", "type": "file", "path": "case/party.py", "codeKey": "call"}]}, "tss": {"name": "tss-lib 고정 원문 · 읽기만 검토", "type": "dir", "children": [{"name": "round_1.go", "type": "file", "path": "tss/ecdsa/keygen/round_1.go", "codeKey": "dkg-start"}, {"name": "round_3.go", "type": "file", "path": "tss/ecdsa/keygen/round_3.go", "codeKey": "dkg-verify"}, {"name": "feldman_vss.go", "type": "file", "path": "tss/crypto/vss/feldman_vss.go", "codeKey": "vss"}, {"name": "message.go", "type": "file", "path": "tss/tss/message.go", "codeKey": "transport"}]}};
export const projectMetas:Record<string,ProjectMeta>={"mpyc": {"id": "mpyc", "label": "MPyC 0.11.2 고정 원문", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}, "case": {"id": "case", "label": "별도 실행 예제", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}, "tss": {"id": "tss", "label": "tss-lib 고정 원문 · 읽기만 검토", "badgeClass": "bg-sky-50 border-sky-300 text-sky-800"}};
