import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation-block";

const Flow = () => (
  <figure data-viz="circom-compiler-flow" className="not-prose rounded-xl border border-border bg-card p-4 sm:p-5">
    <figcaption className="mb-4 text-sm font-semibold">3 · 4 = 12가 proof artifact가 되는 경로</figcaption>
    <div className="grid gap-3 sm:grid-cols-4">
      {[['01','Template · signal','관계와 public/private 값'],['02','Constraint lowering','witness 계산 + R1CS'],['03','Artifacts','R1CS · WASM · symbols'],['04','Prove · verify','key·public order 결속']].map(([n,t,d]) => <div key={n} className="min-w-0 rounded-lg border border-border bg-background p-4"><p className="text-xs font-semibold text-primary">{n}</p><p className="mt-2 break-words text-sm font-semibold">{t}</p><p className="mt-1 break-words text-xs leading-5 text-muted-foreground">{d}</p></div>)}
    </div>
  </figure>
);

export default function ModernArticle() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-5"><h2 className="text-3xl font-bold">Circom은 계산기가 아니라 circuit compiler다</h2><p className="text-lg leading-8">Public output을 12로 고정하고 private inputs 3과 4를 알고 있음을 증명한다고 해 봅시다. Circom source는 prover가 witness를 계산하는 코드와 verifier가 그 witness를 강제할 R1CS를 함께 만듭니다. 둘 중 하나라도 빠지면 정상 입력 데모는 돌아가더라도 안전한 circuit이 아닙니다.</p><Flow /><p>
            Instance와 witness, R1CS의 수학은 기존 정본을 따라가고 이 글은 Circom compiler가 그 수학을 어떤 artifact로 낮추는지만 소유합니다.
          </p></section>
    <section id="lowering" className="space-y-5"><h2 className="text-2xl font-bold">Witness assignment과 constraint를 분리해 읽다</h2><p>
            z=(1,a,b,out)=(1,3,4,12)일 때 compiler가 남겨야 할 핵심 row는 a·b=out입니다. 값 12를 계산하는 로직은 prover를 돕지만 이 row가
            없으면 out=11인 malicious witness를 verifier가 거절할 근거가 없습니다.
          </p><ExplainedFormula question="Generated R1CS에서 정확히 무엇을 검사하는가?" idea={<>Witness vector의 선형 조합 두 개를 곱한 값이 세 번째 선형 조합과 같아야 합니다. 한 row가 성립한다는 사실과 intended semantics 전체가 충분히 제약된다는 사실은 구분합니다.</>} formula={String.raw`\langle A_i,z\rangle\,\langle B_i,z\rangle=\langle C_i,z\rangle,\qquad (3)(4)=12`}
    annotatedFormula={String.raw`\langle A_i,z\rangle\,\langle B_i,z\rangle=\underbrace{\langle C_i,z\rangle,\qquad (3)(4)=12}_{\text{Witness vector 계산}}`}
    operations={[
      { expression: String.raw`\langle C_i,z\rangle,\qquad (3)(4)=12`, annotation: ["Witness vector이(가) 식의 결과에 기여하는 방식을","계산합니다.","Witness vector의 선형 조합 두 개를 곱한 값이 세","번째 선형 조합과 같아야 합니다."] },
    ]} terms={[{symbol:"z",name:"Witness vector",description:"Constant 1, private signals, intermediate values와 public signals의 ordered vector입니다."},{symbol:"A_i,B_i,C_i",name:"Constraint row",description:"i번째 quadratic constraint의 세 sparse linear combinations입니다."},{symbol:"out",name:"Public output",description:"Verifier API의 public signal order에 결속되는 값입니다."}]} assumptions={["Compiler version과 field modulus, template parameters가 고정됩니다.","의도한 relation의 모든 경로가 constraints로 커버됩니다."]} interpretation="3·4=12는 통과하지만 3·4=11은 실패합니다. 단, out이 constraint에 참여하지 않았다면 이 거절은 보장되지 않습니다." /></section>
    <section id="artifacts" className="space-y-5"><h2 className="text-2xl font-bold">Source보다 넓은 circuit artifact를 고정한다</h2><p>Release manifest에는 compiler commit과 source hash, R1CS, witness generator, symbol map, field/backend profile, public signal names·order가 필요합니다. Proving/verifying key도 그 R1CS hash에 묶어야 합니다. 예를 들어 verifier가 [out,a]를 기대하는데 client가 [a,out]를 보내면 숫자는 같아 보여도 다른 statement입니다.</p><div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="bg-muted/50"><tr><th className="p-3">Layer</th><th className="p-3">Pin</th><th className="p-3">깨지는 반례</th></tr></thead><tbody><tr className="border-t border-border"><td className="p-3">Compile</td><td className="p-3">compiler/source/R1CS hash</td><td className="p-3">old key + new constraints</td></tr><tr className="border-t border-border"><td className="p-3">Witness</td><td className="p-3">generator/symbol layout</td><td className="p-3">unconstrained intermediate</td></tr><tr className="border-t border-border"><td className="p-3">Verify</td><td className="p-3">public names/order/backend</td><td className="p-3">public field swap</td></tr></tbody></table></div></section>
    <section id="release" className="space-y-5"><h2 className="text-2xl font-bold">Correctness를 통과한 뒤에만 성능을 비교한다</h2><p>Valid 3·4=12, invalid out=11, public order swap, tampered R1CS, stale key, missing-constraint mutation을 서로 독립된 fixture로 유지합니다. 그 뒤 같은 curve·backend·circuit size·hardware에서 compile, witness, prove, verify 시간과 peak RSS, proof bytes를 나눠 측정합니다. Artifact hash나 public schema가 바뀌는데 verifier/key rollout이 동시에 준비되지 않으면 이전 manifest로 rollback합니다.</p><div id="paper-circom"><CitationBlock source="Circom: A Circuit Description Language for Building Zero-Knowledge Applications" citeKey={1} href="https://eprint.iacr.org/2020/1003.pdf"><p><b>문제:</b> ZK circuit과 witness generation을 modular DSL로 작성합니다.</p><p><b>기여:</b> Template·signal·constraint compilation model과 toolchain을 제시합니다.</p><p><b>전제:</b> 논문의 Circom·R1CS·SNARK model을 사용합니다.</p><p><b>근거 범위:</b> Language/compiler design과 generated-constraint 경계입니다.</p><p><b>말하지 않는 것:</b> 모든 circuit가 underconstraint 없음을 보장하지 않습니다.</p></CitationBlock></div><div id="paper-circom-source"><CitationBlock source="iden3/circom pinned source a100fae" citeKey={2} href="https://github.com/iden3/circom/tree/a100faedb1c62d4d3e1463f8a3f88342d82351cd"><p><b>문제:</b> 실제 compiler pipeline과 artifact seam을 고정합니다.</p><p><b>기여:</b> Official Rust compiler source·tests snapshot을 제공합니다.</p><p><b>전제:</b> Commit a100fae와 의존성·backend를 pin합니다.</p><p><b>근거 범위:</b> 선택 commit의 source/artifact behavior입니다.</p><p><b>말하지 않는 것:</b> Moving main, snarkjs 전체, 배포 circuit audit를 대신하지 않습니다.</p></CitationBlock></div></section>
  </article>;
}
