import ContentBoundary from "@/components/articles/content-boundary";
import { CitationBlock } from "@/components/ui/citation-block";
import ExplainedFormula from "@/components/ui/explained-formula";
import { LotusMpoolFlowViz } from "./LotusMpoolFlowViz";

const LOTUS_MPOOL = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/chain/messagepool/messagepool.go";
const LOTUS_SELECTION = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/chain/messagepool/selection.go";
const LOTUS_GAS = "https://github.com/filecoin-project/lotus/blob/154c0c3a46e92006008818bb06aaf959e2e705a9/node/impl/full/gas.go";
const FIP_0054 = "https://github.com/filecoin-project/FIPs/blob/c856d99b126cb52a0436c4838da55ec84495cfa7/FIPS/fip-0054.md";

export default function ModernLotusMpool() {
  return <article className="space-y-14">
    <section id="overview" className="space-y-6">
      <header className="space-y-3"><p className="text-sm font-semibold text-primary">Alice의 nonce 7·8·9 메시지를 현재 head에서 안전하게 블록 후보로 만들기</p><h2 className="text-3xl font-bold tracking-tight">Lotus message pool은 접수함이 아니라 head-relative admission, sender nonce chain, gas-aware selection과 reorg reconciliation의 연속 과정이다</h2></header>
      <p className="text-lg leading-8 text-foreground/90">Message pool(mpool)은 아직 chain에 포함되지 않은 signed messages를 노드가 임시로 보관하는 곳입니다. 하지만 로컬 admission은 inclusion이나 finality가 아닙니다. Lotus는 현재 heaviest tipset의 actor nonce·balance와 network version으로 메시지를 검사하고, sender별 연속 nonce chain을 만든 뒤, block gas/message budget과 fee ordering을 고려해 후보를 고릅니다. Head가 바뀌면 applied messages를 제거하고 reverted messages를 복원·재검사합니다. <a className="text-primary hover:underline" href="/blockchain/filecoin-fvm#message-envelope">FVM message execution envelope</a>와 <a className="text-primary hover:underline" href="/blockchain/cometbft#mempool">일반적인 local mempool admission</a>은 정본을 재사용하고, 이 글은 Lotus v1.36.0 구현 경계만 소유합니다.</p>
      <LotusMpoolFlowViz />
      <ContentBoundary article="lotus-mpool" />
      <div id="paper-lotus-mpool-source"><CitationBlock type="code" citeKey={1} source="Lotus messagepool.go · v1.36.0 commit 154c0c3" href={LOTUS_MPOOL}><p><strong>문제:</strong> Untrusted signed message를 현재 chain head와 runtime policy에 맞춰 검증하고 sender별 pending state와 head changes에 일관되게 반영해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 admission checks, push/add paths, nonce·replacement policy, pending retrieval과 apply/revert reconciliation을 구현합니다.</p><p><strong>중요 가정:</strong> Lotus v1.36.0 commit 154c0c3의 network version, actor state, mpool config, wallet/signature rules와 heaviest tipset을 함께 고정합니다.</p><p><strong>근거 범위:</strong> 해당 Lotus snapshot의 local message-pool behavior와 state transition에 한정합니다.</p><p><strong>일반화 금지:</strong> Local acceptance를 block inclusion·execution success·economic optimality·finality로 확대하지 않고, replacement 비율이나 queue 한도를 모든 Lotus version의 상수로 복제하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="admission" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">01 · Head-relative admission</p><h2 className="mt-2 text-2xl font-bold">Signed bytes만 보지 않고 head, actor state와 runtime policy를 receipt에 고정한다</h2></header>
      <p>Alice의 actor nonce가 7이라면 nonce 7 message는 즉시 실행 가능한 후보지만, nonce 9만 먼저 도착하면 8이 올 때까지 gap 뒤에 머뭅니다. Admission은 signature와 CID뿐 아니라 sender protocol, network version별 message size·gas constraints, 현재 balance와 required funds, nonce 범위, duplicate와 same-nonce replacement policy를 검사합니다. Head가 움직이면 같은 bytes의 유효성도 달라질 수 있으므로 acceptance receipt에 base tipset key와 height를 기록합니다.</p>
      <ExplainedFormula question="같은 message가 어느 chain context에서 admission됐는지 어떻게 재현할까?" idea={<>Signed message identity에 head와 validation policy snapshot을 함께 묶습니다.</>} formula={String.raw`A=H(C_{msg}\|K_H\|h\|N_V\|P_{mpool})`}
      annotatedFormula={String.raw`A=\underbrace{H(C_{msg}\|K_H\|h\|N_V\|P_{mpool})}_{\text{Mpool policy 계산}}`}
      operations={[
        { expression: String.raw`H(C_{msg}\|K_H\|h\|N_V\|P_{mpool})`, annotation: ["Mpool policy이(가) 식의 결과에 기여하는 방식을","계산합니다.","Signed message identity에 head와","validation policy snapshot을 함께"] },
      ]} terms={[{symbol:"A",name:"Admission digest",description:"한 local admission 판단을 재현하는 receipt identity입니다."},{symbol:"H",name:"Cryptographic hash",description:"Canonical serialization에 적용한 hash입니다."},{symbol:"C_{msg}",name:"Signed-message CID",description:"From, To, Nonce, Value, Gas fields, method parameters와 signature를 식별합니다."},{symbol:"K_H",name:"Head tipset key",description:"Admission 때 actor state를 읽은 exact heaviest tipset입니다."},{symbol:"h",name:"Head height",description:"Network-version과 base-fee context를 해석할 epoch입니다."},{symbol:"N_V",name:"Network version",description:"Message validity와 actor semantics를 선택하는 version입니다."},{symbol:"P_{mpool}",name:"Mpool policy",description:"Replacement ratio, queue limits와 local configuration snapshot입니다."}]} assumptions={["Fields는 Filecoin canonical message/CID rules와 deterministic policy encoding을 따릅니다.","A는 판단 provenance이며 이후 head에서도 message가 유효하거나 포함된다는 증명이 아닙니다."]} interpretation="Signed-message CID가 같아도 head나 mpool config가 바뀌면 admission digest가 달라지므로 stale 판단을 새 head에 재사용하지 않습니다." />
      <p>같은 sender·nonce의 replacement도 단순히 새 메시지가 왔다고 허용하지 않습니다. 새 fee가 configured replace-by-fee threshold를 충족하고 dependent chain을 깨지 않아야 합니다. 정확한 threshold는 pinned config artifact에서 읽으며 이 글은 임의의 고정 퍼센트를 주장하지 않습니다.</p>
    </section>

    <section id="nonce-packages" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">02 · Sender nonce chain and block selection</p><h2 className="mt-2 text-2xl font-bold">Actor nonce부터 끊기지 않은 chain만 실행 가능한 package로 만들고 block budgets 안에서 비교한다</h2></header>
      <p>Filecoin actor는 sender별 nonce 순서대로 messages를 실행합니다. 따라서 Alice의 state nonce가 7이고 pending이 7·9라면 9의 fee가 아무리 높아도 8 없이 먼저 실행할 수 없습니다. Lotus selection은 sender마다 7→8→9처럼 contiguous한 package를 만든 뒤 base fee에서 얻을 수 있는 effective premium과 gas reward, block gas limit과 message count를 고려합니다. 이 단계는 local queue ordering이지 consensus가 모든 노드에 같은 candidate order를 강제한다는 뜻은 아닙니다.</p>
      <ExplainedFormula question="Sender의 어떤 pending messages가 하나의 실행 가능한 chain일까?" idea={<>On-chain actor nonce에서 시작해 정확히 1씩 증가하는 prefix만 선택합니다.</>} formula={String.raw`n_i=n_{state}+i,\quad i=0,\ldots,k-1`}
      annotatedFormula={String.raw`n_i=\underbrace{n_{state}+i,\quad i=0,\ldots,k-1}_{\text{Actor state nonce 계산}}`}
      operations={[
        { expression: String.raw`n_{state}+i,\quad i=0,\ldots,k-1`, annotation: ["Actor state nonce이(가) 식의 결과에 기여하는","방식을 계산합니다.","On-chain actor nonce에서 시작해 정확히 1씩","증가하는 prefix만 선택합니다."] },
      ]} terms={[{symbol:"n_i",name:"Message nonce",description:"Package 안 i번째 signed message의 nonce입니다."},{symbol:"n_{state}",name:"Actor state nonce",description:"Selection base tipset에서 읽은 sender의 다음 expected nonce입니다."},{symbol:"i",name:"Chain offset",description:"Contiguous prefix 안의 0-based 위치입니다."},{symbol:"k",name:"Package length",description:"Gap, invalid message 또는 budget boundary 전까지 이어지는 메시지 수입니다."}]} assumptions={["모든 messages가 같은 sender이고 base tipset에서 admission checks를 통과했습니다.","Replacement이 있으면 같은 nonce의 winner를 먼저 정한 뒤 contiguous chain을 구성합니다."]} interpretation="n_state=7일 때 7·8·9는 k=3 package지만 7·9는 7까지만 executable prefix이며 9는 nonce 8을 기다립니다." />
      <div id="paper-lotus-selection"><CitationBlock type="code" citeKey={2} source="Lotus selection.go · v1.36.0 commit 154c0c3" href={LOTUS_SELECTION}><p><strong>문제:</strong> Sender nonce dependencies를 보존하면서 block gas/message limits와 fee incentives 안에서 pending messages를 골라야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 actor nonce에서 sender chains를 구성하고 effective premium·gas reward를 계산해 block candidate selection을 수행합니다.</p><p><strong>중요 가정:</strong> Selection base tipset, actor nonces, base fee, block gas limit, pending set과 Lotus v1.36.0 algorithm/config를 동일하게 고정합니다.</p><p><strong>근거 범위:</strong> commit 154c0c3 selection implementation의 package construction과 ordering behavior에 한정합니다.</p><p><strong>일반화 금지:</strong> 선택 순서를 global consensus, guaranteed inclusion, MEV-free ordering 또는 모든 workload의 최적 packing으로 해석하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="gas-estimate" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">03 · Gas estimate context receipt</p><h2 className="mt-2 text-2xl font-bold">GasLimit, GasPremium, GasFeeCap의 서로 다른 질문을 나누고 estimate context를 함께 보존한다</h2></header>
      <p><code>GasEstimateGasLimit</code>은 actor call을 simulation해 사용량에 configured overestimation을 적용하고 block gas limit을 넘지 않게 합니다. <code>GasEstimateGasPremium</code>은 inclusion urgency와 recent chain conditions를, <code>GasEstimateFeeCap</code>은 base-fee growth risk를 다룹니다. Estimate 후 head가 바뀌면 actor state와 base fee가 달라질 수 있으므로 tipset key, height, network version, estimator revision, overestimation multiplier와 observed base fee를 receipt에 저장합니다.</p>
      <ExplainedFormula question="Block selection에서 message의 실제 priority contribution을 어떻게 비교할까?" idea={<>Premium claim을 그대로 믿지 않고 fee cap에서 base fee를 낸 뒤 남는 한도와 작은 값을 effective premium으로 사용합니다.</>} formula={String.raw`p_{eff}=\min\!\left(p,\max(f-b,0)\right),\qquad R=p_{eff}G`}
      annotatedFormula={String.raw`p_{eff}=\underbrace{\min\!\left(p,\max(f-b,0)\right),\qquad R=p_{eff}G}_{\text{경계 후보 선택}}`}
      operations={[
        { expression: String.raw`\min\!\left(p,\max(f-b,0)\right),\qquad R=p_{eff}G`, annotation: ["허용 후보 중 목적에 맞는 경계값을 선택합니다.","Premium claim을 그대로 믿지 않고 fee cap에서","base fee를 낸 뒤 남는 한도와 작은 값을","effective premium으로 사용합니다."] },
      ]} terms={[{symbol:"p_{eff}",name:"Effective gas premium",description:"Base fee를 고려한 token-per-gas priority contribution입니다."},{symbol:"p",name:"GasPremium",description:"Sender가 miner에게 지불하겠다고 제시한 per-gas premium입니다."},{symbol:"f",name:"GasFeeCap",description:"Base fee와 premium을 합쳐 sender가 허용한 maximum per-gas price입니다."},{symbol:"b",name:"Base fee",description:"Selection base tipset의 network base fee입니다."},{symbol:"R",name:"Gas reward score",description:"Pinned selection code가 package comparison에 사용하는 effective premium×gas-limit quantity입니다."},{symbol:"G",name:"GasLimit",description:"Message가 block에서 예약하는 gas units입니다."}]} assumptions={["FIP-0054 semantics와 pinned Lotus selection snapshot을 사용하며 모든 fee field는 같은 token-per-gas 단위를 사용합니다.","R은 actual execution gas used나 guaranteed miner payout이 아니라 selection-time quantity입니다."]} interpretation="p=3, f=12, b=10이면 p_eff=min(3,2)=2입니다. Premium을 3으로 적었어도 fee cap의 남는 폭이 2라서 priority contribution은 gas당 2입니다." />
      <div id="paper-lotus-gas-api"><CitationBlock type="code" citeKey={3} source="Lotus gas.go · v1.36.0 commit 154c0c3" href={LOTUS_GAS}><p><strong>문제:</strong> Client가 execution simulation, premium와 future base-fee risk를 서로 다른 estimators로 계산하고 message fields에 적용해야 합니다.</p><p><strong>핵심 기여:</strong> Pinned source는 GasLimit simulation/overestimation/cap, premium sampling과 fee-cap estimation APIs의 exact paths를 구현합니다.</p><p><strong>중요 가정:</strong> Lotus v1.36.0 estimator code, base tipset, actor state, mpool pending set, network policy와 caller-provided overestimation 값을 고정합니다.</p><p><strong>근거 범위:</strong> commit 154c0c3 full-node gas estimation behavior와 error boundary에 한정합니다.</p><p><strong>일반화 금지:</strong> Estimate를 future execution receipt, fixed latency/fee, inclusion guarantee 또는 adversarial base-fee movement의 upper bound로 해석하지 않습니다.</p></CitationBlock></div>
      <div id="paper-filecoin-fip54"><CitationBlock type="paper" citeKey={4} source="FIP-0054 · revision c856d99" href={FIP_0054}><p><strong>문제:</strong> Legacy selection이 fee cap과 base fee interaction을 충분히 반영하지 못해 실제 miner reward와 message ranking이 어긋날 수 있습니다.</p><p><strong>핵심 기여:</strong> FIP-0054는 effective gas premium을 fee-cap residual로 제한해 block-selection reward 계산을 수정합니다.</p><p><strong>중요 가정:</strong> FIP revision c856d99, 해당 network upgrade activation과 compatible Lotus implementation을 사용합니다.</p><p><strong>근거 범위:</strong> Filecoin block selection의 effective premium semantics와 migration rationale에 한정합니다.</p><p><strong>일반화 금지:</strong> 이 ranking rule이 fee predictability, fair ordering, inclusion이나 globally optimal block construction을 보장한다고 주장하지 않습니다.</p></CitationBlock></div>
    </section>

    <section id="release-gate" className="space-y-6">
      <header><p className="text-sm font-semibold text-primary">04 · Head-change release gate</p><h2 className="mt-2 text-2xl font-bold">Apply·revert·restart와 concurrent nonce allocation을 주입한 뒤에만 mpool 변경을 배포한다</h2></header>
      <p>Release test는 같은 sender의 concurrent submitters, nonce gap, same-nonce replacement과 dependent message, insufficient funds, stale gas estimate, invalid signature/network version, full block budget, apply/revert reorg와 crash/restart를 포함합니다. Head apply 때 included messages가 빠지고 revert 때 아직 유효한 messages가 돌아오는지, 새 actor nonce·balance에서 stale entries가 재검사되는지 확인합니다. 여러 process가 nonce를 할당한다면 <code>MpoolGetNonce</code>를 단독 lock처럼 사용하지 않고 external allocator 또는 same-nonce conflict recovery를 설계합니다.</p>
      <ExplainedFormula question="새 Lotus mpool 후보를 production에 release할 최소 조건은 무엇일까?" idea={<>정확성, nonce dependency, fee context, reorg recovery와 persistence를 독립 gates로 검사합니다.</>} formula={String.raw`A=C_{admit}\land N_{chain}\land G_{ctx}\land H_{reorg}\land P_{restart}\land O_{observe}`}
      annotatedFormula={String.raw`A=\underbrace{C_{admit}\land N_{chain}\land G_{ctx}\land H_{reorg}\land P_{restart}\land O_{observe}}_{\text{판정 조건 결합}}`}
      operations={[
        { expression: String.raw`C_{admit}\land N_{chain}\land G_{ctx}\land H_{reorg}\land P_{restart}\land O_{observe}`, annotation: ["필요한 gate가 모두 참일 때만 전체 조건을 통과시킵니다.","정확성, nonce dependency, fee","context, reorg recovery와","persistence를 독립 gates로 검사합니다."] },
      ]} terms={[{symbol:"A",name:"Release acceptance",description:"Candidate mpool build/config를 production에 채택하면 1입니다."},{symbol:"C_{admit}",name:"Admission parity",description:"Pinned corpus의 accepted/rejected messages가 expected reason과 일치하면 1입니다."},{symbol:"N_{chain}",name:"Nonce-chain integrity",description:"Gap·replacement·dependent packages가 actor nonce 순서를 지키면 1입니다."},{symbol:"G_{ctx}",name:"Gas context receipt",description:"Estimates와 selection metrics가 exact head/base fee/config에 결속되면 1입니다."},{symbol:"H_{reorg}",name:"Head-change recovery",description:"Apply 때 제거하고 revert 때 복원한 뒤 stale entry를 다시 검증하면 1입니다."},{symbol:"P_{restart}",name:"Persistence recovery",description:"Crash/restart에서 local journal/state가 duplicate/lost messages 없이 복구되면 1입니다."},{symbol:"O_{observe}",name:"Operational observability",description:"Reject reasons, queue depth/age, sender gaps, replacements와 head lag를 관찰할 수 있으면 1입니다."}]} assumptions={["Test receipts는 exact Lotus binary/commit, config, network version, base tipsets와 actor state snapshots을 pin합니다.","Canary에서 acceptance/reject drift가 발견되면 prior binary/config로 rollback하고 pending messages를 새 head에서 다시 검증합니다."]} interpretation="Selection throughput이 빨라도 reorg 뒤 reverted message를 복원하지 못하면 H_reorg=0이므로 A=0입니다." />
      <aside className="rounded-lg border border-border bg-muted/20 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Article-only 10/10:</strong> Local admission과 inclusion 구분, head-relative checks, nonce package, replacement, 세 gas fields와 effective premium, stale estimate, reorg/restart, concurrent nonce와 rollback을 이 글만으로 답할 수 있습니다.</aside>
    </section>
  </article>;
}
