import ContentBoundary from "@/components/articles/content-boundary";
import TermBreakdown from "@/components/articles/term-breakdown";
import ExplainedFormula from "@/components/ui/explained-formula";
import { CitationBlock } from "@/components/ui/citation";
import { MemoryLifecycleViz } from "../context-engineering/viz/ModernContextEngineeringViz";

export default function AgentMemoryLifecycleArticle() {
  return <div className="space-y-16">
    <section id="overview" className="scroll-mt-20"><h2 className="mb-6 text-2xl font-bold">Agent memory는 수명과 삭제 규칙이 있는 application state입니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p className="text-lg leading-8">현재 run의 goal과 failed test, 여러 session에 재사용할 사용자 선호, 긴 tool log, versioned procedure는 보존 이유가 다릅니다. 모두 ‘memory’라는 한 배열에 넣으면 stale fact·privacy·resume failure가 생깁니다.</p></div><TermBreakdown title="수명에 따라 네 저장소로 나누기" items={[{term:"Working state",description:"현재 objective·decision·unresolved issue·next action입니다.",example:"지금 수정 중인 route와 실패한 mobile formula"},{term:"Long-term memory",description:"여러 session에 재사용할 가치가 있고 사용자가 보존에 동의한 사실·preference입니다.",boundary:"Source·expiry·update·delete가 없으면 영구 사실로 취급하지 않습니다."},{term:"Artifact",description:"긴 log·dataset·patch·screenshot처럼 원문을 보존해야 하는 외부 object입니다.",example:"artifact URI와 digest만 context summary에 남깁니다."},{term:"Versioned procedure",description:"여러 사람이 검토·수정해야 하는 반복 절차입니다.",boundary:"대화 summary보다 문서·skill·code가 정본입니다."}]}/><MemoryLifecycleViz/><ContentBoundary article="agent-memory-lifecycle"/></section>
    <section id="lifetimes" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">저장 시점에 owner와 source, expiry, delete path를 함께 씁니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>‘사용자는 한국어를 선호한다’는 fact도 어느 대화에서 동의했는지, tenant와 user identity가 무엇인지, 언제 다시 확인할지, 사용자가 삭제를 요청하면 어느 index와 cache를 지울지까지 하나의 lifecycle입니다.</p></div></section>
    <section id="compaction" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Compaction fidelity는 요약 길이가 아니라 다음 행동을 바꾸는 state의 보존율입니다</h2><ExplainedFormula question="긴 trace를 줄인 뒤 무엇이 남았는지 어떻게 검사하나요?" idea={<p>원 trace에서 다음 행동을 결정하는 필수 state key를 먼저 정의하고, compacted state가 그 key를 정확한 source와 함께 복원하는지 비교합니다. 단순 keyword 존재가 아니라 값과 artifact identity까지 확인합니다.</p>} formula={String.raw`F=\frac{|K_{trace}\cap K_{resume}^{correct}|}{|K_{trace}|}`} annotatedFormula={String.raw`\begin{aligned}K_{need}&=\{goal,decision,reason,\\&\quad unresolved,artifact,next\}\\&\underbrace{K_{need}}_{\substack{\text{resume 행동을 바꾸는}\\\text{필수 state key}}}\\K_{ok}&=\{k\in K_{need}:\\&\quad resume(k)=trace(k)\}\\&\underbrace{K_{ok}}_{\substack{\text{원 trace와 값·source가}\\\text{일치한 key}}}\\F&=\underbrace{\frac{|K_{ok}|}{|K_{need}|}}_{\substack{\text{필수 key 중}\\\text{정확히 보존된 비율}}}\end{aligned}`} operations={[{expression:String.raw`K_{need}`,annotation:["다음 행동에 영향을 주는","필수 state schema를 먼저 고정"]},{expression:String.raw`resume(k)=trace(k)`,annotation:["resume 결과를 원 trace와 대조해","값과 source가 맞는 key만 인정"]},{expression:String.raw`|K_{ok}|/|K_{need}|`,annotation:["정확히 복원한 key 수를","전체 필수 key 수로 나눠 fidelity 측정"]}]} terms={[{symbol:String.raw`K_{need}`,name:"Required state keys",description:"Resume가 보존해야 하는 최소 state schema입니다."},{symbol:String.raw`K_{ok}`,name:"Correctly restored keys",description:"원 trace와 값·source가 일치한 key입니다."},{symbol:"F",name:"Compaction fidelity",description:"0과 1 사이의 필수 state 보존 비율입니다."}]} assumptions={["필수 key schema는 compaction 결과를 보기 전에 정의합니다.","Artifact content는 summary에 복사하지 않고 URI·digest로 검증합니다.","F=1이어도 privacy·authorization·already-executed side effect를 별도로 검사합니다."]} interpretation="6개 필수 key 중 decision reason과 failed test가 빠졌다면 F=4/6입니다. 문장이 자연스러워도 resume contract는 실패입니다."/></section>
    <section id="resume" className="scroll-mt-20"><h2 className="mb-5 text-2xl font-bold">Resume test는 목표 재진술과 다음 safe action 선택을 확인합니다</h2><div className="prose prose-neutral max-w-none dark:prose-invert"><p>새 session에는 compacted state와 artifact receipts만 주고 objective·선택 이유·미완료·이미 실행된 effect·다음 action을 복원하게 합니다. 원 trace와 다른 write를 반복하거나 rejected alternative를 다시 선택하면 compaction을 release하지 않습니다.</p></div><div className="not-prose mt-8 grid gap-4 lg:grid-cols-2"><div id="paper-memgpt" className="scroll-mt-24"><CitationBlock type="paper" citeKey={1} source="MemGPT: Towards LLMs as Operating Systems" href="https://arxiv.org/abs/2310.08560">제한된 context와 외부 storage 사이의 tier 이동을 virtual context management로 제안하고 공개 task에서 평가합니다. 무제한·무손실 인간 기억을 보장한다는 주장은 아닙니다.</CitationBlock></div><div id="paper-anthropic-context-management" className="scroll-mt-24"><CitationBlock type="paper" citeKey={2} source="Anthropic — Managing context on the Claude Developer Platform" href="https://claude.com/blog/context-management">Stale tool result를 제거하는 context editing과 file memory tool의 제품 경계를 설명합니다. 공개된 특정 model·agentic-search 조건의 측정을 모든 workload에 일반화하지 않습니다.</CitationBlock></div></div></section>
  </div>;
}
