import { Link } from "react-router-dom";
import { CitationBlock } from "@/components/ui/citation";
import FlowRail from "../../world-systems/FlowRail";
import SourceApplication from "../../world-systems/SourceApplication";
import ReviewPrompts from "../../world-systems/ReviewPrompts";
import { CodeSidebar, CodeViewButton, useCodeSidebar } from "@/components/code";
import { codeRefs } from "./codeRefs";
export default function RobinhoodChainSettlementArticle() { const sidebar=useCodeSidebar(); return <><article className="space-y-14">
<section id="overview" data-teach-level="S" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">1. 체인에서 보낸 자산이 언제 도착했고 무엇을 소유하게 됐는가</h2>
<p>Robinhood Chain에서 자산을 보내면 지갑에는 빠르게 성공이 표시됩니다. 뒤에서는 거래 순서를 정하고 Ethereum에 자료를 게시합니다. 필요하면 브리지에서 자금을 꺼내는 과정도 이어집니다. 각 단계가 보장하는 결과가 다르므로 성공 표시가 어느 단계의 결과인지 확인해야 합니다.</p><p>2026-10-04 공식 문서는 메인넷 chain ID 4663과 테스트넷 46630을 구분합니다. 예전 testnet이라는 URL에 메인넷 설명이 남아 있으므로 URL 이름 대신 현재 네트워크 자료를 확인합니다. 이 글은 일반 토큰 전달을 따라간 뒤 Stock Token의 법적 권리와 비교합니다.</p><CitationBlock source="Robinhood Chain · Connecting" citeKey={1} href="https://docs.robinhood.com/chain/connecting/">현재 네트워크 식별자·RPC·ETH gas·Ethereum blobs 사용을 확인했습니다.</CitationBlock>
<p data-stage-bridge="overview" className="text-sm text-muted-foreground">성공의 단계를 나누기 위해 누가 주문을 받고 누가 자산을 내주는지 봅니다.</p>
</section>
<section id="black-box" data-teach-level="B" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">2. 전송을 승인한 뒤 누가 기록하고 지급하는가</h2>
<FlowRail title="한 전송이 통과하는 네 역할" steps={[{actor:"지갑",movement:"체인·받는 곳·수량을 서명합니다.",receives:"승인한 거래"},{actor:"L2 실행",movement:"순서를 정하고 계약을 실행합니다.",receives:"실행 영수증"},{actor:"Ethereum 게시",movement:"묶음 자료를 올리고 확정합니다.",receives:"L1에 고정된 순서"},{actor:"인출 계약",movement:"인출 조건과 증거를 검사합니다.",receives:"L1에서 실행한 지급"}]} /><p>지갑은 사용자의 승인 권한을 맡고 체인 실행은 계약의 잔액을 바꿉니다. 브리지는 서로 다른 체인의 사건을 연결합니다. 자산 발행자는 그 토큰의 지급·상환 의무를 맡을 수 있습니다. 같은 회사 이름이 화면에 보여도 이 역할과 실패 조건은 구분해야 합니다.</p>
<p data-stage-bridge="black-box" className="text-sm text-muted-foreground">네 역할에 작은 전송과 인출 사례를 넣어 봅니다.</p>
</section>
<section id="case" data-teach-level="0" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">3. 100개에서 10개를 보내고 받은 사람이 5개를 인출한다</h2>
<p>공식 canonical bridge가 지원하는 가상 ERC-20 TOK를 A가 L2에서 100개 갖고 있다고 합시다. A가 B에게 10개를 전송하면 성공 후 잔액은 A 90·B 10입니다. B가 그중 5개를 Ethereum으로 인출하면 L2의 B 잔액 5와 처리 중인 인출 5를 구분합니다. L1 지급까지 성공해야 B의 L1 수령 5를 기록합니다.</p><p>금액은 교육용 가정이며 실제 Stock Token의 브리지 지원을 뜻하지 않습니다. TOK의 단위를 18자리로 가정하면 10개는 10×10¹⁸의 정수로 서명합니다. ETH로 지불하는 gas는 TOK 100과 별도로 준비합니다. 위 수량에는 gas 비용을 포함하지 않았습니다.</p>
<p data-stage-bridge="case" className="text-sm text-muted-foreground">잔액과 처리 중인 인출을 같은 돈으로 두 번 세지 않도록 단계별로 표시합니다.</p>
</section>
<section id="picture" data-teach-level="1" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">4. B의 10개가 한 번만 이동하도록 기록한다</h2>
<div className="overflow-x-auto"><table className="w-full min-w-[540px] text-sm"><caption className="mb-3 text-left">가상 TOK의 이동. 수수료용 ETH는 별도입니다.</caption><thead><tr><th className="p-3 text-left">사건</th><th className="p-3">A L2</th><th className="p-3">B L2</th><th className="p-3">인출 중</th><th className="p-3">B L1</th></tr></thead><tbody>{[["시작",100,0,0,0],["10 전송 성공",90,10,0,0],["5 인출 시작",90,5,5,0],["L1 지급 성공",90,5,0,5]].map(r=><tr key={r[0]} className="border-t">{r.map((c,i)=><td key={i} className="p-3 text-center">{c}</td>)}</tr>)}</tbody></table></div><p>인출 중 5는 별도의 새 자산이 아닙니다. 이 표에서는 아직 지급되지 않은 같은 수량을 추적합니다. L2에서 인출을 시작한 거래 hash, 인출 메시지 식별자, L1 지급 거래 hash를 연결해야 중복 지급이나 누락을 찾을 수 있습니다.</p>
<p data-stage-bridge="picture" className="text-sm text-muted-foreground">수량은 보존되지만 단계마다 쓸 수 있는 장소가 다릅니다. 왜 기다림과 재확인이 필요한지 살펴봅니다.</p>
</section>
<section id="need" data-teach-level="2" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">5. 빠른 영수증과 L1 인출 대기에는 서로 다른 이유가 있다</h2>
<p>첫 실행 영수증은 순서 제공자가 거래를 처리했다는 빠른 결과입니다. 아직 Ethereum에 게시되지 않은 단계에서는 그 순서에 의존합니다. 게시한 L1 블록이 확정되면 자료의 순서를 되돌리기 훨씬 어려워지지만, canonical 인출 메시지를 집행하려면 별도의 이의 제기 기간이 남습니다.</p><p>공식 문서는 빠른 확인을 1초 미만, 게시는 수분, 게시 후 Ethereum 확정은 약 13분으로 안내합니다. 이는 통상 지연 안내이며 모든 거래의 기한을 보장하는 값이 아닙니다. 인출의 약 7일은 이 13분을 일곱 날 반복하는 과정이 아닙니다.</p><CitationBlock source="Robinhood Chain · Transaction finality" citeKey={2} href="https://docs.robinhood.com/chain/transaction-finality/">단계별 확인과 canonical 인출의 7일 대기를 구분합니다. 통상 지연은 장애·혼잡에 따라 달라집니다.</CitationBlock>
<p data-stage-bridge="need" className="text-sm text-muted-foreground">기다림의 이유가 달랐습니다. 각 단계에 사용되는 이름을 붙입니다.</p>
</section>
<section id="names" data-teach-level="3" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">6. Soft confirmation·L1 finality·withdrawal을 구별한다</h2>
<p>거래를 받아 순서를 정하는 역할은 sequencer입니다. soft confirmation은 그 역할이 돌려준 빠른 확인입니다. batch는 여러 거래를 묶은 자료이며 Ethereum의 inbox에 게시합니다. L1 finality는 그 게시를 포함한 Ethereum 블록의 확정입니다.</p><p>withdrawal은 L2에서 L1으로 자산이나 메시지를 전달하는 인출입니다. challenge period는 주장에 이의를 제기할 시간이며, 기간과 다른 조건을 충족한 메시지를 L1 outbox에서 실행해야 지급이 끝납니다. 출발지 receipt·메시지 상태·도착지 receipt를 한 종류의 확인 횟수로 세지 않습니다.</p>
<p data-stage-bridge="names" className="text-sm text-muted-foreground">이름을 붙였으니 A의 10개와 B의 5개가 실제 경로를 어떻게 통과하는지 따라갑니다.</p>
</section>
<section id="mechanism" data-teach-level="4" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">7. A의 전송에서 B의 L1 수령까지 따라간다</h2>
<p>A는 chain 4663, TOK 계약 주소, B 주소와 10개를 확인해 서명합니다. 주소가 같아 보여도 Ethereum과 L2의 토큰 계약은 다를 수 있으므로 공식 목록과 gateway 매핑을 확인합니다. 실행 영수증의 status와 transfer 결과를 읽은 뒤 잔액 A 90·B 10을 대조합니다. 거래 hash가 나왔다는 사실만으로 계약 실행 성공을 판단하지 않습니다.</p><p>그 거래를 담은 batch가 Ethereum에 게시되고 해당 L1 블록이 확정됐는지 추적합니다. B가 5개를 인출하면 별도의 L2 인출 사건에서 메시지를 얻습니다. 공식 안내의 약 7일 대기를 거쳐 메시지가 실행 가능해진 뒤 L1에서 claim 거래를 보내고 영수증과 수령 5를 확인합니다. 마지막 단계에는 L1 gas가 듭니다.</p><p>반대 방향의 입금은 retryable ticket을 사용할 수 있습니다. L1 처리 뒤 L2 실행이 gas 부족 등으로 실패하면 공식 안내의 7일 안에 재실행하는 경로를 확인합니다. 입금 재실행 기한과 출금 challenge period는 모두 7일이라는 숫자가 보이지만 다른 절차입니다.</p><CitationBlock source="Robinhood Chain · Bridging" citeKey={3} href="https://docs.robinhood.com/chain/bridging/">입금 재실행과 인출 시작→대기→L1 claim, 서로 다른 체인의 토큰 주소를 확인합니다.</CitationBlock><CitationBlock source="Robinhood Chain · Protocol contracts" citeKey={4} href="https://docs.robinhood.com/chain/protocol-contracts/">Mainnet·Testnet, L1·L2의 inbox·outbox·gateway 목록을 구분합니다.</CitationBlock>
<p data-stage-bridge="mechanism" className="text-sm text-muted-foreground">인출 대기와 지급 실행이 다른 사건임을 확인했습니다. 공개 SDK도 같은 구분을 하는지 봅니다.</p>
</section>
<section id="source" data-teach-level="5" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">8. SDK의 CONFIRMED는 이미 지급했다는 뜻이 아니다</h2>
<SourceApplication source="Arbitrum SDK · ChildToParentMessageNitro.status()" excerpt="ChildToParentMessageStatus.CONFIRMED" application="B의 5개 메시지가 CONFIRMED여도 아직 실행하지 않았다면 표의 인출 중 5에 남습니다. execute()가 proof와 메시지 자료를 outbox에 보내고 L1 거래가 성공한 뒤에야 B L1의 5로 옮깁니다." /><p>공식 Arbitrum SDK commit cbb96c6f7f84d71bdef65d0fd9d3d7275a236711의 status()는 send root가 미확정이면 UNCONFIRMED, 이미 실행했으면 EXECUTED, 그 외 실행 가능한 경우 CONFIRMED를 반환합니다. execute()는 이 상태를 검사한 뒤 proof·메시지 위치·수신처·금액 등을 L1 outbox로 전달합니다.</p><div className="flex flex-wrap gap-3"><CodeViewButton label="CONFIRMED와 EXECUTED 원본" onClick={()=>sidebar.open("status",codeRefs.status)} /><CodeViewButton label="proof를 붙여 outbox 실행" onClick={()=>sidebar.open("execute",codeRefs.execute)} /></div><p>이 코드는 Arbitrum 계열 메시지 처리 구조의 공개 실물입니다. 라이브 Robinhood 계약과 동일 bytecode임을 검증한 결과는 아닙니다. 실제 연결에는 해당 네트워크의 공식 주소·구성·배포 버전을 별도로 맞춰야 합니다.</p><CitationBlock source="OffchainLabs · Arbitrum SDK, pinned cbb96c6" citeKey={5} href="https://github.com/OffchainLabs/arbitrum-sdk/blob/cbb96c6f7f84d71bdef65d0fd9d3d7275a236711/packages/sdk/src/lib/message/ChildToParentMessageNitro.ts">원본과 라이선스를 보존했습니다. 상태 조회와 지급 트랜잭션의 실행을 구분합니다.</CitationBlock>
<p data-stage-bridge="source" className="text-sm text-muted-foreground">코드의 성공도 어느 사건인지 확인했습니다. 이제 같은 10개가 Stock Token일 때 달라지는 권리를 봅니다.</p>
</section>
<section id="comparison" data-teach-level="6" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">9. Stock Token 10개를 받았어도 기초 주식의 주주가 되는 것은 아니다</h2>
<SourceApplication source="Robinhood Chain · Stock Tokens" excerpt="tokenised debt securities" application="가상 TOK 대신 Stock Token 10개를 받았다고 해도 그 전송 결과만으로 기초 회사 주식 10주의 법적 소유권을 얻었다고 적지 않습니다. RHJ가 발행한 채무증권의 조건과 경제적 노출을 확인해야 합니다. 앞의 5개 canonical 인출 예시가 이 상품에도 지원된다는 뜻도 아닙니다." /><p>공식 설명에서 발행자는 Robinhood Assets (Jersey) Limited이며 기초 주식·ETF에 대한 경제적 노출을 제공합니다. 기초 증권 발행자에 대한 직접 법적·수익적 권리는 주지 않는다고 명시합니다. 네트워크의 공개성과 상품의 투자자·국가별 판매 자격은 별개입니다.</p><p>현재 문서는 18자리 ERC-20과 주식당 비율을 바꾸는 uiMultiplier를 설명합니다. raw balance 10이 그대로여도 배당·분할 처리에 따른 표시 비율이 바뀔 수 있으므로 10토큰을 언제나 10주로 고정하지 않습니다. 직접 발행 청약은 자격을 갖춘 Authorised Participant 경로이며, 일반 앱의 transfer 지원과 다릅니다.</p><p>문서의 발행·소각 창은 월요일 02:00부터 토요일 02:00 CET/CEST이며 종목별 거래 가능 시간은 별도 API로 확인합니다. 창 밖의 온체인 거래 가능성과 신규 발행 가능성을 혼동하지 않습니다. 이러한 조건은 변경될 수 있으므로 최신 기본 투자설명서와 개별 조건을 확인합니다.</p><CitationBlock source="Robinhood Chain · Stock Tokens" citeKey={6} href="https://docs.robinhood.com/chain/stock-tokens/">권리·발행자·raw balance와 multiplier·청약 자격·시간 창을 확인했습니다.</CitationBlock><CitationBlock source="Robinhood Assets Jersey · Product documents" citeKey={7} href="https://docs.robinhood.com/rhj">상품별 권리와 국가별 제한은 투자설명서·추가 문서·최종 조건의 적용 대상입니다.</CitationBlock>
<p data-stage-bridge="comparison" className="text-sm text-muted-foreground">체인 결제와 법적 권리를 각각 확인했습니다. 마지막으로 속도와 이용 가능성을 평가할 때 남는 조건을 봅니다.</p>
</section>
<section id="limits" data-teach-level="7" className="scroll-mt-20 space-y-5"><h2 className="text-2xl font-bold">10. 빠른 bridge와 공개 체인은 서로 다른 추가 조건을 갖는다</h2>
<p>다른 bridge가 B의 5개를 먼저 지급할 수는 있습니다. 이 경우 유동성 제공자·메시지 검증·별도 계약의 조건을 추가로 검토합니다. canonical 경로의 이의 제기 절차가 사라졌다고 일반화하지 않습니다. 급한 지급을 받는 대가와 실패 때 누구에게 청구할지 확인해야 합니다.</p><p>시퀀서 장애, 게시 지연, 스마트 계약 오류, 관리자 권한, 발행자 상환 조건은 서로 다른 위험입니다. 동일 브랜드의 문서도 확인일과 네트워크를 붙여 읽습니다. 공식 문서의 통상 13분·7일을 모든 상황의 확정 지급 시한으로 약속하지 않습니다.</p><p>이 체인이 Ethereum의 데이터 수요에 얼마나 기여했는지는 <Link className="underline" to="/cs/blockchain/robinhood-chain-blob-demand">블롭 수요 회계</Link>에서 별도로 계산합니다. 기관 상품의 토큰·자산·현금 관계는 <Link className="underline" to="/cs/blockchain/rwa-composition">RWA 권리와 회수</Link>로 이어집니다.</p>
<p data-stage-bridge="limits" className="text-sm text-muted-foreground">A 90·B L2의 5·B L1의 5까지 추적하면 빠른 확인, 지급 완료, 상품 권리를 따로 판단할 수 있습니다.</p>
<ReviewPrompts questions={["B의 인출 메시지가 CONFIRMED이면 5개를 L1에서 이미 받은 것인가요? (답: 4·8절)", "Stock Token의 raw balance 10이 왜 기초 주식 10주의 직접 소유권과 같지 않나요? (답: 9절)"]} />
</section>
</article><CodeSidebar codeRefKey={sidebar.codeRefKey} codeRef={sidebar.codeRef} onClose={sidebar.close} onNavigate={sidebar.navigate} codeRefs={codeRefs} fileTrees={{}} projectMetas={{"arbitrum-sdk": {"id": "arbitrum-sdk", "label": "공식 SDK · cbb96c6", "badgeClass": "border-sky-500 text-sky-700"}}} /></>; }
